externdef __imp_?ClearLogFile@@YAKPEAX@Z:PPROC
?ClearLogFile@@YAKPEAX@Z equ <__imp_?ClearLogFile@@YAKPEAX@Z>

externdef __imp_?FindAccelerometerDevice@@YAEPEAPEAX@Z:PPROC
?FindAccelerometerDevice@@YAEPEAPEAX@Z equ <__imp_?FindAccelerometerDevice@@YAEPEAPEAX@Z>

externdef __imp_?GetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z:PPROC
?GetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z equ <__imp_?GetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z>

externdef __imp_?GetRealTimeXYZ@@YAKPEAXPEAGPEAU_OVERLAPPED@@@Z:PPROC
?GetRealTimeXYZ@@YAKPEAXPEAGPEAU_OVERLAPPED@@@Z equ <__imp_?GetRealTimeXYZ@@YAKPEAXPEAGPEAU_OVERLAPPED@@@Z>

externdef __imp_?IsSoftwareEnabled@@YAKPEAXPEAE@Z:PPROC
?IsSoftwareEnabled@@YAKPEAXPEAE@Z equ <__imp_?IsSoftwareEnabled@@YAKPEAXPEAE@Z>

externdef __imp_?NotifyAccelerometerAboutPower@@YAKPEAXK@Z:PPROC
?NotifyAccelerometerAboutPower@@YAKPEAXK@Z equ <__imp_?NotifyAccelerometerAboutPower@@YAKPEAXK@Z>

externdef __imp_?RegisterForAccelerometerDisabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PPROC
?RegisterForAccelerometerDisabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z equ <__imp_?RegisterForAccelerometerDisabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z>

externdef __imp_?RegisterForAccelerometerDiskCountChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PPROC
?RegisterForAccelerometerDiskCountChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z equ <__imp_?RegisterForAccelerometerDiskCountChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z>

externdef __imp_?RegisterForAccelerometerEnabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PPROC
?RegisterForAccelerometerEnabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z equ <__imp_?RegisterForAccelerometerEnabledEvent@@YAPEAXPEAUHWND__@@PEAX@Z>

externdef __imp_?RegisterForAccelerometerParameterChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PPROC
?RegisterForAccelerometerParameterChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z equ <__imp_?RegisterForAccelerometerParameterChangeEvent@@YAPEAXPEAUHWND__@@PEAX@Z>

externdef __imp_?RegisterForAccelerometerShockEndEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PPROC
?RegisterForAccelerometerShockEndEvent@@YAPEAXPEAUHWND__@@PEAX@Z equ <__imp_?RegisterForAccelerometerShockEndEvent@@YAPEAXPEAUHWND__@@PEAX@Z>

externdef __imp_?RegisterForAccelerometerShockSignaledEvent@@YAPEAXPEAUHWND__@@PEAX@Z:PPROC
?RegisterForAccelerometerShockSignaledEvent@@YAPEAXPEAUHWND__@@PEAX@Z equ <__imp_?RegisterForAccelerometerShockSignaledEvent@@YAPEAXPEAUHWND__@@PEAX@Z>

externdef __imp_?SetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z:PPROC
?SetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z equ <__imp_?SetAccelerometerProperty@@YAKPEAXW4_ACCELEROMETER_PROPERTY_FLAGS@@0@Z>
