externdef __imp_??0CDecryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PPROC
??0CDecryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z equ <__imp_??0CDecryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>

externdef __imp_??0CEncryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PPROC
??0CEncryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z equ <__imp_??0CEncryptedData@@QEAA@KAEBV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>

externdef __imp_??1CDecryptedData@@QEAA@XZ:PPROC
??1CDecryptedData@@QEAA@XZ equ <__imp_??1CDecryptedData@@QEAA@XZ>

externdef __imp_??1CEncryptedData@@QEAA@XZ:PPROC
??1CEncryptedData@@QEAA@XZ equ <__imp_??1CEncryptedData@@QEAA@XZ>

externdef __imp_?Decrypt@CEncryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PPROC
?Decrypt@CEncryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z equ <__imp_?Decrypt@CEncryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>

externdef __imp_?Encrypt@CDecryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z:PPROC
?Encrypt@CDecryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z equ <__imp_?Encrypt@CDecryptedData@@QEAAHAEAV?$basic_string@EU?$char_traits@E@std@@V?$allocator@E@2@@std@@@Z>

externdef __imp_ACCAPENCDecryptFile:PPROC
ACCAPENCDecryptFile equ <__imp_ACCAPENCDecryptFile>

externdef __imp_ACCAPENCEncryptFile:PPROC
ACCAPENCEncryptFile equ <__imp_ACCAPENCEncryptFile>

externdef __imp_PKCS5_PBES2_SHA256_AES256CBC_Decrypt:PPROC
PKCS5_PBES2_SHA256_AES256CBC_Decrypt equ <__imp_PKCS5_PBES2_SHA256_AES256CBC_Decrypt>

externdef __imp_PKCS5_PBES2_SHA256_AES256CBC_Encrypt:PPROC
PKCS5_PBES2_SHA256_AES256CBC_Encrypt equ <__imp_PKCS5_PBES2_SHA256_AES256CBC_Encrypt>

externdef __imp_PKCS5_PBKDF2_HMAC_SHA256:PPROC
PKCS5_PBKDF2_HMAC_SHA256 equ <__imp_PKCS5_PBKDF2_HMAC_SHA256>

externdef __imp_acGetEKUFromCertificate:PPROC
acGetEKUFromCertificate equ <__imp_acGetEKUFromCertificate>

externdef __imp_acGetMaximumEncryptedSize:PPROC
acGetMaximumEncryptedSize equ <__imp_acGetMaximumEncryptedSize>

externdef __imp_acIsCertOKForPKILogon:PPROC
acIsCertOKForPKILogon equ <__imp_acIsCertOKForPKILogon>

externdef __imp_acProfileAddRuntimeParameter:PPROC
acProfileAddRuntimeParameter equ <__imp_acProfileAddRuntimeParameter>

externdef __imp_acProfileCheckSignature:PPROC
acProfileCheckSignature equ <__imp_acProfileCheckSignature>

externdef __imp_acProfileClose:PPROC
acProfileClose equ <__imp_acProfileClose>

externdef __imp_acProfileExportFromHandle:PPROC
acProfileExportFromHandle equ <__imp_acProfileExportFromHandle>

externdef __imp_acProfileFreeString:PPROC
acProfileFreeString equ <__imp_acProfileFreeString>

externdef __imp_acProfileGetAttribute:PPROC
acProfileGetAttribute equ <__imp_acProfileGetAttribute>

externdef __imp_acProfileGetAttributeValue:PPROC
acProfileGetAttributeValue equ <__imp_acProfileGetAttributeValue>

externdef __imp_acProfileIsSectionExists:PPROC
acProfileIsSectionExists equ <__imp_acProfileIsSectionExists>

externdef __imp_acProfileLoadFile:PPROC
acProfileLoadFile equ <__imp_acProfileLoadFile>

externdef __imp_acProfileOpen:PPROC
acProfileOpen equ <__imp_acProfileOpen>
