externdef __imp_??0ACDelegateSubscriber@@QEAA@AEBV0@@Z:PPROC
??0ACDelegateSubscriber@@QEAA@AEBV0@@Z equ <__imp_??0ACDelegateSubscriber@@QEAA@AEBV0@@Z>

externdef __imp_??0ACDelegateSubscriber@@QEAA@XZ:PPROC
??0ACDelegateSubscriber@@QEAA@XZ equ <__imp_??0ACDelegateSubscriber@@QEAA@XZ>

externdef __imp_??1ACDelegateSubscriber@@UEAA@XZ:PPROC
??1ACDelegateSubscriber@@UEAA@XZ equ <__imp_??1ACDelegateSubscriber@@UEAA@XZ>

externdef __imp_??4ACDelegateSubscriber@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ACDelegateSubscriber@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ACDelegateSubscriber@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_7ACDelegateSubscriber@@6B@:PPROC
??_7ACDelegateSubscriber@@6B@ equ <__imp_??_7ACDelegateSubscriber@@6B@>

externdef __imp_?GetEvent@ACDelegateSubscriber@@QEAAHXZ:PPROC
?GetEvent@ACDelegateSubscriber@@QEAAHXZ equ <__imp_?GetEvent@ACDelegateSubscriber@@QEAAHXZ>

externdef __imp_?GetEventHandle@ACDelegateSubscriber@@QEAAPEAXXZ:PPROC
?GetEventHandle@ACDelegateSubscriber@@QEAAPEAXXZ equ <__imp_?GetEventHandle@ACDelegateSubscriber@@QEAAPEAXXZ>

externdef __imp_?GetEventTable@ACDelegateSubscriber@@QEAAPEAPEAXXZ:PPROC
?GetEventTable@ACDelegateSubscriber@@QEAAPEAPEAXXZ equ <__imp_?GetEventTable@ACDelegateSubscriber@@QEAAPEAPEAXXZ>

externdef __imp_?Subscribe@ACDelegateSubscriber@@IEAAHH@Z:PPROC
?Subscribe@ACDelegateSubscriber@@IEAAHH@Z equ <__imp_?Subscribe@ACDelegateSubscriber@@IEAAHH@Z>

externdef __imp_?UnSubscribe@ACDelegateSubscriber@@IEAAHXZ:PPROC
?UnSubscribe@ACDelegateSubscriber@@IEAAHXZ equ <__imp_?UnSubscribe@ACDelegateSubscriber@@IEAAHXZ>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
