externdef __imp_aclogClose:PPROC
aclogClose equ <__imp_aclogClose>

externdef __imp_aclogLog:PPROC
aclogLog equ <__imp_aclogLog>

externdef __imp_aclogLogBin:PPROC
aclogLogBin equ <__imp_aclogLogBin>

externdef __imp_aclogSetDate:PPROC
aclogSetDate equ <__imp_aclogSetDate>

externdef __imp_aclogSetFile:PPROC
aclogSetFile equ <__imp_aclogSetFile>

externdef __imp_aclogSetModuleName:PPROC
aclogSetModuleName equ <__imp_aclogSetModuleName>

externdef __imp_aclogSetOutput:PPROC
aclogSetOutput equ <__imp_aclogSetOutput>

externdef __imp_aclogTrace:PPROC
aclogTrace equ <__imp_aclogTrace>

externdef __imp_aclogTraceBin:PPROC
aclogTraceBin equ <__imp_aclogTraceBin>
