externdef __imp_CreateSecurityPage:PPROC
CreateSecurityPage equ <__imp_CreateSecurityPage>

externdef __imp_EditSecurity:PPROC
EditSecurity equ <__imp_EditSecurity>

externdef __imp_IID_ISecurityInformation:PPROC
IID_ISecurityInformation equ <__imp_IID_ISecurityInformation>

externdef __imp_aclui_ordinal10:PPROC
aclui_ordinal10 equ <__imp_aclui_ordinal10>

externdef __imp_aclui_ordinal11:PPROC
aclui_ordinal11 equ <__imp_aclui_ordinal11>

externdef __imp_aclui_ordinal12:PPROC
aclui_ordinal12 equ <__imp_aclui_ordinal12>

externdef __imp_aclui_ordinal13:PPROC
aclui_ordinal13 equ <__imp_aclui_ordinal13>

externdef __imp_aclui_ordinal14:PPROC
aclui_ordinal14 equ <__imp_aclui_ordinal14>

externdef __imp_aclui_ordinal15:PPROC
aclui_ordinal15 equ <__imp_aclui_ordinal15>

externdef __imp_aclui_ordinal3:PPROC
aclui_ordinal3 equ <__imp_aclui_ordinal3>

externdef __imp_aclui_ordinal4:PPROC
aclui_ordinal4 equ <__imp_aclui_ordinal4>

externdef __imp_aclui_ordinal5:PPROC
aclui_ordinal5 equ <__imp_aclui_ordinal5>

externdef __imp_aclui_ordinal6:PPROC
aclui_ordinal6 equ <__imp_aclui_ordinal6>

externdef __imp_aclui_ordinal7:PPROC
aclui_ordinal7 equ <__imp_aclui_ordinal7>

externdef __imp_aclui_ordinal8:PPROC
aclui_ordinal8 equ <__imp_aclui_ordinal8>

externdef __imp_aclui_ordinal9:PPROC
aclui_ordinal9 equ <__imp_aclui_ordinal9>
