externdef __imp_??0Card@@QEAA@AEBV0@@Z:PPROC
??0Card@@QEAA@AEBV0@@Z equ <__imp_??0Card@@QEAA@AEBV0@@Z>

externdef __imp_??0Card@@QEAA@PEAVSmartCardConnection@@@Z:PPROC
??0Card@@QEAA@PEAVSmartCardConnection@@@Z equ <__imp_??0Card@@QEAA@PEAVSmartCardConnection@@@Z>

externdef __imp_??0Card@@QEAA@XZ:PPROC
??0Card@@QEAA@XZ equ <__imp_??0Card@@QEAA@XZ>

externdef __imp_??0CardAccessor@@QEAA@AEBV0@@Z:PPROC
??0CardAccessor@@QEAA@AEBV0@@Z equ <__imp_??0CardAccessor@@QEAA@AEBV0@@Z>

externdef __imp_??0CardAccessor@@QEAA@XZ:PPROC
??0CardAccessor@@QEAA@XZ equ <__imp_??0CardAccessor@@QEAA@XZ>

externdef __imp_??0CardCriteria@@QEAA@AEBV0@@Z:PPROC
??0CardCriteria@@QEAA@AEBV0@@Z equ <__imp_??0CardCriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0CardCriteria@@QEAA@XZ:PPROC
??0CardCriteria@@QEAA@XZ equ <__imp_??0CardCriteria@@QEAA@XZ>

externdef __imp_??0Criteria@@QEAA@AEBV0@@Z:PPROC
??0Criteria@@QEAA@AEBV0@@Z equ <__imp_??0Criteria@@QEAA@AEBV0@@Z>

externdef __imp_??0Criteria@@QEAA@XZ:PPROC
??0Criteria@@QEAA@XZ equ <__imp_??0Criteria@@QEAA@XZ>

externdef __imp_??0ObjectAccessor@@QEAA@AEBV0@@Z:PPROC
??0ObjectAccessor@@QEAA@AEBV0@@Z equ <__imp_??0ObjectAccessor@@QEAA@AEBV0@@Z>

externdef __imp_??0ObjectAccessor@@QEAA@XZ:PPROC
??0ObjectAccessor@@QEAA@XZ equ <__imp_??0ObjectAccessor@@QEAA@XZ>

externdef __imp_??0PIN@@QEAA@AEBV0@@Z:PPROC
??0PIN@@QEAA@AEBV0@@Z equ <__imp_??0PIN@@QEAA@AEBV0@@Z>

externdef __imp_??0PIN@@QEAA@PEAVSmartCardConnection@@@Z:PPROC
??0PIN@@QEAA@PEAVSmartCardConnection@@@Z equ <__imp_??0PIN@@QEAA@PEAVSmartCardConnection@@@Z>

externdef __imp_??0PIN@@QEAA@XZ:PPROC
??0PIN@@QEAA@XZ equ <__imp_??0PIN@@QEAA@XZ>

externdef __imp_??0PINAccessor@@QEAA@AEBV0@@Z:PPROC
??0PINAccessor@@QEAA@AEBV0@@Z equ <__imp_??0PINAccessor@@QEAA@AEBV0@@Z>

externdef __imp_??0PINAccessor@@QEAA@XZ:PPROC
??0PINAccessor@@QEAA@XZ equ <__imp_??0PINAccessor@@QEAA@XZ>

externdef __imp_??0PINCriteria@@QEAA@AEBV0@@Z:PPROC
??0PINCriteria@@QEAA@AEBV0@@Z equ <__imp_??0PINCriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0PINCriteria@@QEAA@XZ:PPROC
??0PINCriteria@@QEAA@XZ equ <__imp_??0PINCriteria@@QEAA@XZ>

externdef __imp_??0PINLogicalCriteria@@QEAA@AEBV0@@Z:PPROC
??0PINLogicalCriteria@@QEAA@AEBV0@@Z equ <__imp_??0PINLogicalCriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0PINLogicalCriteria@@QEAA@W4PINLogicalCriteriaType@@PEAEI@Z:PPROC
??0PINLogicalCriteria@@QEAA@W4PINLogicalCriteriaType@@PEAEI@Z equ <__imp_??0PINLogicalCriteria@@QEAA@W4PINLogicalCriteriaType@@PEAEI@Z>

externdef __imp_??0Reader@@QEAA@AEBV0@@Z:PPROC
??0Reader@@QEAA@AEBV0@@Z equ <__imp_??0Reader@@QEAA@AEBV0@@Z>

externdef __imp_??0Reader@@QEAA@PEAD@Z:PPROC
??0Reader@@QEAA@PEAD@Z equ <__imp_??0Reader@@QEAA@PEAD@Z>

externdef __imp_??0ReaderManager@@QEAA@AEBV0@@Z:PPROC
??0ReaderManager@@QEAA@AEBV0@@Z equ <__imp_??0ReaderManager@@QEAA@AEBV0@@Z>

externdef __imp_??0ReaderManager@@QEAA@XZ:PPROC
??0ReaderManager@@QEAA@XZ equ <__imp_??0ReaderManager@@QEAA@XZ>

externdef __imp_??0SDKCardServiceFactory@@QEAA@AEBV0@@Z:PPROC
??0SDKCardServiceFactory@@QEAA@AEBV0@@Z equ <__imp_??0SDKCardServiceFactory@@QEAA@AEBV0@@Z>

externdef __imp_??0SDKCardServiceFactory@@QEAA@XZ:PPROC
??0SDKCardServiceFactory@@QEAA@XZ equ <__imp_??0SDKCardServiceFactory@@QEAA@XZ>

externdef __imp_??0SKI@@QEAA@AEBV0@@Z:PPROC
??0SKI@@QEAA@AEBV0@@Z equ <__imp_??0SKI@@QEAA@AEBV0@@Z>

externdef __imp_??0SKI@@QEAA@PEAVSmartCardConnection@@@Z:PPROC
??0SKI@@QEAA@PEAVSmartCardConnection@@@Z equ <__imp_??0SKI@@QEAA@PEAVSmartCardConnection@@@Z>

externdef __imp_??0SKI@@QEAA@XZ:PPROC
??0SKI@@QEAA@XZ equ <__imp_??0SKI@@QEAA@XZ>

externdef __imp_??0SKIAccessor@@QEAA@AEBV0@@Z:PPROC
??0SKIAccessor@@QEAA@AEBV0@@Z equ <__imp_??0SKIAccessor@@QEAA@AEBV0@@Z>

externdef __imp_??0SKIAccessor@@QEAA@XZ:PPROC
??0SKIAccessor@@QEAA@XZ equ <__imp_??0SKIAccessor@@QEAA@XZ>

externdef __imp_??0SKICriteria@@QEAA@AEBV0@@Z:PPROC
??0SKICriteria@@QEAA@AEBV0@@Z equ <__imp_??0SKICriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0SKICriteria@@QEAA@XZ:PPROC
??0SKICriteria@@QEAA@XZ equ <__imp_??0SKICriteria@@QEAA@XZ>

externdef __imp_??0SKILogicalCriteria@@QEAA@AEBV0@@Z:PPROC
??0SKILogicalCriteria@@QEAA@AEBV0@@Z equ <__imp_??0SKILogicalCriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0SKILogicalCriteria@@QEAA@W4SKILogicalCriteriaType@@PEAEI@Z:PPROC
??0SKILogicalCriteria@@QEAA@W4SKILogicalCriteriaType@@PEAEI@Z equ <__imp_??0SKILogicalCriteria@@QEAA@W4SKILogicalCriteriaType@@PEAEI@Z>

externdef __imp_??0SmartCardConnection@@QEAA@AEBV0@@Z:PPROC
??0SmartCardConnection@@QEAA@AEBV0@@Z equ <__imp_??0SmartCardConnection@@QEAA@AEBV0@@Z>

externdef __imp_??0SmartCardConnection@@QEAA@XZ:PPROC
??0SmartCardConnection@@QEAA@XZ equ <__imp_??0SmartCardConnection@@QEAA@XZ>

externdef __imp_??0SmartCardConnectionManager@@QEAA@AEBV0@@Z:PPROC
??0SmartCardConnectionManager@@QEAA@AEBV0@@Z equ <__imp_??0SmartCardConnectionManager@@QEAA@AEBV0@@Z>

externdef __imp_??0SmartCardConnectionManager@@QEAA@XZ:PPROC
??0SmartCardConnectionManager@@QEAA@XZ equ <__imp_??0SmartCardConnectionManager@@QEAA@XZ>

externdef __imp_??0Static@@QEAA@AEBV0@@Z:PPROC
??0Static@@QEAA@AEBV0@@Z equ <__imp_??0Static@@QEAA@AEBV0@@Z>

externdef __imp_??0Static@@QEAA@PEAVSmartCardConnection@@@Z:PPROC
??0Static@@QEAA@PEAVSmartCardConnection@@@Z equ <__imp_??0Static@@QEAA@PEAVSmartCardConnection@@@Z>

externdef __imp_??0Static@@QEAA@XZ:PPROC
??0Static@@QEAA@XZ equ <__imp_??0Static@@QEAA@XZ>

externdef __imp_??0StaticAccessor@@QEAA@AEBV0@@Z:PPROC
??0StaticAccessor@@QEAA@AEBV0@@Z equ <__imp_??0StaticAccessor@@QEAA@AEBV0@@Z>

externdef __imp_??0StaticAccessor@@QEAA@XZ:PPROC
??0StaticAccessor@@QEAA@XZ equ <__imp_??0StaticAccessor@@QEAA@XZ>

externdef __imp_??0StaticCriteria@@QEAA@AEBV0@@Z:PPROC
??0StaticCriteria@@QEAA@AEBV0@@Z equ <__imp_??0StaticCriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0StaticCriteria@@QEAA@XZ:PPROC
??0StaticCriteria@@QEAA@XZ equ <__imp_??0StaticCriteria@@QEAA@XZ>

externdef __imp_??0StaticLogicalCriteria@@QEAA@AEBV0@@Z:PPROC
??0StaticLogicalCriteria@@QEAA@AEBV0@@Z equ <__imp_??0StaticLogicalCriteria@@QEAA@AEBV0@@Z>

externdef __imp_??0StaticLogicalCriteria@@QEAA@W4StaticLogicalCriteriaType@@PEAEI@Z:PPROC
??0StaticLogicalCriteria@@QEAA@W4StaticLogicalCriteriaType@@PEAEI@Z equ <__imp_??0StaticLogicalCriteria@@QEAA@W4StaticLogicalCriteriaType@@PEAEI@Z>

externdef __imp_??1Card@@UEAA@XZ:PPROC
??1Card@@UEAA@XZ equ <__imp_??1Card@@UEAA@XZ>

externdef __imp_??1CardAccessor@@UEAA@XZ:PPROC
??1CardAccessor@@UEAA@XZ equ <__imp_??1CardAccessor@@UEAA@XZ>

externdef __imp_??1CardCriteria@@UEAA@XZ:PPROC
??1CardCriteria@@UEAA@XZ equ <__imp_??1CardCriteria@@UEAA@XZ>

externdef __imp_??1Criteria@@UEAA@XZ:PPROC
??1Criteria@@UEAA@XZ equ <__imp_??1Criteria@@UEAA@XZ>

externdef __imp_??1ObjectAccessor@@UEAA@XZ:PPROC
??1ObjectAccessor@@UEAA@XZ equ <__imp_??1ObjectAccessor@@UEAA@XZ>

externdef __imp_??1PIN@@UEAA@XZ:PPROC
??1PIN@@UEAA@XZ equ <__imp_??1PIN@@UEAA@XZ>

externdef __imp_??1PINAccessor@@UEAA@XZ:PPROC
??1PINAccessor@@UEAA@XZ equ <__imp_??1PINAccessor@@UEAA@XZ>

externdef __imp_??1PINCriteria@@UEAA@XZ:PPROC
??1PINCriteria@@UEAA@XZ equ <__imp_??1PINCriteria@@UEAA@XZ>

externdef __imp_??1PINLogicalCriteria@@UEAA@XZ:PPROC
??1PINLogicalCriteria@@UEAA@XZ equ <__imp_??1PINLogicalCriteria@@UEAA@XZ>

externdef __imp_??1Reader@@UEAA@XZ:PPROC
??1Reader@@UEAA@XZ equ <__imp_??1Reader@@UEAA@XZ>

externdef __imp_??1ReaderManager@@UEAA@XZ:PPROC
??1ReaderManager@@UEAA@XZ equ <__imp_??1ReaderManager@@UEAA@XZ>

externdef __imp_??1SDKCardServiceFactory@@UEAA@XZ:PPROC
??1SDKCardServiceFactory@@UEAA@XZ equ <__imp_??1SDKCardServiceFactory@@UEAA@XZ>

externdef __imp_??1SKI@@UEAA@XZ:PPROC
??1SKI@@UEAA@XZ equ <__imp_??1SKI@@UEAA@XZ>

externdef __imp_??1SKIAccessor@@UEAA@XZ:PPROC
??1SKIAccessor@@UEAA@XZ equ <__imp_??1SKIAccessor@@UEAA@XZ>

externdef __imp_??1SKICriteria@@UEAA@XZ:PPROC
??1SKICriteria@@UEAA@XZ equ <__imp_??1SKICriteria@@UEAA@XZ>

externdef __imp_??1SKILogicalCriteria@@UEAA@XZ:PPROC
??1SKILogicalCriteria@@UEAA@XZ equ <__imp_??1SKILogicalCriteria@@UEAA@XZ>

externdef __imp_??1SmartCardConnection@@UEAA@XZ:PPROC
??1SmartCardConnection@@UEAA@XZ equ <__imp_??1SmartCardConnection@@UEAA@XZ>

externdef __imp_??1SmartCardConnectionManager@@UEAA@XZ:PPROC
??1SmartCardConnectionManager@@UEAA@XZ equ <__imp_??1SmartCardConnectionManager@@UEAA@XZ>

externdef __imp_??1Static@@UEAA@XZ:PPROC
??1Static@@UEAA@XZ equ <__imp_??1Static@@UEAA@XZ>

externdef __imp_??1StaticAccessor@@UEAA@XZ:PPROC
??1StaticAccessor@@UEAA@XZ equ <__imp_??1StaticAccessor@@UEAA@XZ>

externdef __imp_??1StaticCriteria@@UEAA@XZ:PPROC
??1StaticCriteria@@UEAA@XZ equ <__imp_??1StaticCriteria@@UEAA@XZ>

externdef __imp_??1StaticLogicalCriteria@@UEAA@XZ:PPROC
??1StaticLogicalCriteria@@UEAA@XZ equ <__imp_??1StaticLogicalCriteria@@UEAA@XZ>

externdef __imp_??4Card@@QEAAAEAV0@AEBV0@@Z:PPROC
??4Card@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4Card@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CardAccessor@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CardAccessor@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CardAccessor@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CardCriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CardCriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CardCriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4Criteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4Criteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4Criteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ObjectAccessor@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ObjectAccessor@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ObjectAccessor@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4PIN@@QEAAAEAV0@AEBV0@@Z:PPROC
??4PIN@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4PIN@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4PINAccessor@@QEAAAEAV0@AEBV0@@Z:PPROC
??4PINAccessor@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4PINAccessor@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4PINCriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4PINCriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4PINCriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4PINLogicalCriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4PINLogicalCriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4PINLogicalCriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4Reader@@QEAAAEAV0@AEBV0@@Z:PPROC
??4Reader@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4Reader@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ReaderManager@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ReaderManager@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ReaderManager@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SDKCardServiceFactory@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SDKCardServiceFactory@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SDKCardServiceFactory@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SKI@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SKI@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SKI@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SKIAccessor@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SKIAccessor@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SKIAccessor@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SKICriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SKICriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SKICriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SKILogicalCriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SKILogicalCriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SKILogicalCriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SmartCardConnection@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SmartCardConnection@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SmartCardConnection@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SmartCardConnectionManager@@QEAAAEAV0@AEBV0@@Z:PPROC
??4SmartCardConnectionManager@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4SmartCardConnectionManager@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4Static@@QEAAAEAV0@AEBV0@@Z:PPROC
??4Static@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4Static@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4StaticAccessor@@QEAAAEAV0@AEBV0@@Z:PPROC
??4StaticAccessor@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4StaticAccessor@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4StaticCriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4StaticCriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4StaticCriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4StaticLogicalCriteria@@QEAAAEAV0@AEBV0@@Z:PPROC
??4StaticLogicalCriteria@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4StaticLogicalCriteria@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_7Card@@6B@:PPROC
??_7Card@@6B@ equ <__imp_??_7Card@@6B@>

externdef __imp_??_7CardAccessor@@6B@:PPROC
??_7CardAccessor@@6B@ equ <__imp_??_7CardAccessor@@6B@>

externdef __imp_??_7CardCriteria@@6B@:PPROC
??_7CardCriteria@@6B@ equ <__imp_??_7CardCriteria@@6B@>

externdef __imp_??_7Criteria@@6B@:PPROC
??_7Criteria@@6B@ equ <__imp_??_7Criteria@@6B@>

externdef __imp_??_7ObjectAccessor@@6B@:PPROC
??_7ObjectAccessor@@6B@ equ <__imp_??_7ObjectAccessor@@6B@>

externdef __imp_??_7PIN@@6B@:PPROC
??_7PIN@@6B@ equ <__imp_??_7PIN@@6B@>

externdef __imp_??_7PINAccessor@@6B@:PPROC
??_7PINAccessor@@6B@ equ <__imp_??_7PINAccessor@@6B@>

externdef __imp_??_7PINCriteria@@6B@:PPROC
??_7PINCriteria@@6B@ equ <__imp_??_7PINCriteria@@6B@>

externdef __imp_??_7PINLogicalCriteria@@6B@:PPROC
??_7PINLogicalCriteria@@6B@ equ <__imp_??_7PINLogicalCriteria@@6B@>

externdef __imp_??_7Reader@@6B@:PPROC
??_7Reader@@6B@ equ <__imp_??_7Reader@@6B@>

externdef __imp_??_7ReaderManager@@6B@:PPROC
??_7ReaderManager@@6B@ equ <__imp_??_7ReaderManager@@6B@>

externdef __imp_??_7SDKCardServiceFactory@@6B@:PPROC
??_7SDKCardServiceFactory@@6B@ equ <__imp_??_7SDKCardServiceFactory@@6B@>

externdef __imp_??_7SKI@@6B@:PPROC
??_7SKI@@6B@ equ <__imp_??_7SKI@@6B@>

externdef __imp_??_7SKIAccessor@@6B@:PPROC
??_7SKIAccessor@@6B@ equ <__imp_??_7SKIAccessor@@6B@>

externdef __imp_??_7SKICriteria@@6B@:PPROC
??_7SKICriteria@@6B@ equ <__imp_??_7SKICriteria@@6B@>

externdef __imp_??_7SKILogicalCriteria@@6B@:PPROC
??_7SKILogicalCriteria@@6B@ equ <__imp_??_7SKILogicalCriteria@@6B@>

externdef __imp_??_7SmartCardConnection@@6B@:PPROC
??_7SmartCardConnection@@6B@ equ <__imp_??_7SmartCardConnection@@6B@>

externdef __imp_??_7SmartCardConnectionManager@@6B@:PPROC
??_7SmartCardConnectionManager@@6B@ equ <__imp_??_7SmartCardConnectionManager@@6B@>

externdef __imp_??_7Static@@6B@:PPROC
??_7Static@@6B@ equ <__imp_??_7Static@@6B@>

externdef __imp_??_7StaticAccessor@@6B@:PPROC
??_7StaticAccessor@@6B@ equ <__imp_??_7StaticAccessor@@6B@>

externdef __imp_??_7StaticCriteria@@6B@:PPROC
??_7StaticCriteria@@6B@ equ <__imp_??_7StaticCriteria@@6B@>

externdef __imp_??_7StaticLogicalCriteria@@6B@:PPROC
??_7StaticLogicalCriteria@@6B@ equ <__imp_??_7StaticLogicalCriteria@@6B@>

externdef __imp_?CreateCardCriteria@@YAPEAVCardCriteria@@XZ:PPROC
?CreateCardCriteria@@YAPEAVCardCriteria@@XZ equ <__imp_?CreateCardCriteria@@YAPEAVCardCriteria@@XZ>

externdef __imp_?CreatePINLogicalCriteria@@YAPEAVPINLogicalCriteria@@W4PINLogicalCriteriaType@@PEAEI@Z:PPROC
?CreatePINLogicalCriteria@@YAPEAVPINLogicalCriteria@@W4PINLogicalCriteriaType@@PEAEI@Z equ <__imp_?CreatePINLogicalCriteria@@YAPEAVPINLogicalCriteria@@W4PINLogicalCriteriaType@@PEAEI@Z>

externdef __imp_?CreateSDKCardServiceFactory@@YAPEAVSDKCardServiceFactory@@XZ:PPROC
?CreateSDKCardServiceFactory@@YAPEAVSDKCardServiceFactory@@XZ equ <__imp_?CreateSDKCardServiceFactory@@YAPEAVSDKCardServiceFactory@@XZ>

externdef __imp_?CreateSKILogicalCriteria@@YAPEAVSKILogicalCriteria@@W4SKILogicalCriteriaType@@PEAEI@Z:PPROC
?CreateSKILogicalCriteria@@YAPEAVSKILogicalCriteria@@W4SKILogicalCriteriaType@@PEAEI@Z equ <__imp_?CreateSKILogicalCriteria@@YAPEAVSKILogicalCriteria@@W4SKILogicalCriteriaType@@PEAEI@Z>

externdef __imp_?CreateStaticLogicalCriteria@@YAPEAVStaticLogicalCriteria@@W4StaticLogicalCriteriaType@@PEAEI@Z:PPROC
?CreateStaticLogicalCriteria@@YAPEAVStaticLogicalCriteria@@W4StaticLogicalCriteriaType@@PEAEI@Z equ <__imp_?CreateStaticLogicalCriteria@@YAPEAVStaticLogicalCriteria@@W4StaticLogicalCriteriaType@@PEAEI@Z>

externdef __imp_?GetCriteriaType@PINLogicalCriteria@@QEAA?AW4PINLogicalCriteriaType@@XZ:PPROC
?GetCriteriaType@PINLogicalCriteria@@QEAA?AW4PINLogicalCriteriaType@@XZ equ <__imp_?GetCriteriaType@PINLogicalCriteria@@QEAA?AW4PINLogicalCriteriaType@@XZ>

externdef __imp_?GetCriteriaType@SKILogicalCriteria@@QEAA?AW4SKILogicalCriteriaType@@XZ:PPROC
?GetCriteriaType@SKILogicalCriteria@@QEAA?AW4SKILogicalCriteriaType@@XZ equ <__imp_?GetCriteriaType@SKILogicalCriteria@@QEAA?AW4SKILogicalCriteriaType@@XZ>

externdef __imp_?GetCriteriaType@StaticLogicalCriteria@@QEAA?AW4StaticLogicalCriteriaType@@XZ:PPROC
?GetCriteriaType@StaticLogicalCriteria@@QEAA?AW4StaticLogicalCriteriaType@@XZ equ <__imp_?GetCriteriaType@StaticLogicalCriteria@@QEAA?AW4StaticLogicalCriteriaType@@XZ>

externdef __imp_?GetCriteriaValue@PINLogicalCriteria@@QEAAPEAEXZ:PPROC
?GetCriteriaValue@PINLogicalCriteria@@QEAAPEAEXZ equ <__imp_?GetCriteriaValue@PINLogicalCriteria@@QEAAPEAEXZ>

externdef __imp_?GetCriteriaValue@SKILogicalCriteria@@QEAAPEAEXZ:PPROC
?GetCriteriaValue@SKILogicalCriteria@@QEAAPEAEXZ equ <__imp_?GetCriteriaValue@SKILogicalCriteria@@QEAAPEAEXZ>

externdef __imp_?GetCriteriaValue@StaticLogicalCriteria@@QEAAPEAEXZ:PPROC
?GetCriteriaValue@StaticLogicalCriteria@@QEAAPEAEXZ equ <__imp_?GetCriteriaValue@StaticLogicalCriteria@@QEAAPEAEXZ>

externdef __imp_?GetCriteriaValueLen@PINLogicalCriteria@@QEAAIXZ:PPROC
?GetCriteriaValueLen@PINLogicalCriteria@@QEAAIXZ equ <__imp_?GetCriteriaValueLen@PINLogicalCriteria@@QEAAIXZ>

externdef __imp_?GetCriteriaValueLen@SKILogicalCriteria@@QEAAIXZ:PPROC
?GetCriteriaValueLen@SKILogicalCriteria@@QEAAIXZ equ <__imp_?GetCriteriaValueLen@SKILogicalCriteria@@QEAAIXZ>

externdef __imp_?GetCriteriaValueLen@StaticLogicalCriteria@@QEAAIXZ:PPROC
?GetCriteriaValueLen@StaticLogicalCriteria@@QEAAIXZ equ <__imp_?GetCriteriaValueLen@StaticLogicalCriteria@@QEAAIXZ>

externdef __imp_?GetName@CardCriteria@@UEAAPEADXZ:PPROC
?GetName@CardCriteria@@UEAAPEADXZ equ <__imp_?GetName@CardCriteria@@UEAAPEADXZ>

externdef __imp_?GetName@PINLogicalCriteria@@UEAAPEADXZ:PPROC
?GetName@PINLogicalCriteria@@UEAAPEADXZ equ <__imp_?GetName@PINLogicalCriteria@@UEAAPEADXZ>

externdef __imp_?GetName@SKILogicalCriteria@@UEAAPEADXZ:PPROC
?GetName@SKILogicalCriteria@@UEAAPEADXZ equ <__imp_?GetName@SKILogicalCriteria@@UEAAPEADXZ>

externdef __imp_?GetName@StaticLogicalCriteria@@UEAAPEADXZ:PPROC
?GetName@StaticLogicalCriteria@@UEAAPEADXZ equ <__imp_?GetName@StaticLogicalCriteria@@UEAAPEADXZ>

externdef __imp_?GetReaderName@Reader@@UEAAPEADXZ:PPROC
?GetReaderName@Reader@@UEAAPEADXZ equ <__imp_?GetReaderName@Reader@@UEAAPEADXZ>

externdef __imp_CreateCardCriteria:PPROC
CreateCardCriteria equ <__imp_CreateCardCriteria>

externdef __imp_CreatePINLogicalCriteria:PPROC
CreatePINLogicalCriteria equ <__imp_CreatePINLogicalCriteria>

externdef __imp_CreateSDKCardServiceFactory:PPROC
CreateSDKCardServiceFactory equ <__imp_CreateSDKCardServiceFactory>

externdef __imp_CreateSKILogicalCriteria:PPROC
CreateSKILogicalCriteria equ <__imp_CreateSKILogicalCriteria>

externdef __imp_CreateStaticLogicalCriteria:PPROC
CreateStaticLogicalCriteria equ <__imp_CreateStaticLogicalCriteria>
