externdef __imp_pivConnect:PPROC
pivConnect equ <__imp_pivConnect>

externdef __imp_pivCrypt:PPROC
pivCrypt equ <__imp_pivCrypt>

externdef __imp_pivDisconnect:PPROC
pivDisconnect equ <__imp_pivDisconnect>

externdef __imp_pivGenerateKeyPair:PPROC
pivGenerateKeyPair equ <__imp_pivGenerateKeyPair>

externdef __imp_pivGetData:PPROC
pivGetData equ <__imp_pivGetData>

externdef __imp_pivLogIntoCardApplication:PPROC
pivLogIntoCardApplication equ <__imp_pivLogIntoCardApplication>

externdef __imp_pivLogoutOfCardApplication:PPROC
pivLogoutOfCardApplication equ <__imp_pivLogoutOfCardApplication>

externdef __imp_pivPutData:PPROC
pivPutData equ <__imp_pivPutData>

externdef __imp_pivSelectCardApplication:PPROC
pivSelectCardApplication equ <__imp_pivSelectCardApplication>
