externdef __imp_C_CancelFunction:PPROC
C_CancelFunction equ <__imp_C_CancelFunction>

externdef __imp_C_CetCUID:PPROC
C_CetCUID equ <__imp_C_CetCUID>

externdef __imp_C_CloseAllSessions:PPROC
C_CloseAllSessions equ <__imp_C_CloseAllSessions>

externdef __imp_C_CloseSession:PPROC
C_CloseSession equ <__imp_C_CloseSession>

externdef __imp_C_CopyObject:PPROC
C_CopyObject equ <__imp_C_CopyObject>

externdef __imp_C_CreateObject:PPROC
C_CreateObject equ <__imp_C_CreateObject>

externdef __imp_C_Decrypt:PPROC
C_Decrypt equ <__imp_C_Decrypt>

externdef __imp_C_DecryptDigestUpdate:PPROC
C_DecryptDigestUpdate equ <__imp_C_DecryptDigestUpdate>

externdef __imp_C_DecryptFinal:PPROC
C_DecryptFinal equ <__imp_C_DecryptFinal>

externdef __imp_C_DecryptInit:PPROC
C_DecryptInit equ <__imp_C_DecryptInit>

externdef __imp_C_DecryptUpdate:PPROC
C_DecryptUpdate equ <__imp_C_DecryptUpdate>

externdef __imp_C_DecryptVerifyUpdate:PPROC
C_DecryptVerifyUpdate equ <__imp_C_DecryptVerifyUpdate>

externdef __imp_C_DeriveKey:PPROC
C_DeriveKey equ <__imp_C_DeriveKey>

externdef __imp_C_DestroyObject:PPROC
C_DestroyObject equ <__imp_C_DestroyObject>

externdef __imp_C_Digest:PPROC
C_Digest equ <__imp_C_Digest>

externdef __imp_C_DigestEncryptUpdate:PPROC
C_DigestEncryptUpdate equ <__imp_C_DigestEncryptUpdate>

externdef __imp_C_DigestFinal:PPROC
C_DigestFinal equ <__imp_C_DigestFinal>

externdef __imp_C_DigestInit:PPROC
C_DigestInit equ <__imp_C_DigestInit>

externdef __imp_C_DigestKey:PPROC
C_DigestKey equ <__imp_C_DigestKey>

externdef __imp_C_DigestUpdate:PPROC
C_DigestUpdate equ <__imp_C_DigestUpdate>

externdef __imp_C_Encrypt:PPROC
C_Encrypt equ <__imp_C_Encrypt>

externdef __imp_C_EncryptFinal:PPROC
C_EncryptFinal equ <__imp_C_EncryptFinal>

externdef __imp_C_EncryptInit:PPROC
C_EncryptInit equ <__imp_C_EncryptInit>

externdef __imp_C_EncryptUpdate:PPROC
C_EncryptUpdate equ <__imp_C_EncryptUpdate>

externdef __imp_C_Finalize:PPROC
C_Finalize equ <__imp_C_Finalize>

externdef __imp_C_FindObjects:PPROC
C_FindObjects equ <__imp_C_FindObjects>

externdef __imp_C_FindObjectsFinal:PPROC
C_FindObjectsFinal equ <__imp_C_FindObjectsFinal>

externdef __imp_C_FindObjectsInit:PPROC
C_FindObjectsInit equ <__imp_C_FindObjectsInit>

externdef __imp_C_GenerateKey:PPROC
C_GenerateKey equ <__imp_C_GenerateKey>

externdef __imp_C_GenerateKeyPair:PPROC
C_GenerateKeyPair equ <__imp_C_GenerateKeyPair>

externdef __imp_C_GenerateRandom:PPROC
C_GenerateRandom equ <__imp_C_GenerateRandom>

externdef __imp_C_GetAttributeValue:PPROC
C_GetAttributeValue equ <__imp_C_GetAttributeValue>

externdef __imp_C_GetFunctionList:PPROC
C_GetFunctionList equ <__imp_C_GetFunctionList>

externdef __imp_C_GetFunctionStatus:PPROC
C_GetFunctionStatus equ <__imp_C_GetFunctionStatus>

externdef __imp_C_GetInfo:PPROC
C_GetInfo equ <__imp_C_GetInfo>

externdef __imp_C_GetMechanismInfo:PPROC
C_GetMechanismInfo equ <__imp_C_GetMechanismInfo>

externdef __imp_C_GetMechanismList:PPROC
C_GetMechanismList equ <__imp_C_GetMechanismList>

externdef __imp_C_GetObjectSize:PPROC
C_GetObjectSize equ <__imp_C_GetObjectSize>

externdef __imp_C_GetOperationState:PPROC
C_GetOperationState equ <__imp_C_GetOperationState>

externdef __imp_C_GetPINInfo:PPROC
C_GetPINInfo equ <__imp_C_GetPINInfo>

externdef __imp_C_GetSessionInfo:PPROC
C_GetSessionInfo equ <__imp_C_GetSessionInfo>

externdef __imp_C_GetSlotInfo:PPROC
C_GetSlotInfo equ <__imp_C_GetSlotInfo>

externdef __imp_C_GetSlotList:PPROC
C_GetSlotList equ <__imp_C_GetSlotList>

externdef __imp_C_GetTokenInfo:PPROC
C_GetTokenInfo equ <__imp_C_GetTokenInfo>

externdef __imp_C_InitPIN:PPROC
C_InitPIN equ <__imp_C_InitPIN>

externdef __imp_C_InitToken:PPROC
C_InitToken equ <__imp_C_InitToken>

externdef __imp_C_Initialize:PPROC
C_Initialize equ <__imp_C_Initialize>

externdef __imp_C_Login:PPROC
C_Login equ <__imp_C_Login>

externdef __imp_C_Logout:PPROC
C_Logout equ <__imp_C_Logout>

externdef __imp_C_OpenSession:PPROC
C_OpenSession equ <__imp_C_OpenSession>

externdef __imp_C_ResetToken:PPROC
C_ResetToken equ <__imp_C_ResetToken>

externdef __imp_C_SeedRandom:PPROC
C_SeedRandom equ <__imp_C_SeedRandom>

externdef __imp_C_SetAttributeValue:PPROC
C_SetAttributeValue equ <__imp_C_SetAttributeValue>

externdef __imp_C_SetOperationState:PPROC
C_SetOperationState equ <__imp_C_SetOperationState>

externdef __imp_C_SetPIN:PPROC
C_SetPIN equ <__imp_C_SetPIN>

externdef __imp_C_Sign:PPROC
C_Sign equ <__imp_C_Sign>

externdef __imp_C_SignEncryptUpdate:PPROC
C_SignEncryptUpdate equ <__imp_C_SignEncryptUpdate>

externdef __imp_C_SignFinal:PPROC
C_SignFinal equ <__imp_C_SignFinal>

externdef __imp_C_SignInit:PPROC
C_SignInit equ <__imp_C_SignInit>

externdef __imp_C_SignRecover:PPROC
C_SignRecover equ <__imp_C_SignRecover>

externdef __imp_C_SignRecoverInit:PPROC
C_SignRecoverInit equ <__imp_C_SignRecoverInit>

externdef __imp_C_SignUpdate:PPROC
C_SignUpdate equ <__imp_C_SignUpdate>

externdef __imp_C_UnlockPIN:PPROC
C_UnlockPIN equ <__imp_C_UnlockPIN>

externdef __imp_C_UnwrapKey:PPROC
C_UnwrapKey equ <__imp_C_UnwrapKey>

externdef __imp_C_Verify:PPROC
C_Verify equ <__imp_C_Verify>

externdef __imp_C_VerifyFinal:PPROC
C_VerifyFinal equ <__imp_C_VerifyFinal>

externdef __imp_C_VerifyInit:PPROC
C_VerifyInit equ <__imp_C_VerifyInit>

externdef __imp_C_VerifyRecover:PPROC
C_VerifyRecover equ <__imp_C_VerifyRecover>

externdef __imp_C_VerifyRecoverInit:PPROC
C_VerifyRecoverInit equ <__imp_C_VerifyRecoverInit>

externdef __imp_C_VerifyUpdate:PPROC
C_VerifyUpdate equ <__imp_C_VerifyUpdate>

externdef __imp_C_WaitForSlotEvent:PPROC
C_WaitForSlotEvent equ <__imp_C_WaitForSlotEvent>

externdef __imp_C_WrapKey:PPROC
C_WrapKey equ <__imp_C_WrapKey>
