externdef __imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV12@1@Z:PPROC
?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV12@1@Z equ <__imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAV12@1@Z>

externdef __imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAV12@1@Z:PPROC
?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAV12@1@Z equ <__imp_?aiNetConvertUserIdToNETBIOS@@YAHAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAV12@1@Z>

externdef __imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z:PPROC
?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z equ <__imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z>

externdef __imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0@Z:PPROC
?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0@Z equ <__imp_?aiNetGetCurrentUserAndDomain@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0@Z>

externdef __imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PPROC
?aiSysGetFixedDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z equ <__imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>

externdef __imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z:PPROC
?aiSysGetFixedDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z equ <__imp_?aiSysGetFixedDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z>

externdef __imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PPROC
?aiSysGetSystemDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z equ <__imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>

externdef __imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z:PPROC
?aiSysGetSystemDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z equ <__imp_?aiSysGetSystemDrive@@YAHAEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@@Z>

externdef __imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAPEAX@Z:PPROC
?aiSysGetUserSID@@YAKAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAPEAX@Z equ <__imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0AEAPEAX@Z>

externdef __imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAPEAX@Z:PPROC
?aiSysGetUserSID@@YAKAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAPEAX@Z equ <__imp_?aiSysGetUserSID@@YAKAEBV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@std@@0AEAPEAX@Z>

externdef __imp_DetectTSE:PPROC
DetectTSE equ <__imp_DetectTSE>

externdef __imp_IsTerminalServicesEnabled:PPROC
IsTerminalServicesEnabled equ <__imp_IsTerminalServicesEnabled>

externdef __imp_MSICleanMergedFolders:PPROC
MSICleanMergedFolders equ <__imp_MSICleanMergedFolders>

externdef __imp_MSIDeleteResourceFiles:PPROC
MSIDeleteResourceFiles equ <__imp_MSIDeleteResourceFiles>

externdef __imp_aiNetConvertUserIdToNETBIOSA:PPROC
aiNetConvertUserIdToNETBIOSA equ <__imp_aiNetConvertUserIdToNETBIOSA>
  IFNDEF __UNICODE__
    aiNetConvertUserIdToNETBIOS equ <__imp_aiNetConvertUserIdToNETBIOSA>
  ENDIF

externdef __imp_aiNetConvertUserIdToNETBIOSW:PPROC
aiNetConvertUserIdToNETBIOSW equ <__imp_aiNetConvertUserIdToNETBIOSW>
  IFDEF __UNICODE__
    aiNetConvertUserIdToNETBIOS equ <__imp_aiNetConvertUserIdToNETBIOSW>
  ENDIF

externdef __imp_aiNetGetCurrentUserAndDomainA:PPROC
aiNetGetCurrentUserAndDomainA equ <__imp_aiNetGetCurrentUserAndDomainA>
  IFNDEF __UNICODE__
    aiNetGetCurrentUserAndDomain equ <__imp_aiNetGetCurrentUserAndDomainA>
  ENDIF

externdef __imp_aiNetGetCurrentUserAndDomainW:PPROC
aiNetGetCurrentUserAndDomainW equ <__imp_aiNetGetCurrentUserAndDomainW>
  IFDEF __UNICODE__
    aiNetGetCurrentUserAndDomain equ <__imp_aiNetGetCurrentUserAndDomainW>
  ENDIF

externdef __imp_aiNetGetNETBIOSDomainNameFromUPNA:PPROC
aiNetGetNETBIOSDomainNameFromUPNA equ <__imp_aiNetGetNETBIOSDomainNameFromUPNA>
  IFNDEF __UNICODE__
    aiNetGetNETBIOSDomainNameFromUPN equ <__imp_aiNetGetNETBIOSDomainNameFromUPNA>
  ENDIF

externdef __imp_aiNetGetNETBIOSDomainNameFromUPNW:PPROC
aiNetGetNETBIOSDomainNameFromUPNW equ <__imp_aiNetGetNETBIOSDomainNameFromUPNW>
  IFDEF __UNICODE__
    aiNetGetNETBIOSDomainNameFromUPN equ <__imp_aiNetGetNETBIOSDomainNameFromUPNW>
  ENDIF

externdef __imp_aiNetGetUserNameDomainFromUPNA:PPROC
aiNetGetUserNameDomainFromUPNA equ <__imp_aiNetGetUserNameDomainFromUPNA>
  IFNDEF __UNICODE__
    aiNetGetUserNameDomainFromUPN equ <__imp_aiNetGetUserNameDomainFromUPNA>
  ENDIF

externdef __imp_aiNetGetUserNameDomainFromUPNW:PPROC
aiNetGetUserNameDomainFromUPNW equ <__imp_aiNetGetUserNameDomainFromUPNW>
  IFDEF __UNICODE__
    aiNetGetUserNameDomainFromUPN equ <__imp_aiNetGetUserNameDomainFromUPNW>
  ENDIF

externdef __imp_aiRegReadBinaryValue:PPROC
aiRegReadBinaryValue equ <__imp_aiRegReadBinaryValue>

externdef __imp_aiRegReadDWORDValue:PPROC
aiRegReadDWORDValue equ <__imp_aiRegReadDWORDValue>

externdef __imp_aiRegReadMultiStringValue:PPROC
aiRegReadMultiStringValue equ <__imp_aiRegReadMultiStringValue>

externdef __imp_aiRegReadStringValue:PPROC
aiRegReadStringValue equ <__imp_aiRegReadStringValue>

externdef __imp_aiRegReadValue:PPROC
aiRegReadValue equ <__imp_aiRegReadValue>

externdef __imp_aiRegWriteBinaryValue:PPROC
aiRegWriteBinaryValue equ <__imp_aiRegWriteBinaryValue>

externdef __imp_aiRegWriteDWORDValue:PPROC
aiRegWriteDWORDValue equ <__imp_aiRegWriteDWORDValue>

externdef __imp_aiRegWriteMultiStringValue:PPROC
aiRegWriteMultiStringValue equ <__imp_aiRegWriteMultiStringValue>

externdef __imp_aiRegWriteStringValue:PPROC
aiRegWriteStringValue equ <__imp_aiRegWriteStringValue>

externdef __imp_aiSysConvertSIDA:PPROC
aiSysConvertSIDA equ <__imp_aiSysConvertSIDA>
  IFNDEF __UNICODE__
    aiSysConvertSID equ <__imp_aiSysConvertSIDA>
  ENDIF

externdef __imp_aiSysConvertSIDW:PPROC
aiSysConvertSIDW equ <__imp_aiSysConvertSIDW>
  IFDEF __UNICODE__
    aiSysConvertSID equ <__imp_aiSysConvertSIDW>
  ENDIF

externdef __imp_aiSysGetFixedDriveA:PPROC
aiSysGetFixedDriveA equ <__imp_aiSysGetFixedDriveA>
  IFNDEF __UNICODE__
    aiSysGetFixedDrive equ <__imp_aiSysGetFixedDriveA>
  ENDIF

externdef __imp_aiSysGetFixedDriveW:PPROC
aiSysGetFixedDriveW equ <__imp_aiSysGetFixedDriveW>
  IFDEF __UNICODE__
    aiSysGetFixedDrive equ <__imp_aiSysGetFixedDriveW>
  ENDIF

externdef __imp_aiSysGetSystemDriveA:PPROC
aiSysGetSystemDriveA equ <__imp_aiSysGetSystemDriveA>
  IFNDEF __UNICODE__
    aiSysGetSystemDrive equ <__imp_aiSysGetSystemDriveA>
  ENDIF

externdef __imp_aiSysGetSystemDriveW:PPROC
aiSysGetSystemDriveW equ <__imp_aiSysGetSystemDriveW>
  IFDEF __UNICODE__
    aiSysGetSystemDrive equ <__imp_aiSysGetSystemDriveW>
  ENDIF

externdef __imp_aiSysGetUserSIDA:PPROC
aiSysGetUserSIDA equ <__imp_aiSysGetUserSIDA>
  IFNDEF __UNICODE__
    aiSysGetUserSID equ <__imp_aiSysGetUserSIDA>
  ENDIF

externdef __imp_aiSysGetUserSIDW:PPROC
aiSysGetUserSIDW equ <__imp_aiSysGetUserSIDW>
  IFDEF __UNICODE__
    aiSysGetUserSID equ <__imp_aiSysGetUserSIDW>
  ENDIF

externdef __imp_aiSysObtainSIDA:PPROC
aiSysObtainSIDA equ <__imp_aiSysObtainSIDA>
  IFNDEF __UNICODE__
    aiSysObtainSID equ <__imp_aiSysObtainSIDA>
  ENDIF

externdef __imp_aiSysObtainSIDW:PPROC
aiSysObtainSIDW equ <__imp_aiSysObtainSIDW>
  IFDEF __UNICODE__
    aiSysObtainSID equ <__imp_aiSysObtainSIDW>
  ENDIF
