externdef __imp_AddDelBackupEntry:PPROC
AddDelBackupEntry equ <__imp_AddDelBackupEntry>

externdef __imp_AdvInstallFile:PPROC
AdvInstallFile equ <__imp_AdvInstallFile>

externdef __imp_CloseINFEngine:PPROC
CloseINFEngine equ <__imp_CloseINFEngine>

externdef __imp_DelNode:PPROC
DelNode equ <__imp_DelNode>

externdef __imp_DelNodeRunDLL32:PPROC
DelNodeRunDLL32 equ <__imp_DelNodeRunDLL32>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_DoInfInstall:PPROC
DoInfInstall equ <__imp_DoInfInstall>

externdef __imp_ExecuteCab:PPROC
ExecuteCab equ <__imp_ExecuteCab>

externdef __imp_ExtractFiles:PPROC
ExtractFiles equ <__imp_ExtractFiles>

externdef __imp_FileSaveMarkNotExist:PPROC
FileSaveMarkNotExist equ <__imp_FileSaveMarkNotExist>

externdef __imp_FileSaveRestore:PPROC
FileSaveRestore equ <__imp_FileSaveRestore>

externdef __imp_FileSaveRestoreOnINF:PPROC
FileSaveRestoreOnINF equ <__imp_FileSaveRestoreOnINF>

externdef __imp_GetVersionFromFile:PPROC
GetVersionFromFile equ <__imp_GetVersionFromFile>

externdef __imp_GetVersionFromFileEx:PPROC
GetVersionFromFileEx equ <__imp_GetVersionFromFileEx>

externdef __imp_IsNTAdmin:PPROC
IsNTAdmin equ <__imp_IsNTAdmin>

externdef __imp_LaunchINFSection:PPROC
LaunchINFSection equ <__imp_LaunchINFSection>

externdef __imp_LaunchINFSectionEx:PPROC
LaunchINFSectionEx equ <__imp_LaunchINFSectionEx>

externdef __imp_NeedReboot:PPROC
NeedReboot equ <__imp_NeedReboot>

externdef __imp_NeedRebootInit:PPROC
NeedRebootInit equ <__imp_NeedRebootInit>

externdef __imp_OpenINFEngine:PPROC
OpenINFEngine equ <__imp_OpenINFEngine>

externdef __imp_RebootCheckOnInstall:PPROC
RebootCheckOnInstall equ <__imp_RebootCheckOnInstall>

externdef __imp_RegInstall:PPROC
RegInstall equ <__imp_RegInstall>

externdef __imp_RegRestoreAll:PPROC
RegRestoreAll equ <__imp_RegRestoreAll>

externdef __imp_RegSaveRestore:PPROC
RegSaveRestore equ <__imp_RegSaveRestore>

externdef __imp_RegSaveRestoreOnINF:PPROC
RegSaveRestoreOnINF equ <__imp_RegSaveRestoreOnINF>

externdef __imp_RegisterOCX:PPROC
RegisterOCX equ <__imp_RegisterOCX>

externdef __imp_RunSetupCommand:PPROC
RunSetupCommand equ <__imp_RunSetupCommand>

externdef __imp_SetPerUserSecValues:PPROC
SetPerUserSecValues equ <__imp_SetPerUserSecValues>

externdef __imp_TranslateInfString:PPROC
TranslateInfString equ <__imp_TranslateInfString>

externdef __imp_TranslateInfStringEx:PPROC
TranslateInfStringEx equ <__imp_TranslateInfStringEx>

externdef __imp_UserInstStubWrapper:PPROC
UserInstStubWrapper equ <__imp_UserInstStubWrapper>

externdef __imp_UserUnInstStubWrapper:PPROC
UserUnInstStubWrapper equ <__imp_UserUnInstStubWrapper>
