externdef __imp_??0CPattern@@QEAA@PEAD_N@Z:PPROC
??0CPattern@@QEAA@PEAD_N@Z equ <__imp_??0CPattern@@QEAA@PEAD_N@Z>

externdef __imp_??0bytestring@@QEAA@AEBV0@@Z:PPROC
??0bytestring@@QEAA@AEBV0@@Z equ <__imp_??0bytestring@@QEAA@AEBV0@@Z>

externdef __imp_??0bytestring@@QEAA@H@Z:PPROC
??0bytestring@@QEAA@H@Z equ <__imp_??0bytestring@@QEAA@H@Z>

externdef __imp_??0bytestring@@QEAA@PEBEH@Z:PPROC
??0bytestring@@QEAA@PEBEH@Z equ <__imp_??0bytestring@@QEAA@PEBEH@Z>

externdef __imp_??0bytestring@@QEAA@XZ:PPROC
??0bytestring@@QEAA@XZ equ <__imp_??0bytestring@@QEAA@XZ>

externdef __imp_??1CPattern@@QEAA@XZ:PPROC
??1CPattern@@QEAA@XZ equ <__imp_??1CPattern@@QEAA@XZ>

externdef __imp_??1bytestring@@QEAA@XZ:PPROC
??1bytestring@@QEAA@XZ equ <__imp_??1bytestring@@QEAA@XZ>

externdef __imp_??4CPattern@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CPattern@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CPattern@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_?IsMatched@CPattern@@QEAA_NPEBD@Z:PPROC
?IsMatched@CPattern@@QEAA_NPEBD@Z equ <__imp_?IsMatched@CPattern@@QEAA_NPEBD@Z>

externdef __imp_?clear@bytestring@@QEAAXXZ:PPROC
?clear@bytestring@@QEAAXXZ equ <__imp_?clear@bytestring@@QEAAXXZ>

externdef __imp_?data@bytestring@@QEAAPEAEXZ:PPROC
?data@bytestring@@QEAAPEAEXZ equ <__imp_?data@bytestring@@QEAAPEAEXZ>

externdef __imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PPROC
?fromasc@bytestring@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z equ <__imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>

externdef __imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z:PPROC
?fromasc@bytestring@@QEAA_NAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z equ <__imp_?fromasc@bytestring@@QEAA_NAEBV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z>

externdef __imp_?fromasc@bytestring@@QEAA_NPEBDH@Z:PPROC
?fromasc@bytestring@@QEAA_NPEBDH@Z equ <__imp_?fromasc@bytestring@@QEAA_NPEBDH@Z>

externdef __imp_?random@bytestring@@QEAAXH@Z:PPROC
?random@bytestring@@QEAAXH@Z equ <__imp_?random@bytestring@@QEAAXH@Z>

externdef __imp_?size@bytestring@@QEAAHXZ:PPROC
?size@bytestring@@QEAAHXZ equ <__imp_?size@bytestring@@QEAAHXZ>

externdef __imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z:PPROC
?toasc@bytestring@@QEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z equ <__imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z>

externdef __imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z:PPROC
?toasc@bytestring@@QEAA_NAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z equ <__imp_?toasc@bytestring@@QEAA_NAEAV?$basic_string@GU?$char_traits@G@std@@V?$allocator@G@2@@std@@@Z>

externdef __imp_acPatternIsMatched:PPROC
acPatternIsMatched equ <__imp_acPatternIsMatched>
