externdef __imp_??0ACCertificateExpiryNotificationInfo@@QEAA@AEBV0@@Z:PPROC
??0ACCertificateExpiryNotificationInfo@@QEAA@AEBV0@@Z equ <__imp_??0ACCertificateExpiryNotificationInfo@@QEAA@AEBV0@@Z>

externdef __imp_??0ACCertificateExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z:PPROC
??0ACCertificateExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z equ <__imp_??0ACCertificateExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z>

externdef __imp_??0ACExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAX@Z:PPROC
??0ACExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAX@Z equ <__imp_??0ACExpiryNotificationInfo@@QEAA@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAX@Z>

externdef __imp_??0ACPoliciesDlg@@QEAA@PEAUPwdRuleArgs@@HPEAUtagRECT@@PEAVCWnd@@HHH@Z:PPROC
??0ACPoliciesDlg@@QEAA@PEAUPwdRuleArgs@@HPEAUtagRECT@@PEAVCWnd@@HHH@Z equ <__imp_??0ACPoliciesDlg@@QEAA@PEAUPwdRuleArgs@@HPEAUtagRECT@@PEAVCWnd@@HHH@Z>

externdef __imp_??0CBaseDialog@@QEAA@IHPEAUtagRECT@@PEAVCWnd@@@Z:PPROC
??0CBaseDialog@@QEAA@IHPEAUtagRECT@@PEAVCWnd@@@Z equ <__imp_??0CBaseDialog@@QEAA@IHPEAUtagRECT@@PEAVCWnd@@@Z>

externdef __imp_??0CCMLockedDlg@@QEAA@PEAVCWnd@@PEBD@Z:PPROC
??0CCMLockedDlg@@QEAA@PEAVCWnd@@PEBD@Z equ <__imp_??0CCMLockedDlg@@QEAA@PEAVCWnd@@PEBD@Z>

externdef __imp_??0CCapsLockSensitiveEdit@@QEAA@XZ:PPROC
??0CCapsLockSensitiveEdit@@QEAA@XZ equ <__imp_??0CCapsLockSensitiveEdit@@QEAA@XZ>

externdef __imp_??0CChangePINDialog@@QEAA@HH_NPEAUtagRECT@@PEAUPwdRuleArgs@@PEAVCButton@@PEAVCWnd@@HHH@Z:PPROC
??0CChangePINDialog@@QEAA@HH_NPEAUtagRECT@@PEAUPwdRuleArgs@@PEAVCButton@@PEAVCWnd@@HHH@Z equ <__imp_??0CChangePINDialog@@QEAA@HH_NPEAUtagRECT@@PEAUPwdRuleArgs@@PEAVCButton@@PEAVCWnd@@HHH@Z>

externdef __imp_??0CDisplayUCChild@@QEAA@HPEAUtagRECT@@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAVCWnd@@@Z:PPROC
??0CDisplayUCChild@@QEAA@HPEAUtagRECT@@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAVCWnd@@@Z equ <__imp_??0CDisplayUCChild@@QEAA@HPEAUtagRECT@@V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAVCWnd@@@Z>

externdef __imp_??0CDisplayUnlockCodeDlg@@QEAA@PEAVCWnd@@PEBD1H@Z:PPROC
??0CDisplayUnlockCodeDlg@@QEAA@PEAVCWnd@@PEBD1H@Z equ <__imp_??0CDisplayUnlockCodeDlg@@QEAA@PEAVCWnd@@PEBD1H@Z>

externdef __imp_??0CInitializePinDlg@@QEAA@PEAVCWnd@@PEAUPINPolicies@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@HHHHHH@ZP6AH2@ZP6AH2AEAV34@@ZPEBD@Z:PPROC
??0CInitializePinDlg@@QEAA@PEAVCWnd@@PEAUPINPolicies@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@HHHHHH@ZP6AH2@ZP6AH2AEAV34@@ZPEBD@Z equ <__imp_??0CInitializePinDlg@@QEAA@PEAVCWnd@@PEAUPINPolicies@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@HHHHHH@ZP6AH2@ZP6AH2AEAV34@@ZPEBD@Z>

externdef __imp_??0CPopupAlert@@QEAA@XZ:PPROC
??0CPopupAlert@@QEAA@XZ equ <__imp_??0CPopupAlert@@QEAA@XZ>

externdef __imp_??0CResetCardDialog@@QEAA@HPEAUtagRECT@@PEAVCButton@@PEAVCWnd@@@Z:PPROC
??0CResetCardDialog@@QEAA@HPEAUtagRECT@@PEAVCButton@@PEAVCWnd@@@Z equ <__imp_??0CResetCardDialog@@QEAA@HPEAUtagRECT@@PEAVCButton@@PEAVCWnd@@@Z>

externdef __imp_??0CResetCardDialogMain@@QEAA@HPEAVCWnd@@HHHPEBD@Z:PPROC
??0CResetCardDialogMain@@QEAA@HPEAVCWnd@@HHHPEBD@Z equ <__imp_??0CResetCardDialogMain@@QEAA@HPEAVCWnd@@HHHPEBD@Z>

externdef __imp_??0CUnlockCardDlg@@QEAA@PEAVCWnd@@PEAUPwdRuleArgs@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@3@ZP6AH2AEAV34@@ZPEBD@Z:PPROC
??0CUnlockCardDlg@@QEAA@PEAVCWnd@@PEAUPwdRuleArgs@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@3@ZP6AH2AEAV34@@ZPEBD@Z equ <__imp_??0CUnlockCardDlg@@QEAA@PEAVCWnd@@PEAUPwdRuleArgs@@PEAXP6AH2V?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@3@ZP6AH2AEAV34@@ZPEBD@Z>

externdef __imp_??0CUnlockFailedDlg@@QEAA@PEAVCWnd@@PEBDH@Z:PPROC
??0CUnlockFailedDlg@@QEAA@PEAVCWnd@@PEBDH@Z equ <__imp_??0CUnlockFailedDlg@@QEAA@PEAVCWnd@@PEBDH@Z>

externdef __imp_??0CUnlockInitToolDlg@@QEAA@PEAVCWnd@@PEBDH@Z:PPROC
??0CUnlockInitToolDlg@@QEAA@PEAVCWnd@@PEBDH@Z equ <__imp_??0CUnlockInitToolDlg@@QEAA@PEAVCWnd@@PEBDH@Z>

externdef __imp_??0CUnlockSuccessDlg@@QEAA@PEAVCWnd@@@Z:PPROC
??0CUnlockSuccessDlg@@QEAA@PEAVCWnd@@@Z equ <__imp_??0CUnlockSuccessDlg@@QEAA@PEAVCWnd@@@Z>

externdef __imp_??1ACCertificateExpiryNotificationInfo@@QEAA@XZ:PPROC
??1ACCertificateExpiryNotificationInfo@@QEAA@XZ equ <__imp_??1ACCertificateExpiryNotificationInfo@@QEAA@XZ>

externdef __imp_??1ACExpiryNotificationInfo@@QEAA@XZ:PPROC
??1ACExpiryNotificationInfo@@QEAA@XZ equ <__imp_??1ACExpiryNotificationInfo@@QEAA@XZ>

externdef __imp_??1ACPoliciesDlg@@UEAA@XZ:PPROC
??1ACPoliciesDlg@@UEAA@XZ equ <__imp_??1ACPoliciesDlg@@UEAA@XZ>

externdef __imp_??1CBaseDialog@@UEAA@XZ:PPROC
??1CBaseDialog@@UEAA@XZ equ <__imp_??1CBaseDialog@@UEAA@XZ>

externdef __imp_??1CCMLockedDlg@@UEAA@XZ:PPROC
??1CCMLockedDlg@@UEAA@XZ equ <__imp_??1CCMLockedDlg@@UEAA@XZ>

externdef __imp_??1CCapsLockSensitiveEdit@@UEAA@XZ:PPROC
??1CCapsLockSensitiveEdit@@UEAA@XZ equ <__imp_??1CCapsLockSensitiveEdit@@UEAA@XZ>

externdef __imp_??1CChangePINDialog@@UEAA@XZ:PPROC
??1CChangePINDialog@@UEAA@XZ equ <__imp_??1CChangePINDialog@@UEAA@XZ>

externdef __imp_??1CDisplayUCChild@@UEAA@XZ:PPROC
??1CDisplayUCChild@@UEAA@XZ equ <__imp_??1CDisplayUCChild@@UEAA@XZ>

externdef __imp_??1CDisplayUnlockCodeDlg@@UEAA@XZ:PPROC
??1CDisplayUnlockCodeDlg@@UEAA@XZ equ <__imp_??1CDisplayUnlockCodeDlg@@UEAA@XZ>

externdef __imp_??1CInitializePinDlg@@UEAA@XZ:PPROC
??1CInitializePinDlg@@UEAA@XZ equ <__imp_??1CInitializePinDlg@@UEAA@XZ>

externdef __imp_??1CPopupAlert@@UEAA@XZ:PPROC
??1CPopupAlert@@UEAA@XZ equ <__imp_??1CPopupAlert@@UEAA@XZ>

externdef __imp_??1CResetCardDialog@@UEAA@XZ:PPROC
??1CResetCardDialog@@UEAA@XZ equ <__imp_??1CResetCardDialog@@UEAA@XZ>

externdef __imp_??1CResetCardDialogMain@@UEAA@XZ:PPROC
??1CResetCardDialogMain@@UEAA@XZ equ <__imp_??1CResetCardDialogMain@@UEAA@XZ>

externdef __imp_??1CUnlockCardDlg@@UEAA@XZ:PPROC
??1CUnlockCardDlg@@UEAA@XZ equ <__imp_??1CUnlockCardDlg@@UEAA@XZ>

externdef __imp_??1CUnlockFailedDlg@@UEAA@XZ:PPROC
??1CUnlockFailedDlg@@UEAA@XZ equ <__imp_??1CUnlockFailedDlg@@UEAA@XZ>

externdef __imp_??1CUnlockInitToolDlg@@UEAA@XZ:PPROC
??1CUnlockInitToolDlg@@UEAA@XZ equ <__imp_??1CUnlockInitToolDlg@@UEAA@XZ>

externdef __imp_??1CUnlockSuccessDlg@@UEAA@XZ:PPROC
??1CUnlockSuccessDlg@@UEAA@XZ equ <__imp_??1CUnlockSuccessDlg@@UEAA@XZ>

externdef __imp_??4ACCertificateExpiryNotificationInfo@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ACCertificateExpiryNotificationInfo@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ACCertificateExpiryNotificationInfo@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_7ACPoliciesDlg@@6B@:PPROC
??_7ACPoliciesDlg@@6B@ equ <__imp_??_7ACPoliciesDlg@@6B@>

externdef __imp_??_7CBaseDialog@@6B@:PPROC
??_7CBaseDialog@@6B@ equ <__imp_??_7CBaseDialog@@6B@>

externdef __imp_??_7CCMLockedDlg@@6B@:PPROC
??_7CCMLockedDlg@@6B@ equ <__imp_??_7CCMLockedDlg@@6B@>

externdef __imp_??_7CCapsLockSensitiveEdit@@6B@:PPROC
??_7CCapsLockSensitiveEdit@@6B@ equ <__imp_??_7CCapsLockSensitiveEdit@@6B@>

externdef __imp_??_7CChangePINDialog@@6B@:PPROC
??_7CChangePINDialog@@6B@ equ <__imp_??_7CChangePINDialog@@6B@>

externdef __imp_??_7CDisplayUCChild@@6B@:PPROC
??_7CDisplayUCChild@@6B@ equ <__imp_??_7CDisplayUCChild@@6B@>

externdef __imp_??_7CDisplayUnlockCodeDlg@@6B@:PPROC
??_7CDisplayUnlockCodeDlg@@6B@ equ <__imp_??_7CDisplayUnlockCodeDlg@@6B@>

externdef __imp_??_7CInitializePinDlg@@6B@:PPROC
??_7CInitializePinDlg@@6B@ equ <__imp_??_7CInitializePinDlg@@6B@>

externdef __imp_??_7CPopupAlert@@6B@:PPROC
??_7CPopupAlert@@6B@ equ <__imp_??_7CPopupAlert@@6B@>

externdef __imp_??_7CResetCardDialog@@6B@:PPROC
??_7CResetCardDialog@@6B@ equ <__imp_??_7CResetCardDialog@@6B@>

externdef __imp_??_7CResetCardDialogMain@@6B@:PPROC
??_7CResetCardDialogMain@@6B@ equ <__imp_??_7CResetCardDialogMain@@6B@>

externdef __imp_??_7CUnlockCardDlg@@6B@:PPROC
??_7CUnlockCardDlg@@6B@ equ <__imp_??_7CUnlockCardDlg@@6B@>

externdef __imp_??_7CUnlockFailedDlg@@6B@:PPROC
??_7CUnlockFailedDlg@@6B@ equ <__imp_??_7CUnlockFailedDlg@@6B@>

externdef __imp_??_7CUnlockInitToolDlg@@6B@:PPROC
??_7CUnlockInitToolDlg@@6B@ equ <__imp_??_7CUnlockInitToolDlg@@6B@>

externdef __imp_??_7CUnlockSuccessDlg@@6B@:PPROC
??_7CUnlockSuccessDlg@@6B@ equ <__imp_??_7CUnlockSuccessDlg@@6B@>

externdef __imp_??_FCDisplayUCChild@@QEAAXXZ:PPROC
??_FCDisplayUCChild@@QEAAXXZ equ <__imp_??_FCDisplayUCChild@@QEAAXXZ>

externdef __imp_??_FCResetCardDialog@@QEAAXXZ:PPROC
??_FCResetCardDialog@@QEAAXXZ equ <__imp_??_FCResetCardDialog@@QEAAXXZ>

externdef __imp_??_FCUnlockSuccessDlg@@QEAAXXZ:PPROC
??_FCUnlockSuccessDlg@@QEAAXXZ equ <__imp_??_FCUnlockSuccessDlg@@QEAAXXZ>

externdef __imp_?AddCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z:PPROC
?AddCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z equ <__imp_?AddCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@_J@Z>

externdef __imp_?AdjustWindow@CCMLockedDlg@@IEAAXXZ:PPROC
?AdjustWindow@CCMLockedDlg@@IEAAXXZ equ <__imp_?AdjustWindow@CCMLockedDlg@@IEAAXXZ>

externdef __imp_?CheckCapsLockMessage@CCapsLockSensitiveEdit@@IEAAXXZ:PPROC
?CheckCapsLockMessage@CCapsLockSensitiveEdit@@IEAAXXZ equ <__imp_?CheckCapsLockMessage@CCapsLockSensitiveEdit@@IEAAXXZ>

externdef __imp_?CheckWindow@CResetCardDialog@@QEAAX_N@Z:PPROC
?CheckWindow@CResetCardDialog@@QEAAX_N@Z equ <__imp_?CheckWindow@CResetCardDialog@@QEAAX_N@Z>

externdef __imp_?Create@CPopupAlert@@QEAAHPEAUHWND__@@@Z:PPROC
?Create@CPopupAlert@@QEAAHPEAUHWND__@@@Z equ <__imp_?Create@CPopupAlert@@QEAAHPEAUHWND__@@@Z>

externdef __imp_?DisablePIN@CResetCardDialog@@QEAAXXZ:PPROC
?DisablePIN@CResetCardDialog@@QEAAXXZ equ <__imp_?DisablePIN@CResetCardDialog@@QEAAXXZ>

externdef __imp_?DoDataExchange@ACPoliciesDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@ACPoliciesDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@ACPoliciesDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CBaseDialog@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CBaseDialog@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CBaseDialog@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CCMLockedDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CCMLockedDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CCMLockedDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CChangePINDialog@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CChangePINDialog@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CChangePINDialog@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CDisplayUCChild@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CDisplayUCChild@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CDisplayUCChild@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CDisplayUnlockCodeDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CDisplayUnlockCodeDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CDisplayUnlockCodeDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CInitializePinDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CInitializePinDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CInitializePinDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CResetCardDialog@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CResetCardDialog@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CResetCardDialog@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CResetCardDialogMain@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CResetCardDialogMain@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CResetCardDialogMain@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CUnlockCardDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CUnlockCardDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CUnlockCardDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CUnlockFailedDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CUnlockFailedDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CUnlockFailedDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CUnlockInitToolDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CUnlockInitToolDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CUnlockInitToolDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoDataExchange@CUnlockSuccessDlg@@MEAAXPEAVCDataExchange@@@Z:PPROC
?DoDataExchange@CUnlockSuccessDlg@@MEAAXPEAVCDataExchange@@@Z equ <__imp_?DoDataExchange@CUnlockSuccessDlg@@MEAAXPEAVCDataExchange@@@Z>

externdef __imp_?DoModal@CCMLockedDlg@@UEAA_JXZ:PPROC
?DoModal@CCMLockedDlg@@UEAA_JXZ equ <__imp_?DoModal@CCMLockedDlg@@UEAA_JXZ>

externdef __imp_?DoModal@CDisplayUnlockCodeDlg@@UEAA_JXZ:PPROC
?DoModal@CDisplayUnlockCodeDlg@@UEAA_JXZ equ <__imp_?DoModal@CDisplayUnlockCodeDlg@@UEAA_JXZ>

externdef __imp_?DoModal@CInitializePinDlg@@UEAA_JXZ:PPROC
?DoModal@CInitializePinDlg@@UEAA_JXZ equ <__imp_?DoModal@CInitializePinDlg@@UEAA_JXZ>

externdef __imp_?DoModal@CResetCardDialogMain@@UEAA_JXZ:PPROC
?DoModal@CResetCardDialogMain@@UEAA_JXZ equ <__imp_?DoModal@CResetCardDialogMain@@UEAA_JXZ>

externdef __imp_?DoModal@CUnlockCardDlg@@UEAA_JXZ:PPROC
?DoModal@CUnlockCardDlg@@UEAA_JXZ equ <__imp_?DoModal@CUnlockCardDlg@@UEAA_JXZ>

externdef __imp_?DoModal@CUnlockFailedDlg@@UEAA_JXZ:PPROC
?DoModal@CUnlockFailedDlg@@UEAA_JXZ equ <__imp_?DoModal@CUnlockFailedDlg@@UEAA_JXZ>

externdef __imp_?DoModal@CUnlockInitToolDlg@@UEAA_JXZ:PPROC
?DoModal@CUnlockInitToolDlg@@UEAA_JXZ equ <__imp_?DoModal@CUnlockInitToolDlg@@UEAA_JXZ>

externdef __imp_?DoModal@CUnlockSuccessDlg@@UEAA_JXZ:PPROC
?DoModal@CUnlockSuccessDlg@@UEAA_JXZ equ <__imp_?DoModal@CUnlockSuccessDlg@@UEAA_JXZ>

externdef __imp_?EraseAllPinBuffers@CChangePINDialog@@QEAAXXZ:PPROC
?EraseAllPinBuffers@CChangePINDialog@@QEAAXXZ equ <__imp_?EraseAllPinBuffers@CChangePINDialog@@QEAAXXZ>

externdef __imp_?GenerateRegion@CPopupAlert@@IEAAPEAUHRGN__@@PEAUHBITMAP__@@EEE@Z:PPROC
?GenerateRegion@CPopupAlert@@IEAAPEAUHRGN__@@PEAUHBITMAP__@@EEE@Z equ <__imp_?GenerateRegion@CPopupAlert@@IEAAPEAUHRGN__@@PEAUHBITMAP__@@EEE@Z>

externdef __imp_?Get24BitPixels@CPopupAlert@@IEAAPEAEPEAUHBITMAP__@@PEAG1@Z:PPROC
?Get24BitPixels@CPopupAlert@@IEAAPEAEPEAUHBITMAP__@@PEAG1@Z equ <__imp_?Get24BitPixels@CPopupAlert@@IEAAPEAEPEAUHBITMAP__@@PEAG1@Z>

externdef __imp_?GetCancelEvent@ACExpiryNotificationInfo@@QEAAPEAXXZ:PPROC
?GetCancelEvent@ACExpiryNotificationInfo@@QEAAPEAXXZ equ <__imp_?GetCancelEvent@ACExpiryNotificationInfo@@QEAAPEAXXZ>

externdef __imp_?GetCertificateExpiryDate@ACCertificateExpiryNotificationInfo@@QEAAAEAVCTime@ATL@@XZ:PPROC
?GetCertificateExpiryDate@ACCertificateExpiryNotificationInfo@@QEAAAEAVCTime@ATL@@XZ equ <__imp_?GetCertificateExpiryDate@ACCertificateExpiryNotificationInfo@@QEAAAEAVCTime@ATL@@XZ>

externdef __imp_?GetCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAPEAVACCertificateExpiryNotificationInfo@@H@Z:PPROC
?GetCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAPEAVACCertificateExpiryNotificationInfo@@H@Z equ <__imp_?GetCertificateExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAPEAVACCertificateExpiryNotificationInfo@@H@Z>

externdef __imp_?GetFriendlyName@ACCertificateExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PPROC
?GetFriendlyName@ACCertificateExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ equ <__imp_?GetFriendlyName@ACCertificateExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>

externdef __imp_?GetMessageMap@ACPoliciesDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@ACPoliciesDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@ACPoliciesDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CBaseDialog@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CBaseDialog@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CBaseDialog@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CCMLockedDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CCMLockedDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CCMLockedDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CCapsLockSensitiveEdit@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CCapsLockSensitiveEdit@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CCapsLockSensitiveEdit@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CChangePINDialog@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CChangePINDialog@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CChangePINDialog@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CDisplayUCChild@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CDisplayUCChild@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CDisplayUCChild@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CDisplayUnlockCodeDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CDisplayUnlockCodeDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CDisplayUnlockCodeDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CInitializePinDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CInitializePinDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CInitializePinDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CPopupAlert@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CPopupAlert@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CPopupAlert@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CResetCardDialog@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CResetCardDialog@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CResetCardDialog@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CResetCardDialogMain@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CResetCardDialogMain@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CResetCardDialogMain@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CUnlockCardDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CUnlockCardDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CUnlockCardDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CUnlockFailedDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CUnlockFailedDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CUnlockFailedDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CUnlockInitToolDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CUnlockInitToolDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CUnlockInitToolDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetMessageMap@CUnlockSuccessDlg@@MEBAPEBUAFX_MSGMAP@@XZ:PPROC
?GetMessageMap@CUnlockSuccessDlg@@MEBAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetMessageMap@CUnlockSuccessDlg@@MEBAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetNbCertExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAHXZ:PPROC
?GetNbCertExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAHXZ equ <__imp_?GetNbCertExpiryNotificationInfo@ACExpiryNotificationInfo@@QEAAHXZ>

externdef __imp_?GetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAHXZ:PPROC
?GetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAHXZ equ <__imp_?GetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAHXZ>

externdef __imp_?GetPin@CResetCardDialog@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PPROC
?GetPin@CResetCardDialog@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ equ <__imp_?GetPin@CResetCardDialog@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>

externdef __imp_?GetPin@CResetCardDialogMain@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PPROC
?GetPin@CResetCardDialogMain@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ equ <__imp_?GetPin@CResetCardDialogMain@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>

externdef __imp_?GetReaderName@ACExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ:PPROC
?GetReaderName@ACExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ equ <__imp_?GetReaderName@ACExpiryNotificationInfo@@QEAA?AV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@XZ>

externdef __imp_?GetRegistryParameters@CPopupAlert@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAKH@Z:PPROC
?GetRegistryParameters@CPopupAlert@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAKH@Z equ <__imp_?GetRegistryParameters@CPopupAlert@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@PEAKH@Z>

externdef __imp_?GetRuntimeClass@ACPoliciesDlg@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@ACPoliciesDlg@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@ACPoliciesDlg@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CBaseDialog@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CBaseDialog@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CBaseDialog@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CCMLockedDlg@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CCMLockedDlg@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CCMLockedDlg@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CCapsLockSensitiveEdit@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CCapsLockSensitiveEdit@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CCapsLockSensitiveEdit@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CChangePINDialog@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CChangePINDialog@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CChangePINDialog@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CDisplayUCChild@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CDisplayUCChild@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CDisplayUCChild@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CDisplayUnlockCodeDlg@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CDisplayUnlockCodeDlg@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CDisplayUnlockCodeDlg@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CPopupAlert@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CPopupAlert@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CPopupAlert@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CResetCardDialog@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CResetCardDialog@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CResetCardDialog@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CResetCardDialogMain@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CResetCardDialogMain@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CResetCardDialogMain@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetRuntimeClass@CUnlockInitToolDlg@@UEBAPEAUCRuntimeClass@@XZ:PPROC
?GetRuntimeClass@CUnlockInitToolDlg@@UEBAPEAUCRuntimeClass@@XZ equ <__imp_?GetRuntimeClass@CUnlockInitToolDlg@@UEBAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@ACPoliciesDlg@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@ACPoliciesDlg@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@ACPoliciesDlg@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CBaseDialog@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CBaseDialog@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CBaseDialog@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CCMLockedDlg@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CCMLockedDlg@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CCMLockedDlg@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CCapsLockSensitiveEdit@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CCapsLockSensitiveEdit@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CCapsLockSensitiveEdit@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CChangePINDialog@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CChangePINDialog@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CChangePINDialog@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CDisplayUCChild@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CDisplayUCChild@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CDisplayUCChild@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CDisplayUnlockCodeDlg@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CDisplayUnlockCodeDlg@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CDisplayUnlockCodeDlg@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CPopupAlert@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CPopupAlert@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CPopupAlert@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CResetCardDialog@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CResetCardDialog@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CResetCardDialog@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CResetCardDialogMain@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CResetCardDialogMain@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CResetCardDialogMain@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisClass@CUnlockInitToolDlg@@SAPEAUCRuntimeClass@@XZ:PPROC
?GetThisClass@CUnlockInitToolDlg@@SAPEAUCRuntimeClass@@XZ equ <__imp_?GetThisClass@CUnlockInitToolDlg@@SAPEAUCRuntimeClass@@XZ>

externdef __imp_?GetThisMessageMap@ACPoliciesDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@ACPoliciesDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@ACPoliciesDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CBaseDialog@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CBaseDialog@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CBaseDialog@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CCMLockedDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CCMLockedDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CCMLockedDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CCapsLockSensitiveEdit@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CCapsLockSensitiveEdit@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CCapsLockSensitiveEdit@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CChangePINDialog@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CChangePINDialog@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CChangePINDialog@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CDisplayUCChild@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CDisplayUCChild@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CDisplayUCChild@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CDisplayUnlockCodeDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CDisplayUnlockCodeDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CDisplayUnlockCodeDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CInitializePinDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CInitializePinDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CInitializePinDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CPopupAlert@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CPopupAlert@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CPopupAlert@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CResetCardDialog@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CResetCardDialog@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CResetCardDialog@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CResetCardDialogMain@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CResetCardDialogMain@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CResetCardDialogMain@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CUnlockCardDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CUnlockCardDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CUnlockCardDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CUnlockFailedDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CUnlockFailedDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CUnlockFailedDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CUnlockInitToolDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CUnlockInitToolDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CUnlockInitToolDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?GetThisMessageMap@CUnlockSuccessDlg@@KAPEBUAFX_MSGMAP@@XZ:PPROC
?GetThisMessageMap@CUnlockSuccessDlg@@KAPEBUAFX_MSGMAP@@XZ equ <__imp_?GetThisMessageMap@CUnlockSuccessDlg@@KAPEBUAFX_MSGMAP@@XZ>

externdef __imp_?Hide@CPopupAlert@@QEAAXXZ:PPROC
?Hide@CPopupAlert@@QEAAXXZ equ <__imp_?Hide@CPopupAlert@@QEAAXXZ>

externdef __imp_?HidePinFromMemory@CBaseDialog@@IEAAXAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PPROC
?HidePinFromMemory@CBaseDialog@@IEAAXAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z equ <__imp_?HidePinFromMemory@CBaseDialog@@IEAAXAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>

externdef __imp_?InitWindow@CPopupAlert@@QEAA_NPEAUHWND__@@HK@Z:PPROC
?InitWindow@CPopupAlert@@QEAA_NPEAUHWND__@@HK@Z equ <__imp_?InitWindow@CPopupAlert@@QEAA_NPEAUHWND__@@HK@Z>

externdef __imp_?IsAlphaPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PPROC
?IsAlphaPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z equ <__imp_?IsAlphaPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>

externdef __imp_?IsNeverDisplayChecked@CDisplayUCChild@@QEAAHXZ:PPROC
?IsNeverDisplayChecked@CDisplayUCChild@@QEAAHXZ equ <__imp_?IsNeverDisplayChecked@CDisplayUCChild@@QEAAHXZ>

externdef __imp_?IsPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PPROC
?IsPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z equ <__imp_?IsPinWeak@ACPoliciesDlg@@AEAA_NAEAV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>

externdef __imp_?IsPointOnArea@CPopupAlert@@AEAA_NPEAVCPoint@@PEAVCRect@@@Z:PPROC
?IsPointOnArea@CPopupAlert@@AEAA_NPEAVCPoint@@PEAVCRect@@@Z equ <__imp_?IsPointOnArea@CPopupAlert@@AEAA_NPEAVCPoint@@PEAVCRect@@@Z>

externdef __imp_?LocCreate@ACPoliciesDlg@@QEAAHPEAVCWnd@@@Z:PPROC
?LocCreate@ACPoliciesDlg@@QEAAHPEAVCWnd@@@Z equ <__imp_?LocCreate@ACPoliciesDlg@@QEAAHPEAVCWnd@@@Z>

externdef __imp_?LocCreate@CChangePINDialog@@QEAAHPEAVCWnd@@@Z:PPROC
?LocCreate@CChangePINDialog@@QEAAHPEAVCWnd@@@Z equ <__imp_?LocCreate@CChangePINDialog@@QEAAHPEAVCWnd@@@Z>

externdef __imp_?LocCreate@CDisplayUCChild@@QEAAHPEAVCWnd@@@Z:PPROC
?LocCreate@CDisplayUCChild@@QEAAHPEAVCWnd@@@Z equ <__imp_?LocCreate@CDisplayUCChild@@QEAAHPEAVCWnd@@@Z>

externdef __imp_?LocCreate@CResetCardDialog@@QEAAHPEAVCWnd@@@Z:PPROC
?LocCreate@CResetCardDialog@@QEAAHPEAVCWnd@@@Z equ <__imp_?LocCreate@CResetCardDialog@@QEAAHPEAVCWnd@@@Z>

externdef __imp_?MoveDlgItem@CResetCardDialogMain@@AEAAXHHH@Z:PPROC
?MoveDlgItem@CResetCardDialogMain@@AEAAXHHH@Z equ <__imp_?MoveDlgItem@CResetCardDialogMain@@AEAAXHHH@Z>

externdef __imp_?MoveUpWindow@CInitializePinDlg@@IEAAXIH@Z:PPROC
?MoveUpWindow@CInitializePinDlg@@IEAAXIH@Z equ <__imp_?MoveUpWindow@CInitializePinDlg@@IEAAXIH@Z>

externdef __imp_?MoveUpWindow@CUnlockCardDlg@@IEAAXIH@Z:PPROC
?MoveUpWindow@CUnlockCardDlg@@IEAAXIH@Z equ <__imp_?MoveUpWindow@CUnlockCardDlg@@IEAAXIH@Z>

externdef __imp_?MustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAHAEAVCTime@ATL@@@Z:PPROC
?MustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAHAEAVCTime@ATL@@@Z equ <__imp_?MustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAHAEAVCTime@ATL@@@Z>

externdef __imp_?OnBnClickedStaticNp@CUnlockCardDlg@@QEAAXXZ:PPROC
?OnBnClickedStaticNp@CUnlockCardDlg@@QEAAXXZ equ <__imp_?OnBnClickedStaticNp@CUnlockCardDlg@@QEAAXXZ>

externdef __imp_?OnCancel@CUnlockCardDlg@@MEAAXXZ:PPROC
?OnCancel@CUnlockCardDlg@@MEAAXXZ equ <__imp_?OnCancel@CUnlockCardDlg@@MEAAXXZ>

externdef __imp_?OnCardEvent@CPopupAlert@@QEAA_J_K_J@Z:PPROC
?OnCardEvent@CPopupAlert@@QEAA_J_K_J@Z equ <__imp_?OnCardEvent@CPopupAlert@@QEAA_J_K_J@Z>

externdef __imp_?OnCardEvent@CResetCardDialogMain@@IEAA_J_K_J@Z:PPROC
?OnCardEvent@CResetCardDialogMain@@IEAA_J_K_J@Z equ <__imp_?OnCardEvent@CResetCardDialogMain@@IEAA_J_K_J@Z>

externdef __imp_?OnCardEvent@CUnlockCardDlg@@IEAA_J_K_J@Z:PPROC
?OnCardEvent@CUnlockCardDlg@@IEAA_J_K_J@Z equ <__imp_?OnCardEvent@CUnlockCardDlg@@IEAA_J_K_J@Z>

externdef __imp_?OnChangeEdit@CUnlockCardDlg@@IEAAXXZ:PPROC
?OnChangeEdit@CUnlockCardDlg@@IEAAXXZ equ <__imp_?OnChangeEdit@CUnlockCardDlg@@IEAAXXZ>

externdef __imp_?OnChangeEditNewPin@CInitializePinDlg@@IEAAXXZ:PPROC
?OnChangeEditNewPin@CInitializePinDlg@@IEAAXXZ equ <__imp_?OnChangeEditNewPin@CInitializePinDlg@@IEAAXXZ>

externdef __imp_?OnCheckOkButton@CResetCardDialog@@IEAAXXZ:PPROC
?OnCheckOkButton@CResetCardDialog@@IEAAXXZ equ <__imp_?OnCheckOkButton@CResetCardDialog@@IEAAXXZ>

externdef __imp_?OnContextualHelp@CCMLockedDlg@@MEAAXXZ:PPROC
?OnContextualHelp@CCMLockedDlg@@MEAAXXZ equ <__imp_?OnContextualHelp@CCMLockedDlg@@MEAAXXZ>

externdef __imp_?OnContextualHelp@CUnlockCardDlg@@MEAAXXZ:PPROC
?OnContextualHelp@CUnlockCardDlg@@MEAAXXZ equ <__imp_?OnContextualHelp@CUnlockCardDlg@@MEAAXXZ>

externdef __imp_?OnCreate@CPopupAlert@@QEAAHPEAUtagCREATESTRUCTA@@@Z:PPROC
?OnCreate@CPopupAlert@@QEAAHPEAUtagCREATESTRUCTA@@@Z equ <__imp_?OnCreate@CPopupAlert@@QEAAHPEAUtagCREATESTRUCTA@@@Z>

externdef __imp_?OnCtlColor@CBaseDialog@@QEAAPEAUHBRUSH__@@PEAVCDC@@PEAVCWnd@@I@Z:PPROC
?OnCtlColor@CBaseDialog@@QEAAPEAUHBRUSH__@@PEAVCDC@@PEAVCWnd@@I@Z equ <__imp_?OnCtlColor@CBaseDialog@@QEAAPEAUHBRUSH__@@PEAVCDC@@PEAVCWnd@@I@Z>

externdef __imp_?OnDestroy@CChangePINDialog@@QEAAXXZ:PPROC
?OnDestroy@CChangePINDialog@@QEAAXXZ equ <__imp_?OnDestroy@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnDestroy@CDisplayUnlockCodeDlg@@IEAAXXZ:PPROC
?OnDestroy@CDisplayUnlockCodeDlg@@IEAAXXZ equ <__imp_?OnDestroy@CDisplayUnlockCodeDlg@@IEAAXXZ>

externdef __imp_?OnDestroy@CPopupAlert@@QEAAXXZ:PPROC
?OnDestroy@CPopupAlert@@QEAAXXZ equ <__imp_?OnDestroy@CPopupAlert@@QEAAXXZ>

externdef __imp_?OnDestroy@CResetCardDialogMain@@IEAAXXZ:PPROC
?OnDestroy@CResetCardDialogMain@@IEAAXXZ equ <__imp_?OnDestroy@CResetCardDialogMain@@IEAAXXZ>

externdef __imp_?OnDestroy@CUnlockCardDlg@@IEAAXXZ:PPROC
?OnDestroy@CUnlockCardDlg@@IEAAXXZ equ <__imp_?OnDestroy@CUnlockCardDlg@@IEAAXXZ>

externdef __imp_?OnDisplayPINPolicies@CInitializePinDlg@@IEAA_J_K_J@Z:PPROC
?OnDisplayPINPolicies@CInitializePinDlg@@IEAA_J_K_J@Z equ <__imp_?OnDisplayPINPolicies@CInitializePinDlg@@IEAA_J_K_J@Z>

externdef __imp_?OnDisplayPINPolicies@CUnlockCardDlg@@IEAA_J_K_J@Z:PPROC
?OnDisplayPINPolicies@CUnlockCardDlg@@IEAA_J_K_J@Z equ <__imp_?OnDisplayPINPolicies@CUnlockCardDlg@@IEAA_J_K_J@Z>

externdef __imp_?OnEnChangeEditPin@CChangePINDialog@@QEAAXXZ:PPROC
?OnEnChangeEditPin@CChangePINDialog@@QEAAXXZ equ <__imp_?OnEnChangeEditPin@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnEnChangeEditPinConfirm@CChangePINDialog@@QEAAXXZ:PPROC
?OnEnChangeEditPinConfirm@CChangePINDialog@@QEAAXXZ equ <__imp_?OnEnChangeEditPinConfirm@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnEnChangeEditPinNew@CChangePINDialog@@QEAAXXZ:PPROC
?OnEnChangeEditPinNew@CChangePINDialog@@QEAAXXZ equ <__imp_?OnEnChangeEditPinNew@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnEnSetfocusEditPin@CChangePINDialog@@QEAAXXZ:PPROC
?OnEnSetfocusEditPin@CChangePINDialog@@QEAAXXZ equ <__imp_?OnEnSetfocusEditPin@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnEnSetfocusEditPinConfirm@CChangePINDialog@@QEAAXXZ:PPROC
?OnEnSetfocusEditPinConfirm@CChangePINDialog@@QEAAXXZ equ <__imp_?OnEnSetfocusEditPinConfirm@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnEnSetfocusEditPinNew@CChangePINDialog@@QEAAXXZ:PPROC
?OnEnSetfocusEditPinNew@CChangePINDialog@@QEAAXXZ equ <__imp_?OnEnSetfocusEditPinNew@CChangePINDialog@@QEAAXXZ>

externdef __imp_?OnEraseBkgnd@CPopupAlert@@QEAAHPEAVCDC@@@Z:PPROC
?OnEraseBkgnd@CPopupAlert@@QEAAHPEAVCDC@@@Z equ <__imp_?OnEraseBkgnd@CPopupAlert@@QEAAHPEAVCDC@@@Z>

externdef __imp_?OnInitDialog@ACPoliciesDlg@@MEAAHXZ:PPROC
?OnInitDialog@ACPoliciesDlg@@MEAAHXZ equ <__imp_?OnInitDialog@ACPoliciesDlg@@MEAAHXZ>

externdef __imp_?OnInitDialog@CBaseDialog@@MEAAHXZ:PPROC
?OnInitDialog@CBaseDialog@@MEAAHXZ equ <__imp_?OnInitDialog@CBaseDialog@@MEAAHXZ>

externdef __imp_?OnInitDialog@CCMLockedDlg@@UEAAHXZ:PPROC
?OnInitDialog@CCMLockedDlg@@UEAAHXZ equ <__imp_?OnInitDialog@CCMLockedDlg@@UEAAHXZ>

externdef __imp_?OnInitDialog@CChangePINDialog@@MEAAHXZ:PPROC
?OnInitDialog@CChangePINDialog@@MEAAHXZ equ <__imp_?OnInitDialog@CChangePINDialog@@MEAAHXZ>

externdef __imp_?OnInitDialog@CDisplayUnlockCodeDlg@@MEAAHXZ:PPROC
?OnInitDialog@CDisplayUnlockCodeDlg@@MEAAHXZ equ <__imp_?OnInitDialog@CDisplayUnlockCodeDlg@@MEAAHXZ>

externdef __imp_?OnInitDialog@CInitializePinDlg@@MEAAHXZ:PPROC
?OnInitDialog@CInitializePinDlg@@MEAAHXZ equ <__imp_?OnInitDialog@CInitializePinDlg@@MEAAHXZ>

externdef __imp_?OnInitDialog@CResetCardDialog@@MEAAHXZ:PPROC
?OnInitDialog@CResetCardDialog@@MEAAHXZ equ <__imp_?OnInitDialog@CResetCardDialog@@MEAAHXZ>

externdef __imp_?OnInitDialog@CResetCardDialogMain@@MEAAHXZ:PPROC
?OnInitDialog@CResetCardDialogMain@@MEAAHXZ equ <__imp_?OnInitDialog@CResetCardDialogMain@@MEAAHXZ>

externdef __imp_?OnInitDialog@CUnlockCardDlg@@MEAAHXZ:PPROC
?OnInitDialog@CUnlockCardDlg@@MEAAHXZ equ <__imp_?OnInitDialog@CUnlockCardDlg@@MEAAHXZ>

externdef __imp_?OnInitDialog@CUnlockFailedDlg@@MEAAHXZ:PPROC
?OnInitDialog@CUnlockFailedDlg@@MEAAHXZ equ <__imp_?OnInitDialog@CUnlockFailedDlg@@MEAAHXZ>

externdef __imp_?OnInitDialog@CUnlockInitToolDlg@@UEAAHXZ:PPROC
?OnInitDialog@CUnlockInitToolDlg@@UEAAHXZ equ <__imp_?OnInitDialog@CUnlockInitToolDlg@@UEAAHXZ>

externdef __imp_?OnInitDialog@CUnlockSuccessDlg@@MEAAHXZ:PPROC
?OnInitDialog@CUnlockSuccessDlg@@MEAAHXZ equ <__imp_?OnInitDialog@CUnlockSuccessDlg@@MEAAHXZ>

externdef __imp_?OnKeyUp@CCapsLockSensitiveEdit@@QEAAXIII@Z:PPROC
?OnKeyUp@CCapsLockSensitiveEdit@@QEAAXIII@Z equ <__imp_?OnKeyUp@CCapsLockSensitiveEdit@@QEAAXIII@Z>

externdef __imp_?OnKillFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z:PPROC
?OnKillFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z equ <__imp_?OnKillFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z>

externdef __imp_?OnMove@CChangePINDialog@@QEAAXHH@Z:PPROC
?OnMove@CChangePINDialog@@QEAAXHH@Z equ <__imp_?OnMove@CChangePINDialog@@QEAAXHH@Z>

externdef __imp_?OnMove@CInitializePinDlg@@QEAAXHH@Z:PPROC
?OnMove@CInitializePinDlg@@QEAAXHH@Z equ <__imp_?OnMove@CInitializePinDlg@@QEAAXHH@Z>

externdef __imp_?OnMove@CResetCardDialog@@QEAAXHH@Z:PPROC
?OnMove@CResetCardDialog@@QEAAXHH@Z equ <__imp_?OnMove@CResetCardDialog@@QEAAXHH@Z>

externdef __imp_?OnMove@CResetCardDialogMain@@QEAAXHH@Z:PPROC
?OnMove@CResetCardDialogMain@@QEAAXHH@Z equ <__imp_?OnMove@CResetCardDialogMain@@QEAAXHH@Z>

externdef __imp_?OnMove@CUnlockCardDlg@@QEAAXHH@Z:PPROC
?OnMove@CUnlockCardDlg@@QEAAXHH@Z equ <__imp_?OnMove@CUnlockCardDlg@@QEAAXHH@Z>

externdef __imp_?OnNcHitTest@CPopupAlert@@QEAA_JVCPoint@@@Z:PPROC
?OnNcHitTest@CPopupAlert@@QEAA_JVCPoint@@@Z equ <__imp_?OnNcHitTest@CPopupAlert@@QEAA_JVCPoint@@@Z>

externdef __imp_?OnNotify@CCapsLockSensitiveEdit@@MEAAH_K_JPEA_J@Z:PPROC
?OnNotify@CCapsLockSensitiveEdit@@MEAAH_K_JPEA_J@Z equ <__imp_?OnNotify@CCapsLockSensitiveEdit@@MEAAH_K_JPEA_J@Z>

externdef __imp_?OnOK@CDisplayUnlockCodeDlg@@MEAAXXZ:PPROC
?OnOK@CDisplayUnlockCodeDlg@@MEAAXXZ equ <__imp_?OnOK@CDisplayUnlockCodeDlg@@MEAAXXZ>

externdef __imp_?OnOK@CInitializePinDlg@@MEAAXXZ:PPROC
?OnOK@CInitializePinDlg@@MEAAXXZ equ <__imp_?OnOK@CInitializePinDlg@@MEAAXXZ>

externdef __imp_?OnOK@CUnlockCardDlg@@MEAAXXZ:PPROC
?OnOK@CUnlockCardDlg@@MEAAXXZ equ <__imp_?OnOK@CUnlockCardDlg@@MEAAXXZ>

externdef __imp_?OnOtpOk@CPopupAlert@@QEAA_J_K_J@Z:PPROC
?OnOtpOk@CPopupAlert@@QEAA_J_K_J@Z equ <__imp_?OnOtpOk@CPopupAlert@@QEAA_J_K_J@Z>

externdef __imp_?OnPopupAlertClicked@CPopupAlert@@QEAA_J_K_J@Z:PPROC
?OnPopupAlertClicked@CPopupAlert@@QEAA_J_K_J@Z equ <__imp_?OnPopupAlertClicked@CPopupAlert@@QEAA_J_K_J@Z>

externdef __imp_?OnPopupAlertHelpClicked@CPopupAlert@@QEAA_J_K_J@Z:PPROC
?OnPopupAlertHelpClicked@CPopupAlert@@QEAA_J_K_J@Z equ <__imp_?OnPopupAlertHelpClicked@CPopupAlert@@QEAA_J_K_J@Z>

externdef __imp_?OnRadioClicked@CResetCardDialog@@IEAAXXZ:PPROC
?OnRadioClicked@CResetCardDialog@@IEAAXXZ equ <__imp_?OnRadioClicked@CResetCardDialog@@IEAAXXZ>

externdef __imp_?OnSetFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z:PPROC
?OnSetFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z equ <__imp_?OnSetFocus@CCapsLockSensitiveEdit@@QEAAXPEAVCWnd@@@Z>

externdef __imp_?OnSysColorChange@CBaseDialog@@QEAAXXZ:PPROC
?OnSysColorChange@CBaseDialog@@QEAAXXZ equ <__imp_?OnSysColorChange@CBaseDialog@@QEAAXXZ>

externdef __imp_?OnTimer@CPopupAlert@@QEAAX_K@Z:PPROC
?OnTimer@CPopupAlert@@QEAAX_K@Z equ <__imp_?OnTimer@CPopupAlert@@QEAAX_K@Z>

externdef __imp_?PrepareBackgroundBitmap@CPopupAlert@@AEAAHI_N0@Z:PPROC
?PrepareBackgroundBitmap@CPopupAlert@@AEAAHI_N0@Z equ <__imp_?PrepareBackgroundBitmap@CPopupAlert@@AEAAHI_N0@Z>

externdef __imp_?PutPoliciesInBox@ACPoliciesDlg@@AEAAXXZ:PPROC
?PutPoliciesInBox@ACPoliciesDlg@@AEAAXXZ equ <__imp_?PutPoliciesInBox@ACPoliciesDlg@@AEAAXXZ>

externdef __imp_?ResetToolTip@CCapsLockSensitiveEdit@@QEAAXXZ:PPROC
?ResetToolTip@CCapsLockSensitiveEdit@@QEAAXXZ equ <__imp_?ResetToolTip@CCapsLockSensitiveEdit@@QEAAXXZ>

externdef __imp_?ResetToolTip@CChangePINDialog@@QEAAXXZ:PPROC
?ResetToolTip@CChangePINDialog@@QEAAXXZ equ <__imp_?ResetToolTip@CChangePINDialog@@QEAAXXZ>

externdef __imp_?ResetToolTip@CInitializePinDlg@@QEAAXXZ:PPROC
?ResetToolTip@CInitializePinDlg@@QEAAXXZ equ <__imp_?ResetToolTip@CInitializePinDlg@@QEAAXXZ>

externdef __imp_?ResetToolTip@CResetCardDialog@@QEAAXXZ:PPROC
?ResetToolTip@CResetCardDialog@@QEAAXXZ equ <__imp_?ResetToolTip@CResetCardDialog@@QEAAXXZ>

externdef __imp_?ResizeDlg@CBaseDialog@@QEAAXHHH@Z:PPROC
?ResizeDlg@CBaseDialog@@QEAAXHHH@Z equ <__imp_?ResizeDlg@CBaseDialog@@QEAAXHHH@Z>

externdef __imp_?ResizeDlg@CResetCardDialogMain@@AEAAXHH@Z:PPROC
?ResizeDlg@CResetCardDialogMain@@AEAAXHH@Z equ <__imp_?ResizeDlg@CResetCardDialogMain@@AEAAXHH@Z>

externdef __imp_?SetAlphaPIN@ACPoliciesDlg@@AEAAX_N0@Z:PPROC
?SetAlphaPIN@ACPoliciesDlg@@AEAAX_N0@Z equ <__imp_?SetAlphaPIN@ACPoliciesDlg@@AEAAX_N0@Z>

externdef __imp_?SetAnimStatusToWaiting@CPopupAlert@@AEAAXXZ:PPROC
?SetAnimStatusToWaiting@CPopupAlert@@AEAAXXZ equ <__imp_?SetAnimStatusToWaiting@CPopupAlert@@AEAAXXZ>

externdef __imp_?SetChallenge@CResetCardDialog@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PPROC
?SetChallenge@CResetCardDialog@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z equ <__imp_?SetChallenge@CResetCardDialog@@QEAAXV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>

externdef __imp_?SetConfirmPIN@ACPoliciesDlg@@AEAAX_N@Z:PPROC
?SetConfirmPIN@ACPoliciesDlg@@AEAAX_N@Z equ <__imp_?SetConfirmPIN@ACPoliciesDlg@@AEAAX_N@Z>

externdef __imp_?SetMaxPINLen@ACPoliciesDlg@@AEAAXH_N0@Z:PPROC
?SetMaxPINLen@ACPoliciesDlg@@AEAAXH_N0@Z equ <__imp_?SetMaxPINLen@ACPoliciesDlg@@AEAAXH_N0@Z>

externdef __imp_?SetMessage@CPopupAlert@@QEAAXPEBD@Z:PPROC
?SetMessage@CPopupAlert@@QEAAXPEBD@Z equ <__imp_?SetMessage@CPopupAlert@@QEAAXPEBD@Z>

externdef __imp_?SetMinPINLen@ACPoliciesDlg@@AEAAXH_N0@Z:PPROC
?SetMinPINLen@ACPoliciesDlg@@AEAAXH_N0@Z equ <__imp_?SetMinPINLen@ACPoliciesDlg@@AEAAXH_N0@Z>

externdef __imp_?SetMode@CCapsLockSensitiveEdit@@QEAAX_N@Z:PPROC
?SetMode@CCapsLockSensitiveEdit@@QEAAX_N@Z equ <__imp_?SetMode@CCapsLockSensitiveEdit@@QEAAX_N@Z>

externdef __imp_?SetMustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAXH_J@Z:PPROC
?SetMustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAXH_J@Z equ <__imp_?SetMustDisplayCardExpiry@ACExpiryNotificationInfo@@QEAAXH_J@Z>

externdef __imp_?SetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAXH@Z:PPROC
?SetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAXH@Z equ <__imp_?SetNbDaysForNotificationDelay@ACExpiryNotificationInfo@@QEAAXH@Z>

externdef __imp_?SetPolicyIcon@ACPoliciesDlg@@AEAAXPEAVCWnd@@PEAUHICON__@@@Z:PPROC
?SetPolicyIcon@ACPoliciesDlg@@AEAAXPEAVCWnd@@PEAUHICON__@@@Z equ <__imp_?SetPolicyIcon@ACPoliciesDlg@@AEAAXPEAVCWnd@@PEAUHICON__@@@Z>

externdef __imp_?SetPreventSamePIN@ACPoliciesDlg@@AEAAX_N0@Z:PPROC
?SetPreventSamePIN@ACPoliciesDlg@@AEAAX_N0@Z equ <__imp_?SetPreventSamePIN@ACPoliciesDlg@@AEAAX_N0@Z>

externdef __imp_?SetReader@CPopupAlert@@QEAAXPEBD@Z:PPROC
?SetReader@CPopupAlert@@QEAAXPEBD@Z equ <__imp_?SetReader@CPopupAlert@@QEAAXPEBD@Z>

externdef __imp_?SetSkin@CPopupAlert@@QEAAHI_N0FFF@Z:PPROC
?SetSkin@CPopupAlert@@QEAAHI_N0FFF@Z equ <__imp_?SetSkin@CPopupAlert@@QEAAHI_N0FFF@Z>

externdef __imp_?SetSkin@CPopupAlert@@QEAAHPEBDFFF@Z:PPROC
?SetSkin@CPopupAlert@@QEAAHPEBDFFF@Z equ <__imp_?SetSkin@CPopupAlert@@QEAAHPEBDFFF@Z>

externdef __imp_?SetTextColor@CPopupAlert@@QEAAXKK@Z:PPROC
?SetTextColor@CPopupAlert@@QEAAXKK@Z equ <__imp_?SetTextColor@CPopupAlert@@QEAAXKK@Z>

externdef __imp_?SetTextFont@CPopupAlert@@QEAAXPEBDHHH@Z:PPROC
?SetTextFont@CPopupAlert@@QEAAXPEBDHHH@Z equ <__imp_?SetTextFont@CPopupAlert@@QEAAXPEBDHHH@Z>

externdef __imp_?SetTextRect@CPopupAlert@@QEAAXUtagRECT@@@Z:PPROC
?SetTextRect@CPopupAlert@@QEAAXUtagRECT@@@Z equ <__imp_?SetTextRect@CPopupAlert@@QEAAXUtagRECT@@@Z>

externdef __imp_?SetThreadRoutine@CPopupAlert@@QEAAXP6AKPEAX@Z@Z:PPROC
?SetThreadRoutine@CPopupAlert@@QEAAXP6AKPEAX@Z@Z equ <__imp_?SetThreadRoutine@CPopupAlert@@QEAAXP6AKPEAX@Z@Z>

externdef __imp_?SetWeakPIN@ACPoliciesDlg@@AEAAX_N0@Z:PPROC
?SetWeakPIN@ACPoliciesDlg@@AEAAX_N0@Z equ <__imp_?SetWeakPIN@ACPoliciesDlg@@AEAAX_N0@Z>

externdef __imp_?Show@CPopupAlert@@QEAAXXZ:PPROC
?Show@CPopupAlert@@QEAAXXZ equ <__imp_?Show@CPopupAlert@@QEAAXXZ>

externdef __imp_?StopDetectingRemoveEvent@CResetCardDialogMain@@IEAAXXZ:PPROC
?StopDetectingRemoveEvent@CResetCardDialogMain@@IEAAXXZ equ <__imp_?StopDetectingRemoveEvent@CResetCardDialogMain@@IEAAXXZ>

externdef __imp_?VerifyAndUpdateAllPolicies@CChangePINDialog@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z:PPROC
?VerifyAndUpdateAllPolicies@CChangePINDialog@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z equ <__imp_?VerifyAndUpdateAllPolicies@CChangePINDialog@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@@Z>

externdef __imp_?VerifyAndUpdatePolicies@ACPoliciesDlg@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@000@Z:PPROC
?VerifyAndUpdatePolicies@ACPoliciesDlg@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@000@Z equ <__imp_?VerifyAndUpdatePolicies@ACPoliciesDlg@@QEAA_NV?$CStringT@DV?$StrTraitMFC_DLL@DV?$ChTraitsCRT@D@ATL@@@@@ATL@@000@Z>

externdef __imp_?_GetBaseClass@ACPoliciesDlg@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@ACPoliciesDlg@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@ACPoliciesDlg@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CBaseDialog@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CBaseDialog@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CBaseDialog@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CCMLockedDlg@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CCMLockedDlg@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CCMLockedDlg@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CCapsLockSensitiveEdit@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CCapsLockSensitiveEdit@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CCapsLockSensitiveEdit@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CChangePINDialog@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CChangePINDialog@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CChangePINDialog@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CDisplayUCChild@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CDisplayUCChild@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CDisplayUCChild@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CDisplayUnlockCodeDlg@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CDisplayUnlockCodeDlg@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CDisplayUnlockCodeDlg@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CPopupAlert@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CPopupAlert@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CPopupAlert@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CResetCardDialog@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CResetCardDialog@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CResetCardDialog@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CResetCardDialogMain@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CResetCardDialogMain@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CResetCardDialogMain@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?_GetBaseClass@CUnlockInitToolDlg@@KAPEAUCRuntimeClass@@XZ:PPROC
?_GetBaseClass@CUnlockInitToolDlg@@KAPEAUCRuntimeClass@@XZ equ <__imp_?_GetBaseClass@CUnlockInitToolDlg@@KAPEAUCRuntimeClass@@XZ>

externdef __imp_?classACPoliciesDlg@ACPoliciesDlg@@2UCRuntimeClass@@B:PPROC
?classACPoliciesDlg@ACPoliciesDlg@@2UCRuntimeClass@@B equ <__imp_?classACPoliciesDlg@ACPoliciesDlg@@2UCRuntimeClass@@B>

externdef __imp_?classCBaseDialog@CBaseDialog@@2UCRuntimeClass@@B:PPROC
?classCBaseDialog@CBaseDialog@@2UCRuntimeClass@@B equ <__imp_?classCBaseDialog@CBaseDialog@@2UCRuntimeClass@@B>

externdef __imp_?classCCMLockedDlg@CCMLockedDlg@@2UCRuntimeClass@@B:PPROC
?classCCMLockedDlg@CCMLockedDlg@@2UCRuntimeClass@@B equ <__imp_?classCCMLockedDlg@CCMLockedDlg@@2UCRuntimeClass@@B>

externdef __imp_?classCCapsLockSensitiveEdit@CCapsLockSensitiveEdit@@2UCRuntimeClass@@B:PPROC
?classCCapsLockSensitiveEdit@CCapsLockSensitiveEdit@@2UCRuntimeClass@@B equ <__imp_?classCCapsLockSensitiveEdit@CCapsLockSensitiveEdit@@2UCRuntimeClass@@B>

externdef __imp_?classCChangePINDialog@CChangePINDialog@@2UCRuntimeClass@@B:PPROC
?classCChangePINDialog@CChangePINDialog@@2UCRuntimeClass@@B equ <__imp_?classCChangePINDialog@CChangePINDialog@@2UCRuntimeClass@@B>

externdef __imp_?classCDisplayUCChild@CDisplayUCChild@@2UCRuntimeClass@@B:PPROC
?classCDisplayUCChild@CDisplayUCChild@@2UCRuntimeClass@@B equ <__imp_?classCDisplayUCChild@CDisplayUCChild@@2UCRuntimeClass@@B>

externdef __imp_?classCDisplayUnlockCodeDlg@CDisplayUnlockCodeDlg@@2UCRuntimeClass@@B:PPROC
?classCDisplayUnlockCodeDlg@CDisplayUnlockCodeDlg@@2UCRuntimeClass@@B equ <__imp_?classCDisplayUnlockCodeDlg@CDisplayUnlockCodeDlg@@2UCRuntimeClass@@B>

externdef __imp_?classCPopupAlert@CPopupAlert@@2UCRuntimeClass@@B:PPROC
?classCPopupAlert@CPopupAlert@@2UCRuntimeClass@@B equ <__imp_?classCPopupAlert@CPopupAlert@@2UCRuntimeClass@@B>

externdef __imp_?classCResetCardDialog@CResetCardDialog@@2UCRuntimeClass@@B:PPROC
?classCResetCardDialog@CResetCardDialog@@2UCRuntimeClass@@B equ <__imp_?classCResetCardDialog@CResetCardDialog@@2UCRuntimeClass@@B>

externdef __imp_?classCResetCardDialogMain@CResetCardDialogMain@@2UCRuntimeClass@@B:PPROC
?classCResetCardDialogMain@CResetCardDialogMain@@2UCRuntimeClass@@B equ <__imp_?classCResetCardDialogMain@CResetCardDialogMain@@2UCRuntimeClass@@B>

externdef __imp_?classCUnlockInitToolDlg@CUnlockInitToolDlg@@2UCRuntimeClass@@B:PPROC
?classCUnlockInitToolDlg@CUnlockInitToolDlg@@2UCRuntimeClass@@B equ <__imp_?classCUnlockInitToolDlg@CUnlockInitToolDlg@@2UCRuntimeClass@@B>

externdef __imp_DisplayCardExpiryNotification:PPROC
DisplayCardExpiryNotification equ <__imp_DisplayCardExpiryNotification>

externdef __imp_DisplayLastPINTry:PPROC
DisplayLastPINTry equ <__imp_DisplayLastPINTry>

externdef __imp_DisplayUnlockCode:PPROC
DisplayUnlockCode equ <__imp_DisplayUnlockCode>

externdef __imp_FreeGetPinBuffer:PPROC
FreeGetPinBuffer equ <__imp_FreeGetPinBuffer>

externdef __imp_GetChangePINInfoFromUser:PPROC
GetChangePINInfoFromUser equ <__imp_GetChangePINInfoFromUser>

externdef __imp_GetErrorString:PPROC
GetErrorString equ <__imp_GetErrorString>

externdef __imp_GetPINFromUser:PPROC
GetPINFromUser equ <__imp_GetPINFromUser>

externdef __imp_InitGUIDll:PPROC
InitGUIDll equ <__imp_InitGUIDll>

externdef __imp_SetPinPromptString:PPROC
SetPinPromptString equ <__imp_SetPinPromptString>

externdef __imp_ShowAbout:PPROC
ShowAbout equ <__imp_ShowAbout>
