externdef __imp_UPSCancelWait:PPROC
UPSCancelWait equ <__imp_UPSCancelWait>

externdef __imp_UPSGetState:PPROC
UPSGetState equ <__imp_UPSGetState>

externdef __imp_UPSInit:PPROC
UPSInit equ <__imp_UPSInit>

externdef __imp_UPSStop:PPROC
UPSStop equ <__imp_UPSStop>

externdef __imp_UPSTurnOff:PPROC
UPSTurnOff equ <__imp_UPSTurnOff>

externdef __imp_UPSWaitForStateChange:PPROC
UPSWaitForStateChange equ <__imp_UPSWaitForStateChange>
