externdef __imp_DefaultFilePath:PPROC
DefaultFilePath equ <__imp_DefaultFilePath>

externdef __imp_DlgSection:PPROC
DlgSection equ <__imp_DlgSection>

externdef __imp_InitRegData:PPROC
InitRegData equ <__imp_InitRegData>

externdef __imp_OFileName:PPROC
OFileName equ <__imp_OFileName>

externdef __imp_OpenFileDialog:PPROC
OpenFileDialog equ <__imp_OpenFileDialog>

externdef __imp_RegClass:PPROC
RegClass equ <__imp_RegClass>

externdef __imp_RegClassEx:PPROC
RegClassEx equ <__imp_RegClassEx>

externdef __imp_RegSection:PPROC
RegSection equ <__imp_RegSection>

externdef __imp_SaveFileDialog:PPROC
SaveFileDialog equ <__imp_SaveFileDialog>

externdef __imp_SetStdClass:PPROC
SetStdClass equ <__imp_SetStdClass>

externdef __imp_StdClass:PPROC
StdClass equ <__imp_StdClass>

externdef __imp_StdWndProc:PPROC
StdWndProc equ <__imp_StdWndProc>
