externdef __imp_GsDrvEnableDriver:PPROC
GsDrvEnableDriver equ <__imp_GsDrvEnableDriver>

externdef __imp_VPEAccessCallback:PPROC
VPEAccessCallback equ <__imp_VPEAccessCallback>

externdef __imp_bD3dHslSetDriverCallsEx:PPROC
bD3dHslSetDriverCallsEx equ <__imp_bD3dHslSetDriverCallsEx>

externdef __imp_bDD4DISPDescribeSurface:PPROC
bDD4DISPDescribeSurface equ <__imp_bDD4DISPDescribeSurface>

externdef __imp_bDD4DISPDescribeSurface_WA:PPROC
bDD4DISPDescribeSurface_WA equ <__imp_bDD4DISPDescribeSurface_WA>
  IFNDEF __UNICODE__
    bDD4DISPDescribeSurface_W equ <__imp_bDD4DISPDescribeSurface_WA>
  ENDIF

externdef __imp_bDD4DISPEnableDD:PPROC
bDD4DISPEnableDD equ <__imp_bDD4DISPEnableDD>

externdef __imp_bDD4DISPInitDD:PPROC
bDD4DISPInitDD equ <__imp_bDD4DISPInitDD>

externdef __imp_bDdHslQueryCIInfo:PPROC
bDdHslQueryCIInfo equ <__imp_bDdHslQueryCIInfo>

externdef __imp_bDdHslQueryRegistryValue:PPROC
bDdHslQueryRegistryValue equ <__imp_bDdHslQueryRegistryValue>

externdef __imp_bDdHslSharedMemFree:PPROC
bDdHslSharedMemFree equ <__imp_bDdHslSharedMemFree>

externdef __imp_bDdHslVideoMemoryFree:PPROC
bDdHslVideoMemoryFree equ <__imp_bDdHslVideoMemoryFree>

externdef __imp_bGDI3DQueryDesktopCompositionSupport:PPROC
bGDI3DQueryDesktopCompositionSupport equ <__imp_bGDI3DQueryDesktopCompositionSupport>

externdef __imp_bGDI3DQueryInfo:PPROC
bGDI3DQueryInfo equ <__imp_bGDI3DQueryInfo>

externdef __imp_dDdHslEscape:PPROC
dDdHslEscape equ <__imp_dDdHslEscape>

externdef __imp_pDD4DISPDeriveSurface:PPROC
pDD4DISPDeriveSurface equ <__imp_pDD4DISPDeriveSurface>

externdef __imp_pDdHslQueryDeviceObject:PPROC
pDdHslQueryDeviceObject equ <__imp_pDdHslQueryDeviceObject>

externdef __imp_pDdHslSharedMemCalloc:PPROC
pDdHslSharedMemCalloc equ <__imp_pDdHslSharedMemCalloc>

externdef __imp_vD3dHslSetDriverCalls:PPROC
vD3dHslSetDriverCalls equ <__imp_vD3dHslSetDriverCalls>

externdef __imp_vDD4DISPDisableDD:PPROC
vDD4DISPDisableDD equ <__imp_vDD4DISPDisableDD>

externdef __imp_vDD4DISPExitDD:PPROC
vDD4DISPExitDD equ <__imp_vDD4DISPExitDD>

externdef __imp_vDD4DISPFlush3D:PPROC
vDD4DISPFlush3D equ <__imp_vDD4DISPFlush3D>

externdef __imp_vDD4DISPHandlePanCallback:PPROC
vDD4DISPHandlePanCallback equ <__imp_vDD4DISPHandlePanCallback>

externdef __imp_vDD4DISPResetDxObj:PPROC
vDD4DISPResetDxObj equ <__imp_vDD4DISPResetDxObj>

externdef __imp_vDD4DISPSetDDCallBacks:PPROC
vDD4DISPSetDDCallBacks equ <__imp_vDD4DISPSetDDCallBacks>

externdef __imp_vDD4DISPSurfaceNotify:PPROC
vDD4DISPSurfaceNotify equ <__imp_vDD4DISPSurfaceNotify>

externdef __imp_vDD4DispGDIPrimaryAccess:PPROC
vDD4DispGDIPrimaryAccess equ <__imp_vDD4DispGDIPrimaryAccess>

externdef __imp_vDVDHSLUpdatePDEV:PPROC
vDVDHSLUpdatePDEV equ <__imp_vDVDHSLUpdatePDEV>

externdef __imp_vDdHslVideoMemoryAlloc:PPROC
vDdHslVideoMemoryAlloc equ <__imp_vDdHslVideoMemoryAlloc>

externdef __imp_vGDI3DAATextOut:PPROC
vGDI3DAATextOut equ <__imp_vGDI3DAATextOut>

externdef __imp_vGDI3DAATextOut_WA:PPROC
vGDI3DAATextOut_WA equ <__imp_vGDI3DAATextOut_WA>
  IFNDEF __UNICODE__
    vGDI3DAATextOut_W equ <__imp_vGDI3DAATextOut_WA>
  ENDIF

externdef __imp_vGDI3DAlphaBlt:PPROC
vGDI3DAlphaBlt equ <__imp_vGDI3DAlphaBlt>

externdef __imp_vGDI3DAlphaBlt_WA:PPROC
vGDI3DAlphaBlt_WA equ <__imp_vGDI3DAlphaBlt_WA>
  IFNDEF __UNICODE__
    vGDI3DAlphaBlt_W equ <__imp_vGDI3DAlphaBlt_WA>
  ENDIF

externdef __imp_vGDI3DDesktopComposition_WA:PPROC
vGDI3DDesktopComposition_WA equ <__imp_vGDI3DDesktopComposition_WA>
  IFNDEF __UNICODE__
    vGDI3DDesktopComposition_W equ <__imp_vGDI3DDesktopComposition_WA>
  ENDIF

externdef __imp_vGDI3DGradientFill:PPROC
vGDI3DGradientFill equ <__imp_vGDI3DGradientFill>

externdef __imp_vGDI3DGradientFill_WA:PPROC
vGDI3DGradientFill_WA equ <__imp_vGDI3DGradientFill_WA>
  IFNDEF __UNICODE__
    vGDI3DGradientFill_W equ <__imp_vGDI3DGradientFill_WA>
  ENDIF

externdef __imp_vGDI3DSolidFill:PPROC
vGDI3DSolidFill equ <__imp_vGDI3DSolidFill>

externdef __imp_vGDI3DSolidFill_WA:PPROC
vGDI3DSolidFill_WA equ <__imp_vGDI3DSolidFill_WA>
  IFNDEF __UNICODE__
    vGDI3DSolidFill_W equ <__imp_vGDI3DSolidFill_WA>
  ENDIF

externdef __imp_vGDI3DStretchBlt:PPROC
vGDI3DStretchBlt equ <__imp_vGDI3DStretchBlt>

externdef __imp_vGDI3DStretchBlt_WA:PPROC
vGDI3DStretchBlt_WA equ <__imp_vGDI3DStretchBlt_WA>
  IFNDEF __UNICODE__
    vGDI3DStretchBlt_W equ <__imp_vGDI3DStretchBlt_WA>
  ENDIF
