externdef __imp_calclAssembleObject:PPROC
calclAssembleObject equ <__imp_calclAssembleObject>

externdef __imp_calclCompile:PPROC
calclCompile equ <__imp_calclCompile>

externdef __imp_calclDisassembleImage:PPROC
calclDisassembleImage equ <__imp_calclDisassembleImage>

externdef __imp_calclDisassembleObject:PPROC
calclDisassembleObject equ <__imp_calclDisassembleObject>

externdef __imp_calclExtGetProc:PPROC
calclExtGetProc equ <__imp_calclExtGetProc>

externdef __imp_calclExtSupported:PPROC
calclExtSupported equ <__imp_calclExtSupported>

externdef __imp_calclFreeImage:PPROC
calclFreeImage equ <__imp_calclFreeImage>

externdef __imp_calclFreeObject:PPROC
calclFreeObject equ <__imp_calclFreeObject>

externdef __imp_calclGetErrorString:PPROC
calclGetErrorString equ <__imp_calclGetErrorString>

externdef __imp_calclGetVersion:PPROC
calclGetVersion equ <__imp_calclGetVersion>

externdef __imp_calclImageGetSize:PPROC
calclImageGetSize equ <__imp_calclImageGetSize>

externdef __imp_calclImageWrite:PPROC
calclImageWrite equ <__imp_calclImageWrite>

externdef __imp_calclLink:PPROC
calclLink equ <__imp_calclLink>
