externdef __imp_calCtxCreate:PPROC
calCtxCreate equ <__imp_calCtxCreate>

externdef __imp_calCtxDestroy:PPROC
calCtxDestroy equ <__imp_calCtxDestroy>

externdef __imp_calCtxFlush:PPROC
calCtxFlush equ <__imp_calCtxFlush>

externdef __imp_calCtxGetMem:PPROC
calCtxGetMem equ <__imp_calCtxGetMem>

externdef __imp_calCtxIsEventDone:PPROC
calCtxIsEventDone equ <__imp_calCtxIsEventDone>

externdef __imp_calCtxReleaseMem:PPROC
calCtxReleaseMem equ <__imp_calCtxReleaseMem>

externdef __imp_calCtxRunProgram:PPROC
calCtxRunProgram equ <__imp_calCtxRunProgram>

externdef __imp_calCtxRunProgramGrid:PPROC
calCtxRunProgramGrid equ <__imp_calCtxRunProgramGrid>

externdef __imp_calCtxRunProgramGridArray:PPROC
calCtxRunProgramGridArray equ <__imp_calCtxRunProgramGridArray>

externdef __imp_calCtxSetMem:PPROC
calCtxSetMem equ <__imp_calCtxSetMem>

externdef __imp_calDeviceClose:PPROC
calDeviceClose equ <__imp_calDeviceClose>

externdef __imp_calDeviceGetAttribs:PPROC
calDeviceGetAttribs equ <__imp_calDeviceGetAttribs>

externdef __imp_calDeviceGetCount:PPROC
calDeviceGetCount equ <__imp_calDeviceGetCount>

externdef __imp_calDeviceGetInfo:PPROC
calDeviceGetInfo equ <__imp_calDeviceGetInfo>

externdef __imp_calDeviceGetStatus:PPROC
calDeviceGetStatus equ <__imp_calDeviceGetStatus>

externdef __imp_calDeviceOpen:PPROC
calDeviceOpen equ <__imp_calDeviceOpen>

externdef __imp_calExtGetProc:PPROC
calExtGetProc equ <__imp_calExtGetProc>

externdef __imp_calExtGetVersion:PPROC
calExtGetVersion equ <__imp_calExtGetVersion>

externdef __imp_calExtSupported:PPROC
calExtSupported equ <__imp_calExtSupported>

externdef __imp_calGetErrorString:PPROC
calGetErrorString equ <__imp_calGetErrorString>

externdef __imp_calGetVersion:PPROC
calGetVersion equ <__imp_calGetVersion>

externdef __imp_calImageFree:PPROC
calImageFree equ <__imp_calImageFree>

externdef __imp_calImageRead:PPROC
calImageRead equ <__imp_calImageRead>

externdef __imp_calInit:PPROC
calInit equ <__imp_calInit>

externdef __imp_calMemCopy:PPROC
calMemCopy equ <__imp_calMemCopy>

externdef __imp_calModuleGetEntry:PPROC
calModuleGetEntry equ <__imp_calModuleGetEntry>

externdef __imp_calModuleGetFuncInfo:PPROC
calModuleGetFuncInfo equ <__imp_calModuleGetFuncInfo>

externdef __imp_calModuleGetName:PPROC
calModuleGetName equ <__imp_calModuleGetName>

externdef __imp_calModuleLoad:PPROC
calModuleLoad equ <__imp_calModuleLoad>

externdef __imp_calModuleUnload:PPROC
calModuleUnload equ <__imp_calModuleUnload>

externdef __imp_calResAllocLocal1D:PPROC
calResAllocLocal1D equ <__imp_calResAllocLocal1D>

externdef __imp_calResAllocLocal2D:PPROC
calResAllocLocal2D equ <__imp_calResAllocLocal2D>

externdef __imp_calResAllocRemote1D:PPROC
calResAllocRemote1D equ <__imp_calResAllocRemote1D>

externdef __imp_calResAllocRemote2D:PPROC
calResAllocRemote2D equ <__imp_calResAllocRemote2D>

externdef __imp_calResFree:PPROC
calResFree equ <__imp_calResFree>

externdef __imp_calResMap:PPROC
calResMap equ <__imp_calResMap>

externdef __imp_calResUnmap:PPROC
calResUnmap equ <__imp_calResUnmap>

externdef __imp_calShutdown:PPROC
calShutdown equ <__imp_calShutdown>
