externdef __imp_bDestroyR0ORCA:PPROC
bDestroyR0ORCA equ <__imp_bDestroyR0ORCA>
  IFNDEF __UNICODE__
    bDestroyR0ORC equ <__imp_bDestroyR0ORCA>
  ENDIF

externdef __imp_bDisableR0ORCA:PPROC
bDisableR0ORCA equ <__imp_bDisableR0ORCA>
  IFNDEF __UNICODE__
    bDisableR0ORC equ <__imp_bDisableR0ORCA>
  ENDIF

externdef __imp_bOriginNotifyR0ORCA:PPROC
bOriginNotifyR0ORCA equ <__imp_bOriginNotifyR0ORCA>
  IFNDEF __UNICODE__
    bOriginNotifyR0ORC equ <__imp_bOriginNotifyR0ORCA>
  ENDIF

externdef __imp_bR0ORCACreateWndObj:PPROC
bR0ORCACreateWndObj equ <__imp_bR0ORCACreateWndObj>

externdef __imp_bR0ORCAInitialize:PPROC
bR0ORCAInitialize equ <__imp_bR0ORCAInitialize>

externdef __imp_bR0ORCASetDriverCallsEx:PPROC
bR0ORCASetDriverCallsEx equ <__imp_bR0ORCASetDriverCallsEx>

externdef __imp_ulR0ORCAEscape:PPROC
ulR0ORCAEscape equ <__imp_ulR0ORCAEscape>
