externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_DrvCopyContext:PPROC
DrvCopyContext equ <__imp_DrvCopyContext>

externdef __imp_DrvCreateContext:PPROC
DrvCreateContext equ <__imp_DrvCreateContext>

externdef __imp_DrvCreateLayerContext:PPROC
DrvCreateLayerContext equ <__imp_DrvCreateLayerContext>

externdef __imp_DrvDeleteContext:PPROC
DrvDeleteContext equ <__imp_DrvDeleteContext>

externdef __imp_DrvDescribeLayerPlane:PPROC
DrvDescribeLayerPlane equ <__imp_DrvDescribeLayerPlane>

externdef __imp_DrvDescribePixelFormat:PPROC
DrvDescribePixelFormat equ <__imp_DrvDescribePixelFormat>

externdef __imp_DrvGetLayerPaletteEntries:PPROC
DrvGetLayerPaletteEntries equ <__imp_DrvGetLayerPaletteEntries>

externdef __imp_DrvGetProcAddress:PPROC
DrvGetProcAddress equ <__imp_DrvGetProcAddress>

externdef __imp_DrvRealizeLayerPalette:PPROC
DrvRealizeLayerPalette equ <__imp_DrvRealizeLayerPalette>

externdef __imp_DrvReleaseContext:PPROC
DrvReleaseContext equ <__imp_DrvReleaseContext>

externdef __imp_DrvSetContext:PPROC
DrvSetContext equ <__imp_DrvSetContext>

externdef __imp_DrvSetLayerPaletteEntries:PPROC
DrvSetLayerPaletteEntries equ <__imp_DrvSetLayerPaletteEntries>

externdef __imp_DrvSetPixelFormat:PPROC
DrvSetPixelFormat equ <__imp_DrvSetPixelFormat>

externdef __imp_DrvShareLists:PPROC
DrvShareLists equ <__imp_DrvShareLists>

externdef __imp_DrvSwapBuffers:PPROC
DrvSwapBuffers equ <__imp_DrvSwapBuffers>

externdef __imp_DrvSwapLayerBuffers:PPROC
DrvSwapLayerBuffers equ <__imp_DrvSwapLayerBuffers>

externdef __imp_DrvValidateVersion:PPROC
DrvValidateVersion equ <__imp_DrvValidateVersion>

externdef __imp_atiPPHSN:PPROC
atiPPHSN equ <__imp_atiPPHSN>

externdef __imp_atiPS:PPROC
atiPS equ <__imp_atiPS>

externdef __imp_atiQD:PPROC
atiQD equ <__imp_atiQD>

externdef __imp_atiQDS:PPROC
atiQDS equ <__imp_atiQDS>
