externdef __imp_AzAddPropertyItem:PPROC
AzAddPropertyItem equ <__imp_AzAddPropertyItem>

externdef __imp_AzApplicationClose:PPROC
AzApplicationClose equ <__imp_AzApplicationClose>

externdef __imp_AzApplicationCreate:PPROC
AzApplicationCreate equ <__imp_AzApplicationCreate>

externdef __imp_AzApplicationDelete:PPROC
AzApplicationDelete equ <__imp_AzApplicationDelete>

externdef __imp_AzApplicationEnum:PPROC
AzApplicationEnum equ <__imp_AzApplicationEnum>

externdef __imp_AzApplicationOpen:PPROC
AzApplicationOpen equ <__imp_AzApplicationOpen>

externdef __imp_AzAuthorizationStoreDelete:PPROC
AzAuthorizationStoreDelete equ <__imp_AzAuthorizationStoreDelete>

externdef __imp_AzCloseHandle:PPROC
AzCloseHandle equ <__imp_AzCloseHandle>

externdef __imp_AzContextAccessCheck:PPROC
AzContextAccessCheck equ <__imp_AzContextAccessCheck>

externdef __imp_AzContextGetAssignedScopesPage:PPROC
AzContextGetAssignedScopesPage equ <__imp_AzContextGetAssignedScopesPage>

externdef __imp_AzContextGetRoles:PPROC
AzContextGetRoles equ <__imp_AzContextGetRoles>

externdef __imp_AzFreeMemory:PPROC
AzFreeMemory equ <__imp_AzFreeMemory>

externdef __imp_AzGetProperty:PPROC
AzGetProperty equ <__imp_AzGetProperty>

externdef __imp_AzGroupCreate:PPROC
AzGroupCreate equ <__imp_AzGroupCreate>

externdef __imp_AzGroupDelete:PPROC
AzGroupDelete equ <__imp_AzGroupDelete>

externdef __imp_AzGroupEnum:PPROC
AzGroupEnum equ <__imp_AzGroupEnum>

externdef __imp_AzGroupOpen:PPROC
AzGroupOpen equ <__imp_AzGroupOpen>

externdef __imp_AzInitialize:PPROC
AzInitialize equ <__imp_AzInitialize>

externdef __imp_AzInitializeContextFromName:PPROC
AzInitializeContextFromName equ <__imp_AzInitializeContextFromName>

externdef __imp_AzInitializeContextFromToken:PPROC
AzInitializeContextFromToken equ <__imp_AzInitializeContextFromToken>

externdef __imp_AzOperationCreate:PPROC
AzOperationCreate equ <__imp_AzOperationCreate>

externdef __imp_AzOperationDelete:PPROC
AzOperationDelete equ <__imp_AzOperationDelete>

externdef __imp_AzOperationEnum:PPROC
AzOperationEnum equ <__imp_AzOperationEnum>

externdef __imp_AzOperationOpen:PPROC
AzOperationOpen equ <__imp_AzOperationOpen>

externdef __imp_AzRemovePropertyItem:PPROC
AzRemovePropertyItem equ <__imp_AzRemovePropertyItem>

externdef __imp_AzRoleCreate:PPROC
AzRoleCreate equ <__imp_AzRoleCreate>

externdef __imp_AzRoleDelete:PPROC
AzRoleDelete equ <__imp_AzRoleDelete>

externdef __imp_AzRoleEnum:PPROC
AzRoleEnum equ <__imp_AzRoleEnum>

externdef __imp_AzRoleOpen:PPROC
AzRoleOpen equ <__imp_AzRoleOpen>

externdef __imp_AzScopeCreate:PPROC
AzScopeCreate equ <__imp_AzScopeCreate>

externdef __imp_AzScopeDelete:PPROC
AzScopeDelete equ <__imp_AzScopeDelete>

externdef __imp_AzScopeEnum:PPROC
AzScopeEnum equ <__imp_AzScopeEnum>

externdef __imp_AzScopeOpen:PPROC
AzScopeOpen equ <__imp_AzScopeOpen>

externdef __imp_AzSetProperty:PPROC
AzSetProperty equ <__imp_AzSetProperty>

externdef __imp_AzSubmit:PPROC
AzSubmit equ <__imp_AzSubmit>

externdef __imp_AzTaskCreate:PPROC
AzTaskCreate equ <__imp_AzTaskCreate>

externdef __imp_AzTaskDelete:PPROC
AzTaskDelete equ <__imp_AzTaskDelete>

externdef __imp_AzTaskEnum:PPROC
AzTaskEnum equ <__imp_AzTaskEnum>

externdef __imp_AzTaskOpen:PPROC
AzTaskOpen equ <__imp_AzTaskOpen>

externdef __imp_AzUpdateCache:PPROC
AzUpdateCache equ <__imp_AzUpdateCache>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
