externdef __imp_BatMeterCapabilities:PPROC
BatMeterCapabilities equ <__imp_BatMeterCapabilities>

externdef __imp_CreateBatMeter:PPROC
CreateBatMeter equ <__imp_CreateBatMeter>

externdef __imp_DestroyBatMeter:PPROC
DestroyBatMeter equ <__imp_DestroyBatMeter>

externdef __imp_PowerCapabilities:PPROC
PowerCapabilities equ <__imp_PowerCapabilities>

externdef __imp_UpdateBatMeter:PPROC
UpdateBatMeter equ <__imp_UpdateBatMeter>
