externdef __imp_VidBitBlt:PPROC
VidBitBlt equ <__imp_VidBitBlt>

externdef __imp_VidBufferToScreenBlt:PPROC
VidBufferToScreenBlt equ <__imp_VidBufferToScreenBlt>

externdef __imp_VidCleanUp:PPROC
VidCleanUp equ <__imp_VidCleanUp>

externdef __imp_VidDisplayString:PPROC
VidDisplayString equ <__imp_VidDisplayString>

externdef __imp_VidDisplayStringXY:PPROC
VidDisplayStringXY equ <__imp_VidDisplayStringXY>

externdef __imp_VidInitialize:PPROC
VidInitialize equ <__imp_VidInitialize>

externdef __imp_VidResetDisplay:PPROC
VidResetDisplay equ <__imp_VidResetDisplay>

externdef __imp_VidScreenToBufferBlt:PPROC
VidScreenToBufferBlt equ <__imp_VidScreenToBufferBlt>

externdef __imp_VidSetScrollRegion:PPROC
VidSetScrollRegion equ <__imp_VidSetScrollRegion>

externdef __imp_VidSetTextColor:PPROC
VidSetTextColor equ <__imp_VidSetTextColor>

externdef __imp_VidSolidColorFill:PPROC
VidSolidColorFill equ <__imp_VidSolidColorFill>
