externdef __imp_DeleteExtractedFiles:PPROC
DeleteExtractedFiles equ <__imp_DeleteExtractedFiles>

externdef __imp_DllGetVersion:PPROC
DllGetVersion equ <__imp_DllGetVersion>

externdef __imp_Extract:PPROC
Extract equ <__imp_Extract>

externdef __imp_FCIAddFile:PPROC
FCIAddFile equ <__imp_FCIAddFile>

externdef __imp_FCICreate:PPROC
FCICreate equ <__imp_FCICreate>

externdef __imp_FCIDestroy:PPROC
FCIDestroy equ <__imp_FCIDestroy>

externdef __imp_FCIFlushCabinet:PPROC
FCIFlushCabinet equ <__imp_FCIFlushCabinet>

externdef __imp_FCIFlushFolder:PPROC
FCIFlushFolder equ <__imp_FCIFlushFolder>

externdef __imp_FDICopy:PPROC
FDICopy equ <__imp_FDICopy>

externdef __imp_FDICreate:PPROC
FDICreate equ <__imp_FDICreate>

externdef __imp_FDIDestroy:PPROC
FDIDestroy equ <__imp_FDIDestroy>

externdef __imp_FDIIsCabinet:PPROC
FDIIsCabinet equ <__imp_FDIIsCabinet>

externdef __imp_FDITruncateCabinet:PPROC
FDITruncateCabinet equ <__imp_FDITruncateCabinet>

externdef __imp_GetDllVersion:PPROC
GetDllVersion equ <__imp_GetDllVersion>

externdef __imp_cabinet_ordinal15:PPROC
cabinet_ordinal15 equ <__imp_cabinet_ordinal15>

externdef __imp_cabinet_ordinal16:PPROC
cabinet_ordinal16 equ <__imp_cabinet_ordinal16>

externdef __imp_cabinet_ordinal17:PPROC
cabinet_ordinal17 equ <__imp_cabinet_ordinal17>

externdef __imp_cabinet_ordinal18:PPROC
cabinet_ordinal18 equ <__imp_cabinet_ordinal18>

externdef __imp_cabinet_ordinal19:PPROC
cabinet_ordinal19 equ <__imp_cabinet_ordinal19>

externdef __imp_cabinet_ordinal5:PPROC
cabinet_ordinal5 equ <__imp_cabinet_ordinal5>

externdef __imp_cabinet_ordinal6:PPROC
cabinet_ordinal6 equ <__imp_cabinet_ordinal6>

externdef __imp_cabinet_ordinal7:PPROC
cabinet_ordinal7 equ <__imp_cabinet_ordinal7>

externdef __imp_cabinet_ordinal8:PPROC
cabinet_ordinal8 equ <__imp_cabinet_ordinal8>

externdef __imp_cabinet_ordinal9:PPROC
cabinet_ordinal9 equ <__imp_cabinet_ordinal9>
