externdef __imp_Factorial:PPROC
Factorial equ <__imp_Factorial>

externdef __imp_GetEngineVersion:PPROC
GetEngineVersion equ <__imp_GetEngineVersion>

externdef __imp_ShortDivUx:PPROC
ShortDivUx equ <__imp_ShortDivUx>

externdef __imp_ShortMulUx:PPROC
ShortMulUx equ <__imp_ShortMulUx>

externdef __imp_ShortRDiv:PPROC
ShortRDiv equ <__imp_ShortRDiv>

externdef __imp_ShortRMul:PPROC
ShortRMul equ <__imp_ShortRMul>

externdef __imp_ShortUintPow:PPROC
ShortUintPow equ <__imp_ShortUintPow>

externdef __imp_Unfactorial:PPROC
Unfactorial equ <__imp_Unfactorial>

externdef __imp__ultoa:PPROC
_ultoa equ <__imp__ultoa>

externdef __imp_atoiX:PPROC
atoiX equ <__imp_atoiX>

externdef __imp_atorX:PPROC
atorX equ <__imp_atorX>

externdef __imp_buffuild:PPROC
buffuild equ <__imp_buffuild>

externdef __imp_fmtator:PPROC
fmtator equ <__imp_fmtator>

externdef __imp_fmtitoax:PPROC
fmtitoax equ <__imp_fmtitoax>

externdef __imp_fmtrtoa:PPROC
fmtrtoa equ <__imp_fmtrtoa>

externdef __imp_ild:PPROC
ild equ <__imp_ild>

externdef __imp_init_calc:PPROC
init_calc equ <__imp_init_calc>

externdef __imp_int_add:PPROC
int_add equ <__imp_int_add>

externdef __imp_int_div:PPROC
int_div equ <__imp_int_div>

externdef __imp_int_mul:PPROC
int_mul equ <__imp_int_mul>

externdef __imp_int_sub:PPROC
int_sub equ <__imp_int_sub>

externdef __imp_itoaX:PPROC
itoaX equ <__imp_itoaX>

externdef __imp_off_calc:PPROC
off_calc equ <__imp_off_calc>

externdef __imp_r2st:PPROC
r2st equ <__imp_r2st>

externdef __imp_radd:PPROC
radd equ <__imp_radd>

externdef __imp_ralloc:PPROC
ralloc equ <__imp_ralloc>

externdef __imp_rcos:PPROC
rcos equ <__imp_rcos>

externdef __imp_rdiv:PPROC
rdiv equ <__imp_rdiv>

externdef __imp_recalcpi:PPROC
recalcpi equ <__imp_recalcpi>

externdef __imp_rfree:PPROC
rfree equ <__imp_rfree>

externdef __imp_rmove:PPROC
rmove equ <__imp_rmove>

externdef __imp_rmul:PPROC
rmul equ <__imp_rmul>

externdef __imp_rshl1:PPROC
rshl1 equ <__imp_rshl1>

externdef __imp_rshr1:PPROC
rshr1 equ <__imp_rshr1>

externdef __imp_rsin:PPROC
rsin equ <__imp_rsin>

externdef __imp_rsqrt:PPROC
rsqrt equ <__imp_rsqrt>

externdef __imp_rsub:PPROC
rsub equ <__imp_rsub>

externdef __imp_rtest:PPROC
rtest equ <__imp_rtest>

externdef __imp_rtoaX:PPROC
rtoaX equ <__imp_rtoaX>

externdef __imp_st2r:PPROC
st2r equ <__imp_st2r>

externdef __imp_uild:PPROC
uild equ <__imp_uild>

externdef __imp_uint_add:PPROC
uint_add equ <__imp_uint_add>

externdef __imp_uint_cmp:PPROC
uint_cmp equ <__imp_uint_cmp>

externdef __imp_uint_div:PPROC
uint_div equ <__imp_uint_div>

externdef __imp_uint_mul:PPROC
uint_mul equ <__imp_uint_mul>

externdef __imp_uint_sub:PPROC
uint_sub equ <__imp_uint_sub>

externdef __imp_ureal_add:PPROC
ureal_add equ <__imp_ureal_add>

externdef __imp_ureal_cmp:PPROC
ureal_cmp equ <__imp_ureal_cmp>

externdef __imp_ureal_sub:PPROC
ureal_sub equ <__imp_ureal_sub>
