externdef __imp_?CancelWriteICR@@YAJPEAPEAUIComponentRecords@@@Z:PPROC
?CancelWriteICR@@YAJPEAPEAUIComponentRecords@@@Z equ <__imp_?CancelWriteICR@@YAJPEAPEAUIComponentRecords@@@Z>

externdef __imp_?GetReadICR@@YAJHPEAPEAUIComponentRecords@@@Z:PPROC
?GetReadICR@@YAJHPEAPEAUIComponentRecords@@@Z equ <__imp_?GetReadICR@@YAJHPEAPEAUIComponentRecords@@@Z>

externdef __imp_?GetWriteICR@@YAJPEAPEAUIComponentRecords@@@Z:PPROC
?GetWriteICR@@YAJPEAPEAUIComponentRecords@@@Z equ <__imp_?GetWriteICR@@YAJPEAPEAUIComponentRecords@@@Z>

externdef __imp_?ReleaseReadICR@@YAXPEAPEAUIComponentRecords@@@Z:PPROC
?ReleaseReadICR@@YAXPEAPEAUIComponentRecords@@@Z equ <__imp_?ReleaseReadICR@@YAXPEAPEAUIComponentRecords@@@Z>

externdef __imp_?SaveWriteICR@@YAJPEAPEAUIComponentRecords@@@Z:PPROC
?SaveWriteICR@@YAJPEAPEAUIComponentRecords@@@Z equ <__imp_?SaveWriteICR@@YAJPEAPEAUIComponentRecords@@@Z>

externdef __imp_CreateComponentLibraryTS:PPROC
CreateComponentLibraryTS equ <__imp_CreateComponentLibraryTS>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_GetCatalogCRMClerk:PPROC
GetCatalogCRMClerk equ <__imp_GetCatalogCRMClerk>

externdef __imp_OpenComponentLibraryTS:PPROC
OpenComponentLibraryTS equ <__imp_OpenComponentLibraryTS>
