externdef __imp_??0CComPlusComponent@@QEAA@AEBV0@@Z:PPROC
??0CComPlusComponent@@QEAA@AEBV0@@Z equ <__imp_??0CComPlusComponent@@QEAA@AEBV0@@Z>

externdef __imp_??0CComPlusInterface@@QEAA@AEBV0@@Z:PPROC
??0CComPlusInterface@@QEAA@AEBV0@@Z equ <__imp_??0CComPlusInterface@@QEAA@AEBV0@@Z>

externdef __imp_??0CComPlusMethod@@QEAA@AEBV0@@Z:PPROC
??0CComPlusMethod@@QEAA@AEBV0@@Z equ <__imp_??0CComPlusMethod@@QEAA@AEBV0@@Z>

externdef __imp_??0CComPlusObject@@QEAA@AEBV0@@Z:PPROC
??0CComPlusObject@@QEAA@AEBV0@@Z equ <__imp_??0CComPlusObject@@QEAA@AEBV0@@Z>

externdef __imp_??1CComPlusComponent@@UEAA@XZ:PPROC
??1CComPlusComponent@@UEAA@XZ equ <__imp_??1CComPlusComponent@@UEAA@XZ>

externdef __imp_??1CComPlusInterface@@UEAA@XZ:PPROC
??1CComPlusInterface@@UEAA@XZ equ <__imp_??1CComPlusInterface@@UEAA@XZ>

externdef __imp_??4CComPlusComponent@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CComPlusComponent@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CComPlusComponent@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CComPlusInterface@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CComPlusInterface@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CComPlusInterface@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CComPlusMethod@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CComPlusMethod@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CComPlusMethod@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CComPlusObject@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CComPlusObject@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CComPlusObject@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CComPlusTypelib@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CComPlusTypelib@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CComPlusTypelib@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_7CComPlusComponent@@6B@:PPROC
??_7CComPlusComponent@@6B@ equ <__imp_??_7CComPlusComponent@@6B@>

externdef __imp_??_7CComPlusInterface@@6B@:PPROC
??_7CComPlusInterface@@6B@ equ <__imp_??_7CComPlusInterface@@6B@>

externdef __imp_??_7CComPlusMethod@@6B@:PPROC
??_7CComPlusMethod@@6B@ equ <__imp_??_7CComPlusMethod@@6B@>

externdef __imp_??_7CComPlusObject@@6B@:PPROC
??_7CComPlusObject@@6B@ equ <__imp_??_7CComPlusObject@@6B@>

externdef __imp_?GetITypeLib@CComPlusTypelib@@QEAAPEAUITypeLib@@XZ:PPROC
?GetITypeLib@CComPlusTypelib@@QEAAPEAUITypeLib@@XZ equ <__imp_?GetITypeLib@CComPlusTypelib@@QEAAPEAUITypeLib@@XZ>

externdef __imp_CGMIsAdministrator:PPROC
CGMIsAdministrator equ <__imp_CGMIsAdministrator>

externdef __imp_COMPlusUninstallActionW:PPROC
COMPlusUninstallActionW equ <__imp_COMPlusUninstallActionW>
  IFDEF __UNICODE__
    COMPlusUninstallAction equ <__imp_COMPlusUninstallActionW>
  ENDIF

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_FindAssemblyModulesW:PPROC
FindAssemblyModulesW equ <__imp_FindAssemblyModulesW>
  IFDEF __UNICODE__
    FindAssemblyModules equ <__imp_FindAssemblyModulesW>
  ENDIF

externdef __imp_ManagedRequestW:PPROC
ManagedRequestW equ <__imp_ManagedRequestW>
  IFDEF __UNICODE__
    ManagedRequest equ <__imp_ManagedRequestW>
  ENDIF

externdef __imp_QueryUserDllW:PPROC
QueryUserDllW equ <__imp_QueryUserDllW>
  IFDEF __UNICODE__
    QueryUserDll equ <__imp_QueryUserDllW>
  ENDIF

externdef __imp_RegDBBackup:PPROC
RegDBBackup equ <__imp_RegDBBackup>

externdef __imp_RegDBRestore:PPROC
RegDBRestore equ <__imp_RegDBRestore>

externdef __imp_RunMTSToCom:PPROC
RunMTSToCom equ <__imp_RunMTSToCom>

externdef __imp_StartMTSTOCOM:PPROC
StartMTSTOCOM equ <__imp_StartMTSTOCOM>

externdef __imp_SysprepComplus2:PPROC
SysprepComplus2 equ <__imp_SysprepComplus2>

externdef __imp_SysprepComplus:PPROC
SysprepComplus equ <__imp_SysprepComplus>

externdef __imp_WinlogonHandlePendingInfOperations:PPROC
WinlogonHandlePendingInfOperations equ <__imp_WinlogonHandlePendingInfOperations>
