externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_OpenChannel:PPROC
OpenChannel equ <__imp_OpenChannel>

externdef __imp_ParseDesktopComponent:PPROC
ParseDesktopComponent equ <__imp_ParseDesktopComponent>

externdef __imp_Subscribe:PPROC
Subscribe equ <__imp_Subscribe>

externdef __imp_SubscribeToCDF:PPROC
SubscribeToCDF equ <__imp_SubscribeToCDF>
