externdef __imp_CLSID_CfgComp:PPROC
CLSID_CfgComp equ <__imp_CLSID_CfgComp>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_IID_ICfgComp:PPROC
IID_ICfgComp equ <__imp_IID_ICfgComp>

externdef __imp_IID_ISettingsComp2:PPROC
IID_ISettingsComp2 equ <__imp_IID_ISettingsComp2>

externdef __imp_IID_ISettingsComp:PPROC
IID_ISettingsComp equ <__imp_IID_ISettingsComp>
