externdef __imp_?ClearList@@YAXPEAVCStructArray@@@Z:PPROC
?ClearList@@YAXPEAVCStructArray@@@Z equ <__imp_?ClearList@@YAXPEAVCStructArray@@@Z>

externdef __imp_?CreateComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z:PPROC
?CreateComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z equ <__imp_?CreateComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z>

externdef __imp_?DataConvert@@YAJGGKPEAKPEAX1KK0EEK@Z:PPROC
?DataConvert@@YAJGGKPEAKPEAX1KK0EEK@Z equ <__imp_?DataConvert@@YAJGGKPEAKPEAX1KK0EEK@Z>

externdef __imp_?DestroyStgDatabase@@YAXPEAVStgDatabase@@@Z:PPROC
?DestroyStgDatabase@@YAXPEAVStgDatabase@@@Z equ <__imp_?DestroyStgDatabase@@YAXPEAVStgDatabase@@@Z>

externdef __imp_?GetDataConversion@@YAJPEAPEAUIDataConvert@@@Z:PPROC
?GetDataConversion@@YAJPEAPEAUIDataConvert@@@Z equ <__imp_?GetDataConversion@@YAJPEAPEAUIDataConvert@@@Z>

externdef __imp_?GetDataConvertObject@@YAPEAVCGetDataConversion@@XZ:PPROC
?GetDataConvertObject@@YAPEAVCGetDataConversion@@XZ equ <__imp_?GetDataConvertObject@@YAPEAVCGetDataConversion@@XZ>

externdef __imp_?GetPropValue@@YAJGPEAJPEAXHPEAHAEAUtagDBPROP@@@Z:PPROC
?GetPropValue@@YAJGPEAJPEAXHPEAHAEAUtagDBPROP@@@Z equ <__imp_?GetPropValue@@YAJGPEAJPEAXHPEAHAEAUtagDBPROP@@@Z>

externdef __imp_?GetStgDatabase@@YAJPEAPEAVStgDatabase@@@Z:PPROC
?GetStgDatabase@@YAJPEAPEAVStgDatabase@@@Z equ <__imp_?GetStgDatabase@@YAJPEAPEAVStgDatabase@@@Z>

externdef __imp_?InitErrors@@YAXPEAK@Z:PPROC
?InitErrors@@YAXPEAK@Z equ <__imp_?InitErrors@@YAXPEAK@Z>

externdef __imp_?OpenComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z:PPROC
?OpenComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z equ <__imp_?OpenComponentLibraryTS@@YAJPEBGJPEAPEAUIComponentRecords@@@Z>

externdef __imp_?PostError@@YAJJZZ:PPROC
?PostError@@YAJJZZ equ <__imp_?PostError@@YAJJZZ>

externdef __imp_?ShutDownDataConversion@@YAXXZ:PPROC
?ShutDownDataConversion@@YAXXZ equ <__imp_?ShutDownDataConversion@@YAXXZ>

externdef __imp_ActivatorUpdateForIsRouterChanges:PPROC
ActivatorUpdateForIsRouterChanges equ <__imp_ActivatorUpdateForIsRouterChanges>

externdef __imp_CLSIDFromStringByBitness:PPROC
CLSIDFromStringByBitness equ <__imp_CLSIDFromStringByBitness>

externdef __imp_CheckMemoryGates:PPROC
CheckMemoryGates equ <__imp_CheckMemoryGates>

externdef __imp_CoRegCleanup:PPROC
CoRegCleanup equ <__imp_CoRegCleanup>

externdef __imp_ComPlusEnablePartitions:PPROC
ComPlusEnablePartitions equ <__imp_ComPlusEnablePartitions>

externdef __imp_ComPlusEnableRemoteAccess:PPROC
ComPlusEnableRemoteAccess equ <__imp_ComPlusEnableRemoteAccess>

externdef __imp_ComPlusMigrate:PPROC
ComPlusMigrate equ <__imp_ComPlusMigrate>

externdef __imp_ComPlusPartitionsEnabled:PPROC
ComPlusPartitionsEnabled equ <__imp_ComPlusPartitionsEnabled>

externdef __imp_ComPlusRemoteAccessEnabled:PPROC
ComPlusRemoteAccessEnabled equ <__imp_ComPlusRemoteAccessEnabled>

externdef __imp_CreateComponentLibraryEx:PPROC
CreateComponentLibraryEx equ <__imp_CreateComponentLibraryEx>

externdef __imp_DeleteAllActivatorsForClsid:PPROC
DeleteAllActivatorsForClsid equ <__imp_DeleteAllActivatorsForClsid>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DowngradeAPL:PPROC
DowngradeAPL equ <__imp_DowngradeAPL>

externdef __imp_GetCatalogObject2:PPROC
GetCatalogObject2 equ <__imp_GetCatalogObject2>

externdef __imp_GetCatalogObject:PPROC
GetCatalogObject equ <__imp_GetCatalogObject>

externdef __imp_GetComputerObject:PPROC
GetComputerObject equ <__imp_GetComputerObject>

externdef __imp_GetGlobalBabyJITEnabled:PPROC
GetGlobalBabyJITEnabled equ <__imp_GetGlobalBabyJITEnabled>

externdef __imp_GetSimpleTableDispenser:PPROC
GetSimpleTableDispenser equ <__imp_GetSimpleTableDispenser>

externdef __imp_InprocServer32FromString:PPROC
InprocServer32FromString equ <__imp_InprocServer32FromString>

externdef __imp_OpenComponentLibraryEx:PPROC
OpenComponentLibraryEx equ <__imp_OpenComponentLibraryEx>

externdef __imp_OpenComponentLibraryOnMemEx:PPROC
OpenComponentLibraryOnMemEx equ <__imp_OpenComponentLibraryOnMemEx>

externdef __imp_OpenComponentLibraryOnStreamEx:PPROC
OpenComponentLibraryOnStreamEx equ <__imp_OpenComponentLibraryOnStreamEx>

externdef __imp_ServerGetApplicationType:PPROC
ServerGetApplicationType equ <__imp_ServerGetApplicationType>

externdef __imp_SetSetupOpen:PPROC
SetSetupOpen equ <__imp_SetSetupOpen>

externdef __imp_SetSetupSave:PPROC
SetSetupSave equ <__imp_SetSetupSave>

externdef __imp_SetupOpen:PPROC
SetupOpen equ <__imp_SetupOpen>

externdef __imp_SetupSave:PPROC
SetupSave equ <__imp_SetupSave>

externdef __imp_UpdateFromAppChange:PPROC
UpdateFromAppChange equ <__imp_UpdateFromAppChange>

externdef __imp_UpdateFromComponentChange:PPROC
UpdateFromComponentChange equ <__imp_UpdateFromComponentChange>
