externdef __imp_AutoDialFunc:PPROC
AutoDialFunc equ <__imp_AutoDialFunc>

externdef __imp_CmCustomDialDlg:PPROC
CmCustomDialDlg equ <__imp_CmCustomDialDlg>

externdef __imp_CmCustomHangUp:PPROC
CmCustomHangUp equ <__imp_CmCustomHangUp>

externdef __imp_CmReConnect:PPROC
CmReConnect equ <__imp_CmReConnect>

externdef __imp_GetCustomProperty:PPROC
GetCustomProperty equ <__imp_GetCustomProperty>

externdef __imp_InetDialHandler:PPROC
InetDialHandler equ <__imp_InetDialHandler>

externdef __imp_RasCustomDeleteEntryNotify:PPROC
RasCustomDeleteEntryNotify equ <__imp_RasCustomDeleteEntryNotify>

externdef __imp_RasCustomDial:PPROC
RasCustomDial equ <__imp_RasCustomDial>

externdef __imp_RasCustomDialDlg:PPROC
RasCustomDialDlg equ <__imp_RasCustomDialDlg>

externdef __imp_RasCustomEntryDlg:PPROC
RasCustomEntryDlg equ <__imp_RasCustomEntryDlg>

externdef __imp_RasCustomHangUp:PPROC
RasCustomHangUp equ <__imp_RasCustomHangUp>
