externdef __imp_??0CIniA@@QEAA@PEAUHINSTANCE__@@PEBD111@Z:PPROC
??0CIniA@@QEAA@PEAUHINSTANCE__@@PEBD111@Z equ <__imp_??0CIniA@@QEAA@PEAUHINSTANCE__@@PEBD111@Z>

externdef __imp_??0CIniW@@QEAA@PEAUHINSTANCE__@@PEBG111@Z:PPROC
??0CIniW@@QEAA@PEAUHINSTANCE__@@PEBG111@Z equ <__imp_??0CIniW@@QEAA@PEAUHINSTANCE__@@PEBG111@Z>

externdef __imp_??0CRandom@@QEAA@I@Z:PPROC
??0CRandom@@QEAA@I@Z equ <__imp_??0CRandom@@QEAA@I@Z>

externdef __imp_??0CRandom@@QEAA@XZ:PPROC
??0CRandom@@QEAA@XZ equ <__imp_??0CRandom@@QEAA@XZ>

externdef __imp_??0CmLogFile@@QEAA@XZ:PPROC
??0CmLogFile@@QEAA@XZ equ <__imp_??0CmLogFile@@QEAA@XZ>

externdef __imp_??1CIniA@@QEAA@XZ:PPROC
??1CIniA@@QEAA@XZ equ <__imp_??1CIniA@@QEAA@XZ>

externdef __imp_??1CIniW@@QEAA@XZ:PPROC
??1CIniW@@QEAA@XZ equ <__imp_??1CIniW@@QEAA@XZ>

externdef __imp_??1CmLogFile@@QEAA@XZ:PPROC
??1CmLogFile@@QEAA@XZ equ <__imp_??1CmLogFile@@QEAA@XZ>

externdef __imp_??4CIniA@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CIniA@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CIniA@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CIniW@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CIniW@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CIniW@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CRandom@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CRandom@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CRandom@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CmLogFile@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CmLogFile@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CmLogFile@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_FCIniA@@QEAAXXZ:PPROC
??_FCIniA@@QEAAXXZ equ <__imp_??_FCIniA@@QEAAXXZ>

externdef __imp_??_FCIniW@@QEAAXXZ:PPROC
??_FCIniW@@QEAAXXZ equ <__imp_??_FCIniW@@QEAAXXZ>

externdef __imp_?Banner@CmLogFile@@QEAAXXZ:PPROC
?Banner@CmLogFile@@QEAAXXZ equ <__imp_?Banner@CmLogFile@@QEAAXXZ>

externdef __imp_?CIniA_DeleteEntryFromReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1@Z:PPROC
?CIniA_DeleteEntryFromReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1@Z equ <__imp_?CIniA_DeleteEntryFromReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1@Z>

externdef __imp_?CIniA_GetEntryFromReg@CIniA@@IEBAPEAEPEAUHKEY__@@PEBD1KK@Z:PPROC
?CIniA_GetEntryFromReg@CIniA@@IEBAPEAEPEAUHKEY__@@PEBD1KK@Z equ <__imp_?CIniA_GetEntryFromReg@CIniA@@IEBAPEAEPEAUHKEY__@@PEBD1KK@Z>

externdef __imp_?CIniA_WriteEntryToReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1PEBEKK@Z:PPROC
?CIniA_WriteEntryToReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1PEBEKK@Z equ <__imp_?CIniA_WriteEntryToReg@CIniA@@IEBAHPEAUHKEY__@@PEBD1PEBEKK@Z>

externdef __imp_?CIniW_DeleteEntryFromReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1@Z:PPROC
?CIniW_DeleteEntryFromReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1@Z equ <__imp_?CIniW_DeleteEntryFromReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1@Z>

externdef __imp_?CIniW_GetEntryFromReg@CIniW@@IEBAPEAEPEAUHKEY__@@PEBG1KK@Z:PPROC
?CIniW_GetEntryFromReg@CIniW@@IEBAPEAEPEAUHKEY__@@PEBG1KK@Z equ <__imp_?CIniW_GetEntryFromReg@CIniW@@IEBAPEAEPEAUHKEY__@@PEBG1KK@Z>

externdef __imp_?CIniW_WriteEntryToReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1PEBEKK@Z:PPROC
?CIniW_WriteEntryToReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1PEBEKK@Z equ <__imp_?CIniW_WriteEntryToReg@CIniW@@IEBAHPEAUHKEY__@@PEBG1PEBEKK@Z>

externdef __imp_?CIni_SetFile@CIniA@@KAXPEAPEADPEBD@Z:PPROC
?CIni_SetFile@CIniA@@KAXPEAPEADPEBD@Z equ <__imp_?CIni_SetFile@CIniA@@KAXPEAPEADPEBD@Z>

externdef __imp_?CIni_SetFile@CIniW@@KAXPEAPEAGPEBG@Z:PPROC
?CIni_SetFile@CIniW@@KAXPEAPEAGPEBG@Z equ <__imp_?CIni_SetFile@CIniW@@KAXPEAPEAGPEBG@Z>

externdef __imp_?Clear@CIniA@@QEAAXXZ:PPROC
?Clear@CIniA@@QEAAXXZ equ <__imp_?Clear@CIniA@@QEAAXXZ>

externdef __imp_?Clear@CIniW@@QEAAXXZ:PPROC
?Clear@CIniW@@QEAAXXZ equ <__imp_?Clear@CIniW@@QEAAXXZ>

externdef __imp_?Clear@CmLogFile@@QEAAXH@Z:PPROC
?Clear@CmLogFile@@QEAAXH@Z equ <__imp_?Clear@CmLogFile@@QEAAXH@Z>

externdef __imp_?CloseFile@CmLogFile@@AEAAJXZ:PPROC
?CloseFile@CmLogFile@@AEAAJXZ equ <__imp_?CloseFile@CmLogFile@@AEAAJXZ>

externdef __imp_?DeInit@CmLogFile@@QEAAJXZ:PPROC
?DeInit@CmLogFile@@QEAAJXZ equ <__imp_?DeInit@CmLogFile@@QEAAJXZ>

externdef __imp_?FormatWrite@CmLogFile@@AEAAXW4_CMLOG_ITEM@@PEAG@Z:PPROC
?FormatWrite@CmLogFile@@AEAAXW4_CMLOG_ITEM@@PEAG@Z equ <__imp_?FormatWrite@CmLogFile@@AEAAXW4_CMLOG_ITEM@@PEAG@Z>

externdef __imp_?GPPB@CIniA@@QEBAHPEBD0H@Z:PPROC
?GPPB@CIniA@@QEBAHPEBD0H@Z equ <__imp_?GPPB@CIniA@@QEBAHPEBD0H@Z>

externdef __imp_?GPPB@CIniW@@QEBAHPEBG0H@Z:PPROC
?GPPB@CIniW@@QEBAHPEBG0H@Z equ <__imp_?GPPB@CIniW@@QEBAHPEBG0H@Z>

externdef __imp_?GPPI@CIniA@@QEBAKPEBD0K@Z:PPROC
?GPPI@CIniA@@QEBAKPEBD0K@Z equ <__imp_?GPPI@CIniA@@QEBAKPEBD0K@Z>

externdef __imp_?GPPI@CIniW@@QEBAKPEBG0K@Z:PPROC
?GPPI@CIniW@@QEBAKPEBG0K@Z equ <__imp_?GPPI@CIniW@@QEBAKPEBG0K@Z>

externdef __imp_?GPPS@CIniA@@QEBAPEADPEBD00@Z:PPROC
?GPPS@CIniA@@QEBAPEADPEBD00@Z equ <__imp_?GPPS@CIniA@@QEBAPEADPEBD00@Z>

externdef __imp_?GPPS@CIniW@@QEBAPEAGPEBG00@Z:PPROC
?GPPS@CIniW@@QEBAPEAGPEBG00@Z equ <__imp_?GPPS@CIniW@@QEBAPEAGPEBG00@Z>

externdef __imp_?Generate@CRandom@@QEAAHXZ:PPROC
?Generate@CRandom@@QEAAHXZ equ <__imp_?Generate@CRandom@@QEAAHXZ>

externdef __imp_?GetFile@CIniA@@QEBAPEBDXZ:PPROC
?GetFile@CIniA@@QEBAPEBDXZ equ <__imp_?GetFile@CIniA@@QEBAPEBDXZ>

externdef __imp_?GetFile@CIniW@@QEBAPEBGXZ:PPROC
?GetFile@CIniW@@QEBAPEBGXZ equ <__imp_?GetFile@CIniW@@QEBAPEBGXZ>

externdef __imp_?GetHInst@CIniA@@QEBAPEAUHINSTANCE__@@XZ:PPROC
?GetHInst@CIniA@@QEBAPEAUHINSTANCE__@@XZ equ <__imp_?GetHInst@CIniA@@QEBAPEAUHINSTANCE__@@XZ>

externdef __imp_?GetHInst@CIniW@@QEBAPEAUHINSTANCE__@@XZ:PPROC
?GetHInst@CIniW@@QEBAPEAUHINSTANCE__@@XZ equ <__imp_?GetHInst@CIniW@@QEBAPEAUHINSTANCE__@@XZ>

externdef __imp_?GetLogFilePath@CmLogFile@@QEAAPEBGXZ:PPROC
?GetLogFilePath@CmLogFile@@QEAAPEBGXZ equ <__imp_?GetLogFilePath@CmLogFile@@QEAAPEBGXZ>

externdef __imp_?GetPrimaryFile@CIniA@@QEBAPEBDXZ:PPROC
?GetPrimaryFile@CIniA@@QEBAPEBDXZ equ <__imp_?GetPrimaryFile@CIniA@@QEBAPEBDXZ>

externdef __imp_?GetPrimaryFile@CIniW@@QEBAPEBGXZ:PPROC
?GetPrimaryFile@CIniW@@QEBAPEBGXZ equ <__imp_?GetPrimaryFile@CIniW@@QEBAPEBGXZ>

externdef __imp_?GetPrimaryRegPath@CIniA@@QEBAPEBDXZ:PPROC
?GetPrimaryRegPath@CIniA@@QEBAPEBDXZ equ <__imp_?GetPrimaryRegPath@CIniA@@QEBAPEBDXZ>

externdef __imp_?GetPrimaryRegPath@CIniW@@QEBAPEBGXZ:PPROC
?GetPrimaryRegPath@CIniW@@QEBAPEBGXZ equ <__imp_?GetPrimaryRegPath@CIniW@@QEBAPEBGXZ>

externdef __imp_?GetRegPath@CIniA@@QEBAPEBDXZ:PPROC
?GetRegPath@CIniA@@QEBAPEBDXZ equ <__imp_?GetRegPath@CIniA@@QEBAPEBDXZ>

externdef __imp_?GetRegPath@CIniW@@QEBAPEBGXZ:PPROC
?GetRegPath@CIniW@@QEBAPEBGXZ equ <__imp_?GetRegPath@CIniW@@QEBAPEBGXZ>

externdef __imp_?GetSection@CIniA@@QEBAPEBDXZ:PPROC
?GetSection@CIniA@@QEBAPEBDXZ equ <__imp_?GetSection@CIniA@@QEBAPEBDXZ>

externdef __imp_?GetSection@CIniW@@QEBAPEBGXZ:PPROC
?GetSection@CIniW@@QEBAPEBGXZ equ <__imp_?GetSection@CIniW@@QEBAPEBGXZ>

externdef __imp_?Init@CRandom@@QEAAXK@Z:PPROC
?Init@CRandom@@QEAAXK@Z equ <__imp_?Init@CRandom@@QEAAXK@Z>

externdef __imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBD@Z:PPROC
?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBD@Z equ <__imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBD@Z>

externdef __imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBG@Z:PPROC
?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBG@Z equ <__imp_?Init@CmLogFile@@QEAAJPEAUHINSTANCE__@@HPEBG@Z>

externdef __imp_?IsEnabled@CmLogFile@@QEAAHXZ:PPROC
?IsEnabled@CmLogFile@@QEAAHXZ equ <__imp_?IsEnabled@CmLogFile@@QEAAHXZ>

externdef __imp_?LoadEntry@CIniA@@IEBAPEADPEBD@Z:PPROC
?LoadEntry@CIniA@@IEBAPEADPEBD@Z equ <__imp_?LoadEntry@CIniA@@IEBAPEADPEBD@Z>

externdef __imp_?LoadEntry@CIniW@@IEBAPEAGPEBG@Z:PPROC
?LoadEntry@CIniW@@IEBAPEAGPEBG@Z equ <__imp_?LoadEntry@CIniW@@IEBAPEAGPEBG@Z>

externdef __imp_?LoadSection@CIniA@@QEBAPEADPEBD@Z:PPROC
?LoadSection@CIniA@@QEBAPEADPEBD@Z equ <__imp_?LoadSection@CIniA@@QEBAPEADPEBD@Z>

externdef __imp_?LoadSection@CIniW@@QEBAPEAGPEBG@Z:PPROC
?LoadSection@CIniW@@QEBAPEAGPEBG@Z equ <__imp_?LoadSection@CIniW@@QEBAPEAGPEBG@Z>

externdef __imp_?Log@CmLogFile@@QEAAXW4_CMLOG_ITEM@@ZZ:PPROC
?Log@CmLogFile@@QEAAXW4_CMLOG_ITEM@@ZZ equ <__imp_?Log@CmLogFile@@QEAAXW4_CMLOG_ITEM@@ZZ>

externdef __imp_?OpenFile@CmLogFile@@AEAAJXZ:PPROC
?OpenFile@CmLogFile@@AEAAJXZ equ <__imp_?OpenFile@CmLogFile@@AEAAJXZ>

externdef __imp_?SetEntry@CIniA@@QEAAXPEBD@Z:PPROC
?SetEntry@CIniA@@QEAAXPEBD@Z equ <__imp_?SetEntry@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetEntry@CIniW@@QEAAXPEBG@Z:PPROC
?SetEntry@CIniW@@QEAAXPEBG@Z equ <__imp_?SetEntry@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetEntryFromIdx@CIniA@@QEAAXK@Z:PPROC
?SetEntryFromIdx@CIniA@@QEAAXK@Z equ <__imp_?SetEntryFromIdx@CIniA@@QEAAXK@Z>

externdef __imp_?SetEntryFromIdx@CIniW@@QEAAXK@Z:PPROC
?SetEntryFromIdx@CIniW@@QEAAXK@Z equ <__imp_?SetEntryFromIdx@CIniW@@QEAAXK@Z>

externdef __imp_?SetFile@CIniA@@QEAAXPEBD@Z:PPROC
?SetFile@CIniA@@QEAAXPEBD@Z equ <__imp_?SetFile@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetFile@CIniW@@QEAAXPEBG@Z:PPROC
?SetFile@CIniW@@QEAAXPEBG@Z equ <__imp_?SetFile@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetHInst@CIniA@@QEAAXPEAUHINSTANCE__@@@Z:PPROC
?SetHInst@CIniA@@QEAAXPEAUHINSTANCE__@@@Z equ <__imp_?SetHInst@CIniA@@QEAAXPEAUHINSTANCE__@@@Z>

externdef __imp_?SetHInst@CIniW@@QEAAXPEAUHINSTANCE__@@@Z:PPROC
?SetHInst@CIniW@@QEAAXPEAUHINSTANCE__@@@Z equ <__imp_?SetHInst@CIniW@@QEAAXPEAUHINSTANCE__@@@Z>

externdef __imp_?SetICSDataPath@CIniA@@QEAAXPEBD@Z:PPROC
?SetICSDataPath@CIniA@@QEAAXPEBD@Z equ <__imp_?SetICSDataPath@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetICSDataPath@CIniW@@QEAAXPEBG@Z:PPROC
?SetICSDataPath@CIniW@@QEAAXPEBG@Z equ <__imp_?SetICSDataPath@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetParams@CmLogFile@@QEAAJHKPEBD@Z:PPROC
?SetParams@CmLogFile@@QEAAJHKPEBD@Z equ <__imp_?SetParams@CmLogFile@@QEAAJHKPEBD@Z>

externdef __imp_?SetParams@CmLogFile@@QEAAJHKPEBG@Z:PPROC
?SetParams@CmLogFile@@QEAAJHKPEBG@Z equ <__imp_?SetParams@CmLogFile@@QEAAJHKPEBG@Z>

externdef __imp_?SetPrimaryFile@CIniA@@QEAAXPEBD@Z:PPROC
?SetPrimaryFile@CIniA@@QEAAXPEBD@Z equ <__imp_?SetPrimaryFile@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetPrimaryFile@CIniW@@QEAAXPEBG@Z:PPROC
?SetPrimaryFile@CIniW@@QEAAXPEBG@Z equ <__imp_?SetPrimaryFile@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetPrimaryRegPath@CIniA@@QEAAXPEBD@Z:PPROC
?SetPrimaryRegPath@CIniA@@QEAAXPEBD@Z equ <__imp_?SetPrimaryRegPath@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetPrimaryRegPath@CIniW@@QEAAXPEBG@Z:PPROC
?SetPrimaryRegPath@CIniW@@QEAAXPEBG@Z equ <__imp_?SetPrimaryRegPath@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetReadICSData@CIniA@@QEAAXH@Z:PPROC
?SetReadICSData@CIniA@@QEAAXH@Z equ <__imp_?SetReadICSData@CIniA@@QEAAXH@Z>

externdef __imp_?SetReadICSData@CIniW@@QEAAXH@Z:PPROC
?SetReadICSData@CIniW@@QEAAXH@Z equ <__imp_?SetReadICSData@CIniW@@QEAAXH@Z>

externdef __imp_?SetRegPath@CIniA@@QEAAXPEBD@Z:PPROC
?SetRegPath@CIniA@@QEAAXPEBD@Z equ <__imp_?SetRegPath@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetRegPath@CIniW@@QEAAXPEBG@Z:PPROC
?SetRegPath@CIniW@@QEAAXPEBG@Z equ <__imp_?SetRegPath@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetSection@CIniA@@QEAAXPEBD@Z:PPROC
?SetSection@CIniA@@QEAAXPEBD@Z equ <__imp_?SetSection@CIniA@@QEAAXPEBD@Z>

externdef __imp_?SetSection@CIniW@@QEAAXPEBG@Z:PPROC
?SetSection@CIniW@@QEAAXPEBG@Z equ <__imp_?SetSection@CIniW@@QEAAXPEBG@Z>

externdef __imp_?SetWriteICSData@CIniA@@QEAAXH@Z:PPROC
?SetWriteICSData@CIniA@@QEAAXH@Z equ <__imp_?SetWriteICSData@CIniA@@QEAAXH@Z>

externdef __imp_?SetWriteICSData@CIniW@@QEAAXH@Z:PPROC
?SetWriteICSData@CIniW@@QEAAXH@Z equ <__imp_?SetWriteICSData@CIniW@@QEAAXH@Z>

externdef __imp_?Start@CmLogFile@@QEAAJH@Z:PPROC
?Start@CmLogFile@@QEAAJH@Z equ <__imp_?Start@CmLogFile@@QEAAJH@Z>

externdef __imp_?Stop@CmLogFile@@QEAAJXZ:PPROC
?Stop@CmLogFile@@QEAAJXZ equ <__imp_?Stop@CmLogFile@@QEAAJXZ>

externdef __imp_?WPPB@CIniA@@QEAAXPEBD0H@Z:PPROC
?WPPB@CIniA@@QEAAXPEBD0H@Z equ <__imp_?WPPB@CIniA@@QEAAXPEBD0H@Z>

externdef __imp_?WPPB@CIniW@@QEAAXPEBG0H@Z:PPROC
?WPPB@CIniW@@QEAAXPEBG0H@Z equ <__imp_?WPPB@CIniW@@QEAAXPEBG0H@Z>

externdef __imp_?WPPI@CIniA@@QEAAXPEBD0K@Z:PPROC
?WPPI@CIniA@@QEAAXPEBD0K@Z equ <__imp_?WPPI@CIniA@@QEAAXPEBD0K@Z>

externdef __imp_?WPPI@CIniW@@QEAAXPEBG0K@Z:PPROC
?WPPI@CIniW@@QEAAXPEBG0K@Z equ <__imp_?WPPI@CIniW@@QEAAXPEBG0K@Z>

externdef __imp_?WPPS@CIniA@@QEAAXPEBD00@Z:PPROC
?WPPS@CIniA@@QEAAXPEBD00@Z equ <__imp_?WPPS@CIniA@@QEAAXPEBD00@Z>

externdef __imp_?WPPS@CIniW@@QEAAXPEBG00@Z:PPROC
?WPPS@CIniW@@QEAAXPEBG00@Z equ <__imp_?WPPS@CIniW@@QEAAXPEBG00@Z>

externdef __imp_?Write@CmLogFile@@AEAAJPEAG@Z:PPROC
?Write@CmLogFile@@AEAAJPEAG@Z equ <__imp_?Write@CmLogFile@@AEAAJPEAG@Z>

externdef __imp_CmAtolA:PPROC
CmAtolA equ <__imp_CmAtolA>
  IFNDEF __UNICODE__
    CmAtol equ <__imp_CmAtolA>
  ENDIF

externdef __imp_CmAtolW:PPROC
CmAtolW equ <__imp_CmAtolW>
  IFDEF __UNICODE__
    CmAtol equ <__imp_CmAtolW>
  ENDIF

externdef __imp_CmBuildFullPathFromRelativeA:PPROC
CmBuildFullPathFromRelativeA equ <__imp_CmBuildFullPathFromRelativeA>
  IFNDEF __UNICODE__
    CmBuildFullPathFromRelative equ <__imp_CmBuildFullPathFromRelativeA>
  ENDIF

externdef __imp_CmBuildFullPathFromRelativeW:PPROC
CmBuildFullPathFromRelativeW equ <__imp_CmBuildFullPathFromRelativeW>
  IFDEF __UNICODE__
    CmBuildFullPathFromRelative equ <__imp_CmBuildFullPathFromRelativeW>
  ENDIF

externdef __imp_CmCompareStringA:PPROC
CmCompareStringA equ <__imp_CmCompareStringA>
  IFNDEF __UNICODE__
    CmCompareString equ <__imp_CmCompareStringA>
  ENDIF

externdef __imp_CmCompareStringW:PPROC
CmCompareStringW equ <__imp_CmCompareStringW>
  IFDEF __UNICODE__
    CmCompareString equ <__imp_CmCompareStringW>
  ENDIF

externdef __imp_CmConvertRelativePathA:PPROC
CmConvertRelativePathA equ <__imp_CmConvertRelativePathA>
  IFNDEF __UNICODE__
    CmConvertRelativePath equ <__imp_CmConvertRelativePathA>
  ENDIF

externdef __imp_CmConvertRelativePathW:PPROC
CmConvertRelativePathW equ <__imp_CmConvertRelativePathW>
  IFDEF __UNICODE__
    CmConvertRelativePath equ <__imp_CmConvertRelativePathW>
  ENDIF

externdef __imp_CmEndOfStrA:PPROC
CmEndOfStrA equ <__imp_CmEndOfStrA>
  IFNDEF __UNICODE__
    CmEndOfStr equ <__imp_CmEndOfStrA>
  ENDIF

externdef __imp_CmEndOfStrW:PPROC
CmEndOfStrW equ <__imp_CmEndOfStrW>
  IFDEF __UNICODE__
    CmEndOfStr equ <__imp_CmEndOfStrW>
  ENDIF

externdef __imp_CmFmtMsgA:PPROC
CmFmtMsgA equ <__imp_CmFmtMsgA>
  IFNDEF __UNICODE__
    CmFmtMsg equ <__imp_CmFmtMsgA>
  ENDIF

externdef __imp_CmFmtMsgW:PPROC
CmFmtMsgW equ <__imp_CmFmtMsgW>
  IFDEF __UNICODE__
    CmFmtMsg equ <__imp_CmFmtMsgW>
  ENDIF

externdef __imp_CmFree:PPROC
CmFree equ <__imp_CmFree>

externdef __imp_CmIsDigitA:PPROC
CmIsDigitA equ <__imp_CmIsDigitA>
  IFNDEF __UNICODE__
    CmIsDigit equ <__imp_CmIsDigitA>
  ENDIF

externdef __imp_CmIsDigitW:PPROC
CmIsDigitW equ <__imp_CmIsDigitW>
  IFDEF __UNICODE__
    CmIsDigit equ <__imp_CmIsDigitW>
  ENDIF

externdef __imp_CmIsSpaceA:PPROC
CmIsSpaceA equ <__imp_CmIsSpaceA>
  IFNDEF __UNICODE__
    CmIsSpace equ <__imp_CmIsSpaceA>
  ENDIF

externdef __imp_CmIsSpaceW:PPROC
CmIsSpaceW equ <__imp_CmIsSpaceW>
  IFDEF __UNICODE__
    CmIsSpace equ <__imp_CmIsSpaceW>
  ENDIF

externdef __imp_CmLoadIconA:PPROC
CmLoadIconA equ <__imp_CmLoadIconA>
  IFNDEF __UNICODE__
    CmLoadIcon equ <__imp_CmLoadIconA>
  ENDIF

externdef __imp_CmLoadIconW:PPROC
CmLoadIconW equ <__imp_CmLoadIconW>
  IFDEF __UNICODE__
    CmLoadIcon equ <__imp_CmLoadIconW>
  ENDIF

externdef __imp_CmLoadImage:PPROC
CmLoadImage equ <__imp_CmLoadImage>

externdef __imp_CmLoadImageA:PPROC
CmLoadImageA equ <__imp_CmLoadImageA>
  IFNDEF __UNICODE__
    CmLoadImage equ <__imp_CmLoadImageA>
  ENDIF

externdef __imp_CmLoadImageW:PPROC
CmLoadImageW equ <__imp_CmLoadImageW>
  IFDEF __UNICODE__
    CmLoadImage equ <__imp_CmLoadImageW>
  ENDIF

externdef __imp_CmLoadSmallIconA:PPROC
CmLoadSmallIconA equ <__imp_CmLoadSmallIconA>
  IFNDEF __UNICODE__
    CmLoadSmallIcon equ <__imp_CmLoadSmallIconA>
  ENDIF

externdef __imp_CmLoadSmallIconW:PPROC
CmLoadSmallIconW equ <__imp_CmLoadSmallIconW>
  IFDEF __UNICODE__
    CmLoadSmallIcon equ <__imp_CmLoadSmallIconW>
  ENDIF

externdef __imp_CmLoadStringA:PPROC
CmLoadStringA equ <__imp_CmLoadStringA>
  IFNDEF __UNICODE__
    CmLoadString equ <__imp_CmLoadStringA>
  ENDIF

externdef __imp_CmLoadStringW:PPROC
CmLoadStringW equ <__imp_CmLoadStringW>
  IFDEF __UNICODE__
    CmLoadString equ <__imp_CmLoadStringW>
  ENDIF

externdef __imp_CmMalloc:PPROC
CmMalloc equ <__imp_CmMalloc>

externdef __imp_CmParsePathA:PPROC
CmParsePathA equ <__imp_CmParsePathA>
  IFNDEF __UNICODE__
    CmParsePath equ <__imp_CmParsePathA>
  ENDIF

externdef __imp_CmParsePathW:PPROC
CmParsePathW equ <__imp_CmParsePathW>
  IFDEF __UNICODE__
    CmParsePath equ <__imp_CmParsePathW>
  ENDIF

externdef __imp_CmRealloc:PPROC
CmRealloc equ <__imp_CmRealloc>

externdef __imp_CmStrCatAllocA:PPROC
CmStrCatAllocA equ <__imp_CmStrCatAllocA>
  IFNDEF __UNICODE__
    CmStrCatAlloc equ <__imp_CmStrCatAllocA>
  ENDIF

externdef __imp_CmStrCatAllocW:PPROC
CmStrCatAllocW equ <__imp_CmStrCatAllocW>
  IFDEF __UNICODE__
    CmStrCatAlloc equ <__imp_CmStrCatAllocW>
  ENDIF

externdef __imp_CmStrCpyAllocA:PPROC
CmStrCpyAllocA equ <__imp_CmStrCpyAllocA>
  IFNDEF __UNICODE__
    CmStrCpyAlloc equ <__imp_CmStrCpyAllocA>
  ENDIF

externdef __imp_CmStrCpyAllocW:PPROC
CmStrCpyAllocW equ <__imp_CmStrCpyAllocW>
  IFDEF __UNICODE__
    CmStrCpyAlloc equ <__imp_CmStrCpyAllocW>
  ENDIF

externdef __imp_CmStrStrA:PPROC
CmStrStrA equ <__imp_CmStrStrA>
  IFNDEF __UNICODE__
    CmStrStr equ <__imp_CmStrStrA>
  ENDIF

externdef __imp_CmStrStrW:PPROC
CmStrStrW equ <__imp_CmStrStrW>
  IFDEF __UNICODE__
    CmStrStr equ <__imp_CmStrStrW>
  ENDIF

externdef __imp_CmStrTrimA:PPROC
CmStrTrimA equ <__imp_CmStrTrimA>
  IFNDEF __UNICODE__
    CmStrTrim equ <__imp_CmStrTrimA>
  ENDIF

externdef __imp_CmStrTrimW:PPROC
CmStrTrimW equ <__imp_CmStrTrimW>
  IFDEF __UNICODE__
    CmStrTrim equ <__imp_CmStrTrimW>
  ENDIF

externdef __imp_CmStrchrA:PPROC
CmStrchrA equ <__imp_CmStrchrA>
  IFNDEF __UNICODE__
    CmStrchr equ <__imp_CmStrchrA>
  ENDIF

externdef __imp_CmStrchrW:PPROC
CmStrchrW equ <__imp_CmStrchrW>
  IFDEF __UNICODE__
    CmStrchr equ <__imp_CmStrchrW>
  ENDIF

externdef __imp_CmStripFileNameA:PPROC
CmStripFileNameA equ <__imp_CmStripFileNameA>
  IFNDEF __UNICODE__
    CmStripFileName equ <__imp_CmStripFileNameA>
  ENDIF

externdef __imp_CmStripFileNameW:PPROC
CmStripFileNameW equ <__imp_CmStripFileNameW>
  IFDEF __UNICODE__
    CmStripFileName equ <__imp_CmStripFileNameW>
  ENDIF

externdef __imp_CmStripPathAndExtA:PPROC
CmStripPathAndExtA equ <__imp_CmStripPathAndExtA>
  IFNDEF __UNICODE__
    CmStripPathAndExt equ <__imp_CmStripPathAndExtA>
  ENDIF

externdef __imp_CmStripPathAndExtW:PPROC
CmStripPathAndExtW equ <__imp_CmStripPathAndExtW>
  IFDEF __UNICODE__
    CmStripPathAndExt equ <__imp_CmStripPathAndExtW>
  ENDIF

externdef __imp_CmStrrchrA:PPROC
CmStrrchrA equ <__imp_CmStrrchrA>
  IFNDEF __UNICODE__
    CmStrrchr equ <__imp_CmStrrchrA>
  ENDIF

externdef __imp_CmStrrchrW:PPROC
CmStrrchrW equ <__imp_CmStrrchrW>
  IFDEF __UNICODE__
    CmStrrchr equ <__imp_CmStrrchrW>
  ENDIF

externdef __imp_CmStrtokA:PPROC
CmStrtokA equ <__imp_CmStrtokA>
  IFNDEF __UNICODE__
    CmStrtok equ <__imp_CmStrtokA>
  ENDIF

externdef __imp_CmStrtokW:PPROC
CmStrtokW equ <__imp_CmStrtokW>
  IFDEF __UNICODE__
    CmStrtok equ <__imp_CmStrtokW>
  ENDIF

externdef __imp_CmWinHelp:PPROC
CmWinHelp equ <__imp_CmWinHelp>

externdef __imp_GetOSBuildNumber:PPROC
GetOSBuildNumber equ <__imp_GetOSBuildNumber>

externdef __imp_GetOSMajorVersion:PPROC
GetOSMajorVersion equ <__imp_GetOSMajorVersion>

externdef __imp_GetOSVersion:PPROC
GetOSVersion equ <__imp_GetOSVersion>

externdef __imp_IsFarEastNonOSR2Win95:PPROC
IsFarEastNonOSR2Win95 equ <__imp_IsFarEastNonOSR2Win95>

externdef __imp_IsLogonAsSystem:PPROC
IsLogonAsSystem equ <__imp_IsLogonAsSystem>

externdef __imp_MakeBold:PPROC
MakeBold equ <__imp_MakeBold>

externdef __imp_ReleaseBold:PPROC
ReleaseBold equ <__imp_ReleaseBold>

externdef __imp_SzToWz:PPROC
SzToWz equ <__imp_SzToWz>

externdef __imp_SzToWzWithAlloc:PPROC
SzToWzWithAlloc equ <__imp_SzToWzWithAlloc>

externdef __imp_UpdateFont:PPROC
UpdateFont equ <__imp_UpdateFont>

externdef __imp_WzToSz:PPROC
WzToSz equ <__imp_WzToSz>

externdef __imp_WzToSzWithAlloc:PPROC
WzToSzWithAlloc equ <__imp_WzToSzWithAlloc>
