externdef __imp_CORLockDownProvider:PPROC
CORLockDownProvider equ <__imp_CORLockDownProvider>

externdef __imp_CORPolicyEE:PPROC
CORPolicyEE equ <__imp_CORPolicyEE>

externdef __imp_CORPolicyProvider:PPROC
CORPolicyProvider equ <__imp_CORPolicyProvider>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_GetPublisher:PPROC
GetPublisher equ <__imp_GetPublisher>

externdef __imp_GetUnsignedPermissions:PPROC
GetUnsignedPermissions equ <__imp_GetUnsignedPermissions>
