externdef __imp_CDBuildIntegrityVect:PPROC
CDBuildIntegrityVect equ <__imp_CDBuildIntegrityVect>

externdef __imp_CDBuildVect:PPROC
CDBuildVect equ <__imp_CDBuildVect>

externdef __imp_CDFindCommonCSystem:PPROC
CDFindCommonCSystem equ <__imp_CDFindCommonCSystem>

externdef __imp_CDFindCommonCSystemWithKey:PPROC
CDFindCommonCSystemWithKey equ <__imp_CDFindCommonCSystemWithKey>

externdef __imp_CDGenerateRandomBits:PPROC
CDGenerateRandomBits equ <__imp_CDGenerateRandomBits>

externdef __imp_CDLocateCSystem:PPROC
CDLocateCSystem equ <__imp_CDLocateCSystem>

externdef __imp_CDLocateCheckSum:PPROC
CDLocateCheckSum equ <__imp_CDLocateCheckSum>

externdef __imp_CDLocateRng:PPROC
CDLocateRng equ <__imp_CDLocateRng>

externdef __imp_CDRegisterCSystem:PPROC
CDRegisterCSystem equ <__imp_CDRegisterCSystem>

externdef __imp_CDRegisterCheckSum:PPROC
CDRegisterCheckSum equ <__imp_CDRegisterCheckSum>

externdef __imp_CDRegisterRng:PPROC
CDRegisterRng equ <__imp_CDRegisterRng>

externdef __imp_MD5Final:PPROC
MD5Final equ <__imp_MD5Final>

externdef __imp_MD5Init:PPROC
MD5Init equ <__imp_MD5Init>

externdef __imp_MD5Update:PPROC
MD5Update equ <__imp_MD5Update>
