externdef __imp_CryptExtAddCER:PPROC
CryptExtAddCER equ <__imp_CryptExtAddCER>

externdef __imp_CryptExtAddCERW:PPROC
CryptExtAddCERW equ <__imp_CryptExtAddCERW>
  IFDEF __UNICODE__
    CryptExtAddCER equ <__imp_CryptExtAddCERW>
  ENDIF

externdef __imp_CryptExtAddCRL:PPROC
CryptExtAddCRL equ <__imp_CryptExtAddCRL>

externdef __imp_CryptExtAddCRLW:PPROC
CryptExtAddCRLW equ <__imp_CryptExtAddCRLW>
  IFDEF __UNICODE__
    CryptExtAddCRL equ <__imp_CryptExtAddCRLW>
  ENDIF

externdef __imp_CryptExtAddCTL:PPROC
CryptExtAddCTL equ <__imp_CryptExtAddCTL>

externdef __imp_CryptExtAddCTLW:PPROC
CryptExtAddCTLW equ <__imp_CryptExtAddCTLW>
  IFDEF __UNICODE__
    CryptExtAddCTL equ <__imp_CryptExtAddCTLW>
  ENDIF

externdef __imp_CryptExtAddP7R:PPROC
CryptExtAddP7R equ <__imp_CryptExtAddP7R>

externdef __imp_CryptExtAddP7RW:PPROC
CryptExtAddP7RW equ <__imp_CryptExtAddP7RW>
  IFDEF __UNICODE__
    CryptExtAddP7R equ <__imp_CryptExtAddP7RW>
  ENDIF

externdef __imp_CryptExtAddPFX:PPROC
CryptExtAddPFX equ <__imp_CryptExtAddPFX>

externdef __imp_CryptExtAddPFXW:PPROC
CryptExtAddPFXW equ <__imp_CryptExtAddPFXW>
  IFDEF __UNICODE__
    CryptExtAddPFX equ <__imp_CryptExtAddPFXW>
  ENDIF

externdef __imp_CryptExtAddSPC:PPROC
CryptExtAddSPC equ <__imp_CryptExtAddSPC>

externdef __imp_CryptExtAddSPCW:PPROC
CryptExtAddSPCW equ <__imp_CryptExtAddSPCW>
  IFDEF __UNICODE__
    CryptExtAddSPC equ <__imp_CryptExtAddSPCW>
  ENDIF

externdef __imp_CryptExtOpenCAT:PPROC
CryptExtOpenCAT equ <__imp_CryptExtOpenCAT>

externdef __imp_CryptExtOpenCATW:PPROC
CryptExtOpenCATW equ <__imp_CryptExtOpenCATW>
  IFDEF __UNICODE__
    CryptExtOpenCAT equ <__imp_CryptExtOpenCATW>
  ENDIF

externdef __imp_CryptExtOpenCER:PPROC
CryptExtOpenCER equ <__imp_CryptExtOpenCER>

externdef __imp_CryptExtOpenCERW:PPROC
CryptExtOpenCERW equ <__imp_CryptExtOpenCERW>
  IFDEF __UNICODE__
    CryptExtOpenCER equ <__imp_CryptExtOpenCERW>
  ENDIF

externdef __imp_CryptExtOpenCRL:PPROC
CryptExtOpenCRL equ <__imp_CryptExtOpenCRL>

externdef __imp_CryptExtOpenCRLW:PPROC
CryptExtOpenCRLW equ <__imp_CryptExtOpenCRLW>
  IFDEF __UNICODE__
    CryptExtOpenCRL equ <__imp_CryptExtOpenCRLW>
  ENDIF

externdef __imp_CryptExtOpenCTL:PPROC
CryptExtOpenCTL equ <__imp_CryptExtOpenCTL>

externdef __imp_CryptExtOpenCTLW:PPROC
CryptExtOpenCTLW equ <__imp_CryptExtOpenCTLW>
  IFDEF __UNICODE__
    CryptExtOpenCTL equ <__imp_CryptExtOpenCTLW>
  ENDIF

externdef __imp_CryptExtOpenP10:PPROC
CryptExtOpenP10 equ <__imp_CryptExtOpenP10>

externdef __imp_CryptExtOpenP10W:PPROC
CryptExtOpenP10W equ <__imp_CryptExtOpenP10W>
  IFDEF __UNICODE__
    CryptExtOpenP10 equ <__imp_CryptExtOpenP10W>
  ENDIF

externdef __imp_CryptExtOpenP7R:PPROC
CryptExtOpenP7R equ <__imp_CryptExtOpenP7R>

externdef __imp_CryptExtOpenP7RW:PPROC
CryptExtOpenP7RW equ <__imp_CryptExtOpenP7RW>
  IFDEF __UNICODE__
    CryptExtOpenP7R equ <__imp_CryptExtOpenP7RW>
  ENDIF

externdef __imp_CryptExtOpenPKCS7:PPROC
CryptExtOpenPKCS7 equ <__imp_CryptExtOpenPKCS7>

externdef __imp_CryptExtOpenPKCS7W:PPROC
CryptExtOpenPKCS7W equ <__imp_CryptExtOpenPKCS7W>
  IFDEF __UNICODE__
    CryptExtOpenPKCS7 equ <__imp_CryptExtOpenPKCS7W>
  ENDIF

externdef __imp_CryptExtOpenSTR:PPROC
CryptExtOpenSTR equ <__imp_CryptExtOpenSTR>

externdef __imp_CryptExtOpenSTRW:PPROC
CryptExtOpenSTRW equ <__imp_CryptExtOpenSTRW>
  IFDEF __UNICODE__
    CryptExtOpenSTR equ <__imp_CryptExtOpenSTRW>
  ENDIF

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
