externdef __imp_CheckFullscreen:PPROC
CheckFullscreen equ <__imp_CheckFullscreen>

externdef __imp_D3DPERF_BeginEvent:PPROC
D3DPERF_BeginEvent equ <__imp_D3DPERF_BeginEvent>

externdef __imp_D3DPERF_EndEvent:PPROC
D3DPERF_EndEvent equ <__imp_D3DPERF_EndEvent>

externdef __imp_D3DPERF_GetStatus:PPROC
D3DPERF_GetStatus equ <__imp_D3DPERF_GetStatus>

externdef __imp_D3DPERF_QueryRepeatFrame:PPROC
D3DPERF_QueryRepeatFrame equ <__imp_D3DPERF_QueryRepeatFrame>

externdef __imp_D3DPERF_SetMarker:PPROC
D3DPERF_SetMarker equ <__imp_D3DPERF_SetMarker>

externdef __imp_D3DPERF_SetOptions:PPROC
D3DPERF_SetOptions equ <__imp_D3DPERF_SetOptions>

externdef __imp_D3DPERF_SetRegion:PPROC
D3DPERF_SetRegion equ <__imp_D3DPERF_SetRegion>

externdef __imp_DebugSetLevel:PPROC
DebugSetLevel equ <__imp_DebugSetLevel>

externdef __imp_DebugSetMute:PPROC
DebugSetMute equ <__imp_DebugSetMute>

externdef __imp_Direct3DCreate9:PPROC
Direct3DCreate9 equ <__imp_Direct3DCreate9>

externdef __imp_Direct3DShaderValidatorCreate9:PPROC
Direct3DShaderValidatorCreate9 equ <__imp_Direct3DShaderValidatorCreate9>

externdef __imp_PSGPError:PPROC
PSGPError equ <__imp_PSGPError>

externdef __imp_PSGPSampleTexture:PPROC
PSGPSampleTexture equ <__imp_PSGPSampleTexture>
