externdef __imp_?COMToCRBvr@@YAPEAVCRBvr@@PEAUIUnknown@@@Z:PPROC
?COMToCRBvr@@YAPEAVCRBvr@@PEAUIUnknown@@@Z equ <__imp_?COMToCRBvr@@YAPEAVCRBvr@@PEAUIUnknown@@@Z>

externdef __imp_?CRAbs@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRAbs@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRAbs@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRAcos@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRAcos@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRAcos@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRAcquireGCLock@@YA_NXZ:PPROC
?CRAcquireGCLock@@YA_NXZ equ <__imp_?CRAcquireGCLock@@YA_NXZ>

externdef __imp_?CRAdd@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRAdd@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRAdd@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRAdd@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z:PPROC
?CRAdd@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z equ <__imp_?CRAdd@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z>

externdef __imp_?CRAdd@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z:PPROC
?CRAdd@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z equ <__imp_?CRAdd@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z>

externdef __imp_?CRAdd@@YAPEAVCRVector2@@PEAV1@0@Z:PPROC
?CRAdd@@YAPEAVCRVector2@@PEAV1@0@Z equ <__imp_?CRAdd@@YAPEAVCRVector2@@PEAV1@0@Z>

externdef __imp_?CRAdd@@YAPEAVCRVector3@@PEAV1@0@Z:PPROC
?CRAdd@@YAPEAVCRVector3@@PEAV1@0@Z equ <__imp_?CRAdd@@YAPEAVCRVector3@@PEAV1@0@Z>

externdef __imp_?CRAddBvrToRun@@YA_NPEAVCRView@@PEAVCRBvr@@_NPEAJ@Z:PPROC
?CRAddBvrToRun@@YA_NPEAVCRView@@PEAVCRBvr@@_NPEAJ@Z equ <__imp_?CRAddBvrToRun@@YA_NPEAVCRView@@PEAVCRBvr@@_NPEAJ@Z>

externdef __imp_?CRAddElement@@YAJPEAVCRArray@@PEAVCRBvr@@K@Z:PPROC
?CRAddElement@@YAJPEAVCRArray@@PEAVCRBvr@@K@Z equ <__imp_?CRAddElement@@YAJPEAVCRArray@@PEAVCRBvr@@K@Z>

externdef __imp_?CRAddPickData@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@_N@Z:PPROC
?CRAddPickData@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@_N@Z equ <__imp_?CRAddPickData@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@_N@Z>

externdef __imp_?CRAddPickData@@YAPEAVCRImage@@PEAV1@PEAUIUnknown@@_N@Z:PPROC
?CRAddPickData@@YAPEAVCRImage@@PEAV1@PEAUIUnknown@@_N@Z equ <__imp_?CRAddPickData@@YAPEAVCRImage@@PEAV1@PEAUIUnknown@@_N@Z>

externdef __imp_?CRAddRefGC@@YA_NPEAX@Z:PPROC
?CRAddRefGC@@YA_NPEAX@Z equ <__imp_?CRAddRefGC@@YA_NPEAX@Z>

externdef __imp_?CRAddSite@@YA_NPEAVCRSite@@@Z:PPROC
?CRAddSite@@YA_NPEAVCRSite@@@Z equ <__imp_?CRAddSite@@YA_NPEAVCRSite@@@Z>

externdef __imp_?CRAlways@@YAPEAVCREvent@@XZ:PPROC
?CRAlways@@YAPEAVCREvent@@XZ equ <__imp_?CRAlways@@YAPEAVCREvent@@XZ>

externdef __imp_?CRAmbientColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRAmbientColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRAmbientColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRAmbientLight@@YAPEAVCRGeometry@@XZ:PPROC
?CRAmbientLight@@YAPEAVCRGeometry@@XZ equ <__imp_?CRAmbientLight@@YAPEAVCRGeometry@@XZ>

externdef __imp_?CRAnd@@YAPEAVCRBoolean@@PEAV1@0@Z:PPROC
?CRAnd@@YAPEAVCRBoolean@@PEAV1@0@Z equ <__imp_?CRAnd@@YAPEAVCRBoolean@@PEAV1@0@Z>

externdef __imp_?CRAndEvent@@YAPEAVCREvent@@PEAV1@0@Z:PPROC
?CRAndEvent@@YAPEAVCREvent@@PEAV1@0@Z equ <__imp_?CRAndEvent@@YAPEAVCREvent@@PEAV1@0@Z>

externdef __imp_?CRAntiAliasing@@YAPEAVCRFontStyle@@PEAV1@N@Z:PPROC
?CRAntiAliasing@@YAPEAVCRFontStyle@@PEAV1@N@Z equ <__imp_?CRAntiAliasing@@YAPEAVCRFontStyle@@PEAV1@N@Z>

externdef __imp_?CRAntiAliasing@@YAPEAVCRLineStyle@@PEAV1@N@Z:PPROC
?CRAntiAliasing@@YAPEAVCRLineStyle@@PEAV1@N@Z equ <__imp_?CRAntiAliasing@@YAPEAVCRLineStyle@@PEAV1@N@Z>

externdef __imp_?CRAppTriggeredEvent@@YAPEAVCREvent@@XZ:PPROC
?CRAppTriggeredEvent@@YAPEAVCREvent@@XZ equ <__imp_?CRAppTriggeredEvent@@YAPEAVCREvent@@XZ>

externdef __imp_?CRApplyDXTransform@@YAPEAVCRDXTransformResult@@PEAUIUnknown@@JPEAPEAVCRBvr@@PEAV3@@Z:PPROC
?CRApplyDXTransform@@YAPEAVCRDXTransformResult@@PEAUIUnknown@@JPEAPEAVCRBvr@@PEAV3@@Z equ <__imp_?CRApplyDXTransform@@YAPEAVCRDXTransformResult@@PEAUIUnknown@@JPEAPEAVCRBvr@@PEAV3@@Z>

externdef __imp_?CRAqua@@YAPEAVCRColor@@XZ:PPROC
?CRAqua@@YAPEAVCRColor@@XZ equ <__imp_?CRAqua@@YAPEAVCRColor@@XZ>

externdef __imp_?CRArc@@YAPEAVCRPath2@@NNNN@Z:PPROC
?CRArc@@YAPEAVCRPath2@@NNNN@Z equ <__imp_?CRArc@@YAPEAVCRPath2@@NNNN@Z>

externdef __imp_?CRArcRadians@@YAPEAVCRPath2@@NNNN@Z:PPROC
?CRArcRadians@@YAPEAVCRPath2@@NNNN@Z equ <__imp_?CRArcRadians@@YAPEAVCRPath2@@NNNN@Z>

externdef __imp_?CRArcRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z:PPROC
?CRArcRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z equ <__imp_?CRArcRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z>

externdef __imp_?CRAsin@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRAsin@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRAsin@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRAtan2@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRAtan2@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRAtan2@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRAtan@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRAtan@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRAtan@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRAttachData@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z:PPROC
?CRAttachData@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z equ <__imp_?CRAttachData@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z>

externdef __imp_?CRBSpline@@YAPEAVCRBvr@@HJQEAPEAVCRNumber@@JQEAPEAV1@J0PEAV2@W4CR_BVR_TYPEID@@@Z:PPROC
?CRBSpline@@YAPEAVCRBvr@@HJQEAPEAVCRNumber@@JQEAPEAV1@J0PEAV2@W4CR_BVR_TYPEID@@@Z equ <__imp_?CRBSpline@@YAPEAVCRBvr@@HJQEAPEAVCRNumber@@JQEAPEAV1@J0PEAV2@W4CR_BVR_TYPEID@@@Z>

externdef __imp_?CRBillboard@@YAPEAVCRGeometry@@PEAV1@PEAVCRVector3@@@Z:PPROC
?CRBillboard@@YAPEAVCRGeometry@@PEAV1@PEAVCRVector3@@@Z equ <__imp_?CRBillboard@@YAPEAVCRGeometry@@PEAV1@PEAVCRVector3@@@Z>

externdef __imp_?CRBlack@@YAPEAVCRColor@@XZ:PPROC
?CRBlack@@YAPEAVCRColor@@XZ equ <__imp_?CRBlack@@YAPEAVCRColor@@XZ>

externdef __imp_?CRBlendTextureDiffuse@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z:PPROC
?CRBlendTextureDiffuse@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z equ <__imp_?CRBlendTextureDiffuse@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z>

externdef __imp_?CRBlue@@YAPEAVCRColor@@XZ:PPROC
?CRBlue@@YAPEAVCRColor@@XZ equ <__imp_?CRBlue@@YAPEAVCRColor@@XZ>

externdef __imp_?CRBold@@YAPEAVCRFontStyle@@PEAV1@@Z:PPROC
?CRBold@@YAPEAVCRFontStyle@@PEAV1@@Z equ <__imp_?CRBold@@YAPEAVCRFontStyle@@PEAV1@@Z>

externdef __imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRImage@@@Z:PPROC
?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRImage@@@Z equ <__imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRImage@@@Z>

externdef __imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRPath2@@PEAVCRLineStyle@@@Z:PPROC
?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRPath2@@PEAVCRLineStyle@@@Z equ <__imp_?CRBoundingBox@@YAPEAVCRBbox2@@PEAVCRPath2@@PEAVCRLineStyle@@@Z>

externdef __imp_?CRBoundingBox@@YAPEAVCRBbox3@@PEAVCRGeometry@@@Z:PPROC
?CRBoundingBox@@YAPEAVCRBbox3@@PEAVCRGeometry@@@Z equ <__imp_?CRBoundingBox@@YAPEAVCRBbox3@@PEAVCRGeometry@@@Z>

externdef __imp_?CRBvrApplyPreference@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z:PPROC
?CRBvrApplyPreference@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z equ <__imp_?CRBvrApplyPreference@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z>

externdef __imp_?CRBvrToCOM@@YA_NPEAVCRBvr@@AEBU_GUID@@PEAPEAX@Z:PPROC
?CRBvrToCOM@@YA_NPEAVCRBvr@@AEBU_GUID@@PEAPEAX@Z equ <__imp_?CRBvrToCOM@@YA_NPEAVCRBvr@@AEBU_GUID@@PEAPEAX@Z>

externdef __imp_?CRCeiling@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRCeiling@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRCeiling@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRClearLastError@@YAXXZ:PPROC
?CRClearLastError@@YAXXZ equ <__imp_?CRClearLastError@@YAXXZ>

externdef __imp_?CRClearMatte@@YAPEAVCRMatte@@XZ:PPROC
?CRClearMatte@@YAPEAVCRMatte@@XZ equ <__imp_?CRClearMatte@@YAPEAVCRMatte@@XZ>

externdef __imp_?CRClip@@YAPEAVCRImage@@PEAV1@PEAVCRMatte@@@Z:PPROC
?CRClip@@YAPEAVCRImage@@PEAV1@PEAVCRMatte@@@Z equ <__imp_?CRClip@@YAPEAVCRImage@@PEAV1@PEAVCRMatte@@@Z>

externdef __imp_?CRClipPolygonImage@@YAPEAVCRImage@@PEAV1@PEAVCRArray@@@Z:PPROC
?CRClipPolygonImage@@YAPEAVCRImage@@PEAV1@PEAVCRArray@@@Z equ <__imp_?CRClipPolygonImage@@YAPEAVCRImage@@PEAV1@PEAVCRArray@@@Z>

externdef __imp_?CRClose@@YAPEAVCRPath2@@PEAV1@@Z:PPROC
?CRClose@@YAPEAVCRPath2@@PEAV1@@Z equ <__imp_?CRClose@@YAPEAVCRPath2@@PEAV1@@Z>

externdef __imp_?CRColorHsl@@YAPEAVCRColor@@NNN@Z:PPROC
?CRColorHsl@@YAPEAVCRColor@@NNN@Z equ <__imp_?CRColorHsl@@YAPEAVCRColor@@NNN@Z>

externdef __imp_?CRColorHsl@@YAPEAVCRColor@@PEAVCRNumber@@00@Z:PPROC
?CRColorHsl@@YAPEAVCRColor@@PEAVCRNumber@@00@Z equ <__imp_?CRColorHsl@@YAPEAVCRColor@@PEAVCRNumber@@00@Z>

externdef __imp_?CRColorKey@@YAPEAVCRImage@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRColorKey@@YAPEAVCRImage@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRColorKey@@YAPEAVCRImage@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRColorRgb255@@YAPEAVCRColor@@FFF@Z:PPROC
?CRColorRgb255@@YAPEAVCRColor@@FFF@Z equ <__imp_?CRColorRgb255@@YAPEAVCRColor@@FFF@Z>

externdef __imp_?CRColorRgb@@YAPEAVCRColor@@NNN@Z:PPROC
?CRColorRgb@@YAPEAVCRColor@@NNN@Z equ <__imp_?CRColorRgb@@YAPEAVCRColor@@NNN@Z>

externdef __imp_?CRColorRgb@@YAPEAVCRColor@@PEAVCRNumber@@00@Z:PPROC
?CRColorRgb@@YAPEAVCRColor@@PEAVCRNumber@@00@Z equ <__imp_?CRColorRgb@@YAPEAVCRColor@@PEAVCRNumber@@00@Z>

externdef __imp_?CRCompose2@@YAPEAVCRTransform2@@PEAV1@0@Z:PPROC
?CRCompose2@@YAPEAVCRTransform2@@PEAV1@0@Z equ <__imp_?CRCompose2@@YAPEAVCRTransform2@@PEAV1@0@Z>

externdef __imp_?CRCompose2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z:PPROC
?CRCompose2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z equ <__imp_?CRCompose2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z>

externdef __imp_?CRCompose3@@YAPEAVCRTransform3@@PEAV1@0@Z:PPROC
?CRCompose3@@YAPEAVCRTransform3@@PEAV1@0@Z equ <__imp_?CRCompose3@@YAPEAVCRTransform3@@PEAV1@0@Z>

externdef __imp_?CRCompose3@@YAPEAVCRTransform3@@PEAVCRArray@@@Z:PPROC
?CRCompose3@@YAPEAVCRTransform3@@PEAVCRArray@@@Z equ <__imp_?CRCompose3@@YAPEAVCRTransform3@@PEAVCRArray@@@Z>

externdef __imp_?CRConcat@@YAPEAVCRPath2@@PEAV1@0@Z:PPROC
?CRConcat@@YAPEAVCRPath2@@PEAV1@0@Z equ <__imp_?CRConcat@@YAPEAVCRPath2@@PEAV1@0@Z>

externdef __imp_?CRConcat@@YAPEAVCRPath2@@PEAVCRArray@@@Z:PPROC
?CRConcat@@YAPEAVCRPath2@@PEAVCRArray@@@Z equ <__imp_?CRConcat@@YAPEAVCRPath2@@PEAVCRArray@@@Z>

externdef __imp_?CRConcatString@@YAPEAVCRString@@PEAV1@0@Z:PPROC
?CRConcatString@@YAPEAVCRString@@PEAV1@0@Z equ <__imp_?CRConcatString@@YAPEAVCRString@@PEAV1@0@Z>

externdef __imp_?CRCond@@YAPEAVCRBvr@@PEAVCRBoolean@@PEAV1@1@Z:PPROC
?CRCond@@YAPEAVCRBvr@@PEAVCRBoolean@@PEAV1@1@Z equ <__imp_?CRCond@@YAPEAVCRBvr@@PEAVCRBoolean@@PEAV1@1@Z>

externdef __imp_?CRConnect@@YA_NPEAUHINSTANCE__@@@Z:PPROC
?CRConnect@@YA_NPEAUHINSTANCE__@@@Z equ <__imp_?CRConnect@@YA_NPEAUHINSTANCE__@@@Z>

externdef __imp_?CRCos@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRCos@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRCos@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRCreateArray@@YAPEAVCRArray@@JQEANW4CR_BVR_TYPEID@@@Z:PPROC
?CRCreateArray@@YAPEAVCRArray@@JQEANW4CR_BVR_TYPEID@@@Z equ <__imp_?CRCreateArray@@YAPEAVCRArray@@JQEANW4CR_BVR_TYPEID@@@Z>

externdef __imp_?CRCreateArray@@YAPEAVCRArray@@JQEAPEAVCRBvr@@K@Z:PPROC
?CRCreateArray@@YAPEAVCRArray@@JQEAPEAVCRBvr@@K@Z equ <__imp_?CRCreateArray@@YAPEAVCRArray@@JQEAPEAVCRBvr@@K@Z>

externdef __imp_?CRCreateBoolean@@YAPEAVCRBoolean@@_N@Z:PPROC
?CRCreateBoolean@@YAPEAVCRBoolean@@_N@Z equ <__imp_?CRCreateBoolean@@YAPEAVCRBoolean@@_N@Z>

externdef __imp_?CRCreateNumber@@YAPEAVCRNumber@@N@Z:PPROC
?CRCreateNumber@@YAPEAVCRNumber@@N@Z equ <__imp_?CRCreateNumber@@YAPEAVCRNumber@@N@Z>

externdef __imp_?CRCreatePoint2@@YAPEAVCRPoint2@@NN@Z:PPROC
?CRCreatePoint2@@YAPEAVCRPoint2@@NN@Z equ <__imp_?CRCreatePoint2@@YAPEAVCRPoint2@@NN@Z>

externdef __imp_?CRCreatePoint2@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z:PPROC
?CRCreatePoint2@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z equ <__imp_?CRCreatePoint2@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRCreatePoint3@@YAPEAVCRPoint3@@NNN@Z:PPROC
?CRCreatePoint3@@YAPEAVCRPoint3@@NNN@Z equ <__imp_?CRCreatePoint3@@YAPEAVCRPoint3@@NNN@Z>

externdef __imp_?CRCreatePoint3@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z:PPROC
?CRCreatePoint3@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z equ <__imp_?CRCreatePoint3@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z>

externdef __imp_?CRCreateString@@YAPEAVCRString@@PEAG@Z:PPROC
?CRCreateString@@YAPEAVCRString@@PEAG@Z equ <__imp_?CRCreateString@@YAPEAVCRString@@PEAG@Z>

externdef __imp_?CRCreateTuple@@YAPEAVCRTuple@@JQEAPEAVCRBvr@@@Z:PPROC
?CRCreateTuple@@YAPEAVCRTuple@@JQEAPEAVCRBvr@@@Z equ <__imp_?CRCreateTuple@@YAPEAVCRTuple@@JQEAPEAVCRBvr@@@Z>

externdef __imp_?CRCreateUserData@@YAPEAVCRUserData@@PEAUIUnknown@@@Z:PPROC
?CRCreateUserData@@YAPEAVCRUserData@@PEAUIUnknown@@@Z equ <__imp_?CRCreateUserData@@YAPEAVCRUserData@@PEAUIUnknown@@@Z>

externdef __imp_?CRCreateVector2@@YAPEAVCRVector2@@NN@Z:PPROC
?CRCreateVector2@@YAPEAVCRVector2@@NN@Z equ <__imp_?CRCreateVector2@@YAPEAVCRVector2@@NN@Z>

externdef __imp_?CRCreateVector2@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z:PPROC
?CRCreateVector2@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z equ <__imp_?CRCreateVector2@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRCreateVector3@@YAPEAVCRVector3@@NNN@Z:PPROC
?CRCreateVector3@@YAPEAVCRVector3@@NNN@Z equ <__imp_?CRCreateVector3@@YAPEAVCRVector3@@NNN@Z>

externdef __imp_?CRCreateVector3@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z:PPROC
?CRCreateVector3@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z equ <__imp_?CRCreateVector3@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z>

externdef __imp_?CRCreateView@@YAPEAVCRView@@XZ:PPROC
?CRCreateView@@YAPEAVCRView@@XZ equ <__imp_?CRCreateView@@YAPEAVCRView@@XZ>

externdef __imp_?CRCrop@@YAPEAVCRImage@@PEAV1@PEAVCRPoint2@@1@Z:PPROC
?CRCrop@@YAPEAVCRImage@@PEAV1@PEAVCRPoint2@@1@Z equ <__imp_?CRCrop@@YAPEAVCRImage@@PEAV1@PEAVCRPoint2@@1@Z>

externdef __imp_?CRCross@@YAPEAVCRVector3@@PEAV1@0@Z:PPROC
?CRCross@@YAPEAVCRVector3@@PEAV1@0@Z equ <__imp_?CRCross@@YAPEAVCRVector3@@PEAV1@0@Z>

externdef __imp_?CRCubicBSplinePath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z:PPROC
?CRCubicBSplinePath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z equ <__imp_?CRCubicBSplinePath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z>

externdef __imp_?CRCyan@@YAPEAVCRColor@@XZ:PPROC
?CRCyan@@YAPEAVCRColor@@XZ equ <__imp_?CRCyan@@YAPEAVCRColor@@XZ>

externdef __imp_?CRD3DRMTexture@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@@Z:PPROC
?CRD3DRMTexture@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@@Z equ <__imp_?CRD3DRMTexture@@YAPEAVCRGeometry@@PEAV1@PEAUIUnknown@@@Z>

externdef __imp_?CRDash@@YAPEAVCRLineStyle@@PEAV1@PEAVCRDashStyle@@@Z:PPROC
?CRDash@@YAPEAVCRLineStyle@@PEAV1@PEAVCRDashStyle@@@Z equ <__imp_?CRDash@@YAPEAVCRLineStyle@@PEAV1@PEAVCRDashStyle@@@Z>

externdef __imp_?CRDashEx@@YAPEAVCRLineStyle@@PEAV1@K@Z:PPROC
?CRDashEx@@YAPEAVCRLineStyle@@PEAV1@K@Z equ <__imp_?CRDashEx@@YAPEAVCRLineStyle@@PEAV1@K@Z>

externdef __imp_?CRDashStyleDashed@@YAPEAVCRDashStyle@@XZ:PPROC
?CRDashStyleDashed@@YAPEAVCRDashStyle@@XZ equ <__imp_?CRDashStyleDashed@@YAPEAVCRDashStyle@@XZ>

externdef __imp_?CRDashStyleSolid@@YAPEAVCRDashStyle@@XZ:PPROC
?CRDashStyleSolid@@YAPEAVCRDashStyle@@XZ equ <__imp_?CRDashStyleSolid@@YAPEAVCRDashStyle@@XZ>

externdef __imp_?CRDefaultFont@@YAPEAVCRFontStyle@@XZ:PPROC
?CRDefaultFont@@YAPEAVCRFontStyle@@XZ equ <__imp_?CRDefaultFont@@YAPEAVCRFontStyle@@XZ>

externdef __imp_?CRDefaultLineStyle@@YAPEAVCRLineStyle@@XZ:PPROC
?CRDefaultLineStyle@@YAPEAVCRLineStyle@@XZ equ <__imp_?CRDefaultLineStyle@@YAPEAVCRLineStyle@@XZ>

externdef __imp_?CRDefaultMicrophone@@YAPEAVCRMicrophone@@XZ:PPROC
?CRDefaultMicrophone@@YAPEAVCRMicrophone@@XZ equ <__imp_?CRDefaultMicrophone@@YAPEAVCRMicrophone@@XZ>

externdef __imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@N@Z:PPROC
?CRDepth@@YAPEAVCRCamera@@PEAV1@N@Z equ <__imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@N@Z>

externdef __imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRDepth@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRDepth@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@N@Z:PPROC
?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@N@Z equ <__imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@N@Z>

externdef __imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRDepthResolution@@YAPEAVCRCamera@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRDerivative@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRDerivative@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRDerivative@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRDerivative@@YAPEAVCRVector2@@PEAV1@@Z:PPROC
?CRDerivative@@YAPEAVCRVector2@@PEAV1@@Z equ <__imp_?CRDerivative@@YAPEAVCRVector2@@PEAV1@@Z>

externdef __imp_?CRDerivative@@YAPEAVCRVector2@@PEAVCRPoint2@@@Z:PPROC
?CRDerivative@@YAPEAVCRVector2@@PEAVCRPoint2@@@Z equ <__imp_?CRDerivative@@YAPEAVCRVector2@@PEAVCRPoint2@@@Z>

externdef __imp_?CRDerivative@@YAPEAVCRVector3@@PEAV1@@Z:PPROC
?CRDerivative@@YAPEAVCRVector3@@PEAV1@@Z equ <__imp_?CRDerivative@@YAPEAVCRVector3@@PEAV1@@Z>

externdef __imp_?CRDerivative@@YAPEAVCRVector3@@PEAVCRPoint3@@@Z:PPROC
?CRDerivative@@YAPEAVCRVector3@@PEAVCRPoint3@@@Z equ <__imp_?CRDerivative@@YAPEAVCRVector3@@PEAVCRPoint3@@@Z>

externdef __imp_?CRDestroyView@@YAXPEAVCRView@@@Z:PPROC
?CRDestroyView@@YAXPEAVCRView@@@Z equ <__imp_?CRDestroyView@@YAXPEAVCRView@@@Z>

externdef __imp_?CRDetail@@YAPEAVCRLineStyle@@PEAV1@@Z:PPROC
?CRDetail@@YAPEAVCRLineStyle@@PEAV1@@Z equ <__imp_?CRDetail@@YAPEAVCRLineStyle@@PEAV1@@Z>

externdef __imp_?CRDetectableEmptyImage@@YAPEAVCRImage@@XZ:PPROC
?CRDetectableEmptyImage@@YAPEAVCRImage@@XZ equ <__imp_?CRDetectableEmptyImage@@YAPEAVCRImage@@XZ>

externdef __imp_?CRDifferenceMatte@@YAPEAVCRMatte@@PEAV1@0@Z:PPROC
?CRDifferenceMatte@@YAPEAVCRMatte@@PEAV1@0@Z equ <__imp_?CRDifferenceMatte@@YAPEAVCRMatte@@PEAV1@0@Z>

externdef __imp_?CRDiffuseColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRDiffuseColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRDiffuseColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRDirectionalLight@@YAPEAVCRGeometry@@XZ:PPROC
?CRDirectionalLight@@YAPEAVCRGeometry@@XZ equ <__imp_?CRDirectionalLight@@YAPEAVCRGeometry@@XZ>

externdef __imp_?CRDisconnect@@YA_NPEAUHINSTANCE__@@@Z:PPROC
?CRDisconnect@@YA_NPEAUHINSTANCE__@@@Z equ <__imp_?CRDisconnect@@YA_NPEAUHINSTANCE__@@@Z>

externdef __imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z:PPROC
?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z equ <__imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z>

externdef __imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z:PPROC
?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z equ <__imp_?CRDistance@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z>

externdef __imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z:PPROC
?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z equ <__imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint2@@0@Z>

externdef __imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z:PPROC
?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z equ <__imp_?CRDistanceSquared@@YAPEAVCRNumber@@PEAVCRPoint3@@0@Z>

externdef __imp_?CRDiv@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRDiv@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRDiv@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@N@Z:PPROC
?CRDiv@@YAPEAVCRVector2@@PEAV1@N@Z equ <__imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@N@Z>

externdef __imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRDiv@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRDiv@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@N@Z:PPROC
?CRDiv@@YAPEAVCRVector3@@PEAV1@N@Z equ <__imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@N@Z>

externdef __imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRDiv@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRDiv@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRDoGC@@YA_NXZ:PPROC
?CRDoGC@@YA_NXZ equ <__imp_?CRDoGC@@YA_NXZ>

externdef __imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector2@@0@Z:PPROC
?CRDot@@YAPEAVCRNumber@@PEAVCRVector2@@0@Z equ <__imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector2@@0@Z>

externdef __imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector3@@0@Z:PPROC
?CRDot@@YAPEAVCRNumber@@PEAVCRVector3@@0@Z equ <__imp_?CRDot@@YAPEAVCRNumber@@PEAVCRVector3@@0@Z>

externdef __imp_?CRDraw@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@@Z:PPROC
?CRDraw@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@@Z equ <__imp_?CRDraw@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@@Z>

externdef __imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@N@Z:PPROC
?CRDuration@@YAPEAVCRBvr@@PEAV1@N@Z equ <__imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@N@Z>

externdef __imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRDuration@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRDuration@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CREQ@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PPROC
?CREQ@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z equ <__imp_?CREQ@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>

externdef __imp_?CREmissiveColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PPROC
?CREmissiveColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CREmissiveColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CREmptyColor@@YAPEAVCRColor@@XZ:PPROC
?CREmptyColor@@YAPEAVCRColor@@XZ equ <__imp_?CREmptyColor@@YAPEAVCRColor@@XZ>

externdef __imp_?CREmptyGeometry@@YAPEAVCRGeometry@@XZ:PPROC
?CREmptyGeometry@@YAPEAVCRGeometry@@XZ equ <__imp_?CREmptyGeometry@@YAPEAVCRGeometry@@XZ>

externdef __imp_?CREmptyImage@@YAPEAVCRImage@@XZ:PPROC
?CREmptyImage@@YAPEAVCRImage@@XZ equ <__imp_?CREmptyImage@@YAPEAVCRImage@@XZ>

externdef __imp_?CREmptyLineStyle@@YAPEAVCRLineStyle@@XZ:PPROC
?CREmptyLineStyle@@YAPEAVCRLineStyle@@XZ equ <__imp_?CREmptyLineStyle@@YAPEAVCRLineStyle@@XZ>

externdef __imp_?CREmptyMontage@@YAPEAVCRMontage@@XZ:PPROC
?CREmptyMontage@@YAPEAVCRMontage@@XZ equ <__imp_?CREmptyMontage@@YAPEAVCRMontage@@XZ>

externdef __imp_?CREnd@@YAPEAVCRLineStyle@@PEAV1@PEAVCREndStyle@@@Z:PPROC
?CREnd@@YAPEAVCRLineStyle@@PEAV1@PEAVCREndStyle@@@Z equ <__imp_?CREnd@@YAPEAVCRLineStyle@@PEAV1@PEAVCREndStyle@@@Z>

externdef __imp_?CREndEvent@@YAPEAVCRBvr@@PEAV1@@Z:PPROC
?CREndEvent@@YAPEAVCRBvr@@PEAV1@@Z equ <__imp_?CREndEvent@@YAPEAVCRBvr@@PEAV1@@Z>

externdef __imp_?CREndEx@@YAPEAVCRLineStyle@@PEAV1@K@Z:PPROC
?CREndEx@@YAPEAVCRLineStyle@@PEAV1@K@Z equ <__imp_?CREndEx@@YAPEAVCRLineStyle@@PEAV1@K@Z>

externdef __imp_?CREndStyleFlat@@YAPEAVCREndStyle@@XZ:PPROC
?CREndStyleFlat@@YAPEAVCREndStyle@@XZ equ <__imp_?CREndStyleFlat@@YAPEAVCREndStyle@@XZ>

externdef __imp_?CREndStyleRound@@YAPEAVCREndStyle@@XZ:PPROC
?CREndStyleRound@@YAPEAVCREndStyle@@XZ equ <__imp_?CREndStyleRound@@YAPEAVCREndStyle@@XZ>

externdef __imp_?CREndStyleSquare@@YAPEAVCREndStyle@@XZ:PPROC
?CREndStyleSquare@@YAPEAVCREndStyle@@XZ equ <__imp_?CREndStyleSquare@@YAPEAVCREndStyle@@XZ>

externdef __imp_?CRExp@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRExp@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRExp@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRExtendedAttrib@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z:PPROC
?CRExtendedAttrib@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z equ <__imp_?CRExtendedAttrib@@YAPEAVCRBvr@@PEAV1@PEAGUtagVARIANT@@@Z>

externdef __imp_?CRExtract@@YANPEAVCRNumber@@@Z:PPROC
?CRExtract@@YANPEAVCRNumber@@@Z equ <__imp_?CRExtract@@YANPEAVCRNumber@@@Z>

externdef __imp_?CRExtract@@YAPEAGPEAVCRString@@@Z:PPROC
?CRExtract@@YAPEAGPEAVCRString@@@Z equ <__imp_?CRExtract@@YAPEAGPEAVCRString@@@Z>

externdef __imp_?CRExtract@@YA_NPEAVCRBoolean@@@Z:PPROC
?CRExtract@@YA_NPEAVCRBoolean@@@Z equ <__imp_?CRExtract@@YA_NPEAVCRBoolean@@@Z>

externdef __imp_?CRFalse@@YAPEAVCRBoolean@@XZ:PPROC
?CRFalse@@YAPEAVCRBoolean@@XZ equ <__imp_?CRFalse@@YAPEAVCRBoolean@@XZ>

externdef __imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAG@Z:PPROC
?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAG@Z equ <__imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAG@Z>

externdef __imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAVCRString@@@Z:PPROC
?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAVCRString@@@Z equ <__imp_?CRFamily@@YAPEAVCRFontStyle@@PEAV1@PEAVCRString@@@Z>

externdef __imp_?CRFill@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@PEAV1@@Z:PPROC
?CRFill@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@PEAV1@@Z equ <__imp_?CRFill@@YAPEAVCRImage@@PEAVCRPath2@@PEAVCRLineStyle@@PEAV1@@Z>

externdef __imp_?CRFillMatte@@YAPEAVCRMatte@@PEAVCRPath2@@@Z:PPROC
?CRFillMatte@@YAPEAVCRMatte@@PEAVCRPath2@@@Z equ <__imp_?CRFillMatte@@YAPEAVCRMatte@@PEAVCRPath2@@@Z>

externdef __imp_?CRFirst@@YAPEAVCRBvr@@PEAVCRPair@@@Z:PPROC
?CRFirst@@YAPEAVCRBvr@@PEAVCRPair@@@Z equ <__imp_?CRFirst@@YAPEAVCRBvr@@PEAVCRPair@@@Z>

externdef __imp_?CRFloor@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRFloor@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRFloor@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z:PPROC
?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z equ <__imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z>

externdef __imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PPROC
?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z equ <__imp_?CRFollowPath@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>

externdef __imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z:PPROC
?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z equ <__imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z>

externdef __imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PPROC
?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z equ <__imp_?CRFollowPathAngle@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>

externdef __imp_?CRFollowPathAngleEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PPROC
?CRFollowPathAngleEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z equ <__imp_?CRFollowPathAngleEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>

externdef __imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z:PPROC
?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z equ <__imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@N@Z>

externdef __imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PPROC
?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z equ <__imp_?CRFollowPathAngleUpright@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>

externdef __imp_?CRFollowPathAngleUprightEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PPROC
?CRFollowPathAngleUprightEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z equ <__imp_?CRFollowPathAngleUprightEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>

externdef __imp_?CRFollowPathEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z:PPROC
?CRFollowPathEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z equ <__imp_?CRFollowPathEval@@YAPEAVCRTransform2@@PEAVCRPath2@@PEAVCRNumber@@@Z>

externdef __imp_?CRFont@@YAPEAVCRFontStyle@@PEAGNPEAVCRColor@@@Z:PPROC
?CRFont@@YAPEAVCRFontStyle@@PEAGNPEAVCRColor@@@Z equ <__imp_?CRFont@@YAPEAVCRFontStyle@@PEAGNPEAVCRColor@@@Z>

externdef __imp_?CRFont@@YAPEAVCRFontStyle@@PEAVCRString@@PEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRFont@@YAPEAVCRFontStyle@@PEAVCRString@@PEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRFont@@YAPEAVCRFontStyle@@PEAVCRString@@PEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRFuchsia@@YAPEAVCRColor@@XZ:PPROC
?CRFuchsia@@YAPEAVCRColor@@XZ equ <__imp_?CRFuchsia@@YAPEAVCRColor@@XZ>

externdef __imp_?CRGT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PPROC
?CRGT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z equ <__imp_?CRGT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>

externdef __imp_?CRGTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PPROC
?CRGTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z equ <__imp_?CRGTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>

externdef __imp_?CRGain@@YAPEAVCRSound@@PEAV1@N@Z:PPROC
?CRGain@@YAPEAVCRSound@@PEAV1@N@Z equ <__imp_?CRGain@@YAPEAVCRSound@@PEAV1@N@Z>

externdef __imp_?CRGain@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRGain@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRGain@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRGetArrayTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z:PPROC
?CRGetArrayTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z equ <__imp_?CRGetArrayTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z>

externdef __imp_?CRGetBlue@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRGetBlue@@YAPEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRGetBlue@@YAPEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRGetCompletionEvent@@YAPEAVCREvent@@PEAVCRImportationResult@@@Z:PPROC
?CRGetCompletionEvent@@YAPEAVCREvent@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetCompletionEvent@@YAPEAVCREvent@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetCompositeDirectlyToTarget@@YA_NPEAVCRView@@@Z:PPROC
?CRGetCompositeDirectlyToTarget@@YA_NPEAVCRView@@@Z equ <__imp_?CRGetCompositeDirectlyToTarget@@YA_NPEAVCRView@@@Z>

externdef __imp_?CRGetConstDuration@@YANPEAVCREvent@@@Z:PPROC
?CRGetConstDuration@@YANPEAVCREvent@@@Z equ <__imp_?CRGetConstDuration@@YANPEAVCREvent@@@Z>

externdef __imp_?CRGetDC@@YAPEAUHDC__@@PEAVCRView@@@Z:PPROC
?CRGetDC@@YAPEAUHDC__@@PEAVCRView@@@Z equ <__imp_?CRGetDC@@YAPEAUHDC__@@PEAVCRView@@@Z>

externdef __imp_?CRGetDDD3DRM@@YA_NPEAVCRView@@PEAPEAUIUnknown@@1@Z:PPROC
?CRGetDDD3DRM@@YA_NPEAVCRView@@PEAPEAUIUnknown@@1@Z equ <__imp_?CRGetDDD3DRM@@YA_NPEAVCRView@@PEAPEAUIUnknown@@1@Z>

externdef __imp_?CRGetData@@YAPEAUIUnknown@@PEAVCRUserData@@@Z:PPROC
?CRGetData@@YAPEAUIUnknown@@PEAVCRUserData@@@Z equ <__imp_?CRGetData@@YAPEAUIUnknown@@PEAVCRUserData@@@Z>

externdef __imp_?CRGetDirectDrawSurface@@YAPEAUIUnknown@@PEAVCRView@@@Z:PPROC
?CRGetDirectDrawSurface@@YAPEAUIUnknown@@PEAVCRView@@@Z equ <__imp_?CRGetDirectDrawSurface@@YAPEAUIUnknown@@PEAVCRView@@@Z>

externdef __imp_?CRGetDuration@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z:PPROC
?CRGetDuration@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetDuration@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetElement@@YAPEAVCRBvr@@PEAVCRArray@@J@Z:PPROC
?CRGetElement@@YAPEAVCRBvr@@PEAVCRArray@@J@Z equ <__imp_?CRGetElement@@YAPEAVCRBvr@@PEAVCRArray@@J@Z>

externdef __imp_?CRGetEvent@@YAPEAVCREvent@@PEAVCRPickableResult@@@Z:PPROC
?CRGetEvent@@YAPEAVCREvent@@PEAVCRPickableResult@@@Z equ <__imp_?CRGetEvent@@YAPEAVCREvent@@PEAVCRPickableResult@@@Z>

externdef __imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRImportationResult@@@Z:PPROC
?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRPickableResult@@@Z:PPROC
?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRPickableResult@@@Z equ <__imp_?CRGetGeometry@@YAPEAVCRGeometry@@PEAVCRPickableResult@@@Z>

externdef __imp_?CRGetGreen@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRGetGreen@@YAPEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRGetGreen@@YAPEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRGetHue@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRGetHue@@YAPEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRGetHue@@YAPEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRImportationResult@@@Z:PPROC
?CRGetImage@@YAPEAVCRImage@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRPickableResult@@@Z:PPROC
?CRGetImage@@YAPEAVCRImage@@PEAVCRPickableResult@@@Z equ <__imp_?CRGetImage@@YAPEAVCRImage@@PEAVCRPickableResult@@@Z>

externdef __imp_?CRGetImportPriority@@YAMPEAVCRBvr@@@Z:PPROC
?CRGetImportPriority@@YAMPEAVCRBvr@@@Z equ <__imp_?CRGetImportPriority@@YAMPEAVCRBvr@@@Z>

externdef __imp_?CRGetInvalidatedRects@@YAJPEAVCRView@@KJPEAUtagRECT@@@Z:PPROC
?CRGetInvalidatedRects@@YAJPEAVCRView@@KJPEAUtagRECT@@@Z equ <__imp_?CRGetInvalidatedRects@@YAJPEAVCRView@@KJPEAUtagRECT@@@Z>

externdef __imp_?CRGetLastError@@YAJXZ:PPROC
?CRGetLastError@@YAJXZ equ <__imp_?CRGetLastError@@YAJXZ>

externdef __imp_?CRGetLastErrorString@@YAPEBGXZ:PPROC
?CRGetLastErrorString@@YAPEBGXZ equ <__imp_?CRGetLastErrorString@@YAPEBGXZ>

externdef __imp_?CRGetLightness@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRGetLightness@@YAPEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRGetLightness@@YAPEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRGetModifiableBvr@@YAPEAVCRBvr@@PEAV1@@Z:PPROC
?CRGetModifiableBvr@@YAPEAVCRBvr@@PEAV1@@Z equ <__imp_?CRGetModifiableBvr@@YAPEAVCRBvr@@PEAV1@@Z>

externdef __imp_?CRGetOutputBvr@@YAPEAVCRBvr@@PEAVCRDXTransformResult@@@Z:PPROC
?CRGetOutputBvr@@YAPEAVCRBvr@@PEAVCRDXTransformResult@@@Z equ <__imp_?CRGetOutputBvr@@YAPEAVCRBvr@@PEAVCRDXTransformResult@@@Z>

externdef __imp_?CRGetPreference@@YA_NPEAVCRView@@PEAGPEAUtagVARIANT@@@Z:PPROC
?CRGetPreference@@YA_NPEAVCRView@@PEAGPEAUtagVARIANT@@@Z equ <__imp_?CRGetPreference@@YA_NPEAVCRView@@PEAGPEAUtagVARIANT@@@Z>

externdef __imp_?CRGetProgress@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z:PPROC
?CRGetProgress@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetProgress@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetRMDevice@@YA_NPEAVCRView@@PEAPEAUIUnknown@@PEAK@Z:PPROC
?CRGetRMDevice@@YA_NPEAVCRView@@PEAPEAUIUnknown@@PEAK@Z equ <__imp_?CRGetRMDevice@@YA_NPEAVCRView@@PEAPEAUIUnknown@@PEAK@Z>

externdef __imp_?CRGetRed@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRGetRed@@YAPEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRGetRed@@YAPEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRGetSaturation@@YAPEAVCRNumber@@PEAVCRColor@@@Z:PPROC
?CRGetSaturation@@YAPEAVCRNumber@@PEAVCRColor@@@Z equ <__imp_?CRGetSaturation@@YAPEAVCRNumber@@PEAVCRColor@@@Z>

externdef __imp_?CRGetServiceProvider@@YAPEAUIServiceProvider@@PEAVCRView@@@Z:PPROC
?CRGetServiceProvider@@YAPEAUIServiceProvider@@PEAVCRView@@@Z equ <__imp_?CRGetServiceProvider@@YAPEAUIServiceProvider@@PEAVCRView@@@Z>

externdef __imp_?CRGetSimulationTime@@YANPEAVCRView@@@Z:PPROC
?CRGetSimulationTime@@YANPEAVCRView@@@Z equ <__imp_?CRGetSimulationTime@@YANPEAVCRView@@@Z>

externdef __imp_?CRGetSite@@YAPEAVCRViewSite@@PEAVCRView@@@Z:PPROC
?CRGetSite@@YAPEAVCRViewSite@@PEAVCRView@@@Z equ <__imp_?CRGetSite@@YAPEAVCRViewSite@@PEAVCRView@@@Z>

externdef __imp_?CRGetSize@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z:PPROC
?CRGetSize@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetSize@@YAPEAVCRNumber@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetSound@@YAPEAVCRSound@@PEAVCRImportationResult@@@Z:PPROC
?CRGetSound@@YAPEAVCRSound@@PEAVCRImportationResult@@@Z equ <__imp_?CRGetSound@@YAPEAVCRSound@@PEAVCRImportationResult@@@Z>

externdef __imp_?CRGetTransform@@YAPEAUIUnknown@@PEAVCRDXTransformResult@@@Z:PPROC
?CRGetTransform@@YAPEAUIUnknown@@PEAVCRDXTransformResult@@@Z equ <__imp_?CRGetTransform@@YAPEAUIUnknown@@PEAVCRDXTransformResult@@@Z>

externdef __imp_?CRGetTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z:PPROC
?CRGetTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z equ <__imp_?CRGetTypeId@@YA?AW4CR_BVR_TYPEID@@PEAVCRBvr@@@Z>

externdef __imp_?CRGetWindow@@YAPEAUHWND__@@PEAVCRView@@@Z:PPROC
?CRGetWindow@@YAPEAUHWND__@@PEAVCRView@@@Z equ <__imp_?CRGetWindow@@YAPEAUHWND__@@PEAVCRView@@@Z>

externdef __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PPROC
?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z equ <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>

externdef __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PPROC
?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z equ <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>

externdef __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PPROC
?CRGetX@@YAPEAVCRNumber@@PEAVCRVector2@@@Z equ <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>

externdef __imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRGetX@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRGetX@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PPROC
?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z equ <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>

externdef __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PPROC
?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z equ <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>

externdef __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PPROC
?CRGetY@@YAPEAVCRNumber@@PEAVCRVector2@@@Z equ <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>

externdef __imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRGetY@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRGetY@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PPROC
?CRGetZ@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z equ <__imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>

externdef __imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRGetZ@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRGetZ@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRGlobalTime@@YAPEAVCRNumber@@XZ:PPROC
?CRGlobalTime@@YAPEAVCRNumber@@XZ equ <__imp_?CRGlobalTime@@YAPEAVCRNumber@@XZ>

externdef __imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0N@Z:PPROC
?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0N@Z equ <__imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0N@Z>

externdef __imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z:PPROC
?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z equ <__imp_?CRGradientHorizontal@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z>

externdef __imp_?CRGradientPolygon@@YAPEAVCRImage@@PEAVCRArray@@0@Z:PPROC
?CRGradientPolygon@@YAPEAVCRImage@@PEAVCRArray@@0@Z equ <__imp_?CRGradientPolygon@@YAPEAVCRImage@@PEAVCRArray@@0@Z>

externdef __imp_?CRGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@000@Z:PPROC
?CRGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@000@Z equ <__imp_?CRGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@000@Z>

externdef __imp_?CRGray@@YAPEAVCRColor@@XZ:PPROC
?CRGray@@YAPEAVCRColor@@XZ equ <__imp_?CRGray@@YAPEAVCRColor@@XZ>

externdef __imp_?CRGreen@@YAPEAVCRColor@@XZ:PPROC
?CRGreen@@YAPEAVCRColor@@XZ equ <__imp_?CRGreen@@YAPEAVCRColor@@XZ>

externdef __imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PPROC
?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z equ <__imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z>

externdef __imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PPROC
?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z equ <__imp_?CRHatchBackwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>

externdef __imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PPROC
?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z equ <__imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z>

externdef __imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PPROC
?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z equ <__imp_?CRHatchCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>

externdef __imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PPROC
?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z equ <__imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@N@Z>

externdef __imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PPROC
?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z equ <__imp_?CRHatchDiagonalCross@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>

externdef __imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PPROC
?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z equ <__imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@N@Z>

externdef __imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PPROC
?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z equ <__imp_?CRHatchForwardDiagonal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>

externdef __imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PPROC
?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@N@Z equ <__imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@N@Z>

externdef __imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PPROC
?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z equ <__imp_?CRHatchHorizontal@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>

externdef __imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@N@Z:PPROC
?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@N@Z equ <__imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@N@Z>

externdef __imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z:PPROC
?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z equ <__imp_?CRHatchVertical@@YAPEAVCRImage@@PEAVCRColor@@PEAVCRNumber@@@Z>

externdef __imp_?CRHook@@YAPEAVCRBvr@@PEAV1@PEAVCRBvrHook@@@Z:PPROC
?CRHook@@YAPEAVCRBvr@@PEAV1@PEAVCRBvrHook@@@Z equ <__imp_?CRHook@@YAPEAVCRBvr@@PEAV1@PEAVCRBvrHook@@@Z>

externdef __imp_?CRIdentityTransform2@@YAPEAVCRTransform2@@XZ:PPROC
?CRIdentityTransform2@@YAPEAVCRTransform2@@XZ equ <__imp_?CRIdentityTransform2@@YAPEAVCRTransform2@@XZ>

externdef __imp_?CRIdentityTransform3@@YAPEAVCRTransform3@@XZ:PPROC
?CRIdentityTransform3@@YAPEAVCRTransform3@@XZ equ <__imp_?CRIdentityTransform3@@YAPEAVCRTransform3@@XZ>

externdef __imp_?CRImageMontage@@YAPEAVCRMontage@@PEAVCRImage@@N@Z:PPROC
?CRImageMontage@@YAPEAVCRMontage@@PEAVCRImage@@N@Z equ <__imp_?CRImageMontage@@YAPEAVCRMontage@@PEAVCRImage@@N@Z>

externdef __imp_?CRImageMontageAnim@@YAPEAVCRMontage@@PEAVCRImage@@PEAVCRNumber@@@Z:PPROC
?CRImageMontageAnim@@YAPEAVCRMontage@@PEAVCRImage@@PEAVCRNumber@@@Z equ <__imp_?CRImageMontageAnim@@YAPEAVCRMontage@@PEAVCRImage@@PEAVCRNumber@@@Z>

externdef __imp_?CRImageQuality@@YAPEAVCRImage@@PEAV1@K@Z:PPROC
?CRImageQuality@@YAPEAVCRImage@@PEAV1@K@Z equ <__imp_?CRImageQuality@@YAPEAVCRImage@@PEAV1@K@Z>

externdef __imp_?CRImportCancel@@YA_NPEAVCRBvr@@@Z:PPROC
?CRImportCancel@@YA_NPEAVCRBvr@@@Z equ <__imp_?CRImportCancel@@YA_NPEAVCRBvr@@@Z>

externdef __imp_?CRImportDirect3DRMVisual@@YAPEAVCRGeometry@@PEAUIUnknown@@@Z:PPROC
?CRImportDirect3DRMVisual@@YAPEAVCRGeometry@@PEAUIUnknown@@@Z equ <__imp_?CRImportDirect3DRMVisual@@YAPEAVCRGeometry@@PEAUIUnknown@@@Z>

externdef __imp_?CRImportDirect3DRMVisualWrapped@@YAPEAVCRGeometry@@PEAUIUnknown@@JNNNNNNNNNNNNNK@Z:PPROC
?CRImportDirect3DRMVisualWrapped@@YAPEAVCRGeometry@@PEAUIUnknown@@JNNNNNNNNNNNNNK@Z equ <__imp_?CRImportDirect3DRMVisualWrapped@@YAPEAVCRGeometry@@PEAUIUnknown@@JNNNNNNNNNNNNNK@Z>

externdef __imp_?CRImportDirectDrawSurface@@YAPEAVCRImage@@PEAUIUnknown@@PEAVCREvent@@@Z:PPROC
?CRImportDirectDrawSurface@@YAPEAVCRImage@@PEAUIUnknown@@PEAVCREvent@@@Z equ <__imp_?CRImportDirectDrawSurface@@YAPEAVCRImage@@PEAUIUnknown@@PEAVCREvent@@@Z>

externdef __imp_?CRImportGeometry@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6@Z:PPROC
?CRImportGeometry@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6@Z equ <__imp_?CRImportGeometry@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6@Z>

externdef __imp_?CRImportGeometryWrapped@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6JNNNNNNNNNNNNNK@Z:PPROC
?CRImportGeometryWrapped@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6JNNNNNNNNNNNNNK@Z equ <__imp_?CRImportGeometryWrapped@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@PEAVCRGeometry@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@6JNNNNNNNNNNNNNK@Z>

externdef __imp_?CRImportImage@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NEEEPEAVCRImage@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@7@Z:PPROC
?CRImportImage@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NEEEPEAVCRImage@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@7@Z equ <__imp_?CRImportImage@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NEEEPEAVCRImage@@PEAPEAV3@PEAPEAVCREvent@@PEAPEAVCRNumber@@7@Z>

externdef __imp_?CRImportMedia@@YAPEAVCRImportationResult@@PEAGPEAXW4CR_MEDIA_SOURCE@@QEAPEAXKPEAVCRImportSite@@@Z:PPROC
?CRImportMedia@@YAPEAVCRImportationResult@@PEAGPEAXW4CR_MEDIA_SOURCE@@QEAPEAXKPEAVCRImportSite@@@Z equ <__imp_?CRImportMedia@@YAPEAVCRImportationResult@@PEAGPEAXW4CR_MEDIA_SOURCE@@QEAPEAXKPEAVCRImportSite@@@Z>

externdef __imp_?CRImportMovie@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRImage@@PEAVCRSound@@PEAPEAV3@PEAPEAV4@PEAPEAVCRNumber@@PEAPEAVCREvent@@88@Z:PPROC
?CRImportMovie@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRImage@@PEAVCRSound@@PEAPEAV3@PEAPEAV4@PEAPEAVCRNumber@@PEAPEAVCREvent@@88@Z equ <__imp_?CRImportMovie@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRImage@@PEAVCRSound@@PEAPEAV3@PEAPEAV4@PEAPEAVCRNumber@@PEAPEAVCREvent@@88@Z>

externdef __imp_?CRImportSound@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRSound@@PEAPEAV3@PEAPEAVCRNumber@@PEAPEAVCREvent@@66@Z:PPROC
?CRImportSound@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRSound@@PEAPEAV3@PEAPEAVCRNumber@@PEAPEAVCREvent@@66@Z equ <__imp_?CRImportSound@@YAKPEBG0PEAVCRImportSite@@PEAUIBindHost@@_NPEAVCRSound@@PEAPEAV3@PEAPEAVCRNumber@@PEAPEAVCREvent@@66@Z>

externdef __imp_?CRImportStatus@@YAJPEAVCRBvr@@@Z:PPROC
?CRImportStatus@@YAJPEAVCRBvr@@@Z equ <__imp_?CRImportStatus@@YAJPEAVCRBvr@@@Z>

externdef __imp_?CRImportance@@YAPEAVCRBvr@@PEAV1@N@Z:PPROC
?CRImportance@@YAPEAVCRBvr@@PEAV1@N@Z equ <__imp_?CRImportance@@YAPEAVCRBvr@@PEAV1@N@Z>

externdef __imp_?CRInit@@YA_NPEAVCRBvr@@0@Z:PPROC
?CRInit@@YA_NPEAVCRBvr@@0@Z equ <__imp_?CRInit@@YA_NPEAVCRBvr@@0@Z>

externdef __imp_?CRIntegral@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRIntegral@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRIntegral@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRIntegral@@YAPEAVCRVector2@@PEAV1@@Z:PPROC
?CRIntegral@@YAPEAVCRVector2@@PEAV1@@Z equ <__imp_?CRIntegral@@YAPEAVCRVector2@@PEAV1@@Z>

externdef __imp_?CRIntegral@@YAPEAVCRVector3@@PEAV1@@Z:PPROC
?CRIntegral@@YAPEAVCRVector3@@PEAV1@@Z equ <__imp_?CRIntegral@@YAPEAVCRVector3@@PEAV1@@Z>

externdef __imp_?CRInterpolate@@YAPEAVCRNumber@@NNN@Z:PPROC
?CRInterpolate@@YAPEAVCRNumber@@NNN@Z equ <__imp_?CRInterpolate@@YAPEAVCRNumber@@NNN@Z>

externdef __imp_?CRInterpolate@@YAPEAVCRNumber@@PEAV1@00@Z:PPROC
?CRInterpolate@@YAPEAVCRNumber@@PEAV1@00@Z equ <__imp_?CRInterpolate@@YAPEAVCRNumber@@PEAV1@00@Z>

externdef __imp_?CRIntersectMatte@@YAPEAVCRMatte@@PEAV1@0@Z:PPROC
?CRIntersectMatte@@YAPEAVCRMatte@@PEAV1@0@Z equ <__imp_?CRIntersectMatte@@YAPEAVCRMatte@@PEAV1@0@Z>

externdef __imp_?CRInverse@@YAPEAVCRTransform2@@PEAV1@@Z:PPROC
?CRInverse@@YAPEAVCRTransform2@@PEAV1@@Z equ <__imp_?CRInverse@@YAPEAVCRTransform2@@PEAV1@@Z>

externdef __imp_?CRInverse@@YAPEAVCRTransform3@@PEAV1@@Z:PPROC
?CRInverse@@YAPEAVCRTransform3@@PEAV1@@Z equ <__imp_?CRInverse@@YAPEAVCRTransform3@@PEAV1@@Z>

externdef __imp_?CRIsConnected@@YA_NPEAUHINSTANCE__@@@Z:PPROC
?CRIsConnected@@YA_NPEAUHINSTANCE__@@@Z equ <__imp_?CRIsConnected@@YA_NPEAUHINSTANCE__@@@Z>

externdef __imp_?CRIsConstantBvr@@YA_NPEAVCRBvr@@@Z:PPROC
?CRIsConstantBvr@@YA_NPEAVCRBvr@@@Z equ <__imp_?CRIsConstantBvr@@YA_NPEAVCRBvr@@@Z>

externdef __imp_?CRIsImport@@YA_NPEAVCRBvr@@@Z:PPROC
?CRIsImport@@YA_NPEAVCRBvr@@@Z equ <__imp_?CRIsImport@@YA_NPEAVCRBvr@@@Z>

externdef __imp_?CRIsModifiableBvr@@YA_NPEAVCRBvr@@@Z:PPROC
?CRIsModifiableBvr@@YA_NPEAVCRBvr@@@Z equ <__imp_?CRIsModifiableBvr@@YA_NPEAVCRBvr@@@Z>

externdef __imp_?CRIsReady@@YA_NPEAVCRBvr@@_N@Z:PPROC
?CRIsReady@@YA_NPEAVCRBvr@@_N@Z equ <__imp_?CRIsReady@@YA_NPEAVCRBvr@@_N@Z>

externdef __imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform2@@@Z:PPROC
?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform2@@@Z equ <__imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform2@@@Z>

externdef __imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform3@@@Z:PPROC
?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform3@@@Z equ <__imp_?CRIsSingular@@YAPEAVCRBoolean@@PEAVCRTransform3@@@Z>

externdef __imp_?CRItalic@@YAPEAVCRFontStyle@@PEAV1@@Z:PPROC
?CRItalic@@YAPEAVCRFontStyle@@PEAV1@@Z equ <__imp_?CRItalic@@YAPEAVCRFontStyle@@PEAV1@@Z>

externdef __imp_?CRJoin@@YAPEAVCRLineStyle@@PEAV1@PEAVCRJoinStyle@@@Z:PPROC
?CRJoin@@YAPEAVCRLineStyle@@PEAV1@PEAVCRJoinStyle@@@Z equ <__imp_?CRJoin@@YAPEAVCRLineStyle@@PEAV1@PEAVCRJoinStyle@@@Z>

externdef __imp_?CRJoinEx@@YAPEAVCRLineStyle@@PEAV1@K@Z:PPROC
?CRJoinEx@@YAPEAVCRLineStyle@@PEAV1@K@Z equ <__imp_?CRJoinEx@@YAPEAVCRLineStyle@@PEAV1@K@Z>

externdef __imp_?CRJoinStyleBevel@@YAPEAVCRJoinStyle@@XZ:PPROC
?CRJoinStyleBevel@@YAPEAVCRJoinStyle@@XZ equ <__imp_?CRJoinStyleBevel@@YAPEAVCRJoinStyle@@XZ>

externdef __imp_?CRJoinStyleMiter@@YAPEAVCRJoinStyle@@XZ:PPROC
?CRJoinStyleMiter@@YAPEAVCRJoinStyle@@XZ equ <__imp_?CRJoinStyleMiter@@YAPEAVCRJoinStyle@@XZ>

externdef __imp_?CRJoinStyleRound@@YAPEAVCRJoinStyle@@XZ:PPROC
?CRJoinStyleRound@@YAPEAVCRJoinStyle@@XZ equ <__imp_?CRJoinStyleRound@@YAPEAVCRJoinStyle@@XZ>

externdef __imp_?CRKeyDown@@YAPEAVCREvent@@J@Z:PPROC
?CRKeyDown@@YAPEAVCREvent@@J@Z equ <__imp_?CRKeyDown@@YAPEAVCREvent@@J@Z>

externdef __imp_?CRKeyState@@YAPEAVCRBoolean@@PEAVCRNumber@@@Z:PPROC
?CRKeyState@@YAPEAVCRBoolean@@PEAVCRNumber@@@Z equ <__imp_?CRKeyState@@YAPEAVCRBoolean@@PEAVCRNumber@@@Z>

externdef __imp_?CRKeyUp@@YAPEAVCREvent@@J@Z:PPROC
?CRKeyUp@@YAPEAVCREvent@@J@Z equ <__imp_?CRKeyUp@@YAPEAVCREvent@@J@Z>

externdef __imp_?CRLT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PPROC
?CRLT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z equ <__imp_?CRLT@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>

externdef __imp_?CRLTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PPROC
?CRLTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z equ <__imp_?CRLTE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>

externdef __imp_?CRLeftButtonDown@@YAPEAVCREvent@@XZ:PPROC
?CRLeftButtonDown@@YAPEAVCREvent@@XZ equ <__imp_?CRLeftButtonDown@@YAPEAVCREvent@@XZ>

externdef __imp_?CRLeftButtonState@@YAPEAVCRBoolean@@XZ:PPROC
?CRLeftButtonState@@YAPEAVCRBoolean@@XZ equ <__imp_?CRLeftButtonState@@YAPEAVCRBoolean@@XZ>

externdef __imp_?CRLeftButtonUp@@YAPEAVCREvent@@XZ:PPROC
?CRLeftButtonUp@@YAPEAVCREvent@@XZ equ <__imp_?CRLeftButtonUp@@YAPEAVCREvent@@XZ>

externdef __imp_?CRLength@@YAJPEAVCRTuple@@@Z:PPROC
?CRLength@@YAJPEAVCRTuple@@@Z equ <__imp_?CRLength@@YAJPEAVCRTuple@@@Z>

externdef __imp_?CRLength@@YAPEAVCRNumber@@PEAVCRArray@@@Z:PPROC
?CRLength@@YAPEAVCRNumber@@PEAVCRArray@@@Z equ <__imp_?CRLength@@YAPEAVCRNumber@@PEAVCRArray@@@Z>

externdef __imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PPROC
?CRLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z equ <__imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>

externdef __imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PPROC
?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector2@@@Z equ <__imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>

externdef __imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRLengthSquared@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@NNN@Z:PPROC
?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@NNN@Z equ <__imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@NNN@Z>

externdef __imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@11@Z:PPROC
?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@11@Z equ <__imp_?CRLightAttenuation@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@11@Z>

externdef __imp_?CRLightColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRLightColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRLightColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@N@Z:PPROC
?CRLightRange@@YAPEAVCRGeometry@@PEAV1@N@Z equ <__imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@N@Z>

externdef __imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRLightRange@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRLightRange@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRLighting@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z:PPROC
?CRLighting@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z equ <__imp_?CRLighting@@YAPEAVCRGeometry@@PEAV1@PEAVCRBoolean@@@Z>

externdef __imp_?CRLime@@YAPEAVCRColor@@XZ:PPROC
?CRLime@@YAPEAVCRColor@@XZ equ <__imp_?CRLime@@YAPEAVCRColor@@XZ>

externdef __imp_?CRLine@@YAPEAVCRPath2@@PEAVCRPoint2@@0@Z:PPROC
?CRLine@@YAPEAVCRPath2@@PEAVCRPoint2@@0@Z equ <__imp_?CRLine@@YAPEAVCRPath2@@PEAVCRPoint2@@0@Z>

externdef __imp_?CRLineColor@@YAPEAVCRLineStyle@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRLineColor@@YAPEAVCRLineStyle@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRLineColor@@YAPEAVCRLineStyle@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRLinearGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z:PPROC
?CRLinearGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z equ <__imp_?CRLinearGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z>

externdef __imp_?CRLn@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRLn@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRLn@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRLocalTime@@YAPEAVCRNumber@@XZ:PPROC
?CRLocalTime@@YAPEAVCRNumber@@XZ equ <__imp_?CRLocalTime@@YAPEAVCRNumber@@XZ>

externdef __imp_?CRLog10@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRLog10@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRLog10@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRLookAtFrom@@YAPEAVCRTransform3@@PEAVCRPoint3@@0PEAVCRVector3@@@Z:PPROC
?CRLookAtFrom@@YAPEAVCRTransform3@@PEAVCRPoint3@@0PEAVCRVector3@@@Z equ <__imp_?CRLookAtFrom@@YAPEAVCRTransform3@@PEAVCRPoint3@@0PEAVCRVector3@@@Z>

externdef __imp_?CRLoop@@YAPEAVCRSound@@PEAV1@@Z:PPROC
?CRLoop@@YAPEAVCRSound@@PEAV1@@Z equ <__imp_?CRLoop@@YAPEAVCRSound@@PEAV1@@Z>

externdef __imp_?CRMagenta@@YAPEAVCRColor@@XZ:PPROC
?CRMagenta@@YAPEAVCRColor@@XZ equ <__imp_?CRMagenta@@YAPEAVCRColor@@XZ>

externdef __imp_?CRMapToUnitSquare@@YAPEAVCRImage@@PEAV1@@Z:PPROC
?CRMapToUnitSquare@@YAPEAVCRImage@@PEAV1@@Z equ <__imp_?CRMapToUnitSquare@@YAPEAVCRImage@@PEAV1@@Z>

externdef __imp_?CRMaroon@@YAPEAVCRColor@@XZ:PPROC
?CRMaroon@@YAPEAVCRColor@@XZ equ <__imp_?CRMaroon@@YAPEAVCRColor@@XZ>

externdef __imp_?CRMax@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z:PPROC
?CRMax@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z equ <__imp_?CRMax@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z>

externdef __imp_?CRMax@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z:PPROC
?CRMax@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z equ <__imp_?CRMax@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z>

externdef __imp_?CRMin@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z:PPROC
?CRMin@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z equ <__imp_?CRMin@@YAPEAVCRPoint2@@PEAVCRBbox2@@@Z>

externdef __imp_?CRMin@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z:PPROC
?CRMin@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z equ <__imp_?CRMin@@YAPEAVCRPoint3@@PEAVCRBbox3@@@Z>

externdef __imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@N@Z:PPROC
?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@N@Z equ <__imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@N@Z>

externdef __imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRMiterLimit@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRMix@@YAPEAVCRSound@@PEAV1@0@Z:PPROC
?CRMix@@YAPEAVCRSound@@PEAV1@0@Z equ <__imp_?CRMix@@YAPEAVCRSound@@PEAV1@0@Z>

externdef __imp_?CRMix@@YAPEAVCRSound@@PEAVCRArray@@@Z:PPROC
?CRMix@@YAPEAVCRSound@@PEAVCRArray@@@Z equ <__imp_?CRMix@@YAPEAVCRSound@@PEAVCRArray@@@Z>

externdef __imp_?CRMod@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRMod@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRMod@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRModelClip@@YAPEAVCRGeometry@@PEAV1@PEAVCRPoint3@@PEAVCRVector3@@@Z:PPROC
?CRModelClip@@YAPEAVCRGeometry@@PEAV1@PEAVCRPoint3@@PEAVCRVector3@@@Z equ <__imp_?CRModelClip@@YAPEAVCRGeometry@@PEAV1@PEAVCRPoint3@@PEAVCRVector3@@@Z>

externdef __imp_?CRModifiableBvr@@YAPEAVCRBvr@@PEAV1@K@Z:PPROC
?CRModifiableBvr@@YAPEAVCRBvr@@PEAV1@K@Z equ <__imp_?CRModifiableBvr@@YAPEAVCRBvr@@PEAV1@K@Z>

externdef __imp_?CRModifiableNumber@@YAPEAVCRNumber@@N@Z:PPROC
?CRModifiableNumber@@YAPEAVCRNumber@@N@Z equ <__imp_?CRModifiableNumber@@YAPEAVCRNumber@@N@Z>

externdef __imp_?CRModifiableString@@YAPEAVCRString@@PEAG@Z:PPROC
?CRModifiableString@@YAPEAVCRString@@PEAG@Z equ <__imp_?CRModifiableString@@YAPEAVCRString@@PEAG@Z>

externdef __imp_?CRMousePosition@@YAPEAVCRPoint2@@XZ:PPROC
?CRMousePosition@@YAPEAVCRPoint2@@XZ equ <__imp_?CRMousePosition@@YAPEAVCRPoint2@@XZ>

externdef __imp_?CRMul@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRMul@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRMul@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRMul@@YAPEAVCRVector2@@PEAV1@N@Z:PPROC
?CRMul@@YAPEAVCRVector2@@PEAV1@N@Z equ <__imp_?CRMul@@YAPEAVCRVector2@@PEAV1@N@Z>

externdef __imp_?CRMul@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRMul@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRMul@@YAPEAVCRVector2@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRMul@@YAPEAVCRVector3@@PEAV1@N@Z:PPROC
?CRMul@@YAPEAVCRVector3@@PEAV1@N@Z equ <__imp_?CRMul@@YAPEAVCRVector3@@PEAV1@N@Z>

externdef __imp_?CRMul@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRMul@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRMul@@YAPEAVCRVector3@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRNE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z:PPROC
?CRNE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z equ <__imp_?CRNE@@YAPEAVCRBoolean@@PEAVCRNumber@@0@Z>

externdef __imp_?CRNavy@@YAPEAVCRColor@@XZ:PPROC
?CRNavy@@YAPEAVCRColor@@XZ equ <__imp_?CRNavy@@YAPEAVCRColor@@XZ>

externdef __imp_?CRNeg@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRNeg@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRNeg@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRNeg@@YAPEAVCRVector2@@PEAV1@@Z:PPROC
?CRNeg@@YAPEAVCRVector2@@PEAV1@@Z equ <__imp_?CRNeg@@YAPEAVCRVector2@@PEAV1@@Z>

externdef __imp_?CRNeg@@YAPEAVCRVector3@@PEAV1@@Z:PPROC
?CRNeg@@YAPEAVCRVector3@@PEAV1@@Z equ <__imp_?CRNeg@@YAPEAVCRVector3@@PEAV1@@Z>

externdef __imp_?CRNever@@YAPEAVCREvent@@XZ:PPROC
?CRNever@@YAPEAVCREvent@@XZ equ <__imp_?CRNever@@YAPEAVCREvent@@XZ>

externdef __imp_?CRNormalize@@YAPEAVCRVector2@@PEAV1@@Z:PPROC
?CRNormalize@@YAPEAVCRVector2@@PEAV1@@Z equ <__imp_?CRNormalize@@YAPEAVCRVector2@@PEAV1@@Z>

externdef __imp_?CRNormalize@@YAPEAVCRVector3@@PEAV1@@Z:PPROC
?CRNormalize@@YAPEAVCRVector3@@PEAV1@@Z equ <__imp_?CRNormalize@@YAPEAVCRVector3@@PEAV1@@Z>

externdef __imp_?CRNot@@YAPEAVCRBoolean@@PEAV1@@Z:PPROC
?CRNot@@YAPEAVCRBoolean@@PEAV1@@Z equ <__imp_?CRNot@@YAPEAVCRBoolean@@PEAV1@@Z>

externdef __imp_?CRNotEvent@@YAPEAVCREvent@@PEAV1@@Z:PPROC
?CRNotEvent@@YAPEAVCREvent@@PEAV1@@Z equ <__imp_?CRNotEvent@@YAPEAVCREvent@@PEAV1@@Z>

externdef __imp_?CRNotify@@YAPEAVCREvent@@PEAV1@PEAVCRUntilNotifier@@@Z:PPROC
?CRNotify@@YAPEAVCREvent@@PEAV1@PEAVCRUntilNotifier@@@Z equ <__imp_?CRNotify@@YAPEAVCREvent@@PEAV1@PEAVCRUntilNotifier@@@Z>

externdef __imp_?CRNth@@YAPEAVCRBvr@@PEAVCRArray@@PEAVCRNumber@@@Z:PPROC
?CRNth@@YAPEAVCRBvr@@PEAVCRArray@@PEAVCRNumber@@@Z equ <__imp_?CRNth@@YAPEAVCRBvr@@PEAVCRArray@@PEAVCRNumber@@@Z>

externdef __imp_?CRNth@@YAPEAVCRBvr@@PEAVCRTuple@@J@Z:PPROC
?CRNth@@YAPEAVCRBvr@@PEAVCRTuple@@J@Z equ <__imp_?CRNth@@YAPEAVCRBvr@@PEAVCRTuple@@J@Z>

externdef __imp_?CROlive@@YAPEAVCRColor@@XZ:PPROC
?CROlive@@YAPEAVCRColor@@XZ equ <__imp_?CROlive@@YAPEAVCRColor@@XZ>

externdef __imp_?CROnFocus@@YA_NPEAVCRView@@_N@Z:PPROC
?CROnFocus@@YA_NPEAVCRView@@_N@Z equ <__imp_?CROnFocus@@YA_NPEAVCRView@@_N@Z>

externdef __imp_?CROnKey@@YA_NPEAVCRView@@NJ_NE@Z:PPROC
?CROnKey@@YA_NPEAVCRView@@NJ_NE@Z equ <__imp_?CROnKey@@YA_NPEAVCRView@@NJ_NE@Z>

externdef __imp_?CROnMouseButton@@YA_NPEAVCRView@@NJJE_NE@Z:PPROC
?CROnMouseButton@@YA_NPEAVCRView@@NJJE_NE@Z equ <__imp_?CROnMouseButton@@YA_NPEAVCRView@@NJJE_NE@Z>

externdef __imp_?CROnMouseLeave@@YA_NPEAVCRView@@N@Z:PPROC
?CROnMouseLeave@@YA_NPEAVCRView@@N@Z equ <__imp_?CROnMouseLeave@@YA_NPEAVCRView@@N@Z>

externdef __imp_?CROnMouseMove@@YA_NPEAVCRView@@NJJE@Z:PPROC
?CROnMouseMove@@YA_NPEAVCRView@@NJJE@Z equ <__imp_?CROnMouseMove@@YA_NPEAVCRView@@NJJE@Z>

externdef __imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@N@Z:PPROC
?CROpacity@@YAPEAVCRGeometry@@PEAV1@N@Z equ <__imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@N@Z>

externdef __imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CROpacity@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CROpacity@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CROpacity@@YAPEAVCRImage@@PEAV1@N@Z:PPROC
?CROpacity@@YAPEAVCRImage@@PEAV1@N@Z equ <__imp_?CROpacity@@YAPEAVCRImage@@PEAV1@N@Z>

externdef __imp_?CROpacity@@YAPEAVCRImage@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CROpacity@@YAPEAVCRImage@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CROpacity@@YAPEAVCRImage@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CROpaqueMatte@@YAPEAVCRMatte@@XZ:PPROC
?CROpaqueMatte@@YAPEAVCRMatte@@XZ equ <__imp_?CROpaqueMatte@@YAPEAVCRMatte@@XZ>

externdef __imp_?CROr@@YAPEAVCRBoolean@@PEAV1@0@Z:PPROC
?CROr@@YAPEAVCRBoolean@@PEAV1@0@Z equ <__imp_?CROr@@YAPEAVCRBoolean@@PEAV1@0@Z>

externdef __imp_?CROrEvent@@YAPEAVCREvent@@PEAV1@0@Z:PPROC
?CROrEvent@@YAPEAVCREvent@@PEAV1@0@Z equ <__imp_?CROrEvent@@YAPEAVCREvent@@PEAV1@0@Z>

externdef __imp_?CROrigin2@@YAPEAVCRPoint2@@XZ:PPROC
?CROrigin2@@YAPEAVCRPoint2@@XZ equ <__imp_?CROrigin2@@YAPEAVCRPoint2@@XZ>

externdef __imp_?CROrigin3@@YAPEAVCRPoint3@@XZ:PPROC
?CROrigin3@@YAPEAVCRPoint3@@XZ equ <__imp_?CROrigin3@@YAPEAVCRPoint3@@XZ>

externdef __imp_?CROval@@YAPEAVCRPath2@@NN@Z:PPROC
?CROval@@YAPEAVCRPath2@@NN@Z equ <__imp_?CROval@@YAPEAVCRPath2@@NN@Z>

externdef __imp_?CROval@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z:PPROC
?CROval@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z equ <__imp_?CROval@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z>

externdef __imp_?CROverlay@@YAPEAVCRImage@@PEAV1@0@Z:PPROC
?CROverlay@@YAPEAVCRImage@@PEAV1@0@Z equ <__imp_?CROverlay@@YAPEAVCRImage@@PEAV1@0@Z>

externdef __imp_?CROverlay@@YAPEAVCRImage@@PEAVCRArray@@@Z:PPROC
?CROverlay@@YAPEAVCRImage@@PEAVCRArray@@@Z equ <__imp_?CROverlay@@YAPEAVCRImage@@PEAVCRArray@@@Z>

externdef __imp_?CRPan@@YAPEAVCRSound@@PEAV1@N@Z:PPROC
?CRPan@@YAPEAVCRSound@@PEAV1@N@Z equ <__imp_?CRPan@@YAPEAVCRSound@@PEAV1@N@Z>

externdef __imp_?CRPan@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRPan@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRPan@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRParallelCamera@@YAPEAVCRCamera@@N@Z:PPROC
?CRParallelCamera@@YAPEAVCRCamera@@N@Z equ <__imp_?CRParallelCamera@@YAPEAVCRCamera@@N@Z>

externdef __imp_?CRParallelCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@@Z:PPROC
?CRParallelCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@@Z equ <__imp_?CRParallelCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@@Z>

externdef __imp_?CRParallelTransform2@@YAPEAVCRTransform2@@PEAVCRTransform3@@@Z:PPROC
?CRParallelTransform2@@YAPEAVCRTransform2@@PEAVCRTransform3@@@Z equ <__imp_?CRParallelTransform2@@YAPEAVCRTransform2@@PEAVCRTransform3@@@Z>

externdef __imp_?CRPauseModel@@YA_NPEAVCRView@@@Z:PPROC
?CRPauseModel@@YA_NPEAVCRView@@@Z equ <__imp_?CRPauseModel@@YA_NPEAVCRView@@@Z>

externdef __imp_?CRPerspectiveCamera@@YAPEAVCRCamera@@NN@Z:PPROC
?CRPerspectiveCamera@@YAPEAVCRCamera@@NN@Z equ <__imp_?CRPerspectiveCamera@@YAPEAVCRCamera@@NN@Z>

externdef __imp_?CRPerspectiveCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@0@Z:PPROC
?CRPerspectiveCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@0@Z equ <__imp_?CRPerspectiveCameraAnim@@YAPEAVCRCamera@@PEAVCRNumber@@0@Z>

externdef __imp_?CRPhase@@YAPEAVCRSound@@PEAV1@N@Z:PPROC
?CRPhase@@YAPEAVCRSound@@PEAV1@N@Z equ <__imp_?CRPhase@@YAPEAVCRSound@@PEAV1@N@Z>

externdef __imp_?CRPhase@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRPhase@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRPhase@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z:PPROC
?CRPickable@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z equ <__imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z>

externdef __imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z:PPROC
?CRPickable@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z equ <__imp_?CRPickable@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z>

externdef __imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z:PPROC
?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z equ <__imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRGeometry@@@Z>

externdef __imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z:PPROC
?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z equ <__imp_?CRPickableOccluded@@YAPEAVCRPickableResult@@PEAVCRImage@@@Z>

externdef __imp_?CRPie@@YAPEAVCRPath2@@NNNN@Z:PPROC
?CRPie@@YAPEAVCRPath2@@NNNN@Z equ <__imp_?CRPie@@YAPEAVCRPath2@@NNNN@Z>

externdef __imp_?CRPieRadians@@YAPEAVCRPath2@@NNNN@Z:PPROC
?CRPieRadians@@YAPEAVCRPath2@@NNNN@Z equ <__imp_?CRPieRadians@@YAPEAVCRPath2@@NNNN@Z>

externdef __imp_?CRPieRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z:PPROC
?CRPieRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z equ <__imp_?CRPieRadians@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z>

externdef __imp_?CRPixel@@YAPEAVCRNumber@@XZ:PPROC
?CRPixel@@YAPEAVCRNumber@@XZ equ <__imp_?CRPixel@@YAPEAVCRNumber@@XZ>

externdef __imp_?CRPoint2Polar@@YAPEAVCRPoint2@@NN@Z:PPROC
?CRPoint2Polar@@YAPEAVCRPoint2@@NN@Z equ <__imp_?CRPoint2Polar@@YAPEAVCRPoint2@@NN@Z>

externdef __imp_?CRPoint2Polar@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z:PPROC
?CRPoint2Polar@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z equ <__imp_?CRPoint2Polar@@YAPEAVCRPoint2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@NNN@Z:PPROC
?CRPoint3Spherical@@YAPEAVCRPoint3@@NNN@Z equ <__imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@NNN@Z>

externdef __imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z:PPROC
?CRPoint3Spherical@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z equ <__imp_?CRPoint3Spherical@@YAPEAVCRPoint3@@PEAVCRNumber@@00@Z>

externdef __imp_?CRPointLight@@YAPEAVCRGeometry@@XZ:PPROC
?CRPointLight@@YAPEAVCRGeometry@@XZ equ <__imp_?CRPointLight@@YAPEAVCRGeometry@@XZ>

externdef __imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PPROC
?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z equ <__imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>

externdef __imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PPROC
?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRVector2@@@Z equ <__imp_?CRPolarCoordAngle@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>

externdef __imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z:PPROC
?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z equ <__imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRPoint2@@@Z>

externdef __imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z:PPROC
?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z equ <__imp_?CRPolarCoordLength@@YAPEAVCRNumber@@PEAVCRVector2@@@Z>

externdef __imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEANI0I@Z:PPROC
?CRPolydrawPath@@YAPEAVCRPath2@@PEANI0I@Z equ <__imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEANI0I@Z>

externdef __imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z:PPROC
?CRPolydrawPath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z equ <__imp_?CRPolydrawPath@@YAPEAVCRPath2@@PEAVCRArray@@0@Z>

externdef __imp_?CRPolyline@@YAPEAVCRPath2@@PEAVCRArray@@@Z:PPROC
?CRPolyline@@YAPEAVCRPath2@@PEAVCRArray@@@Z equ <__imp_?CRPolyline@@YAPEAVCRPath2@@PEAVCRArray@@@Z>

externdef __imp_?CRPow@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRPow@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRPow@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRPredicate@@YAPEAVCREvent@@PEAVCRBoolean@@@Z:PPROC
?CRPredicate@@YAPEAVCREvent@@PEAVCRBoolean@@@Z equ <__imp_?CRPredicate@@YAPEAVCREvent@@PEAVCRBoolean@@@Z>

externdef __imp_?CRProject@@YAPEAVCRPoint2@@PEAVCRPoint3@@PEAVCRCamera@@@Z:PPROC
?CRProject@@YAPEAVCRPoint2@@PEAVCRPoint3@@PEAVCRCamera@@@Z equ <__imp_?CRProject@@YAPEAVCRPoint2@@PEAVCRPoint3@@PEAVCRCamera@@@Z>

externdef __imp_?CRPropagate@@YA_NPEAVCRView@@@Z:PPROC
?CRPropagate@@YA_NPEAVCRView@@@Z equ <__imp_?CRPropagate@@YA_NPEAVCRView@@@Z>

externdef __imp_?CRPurple@@YAPEAVCRColor@@XZ:PPROC
?CRPurple@@YAPEAVCRColor@@XZ equ <__imp_?CRPurple@@YAPEAVCRColor@@XZ>

externdef __imp_?CRPutPreference@@YA_NPEAVCRView@@PEAGUtagVARIANT@@@Z:PPROC
?CRPutPreference@@YA_NPEAVCRView@@PEAGUtagVARIANT@@@Z equ <__imp_?CRPutPreference@@YA_NPEAVCRView@@PEAGUtagVARIANT@@@Z>

externdef __imp_?CRQueryHitPoint@@YAKPEAVCRView@@KPEBUtagRECT@@UtagPOINT@@J@Z:PPROC
?CRQueryHitPoint@@YAKPEAVCRView@@KPEBUtagRECT@@UtagPOINT@@J@Z equ <__imp_?CRQueryHitPoint@@YAKPEAVCRView@@KPEBUtagRECT@@UtagPOINT@@J@Z>

externdef __imp_?CRQueryHitPointEx@@YAJPEAVCRView@@JPEA_KPEANPEBUtagRECT@@UtagPOINT@@@Z:PPROC
?CRQueryHitPointEx@@YAJPEAVCRView@@JPEA_KPEANPEBUtagRECT@@UtagPOINT@@@Z equ <__imp_?CRQueryHitPointEx@@YAJPEAVCRView@@JPEA_KPEANPEBUtagRECT@@UtagPOINT@@@Z>

externdef __imp_?CRRadialGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z:PPROC
?CRRadialGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z equ <__imp_?CRRadialGradientMulticolor@@YAPEAVCRImage@@PEAVCRArray@@0@Z>

externdef __imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@N@Z:PPROC
?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@N@Z equ <__imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@N@Z>

externdef __imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@PEAVCRNumber@@@Z:PPROC
?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@PEAVCRNumber@@@Z equ <__imp_?CRRadialGradientPolygon@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRArray@@PEAVCRNumber@@@Z>

externdef __imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0NN@Z:PPROC
?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0NN@Z equ <__imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0NN@Z>

externdef __imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@1@Z:PPROC
?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@1@Z equ <__imp_?CRRadialGradientRegularPoly@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@1@Z>

externdef __imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0N@Z:PPROC
?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0N@Z equ <__imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0N@Z>

externdef __imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z:PPROC
?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z equ <__imp_?CRRadialGradientSquare@@YAPEAVCRImage@@PEAVCRColor@@0PEAVCRNumber@@@Z>

externdef __imp_?CRRate@@YAPEAVCRSound@@PEAV1@N@Z:PPROC
?CRRate@@YAPEAVCRSound@@PEAV1@N@Z equ <__imp_?CRRate@@YAPEAVCRSound@@PEAV1@N@Z>

externdef __imp_?CRRate@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRRate@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRRate@@YAPEAVCRSound@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRRay@@YAPEAVCRPath2@@PEAVCRPoint2@@@Z:PPROC
?CRRay@@YAPEAVCRPath2@@PEAVCRPoint2@@@Z equ <__imp_?CRRay@@YAPEAVCRPath2@@PEAVCRPoint2@@@Z>

externdef __imp_?CRRect@@YAPEAVCRPath2@@NN@Z:PPROC
?CRRect@@YAPEAVCRPath2@@NN@Z equ <__imp_?CRRect@@YAPEAVCRPath2@@NN@Z>

externdef __imp_?CRRect@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z:PPROC
?CRRect@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z equ <__imp_?CRRect@@YAPEAVCRPath2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRRed@@YAPEAVCRColor@@XZ:PPROC
?CRRed@@YAPEAVCRColor@@XZ equ <__imp_?CRRed@@YAPEAVCRColor@@XZ>

externdef __imp_?CRReleaseGC@@YA_NPEAX@Z:PPROC
?CRReleaseGC@@YA_NPEAX@Z equ <__imp_?CRReleaseGC@@YA_NPEAX@Z>

externdef __imp_?CRReleaseGCLock@@YA_NXZ:PPROC
?CRReleaseGCLock@@YA_NXZ equ <__imp_?CRReleaseGCLock@@YA_NXZ>

externdef __imp_?CRRemoveElement@@YA_NPEAVCRArray@@J@Z:PPROC
?CRRemoveElement@@YA_NPEAVCRArray@@J@Z equ <__imp_?CRRemoveElement@@YA_NPEAVCRArray@@J@Z>

externdef __imp_?CRRemoveRunningBvr@@YA_NPEAVCRView@@J@Z:PPROC
?CRRemoveRunningBvr@@YA_NPEAVCRView@@J@Z equ <__imp_?CRRemoveRunningBvr@@YA_NPEAVCRView@@J@Z>

externdef __imp_?CRRemoveSite@@YA_NPEAVCRSite@@@Z:PPROC
?CRRemoveSite@@YA_NPEAVCRSite@@@Z equ <__imp_?CRRemoveSite@@YA_NPEAVCRSite@@@Z>

externdef __imp_?CRRender@@YAPEAVCRImage@@PEAVCRGeometry@@PEAVCRCamera@@@Z:PPROC
?CRRender@@YAPEAVCRImage@@PEAVCRGeometry@@PEAVCRCamera@@@Z equ <__imp_?CRRender@@YAPEAVCRImage@@PEAVCRGeometry@@PEAVCRCamera@@@Z>

externdef __imp_?CRRender@@YAPEAVCRImage@@PEAVCRMontage@@@Z:PPROC
?CRRender@@YAPEAVCRImage@@PEAVCRMontage@@@Z equ <__imp_?CRRender@@YAPEAVCRImage@@PEAVCRMontage@@@Z>

externdef __imp_?CRRender@@YA_NPEAVCRView@@@Z:PPROC
?CRRender@@YA_NPEAVCRView@@@Z equ <__imp_?CRRender@@YA_NPEAVCRView@@@Z>

externdef __imp_?CRRenderResolution@@YAPEAVCRImage@@PEAV1@JJ@Z:PPROC
?CRRenderResolution@@YAPEAVCRImage@@PEAV1@JJ@Z equ <__imp_?CRRenderResolution@@YAPEAVCRImage@@PEAV1@JJ@Z>

externdef __imp_?CRRenderSound@@YAPEAVCRSound@@PEAVCRGeometry@@PEAVCRMicrophone@@@Z:PPROC
?CRRenderSound@@YAPEAVCRSound@@PEAVCRGeometry@@PEAVCRMicrophone@@@Z equ <__imp_?CRRenderSound@@YAPEAVCRSound@@PEAVCRGeometry@@PEAVCRMicrophone@@@Z>

externdef __imp_?CRRepaint@@YA_NPEAVCRView@@JJJJ@Z:PPROC
?CRRepaint@@YA_NPEAVCRView@@JJJJ@Z equ <__imp_?CRRepaint@@YA_NPEAVCRView@@JJJJ@Z>

externdef __imp_?CRRepeat@@YAPEAVCRBvr@@PEAV1@J@Z:PPROC
?CRRepeat@@YAPEAVCRBvr@@PEAV1@J@Z equ <__imp_?CRRepeat@@YAPEAVCRBvr@@PEAV1@J@Z>

externdef __imp_?CRRepeatForever@@YAPEAVCRBvr@@PEAV1@@Z:PPROC
?CRRepeatForever@@YAPEAVCRBvr@@PEAV1@@Z equ <__imp_?CRRepeatForever@@YAPEAVCRBvr@@PEAV1@@Z>

externdef __imp_?CRResumeModel@@YA_NPEAVCRView@@@Z:PPROC
?CRResumeModel@@YA_NPEAVCRView@@@Z equ <__imp_?CRResumeModel@@YA_NPEAVCRView@@@Z>

externdef __imp_?CRRightButtonDown@@YAPEAVCREvent@@XZ:PPROC
?CRRightButtonDown@@YAPEAVCREvent@@XZ equ <__imp_?CRRightButtonDown@@YAPEAVCREvent@@XZ>

externdef __imp_?CRRightButtonState@@YAPEAVCRBoolean@@XZ:PPROC
?CRRightButtonState@@YAPEAVCRBoolean@@XZ equ <__imp_?CRRightButtonState@@YAPEAVCRBoolean@@XZ>

externdef __imp_?CRRightButtonUp@@YAPEAVCREvent@@XZ:PPROC
?CRRightButtonUp@@YAPEAVCREvent@@XZ equ <__imp_?CRRightButtonUp@@YAPEAVCREvent@@XZ>

externdef __imp_?CRRotate2@@YAPEAVCRTransform2@@N@Z:PPROC
?CRRotate2@@YAPEAVCRTransform2@@N@Z equ <__imp_?CRRotate2@@YAPEAVCRTransform2@@N@Z>

externdef __imp_?CRRotate2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PPROC
?CRRotate2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z equ <__imp_?CRRotate2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>

externdef __imp_?CRRotate2Degrees@@YAPEAVCRTransform2@@N@Z:PPROC
?CRRotate2Degrees@@YAPEAVCRTransform2@@N@Z equ <__imp_?CRRotate2Degrees@@YAPEAVCRTransform2@@N@Z>

externdef __imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@N@Z:PPROC
?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@N@Z equ <__imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@N@Z>

externdef __imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@PEAVCRNumber@@@Z:PPROC
?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@PEAVCRNumber@@@Z equ <__imp_?CRRotate3@@YAPEAVCRTransform3@@PEAVCRVector3@@PEAVCRNumber@@@Z>

externdef __imp_?CRRound@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRRound@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRRound@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRRoundRect@@YAPEAVCRPath2@@NNNN@Z:PPROC
?CRRoundRect@@YAPEAVCRPath2@@NNNN@Z equ <__imp_?CRRoundRect@@YAPEAVCRPath2@@NNNN@Z>

externdef __imp_?CRRoundRect@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z:PPROC
?CRRoundRect@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z equ <__imp_?CRRoundRect@@YAPEAVCRPath2@@PEAVCRNumber@@000@Z>

externdef __imp_?CRRunOnce@@YAPEAVCRBvr@@PEAV1@@Z:PPROC
?CRRunOnce@@YAPEAVCRBvr@@PEAV1@@Z equ <__imp_?CRRunOnce@@YAPEAVCRBvr@@PEAV1@@Z>

externdef __imp_?CRSampleAtLocalTime@@YAPEAVCRBvr@@PEAV1@N@Z:PPROC
?CRSampleAtLocalTime@@YAPEAVCRBvr@@PEAV1@N@Z equ <__imp_?CRSampleAtLocalTime@@YAPEAVCRBvr@@PEAV1@N@Z>

externdef __imp_?CRScale2@@YAPEAVCRTransform2@@NN@Z:PPROC
?CRScale2@@YAPEAVCRTransform2@@NN@Z equ <__imp_?CRScale2@@YAPEAVCRTransform2@@NN@Z>

externdef __imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z:PPROC
?CRScale2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z equ <__imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z:PPROC
?CRScale2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z equ <__imp_?CRScale2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z>

externdef __imp_?CRScale2Uniform@@YAPEAVCRTransform2@@N@Z:PPROC
?CRScale2Uniform@@YAPEAVCRTransform2@@N@Z equ <__imp_?CRScale2Uniform@@YAPEAVCRTransform2@@N@Z>

externdef __imp_?CRScale2Uniform@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PPROC
?CRScale2Uniform@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z equ <__imp_?CRScale2Uniform@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>

externdef __imp_?CRScale3@@YAPEAVCRTransform3@@NNN@Z:PPROC
?CRScale3@@YAPEAVCRTransform3@@NNN@Z equ <__imp_?CRScale3@@YAPEAVCRTransform3@@NNN@Z>

externdef __imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z:PPROC
?CRScale3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z equ <__imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z>

externdef __imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z:PPROC
?CRScale3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z equ <__imp_?CRScale3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z>

externdef __imp_?CRScale3Uniform@@YAPEAVCRTransform3@@N@Z:PPROC
?CRScale3Uniform@@YAPEAVCRTransform3@@N@Z equ <__imp_?CRScale3Uniform@@YAPEAVCRTransform3@@N@Z>

externdef __imp_?CRScale3Uniform@@YAPEAVCRTransform3@@PEAVCRNumber@@@Z:PPROC
?CRScale3Uniform@@YAPEAVCRTransform3@@PEAVCRNumber@@@Z equ <__imp_?CRScale3Uniform@@YAPEAVCRTransform3@@PEAVCRNumber@@@Z>

externdef __imp_?CRSecond@@YAPEAVCRBvr@@PEAVCRPair@@@Z:PPROC
?CRSecond@@YAPEAVCRBvr@@PEAVCRPair@@@Z equ <__imp_?CRSecond@@YAPEAVCRBvr@@PEAVCRPair@@@Z>

externdef __imp_?CRSeededRandom@@YAPEAVCRNumber@@N@Z:PPROC
?CRSeededRandom@@YAPEAVCRNumber@@N@Z equ <__imp_?CRSeededRandom@@YAPEAVCRNumber@@N@Z>

externdef __imp_?CRSequence@@YAPEAVCRBvr@@PEAV1@0@Z:PPROC
?CRSequence@@YAPEAVCRBvr@@PEAV1@0@Z equ <__imp_?CRSequence@@YAPEAVCRBvr@@PEAV1@0@Z>

externdef __imp_?CRSequenceArray@@YAPEAVCRBvr@@JQEAPEAV1@@Z:PPROC
?CRSequenceArray@@YAPEAVCRBvr@@JQEAPEAV1@@Z equ <__imp_?CRSequenceArray@@YAPEAVCRBvr@@JQEAPEAV1@@Z>

externdef __imp_?CRSetBvrAsProperty@@YA_NPEAVCRDXTransformResult@@PEBGPEAVCRBvr@@@Z:PPROC
?CRSetBvrAsProperty@@YA_NPEAVCRDXTransformResult@@PEBGPEAVCRBvr@@@Z equ <__imp_?CRSetBvrAsProperty@@YA_NPEAVCRDXTransformResult@@PEBGPEAVCRBvr@@@Z>

externdef __imp_?CRSetClipRect@@YA_NPEAVCRView@@JJJJ@Z:PPROC
?CRSetClipRect@@YA_NPEAVCRView@@JJJJ@Z equ <__imp_?CRSetClipRect@@YA_NPEAVCRView@@JJJJ@Z>

externdef __imp_?CRSetCompositeDirectlyToTarget@@YA_NPEAVCRView@@_N@Z:PPROC
?CRSetCompositeDirectlyToTarget@@YA_NPEAVCRView@@_N@Z equ <__imp_?CRSetCompositeDirectlyToTarget@@YA_NPEAVCRView@@_N@Z>

externdef __imp_?CRSetDC@@YA_NPEAVCRView@@PEAUHDC__@@@Z:PPROC
?CRSetDC@@YA_NPEAVCRView@@PEAUHDC__@@@Z equ <__imp_?CRSetDC@@YA_NPEAVCRView@@PEAUHDC__@@@Z>

externdef __imp_?CRSetDirectDrawSurface@@YA_NPEAVCRView@@PEAUIUnknown@@@Z:PPROC
?CRSetDirectDrawSurface@@YA_NPEAVCRView@@PEAUIUnknown@@@Z equ <__imp_?CRSetDirectDrawSurface@@YA_NPEAVCRView@@PEAUIUnknown@@@Z>

externdef __imp_?CRSetElement@@YA_NPEAVCRArray@@JPEAVCRBvr@@J@Z:PPROC
?CRSetElement@@YA_NPEAVCRArray@@JPEAVCRBvr@@J@Z equ <__imp_?CRSetElement@@YA_NPEAVCRArray@@JPEAVCRBvr@@J@Z>

externdef __imp_?CRSetImportPriority@@YA_NPEAVCRBvr@@M@Z:PPROC
?CRSetImportPriority@@YA_NPEAVCRBvr@@M@Z equ <__imp_?CRSetImportPriority@@YA_NPEAVCRBvr@@M@Z>

externdef __imp_?CRSetLastError@@YAXJPEBG@Z:PPROC
?CRSetLastError@@YAXJPEBG@Z equ <__imp_?CRSetLastError@@YAXJPEBG@Z>

externdef __imp_?CRSetServiceProvider@@YA_NPEAVCRView@@PEAUIServiceProvider@@@Z:PPROC
?CRSetServiceProvider@@YA_NPEAVCRView@@PEAUIServiceProvider@@@Z equ <__imp_?CRSetServiceProvider@@YA_NPEAVCRView@@PEAUIServiceProvider@@@Z>

externdef __imp_?CRSetSite@@YA_NPEAVCRView@@PEAVCRViewSite@@@Z:PPROC
?CRSetSite@@YA_NPEAVCRView@@PEAVCRViewSite@@@Z equ <__imp_?CRSetSite@@YA_NPEAVCRView@@PEAVCRViewSite@@@Z>

externdef __imp_?CRSetViewport@@YA_NPEAVCRView@@JJJJ@Z:PPROC
?CRSetViewport@@YA_NPEAVCRView@@JJJJ@Z equ <__imp_?CRSetViewport@@YA_NPEAVCRView@@JJJJ@Z>

externdef __imp_?CRSetWindow@@YA_NPEAVCRView@@PEAUHWND__@@@Z:PPROC
?CRSetWindow@@YA_NPEAVCRView@@PEAUHWND__@@@Z equ <__imp_?CRSetWindow@@YA_NPEAVCRView@@PEAUHWND__@@@Z>

externdef __imp_?CRShadow@@YAPEAVCRGeometry@@PEAV1@0PEAVCRPoint3@@PEAVCRVector3@@@Z:PPROC
?CRShadow@@YAPEAVCRGeometry@@PEAV1@0PEAVCRPoint3@@PEAVCRVector3@@@Z equ <__imp_?CRShadow@@YAPEAVCRGeometry@@PEAV1@0PEAVCRPoint3@@PEAVCRVector3@@@Z>

externdef __imp_?CRSilence@@YAPEAVCRSound@@XZ:PPROC
?CRSilence@@YAPEAVCRSound@@XZ equ <__imp_?CRSilence@@YAPEAVCRSound@@XZ>

externdef __imp_?CRSilver@@YAPEAVCRColor@@XZ:PPROC
?CRSilver@@YAPEAVCRColor@@XZ equ <__imp_?CRSilver@@YAPEAVCRColor@@XZ>

externdef __imp_?CRSin@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRSin@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRSin@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRSinSynth@@YAPEAVCRSound@@XZ:PPROC
?CRSinSynth@@YAPEAVCRSound@@XZ equ <__imp_?CRSinSynth@@YAPEAVCRSound@@XZ>

externdef __imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@N@Z:PPROC
?CRSize@@YAPEAVCRFontStyle@@PEAV1@N@Z equ <__imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@N@Z>

externdef __imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRSize@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRSize@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@NNNN@Z:PPROC
?CRSlowInSlowOut@@YAPEAVCRNumber@@NNNN@Z equ <__imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@NNNN@Z>

externdef __imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@PEAV1@000@Z:PPROC
?CRSlowInSlowOut@@YAPEAVCRNumber@@PEAV1@000@Z equ <__imp_?CRSlowInSlowOut@@YAPEAVCRNumber@@PEAV1@000@Z>

externdef __imp_?CRSnapshot@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z:PPROC
?CRSnapshot@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z equ <__imp_?CRSnapshot@@YAPEAVCREvent@@PEAV1@PEAVCRBvr@@@Z>

externdef __imp_?CRSolidColorImage@@YAPEAVCRImage@@PEAVCRColor@@@Z:PPROC
?CRSolidColorImage@@YAPEAVCRImage@@PEAVCRColor@@@Z equ <__imp_?CRSolidColorImage@@YAPEAVCRImage@@PEAVCRColor@@@Z>

externdef __imp_?CRSoundSource@@YAPEAVCRGeometry@@PEAVCRSound@@@Z:PPROC
?CRSoundSource@@YAPEAVCRGeometry@@PEAVCRSound@@@Z equ <__imp_?CRSoundSource@@YAPEAVCRGeometry@@PEAVCRSound@@@Z>

externdef __imp_?CRSpecularColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRSpecularColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRSpecularColor@@YAPEAVCRGeometry@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRSpecularExponent@@YAPEAVCRGeometry@@PEAV1@N@Z:PPROC
?CRSpecularExponent@@YAPEAVCRGeometry@@PEAV1@N@Z equ <__imp_?CRSpecularExponent@@YAPEAVCRGeometry@@PEAV1@N@Z>

externdef __imp_?CRSpecularExponentAnim@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRSpecularExponentAnim@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRSpecularExponentAnim@@YAPEAVCRGeometry@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PPROC
?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z equ <__imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>

externdef __imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRSphericalCoordLength@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PPROC
?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z equ <__imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>

externdef __imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRSphericalCoordXYAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z:PPROC
?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z equ <__imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRPoint3@@@Z>

externdef __imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z:PPROC
?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z equ <__imp_?CRSphericalCoordYZAngle@@YAPEAVCRNumber@@PEAVCRVector3@@@Z>

externdef __imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@0@Z:PPROC
?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@0@Z equ <__imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@0@Z>

externdef __imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@N@Z:PPROC
?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@N@Z equ <__imp_?CRSpotLight@@YAPEAVCRGeometry@@PEAVCRNumber@@N@Z>

externdef __imp_?CRSqrt@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRSqrt@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRSqrt@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRStartModel@@YA_NPEAVCRView@@PEAVCRImage@@PEAVCRSound@@NKPEA_N@Z:PPROC
?CRStartModel@@YA_NPEAVCRView@@PEAVCRImage@@PEAVCRSound@@NKPEA_N@Z equ <__imp_?CRStartModel@@YA_NPEAVCRView@@PEAVCRImage@@PEAVCRSound@@NKPEA_N@Z>

externdef __imp_?CRStopModel@@YA_NPEAVCRView@@@Z:PPROC
?CRStopModel@@YA_NPEAVCRView@@@Z equ <__imp_?CRStopModel@@YA_NPEAVCRView@@@Z>

externdef __imp_?CRStrikethrough@@YAPEAVCRFontStyle@@PEAV1@@Z:PPROC
?CRStrikethrough@@YAPEAVCRFontStyle@@PEAV1@@Z equ <__imp_?CRStrikethrough@@YAPEAVCRFontStyle@@PEAV1@@Z>

externdef __imp_?CRStringImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z:PPROC
?CRStringImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z equ <__imp_?CRStringImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z>

externdef __imp_?CRStringImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z:PPROC
?CRStringImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z equ <__imp_?CRStringImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z>

externdef __imp_?CRStringPath@@YAPEAVCRPath2@@PEAGPEAVCRFontStyle@@@Z:PPROC
?CRStringPath@@YAPEAVCRPath2@@PEAGPEAVCRFontStyle@@@Z equ <__imp_?CRStringPath@@YAPEAVCRPath2@@PEAGPEAVCRFontStyle@@@Z>

externdef __imp_?CRStringPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z:PPROC
?CRStringPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z equ <__imp_?CRStringPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z>

externdef __imp_?CRSub@@YAPEAVCRNumber@@PEAV1@0@Z:PPROC
?CRSub@@YAPEAVCRNumber@@PEAV1@0@Z equ <__imp_?CRSub@@YAPEAVCRNumber@@PEAV1@0@Z>

externdef __imp_?CRSub@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z:PPROC
?CRSub@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z equ <__imp_?CRSub@@YAPEAVCRPoint2@@PEAV1@PEAVCRVector2@@@Z>

externdef __imp_?CRSub@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z:PPROC
?CRSub@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z equ <__imp_?CRSub@@YAPEAVCRPoint3@@PEAV1@PEAVCRVector3@@@Z>

externdef __imp_?CRSub@@YAPEAVCRVector2@@PEAV1@0@Z:PPROC
?CRSub@@YAPEAVCRVector2@@PEAV1@0@Z equ <__imp_?CRSub@@YAPEAVCRVector2@@PEAV1@0@Z>

externdef __imp_?CRSub@@YAPEAVCRVector2@@PEAVCRPoint2@@0@Z:PPROC
?CRSub@@YAPEAVCRVector2@@PEAVCRPoint2@@0@Z equ <__imp_?CRSub@@YAPEAVCRVector2@@PEAVCRPoint2@@0@Z>

externdef __imp_?CRSub@@YAPEAVCRVector3@@PEAV1@0@Z:PPROC
?CRSub@@YAPEAVCRVector3@@PEAV1@0@Z equ <__imp_?CRSub@@YAPEAVCRVector3@@PEAV1@0@Z>

externdef __imp_?CRSub@@YAPEAVCRVector3@@PEAVCRPoint3@@0@Z:PPROC
?CRSub@@YAPEAVCRVector3@@PEAVCRPoint3@@0@Z equ <__imp_?CRSub@@YAPEAVCRVector3@@PEAVCRPoint3@@0@Z>

externdef __imp_?CRSubstituteTime@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRSubstituteTime@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRSubstituteTime@@YAPEAVCRBvr@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRSwitchTo@@YA_NPEAVCRBvr@@0_NKN@Z:PPROC
?CRSwitchTo@@YA_NPEAVCRBvr@@0_NKN@Z equ <__imp_?CRSwitchTo@@YA_NPEAVCRBvr@@0_NKN@Z>

externdef __imp_?CRSwitchToBool@@YA_NPEAVCRBoolean@@_N@Z:PPROC
?CRSwitchToBool@@YA_NPEAVCRBoolean@@_N@Z equ <__imp_?CRSwitchToBool@@YA_NPEAVCRBoolean@@_N@Z>

externdef __imp_?CRSwitchToNumber@@YA_NPEAVCRNumber@@N@Z:PPROC
?CRSwitchToNumber@@YA_NPEAVCRNumber@@N@Z equ <__imp_?CRSwitchToNumber@@YA_NPEAVCRNumber@@N@Z>

externdef __imp_?CRSwitchToString@@YA_NPEAVCRString@@PEAG@Z:PPROC
?CRSwitchToString@@YA_NPEAVCRString@@PEAG@Z equ <__imp_?CRSwitchToString@@YA_NPEAVCRString@@PEAG@Z>

externdef __imp_?CRTan@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRTan@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRTan@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRTeal@@YAPEAVCRColor@@XZ:PPROC
?CRTeal@@YAPEAVCRColor@@XZ equ <__imp_?CRTeal@@YAPEAVCRColor@@XZ>

externdef __imp_?CRTextColor@@YAPEAVCRFontStyle@@PEAV1@PEAVCRColor@@@Z:PPROC
?CRTextColor@@YAPEAVCRFontStyle@@PEAV1@PEAVCRColor@@@Z equ <__imp_?CRTextColor@@YAPEAVCRFontStyle@@PEAV1@PEAVCRColor@@@Z>

externdef __imp_?CRTextImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z:PPROC
?CRTextImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z equ <__imp_?CRTextImage@@YAPEAVCRImage@@PEAGPEAVCRFontStyle@@@Z>

externdef __imp_?CRTextImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z:PPROC
?CRTextImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z equ <__imp_?CRTextImage@@YAPEAVCRImage@@PEAVCRString@@PEAVCRFontStyle@@@Z>

externdef __imp_?CRTextMatte@@YAPEAVCRMatte@@PEAVCRString@@PEAVCRFontStyle@@@Z:PPROC
?CRTextMatte@@YAPEAVCRMatte@@PEAVCRString@@PEAVCRFontStyle@@@Z equ <__imp_?CRTextMatte@@YAPEAVCRMatte@@PEAVCRString@@PEAVCRFontStyle@@@Z>

externdef __imp_?CRTextPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z:PPROC
?CRTextPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z equ <__imp_?CRTextPath@@YAPEAVCRPath2@@PEAVCRString@@PEAVCRFontStyle@@@Z>

externdef __imp_?CRTexture@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z:PPROC
?CRTexture@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z equ <__imp_?CRTexture@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z>

externdef __imp_?CRTextureImage@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z:PPROC
?CRTextureImage@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z equ <__imp_?CRTextureImage@@YAPEAVCRGeometry@@PEAV1@PEAVCRImage@@@Z>

externdef __imp_?CRThenEvent@@YAPEAVCREvent@@PEAV1@0@Z:PPROC
?CRThenEvent@@YAPEAVCREvent@@PEAV1@0@Z equ <__imp_?CRThenEvent@@YAPEAVCREvent@@PEAV1@0@Z>

externdef __imp_?CRTick@@YA_NPEAVCRView@@NPEA_N@Z:PPROC
?CRTick@@YA_NPEAVCRView@@NPEA_N@Z equ <__imp_?CRTick@@YA_NPEAVCRView@@NPEA_N@Z>

externdef __imp_?CRTile@@YAPEAVCRImage@@PEAV1@@Z:PPROC
?CRTile@@YAPEAVCRImage@@PEAV1@@Z equ <__imp_?CRTile@@YAPEAVCRImage@@PEAV1@@Z>

externdef __imp_?CRTimer@@YAPEAVCREvent@@N@Z:PPROC
?CRTimer@@YAPEAVCREvent@@N@Z equ <__imp_?CRTimer@@YAPEAVCREvent@@N@Z>

externdef __imp_?CRTimer@@YAPEAVCREvent@@PEAVCRNumber@@@Z:PPROC
?CRTimer@@YAPEAVCREvent@@PEAVCRNumber@@@Z equ <__imp_?CRTimer@@YAPEAVCREvent@@PEAVCRNumber@@@Z>

externdef __imp_?CRToDegrees@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRToDegrees@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRToDegrees@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRToRadians@@YAPEAVCRNumber@@PEAV1@@Z:PPROC
?CRToRadians@@YAPEAVCRNumber@@PEAV1@@Z equ <__imp_?CRToRadians@@YAPEAVCRNumber@@PEAV1@@Z>

externdef __imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@0@Z:PPROC
?CRToString@@YAPEAVCRString@@PEAVCRNumber@@0@Z equ <__imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@0@Z>

externdef __imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@N@Z:PPROC
?CRToString@@YAPEAVCRString@@PEAVCRNumber@@N@Z equ <__imp_?CRToString@@YAPEAVCRString@@PEAVCRNumber@@N@Z>

externdef __imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEANI@Z:PPROC
?CRTransform3x2@@YAPEAVCRTransform2@@PEANI@Z equ <__imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEANI@Z>

externdef __imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z:PPROC
?CRTransform3x2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z equ <__imp_?CRTransform3x2@@YAPEAVCRTransform2@@PEAVCRArray@@@Z>

externdef __imp_?CRTransform4x4@@YAPEAVCRTransform3@@PEAVCRArray@@@Z:PPROC
?CRTransform4x4@@YAPEAVCRTransform3@@PEAVCRArray@@@Z equ <__imp_?CRTransform4x4@@YAPEAVCRTransform3@@PEAVCRArray@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRCamera@@PEAV1@PEAVCRTransform3@@@Z:PPROC
?CRTransform@@YAPEAVCRCamera@@PEAV1@PEAVCRTransform3@@@Z equ <__imp_?CRTransform@@YAPEAVCRCamera@@PEAV1@PEAVCRTransform3@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRGeometry@@PEAV1@PEAVCRTransform3@@@Z:PPROC
?CRTransform@@YAPEAVCRGeometry@@PEAV1@PEAVCRTransform3@@@Z equ <__imp_?CRTransform@@YAPEAVCRGeometry@@PEAV1@PEAVCRTransform3@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRImage@@PEAV1@PEAVCRTransform2@@@Z:PPROC
?CRTransform@@YAPEAVCRImage@@PEAV1@PEAVCRTransform2@@@Z equ <__imp_?CRTransform@@YAPEAVCRImage@@PEAV1@PEAVCRTransform2@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRMatte@@PEAV1@PEAVCRTransform2@@@Z:PPROC
?CRTransform@@YAPEAVCRMatte@@PEAV1@PEAVCRTransform2@@@Z equ <__imp_?CRTransform@@YAPEAVCRMatte@@PEAV1@PEAVCRTransform2@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRMicrophone@@PEAV1@PEAVCRTransform3@@@Z:PPROC
?CRTransform@@YAPEAVCRMicrophone@@PEAV1@PEAVCRTransform3@@@Z equ <__imp_?CRTransform@@YAPEAVCRMicrophone@@PEAV1@PEAVCRTransform3@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRPath2@@PEAV1@PEAVCRTransform2@@@Z:PPROC
?CRTransform@@YAPEAVCRPath2@@PEAV1@PEAVCRTransform2@@@Z equ <__imp_?CRTransform@@YAPEAVCRPath2@@PEAV1@PEAVCRTransform2@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRPoint2@@PEAV1@PEAVCRTransform2@@@Z:PPROC
?CRTransform@@YAPEAVCRPoint2@@PEAV1@PEAVCRTransform2@@@Z equ <__imp_?CRTransform@@YAPEAVCRPoint2@@PEAV1@PEAVCRTransform2@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRPoint3@@PEAV1@PEAVCRTransform3@@@Z:PPROC
?CRTransform@@YAPEAVCRPoint3@@PEAV1@PEAVCRTransform3@@@Z equ <__imp_?CRTransform@@YAPEAVCRPoint3@@PEAV1@PEAVCRTransform3@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRVector2@@PEAV1@PEAVCRTransform2@@@Z:PPROC
?CRTransform@@YAPEAVCRVector2@@PEAV1@PEAVCRTransform2@@@Z equ <__imp_?CRTransform@@YAPEAVCRVector2@@PEAV1@PEAVCRTransform2@@@Z>

externdef __imp_?CRTransform@@YAPEAVCRVector3@@PEAV1@PEAVCRTransform3@@@Z:PPROC
?CRTransform@@YAPEAVCRVector3@@PEAV1@PEAVCRTransform3@@@Z equ <__imp_?CRTransform@@YAPEAVCRVector3@@PEAV1@PEAVCRTransform3@@@Z>

externdef __imp_?CRTransformCharacters@@YAPEAVCRFontStyle@@PEAV1@PEAVCRTransform2@@@Z:PPROC
?CRTransformCharacters@@YAPEAVCRFontStyle@@PEAV1@PEAVCRTransform2@@@Z equ <__imp_?CRTransformCharacters@@YAPEAVCRFontStyle@@PEAV1@PEAVCRTransform2@@@Z>

externdef __imp_?CRTransformColorRGB@@YAPEAVCRImage@@PEAV1@PEAVCRTransform3@@@Z:PPROC
?CRTransformColorRGB@@YAPEAVCRImage@@PEAV1@PEAVCRTransform3@@@Z equ <__imp_?CRTransformColorRGB@@YAPEAVCRImage@@PEAV1@PEAVCRTransform3@@@Z>

externdef __imp_?CRTranslate2@@YAPEAVCRTransform2@@NN@Z:PPROC
?CRTranslate2@@YAPEAVCRTransform2@@NN@Z equ <__imp_?CRTranslate2@@YAPEAVCRTransform2@@NN@Z>

externdef __imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z:PPROC
?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z equ <__imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRPoint2@@@Z:PPROC
?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRPoint2@@@Z equ <__imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRPoint2@@@Z>

externdef __imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z:PPROC
?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z equ <__imp_?CRTranslate2@@YAPEAVCRTransform2@@PEAVCRVector2@@@Z>

externdef __imp_?CRTranslate3@@YAPEAVCRTransform3@@NNN@Z:PPROC
?CRTranslate3@@YAPEAVCRTransform3@@NNN@Z equ <__imp_?CRTranslate3@@YAPEAVCRTransform3@@NNN@Z>

externdef __imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z:PPROC
?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z equ <__imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRNumber@@00@Z>

externdef __imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRPoint3@@@Z:PPROC
?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRPoint3@@@Z equ <__imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRPoint3@@@Z>

externdef __imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z:PPROC
?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z equ <__imp_?CRTranslate3@@YAPEAVCRTransform3@@PEAVCRVector3@@@Z>

externdef __imp_?CRTriMesh@@YAPEAVCRGeometry@@AEAVTriMeshData@@@Z:PPROC
?CRTriMesh@@YAPEAVCRGeometry@@AEAVTriMeshData@@@Z equ <__imp_?CRTriMesh@@YAPEAVCRGeometry@@AEAVTriMeshData@@@Z>

externdef __imp_?CRTriggerEvent@@YA_NPEAVCREvent@@PEAVCRBvr@@@Z:PPROC
?CRTriggerEvent@@YA_NPEAVCREvent@@PEAVCRBvr@@@Z equ <__imp_?CRTriggerEvent@@YA_NPEAVCREvent@@PEAVCRBvr@@@Z>

externdef __imp_?CRTrue@@YAPEAVCRBoolean@@XZ:PPROC
?CRTrue@@YAPEAVCRBoolean@@XZ equ <__imp_?CRTrue@@YAPEAVCRBoolean@@XZ>

externdef __imp_?CRUnderline@@YAPEAVCRFontStyle@@PEAV1@@Z:PPROC
?CRUnderline@@YAPEAVCRFontStyle@@PEAV1@@Z equ <__imp_?CRUnderline@@YAPEAVCRFontStyle@@PEAV1@@Z>

externdef __imp_?CRUndetectable@@YAPEAVCRGeometry@@PEAV1@@Z:PPROC
?CRUndetectable@@YAPEAVCRGeometry@@PEAV1@@Z equ <__imp_?CRUndetectable@@YAPEAVCRGeometry@@PEAV1@@Z>

externdef __imp_?CRUndetectable@@YAPEAVCRImage@@PEAV1@@Z:PPROC
?CRUndetectable@@YAPEAVCRImage@@PEAV1@@Z equ <__imp_?CRUndetectable@@YAPEAVCRImage@@PEAV1@@Z>

externdef __imp_?CRUninitializedArray@@YAPEAVCRArray@@PEAV1@@Z:PPROC
?CRUninitializedArray@@YAPEAVCRArray@@PEAV1@@Z equ <__imp_?CRUninitializedArray@@YAPEAVCRArray@@PEAV1@@Z>

externdef __imp_?CRUninitializedBvr@@YAPEAVCRBvr@@W4CR_BVR_TYPEID@@@Z:PPROC
?CRUninitializedBvr@@YAPEAVCRBvr@@W4CR_BVR_TYPEID@@@Z equ <__imp_?CRUninitializedBvr@@YAPEAVCRBvr@@W4CR_BVR_TYPEID@@@Z>

externdef __imp_?CRUninitializedTuple@@YAPEAVCRTuple@@PEAV1@@Z:PPROC
?CRUninitializedTuple@@YAPEAVCRTuple@@PEAV1@@Z equ <__imp_?CRUninitializedTuple@@YAPEAVCRTuple@@PEAV1@@Z>

externdef __imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAV1@0@Z:PPROC
?CRUnionGeometry@@YAPEAVCRGeometry@@PEAV1@0@Z equ <__imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAV1@0@Z>

externdef __imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAVCRArray@@@Z:PPROC
?CRUnionGeometry@@YAPEAVCRGeometry@@PEAVCRArray@@@Z equ <__imp_?CRUnionGeometry@@YAPEAVCRGeometry@@PEAVCRArray@@@Z>

externdef __imp_?CRUnionMatte@@YAPEAVCRMatte@@PEAV1@0@Z:PPROC
?CRUnionMatte@@YAPEAVCRMatte@@PEAV1@0@Z equ <__imp_?CRUnionMatte@@YAPEAVCRMatte@@PEAV1@0@Z>

externdef __imp_?CRUnionMontage@@YAPEAVCRMontage@@PEAV1@0@Z:PPROC
?CRUnionMontage@@YAPEAVCRMontage@@PEAV1@0@Z equ <__imp_?CRUnionMontage@@YAPEAVCRMontage@@PEAV1@0@Z>

externdef __imp_?CRUnionMontageArray@@YAPEAVCRMontage@@PEAVCRArray@@@Z:PPROC
?CRUnionMontageArray@@YAPEAVCRMontage@@PEAVCRArray@@@Z equ <__imp_?CRUnionMontageArray@@YAPEAVCRMontage@@PEAVCRArray@@@Z>

externdef __imp_?CRUntil@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@0@Z:PPROC
?CRUntil@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@0@Z equ <__imp_?CRUntil@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@0@Z>

externdef __imp_?CRUntilEx@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@@Z:PPROC
?CRUntilEx@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@@Z equ <__imp_?CRUntilEx@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@@Z>

externdef __imp_?CRUntilNotify@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@PEAVCRUntilNotifier@@@Z:PPROC
?CRUntilNotify@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@PEAVCRUntilNotifier@@@Z equ <__imp_?CRUntilNotify@@YAPEAVCRBvr@@PEAV1@PEAVCREvent@@PEAVCRUntilNotifier@@@Z>

externdef __imp_?CRVector2Polar@@YAPEAVCRVector2@@NN@Z:PPROC
?CRVector2Polar@@YAPEAVCRVector2@@NN@Z equ <__imp_?CRVector2Polar@@YAPEAVCRVector2@@NN@Z>

externdef __imp_?CRVector2Polar@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z:PPROC
?CRVector2Polar@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z equ <__imp_?CRVector2Polar@@YAPEAVCRVector2@@PEAVCRNumber@@0@Z>

externdef __imp_?CRVector3Spherical@@YAPEAVCRVector3@@NNN@Z:PPROC
?CRVector3Spherical@@YAPEAVCRVector3@@NNN@Z equ <__imp_?CRVector3Spherical@@YAPEAVCRVector3@@NNN@Z>

externdef __imp_?CRVector3Spherical@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z:PPROC
?CRVector3Spherical@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z equ <__imp_?CRVector3Spherical@@YAPEAVCRVector3@@PEAVCRNumber@@00@Z>

externdef __imp_?CRVersionString@@YAPEBGXZ:PPROC
?CRVersionString@@YAPEBGXZ equ <__imp_?CRVersionString@@YAPEBGXZ>

externdef __imp_?CRViewFrameRate@@YAPEAVCRNumber@@XZ:PPROC
?CRViewFrameRate@@YAPEAVCRNumber@@XZ equ <__imp_?CRViewFrameRate@@YAPEAVCRNumber@@XZ>

externdef __imp_?CRViewTimeDelta@@YAPEAVCRNumber@@XZ:PPROC
?CRViewTimeDelta@@YAPEAVCRNumber@@XZ equ <__imp_?CRViewTimeDelta@@YAPEAVCRNumber@@XZ>

externdef __imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@N@Z:PPROC
?CRWeight@@YAPEAVCRFontStyle@@PEAV1@N@Z equ <__imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@N@Z>

externdef __imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRWeight@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRWeight@@YAPEAVCRFontStyle@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRWhite@@YAPEAVCRColor@@XZ:PPROC
?CRWhite@@YAPEAVCRColor@@XZ equ <__imp_?CRWhite@@YAPEAVCRColor@@XZ>

externdef __imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@N@Z:PPROC
?CRWidth@@YAPEAVCRLineStyle@@PEAV1@N@Z equ <__imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@N@Z>

externdef __imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z:PPROC
?CRWidth@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z equ <__imp_?CRWidth@@YAPEAVCRLineStyle@@PEAV1@PEAVCRNumber@@@Z>

externdef __imp_?CRXShear2@@YAPEAVCRTransform2@@N@Z:PPROC
?CRXShear2@@YAPEAVCRTransform2@@N@Z equ <__imp_?CRXShear2@@YAPEAVCRTransform2@@N@Z>

externdef __imp_?CRXShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PPROC
?CRXShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z equ <__imp_?CRXShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>

externdef __imp_?CRXShear3@@YAPEAVCRTransform3@@NN@Z:PPROC
?CRXShear3@@YAPEAVCRTransform3@@NN@Z equ <__imp_?CRXShear3@@YAPEAVCRTransform3@@NN@Z>

externdef __imp_?CRXShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z:PPROC
?CRXShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z equ <__imp_?CRXShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z>

externdef __imp_?CRXVector2@@YAPEAVCRVector2@@XZ:PPROC
?CRXVector2@@YAPEAVCRVector2@@XZ equ <__imp_?CRXVector2@@YAPEAVCRVector2@@XZ>

externdef __imp_?CRXVector3@@YAPEAVCRVector3@@XZ:PPROC
?CRXVector3@@YAPEAVCRVector3@@XZ equ <__imp_?CRXVector3@@YAPEAVCRVector3@@XZ>

externdef __imp_?CRYShear2@@YAPEAVCRTransform2@@N@Z:PPROC
?CRYShear2@@YAPEAVCRTransform2@@N@Z equ <__imp_?CRYShear2@@YAPEAVCRTransform2@@N@Z>

externdef __imp_?CRYShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z:PPROC
?CRYShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z equ <__imp_?CRYShear2@@YAPEAVCRTransform2@@PEAVCRNumber@@@Z>

externdef __imp_?CRYShear3@@YAPEAVCRTransform3@@NN@Z:PPROC
?CRYShear3@@YAPEAVCRTransform3@@NN@Z equ <__imp_?CRYShear3@@YAPEAVCRTransform3@@NN@Z>

externdef __imp_?CRYShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z:PPROC
?CRYShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z equ <__imp_?CRYShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z>

externdef __imp_?CRYVector2@@YAPEAVCRVector2@@XZ:PPROC
?CRYVector2@@YAPEAVCRVector2@@XZ equ <__imp_?CRYVector2@@YAPEAVCRVector2@@XZ>

externdef __imp_?CRYVector3@@YAPEAVCRVector3@@XZ:PPROC
?CRYVector3@@YAPEAVCRVector3@@XZ equ <__imp_?CRYVector3@@YAPEAVCRVector3@@XZ>

externdef __imp_?CRYellow@@YAPEAVCRColor@@XZ:PPROC
?CRYellow@@YAPEAVCRColor@@XZ equ <__imp_?CRYellow@@YAPEAVCRColor@@XZ>

externdef __imp_?CRZShear3@@YAPEAVCRTransform3@@NN@Z:PPROC
?CRZShear3@@YAPEAVCRTransform3@@NN@Z equ <__imp_?CRZShear3@@YAPEAVCRTransform3@@NN@Z>

externdef __imp_?CRZShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z:PPROC
?CRZShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z equ <__imp_?CRZShear3@@YAPEAVCRTransform3@@PEAVCRNumber@@0@Z>

externdef __imp_?CRZVector3@@YAPEAVCRVector3@@XZ:PPROC
?CRZVector3@@YAPEAVCRVector3@@XZ equ <__imp_?CRZVector3@@YAPEAVCRVector3@@XZ>

externdef __imp_?CRZeroVector2@@YAPEAVCRVector2@@XZ:PPROC
?CRZeroVector2@@YAPEAVCRVector2@@XZ equ <__imp_?CRZeroVector2@@YAPEAVCRVector2@@XZ>

externdef __imp_?CRZeroVector3@@YAPEAVCRVector3@@XZ:PPROC
?CRZeroVector3@@YAPEAVCRVector3@@XZ equ <__imp_?CRZeroVector3@@YAPEAVCRVector3@@XZ>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
