externdef __imp_DavFreeUsedDiskSpace:PPROC
DavFreeUsedDiskSpace equ <__imp_DavFreeUsedDiskSpace>

externdef __imp_DavGetDiskSpaceUsage:PPROC
DavGetDiskSpaceUsage equ <__imp_DavGetDiskSpaceUsage>

externdef __imp_DavGetTheLockOwnerOfTheFile:PPROC
DavGetTheLockOwnerOfTheFile equ <__imp_DavGetTheLockOwnerOfTheFile>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_NPAddConnection3:PPROC
NPAddConnection3 equ <__imp_NPAddConnection3>

externdef __imp_NPAddConnection:PPROC
NPAddConnection equ <__imp_NPAddConnection>

externdef __imp_NPCancelConnection:PPROC
NPCancelConnection equ <__imp_NPCancelConnection>

externdef __imp_NPCloseEnum:PPROC
NPCloseEnum equ <__imp_NPCloseEnum>

externdef __imp_NPEnumResource:PPROC
NPEnumResource equ <__imp_NPEnumResource>

externdef __imp_NPFormatNetworkName:PPROC
NPFormatNetworkName equ <__imp_NPFormatNetworkName>

externdef __imp_NPGetCaps:PPROC
NPGetCaps equ <__imp_NPGetCaps>

externdef __imp_NPGetConnection:PPROC
NPGetConnection equ <__imp_NPGetConnection>

externdef __imp_NPGetResourceInformation:PPROC
NPGetResourceInformation equ <__imp_NPGetResourceInformation>

externdef __imp_NPGetResourceParent:PPROC
NPGetResourceParent equ <__imp_NPGetResourceParent>

externdef __imp_NPGetUniversalName:PPROC
NPGetUniversalName equ <__imp_NPGetUniversalName>

externdef __imp_NPGetUser:PPROC
NPGetUser equ <__imp_NPGetUser>

externdef __imp_NPOpenEnum:PPROC
NPOpenEnum equ <__imp_NPOpenEnum>
