externdef __imp_DCIBeginAccess:PPROC
DCIBeginAccess equ <__imp_DCIBeginAccess>

externdef __imp_DCICloseProvider:PPROC
DCICloseProvider equ <__imp_DCICloseProvider>

externdef __imp_DCICreateOffscreen:PPROC
DCICreateOffscreen equ <__imp_DCICreateOffscreen>

externdef __imp_DCICreateOverlay:PPROC
DCICreateOverlay equ <__imp_DCICreateOverlay>

externdef __imp_DCICreatePrimary:PPROC
DCICreatePrimary equ <__imp_DCICreatePrimary>

externdef __imp_DCIDestroy:PPROC
DCIDestroy equ <__imp_DCIDestroy>

externdef __imp_DCIDraw:PPROC
DCIDraw equ <__imp_DCIDraw>

externdef __imp_DCIEndAccess:PPROC
DCIEndAccess equ <__imp_DCIEndAccess>

externdef __imp_DCIEnum:PPROC
DCIEnum equ <__imp_DCIEnum>

externdef __imp_DCIOpenProvider:PPROC
DCIOpenProvider equ <__imp_DCIOpenProvider>

externdef __imp_DCISetClipList:PPROC
DCISetClipList equ <__imp_DCISetClipList>

externdef __imp_DCISetDestination:PPROC
DCISetDestination equ <__imp_DCISetDestination>

externdef __imp_DCISetSrcDestClip:PPROC
DCISetSrcDestClip equ <__imp_DCISetSrcDestClip>

externdef __imp_GetDCRegionData:PPROC
GetDCRegionData equ <__imp_GetDCRegionData>

externdef __imp_GetWindowRegionData:PPROC
GetWindowRegionData equ <__imp_GetWindowRegionData>

externdef __imp_WinWatchClose:PPROC
WinWatchClose equ <__imp_WinWatchClose>

externdef __imp_WinWatchDidStatusChange:PPROC
WinWatchDidStatusChange equ <__imp_WinWatchDidStatusChange>

externdef __imp_WinWatchGetClipList:PPROC
WinWatchGetClipList equ <__imp_WinWatchGetClipList>

externdef __imp_WinWatchNotify:PPROC
WinWatchNotify equ <__imp_WinWatchNotify>

externdef __imp_WinWatchOpen:PPROC
WinWatchOpen equ <__imp_WinWatchOpen>
