externdef __imp_??0CDbgCallTracer@@QEAA@KPEBD@Z:PPROC
??0CDbgCallTracer@@QEAA@KPEBD@Z equ <__imp_??0CDbgCallTracer@@QEAA@KPEBD@Z>

externdef __imp_??0CDfrgAsyncObject@@QEAA@XZ:PPROC
??0CDfrgAsyncObject@@QEAA@XZ equ <__imp_??0CDfrgAsyncObject@@QEAA@XZ>

externdef __imp_??1CDbgCallTracer@@QEAA@XZ:PPROC
??1CDbgCallTracer@@QEAA@XZ equ <__imp_??1CDbgCallTracer@@QEAA@XZ>

externdef __imp_??1CDfrgAsyncObject@@QEAA@XZ:PPROC
??1CDfrgAsyncObject@@QEAA@XZ equ <__imp_??1CDfrgAsyncObject@@QEAA@XZ>

externdef __imp_?AllowCancel@CDfrgAsyncObject@@QEAAXXZ:PPROC
?AllowCancel@CDfrgAsyncObject@@QEAAXXZ equ <__imp_?AllowCancel@CDfrgAsyncObject@@QEAAXXZ>

externdef __imp_?Cancel@CDfrgAsyncObject@@UEAAJXZ:PPROC
?Cancel@CDfrgAsyncObject@@UEAAJXZ equ <__imp_?Cancel@CDfrgAsyncObject@@UEAAJXZ>

externdef __imp_?DisallowCancel@CDfrgAsyncObject@@QEAAXXZ:PPROC
?DisallowCancel@CDfrgAsyncObject@@QEAAXXZ equ <__imp_?DisallowCancel@CDfrgAsyncObject@@QEAAXXZ>

externdef __imp_?GetDefragReport@CDfrgAsyncObject@@UEAAJPEAU_DEFRAG_REPORT@@@Z:PPROC
?GetDefragReport@CDfrgAsyncObject@@UEAAJPEAU_DEFRAG_REPORT@@@Z equ <__imp_?GetDefragReport@CDfrgAsyncObject@@UEAAJPEAU_DEFRAG_REPORT@@@Z>

externdef __imp_?Initialize@CDfrgAsyncObject@@SAKXZ:PPROC
?Initialize@CDfrgAsyncObject@@SAKXZ equ <__imp_?Initialize@CDfrgAsyncObject@@SAKXZ>

externdef __imp_?IsCancelRequested@CDfrgAsyncObject@@QEAAHXZ:PPROC
?IsCancelRequested@CDfrgAsyncObject@@QEAAHXZ equ <__imp_?IsCancelRequested@CDfrgAsyncObject@@QEAAHXZ>

externdef __imp_?IsFinished@CDfrgAsyncObject@@QEAAHXZ:PPROC
?IsFinished@CDfrgAsyncObject@@QEAAHXZ equ <__imp_?IsFinished@CDfrgAsyncObject@@QEAAHXZ>

externdef __imp_?QueryStatus@CDfrgAsyncObject@@UEAAJPEAJPEAK@Z:PPROC
?QueryStatus@CDfrgAsyncObject@@UEAAJPEAJPEAK@Z equ <__imp_?QueryStatus@CDfrgAsyncObject@@UEAAJPEAJPEAK@Z>

externdef __imp_?SetCompletionStatus@CDfrgAsyncObject@@QEAAXJK@Z:PPROC
?SetCompletionStatus@CDfrgAsyncObject@@QEAAXJK@Z equ <__imp_?SetCompletionStatus@CDfrgAsyncObject@@QEAAXJK@Z>

externdef __imp_?Signal@CDfrgAsyncObject@@QEAAXXZ:PPROC
?Signal@CDfrgAsyncObject@@QEAAXXZ equ <__imp_?Signal@CDfrgAsyncObject@@QEAAXXZ>

externdef __imp_?Uninitialize@CDfrgAsyncObject@@SAXXZ:PPROC
?Uninitialize@CDfrgAsyncObject@@SAXXZ equ <__imp_?Uninitialize@CDfrgAsyncObject@@SAXXZ>

externdef __imp_?Wait@CDfrgAsyncObject@@UEAAJPEAJ@Z:PPROC
?Wait@CDfrgAsyncObject@@UEAAJPEAJ@Z equ <__imp_?Wait@CDfrgAsyncObject@@UEAAJPEAJ@Z>

externdef __imp_?WaitImpl@CDfrgAsyncObject@@QEAAJPEAJ@Z:PPROC
?WaitImpl@CDfrgAsyncObject@@QEAAJPEAJ@Z equ <__imp_?WaitImpl@CDfrgAsyncObject@@QEAAJPEAJ@Z>
