externdef __imp_WlDimsLock:PPROC
WlDimsLock equ <__imp_WlDimsLock>

externdef __imp_WlDimsLogoff:PPROC
WlDimsLogoff equ <__imp_WlDimsLogoff>

externdef __imp_WlDimsLogon:PPROC
WlDimsLogon equ <__imp_WlDimsLogon>

externdef __imp_WlDimsShutdown:PPROC
WlDimsShutdown equ <__imp_WlDimsShutdown>

externdef __imp_WlDimsStartShell:PPROC
WlDimsStartShell equ <__imp_WlDimsStartShell>

externdef __imp_WlDimsStartup:PPROC
WlDimsStartup equ <__imp_WlDimsStartup>

externdef __imp_WlDimsUnlock:PPROC
WlDimsUnlock equ <__imp_WlDimsUnlock>
