externdef __imp_??0CDrCallTracer@@QEAA@KQEBD0PEBJ@Z:PPROC
??0CDrCallTracer@@QEAA@KQEBD0PEBJ@Z equ <__imp_??0CDrCallTracer@@QEAA@KQEBD0PEBJ@Z>

externdef __imp_??1CDrCallTracer@@QEAA@XZ:PPROC
??1CDrCallTracer@@QEAA@XZ equ <__imp_??1CDrCallTracer@@QEAA@XZ>

externdef __imp_?LogMessage@CDrCallTracer@@QEAAXKPEADZZ:PPROC
?LogMessage@CDrCallTracer@@QEAAXKPEADZZ equ <__imp_?LogMessage@CDrCallTracer@@QEAAXKPEADZZ>
