externdef __imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z:PPROC
?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z equ <__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z>

externdef __imp_?FreeArrayOfStrings@@YAXPEAUarrayOfStrings@@@Z:PPROC
?FreeArrayOfStrings@@YAXPEAUarrayOfStrings@@@Z equ <__imp_?FreeArrayOfStrings@@YAXPEAUarrayOfStrings@@@Z>

externdef __imp_?GetDiskCount@CDataCache@@QEAAKXZ:PPROC
?GetDiskCount@CDataCache@@QEAAKXZ equ <__imp_?GetDiskCount@CDataCache@@QEAAKXZ>

externdef __imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ:PPROC
?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ equ <__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ>

externdef __imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ:PPROC
?GetNumMembers@CDMNodeObj@@QEAAKXZ equ <__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ:PPROC
?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ equ <__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ>

externdef __imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z:PPROC
?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z equ <__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z>

externdef __imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ:PPROC
?GetServerName@CDataCache@@QEAA?AVCString@@XZ equ <__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ>

externdef __imp_?GetVolumeCount@CDataCache@@QEAAKXZ:PPROC
?GetVolumeCount@CDataCache@@QEAAKXZ equ <__imp_?GetVolumeCount@CDataCache@@QEAAKXZ>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>
