externdef __imp_??0CDataCache@@QEAA@XZ:PPROC
??0CDataCache@@QEAA@XZ equ <__imp_??0CDataCache@@QEAA@XZ>

externdef __imp_??1CDMNodeObj@@QEAA@XZ:PPROC
??1CDMNodeObj@@QEAA@XZ equ <__imp_??1CDMNodeObj@@QEAA@XZ>

externdef __imp_??1CDataCache@@UEAA@XZ:PPROC
??1CDataCache@@UEAA@XZ equ <__imp_??1CDataCache@@UEAA@XZ>

externdef __imp_?AddFileSystemInfoToListAndMap@CDataCache@@QEAAXKPEAUfilesysteminfo@@@Z:PPROC
?AddFileSystemInfoToListAndMap@CDataCache@@QEAAXKPEAUfilesysteminfo@@@Z equ <__imp_?AddFileSystemInfoToListAndMap@CDataCache@@QEAAXKPEAUfilesysteminfo@@@Z>

externdef __imp_?AddInstalledFileSystemsToList@CDataCache@@QEAAXKPEAUifilesysteminfo@@@Z:PPROC
?AddInstalledFileSystemsToList@CDataCache@@QEAAXKPEAUifilesysteminfo@@@Z equ <__imp_?AddInstalledFileSystemsToList@CDataCache@@QEAAXKPEAUifilesysteminfo@@@Z>

externdef __imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z:PPROC
?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z equ <__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z>

externdef __imp_?AddRegionToVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z:PPROC
?AddRegionToVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z equ <__imp_?AddRegionToVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z>

externdef __imp_?AddRow@CDMComponentData@@QEAAX_J@Z:PPROC
?AddRow@CDMComponentData@@QEAAX_J@Z equ <__imp_?AddRow@CDMComponentData@@QEAAX_J@Z>

externdef __imp_?AdjustRegionCountInLegendList@CDataCache@@QEAAXW4_REGIONTYPE@@H@Z:PPROC
?AdjustRegionCountInLegendList@CDataCache@@QEAAXW4_REGIONTYPE@@H@Z equ <__imp_?AdjustRegionCountInLegendList@CDataCache@@QEAAXW4_REGIONTYPE@@H@Z>

externdef __imp_?AdjustVolumeCountInLegendList@CDataCache@@QEAAXW4_VOLUMELAYOUT@@H@Z:PPROC
?AdjustVolumeCountInLegendList@CDataCache@@QEAAXW4_VOLUMELAYOUT@@H@Z equ <__imp_?AdjustVolumeCountInLegendList@CDataCache@@QEAAXW4_VOLUMELAYOUT@@H@Z>

externdef __imp_?CanHaveGPT@CDMNodeObj@@QEAAHXZ:PPROC
?CanHaveGPT@CDMNodeObj@@QEAAHXZ equ <__imp_?CanHaveGPT@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ChangeRow@CDMComponentData@@QEAAX_J@Z:PPROC
?ChangeRow@CDMComponentData@@QEAAX_J@Z equ <__imp_?ChangeRow@CDMComponentData@@QEAAX_J@Z>

externdef __imp_?Command@CContextMenu@@QEAAJJPEAUIDataObject@@_J@Z:PPROC
?Command@CContextMenu@@QEAAJJPEAUIDataObject@@_J@Z equ <__imp_?Command@CContextMenu@@QEAAJJPEAUIDataObject@@_J@Z>

externdef __imp_?CompareDiskNames@@YAH_J0@Z:PPROC
?CompareDiskNames@@YAH_J0@Z equ <__imp_?CompareDiskNames@@YAH_J0@Z>

externdef __imp_?ContainsActivePartition@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsActivePartition@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsActivePartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsBootIniPartition@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsBootIniPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsBootIniPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsBootIniPartitionForWolfpack@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsBootIniPartitionForWolfpack@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsBootIniPartitionForWolfpack@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsBootVolumesNumberChange@CDMNodeObj@@QEAAH_JPEAH@Z:PPROC
?ContainsBootVolumesNumberChange@CDMNodeObj@@QEAAH_JPEAH@Z equ <__imp_?ContainsBootVolumesNumberChange@CDMNodeObj@@QEAAH_JPEAH@Z>

externdef __imp_?ContainsESPPartition@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsESPPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsESPPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsLogicalDrvBootPartition@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsLogicalDrvBootPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsLogicalDrvBootPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsPageFile@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsPageFile@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsPageFile@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsRealSystemPartition@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsRealSystemPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsRealSystemPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsSubDiskNeedResync@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsSubDiskNeedResync@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsSubDiskNeedResync@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsSystemInformation@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsSystemInformation@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsSystemInformation@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ContainsSystemPartition@CDMNodeObj@@QEAAHXZ:PPROC
?ContainsSystemPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?ContainsSystemPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?ConvertBytesToMB@@YAK_J@Z:PPROC
?ConvertBytesToMB@@YAK_J@Z equ <__imp_?ConvertBytesToMB@@YAK_J@Z>

externdef __imp_?ConvertMBToBytes@@YA_J_J@Z:PPROC
?ConvertMBToBytes@@YA_J_J@Z equ <__imp_?ConvertMBToBytes@@YA_J_J@Z>

externdef __imp_?CookieSort@@YAXPEA_JJJP6AH_J1@Z@Z:PPROC
?CookieSort@@YAXPEA_JJJP6AH_J1@Z@Z equ <__imp_?CookieSort@@YAXPEA_JJJP6AH_J1@Z@Z>

externdef __imp_?CreateDiskList@CDataCache@@QEAAXXZ:PPROC
?CreateDiskList@CDataCache@@QEAAXXZ equ <__imp_?CreateDiskList@CDataCache@@QEAAXXZ>

externdef __imp_?CreateNodeObjAndAddToMap@CDataCache@@QEAAPEAVCDMNodeObj@@HW4_NODEOBJ_TYPES@@PEAV1@PEAX_J@Z:PPROC
?CreateNodeObjAndAddToMap@CDataCache@@QEAAPEAVCDMNodeObj@@HW4_NODEOBJ_TYPES@@PEAV1@PEAX_J@Z equ <__imp_?CreateNodeObjAndAddToMap@CDataCache@@QEAAPEAVCDMNodeObj@@HW4_NODEOBJ_TYPES@@PEAV1@PEAX_J@Z>

externdef __imp_?CreateRegionNodeObj@CDataCache@@QEAAPEAVCDMNodeObj@@PEAV2@PEAUregioninfoex@@@Z:PPROC
?CreateRegionNodeObj@CDataCache@@QEAAPEAVCDMNodeObj@@PEAV2@PEAUregioninfoex@@@Z equ <__imp_?CreateRegionNodeObj@CDataCache@@QEAAPEAVCDMNodeObj@@PEAV2@PEAUregioninfoex@@@Z>

externdef __imp_?CreateShortDiskName@CDataCache@@QEAAXAEAUdiskinfoex@@@Z:PPROC
?CreateShortDiskName@CDataCache@@QEAAXAEAUdiskinfoex@@@Z equ <__imp_?CreateShortDiskName@CDataCache@@QEAAXAEAUdiskinfoex@@@Z>

externdef __imp_?CreateVolumeList@CDataCache@@QEAAXXZ:PPROC
?CreateVolumeList@CDataCache@@QEAAXXZ equ <__imp_?CreateVolumeList@CDataCache@@QEAAXXZ>

externdef __imp_?DeleteDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z:PPROC
?DeleteDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z equ <__imp_?DeleteDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z>

externdef __imp_?DeleteEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z:PPROC
?DeleteEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z equ <__imp_?DeleteEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z>

externdef __imp_?DeleteLists@CDataCache@@QEAAXXZ:PPROC
?DeleteLists@CDataCache@@QEAAXXZ equ <__imp_?DeleteLists@CDataCache@@QEAAXXZ>

externdef __imp_?DeleteRegionFromVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z:PPROC
?DeleteRegionFromVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z equ <__imp_?DeleteRegionFromVolumeMemberList@CDataCache@@QEAAXPEAVCDMNodeObj@@@Z>

externdef __imp_?DeleteRow@CDMComponentData@@QEAAX_J@Z:PPROC
?DeleteRow@CDMComponentData@@QEAAX_J@Z equ <__imp_?DeleteRow@CDMComponentData@@QEAAX_J@Z>

externdef __imp_?DoDelete@CContextMenu@@QEAAX_J@Z:PPROC
?DoDelete@CContextMenu@@QEAAX_J@Z equ <__imp_?DoDelete@CContextMenu@@QEAAX_J@Z>

externdef __imp_?EmptyOcxViewData@CDMComponentData@@QEAAXXZ:PPROC
?EmptyOcxViewData@CDMComponentData@@QEAAXXZ equ <__imp_?EmptyOcxViewData@CDMComponentData@@QEAAXXZ>

externdef __imp_?EnhancedIsUpgradeable@CDMNodeObj@@QEAAHPEAVCTaskData@@@Z:PPROC
?EnhancedIsUpgradeable@CDMNodeObj@@QEAAHPEAVCTaskData@@@Z equ <__imp_?EnhancedIsUpgradeable@CDMNodeObj@@QEAAHPEAVCTaskData@@@Z>

externdef __imp_?EnumDiskRegions@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z:PPROC
?EnumDiskRegions@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z equ <__imp_?EnumDiskRegions@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z>

externdef __imp_?EnumDisks@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PPROC
?EnumDisks@CTaskData@@QEAAXAEAKPEAPEA_J@Z equ <__imp_?EnumDisks@CTaskData@@QEAAXAEAKPEAPEA_J@Z>

externdef __imp_?EnumFirstVolumeMember@CDMNodeObj@@QEAAXAEA_JAEAJ@Z:PPROC
?EnumFirstVolumeMember@CDMNodeObj@@QEAAXAEA_JAEAJ@Z equ <__imp_?EnumFirstVolumeMember@CDMNodeObj@@QEAAXAEA_JAEAJ@Z>

externdef __imp_?EnumNTFSwithDriveLetter@CDataCache@@QEAAXPEAHPEAPEAG@Z:PPROC
?EnumNTFSwithDriveLetter@CDataCache@@QEAAXPEAHPEAPEAG@Z equ <__imp_?EnumNTFSwithDriveLetter@CDataCache@@QEAAXPEAHPEAPEAG@Z>

externdef __imp_?EnumNTFSwithDriveLetter@CTaskData@@QEAAXPEAHPEAPEAG@Z:PPROC
?EnumNTFSwithDriveLetter@CTaskData@@QEAAXPEAHPEAPEAG@Z equ <__imp_?EnumNTFSwithDriveLetter@CTaskData@@QEAAXPEAHPEAPEAG@Z>

externdef __imp_?EnumVolumeMembers@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z:PPROC
?EnumVolumeMembers@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z equ <__imp_?EnumVolumeMembers@CDMNodeObj@@QEAAXPEAPEA_JAEAJ@Z>

externdef __imp_?EnumVolumes@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PPROC
?EnumVolumes@CTaskData@@QEAAXAEAKPEAPEA_J@Z equ <__imp_?EnumVolumes@CTaskData@@QEAAXAEAKPEAPEA_J@Z>

externdef __imp_?FillDeviceInstanceId@CDataCache@@QEAAXPEAG0@Z:PPROC
?FillDeviceInstanceId@CDataCache@@QEAAXPEAG0@Z equ <__imp_?FillDeviceInstanceId@CDataCache@@QEAAXPEAG0@Z>

externdef __imp_?FilterCookiesBigEnoughForFTRepair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z:PPROC
?FilterCookiesBigEnoughForFTRepair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z equ <__imp_?FilterCookiesBigEnoughForFTRepair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z>

externdef __imp_?FilterCookiesBigEnoughForRAID5Repair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z:PPROC
?FilterCookiesBigEnoughForRAID5Repair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z equ <__imp_?FilterCookiesBigEnoughForRAID5Repair@CTaskData@@QEAAXAEAKPEA_JPEAPEA_JJPEAVCDMNodeObj@@@Z>

externdef __imp_?FindCookieAndRemoveFromList@CDataCache@@QEAAH_JPEAV?$CList@PEAVCDMNodeObj@@PEAV1@@@@Z:PPROC
?FindCookieAndRemoveFromList@CDataCache@@QEAAH_JPEAV?$CList@PEAVCDMNodeObj@@PEAV1@@@@Z equ <__imp_?FindCookieAndRemoveFromList@CDataCache@@QEAAH_JPEAV?$CList@PEAVCDMNodeObj@@PEAV1@@@@Z>

externdef __imp_?FindDeviceInstanceId@CDataCache@@QEAAPEAG_J@Z:PPROC
?FindDeviceInstanceId@CDataCache@@QEAAPEAG_J@Z equ <__imp_?FindDeviceInstanceId@CDataCache@@QEAAPEAG_J@Z>

externdef __imp_?FindDiskPtrFromDiskId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z:PPROC
?FindDiskPtrFromDiskId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z equ <__imp_?FindDiskPtrFromDiskId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z>

externdef __imp_?FindDriveLetter@CDataCache@@QEAAH_JAEAG@Z:PPROC
?FindDriveLetter@CDataCache@@QEAAH_JAEAG@Z equ <__imp_?FindDriveLetter@CDataCache@@QEAAH_JAEAG@Z>

externdef __imp_?FindDriveLetter@CTaskData@@QEAAX_JAEAG@Z:PPROC
?FindDriveLetter@CTaskData@@QEAAX_JAEAG@Z equ <__imp_?FindDriveLetter@CTaskData@@QEAAX_JAEAG@Z>

externdef __imp_?FindDriveLetterHelper@@YAHPEAUdriveletterinfo@@H_JAEAG@Z:PPROC
?FindDriveLetterHelper@@YAHPEAUdriveletterinfo@@H_JAEAG@Z equ <__imp_?FindDriveLetterHelper@@YAHPEAUdriveletterinfo@@H_JAEAG@Z>

externdef __imp_?FindFileSystem@CDataCache@@QEAAH_JAEAUfilesysteminfo@@@Z:PPROC
?FindFileSystem@CDataCache@@QEAAH_JAEAUfilesysteminfo@@@Z equ <__imp_?FindFileSystem@CDataCache@@QEAAH_JAEAUfilesysteminfo@@@Z>

externdef __imp_?FindFileSystem@CTaskData@@QEAAH_JAEAUfilesysteminfo@@@Z:PPROC
?FindFileSystem@CTaskData@@QEAAH_JAEAUfilesysteminfo@@@Z equ <__imp_?FindFileSystem@CTaskData@@QEAAH_JAEAUfilesysteminfo@@@Z>

externdef __imp_?FindRegionPtrFromRegionId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z:PPROC
?FindRegionPtrFromRegionId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z equ <__imp_?FindRegionPtrFromRegionId@CDataCache@@QEAAH_JPEAPEAVCDMNodeObj@@@Z>

externdef __imp_?FindRegionPtrFromRegionId@CTaskData@@QEAAH_JPEAPEAVCDMNodeObj@@@Z:PPROC
?FindRegionPtrFromRegionId@CTaskData@@QEAAH_JPEAPEAVCDMNodeObj@@@Z equ <__imp_?FindRegionPtrFromRegionId@CTaskData@@QEAAH_JPEAPEAVCDMNodeObj@@@Z>

externdef __imp_?FindRegionPtrOnDiskFromRegionId@CDataCache@@QEAAHPEAVCDMNodeObj@@_JPEAPEAV2@AEAPEAU__POSITION@@@Z:PPROC
?FindRegionPtrOnDiskFromRegionId@CDataCache@@QEAAHPEAVCDMNodeObj@@_JPEAPEAV2@AEAPEAU__POSITION@@@Z equ <__imp_?FindRegionPtrOnDiskFromRegionId@CDataCache@@QEAAHPEAVCDMNodeObj@@_JPEAPEAV2@AEAPEAU__POSITION@@@Z>

externdef __imp_?GetAssignedDriveLetter@CTaskData@@QEAAH_JAEAG@Z:PPROC
?GetAssignedDriveLetter@CTaskData@@QEAAH_JAEAG@Z equ <__imp_?GetAssignedDriveLetter@CTaskData@@QEAAH_JAEAG@Z>

externdef __imp_?GetBootPort@CTaskData@@QEAAHXZ:PPROC
?GetBootPort@CTaskData@@QEAAHXZ equ <__imp_?GetBootPort@CTaskData@@QEAAHXZ>

externdef __imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ:PPROC
?GetBottomViewStyle@CDMSnapin@@QEAAHXZ equ <__imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetColorRef@CDMNodeObj@@QEAAKXZ:PPROC
?GetColorRef@CDMNodeObj@@QEAAKXZ equ <__imp_?GetColorRef@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetDMDataObjPtrFromId@CTaskData@@QEAAPEAVCDMNodeObj@@_J@Z:PPROC
?GetDMDataObjPtrFromId@CTaskData@@QEAAPEAVCDMNodeObj@@_J@Z equ <__imp_?GetDMDataObjPtrFromId@CTaskData@@QEAAPEAVCDMNodeObj@@_J@Z>

externdef __imp_?GetDeviceState@CDMNodeObj@@QEAAKXZ:PPROC
?GetDeviceState@CDMNodeObj@@QEAAKXZ equ <__imp_?GetDeviceState@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetDeviceType@CDMNodeObj@@QEAAKXZ:PPROC
?GetDeviceType@CDMNodeObj@@QEAAKXZ equ <__imp_?GetDeviceType@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetDiskCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z:PPROC
?GetDiskCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z equ <__imp_?GetDiskCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z>

externdef __imp_?GetDiskCookies@CTaskData@@QEAAXAEAKPEAPEA_JHKH@Z:PPROC
?GetDiskCookies@CTaskData@@QEAAXAEAKPEAPEA_JHKH@Z equ <__imp_?GetDiskCookies@CTaskData@@QEAAXAEAKPEAPEA_JHKH@Z>

externdef __imp_?GetDiskCookiesForSig@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PPROC
?GetDiskCookiesForSig@CTaskData@@QEAAXAEAKPEAPEA_J@Z equ <__imp_?GetDiskCookiesForSig@CTaskData@@QEAAXAEAKPEAPEA_J@Z>

externdef __imp_?GetDiskCookiesForUpgrade@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PPROC
?GetDiskCookiesForUpgrade@CTaskData@@QEAAXAEAKPEAPEA_J@Z equ <__imp_?GetDiskCookiesForUpgrade@CTaskData@@QEAAXAEAKPEAPEA_J@Z>

externdef __imp_?GetDiskCookiesToEncap@CTaskData@@QEAAXAEAKPEAPEA_J@Z:PPROC
?GetDiskCookiesToEncap@CTaskData@@QEAAXAEAKPEAPEA_J@Z equ <__imp_?GetDiskCookiesToEncap@CTaskData@@QEAAXAEAKPEAPEA_J@Z>

externdef __imp_?GetDiskCount@CDataCache@@QEAAKXZ:PPROC
?GetDiskCount@CDataCache@@QEAAKXZ equ <__imp_?GetDiskCount@CDataCache@@QEAAKXZ>

externdef __imp_?GetDiskInfo@CDMNodeObj@@QEAAHAEAUdiskinfoex@@@Z:PPROC
?GetDiskInfo@CDMNodeObj@@QEAAHAEAUdiskinfoex@@@Z equ <__imp_?GetDiskInfo@CDMNodeObj@@QEAAHAEAUdiskinfoex@@@Z>

externdef __imp_?GetDiskInfoFromVolCookie@CTaskData@@QEAAX_JAEAHAEAKPEAPEA_JKH@Z:PPROC
?GetDiskInfoFromVolCookie@CTaskData@@QEAAX_JAEAHAEAKPEAPEA_JKH@Z equ <__imp_?GetDiskInfoFromVolCookie@CTaskData@@QEAAX_JAEAHAEAKPEAPEA_JKH@Z>

externdef __imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ:PPROC
?GetDiskScaling@CDMSnapin@@QEAAHXZ equ <__imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetDiskSpec@CDMNodeObj@@QEAAHAEAUdiskspec@@@Z:PPROC
?GetDiskSpec@CDMNodeObj@@QEAAHAEAUdiskspec@@@Z equ <__imp_?GetDiskSpec@CDMNodeObj@@QEAAHAEAUdiskspec@@@Z>

externdef __imp_?GetDiskStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z:PPROC
?GetDiskStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z equ <__imp_?GetDiskStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z>

externdef __imp_?GetDiskStatusHelper@@YAHPEAUdiskinfoex@@AEAVCString@@H@Z:PPROC
?GetDiskStatusHelper@@YAHPEAUdiskinfoex@@AEAVCString@@H@Z equ <__imp_?GetDiskStatusHelper@@YAHPEAUdiskinfoex@@AEAVCString@@H@Z>

externdef __imp_?GetDiskTypeName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PPROC
?GetDiskTypeName@CDMNodeObj@@QEAAXAEAVCString@@@Z equ <__imp_?GetDiskTypeName@CDMNodeObj@@QEAAXAEAVCString@@@Z>

externdef __imp_?GetDiskTypeNameHelper@@YAXPEAUdiskinfoex@@AEAVCString@@G@Z:PPROC
?GetDiskTypeNameHelper@@YAXPEAUdiskinfoex@@AEAVCString@@G@Z equ <__imp_?GetDiskTypeNameHelper@@YAXPEAUdiskinfoex@@AEAVCString@@G@Z>

externdef __imp_?GetDriveLetter@CDMNodeObj@@QEAAXAEAG@Z:PPROC
?GetDriveLetter@CDMNodeObj@@QEAAXAEAG@Z equ <__imp_?GetDriveLetter@CDMNodeObj@@QEAAXAEAG@Z>

externdef __imp_?GetDriveLetters@CDataCache@@IEAAXAEAFPEAPEAGG@Z:PPROC
?GetDriveLetters@CDataCache@@IEAAXAEAFPEAPEAGG@Z equ <__imp_?GetDriveLetters@CDataCache@@IEAAXAEAFPEAPEAGG@Z>

externdef __imp_?GetDriveLetters@CTaskData@@QEAAXAEAFPEAPEAGG@Z:PPROC
?GetDriveLetters@CTaskData@@QEAAXAEAFPEAPEAGG@Z equ <__imp_?GetDriveLetters@CTaskData@@QEAAXAEAFPEAPEAGG@Z>

externdef __imp_?GetExtendedRegionColor@CDMNodeObj@@QEAAKXZ:PPROC
?GetExtendedRegionColor@CDMNodeObj@@QEAAKXZ equ <__imp_?GetExtendedRegionColor@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetExtraRegionStatus@CDMNodeObj@@QEAAHAEAVCString@@H@Z:PPROC
?GetExtraRegionStatus@CDMNodeObj@@QEAAHAEAVCString@@H@Z equ <__imp_?GetExtraRegionStatus@CDMNodeObj@@QEAAHAEAVCString@@H@Z>

externdef __imp_?GetFileSystemLabel@CDMNodeObj@@QEAAXAEAVCString@@@Z:PPROC
?GetFileSystemLabel@CDMNodeObj@@QEAAXAEAVCString@@@Z equ <__imp_?GetFileSystemLabel@CDMNodeObj@@QEAAXAEAVCString@@@Z>

externdef __imp_?GetFileSystemName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PPROC
?GetFileSystemName@CDMNodeObj@@QEAAXAEAVCString@@@Z equ <__imp_?GetFileSystemName@CDMNodeObj@@QEAAXAEAVCString@@@Z>

externdef __imp_?GetFileSystemSize@CDMNodeObj@@QEAAXAEAJ@Z:PPROC
?GetFileSystemSize@CDMNodeObj@@QEAAXAEAJ@Z equ <__imp_?GetFileSystemSize@CDMNodeObj@@QEAAXAEAJ@Z>

externdef __imp_?GetFileSystemType@CDMNodeObj@@QEAAHXZ:PPROC
?GetFileSystemType@CDMNodeObj@@QEAAHXZ equ <__imp_?GetFileSystemType@CDMNodeObj@@QEAAHXZ>

externdef __imp_?GetFileSystemTypes@CDataCache@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z:PPROC
?GetFileSystemTypes@CDataCache@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z equ <__imp_?GetFileSystemTypes@CDataCache@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z>

externdef __imp_?GetFileSystemTypes@CTaskData@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z:PPROC
?GetFileSystemTypes@CTaskData@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z equ <__imp_?GetFileSystemTypes@CTaskData@@QEAAXAEAKPEAPEAUifilesysteminfo@@@Z>

externdef __imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ:PPROC
?GetFilterToggle@CDMSnapin@@QEAAHXZ equ <__imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetFlags@CDMNodeObj@@QEAAJXZ:PPROC
?GetFlags@CDMNodeObj@@QEAAJXZ equ <__imp_?GetFlags@CDMNodeObj@@QEAAJXZ>

externdef __imp_?GetIVolumeClientVersion@CDMNodeObj@@QEAAFXZ:PPROC
?GetIVolumeClientVersion@CDMNodeObj@@QEAAFXZ equ <__imp_?GetIVolumeClientVersion@CDMNodeObj@@QEAAFXZ>

externdef __imp_?GetIVolumeClientVersion@CTaskData@@QEAAFXZ:PPROC
?GetIVolumeClientVersion@CTaskData@@QEAAFXZ equ <__imp_?GetIVolumeClientVersion@CTaskData@@QEAAFXZ>

externdef __imp_?GetIconId@CDMNodeObj@@QEAAIH@Z:PPROC
?GetIconId@CDMNodeObj@@QEAAIH@Z equ <__imp_?GetIconId@CDMNodeObj@@QEAAIH@Z>

externdef __imp_?GetImageNum@CDMNodeObj@@QEAAHXZ:PPROC
?GetImageNum@CDMNodeObj@@QEAAHXZ equ <__imp_?GetImageNum@CDMNodeObj@@QEAAHXZ>

externdef __imp_?GetLastKnownState@CDataCache@@QEAA_J_J@Z:PPROC
?GetLastKnownState@CDataCache@@QEAA_J_J@Z equ <__imp_?GetLastKnownState@CDataCache@@QEAA_J_J@Z>

externdef __imp_?GetLayoutType@CDMNodeObj@@QEAA?AW4_LAYOUT_TYPES@@XZ:PPROC
?GetLayoutType@CDMNodeObj@@QEAA?AW4_LAYOUT_TYPES@@XZ equ <__imp_?GetLayoutType@CDMNodeObj@@QEAA?AW4_LAYOUT_TYPES@@XZ>

externdef __imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ:PPROC
?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ equ <__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ>

externdef __imp_?GetListBehavior@CDMSnapin@@QEAAHXZ:PPROC
?GetListBehavior@CDMSnapin@@QEAAHXZ equ <__imp_?GetListBehavior@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetLogicalDriveCount@CDMNodeObj@@QEAAKXZ:PPROC
?GetLogicalDriveCount@CDMNodeObj@@QEAAKXZ equ <__imp_?GetLogicalDriveCount@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetLongName@CDMNodeObj@@QEAAXAEAVCString@@H@Z:PPROC
?GetLongName@CDMNodeObj@@QEAAXAEAVCString@@H@Z equ <__imp_?GetLongName@CDMNodeObj@@QEAAXAEAVCString@@H@Z>

externdef __imp_?GetMMCWindow@CDMComponentData@@QEAAPEAUHWND__@@XZ:PPROC
?GetMMCWindow@CDMComponentData@@QEAAPEAUHWND__@@XZ equ <__imp_?GetMMCWindow@CDMComponentData@@QEAAPEAUHWND__@@XZ>

externdef __imp_?GetMaxAdjustedFreeSize@CDMNodeObj@@QEAAXAEA_J@Z:PPROC
?GetMaxAdjustedFreeSize@CDMNodeObj@@QEAAXAEA_J@Z equ <__imp_?GetMaxAdjustedFreeSize@CDMNodeObj@@QEAAXAEA_J@Z>

externdef __imp_?GetMaxPartitionCount@CDMNodeObj@@QEAAKXZ:PPROC
?GetMaxPartitionCount@CDMNodeObj@@QEAAKXZ equ <__imp_?GetMaxPartitionCount@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetMinMaxPartitionSizes@CDataCache@@IEAAX_JAEAK1@Z:PPROC
?GetMinMaxPartitionSizes@CDataCache@@IEAAX_JAEAK1@Z equ <__imp_?GetMinMaxPartitionSizes@CDataCache@@IEAAX_JAEAK1@Z>

externdef __imp_?GetMinMaxPartitionSizes@CTaskData@@QEAAX_JAEAK1@Z:PPROC
?GetMinMaxPartitionSizes@CTaskData@@QEAAX_JAEAK1@Z equ <__imp_?GetMinMaxPartitionSizes@CTaskData@@QEAAX_JAEAK1@Z>

externdef __imp_?GetName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PPROC
?GetName@CDMNodeObj@@QEAAXAEAVCString@@@Z equ <__imp_?GetName@CDMNodeObj@@QEAAXAEAVCString@@@Z>

externdef __imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ:PPROC
?GetNumMembers@CDMNodeObj@@QEAAKXZ equ <__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetNumRegions@CDMNodeObj@@QEAAKXZ:PPROC
?GetNumRegions@CDMNodeObj@@QEAAKXZ equ <__imp_?GetNumRegions@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetObjectId@CDMNodeObj@@QEAAXAEA_J@Z:PPROC
?GetObjectId@CDMNodeObj@@QEAAXAEA_J@Z equ <__imp_?GetObjectId@CDMNodeObj@@QEAAXAEA_J@Z>

externdef __imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ:PPROC
?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ equ <__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ>

externdef __imp_?GetParentDiskPtr@CDMNodeObj@@QEAAPEAV1@XZ:PPROC
?GetParentDiskPtr@CDMNodeObj@@QEAAPEAV1@XZ equ <__imp_?GetParentDiskPtr@CDMNodeObj@@QEAAPEAV1@XZ>

externdef __imp_?GetParentVolumePtr@CDMNodeObj@@QEAAPEAV1@XZ:PPROC
?GetParentVolumePtr@CDMNodeObj@@QEAAPEAV1@XZ equ <__imp_?GetParentVolumePtr@CDMNodeObj@@QEAAPEAV1@XZ>

externdef __imp_?GetPartitionStyle@CDMNodeObj@@QEAA?AW4_PARTITIONSTYLE@@XZ:PPROC
?GetPartitionStyle@CDMNodeObj@@QEAA?AW4_PARTITIONSTYLE@@XZ equ <__imp_?GetPartitionStyle@CDMNodeObj@@QEAA?AW4_PARTITIONSTYLE@@XZ>

externdef __imp_?GetPartitionStyleString@CDMNodeObj@@QEAAXAEAVCString@@H@Z:PPROC
?GetPartitionStyleString@CDMNodeObj@@QEAAXAEAVCString@@H@Z equ <__imp_?GetPartitionStyleString@CDMNodeObj@@QEAAXAEAVCString@@H@Z>

externdef __imp_?GetPartitionStyleStringHelper@@YAXW4_PARTITIONSTYLE@@AEAVCString@@HKKH@Z:PPROC
?GetPartitionStyleStringHelper@@YAXW4_PARTITIONSTYLE@@AEAVCString@@HKKH@Z equ <__imp_?GetPartitionStyleStringHelper@@YAXW4_PARTITIONSTYLE@@AEAVCString@@HKKH@Z>

externdef __imp_?GetPatternRef@CDMNodeObj@@QEAAHXZ:PPROC
?GetPatternRef@CDMNodeObj@@QEAAHXZ equ <__imp_?GetPatternRef@CDMNodeObj@@QEAAHXZ>

externdef __imp_?GetPort@CDMNodeObj@@QEAAHXZ:PPROC
?GetPort@CDMNodeObj@@QEAAHXZ equ <__imp_?GetPort@CDMNodeObj@@QEAAHXZ>

externdef __imp_?GetPrimaryPartitionCount@CDMNodeObj@@QEAAKXZ:PPROC
?GetPrimaryPartitionCount@CDMNodeObj@@QEAAKXZ equ <__imp_?GetPrimaryPartitionCount@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z:PPROC
?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z equ <__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z>

externdef __imp_?GetRegionInfo@CDMNodeObj@@QEAAHAEAUregioninfoex@@@Z:PPROC
?GetRegionInfo@CDMNodeObj@@QEAAHAEAUregioninfoex@@@Z equ <__imp_?GetRegionInfo@CDMNodeObj@@QEAAHAEAUregioninfoex@@@Z>

externdef __imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ:PPROC
?GetRegionScaling@CDMSnapin@@QEAAHXZ equ <__imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetResultStringArray@CDMNodeObj@@QEAAHAEAVCStringArray@@@Z:PPROC
?GetResultStringArray@CDMNodeObj@@QEAAHAEAVCStringArray@@@Z equ <__imp_?GetResultStringArray@CDMNodeObj@@QEAAHAEAVCStringArray@@@Z>

externdef __imp_?GetRevertDiskName@CServerRequests@@QEAAAEAVCString@@XZ:PPROC
?GetRevertDiskName@CServerRequests@@QEAAAEAVCString@@XZ equ <__imp_?GetRevertDiskName@CServerRequests@@QEAAAEAVCString@@XZ>

externdef __imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ:PPROC
?GetServerName@CDataCache@@QEAA?AVCString@@XZ equ <__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ>

externdef __imp_?GetServerName@CTaskData@@QEAA?AVCString@@XZ:PPROC
?GetServerName@CTaskData@@QEAA?AVCString@@XZ equ <__imp_?GetServerName@CTaskData@@QEAA?AVCString@@XZ>

externdef __imp_?GetShortName@CDMNodeObj@@QEAAXAEAVCString@@@Z:PPROC
?GetShortName@CDMNodeObj@@QEAAXAEAVCString@@@Z equ <__imp_?GetShortName@CDMNodeObj@@QEAAXAEAVCString@@@Z>

externdef __imp_?GetSize@CDMNodeObj@@QEAAXAEAJ@Z:PPROC
?GetSize@CDMNodeObj@@QEAAXAEAJ@Z equ <__imp_?GetSize@CDMNodeObj@@QEAAXAEAJ@Z>

externdef __imp_?GetSize@CDMNodeObj@@QEAAXAEA_JH@Z:PPROC
?GetSize@CDMNodeObj@@QEAAXAEA_JH@Z equ <__imp_?GetSize@CDMNodeObj@@QEAAXAEA_JH@Z>

externdef __imp_?GetSizeString@CDMNodeObj@@QEAAXAEAVCString@@@Z:PPROC
?GetSizeString@CDMNodeObj@@QEAAXAEAVCString@@@Z equ <__imp_?GetSizeString@CDMNodeObj@@QEAAXAEAVCString@@@Z>

externdef __imp_?GetStartOffset@CDMNodeObj@@QEAA_JXZ:PPROC
?GetStartOffset@CDMNodeObj@@QEAA_JXZ equ <__imp_?GetStartOffset@CDMNodeObj@@QEAA_JXZ>

externdef __imp_?GetStatus@CDMNodeObj@@QEAAHXZ:PPROC
?GetStatus@CDMNodeObj@@QEAAHXZ equ <__imp_?GetStatus@CDMNodeObj@@QEAAHXZ>

externdef __imp_?GetStorageType@CDMNodeObj@@QEAA?AW4_STORAGE_TYPES@@XZ:PPROC
?GetStorageType@CDMNodeObj@@QEAA?AW4_STORAGE_TYPES@@XZ equ <__imp_?GetStorageType@CDMNodeObj@@QEAA?AW4_STORAGE_TYPES@@XZ>

externdef __imp_?GetStorageType@CDMNodeObj@@QEAAXAEAVCString@@H@Z:PPROC
?GetStorageType@CDMNodeObj@@QEAAXAEAVCString@@H@Z equ <__imp_?GetStorageType@CDMNodeObj@@QEAAXAEAVCString@@H@Z>

externdef __imp_?GetStringFromRc@@YA?AVCString@@K@Z:PPROC
?GetStringFromRc@@YA?AVCString@@K@Z equ <__imp_?GetStringFromRc@@YA?AVCString@@K@Z>

externdef __imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ:PPROC
?GetTopViewStyle@CDMSnapin@@QEAAHXZ equ <__imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetUIState@CTaskData@@QEAAKXZ:PPROC
?GetUIState@CTaskData@@QEAAKXZ equ <__imp_?GetUIState@CTaskData@@QEAAKXZ>

externdef __imp_?GetUnallocSpace@CDMNodeObj@@QEAA_JH@Z:PPROC
?GetUnallocSpace@CDMNodeObj@@QEAA_JH@Z equ <__imp_?GetUnallocSpace@CDMNodeObj@@QEAA_JH@Z>

externdef __imp_?GetVolumeCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z:PPROC
?GetVolumeCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z equ <__imp_?GetVolumeCookies@CDataCache@@IEAAXAEAKPEAPEA_J@Z>

externdef __imp_?GetVolumeCount@CDataCache@@QEAAKXZ:PPROC
?GetVolumeCount@CDataCache@@QEAAKXZ equ <__imp_?GetVolumeCount@CDataCache@@QEAAKXZ>

externdef __imp_?GetVolumeInfo@CDMNodeObj@@QEAAHAEAUvolumeinfo@@@Z:PPROC
?GetVolumeInfo@CDMNodeObj@@QEAAHAEAUvolumeinfo@@@Z equ <__imp_?GetVolumeInfo@CDMNodeObj@@QEAAHAEAUvolumeinfo@@@Z>

externdef __imp_?GetVolumeStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z:PPROC
?GetVolumeStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z equ <__imp_?GetVolumeStatus@CDMNodeObj@@QEAAHAEAVCString@@@Z>

externdef __imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ:PPROC
?GetWaitCursor@CDMSnapin@@QEAAHXZ equ <__imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ>

externdef __imp_?HasExtendedPartition@CDMNodeObj@@QEAAHXZ:PPROC
?HasExtendedPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?HasExtendedPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?HasNTFSwithDriveLetter@CDataCache@@QEAAHXZ:PPROC
?HasNTFSwithDriveLetter@CDataCache@@QEAAHXZ equ <__imp_?HasNTFSwithDriveLetter@CDataCache@@QEAAHXZ>

externdef __imp_?HasNTFSwithDriveLetter@CTaskData@@QEAAHXZ:PPROC
?HasNTFSwithDriveLetter@CTaskData@@QEAAHXZ equ <__imp_?HasNTFSwithDriveLetter@CTaskData@@QEAAHXZ>

externdef __imp_?HasVMDisk@CDataCache@@QEAAHXZ:PPROC
?HasVMDisk@CDataCache@@QEAAHXZ equ <__imp_?HasVMDisk@CDataCache@@QEAAHXZ>

externdef __imp_?IsActive@CDMNodeObj@@QEAAHXZ:PPROC
?IsActive@CDMNodeObj@@QEAAHXZ equ <__imp_?IsActive@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsAlpha@CDataCache@@QEAAHXZ:PPROC
?IsAlpha@CDataCache@@QEAAHXZ equ <__imp_?IsAlpha@CDataCache@@QEAAHXZ>

externdef __imp_?IsAlpha@CTaskData@@QEAAHXZ:PPROC
?IsAlpha@CTaskData@@QEAAHXZ equ <__imp_?IsAlpha@CTaskData@@QEAAHXZ>

externdef __imp_?IsCurrBootVolume@CDMNodeObj@@QEAAHXZ:PPROC
?IsCurrBootVolume@CDMNodeObj@@QEAAHXZ equ <__imp_?IsCurrBootVolume@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsCurrSystemVolume@CDMNodeObj@@QEAAHXZ:PPROC
?IsCurrSystemVolume@CDMNodeObj@@QEAAHXZ equ <__imp_?IsCurrSystemVolume@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsDiskEmpty@CDMNodeObj@@QEAAHXZ:PPROC
?IsDiskEmpty@CDMNodeObj@@QEAAHXZ equ <__imp_?IsDiskEmpty@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsDynamic1394@CDataCache@@QEAAHXZ:PPROC
?IsDynamic1394@CDataCache@@QEAAHXZ equ <__imp_?IsDynamic1394@CDataCache@@QEAAHXZ>

externdef __imp_?IsEECoveredGPTDisk@CDMNodeObj@@QEAAHXZ:PPROC
?IsEECoveredGPTDisk@CDMNodeObj@@QEAAHXZ equ <__imp_?IsEECoveredGPTDisk@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsESPPartition@CDMNodeObj@@QEAAHXZ:PPROC
?IsESPPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?IsESPPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsEfi@CDataCache@@QEAAHXZ:PPROC
?IsEfi@CDataCache@@QEAAHXZ equ <__imp_?IsEfi@CDataCache@@QEAAHXZ>

externdef __imp_?IsEfi@CTaskData@@QEAAHXZ:PPROC
?IsEfi@CTaskData@@QEAAHXZ equ <__imp_?IsEfi@CTaskData@@QEAAHXZ>

externdef __imp_?IsFTVolume@CDMNodeObj@@QEAAHXZ:PPROC
?IsFTVolume@CDMNodeObj@@QEAAHXZ equ <__imp_?IsFTVolume@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsFakeVolume@CDMNodeObj@@QEAAHXZ:PPROC
?IsFakeVolume@CDMNodeObj@@QEAAHXZ equ <__imp_?IsFakeVolume@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsFirstFreeRegion@CDMNodeObj@@QEAAHXZ:PPROC
?IsFirstFreeRegion@CDMNodeObj@@QEAAHXZ equ <__imp_?IsFirstFreeRegion@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsHiddenRegion@@YAHAEAUregioninfoex@@@Z:PPROC
?IsHiddenRegion@@YAHAEAUregioninfoex@@@Z equ <__imp_?IsHiddenRegion@@YAHAEAUregioninfoex@@@Z>

externdef __imp_?IsHiddenRegion@CDMNodeObj@@QEAAHXZ:PPROC
?IsHiddenRegion@CDMNodeObj@@QEAAHXZ equ <__imp_?IsHiddenRegion@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsInFlux@CDMNodeObj@@QEAAHXZ:PPROC
?IsInFlux@CDMNodeObj@@QEAAHXZ equ <__imp_?IsInFlux@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsLocalMachine@CTaskData@@QEAAHXZ:PPROC
?IsLocalMachine@CTaskData@@QEAAHXZ equ <__imp_?IsLocalMachine@CTaskData@@QEAAHXZ>

externdef __imp_?IsMbrEEPartition@@YAHAEAUregioninfoex@@@Z:PPROC
?IsMbrEEPartition@@YAHAEAUregioninfoex@@@Z equ <__imp_?IsMbrEEPartition@@YAHAEAUregioninfoex@@@Z>

externdef __imp_?IsMbrEEPartition@CDMNodeObj@@QEAAHXZ:PPROC
?IsMbrEEPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?IsMbrEEPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsMember@CDMNodeObj@@QEAAHPEAV1@@Z:PPROC
?IsMember@CDMNodeObj@@QEAAHPEAV1@@Z equ <__imp_?IsMember@CDMNodeObj@@QEAAHPEAV1@@Z>

externdef __imp_?IsNEC_98Disk@CDMNodeObj@@QEAAHXZ:PPROC
?IsNEC_98Disk@CDMNodeObj@@QEAAHXZ equ <__imp_?IsNEC_98Disk@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsNEC_98Server@CDataCache@@QEAAHXZ:PPROC
?IsNEC_98Server@CDataCache@@QEAAHXZ equ <__imp_?IsNEC_98Server@CDataCache@@QEAAHXZ>

externdef __imp_?IsNEC_98Server@CTaskData@@QEAAHXZ:PPROC
?IsNEC_98Server@CTaskData@@QEAAHXZ equ <__imp_?IsNEC_98Server@CTaskData@@QEAAHXZ>

externdef __imp_?IsNTServer@CTaskData@@QEAAHXZ:PPROC
?IsNTServer@CTaskData@@QEAAHXZ equ <__imp_?IsNTServer@CTaskData@@QEAAHXZ>

externdef __imp_?IsOemPartition@CDMNodeObj@@QEAAHXZ:PPROC
?IsOemPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?IsOemPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsPersonalOrLapTopServer@CDataCache@@QEAAHXZ:PPROC
?IsPersonalOrLapTopServer@CDataCache@@QEAAHXZ equ <__imp_?IsPersonalOrLapTopServer@CDataCache@@QEAAHXZ>

externdef __imp_?IsRevertable@CDMNodeObj@@QEAAHXZ:PPROC
?IsRevertable@CDMNodeObj@@QEAAHXZ equ <__imp_?IsRevertable@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsSecureSystemPartition@CTaskData@@QEAAHXZ:PPROC
?IsSecureSystemPartition@CTaskData@@QEAAHXZ equ <__imp_?IsSecureSystemPartition@CTaskData@@QEAAHXZ>

externdef __imp_?IsUnknownPartition@CDMNodeObj@@QEAAHXZ:PPROC
?IsUnknownPartition@CDMNodeObj@@QEAAHXZ equ <__imp_?IsUnknownPartition@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsUpgradeable@CDMNodeObj@@QEAAHXZ:PPROC
?IsUpgradeable@CDMNodeObj@@QEAAHXZ equ <__imp_?IsUpgradeable@CDMNodeObj@@QEAAHXZ>

externdef __imp_?IsWolfpack@CTaskData@@QEAAHXZ:PPROC
?IsWolfpack@CTaskData@@QEAAHXZ equ <__imp_?IsWolfpack@CTaskData@@QEAAHXZ>

externdef __imp_?LoadData@CDMComponentData@@QEAAXJ@Z:PPROC
?LoadData@CDMComponentData@@QEAAXJ@Z equ <__imp_?LoadData@CDMComponentData@@QEAAXJ@Z>

externdef __imp_?ParseDeviceName@@YAXPEAH00PEAG@Z:PPROC
?ParseDeviceName@@YAXPEAH00PEAG@Z equ <__imp_?ParseDeviceName@@YAXPEAH00PEAG@Z>

externdef __imp_?PopUpInit@CContextMenu@@QEAAXPEAVCDMNodeObj@@AEAHH@Z:PPROC
?PopUpInit@CContextMenu@@QEAAXPEAVCDMNodeObj@@AEAHH@Z equ <__imp_?PopUpInit@CContextMenu@@QEAAXPEAVCDMNodeObj@@AEAHH@Z>

externdef __imp_?PopulateDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z:PPROC
?PopulateDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z equ <__imp_?PopulateDiskGroupData@CDataCache@@QEAAXPEAUDISK_GROUP_DATA@@@Z>

externdef __imp_?PopulateEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z:PPROC
?PopulateEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z equ <__imp_?PopulateEncapsulateData@CDataCache@@QEAAXPEAUENCAPSULATE_DATA@@@Z>

externdef __imp_?RecalculateSpace@CDMNodeObj@@QEAAXXZ:PPROC
?RecalculateSpace@CDMNodeObj@@QEAAXXZ equ <__imp_?RecalculateSpace@CDMNodeObj@@QEAAXXZ>

externdef __imp_?RefreshDiskView@CDMComponentData@@QEAAXXZ:PPROC
?RefreshDiskView@CDMComponentData@@QEAAXXZ equ <__imp_?RefreshDiskView@CDMComponentData@@QEAAXXZ>

externdef __imp_?RefreshFileSys@CContextMenu@@QEAAX_J@Z:PPROC
?RefreshFileSys@CContextMenu@@QEAAX_J@Z equ <__imp_?RefreshFileSys@CContextMenu@@QEAAX_J@Z>

externdef __imp_?ReloadData@CDMComponentData@@QEAAXXZ:PPROC
?ReloadData@CDMComponentData@@QEAAXXZ equ <__imp_?ReloadData@CDMComponentData@@QEAAXXZ>

externdef __imp_?RoundUpToMB@@YA_J_J@Z:PPROC
?RoundUpToMB@@YA_J_J@Z equ <__imp_?RoundUpToMB@@YA_J_J@Z>

externdef __imp_?SetDescriptionBarText@CDMSnapin@@QEAAXXZ:PPROC
?SetDescriptionBarText@CDMSnapin@@QEAAXXZ equ <__imp_?SetDescriptionBarText@CDMSnapin@@QEAAXXZ>

externdef __imp_?SetDiskList@CDataCache@@QEAAXPEAUdiskinfoex@@K@Z:PPROC
?SetDiskList@CDataCache@@QEAAXPEAUdiskinfoex@@K@Z equ <__imp_?SetDiskList@CDataCache@@QEAAXPEAUdiskinfoex@@K@Z>

externdef __imp_?SetDriveLetterInUse@CDataCache@@QEAAXGH@Z:PPROC
?SetDriveLetterInUse@CDataCache@@QEAAXGH@Z equ <__imp_?SetDriveLetterInUse@CDataCache@@QEAAXGH@Z>

externdef __imp_?SetFSId@CDMNodeObj@@QEAAX_J@Z:PPROC
?SetFSId@CDMNodeObj@@QEAAX_J@Z equ <__imp_?SetFSId@CDMNodeObj@@QEAAX_J@Z>

externdef __imp_?SetOcxViewType@CDMComponentData@@QEAAXXZ:PPROC
?SetOcxViewType@CDMComponentData@@QEAAXXZ equ <__imp_?SetOcxViewType@CDMComponentData@@QEAAXXZ>

externdef __imp_?SetOcxViewTypeForce@CDMComponentData@@QEAAXXZ:PPROC
?SetOcxViewTypeForce@CDMComponentData@@QEAAXXZ equ <__imp_?SetOcxViewTypeForce@CDMComponentData@@QEAAXXZ>

externdef __imp_?SetUIState@CTaskData@@QEAAXK@Z:PPROC
?SetUIState@CTaskData@@QEAAXK@Z equ <__imp_?SetUIState@CTaskData@@QEAAXK@Z>

externdef __imp_?SetVolumeList@CDataCache@@QEAAXPEAUvolumeinfo@@K@Z:PPROC
?SetVolumeList@CDataCache@@QEAAXPEAUvolumeinfo@@K@Z equ <__imp_?SetVolumeList@CDataCache@@QEAAXPEAUvolumeinfo@@K@Z>

externdef __imp_?ShowContextMenu@CContextMenu@@QEAAJPEAVCWnd@@JJ_J@Z:PPROC
?ShowContextMenu@CContextMenu@@QEAAJPEAVCWnd@@JJ_J@Z equ <__imp_?ShowContextMenu@CContextMenu@@QEAAJPEAVCWnd@@JJ_J@Z>

externdef __imp_?SupportGpt@CDataCache@@QEAAHXZ:PPROC
?SupportGpt@CDataCache@@QEAAHXZ equ <__imp_?SupportGpt@CDataCache@@QEAAHXZ>

externdef __imp_?SupportGpt@CTaskData@@QEAAHXZ:PPROC
?SupportGpt@CTaskData@@QEAAHXZ equ <__imp_?SupportGpt@CTaskData@@QEAAHXZ>

externdef __imp_?UIStateChange@CDMComponentData@@QEAAXK@Z:PPROC
?UIStateChange@CDMComponentData@@QEAAXK@Z equ <__imp_?UIStateChange@CDMComponentData@@QEAAXK@Z>

externdef __imp_?UpDateConsoleView@CDMSnapin@@QEAAXXZ:PPROC
?UpDateConsoleView@CDMSnapin@@QEAAXXZ equ <__imp_?UpDateConsoleView@CDMSnapin@@QEAAXXZ>

externdef __imp_?VolumeContainsActiveRegion@CDMNodeObj@@QEAAHXZ:PPROC
?VolumeContainsActiveRegion@CDMNodeObj@@QEAAHXZ equ <__imp_?VolumeContainsActiveRegion@CDMNodeObj@@QEAAHXZ>

externdef __imp_?namecmp@@YAHPEBG0@Z:PPROC
?namecmp@@YAHPEBG0@Z equ <__imp_?namecmp@@YAHPEBG0@Z>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_GetPropertyPageData:PPROC
GetPropertyPageData equ <__imp_GetPropertyPageData>

externdef __imp_IsFailPopupMgmtSupported:PPROC
IsFailPopupMgmtSupported equ <__imp_IsFailPopupMgmtSupported>

externdef __imp_IsRequestPending:PPROC
IsRequestPending equ <__imp_IsRequestPending>

externdef __imp_LoadPropertyPageData:PPROC
LoadPropertyPageData equ <__imp_LoadPropertyPageData>
