externdef __imp_AddEntryBootFileGpt:PPROC
AddEntryBootFileGpt equ <__imp_AddEntryBootFileGpt>

externdef __imp_AddEntryBootFileMbr:PPROC
AddEntryBootFileMbr equ <__imp_AddEntryBootFileMbr>

externdef __imp_CoDisableDynamicVolumes:PPROC
CoDisableDynamicVolumes equ <__imp_CoDisableDynamicVolumes>

externdef __imp_DisplayError:PPROC
DisplayError equ <__imp_DisplayError>

externdef __imp_DisplayErrorRgszw:PPROC
DisplayErrorRgszw equ <__imp_DisplayErrorRgszw>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_DmCommonNtOpenFile:PPROC
DmCommonNtOpenFile equ <__imp_DmCommonNtOpenFile>

externdef __imp_DynamicSupport:PPROC
DynamicSupport equ <__imp_DynamicSupport>

externdef __imp_FTrace:PPROC
FTrace equ <__imp_FTrace>

externdef __imp_FTraceValist:PPROC
FTraceValist equ <__imp_FTraceValist>

externdef __imp_FreeRgszw:PPROC
FreeRgszw equ <__imp_FreeRgszw>

externdef __imp_GetErrorData:PPROC
GetErrorData equ <__imp_GetErrorData>

externdef __imp_GetInstallDirectoryPath:PPROC
GetInstallDirectoryPath equ <__imp_GetInstallDirectoryPath>

externdef __imp_GetSystemVolume:PPROC
GetSystemVolume equ <__imp_GetSystemVolume>

externdef __imp_IsPersonalSKU:PPROC
IsPersonalSKU equ <__imp_IsPersonalSKU>

externdef __imp_LowAcquirePrivilege:PPROC
LowAcquirePrivilege equ <__imp_LowAcquirePrivilege>

externdef __imp_LowGetPartitionInfo:PPROC
LowGetPartitionInfo equ <__imp_LowGetPartitionInfo>

externdef __imp_LowNtAddBootEntry:PPROC
LowNtAddBootEntry equ <__imp_LowNtAddBootEntry>

externdef __imp_LowNtReadFile:PPROC
LowNtReadFile equ <__imp_LowNtReadFile>

externdef __imp_LowNtReadOnlyAttributeOff:PPROC
LowNtReadOnlyAttributeOff equ <__imp_LowNtReadOnlyAttributeOff>

externdef __imp_LowNtWriteFile:PPROC
LowNtWriteFile equ <__imp_LowNtWriteFile>

externdef __imp_RgszwDupRgszw:PPROC
RgszwDupRgszw equ <__imp_RgszwDupRgszw>

externdef __imp_RgszwFromArgs:PPROC
RgszwFromArgs equ <__imp_RgszwFromArgs>

externdef __imp_RgszwFromValist:PPROC
RgszwFromValist equ <__imp_RgszwFromValist>

externdef __imp_ShowMessage:PPROC
ShowMessage equ <__imp_ShowMessage>

externdef __imp_ShowMessageValist:PPROC
ShowMessageValist equ <__imp_ShowMessageValist>

externdef __imp_SzwDupSzw:PPROC
SzwDupSzw equ <__imp_SzwDupSzw>

externdef __imp_SzwFromSza:PPROC
SzwFromSza equ <__imp_SzwFromSza>

externdef __imp_TranslateError:PPROC
TranslateError equ <__imp_TranslateError>
