externdef __imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z:PPROC
?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z equ <__imp_?AddLDMObjMapEntry@CDataCache@@QEAAXPEAU_LDM_OBJ_MAP_ENTRY@@@Z>

externdef __imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ:PPROC
?GetBottomViewStyle@CDMSnapin@@QEAAHXZ equ <__imp_?GetBottomViewStyle@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetDiskCount@CDataCache@@QEAAKXZ:PPROC
?GetDiskCount@CDataCache@@QEAAKXZ equ <__imp_?GetDiskCount@CDataCache@@QEAAKXZ>

externdef __imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ:PPROC
?GetDiskScaling@CDMSnapin@@QEAAHXZ equ <__imp_?GetDiskScaling@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ:PPROC
?GetFilterToggle@CDMSnapin@@QEAAHXZ equ <__imp_?GetFilterToggle@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ:PPROC
?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ equ <__imp_?GetLdmObjectId@CDMNodeObj@@QEAA_JXZ>

externdef __imp_?GetListBehavior@CDMSnapin@@QEAAHXZ:PPROC
?GetListBehavior@CDMSnapin@@QEAAHXZ equ <__imp_?GetListBehavior@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ:PPROC
?GetNumMembers@CDMNodeObj@@QEAAKXZ equ <__imp_?GetNumMembers@CDMNodeObj@@QEAAKXZ>

externdef __imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ:PPROC
?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ equ <__imp_?GetOcxFrameCWndPtr@CTaskData@@QEAAPEAVCWnd@@XZ>

externdef __imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z:PPROC
?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z equ <__imp_?GetRegionColorStructPtr@CTaskData@@QEAAXPEAPEAU_REGION_COLORS@@AEAH@Z>

externdef __imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ:PPROC
?GetRegionScaling@CDMSnapin@@QEAAHXZ equ <__imp_?GetRegionScaling@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ:PPROC
?GetServerName@CDataCache@@QEAA?AVCString@@XZ equ <__imp_?GetServerName@CDataCache@@QEAA?AVCString@@XZ>

externdef __imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ:PPROC
?GetTopViewStyle@CDMSnapin@@QEAAHXZ equ <__imp_?GetTopViewStyle@CDMSnapin@@QEAAHXZ>

externdef __imp_?GetVolumeCount@CDataCache@@QEAAKXZ:PPROC
?GetVolumeCount@CDataCache@@QEAAKXZ equ <__imp_?GetVolumeCount@CDataCache@@QEAAKXZ>

externdef __imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ:PPROC
?GetWaitCursor@CDMSnapin@@QEAAHXZ equ <__imp_?GetWaitCursor@CDMSnapin@@QEAAHXZ>

externdef __imp_CreateDataCacheZ:PPROC
CreateDataCacheZ equ <__imp_CreateDataCacheZ>

externdef __imp_CreateServerRequestsZ:PPROC
CreateServerRequestsZ equ <__imp_CreateServerRequestsZ>
