externdef __imp_NPAddConnection3:PPROC
NPAddConnection3 equ <__imp_NPAddConnection3>

externdef __imp_NPAddConnection:PPROC
NPAddConnection equ <__imp_NPAddConnection>

externdef __imp_NPCancelConnection:PPROC
NPCancelConnection equ <__imp_NPCancelConnection>

externdef __imp_NPCloseEnum:PPROC
NPCloseEnum equ <__imp_NPCloseEnum>

externdef __imp_NPEnumResource:PPROC
NPEnumResource equ <__imp_NPEnumResource>

externdef __imp_NPGetCaps:PPROC
NPGetCaps equ <__imp_NPGetCaps>

externdef __imp_NPGetConnection:PPROC
NPGetConnection equ <__imp_NPGetConnection>

externdef __imp_NPGetResourceInformation:PPROC
NPGetResourceInformation equ <__imp_NPGetResourceInformation>

externdef __imp_NPGetResourceParent:PPROC
NPGetResourceParent equ <__imp_NPGetResourceParent>

externdef __imp_NPGetUniversalName:PPROC
NPGetUniversalName equ <__imp_NPGetUniversalName>

externdef __imp_NPOpenEnum:PPROC
NPOpenEnum equ <__imp_NPOpenEnum>

externdef __imp_drprov_ordinal11:PPROC
drprov_ordinal11 equ <__imp_drprov_ordinal11>
