externdef __imp_AddDirectory:PPROC
AddDirectory equ <__imp_AddDirectory>

externdef __imp_AddFile:PPROC
AddFile equ <__imp_AddFile>

externdef __imp_AddRef:PPROC
AddRef equ <__imp_AddRef>

externdef __imp_AddString:PPROC
AddString equ <__imp_AddString>

externdef __imp_AddStringEx:PPROC
AddStringEx equ <__imp_AddStringEx>

externdef __imp_CloseDataBase:PPROC
CloseDataBase equ <__imp_CloseDataBase>

externdef __imp_CloseDataBaseEx:PPROC
CloseDataBaseEx equ <__imp_CloseDataBaseEx>

externdef __imp_CreateDataBase:PPROC
CreateDataBase equ <__imp_CreateDataBase>

externdef __imp_DecreaseDataBase:PPROC
DecreaseDataBase equ <__imp_DecreaseDataBase>

externdef __imp_DelDirectory:PPROC
DelDirectory equ <__imp_DelDirectory>

externdef __imp_DelFile:PPROC
DelFile equ <__imp_DelFile>

externdef __imp_DeleteRef:PPROC
DeleteRef equ <__imp_DeleteRef>

externdef __imp_DeleteString:PPROC
DeleteString equ <__imp_DeleteString>

externdef __imp_DeleteStringEx:PPROC
DeleteStringEx equ <__imp_DeleteStringEx>

externdef __imp_GetDirIndex:PPROC
GetDirIndex equ <__imp_GetDirIndex>

externdef __imp_GetDirIndexAndUp:PPROC
GetDirIndexAndUp equ <__imp_GetDirIndexAndUp>

externdef __imp_GetFileIndexByNameInd:PPROC
GetFileIndexByNameInd equ <__imp_GetFileIndexByNameInd>

externdef __imp_GetFilePtr:PPROC
GetFilePtr equ <__imp_GetFilePtr>

externdef __imp_GetIndexType:PPROC
GetIndexType equ <__imp_GetIndexType>

externdef __imp_GetIndexTypeEx:PPROC
GetIndexTypeEx equ <__imp_GetIndexTypeEx>

externdef __imp_GetOrder:PPROC
GetOrder equ <__imp_GetOrder>

externdef __imp_GetRefByOrder:PPROC
GetRefByOrder equ <__imp_GetRefByOrder>

externdef __imp_GetRefOrder:PPROC
GetRefOrder equ <__imp_GetRefOrder>

externdef __imp_GetString:PPROC
GetString equ <__imp_GetString>

externdef __imp_IncreaseBDirRes:PPROC
IncreaseBDirRes equ <__imp_IncreaseBDirRes>

externdef __imp_IncreaseDataBase:PPROC
IncreaseDataBase equ <__imp_IncreaseDataBase>

externdef __imp_IncreaseDirRes:PPROC
IncreaseDirRes equ <__imp_IncreaseDirRes>

externdef __imp_IncreaseErasedRes:PPROC
IncreaseErasedRes equ <__imp_IncreaseErasedRes>

externdef __imp_IncreaseFileRes:PPROC
IncreaseFileRes equ <__imp_IncreaseFileRes>

externdef __imp_IncreaseStrRes:PPROC
IncreaseStrRes equ <__imp_IncreaseStrRes>

externdef __imp_IndexToPath:PPROC
IndexToPath equ <__imp_IndexToPath>

externdef __imp_NewDirectory:PPROC
NewDirectory equ <__imp_NewDirectory>

externdef __imp_NewFile:PPROC
NewFile equ <__imp_NewFile>

externdef __imp_PathToIndex:PPROC
PathToIndex equ <__imp_PathToIndex>

externdef __imp_PathToIndexEx:PPROC
PathToIndexEx equ <__imp_PathToIndexEx>

externdef __imp_RenameObject:PPROC
RenameObject equ <__imp_RenameObject>

externdef __imp_SetObjectSize:PPROC
SetObjectSize equ <__imp_SetObjectSize>

externdef __imp_SetOrder:PPROC
SetOrder equ <__imp_SetOrder>

externdef __imp_SetRefOrder:PPROC
SetRefOrder equ <__imp_SetRefOrder>

externdef __imp_SetString:PPROC
SetString equ <__imp_SetString>

externdef __imp_SortStringIndices:PPROC
SortStringIndices equ <__imp_SortStringIndices>
