externdef __imp_AddEquation:PPROC
AddEquation equ <__imp_AddEquation>

externdef __imp_AddEquationEx:PPROC
AddEquationEx equ <__imp_AddEquationEx>

externdef __imp_AddNumbers:PPROC
AddNumbers equ <__imp_AddNumbers>

externdef __imp_AndNumbers:PPROC
AndNumbers equ <__imp_AndNumbers>

externdef __imp_Assemble:PPROC
Assemble equ <__imp_Assemble>

externdef __imp_AssembleEx:PPROC
AssembleEx equ <__imp_AssembleEx>

externdef __imp_AssignDataBase:PPROC
AssignDataBase equ <__imp_AssignDataBase>

externdef __imp_AssignDataBaseByHandle:PPROC
AssignDataBaseByHandle equ <__imp_AssignDataBaseByHandle>

externdef __imp_CmpNumbers:PPROC
CmpNumbers equ <__imp_CmpNumbers>

externdef __imp_DelEquation:PPROC
DelEquation equ <__imp_DelEquation>

externdef __imp_Disassemble:PPROC
Disassemble equ <__imp_Disassemble>

externdef __imp_DivNumbers:PPROC
DivNumbers equ <__imp_DivNumbers>

externdef __imp_DsmVersion:PPROC
DsmVersion equ <__imp_DsmVersion>

externdef __imp_EvalExpr128:PPROC
EvalExpr128 equ <__imp_EvalExpr128>

externdef __imp_EvalExpr256:PPROC
EvalExpr256 equ <__imp_EvalExpr256>

externdef __imp_FreeInstr:PPROC
FreeInstr equ <__imp_FreeInstr>

externdef __imp_GetControlFlags:PPROC
GetControlFlags equ <__imp_GetControlFlags>

externdef __imp_GetExceptTextNote:PPROC
GetExceptTextNote equ <__imp_GetExceptTextNote>

externdef __imp_GetExceptions:PPROC
GetExceptions equ <__imp_GetExceptions>

externdef __imp_GetInterruptProps:PPROC
GetInterruptProps equ <__imp_GetInterruptProps>

externdef __imp_GetLatency:PPROC
GetLatency equ <__imp_GetLatency>

externdef __imp_GetMediaExceptionProps:PPROC
GetMediaExceptionProps equ <__imp_GetMediaExceptionProps>

externdef __imp_GetPfxMeaning:PPROC
GetPfxMeaning equ <__imp_GetPfxMeaning>

externdef __imp_GetX87ExceptionProps:PPROC
GetX87ExceptionProps equ <__imp_GetX87ExceptionProps>

externdef __imp_InitInstr:PPROC
InitInstr equ <__imp_InitInstr>

externdef __imp_InitInstrEx:PPROC
InitInstrEx equ <__imp_InitInstrEx>

externdef __imp_InitMainDat:PPROC
InitMainDat equ <__imp_InitMainDat>

externdef __imp_InstrDasm:PPROC
InstrDasm equ <__imp_InstrDasm>

externdef __imp_InstrEF:PPROC
InstrEF equ <__imp_InstrEF>

externdef __imp_IntToStr:PPROC
IntToStr equ <__imp_IntToStr>

externdef __imp_IprInit:PPROC
IprInit equ <__imp_IprInit>

externdef __imp_IsDFCondition:PPROC
IsDFCondition equ <__imp_IsDFCondition>

externdef __imp_JoinMnemonic:PPROC
JoinMnemonic equ <__imp_JoinMnemonic>

externdef __imp_LastInstrLength:PPROC
LastInstrLength equ <__imp_LastInstrLength>

externdef __imp_LatToStr:PPROC
LatToStr equ <__imp_LatToStr>

externdef __imp_MulNumbers:PPROC
MulNumbers equ <__imp_MulNumbers>

externdef __imp_NegateNumber:PPROC
NegateNumber equ <__imp_NegateNumber>

externdef __imp_NotNumber:PPROC
NotNumber equ <__imp_NotNumber>

externdef __imp_OrNumbers:PPROC
OrNumbers equ <__imp_OrNumbers>

externdef __imp_ParseSource:PPROC
ParseSource equ <__imp_ParseSource>

externdef __imp_ParseSourceEx:PPROC
ParseSourceEx equ <__imp_ParseSourceEx>

externdef __imp_ParseSourceExt:PPROC
ParseSourceExt equ <__imp_ParseSourceExt>

externdef __imp_ReinitInstr:PPROC
ReinitInstr equ <__imp_ReinitInstr>

externdef __imp_SelectValidLabelOrNumber:PPROC
SelectValidLabelOrNumber equ <__imp_SelectValidLabelOrNumber>

externdef __imp_SetArch:PPROC
SetArch equ <__imp_SetArch>

externdef __imp_SetBMI1:PPROC
SetBMI1 equ <__imp_SetBMI1>

externdef __imp_SetCPointer:PPROC
SetCPointer equ <__imp_SetCPointer>

externdef __imp_SetCPointerEx:PPROC
SetCPointerEx equ <__imp_SetCPointerEx>

externdef __imp_SetControlFlags:PPROC
SetControlFlags equ <__imp_SetControlFlags>

externdef __imp_SetLoadall:PPROC
SetLoadall equ <__imp_SetLoadall>

externdef __imp_SetLzcnt:PPROC
SetLzcnt equ <__imp_SetLzcnt>

externdef __imp_SetMode:PPROC
SetMode equ <__imp_SetMode>

externdef __imp_SetPopCs:PPROC
SetPopCs equ <__imp_SetPopCs>

externdef __imp_ShlNumber:PPROC
ShlNumber equ <__imp_ShlNumber>

externdef __imp_ShrNumber:PPROC
ShrNumber equ <__imp_ShrNumber>

externdef __imp_SrcAssemble:PPROC
SrcAssemble equ <__imp_SrcAssemble>

externdef __imp_SrcAssembleEx:PPROC
SrcAssembleEx equ <__imp_SrcAssembleEx>

externdef __imp_StrToInt:PPROC
StrToInt equ <__imp_StrToInt>

externdef __imp_SubNumbers:PPROC
SubNumbers equ <__imp_SubNumbers>

externdef __imp_XorNumbers:PPROC
XorNumbers equ <__imp_XorNumbers>
