externdef __imp_ADsPropCheckIfWritable:PPROC
ADsPropCheckIfWritable equ <__imp_ADsPropCheckIfWritable>

externdef __imp_ADsPropCreateNotifyObj:PPROC
ADsPropCreateNotifyObj equ <__imp_ADsPropCreateNotifyObj>

externdef __imp_ADsPropGetInitInfo:PPROC
ADsPropGetInitInfo equ <__imp_ADsPropGetInitInfo>

externdef __imp_ADsPropSendErrorMessage:PPROC
ADsPropSendErrorMessage equ <__imp_ADsPropSendErrorMessage>

externdef __imp_ADsPropSetHwnd:PPROC
ADsPropSetHwnd equ <__imp_ADsPropSetHwnd>

externdef __imp_ADsPropSetHwndWithTitle:PPROC
ADsPropSetHwndWithTitle equ <__imp_ADsPropSetHwndWithTitle>

externdef __imp_ADsPropShowErrorDialog:PPROC
ADsPropShowErrorDialog equ <__imp_ADsPropShowErrorDialog>

externdef __imp_BringSheetToForeground:PPROC
BringSheetToForeground equ <__imp_BringSheetToForeground>

externdef __imp_CheckADsError:PPROC
CheckADsError equ <__imp_CheckADsError>

externdef __imp_CrackName:PPROC
CrackName equ <__imp_CrackName>

externdef __imp_DSPROP_GetGCSearchOnDomain:PPROC
DSPROP_GetGCSearchOnDomain equ <__imp_DSPROP_GetGCSearchOnDomain>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_ErrMsg:PPROC
ErrMsg equ <__imp_ErrMsg>

externdef __imp_ErrMsgParam:PPROC
ErrMsgParam equ <__imp_ErrMsgParam>

externdef __imp_FindSheet:PPROC
FindSheet equ <__imp_FindSheet>

externdef __imp_IsSheetAlreadyUp:PPROC
IsSheetAlreadyUp equ <__imp_IsSheetAlreadyUp>

externdef __imp_MsgBox:PPROC
MsgBox equ <__imp_MsgBox>

externdef __imp_PostADsPropSheet:PPROC
PostADsPropSheet equ <__imp_PostADsPropSheet>

externdef __imp_ReportError:PPROC
ReportError equ <__imp_ReportError>

externdef __imp_Smart_PADS_ATTR_INFO__Empty:PPROC
Smart_PADS_ATTR_INFO__Empty equ <__imp_Smart_PADS_ATTR_INFO__Empty>
