externdef __imp_?DXConstOverArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z:PPROC
?DXConstOverArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z equ <__imp_?DXConstOverArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z>

externdef __imp_?DXConstUnderArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z:PPROC
?DXConstUnderArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z equ <__imp_?DXConstUnderArray@@YAXPEAVDXPMSAMPLE@@AEBV1@K@Z>

externdef __imp_?DXDitherArray@@YAXPEBUDXDITHERDESC@@@Z:PPROC
?DXDitherArray@@YAXPEBUDXDITHERDESC@@@Z equ <__imp_?DXDitherArray@@YAXPEBUDXDITHERDESC@@@Z>

externdef __imp_?DXLinearInterpolateArray@@YAXPEBVDXBASESAMPLE@@PEAUDXLIMAPINFO@@PEAV1@K@Z:PPROC
?DXLinearInterpolateArray@@YAXPEBVDXBASESAMPLE@@PEAUDXLIMAPINFO@@PEAV1@K@Z equ <__imp_?DXLinearInterpolateArray@@YAXPEBVDXBASESAMPLE@@PEAUDXLIMAPINFO@@PEAV1@K@Z>

externdef __imp_?DXOverArray@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z:PPROC
?DXOverArray@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z equ <__imp_?DXOverArray@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z>

externdef __imp_?DXOverArrayMMX@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z:PPROC
?DXOverArrayMMX@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z equ <__imp_?DXOverArrayMMX@@YAXPEAVDXPMSAMPLE@@PEBV1@K@Z>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllEnumClassObjects:PPROC
DllEnumClassObjects equ <__imp_DllEnumClassObjects>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
