externdef __imp_JetAddColumn:PPROC
JetAddColumn equ <__imp_JetAddColumn>

externdef __imp_JetAttachDatabase2:PPROC
JetAttachDatabase2 equ <__imp_JetAttachDatabase2>

externdef __imp_JetAttachDatabase:PPROC
JetAttachDatabase equ <__imp_JetAttachDatabase>

externdef __imp_JetAttachDatabaseWithStreaming:PPROC
JetAttachDatabaseWithStreaming equ <__imp_JetAttachDatabaseWithStreaming>

externdef __imp_JetBackup:PPROC
JetBackup equ <__imp_JetBackup>

externdef __imp_JetBackupInstance:PPROC
JetBackupInstance equ <__imp_JetBackupInstance>

externdef __imp_JetBeginExternalBackup:PPROC
JetBeginExternalBackup equ <__imp_JetBeginExternalBackup>

externdef __imp_JetBeginExternalBackupInstance:PPROC
JetBeginExternalBackupInstance equ <__imp_JetBeginExternalBackupInstance>

externdef __imp_JetBeginSession:PPROC
JetBeginSession equ <__imp_JetBeginSession>

externdef __imp_JetBeginTransaction2:PPROC
JetBeginTransaction2 equ <__imp_JetBeginTransaction2>

externdef __imp_JetBeginTransaction:PPROC
JetBeginTransaction equ <__imp_JetBeginTransaction>

externdef __imp_JetCloseDatabase:PPROC
JetCloseDatabase equ <__imp_JetCloseDatabase>

externdef __imp_JetCloseFile:PPROC
JetCloseFile equ <__imp_JetCloseFile>

externdef __imp_JetCloseFileInstance:PPROC
JetCloseFileInstance equ <__imp_JetCloseFileInstance>

externdef __imp_JetCloseTable:PPROC
JetCloseTable equ <__imp_JetCloseTable>

externdef __imp_JetCommitTransaction:PPROC
JetCommitTransaction equ <__imp_JetCommitTransaction>

externdef __imp_JetCompact:PPROC
JetCompact equ <__imp_JetCompact>

externdef __imp_JetComputeStats:PPROC
JetComputeStats equ <__imp_JetComputeStats>

externdef __imp_JetConvertDDL:PPROC
JetConvertDDL equ <__imp_JetConvertDDL>

externdef __imp_JetCreateDatabase2:PPROC
JetCreateDatabase2 equ <__imp_JetCreateDatabase2>

externdef __imp_JetCreateDatabase:PPROC
JetCreateDatabase equ <__imp_JetCreateDatabase>

externdef __imp_JetCreateDatabaseWithStreaming:PPROC
JetCreateDatabaseWithStreaming equ <__imp_JetCreateDatabaseWithStreaming>

externdef __imp_JetCreateIndex2:PPROC
JetCreateIndex2 equ <__imp_JetCreateIndex2>

externdef __imp_JetCreateIndex:PPROC
JetCreateIndex equ <__imp_JetCreateIndex>

externdef __imp_JetCreateInstance2:PPROC
JetCreateInstance2 equ <__imp_JetCreateInstance2>

externdef __imp_JetCreateInstance:PPROC
JetCreateInstance equ <__imp_JetCreateInstance>

externdef __imp_JetCreateTable:PPROC
JetCreateTable equ <__imp_JetCreateTable>

externdef __imp_JetCreateTableColumnIndex2:PPROC
JetCreateTableColumnIndex2 equ <__imp_JetCreateTableColumnIndex2>

externdef __imp_JetCreateTableColumnIndex:PPROC
JetCreateTableColumnIndex equ <__imp_JetCreateTableColumnIndex>

externdef __imp_JetDBUtilities:PPROC
JetDBUtilities equ <__imp_JetDBUtilities>

externdef __imp_JetDefragment2:PPROC
JetDefragment2 equ <__imp_JetDefragment2>

externdef __imp_JetDefragment:PPROC
JetDefragment equ <__imp_JetDefragment>

externdef __imp_JetDelete:PPROC
JetDelete equ <__imp_JetDelete>

externdef __imp_JetDeleteColumn2:PPROC
JetDeleteColumn2 equ <__imp_JetDeleteColumn2>

externdef __imp_JetDeleteColumn:PPROC
JetDeleteColumn equ <__imp_JetDeleteColumn>

externdef __imp_JetDeleteIndex:PPROC
JetDeleteIndex equ <__imp_JetDeleteIndex>

externdef __imp_JetDeleteTable:PPROC
JetDeleteTable equ <__imp_JetDeleteTable>

externdef __imp_JetDetachDatabase2:PPROC
JetDetachDatabase2 equ <__imp_JetDetachDatabase2>

externdef __imp_JetDetachDatabase:PPROC
JetDetachDatabase equ <__imp_JetDetachDatabase>

externdef __imp_JetDupCursor:PPROC
JetDupCursor equ <__imp_JetDupCursor>

externdef __imp_JetDupSession:PPROC
JetDupSession equ <__imp_JetDupSession>

externdef __imp_JetEnableMultiInstance:PPROC
JetEnableMultiInstance equ <__imp_JetEnableMultiInstance>

externdef __imp_JetEndExternalBackup:PPROC
JetEndExternalBackup equ <__imp_JetEndExternalBackup>

externdef __imp_JetEndExternalBackupInstance2:PPROC
JetEndExternalBackupInstance2 equ <__imp_JetEndExternalBackupInstance2>

externdef __imp_JetEndExternalBackupInstance:PPROC
JetEndExternalBackupInstance equ <__imp_JetEndExternalBackupInstance>

externdef __imp_JetEndSession:PPROC
JetEndSession equ <__imp_JetEndSession>

externdef __imp_JetEnumerateColumns:PPROC
JetEnumerateColumns equ <__imp_JetEnumerateColumns>

externdef __imp_JetEscrowUpdate:PPROC
JetEscrowUpdate equ <__imp_JetEscrowUpdate>

externdef __imp_JetExternalRestore2:PPROC
JetExternalRestore2 equ <__imp_JetExternalRestore2>

externdef __imp_JetExternalRestore:PPROC
JetExternalRestore equ <__imp_JetExternalRestore>

externdef __imp_JetFreeBuffer:PPROC
JetFreeBuffer equ <__imp_JetFreeBuffer>

externdef __imp_JetGetAttachInfo:PPROC
JetGetAttachInfo equ <__imp_JetGetAttachInfo>

externdef __imp_JetGetAttachInfoInstance:PPROC
JetGetAttachInfoInstance equ <__imp_JetGetAttachInfoInstance>

externdef __imp_JetGetBookmark:PPROC
JetGetBookmark equ <__imp_JetGetBookmark>

externdef __imp_JetGetColumnInfo:PPROC
JetGetColumnInfo equ <__imp_JetGetColumnInfo>

externdef __imp_JetGetCounter:PPROC
JetGetCounter equ <__imp_JetGetCounter>

externdef __imp_JetGetCurrentIndex:PPROC
JetGetCurrentIndex equ <__imp_JetGetCurrentIndex>

externdef __imp_JetGetCursorInfo:PPROC
JetGetCursorInfo equ <__imp_JetGetCursorInfo>

externdef __imp_JetGetDatabaseFileInfo:PPROC
JetGetDatabaseFileInfo equ <__imp_JetGetDatabaseFileInfo>

externdef __imp_JetGetDatabaseInfo:PPROC
JetGetDatabaseInfo equ <__imp_JetGetDatabaseInfo>

externdef __imp_JetGetIndexInfo:PPROC
JetGetIndexInfo equ <__imp_JetGetIndexInfo>

externdef __imp_JetGetInstanceInfo:PPROC
JetGetInstanceInfo equ <__imp_JetGetInstanceInfo>

externdef __imp_JetGetLS:PPROC
JetGetLS equ <__imp_JetGetLS>

externdef __imp_JetGetLock:PPROC
JetGetLock equ <__imp_JetGetLock>

externdef __imp_JetGetLogInfo:PPROC
JetGetLogInfo equ <__imp_JetGetLogInfo>

externdef __imp_JetGetLogInfoInstance2:PPROC
JetGetLogInfoInstance2 equ <__imp_JetGetLogInfoInstance2>

externdef __imp_JetGetLogInfoInstance:PPROC
JetGetLogInfoInstance equ <__imp_JetGetLogInfoInstance>

externdef __imp_JetGetObjectInfo:PPROC
JetGetObjectInfo equ <__imp_JetGetObjectInfo>

externdef __imp_JetGetRecordPosition:PPROC
JetGetRecordPosition equ <__imp_JetGetRecordPosition>

externdef __imp_JetGetSecondaryIndexBookmark:PPROC
JetGetSecondaryIndexBookmark equ <__imp_JetGetSecondaryIndexBookmark>

externdef __imp_JetGetSystemParameter:PPROC
JetGetSystemParameter equ <__imp_JetGetSystemParameter>

externdef __imp_JetGetTableColumnInfo:PPROC
JetGetTableColumnInfo equ <__imp_JetGetTableColumnInfo>

externdef __imp_JetGetTableIndexInfo:PPROC
JetGetTableIndexInfo equ <__imp_JetGetTableIndexInfo>

externdef __imp_JetGetTableInfo:PPROC
JetGetTableInfo equ <__imp_JetGetTableInfo>

externdef __imp_JetGetTruncateLogInfoInstance:PPROC
JetGetTruncateLogInfoInstance equ <__imp_JetGetTruncateLogInfoInstance>

externdef __imp_JetGetVersion:PPROC
JetGetVersion equ <__imp_JetGetVersion>

externdef __imp_JetGotoBookmark:PPROC
JetGotoBookmark equ <__imp_JetGotoBookmark>

externdef __imp_JetGotoPosition:PPROC
JetGotoPosition equ <__imp_JetGotoPosition>

externdef __imp_JetGotoSecondaryIndexBookmark:PPROC
JetGotoSecondaryIndexBookmark equ <__imp_JetGotoSecondaryIndexBookmark>

externdef __imp_JetGrowDatabase:PPROC
JetGrowDatabase equ <__imp_JetGrowDatabase>

externdef __imp_JetIdle:PPROC
JetIdle equ <__imp_JetIdle>

externdef __imp_JetIndexRecordCount:PPROC
JetIndexRecordCount equ <__imp_JetIndexRecordCount>

externdef __imp_JetInit2:PPROC
JetInit2 equ <__imp_JetInit2>

externdef __imp_JetInit3:PPROC
JetInit3 equ <__imp_JetInit3>

externdef __imp_JetInit:PPROC
JetInit equ <__imp_JetInit>

externdef __imp_JetIntersectIndexes:PPROC
JetIntersectIndexes equ <__imp_JetIntersectIndexes>

externdef __imp_JetMakeKey:PPROC
JetMakeKey equ <__imp_JetMakeKey>

externdef __imp_JetMove:PPROC
JetMove equ <__imp_JetMove>

externdef __imp_JetOSSnapshotAbort:PPROC
JetOSSnapshotAbort equ <__imp_JetOSSnapshotAbort>

externdef __imp_JetOSSnapshotFreeze:PPROC
JetOSSnapshotFreeze equ <__imp_JetOSSnapshotFreeze>

externdef __imp_JetOSSnapshotPrepare:PPROC
JetOSSnapshotPrepare equ <__imp_JetOSSnapshotPrepare>

externdef __imp_JetOSSnapshotThaw:PPROC
JetOSSnapshotThaw equ <__imp_JetOSSnapshotThaw>

externdef __imp_JetOpenDatabase:PPROC
JetOpenDatabase equ <__imp_JetOpenDatabase>

externdef __imp_JetOpenFile:PPROC
JetOpenFile equ <__imp_JetOpenFile>

externdef __imp_JetOpenFileInstance:PPROC
JetOpenFileInstance equ <__imp_JetOpenFileInstance>

externdef __imp_JetOpenFileSectionInstance:PPROC
JetOpenFileSectionInstance equ <__imp_JetOpenFileSectionInstance>

externdef __imp_JetOpenTable:PPROC
JetOpenTable equ <__imp_JetOpenTable>

externdef __imp_JetOpenTempTable2:PPROC
JetOpenTempTable2 equ <__imp_JetOpenTempTable2>

externdef __imp_JetOpenTempTable3:PPROC
JetOpenTempTable3 equ <__imp_JetOpenTempTable3>

externdef __imp_JetOpenTempTable:PPROC
JetOpenTempTable equ <__imp_JetOpenTempTable>

externdef __imp_JetPrepareToCommitTransaction:PPROC
JetPrepareToCommitTransaction equ <__imp_JetPrepareToCommitTransaction>

externdef __imp_JetPrepareUpdate:PPROC
JetPrepareUpdate equ <__imp_JetPrepareUpdate>

externdef __imp_JetReadFile:PPROC
JetReadFile equ <__imp_JetReadFile>

externdef __imp_JetReadFileInstance:PPROC
JetReadFileInstance equ <__imp_JetReadFileInstance>

externdef __imp_JetRegisterCallback:PPROC
JetRegisterCallback equ <__imp_JetRegisterCallback>

externdef __imp_JetRenameColumn:PPROC
JetRenameColumn equ <__imp_JetRenameColumn>

externdef __imp_JetRenameTable:PPROC
JetRenameTable equ <__imp_JetRenameTable>

externdef __imp_JetResetCounter:PPROC
JetResetCounter equ <__imp_JetResetCounter>

externdef __imp_JetResetSessionContext:PPROC
JetResetSessionContext equ <__imp_JetResetSessionContext>

externdef __imp_JetResetTableSequential:PPROC
JetResetTableSequential equ <__imp_JetResetTableSequential>

externdef __imp_JetRestore2:PPROC
JetRestore2 equ <__imp_JetRestore2>

externdef __imp_JetRestore:PPROC
JetRestore equ <__imp_JetRestore>

externdef __imp_JetRestoreInstance:PPROC
JetRestoreInstance equ <__imp_JetRestoreInstance>

externdef __imp_JetRetrieveColumn:PPROC
JetRetrieveColumn equ <__imp_JetRetrieveColumn>

externdef __imp_JetRetrieveColumns:PPROC
JetRetrieveColumns equ <__imp_JetRetrieveColumns>

externdef __imp_JetRetrieveKey:PPROC
JetRetrieveKey equ <__imp_JetRetrieveKey>

externdef __imp_JetRetrieveTaggedColumnList:PPROC
JetRetrieveTaggedColumnList equ <__imp_JetRetrieveTaggedColumnList>

externdef __imp_JetRollback:PPROC
JetRollback equ <__imp_JetRollback>

externdef __imp_JetSeek:PPROC
JetSeek equ <__imp_JetSeek>

externdef __imp_JetSetColumn:PPROC
JetSetColumn equ <__imp_JetSetColumn>

externdef __imp_JetSetColumnDefaultValue:PPROC
JetSetColumnDefaultValue equ <__imp_JetSetColumnDefaultValue>

externdef __imp_JetSetColumns:PPROC
JetSetColumns equ <__imp_JetSetColumns>

externdef __imp_JetSetCurrentIndex2:PPROC
JetSetCurrentIndex2 equ <__imp_JetSetCurrentIndex2>

externdef __imp_JetSetCurrentIndex3:PPROC
JetSetCurrentIndex3 equ <__imp_JetSetCurrentIndex3>

externdef __imp_JetSetCurrentIndex4:PPROC
JetSetCurrentIndex4 equ <__imp_JetSetCurrentIndex4>

externdef __imp_JetSetCurrentIndex:PPROC
JetSetCurrentIndex equ <__imp_JetSetCurrentIndex>

externdef __imp_JetSetDatabaseSize:PPROC
JetSetDatabaseSize equ <__imp_JetSetDatabaseSize>

externdef __imp_JetSetIndexRange:PPROC
JetSetIndexRange equ <__imp_JetSetIndexRange>

externdef __imp_JetSetLS:PPROC
JetSetLS equ <__imp_JetSetLS>

externdef __imp_JetSetSessionContext:PPROC
JetSetSessionContext equ <__imp_JetSetSessionContext>

externdef __imp_JetSetSystemParameter:PPROC
JetSetSystemParameter equ <__imp_JetSetSystemParameter>

externdef __imp_JetSetTableSequential:PPROC
JetSetTableSequential equ <__imp_JetSetTableSequential>

externdef __imp_JetSnapshotStart:PPROC
JetSnapshotStart equ <__imp_JetSnapshotStart>

externdef __imp_JetSnapshotStop:PPROC
JetSnapshotStop equ <__imp_JetSnapshotStop>

externdef __imp_JetStopBackup:PPROC
JetStopBackup equ <__imp_JetStopBackup>

externdef __imp_JetStopBackupInstance:PPROC
JetStopBackupInstance equ <__imp_JetStopBackupInstance>

externdef __imp_JetStopService:PPROC
JetStopService equ <__imp_JetStopService>

externdef __imp_JetStopServiceInstance:PPROC
JetStopServiceInstance equ <__imp_JetStopServiceInstance>

externdef __imp_JetTerm2:PPROC
JetTerm2 equ <__imp_JetTerm2>

externdef __imp_JetTerm:PPROC
JetTerm equ <__imp_JetTerm>

externdef __imp_JetTruncateLog:PPROC
JetTruncateLog equ <__imp_JetTruncateLog>

externdef __imp_JetTruncateLogInstance:PPROC
JetTruncateLogInstance equ <__imp_JetTruncateLogInstance>

externdef __imp_JetUnregisterCallback:PPROC
JetUnregisterCallback equ <__imp_JetUnregisterCallback>

externdef __imp_JetUpdate2:PPROC
JetUpdate2 equ <__imp_JetUpdate2>

externdef __imp_JetUpdate:PPROC
JetUpdate equ <__imp_JetUpdate>

externdef __imp_JetUpgradeDatabase:PPROC
JetUpgradeDatabase equ <__imp_JetUpgradeDatabase>

externdef __imp_ese:PPROC
ese equ <__imp_ese>

externdef __imp_esent:PPROC
esent equ <__imp_esent>
