externdef __imp_Chkdsk:PPROC
Chkdsk equ <__imp_Chkdsk>

externdef __imp_ChkdskEx:PPROC
ChkdskEx equ <__imp_ChkdskEx>

externdef __imp_ComputeFmMediaType:PPROC
ComputeFmMediaType equ <__imp_ComputeFmMediaType>

externdef __imp_DiskCopy:PPROC
DiskCopy equ <__imp_DiskCopy>

externdef __imp_EnableVolumeCompression:PPROC
EnableVolumeCompression equ <__imp_EnableVolumeCompression>

externdef __imp_Extend:PPROC
Extend equ <__imp_Extend>

externdef __imp_Format:PPROC
Format equ <__imp_Format>

externdef __imp_FormatEx2:PPROC
FormatEx2 equ <__imp_FormatEx2>

externdef __imp_FormatEx:PPROC
FormatEx equ <__imp_FormatEx>

externdef __imp_QueryAvailableFileSystemFormat:PPROC
QueryAvailableFileSystemFormat equ <__imp_QueryAvailableFileSystemFormat>

externdef __imp_QueryDeviceInformation:PPROC
QueryDeviceInformation equ <__imp_QueryDeviceInformation>

externdef __imp_QueryDeviceInformationByHandle:PPROC
QueryDeviceInformationByHandle equ <__imp_QueryDeviceInformationByHandle>

externdef __imp_QueryFileSystemName:PPROC
QueryFileSystemName equ <__imp_QueryFileSystemName>

externdef __imp_QueryLatestFileSystemVersion:PPROC
QueryLatestFileSystemVersion equ <__imp_QueryLatestFileSystemVersion>

externdef __imp_QuerySupportedMedia:PPROC
QuerySupportedMedia equ <__imp_QuerySupportedMedia>

externdef __imp_SetLabel:PPROC
SetLabel equ <__imp_SetLabel>
