externdef __imp___glsParser_create:PPROC
__glsParser_create equ <__imp___glsParser_create>

externdef __imp___glsParser_print:PPROC
__glsParser_print equ <__imp___glsParser_print>

externdef __imp___glsString_appendChar:PPROC
__glsString_appendChar equ <__imp___glsString_appendChar>

externdef __imp___glsString_assign:PPROC
__glsString_assign equ <__imp___glsString_assign>

externdef __imp___glsString_init:PPROC
__glsString_init equ <__imp___glsString_init>

externdef __imp_glsAbortCall:PPROC
glsAbortCall equ <__imp_glsAbortCall>

externdef __imp_glsAppRef:PPROC
glsAppRef equ <__imp_glsAppRef>

externdef __imp_glsBeginCapture:PPROC
glsBeginCapture equ <__imp_glsBeginCapture>

externdef __imp_glsBeginGLS:PPROC
glsBeginGLS equ <__imp_glsBeginGLS>

externdef __imp_glsBeginObj:PPROC
glsBeginObj equ <__imp_glsBeginObj>

externdef __imp_glsBinary:PPROC
glsBinary equ <__imp_glsBinary>

externdef __imp_glsBlock:PPROC
glsBlock equ <__imp_glsBlock>

externdef __imp_glsCallArray:PPROC
glsCallArray equ <__imp_glsCallArray>

externdef __imp_glsCallArrayInContext:PPROC
glsCallArrayInContext equ <__imp_glsCallArrayInContext>

externdef __imp_glsCallStream:PPROC
glsCallStream equ <__imp_glsCallStream>

externdef __imp_glsCaptureFlags:PPROC
glsCaptureFlags equ <__imp_glsCaptureFlags>

externdef __imp_glsCaptureFunc:PPROC
glsCaptureFunc equ <__imp_glsCaptureFunc>

externdef __imp_glsChannel:PPROC
glsChannel equ <__imp_glsChannel>

externdef __imp_glsCharubz:PPROC
glsCharubz equ <__imp_glsCharubz>

externdef __imp_glsCommandAPI:PPROC
glsCommandAPI equ <__imp_glsCommandAPI>

externdef __imp_glsCommandFunc:PPROC
glsCommandFunc equ <__imp_glsCommandFunc>

externdef __imp_glsCommandString:PPROC
glsCommandString equ <__imp_glsCommandString>

externdef __imp_glsComment:PPROC
glsComment equ <__imp_glsComment>

externdef __imp_glsContext:PPROC
glsContext equ <__imp_glsContext>

externdef __imp_glsCopyStream:PPROC
glsCopyStream equ <__imp_glsCopyStream>

externdef __imp_glsDataPointer:PPROC
glsDataPointer equ <__imp_glsDataPointer>

externdef __imp_glsDeleteContext:PPROC
glsDeleteContext equ <__imp_glsDeleteContext>

externdef __imp_glsDeleteReadPrefix:PPROC
glsDeleteReadPrefix equ <__imp_glsDeleteReadPrefix>

externdef __imp_glsDeleteStream:PPROC
glsDeleteStream equ <__imp_glsDeleteStream>

externdef __imp_glsDisplayMapfv:PPROC
glsDisplayMapfv equ <__imp_glsDisplayMapfv>

externdef __imp_glsEndCapture:PPROC
glsEndCapture equ <__imp_glsEndCapture>

externdef __imp_glsEndGLS:PPROC
glsEndGLS equ <__imp_glsEndGLS>

externdef __imp_glsEndObj:PPROC
glsEndObj equ <__imp_glsEndObj>

externdef __imp_glsEnumString:PPROC
glsEnumString equ <__imp_glsEnumString>

externdef __imp_glsError:PPROC
glsError equ <__imp_glsError>

externdef __imp_glsFlush:PPROC
glsFlush equ <__imp_glsFlush>

externdef __imp_glsGLRC:PPROC
glsGLRC equ <__imp_glsGLRC>

externdef __imp_glsGLRCLayer:PPROC
glsGLRCLayer equ <__imp_glsGLRCLayer>

externdef __imp_glsGenContext:PPROC
glsGenContext equ <__imp_glsGenContext>

externdef __imp_glsGetAllContexts:PPROC
glsGetAllContexts equ <__imp_glsGetAllContexts>

externdef __imp_glsGetCaptureDispatchTable:PPROC
glsGetCaptureDispatchTable equ <__imp_glsGetCaptureDispatchTable>

externdef __imp_glsGetCaptureExecTable:PPROC
glsGetCaptureExecTable equ <__imp_glsGetCaptureExecTable>

externdef __imp_glsGetCaptureFlags:PPROC
glsGetCaptureFlags equ <__imp_glsGetCaptureFlags>

externdef __imp_glsGetCommandAlignment:PPROC
glsGetCommandAlignment equ <__imp_glsGetCommandAlignment>

externdef __imp_glsGetCommandAttrib:PPROC
glsGetCommandAttrib equ <__imp_glsGetCommandAttrib>

externdef __imp_glsGetCommandFunc:PPROC
glsGetCommandFunc equ <__imp_glsGetCommandFunc>

externdef __imp_glsGetConsti:PPROC
glsGetConsti equ <__imp_glsGetConsti>

externdef __imp_glsGetConstiv:PPROC
glsGetConstiv equ <__imp_glsGetConstiv>

externdef __imp_glsGetConstubz:PPROC
glsGetConstubz equ <__imp_glsGetConstubz>

externdef __imp_glsGetContextFunc:PPROC
glsGetContextFunc equ <__imp_glsGetContextFunc>

externdef __imp_glsGetContextListl:PPROC
glsGetContextListl equ <__imp_glsGetContextListl>

externdef __imp_glsGetContextListubz:PPROC
glsGetContextListubz equ <__imp_glsGetContextListubz>

externdef __imp_glsGetContextPointer:PPROC
glsGetContextPointer equ <__imp_glsGetContextPointer>

externdef __imp_glsGetContexti:PPROC
glsGetContexti equ <__imp_glsGetContexti>

externdef __imp_glsGetContextubz:PPROC
glsGetContextubz equ <__imp_glsGetContextubz>

externdef __imp_glsGetCurrentContext:PPROC
glsGetCurrentContext equ <__imp_glsGetCurrentContext>

externdef __imp_glsGetCurrentTime:PPROC
glsGetCurrentTime equ <__imp_glsGetCurrentTime>

externdef __imp_glsGetError:PPROC
glsGetError equ <__imp_glsGetError>

externdef __imp_glsGetGLRCi:PPROC
glsGetGLRCi equ <__imp_glsGetGLRCi>

externdef __imp_glsGetHeaderf:PPROC
glsGetHeaderf equ <__imp_glsGetHeaderf>

externdef __imp_glsGetHeaderfv:PPROC
glsGetHeaderfv equ <__imp_glsGetHeaderfv>

externdef __imp_glsGetHeaderi:PPROC
glsGetHeaderi equ <__imp_glsGetHeaderi>

externdef __imp_glsGetHeaderiv:PPROC
glsGetHeaderiv equ <__imp_glsGetHeaderiv>

externdef __imp_glsGetHeaderubz:PPROC
glsGetHeaderubz equ <__imp_glsGetHeaderubz>

externdef __imp_glsGetLayerf:PPROC
glsGetLayerf equ <__imp_glsGetLayerf>

externdef __imp_glsGetLayeri:PPROC
glsGetLayeri equ <__imp_glsGetLayeri>

externdef __imp_glsGetOpcodeCount:PPROC
glsGetOpcodeCount equ <__imp_glsGetOpcodeCount>

externdef __imp_glsGetOpcodes:PPROC
glsGetOpcodes equ <__imp_glsGetOpcodes>

externdef __imp_glsGetStreamAttrib:PPROC
glsGetStreamAttrib equ <__imp_glsGetStreamAttrib>

externdef __imp_glsGetStreamCRC32:PPROC
glsGetStreamCRC32 equ <__imp_glsGetStreamCRC32>

externdef __imp_glsGetStreamReadName:PPROC
glsGetStreamReadName equ <__imp_glsGetStreamReadName>

externdef __imp_glsGetStreamSize:PPROC
glsGetStreamSize equ <__imp_glsGetStreamSize>

externdef __imp_glsGetStreamType:PPROC
glsGetStreamType equ <__imp_glsGetStreamType>

externdef __imp_glsHeaderGLRCi:PPROC
glsHeaderGLRCi equ <__imp_glsHeaderGLRCi>

externdef __imp_glsHeaderLayerf:PPROC
glsHeaderLayerf equ <__imp_glsHeaderLayerf>

externdef __imp_glsHeaderLayeri:PPROC
glsHeaderLayeri equ <__imp_glsHeaderLayeri>

externdef __imp_glsHeaderf:PPROC
glsHeaderf equ <__imp_glsHeaderf>

externdef __imp_glsHeaderfv:PPROC
glsHeaderfv equ <__imp_glsHeaderfv>

externdef __imp_glsHeaderi:PPROC
glsHeaderi equ <__imp_glsHeaderi>

externdef __imp_glsHeaderiv:PPROC
glsHeaderiv equ <__imp_glsHeaderiv>

externdef __imp_glsHeaderubz:PPROC
glsHeaderubz equ <__imp_glsHeaderubz>

externdef __imp_glsIsContext:PPROC
glsIsContext equ <__imp_glsIsContext>

externdef __imp_glsIsContextStream:PPROC
glsIsContextStream equ <__imp_glsIsContextStream>

externdef __imp_glsIsExtensionSupported:PPROC
glsIsExtensionSupported equ <__imp_glsIsExtensionSupported>

externdef __imp_glsIsUTF8String:PPROC
glsIsUTF8String equ <__imp_glsIsUTF8String>

externdef __imp_glsLong:PPROC
glsLong equ <__imp_glsLong>

externdef __imp_glsLongHigh:PPROC
glsLongHigh equ <__imp_glsLongHigh>

externdef __imp_glsLongLow:PPROC
glsLongLow equ <__imp_glsLongLow>

externdef __imp_glsNullCommandFunc:PPROC
glsNullCommandFunc equ <__imp_glsNullCommandFunc>

externdef __imp_glsNumb:PPROC
glsNumb equ <__imp_glsNumb>

externdef __imp_glsNumbv:PPROC
glsNumbv equ <__imp_glsNumbv>

externdef __imp_glsNumd:PPROC
glsNumd equ <__imp_glsNumd>

externdef __imp_glsNumdv:PPROC
glsNumdv equ <__imp_glsNumdv>

externdef __imp_glsNumf:PPROC
glsNumf equ <__imp_glsNumf>

externdef __imp_glsNumfv:PPROC
glsNumfv equ <__imp_glsNumfv>

externdef __imp_glsNumi:PPROC
glsNumi equ <__imp_glsNumi>

externdef __imp_glsNumiv:PPROC
glsNumiv equ <__imp_glsNumiv>

externdef __imp_glsNuml:PPROC
glsNuml equ <__imp_glsNuml>

externdef __imp_glsNumlv:PPROC
glsNumlv equ <__imp_glsNumlv>

externdef __imp_glsNums:PPROC
glsNums equ <__imp_glsNums>

externdef __imp_glsNumsv:PPROC
glsNumsv equ <__imp_glsNumsv>

externdef __imp_glsNumub:PPROC
glsNumub equ <__imp_glsNumub>

externdef __imp_glsNumubv:PPROC
glsNumubv equ <__imp_glsNumubv>

externdef __imp_glsNumui:PPROC
glsNumui equ <__imp_glsNumui>

externdef __imp_glsNumuiv:PPROC
glsNumuiv equ <__imp_glsNumuiv>

externdef __imp_glsNumul:PPROC
glsNumul equ <__imp_glsNumul>

externdef __imp_glsNumulv:PPROC
glsNumulv equ <__imp_glsNumulv>

externdef __imp_glsNumus:PPROC
glsNumus equ <__imp_glsNumus>

externdef __imp_glsNumusv:PPROC
glsNumusv equ <__imp_glsNumusv>

externdef __imp_glsPad:PPROC
glsPad equ <__imp_glsPad>

externdef __imp_glsPixelSetup:PPROC
glsPixelSetup equ <__imp_glsPixelSetup>

externdef __imp_glsPixelSetupGen:PPROC
glsPixelSetupGen equ <__imp_glsPixelSetupGen>

externdef __imp_glsReadFunc:PPROC
glsReadFunc equ <__imp_glsReadFunc>

externdef __imp_glsReadPrefix:PPROC
glsReadPrefix equ <__imp_glsReadPrefix>

externdef __imp_glsRequireExtension:PPROC
glsRequireExtension equ <__imp_glsRequireExtension>

externdef __imp_glsSwapBuffers:PPROC
glsSwapBuffers equ <__imp_glsSwapBuffers>

externdef __imp_glsUCS1toUTF8z:PPROC
glsUCS1toUTF8z equ <__imp_glsUCS1toUTF8z>

externdef __imp_glsUCS2toUTF8z:PPROC
glsUCS2toUTF8z equ <__imp_glsUCS2toUTF8z>

externdef __imp_glsUCS4toUTF8:PPROC
glsUCS4toUTF8 equ <__imp_glsUCS4toUTF8>

externdef __imp_glsUCS4toUTF8z:PPROC
glsUCS4toUTF8z equ <__imp_glsUCS4toUTF8z>

externdef __imp_glsUCStoUTF8z:PPROC
glsUCStoUTF8z equ <__imp_glsUCStoUTF8z>

externdef __imp_glsULong:PPROC
glsULong equ <__imp_glsULong>

externdef __imp_glsULongHigh:PPROC
glsULongHigh equ <__imp_glsULongHigh>

externdef __imp_glsULongLow:PPROC
glsULongLow equ <__imp_glsULongLow>

externdef __imp_glsUTF8toUCS1z:PPROC
glsUTF8toUCS1z equ <__imp_glsUTF8toUCS1z>

externdef __imp_glsUTF8toUCS2z:PPROC
glsUTF8toUCS2z equ <__imp_glsUTF8toUCS2z>

externdef __imp_glsUTF8toUCS4:PPROC
glsUTF8toUCS4 equ <__imp_glsUTF8toUCS4>

externdef __imp_glsUTF8toUCS4z:PPROC
glsUTF8toUCS4z equ <__imp_glsUTF8toUCS4z>

externdef __imp_glsUTF8toUCSz:PPROC
glsUTF8toUCSz equ <__imp_glsUTF8toUCSz>

externdef __imp_glsUnreadFunc:PPROC
glsUnreadFunc equ <__imp_glsUnreadFunc>

externdef __imp_glsUnsupportedCommand:PPROC
glsUnsupportedCommand equ <__imp_glsUnsupportedCommand>

externdef __imp_glsUpdateCaptureExecTable:PPROC
glsUpdateCaptureExecTable equ <__imp_glsUpdateCaptureExecTable>

externdef __imp_glsWriteFunc:PPROC
glsWriteFunc equ <__imp_glsWriteFunc>

externdef __imp_glsWritePrefix:PPROC
glsWritePrefix equ <__imp_glsWritePrefix>
