externdef __imp_gluBeginCurve:PPROC
gluBeginCurve equ <__imp_gluBeginCurve>

externdef __imp_gluBeginPolygon:PPROC
gluBeginPolygon equ <__imp_gluBeginPolygon>

externdef __imp_gluBeginSurface:PPROC
gluBeginSurface equ <__imp_gluBeginSurface>

externdef __imp_gluBeginTrim:PPROC
gluBeginTrim equ <__imp_gluBeginTrim>

externdef __imp_gluBuild1DMipmaps:PPROC
gluBuild1DMipmaps equ <__imp_gluBuild1DMipmaps>

externdef __imp_gluBuild2DMipmaps:PPROC
gluBuild2DMipmaps equ <__imp_gluBuild2DMipmaps>

externdef __imp_gluCylinder:PPROC
gluCylinder equ <__imp_gluCylinder>

externdef __imp_gluDeleteNurbsRenderer:PPROC
gluDeleteNurbsRenderer equ <__imp_gluDeleteNurbsRenderer>

externdef __imp_gluDeleteQuadric:PPROC
gluDeleteQuadric equ <__imp_gluDeleteQuadric>

externdef __imp_gluDeleteTess:PPROC
gluDeleteTess equ <__imp_gluDeleteTess>

externdef __imp_gluDisk:PPROC
gluDisk equ <__imp_gluDisk>

externdef __imp_gluEndCurve:PPROC
gluEndCurve equ <__imp_gluEndCurve>

externdef __imp_gluEndPolygon:PPROC
gluEndPolygon equ <__imp_gluEndPolygon>

externdef __imp_gluEndSurface:PPROC
gluEndSurface equ <__imp_gluEndSurface>

externdef __imp_gluEndTrim:PPROC
gluEndTrim equ <__imp_gluEndTrim>

externdef __imp_gluErrorString:PPROC
gluErrorString equ <__imp_gluErrorString>

externdef __imp_gluErrorUnicodeStringEXT:PPROC
gluErrorUnicodeStringEXT equ <__imp_gluErrorUnicodeStringEXT>

externdef __imp_gluGetNurbsProperty:PPROC
gluGetNurbsProperty equ <__imp_gluGetNurbsProperty>

externdef __imp_gluGetString:PPROC
gluGetString equ <__imp_gluGetString>

externdef __imp_gluGetTessProperty:PPROC
gluGetTessProperty equ <__imp_gluGetTessProperty>

externdef __imp_gluLoadSamplingMatrices:PPROC
gluLoadSamplingMatrices equ <__imp_gluLoadSamplingMatrices>

externdef __imp_gluLookAt:PPROC
gluLookAt equ <__imp_gluLookAt>

externdef __imp_gluNewNurbsRenderer:PPROC
gluNewNurbsRenderer equ <__imp_gluNewNurbsRenderer>

externdef __imp_gluNewQuadric:PPROC
gluNewQuadric equ <__imp_gluNewQuadric>

externdef __imp_gluNewTess:PPROC
gluNewTess equ <__imp_gluNewTess>

externdef __imp_gluNextContour:PPROC
gluNextContour equ <__imp_gluNextContour>

externdef __imp_gluNurbsCallback:PPROC
gluNurbsCallback equ <__imp_gluNurbsCallback>

externdef __imp_gluNurbsCurve:PPROC
gluNurbsCurve equ <__imp_gluNurbsCurve>

externdef __imp_gluNurbsProperty:PPROC
gluNurbsProperty equ <__imp_gluNurbsProperty>

externdef __imp_gluNurbsSurface:PPROC
gluNurbsSurface equ <__imp_gluNurbsSurface>

externdef __imp_gluOrtho2D:PPROC
gluOrtho2D equ <__imp_gluOrtho2D>

externdef __imp_gluPartialDisk:PPROC
gluPartialDisk equ <__imp_gluPartialDisk>

externdef __imp_gluPerspective:PPROC
gluPerspective equ <__imp_gluPerspective>

externdef __imp_gluPickMatrix:PPROC
gluPickMatrix equ <__imp_gluPickMatrix>

externdef __imp_gluProject:PPROC
gluProject equ <__imp_gluProject>

externdef __imp_gluPwlCurve:PPROC
gluPwlCurve equ <__imp_gluPwlCurve>

externdef __imp_gluQuadricCallback:PPROC
gluQuadricCallback equ <__imp_gluQuadricCallback>

externdef __imp_gluQuadricDrawStyle:PPROC
gluQuadricDrawStyle equ <__imp_gluQuadricDrawStyle>

externdef __imp_gluQuadricNormals:PPROC
gluQuadricNormals equ <__imp_gluQuadricNormals>

externdef __imp_gluQuadricOrientation:PPROC
gluQuadricOrientation equ <__imp_gluQuadricOrientation>

externdef __imp_gluQuadricTexture:PPROC
gluQuadricTexture equ <__imp_gluQuadricTexture>

externdef __imp_gluScaleImage:PPROC
gluScaleImage equ <__imp_gluScaleImage>

externdef __imp_gluSphere:PPROC
gluSphere equ <__imp_gluSphere>

externdef __imp_gluTessBeginContour:PPROC
gluTessBeginContour equ <__imp_gluTessBeginContour>

externdef __imp_gluTessBeginPolygon:PPROC
gluTessBeginPolygon equ <__imp_gluTessBeginPolygon>

externdef __imp_gluTessCallback:PPROC
gluTessCallback equ <__imp_gluTessCallback>

externdef __imp_gluTessEndContour:PPROC
gluTessEndContour equ <__imp_gluTessEndContour>

externdef __imp_gluTessEndPolygon:PPROC
gluTessEndPolygon equ <__imp_gluTessEndPolygon>

externdef __imp_gluTessNormal:PPROC
gluTessNormal equ <__imp_gluTessNormal>

externdef __imp_gluTessProperty:PPROC
gluTessProperty equ <__imp_gluTessProperty>

externdef __imp_gluTessVertex:PPROC
gluTessVertex equ <__imp_gluTessVertex>

externdef __imp_gluUnProject:PPROC
gluUnProject equ <__imp_gluUnProject>
