externdef __imp_BrowseForGPO:PPROC
BrowseForGPO equ <__imp_BrowseForGPO>

externdef __imp_CreateGPOLink:PPROC
CreateGPOLink equ <__imp_CreateGPOLink>

externdef __imp_DeleteAllGPOLinks:PPROC
DeleteAllGPOLinks equ <__imp_DeleteAllGPOLinks>

externdef __imp_DeleteGPOLink:PPROC
DeleteGPOLink equ <__imp_DeleteGPOLink>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_ExportRSoPData:PPROC
ExportRSoPData equ <__imp_ExportRSoPData>

externdef __imp_ImportRSoPData:PPROC
ImportRSoPData equ <__imp_ImportRSoPData>

externdef __imp_gpedit_ordinal100:PPROC
gpedit_ordinal100 equ <__imp_gpedit_ordinal100>

externdef __imp_gpedit_ordinal101:PPROC
gpedit_ordinal101 equ <__imp_gpedit_ordinal101>

externdef __imp_gpedit_ordinal102:PPROC
gpedit_ordinal102 equ <__imp_gpedit_ordinal102>

externdef __imp_gpedit_ordinal103:PPROC
gpedit_ordinal103 equ <__imp_gpedit_ordinal103>

externdef __imp_gpedit_ordinal104:PPROC
gpedit_ordinal104 equ <__imp_gpedit_ordinal104>
