externdef __imp_??0CCollection@@QEAA@XZ:PPROC
??0CCollection@@QEAA@XZ equ <__imp_??0CCollection@@QEAA@XZ>

externdef __imp_??0CFIFOString@@QEAA@XZ:PPROC
??0CFIFOString@@QEAA@XZ equ <__imp_??0CFIFOString@@QEAA@XZ>

externdef __imp_??0CFolder@@QEAA@XZ:PPROC
??0CFolder@@QEAA@XZ equ <__imp_??0CFolder@@QEAA@XZ>

externdef __imp_??0CLocation@@QEAA@XZ:PPROC
??0CLocation@@QEAA@XZ equ <__imp_??0CLocation@@QEAA@XZ>

externdef __imp_??0CPointerList@@QEAA@XZ:PPROC
??0CPointerList@@QEAA@XZ equ <__imp_??0CPointerList@@QEAA@XZ>

externdef __imp_??0CTitle@@QEAA@XZ:PPROC
??0CTitle@@QEAA@XZ equ <__imp_??0CTitle@@QEAA@XZ>

externdef __imp_??1CCollection@@QEAA@XZ:PPROC
??1CCollection@@QEAA@XZ equ <__imp_??1CCollection@@QEAA@XZ>

externdef __imp_??1CFIFOString@@QEAA@XZ:PPROC
??1CFIFOString@@QEAA@XZ equ <__imp_??1CFIFOString@@QEAA@XZ>

externdef __imp_??1CFolder@@QEAA@XZ:PPROC
??1CFolder@@QEAA@XZ equ <__imp_??1CFolder@@QEAA@XZ>

externdef __imp_??1CLocation@@QEAA@XZ:PPROC
??1CLocation@@QEAA@XZ equ <__imp_??1CLocation@@QEAA@XZ>

externdef __imp_??1CPointerList@@QEAA@XZ:PPROC
??1CPointerList@@QEAA@XZ equ <__imp_??1CPointerList@@QEAA@XZ>

externdef __imp_??1CTitle@@QEAA@XZ:PPROC
??1CTitle@@QEAA@XZ equ <__imp_??1CTitle@@QEAA@XZ>

externdef __imp_??4CCollection@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CCollection@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CCollection@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CFIFOString@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CFIFOString@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CFIFOString@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CFolder@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CFolder@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CFolder@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CLocation@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CLocation@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CLocation@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CPointerList@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CPointerList@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CPointerList@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CTitle@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CTitle@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CTitle@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_?Add@CPointerList@@QEAAPEAUListItem@@PEAX@Z:PPROC
?Add@CPointerList@@QEAAPEAUListItem@@PEAX@Z equ <__imp_?Add@CPointerList@@QEAAPEAUListItem@@PEAX@Z>

externdef __imp_?AddChildFolder@CFolder@@QEAAKPEAV1@@Z:PPROC
?AddChildFolder@CFolder@@QEAAKPEAV1@@Z equ <__imp_?AddChildFolder@CFolder@@QEAAKPEAV1@@Z>

externdef __imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBDKPEAKG@Z:PPROC
?AddChildFolder@CFolder@@QEAAPEAV1@PEBDKPEAKG@Z equ <__imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBDKPEAKG@Z>

externdef __imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBGKPEAKG@Z:PPROC
?AddChildFolder@CFolder@@QEAAPEAV1@PEBGKPEAKG@Z equ <__imp_?AddChildFolder@CFolder@@QEAAPEAV1@PEBGKPEAKG@Z>

externdef __imp_?AddCollection@CCollection@@QEAAPEAVCColList@@XZ:PPROC
?AddCollection@CCollection@@QEAAPEAVCColList@@XZ equ <__imp_?AddCollection@CCollection@@QEAAPEAVCColList@@XZ>

externdef __imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBDKPEAKG@Z:PPROC
?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBDKPEAKG@Z equ <__imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBDKPEAKG@Z>

externdef __imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBGKPEAKG@Z:PPROC
?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBGKPEAKG@Z equ <__imp_?AddFolder@CCollection@@QEAAPEAVCFolder@@PEBGKPEAKG@Z>

externdef __imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBD000PEAK@Z:PPROC
?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBD000PEAK@Z equ <__imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBD000PEAK@Z>

externdef __imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBG000PEAK@Z:PPROC
?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBG000PEAK@Z equ <__imp_?AddLocation@CCollection@@QEAAPEAVCLocation@@PEBG000PEAK@Z>

externdef __imp_?AddLocationHistory@CTitle@@QEAAKKPEBD00PEBVCLocation@@00H@Z:PPROC
?AddLocationHistory@CTitle@@QEAAKKPEBD00PEBVCLocation@@00H@Z equ <__imp_?AddLocationHistory@CTitle@@QEAAKKPEBD00PEBVCLocation@@00H@Z>

externdef __imp_?AddLocationHistory@CTitle@@QEAAKKPEBG00PEBVCLocation@@00H@Z:PPROC
?AddLocationHistory@CTitle@@QEAAKKPEBG00PEBVCLocation@@00H@Z equ <__imp_?AddLocationHistory@CTitle@@QEAAKKPEBG00PEBVCLocation@@00H@Z>

externdef __imp_?AddRef@CCollection@@QEAAXXZ:PPROC
?AddRef@CCollection@@QEAAXXZ equ <__imp_?AddRef@CCollection@@QEAAXXZ>

externdef __imp_?AddRefedTitle@CCollection@@AEAAKPEAVCFolder@@@Z:PPROC
?AddRefedTitle@CCollection@@AEAAKPEAVCFolder@@@Z equ <__imp_?AddRefedTitle@CCollection@@AEAAKPEAVCFolder@@@Z>

externdef __imp_?AddTail@CFIFOString@@QEAAKPEAD@Z:PPROC
?AddTail@CFIFOString@@QEAAKPEAD@Z equ <__imp_?AddTail@CFIFOString@@QEAAKPEAD@Z>

externdef __imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBD0000GIPEAVCLocation@@PEAKH0@Z:PPROC
?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBD0000GIPEAVCLocation@@PEAKH0@Z equ <__imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBD0000GIPEAVCLocation@@PEAKH0@Z>

externdef __imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBG0000GIPEAVCLocation@@PEAKH0@Z:PPROC
?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBG0000GIPEAVCLocation@@PEAKH0@Z equ <__imp_?AddTitle@CCollection@@QEAAPEAVCTitle@@PEBG0000GIPEAVCLocation@@PEAKH0@Z>

externdef __imp_?AllocCopyValue@CCollection@@AEAAKPEAVCParseXML@@PEADPEAPEAD@Z:PPROC
?AllocCopyValue@CCollection@@AEAAKPEAVCParseXML@@PEADPEAPEAD@Z equ <__imp_?AllocCopyValue@CCollection@@AEAAKPEAVCParseXML@@PEADPEAPEAD@Z>

externdef __imp_?AllocSetValue@@YAKPEBDPEAPEAD@Z:PPROC
?AllocSetValue@@YAKPEBDPEAPEAD@Z equ <__imp_?AllocSetValue@@YAKPEBDPEAPEAD@Z>

externdef __imp_?CheckTitleRef@CCollection@@AEAAKPEBDG@Z:PPROC
?CheckTitleRef@CCollection@@AEAAKPEBDG@Z equ <__imp_?CheckTitleRef@CCollection@@AEAAKPEBDG@Z>

externdef __imp_?CheckTitleRef@CCollection@@AEAAKPEBGG@Z:PPROC
?CheckTitleRef@CCollection@@AEAAKPEBGG@Z equ <__imp_?CheckTitleRef@CCollection@@AEAAKPEBGG@Z>

externdef __imp_?Close@CCollection@@QEAAKXZ:PPROC
?Close@CCollection@@QEAAKXZ equ <__imp_?Close@CCollection@@QEAAKXZ>

externdef __imp_?ConfirmTitles@CCollection@@QEAAXXZ:PPROC
?ConfirmTitles@CCollection@@QEAAXXZ equ <__imp_?ConfirmTitles@CCollection@@QEAAXXZ>

externdef __imp_?DecrementRefTitleCount@CCollection@@QEAAXXZ:PPROC
?DecrementRefTitleCount@CCollection@@QEAAXXZ equ <__imp_?DecrementRefTitleCount@CCollection@@QEAAXXZ>

externdef __imp_?DeleteChildren@CCollection@@AEAAXPEAPEAVCFolder@@@Z:PPROC
?DeleteChildren@CCollection@@AEAAXPEAPEAVCFolder@@@Z equ <__imp_?DeleteChildren@CCollection@@AEAAXPEAPEAVCFolder@@@Z>

externdef __imp_?DeleteFolder@CCollection@@QEAAKPEAVCFolder@@@Z:PPROC
?DeleteFolder@CCollection@@QEAAKPEAVCFolder@@@Z equ <__imp_?DeleteFolder@CCollection@@QEAAKPEAVCFolder@@@Z>

externdef __imp_?DeleteFolders@CCollection@@AEAAXPEAPEAVCFolder@@@Z:PPROC
?DeleteFolders@CCollection@@AEAAXPEAPEAVCFolder@@@Z equ <__imp_?DeleteFolders@CCollection@@AEAAXPEAPEAVCFolder@@@Z>

externdef __imp_?DeleteLocalFiles@CCollection@@AEAAXPEAULocationHistory@@PEAVCTitle@@@Z:PPROC
?DeleteLocalFiles@CCollection@@AEAAXPEAULocationHistory@@PEAVCTitle@@@Z equ <__imp_?DeleteLocalFiles@CCollection@@AEAAXPEAULocationHistory@@PEAVCTitle@@@Z>

externdef __imp_?DeleteLocation@CCollection@@AEAAKPEAVCLocation@@@Z:PPROC
?DeleteLocation@CCollection@@AEAAKPEAVCLocation@@@Z equ <__imp_?DeleteLocation@CCollection@@AEAAKPEAVCLocation@@@Z>

externdef __imp_?DeleteTitle@CCollection@@AEAAKPEAVCTitle@@@Z:PPROC
?DeleteTitle@CCollection@@AEAAKPEAVCTitle@@@Z equ <__imp_?DeleteTitle@CCollection@@AEAAKPEAVCTitle@@@Z>

externdef __imp_?Dirty@CCollection@@QEAAXXZ:PPROC
?Dirty@CCollection@@QEAAXXZ equ <__imp_?Dirty@CCollection@@QEAAXXZ>

externdef __imp_?FindCollection@CCollection@@QEAAPEAVCColList@@PEAD@Z:PPROC
?FindCollection@CCollection@@QEAAPEAVCColList@@PEAD@Z equ <__imp_?FindCollection@CCollection@@QEAAPEAVCColList@@PEAD@Z>

externdef __imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBDPEAI@Z:PPROC
?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBDPEAI@Z equ <__imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBDPEAI@Z>

externdef __imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBGPEAI@Z:PPROC
?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBGPEAI@Z equ <__imp_?FindLocation@CCollection@@QEAAPEAVCLocation@@PEBGPEAI@Z>

externdef __imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBDG@Z:PPROC
?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBDG@Z equ <__imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBDG@Z>

externdef __imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBGG@Z:PPROC
?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBGG@Z equ <__imp_?FindTitle@CCollection@@QEAAPEAVCTitle@@PEBGG@Z>

externdef __imp_?First@CPointerList@@QEAAPEAUListItem@@XZ:PPROC
?First@CPointerList@@QEAAPEAUListItem@@XZ equ <__imp_?First@CPointerList@@QEAAPEAUListItem@@XZ>

externdef __imp_?FirstLocation@CCollection@@QEAAPEAVCLocation@@XZ:PPROC
?FirstLocation@CCollection@@QEAAPEAVCLocation@@XZ equ <__imp_?FirstLocation@CCollection@@QEAAPEAVCLocation@@XZ>

externdef __imp_?GetColNo@CCollection@@QEAAKXZ:PPROC
?GetColNo@CCollection@@QEAAKXZ equ <__imp_?GetColNo@CCollection@@QEAAKXZ>

externdef __imp_?GetCollectionFileName@CCollection@@QEAAPEBDXZ:PPROC
?GetCollectionFileName@CCollection@@QEAAPEBDXZ equ <__imp_?GetCollectionFileName@CCollection@@QEAAPEBDXZ>

externdef __imp_?GetCollectionFileNameW@CCollection@@QEAAPEBGXZ:PPROC
?GetCollectionFileNameW@CCollection@@QEAAPEBGXZ equ <__imp_?GetCollectionFileNameW@CCollection@@QEAAPEBGXZ>

externdef __imp_?GetFindMergedCHMS@CCollection@@QEAAHXZ:PPROC
?GetFindMergedCHMS@CCollection@@QEAAHXZ equ <__imp_?GetFindMergedCHMS@CCollection@@QEAAHXZ>

externdef __imp_?GetFirstChildFolder@CFolder@@QEAAPEAV1@XZ:PPROC
?GetFirstChildFolder@CFolder@@QEAAPEAV1@XZ equ <__imp_?GetFirstChildFolder@CFolder@@QEAAPEAV1@XZ>

externdef __imp_?GetFirstTitle@CCollection@@QEAAPEAVCTitle@@XZ:PPROC
?GetFirstTitle@CCollection@@QEAAPEAVCTitle@@XZ equ <__imp_?GetFirstTitle@CCollection@@QEAAPEAVCTitle@@XZ>

externdef __imp_?GetId@CLocation@@QEBAPEADXZ:PPROC
?GetId@CLocation@@QEBAPEADXZ equ <__imp_?GetId@CLocation@@QEBAPEADXZ>

externdef __imp_?GetId@CTitle@@QEAAPEADXZ:PPROC
?GetId@CTitle@@QEAAPEADXZ equ <__imp_?GetId@CTitle@@QEAAPEADXZ>

externdef __imp_?GetIdW@CLocation@@QEAAPEBGXZ:PPROC
?GetIdW@CLocation@@QEAAPEBGXZ equ <__imp_?GetIdW@CLocation@@QEAAPEBGXZ>

externdef __imp_?GetIdW@CTitle@@QEAAPEBGXZ:PPROC
?GetIdW@CTitle@@QEAAPEBGXZ equ <__imp_?GetIdW@CTitle@@QEAAPEBGXZ>

externdef __imp_?GetLangId@CCollection@@QEAAGPEBD@Z:PPROC
?GetLangId@CCollection@@QEAAGPEBD@Z equ <__imp_?GetLangId@CCollection@@QEAAGPEBD@Z>

externdef __imp_?GetLangId@CCollection@@QEAAGPEBG@Z:PPROC
?GetLangId@CCollection@@QEAAGPEBG@Z equ <__imp_?GetLangId@CCollection@@QEAAGPEBG@Z>

externdef __imp_?GetLanguage@CFolder@@QEAAGXZ:PPROC
?GetLanguage@CFolder@@QEAAGXZ equ <__imp_?GetLanguage@CFolder@@QEAAGXZ>

externdef __imp_?GetLanguage@CTitle@@QEAAGXZ:PPROC
?GetLanguage@CTitle@@QEAAGXZ equ <__imp_?GetLanguage@CTitle@@QEAAGXZ>

externdef __imp_?GetLocation@CTitle@@QEAAPEAULocationHistory@@K@Z:PPROC
?GetLocation@CTitle@@QEAAPEAULocationHistory@@K@Z equ <__imp_?GetLocation@CTitle@@QEAAPEAULocationHistory@@K@Z>

externdef __imp_?GetMasterCHM@CCollection@@QEAAHPEAPEADPEAG@Z:PPROC
?GetMasterCHM@CCollection@@QEAAHPEAPEADPEAG@Z equ <__imp_?GetMasterCHM@CCollection@@QEAAHPEAPEADPEAG@Z>

externdef __imp_?GetMasterCHM@CCollection@@QEAAHPEAPEAGPEAG@Z:PPROC
?GetMasterCHM@CCollection@@QEAAHPEAPEAGPEAG@Z equ <__imp_?GetMasterCHM@CCollection@@QEAAHPEAPEAGPEAG@Z>

externdef __imp_?GetNextFolder@CFolder@@QEAAPEAV1@XZ:PPROC
?GetNextFolder@CFolder@@QEAAPEAV1@XZ equ <__imp_?GetNextFolder@CFolder@@QEAAPEAV1@XZ>

externdef __imp_?GetNextLocation@CLocation@@QEAAPEAV1@XZ:PPROC
?GetNextLocation@CLocation@@QEAAPEAV1@XZ equ <__imp_?GetNextLocation@CLocation@@QEAAPEAV1@XZ>

externdef __imp_?GetNextTitle@CTitle@@QEAAPEAV1@XZ:PPROC
?GetNextTitle@CTitle@@QEAAPEAV1@XZ equ <__imp_?GetNextTitle@CTitle@@QEAAPEAV1@XZ>

externdef __imp_?GetOrder@CFolder@@QEAAKXZ:PPROC
?GetOrder@CFolder@@QEAAKXZ equ <__imp_?GetOrder@CFolder@@QEAAKXZ>

externdef __imp_?GetParent@CFolder@@QEAAPEAV1@XZ:PPROC
?GetParent@CFolder@@QEAAPEAV1@XZ equ <__imp_?GetParent@CFolder@@QEAAPEAV1@XZ>

externdef __imp_?GetPath@CLocation@@QEAAPEADXZ:PPROC
?GetPath@CLocation@@QEAAPEADXZ equ <__imp_?GetPath@CLocation@@QEAAPEADXZ>

externdef __imp_?GetPathW@CLocation@@QEAAPEBGXZ:PPROC
?GetPathW@CLocation@@QEAAPEBGXZ equ <__imp_?GetPathW@CLocation@@QEAAPEBGXZ>

externdef __imp_?GetRefTitleCount@CCollection@@QEAAKXZ:PPROC
?GetRefTitleCount@CCollection@@QEAAKXZ equ <__imp_?GetRefTitleCount@CCollection@@QEAAKXZ>

externdef __imp_?GetRootFolder@CCollection@@QEAAPEAVCFolder@@XZ:PPROC
?GetRootFolder@CCollection@@QEAAPEAVCFolder@@XZ equ <__imp_?GetRootFolder@CCollection@@QEAAPEAVCFolder@@XZ>

externdef __imp_?GetSampleLocation@CCollection@@QEAAPEADXZ:PPROC
?GetSampleLocation@CCollection@@QEAAPEADXZ equ <__imp_?GetSampleLocation@CCollection@@QEAAPEADXZ>

externdef __imp_?GetSampleLocationW@CCollection@@QEAAPEBGXZ:PPROC
?GetSampleLocationW@CCollection@@QEAAPEBGXZ equ <__imp_?GetSampleLocationW@CCollection@@QEAAPEBGXZ>

externdef __imp_?GetTail@CFIFOString@@QEAAKPEAPEAD@Z:PPROC
?GetTail@CFIFOString@@QEAAKPEAPEAD@Z equ <__imp_?GetTail@CFIFOString@@QEAAKPEAPEAD@Z>

externdef __imp_?GetTitle@CFolder@@QEAAPEADXZ:PPROC
?GetTitle@CFolder@@QEAAPEADXZ equ <__imp_?GetTitle@CFolder@@QEAAPEADXZ>

externdef __imp_?GetTitle@CLocation@@QEAAPEADXZ:PPROC
?GetTitle@CLocation@@QEAAPEADXZ equ <__imp_?GetTitle@CLocation@@QEAAPEADXZ>

externdef __imp_?GetTitleW@CFolder@@QEAAPEBGXZ:PPROC
?GetTitleW@CFolder@@QEAAPEBGXZ equ <__imp_?GetTitleW@CFolder@@QEAAPEBGXZ>

externdef __imp_?GetTitleW@CLocation@@QEAAPEBGXZ:PPROC
?GetTitleW@CLocation@@QEAAPEBGXZ equ <__imp_?GetTitleW@CLocation@@QEAAPEBGXZ>

externdef __imp_?GetVersion@CCollection@@QEAAKXZ:PPROC
?GetVersion@CCollection@@QEAAKXZ equ <__imp_?GetVersion@CCollection@@QEAAKXZ>

externdef __imp_?GetVisableRootFolder@CCollection@@QEAAPEAVCFolder@@XZ:PPROC
?GetVisableRootFolder@CCollection@@QEAAPEAVCFolder@@XZ equ <__imp_?GetVisableRootFolder@CCollection@@QEAAPEAVCFolder@@XZ>

externdef __imp_?GetVolume@CLocation@@QEAAPEADXZ:PPROC
?GetVolume@CLocation@@QEAAPEADXZ equ <__imp_?GetVolume@CLocation@@QEAAPEADXZ>

externdef __imp_?GetVolumeW@CLocation@@QEAAPEBGXZ:PPROC
?GetVolumeW@CLocation@@QEAAPEBGXZ equ <__imp_?GetVolumeW@CLocation@@QEAAPEBGXZ>

externdef __imp_?HandleCollection@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PPROC
?HandleCollection@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z equ <__imp_?HandleCollection@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>

externdef __imp_?HandleCollectionEntry@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PPROC
?HandleCollectionEntry@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z equ <__imp_?HandleCollectionEntry@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>

externdef __imp_?HandleFolder@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PPROC
?HandleFolder@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z equ <__imp_?HandleFolder@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>

externdef __imp_?HandleLocation@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PPROC
?HandleLocation@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z equ <__imp_?HandleLocation@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>

externdef __imp_?HandleTitle@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z:PPROC
?HandleTitle@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z equ <__imp_?HandleTitle@CCollection@@AEAAKPEAVCParseXML@@PEAD@Z>

externdef __imp_?IncrementRefTitleCount@CCollection@@QEAAXXZ:PPROC
?IncrementRefTitleCount@CCollection@@QEAAXXZ equ <__imp_?IncrementRefTitleCount@CCollection@@QEAAXXZ>

externdef __imp_?IsDirty@CCollection@@QEAAHXZ:PPROC
?IsDirty@CCollection@@QEAAHXZ equ <__imp_?IsDirty@CCollection@@QEAAHXZ>

externdef __imp_?MergeKeywords@CCollection@@QEAAHPEAD@Z:PPROC
?MergeKeywords@CCollection@@QEAAHPEAD@Z equ <__imp_?MergeKeywords@CCollection@@QEAAHPEAD@Z>

externdef __imp_?MergeKeywords@CCollection@@QEAAHPEAG@Z:PPROC
?MergeKeywords@CCollection@@QEAAHPEAG@Z equ <__imp_?MergeKeywords@CCollection@@QEAAHPEAG@Z>

externdef __imp_?NewLocation@CCollection@@AEAAPEAVCLocation@@XZ:PPROC
?NewLocation@CCollection@@AEAAPEAVCLocation@@XZ equ <__imp_?NewLocation@CCollection@@AEAAPEAVCLocation@@XZ>

externdef __imp_?NewLocationHistory@CTitle@@QEAAPEAULocationHistory@@XZ:PPROC
?NewLocationHistory@CTitle@@QEAAPEAULocationHistory@@XZ equ <__imp_?NewLocationHistory@CTitle@@QEAAPEAULocationHistory@@XZ>

externdef __imp_?NewTitle@CCollection@@AEAAPEAVCTitle@@XZ:PPROC
?NewTitle@CCollection@@AEAAPEAVCTitle@@XZ equ <__imp_?NewTitle@CCollection@@AEAAPEAVCTitle@@XZ>

externdef __imp_?Next@CPointerList@@QEAAPEAUListItem@@PEAU2@@Z:PPROC
?Next@CPointerList@@QEAAPEAUListItem@@PEAU2@@Z equ <__imp_?Next@CPointerList@@QEAAPEAUListItem@@PEAU2@@Z>

externdef __imp_?Open@CCollection@@QEAAKPEBD@Z:PPROC
?Open@CCollection@@QEAAKPEBD@Z equ <__imp_?Open@CCollection@@QEAAKPEBD@Z>

externdef __imp_?Open@CCollection@@QEAAKPEBG@Z:PPROC
?Open@CCollection@@QEAAKPEBG@Z equ <__imp_?Open@CCollection@@QEAAKPEBG@Z>

externdef __imp_?ParseFile@CCollection@@AEAAKPEBD@Z:PPROC
?ParseFile@CCollection@@AEAAKPEBD@Z equ <__imp_?ParseFile@CCollection@@AEAAKPEBD@Z>

externdef __imp_?Release@CCollection@@AEAAKXZ:PPROC
?Release@CCollection@@AEAAKXZ equ <__imp_?Release@CCollection@@AEAAKXZ>

externdef __imp_?RemoveAll@CFIFOString@@QEAAXXZ:PPROC
?RemoveAll@CFIFOString@@QEAAXXZ equ <__imp_?RemoveAll@CFIFOString@@QEAAXXZ>

externdef __imp_?RemoveAll@CPointerList@@QEAAXXZ:PPROC
?RemoveAll@CPointerList@@QEAAXXZ equ <__imp_?RemoveAll@CPointerList@@QEAAXXZ>

externdef __imp_?RemoveCollection@CCollection@@QEAAKH@Z:PPROC
?RemoveCollection@CCollection@@QEAAKH@Z equ <__imp_?RemoveCollection@CCollection@@QEAAKH@Z>

externdef __imp_?RemoveCollectionEntry@CCollection@@QEAAXPEAD@Z:PPROC
?RemoveCollectionEntry@CCollection@@QEAAXPEAD@Z equ <__imp_?RemoveCollectionEntry@CCollection@@QEAAXPEAD@Z>

externdef __imp_?Save@CCollection@@QEAAKXZ:PPROC
?Save@CCollection@@QEAAKXZ equ <__imp_?Save@CCollection@@QEAAKXZ>

externdef __imp_?SetExTitlePtr@CFolder@@QEAAXPEAVCExTitle@@@Z:PPROC
?SetExTitlePtr@CFolder@@QEAAXPEAVCExTitle@@@Z equ <__imp_?SetExTitlePtr@CFolder@@QEAAXPEAVCExTitle@@@Z>

externdef __imp_?SetFindMergedCHMS@CCollection@@QEAAXH@Z:PPROC
?SetFindMergedCHMS@CCollection@@QEAAXH@Z equ <__imp_?SetFindMergedCHMS@CCollection@@QEAAXH@Z>

externdef __imp_?SetFirstChildFolder@CFolder@@QEAAXPEAV1@@Z:PPROC
?SetFirstChildFolder@CFolder@@QEAAXPEAV1@@Z equ <__imp_?SetFirstChildFolder@CFolder@@QEAAXPEAV1@@Z>

externdef __imp_?SetId@CLocation@@QEAAXPEBD@Z:PPROC
?SetId@CLocation@@QEAAXPEBD@Z equ <__imp_?SetId@CLocation@@QEAAXPEBD@Z>

externdef __imp_?SetId@CLocation@@QEAAXPEBG@Z:PPROC
?SetId@CLocation@@QEAAXPEBG@Z equ <__imp_?SetId@CLocation@@QEAAXPEBG@Z>

externdef __imp_?SetId@CTitle@@QEAAXPEBD@Z:PPROC
?SetId@CTitle@@QEAAXPEBD@Z equ <__imp_?SetId@CTitle@@QEAAXPEBD@Z>

externdef __imp_?SetId@CTitle@@QEAAXPEBG@Z:PPROC
?SetId@CTitle@@QEAAXPEBG@Z equ <__imp_?SetId@CTitle@@QEAAXPEBG@Z>

externdef __imp_?SetLanguage@CFolder@@QEAAXG@Z:PPROC
?SetLanguage@CFolder@@QEAAXG@Z equ <__imp_?SetLanguage@CFolder@@QEAAXG@Z>

externdef __imp_?SetLanguage@CTitle@@QEAAXG@Z:PPROC
?SetLanguage@CTitle@@QEAAXG@Z equ <__imp_?SetLanguage@CTitle@@QEAAXG@Z>

externdef __imp_?SetMasterCHM@CCollection@@QEAAXPEBDG@Z:PPROC
?SetMasterCHM@CCollection@@QEAAXPEBDG@Z equ <__imp_?SetMasterCHM@CCollection@@QEAAXPEBDG@Z>

externdef __imp_?SetMasterCHM@CCollection@@QEAAXPEBGG@Z:PPROC
?SetMasterCHM@CCollection@@QEAAXPEBGG@Z equ <__imp_?SetMasterCHM@CCollection@@QEAAXPEBGG@Z>

externdef __imp_?SetNextFolder@CFolder@@QEAAXPEAV1@@Z:PPROC
?SetNextFolder@CFolder@@QEAAXPEAV1@@Z equ <__imp_?SetNextFolder@CFolder@@QEAAXPEAV1@@Z>

externdef __imp_?SetNextLocation@CLocation@@QEAAXPEAV1@@Z:PPROC
?SetNextLocation@CLocation@@QEAAXPEAV1@@Z equ <__imp_?SetNextLocation@CLocation@@QEAAXPEAV1@@Z>

externdef __imp_?SetNextTitle@CTitle@@QEAAXPEAV1@@Z:PPROC
?SetNextTitle@CTitle@@QEAAXPEAV1@@Z equ <__imp_?SetNextTitle@CTitle@@QEAAXPEAV1@@Z>

externdef __imp_?SetOrder@CFolder@@QEAAXK@Z:PPROC
?SetOrder@CFolder@@QEAAXK@Z equ <__imp_?SetOrder@CFolder@@QEAAXK@Z>

externdef __imp_?SetParent@CFolder@@QEAAXPEAV1@@Z:PPROC
?SetParent@CFolder@@QEAAXPEAV1@@Z equ <__imp_?SetParent@CFolder@@QEAAXPEAV1@@Z>

externdef __imp_?SetPath@CLocation@@QEAAXPEBD@Z:PPROC
?SetPath@CLocation@@QEAAXPEBD@Z equ <__imp_?SetPath@CLocation@@QEAAXPEBD@Z>

externdef __imp_?SetPath@CLocation@@QEAAXPEBG@Z:PPROC
?SetPath@CLocation@@QEAAXPEBG@Z equ <__imp_?SetPath@CLocation@@QEAAXPEBG@Z>

externdef __imp_?SetSampleLocation@CCollection@@QEAAXPEBD@Z:PPROC
?SetSampleLocation@CCollection@@QEAAXPEBD@Z equ <__imp_?SetSampleLocation@CCollection@@QEAAXPEBD@Z>

externdef __imp_?SetSampleLocation@CCollection@@QEAAXPEBG@Z:PPROC
?SetSampleLocation@CCollection@@QEAAXPEBG@Z equ <__imp_?SetSampleLocation@CCollection@@QEAAXPEBG@Z>

externdef __imp_?SetTitle@CFolder@@QEAAXPEBD@Z:PPROC
?SetTitle@CFolder@@QEAAXPEBD@Z equ <__imp_?SetTitle@CFolder@@QEAAXPEBD@Z>

externdef __imp_?SetTitle@CFolder@@QEAAXPEBG@Z:PPROC
?SetTitle@CFolder@@QEAAXPEBG@Z equ <__imp_?SetTitle@CFolder@@QEAAXPEBG@Z>

externdef __imp_?SetTitle@CLocation@@QEAAXPEBD@Z:PPROC
?SetTitle@CLocation@@QEAAXPEBD@Z equ <__imp_?SetTitle@CLocation@@QEAAXPEBD@Z>

externdef __imp_?SetTitle@CLocation@@QEAAXPEBG@Z:PPROC
?SetTitle@CLocation@@QEAAXPEBG@Z equ <__imp_?SetTitle@CLocation@@QEAAXPEBG@Z>

externdef __imp_?SetVersion@CCollection@@QEAAXK@Z:PPROC
?SetVersion@CCollection@@QEAAXK@Z equ <__imp_?SetVersion@CCollection@@QEAAXK@Z>

externdef __imp_?SetVolume@CLocation@@QEAAXPEBD@Z:PPROC
?SetVolume@CLocation@@QEAAXPEBD@Z equ <__imp_?SetVolume@CLocation@@QEAAXPEBD@Z>

externdef __imp_?SetVolume@CLocation@@QEAAXPEBG@Z:PPROC
?SetVolume@CLocation@@QEAAXPEBG@Z equ <__imp_?SetVolume@CLocation@@QEAAXPEBG@Z>

externdef __imp_?WriteFolder@CCollection@@AEAAHPEAPEAVCFolder@@@Z:PPROC
?WriteFolder@CCollection@@AEAAHPEAPEAVCFolder@@@Z equ <__imp_?WriteFolder@CCollection@@AEAAHPEAPEAVCFolder@@@Z>

externdef __imp_?WriteFolders@CCollection@@AEAAHPEAPEAVCFolder@@@Z:PPROC
?WriteFolders@CCollection@@AEAAHPEAPEAVCFolder@@@Z equ <__imp_?WriteFolders@CCollection@@AEAAHPEAPEAVCFolder@@@Z>

externdef __imp_?bIsVisable@CFolder@@QEAAHXZ:PPROC
?bIsVisable@CFolder@@QEAAHXZ equ <__imp_?bIsVisable@CFolder@@QEAAHXZ>

externdef __imp_?wssResetNextColNum@CCollection@@AEAAXXZ:PPROC
?wssResetNextColNum@CCollection@@AEAAXXZ equ <__imp_?wssResetNextColNum@CCollection@@AEAAXXZ>
