externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_InitInstance:PPROC
InitInstance equ <__imp_InitInstance>

externdef __imp_MessageLoop:PPROC
MessageLoop equ <__imp_MessageLoop>

externdef __imp_sessQuerySysFileHdl:PPROC
sessQuerySysFileHdl equ <__imp_sessQuerySysFileHdl>

externdef __imp_sessQueryTranslateHdl:PPROC
sessQueryTranslateHdl equ <__imp_sessQueryTranslateHdl>

externdef __imp_sfGetSessionItem:PPROC
sfGetSessionItem equ <__imp_sfGetSessionItem>

externdef __imp_sfPutSessionItem:PPROC
sfPutSessionItem equ <__imp_sfPutSessionItem>
