externdef __imp_AllocateAttributes:PPROC
AllocateAttributes equ <__imp_AllocateAttributes>

externdef __imp_ConfigureIas:PPROC
ConfigureIas equ <__imp_ConfigureIas>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DoRequest:PPROC
DoRequest equ <__imp_DoRequest>

externdef __imp_FreeAttributes:PPROC
FreeAttributes equ <__imp_FreeAttributes>

externdef __imp_InitializeIas:PPROC
InitializeIas equ <__imp_InitializeIas>

externdef __imp_MemAllocIas:PPROC
MemAllocIas equ <__imp_MemAllocIas>

externdef __imp_MemFreeIas:PPROC
MemFreeIas equ <__imp_MemFreeIas>

externdef __imp_MemReallocIas:PPROC
MemReallocIas equ <__imp_MemReallocIas>

externdef __imp_ShutdownIas:PPROC
ShutdownIas equ <__imp_ShutdownIas>
