externdef __imp_?initialize@VSAFilter@@QEAAJXZ:PPROC
?initialize@VSAFilter@@QEAAJXZ equ <__imp_?initialize@VSAFilter@@QEAAJXZ>

externdef __imp_?radiusFromIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z:PPROC
?radiusFromIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z equ <__imp_?radiusFromIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z>

externdef __imp_?radiusToIAS@VSAFilter@@QEBAJPEAEKAEAVIASAttributeVector@IASTL@@@Z:PPROC
?radiusToIAS@VSAFilter@@QEBAJPEAEKAEAVIASAttributeVector@IASTL@@@Z equ <__imp_?radiusToIAS@VSAFilter@@QEBAJPEAEKAEAVIASAttributeVector@IASTL@@@Z>

externdef __imp_?radiusToIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z:PPROC
?radiusToIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z equ <__imp_?radiusToIAS@VSAFilter@@QEBAJPEAUIAttributesRaw@@@Z>

externdef __imp_?shutdown@VSAFilter@@QEAAJXZ:PPROC
?shutdown@VSAFilter@@QEAAJXZ equ <__imp_?shutdown@VSAFilter@@QEAAJXZ>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
