externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_IASAdler32:PPROC
IASAdler32 equ <__imp_IASAdler32>

externdef __imp_IASAllocateUniqueID:PPROC
IASAllocateUniqueID equ <__imp_IASAllocateUniqueID>

externdef __imp_IASGetDictionary:PPROC
IASGetDictionary equ <__imp_IASGetDictionary>

externdef __imp_IASGetHostByName:PPROC
IASGetHostByName equ <__imp_IASGetHostByName>

externdef __imp_IASGetLocalDictionary:PPROC
IASGetLocalDictionary equ <__imp_IASGetLocalDictionary>

externdef __imp_IASGetProductLimits:PPROC
IASGetProductLimits equ <__imp_IASGetProductLimits>

externdef __imp_IASGlobalLock:PPROC
IASGlobalLock equ <__imp_IASGlobalLock>

externdef __imp_IASGlobalUnlock:PPROC
IASGlobalUnlock equ <__imp_IASGlobalUnlock>

externdef __imp_IASInitialize:PPROC
IASInitialize equ <__imp_IASInitialize>

externdef __imp_IASRadiusCrypt:PPROC
IASRadiusCrypt equ <__imp_IASRadiusCrypt>

externdef __imp_IASRegisterComponent:PPROC
IASRegisterComponent equ <__imp_IASRegisterComponent>

externdef __imp_IASReportEvent:PPROC
IASReportEvent equ <__imp_IASReportEvent>

externdef __imp_IASReportLicenseViolation:PPROC
IASReportLicenseViolation equ <__imp_IASReportLicenseViolation>

externdef __imp_IASRequestThread:PPROC
IASRequestThread equ <__imp_IASRequestThread>

externdef __imp_IASSetMaxNumberOfThreads:PPROC
IASSetMaxNumberOfThreads equ <__imp_IASSetMaxNumberOfThreads>

externdef __imp_IASSetMaxThreadIdle:PPROC
IASSetMaxThreadIdle equ <__imp_IASSetMaxThreadIdle>

externdef __imp_IASUninitialize:PPROC
IASUninitialize equ <__imp_IASUninitialize>

externdef __imp_IASVariantChangeType:PPROC
IASVariantChangeType equ <__imp_IASVariantChangeType>
