externdef __imp_IcmpCloseHandle:PPROC
IcmpCloseHandle equ <__imp_IcmpCloseHandle>

externdef __imp_IcmpCreateFile:PPROC
IcmpCreateFile equ <__imp_IcmpCreateFile>

externdef __imp_IcmpParseReplies:PPROC
IcmpParseReplies equ <__imp_IcmpParseReplies>

externdef __imp_IcmpSendEcho2:PPROC
IcmpSendEcho2 equ <__imp_IcmpSendEcho2>

externdef __imp_IcmpSendEcho:PPROC
IcmpSendEcho equ <__imp_IcmpSendEcho>

externdef __imp_do_echo_rep:PPROC
do_echo_rep equ <__imp_do_echo_rep>

externdef __imp_do_echo_req:PPROC
do_echo_req equ <__imp_do_echo_req>

externdef __imp_register_icmp:PPROC
register_icmp equ <__imp_register_icmp>
