externdef __imp_AddADMItemA:PPROC
AddADMItemA equ <__imp_AddADMItemA>
  IFNDEF __UNICODE__
    AddADMItem equ <__imp_AddADMItemA>
  ENDIF

externdef __imp_AddADMItemW:PPROC
AddADMItemW equ <__imp_AddADMItemW>
  IFDEF __UNICODE__
    AddADMItem equ <__imp_AddADMItemW>
  ENDIF

externdef __imp_BToolbar_Edit:PPROC
BToolbar_Edit equ <__imp_BToolbar_Edit>

externdef __imp_BToolbar_InitA:PPROC
BToolbar_InitA equ <__imp_BToolbar_InitA>
  IFNDEF __UNICODE__
    BToolbar_Init equ <__imp_BToolbar_InitA>
  ENDIF

externdef __imp_BToolbar_InitW:PPROC
BToolbar_InitW equ <__imp_BToolbar_InitW>
  IFDEF __UNICODE__
    BToolbar_Init equ <__imp_BToolbar_InitW>
  ENDIF

externdef __imp_BToolbar_Remove:PPROC
BToolbar_Remove equ <__imp_BToolbar_Remove>

externdef __imp_BToolbar_SaveA:PPROC
BToolbar_SaveA equ <__imp_BToolbar_SaveA>
  IFNDEF __UNICODE__
    BToolbar_Save equ <__imp_BToolbar_SaveA>
  ENDIF

externdef __imp_BToolbar_SaveW:PPROC
BToolbar_SaveW equ <__imp_BToolbar_SaveW>
  IFDEF __UNICODE__
    BToolbar_Save equ <__imp_BToolbar_SaveW>
  ENDIF

externdef __imp_BrowseForFileA:PPROC
BrowseForFileA equ <__imp_BrowseForFileA>
  IFNDEF __UNICODE__
    BrowseForFile equ <__imp_BrowseForFileA>
  ENDIF

externdef __imp_BrowseForFileW:PPROC
BrowseForFileW equ <__imp_BrowseForFileW>
  IFDEF __UNICODE__
    BrowseForFile equ <__imp_BrowseForFileW>
  ENDIF

externdef __imp_BrowseForFolderA:PPROC
BrowseForFolderA equ <__imp_BrowseForFolderA>
  IFNDEF __UNICODE__
    BrowseForFolder equ <__imp_BrowseForFolderA>
  ENDIF

externdef __imp_BrowseForFolderW:PPROC
BrowseForFolderW equ <__imp_BrowseForFolderW>
  IFDEF __UNICODE__
    BrowseForFolder equ <__imp_BrowseForFolderW>
  ENDIF

externdef __imp_BuildPalette:PPROC
BuildPalette equ <__imp_BuildPalette>

externdef __imp_CanDeleteADM:PPROC
CanDeleteADM equ <__imp_CanDeleteADM>

externdef __imp_CheckField:PPROC
CheckField equ <__imp_CheckField>

externdef __imp_CheckForDupKeys:PPROC
CheckForDupKeys equ <__imp_CheckForDupKeys>

externdef __imp_CheckVerA:PPROC
CheckVerA equ <__imp_CheckVerA>
  IFNDEF __UNICODE__
    CheckVer equ <__imp_CheckVerA>
  ENDIF

externdef __imp_CheckVerW:PPROC
CheckVerW equ <__imp_CheckVerW>
  IFDEF __UNICODE__
    CheckVer equ <__imp_CheckVerW>
  ENDIF

externdef __imp_CopyAnimBmpA:PPROC
CopyAnimBmpA equ <__imp_CopyAnimBmpA>
  IFNDEF __UNICODE__
    CopyAnimBmp equ <__imp_CopyAnimBmpA>
  ENDIF

externdef __imp_CopyAnimBmpW:PPROC
CopyAnimBmpW equ <__imp_CopyAnimBmpW>
  IFDEF __UNICODE__
    CopyAnimBmp equ <__imp_CopyAnimBmpW>
  ENDIF

externdef __imp_CopyHttFileA:PPROC
CopyHttFileA equ <__imp_CopyHttFileA>
  IFNDEF __UNICODE__
    CopyHttFile equ <__imp_CopyHttFileA>
  ENDIF

externdef __imp_CopyHttFileW:PPROC
CopyHttFileW equ <__imp_CopyHttFileW>
  IFDEF __UNICODE__
    CopyHttFile equ <__imp_CopyHttFileW>
  ENDIF

externdef __imp_CopyLogoBmpA:PPROC
CopyLogoBmpA equ <__imp_CopyLogoBmpA>
  IFNDEF __UNICODE__
    CopyLogoBmp equ <__imp_CopyLogoBmpA>
  ENDIF

externdef __imp_CopyLogoBmpW:PPROC
CopyLogoBmpW equ <__imp_CopyLogoBmpW>
  IFDEF __UNICODE__
    CopyLogoBmp equ <__imp_CopyLogoBmpW>
  ENDIF

externdef __imp_CopyWallPaperA:PPROC
CopyWallPaperA equ <__imp_CopyWallPaperA>
  IFNDEF __UNICODE__
    CopyWallPaper equ <__imp_CopyWallPaperA>
  ENDIF

externdef __imp_CopyWallPaperW:PPROC
CopyWallPaperW equ <__imp_CopyWallPaperW>
  IFDEF __UNICODE__
    CopyWallPaper equ <__imp_CopyWallPaperW>
  ENDIF

externdef __imp_CreateADMWindow:PPROC
CreateADMWindow equ <__imp_CreateADMWindow>

externdef __imp_DeleteADMItemA:PPROC
DeleteADMItemA equ <__imp_DeleteADMItemA>
  IFNDEF __UNICODE__
    DeleteADMItem equ <__imp_DeleteADMItemA>
  ENDIF

externdef __imp_DeleteADMItemW:PPROC
DeleteADMItemW equ <__imp_DeleteADMItemW>
  IFDEF __UNICODE__
    DeleteADMItem equ <__imp_DeleteADMItemW>
  ENDIF

externdef __imp_DeleteADMItemsA:PPROC
DeleteADMItemsA equ <__imp_DeleteADMItemsA>
  IFNDEF __UNICODE__
    DeleteADMItems equ <__imp_DeleteADMItemsA>
  ENDIF

externdef __imp_DeleteADMItemsW:PPROC
DeleteADMItemsW equ <__imp_DeleteADMItemsW>
  IFDEF __UNICODE__
    DeleteADMItems equ <__imp_DeleteADMItemsW>
  ENDIF

externdef __imp_DeleteFavoriteA:PPROC
DeleteFavoriteA equ <__imp_DeleteFavoriteA>
  IFNDEF __UNICODE__
    DeleteFavorite equ <__imp_DeleteFavoriteA>
  ENDIF

externdef __imp_DeleteFavoriteW:PPROC
DeleteFavoriteW equ <__imp_DeleteFavoriteW>
  IFDEF __UNICODE__
    DeleteFavorite equ <__imp_DeleteFavoriteW>
  ENDIF

externdef __imp_DestroyADMWindow:PPROC
DestroyADMWindow equ <__imp_DestroyADMWindow>

externdef __imp_DisplayADMItem:PPROC
DisplayADMItem equ <__imp_DisplayADMItem>

externdef __imp_DoReboot:PPROC
DoReboot equ <__imp_DoReboot>

externdef __imp_EncodeSignatureA:PPROC
EncodeSignatureA equ <__imp_EncodeSignatureA>
  IFNDEF __UNICODE__
    EncodeSignature equ <__imp_EncodeSignatureA>
  ENDIF

externdef __imp_EncodeSignatureW:PPROC
EncodeSignatureW equ <__imp_EncodeSignatureW>
  IFDEF __UNICODE__
    EncodeSignature equ <__imp_EncodeSignatureW>
  ENDIF

externdef __imp_ErrorMessageBox:PPROC
ErrorMessageBox equ <__imp_ErrorMessageBox>

externdef __imp_ExportFavoritesA:PPROC
ExportFavoritesA equ <__imp_ExportFavoritesA>
  IFNDEF __UNICODE__
    ExportFavorites equ <__imp_ExportFavoritesA>
  ENDIF

externdef __imp_ExportFavoritesW:PPROC
ExportFavoritesW equ <__imp_ExportFavoritesW>
  IFDEF __UNICODE__
    ExportFavorites equ <__imp_ExportFavoritesW>
  ENDIF

externdef __imp_ExportQuickLinksA:PPROC
ExportQuickLinksA equ <__imp_ExportQuickLinksA>
  IFNDEF __UNICODE__
    ExportQuickLinks equ <__imp_ExportQuickLinksA>
  ENDIF

externdef __imp_ExportQuickLinksW:PPROC
ExportQuickLinksW equ <__imp_ExportQuickLinksW>
  IFDEF __UNICODE__
    ExportQuickLinks equ <__imp_ExportQuickLinksW>
  ENDIF

externdef __imp_ExportRegKey2InfA:PPROC
ExportRegKey2InfA equ <__imp_ExportRegKey2InfA>
  IFNDEF __UNICODE__
    ExportRegKey2Inf equ <__imp_ExportRegKey2InfA>
  ENDIF

externdef __imp_ExportRegKey2InfW:PPROC
ExportRegKey2InfW equ <__imp_ExportRegKey2InfW>
  IFDEF __UNICODE__
    ExportRegKey2Inf equ <__imp_ExportRegKey2InfW>
  ENDIF

externdef __imp_ExportRegTree2InfA:PPROC
ExportRegTree2InfA equ <__imp_ExportRegTree2InfA>
  IFNDEF __UNICODE__
    ExportRegTree2Inf equ <__imp_ExportRegTree2InfA>
  ENDIF

externdef __imp_ExportRegTree2InfW:PPROC
ExportRegTree2InfW equ <__imp_ExportRegTree2InfW>
  IFDEF __UNICODE__
    ExportRegTree2Inf equ <__imp_ExportRegTree2InfW>
  ENDIF

externdef __imp_ExportRegValue2InfA:PPROC
ExportRegValue2InfA equ <__imp_ExportRegValue2InfA>
  IFNDEF __UNICODE__
    ExportRegValue2Inf equ <__imp_ExportRegValue2InfA>
  ENDIF

externdef __imp_ExportRegValue2InfW:PPROC
ExportRegValue2InfW equ <__imp_ExportRegValue2InfW>
  IFDEF __UNICODE__
    ExportRegValue2Inf equ <__imp_ExportRegValue2InfW>
  ENDIF

externdef __imp_GenerateNewVersionStrA:PPROC
GenerateNewVersionStrA equ <__imp_GenerateNewVersionStrA>
  IFNDEF __UNICODE__
    GenerateNewVersionStr equ <__imp_GenerateNewVersionStrA>
  ENDIF

externdef __imp_GenerateNewVersionStrW:PPROC
GenerateNewVersionStrW equ <__imp_GenerateNewVersionStrW>
  IFDEF __UNICODE__
    GenerateNewVersionStr equ <__imp_GenerateNewVersionStrW>
  ENDIF

externdef __imp_GetAdmFileListA:PPROC
GetAdmFileListA equ <__imp_GetAdmFileListA>
  IFNDEF __UNICODE__
    GetAdmFileList equ <__imp_GetAdmFileListA>
  ENDIF

externdef __imp_GetAdmFileListW:PPROC
GetAdmFileListW equ <__imp_GetAdmFileListW>
  IFDEF __UNICODE__
    GetAdmFileList equ <__imp_GetAdmFileListW>
  ENDIF

externdef __imp_GetAdmWindowHandle:PPROC
GetAdmWindowHandle equ <__imp_GetAdmWindowHandle>

externdef __imp_GetBaseFileNameA:PPROC
GetBaseFileNameA equ <__imp_GetBaseFileNameA>
  IFNDEF __UNICODE__
    GetBaseFileName equ <__imp_GetBaseFileNameA>
  ENDIF

externdef __imp_GetBaseFileNameW:PPROC
GetBaseFileNameW equ <__imp_GetBaseFileNameW>
  IFDEF __UNICODE__
    GetBaseFileName equ <__imp_GetBaseFileNameW>
  ENDIF

externdef __imp_GetFavoriteUrlA:PPROC
GetFavoriteUrlA equ <__imp_GetFavoriteUrlA>
  IFNDEF __UNICODE__
    GetFavoriteUrl equ <__imp_GetFavoriteUrlA>
  ENDIF

externdef __imp_GetFavoriteUrlW:PPROC
GetFavoriteUrlW equ <__imp_GetFavoriteUrlW>
  IFDEF __UNICODE__
    GetFavoriteUrl equ <__imp_GetFavoriteUrlW>
  ENDIF

externdef __imp_GetFavoritesInfoTipA:PPROC
GetFavoritesInfoTipA equ <__imp_GetFavoritesInfoTipA>
  IFNDEF __UNICODE__
    GetFavoritesInfoTip equ <__imp_GetFavoritesInfoTipA>
  ENDIF

externdef __imp_GetFavoritesInfoTipW:PPROC
GetFavoritesInfoTipW equ <__imp_GetFavoritesInfoTipW>
  IFDEF __UNICODE__
    GetFavoritesInfoTip equ <__imp_GetFavoritesInfoTipW>
  ENDIF

externdef __imp_GetFavoritesMaxNumber:PPROC
GetFavoritesMaxNumber equ <__imp_GetFavoritesMaxNumber>

externdef __imp_GetFavoritesNumber:PPROC
GetFavoritesNumber equ <__imp_GetFavoritesNumber>

externdef __imp_GetProxyDlgA:PPROC
GetProxyDlgA equ <__imp_GetProxyDlgA>
  IFNDEF __UNICODE__
    GetProxyDlg equ <__imp_GetProxyDlgA>
  ENDIF

externdef __imp_GetProxyDlgW:PPROC
GetProxyDlgW equ <__imp_GetProxyDlgW>
  IFDEF __UNICODE__
    GetProxyDlg equ <__imp_GetProxyDlgW>
  ENDIF

externdef __imp_ImportADMFileA:PPROC
ImportADMFileA equ <__imp_ImportADMFileA>
  IFNDEF __UNICODE__
    ImportADMFile equ <__imp_ImportADMFileA>
  ENDIF

externdef __imp_ImportADMFileW:PPROC
ImportADMFileW equ <__imp_ImportADMFileW>
  IFDEF __UNICODE__
    ImportADMFile equ <__imp_ImportADMFileW>
  ENDIF

externdef __imp_ImportADTInfoA:PPROC
ImportADTInfoA equ <__imp_ImportADTInfoA>
  IFNDEF __UNICODE__
    ImportADTInfo equ <__imp_ImportADTInfoA>
  ENDIF

externdef __imp_ImportADTInfoW:PPROC
ImportADTInfoW equ <__imp_ImportADTInfoW>
  IFDEF __UNICODE__
    ImportADTInfo equ <__imp_ImportADTInfoW>
  ENDIF

externdef __imp_ImportAuthCodeA:PPROC
ImportAuthCodeA equ <__imp_ImportAuthCodeA>
  IFNDEF __UNICODE__
    ImportAuthCode equ <__imp_ImportAuthCodeA>
  ENDIF

externdef __imp_ImportAuthCodeW:PPROC
ImportAuthCodeW equ <__imp_ImportAuthCodeW>
  IFDEF __UNICODE__
    ImportAuthCode equ <__imp_ImportAuthCodeW>
  ENDIF

externdef __imp_ImportConnectSetA:PPROC
ImportConnectSetA equ <__imp_ImportConnectSetA>
  IFNDEF __UNICODE__
    ImportConnectSet equ <__imp_ImportConnectSetA>
  ENDIF

externdef __imp_ImportConnectSetW:PPROC
ImportConnectSetW equ <__imp_ImportConnectSetW>
  IFDEF __UNICODE__
    ImportConnectSet equ <__imp_ImportConnectSetW>
  ENDIF

externdef __imp_ImportFavoritesA:PPROC
ImportFavoritesA equ <__imp_ImportFavoritesA>
  IFNDEF __UNICODE__
    ImportFavorites equ <__imp_ImportFavoritesA>
  ENDIF

externdef __imp_ImportFavoritesCmdA:PPROC
ImportFavoritesCmdA equ <__imp_ImportFavoritesCmdA>
  IFNDEF __UNICODE__
    ImportFavoritesCmd equ <__imp_ImportFavoritesCmdA>
  ENDIF

externdef __imp_ImportFavoritesCmdW:PPROC
ImportFavoritesCmdW equ <__imp_ImportFavoritesCmdW>
  IFDEF __UNICODE__
    ImportFavoritesCmd equ <__imp_ImportFavoritesCmdW>
  ENDIF

externdef __imp_ImportFavoritesW:PPROC
ImportFavoritesW equ <__imp_ImportFavoritesW>
  IFDEF __UNICODE__
    ImportFavorites equ <__imp_ImportFavoritesW>
  ENDIF

externdef __imp_ImportLDAPBitmapA:PPROC
ImportLDAPBitmapA equ <__imp_ImportLDAPBitmapA>
  IFNDEF __UNICODE__
    ImportLDAPBitmap equ <__imp_ImportLDAPBitmapA>
  ENDIF

externdef __imp_ImportLDAPBitmapW:PPROC
ImportLDAPBitmapW equ <__imp_ImportLDAPBitmapW>
  IFDEF __UNICODE__
    ImportLDAPBitmap equ <__imp_ImportLDAPBitmapW>
  ENDIF

externdef __imp_ImportOEInfoA:PPROC
ImportOEInfoA equ <__imp_ImportOEInfoA>
  IFNDEF __UNICODE__
    ImportOEInfo equ <__imp_ImportOEInfoA>
  ENDIF

externdef __imp_ImportOEInfoW:PPROC
ImportOEInfoW equ <__imp_ImportOEInfoW>
  IFDEF __UNICODE__
    ImportOEInfo equ <__imp_ImportOEInfoW>
  ENDIF

externdef __imp_ImportProgramsA:PPROC
ImportProgramsA equ <__imp_ImportProgramsA>
  IFNDEF __UNICODE__
    ImportPrograms equ <__imp_ImportProgramsA>
  ENDIF

externdef __imp_ImportProgramsW:PPROC
ImportProgramsW equ <__imp_ImportProgramsW>
  IFDEF __UNICODE__
    ImportPrograms equ <__imp_ImportProgramsW>
  ENDIF

externdef __imp_ImportQuickLinksA:PPROC
ImportQuickLinksA equ <__imp_ImportQuickLinksA>
  IFNDEF __UNICODE__
    ImportQuickLinks equ <__imp_ImportQuickLinksA>
  ENDIF

externdef __imp_ImportQuickLinksW:PPROC
ImportQuickLinksW equ <__imp_ImportQuickLinksW>
  IFDEF __UNICODE__
    ImportQuickLinks equ <__imp_ImportQuickLinksW>
  ENDIF

externdef __imp_ImportRatingsA:PPROC
ImportRatingsA equ <__imp_ImportRatingsA>
  IFNDEF __UNICODE__
    ImportRatings equ <__imp_ImportRatingsA>
  ENDIF

externdef __imp_ImportRatingsW:PPROC
ImportRatingsW equ <__imp_ImportRatingsW>
  IFDEF __UNICODE__
    ImportRatings equ <__imp_ImportRatingsW>
  ENDIF

externdef __imp_ImportSiteCertA:PPROC
ImportSiteCertA equ <__imp_ImportSiteCertA>
  IFNDEF __UNICODE__
    ImportSiteCert equ <__imp_ImportSiteCertA>
  ENDIF

externdef __imp_ImportSiteCertW:PPROC
ImportSiteCertW equ <__imp_ImportSiteCertW>
  IFDEF __UNICODE__
    ImportSiteCert equ <__imp_ImportSiteCertW>
  ENDIF

externdef __imp_ImportToolbarInfoA:PPROC
ImportToolbarInfoA equ <__imp_ImportToolbarInfoA>
  IFNDEF __UNICODE__
    ImportToolbarInfo equ <__imp_ImportToolbarInfoA>
  ENDIF

externdef __imp_ImportToolbarInfoW:PPROC
ImportToolbarInfoW equ <__imp_ImportToolbarInfoW>
  IFDEF __UNICODE__
    ImportToolbarInfo equ <__imp_ImportToolbarInfoW>
  ENDIF

externdef __imp_ImportZonesA:PPROC
ImportZonesA equ <__imp_ImportZonesA>
  IFNDEF __UNICODE__
    ImportZones equ <__imp_ImportZonesA>
  ENDIF

externdef __imp_ImportZonesW:PPROC
ImportZonesW equ <__imp_ImportZonesW>
  IFDEF __UNICODE__
    ImportZones equ <__imp_ImportZonesW>
  ENDIF

externdef __imp_InitializeStartSearchA:PPROC
InitializeStartSearchA equ <__imp_InitializeStartSearchA>
  IFNDEF __UNICODE__
    InitializeStartSearch equ <__imp_InitializeStartSearchA>
  ENDIF

externdef __imp_InitializeStartSearchW:PPROC
InitializeStartSearchW equ <__imp_InitializeStartSearchW>
  IFDEF __UNICODE__
    InitializeStartSearch equ <__imp_InitializeStartSearchW>
  ENDIF

externdef __imp_IsADMFileVisibleA:PPROC
IsADMFileVisibleA equ <__imp_IsADMFileVisibleA>
  IFNDEF __UNICODE__
    IsADMFileVisible equ <__imp_IsADMFileVisibleA>
  ENDIF

externdef __imp_IsADMFileVisibleW:PPROC
IsADMFileVisibleW equ <__imp_IsADMFileVisibleW>
  IFDEF __UNICODE__
    IsADMFileVisible equ <__imp_IsADMFileVisibleW>
  ENDIF

externdef __imp_IsAnimBitmapFileValidA:PPROC
IsAnimBitmapFileValidA equ <__imp_IsAnimBitmapFileValidA>
  IFNDEF __UNICODE__
    IsAnimBitmapFileValid equ <__imp_IsAnimBitmapFileValidA>
  ENDIF

externdef __imp_IsAnimBitmapFileValidW:PPROC
IsAnimBitmapFileValidW equ <__imp_IsAnimBitmapFileValidW>
  IFDEF __UNICODE__
    IsAnimBitmapFileValid equ <__imp_IsAnimBitmapFileValidW>
  ENDIF

externdef __imp_IsBitmapFileValidA:PPROC
IsBitmapFileValidA equ <__imp_IsBitmapFileValidA>
  IFNDEF __UNICODE__
    IsBitmapFileValid equ <__imp_IsBitmapFileValidA>
  ENDIF

externdef __imp_IsBitmapFileValidW:PPROC
IsBitmapFileValidW equ <__imp_IsBitmapFileValidW>
  IFDEF __UNICODE__
    IsBitmapFileValid equ <__imp_IsBitmapFileValidW>
  ENDIF

externdef __imp_IsFavoriteItem:PPROC
IsFavoriteItem equ <__imp_IsFavoriteItem>

externdef __imp_LoadADMFilesA:PPROC
LoadADMFilesA equ <__imp_LoadADMFilesA>
  IFNDEF __UNICODE__
    LoadADMFiles equ <__imp_LoadADMFilesA>
  ENDIF

externdef __imp_LoadADMFilesW:PPROC
LoadADMFilesW equ <__imp_LoadADMFilesW>
  IFDEF __UNICODE__
    LoadADMFiles equ <__imp_LoadADMFilesW>
  ENDIF

externdef __imp_MigrateFavoritesA:PPROC
MigrateFavoritesA equ <__imp_MigrateFavoritesA>
  IFNDEF __UNICODE__
    MigrateFavorites equ <__imp_MigrateFavoritesA>
  ENDIF

externdef __imp_MigrateFavoritesW:PPROC
MigrateFavoritesW equ <__imp_MigrateFavoritesW>
  IFDEF __UNICODE__
    MigrateFavorites equ <__imp_MigrateFavoritesW>
  ENDIF

externdef __imp_MigrateToOldFavoritesA:PPROC
MigrateToOldFavoritesA equ <__imp_MigrateToOldFavoritesA>
  IFNDEF __UNICODE__
    MigrateToOldFavorites equ <__imp_MigrateToOldFavoritesA>
  ENDIF

externdef __imp_MigrateToOldFavoritesW:PPROC
MigrateToOldFavoritesW equ <__imp_MigrateToOldFavoritesW>
  IFDEF __UNICODE__
    MigrateToOldFavorites equ <__imp_MigrateToOldFavoritesW>
  ENDIF

externdef __imp_ModifyAuthCode:PPROC
ModifyAuthCode equ <__imp_ModifyAuthCode>

externdef __imp_ModifyFavoriteA:PPROC
ModifyFavoriteA equ <__imp_ModifyFavoriteA>
  IFNDEF __UNICODE__
    ModifyFavorite equ <__imp_ModifyFavoriteA>
  ENDIF

externdef __imp_ModifyFavoriteW:PPROC
ModifyFavoriteW equ <__imp_ModifyFavoriteW>
  IFDEF __UNICODE__
    ModifyFavorite equ <__imp_ModifyFavoriteW>
  ENDIF

externdef __imp_ModifyRatings:PPROC
ModifyRatings equ <__imp_ModifyRatings>

externdef __imp_ModifySiteCert:PPROC
ModifySiteCert equ <__imp_ModifySiteCert>

externdef __imp_ModifyZones:PPROC
ModifyZones equ <__imp_ModifyZones>

externdef __imp_MoveADMWindow:PPROC
MoveADMWindow equ <__imp_MoveADMWindow>

externdef __imp_MoveDownFavorite:PPROC
MoveDownFavorite equ <__imp_MoveDownFavorite>

externdef __imp_MoveUpFavorite:PPROC
MoveUpFavorite equ <__imp_MoveUpFavorite>

externdef __imp_NewFolder:PPROC
NewFolder equ <__imp_NewFolder>

externdef __imp_NewUrlA:PPROC
NewUrlA equ <__imp_NewUrlA>
  IFNDEF __UNICODE__
    NewUrl equ <__imp_NewUrlA>
  ENDIF

externdef __imp_NewUrlW:PPROC
NewUrlW equ <__imp_NewUrlW>
  IFDEF __UNICODE__
    NewUrl equ <__imp_NewUrlW>
  ENDIF

externdef __imp_ProcessFavSelChange:PPROC
ProcessFavSelChange equ <__imp_ProcessFavSelChange>

externdef __imp_ResetAdmFilesA:PPROC
ResetAdmFilesA equ <__imp_ResetAdmFilesA>
  IFNDEF __UNICODE__
    ResetAdmFiles equ <__imp_ResetAdmFilesA>
  ENDIF

externdef __imp_ResetAdmFilesW:PPROC
ResetAdmFilesW equ <__imp_ResetAdmFilesW>
  IFDEF __UNICODE__
    ResetAdmFiles equ <__imp_ResetAdmFilesW>
  ENDIF

externdef __imp_SaveADMItem:PPROC
SaveADMItem equ <__imp_SaveADMItem>

externdef __imp_SaveAdmFilesA:PPROC
SaveAdmFilesA equ <__imp_SaveAdmFilesA>
  IFNDEF __UNICODE__
    SaveAdmFiles equ <__imp_SaveAdmFilesA>
  ENDIF

externdef __imp_SaveAdmFilesW:PPROC
SaveAdmFilesW equ <__imp_SaveAdmFilesW>
  IFDEF __UNICODE__
    SaveAdmFiles equ <__imp_SaveAdmFilesW>
  ENDIF

externdef __imp_SaveStartSearchA:PPROC
SaveStartSearchA equ <__imp_SaveStartSearchA>
  IFNDEF __UNICODE__
    SaveStartSearch equ <__imp_SaveStartSearchA>
  ENDIF

externdef __imp_SaveStartSearchW:PPROC
SaveStartSearchW equ <__imp_SaveStartSearchW>
  IFDEF __UNICODE__
    SaveStartSearch equ <__imp_SaveStartSearchW>
  ENDIF

externdef __imp_SelectADMItem:PPROC
SelectADMItem equ <__imp_SelectADMItem>

externdef __imp_SetADMWindowTextA:PPROC
SetADMWindowTextA equ <__imp_SetADMWindowTextA>
  IFNDEF __UNICODE__
    SetADMWindowText equ <__imp_SetADMWindowTextA>
  ENDIF

externdef __imp_SetADMWindowTextW:PPROC
SetADMWindowTextW equ <__imp_SetADMWindowTextW>
  IFDEF __UNICODE__
    SetADMWindowText equ <__imp_SetADMWindowTextW>
  ENDIF

externdef __imp_SetLBWidth:PPROC
SetLBWidth equ <__imp_SetLBWidth>

externdef __imp_SetOrClearVersionInfoA:PPROC
SetOrClearVersionInfoA equ <__imp_SetOrClearVersionInfoA>
  IFNDEF __UNICODE__
    SetOrClearVersionInfo equ <__imp_SetOrClearVersionInfoA>
  ENDIF

externdef __imp_SetOrClearVersionInfoW:PPROC
SetOrClearVersionInfoW equ <__imp_SetOrClearVersionInfoW>
  IFDEF __UNICODE__
    SetOrClearVersionInfo equ <__imp_SetOrClearVersionInfoW>
  ENDIF

externdef __imp_SetProxyDlgA:PPROC
SetProxyDlgA equ <__imp_SetProxyDlgA>
  IFNDEF __UNICODE__
    SetProxyDlg equ <__imp_SetProxyDlgA>
  ENDIF

externdef __imp_SetProxyDlgW:PPROC
SetProxyDlgW equ <__imp_SetProxyDlgW>
  IFDEF __UNICODE__
    SetProxyDlg equ <__imp_SetProxyDlgW>
  ENDIF

externdef __imp_ShowADMWindow:PPROC
ShowADMWindow equ <__imp_ShowADMWindow>

externdef __imp_ShowBitmapA:PPROC
ShowBitmapA equ <__imp_ShowBitmapA>
  IFNDEF __UNICODE__
    ShowBitmap equ <__imp_ShowBitmapA>
  ENDIF

externdef __imp_ShowBitmapW:PPROC
ShowBitmapW equ <__imp_ShowBitmapW>
  IFDEF __UNICODE__
    ShowBitmap equ <__imp_ShowBitmapW>
  ENDIF

externdef __imp_ShowDeskCpl:PPROC
ShowDeskCpl equ <__imp_ShowDeskCpl>

externdef __imp_ShowInetcpl:PPROC
ShowInetcpl equ <__imp_ShowInetcpl>

externdef __imp_SignFileA:PPROC
SignFileA equ <__imp_SignFileA>
  IFNDEF __UNICODE__
    SignFile equ <__imp_SignFileA>
  ENDIF

externdef __imp_SignFileW:PPROC
SignFileW equ <__imp_SignFileW>
  IFDEF __UNICODE__
    SignFile equ <__imp_SignFileW>
  ENDIF

externdef __imp_TestURLA:PPROC
TestURLA equ <__imp_TestURLA>
  IFNDEF __UNICODE__
    TestURL equ <__imp_TestURLA>
  ENDIF

externdef __imp_TestURLW:PPROC
TestURLW equ <__imp_TestURLW>
  IFDEF __UNICODE__
    TestURL equ <__imp_TestURLW>
  ENDIF
