externdef __imp_BrandCleanInstallStubs:PPROC
BrandCleanInstallStubs equ <__imp_BrandCleanInstallStubs>

externdef __imp_BrandExternal:PPROC
BrandExternal equ <__imp_BrandExternal>

externdef __imp_BrandICW2:PPROC
BrandICW2 equ <__imp_BrandICW2>

externdef __imp_BrandICW:PPROC
BrandICW equ <__imp_BrandICW>
  IFDEF __UNICODE__
    BrandIC equ <__imp_BrandICW>
  ENDIF

externdef __imp_BrandIE4:PPROC
BrandIE4 equ <__imp_BrandIE4>

externdef __imp_BrandInfAndOutlookExpress:PPROC
BrandInfAndOutlookExpress equ <__imp_BrandInfAndOutlookExpress>

externdef __imp_BrandInternetExplorer:PPROC
BrandInternetExplorer equ <__imp_BrandInternetExplorer>

externdef __imp_BrandIntra:PPROC
BrandIntra equ <__imp_BrandIntra>

externdef __imp_BrandMe:PPROC
BrandMe equ <__imp_BrandMe>

externdef __imp_Clear:PPROC
Clear equ <__imp_Clear>

externdef __imp_CloseRASConnections:PPROC
CloseRASConnections equ <__imp_CloseRASConnections>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_GenerateGroupPolicy:PPROC
GenerateGroupPolicy equ <__imp_GenerateGroupPolicy>

externdef __imp_InternetInitializeAutoProxyDll:PPROC
InternetInitializeAutoProxyDll equ <__imp_InternetInitializeAutoProxyDll>

externdef __imp_ProcessGroupPolicy:PPROC
ProcessGroupPolicy equ <__imp_ProcessGroupPolicy>

externdef __imp_ProcessGroupPolicyEx:PPROC
ProcessGroupPolicyEx equ <__imp_ProcessGroupPolicyEx>

externdef __imp_ProcessGroupPolicyForZoneMap:PPROC
ProcessGroupPolicyForZoneMap equ <__imp_ProcessGroupPolicyForZoneMap>
