externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_FixIE:PPROC
FixIE equ <__imp_FixIE>

externdef __imp_IEHardenAdmin:PPROC
IEHardenAdmin equ <__imp_IEHardenAdmin>

externdef __imp_IEHardenAdminNow:PPROC
IEHardenAdminNow equ <__imp_IEHardenAdminNow>

externdef __imp_IEHardenMachineNow:PPROC
IEHardenMachineNow equ <__imp_IEHardenMachineNow>

externdef __imp_IEHardenUser:PPROC
IEHardenUser equ <__imp_IEHardenUser>

externdef __imp_SetFirstHomepage:PPROC
SetFirstHomepage equ <__imp_SetFirstHomepage>
