externdef __imp_ComputeInvCMAP:PPROC
ComputeInvCMAP equ <__imp_ComputeInvCMAP>

externdef __imp_CreateDDrawSurfaceOnDIB:PPROC
CreateDDrawSurfaceOnDIB equ <__imp_CreateDDrawSurfaceOnDIB>

externdef __imp_CreateMIMEMap:PPROC
CreateMIMEMap equ <__imp_CreateMIMEMap>

externdef __imp_DecodeImage:PPROC
DecodeImage equ <__imp_DecodeImage>

externdef __imp_DitherTo8:PPROC
DitherTo8 equ <__imp_DitherTo8>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_GetMaxMIMEIDBytes:PPROC
GetMaxMIMEIDBytes equ <__imp_GetMaxMIMEIDBytes>

externdef __imp_IdentifyMIMEType:PPROC
IdentifyMIMEType equ <__imp_IdentifyMIMEType>

externdef __imp_SniffStream:PPROC
SniffStream equ <__imp_SniffStream>
