externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_IIGetAppElem:PPROC
IIGetAppElem equ <__imp_IIGetAppElem>

externdef __imp_IIGetFM:PPROC
IIGetFM equ <__imp_IIGetFM>

externdef __imp_IIapp:PPROC
IIapp equ <__imp_IIapp>

externdef __imp_IIapp_mem:PPROC
IIapp_mem equ <__imp_IIapp_mem>

externdef __imp_IIbuf:PPROC
IIbuf equ <__imp_IIbuf>

externdef __imp_IIbuf_mem:PPROC
IIbuf_mem equ <__imp_IIbuf_mem>

externdef __imp_IIdb:PPROC
IIdb equ <__imp_IIdb>

externdef __imp_IIdb_mem:PPROC
IIdb_mem equ <__imp_IIdb_mem>

externdef __imp_IIdiagoff:PPROC
IIdiagoff equ <__imp_IIdiagoff>

externdef __imp_IIdiagon:PPROC
IIdiagon equ <__imp_IIdiagon>

externdef __imp_IIword:PPROC
IIword equ <__imp_IIword>

externdef __imp_NTFMClose:PPROC
NTFMClose equ <__imp_NTFMClose>

externdef __imp_NTFMCompare:PPROC
NTFMCompare equ <__imp_NTFMCompare>

externdef __imp_NTFMCopy:PPROC
NTFMCopy equ <__imp_NTFMCopy>

externdef __imp_NTFMCreate:PPROC
NTFMCreate equ <__imp_NTFMCreate>

externdef __imp_NTFMDelete:PPROC
NTFMDelete equ <__imp_NTFMDelete>

externdef __imp_NTFMDestruct:PPROC
NTFMDestruct equ <__imp_NTFMDestruct>

externdef __imp_NTFMFlushMapping:PPROC
NTFMFlushMapping equ <__imp_NTFMFlushMapping>

externdef __imp_NTFMGetDirtyBit:PPROC
NTFMGetDirtyBit equ <__imp_NTFMGetDirtyBit>

externdef __imp_NTFMGetLength:PPROC
NTFMGetLength equ <__imp_NTFMGetLength>

externdef __imp_NTFMGetMapHandle:PPROC
NTFMGetMapHandle equ <__imp_NTFMGetMapHandle>

externdef __imp_NTFMGetMapping:PPROC
NTFMGetMapping equ <__imp_NTFMGetMapping>

externdef __imp_NTFMGetName:PPROC
NTFMGetName equ <__imp_NTFMGetName>

externdef __imp_NTFMGetPosition:PPROC
NTFMGetPosition equ <__imp_NTFMGetPosition>

externdef __imp_NTFMGetStatus:PPROC
NTFMGetStatus equ <__imp_NTFMGetStatus>

externdef __imp_NTFMLockMapping:PPROC
NTFMLockMapping equ <__imp_NTFMLockMapping>

externdef __imp_NTFMOpen:PPROC
NTFMOpen equ <__imp_NTFMOpen>

externdef __imp_NTFMRead:PPROC
NTFMRead equ <__imp_NTFMRead>

externdef __imp_NTFMReleaseMapHandle:PPROC
NTFMReleaseMapHandle equ <__imp_NTFMReleaseMapHandle>

externdef __imp_NTFMSeek:PPROC
NTFMSeek equ <__imp_NTFMSeek>

externdef __imp_NTFMSetDirtyBit:PPROC
NTFMSetDirtyBit equ <__imp_NTFMSetDirtyBit>

externdef __imp_NTFMSetLength:PPROC
NTFMSetLength equ <__imp_NTFMSetLength>

externdef __imp_NTFMSetMapping:PPROC
NTFMSetMapping equ <__imp_NTFMSetMapping>

externdef __imp_NTFMSetMutexProc:PPROC
NTFMSetMutexProc equ <__imp_NTFMSetMutexProc>

externdef __imp_NTFMSetName:PPROC
NTFMSetName equ <__imp_NTFMSetName>

externdef __imp_NTFMUnlockMapping:PPROC
NTFMUnlockMapping equ <__imp_NTFMUnlockMapping>

externdef __imp_NTFMWrite:PPROC
NTFMWrite equ <__imp_NTFMWrite>
