externdef __imp_CPlApplet:PPROC
CPlApplet equ <__imp_CPlApplet>

externdef __imp_input_ordinal101:PPROC
input_ordinal101 equ <__imp_input_ordinal101>

externdef __imp_input_ordinal102:PPROC
input_ordinal102 equ <__imp_input_ordinal102>

externdef __imp_input_ordinal103:PPROC
input_ordinal103 equ <__imp_input_ordinal103>

externdef __imp_input_ordinal104:PPROC
input_ordinal104 equ <__imp_input_ordinal104>
