externdef __imp_CheckForVersionConflict:PPROC
CheckForVersionConflict equ <__imp_CheckForVersionConflict>

externdef __imp_CheckTrust:PPROC
CheckTrust equ <__imp_CheckTrust>

externdef __imp_CheckTrustEx:PPROC
CheckTrustEx equ <__imp_CheckTrustEx>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DownloadFile:PPROC
DownloadFile equ <__imp_DownloadFile>

externdef __imp_GetICifFileFromFile:PPROC
GetICifFileFromFile equ <__imp_GetICifFileFromFile>

externdef __imp_GetICifRWFileFromFile:PPROC
GetICifRWFileFromFile equ <__imp_GetICifRWFileFromFile>

externdef __imp_PurgeDownloadDirectory:PPROC
PurgeDownloadDirectory equ <__imp_PurgeDownloadDirectory>
