externdef __imp_JetAddColumn:PPROC
JetAddColumn equ <__imp_JetAddColumn>

externdef __imp_JetAttachDatabase:PPROC
JetAttachDatabase equ <__imp_JetAttachDatabase>

externdef __imp_JetBackup:PPROC
JetBackup equ <__imp_JetBackup>

externdef __imp_JetBeginExternalBackup:PPROC
JetBeginExternalBackup equ <__imp_JetBeginExternalBackup>

externdef __imp_JetBeginSession:PPROC
JetBeginSession equ <__imp_JetBeginSession>

externdef __imp_JetBeginTransaction:PPROC
JetBeginTransaction equ <__imp_JetBeginTransaction>

externdef __imp_JetCloseDatabase:PPROC
JetCloseDatabase equ <__imp_JetCloseDatabase>

externdef __imp_JetCloseFile:PPROC
JetCloseFile equ <__imp_JetCloseFile>

externdef __imp_JetCloseTable:PPROC
JetCloseTable equ <__imp_JetCloseTable>

externdef __imp_JetCommitTransaction:PPROC
JetCommitTransaction equ <__imp_JetCommitTransaction>

externdef __imp_JetCompact:PPROC
JetCompact equ <__imp_JetCompact>

externdef __imp_JetComputeStats:PPROC
JetComputeStats equ <__imp_JetComputeStats>

externdef __imp_JetCreateDatabase:PPROC
JetCreateDatabase equ <__imp_JetCreateDatabase>

externdef __imp_JetCreateIndex:PPROC
JetCreateIndex equ <__imp_JetCreateIndex>

externdef __imp_JetCreateLink:PPROC
JetCreateLink equ <__imp_JetCreateLink>

externdef __imp_JetCreateQuery:PPROC
JetCreateQuery equ <__imp_JetCreateQuery>

externdef __imp_JetCreateTable:PPROC
JetCreateTable equ <__imp_JetCreateTable>

externdef __imp_JetCreateTableColumnIndex:PPROC
JetCreateTableColumnIndex equ <__imp_JetCreateTableColumnIndex>

externdef __imp_JetDBUtilities:PPROC
JetDBUtilities equ <__imp_JetDBUtilities>

externdef __imp_JetDelete:PPROC
JetDelete equ <__imp_JetDelete>

externdef __imp_JetDeleteColumn:PPROC
JetDeleteColumn equ <__imp_JetDeleteColumn>

externdef __imp_JetDeleteIndex:PPROC
JetDeleteIndex equ <__imp_JetDeleteIndex>

externdef __imp_JetDeleteTable:PPROC
JetDeleteTable equ <__imp_JetDeleteTable>

externdef __imp_JetDetachDatabase:PPROC
JetDetachDatabase equ <__imp_JetDetachDatabase>

externdef __imp_JetDupCursor:PPROC
JetDupCursor equ <__imp_JetDupCursor>

externdef __imp_JetDupSession:PPROC
JetDupSession equ <__imp_JetDupSession>

externdef __imp_JetEndExternalBackup:PPROC
JetEndExternalBackup equ <__imp_JetEndExternalBackup>

externdef __imp_JetEndSession:PPROC
JetEndSession equ <__imp_JetEndSession>

externdef __imp_JetExecuteSql:PPROC
JetExecuteSql equ <__imp_JetExecuteSql>

externdef __imp_JetExternalRestore:PPROC
JetExternalRestore equ <__imp_JetExternalRestore>

externdef __imp_JetGetAttachInfo:PPROC
JetGetAttachInfo equ <__imp_JetGetAttachInfo>

externdef __imp_JetGetBookmark:PPROC
JetGetBookmark equ <__imp_JetGetBookmark>

externdef __imp_JetGetChecksum:PPROC
JetGetChecksum equ <__imp_JetGetChecksum>

externdef __imp_JetGetColumnInfo:PPROC
JetGetColumnInfo equ <__imp_JetGetColumnInfo>

externdef __imp_JetGetCounter:PPROC
JetGetCounter equ <__imp_JetGetCounter>

externdef __imp_JetGetCurrentIndex:PPROC
JetGetCurrentIndex equ <__imp_JetGetCurrentIndex>

externdef __imp_JetGetCursorInfo:PPROC
JetGetCursorInfo equ <__imp_JetGetCursorInfo>

externdef __imp_JetGetDatabaseInfo:PPROC
JetGetDatabaseInfo equ <__imp_JetGetDatabaseInfo>

externdef __imp_JetGetIndexInfo:PPROC
JetGetIndexInfo equ <__imp_JetGetIndexInfo>

externdef __imp_JetGetLogInfo:PPROC
JetGetLogInfo equ <__imp_JetGetLogInfo>

externdef __imp_JetGetObjectInfo:PPROC
JetGetObjectInfo equ <__imp_JetGetObjectInfo>

externdef __imp_JetGetObjidFromName:PPROC
JetGetObjidFromName equ <__imp_JetGetObjidFromName>

externdef __imp_JetGetQueryParameterInfo:PPROC
JetGetQueryParameterInfo equ <__imp_JetGetQueryParameterInfo>

externdef __imp_JetGetRecordPosition:PPROC
JetGetRecordPosition equ <__imp_JetGetRecordPosition>

externdef __imp_JetGetSystemParameter:PPROC
JetGetSystemParameter equ <__imp_JetGetSystemParameter>

externdef __imp_JetGetTableColumnInfo:PPROC
JetGetTableColumnInfo equ <__imp_JetGetTableColumnInfo>

externdef __imp_JetGetTableIndexInfo:PPROC
JetGetTableIndexInfo equ <__imp_JetGetTableIndexInfo>

externdef __imp_JetGetTableInfo:PPROC
JetGetTableInfo equ <__imp_JetGetTableInfo>

externdef __imp_JetGetVersion:PPROC
JetGetVersion equ <__imp_JetGetVersion>

externdef __imp_JetGotoBookmark:PPROC
JetGotoBookmark equ <__imp_JetGotoBookmark>

externdef __imp_JetGotoPosition:PPROC
JetGotoPosition equ <__imp_JetGotoPosition>

externdef __imp_JetIdle:PPROC
JetIdle equ <__imp_JetIdle>

externdef __imp_JetIndexRecordCount:PPROC
JetIndexRecordCount equ <__imp_JetIndexRecordCount>

externdef __imp_JetInit:PPROC
JetInit equ <__imp_JetInit>

externdef __imp_JetMakeKey:PPROC
JetMakeKey equ <__imp_JetMakeKey>

externdef __imp_JetMove:PPROC
JetMove equ <__imp_JetMove>

externdef __imp_JetOpenDatabase:PPROC
JetOpenDatabase equ <__imp_JetOpenDatabase>

externdef __imp_JetOpenFile:PPROC
JetOpenFile equ <__imp_JetOpenFile>

externdef __imp_JetOpenQueryDef:PPROC
JetOpenQueryDef equ <__imp_JetOpenQueryDef>

externdef __imp_JetOpenTable:PPROC
JetOpenTable equ <__imp_JetOpenTable>

externdef __imp_JetOpenTempTable2:PPROC
JetOpenTempTable2 equ <__imp_JetOpenTempTable2>

externdef __imp_JetOpenTempTable:PPROC
JetOpenTempTable equ <__imp_JetOpenTempTable>

externdef __imp_JetPrepareUpdate:PPROC
JetPrepareUpdate equ <__imp_JetPrepareUpdate>

externdef __imp_JetReadFile:PPROC
JetReadFile equ <__imp_JetReadFile>

externdef __imp_JetResetCounter:PPROC
JetResetCounter equ <__imp_JetResetCounter>

externdef __imp_JetRestore2:PPROC
JetRestore2 equ <__imp_JetRestore2>

externdef __imp_JetRestore:PPROC
JetRestore equ <__imp_JetRestore>

externdef __imp_JetRetrieveColumn:PPROC
JetRetrieveColumn equ <__imp_JetRetrieveColumn>

externdef __imp_JetRetrieveColumns:PPROC
JetRetrieveColumns equ <__imp_JetRetrieveColumns>

externdef __imp_JetRetrieveKey:PPROC
JetRetrieveKey equ <__imp_JetRetrieveKey>

externdef __imp_JetRetrieveQoSql:PPROC
JetRetrieveQoSql equ <__imp_JetRetrieveQoSql>

externdef __imp_JetRollback:PPROC
JetRollback equ <__imp_JetRollback>

externdef __imp_JetSeek:PPROC
JetSeek equ <__imp_JetSeek>

externdef __imp_JetSetAccess:PPROC
JetSetAccess equ <__imp_JetSetAccess>

externdef __imp_JetSetColumn:PPROC
JetSetColumn equ <__imp_JetSetColumn>

externdef __imp_JetSetColumns:PPROC
JetSetColumns equ <__imp_JetSetColumns>

externdef __imp_JetSetCurrentIndex2:PPROC
JetSetCurrentIndex2 equ <__imp_JetSetCurrentIndex2>

externdef __imp_JetSetCurrentIndex:PPROC
JetSetCurrentIndex equ <__imp_JetSetCurrentIndex>

externdef __imp_JetSetIndexRange:PPROC
JetSetIndexRange equ <__imp_JetSetIndexRange>

externdef __imp_JetSetQoSql:PPROC
JetSetQoSql equ <__imp_JetSetQoSql>

externdef __imp_JetSetSystemParameter:PPROC
JetSetSystemParameter equ <__imp_JetSetSystemParameter>

externdef __imp_JetTerm2:PPROC
JetTerm2 equ <__imp_JetTerm2>

externdef __imp_JetTerm:PPROC
JetTerm equ <__imp_JetTerm>

externdef __imp_JetTruncateLog:PPROC
JetTruncateLog equ <__imp_JetTruncateLog>

externdef __imp_JetUpdate:PPROC
JetUpdate equ <__imp_JetUpdate>
