externdef __imp_KdD0Transition:PPROC
KdD0Transition equ <__imp_KdD0Transition>

externdef __imp_KdD3Transition:PPROC
KdD3Transition equ <__imp_KdD3Transition>

externdef __imp_KdDebuggerInitialize0:PPROC
KdDebuggerInitialize0 equ <__imp_KdDebuggerInitialize0>

externdef __imp_KdDebuggerInitialize1:PPROC
KdDebuggerInitialize1 equ <__imp_KdDebuggerInitialize1>

externdef __imp_KdReceivePacket:PPROC
KdReceivePacket equ <__imp_KdReceivePacket>

externdef __imp_KdRestore:PPROC
KdRestore equ <__imp_KdRestore>

externdef __imp_KdSave:PPROC
KdSave equ <__imp_KdSave>

externdef __imp_KdSendPacket:PPROC
KdSendPacket equ <__imp_KdSendPacket>
