externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_licdll_ordinal124:PPROC
licdll_ordinal124 equ <__imp_licdll_ordinal124>

externdef __imp_licdll_ordinal129:PPROC
licdll_ordinal129 equ <__imp_licdll_ordinal129>

externdef __imp_licdll_ordinal130:PPROC
licdll_ordinal130 equ <__imp_licdll_ordinal130>

externdef __imp_licdll_ordinal131:PPROC
licdll_ordinal131 equ <__imp_licdll_ordinal131>

externdef __imp_licdll_ordinal132:PPROC
licdll_ordinal132 equ <__imp_licdll_ordinal132>

externdef __imp_licdll_ordinal133:PPROC
licdll_ordinal133 equ <__imp_licdll_ordinal133>

externdef __imp_licdll_ordinal134:PPROC
licdll_ordinal134 equ <__imp_licdll_ordinal134>

externdef __imp_licdll_ordinal135:PPROC
licdll_ordinal135 equ <__imp_licdll_ordinal135>

externdef __imp_licdll_ordinal136:PPROC
licdll_ordinal136 equ <__imp_licdll_ordinal136>

externdef __imp_licdll_ordinal137:PPROC
licdll_ordinal137 equ <__imp_licdll_ordinal137>

externdef __imp_licdll_ordinal138:PPROC
licdll_ordinal138 equ <__imp_licdll_ordinal138>

externdef __imp_licdll_ordinal139:PPROC
licdll_ordinal139 equ <__imp_licdll_ordinal139>

externdef __imp_licdll_ordinal140:PPROC
licdll_ordinal140 equ <__imp_licdll_ordinal140>

externdef __imp_licdll_ordinal141:PPROC
licdll_ordinal141 equ <__imp_licdll_ordinal141>

externdef __imp_licdll_ordinal142:PPROC
licdll_ordinal142 equ <__imp_licdll_ordinal142>

externdef __imp_licdll_ordinal143:PPROC
licdll_ordinal143 equ <__imp_licdll_ordinal143>

externdef __imp_licdll_ordinal144:PPROC
licdll_ordinal144 equ <__imp_licdll_ordinal144>

externdef __imp_licdll_ordinal145:PPROC
licdll_ordinal145 equ <__imp_licdll_ordinal145>

externdef __imp_licdll_ordinal146:PPROC
licdll_ordinal146 equ <__imp_licdll_ordinal146>

externdef __imp_licdll_ordinal147:PPROC
licdll_ordinal147 equ <__imp_licdll_ordinal147>

externdef __imp_licdll_ordinal148:PPROC
licdll_ordinal148 equ <__imp_licdll_ordinal148>

externdef __imp_licdll_ordinal149:PPROC
licdll_ordinal149 equ <__imp_licdll_ordinal149>

externdef __imp_licdll_ordinal150:PPROC
licdll_ordinal150 equ <__imp_licdll_ordinal150>

externdef __imp_licdll_ordinal151:PPROC
licdll_ordinal151 equ <__imp_licdll_ordinal151>

externdef __imp_licdll_ordinal152:PPROC
licdll_ordinal152 equ <__imp_licdll_ordinal152>

externdef __imp_licdll_ordinal153:PPROC
licdll_ordinal153 equ <__imp_licdll_ordinal153>

externdef __imp_licdll_ordinal154:PPROC
licdll_ordinal154 equ <__imp_licdll_ordinal154>

externdef __imp_licdll_ordinal155:PPROC
licdll_ordinal155 equ <__imp_licdll_ordinal155>

externdef __imp_licdll_ordinal156:PPROC
licdll_ordinal156 equ <__imp_licdll_ordinal156>

externdef __imp_licdll_ordinal157:PPROC
licdll_ordinal157 equ <__imp_licdll_ordinal157>

externdef __imp_licdll_ordinal158:PPROC
licdll_ordinal158 equ <__imp_licdll_ordinal158>

externdef __imp_licdll_ordinal159:PPROC
licdll_ordinal159 equ <__imp_licdll_ordinal159>

externdef __imp_licdll_ordinal160:PPROC
licdll_ordinal160 equ <__imp_licdll_ordinal160>

externdef __imp_licdll_ordinal161:PPROC
licdll_ordinal161 equ <__imp_licdll_ordinal161>

externdef __imp_licdll_ordinal162:PPROC
licdll_ordinal162 equ <__imp_licdll_ordinal162>

externdef __imp_licdll_ordinal163:PPROC
licdll_ordinal163 equ <__imp_licdll_ordinal163>

externdef __imp_licdll_ordinal164:PPROC
licdll_ordinal164 equ <__imp_licdll_ordinal164>

externdef __imp_licdll_ordinal165:PPROC
licdll_ordinal165 equ <__imp_licdll_ordinal165>

externdef __imp_licdll_ordinal166:PPROC
licdll_ordinal166 equ <__imp_licdll_ordinal166>

externdef __imp_licdll_ordinal167:PPROC
licdll_ordinal167 equ <__imp_licdll_ordinal167>

externdef __imp_licdll_ordinal168:PPROC
licdll_ordinal168 equ <__imp_licdll_ordinal168>

externdef __imp_licdll_ordinal169:PPROC
licdll_ordinal169 equ <__imp_licdll_ordinal169>

externdef __imp_licdll_ordinal170:PPROC
licdll_ordinal170 equ <__imp_licdll_ordinal170>

externdef __imp_licdll_ordinal171:PPROC
licdll_ordinal171 equ <__imp_licdll_ordinal171>

externdef __imp_licdll_ordinal172:PPROC
licdll_ordinal172 equ <__imp_licdll_ordinal172>

externdef __imp_licdll_ordinal173:PPROC
licdll_ordinal173 equ <__imp_licdll_ordinal173>

externdef __imp_licdll_ordinal174:PPROC
licdll_ordinal174 equ <__imp_licdll_ordinal174>

externdef __imp_licdll_ordinal175:PPROC
licdll_ordinal175 equ <__imp_licdll_ordinal175>

externdef __imp_licdll_ordinal176:PPROC
licdll_ordinal176 equ <__imp_licdll_ordinal176>

externdef __imp_licdll_ordinal177:PPROC
licdll_ordinal177 equ <__imp_licdll_ordinal177>

externdef __imp_licdll_ordinal178:PPROC
licdll_ordinal178 equ <__imp_licdll_ordinal178>

externdef __imp_licdll_ordinal179:PPROC
licdll_ordinal179 equ <__imp_licdll_ordinal179>

externdef __imp_licdll_ordinal180:PPROC
licdll_ordinal180 equ <__imp_licdll_ordinal180>

externdef __imp_licdll_ordinal181:PPROC
licdll_ordinal181 equ <__imp_licdll_ordinal181>

externdef __imp_licdll_ordinal182:PPROC
licdll_ordinal182 equ <__imp_licdll_ordinal182>

externdef __imp_licdll_ordinal183:PPROC
licdll_ordinal183 equ <__imp_licdll_ordinal183>

externdef __imp_licdll_ordinal184:PPROC
licdll_ordinal184 equ <__imp_licdll_ordinal184>

externdef __imp_licdll_ordinal185:PPROC
licdll_ordinal185 equ <__imp_licdll_ordinal185>

externdef __imp_licdll_ordinal186:PPROC
licdll_ordinal186 equ <__imp_licdll_ordinal186>

externdef __imp_licdll_ordinal187:PPROC
licdll_ordinal187 equ <__imp_licdll_ordinal187>

externdef __imp_licdll_ordinal188:PPROC
licdll_ordinal188 equ <__imp_licdll_ordinal188>

externdef __imp_licdll_ordinal189:PPROC
licdll_ordinal189 equ <__imp_licdll_ordinal189>

externdef __imp_licdll_ordinal190:PPROC
licdll_ordinal190 equ <__imp_licdll_ordinal190>

externdef __imp_licdll_ordinal191:PPROC
licdll_ordinal191 equ <__imp_licdll_ordinal191>

externdef __imp_licdll_ordinal192:PPROC
licdll_ordinal192 equ <__imp_licdll_ordinal192>

externdef __imp_licdll_ordinal193:PPROC
licdll_ordinal193 equ <__imp_licdll_ordinal193>

externdef __imp_licdll_ordinal194:PPROC
licdll_ordinal194 equ <__imp_licdll_ordinal194>

externdef __imp_licdll_ordinal195:PPROC
licdll_ordinal195 equ <__imp_licdll_ordinal195>

externdef __imp_licdll_ordinal196:PPROC
licdll_ordinal196 equ <__imp_licdll_ordinal196>

externdef __imp_licdll_ordinal197:PPROC
licdll_ordinal197 equ <__imp_licdll_ordinal197>

externdef __imp_licdll_ordinal198:PPROC
licdll_ordinal198 equ <__imp_licdll_ordinal198>

externdef __imp_licdll_ordinal199:PPROC
licdll_ordinal199 equ <__imp_licdll_ordinal199>

externdef __imp_licdll_ordinal200:PPROC
licdll_ordinal200 equ <__imp_licdll_ordinal200>

externdef __imp_licdll_ordinal201:PPROC
licdll_ordinal201 equ <__imp_licdll_ordinal201>

externdef __imp_licdll_ordinal202:PPROC
licdll_ordinal202 equ <__imp_licdll_ordinal202>

externdef __imp_licdll_ordinal203:PPROC
licdll_ordinal203 equ <__imp_licdll_ordinal203>

externdef __imp_licdll_ordinal204:PPROC
licdll_ordinal204 equ <__imp_licdll_ordinal204>

externdef __imp_licdll_ordinal205:PPROC
licdll_ordinal205 equ <__imp_licdll_ordinal205>

externdef __imp_licdll_ordinal206:PPROC
licdll_ordinal206 equ <__imp_licdll_ordinal206>

externdef __imp_licdll_ordinal207:PPROC
licdll_ordinal207 equ <__imp_licdll_ordinal207>

externdef __imp_licdll_ordinal208:PPROC
licdll_ordinal208 equ <__imp_licdll_ordinal208>

externdef __imp_licdll_ordinal209:PPROC
licdll_ordinal209 equ <__imp_licdll_ordinal209>

externdef __imp_licdll_ordinal210:PPROC
licdll_ordinal210 equ <__imp_licdll_ordinal210>

externdef __imp_licdll_ordinal211:PPROC
licdll_ordinal211 equ <__imp_licdll_ordinal211>

externdef __imp_licdll_ordinal212:PPROC
licdll_ordinal212 equ <__imp_licdll_ordinal212>

externdef __imp_licdll_ordinal213:PPROC
licdll_ordinal213 equ <__imp_licdll_ordinal213>

externdef __imp_licdll_ordinal214:PPROC
licdll_ordinal214 equ <__imp_licdll_ordinal214>

externdef __imp_licdll_ordinal215:PPROC
licdll_ordinal215 equ <__imp_licdll_ordinal215>

externdef __imp_licdll_ordinal216:PPROC
licdll_ordinal216 equ <__imp_licdll_ordinal216>

externdef __imp_licdll_ordinal217:PPROC
licdll_ordinal217 equ <__imp_licdll_ordinal217>

externdef __imp_licdll_ordinal218:PPROC
licdll_ordinal218 equ <__imp_licdll_ordinal218>

externdef __imp_licdll_ordinal219:PPROC
licdll_ordinal219 equ <__imp_licdll_ordinal219>

externdef __imp_licdll_ordinal220:PPROC
licdll_ordinal220 equ <__imp_licdll_ordinal220>

externdef __imp_licdll_ordinal221:PPROC
licdll_ordinal221 equ <__imp_licdll_ordinal221>

externdef __imp_licdll_ordinal222:PPROC
licdll_ordinal222 equ <__imp_licdll_ordinal222>

externdef __imp_licdll_ordinal223:PPROC
licdll_ordinal223 equ <__imp_licdll_ordinal223>

externdef __imp_licdll_ordinal224:PPROC
licdll_ordinal224 equ <__imp_licdll_ordinal224>

externdef __imp_licdll_ordinal225:PPROC
licdll_ordinal225 equ <__imp_licdll_ordinal225>

externdef __imp_licdll_ordinal226:PPROC
licdll_ordinal226 equ <__imp_licdll_ordinal226>

externdef __imp_licdll_ordinal227:PPROC
licdll_ordinal227 equ <__imp_licdll_ordinal227>

externdef __imp_licdll_ordinal228:PPROC
licdll_ordinal228 equ <__imp_licdll_ordinal228>

externdef __imp_licdll_ordinal229:PPROC
licdll_ordinal229 equ <__imp_licdll_ordinal229>
