externdef __imp_LpkDllInitialize:PPROC
LpkDllInitialize equ <__imp_LpkDllInitialize>

externdef __imp_LpkDrawTextEx:PPROC
LpkDrawTextEx equ <__imp_LpkDrawTextEx>

externdef __imp_LpkEditControl:PPROC
LpkEditControl equ <__imp_LpkEditControl>

externdef __imp_LpkExtTextOut:PPROC
LpkExtTextOut equ <__imp_LpkExtTextOut>

externdef __imp_LpkGetCharacterPlacement:PPROC
LpkGetCharacterPlacement equ <__imp_LpkGetCharacterPlacement>

externdef __imp_LpkGetTextExtentExPoint:PPROC
LpkGetTextExtentExPoint equ <__imp_LpkGetTextExtentExPoint>

externdef __imp_LpkInitialize:PPROC
LpkInitialize equ <__imp_LpkInitialize>

externdef __imp_LpkPSMTextOut:PPROC
LpkPSMTextOut equ <__imp_LpkPSMTextOut>

externdef __imp_LpkTabbedTextOut:PPROC
LpkTabbedTextOut equ <__imp_LpkTabbedTextOut>

externdef __imp_LpkUseGDIWidthCache:PPROC
LpkUseGDIWidthCache equ <__imp_LpkUseGDIWidthCache>

externdef __imp_ftsWordBreak:PPROC
ftsWordBreak equ <__imp_ftsWordBreak>
