externdef __imp_CancelJob:PPROC
CancelJob equ <__imp_CancelJob>

externdef __imp_CloseLPR:PPROC
CloseLPR equ <__imp_CloseLPR>

externdef __imp_EndJob:PPROC
EndJob equ <__imp_EndJob>

externdef __imp_GetLongQueue:PPROC
GetLongQueue equ <__imp_GetLongQueue>

externdef __imp_GetShortQueue:PPROC
GetShortQueue equ <__imp_GetShortQueue>

externdef __imp_InitiateConnection:PPROC
InitiateConnection equ <__imp_InitiateConnection>

externdef __imp_OpenLPR:PPROC
OpenLPR equ <__imp_OpenLPR>

externdef __imp_PrintWaitingJobs:PPROC
PrintWaitingJobs equ <__imp_PrintWaitingJobs>

externdef __imp_SetLPRTimeouts:PPROC
SetLPRTimeouts equ <__imp_SetLPRTimeouts>

externdef __imp_StartJob:PPROC
StartJob equ <__imp_StartJob>

externdef __imp_WriteJobData:PPROC
WriteJobData equ <__imp_WriteJobData>
