externdef __imp_MCDAddState:PPROC
MCDAddState equ <__imp_MCDAddState>

externdef __imp_MCDAddStateStruct:PPROC
MCDAddStateStruct equ <__imp_MCDAddStateStruct>

externdef __imp_MCDAlloc:PPROC
MCDAlloc equ <__imp_MCDAlloc>

externdef __imp_MCDAllocBuffers:PPROC
MCDAllocBuffers equ <__imp_MCDAllocBuffers>

externdef __imp_MCDBeginState:PPROC
MCDBeginState equ <__imp_MCDBeginState>

externdef __imp_MCDBindContext:PPROC
MCDBindContext equ <__imp_MCDBindContext>

externdef __imp_MCDClear:PPROC
MCDClear equ <__imp_MCDClear>

externdef __imp_MCDCopyPixels:PPROC
MCDCopyPixels equ <__imp_MCDCopyPixels>

externdef __imp_MCDCreateContext:PPROC
MCDCreateContext equ <__imp_MCDCreateContext>

externdef __imp_MCDCreateTexture:PPROC
MCDCreateTexture equ <__imp_MCDCreateTexture>

externdef __imp_MCDDeleteContext:PPROC
MCDDeleteContext equ <__imp_MCDDeleteContext>

externdef __imp_MCDDeleteTexture:PPROC
MCDDeleteTexture equ <__imp_MCDDeleteTexture>

externdef __imp_MCDDescribeLayerPlane:PPROC
MCDDescribeLayerPlane equ <__imp_MCDDescribeLayerPlane>

externdef __imp_MCDDescribeMcdLayerPlane:PPROC
MCDDescribeMcdLayerPlane equ <__imp_MCDDescribeMcdLayerPlane>

externdef __imp_MCDDescribeMcdPixelFormat:PPROC
MCDDescribeMcdPixelFormat equ <__imp_MCDDescribeMcdPixelFormat>

externdef __imp_MCDDescribePixelFormat:PPROC
MCDDescribePixelFormat equ <__imp_MCDDescribePixelFormat>

externdef __imp_MCDDestroyWindow:PPROC
MCDDestroyWindow equ <__imp_MCDDestroyWindow>

externdef __imp_MCDDrawPixels:PPROC
MCDDrawPixels equ <__imp_MCDDrawPixels>

externdef __imp_MCDFlushState:PPROC
MCDFlushState equ <__imp_MCDFlushState>

externdef __imp_MCDFree:PPROC
MCDFree equ <__imp_MCDFree>

externdef __imp_MCDGetBuffers:PPROC
MCDGetBuffers equ <__imp_MCDGetBuffers>

externdef __imp_MCDGetDriverInfo:PPROC
MCDGetDriverInfo equ <__imp_MCDGetDriverInfo>

externdef __imp_MCDGetTextureFormats:PPROC
MCDGetTextureFormats equ <__imp_MCDGetTextureFormats>

externdef __imp_MCDLock:PPROC
MCDLock equ <__imp_MCDLock>

externdef __imp_MCDPixelMap:PPROC
MCDPixelMap equ <__imp_MCDPixelMap>

externdef __imp_MCDProcessBatch2:PPROC
MCDProcessBatch2 equ <__imp_MCDProcessBatch2>

externdef __imp_MCDProcessBatch:PPROC
MCDProcessBatch equ <__imp_MCDProcessBatch>

externdef __imp_MCDQueryMemStatus:PPROC
MCDQueryMemStatus equ <__imp_MCDQueryMemStatus>

externdef __imp_MCDReadPixels:PPROC
MCDReadPixels equ <__imp_MCDReadPixels>

externdef __imp_MCDReadSpan:PPROC
MCDReadSpan equ <__imp_MCDReadSpan>

externdef __imp_MCDSetLayerPalette:PPROC
MCDSetLayerPalette equ <__imp_MCDSetLayerPalette>

externdef __imp_MCDSetScissorRect:PPROC
MCDSetScissorRect equ <__imp_MCDSetScissorRect>

externdef __imp_MCDSetViewport:PPROC
MCDSetViewport equ <__imp_MCDSetViewport>

externdef __imp_MCDSwap:PPROC
MCDSwap equ <__imp_MCDSwap>

externdef __imp_MCDSwapMultiple:PPROC
MCDSwapMultiple equ <__imp_MCDSwapMultiple>

externdef __imp_MCDSync:PPROC
MCDSync equ <__imp_MCDSync>

externdef __imp_MCDTextureKey:PPROC
MCDTextureKey equ <__imp_MCDTextureKey>

externdef __imp_MCDTextureStatus:PPROC
MCDTextureStatus equ <__imp_MCDTextureStatus>

externdef __imp_MCDUnlock:PPROC
MCDUnlock equ <__imp_MCDUnlock>

externdef __imp_MCDUpdateSubTexture:PPROC
MCDUpdateSubTexture equ <__imp_MCDUpdateSubTexture>

externdef __imp_MCDUpdateTexturePalette:PPROC
MCDUpdateTexturePalette equ <__imp_MCDUpdateTexturePalette>

externdef __imp_MCDUpdateTexturePriority:PPROC
MCDUpdateTexturePriority equ <__imp_MCDUpdateTexturePriority>

externdef __imp_MCDUpdateTextureState:PPROC
MCDUpdateTextureState equ <__imp_MCDUpdateTextureState>

externdef __imp_MCDWriteSpan:PPROC
MCDWriteSpan equ <__imp_MCDWriteSpan>
