externdef __imp_DllCreate:PPROC
DllCreate equ <__imp_DllCreate>

externdef __imp_DllCreateFromClip:PPROC
DllCreateFromClip equ <__imp_DllCreateFromClip>

externdef __imp_DllCreateFromFile:PPROC
DllCreateFromFile equ <__imp_DllCreateFromFile>

externdef __imp_DllCreateFromTemplate:PPROC
DllCreateFromTemplate equ <__imp_DllCreateFromTemplate>

externdef __imp_DllCreateLinkFromClip:PPROC
DllCreateLinkFromClip equ <__imp_DllCreateLinkFromClip>

externdef __imp_DllCreateLinkFromFile:PPROC
DllCreateLinkFromFile equ <__imp_DllCreateLinkFromFile>

externdef __imp_DllLoadFromStream:PPROC
DllLoadFromStream equ <__imp_DllLoadFromStream>

externdef __imp_GetMessageHook:PPROC
GetMessageHook equ <__imp_GetMessageHook>

externdef __imp_InstallHook:PPROC
InstallHook equ <__imp_InstallHook>

externdef __imp_OleQueryObjPos:PPROC
OleQueryObjPos equ <__imp_OleQueryObjPos>

externdef __imp_RemoveHook:PPROC
RemoveHook equ <__imp_RemoveHook>
