externdef __imp_??$ConstructElements@VCString@@@@YAXPEAVCString@@H@Z:PPROC
??$ConstructElements@VCString@@@@YAXPEAVCString@@H@Z equ <__imp_??$ConstructElements@VCString@@@@YAXPEAVCString@@H@Z>

externdef __imp_??$CopyElements@VCString@@@@YAXPEAVCString@@PEBV0@H@Z:PPROC
??$CopyElements@VCString@@@@YAXPEAVCString@@PEBV0@H@Z equ <__imp_??$CopyElements@VCString@@@@YAXPEAVCString@@PEBV0@H@Z>

externdef __imp_??$DestructElements@VCString@@@@YAXPEAVCString@@H@Z:PPROC
??$DestructElements@VCString@@@@YAXPEAVCString@@H@Z equ <__imp_??$DestructElements@VCString@@@@YAXPEAVCString@@H@Z>

externdef __imp_??$HashKey@AEBU_GUID@@@@YAIAEBU_GUID@@@Z:PPROC
??$HashKey@AEBU_GUID@@@@YAIAEBU_GUID@@@Z equ <__imp_??$HashKey@AEBU_GUID@@@@YAIAEBU_GUID@@@Z>

externdef __imp_??$HashKey@PEBD@@YAIPEBD@Z:PPROC
??$HashKey@PEBD@@YAIPEBD@Z equ <__imp_??$HashKey@PEBD@@YAIPEBD@Z>

externdef __imp_??$HashKey@PEBG@@YAIPEBG@Z:PPROC
??$HashKey@PEBG@@YAIPEBG@Z equ <__imp_??$HashKey@PEBG@@YAIPEBG@Z>

externdef __imp_??0CCriticalSection@@QEAA@XZ:PPROC
??0CCriticalSection@@QEAA@XZ equ <__imp_??0CCriticalSection@@QEAA@XZ>

externdef __imp_??0CMapStringToPtr@@QEAA@H@Z:PPROC
??0CMapStringToPtr@@QEAA@H@Z equ <__imp_??0CMapStringToPtr@@QEAA@H@Z>

externdef __imp_??0CObject@@IEAA@XZ:PPROC
??0CObject@@IEAA@XZ equ <__imp_??0CObject@@IEAA@XZ>

externdef __imp_??0CString@@QEAA@AEBV0@@Z:PPROC
??0CString@@QEAA@AEBV0@@Z equ <__imp_??0CString@@QEAA@AEBV0@@Z>

externdef __imp_??0CString@@QEAA@GH@Z:PPROC
??0CString@@QEAA@GH@Z equ <__imp_??0CString@@QEAA@GH@Z>

externdef __imp_??0CString@@QEAA@PEBD@Z:PPROC
??0CString@@QEAA@PEBD@Z equ <__imp_??0CString@@QEAA@PEBD@Z>

externdef __imp_??0CString@@QEAA@PEBE@Z:PPROC
??0CString@@QEAA@PEBE@Z equ <__imp_??0CString@@QEAA@PEBE@Z>

externdef __imp_??0CString@@QEAA@PEBG@Z:PPROC
??0CString@@QEAA@PEBG@Z equ <__imp_??0CString@@QEAA@PEBG@Z>

externdef __imp_??0CString@@QEAA@PEBGH@Z:PPROC
??0CString@@QEAA@PEBGH@Z equ <__imp_??0CString@@QEAA@PEBGH@Z>

externdef __imp_??0CString@@QEAA@XZ:PPROC
??0CString@@QEAA@XZ equ <__imp_??0CString@@QEAA@XZ>

externdef __imp_??0CStringArray@@QEAA@XZ:PPROC
??0CStringArray@@QEAA@XZ equ <__imp_??0CStringArray@@QEAA@XZ>

externdef __imp_??0CSyncObject@@QEAA@PEBG@Z:PPROC
??0CSyncObject@@QEAA@PEBG@Z equ <__imp_??0CSyncObject@@QEAA@PEBG@Z>

externdef __imp_??1CCriticalSection@@UEAA@XZ:PPROC
??1CCriticalSection@@UEAA@XZ equ <__imp_??1CCriticalSection@@UEAA@XZ>

externdef __imp_??1CMapStringToPtr@@UEAA@XZ:PPROC
??1CMapStringToPtr@@UEAA@XZ equ <__imp_??1CMapStringToPtr@@UEAA@XZ>

externdef __imp_??1CObject@@UEAA@XZ:PPROC
??1CObject@@UEAA@XZ equ <__imp_??1CObject@@UEAA@XZ>

externdef __imp_??1CString@@QEAA@XZ:PPROC
??1CString@@QEAA@XZ equ <__imp_??1CString@@QEAA@XZ>

externdef __imp_??1CStringArray@@UEAA@XZ:PPROC
??1CStringArray@@UEAA@XZ equ <__imp_??1CStringArray@@UEAA@XZ>

externdef __imp_??1CSyncObject@@UEAA@XZ:PPROC
??1CSyncObject@@UEAA@XZ equ <__imp_??1CSyncObject@@UEAA@XZ>

externdef __imp_??4CPlex@@QEAAAEAU0@AEBU0@@Z:PPROC
??4CPlex@@QEAAAEAU0@AEBU0@@Z equ <__imp_??4CPlex@@QEAAAEAU0@AEBU0@@Z>

externdef __imp_??4CString@@QEAAAEBV0@AEBV0@@Z:PPROC
??4CString@@QEAAAEBV0@AEBV0@@Z equ <__imp_??4CString@@QEAAAEBV0@AEBV0@@Z>

externdef __imp_??4CString@@QEAAAEBV0@D@Z:PPROC
??4CString@@QEAAAEBV0@D@Z equ <__imp_??4CString@@QEAAAEBV0@D@Z>

externdef __imp_??4CString@@QEAAAEBV0@G@Z:PPROC
??4CString@@QEAAAEBV0@G@Z equ <__imp_??4CString@@QEAAAEBV0@G@Z>

externdef __imp_??4CString@@QEAAAEBV0@PEBD@Z:PPROC
??4CString@@QEAAAEBV0@PEBD@Z equ <__imp_??4CString@@QEAAAEBV0@PEBD@Z>

externdef __imp_??4CString@@QEAAAEBV0@PEBE@Z:PPROC
??4CString@@QEAAAEBV0@PEBE@Z equ <__imp_??4CString@@QEAAAEBV0@PEBE@Z>

externdef __imp_??4CString@@QEAAAEBV0@PEBG@Z:PPROC
??4CString@@QEAAAEBV0@PEBG@Z equ <__imp_??4CString@@QEAAAEBV0@PEBG@Z>

externdef __imp_??8@YA_NAEBVCString@@0@Z:PPROC
??8@YA_NAEBVCString@@0@Z equ <__imp_??8@YA_NAEBVCString@@0@Z>

externdef __imp_??8@YA_NAEBVCString@@PEBG@Z:PPROC
??8@YA_NAEBVCString@@PEBG@Z equ <__imp_??8@YA_NAEBVCString@@PEBG@Z>

externdef __imp_??8@YA_NPEBGAEBVCString@@@Z:PPROC
??8@YA_NPEBGAEBVCString@@@Z equ <__imp_??8@YA_NPEBGAEBVCString@@@Z>

externdef __imp_??9@YA_NAEBVCString@@0@Z:PPROC
??9@YA_NAEBVCString@@0@Z equ <__imp_??9@YA_NAEBVCString@@0@Z>

externdef __imp_??9@YA_NAEBVCString@@PEBG@Z:PPROC
??9@YA_NAEBVCString@@PEBG@Z equ <__imp_??9@YA_NAEBVCString@@PEBG@Z>

externdef __imp_??9@YA_NPEBGAEBVCString@@@Z:PPROC
??9@YA_NPEBGAEBVCString@@@Z equ <__imp_??9@YA_NPEBGAEBVCString@@@Z>

externdef __imp_??ACMapStringToPtr@@QEAAAEAPEAXPEBG@Z:PPROC
??ACMapStringToPtr@@QEAAAEAPEAXPEBG@Z equ <__imp_??ACMapStringToPtr@@QEAAAEAPEAXPEBG@Z>

externdef __imp_??ACString@@QEBAGH@Z:PPROC
??ACString@@QEBAGH@Z equ <__imp_??ACString@@QEBAGH@Z>

externdef __imp_??ACStringArray@@QEAAAEAVCString@@H@Z:PPROC
??ACStringArray@@QEAAAEAVCString@@H@Z equ <__imp_??ACStringArray@@QEAAAEAVCString@@H@Z>

externdef __imp_??ACStringArray@@QEBA?AVCString@@H@Z:PPROC
??ACStringArray@@QEBA?AVCString@@H@Z equ <__imp_??ACStringArray@@QEBA?AVCString@@H@Z>

externdef __imp_??BCCriticalSection@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ:PPROC
??BCCriticalSection@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ equ <__imp_??BCCriticalSection@@QEAAPEAU_RTL_CRITICAL_SECTION@@XZ>

externdef __imp_??BCString@@QEBAPEBGXZ:PPROC
??BCString@@QEBAPEBGXZ equ <__imp_??BCString@@QEBAPEBGXZ>

externdef __imp_??BCSyncObject@@QEBAPEAXXZ:PPROC
??BCSyncObject@@QEBAPEAXXZ equ <__imp_??BCSyncObject@@QEBAPEAXXZ>

externdef __imp_??H@YA?AVCString@@AEBV0@0@Z:PPROC
??H@YA?AVCString@@AEBV0@0@Z equ <__imp_??H@YA?AVCString@@AEBV0@0@Z>

externdef __imp_??H@YA?AVCString@@AEBV0@D@Z:PPROC
??H@YA?AVCString@@AEBV0@D@Z equ <__imp_??H@YA?AVCString@@AEBV0@D@Z>

externdef __imp_??H@YA?AVCString@@AEBV0@G@Z:PPROC
??H@YA?AVCString@@AEBV0@G@Z equ <__imp_??H@YA?AVCString@@AEBV0@G@Z>

externdef __imp_??H@YA?AVCString@@AEBV0@PEBG@Z:PPROC
??H@YA?AVCString@@AEBV0@PEBG@Z equ <__imp_??H@YA?AVCString@@AEBV0@PEBG@Z>

externdef __imp_??H@YA?AVCString@@DAEBV0@@Z:PPROC
??H@YA?AVCString@@DAEBV0@@Z equ <__imp_??H@YA?AVCString@@DAEBV0@@Z>

externdef __imp_??H@YA?AVCString@@GAEBV0@@Z:PPROC
??H@YA?AVCString@@GAEBV0@@Z equ <__imp_??H@YA?AVCString@@GAEBV0@@Z>

externdef __imp_??H@YA?AVCString@@PEBGAEBV0@@Z:PPROC
??H@YA?AVCString@@PEBGAEBV0@@Z equ <__imp_??H@YA?AVCString@@PEBGAEBV0@@Z>

externdef __imp_??M@YA_NAEBVCString@@0@Z:PPROC
??M@YA_NAEBVCString@@0@Z equ <__imp_??M@YA_NAEBVCString@@0@Z>

externdef __imp_??M@YA_NAEBVCString@@PEBG@Z:PPROC
??M@YA_NAEBVCString@@PEBG@Z equ <__imp_??M@YA_NAEBVCString@@PEBG@Z>

externdef __imp_??M@YA_NPEBGAEBVCString@@@Z:PPROC
??M@YA_NPEBGAEBVCString@@@Z equ <__imp_??M@YA_NPEBGAEBVCString@@@Z>

externdef __imp_??N@YA_NAEBVCString@@0@Z:PPROC
??N@YA_NAEBVCString@@0@Z equ <__imp_??N@YA_NAEBVCString@@0@Z>

externdef __imp_??N@YA_NAEBVCString@@PEBG@Z:PPROC
??N@YA_NAEBVCString@@PEBG@Z equ <__imp_??N@YA_NAEBVCString@@PEBG@Z>

externdef __imp_??N@YA_NPEBGAEBVCString@@@Z:PPROC
??N@YA_NPEBGAEBVCString@@@Z equ <__imp_??N@YA_NPEBGAEBVCString@@@Z>

externdef __imp_??O@YA_NAEBVCString@@0@Z:PPROC
??O@YA_NAEBVCString@@0@Z equ <__imp_??O@YA_NAEBVCString@@0@Z>

externdef __imp_??O@YA_NAEBVCString@@PEBG@Z:PPROC
??O@YA_NAEBVCString@@PEBG@Z equ <__imp_??O@YA_NAEBVCString@@PEBG@Z>

externdef __imp_??O@YA_NPEBGAEBVCString@@@Z:PPROC
??O@YA_NPEBGAEBVCString@@@Z equ <__imp_??O@YA_NPEBGAEBVCString@@@Z>

externdef __imp_??P@YA_NAEBVCString@@0@Z:PPROC
??P@YA_NAEBVCString@@0@Z equ <__imp_??P@YA_NAEBVCString@@0@Z>

externdef __imp_??P@YA_NAEBVCString@@PEBG@Z:PPROC
??P@YA_NAEBVCString@@PEBG@Z equ <__imp_??P@YA_NAEBVCString@@PEBG@Z>

externdef __imp_??P@YA_NPEBGAEBVCString@@@Z:PPROC
??P@YA_NPEBGAEBVCString@@@Z equ <__imp_??P@YA_NPEBGAEBVCString@@@Z>

externdef __imp_??YCString@@QEAAAEBV0@AEBV0@@Z:PPROC
??YCString@@QEAAAEBV0@AEBV0@@Z equ <__imp_??YCString@@QEAAAEBV0@AEBV0@@Z>

externdef __imp_??YCString@@QEAAAEBV0@D@Z:PPROC
??YCString@@QEAAAEBV0@D@Z equ <__imp_??YCString@@QEAAAEBV0@D@Z>

externdef __imp_??YCString@@QEAAAEBV0@G@Z:PPROC
??YCString@@QEAAAEBV0@G@Z equ <__imp_??YCString@@QEAAAEBV0@G@Z>

externdef __imp_??YCString@@QEAAAEBV0@PEBG@Z:PPROC
??YCString@@QEAAAEBV0@PEBG@Z equ <__imp_??YCString@@QEAAAEBV0@PEBG@Z>

externdef __imp_??_7CCriticalSection@@6B@:PPROC
??_7CCriticalSection@@6B@ equ <__imp_??_7CCriticalSection@@6B@>

externdef __imp_??_7CMapStringToPtr@@6B@:PPROC
??_7CMapStringToPtr@@6B@ equ <__imp_??_7CMapStringToPtr@@6B@>

externdef __imp_??_7CObject@@6B@:PPROC
??_7CObject@@6B@ equ <__imp_??_7CObject@@6B@>

externdef __imp_??_7CStringArray@@6B@:PPROC
??_7CStringArray@@6B@ equ <__imp_??_7CStringArray@@6B@>

externdef __imp_??_7CSyncObject@@6B@:PPROC
??_7CSyncObject@@6B@ equ <__imp_??_7CSyncObject@@6B@>

externdef __imp_??_FCMapStringToPtr@@QEAAXXZ:PPROC
??_FCMapStringToPtr@@QEAAXXZ equ <__imp_??_FCMapStringToPtr@@QEAAXXZ>

externdef __imp_?Add@CStringArray@@QEAAHPEBG@Z:PPROC
?Add@CStringArray@@QEAAHPEBG@Z equ <__imp_?Add@CStringArray@@QEAAHPEBG@Z>

externdef __imp_?AfxA2WHelper@@YAPEAGPEAGPEBDH@Z:PPROC
?AfxA2WHelper@@YAPEAGPEAGPEBDH@Z equ <__imp_?AfxA2WHelper@@YAPEAGPEAGPEBDH@Z>

externdef __imp_?AfxExtractSubString@@YAHAEAVCString@@PEBGHG@Z:PPROC
?AfxExtractSubString@@YAHAEAVCString@@PEBGHG@Z equ <__imp_?AfxExtractSubString@@YAHAEAVCString@@PEBGHG@Z>

externdef __imp_?AfxGetEmptyString@@YAAEBVCString@@XZ:PPROC
?AfxGetEmptyString@@YAAEBVCString@@XZ equ <__imp_?AfxGetEmptyString@@YAAEBVCString@@XZ>

externdef __imp_?AfxLoadString@@YAHIPEAGI@Z:PPROC
?AfxLoadString@@YAHIPEAGI@Z equ <__imp_?AfxLoadString@@YAHIPEAGI@Z>

externdef __imp_?AfxW2AHelper@@YAPEADPEADPEBGH@Z:PPROC
?AfxW2AHelper@@YAPEADPEADPEBGH@Z equ <__imp_?AfxW2AHelper@@YAPEADPEADPEBGH@Z>

externdef __imp_?AllocBeforeWrite@CString@@IEAAXH@Z:PPROC
?AllocBeforeWrite@CString@@IEAAXH@Z equ <__imp_?AllocBeforeWrite@CString@@IEAAXH@Z>

externdef __imp_?AllocBuffer@CString@@IEAAXH@Z:PPROC
?AllocBuffer@CString@@IEAAXH@Z equ <__imp_?AllocBuffer@CString@@IEAAXH@Z>

externdef __imp_?AllocCopy@CString@@IEBAXAEAV1@HHH@Z:PPROC
?AllocCopy@CString@@IEBAXAEAV1@HHH@Z equ <__imp_?AllocCopy@CString@@IEBAXAEAV1@HHH@Z>

externdef __imp_?Append@CStringArray@@QEAAHAEBV1@@Z:PPROC
?Append@CStringArray@@QEAAHAEBV1@@Z equ <__imp_?Append@CStringArray@@QEAAHAEBV1@@Z>

externdef __imp_?AssignCopy@CString@@IEAAXHPEBG@Z:PPROC
?AssignCopy@CString@@IEAAXHPEBG@Z equ <__imp_?AssignCopy@CString@@IEAAXHPEBG@Z>

externdef __imp_?Collate@CString@@QEBAHPEBG@Z:PPROC
?Collate@CString@@QEBAHPEBG@Z equ <__imp_?Collate@CString@@QEBAHPEBG@Z>

externdef __imp_?Compare@CString@@QEBAHPEBG@Z:PPROC
?Compare@CString@@QEBAHPEBG@Z equ <__imp_?Compare@CString@@QEBAHPEBG@Z>

externdef __imp_?CompareNoCase@CString@@QEBAHPEBG@Z:PPROC
?CompareNoCase@CString@@QEBAHPEBG@Z equ <__imp_?CompareNoCase@CString@@QEBAHPEBG@Z>

externdef __imp_?ConcatCopy@CString@@IEAAXHPEBGH0@Z:PPROC
?ConcatCopy@CString@@IEAAXHPEBGH0@Z equ <__imp_?ConcatCopy@CString@@IEAAXHPEBGH0@Z>

externdef __imp_?ConcatInPlace@CString@@IEAAXHPEBG@Z:PPROC
?ConcatInPlace@CString@@IEAAXHPEBG@Z equ <__imp_?ConcatInPlace@CString@@IEAAXHPEBG@Z>

externdef __imp_?Copy@CStringArray@@QEAAXAEBV1@@Z:PPROC
?Copy@CStringArray@@QEAAXAEBV1@@Z equ <__imp_?Copy@CStringArray@@QEAAXAEBV1@@Z>

externdef __imp_?CopyBeforeWrite@CString@@IEAAXXZ:PPROC
?CopyBeforeWrite@CString@@IEAAXXZ equ <__imp_?CopyBeforeWrite@CString@@IEAAXXZ>

externdef __imp_?Create@CPlex@@SAPEAU1@AEAPEAU1@II@Z:PPROC
?Create@CPlex@@SAPEAU1@AEAPEAU1@II@Z equ <__imp_?Create@CPlex@@SAPEAU1@AEAPEAU1@II@Z>

externdef __imp_?ElementAt@CStringArray@@QEAAAEAVCString@@H@Z:PPROC
?ElementAt@CStringArray@@QEAAAEAVCString@@H@Z equ <__imp_?ElementAt@CStringArray@@QEAAAEAVCString@@H@Z>

externdef __imp_?Empty@CString@@QEAAXXZ:PPROC
?Empty@CString@@QEAAXXZ equ <__imp_?Empty@CString@@QEAAXXZ>

externdef __imp_?Find@CString@@QEBAHG@Z:PPROC
?Find@CString@@QEBAHG@Z equ <__imp_?Find@CString@@QEBAHG@Z>

externdef __imp_?Find@CString@@QEBAHPEBG@Z:PPROC
?Find@CString@@QEBAHPEBG@Z equ <__imp_?Find@CString@@QEBAHPEBG@Z>

externdef __imp_?FindOneOf@CString@@QEBAHPEBG@Z:PPROC
?FindOneOf@CString@@QEBAHPEBG@Z equ <__imp_?FindOneOf@CString@@QEBAHPEBG@Z>

externdef __imp_?Format@CString@@QEAAXIZZ:PPROC
?Format@CString@@QEAAXIZZ equ <__imp_?Format@CString@@QEAAXIZZ>

externdef __imp_?Format@CString@@QEAAXPEBGZZ:PPROC
?Format@CString@@QEAAXPEBGZZ equ <__imp_?Format@CString@@QEAAXPEBGZZ>

externdef __imp_?FormatMessageW@CString@@QEAAXIZZ:PPROC
?FormatMessageW@CString@@QEAAXIZZ equ <__imp_?FormatMessageW@CString@@QEAAXIZZ>

externdef __imp_?FormatMessageW@CString@@QEAAXPEBGZZ:PPROC
?FormatMessageW@CString@@QEAAXPEBGZZ equ <__imp_?FormatMessageW@CString@@QEAAXPEBGZZ>

externdef __imp_?FormatV@CString@@IEAAXPEBGPEAD@Z:PPROC
?FormatV@CString@@IEAAXPEBGPEAD@Z equ <__imp_?FormatV@CString@@IEAAXPEBGPEAD@Z>

externdef __imp_?FreeAssoc@CMapStringToPtr@@IEAAXPEAUCAssoc@1@@Z:PPROC
?FreeAssoc@CMapStringToPtr@@IEAAXPEAUCAssoc@1@@Z equ <__imp_?FreeAssoc@CMapStringToPtr@@IEAAXPEAUCAssoc@1@@Z>

externdef __imp_?FreeDataChain@CPlex@@QEAAXXZ:PPROC
?FreeDataChain@CPlex@@QEAAXXZ equ <__imp_?FreeDataChain@CPlex@@QEAAXXZ>

externdef __imp_?FreeExtra@CString@@QEAAXXZ:PPROC
?FreeExtra@CString@@QEAAXXZ equ <__imp_?FreeExtra@CString@@QEAAXXZ>

externdef __imp_?FreeExtra@CStringArray@@QEAAXXZ:PPROC
?FreeExtra@CStringArray@@QEAAXXZ equ <__imp_?FreeExtra@CStringArray@@QEAAXXZ>

externdef __imp_?GetAllocLength@CString@@QEBAHXZ:PPROC
?GetAllocLength@CString@@QEBAHXZ equ <__imp_?GetAllocLength@CString@@QEBAHXZ>

externdef __imp_?GetAssocAt@CMapStringToPtr@@IEBAPEAUCAssoc@1@PEBGAEAI@Z:PPROC
?GetAssocAt@CMapStringToPtr@@IEBAPEAUCAssoc@1@PEBGAEAI@Z equ <__imp_?GetAssocAt@CMapStringToPtr@@IEBAPEAUCAssoc@1@PEBGAEAI@Z>

externdef __imp_?GetAt@CString@@QEBAGH@Z:PPROC
?GetAt@CString@@QEBAGH@Z equ <__imp_?GetAt@CString@@QEBAGH@Z>

externdef __imp_?GetAt@CStringArray@@QEBA?AVCString@@H@Z:PPROC
?GetAt@CStringArray@@QEBA?AVCString@@H@Z equ <__imp_?GetAt@CStringArray@@QEBA?AVCString@@H@Z>

externdef __imp_?GetBuffer@CString@@QEAAPEAGH@Z:PPROC
?GetBuffer@CString@@QEAAPEAGH@Z equ <__imp_?GetBuffer@CString@@QEAAPEAGH@Z>

externdef __imp_?GetBufferSetLength@CString@@QEAAPEAGH@Z:PPROC
?GetBufferSetLength@CString@@QEAAPEAGH@Z equ <__imp_?GetBufferSetLength@CString@@QEAAPEAGH@Z>

externdef __imp_?GetCount@CMapStringToPtr@@QEBAHXZ:PPROC
?GetCount@CMapStringToPtr@@QEBAHXZ equ <__imp_?GetCount@CMapStringToPtr@@QEBAHXZ>

externdef __imp_?GetData@CString@@IEBAPEAUCStringData@@XZ:PPROC
?GetData@CString@@IEBAPEAUCStringData@@XZ equ <__imp_?GetData@CString@@IEBAPEAUCStringData@@XZ>

externdef __imp_?GetData@CStringArray@@QEAAPEAVCString@@XZ:PPROC
?GetData@CStringArray@@QEAAPEAVCString@@XZ equ <__imp_?GetData@CStringArray@@QEAAPEAVCString@@XZ>

externdef __imp_?GetData@CStringArray@@QEBAPEBVCString@@XZ:PPROC
?GetData@CStringArray@@QEBAPEBVCString@@XZ equ <__imp_?GetData@CStringArray@@QEBAPEBVCString@@XZ>

externdef __imp_?GetHashTableSize@CMapStringToPtr@@QEBAIXZ:PPROC
?GetHashTableSize@CMapStringToPtr@@QEBAIXZ equ <__imp_?GetHashTableSize@CMapStringToPtr@@QEBAIXZ>

externdef __imp_?GetLength@CString@@QEBAHXZ:PPROC
?GetLength@CString@@QEBAHXZ equ <__imp_?GetLength@CString@@QEBAHXZ>

externdef __imp_?GetNextAssoc@CMapStringToPtr@@QEBAXAEAPEAU__POSITION@@AEAVCString@@AEAPEAX@Z:PPROC
?GetNextAssoc@CMapStringToPtr@@QEBAXAEAPEAU__POSITION@@AEAVCString@@AEAPEAX@Z equ <__imp_?GetNextAssoc@CMapStringToPtr@@QEBAXAEAPEAU__POSITION@@AEAVCString@@AEAPEAX@Z>

externdef __imp_?GetSize@CStringArray@@QEBAHXZ:PPROC
?GetSize@CStringArray@@QEBAHXZ equ <__imp_?GetSize@CStringArray@@QEBAHXZ>

externdef __imp_?GetStartPosition@CMapStringToPtr@@QEBAPEAU__POSITION@@XZ:PPROC
?GetStartPosition@CMapStringToPtr@@QEBAPEAU__POSITION@@XZ equ <__imp_?GetStartPosition@CMapStringToPtr@@QEBAPEAU__POSITION@@XZ>

externdef __imp_?GetUpperBound@CStringArray@@QEBAHXZ:PPROC
?GetUpperBound@CStringArray@@QEBAHXZ equ <__imp_?GetUpperBound@CStringArray@@QEBAHXZ>

externdef __imp_?HashKey@CMapStringToPtr@@QEBAIPEBG@Z:PPROC
?HashKey@CMapStringToPtr@@QEBAIPEBG@Z equ <__imp_?HashKey@CMapStringToPtr@@QEBAIPEBG@Z>

externdef __imp_?Init@CString@@IEAAXXZ:PPROC
?Init@CString@@IEAAXXZ equ <__imp_?Init@CString@@IEAAXXZ>

externdef __imp_?InitHashTable@CMapStringToPtr@@QEAAXIH@Z:PPROC
?InitHashTable@CMapStringToPtr@@QEAAXIH@Z equ <__imp_?InitHashTable@CMapStringToPtr@@QEAAXIH@Z>

externdef __imp_?InsertAt@CStringArray@@QEAAXHPEAV1@@Z:PPROC
?InsertAt@CStringArray@@QEAAXHPEAV1@@Z equ <__imp_?InsertAt@CStringArray@@QEAAXHPEAV1@@Z>

externdef __imp_?InsertAt@CStringArray@@QEAAXHPEBGH@Z:PPROC
?InsertAt@CStringArray@@QEAAXHPEBGH@Z equ <__imp_?InsertAt@CStringArray@@QEAAXHPEBGH@Z>

externdef __imp_?IsEmpty@CMapStringToPtr@@QEBAHXZ:PPROC
?IsEmpty@CMapStringToPtr@@QEBAHXZ equ <__imp_?IsEmpty@CMapStringToPtr@@QEBAHXZ>

externdef __imp_?IsEmpty@CString@@QEBAHXZ:PPROC
?IsEmpty@CString@@QEBAHXZ equ <__imp_?IsEmpty@CString@@QEBAHXZ>

externdef __imp_?Left@CString@@QEBA?AV1@H@Z:PPROC
?Left@CString@@QEBA?AV1@H@Z equ <__imp_?Left@CString@@QEBA?AV1@H@Z>

externdef __imp_?LoadStringW@CString@@QEAAHI@Z:PPROC
?LoadStringW@CString@@QEAAHI@Z equ <__imp_?LoadStringW@CString@@QEAAHI@Z>

externdef __imp_?Lock@CCriticalSection@@QEAAHXZ:PPROC
?Lock@CCriticalSection@@QEAAHXZ equ <__imp_?Lock@CCriticalSection@@QEAAHXZ>

externdef __imp_?Lock@CCriticalSection@@UEAAHK@Z:PPROC
?Lock@CCriticalSection@@UEAAHK@Z equ <__imp_?Lock@CCriticalSection@@UEAAHK@Z>

externdef __imp_?Lock@CSyncObject@@UEAAHK@Z:PPROC
?Lock@CSyncObject@@UEAAHK@Z equ <__imp_?Lock@CSyncObject@@UEAAHK@Z>

externdef __imp_?LockBuffer@CString@@QEAAPEAGXZ:PPROC
?LockBuffer@CString@@QEAAPEAGXZ equ <__imp_?LockBuffer@CString@@QEAAPEAGXZ>

externdef __imp_?Lookup@CMapStringToPtr@@QEBAHPEBGAEAPEAX@Z:PPROC
?Lookup@CMapStringToPtr@@QEBAHPEBGAEAPEAX@Z equ <__imp_?Lookup@CMapStringToPtr@@QEBAHPEBGAEAPEAX@Z>

externdef __imp_?LookupKey@CMapStringToPtr@@QEBAHPEBGAEAPEBG@Z:PPROC
?LookupKey@CMapStringToPtr@@QEBAHPEBGAEAPEBG@Z equ <__imp_?LookupKey@CMapStringToPtr@@QEBAHPEBGAEAPEBG@Z>

externdef __imp_?MakeLower@CString@@QEAAXXZ:PPROC
?MakeLower@CString@@QEAAXXZ equ <__imp_?MakeLower@CString@@QEAAXXZ>

externdef __imp_?MakeReverse@CString@@QEAAXXZ:PPROC
?MakeReverse@CString@@QEAAXXZ equ <__imp_?MakeReverse@CString@@QEAAXXZ>

externdef __imp_?MakeUpper@CString@@QEAAXXZ:PPROC
?MakeUpper@CString@@QEAAXXZ equ <__imp_?MakeUpper@CString@@QEAAXXZ>

externdef __imp_?Mid@CString@@QEBA?AV1@H@Z:PPROC
?Mid@CString@@QEBA?AV1@H@Z equ <__imp_?Mid@CString@@QEBA?AV1@H@Z>

externdef __imp_?Mid@CString@@QEBA?AV1@HH@Z:PPROC
?Mid@CString@@QEBA?AV1@HH@Z equ <__imp_?Mid@CString@@QEBA?AV1@HH@Z>

externdef __imp_?NewAssoc@CMapStringToPtr@@IEAAPEAUCAssoc@1@XZ:PPROC
?NewAssoc@CMapStringToPtr@@IEAAPEAUCAssoc@1@XZ equ <__imp_?NewAssoc@CMapStringToPtr@@IEAAPEAUCAssoc@1@XZ>

externdef __imp_?Release@CString@@IEAAXXZ:PPROC
?Release@CString@@IEAAXXZ equ <__imp_?Release@CString@@IEAAXXZ>

externdef __imp_?Release@CString@@KAXPEAUCStringData@@@Z:PPROC
?Release@CString@@KAXPEAUCStringData@@@Z equ <__imp_?Release@CString@@KAXPEAUCStringData@@@Z>

externdef __imp_?ReleaseBuffer@CString@@QEAAXH@Z:PPROC
?ReleaseBuffer@CString@@QEAAXH@Z equ <__imp_?ReleaseBuffer@CString@@QEAAXH@Z>

externdef __imp_?RemoveAll@CMapStringToPtr@@QEAAXXZ:PPROC
?RemoveAll@CMapStringToPtr@@QEAAXXZ equ <__imp_?RemoveAll@CMapStringToPtr@@QEAAXXZ>

externdef __imp_?RemoveAll@CStringArray@@QEAAXXZ:PPROC
?RemoveAll@CStringArray@@QEAAXXZ equ <__imp_?RemoveAll@CStringArray@@QEAAXXZ>

externdef __imp_?RemoveAt@CStringArray@@QEAAXHH@Z:PPROC
?RemoveAt@CStringArray@@QEAAXHH@Z equ <__imp_?RemoveAt@CStringArray@@QEAAXHH@Z>

externdef __imp_?RemoveKey@CMapStringToPtr@@QEAAHPEBG@Z:PPROC
?RemoveKey@CMapStringToPtr@@QEAAHPEBG@Z equ <__imp_?RemoveKey@CMapStringToPtr@@QEAAHPEBG@Z>

externdef __imp_?ReverseFind@CString@@QEBAHG@Z:PPROC
?ReverseFind@CString@@QEBAHG@Z equ <__imp_?ReverseFind@CString@@QEBAHG@Z>

externdef __imp_?Right@CString@@QEBA?AV1@H@Z:PPROC
?Right@CString@@QEBA?AV1@H@Z equ <__imp_?Right@CString@@QEBA?AV1@H@Z>

externdef __imp_?SafeStrlen@CString@@KAHPEBG@Z:PPROC
?SafeStrlen@CString@@KAHPEBG@Z equ <__imp_?SafeStrlen@CString@@KAHPEBG@Z>

externdef __imp_?SetAt@CMapStringToPtr@@QEAAXPEBGPEAX@Z:PPROC
?SetAt@CMapStringToPtr@@QEAAXPEBGPEAX@Z equ <__imp_?SetAt@CMapStringToPtr@@QEAAXPEBGPEAX@Z>

externdef __imp_?SetAt@CString@@QEAAXHG@Z:PPROC
?SetAt@CString@@QEAAXHG@Z equ <__imp_?SetAt@CString@@QEAAXHG@Z>

externdef __imp_?SetAt@CStringArray@@QEAAXHPEBG@Z:PPROC
?SetAt@CStringArray@@QEAAXHPEBG@Z equ <__imp_?SetAt@CStringArray@@QEAAXHPEBG@Z>

externdef __imp_?SetAtGrow@CStringArray@@QEAAXHPEBG@Z:PPROC
?SetAtGrow@CStringArray@@QEAAXHPEBG@Z equ <__imp_?SetAtGrow@CStringArray@@QEAAXHPEBG@Z>

externdef __imp_?SetSize@CStringArray@@QEAAXHH@Z:PPROC
?SetSize@CStringArray@@QEAAXHH@Z equ <__imp_?SetSize@CStringArray@@QEAAXHH@Z>

externdef __imp_?SpanExcluding@CString@@QEBA?AV1@PEBG@Z:PPROC
?SpanExcluding@CString@@QEBA?AV1@PEBG@Z equ <__imp_?SpanExcluding@CString@@QEBA?AV1@PEBG@Z>

externdef __imp_?SpanIncluding@CString@@QEBA?AV1@PEBG@Z:PPROC
?SpanIncluding@CString@@QEBA?AV1@PEBG@Z equ <__imp_?SpanIncluding@CString@@QEBA?AV1@PEBG@Z>

externdef __imp_?TrimLeft@CString@@QEAAXXZ:PPROC
?TrimLeft@CString@@QEAAXXZ equ <__imp_?TrimLeft@CString@@QEAAXXZ>

externdef __imp_?TrimRight@CString@@QEAAXXZ:PPROC
?TrimRight@CString@@QEAAXXZ equ <__imp_?TrimRight@CString@@QEAAXXZ>

externdef __imp_?Unlock@CCriticalSection@@UEAAHXZ:PPROC
?Unlock@CCriticalSection@@UEAAHXZ equ <__imp_?Unlock@CCriticalSection@@UEAAHXZ>

externdef __imp_?Unlock@CSyncObject@@UEAAHJPEAJ@Z:PPROC
?Unlock@CSyncObject@@UEAAHJPEAJ@Z equ <__imp_?Unlock@CSyncObject@@UEAAHJPEAJ@Z>

externdef __imp_?UnlockBuffer@CString@@QEAAXXZ:PPROC
?UnlockBuffer@CString@@QEAAXXZ equ <__imp_?UnlockBuffer@CString@@QEAAXXZ>

externdef __imp_?data@CPlex@@QEAAPEAXXZ:PPROC
?data@CPlex@@QEAAPEAXXZ equ <__imp_?data@CPlex@@QEAAPEAXXZ>
