externdef __imp_SnmpMgrClose:PPROC
SnmpMgrClose equ <__imp_SnmpMgrClose>

externdef __imp_SnmpMgrCtl:PPROC
SnmpMgrCtl equ <__imp_SnmpMgrCtl>

externdef __imp_SnmpMgrGetTrap:PPROC
SnmpMgrGetTrap equ <__imp_SnmpMgrGetTrap>

externdef __imp_SnmpMgrGetTrapEx:PPROC
SnmpMgrGetTrapEx equ <__imp_SnmpMgrGetTrapEx>

externdef __imp_SnmpMgrOidToStr:PPROC
SnmpMgrOidToStr equ <__imp_SnmpMgrOidToStr>

externdef __imp_SnmpMgrOpen:PPROC
SnmpMgrOpen equ <__imp_SnmpMgrOpen>

externdef __imp_SnmpMgrRequest:PPROC
SnmpMgrRequest equ <__imp_SnmpMgrRequest>

externdef __imp_SnmpMgrStrToOid:PPROC
SnmpMgrStrToOid equ <__imp_SnmpMgrStrToOid>

externdef __imp_SnmpMgrTrapListen:PPROC
SnmpMgrTrapListen equ <__imp_SnmpMgrTrapListen>
