externdef __imp_??0?$CEventLock@UAppEvents@@@@QEAA@XZ:PPROC
??0?$CEventLock@UAppEvents@@@@QEAA@XZ equ <__imp_??0?$CEventLock@UAppEvents@@@@QEAA@XZ>

externdef __imp_??0CEventBuffer@@QEAA@AEBV0@@Z:PPROC
??0CEventBuffer@@QEAA@AEBV0@@Z equ <__imp_??0CEventBuffer@@QEAA@AEBV0@@Z>

externdef __imp_??0CEventBuffer@@QEAA@XZ:PPROC
??0CEventBuffer@@QEAA@XZ equ <__imp_??0CEventBuffer@@QEAA@XZ>

externdef __imp_??0CMMCStrongReferences@@AEAA@XZ:PPROC
??0CMMCStrongReferences@@AEAA@XZ equ <__imp_??0CMMCStrongReferences@@AEAA@XZ>

externdef __imp_??0SC@mmcerror@@QEAA@AEBV01@@Z:PPROC
??0SC@mmcerror@@QEAA@AEBV01@@Z equ <__imp_??0SC@mmcerror@@QEAA@AEBV01@@Z>

externdef __imp_??0SC@mmcerror@@QEAA@J@Z:PPROC
??0SC@mmcerror@@QEAA@J@Z equ <__imp_??0SC@mmcerror@@QEAA@J@Z>

externdef __imp_??1?$CEventLock@UAppEvents@@@@QEAA@XZ:PPROC
??1?$CEventLock@UAppEvents@@@@QEAA@XZ equ <__imp_??1?$CEventLock@UAppEvents@@@@QEAA@XZ>

externdef __imp_??1CEventBuffer@@QEAA@XZ:PPROC
??1CEventBuffer@@QEAA@XZ equ <__imp_??1CEventBuffer@@QEAA@XZ>

externdef __imp_??1SC@mmcerror@@QEAA@XZ:PPROC
??1SC@mmcerror@@QEAA@XZ equ <__imp_??1SC@mmcerror@@QEAA@XZ>

externdef __imp_??4?$CEventLock@UAppEvents@@@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CEventLock@UAppEvents@@@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CEventLock@UAppEvents@@@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CEventBuffer@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CEventBuffer@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CEventBuffer@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CMMCStrongReferences@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CMMCStrongReferences@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CMMCStrongReferences@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4SC@mmcerror@@QEAAAEAV01@AEBV01@@Z:PPROC
??4SC@mmcerror@@QEAAAEAV01@AEBV01@@Z equ <__imp_??4SC@mmcerror@@QEAAAEAV01@AEBV01@@Z>

externdef __imp_??4SC@mmcerror@@QEAAAEAV01@J@Z:PPROC
??4SC@mmcerror@@QEAAAEAV01@J@Z equ <__imp_??4SC@mmcerror@@QEAAAEAV01@J@Z>

externdef __imp_??7SC@mmcerror@@QEBAHXZ:PPROC
??7SC@mmcerror@@QEBAHXZ equ <__imp_??7SC@mmcerror@@QEBAHXZ>

externdef __imp_??8SC@mmcerror@@QEBA_NAEBV01@@Z:PPROC
??8SC@mmcerror@@QEBA_NAEBV01@@Z equ <__imp_??8SC@mmcerror@@QEBA_NAEBV01@@Z>

externdef __imp_??8SC@mmcerror@@QEBA_NJ@Z:PPROC
??8SC@mmcerror@@QEBA_NJ@Z equ <__imp_??8SC@mmcerror@@QEBA_NJ@Z>

externdef __imp_??9SC@mmcerror@@QEBA_NAEBV01@@Z:PPROC
??9SC@mmcerror@@QEBA_NAEBV01@@Z equ <__imp_??9SC@mmcerror@@QEBA_NAEBV01@@Z>

externdef __imp_??9SC@mmcerror@@QEBA_NJ@Z:PPROC
??9SC@mmcerror@@QEBA_NJ@Z equ <__imp_??9SC@mmcerror@@QEBA_NJ@Z>

externdef __imp_??BSC@mmcerror@@QEBA_NXZ:PPROC
??BSC@mmcerror@@QEBA_NXZ equ <__imp_??BSC@mmcerror@@QEBA_NXZ>

externdef __imp_??_FSC@mmcerror@@QEAAXXZ:PPROC
??_FSC@mmcerror@@QEAAXXZ equ <__imp_??_FSC@mmcerror@@QEAAXXZ>

externdef __imp_?AddItem@BookKeeping@@SAJAEAVItemHandle@@@Z:PPROC
?AddItem@BookKeeping@@SAJAEAVItemHandle@@@Z equ <__imp_?AddItem@BookKeeping@@SAJAEAVItemHandle@@@Z>

externdef __imp_?AddRef@CMMCStrongReferences@@SAKXZ:PPROC
?AddRef@CMMCStrongReferences@@SAKXZ equ <__imp_?AddRef@CMMCStrongReferences@@SAKXZ>

externdef __imp_?AddSnapin@BookKeeping@@SAJPEBGAEAH@Z:PPROC
?AddSnapin@BookKeeping@@SAJPEBGAEAH@Z equ <__imp_?AddSnapin@BookKeeping@@SAJPEBGAEAH@Z>

externdef __imp_?AddSnapinInterface@BookKeeping@@SA_NPEAUIUnknown@@PEBGAEAH@Z:PPROC
?AddSnapinInterface@BookKeeping@@SA_NPEAUIUnknown@@PEBGAEAH@Z equ <__imp_?AddSnapinInterface@BookKeeping@@SA_NPEAUIUnknown@@PEBGAEAH@Z>

externdef __imp_?CheckCallingThreadID@SC@mmcerror@@QEAAXXZ:PPROC
?CheckCallingThreadID@SC@mmcerror@@QEAAXXZ equ <__imp_?CheckCallingThreadID@SC@mmcerror@@QEAAXXZ>

externdef __imp_?Clear@SC@mmcerror@@QEAAXXZ:PPROC
?Clear@SC@mmcerror@@QEAAXXZ equ <__imp_?Clear@SC@mmcerror@@QEAAXXZ>

externdef __imp_?DumpWatsonTables@BookKeeping@@SAJPEAXPEBGH@Z:PPROC
?DumpWatsonTables@BookKeeping@@SAJPEAXPEBGH@Z equ <__imp_?DumpWatsonTables@BookKeeping@@SAJPEAXPEBGH@Z>

externdef __imp_?EnableDiagnosticMessageBox@BookKeeping@@SA_N_N@Z:PPROC
?EnableDiagnosticMessageBox@BookKeeping@@SA_N_N@Z equ <__imp_?EnableDiagnosticMessageBox@BookKeeping@@SA_N_N@Z>

externdef __imp_?ExceptionFilter@CMMCWatsonAPI@@SAJPEAU_EXCEPTION_POINTERS@@H@Z:PPROC
?ExceptionFilter@CMMCWatsonAPI@@SAJPEAU_EXCEPTION_POINTERS@@H@Z equ <__imp_?ExceptionFilter@CMMCWatsonAPI@@SAJPEAU_EXCEPTION_POINTERS@@H@Z>

externdef __imp_?FatalError@SC@mmcerror@@QEBAXXZ:PPROC
?FatalError@SC@mmcerror@@QEBAXXZ equ <__imp_?FatalError@SC@mmcerror@@QEBAXXZ>

externdef __imp_?FindAllSnapinUIThreads@BookKeeping@@SAJHPEAPEAKPEAK@Z:PPROC
?FindAllSnapinUIThreads@BookKeeping@@SAJHPEAPEAKPEAK@Z equ <__imp_?FindAllSnapinUIThreads@BookKeeping@@SAJHPEAPEAKPEAK@Z>

externdef __imp_?FindAllSnapinUIThreads@BookKeeping@@SAJPEAPEAKPEAK@Z:PPROC
?FindAllSnapinUIThreads@BookKeeping@@SAJPEAPEAKPEAK@Z equ <__imp_?FindAllSnapinUIThreads@BookKeeping@@SAJPEAPEAKPEAK@Z>

externdef __imp_?FindItem@BookKeeping@@SAPEAVItemHandle@@PEAX@Z:PPROC
?FindItem@BookKeeping@@SAPEAVItemHandle@@PEAX@Z equ <__imp_?FindItem@BookKeeping@@SAPEAVItemHandle@@PEAX@Z>

externdef __imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@H@Z:PPROC
?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@H@Z equ <__imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@H@Z>

externdef __imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEAUIUnknown@@@Z:PPROC
?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEAUIUnknown@@@Z equ <__imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEAUIUnknown@@@Z>

externdef __imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEBG@Z:PPROC
?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEBG@Z equ <__imp_?FindSnapin@BookKeeping@@SAAEBVSnapinBookkeepingInfo@@PEBG@Z>

externdef __imp_?ForceException@CMMCWatsonAPI@@SAXH@Z:PPROC
?ForceException@CMMCWatsonAPI@@SAXH@Z equ <__imp_?ForceException@CMMCWatsonAPI@@SAXH@Z>

externdef __imp_?FormatErrorIds@@YAXIVSC@mmcerror@@IPEAG@Z:PPROC
?FormatErrorIds@@YAXIVSC@mmcerror@@IPEAG@Z equ <__imp_?FormatErrorIds@@YAXIVSC@mmcerror@@IPEAG@Z>

externdef __imp_?FormatErrorShort@@YAXVSC@mmcerror@@IPEAG@Z:PPROC
?FormatErrorShort@@YAXVSC@mmcerror@@IPEAG@Z equ <__imp_?FormatErrorShort@@YAXVSC@mmcerror@@IPEAG@Z>

externdef __imp_?FormatErrorString@@YAXPEBGVSC@mmcerror@@IPEAGH@Z:PPROC
?FormatErrorString@@YAXPEBGVSC@mmcerror@@IPEAGH@Z equ <__imp_?FormatErrorString@@YAXPEBGVSC@mmcerror@@IPEAGH@Z>

externdef __imp_?FromLastError@SC@mmcerror@@QEAAAEAV12@XZ:PPROC
?FromLastError@SC@mmcerror@@QEAAAEAV12@XZ equ <__imp_?FromLastError@SC@mmcerror@@QEAAAEAV12@XZ>

externdef __imp_?FromMMC@SC@mmcerror@@QEAAAEAV12@J@Z:PPROC
?FromMMC@SC@mmcerror@@QEAAAEAV12@J@Z equ <__imp_?FromMMC@SC@mmcerror@@QEAAAEAV12@J@Z>

externdef __imp_?FromWin32@SC@mmcerror@@QEAAAEAV12@J@Z:PPROC
?FromWin32@SC@mmcerror@@QEAAAEAV12@J@Z equ <__imp_?FromWin32@SC@mmcerror@@QEAAAEAV12@J@Z>

externdef __imp_?FxSnapinException@BookKeeping@@SA_NHPEBG000H@Z:PPROC
?FxSnapinException@BookKeeping@@SA_NHPEBG000H@Z equ <__imp_?FxSnapinException@BookKeeping@@SA_NHPEBG000H@Z>

externdef __imp_?GetCode@SC@mmcerror@@QEBAJXZ:PPROC
?GetCode@SC@mmcerror@@QEBAJXZ equ <__imp_?GetCode@SC@mmcerror@@QEBAJXZ>

externdef __imp_?GetComObjectEventSource@@YAAEAV?$CEventSource@VCComObjectObserver@@VCVoid@@V2@V2@V2@@@XZ:PPROC
?GetComObjectEventSource@@YAAEAV?$CEventSource@VCComObjectObserver@@VCVoid@@V2@V2@V2@@@XZ equ <__imp_?GetComObjectEventSource@@YAAEAV?$CEventSource@VCComObjectObserver@@VCVoid@@V2@V2@V2@@@XZ>

externdef __imp_?GetErrorMessage@SC@mmcerror@@QEBAXIPEAG@Z:PPROC
?GetErrorMessage@SC@mmcerror@@QEBAXIPEAG@Z equ <__imp_?GetErrorMessage@SC@mmcerror@@QEBAXIPEAG@Z>

externdef __imp_?GetEventBuffer@@YAAEAVCEventBuffer@@XZ:PPROC
?GetEventBuffer@@YAAEAVCEventBuffer@@XZ equ <__imp_?GetEventBuffer@@YAAEAVCEventBuffer@@XZ>

externdef __imp_?GetFacility@SC@mmcerror@@AEBA?AW4facility_type@12@XZ:PPROC
?GetFacility@SC@mmcerror@@AEBA?AW4facility_type@12@XZ equ <__imp_?GetFacility@SC@mmcerror@@AEBA?AW4facility_type@12@XZ>

externdef __imp_?GetFunctionName@SC@mmcerror@@QEBAPEBGXZ:PPROC
?GetFunctionName@SC@mmcerror@@QEBAPEBGXZ equ <__imp_?GetFunctionName@SC@mmcerror@@QEBAPEBGXZ>

externdef __imp_?GetHWnd@SC@mmcerror@@SAPEAUHWND__@@XZ:PPROC
?GetHWnd@SC@mmcerror@@SAPEAUHWND__@@XZ equ <__imp_?GetHWnd@SC@mmcerror@@SAPEAUHWND__@@XZ>

externdef __imp_?GetHelpFile@SC@mmcerror@@SAPEBGXZ:PPROC
?GetHelpFile@SC@mmcerror@@SAPEBGXZ equ <__imp_?GetHelpFile@SC@mmcerror@@SAPEBGXZ>

externdef __imp_?GetHelpID@SC@mmcerror@@QEAAKXZ:PPROC
?GetHelpID@SC@mmcerror@@QEAAKXZ equ <__imp_?GetHelpID@SC@mmcerror@@QEAAKXZ>

externdef __imp_?GetHinst@SC@mmcerror@@SAPEAUHINSTANCE__@@XZ:PPROC
?GetHinst@SC@mmcerror@@SAPEAUHINSTANCE__@@XZ equ <__imp_?GetHinst@SC@mmcerror@@SAPEAUHINSTANCE__@@XZ>

externdef __imp_?GetMainThreadID@SC@mmcerror@@SAKXZ:PPROC
?GetMainThreadID@SC@mmcerror@@SAKXZ equ <__imp_?GetMainThreadID@SC@mmcerror@@SAKXZ>

externdef __imp_?GetModalHWND@SC@mmcerror@@SAPEAUHWND__@@XZ:PPROC
?GetModalHWND@SC@mmcerror@@SAPEAUHWND__@@XZ equ <__imp_?GetModalHWND@SC@mmcerror@@SAPEAUHWND__@@XZ>

externdef __imp_?GetNewSnapinInstanceId@BookKeeping@@SAHXZ:PPROC
?GetNewSnapinInstanceId@BookKeeping@@SAHXZ equ <__imp_?GetNewSnapinInstanceId@BookKeeping@@SAHXZ>

externdef __imp_?GetSingletonObject@CMMCStrongReferences@@CAAEAV1@XZ:PPROC
?GetSingletonObject@CMMCStrongReferences@@CAAEAV1@XZ equ <__imp_?GetSingletonObject@CMMCStrongReferences@@CAAEAV1@XZ>

externdef __imp_?GetSnapinModuleName@BookKeeping@@SAPEBGH@Z:PPROC
?GetSnapinModuleName@BookKeeping@@SAPEBGH@Z equ <__imp_?GetSnapinModuleName@BookKeeping@@SAPEBGH@Z>

externdef __imp_?GetSnapinName@BookKeeping@@SAPEBGH@Z:PPROC
?GetSnapinName@BookKeeping@@SAPEBGH@Z equ <__imp_?GetSnapinName@BookKeeping@@SAPEBGH@Z>

externdef __imp_?GetSnapinName@SC@mmcerror@@QEBAPEBGXZ:PPROC
?GetSnapinName@SC@mmcerror@@QEBAPEBGXZ equ <__imp_?GetSnapinName@SC@mmcerror@@QEBAPEBGXZ>

externdef __imp_?GetStringModule@@YAPEAUHINSTANCE__@@XZ:PPROC
?GetStringModule@@YAPEAUHINSTANCE__@@XZ equ <__imp_?GetStringModule@@YAPEAUHINSTANCE__@@XZ>

externdef __imp_?HrFromSc@@YAJAEBVSC@mmcerror@@@Z:PPROC
?HrFromSc@@YAJAEBVSC@mmcerror@@@Z equ <__imp_?HrFromSc@@YAJAEBVSC@mmcerror@@@Z>

externdef __imp_?InitInstance@BookKeeping@@SAJXZ:PPROC
?InitInstance@BookKeeping@@SAJXZ equ <__imp_?InitInstance@BookKeeping@@SAJXZ>

externdef __imp_?InterfaceFailure@BookKeeping@@SAXHPEBG0@Z:PPROC
?InterfaceFailure@BookKeeping@@SAXHPEBG0@Z equ <__imp_?InterfaceFailure@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?InterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@@Z:PPROC
?InterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@@Z equ <__imp_?InterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@@Z>

externdef __imp_?InterfaceNotFound@BookKeeping@@SAXHPEBG@Z:PPROC
?InterfaceNotFound@BookKeeping@@SAXHPEBG@Z equ <__imp_?InterfaceNotFound@BookKeeping@@SAXHPEBG@Z>

externdef __imp_?InternalAddRef@CMMCStrongReferences@@AEAAKXZ:PPROC
?InternalAddRef@CMMCStrongReferences@@AEAAKXZ equ <__imp_?InternalAddRef@CMMCStrongReferences@@AEAAKXZ>

externdef __imp_?InternalLastRefReleased@CMMCStrongReferences@@AEAA_NXZ:PPROC
?InternalLastRefReleased@CMMCStrongReferences@@AEAA_NXZ equ <__imp_?InternalLastRefReleased@CMMCStrongReferences@@AEAA_NXZ>

externdef __imp_?InternalRelease@CMMCStrongReferences@@AEAAKXZ:PPROC
?InternalRelease@CMMCStrongReferences@@AEAAKXZ equ <__imp_?InternalRelease@CMMCStrongReferences@@AEAAKXZ>

externdef __imp_?InvalidInterface@BookKeeping@@SAXHPEBG0@Z:PPROC
?InvalidInterface@BookKeeping@@SAXHPEBG0@Z equ <__imp_?InvalidInterface@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?InvalidMMCInterface@BookKeeping@@SAXHPEBG0@Z:PPROC
?InvalidMMCInterface@BookKeeping@@SAXHPEBG0@Z equ <__imp_?InvalidMMCInterface@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?InvalidMMCInterfaceRelease@BookKeeping@@SAXHPEBG0@Z:PPROC
?InvalidMMCInterfaceRelease@BookKeeping@@SAXHPEBG0@Z equ <__imp_?InvalidMMCInterfaceRelease@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?IsError@SC@mmcerror@@QEBA_NXZ:PPROC
?IsError@SC@mmcerror@@QEBA_NXZ equ <__imp_?IsError@SC@mmcerror@@QEBA_NXZ>

externdef __imp_?IsLocked@CEventBuffer@@QEAA_NXZ:PPROC
?IsLocked@CEventBuffer@@QEAA_NXZ equ <__imp_?IsLocked@CEventBuffer@@QEAA_NXZ>

externdef __imp_?IsValid@ItemHandle@@SA_NPEBV1@@Z:PPROC
?IsValid@ItemHandle@@SA_NPEBV1@@Z equ <__imp_?IsValid@ItemHandle@@SA_NPEBV1@@Z>

externdef __imp_?LKResult2HRESULT@BookKeeping@@SAJ_J@Z:PPROC
?LKResult2HRESULT@BookKeeping@@SAJ_J@Z equ <__imp_?LKResult2HRESULT@BookKeeping@@SAJ_J@Z>

externdef __imp_?LastRefReleased@CMMCStrongReferences@@SA_NXZ:PPROC
?LastRefReleased@CMMCStrongReferences@@SA_NXZ equ <__imp_?LastRefReleased@CMMCStrongReferences@@SA_NXZ>

externdef __imp_?LoadStandardOverlays@@YAJPEAU_IMAGELIST@@HPEAH1@Z:PPROC
?LoadStandardOverlays@@YAJPEAU_IMAGELIST@@HPEAH1@Z equ <__imp_?LoadStandardOverlays@@YAJPEAU_IMAGELIST@@HPEAH1@Z>

externdef __imp_?Lock@CEventBuffer@@QEAAXXZ:PPROC
?Lock@CEventBuffer@@QEAAXXZ equ <__imp_?Lock@CEventBuffer@@QEAAXXZ>

externdef __imp_?MMCErrorBox@@YAHII@Z:PPROC
?MMCErrorBox@@YAHII@Z equ <__imp_?MMCErrorBox@@YAHII@Z>

externdef __imp_?MMCErrorBox@@YAHIVSC@mmcerror@@I@Z:PPROC
?MMCErrorBox@@YAHIVSC@mmcerror@@I@Z equ <__imp_?MMCErrorBox@@YAHIVSC@mmcerror@@I@Z>

externdef __imp_?MMCErrorBox@@YAHPEBGI@Z:PPROC
?MMCErrorBox@@YAHPEBGI@Z equ <__imp_?MMCErrorBox@@YAHPEBGI@Z>

externdef __imp_?MMCErrorBox@@YAHPEBGVSC@mmcerror@@I@Z:PPROC
?MMCErrorBox@@YAHPEBGVSC@mmcerror@@I@Z equ <__imp_?MMCErrorBox@@YAHPEBGVSC@mmcerror@@I@Z>

externdef __imp_?MMCErrorBox@@YAHVSC@mmcerror@@I@Z:PPROC
?MMCErrorBox@@YAHVSC@mmcerror@@I@Z equ <__imp_?MMCErrorBox@@YAHVSC@mmcerror@@I@Z>

externdef __imp_?MMCInterfaceError@BookKeeping@@SAXHPEBG0@Z:PPROC
?MMCInterfaceError@BookKeeping@@SAXHPEBG0@Z equ <__imp_?MMCInterfaceError@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?MMCInterfaceLeak@BookKeeping@@SAXHPEBG@Z:PPROC
?MMCInterfaceLeak@BookKeeping@@SAXHPEBG@Z equ <__imp_?MMCInterfaceLeak@BookKeeping@@SAXHPEBG@Z>

externdef __imp_?MMCInterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@W4_SnapinError@1@@Z:PPROC
?MMCInterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@W4_SnapinError@1@@Z equ <__imp_?MMCInterfaceMethodException@BookKeeping@@SAXHPEBG0KPEAU_EXCEPTION_POINTERS@@W4_SnapinError@1@@Z>

externdef __imp_?MMCNullInterface@BookKeeping@@SAXHPEBG0@Z:PPROC
?MMCNullInterface@BookKeeping@@SAXHPEBG0@Z equ <__imp_?MMCNullInterface@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?MMCUpdateRegistry@@YAJHPEBVCObjectRegParams@@PEBVCControlRegParams@@@Z:PPROC
?MMCUpdateRegistry@@YAJHPEBVCObjectRegParams@@PEBVCControlRegParams@@@Z equ <__imp_?MMCUpdateRegistry@@YAJHPEBVCObjectRegParams@@PEBVCControlRegParams@@@Z>

externdef __imp_?MMC_PickIconDlg@@YA_JPEAUHWND__@@PEAGIPEAH@Z:PPROC
?MMC_PickIconDlg@@YA_JPEAUHWND__@@PEAGIPEAH@Z equ <__imp_?MMC_PickIconDlg@@YA_JPEAUHWND__@@PEAGIPEAH@Z>

externdef __imp_?MakeSc@SC@mmcerror@@AEAAXW4facility_type@12@J@Z:PPROC
?MakeSc@SC@mmcerror@@AEAAXW4facility_type@12@J@Z equ <__imp_?MakeSc@SC@mmcerror@@AEAAXW4facility_type@12@J@Z>

externdef __imp_?RegisterSnapinInterfaceErrorHandler@BookKeeping@@SAP6A_NAEAVSnapinBookkeepingInfo@@W4_SnapinError@1@PEBG222KPEAU_EXCEPTION_POINTERS@@@ZP6A_N012222K3@Z@Z:PPROC
?RegisterSnapinInterfaceErrorHandler@BookKeeping@@SAP6A_NAEAVSnapinBookkeepingInfo@@W4_SnapinError@1@PEBG222KPEAU_EXCEPTION_POINTERS@@@ZP6A_N012222K3@Z@Z equ <__imp_?RegisterSnapinInterfaceErrorHandler@BookKeeping@@SAP6A_NAEAVSnapinBookkeepingInfo@@W4_SnapinError@1@PEBG222KPEAU_EXCEPTION_POINTERS@@@ZP6A_N012222K3@Z@Z>

externdef __imp_?RegisterThread@BookKeeping@@SAJHHKW4SnapinThreadFlags@1@@Z:PPROC
?RegisterThread@BookKeeping@@SAJHHKW4SnapinThreadFlags@1@@Z equ <__imp_?RegisterThread@BookKeeping@@SAJHHKW4SnapinThreadFlags@1@@Z>

externdef __imp_?Release@CMMCStrongReferences@@SAKXZ:PPROC
?Release@CMMCStrongReferences@@SAKXZ equ <__imp_?Release@CMMCStrongReferences@@SAKXZ>

externdef __imp_?ReleaseSnapinInterface@BookKeeping@@SAJPEAUIUnknown@@H@Z:PPROC
?ReleaseSnapinInterface@BookKeeping@@SAJPEAUIUnknown@@H@Z equ <__imp_?ReleaseSnapinInterface@BookKeeping@@SAJPEAUIUnknown@@H@Z>

externdef __imp_?RemoveItem@BookKeeping@@SAJPEAX@Z:PPROC
?RemoveItem@BookKeeping@@SAJPEAX@Z equ <__imp_?RemoveItem@BookKeeping@@SAJPEAX@Z>

externdef __imp_?SCODEFromSc@@YAJAEBVSC@mmcerror@@@Z:PPROC
?SCODEFromSc@@YAJAEBVSC@mmcerror@@@Z equ <__imp_?SCODEFromSc@@YAJAEBVSC@mmcerror@@@Z>

externdef __imp_?ScEmitOrPostpone@CEventBuffer@@QEAA?AVSC@mmcerror@@PEAUIDispatch@@JPEAVCComVariant@ATL@@H@Z:PPROC
?ScEmitOrPostpone@CEventBuffer@@QEAA?AVSC@mmcerror@@PEAUIDispatch@@JPEAVCComVariant@ATL@@H@Z equ <__imp_?ScEmitOrPostpone@CEventBuffer@@QEAA?AVSC@mmcerror@@PEAUIDispatch@@JPEAVCComVariant@ATL@@H@Z>

externdef __imp_?ScFlushPostponed@CEventBuffer@@AEAA?AVSC@mmcerror@@XZ:PPROC
?ScFlushPostponed@CEventBuffer@@AEAA?AVSC@mmcerror@@XZ equ <__imp_?ScFlushPostponed@CEventBuffer@@AEAA?AVSC@mmcerror@@XZ>

externdef __imp_?ScFromMMC@@YA?AVSC@mmcerror@@J@Z:PPROC
?ScFromMMC@@YA?AVSC@mmcerror@@J@Z equ <__imp_?ScFromMMC@@YA?AVSC@mmcerror@@J@Z>

externdef __imp_?ScGetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@AEAPEAVCConsoleEventDispatcher@@@Z:PPROC
?ScGetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@AEAPEAVCConsoleEventDispatcher@@@Z equ <__imp_?ScGetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@AEAPEAVCConsoleEventDispatcher@@@Z>

externdef __imp_?ScSetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@PEAVCConsoleEventDispatcher@@@Z:PPROC
?ScSetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@PEAVCConsoleEventDispatcher@@@Z equ <__imp_?ScSetConsoleEventDispatcher@CConsoleEventDispatcherProvider@@SA?AVSC@mmcerror@@PEAVCConsoleEventDispatcher@@@Z>

externdef __imp_?SetFunctionName@SC@mmcerror@@QEAAXPEBG@Z:PPROC
?SetFunctionName@SC@mmcerror@@QEAAXPEBG@Z equ <__imp_?SetFunctionName@SC@mmcerror@@QEAAXPEBG@Z>

externdef __imp_?SetHWnd@SC@mmcerror@@SAXPEAUHWND__@@@Z:PPROC
?SetHWnd@SC@mmcerror@@SAXPEAUHWND__@@@Z equ <__imp_?SetHWnd@SC@mmcerror@@SAXPEAUHWND__@@@Z>

externdef __imp_?SetHinst@SC@mmcerror@@SAXPEAUHINSTANCE__@@@Z:PPROC
?SetHinst@SC@mmcerror@@SAXPEAUHINSTANCE__@@@Z equ <__imp_?SetHinst@SC@mmcerror@@SAXPEAUHINSTANCE__@@@Z>

externdef __imp_?SetMainThreadID@SC@mmcerror@@SAXK@Z:PPROC
?SetMainThreadID@SC@mmcerror@@SAXK@Z equ <__imp_?SetMainThreadID@SC@mmcerror@@SAXK@Z>

externdef __imp_?SetModalHWND@SC@mmcerror@@SAPEAUHWND__@@PEAU3@@Z:PPROC
?SetModalHWND@SC@mmcerror@@SAPEAUHWND__@@PEAU3@@Z equ <__imp_?SetModalHWND@SC@mmcerror@@SAPEAUHWND__@@PEAU3@@Z>

externdef __imp_?SetSnapinName@SC@mmcerror@@QEAAXPEBG@Z:PPROC
?SetSnapinName@SC@mmcerror@@QEAAXPEBG@Z equ <__imp_?SetSnapinName@SC@mmcerror@@QEAAXPEBG@Z>

externdef __imp_?Throw@SC@mmcerror@@QEAAXJ@Z:PPROC
?Throw@SC@mmcerror@@QEAAXJ@Z equ <__imp_?Throw@SC@mmcerror@@QEAAXJ@Z>

externdef __imp_?Throw@SC@mmcerror@@QEAAXXZ:PPROC
?Throw@SC@mmcerror@@QEAAXXZ equ <__imp_?Throw@SC@mmcerror@@QEAAXXZ>

externdef __imp_?ToHr@SC@mmcerror@@QEBAJXZ:PPROC
?ToHr@SC@mmcerror@@QEBAJXZ equ <__imp_?ToHr@SC@mmcerror@@QEBAJXZ>

externdef __imp_?TraceAndClear@SC@mmcerror@@QEAAXXZ:PPROC
?TraceAndClear@SC@mmcerror@@QEAAXXZ equ <__imp_?TraceAndClear@SC@mmcerror@@QEAAXXZ>

externdef __imp_?TraceError@@YAXPEBGAEBVSC@mmcerror@@@Z:PPROC
?TraceError@@YAXPEBGAEBVSC@mmcerror@@@Z equ <__imp_?TraceError@@YAXPEBGAEBVSC@mmcerror@@@Z>

externdef __imp_?TraceSnapinError@@YAXPEBGAEBVSC@mmcerror@@@Z:PPROC
?TraceSnapinError@@YAXPEBGAEBVSC@mmcerror@@@Z equ <__imp_?TraceSnapinError@@YAXPEBGAEBVSC@mmcerror@@@Z>

externdef __imp_?Trace_@SC@mmcerror@@QEBAXXZ:PPROC
?Trace_@SC@mmcerror@@QEBAXXZ equ <__imp_?Trace_@SC@mmcerror@@QEBAXXZ>

externdef __imp_?Unlock@CEventBuffer@@QEAAXXZ:PPROC
?Unlock@CEventBuffer@@QEAAXXZ equ <__imp_?Unlock@CEventBuffer@@QEAAXXZ>

externdef __imp_?UnregisterAllSnapinInstanceThreads@BookKeeping@@SAJH@Z:PPROC
?UnregisterAllSnapinInstanceThreads@BookKeeping@@SAJH@Z equ <__imp_?UnregisterAllSnapinInstanceThreads@BookKeeping@@SAJH@Z>

externdef __imp_?UnregisterThread@BookKeeping@@SAJHK@Z:PPROC
?UnregisterThread@BookKeeping@@SAJHK@Z equ <__imp_?UnregisterThread@BookKeeping@@SAJHK@Z>

externdef __imp_?WrongThreadCall@BookKeeping@@SAXHPEBG0@Z:PPROC
?WrongThreadCall@BookKeeping@@SAXHPEBG0@Z equ <__imp_?WrongThreadCall@BookKeeping@@SAXHPEBG0@Z>

externdef __imp_?s_CallDepth@SC@mmcerror@@0IA:PPROC
?s_CallDepth@SC@mmcerror@@0IA equ <__imp_?s_CallDepth@SC@mmcerror@@0IA>
  IFNDEF __UNICODE__
    ?s_CallDepth@SC@mmcerror@@0I equ <__imp_?s_CallDepth@SC@mmcerror@@0IA>
  ENDIF

externdef __imp_?s_dwMainThreadID@SC@mmcerror@@0KA:PPROC
?s_dwMainThreadID@SC@mmcerror@@0KA equ <__imp_?s_dwMainThreadID@SC@mmcerror@@0KA>
  IFNDEF __UNICODE__
    ?s_dwMainThreadID@SC@mmcerror@@0K equ <__imp_?s_dwMainThreadID@SC@mmcerror@@0KA>
  ENDIF

externdef __imp_?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@EA:PPROC
?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@EA equ <__imp_?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@EA>
  IFNDEF __UNICODE__
    ?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@E equ <__imp_?s_hInst@SC@mmcerror@@0PEAUHINSTANCE__@@EA>
  ENDIF

externdef __imp_?s_hWnd@SC@mmcerror@@0PEAUHWND__@@EA:PPROC
?s_hWnd@SC@mmcerror@@0PEAUHWND__@@EA equ <__imp_?s_hWnd@SC@mmcerror@@0PEAUHWND__@@EA>
  IFNDEF __UNICODE__
    ?s_hWnd@SC@mmcerror@@0PEAUHWND__@@E equ <__imp_?s_hWnd@SC@mmcerror@@0PEAUHWND__@@EA>
  ENDIF

externdef __imp_?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@EA:PPROC
?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@EA equ <__imp_?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@EA>
  IFNDEF __UNICODE__
    ?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@E equ <__imp_?s_hWndModal@SC@mmcerror@@0PEAUHWND__@@EA>
  ENDIF

externdef __imp_?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@EA:PPROC
?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@EA equ <__imp_?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@EA>
  IFNDEF __UNICODE__
    ?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@E equ <__imp_?s_pDispatcher@CConsoleEventDispatcherProvider@@0PEAVCConsoleEventDispatcher@@EA>
  ENDIF

externdef __imp_GetAllocCounters:PPROC
GetAllocCounters equ <__imp_GetAllocCounters>

externdef __imp_ReportFxSnapinException:PPROC
ReportFxSnapinException equ <__imp_ReportFxSnapinException>
