externdef __imp_?DisplayAVIBox@@YA_JPEAUHWND__@@PEBG1PEAPEAU1@@Z:PPROC
?DisplayAVIBox@@YA_JPEAUHWND__@@PEBG1PEAPEAU1@@Z equ <__imp_?DisplayAVIBox@@YA_JPEAUHWND__@@PEBG1PEAPEAU1@@Z>

externdef __imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEAUHINSTANCE__@@IIW4ERROR_SRC@@JI@Z:PPROC
?DisplayUserMessage@@YAHPEAUHWND__@@PEAUHINSTANCE__@@IIW4ERROR_SRC@@JI@Z equ <__imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEAUHINSTANCE__@@IIW4ERROR_SRC@@JI@Z>

externdef __imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEBG1W4ERROR_SRC@@JI@Z:PPROC
?DisplayUserMessage@@YAHPEAUHWND__@@PEBG1W4ERROR_SRC@@JI@Z equ <__imp_?DisplayUserMessage@@YAHPEAUHWND__@@PEBG1W4ERROR_SRC@@JI@Z>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_ErrorStringEx:PPROC
ErrorStringEx equ <__imp_ErrorStringEx>
