externdef __imp_??0CDirectDrawSurface@IHammer@@QEAA@PEAUHPALETTE__@@KPEBUtagSIZE@@PEAJ@Z:PPROC
??0CDirectDrawSurface@IHammer@@QEAA@PEAUHPALETTE__@@KPEBUtagSIZE@@PEAJ@Z equ <__imp_??0CDirectDrawSurface@IHammer@@QEAA@PEAUHPALETTE__@@KPEBUtagSIZE@@PEAJ@Z>

externdef __imp_??0CHalftone@@QEAA@PEAUHPALETTE__@@@Z:PPROC
??0CHalftone@@QEAA@PEAUHPALETTE__@@@Z equ <__imp_??0CHalftone@@QEAA@PEAUHPALETTE__@@@Z>

externdef __imp_??0CHalftonePalette@@QEAA@PEAUHPALETTE__@@@Z:PPROC
??0CHalftonePalette@@QEAA@PEAUHPALETTE__@@@Z equ <__imp_??0CHalftonePalette@@QEAA@PEAUHPALETTE__@@@Z>

externdef __imp_??0CHalftonePalette@@QEAA@XZ:PPROC
??0CHalftonePalette@@QEAA@XZ equ <__imp_??0CHalftonePalette@@QEAA@XZ>

externdef __imp_??0CMemManager@@QEAA@XZ:PPROC
??0CMemManager@@QEAA@XZ equ <__imp_??0CMemManager@@QEAA@XZ>

externdef __imp_??0CMemUser@@QEAA@XZ:PPROC
??0CMemUser@@QEAA@XZ equ <__imp_??0CMemUser@@QEAA@XZ>

externdef __imp_??0CTStr@@QEAA@AEAV0@@Z:PPROC
??0CTStr@@QEAA@AEAV0@@Z equ <__imp_??0CTStr@@QEAA@AEAV0@@Z>

externdef __imp_??0CTStr@@QEAA@H@Z:PPROC
??0CTStr@@QEAA@H@Z equ <__imp_??0CTStr@@QEAA@H@Z>

externdef __imp_??0CTStr@@QEAA@PEAD@Z:PPROC
??0CTStr@@QEAA@PEAD@Z equ <__imp_??0CTStr@@QEAA@PEAD@Z>

externdef __imp_??0CTStr@@QEAA@PEAG@Z:PPROC
??0CTStr@@QEAA@PEAG@Z equ <__imp_??0CTStr@@QEAA@PEAG@Z>

externdef __imp_??0CURLArchive@@QEAA@PEAUIUnknown@@@Z:PPROC
??0CURLArchive@@QEAA@PEAUIUnknown@@@Z equ <__imp_??0CURLArchive@@QEAA@PEAUIUnknown@@@Z>

externdef __imp_??0OTrig@@QEAA@XZ:PPROC
??0OTrig@@QEAA@XZ equ <__imp_??0OTrig@@QEAA@XZ>

externdef __imp_??1CMemManager@@UEAA@XZ:PPROC
??1CMemManager@@UEAA@XZ equ <__imp_??1CMemManager@@UEAA@XZ>

externdef __imp_??1CMemUser@@UEAA@XZ:PPROC
??1CMemUser@@UEAA@XZ equ <__imp_??1CMemUser@@UEAA@XZ>

externdef __imp_??1CTStr@@QEAA@XZ:PPROC
??1CTStr@@QEAA@XZ equ <__imp_??1CTStr@@QEAA@XZ>

externdef __imp_??1CURLArchive@@UEAA@XZ:PPROC
??1CURLArchive@@UEAA@XZ equ <__imp_??1CURLArchive@@UEAA@XZ>

externdef __imp_??_FCTStr@@QEAAXXZ:PPROC
??_FCTStr@@QEAAXXZ equ <__imp_??_FCTStr@@QEAAXXZ>

externdef __imp_??_FCURLArchive@@QEAAXXZ:PPROC
??_FCURLArchive@@QEAAXXZ equ <__imp_??_FCURLArchive@@QEAAXXZ>

externdef __imp_?AllocBuffer@CMemManager@@QEAAPEAXKG@Z:PPROC
?AllocBuffer@CMemManager@@QEAAPEAXKG@Z equ <__imp_?AllocBuffer@CMemManager@@QEAAPEAXKG@Z>

externdef __imp_?AllocBuffer@CMemUser@@QEAAPEAUMEMBLOCK_tag@@KG@Z:PPROC
?AllocBuffer@CMemUser@@QEAAPEAUMEMBLOCK_tag@@KG@Z equ <__imp_?AllocBuffer@CMemUser@@QEAAPEAUMEMBLOCK_tag@@KG@Z>

externdef __imp_?AllocBuffer@CTStr@@QEAAHHH@Z:PPROC
?AllocBuffer@CTStr@@QEAAHHH@Z equ <__imp_?AllocBuffer@CTStr@@QEAAHHH@Z>

externdef __imp_?AllocBufferGlb@CMemManager@@SAPEAXKG@Z:PPROC
?AllocBufferGlb@CMemManager@@SAPEAXKG@Z equ <__imp_?AllocBufferGlb@CMemManager@@SAPEAXKG@Z>

externdef __imp_?Atoi@CStringWrapper@@SAHPEBD@Z:PPROC
?Atoi@CStringWrapper@@SAHPEBD@Z equ <__imp_?Atoi@CStringWrapper@@SAHPEBD@Z>

externdef __imp_?Atol@CStringWrapper@@SAJPEBD@Z:PPROC
?Atol@CStringWrapper@@SAJPEBD@Z equ <__imp_?Atol@CStringWrapper@@SAJPEBD@Z>

externdef __imp_?BitCountFromDDPIXELFORMAT@@YAJAEBU_DDPIXELFORMAT@@@Z:PPROC
?BitCountFromDDPIXELFORMAT@@YAJAEBU_DDPIXELFORMAT@@@Z equ <__imp_?BitCountFromDDPIXELFORMAT@@YAJAEBU_DDPIXELFORMAT@@@Z>

externdef __imp_?Close@CURLArchive@@UEAAJXZ:PPROC
?Close@CURLArchive@@UEAAJXZ equ <__imp_?Close@CURLArchive@@UEAAJXZ>

externdef __imp_?CopyFrom@CNonCollapsingDrg@@UEAAHPEAVCDrg@@@Z:PPROC
?CopyFrom@CNonCollapsingDrg@@UEAAHPEAVCDrg@@@Z equ <__imp_?CopyFrom@CNonCollapsingDrg@@UEAAHPEAVCDrg@@@Z>

externdef __imp_?CopyLocal@CURLArchive@@UEAAJPEADH@Z:PPROC
?CopyLocal@CURLArchive@@UEAAJPEADH@Z equ <__imp_?CopyLocal@CURLArchive@@UEAAJPEADH@Z>

externdef __imp_?CopyLocal@CURLArchive@@UEAAJPEAGH@Z:PPROC
?CopyLocal@CURLArchive@@UEAAJPEAGH@Z equ <__imp_?CopyLocal@CURLArchive@@UEAAJPEAGH@Z>

externdef __imp_?Cos@OTrig@@QEAAMJ@Z:PPROC
?Cos@OTrig@@QEAAMJ@Z equ <__imp_?Cos@OTrig@@QEAAMJ@Z>

externdef __imp_?Cos@OTrig@@QEAAMM@Z:PPROC
?Cos@OTrig@@QEAAMM@Z equ <__imp_?Cos@OTrig@@QEAAMM@Z>

externdef __imp_?CosDeg@CMathWrapper@@SAMJ@Z:PPROC
?CosDeg@CMathWrapper@@SAMJ@Z equ <__imp_?CosDeg@CMathWrapper@@SAMJ@Z>

externdef __imp_?CosDeg@CMathWrapper@@SAMM@Z:PPROC
?CosDeg@CMathWrapper@@SAMM@Z equ <__imp_?CosDeg@CMathWrapper@@SAMM@Z>

externdef __imp_?CosDegWrap@CMathWrapper@@SAMJ@Z:PPROC
?CosDegWrap@CMathWrapper@@SAMJ@Z equ <__imp_?CosDegWrap@CMathWrapper@@SAMJ@Z>

externdef __imp_?CosDegWrap@CMathWrapper@@SAMM@Z:PPROC
?CosDegWrap@CMathWrapper@@SAMM@Z equ <__imp_?CosDegWrap@CMathWrapper@@SAMM@Z>

externdef __imp_?CosRad@CMathWrapper@@SANN@Z:PPROC
?CosRad@CMathWrapper@@SANN@Z equ <__imp_?CosRad@CMathWrapper@@SANN@Z>

externdef __imp_?CosWrap@OTrig@@QEAAMJ@Z:PPROC
?CosWrap@OTrig@@QEAAMJ@Z equ <__imp_?CosWrap@OTrig@@QEAAMJ@Z>

externdef __imp_?CosWrap@OTrig@@QEAAMM@Z:PPROC
?CosWrap@OTrig@@QEAAMM@Z equ <__imp_?CosWrap@OTrig@@QEAAMM@Z>

externdef __imp_?Create@CURLArchive@@UEAAJPEBD@Z:PPROC
?Create@CURLArchive@@UEAAJPEBD@Z equ <__imp_?Create@CURLArchive@@UEAAJPEBD@Z>

externdef __imp_?Create@CURLArchive@@UEAAJPEBG@Z:PPROC
?Create@CURLArchive@@UEAAJPEBG@Z equ <__imp_?Create@CURLArchive@@UEAAJPEBG@Z>

externdef __imp_?CreateIDispatchCollection@@YAHPEAPEAUIUnknown@@@Z:PPROC
?CreateIDispatchCollection@@YAHPEAPEAUIUnknown@@@Z equ <__imp_?CreateIDispatchCollection@@YAHPEAPEAUIUnknown@@@Z>

externdef __imp_?DumpAllocations@CMemManager@@QEAAXPEAD@Z:PPROC
?DumpAllocations@CMemManager@@QEAAXPEAD@Z equ <__imp_?DumpAllocations@CMemManager@@QEAAXPEAD@Z>

externdef __imp_?DumpAllocationsGlb@CMemManager@@SAXPEAD@Z:PPROC
?DumpAllocationsGlb@CMemManager@@SAXPEAD@Z equ <__imp_?DumpAllocationsGlb@CMemManager@@SAXPEAD@Z>

externdef __imp_?DumpHeapHeader@CMemManager@@AEAAXPEAUHEAPHEADER_tag@@PEAU_iobuf@@@Z:PPROC
?DumpHeapHeader@CMemManager@@AEAAXPEAUHEAPHEADER_tag@@PEAU_iobuf@@@Z equ <__imp_?DumpHeapHeader@CMemManager@@AEAAXPEAUHEAPHEADER_tag@@PEAU_iobuf@@@Z>

externdef __imp_?DumpMemBlock@CMemManager@@AEAAXPEAUMEMBLOCK_tag@@PEAU_iobuf@@@Z:PPROC
?DumpMemBlock@CMemManager@@AEAAXPEAUMEMBLOCK_tag@@PEAU_iobuf@@@Z equ <__imp_?DumpMemBlock@CMemManager@@AEAAXPEAUMEMBLOCK_tag@@PEAU_iobuf@@@Z>

externdef __imp_?DumpMemUserInfo@CMemManager@@AEAAXPEAUMEMUSERINFO_tag@@PEAU_iobuf@@@Z:PPROC
?DumpMemUserInfo@CMemManager@@AEAAXPEAUMEMUSERINFO_tag@@PEAU_iobuf@@@Z equ <__imp_?DumpMemUserInfo@CMemManager@@AEAAXPEAUMEMUSERINFO_tag@@PEAU_iobuf@@@Z>

externdef __imp_?ExternalDumpAllocations@@YAXPEAD@Z:PPROC
?ExternalDumpAllocations@@YAXPEAD@Z equ <__imp_?ExternalDumpAllocations@@YAXPEAD@Z>

externdef __imp_?FreeBuffer@CMemManager@@QEAAXPEAX@Z:PPROC
?FreeBuffer@CMemManager@@QEAAXPEAX@Z equ <__imp_?FreeBuffer@CMemManager@@QEAAXPEAX@Z>

externdef __imp_?FreeBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z:PPROC
?FreeBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z equ <__imp_?FreeBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z>

externdef __imp_?FreeBuffer@CTStr@@QEAAXXZ:PPROC
?FreeBuffer@CTStr@@QEAAXXZ equ <__imp_?FreeBuffer@CTStr@@QEAAXXZ>

externdef __imp_?FreeBufferGlb@CMemManager@@SAXPEAX@Z:PPROC
?FreeBufferGlb@CMemManager@@SAXPEAX@Z equ <__imp_?FreeBufferGlb@CMemManager@@SAXPEAX@Z>

externdef __imp_?FreeBufferMemBlock@CMemManager@@QEAAXPEAUMEMBLOCK_tag@@@Z:PPROC
?FreeBufferMemBlock@CMemManager@@QEAAXPEAUMEMBLOCK_tag@@@Z equ <__imp_?FreeBufferMemBlock@CMemManager@@QEAAXPEAUMEMBLOCK_tag@@@Z>

externdef __imp_?Gcvt@CStringWrapper@@SAPEADNHPEAD@Z:PPROC
?Gcvt@CStringWrapper@@SAPEADNHPEAD@Z equ <__imp_?Gcvt@CStringWrapper@@SAPEADNHPEAD@Z>

externdef __imp_?GetAt@CNonCollapsingDrg@@UEAAPEAXJ@Z:PPROC
?GetAt@CNonCollapsingDrg@@UEAAPEAXJ@Z equ <__imp_?GetAt@CNonCollapsingDrg@@UEAAPEAXJ@Z>

externdef __imp_?GetFileSize@CURLArchive@@UEAAJAEAJ@Z:PPROC
?GetFileSize@CURLArchive@@UEAAJAEAJ@Z equ <__imp_?GetFileSize@CURLArchive@@UEAAJAEAJ@Z>

externdef __imp_?GetFirst@CNonCollapsingDrg@@UEAAPEAXXZ:PPROC
?GetFirst@CNonCollapsingDrg@@UEAAPEAXXZ equ <__imp_?GetFirst@CNonCollapsingDrg@@UEAAPEAXXZ>

externdef __imp_?GetNext@CNonCollapsingDrg@@UEAAPEAXXZ:PPROC
?GetNext@CNonCollapsingDrg@@UEAAPEAXXZ equ <__imp_?GetNext@CNonCollapsingDrg@@UEAAPEAXXZ>

externdef __imp_?GetSigBitsFrom16BPP@@YAKPEAUHDC__@@@Z:PPROC
?GetSigBitsFrom16BPP@@YAKPEAUHDC__@@@Z equ <__imp_?GetSigBitsFrom16BPP@@YAKPEAUHDC__@@@Z>

externdef __imp_?GetStreamInterface@CURLArchive@@UEBAPEAUIStream@@XZ:PPROC
?GetStreamInterface@CURLArchive@@UEBAPEAUIStream@@XZ equ <__imp_?GetStreamInterface@CURLArchive@@UEBAPEAUIStream@@XZ>

externdef __imp_?Insert@CDrg@@UEAAHPEAXJ@Z:PPROC
?Insert@CDrg@@UEAAHPEAXJ@Z equ <__imp_?Insert@CDrg@@UEAAHPEAXJ@Z>

externdef __imp_?IsMMXCpu@@YAHXZ:PPROC
?IsMMXCpu@@YAHXZ equ <__imp_?IsMMXCpu@@YAHXZ>

externdef __imp_?Iswspace@CStringWrapper@@SAHG@Z:PPROC
?Iswspace@CStringWrapper@@SAHG@Z equ <__imp_?Iswspace@CStringWrapper@@SAHG@Z>

externdef __imp_?Itoa@CStringWrapper@@SAPEADHPEADH@Z:PPROC
?Itoa@CStringWrapper@@SAPEADHPEADH@Z equ <__imp_?Itoa@CStringWrapper@@SAPEADHPEADH@Z>

externdef __imp_?Len@CTStr@@QEAAHXZ:PPROC
?Len@CTStr@@QEAAHXZ equ <__imp_?Len@CTStr@@QEAAHXZ>

externdef __imp_?LoadStringW@CStringWrapper@@SAHPEAUHINSTANCE__@@IPEAGH@Z:PPROC
?LoadStringW@CStringWrapper@@SAHPEAUHINSTANCE__@@IPEAGH@Z equ <__imp_?LoadStringW@CStringWrapper@@SAHPEAUHINSTANCE__@@IPEAGH@Z>

externdef __imp_?LockBuffer@CMemUser@@QEAAPEAXPEAUMEMBLOCK_tag@@@Z:PPROC
?LockBuffer@CMemUser@@QEAAPEAXPEAUMEMBLOCK_tag@@@Z equ <__imp_?LockBuffer@CMemUser@@QEAAPEAXPEAUMEMBLOCK_tag@@@Z>

externdef __imp_?Ltoa@CStringWrapper@@SAPEADJPEADH@Z:PPROC
?Ltoa@CStringWrapper@@SAPEADJPEADH@Z equ <__imp_?Ltoa@CStringWrapper@@SAPEADJPEADH@Z>

externdef __imp_?Mbstowcs@CStringWrapper@@SA_KPEAGPEBD_K@Z:PPROC
?Mbstowcs@CStringWrapper@@SA_KPEAGPEBD_K@Z equ <__imp_?Mbstowcs@CStringWrapper@@SA_KPEAGPEBD_K@Z>

externdef __imp_?Memcmp@CStringWrapper@@SAHPEBX0_K@Z:PPROC
?Memcmp@CStringWrapper@@SAHPEBX0_K@Z equ <__imp_?Memcmp@CStringWrapper@@SAHPEBX0_K@Z>

externdef __imp_?Memcpy@CStringWrapper@@SAPEAXPEAXPEBX_K@Z:PPROC
?Memcpy@CStringWrapper@@SAPEAXPEAXPEBX_K@Z equ <__imp_?Memcpy@CStringWrapper@@SAPEAXPEAXPEBX_K@Z>

externdef __imp_?Memset@CStringWrapper@@SAPEAXPEAXH_K@Z:PPROC
?Memset@CStringWrapper@@SAPEAXPEAXH_K@Z equ <__imp_?Memset@CStringWrapper@@SAPEAXPEAXH_K@Z>

externdef __imp_?NotifyMemUser@CMemUser@@UEAAHPEAUMEMNOTIFY_tag@@@Z:PPROC
?NotifyMemUser@CMemUser@@UEAAHPEAUMEMNOTIFY_tag@@@Z equ <__imp_?NotifyMemUser@CMemUser@@UEAAHPEAUMEMNOTIFY_tag@@@Z>

externdef __imp_?OverheadOfSavePtrDrg@@YAKXZ:PPROC
?OverheadOfSavePtrDrg@@YAKXZ equ <__imp_?OverheadOfSavePtrDrg@@YAKXZ>

externdef __imp_?Pow@CMathWrapper@@SAMNN@Z:PPROC
?Pow@CMathWrapper@@SAMNN@Z equ <__imp_?Pow@CMathWrapper@@SAMNN@Z>

externdef __imp_?ReAllocBuffer@CMemManager@@QEAAPEAXPEAXKG@Z:PPROC
?ReAllocBuffer@CMemManager@@QEAAPEAXPEAXKG@Z equ <__imp_?ReAllocBuffer@CMemManager@@QEAAPEAXPEAXKG@Z>

externdef __imp_?ReAllocBufferGlb@CMemManager@@SAPEAXPEAXKG@Z:PPROC
?ReAllocBufferGlb@CMemManager@@SAPEAXPEAXKG@Z equ <__imp_?ReAllocBufferGlb@CMemManager@@SAPEAXPEAXKG@Z>

externdef __imp_?Read@CURLArchive@@UEAAKPEAEK@Z:PPROC
?Read@CURLArchive@@UEAAKPEAEK@Z equ <__imp_?Read@CURLArchive@@UEAAKPEAEK@Z>

externdef __imp_?ReadBstrFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAPEAG@Z:PPROC
?ReadBstrFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAPEAG@Z equ <__imp_?ReadBstrFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAPEAG@Z>

externdef __imp_?ReadLine@CURLArchive@@UEAAKPEADK@Z:PPROC
?ReadLine@CURLArchive@@UEAAKPEADK@Z equ <__imp_?ReadLine@CURLArchive@@UEAAKPEADK@Z>

externdef __imp_?ReadLine@CURLArchive@@UEAAKPEAGK@Z:PPROC
?ReadLine@CURLArchive@@UEAAKPEAGK@Z equ <__imp_?ReadLine@CURLArchive@@UEAAKPEAGK@Z>

externdef __imp_?ReadLongFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAJ@Z:PPROC
?ReadLongFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAJ@Z equ <__imp_?ReadLongFromPropBag@@YAJPEAUIPropertyBag@@PEAUIErrorLog@@PEADPEAJ@Z>

externdef __imp_?RegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z:PPROC
?RegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z equ <__imp_?RegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z>

externdef __imp_?RegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z:PPROC
?RegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z equ <__imp_?RegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z>

externdef __imp_?Remove@CDrg@@UEAAHPEAXJ@Z:PPROC
?Remove@CDrg@@UEAAHPEAXJ@Z equ <__imp_?Remove@CDrg@@UEAAHPEAXJ@Z>

externdef __imp_?Remove@CNonCollapsingDrg@@UEAAHPEAXJ@Z:PPROC
?Remove@CNonCollapsingDrg@@UEAAHPEAXJ@Z equ <__imp_?Remove@CNonCollapsingDrg@@UEAAHPEAXJ@Z>

externdef __imp_?ResetLength@CTStr@@QEAAXXZ:PPROC
?ResetLength@CTStr@@QEAAXXZ equ <__imp_?ResetLength@CTStr@@QEAAXXZ>

externdef __imp_?RetailEcho@@YAXPEADZZ:PPROC
?RetailEcho@@YAXPEADZZ equ <__imp_?RetailEcho@@YAXPEADZZ>

externdef __imp_?Seek@CURLArchive@@UEAAJJW4origin@1@@Z:PPROC
?Seek@CURLArchive@@UEAAJJW4origin@1@@Z equ <__imp_?Seek@CURLArchive@@UEAAJJW4origin@1@@Z>

externdef __imp_?SetArray@CNonCollapsingDrg@@UEAAXPEAEJI@Z:PPROC
?SetArray@CNonCollapsingDrg@@UEAAXPEAEJI@Z equ <__imp_?SetArray@CNonCollapsingDrg@@UEAAXPEAEJI@Z>

externdef __imp_?SetAt@CNonCollapsingDrg@@UEAAHPEAXJ@Z:PPROC
?SetAt@CNonCollapsingDrg@@UEAAHPEAXJ@Z equ <__imp_?SetAt@CNonCollapsingDrg@@UEAAHPEAXJ@Z>

externdef __imp_?SetNonDefaultSizes@CDrg@@UEAAXII@Z:PPROC
?SetNonDefaultSizes@CDrg@@UEAAXII@Z equ <__imp_?SetNonDefaultSizes@CDrg@@UEAAXII@Z>

externdef __imp_?SetString@CTStr@@QEAAHPEAD@Z:PPROC
?SetString@CTStr@@QEAAHPEAD@Z equ <__imp_?SetString@CTStr@@QEAAHPEAD@Z>

externdef __imp_?SetString@CTStr@@QEAAHPEAG@Z:PPROC
?SetString@CTStr@@QEAAHPEAG@Z equ <__imp_?SetString@CTStr@@QEAAHPEAG@Z>

externdef __imp_?SetStringPointer@CTStr@@QEAAHPEADH@Z:PPROC
?SetStringPointer@CTStr@@QEAAHPEADH@Z equ <__imp_?SetStringPointer@CTStr@@QEAAHPEADH@Z>

externdef __imp_?Sin@OTrig@@QEAAMJ@Z:PPROC
?Sin@OTrig@@QEAAMJ@Z equ <__imp_?Sin@OTrig@@QEAAMJ@Z>

externdef __imp_?Sin@OTrig@@QEAAMM@Z:PPROC
?Sin@OTrig@@QEAAMM@Z equ <__imp_?Sin@OTrig@@QEAAMM@Z>

externdef __imp_?SinDeg@CMathWrapper@@SAMJ@Z:PPROC
?SinDeg@CMathWrapper@@SAMJ@Z equ <__imp_?SinDeg@CMathWrapper@@SAMJ@Z>

externdef __imp_?SinDeg@CMathWrapper@@SAMM@Z:PPROC
?SinDeg@CMathWrapper@@SAMM@Z equ <__imp_?SinDeg@CMathWrapper@@SAMM@Z>

externdef __imp_?SinDegWrap@CMathWrapper@@SAMJ@Z:PPROC
?SinDegWrap@CMathWrapper@@SAMJ@Z equ <__imp_?SinDegWrap@CMathWrapper@@SAMJ@Z>

externdef __imp_?SinDegWrap@CMathWrapper@@SAMM@Z:PPROC
?SinDegWrap@CMathWrapper@@SAMM@Z equ <__imp_?SinDegWrap@CMathWrapper@@SAMM@Z>

externdef __imp_?SinRad@CMathWrapper@@SANN@Z:PPROC
?SinRad@CMathWrapper@@SANN@Z equ <__imp_?SinRad@CMathWrapper@@SANN@Z>

externdef __imp_?SinWrap@OTrig@@QEAAMJ@Z:PPROC
?SinWrap@OTrig@@QEAAMJ@Z equ <__imp_?SinWrap@OTrig@@QEAAMJ@Z>

externdef __imp_?SinWrap@OTrig@@QEAAMM@Z:PPROC
?SinWrap@OTrig@@QEAAMM@Z equ <__imp_?SinWrap@OTrig@@QEAAMM@Z>

externdef __imp_?SizeBuffer@CMemManager@@QEAAKPEAX@Z:PPROC
?SizeBuffer@CMemManager@@QEAAKPEAX@Z equ <__imp_?SizeBuffer@CMemManager@@QEAAKPEAX@Z>

externdef __imp_?SizeBufferGlb@CMemManager@@SAKPEAX@Z:PPROC
?SizeBufferGlb@CMemManager@@SAKPEAX@Z equ <__imp_?SizeBufferGlb@CMemManager@@SAKPEAX@Z>

externdef __imp_?Sprintf@CStringWrapper@@SAHPEADPEBDZZ:PPROC
?Sprintf@CStringWrapper@@SAHPEADPEBDZZ equ <__imp_?Sprintf@CStringWrapper@@SAHPEADPEBDZZ>

externdef __imp_?Sqrt@CMathWrapper@@SAMM@Z:PPROC
?Sqrt@CMathWrapper@@SAMM@Z equ <__imp_?Sqrt@CMathWrapper@@SAMM@Z>

externdef __imp_?Sscanf1@CStringWrapper@@SAHPEBD0PEAX@Z:PPROC
?Sscanf1@CStringWrapper@@SAHPEBD0PEAX@Z equ <__imp_?Sscanf1@CStringWrapper@@SAHPEBD0PEAX@Z>

externdef __imp_?Sscanf2@CStringWrapper@@SAHPEBD0PEAX1@Z:PPROC
?Sscanf2@CStringWrapper@@SAHPEBD0PEAX1@Z equ <__imp_?Sscanf2@CStringWrapper@@SAHPEBD0PEAX1@Z>

externdef __imp_?Sscanf3@CStringWrapper@@SAHPEBD0PEAX11@Z:PPROC
?Sscanf3@CStringWrapper@@SAHPEBD0PEAX11@Z equ <__imp_?Sscanf3@CStringWrapper@@SAHPEBD0PEAX11@Z>

externdef __imp_?Strcat@CStringWrapper@@SAPEADPEADPEBD@Z:PPROC
?Strcat@CStringWrapper@@SAPEADPEADPEBD@Z equ <__imp_?Strcat@CStringWrapper@@SAPEADPEADPEBD@Z>

externdef __imp_?Strchr@CStringWrapper@@SAPEADPEBDD@Z:PPROC
?Strchr@CStringWrapper@@SAPEADPEBDD@Z equ <__imp_?Strchr@CStringWrapper@@SAPEADPEBDD@Z>

externdef __imp_?Strcmp@CStringWrapper@@SAHPEBD0@Z:PPROC
?Strcmp@CStringWrapper@@SAHPEBD0@Z equ <__imp_?Strcmp@CStringWrapper@@SAHPEBD0@Z>

externdef __imp_?Strcpy@CStringWrapper@@SAPEADPEADPEBD@Z:PPROC
?Strcpy@CStringWrapper@@SAPEADPEADPEBD@Z equ <__imp_?Strcpy@CStringWrapper@@SAPEADPEADPEBD@Z>

externdef __imp_?Stricmp@CStringWrapper@@SAHPEBD0@Z:PPROC
?Stricmp@CStringWrapper@@SAHPEBD0@Z equ <__imp_?Stricmp@CStringWrapper@@SAHPEBD0@Z>

externdef __imp_?Strinc@CStringWrapper@@SAPEADPEBD@Z:PPROC
?Strinc@CStringWrapper@@SAPEADPEBD@Z equ <__imp_?Strinc@CStringWrapper@@SAPEADPEBD@Z>

externdef __imp_?Strlen@CStringWrapper@@SAHPEBD@Z:PPROC
?Strlen@CStringWrapper@@SAHPEBD@Z equ <__imp_?Strlen@CStringWrapper@@SAHPEBD@Z>

externdef __imp_?Strncmp@CStringWrapper@@SAHPEBD0_K@Z:PPROC
?Strncmp@CStringWrapper@@SAHPEBD0_K@Z equ <__imp_?Strncmp@CStringWrapper@@SAHPEBD0_K@Z>

externdef __imp_?Strncpy@CStringWrapper@@SAPEADPEADPEBD_K@Z:PPROC
?Strncpy@CStringWrapper@@SAPEADPEADPEBD_K@Z equ <__imp_?Strncpy@CStringWrapper@@SAPEADPEADPEBD_K@Z>

externdef __imp_?Strnicmp@CStringWrapper@@SAHPEBD0_K@Z:PPROC
?Strnicmp@CStringWrapper@@SAHPEBD0_K@Z equ <__imp_?Strnicmp@CStringWrapper@@SAHPEBD0_K@Z>

externdef __imp_?Strrchr@CStringWrapper@@SAPEADPEBDD@Z:PPROC
?Strrchr@CStringWrapper@@SAPEADPEBDD@Z equ <__imp_?Strrchr@CStringWrapper@@SAPEADPEBDD@Z>

externdef __imp_?Strstr@CStringWrapper@@SAPEADPEBD0@Z:PPROC
?Strstr@CStringWrapper@@SAPEADPEBD0@Z equ <__imp_?Strstr@CStringWrapper@@SAPEADPEBD0@Z>

externdef __imp_?Strtok@CStringWrapper@@SAPEADPEADPEBD@Z:PPROC
?Strtok@CStringWrapper@@SAPEADPEADPEBD@Z equ <__imp_?Strtok@CStringWrapper@@SAPEADPEADPEBD@Z>

externdef __imp_?SysAllocString@CTStr@@QEAAPEAGXZ:PPROC
?SysAllocString@CTStr@@QEAAPEAGXZ equ <__imp_?SysAllocString@CTStr@@QEAAPEAGXZ>

externdef __imp_?UnLockBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z:PPROC
?UnLockBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z equ <__imp_?UnLockBuffer@CMemUser@@QEAAXPEAUMEMBLOCK_tag@@@Z>

externdef __imp_?UnRegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z:PPROC
?UnRegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z equ <__imp_?UnRegisterMemUser@CMemManager@@QEAAHPEAVCMemUser@@@Z>

externdef __imp_?UnRegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z:PPROC
?UnRegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z equ <__imp_?UnRegisterMemUserGlb@CMemManager@@SAHPEAVCMemUser@@@Z>

externdef __imp_?WStrCmpin@CStringWrapper@@SAHPEBG0_K@Z:PPROC
?WStrCmpin@CStringWrapper@@SAHPEBG0_K@Z equ <__imp_?WStrCmpin@CStringWrapper@@SAHPEBG0_K@Z>

externdef __imp_?WStrcat@CStringWrapper@@SAPEAGPEAGPEBG@Z:PPROC
?WStrcat@CStringWrapper@@SAPEAGPEAGPEBG@Z equ <__imp_?WStrcat@CStringWrapper@@SAPEAGPEAGPEBG@Z>

externdef __imp_?WStrcpy@CStringWrapper@@SAPEAGPEAGPEBG@Z:PPROC
?WStrcpy@CStringWrapper@@SAPEAGPEAGPEBG@Z equ <__imp_?WStrcpy@CStringWrapper@@SAPEAGPEAGPEBG@Z>

externdef __imp_?WStrlen@CStringWrapper@@SAHPEBG@Z:PPROC
?WStrlen@CStringWrapper@@SAHPEBG@Z equ <__imp_?WStrlen@CStringWrapper@@SAHPEBG@Z>

externdef __imp_?WStrncpy@CStringWrapper@@SAPEAGPEAGPEBG_K@Z:PPROC
?WStrncpy@CStringWrapper@@SAPEAGPEAGPEBG_K@Z equ <__imp_?WStrncpy@CStringWrapper@@SAPEAGPEAGPEBG_K@Z>

externdef __imp_?Wcstombs@CStringWrapper@@SA_KPEADPEBG_K@Z:PPROC
?Wcstombs@CStringWrapper@@SA_KPEADPEBG_K@Z equ <__imp_?Wcstombs@CStringWrapper@@SA_KPEADPEBG_K@Z>

externdef __imp_?Write@CURLArchive@@UEAAKPEAEK@Z:PPROC
?Write@CURLArchive@@UEAAKPEAEK@Z equ <__imp_?Write@CURLArchive@@UEAAKPEAEK@Z>

externdef __imp_?WriteBstrToPropBag@@YAJPEAUIPropertyBag@@PEADPEAG@Z:PPROC
?WriteBstrToPropBag@@YAJPEAUIPropertyBag@@PEADPEAG@Z equ <__imp_?WriteBstrToPropBag@@YAJPEAUIPropertyBag@@PEADPEAG@Z>

externdef __imp_?WriteLongToPropBag@@YAJPEAUIPropertyBag@@PEADJ@Z:PPROC
?WriteLongToPropBag@@YAJPEAUIPropertyBag@@PEADJ@Z equ <__imp_?WriteLongToPropBag@@YAJPEAUIPropertyBag@@PEADJ@Z>

externdef __imp_?psz@CTStr@@QEAAPEADXZ:PPROC
?psz@CTStr@@QEAAPEADXZ equ <__imp_?psz@CTStr@@QEAAPEADXZ>

externdef __imp_?pszA@CTStr@@QEAAPEADXZ:PPROC
?pszA@CTStr@@QEAAPEADXZ equ <__imp_?pszA@CTStr@@QEAAPEADXZ>

externdef __imp_?pszW@CTStr@@QEAAPEAGXZ:PPROC
?pszW@CTStr@@QEAAPEAGXZ equ <__imp_?pszW@CTStr@@QEAAPEAGXZ>

externdef __imp__wcsicmp:PPROC
_wcsicmp equ <__imp__wcsicmp>

externdef __imp__wtoi:PPROC
_wtoi equ <__imp__wtoi>

externdef __imp_fmod:PPROC
fmod equ <__imp_fmod>

externdef __imp_memcmp:PPROC
memcmp equ <__imp_memcmp>

externdef __imp_memset:PPROC
memset equ <__imp_memset>

externdef __imp_setlocale:PPROC
setlocale equ <__imp_setlocale>

externdef __imp_strcpy:PPROC
strcpy equ <__imp_strcpy>

externdef __imp_strlen:PPROC
strlen equ <__imp_strlen>

externdef __imp_swprintf:PPROC
swprintf equ <__imp_swprintf>
