externdef __imp_?CreateInstance@CLogMgr@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PPROC
?CreateInstance@CLogMgr@@SAJPEAPEAV1@PEAUIUnknown@@@Z equ <__imp_?CreateInstance@CLogMgr@@SAJPEAPEAV1@PEAUIUnknown@@@Z>

externdef __imp_?DllGetDTCLOG@@YAHAEBU_GUID@@0PEAPEAX@Z:PPROC
?DllGetDTCLOG@@YAHAEBU_GUID@@0PEAPEAX@Z equ <__imp_?DllGetDTCLOG@@YAHAEBU_GUID@@0PEAPEAX@Z>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllGetDTCLOG2:PPROC
DllGetDTCLOG2 equ <__imp_DllGetDTCLOG2>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
