externdef __imp_??0CCancelRpc@@QEAA@AEBV0@@Z:PPROC
??0CCancelRpc@@QEAA@AEBV0@@Z equ <__imp_??0CCancelRpc@@QEAA@AEBV0@@Z>

externdef __imp_??0CCancelRpc@@QEAA@XZ:PPROC
??0CCancelRpc@@QEAA@XZ equ <__imp_??0CCancelRpc@@QEAA@XZ>

externdef __imp_??0CColumns@@QEAA@AEBV0@@Z:PPROC
??0CColumns@@QEAA@AEBV0@@Z equ <__imp_??0CColumns@@QEAA@AEBV0@@Z>

externdef __imp_??0CColumns@@QEAA@I@Z:PPROC
??0CColumns@@QEAA@I@Z equ <__imp_??0CColumns@@QEAA@I@Z>

externdef __imp_??0CDSBaseUpdate@@QEAA@AEBV0@@Z:PPROC
??0CDSBaseUpdate@@QEAA@AEBV0@@Z equ <__imp_??0CDSBaseUpdate@@QEAA@AEBV0@@Z>

externdef __imp_??0CDSBaseUpdate@@QEAA@XZ:PPROC
??0CDSBaseUpdate@@QEAA@XZ equ <__imp_??0CDSBaseUpdate@@QEAA@XZ>

externdef __imp_??0COutputReport@@QEAA@XZ:PPROC
??0COutputReport@@QEAA@XZ equ <__imp_??0COutputReport@@QEAA@XZ>

externdef __imp_??0CPropertyRestriction@@QEAA@AEBV0@@Z:PPROC
??0CPropertyRestriction@@QEAA@AEBV0@@Z equ <__imp_??0CPropertyRestriction@@QEAA@AEBV0@@Z>

externdef __imp_??0CPropertyRestriction@@QEAA@KAEBKAEBVCMQVariant@@@Z:PPROC
??0CPropertyRestriction@@QEAA@KAEBKAEBVCMQVariant@@@Z equ <__imp_??0CPropertyRestriction@@QEAA@KAEBKAEBVCMQVariant@@@Z>

externdef __imp_??0CPropertyRestriction@@QEAA@XZ:PPROC
??0CPropertyRestriction@@QEAA@XZ equ <__imp_??0CPropertyRestriction@@QEAA@XZ>

externdef __imp_??0CRestriction@@QEAA@AEBV0@@Z:PPROC
??0CRestriction@@QEAA@AEBV0@@Z equ <__imp_??0CRestriction@@QEAA@AEBV0@@Z>

externdef __imp_??0CRestriction@@QEAA@I@Z:PPROC
??0CRestriction@@QEAA@I@Z equ <__imp_??0CRestriction@@QEAA@I@Z>

externdef __imp_??0CSort@@QEAA@AEBV0@@Z:PPROC
??0CSort@@QEAA@AEBV0@@Z equ <__imp_??0CSort@@QEAA@AEBV0@@Z>

externdef __imp_??0CSort@@QEAA@I@Z:PPROC
??0CSort@@QEAA@I@Z equ <__imp_??0CSort@@QEAA@I@Z>

externdef __imp_??0CSortKey@@QEAA@AEBKK@Z:PPROC
??0CSortKey@@QEAA@AEBKK@Z equ <__imp_??0CSortKey@@QEAA@AEBKK@Z>

externdef __imp_??0CSortKey@@QEAA@XZ:PPROC
??0CSortKey@@QEAA@XZ equ <__imp_??0CSortKey@@QEAA@XZ>

externdef __imp_??1CCancelRpc@@QEAA@XZ:PPROC
??1CCancelRpc@@QEAA@XZ equ <__imp_??1CCancelRpc@@QEAA@XZ>

externdef __imp_??1CColumns@@QEAA@XZ:PPROC
??1CColumns@@QEAA@XZ equ <__imp_??1CColumns@@QEAA@XZ>

externdef __imp_??1CDSBaseUpdate@@QEAA@XZ:PPROC
??1CDSBaseUpdate@@QEAA@XZ equ <__imp_??1CDSBaseUpdate@@QEAA@XZ>

externdef __imp_??1COutputReport@@QEAA@XZ:PPROC
??1COutputReport@@QEAA@XZ equ <__imp_??1COutputReport@@QEAA@XZ>

externdef __imp_??1CPropertyRestriction@@QEAA@XZ:PPROC
??1CPropertyRestriction@@QEAA@XZ equ <__imp_??1CPropertyRestriction@@QEAA@XZ>

externdef __imp_??1CRestriction@@QEAA@XZ:PPROC
??1CRestriction@@QEAA@XZ equ <__imp_??1CRestriction@@QEAA@XZ>

externdef __imp_??1CSort@@QEAA@XZ:PPROC
??1CSort@@QEAA@XZ equ <__imp_??1CSort@@QEAA@XZ>

externdef __imp_??1CSortKey@@QEAA@XZ:PPROC
??1CSortKey@@QEAA@XZ equ <__imp_??1CSortKey@@QEAA@XZ>

externdef __imp_??4CCancelRpc@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CCancelRpc@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CCancelRpc@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CDSBaseUpdate@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CDSBaseUpdate@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CDSBaseUpdate@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4COutputReport@@QEAAAEAV0@AEBV0@@Z:PPROC
??4COutputReport@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4COutputReport@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CPropertyRestriction@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CPropertyRestriction@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CPropertyRestriction@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CRestriction@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CRestriction@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CRestriction@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CSortKey@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CSortKey@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CSortKey@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_FCColumns@@QEAAXXZ:PPROC
??_FCColumns@@QEAAXXZ equ <__imp_??_FCColumns@@QEAAXXZ>

externdef __imp_??_FCRestriction@@QEAAXXZ:PPROC
??_FCRestriction@@QEAAXXZ equ <__imp_??_FCRestriction@@QEAAXXZ>

externdef __imp_??_FCSort@@QEAAXXZ:PPROC
??_FCSort@@QEAAXXZ equ <__imp_??_FCSort@@QEAAXXZ>

externdef __imp_?Add@CCancelRpc@@QEAAXPEAX_J@Z:PPROC
?Add@CCancelRpc@@QEAAXPEAX_J@Z equ <__imp_?Add@CCancelRpc@@QEAAXPEAX_J@Z>

externdef __imp_?Add@CColumns@@QEAAXAEBK@Z:PPROC
?Add@CColumns@@QEAAXAEBK@Z equ <__imp_?Add@CColumns@@QEAAXAEBK@Z>

externdef __imp_?Add@CSort@@QEAAXAEBKK@Z:PPROC
?Add@CSort@@QEAAXAEBKK@Z equ <__imp_?Add@CSort@@QEAAXAEBKK@Z>

externdef __imp_?Add@CSort@@QEAAXAEBVCSortKey@@@Z:PPROC
?Add@CSort@@QEAAXAEBVCSortKey@@@Z equ <__imp_?Add@CSort@@QEAAXAEBVCSortKey@@@Z>

externdef __imp_?AddChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@@Z:PPROC
?AddChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@@Z equ <__imp_?AddChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXAEAUtagBLOB@@KK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXAEAUtagBLOB@@KK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXAEAUtagBLOB@@KK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXAEBVCMQVariant@@KK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXAEBVCMQVariant@@KK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXAEBVCMQVariant@@KK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXEKK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXEKK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXEKK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXFKK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXFKK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXFKK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXJKK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXJKK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXJKK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXKKK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXKKK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXKKK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXPEAGKK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXPEAGKK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXPEAGKK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXPEAU_GUID@@KK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXPEAU_GUID@@KK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXPEAU_GUID@@KK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCACLSID@@KK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXPEAUtagCACLSID@@KK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCACLSID@@KK@Z>

externdef __imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCALPWSTR@@KK@Z:PPROC
?AddRestriction@CRestriction@@QEAAXPEAUtagCALPWSTR@@KK@Z equ <__imp_?AddRestriction@CRestriction@@QEAAXPEAUtagCALPWSTR@@KK@Z>

externdef __imp_?CancelRequests@CCancelRpc@@QEAAX_J@Z:PPROC
?CancelRequests@CCancelRpc@@QEAAX_J@Z equ <__imp_?CancelRequests@CCancelRpc@@QEAAX_J@Z>

externdef __imp_?CancelThread@CCancelRpc@@CAKPEAX@Z:PPROC
?CancelThread@CCancelRpc@@CAKPEAX@Z equ <__imp_?CancelThread@CCancelRpc@@CAKPEAX@Z>

externdef __imp_?CastToStruct@CColumns@@QEAAPEAUtagMQCOLUMNSET@@XZ:PPROC
?CastToStruct@CColumns@@QEAAPEAUtagMQCOLUMNSET@@XZ equ <__imp_?CastToStruct@CColumns@@QEAAPEAUtagMQCOLUMNSET@@XZ>

externdef __imp_?CastToStruct@CRestriction@@QEAAPEAUtagMQRESTRICTION@@XZ:PPROC
?CastToStruct@CRestriction@@QEAAPEAUtagMQRESTRICTION@@XZ equ <__imp_?CastToStruct@CRestriction@@QEAAPEAUtagMQRESTRICTION@@XZ>

externdef __imp_?CastToStruct@CSort@@QEAAPEAUtagMQSORTSET@@XZ:PPROC
?CastToStruct@CSort@@QEAAPEAUtagMQSORTSET@@XZ equ <__imp_?CastToStruct@CSort@@QEAAPEAUtagMQSORTSET@@XZ>

externdef __imp_?ComposeRPCEndPointName@@YAXPEBG0PEAPEAG@Z:PPROC
?ComposeRPCEndPointName@@YAXPEBG0PEAPEAG@Z equ <__imp_?ComposeRPCEndPointName@@YAXPEBG0PEAPEAG@Z>

externdef __imp_?CopyProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAU2@@Z:PPROC
?CopyProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAU2@@Z equ <__imp_?CopyProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAU2@@Z>

externdef __imp_?Count@CColumns@@QEBAIXZ:PPROC
?Count@CColumns@@QEBAIXZ equ <__imp_?Count@CColumns@@QEBAIXZ>

externdef __imp_?Count@CRestriction@@QEBAIXZ:PPROC
?Count@CRestriction@@QEBAIXZ equ <__imp_?Count@CRestriction@@QEBAIXZ>

externdef __imp_?Count@CSort@@QEBAIXZ:PPROC
?Count@CSort@@QEBAIXZ equ <__imp_?Count@CSort@@QEBAIXZ>

externdef __imp_?DeleteFalconKeyValue@@YAJPEBG@Z:PPROC
?DeleteFalconKeyValue@@YAJPEBG@Z equ <__imp_?DeleteFalconKeyValue@@YAJPEBG@Z>

externdef __imp_?DeleteProperty@CDSBaseUpdate@@AEAAXAEAUtagPROPVARIANT@@@Z:PPROC
?DeleteProperty@CDSBaseUpdate@@AEAAXAEAUtagPROPVARIANT@@@Z equ <__imp_?DeleteProperty@CDSBaseUpdate@@AEAAXAEAUtagPROPVARIANT@@@Z>

externdef __imp_?Get@CColumns@@QEBAAEBKI@Z:PPROC
?Get@CColumns@@QEBAAEBKI@Z equ <__imp_?Get@CColumns@@QEBAAEBKI@Z>

externdef __imp_?Get@CSort@@QEBAAEBVCSortKey@@I@Z:PPROC
?Get@CSort@@QEBAAEBVCSortKey@@I@Z equ <__imp_?Get@CSort@@QEBAAEBVCSortKey@@I@Z>

externdef __imp_?GetChild@CRestriction@@QEBAAEBVCPropertyRestriction@@I@Z:PPROC
?GetChild@CRestriction@@QEBAAEBVCPropertyRestriction@@I@Z equ <__imp_?GetChild@CRestriction@@QEBAAEBVCPropertyRestriction@@I@Z>

externdef __imp_?GetCommand@CDSBaseUpdate@@QEAAEXZ:PPROC
?GetCommand@CDSBaseUpdate@@QEAAEXZ equ <__imp_?GetCommand@CDSBaseUpdate@@QEAAEXZ>

externdef __imp_?GetComputerDnsNameInternal@@YAJPEAGPEAK@Z:PPROC
?GetComputerDnsNameInternal@@YAJPEAGPEAK@Z equ <__imp_?GetComputerDnsNameInternal@@YAJPEAGPEAK@Z>

externdef __imp_?GetComputerNameInternal@@YAJPEAGPEAK@Z:PPROC
?GetComputerNameInternal@@YAJPEAGPEAK@Z equ <__imp_?GetComputerNameInternal@@YAJPEAGPEAK@Z>

externdef __imp_?GetFalconKey@@YAJPEBGPEAPEAUHKEY__@@@Z:PPROC
?GetFalconKey@@YAJPEBGPEAPEAUHKEY__@@@Z equ <__imp_?GetFalconKey@@YAJPEBGPEAPEAUHKEY__@@@Z>

externdef __imp_?GetFalconSectionName@@YAPEBGXZ:PPROC
?GetFalconSectionName@@YAPEBGXZ equ <__imp_?GetFalconSectionName@@YAPEBGXZ>

externdef __imp_?GetFalconServiceName@@YAKPEAGK@Z:PPROC
?GetFalconServiceName@@YAKPEAGK@Z equ <__imp_?GetFalconServiceName@@YAKPEAGK@Z>

externdef __imp_?GetGuidIdentifier@CDSBaseUpdate@@QEAAPEAU_GUID@@XZ:PPROC
?GetGuidIdentifier@CDSBaseUpdate@@QEAAPEAU_GUID@@XZ equ <__imp_?GetGuidIdentifier@CDSBaseUpdate@@QEAAPEAU_GUID@@XZ>

externdef __imp_?GetMasterId@CDSBaseUpdate@@QEAAPEBU_GUID@@XZ:PPROC
?GetMasterId@CDSBaseUpdate@@QEAAPEBU_GUID@@XZ equ <__imp_?GetMasterId@CDSBaseUpdate@@QEAAPEBU_GUID@@XZ>

externdef __imp_?GetObjectType@CDSBaseUpdate@@QEAAKXZ:PPROC
?GetObjectType@CDSBaseUpdate@@QEAAKXZ equ <__imp_?GetObjectType@CDSBaseUpdate@@QEAAKXZ>

externdef __imp_?GetOrder@CSortKey@@QEBAKXZ:PPROC
?GetOrder@CSortKey@@QEBAKXZ equ <__imp_?GetOrder@CSortKey@@QEBAKXZ>

externdef __imp_?GetPathName@CDSBaseUpdate@@QEAAPEAGXZ:PPROC
?GetPathName@CDSBaseUpdate@@QEAAPEAGXZ equ <__imp_?GetPathName@CDSBaseUpdate@@QEAAPEAGXZ>

externdef __imp_?GetPrevSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ:PPROC
?GetPrevSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ equ <__imp_?GetPrevSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ>

externdef __imp_?GetProperty@CSortKey@@QEBAAEBKXZ:PPROC
?GetProperty@CSortKey@@QEBAAEBKXZ equ <__imp_?GetProperty@CSortKey@@QEBAAEBKXZ>

externdef __imp_?GetProps@CDSBaseUpdate@@QEAAPEAKXZ:PPROC
?GetProps@CDSBaseUpdate@@QEAAPEAKXZ equ <__imp_?GetProps@CDSBaseUpdate@@QEAAPEAKXZ>

externdef __imp_?GetPurgeSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ:PPROC
?GetPurgeSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ equ <__imp_?GetPurgeSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ>

externdef __imp_?GetSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ:PPROC
?GetSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ equ <__imp_?GetSeqNum@CDSBaseUpdate@@QEBAAEBVCSeqNum@@XZ>

externdef __imp_?GetSerializeSize@CDSBaseUpdate@@QEAAJPEAK@Z:PPROC
?GetSerializeSize@CDSBaseUpdate@@QEAAJPEAK@Z equ <__imp_?GetSerializeSize@CDSBaseUpdate@@QEAAJPEAK@Z>

externdef __imp_?GetThisServerIpPort@@YAJPEAGK@Z:PPROC
?GetThisServerIpPort@@YAJPEAGK@Z equ <__imp_?GetThisServerIpPort@@YAJPEAGK@Z>

externdef __imp_?GetVars@CDSBaseUpdate@@QEAAPEAUtagPROPVARIANT@@XZ:PPROC
?GetVars@CDSBaseUpdate@@QEAAPEAUtagPROPVARIANT@@XZ equ <__imp_?GetVars@CDSBaseUpdate@@QEAAPEAUtagPROPVARIANT@@XZ>

externdef __imp_?Grow@CRestriction@@AEAAXXZ:PPROC
?Grow@CRestriction@@AEAAXXZ equ <__imp_?Grow@CRestriction@@AEAAXXZ>

externdef __imp_?HashMessageProperties@@YAJ_KPEBEKK1KPEBGKPEBUQUEUE_FORMAT@@3@Z:PPROC
?HashMessageProperties@@YAJ_KPEBEKK1KPEBGKPEBUQUEUE_FORMAT@@3@Z equ <__imp_?HashMessageProperties@@YAJ_KPEBEKK1KPEBGKPEBUQUEUE_FORMAT@@3@Z>

externdef __imp_?HashProperties@@YAJ_KKPEAKPEAUtagPROPVARIANT@@@Z:PPROC
?HashProperties@@YAJ_KKPEAKPEAUtagPROPVARIANT@@@Z equ <__imp_?HashProperties@@YAJ_KKPEAKPEAUtagPROPVARIANT@@@Z>

externdef __imp_?Init@CCancelRpc@@QEAAXXZ:PPROC
?Init@CCancelRpc@@QEAAXXZ equ <__imp_?Init@CCancelRpc@@QEAAXXZ>

externdef __imp_?Init@CDSBaseUpdate@@QEAAJPEBEPEAKH@Z:PPROC
?Init@CDSBaseUpdate@@QEAAJPEBEPEAKH@Z equ <__imp_?Init@CDSBaseUpdate@@QEAAJPEBEPEAKH@Z>

externdef __imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEK0KPEAKPEAUtagPROPVARIANT@@@Z:PPROC
?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEK0KPEAKPEAUtagPROPVARIANT@@@Z equ <__imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEK0KPEAKPEAUtagPROPVARIANT@@@Z>

externdef __imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEKPEAGKPEAKPEAUtagPROPVARIANT@@@Z:PPROC
?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEKPEAGKPEAKPEAUtagPROPVARIANT@@@Z equ <__imp_?Init@CDSBaseUpdate@@QEAAJPEBU_GUID@@AEBVCSeqNum@@11HEKPEAGKPEAKPEAUtagPROPVARIANT@@@Z>

externdef __imp_?InitProperty@CDSBaseUpdate@@AEAAJPEBEPEAKKAEAUtagPROPVARIANT@@@Z:PPROC
?InitProperty@CDSBaseUpdate@@AEAAJPEBEPEAKKAEAUtagPROPVARIANT@@@Z equ <__imp_?InitProperty@CDSBaseUpdate@@AEAAJPEBEPEAKKAEAUtagPROPVARIANT@@@Z>

externdef __imp_?IsLocalSystemCluster@@YA_NXZ:PPROC
?IsLocalSystemCluster@@YA_NXZ equ <__imp_?IsLocalSystemCluster@@YA_NXZ>

externdef __imp_?KeepErrorHistory@COutputReport@@QEAAXPEBGGJ@Z:PPROC
?KeepErrorHistory@COutputReport@@QEAAXPEBGGJ@Z equ <__imp_?KeepErrorHistory@COutputReport@@QEAAXPEBGGJ@Z>

externdef __imp_?MQSetCaConfig@@YAJKPEAVMQ_CA_CONFIG@@@Z:PPROC
?MQSetCaConfig@@YAJKPEAVMQ_CA_CONFIG@@@Z equ <__imp_?MQSetCaConfig@@YAJKPEAVMQ_CA_CONFIG@@@Z>

externdef __imp_?ProcessEvents@CCancelRpc@@AEAAXXZ:PPROC
?ProcessEvents@CCancelRpc@@AEAAXXZ equ <__imp_?ProcessEvents@CCancelRpc@@AEAAXXZ>

externdef __imp_?ProduceRPCErrorTracing@@YAXPEAGK@Z:PPROC
?ProduceRPCErrorTracing@@YAXPEAGK@Z equ <__imp_?ProduceRPCErrorTracing@@YAXPEAGK@Z>

externdef __imp_?Relation@CPropertyRestriction@@QEAAKXZ:PPROC
?Relation@CPropertyRestriction@@QEAAKXZ equ <__imp_?Relation@CPropertyRestriction@@QEAAKXZ>

externdef __imp_?Remove@CCancelRpc@@QEAAXPEAX@Z:PPROC
?Remove@CCancelRpc@@QEAAXPEAX@Z equ <__imp_?Remove@CCancelRpc@@QEAAXPEAX@Z>

externdef __imp_?Remove@CColumns@@QEAAXI@Z:PPROC
?Remove@CColumns@@QEAAXI@Z equ <__imp_?Remove@CColumns@@QEAAXI@Z>

externdef __imp_?Remove@CSort@@QEAAXI@Z:PPROC
?Remove@CSort@@QEAAXI@Z equ <__imp_?Remove@CSort@@QEAAXI@Z>

externdef __imp_?Report@@3VCOutputReport@@A:PPROC
?Report@@3VCOutputReport@@A equ <__imp_?Report@@3VCOutputReport@@A>
  IFNDEF __UNICODE__
    ?Report@@3VCOutputReport@@ equ <__imp_?Report@@3VCOutputReport@@A>
  ENDIF

externdef __imp_?RpcCancelTimeout@CCancelRpc@@QEAAKXZ:PPROC
?RpcCancelTimeout@CCancelRpc@@QEAAKXZ equ <__imp_?RpcCancelTimeout@CCancelRpc@@QEAAKXZ>

externdef __imp_?Serialize@CDSBaseUpdate@@QEAAJPEAEPEAKH@Z:PPROC
?Serialize@CDSBaseUpdate@@QEAAJPEAEPEAKH@Z equ <__imp_?Serialize@CDSBaseUpdate@@QEAAJPEAEPEAKH@Z>

externdef __imp_?SerializeProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAEPEAK@Z:PPROC
?SerializeProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAEPEAK@Z equ <__imp_?SerializeProperty@CDSBaseUpdate@@AEAAJAEAUtagPROPVARIANT@@PEAEPEAK@Z>

externdef __imp_?SetChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@I@Z:PPROC
?SetChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@I@Z equ <__imp_?SetChild@CRestriction@@QEAAXAEBVCPropertyRestriction@@I@Z>

externdef __imp_?SetOrder@CSortKey@@QEAAXAEBK@Z:PPROC
?SetOrder@CSortKey@@QEAAXAEBK@Z equ <__imp_?SetOrder@CSortKey@@QEAAXAEBK@Z>

externdef __imp_?SetPrevSeqNum@CDSBaseUpdate@@QEAAXAEAVCSeqNum@@@Z:PPROC
?SetPrevSeqNum@CDSBaseUpdate@@QEAAXAEAVCSeqNum@@@Z equ <__imp_?SetPrevSeqNum@CDSBaseUpdate@@QEAAXAEAVCSeqNum@@@Z>

externdef __imp_?SetProperty@CPropertyRestriction@@QEAAXAEBK@Z:PPROC
?SetProperty@CPropertyRestriction@@QEAAXAEBK@Z equ <__imp_?SetProperty@CPropertyRestriction@@QEAAXAEBK@Z>

externdef __imp_?SetProperty@CSortKey@@QEAAXAEBK@Z:PPROC
?SetProperty@CSortKey@@QEAAXAEBK@Z equ <__imp_?SetProperty@CSortKey@@QEAAXAEBK@Z>

externdef __imp_?SetRelation@CPropertyRestriction@@QEAAXK@Z:PPROC
?SetRelation@CPropertyRestriction@@QEAAXK@Z equ <__imp_?SetRelation@CPropertyRestriction@@QEAAXK@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXAEBVCMQVariant@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXAEBVCMQVariant@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXAEBVCMQVariant@@@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXE@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXE@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXE@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXF@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXF@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXF@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXJ@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXJ@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXJ@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXK@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXK@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXK@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXPEAG@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCACLSID@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXPEAUtagCACLSID@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCACLSID@@@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCALPWSTR@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXPEAUtagCALPWSTR@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAUtagCALPWSTR@@@Z>

externdef __imp_?ShutDownCancelThread@CCancelRpc@@QEAAXXZ:PPROC
?ShutDownCancelThread@CCancelRpc@@QEAAXXZ equ <__imp_?ShutDownCancelThread@CCancelRpc@@QEAAXXZ>

externdef __imp_?UnalignedWcslen@@YA_KPEFBG@Z:PPROC
?UnalignedWcslen@@YA_KPEFBG@Z equ <__imp_?UnalignedWcslen@@YA_KPEFBG@Z>

externdef __imp_?Value@CPropertyRestriction@@QEAAAEBVCMQVariant@@XZ:PPROC
?Value@CPropertyRestriction@@QEAAAEBVCMQVariant@@XZ equ <__imp_?Value@CPropertyRestriction@@QEAAAEBVCMQVariant@@XZ>

externdef __imp_?XactGetDTC@@YAJPEAPEAUIUnknown@@@Z:PPROC
?XactGetDTC@@YAJPEAPEAUIUnknown@@@Z equ <__imp_?XactGetDTC@@YAJPEAPEAUIUnknown@@@Z>

externdef __imp_?XactGetWhereabouts@@YAJPEAKPEAE@Z:PPROC
?XactGetWhereabouts@@YAJPEAKPEAE@Z equ <__imp_?XactGetWhereabouts@@YAJPEAKPEAE@Z>

externdef __imp_?g_CancelRpc@@3VCCancelRpc@@A:PPROC
?g_CancelRpc@@3VCCancelRpc@@A equ <__imp_?g_CancelRpc@@3VCCancelRpc@@A>
  IFNDEF __UNICODE__
    ?g_CancelRpc@@3VCCancelRpc@@ equ <__imp_?g_CancelRpc@@3VCCancelRpc@@A>
  ENDIF

externdef __imp_?g_hProvVer@@3VCHCryptProv@@A:PPROC
?g_hProvVer@@3VCHCryptProv@@A equ <__imp_?g_hProvVer@@3VCHCryptProv@@A>
  IFNDEF __UNICODE__
    ?g_hProvVer@@3VCHCryptProv@@ equ <__imp_?g_hProvVer@@3VCHCryptProv@@A>
  ENDIF

externdef __imp_?getNumOfProps@CDSBaseUpdate@@QEAAEXZ:PPROC
?getNumOfProps@CDSBaseUpdate@@QEAAEXZ equ <__imp_?getNumOfProps@CDSBaseUpdate@@QEAAEXZ>

externdef __imp_?mqrpcBindQMService@@YAJPEAG0PEAKPEAPEAXW4PORTTYPE@@P6AKPEAXK@ZK@Z:PPROC
?mqrpcBindQMService@@YAJPEAG0PEAKPEAPEAXW4PORTTYPE@@P6AKPEAXK@ZK@Z equ <__imp_?mqrpcBindQMService@@YAJPEAG0PEAKPEAPEAXW4PORTTYPE@@P6AKPEAXK@ZK@Z>

externdef __imp_?mqrpcGetLocalCallPID@@YAKPEAX@Z:PPROC
?mqrpcGetLocalCallPID@@YAKPEAX@Z equ <__imp_?mqrpcGetLocalCallPID@@YAKPEAX@Z>

externdef __imp_?mqrpcIsLocalCall@@YAHPEAX@Z:PPROC
?mqrpcIsLocalCall@@YAHPEAX@Z equ <__imp_?mqrpcIsLocalCall@@YAHPEAX@Z>

externdef __imp_?mqrpcIsTcpipTransport@@YAHPEAX@Z:PPROC
?mqrpcIsTcpipTransport@@YAHPEAX@Z equ <__imp_?mqrpcIsTcpipTransport@@YAHPEAX@Z>

externdef __imp_?mqrpcUnbindQMService@@YAJPEAPEAXPEAPEAG@Z:PPROC
?mqrpcUnbindQMService@@YAJPEAPEAXPEAPEAG@Z equ <__imp_?mqrpcUnbindQMService@@YAJPEAPEAXPEAPEAG@Z>

externdef __imp_FreeContextHandle:PPROC
FreeContextHandle equ <__imp_FreeContextHandle>

externdef __imp_GetDomainFQDNName:PPROC
GetDomainFQDNName equ <__imp_GetDomainFQDNName>

externdef __imp_GetFalconKeyValue:PPROC
GetFalconKeyValue equ <__imp_GetFalconKeyValue>

externdef __imp_GetSizes:PPROC
GetSizes equ <__imp_GetSizes>

externdef __imp_MQSealBuffer:PPROC
MQSealBuffer equ <__imp_MQSealBuffer>

externdef __imp_MQSec_AccessCheck:PPROC
MQSec_AccessCheck equ <__imp_MQSec_AccessCheck>

externdef __imp_MQSec_AccessCheckForSelf:PPROC
MQSec_AccessCheckForSelf equ <__imp_MQSec_AccessCheckForSelf>

externdef __imp_MQSec_AcquireCryptoProvider:PPROC
MQSec_AcquireCryptoProvider equ <__imp_MQSec_AcquireCryptoProvider>

externdef __imp_MQSec_CanGenerateAudit:PPROC
MQSec_CanGenerateAudit equ <__imp_MQSec_CanGenerateAudit>

externdef __imp_MQSec_ConvertSDToNT4Format:PPROC
MQSec_ConvertSDToNT4Format equ <__imp_MQSec_ConvertSDToNT4Format>

externdef __imp_MQSec_ConvertSDToNT5Format:PPROC
MQSec_ConvertSDToNT5Format equ <__imp_MQSec_ConvertSDToNT5Format>

externdef __imp_MQSec_CopySecurityDescriptor:PPROC
MQSec_CopySecurityDescriptor equ <__imp_MQSec_CopySecurityDescriptor>

externdef __imp_MQSec_GetAdminSid:PPROC
MQSec_GetAdminSid equ <__imp_MQSec_GetAdminSid>

externdef __imp_MQSec_GetAnonymousSid:PPROC
MQSec_GetAnonymousSid equ <__imp_MQSec_GetAnonymousSid>

externdef __imp_MQSec_GetCryptoProvProperty:PPROC
MQSec_GetCryptoProvProperty equ <__imp_MQSec_GetCryptoProvProperty>

externdef __imp_MQSec_GetDefaultSecDescriptor:PPROC
MQSec_GetDefaultSecDescriptor equ <__imp_MQSec_GetDefaultSecDescriptor>

externdef __imp_MQSec_GetImpersonationObject:PPROC
MQSec_GetImpersonationObject equ <__imp_MQSec_GetImpersonationObject>

externdef __imp_MQSec_GetLocalMachineSid:PPROC
MQSec_GetLocalMachineSid equ <__imp_MQSec_GetLocalMachineSid>

externdef __imp_MQSec_GetLocalSystemSid:PPROC
MQSec_GetLocalSystemSid equ <__imp_MQSec_GetLocalSystemSid>

externdef __imp_MQSec_GetNetworkServiceSid:PPROC
MQSec_GetNetworkServiceSid equ <__imp_MQSec_GetNetworkServiceSid>

externdef __imp_MQSec_GetProcessSid:PPROC
MQSec_GetProcessSid equ <__imp_MQSec_GetProcessSid>

externdef __imp_MQSec_GetProcessUserSid:PPROC
MQSec_GetProcessUserSid equ <__imp_MQSec_GetProcessUserSid>

externdef __imp_MQSec_GetPubKeysFromDS:PPROC
MQSec_GetPubKeysFromDS equ <__imp_MQSec_GetPubKeysFromDS>

externdef __imp_MQSec_GetThreadUserSid:PPROC
MQSec_GetThreadUserSid equ <__imp_MQSec_GetThreadUserSid>

externdef __imp_MQSec_GetUserType:PPROC
MQSec_GetUserType equ <__imp_MQSec_GetUserType>

externdef __imp_MQSec_GetWorldSid:PPROC
MQSec_GetWorldSid equ <__imp_MQSec_GetWorldSid>

externdef __imp_MQSec_IsAnonymusSid:PPROC
MQSec_IsAnonymusSid equ <__imp_MQSec_IsAnonymusSid>

externdef __imp_MQSec_IsDC:PPROC
MQSec_IsDC equ <__imp_MQSec_IsDC>

externdef __imp_MQSec_IsGuestSid:PPROC
MQSec_IsGuestSid equ <__imp_MQSec_IsGuestSid>

externdef __imp_MQSec_IsNetworkServiceSid:PPROC
MQSec_IsNetworkServiceSid equ <__imp_MQSec_IsNetworkServiceSid>

externdef __imp_MQSec_IsSystemSid:PPROC
MQSec_IsSystemSid equ <__imp_MQSec_IsSystemSid>

externdef __imp_MQSec_IsUnAuthenticatedUser:PPROC
MQSec_IsUnAuthenticatedUser equ <__imp_MQSec_IsUnAuthenticatedUser>

externdef __imp_MQSec_MakeAbsoluteSD:PPROC
MQSec_MakeAbsoluteSD equ <__imp_MQSec_MakeAbsoluteSD>

externdef __imp_MQSec_MakeSelfRelative:PPROC
MQSec_MakeSelfRelative equ <__imp_MQSec_MakeSelfRelative>

externdef __imp_MQSec_MergeSecurityDescriptors:PPROC
MQSec_MergeSecurityDescriptors equ <__imp_MQSec_MergeSecurityDescriptors>

externdef __imp_MQSec_PackPublicKey:PPROC
MQSec_PackPublicKey equ <__imp_MQSec_PackPublicKey>

externdef __imp_MQSec_RpcAuthnLevel:PPROC
MQSec_RpcAuthnLevel equ <__imp_MQSec_RpcAuthnLevel>

externdef __imp_MQSec_SetLocalRpcMutualAuth:PPROC
MQSec_SetLocalRpcMutualAuth equ <__imp_MQSec_SetLocalRpcMutualAuth>

externdef __imp_MQSec_SetPrivilegeInThread:PPROC
MQSec_SetPrivilegeInThread equ <__imp_MQSec_SetPrivilegeInThread>

externdef __imp_MQSec_SetSecurityDescriptorDacl:PPROC
MQSec_SetSecurityDescriptorDacl equ <__imp_MQSec_SetSecurityDescriptorDacl>

externdef __imp_MQSec_StorePubKeys:PPROC
MQSec_StorePubKeys equ <__imp_MQSec_StorePubKeys>

externdef __imp_MQSec_StorePubKeysInDS:PPROC
MQSec_StorePubKeysInDS equ <__imp_MQSec_StorePubKeysInDS>

externdef __imp_MQSec_TraceThreadTokenInfo:PPROC
MQSec_TraceThreadTokenInfo equ <__imp_MQSec_TraceThreadTokenInfo>

externdef __imp_MQSec_UnpackPublicKey:PPROC
MQSec_UnpackPublicKey equ <__imp_MQSec_UnpackPublicKey>

externdef __imp_MQSec_UpdateLocalMachineSid:PPROC
MQSec_UpdateLocalMachineSid equ <__imp_MQSec_UpdateLocalMachineSid>

externdef __imp_MQSigCloneCertFromReg:PPROC
MQSigCloneCertFromReg equ <__imp_MQSigCloneCertFromReg>

externdef __imp_MQSigCloneCertFromSysStore:PPROC
MQSigCloneCertFromSysStore equ <__imp_MQSigCloneCertFromSysStore>

externdef __imp_MQSigCreateCertificate:PPROC
MQSigCreateCertificate equ <__imp_MQSigCreateCertificate>

externdef __imp_MQSigHashMessageProperties:PPROC
MQSigHashMessageProperties equ <__imp_MQSigHashMessageProperties>

externdef __imp_MQSigOpenUserCertStore:PPROC
MQSigOpenUserCertStore equ <__imp_MQSigOpenUserCertStore>

externdef __imp_MQUInitGlobalScurityVars:PPROC
MQUInitGlobalScurityVars equ <__imp_MQUInitGlobalScurityVars>

externdef __imp_MQsspi_InitServerAuthntication:PPROC
MQsspi_InitServerAuthntication equ <__imp_MQsspi_InitServerAuthntication>

externdef __imp_MSMQGetOperatingSystem:PPROC
MSMQGetOperatingSystem equ <__imp_MSMQGetOperatingSystem>

externdef __imp_ServerAcceptSecCtx:PPROC
ServerAcceptSecCtx equ <__imp_ServerAcceptSecCtx>

externdef __imp_SetFalconKeyValue:PPROC
SetFalconKeyValue equ <__imp_SetFalconKeyValue>

externdef __imp_SetFalconServiceName:PPROC
SetFalconServiceName equ <__imp_SetFalconServiceName>

externdef __imp_ShutDownDebugWindow:PPROC
ShutDownDebugWindow equ <__imp_ShutDownDebugWindow>
