externdef __imp_acmDriverAddA:PPROC
acmDriverAddA equ <__imp_acmDriverAddA>
  IFNDEF __UNICODE__
    acmDriverAdd equ <__imp_acmDriverAddA>
  ENDIF

externdef __imp_acmDriverAddW:PPROC
acmDriverAddW equ <__imp_acmDriverAddW>
  IFDEF __UNICODE__
    acmDriverAdd equ <__imp_acmDriverAddW>
  ENDIF

externdef __imp_acmDriverClose:PPROC
acmDriverClose equ <__imp_acmDriverClose>

externdef __imp_acmDriverDetailsA:PPROC
acmDriverDetailsA equ <__imp_acmDriverDetailsA>
  IFNDEF __UNICODE__
    acmDriverDetails equ <__imp_acmDriverDetailsA>
  ENDIF

externdef __imp_acmDriverDetailsW:PPROC
acmDriverDetailsW equ <__imp_acmDriverDetailsW>
  IFDEF __UNICODE__
    acmDriverDetails equ <__imp_acmDriverDetailsW>
  ENDIF

externdef __imp_acmDriverEnum:PPROC
acmDriverEnum equ <__imp_acmDriverEnum>

externdef __imp_acmDriverID:PPROC
acmDriverID equ <__imp_acmDriverID>

externdef __imp_acmDriverMessage:PPROC
acmDriverMessage equ <__imp_acmDriverMessage>

externdef __imp_acmDriverOpen:PPROC
acmDriverOpen equ <__imp_acmDriverOpen>

externdef __imp_acmDriverPriority:PPROC
acmDriverPriority equ <__imp_acmDriverPriority>

externdef __imp_acmDriverRemove:PPROC
acmDriverRemove equ <__imp_acmDriverRemove>

externdef __imp_acmFilterChooseA:PPROC
acmFilterChooseA equ <__imp_acmFilterChooseA>
  IFNDEF __UNICODE__
    acmFilterChoose equ <__imp_acmFilterChooseA>
  ENDIF

externdef __imp_acmFilterChooseW:PPROC
acmFilterChooseW equ <__imp_acmFilterChooseW>
  IFDEF __UNICODE__
    acmFilterChoose equ <__imp_acmFilterChooseW>
  ENDIF

externdef __imp_acmFilterDetailsA:PPROC
acmFilterDetailsA equ <__imp_acmFilterDetailsA>
  IFNDEF __UNICODE__
    acmFilterDetails equ <__imp_acmFilterDetailsA>
  ENDIF

externdef __imp_acmFilterDetailsW:PPROC
acmFilterDetailsW equ <__imp_acmFilterDetailsW>
  IFDEF __UNICODE__
    acmFilterDetails equ <__imp_acmFilterDetailsW>
  ENDIF

externdef __imp_acmFilterEnumA:PPROC
acmFilterEnumA equ <__imp_acmFilterEnumA>
  IFNDEF __UNICODE__
    acmFilterEnum equ <__imp_acmFilterEnumA>
  ENDIF

externdef __imp_acmFilterEnumW:PPROC
acmFilterEnumW equ <__imp_acmFilterEnumW>
  IFDEF __UNICODE__
    acmFilterEnum equ <__imp_acmFilterEnumW>
  ENDIF

externdef __imp_acmFilterTagDetailsA:PPROC
acmFilterTagDetailsA equ <__imp_acmFilterTagDetailsA>
  IFNDEF __UNICODE__
    acmFilterTagDetails equ <__imp_acmFilterTagDetailsA>
  ENDIF

externdef __imp_acmFilterTagDetailsW:PPROC
acmFilterTagDetailsW equ <__imp_acmFilterTagDetailsW>
  IFDEF __UNICODE__
    acmFilterTagDetails equ <__imp_acmFilterTagDetailsW>
  ENDIF

externdef __imp_acmFilterTagEnumA:PPROC
acmFilterTagEnumA equ <__imp_acmFilterTagEnumA>
  IFNDEF __UNICODE__
    acmFilterTagEnum equ <__imp_acmFilterTagEnumA>
  ENDIF

externdef __imp_acmFilterTagEnumW:PPROC
acmFilterTagEnumW equ <__imp_acmFilterTagEnumW>
  IFDEF __UNICODE__
    acmFilterTagEnum equ <__imp_acmFilterTagEnumW>
  ENDIF

externdef __imp_acmFormatChooseA:PPROC
acmFormatChooseA equ <__imp_acmFormatChooseA>
  IFNDEF __UNICODE__
    acmFormatChoose equ <__imp_acmFormatChooseA>
  ENDIF

externdef __imp_acmFormatChooseW:PPROC
acmFormatChooseW equ <__imp_acmFormatChooseW>
  IFDEF __UNICODE__
    acmFormatChoose equ <__imp_acmFormatChooseW>
  ENDIF

externdef __imp_acmFormatDetailsA:PPROC
acmFormatDetailsA equ <__imp_acmFormatDetailsA>
  IFNDEF __UNICODE__
    acmFormatDetails equ <__imp_acmFormatDetailsA>
  ENDIF

externdef __imp_acmFormatDetailsW:PPROC
acmFormatDetailsW equ <__imp_acmFormatDetailsW>
  IFDEF __UNICODE__
    acmFormatDetails equ <__imp_acmFormatDetailsW>
  ENDIF

externdef __imp_acmFormatEnumA:PPROC
acmFormatEnumA equ <__imp_acmFormatEnumA>
  IFNDEF __UNICODE__
    acmFormatEnum equ <__imp_acmFormatEnumA>
  ENDIF

externdef __imp_acmFormatEnumW:PPROC
acmFormatEnumW equ <__imp_acmFormatEnumW>
  IFDEF __UNICODE__
    acmFormatEnum equ <__imp_acmFormatEnumW>
  ENDIF

externdef __imp_acmFormatSuggest:PPROC
acmFormatSuggest equ <__imp_acmFormatSuggest>

externdef __imp_acmFormatTagDetailsA:PPROC
acmFormatTagDetailsA equ <__imp_acmFormatTagDetailsA>
  IFNDEF __UNICODE__
    acmFormatTagDetails equ <__imp_acmFormatTagDetailsA>
  ENDIF

externdef __imp_acmFormatTagDetailsW:PPROC
acmFormatTagDetailsW equ <__imp_acmFormatTagDetailsW>
  IFDEF __UNICODE__
    acmFormatTagDetails equ <__imp_acmFormatTagDetailsW>
  ENDIF

externdef __imp_acmFormatTagEnumA:PPROC
acmFormatTagEnumA equ <__imp_acmFormatTagEnumA>
  IFNDEF __UNICODE__
    acmFormatTagEnum equ <__imp_acmFormatTagEnumA>
  ENDIF

externdef __imp_acmFormatTagEnumW:PPROC
acmFormatTagEnumW equ <__imp_acmFormatTagEnumW>
  IFDEF __UNICODE__
    acmFormatTagEnum equ <__imp_acmFormatTagEnumW>
  ENDIF

externdef __imp_acmGetVersion:PPROC
acmGetVersion equ <__imp_acmGetVersion>

externdef __imp_acmMetrics:PPROC
acmMetrics equ <__imp_acmMetrics>

externdef __imp_acmStreamClose:PPROC
acmStreamClose equ <__imp_acmStreamClose>

externdef __imp_acmStreamConvert:PPROC
acmStreamConvert equ <__imp_acmStreamConvert>

externdef __imp_acmStreamMessage:PPROC
acmStreamMessage equ <__imp_acmStreamMessage>

externdef __imp_acmStreamOpen:PPROC
acmStreamOpen equ <__imp_acmStreamOpen>

externdef __imp_acmStreamPrepareHeader:PPROC
acmStreamPrepareHeader equ <__imp_acmStreamPrepareHeader>

externdef __imp_acmStreamReset:PPROC
acmStreamReset equ <__imp_acmStreamReset>

externdef __imp_acmStreamSize:PPROC
acmStreamSize equ <__imp_acmStreamSize>

externdef __imp_acmStreamUnprepareHeader:PPROC
acmStreamUnprepareHeader equ <__imp_acmStreamUnprepareHeader>
