externdef __imp_??0CCritSec@@QEAA@XZ:PPROC
??0CCritSec@@QEAA@XZ equ <__imp_??0CCritSec@@QEAA@XZ>

externdef __imp_??0CDoubleList@@QEAA@XZ:PPROC
??0CDoubleList@@QEAA@XZ equ <__imp_??0CDoubleList@@QEAA@XZ>

externdef __imp_??0CEXAutoBackupFile@@QEAA@PEBG@Z:PPROC
??0CEXAutoBackupFile@@QEAA@PEBG@Z equ <__imp_??0CEXAutoBackupFile@@QEAA@PEBG@Z>

externdef __imp_??0CEXAutoBackupFile@@QEAA@XZ:PPROC
??0CEXAutoBackupFile@@QEAA@XZ equ <__imp_??0CEXAutoBackupFile@@QEAA@XZ>

externdef __imp_??0CExFileOperation@@QEAA@XZ:PPROC
??0CExFileOperation@@QEAA@XZ equ <__imp_??0CExFileOperation@@QEAA@XZ>

externdef __imp_??0CFakeLock@@QEAA@XZ:PPROC
??0CFakeLock@@QEAA@XZ equ <__imp_??0CFakeLock@@QEAA@XZ>

externdef __imp_??0CLKRHashTable@@AEAA@AEBV0@@Z:PPROC
??0CLKRHashTable@@AEAA@AEBV0@@Z equ <__imp_??0CLKRHashTable@@AEAA@AEBV0@@Z>

externdef __imp_??0CLKRHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z:PPROC
??0CLKRHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z equ <__imp_??0CLKRHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z>

externdef __imp_??0CLKRHashTableStats@@QEAA@XZ:PPROC
??0CLKRHashTableStats@@QEAA@XZ equ <__imp_??0CLKRHashTableStats@@QEAA@XZ>

externdef __imp_??0CLKRLinearHashTable@@AEAA@AEBV0@@Z:PPROC
??0CLKRLinearHashTable@@AEAA@AEBV0@@Z equ <__imp_??0CLKRLinearHashTable@@AEAA@AEBV0@@Z>

externdef __imp_??0CLKRLinearHashTable@@AEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAVCLKRHashTable@@@Z:PPROC
??0CLKRLinearHashTable@@AEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAVCLKRHashTable@@@Z equ <__imp_??0CLKRLinearHashTable@@AEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAVCLKRHashTable@@@Z>

externdef __imp_??0CLKRLinearHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z:PPROC
??0CLKRLinearHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z equ <__imp_??0CLKRLinearHashTable@@QEAA@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKK@Z>

externdef __imp_??0CLockedDoubleList@@QEAA@XZ:PPROC
??0CLockedDoubleList@@QEAA@XZ equ <__imp_??0CLockedDoubleList@@QEAA@XZ>

externdef __imp_??0CLockedSingleList@@QEAA@XZ:PPROC
??0CLockedSingleList@@QEAA@XZ equ <__imp_??0CLockedSingleList@@QEAA@XZ>

externdef __imp_??0CReaderWriterLock2@@QEAA@XZ:PPROC
??0CReaderWriterLock2@@QEAA@XZ equ <__imp_??0CReaderWriterLock2@@QEAA@XZ>

externdef __imp_??0CReaderWriterLock3@@QEAA@XZ:PPROC
??0CReaderWriterLock3@@QEAA@XZ equ <__imp_??0CReaderWriterLock3@@QEAA@XZ>

externdef __imp_??0CReaderWriterLock@@QEAA@XZ:PPROC
??0CReaderWriterLock@@QEAA@XZ equ <__imp_??0CReaderWriterLock@@QEAA@XZ>

externdef __imp_??0CSingleList@@QEAA@XZ:PPROC
??0CSingleList@@QEAA@XZ equ <__imp_??0CSingleList@@QEAA@XZ>

externdef __imp_??0CSmallSpinLock@@QEAA@XZ:PPROC
??0CSmallSpinLock@@QEAA@XZ equ <__imp_??0CSmallSpinLock@@QEAA@XZ>

externdef __imp_??0CSpinLock@@QEAA@XZ:PPROC
??0CSpinLock@@QEAA@XZ equ <__imp_??0CSpinLock@@QEAA@XZ>

externdef __imp_??1CCritSec@@QEAA@XZ:PPROC
??1CCritSec@@QEAA@XZ equ <__imp_??1CCritSec@@QEAA@XZ>

externdef __imp_??1CDoubleList@@QEAA@XZ:PPROC
??1CDoubleList@@QEAA@XZ equ <__imp_??1CDoubleList@@QEAA@XZ>

externdef __imp_??1CEXAutoBackupFile@@QEAA@XZ:PPROC
??1CEXAutoBackupFile@@QEAA@XZ equ <__imp_??1CEXAutoBackupFile@@QEAA@XZ>

externdef __imp_??1CExFileOperation@@QEAA@XZ:PPROC
??1CExFileOperation@@QEAA@XZ equ <__imp_??1CExFileOperation@@QEAA@XZ>

externdef __imp_??1CFakeLock@@QEAA@XZ:PPROC
??1CFakeLock@@QEAA@XZ equ <__imp_??1CFakeLock@@QEAA@XZ>

externdef __imp_??1CLKRHashTable@@QEAA@XZ:PPROC
??1CLKRHashTable@@QEAA@XZ equ <__imp_??1CLKRHashTable@@QEAA@XZ>

externdef __imp_??1CLKRLinearHashTable@@QEAA@XZ:PPROC
??1CLKRLinearHashTable@@QEAA@XZ equ <__imp_??1CLKRLinearHashTable@@QEAA@XZ>

externdef __imp_??1CLockedDoubleList@@QEAA@XZ:PPROC
??1CLockedDoubleList@@QEAA@XZ equ <__imp_??1CLockedDoubleList@@QEAA@XZ>

externdef __imp_??1CLockedSingleList@@QEAA@XZ:PPROC
??1CLockedSingleList@@QEAA@XZ equ <__imp_??1CLockedSingleList@@QEAA@XZ>

externdef __imp_??1CReaderWriterLock2@@QEAA@XZ:PPROC
??1CReaderWriterLock2@@QEAA@XZ equ <__imp_??1CReaderWriterLock2@@QEAA@XZ>

externdef __imp_??1CReaderWriterLock3@@QEAA@XZ:PPROC
??1CReaderWriterLock3@@QEAA@XZ equ <__imp_??1CReaderWriterLock3@@QEAA@XZ>

externdef __imp_??1CReaderWriterLock@@QEAA@XZ:PPROC
??1CReaderWriterLock@@QEAA@XZ equ <__imp_??1CReaderWriterLock@@QEAA@XZ>

externdef __imp_??1CSingleList@@QEAA@XZ:PPROC
??1CSingleList@@QEAA@XZ equ <__imp_??1CSingleList@@QEAA@XZ>

externdef __imp_??1CSmallSpinLock@@QEAA@XZ:PPROC
??1CSmallSpinLock@@QEAA@XZ equ <__imp_??1CSmallSpinLock@@QEAA@XZ>

externdef __imp_??1CSpinLock@@QEAA@XZ:PPROC
??1CSpinLock@@QEAA@XZ equ <__imp_??1CSpinLock@@QEAA@XZ>

externdef __imp_??4?$CLockBase@$00$00$02$00$02$01@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$00$00$02$00$02$01@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$00$00$02$00$02$01@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4?$CLockBase@$01$00$00$00$02$01@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$01$00$00$00$02$01@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$01$00$00$00$02$01@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4?$CLockBase@$02$00$00$00$00$00@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$02$00$00$00$00$00@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$02$00$00$00$00$00@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4?$CLockBase@$03$00$00$01$02$02@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$03$00$00$01$02$02@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$03$00$00$01$02$02@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4?$CLockBase@$04$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$04$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$04$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4?$CLockBase@$05$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$05$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$05$01$01$00$02$01@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4?$CLockBase@$06$01$00$00$02$01@@QEAAAEAV0@AEBV0@@Z:PPROC
??4?$CLockBase@$06$01$00$00$02$01@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4?$CLockBase@$06$01$00$00$02$01@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CCritSec@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CCritSec@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CCritSec@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CDoubleList@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CDoubleList@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CDoubleList@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CEXAutoBackupFile@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CEXAutoBackupFile@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CEXAutoBackupFile@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CExFileOperation@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CExFileOperation@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CExFileOperation@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CFakeLock@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CFakeLock@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CFakeLock@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CLKRHashTable@@AEAAAEAV0@AEBV0@@Z:PPROC
??4CLKRHashTable@@AEAAAEAV0@AEBV0@@Z equ <__imp_??4CLKRHashTable@@AEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CLKRHashTableStats@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CLKRHashTableStats@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CLKRHashTableStats@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CLKRLinearHashTable@@AEAAAEAV0@AEBV0@@Z:PPROC
??4CLKRLinearHashTable@@AEAAAEAV0@AEBV0@@Z equ <__imp_??4CLKRLinearHashTable@@AEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CLockedDoubleList@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CLockedDoubleList@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CLockedDoubleList@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CLockedSingleList@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CLockedSingleList@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CLockedSingleList@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CMdVersionInfo@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CMdVersionInfo@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CMdVersionInfo@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CReaderWriterLock2@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CReaderWriterLock2@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CReaderWriterLock2@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CReaderWriterLock3@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CReaderWriterLock3@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CReaderWriterLock3@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CReaderWriterLock@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CReaderWriterLock@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CReaderWriterLock@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CSingleList@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CSingleList@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CSingleList@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CSmallSpinLock@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CSmallSpinLock@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CSmallSpinLock@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CSpinLock@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CSpinLock@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CSpinLock@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_?Apply@CLKRHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z:PPROC
?Apply@CLKRHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z equ <__imp_?Apply@CLKRHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z>

externdef __imp_?Apply@CLKRLinearHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z:PPROC
?Apply@CLKRLinearHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z equ <__imp_?Apply@CLKRLinearHashTable@@QEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@@Z>

externdef __imp_?ApplyIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z:PPROC
?ApplyIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z equ <__imp_?ApplyIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z>

externdef __imp_?ApplyIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z:PPROC
?ApplyIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z equ <__imp_?ApplyIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@@Z>

externdef __imp_?BackupFile@CEXAutoBackupFile@@QEAAJPEBG@Z:PPROC
?BackupFile@CEXAutoBackupFile@@QEAAJPEBG@Z equ <__imp_?BackupFile@CEXAutoBackupFile@@QEAAJPEBG@Z>

externdef __imp_?BucketIndex@CLKRHashTableStats@@SAJJ@Z:PPROC
?BucketIndex@CLKRHashTableStats@@SAJJ@Z equ <__imp_?BucketIndex@CLKRHashTableStats@@SAJJ@Z>

externdef __imp_?BucketSize@CLKRHashTableStats@@SAJJ@Z:PPROC
?BucketSize@CLKRHashTableStats@@SAJJ@Z equ <__imp_?BucketSize@CLKRHashTableStats@@SAJJ@Z>

externdef __imp_?BucketSizes@CLKRHashTableStats@@SAPEBJXZ:PPROC
?BucketSizes@CLKRHashTableStats@@SAPEBJXZ equ <__imp_?BucketSizes@CLKRHashTableStats@@SAPEBJXZ>

externdef __imp_?CheckTable@CLKRHashTable@@QEBAHXZ:PPROC
?CheckTable@CLKRHashTable@@QEBAHXZ equ <__imp_?CheckTable@CLKRHashTable@@QEBAHXZ>

externdef __imp_?CheckTable@CLKRLinearHashTable@@QEBAHXZ:PPROC
?CheckTable@CLKRLinearHashTable@@QEBAHXZ equ <__imp_?CheckTable@CLKRLinearHashTable@@QEBAHXZ>

externdef __imp_?ClassName@CCritSec@@SAPEBDXZ:PPROC
?ClassName@CCritSec@@SAPEBDXZ equ <__imp_?ClassName@CCritSec@@SAPEBDXZ>

externdef __imp_?ClassName@CFakeLock@@SAPEBDXZ:PPROC
?ClassName@CFakeLock@@SAPEBDXZ equ <__imp_?ClassName@CFakeLock@@SAPEBDXZ>

externdef __imp_?ClassName@CLKRHashTable@@SAPEBDXZ:PPROC
?ClassName@CLKRHashTable@@SAPEBDXZ equ <__imp_?ClassName@CLKRHashTable@@SAPEBDXZ>

externdef __imp_?ClassName@CLKRLinearHashTable@@SAPEBDXZ:PPROC
?ClassName@CLKRLinearHashTable@@SAPEBDXZ equ <__imp_?ClassName@CLKRLinearHashTable@@SAPEBDXZ>

externdef __imp_?ClassName@CReaderWriterLock2@@SAPEBDXZ:PPROC
?ClassName@CReaderWriterLock2@@SAPEBDXZ equ <__imp_?ClassName@CReaderWriterLock2@@SAPEBDXZ>

externdef __imp_?ClassName@CReaderWriterLock3@@SAPEBDXZ:PPROC
?ClassName@CReaderWriterLock3@@SAPEBDXZ equ <__imp_?ClassName@CReaderWriterLock3@@SAPEBDXZ>

externdef __imp_?ClassName@CReaderWriterLock@@SAPEBDXZ:PPROC
?ClassName@CReaderWriterLock@@SAPEBDXZ equ <__imp_?ClassName@CReaderWriterLock@@SAPEBDXZ>

externdef __imp_?ClassName@CSmallSpinLock@@SAPEBDXZ:PPROC
?ClassName@CSmallSpinLock@@SAPEBDXZ equ <__imp_?ClassName@CSmallSpinLock@@SAPEBDXZ>

externdef __imp_?ClassName@CSpinLock@@SAPEBDXZ:PPROC
?ClassName@CSpinLock@@SAPEBDXZ equ <__imp_?ClassName@CSpinLock@@SAPEBDXZ>

externdef __imp_?Clear@CLKRHashTable@@QEAAXXZ:PPROC
?Clear@CLKRHashTable@@QEAAXXZ equ <__imp_?Clear@CLKRHashTable@@QEAAXXZ>

externdef __imp_?Clear@CLKRLinearHashTable@@QEAAXXZ:PPROC
?Clear@CLKRLinearHashTable@@QEAAXXZ equ <__imp_?Clear@CLKRLinearHashTable@@QEAAXXZ>

externdef __imp_?CloseIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?CloseIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?CloseIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?CloseIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PPROC
?CloseIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z equ <__imp_?CloseIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>

externdef __imp_?CloseIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?CloseIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?CloseIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?CloseIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PPROC
?CloseIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z equ <__imp_?CloseIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>

externdef __imp_?ConvertExclusiveToShared@CCritSec@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CCritSec@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CCritSec@@QEAAXXZ>

externdef __imp_?ConvertExclusiveToShared@CFakeLock@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CFakeLock@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CFakeLock@@QEAAXXZ>

externdef __imp_?ConvertExclusiveToShared@CLKRHashTable@@QEBAXXZ:PPROC
?ConvertExclusiveToShared@CLKRHashTable@@QEBAXXZ equ <__imp_?ConvertExclusiveToShared@CLKRHashTable@@QEBAXXZ>

externdef __imp_?ConvertExclusiveToShared@CLKRLinearHashTable@@QEBAXXZ:PPROC
?ConvertExclusiveToShared@CLKRLinearHashTable@@QEBAXXZ equ <__imp_?ConvertExclusiveToShared@CLKRLinearHashTable@@QEBAXXZ>

externdef __imp_?ConvertExclusiveToShared@CReaderWriterLock2@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CReaderWriterLock2@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CReaderWriterLock2@@QEAAXXZ>

externdef __imp_?ConvertExclusiveToShared@CReaderWriterLock3@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CReaderWriterLock3@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CReaderWriterLock3@@QEAAXXZ>

externdef __imp_?ConvertExclusiveToShared@CReaderWriterLock@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CReaderWriterLock@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CReaderWriterLock@@QEAAXXZ>

externdef __imp_?ConvertExclusiveToShared@CSmallSpinLock@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CSmallSpinLock@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CSmallSpinLock@@QEAAXXZ>

externdef __imp_?ConvertExclusiveToShared@CSpinLock@@QEAAXXZ:PPROC
?ConvertExclusiveToShared@CSpinLock@@QEAAXXZ equ <__imp_?ConvertExclusiveToShared@CSpinLock@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CCritSec@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CCritSec@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CCritSec@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CFakeLock@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CFakeLock@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CFakeLock@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CLKRHashTable@@QEBAXXZ:PPROC
?ConvertSharedToExclusive@CLKRHashTable@@QEBAXXZ equ <__imp_?ConvertSharedToExclusive@CLKRHashTable@@QEBAXXZ>

externdef __imp_?ConvertSharedToExclusive@CLKRLinearHashTable@@QEBAXXZ:PPROC
?ConvertSharedToExclusive@CLKRLinearHashTable@@QEBAXXZ equ <__imp_?ConvertSharedToExclusive@CLKRLinearHashTable@@QEBAXXZ>

externdef __imp_?ConvertSharedToExclusive@CReaderWriterLock2@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CReaderWriterLock2@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CReaderWriterLock2@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CReaderWriterLock3@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CReaderWriterLock3@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CReaderWriterLock3@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CReaderWriterLock@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CReaderWriterLock@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CReaderWriterLock@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CSmallSpinLock@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CSmallSpinLock@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CSmallSpinLock@@QEAAXXZ>

externdef __imp_?ConvertSharedToExclusive@CSpinLock@@QEAAXXZ:PPROC
?ConvertSharedToExclusive@CSpinLock@@QEAAXXZ equ <__imp_?ConvertSharedToExclusive@CSpinLock@@QEAAXXZ>

externdef __imp_?CreateHolder@@YAJPEAUIGPDispenser@@HIPEAPEAUIGPHolder@@@Z:PPROC
?CreateHolder@@YAJPEAUIGPDispenser@@HIPEAPEAUIGPHolder@@@Z equ <__imp_?CreateHolder@@YAJPEAUIGPDispenser@@HIPEAPEAUIGPHolder@@@Z>

externdef __imp_?DeleteIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z:PPROC
?DeleteIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z equ <__imp_?DeleteIf@CLKRHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z>

externdef __imp_?DeleteIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z:PPROC
?DeleteIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z equ <__imp_?DeleteIf@CLKRLinearHashTable@@QEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1@Z>

externdef __imp_?DeleteKey@CLKRHashTable@@QEAA?AW4LK_RETCODE@@_K@Z:PPROC
?DeleteKey@CLKRHashTable@@QEAA?AW4LK_RETCODE@@_K@Z equ <__imp_?DeleteKey@CLKRHashTable@@QEAA?AW4LK_RETCODE@@_K@Z>

externdef __imp_?DeleteKey@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@_K@Z:PPROC
?DeleteKey@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@_K@Z equ <__imp_?DeleteKey@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@_K@Z>

externdef __imp_?DeleteRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z:PPROC
?DeleteRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z equ <__imp_?DeleteRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z>

externdef __imp_?DeleteRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z:PPROC
?DeleteRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z equ <__imp_?DeleteRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX@Z>

externdef __imp_?FOCopyFile@CExFileOperation@@QEAAJPEBG0H@Z:PPROC
?FOCopyFile@CExFileOperation@@QEAAJPEBG0H@Z equ <__imp_?FOCopyFile@CExFileOperation@@QEAAJPEBG0H@Z>

externdef __imp_?FOCopyFileDACLS@CExFileOperation@@QEAAJPEBG0@Z:PPROC
?FOCopyFileDACLS@CExFileOperation@@QEAAJPEBG0@Z equ <__imp_?FOCopyFileDACLS@CExFileOperation@@QEAAJPEBG0@Z>

externdef __imp_?FODeleteFile@CExFileOperation@@QEAAJPEBG@Z:PPROC
?FODeleteFile@CExFileOperation@@QEAAJPEBG@Z equ <__imp_?FODeleteFile@CExFileOperation@@QEAAJPEBG@Z>

externdef __imp_?FOMoveFile@CExFileOperation@@QEAAJPEBG0@Z:PPROC
?FOMoveFile@CExFileOperation@@QEAAJPEBG0@Z equ <__imp_?FOMoveFile@CExFileOperation@@QEAAJPEBG0@Z>

externdef __imp_?FOReplaceFile@CExFileOperation@@QEAAJPEBG0@Z:PPROC
?FOReplaceFile@CExFileOperation@@QEAAJPEBG0@Z equ <__imp_?FOReplaceFile@CExFileOperation@@QEAAJPEBG0@Z>

externdef __imp_?FindKey@CLKRHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z:PPROC
?FindKey@CLKRHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z equ <__imp_?FindKey@CLKRHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z>

externdef __imp_?FindKey@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z:PPROC
?FindKey@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z equ <__imp_?FindKey@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@_KPEAPEBX@Z>

externdef __imp_?FindRecord@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z:PPROC
?FindRecord@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z equ <__imp_?FindRecord@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z>

externdef __imp_?FindRecord@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z:PPROC
?FindRecord@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z equ <__imp_?FindRecord@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEBX@Z>

externdef __imp_?First@CDoubleList@@QEBAQEAVCListEntry@@XZ:PPROC
?First@CDoubleList@@QEBAQEAVCListEntry@@XZ equ <__imp_?First@CDoubleList@@QEBAQEAVCListEntry@@XZ>

externdef __imp_?First@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PPROC
?First@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ equ <__imp_?First@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>

externdef __imp_?GetBackupFile@CEXAutoBackupFile@@QEAAHPEAPEAG@Z:PPROC
?GetBackupFile@CEXAutoBackupFile@@QEAAHPEAPEAG@Z equ <__imp_?GetBackupFile@CEXAutoBackupFile@@QEAAHPEAPEAG@Z>

externdef __imp_?GetBucketLockSpinCount@CLKRHashTable@@QEAAGXZ:PPROC
?GetBucketLockSpinCount@CLKRHashTable@@QEAAGXZ equ <__imp_?GetBucketLockSpinCount@CLKRHashTable@@QEAAGXZ>

externdef __imp_?GetBucketLockSpinCount@CLKRLinearHashTable@@QEAAGXZ:PPROC
?GetBucketLockSpinCount@CLKRLinearHashTable@@QEAAGXZ equ <__imp_?GetBucketLockSpinCount@CLKRLinearHashTable@@QEAAGXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CCritSec@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CCritSec@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CCritSec@@SANXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CFakeLock@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CFakeLock@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CFakeLock@@SANXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SANXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SANXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SANXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SANXZ>

externdef __imp_?GetDefaultSpinAdjustmentFactor@CSpinLock@@SANXZ:PPROC
?GetDefaultSpinAdjustmentFactor@CSpinLock@@SANXZ equ <__imp_?GetDefaultSpinAdjustmentFactor@CSpinLock@@SANXZ>

externdef __imp_?GetDefaultSpinCount@CCritSec@@SAGXZ:PPROC
?GetDefaultSpinCount@CCritSec@@SAGXZ equ <__imp_?GetDefaultSpinCount@CCritSec@@SAGXZ>

externdef __imp_?GetDefaultSpinCount@CFakeLock@@SAGXZ:PPROC
?GetDefaultSpinCount@CFakeLock@@SAGXZ equ <__imp_?GetDefaultSpinCount@CFakeLock@@SAGXZ>

externdef __imp_?GetDefaultSpinCount@CReaderWriterLock2@@SAGXZ:PPROC
?GetDefaultSpinCount@CReaderWriterLock2@@SAGXZ equ <__imp_?GetDefaultSpinCount@CReaderWriterLock2@@SAGXZ>

externdef __imp_?GetDefaultSpinCount@CReaderWriterLock3@@SAGXZ:PPROC
?GetDefaultSpinCount@CReaderWriterLock3@@SAGXZ equ <__imp_?GetDefaultSpinCount@CReaderWriterLock3@@SAGXZ>

externdef __imp_?GetDefaultSpinCount@CReaderWriterLock@@SAGXZ:PPROC
?GetDefaultSpinCount@CReaderWriterLock@@SAGXZ equ <__imp_?GetDefaultSpinCount@CReaderWriterLock@@SAGXZ>

externdef __imp_?GetDefaultSpinCount@CSmallSpinLock@@SAGXZ:PPROC
?GetDefaultSpinCount@CSmallSpinLock@@SAGXZ equ <__imp_?GetDefaultSpinCount@CSmallSpinLock@@SAGXZ>

externdef __imp_?GetDefaultSpinCount@CSpinLock@@SAGXZ:PPROC
?GetDefaultSpinCount@CSpinLock@@SAGXZ equ <__imp_?GetDefaultSpinCount@CSpinLock@@SAGXZ>

externdef __imp_?GetSpinCount@CCritSec@@QEBAGXZ:PPROC
?GetSpinCount@CCritSec@@QEBAGXZ equ <__imp_?GetSpinCount@CCritSec@@QEBAGXZ>

externdef __imp_?GetSpinCount@CFakeLock@@QEBAGXZ:PPROC
?GetSpinCount@CFakeLock@@QEBAGXZ equ <__imp_?GetSpinCount@CFakeLock@@QEBAGXZ>

externdef __imp_?GetSpinCount@CReaderWriterLock2@@QEBAGXZ:PPROC
?GetSpinCount@CReaderWriterLock2@@QEBAGXZ equ <__imp_?GetSpinCount@CReaderWriterLock2@@QEBAGXZ>

externdef __imp_?GetSpinCount@CReaderWriterLock3@@QEBAGXZ:PPROC
?GetSpinCount@CReaderWriterLock3@@QEBAGXZ equ <__imp_?GetSpinCount@CReaderWriterLock3@@QEBAGXZ>

externdef __imp_?GetSpinCount@CReaderWriterLock@@QEBAGXZ:PPROC
?GetSpinCount@CReaderWriterLock@@QEBAGXZ equ <__imp_?GetSpinCount@CReaderWriterLock@@QEBAGXZ>

externdef __imp_?GetSpinCount@CSmallSpinLock@@QEBAGXZ:PPROC
?GetSpinCount@CSmallSpinLock@@QEBAGXZ equ <__imp_?GetSpinCount@CSmallSpinLock@@QEBAGXZ>

externdef __imp_?GetSpinCount@CSpinLock@@QEBAGXZ:PPROC
?GetSpinCount@CSpinLock@@QEBAGXZ equ <__imp_?GetSpinCount@CSpinLock@@QEBAGXZ>

externdef __imp_?GetStatistics@CLKRHashTable@@QEBA?AVCLKRHashTableStats@@XZ:PPROC
?GetStatistics@CLKRHashTable@@QEBA?AVCLKRHashTableStats@@XZ equ <__imp_?GetStatistics@CLKRHashTable@@QEBA?AVCLKRHashTableStats@@XZ>

externdef __imp_?GetStatistics@CLKRLinearHashTable@@QEBA?AVCLKRHashTableStats@@XZ:PPROC
?GetStatistics@CLKRLinearHashTable@@QEBA?AVCLKRHashTableStats@@XZ equ <__imp_?GetStatistics@CLKRLinearHashTable@@QEBA?AVCLKRHashTableStats@@XZ>

externdef __imp_?GetTableLockSpinCount@CLKRHashTable@@QEAAGXZ:PPROC
?GetTableLockSpinCount@CLKRHashTable@@QEAAGXZ equ <__imp_?GetTableLockSpinCount@CLKRHashTable@@QEAAGXZ>

externdef __imp_?GetTableLockSpinCount@CLKRLinearHashTable@@QEAAGXZ:PPROC
?GetTableLockSpinCount@CLKRLinearHashTable@@QEAAGXZ equ <__imp_?GetTableLockSpinCount@CLKRLinearHashTable@@QEAAGXZ>

externdef __imp_?GetVersionExW@CMdVersionInfo@@SAHPEAU_OSVERSIONINFOW@@@Z:PPROC
?GetVersionExW@CMdVersionInfo@@SAHPEAU_OSVERSIONINFOW@@@Z equ <__imp_?GetVersionExW@CMdVersionInfo@@SAHPEAU_OSVERSIONINFOW@@@Z>

externdef __imp_?HeadNode@CDoubleList@@QEBAQEBVCListEntry@@XZ:PPROC
?HeadNode@CDoubleList@@QEBAQEBVCListEntry@@XZ equ <__imp_?HeadNode@CDoubleList@@QEBAQEBVCListEntry@@XZ>

externdef __imp_?HeadNode@CLockedDoubleList@@QEBAQEBVCListEntry@@XZ:PPROC
?HeadNode@CLockedDoubleList@@QEBAQEBVCListEntry@@XZ equ <__imp_?HeadNode@CLockedDoubleList@@QEBAQEBVCListEntry@@XZ>

externdef __imp_?IncrementIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?IncrementIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?IncrementIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?IncrementIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PPROC
?IncrementIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z equ <__imp_?IncrementIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>

externdef __imp_?IncrementIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?IncrementIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?IncrementIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?IncrementIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PPROC
?IncrementIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z equ <__imp_?IncrementIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>

externdef __imp_?InitializeIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?InitializeIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?InitializeIterator@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?InitializeIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PPROC
?InitializeIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z equ <__imp_?InitializeIterator@CLKRHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>

externdef __imp_?InitializeIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?InitializeIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?InitializeIterator@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?InitializeIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z:PPROC
?InitializeIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z equ <__imp_?InitializeIterator@CLKRLinearHashTable@@QEBA?AW4LK_RETCODE@@PEAVCConstIterator@1@@Z>

externdef __imp_?InitializeVersionInfo@CMdVersionInfo@@CAHXZ:PPROC
?InitializeVersionInfo@CMdVersionInfo@@CAHXZ equ <__imp_?InitializeVersionInfo@CMdVersionInfo@@CAHXZ>

externdef __imp_?InsertHead@CDoubleList@@QEAAXQEAVCListEntry@@@Z:PPROC
?InsertHead@CDoubleList@@QEAAXQEAVCListEntry@@@Z equ <__imp_?InsertHead@CDoubleList@@QEAAXQEAVCListEntry@@@Z>

externdef __imp_?InsertHead@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z:PPROC
?InsertHead@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z equ <__imp_?InsertHead@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z>

externdef __imp_?InsertRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z:PPROC
?InsertRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z equ <__imp_?InsertRecord@CLKRHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z>

externdef __imp_?InsertRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z:PPROC
?InsertRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z equ <__imp_?InsertRecord@CLKRLinearHashTable@@QEAA?AW4LK_RETCODE@@PEBX_N@Z>

externdef __imp_?InsertTail@CDoubleList@@QEAAXQEAVCListEntry@@@Z:PPROC
?InsertTail@CDoubleList@@QEAAXQEAVCListEntry@@@Z equ <__imp_?InsertTail@CDoubleList@@QEAAXQEAVCListEntry@@@Z>

externdef __imp_?InsertTail@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z:PPROC
?InsertTail@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z equ <__imp_?InsertTail@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z>

externdef __imp_?IsEmpty@CDoubleList@@QEBA_NXZ:PPROC
?IsEmpty@CDoubleList@@QEBA_NXZ equ <__imp_?IsEmpty@CDoubleList@@QEBA_NXZ>

externdef __imp_?IsEmpty@CLockedDoubleList@@QEBA_NXZ:PPROC
?IsEmpty@CLockedDoubleList@@QEBA_NXZ equ <__imp_?IsEmpty@CLockedDoubleList@@QEBA_NXZ>

externdef __imp_?IsEmpty@CLockedSingleList@@QEBA_NXZ:PPROC
?IsEmpty@CLockedSingleList@@QEBA_NXZ equ <__imp_?IsEmpty@CLockedSingleList@@QEBA_NXZ>

externdef __imp_?IsEmpty@CSingleList@@QEBA_NXZ:PPROC
?IsEmpty@CSingleList@@QEBA_NXZ equ <__imp_?IsEmpty@CSingleList@@QEBA_NXZ>

externdef __imp_?IsLocked@CLockedDoubleList@@QEBA_NXZ:PPROC
?IsLocked@CLockedDoubleList@@QEBA_NXZ equ <__imp_?IsLocked@CLockedDoubleList@@QEBA_NXZ>

externdef __imp_?IsLocked@CLockedSingleList@@QEBA_NXZ:PPROC
?IsLocked@CLockedSingleList@@QEBA_NXZ equ <__imp_?IsLocked@CLockedSingleList@@QEBA_NXZ>

externdef __imp_?IsMillnm@CMdVersionInfo@@SAHXZ:PPROC
?IsMillnm@CMdVersionInfo@@SAHXZ equ <__imp_?IsMillnm@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsReadLocked@CCritSec@@QEBA_NXZ:PPROC
?IsReadLocked@CCritSec@@QEBA_NXZ equ <__imp_?IsReadLocked@CCritSec@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CFakeLock@@QEBA_NXZ:PPROC
?IsReadLocked@CFakeLock@@QEBA_NXZ equ <__imp_?IsReadLocked@CFakeLock@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CLKRHashTable@@QEBA_NXZ:PPROC
?IsReadLocked@CLKRHashTable@@QEBA_NXZ equ <__imp_?IsReadLocked@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?IsReadLocked@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?IsReadLocked@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CReaderWriterLock2@@QEBA_NXZ:PPROC
?IsReadLocked@CReaderWriterLock2@@QEBA_NXZ equ <__imp_?IsReadLocked@CReaderWriterLock2@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CReaderWriterLock3@@QEBA_NXZ:PPROC
?IsReadLocked@CReaderWriterLock3@@QEBA_NXZ equ <__imp_?IsReadLocked@CReaderWriterLock3@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CReaderWriterLock@@QEBA_NXZ:PPROC
?IsReadLocked@CReaderWriterLock@@QEBA_NXZ equ <__imp_?IsReadLocked@CReaderWriterLock@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CSmallSpinLock@@QEBA_NXZ:PPROC
?IsReadLocked@CSmallSpinLock@@QEBA_NXZ equ <__imp_?IsReadLocked@CSmallSpinLock@@QEBA_NXZ>

externdef __imp_?IsReadLocked@CSpinLock@@QEBA_NXZ:PPROC
?IsReadLocked@CSpinLock@@QEBA_NXZ equ <__imp_?IsReadLocked@CSpinLock@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CCritSec@@QEBA_NXZ:PPROC
?IsReadUnlocked@CCritSec@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CCritSec@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CFakeLock@@QEBA_NXZ:PPROC
?IsReadUnlocked@CFakeLock@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CFakeLock@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CLKRHashTable@@QEBA_NXZ:PPROC
?IsReadUnlocked@CLKRHashTable@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?IsReadUnlocked@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CReaderWriterLock2@@QEBA_NXZ:PPROC
?IsReadUnlocked@CReaderWriterLock2@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CReaderWriterLock2@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CReaderWriterLock3@@QEBA_NXZ:PPROC
?IsReadUnlocked@CReaderWriterLock3@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CReaderWriterLock3@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CReaderWriterLock@@QEBA_NXZ:PPROC
?IsReadUnlocked@CReaderWriterLock@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CReaderWriterLock@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CSmallSpinLock@@QEBA_NXZ:PPROC
?IsReadUnlocked@CSmallSpinLock@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CSmallSpinLock@@QEBA_NXZ>

externdef __imp_?IsReadUnlocked@CSpinLock@@QEBA_NXZ:PPROC
?IsReadUnlocked@CSpinLock@@QEBA_NXZ equ <__imp_?IsReadUnlocked@CSpinLock@@QEBA_NXZ>

externdef __imp_?IsUnlocked@CLockedDoubleList@@QEBA_NXZ:PPROC
?IsUnlocked@CLockedDoubleList@@QEBA_NXZ equ <__imp_?IsUnlocked@CLockedDoubleList@@QEBA_NXZ>

externdef __imp_?IsUnlocked@CLockedSingleList@@QEBA_NXZ:PPROC
?IsUnlocked@CLockedSingleList@@QEBA_NXZ equ <__imp_?IsUnlocked@CLockedSingleList@@QEBA_NXZ>

externdef __imp_?IsUsable@CLKRHashTable@@QEBA_NXZ:PPROC
?IsUsable@CLKRHashTable@@QEBA_NXZ equ <__imp_?IsUsable@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?IsUsable@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?IsUsable@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?IsUsable@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?IsValid@CLKRHashTable@@QEBA_NXZ:PPROC
?IsValid@CLKRHashTable@@QEBA_NXZ equ <__imp_?IsValid@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?IsValid@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?IsValid@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?IsValid@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?IsWin2k@CMdVersionInfo@@SAHXZ:PPROC
?IsWin2k@CMdVersionInfo@@SAHXZ equ <__imp_?IsWin2k@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWin2korLater@CMdVersionInfo@@SAHXZ:PPROC
?IsWin2korLater@CMdVersionInfo@@SAHXZ equ <__imp_?IsWin2korLater@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWin95@CMdVersionInfo@@SAHXZ:PPROC
?IsWin95@CMdVersionInfo@@SAHXZ equ <__imp_?IsWin95@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWin98@CMdVersionInfo@@SAHXZ:PPROC
?IsWin98@CMdVersionInfo@@SAHXZ equ <__imp_?IsWin98@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWin98orLater@CMdVersionInfo@@SAHXZ:PPROC
?IsWin98orLater@CMdVersionInfo@@SAHXZ equ <__imp_?IsWin98orLater@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWin9x@CMdVersionInfo@@SAHXZ:PPROC
?IsWin9x@CMdVersionInfo@@SAHXZ equ <__imp_?IsWin9x@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWinNT4@CMdVersionInfo@@SAHXZ:PPROC
?IsWinNT4@CMdVersionInfo@@SAHXZ equ <__imp_?IsWinNT4@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWinNT@CMdVersionInfo@@SAHXZ:PPROC
?IsWinNT@CMdVersionInfo@@SAHXZ equ <__imp_?IsWinNT@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWinNt4orLater@CMdVersionInfo@@SAHXZ:PPROC
?IsWinNt4orLater@CMdVersionInfo@@SAHXZ equ <__imp_?IsWinNt4orLater@CMdVersionInfo@@SAHXZ>

externdef __imp_?IsWriteLocked@CCritSec@@QEBA_NXZ:PPROC
?IsWriteLocked@CCritSec@@QEBA_NXZ equ <__imp_?IsWriteLocked@CCritSec@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CFakeLock@@QEBA_NXZ:PPROC
?IsWriteLocked@CFakeLock@@QEBA_NXZ equ <__imp_?IsWriteLocked@CFakeLock@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CLKRHashTable@@QEBA_NXZ:PPROC
?IsWriteLocked@CLKRHashTable@@QEBA_NXZ equ <__imp_?IsWriteLocked@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?IsWriteLocked@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?IsWriteLocked@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CReaderWriterLock2@@QEBA_NXZ:PPROC
?IsWriteLocked@CReaderWriterLock2@@QEBA_NXZ equ <__imp_?IsWriteLocked@CReaderWriterLock2@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CReaderWriterLock3@@QEBA_NXZ:PPROC
?IsWriteLocked@CReaderWriterLock3@@QEBA_NXZ equ <__imp_?IsWriteLocked@CReaderWriterLock3@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CReaderWriterLock@@QEBA_NXZ:PPROC
?IsWriteLocked@CReaderWriterLock@@QEBA_NXZ equ <__imp_?IsWriteLocked@CReaderWriterLock@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CSmallSpinLock@@QEBA_NXZ:PPROC
?IsWriteLocked@CSmallSpinLock@@QEBA_NXZ equ <__imp_?IsWriteLocked@CSmallSpinLock@@QEBA_NXZ>

externdef __imp_?IsWriteLocked@CSpinLock@@QEBA_NXZ:PPROC
?IsWriteLocked@CSpinLock@@QEBA_NXZ equ <__imp_?IsWriteLocked@CSpinLock@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CCritSec@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CCritSec@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CCritSec@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CFakeLock@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CFakeLock@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CFakeLock@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CLKRHashTable@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CLKRHashTable@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CReaderWriterLock2@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CReaderWriterLock2@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CReaderWriterLock2@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CReaderWriterLock3@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CReaderWriterLock3@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CReaderWriterLock3@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CReaderWriterLock@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CReaderWriterLock@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CReaderWriterLock@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CSmallSpinLock@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CSmallSpinLock@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CSmallSpinLock@@QEBA_NXZ>

externdef __imp_?IsWriteUnlocked@CSpinLock@@QEBA_NXZ:PPROC
?IsWriteUnlocked@CSpinLock@@QEBA_NXZ equ <__imp_?IsWriteUnlocked@CSpinLock@@QEBA_NXZ>

externdef __imp_?Last@CDoubleList@@QEBAQEAVCListEntry@@XZ:PPROC
?Last@CDoubleList@@QEBAQEAVCListEntry@@XZ equ <__imp_?Last@CDoubleList@@QEBAQEAVCListEntry@@XZ>

externdef __imp_?Last@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PPROC
?Last@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ equ <__imp_?Last@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>

externdef __imp_?Lock@CLockedDoubleList@@QEAAXXZ:PPROC
?Lock@CLockedDoubleList@@QEAAXXZ equ <__imp_?Lock@CLockedDoubleList@@QEAAXXZ>

externdef __imp_?Lock@CLockedSingleList@@QEAAXXZ:PPROC
?Lock@CLockedSingleList@@QEAAXXZ equ <__imp_?Lock@CLockedSingleList@@QEAAXXZ>

externdef __imp_?LockType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?LockType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?LockType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?LockType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?LockType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?LockType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?LockType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ:PPROC
?LockType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ equ <__imp_?LockType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_LOCKTYPE@@XZ>

externdef __imp_?MaxSize@CLKRHashTable@@QEBAKXZ:PPROC
?MaxSize@CLKRHashTable@@QEBAKXZ equ <__imp_?MaxSize@CLKRHashTable@@QEBAKXZ>

externdef __imp_?MaxSize@CLKRLinearHashTable@@QEBAKXZ:PPROC
?MaxSize@CLKRLinearHashTable@@QEBAKXZ equ <__imp_?MaxSize@CLKRLinearHashTable@@QEBAKXZ>

externdef __imp_?MpHeapCompact@@YA_KPEAX@Z:PPROC
?MpHeapCompact@@YA_KPEAX@Z equ <__imp_?MpHeapCompact@@YA_KPEAX@Z>

externdef __imp_?MutexType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?MutexType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?MutexType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?MutexType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?MutexType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?MutexType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?MutexType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ:PPROC
?MutexType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ equ <__imp_?MutexType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RW_MUTEX@@XZ>

externdef __imp_?NumSubTables@CLKRHashTable@@QEBAHXZ:PPROC
?NumSubTables@CLKRHashTable@@QEBAHXZ equ <__imp_?NumSubTables@CLKRHashTable@@QEBAHXZ>

externdef __imp_?NumSubTables@CLKRHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z:PPROC
?NumSubTables@CLKRHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z equ <__imp_?NumSubTables@CLKRHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z>

externdef __imp_?NumSubTables@CLKRLinearHashTable@@QEBAHXZ:PPROC
?NumSubTables@CLKRLinearHashTable@@QEBAHXZ equ <__imp_?NumSubTables@CLKRLinearHashTable@@QEBAHXZ>

externdef __imp_?NumSubTables@CLKRLinearHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z:PPROC
?NumSubTables@CLKRLinearHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z equ <__imp_?NumSubTables@CLKRLinearHashTable@@SA?AW4LK_TABLESIZE@@AEAK0@Z>

externdef __imp_?OnUnicodeSystem@@YAHXZ:PPROC
?OnUnicodeSystem@@YAHXZ equ <__imp_?OnUnicodeSystem@@YAHXZ>

externdef __imp_?PerLockSpin@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?PerLockSpin@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?PerLockSpin@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?PerLockSpin@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?PerLockSpin@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?PerLockSpin@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?PerLockSpin@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ:PPROC
?PerLockSpin@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ equ <__imp_?PerLockSpin@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_PERLOCK_SPIN@@XZ>

externdef __imp_?Pop@CLockedSingleList@@QEAAQEAVCSingleListEntry@@XZ:PPROC
?Pop@CLockedSingleList@@QEAAQEAVCSingleListEntry@@XZ equ <__imp_?Pop@CLockedSingleList@@QEAAQEAVCSingleListEntry@@XZ>

externdef __imp_?Pop@CSingleList@@QEAAQEAVCSingleListEntry@@XZ:PPROC
?Pop@CSingleList@@QEAAQEAVCSingleListEntry@@XZ equ <__imp_?Pop@CSingleList@@QEAAQEAVCSingleListEntry@@XZ>

externdef __imp_?Print@CLKRHashTable@@QEBAXXZ:PPROC
?Print@CLKRHashTable@@QEBAXXZ equ <__imp_?Print@CLKRHashTable@@QEBAXXZ>

externdef __imp_?Print@CLKRLinearHashTable@@QEBAXXZ:PPROC
?Print@CLKRLinearHashTable@@QEBAXXZ equ <__imp_?Print@CLKRLinearHashTable@@QEBAXXZ>

externdef __imp_?Push@CLockedSingleList@@QEAAXQEAVCSingleListEntry@@@Z:PPROC
?Push@CLockedSingleList@@QEAAXQEAVCSingleListEntry@@@Z equ <__imp_?Push@CLockedSingleList@@QEAAXQEAVCSingleListEntry@@@Z>

externdef __imp_?Push@CSingleList@@QEAAXQEAVCSingleListEntry@@@Z:PPROC
?Push@CSingleList@@QEAAXQEAVCSingleListEntry@@@Z equ <__imp_?Push@CSingleList@@QEAAXQEAVCSingleListEntry@@@Z>

externdef __imp_?QueueType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?QueueType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?QueueType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?QueueType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?QueueType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?QueueType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?QueueType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ:PPROC
?QueueType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ equ <__imp_?QueueType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_QUEUE_TYPE@@XZ>

externdef __imp_?ReadLock@CCritSec@@QEAAXXZ:PPROC
?ReadLock@CCritSec@@QEAAXXZ equ <__imp_?ReadLock@CCritSec@@QEAAXXZ>

externdef __imp_?ReadLock@CFakeLock@@QEAAXXZ:PPROC
?ReadLock@CFakeLock@@QEAAXXZ equ <__imp_?ReadLock@CFakeLock@@QEAAXXZ>

externdef __imp_?ReadLock@CLKRHashTable@@QEBAXXZ:PPROC
?ReadLock@CLKRHashTable@@QEBAXXZ equ <__imp_?ReadLock@CLKRHashTable@@QEBAXXZ>

externdef __imp_?ReadLock@CLKRLinearHashTable@@QEBAXXZ:PPROC
?ReadLock@CLKRLinearHashTable@@QEBAXXZ equ <__imp_?ReadLock@CLKRLinearHashTable@@QEBAXXZ>

externdef __imp_?ReadLock@CReaderWriterLock2@@QEAAXXZ:PPROC
?ReadLock@CReaderWriterLock2@@QEAAXXZ equ <__imp_?ReadLock@CReaderWriterLock2@@QEAAXXZ>

externdef __imp_?ReadLock@CReaderWriterLock3@@QEAAXXZ:PPROC
?ReadLock@CReaderWriterLock3@@QEAAXXZ equ <__imp_?ReadLock@CReaderWriterLock3@@QEAAXXZ>

externdef __imp_?ReadLock@CReaderWriterLock@@QEAAXXZ:PPROC
?ReadLock@CReaderWriterLock@@QEAAXXZ equ <__imp_?ReadLock@CReaderWriterLock@@QEAAXXZ>

externdef __imp_?ReadLock@CSmallSpinLock@@QEAAXXZ:PPROC
?ReadLock@CSmallSpinLock@@QEAAXXZ equ <__imp_?ReadLock@CSmallSpinLock@@QEAAXXZ>

externdef __imp_?ReadLock@CSpinLock@@QEAAXXZ:PPROC
?ReadLock@CSpinLock@@QEAAXXZ equ <__imp_?ReadLock@CSpinLock@@QEAAXXZ>

externdef __imp_?ReadOrWriteLock@CCritSec@@QEAA_NXZ:PPROC
?ReadOrWriteLock@CCritSec@@QEAA_NXZ equ <__imp_?ReadOrWriteLock@CCritSec@@QEAA_NXZ>

externdef __imp_?ReadOrWriteLock@CFakeLock@@QEAA_NXZ:PPROC
?ReadOrWriteLock@CFakeLock@@QEAA_NXZ equ <__imp_?ReadOrWriteLock@CFakeLock@@QEAA_NXZ>

externdef __imp_?ReadOrWriteLock@CReaderWriterLock3@@QEAA_NXZ:PPROC
?ReadOrWriteLock@CReaderWriterLock3@@QEAA_NXZ equ <__imp_?ReadOrWriteLock@CReaderWriterLock3@@QEAA_NXZ>

externdef __imp_?ReadOrWriteLock@CSpinLock@@QEAA_NXZ:PPROC
?ReadOrWriteLock@CSpinLock@@QEAA_NXZ equ <__imp_?ReadOrWriteLock@CSpinLock@@QEAA_NXZ>

externdef __imp_?ReadOrWriteUnlock@CCritSec@@QEAAX_N@Z:PPROC
?ReadOrWriteUnlock@CCritSec@@QEAAX_N@Z equ <__imp_?ReadOrWriteUnlock@CCritSec@@QEAAX_N@Z>

externdef __imp_?ReadOrWriteUnlock@CFakeLock@@QEAAX_N@Z:PPROC
?ReadOrWriteUnlock@CFakeLock@@QEAAX_N@Z equ <__imp_?ReadOrWriteUnlock@CFakeLock@@QEAAX_N@Z>

externdef __imp_?ReadOrWriteUnlock@CReaderWriterLock3@@QEAAX_N@Z:PPROC
?ReadOrWriteUnlock@CReaderWriterLock3@@QEAAX_N@Z equ <__imp_?ReadOrWriteUnlock@CReaderWriterLock3@@QEAAX_N@Z>

externdef __imp_?ReadOrWriteUnlock@CSpinLock@@QEAAX_N@Z:PPROC
?ReadOrWriteUnlock@CSpinLock@@QEAAX_N@Z equ <__imp_?ReadOrWriteUnlock@CSpinLock@@QEAAX_N@Z>

externdef __imp_?ReadUnlock@CCritSec@@QEAAXXZ:PPROC
?ReadUnlock@CCritSec@@QEAAXXZ equ <__imp_?ReadUnlock@CCritSec@@QEAAXXZ>

externdef __imp_?ReadUnlock@CFakeLock@@QEAAXXZ:PPROC
?ReadUnlock@CFakeLock@@QEAAXXZ equ <__imp_?ReadUnlock@CFakeLock@@QEAAXXZ>

externdef __imp_?ReadUnlock@CLKRHashTable@@QEBAXXZ:PPROC
?ReadUnlock@CLKRHashTable@@QEBAXXZ equ <__imp_?ReadUnlock@CLKRHashTable@@QEBAXXZ>

externdef __imp_?ReadUnlock@CLKRLinearHashTable@@QEBAXXZ:PPROC
?ReadUnlock@CLKRLinearHashTable@@QEBAXXZ equ <__imp_?ReadUnlock@CLKRLinearHashTable@@QEBAXXZ>

externdef __imp_?ReadUnlock@CReaderWriterLock2@@QEAAXXZ:PPROC
?ReadUnlock@CReaderWriterLock2@@QEAAXXZ equ <__imp_?ReadUnlock@CReaderWriterLock2@@QEAAXXZ>

externdef __imp_?ReadUnlock@CReaderWriterLock3@@QEAAXXZ:PPROC
?ReadUnlock@CReaderWriterLock3@@QEAAXXZ equ <__imp_?ReadUnlock@CReaderWriterLock3@@QEAAXXZ>

externdef __imp_?ReadUnlock@CReaderWriterLock@@QEAAXXZ:PPROC
?ReadUnlock@CReaderWriterLock@@QEAAXXZ equ <__imp_?ReadUnlock@CReaderWriterLock@@QEAAXXZ>

externdef __imp_?ReadUnlock@CSmallSpinLock@@QEAAXXZ:PPROC
?ReadUnlock@CSmallSpinLock@@QEAAXXZ equ <__imp_?ReadUnlock@CSmallSpinLock@@QEAAXXZ>

externdef __imp_?ReadUnlock@CSpinLock@@QEAAXXZ:PPROC
?ReadUnlock@CSpinLock@@QEAAXXZ equ <__imp_?ReadUnlock@CSpinLock@@QEAAXXZ>

externdef __imp_?Recursion@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?Recursion@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?Recursion@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?Recursion@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?Recursion@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?Recursion@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?Recursion@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ:PPROC
?Recursion@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ equ <__imp_?Recursion@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_RECURSION@@XZ>

externdef __imp_?ReleaseVersionInfo@CMdVersionInfo@@SAXXZ:PPROC
?ReleaseVersionInfo@CMdVersionInfo@@SAXXZ equ <__imp_?ReleaseVersionInfo@CMdVersionInfo@@SAXXZ>

externdef __imp_?RemoveEntry@CDoubleList@@SAXQEAVCListEntry@@@Z:PPROC
?RemoveEntry@CDoubleList@@SAXQEAVCListEntry@@@Z equ <__imp_?RemoveEntry@CDoubleList@@SAXQEAVCListEntry@@@Z>

externdef __imp_?RemoveEntry@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z:PPROC
?RemoveEntry@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z equ <__imp_?RemoveEntry@CLockedDoubleList@@QEAAXQEAVCListEntry@@@Z>

externdef __imp_?RemoveHead@CDoubleList@@QEAAQEAVCListEntry@@XZ:PPROC
?RemoveHead@CDoubleList@@QEAAQEAVCListEntry@@XZ equ <__imp_?RemoveHead@CDoubleList@@QEAAQEAVCListEntry@@XZ>

externdef __imp_?RemoveHead@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PPROC
?RemoveHead@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ equ <__imp_?RemoveHead@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>

externdef __imp_?RemoveTail@CDoubleList@@QEAAQEAVCListEntry@@XZ:PPROC
?RemoveTail@CDoubleList@@QEAAQEAVCListEntry@@XZ equ <__imp_?RemoveTail@CDoubleList@@QEAAQEAVCListEntry@@XZ>

externdef __imp_?RemoveTail@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ:PPROC
?RemoveTail@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ equ <__imp_?RemoveTail@CLockedDoubleList@@QEAAQEAVCListEntry@@XZ>

externdef __imp_?RestoreFile@CEXAutoBackupFile@@QEAAJXZ:PPROC
?RestoreFile@CEXAutoBackupFile@@QEAAJXZ equ <__imp_?RestoreFile@CEXAutoBackupFile@@QEAAJXZ>

externdef __imp_?SetBucketLockSpinCount@CLKRHashTable@@QEAAXG@Z:PPROC
?SetBucketLockSpinCount@CLKRHashTable@@QEAAXG@Z equ <__imp_?SetBucketLockSpinCount@CLKRHashTable@@QEAAXG@Z>

externdef __imp_?SetBucketLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z:PPROC
?SetBucketLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z equ <__imp_?SetBucketLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CCritSec@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CCritSec@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CCritSec@@SAXN@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CFakeLock@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CFakeLock@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CFakeLock@@SAXN@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock2@@SAXN@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock3@@SAXN@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CReaderWriterLock@@SAXN@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CSmallSpinLock@@SAXN@Z>

externdef __imp_?SetDefaultSpinAdjustmentFactor@CSpinLock@@SAXN@Z:PPROC
?SetDefaultSpinAdjustmentFactor@CSpinLock@@SAXN@Z equ <__imp_?SetDefaultSpinAdjustmentFactor@CSpinLock@@SAXN@Z>

externdef __imp_?SetDefaultSpinCount@CCritSec@@SAXG@Z:PPROC
?SetDefaultSpinCount@CCritSec@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CCritSec@@SAXG@Z>

externdef __imp_?SetDefaultSpinCount@CFakeLock@@SAXG@Z:PPROC
?SetDefaultSpinCount@CFakeLock@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CFakeLock@@SAXG@Z>

externdef __imp_?SetDefaultSpinCount@CReaderWriterLock2@@SAXG@Z:PPROC
?SetDefaultSpinCount@CReaderWriterLock2@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CReaderWriterLock2@@SAXG@Z>

externdef __imp_?SetDefaultSpinCount@CReaderWriterLock3@@SAXG@Z:PPROC
?SetDefaultSpinCount@CReaderWriterLock3@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CReaderWriterLock3@@SAXG@Z>

externdef __imp_?SetDefaultSpinCount@CReaderWriterLock@@SAXG@Z:PPROC
?SetDefaultSpinCount@CReaderWriterLock@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CReaderWriterLock@@SAXG@Z>

externdef __imp_?SetDefaultSpinCount@CSmallSpinLock@@SAXG@Z:PPROC
?SetDefaultSpinCount@CSmallSpinLock@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CSmallSpinLock@@SAXG@Z>

externdef __imp_?SetDefaultSpinCount@CSpinLock@@SAXG@Z:PPROC
?SetDefaultSpinCount@CSpinLock@@SAXG@Z equ <__imp_?SetDefaultSpinCount@CSpinLock@@SAXG@Z>

externdef __imp_?SetSpinCount@CCritSec@@QEAA_NG@Z:PPROC
?SetSpinCount@CCritSec@@QEAA_NG@Z equ <__imp_?SetSpinCount@CCritSec@@QEAA_NG@Z>

externdef __imp_?SetSpinCount@CCritSec@@SAKPEAPEAVCCriticalSection@@K@Z:PPROC
?SetSpinCount@CCritSec@@SAKPEAPEAVCCriticalSection@@K@Z equ <__imp_?SetSpinCount@CCritSec@@SAKPEAPEAVCCriticalSection@@K@Z>

externdef __imp_?SetSpinCount@CFakeLock@@QEAA_NG@Z:PPROC
?SetSpinCount@CFakeLock@@QEAA_NG@Z equ <__imp_?SetSpinCount@CFakeLock@@QEAA_NG@Z>

externdef __imp_?SetSpinCount@CReaderWriterLock2@@QEAA_NG@Z:PPROC
?SetSpinCount@CReaderWriterLock2@@QEAA_NG@Z equ <__imp_?SetSpinCount@CReaderWriterLock2@@QEAA_NG@Z>

externdef __imp_?SetSpinCount@CReaderWriterLock3@@QEAA_NG@Z:PPROC
?SetSpinCount@CReaderWriterLock3@@QEAA_NG@Z equ <__imp_?SetSpinCount@CReaderWriterLock3@@QEAA_NG@Z>

externdef __imp_?SetSpinCount@CReaderWriterLock@@QEAA_NG@Z:PPROC
?SetSpinCount@CReaderWriterLock@@QEAA_NG@Z equ <__imp_?SetSpinCount@CReaderWriterLock@@QEAA_NG@Z>

externdef __imp_?SetSpinCount@CSmallSpinLock@@QEAA_NG@Z:PPROC
?SetSpinCount@CSmallSpinLock@@QEAA_NG@Z equ <__imp_?SetSpinCount@CSmallSpinLock@@QEAA_NG@Z>

externdef __imp_?SetSpinCount@CSpinLock@@QEAA_NG@Z:PPROC
?SetSpinCount@CSpinLock@@QEAA_NG@Z equ <__imp_?SetSpinCount@CSpinLock@@QEAA_NG@Z>

externdef __imp_?SetTableLockSpinCount@CLKRHashTable@@QEAAXG@Z:PPROC
?SetTableLockSpinCount@CLKRHashTable@@QEAAXG@Z equ <__imp_?SetTableLockSpinCount@CLKRHashTable@@QEAAXG@Z>

externdef __imp_?SetTableLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z:PPROC
?SetTableLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z equ <__imp_?SetTableLockSpinCount@CLKRLinearHashTable@@QEAAXG@Z>

externdef __imp_?Size@CLKRHashTable@@QEBAKXZ:PPROC
?Size@CLKRHashTable@@QEBAKXZ equ <__imp_?Size@CLKRHashTable@@QEBAKXZ>

externdef __imp_?Size@CLKRLinearHashTable@@QEBAKXZ:PPROC
?Size@CLKRLinearHashTable@@QEBAKXZ equ <__imp_?Size@CLKRLinearHashTable@@QEBAKXZ>

externdef __imp_?TryReadLock@CCritSec@@QEAA_NXZ:PPROC
?TryReadLock@CCritSec@@QEAA_NXZ equ <__imp_?TryReadLock@CCritSec@@QEAA_NXZ>

externdef __imp_?TryReadLock@CFakeLock@@QEAA_NXZ:PPROC
?TryReadLock@CFakeLock@@QEAA_NXZ equ <__imp_?TryReadLock@CFakeLock@@QEAA_NXZ>

externdef __imp_?TryReadLock@CReaderWriterLock2@@QEAA_NXZ:PPROC
?TryReadLock@CReaderWriterLock2@@QEAA_NXZ equ <__imp_?TryReadLock@CReaderWriterLock2@@QEAA_NXZ>

externdef __imp_?TryReadLock@CReaderWriterLock3@@QEAA_NXZ:PPROC
?TryReadLock@CReaderWriterLock3@@QEAA_NXZ equ <__imp_?TryReadLock@CReaderWriterLock3@@QEAA_NXZ>

externdef __imp_?TryReadLock@CReaderWriterLock@@QEAA_NXZ:PPROC
?TryReadLock@CReaderWriterLock@@QEAA_NXZ equ <__imp_?TryReadLock@CReaderWriterLock@@QEAA_NXZ>

externdef __imp_?TryReadLock@CSmallSpinLock@@QEAA_NXZ:PPROC
?TryReadLock@CSmallSpinLock@@QEAA_NXZ equ <__imp_?TryReadLock@CSmallSpinLock@@QEAA_NXZ>

externdef __imp_?TryReadLock@CSpinLock@@QEAA_NXZ:PPROC
?TryReadLock@CSpinLock@@QEAA_NXZ equ <__imp_?TryReadLock@CSpinLock@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CCritSec@@QEAA_NXZ:PPROC
?TryWriteLock@CCritSec@@QEAA_NXZ equ <__imp_?TryWriteLock@CCritSec@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CFakeLock@@QEAA_NXZ:PPROC
?TryWriteLock@CFakeLock@@QEAA_NXZ equ <__imp_?TryWriteLock@CFakeLock@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CReaderWriterLock2@@QEAA_NXZ:PPROC
?TryWriteLock@CReaderWriterLock2@@QEAA_NXZ equ <__imp_?TryWriteLock@CReaderWriterLock2@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CReaderWriterLock3@@QEAA_NXZ:PPROC
?TryWriteLock@CReaderWriterLock3@@QEAA_NXZ equ <__imp_?TryWriteLock@CReaderWriterLock3@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CReaderWriterLock@@QEAA_NXZ:PPROC
?TryWriteLock@CReaderWriterLock@@QEAA_NXZ equ <__imp_?TryWriteLock@CReaderWriterLock@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CSmallSpinLock@@QEAA_NXZ:PPROC
?TryWriteLock@CSmallSpinLock@@QEAA_NXZ equ <__imp_?TryWriteLock@CSmallSpinLock@@QEAA_NXZ>

externdef __imp_?TryWriteLock@CSpinLock@@QEAA_NXZ:PPROC
?TryWriteLock@CSpinLock@@QEAA_NXZ equ <__imp_?TryWriteLock@CSpinLock@@QEAA_NXZ>

externdef __imp_?UndoBackup@CEXAutoBackupFile@@QEAAJXZ:PPROC
?UndoBackup@CEXAutoBackupFile@@QEAAJXZ equ <__imp_?UndoBackup@CEXAutoBackupFile@@QEAAJXZ>

externdef __imp_?Unlock@CLockedDoubleList@@QEAAXXZ:PPROC
?Unlock@CLockedDoubleList@@QEAAXXZ equ <__imp_?Unlock@CLockedDoubleList@@QEAAXXZ>

externdef __imp_?Unlock@CLockedSingleList@@QEAAXXZ:PPROC
?Unlock@CLockedSingleList@@QEAAXXZ equ <__imp_?Unlock@CLockedSingleList@@QEAAXXZ>

externdef __imp_?ValidSignature@CLKRHashTable@@QEBA_NXZ:PPROC
?ValidSignature@CLKRHashTable@@QEBA_NXZ equ <__imp_?ValidSignature@CLKRHashTable@@QEBA_NXZ>

externdef __imp_?ValidSignature@CLKRLinearHashTable@@QEBA_NXZ:PPROC
?ValidSignature@CLKRLinearHashTable@@QEBA_NXZ equ <__imp_?ValidSignature@CLKRLinearHashTable@@QEBA_NXZ>

externdef __imp_?WaitType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$00$00$02$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WaitType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$01$00$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WaitType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$02$00$00$00$00$00@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WaitType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$03$00$00$01$02$02@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WaitType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$04$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WaitType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$05$01$01$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WaitType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ:PPROC
?WaitType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ equ <__imp_?WaitType@?$CLockBase@$06$01$00$00$02$01@@SA?AW4LOCK_WAIT_TYPE@@XZ>

externdef __imp_?WriteLock@CCritSec@@QEAAXXZ:PPROC
?WriteLock@CCritSec@@QEAAXXZ equ <__imp_?WriteLock@CCritSec@@QEAAXXZ>

externdef __imp_?WriteLock@CFakeLock@@QEAAXXZ:PPROC
?WriteLock@CFakeLock@@QEAAXXZ equ <__imp_?WriteLock@CFakeLock@@QEAAXXZ>

externdef __imp_?WriteLock@CLKRHashTable@@QEAAXXZ:PPROC
?WriteLock@CLKRHashTable@@QEAAXXZ equ <__imp_?WriteLock@CLKRHashTable@@QEAAXXZ>

externdef __imp_?WriteLock@CLKRLinearHashTable@@QEAAXXZ:PPROC
?WriteLock@CLKRLinearHashTable@@QEAAXXZ equ <__imp_?WriteLock@CLKRLinearHashTable@@QEAAXXZ>

externdef __imp_?WriteLock@CReaderWriterLock2@@QEAAXXZ:PPROC
?WriteLock@CReaderWriterLock2@@QEAAXXZ equ <__imp_?WriteLock@CReaderWriterLock2@@QEAAXXZ>

externdef __imp_?WriteLock@CReaderWriterLock3@@QEAAXXZ:PPROC
?WriteLock@CReaderWriterLock3@@QEAAXXZ equ <__imp_?WriteLock@CReaderWriterLock3@@QEAAXXZ>

externdef __imp_?WriteLock@CReaderWriterLock@@QEAAXXZ:PPROC
?WriteLock@CReaderWriterLock@@QEAAXXZ equ <__imp_?WriteLock@CReaderWriterLock@@QEAAXXZ>

externdef __imp_?WriteLock@CSmallSpinLock@@QEAAXXZ:PPROC
?WriteLock@CSmallSpinLock@@QEAAXXZ equ <__imp_?WriteLock@CSmallSpinLock@@QEAAXXZ>

externdef __imp_?WriteLock@CSpinLock@@QEAAXXZ:PPROC
?WriteLock@CSpinLock@@QEAAXXZ equ <__imp_?WriteLock@CSpinLock@@QEAAXXZ>

externdef __imp_?WriteUnlock@CCritSec@@QEAAXXZ:PPROC
?WriteUnlock@CCritSec@@QEAAXXZ equ <__imp_?WriteUnlock@CCritSec@@QEAAXXZ>

externdef __imp_?WriteUnlock@CFakeLock@@QEAAXXZ:PPROC
?WriteUnlock@CFakeLock@@QEAAXXZ equ <__imp_?WriteUnlock@CFakeLock@@QEAAXXZ>

externdef __imp_?WriteUnlock@CLKRHashTable@@QEBAXXZ:PPROC
?WriteUnlock@CLKRHashTable@@QEBAXXZ equ <__imp_?WriteUnlock@CLKRHashTable@@QEBAXXZ>

externdef __imp_?WriteUnlock@CLKRLinearHashTable@@QEBAXXZ:PPROC
?WriteUnlock@CLKRLinearHashTable@@QEBAXXZ equ <__imp_?WriteUnlock@CLKRLinearHashTable@@QEBAXXZ>

externdef __imp_?WriteUnlock@CReaderWriterLock2@@QEAAXXZ:PPROC
?WriteUnlock@CReaderWriterLock2@@QEAAXXZ equ <__imp_?WriteUnlock@CReaderWriterLock2@@QEAAXXZ>

externdef __imp_?WriteUnlock@CReaderWriterLock3@@QEAAXXZ:PPROC
?WriteUnlock@CReaderWriterLock3@@QEAAXXZ equ <__imp_?WriteUnlock@CReaderWriterLock3@@QEAAXXZ>

externdef __imp_?WriteUnlock@CReaderWriterLock@@QEAAXXZ:PPROC
?WriteUnlock@CReaderWriterLock@@QEAAXXZ equ <__imp_?WriteUnlock@CReaderWriterLock@@QEAAXXZ>

externdef __imp_?WriteUnlock@CSmallSpinLock@@QEAAXXZ:PPROC
?WriteUnlock@CSmallSpinLock@@QEAAXXZ equ <__imp_?WriteUnlock@CSmallSpinLock@@QEAAXXZ>

externdef __imp_?WriteUnlock@CSpinLock@@QEAAXXZ:PPROC
?WriteUnlock@CSpinLock@@QEAAXXZ equ <__imp_?WriteUnlock@CSpinLock@@QEAAXXZ>

externdef __imp_?_AddRefRecord@CLKRLinearHashTable@@AEBAXPEBXH@Z:PPROC
?_AddRefRecord@CLKRLinearHashTable@@AEBAXPEBXH@Z equ <__imp_?_AddRefRecord@CLKRLinearHashTable@@AEBAXPEBXH@Z>

externdef __imp_?_AllocateNodeClump@CLKRLinearHashTable@@CAQEAVCNodeClump@1@XZ:PPROC
?_AllocateNodeClump@CLKRLinearHashTable@@CAQEAVCNodeClump@1@XZ equ <__imp_?_AllocateNodeClump@CLKRLinearHashTable@@CAQEAVCNodeClump@1@XZ>

externdef __imp_?_AllocateSegment@CLKRLinearHashTable@@AEBAQEAVCSegment@1@XZ:PPROC
?_AllocateSegment@CLKRLinearHashTable@@AEBAQEAVCSegment@1@XZ equ <__imp_?_AllocateSegment@CLKRLinearHashTable@@AEBAQEAVCSegment@1@XZ>

externdef __imp_?_AllocateSegmentDirectory@CLKRLinearHashTable@@CAQEAVCDirEntry@1@_K@Z:PPROC
?_AllocateSegmentDirectory@CLKRLinearHashTable@@CAQEAVCDirEntry@1@_K@Z equ <__imp_?_AllocateSegmentDirectory@CLKRLinearHashTable@@CAQEAVCDirEntry@1@_K@Z>

externdef __imp_?_AllocateSubTable@CLKRHashTable@@CAQEAVCLKRLinearHashTable@@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAV1@@Z:PPROC
?_AllocateSubTable@CLKRHashTable@@CAQEAVCLKRLinearHashTable@@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAV1@@Z equ <__imp_?_AllocateSubTable@CLKRHashTable@@CAQEAVCLKRLinearHashTable@@PEBDP6A?B_KPEBX@ZP6AK_K@ZP6A_N33@ZP6AX1H@ZNKPEAV1@@Z>

externdef __imp_?_AllocateSubTableArray@CLKRHashTable@@CAQEAPEAVCLKRLinearHashTable@@_K@Z:PPROC
?_AllocateSubTableArray@CLKRHashTable@@CAQEAPEAVCLKRLinearHashTable@@_K@Z equ <__imp_?_AllocateSubTableArray@CLKRHashTable@@CAQEAPEAVCLKRLinearHashTable@@_K@Z>

externdef __imp_?_Apply@CLKRLinearHashTable@@AEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@AEAW4LK_PREDICATE@@@Z:PPROC
?_Apply@CLKRLinearHashTable@@AEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@AEAW4LK_PREDICATE@@@Z equ <__imp_?_Apply@CLKRLinearHashTable@@AEAAKP6A?AW4LK_ACTION@@PEBXPEAX@Z1W4LK_LOCKTYPE@@AEAW4LK_PREDICATE@@@Z>

externdef __imp_?_ApplyIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@AEAW42@@Z:PPROC
?_ApplyIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@AEAW42@@Z equ <__imp_?_ApplyIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@ZP6A?AW4LK_ACTION@@01@Z1W4LK_LOCKTYPE@@AEAW42@@Z>

externdef __imp_?_Bucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K@Z:PPROC
?_Bucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K@Z equ <__imp_?_Bucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K@Z>

externdef __imp_?_BucketAddress@CLKRLinearHashTable@@AEBAKK@Z:PPROC
?_BucketAddress@CLKRLinearHashTable@@AEBAKK@Z equ <__imp_?_BucketAddress@CLKRLinearHashTable@@AEBAKK@Z>

externdef __imp_?_CalcKeyHash@CLKRHashTable@@AEBAK_K@Z:PPROC
?_CalcKeyHash@CLKRHashTable@@AEBAK_K@Z equ <__imp_?_CalcKeyHash@CLKRHashTable@@AEBAK_K@Z>

externdef __imp_?_CalcKeyHash@CLKRLinearHashTable@@AEBAK_K@Z:PPROC
?_CalcKeyHash@CLKRLinearHashTable@@AEBAK_K@Z equ <__imp_?_CalcKeyHash@CLKRLinearHashTable@@AEBAK_K@Z>

externdef __imp_?_Clear@CLKRLinearHashTable@@AEAAX_N@Z:PPROC
?_Clear@CLKRLinearHashTable@@AEAAX_N@Z equ <__imp_?_Clear@CLKRLinearHashTable@@AEAAX_N@Z>

externdef __imp_?_CloseIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?_CloseIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?_CloseIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?_CmpExch@CReaderWriterLock2@@AEAA_NJJ@Z:PPROC
?_CmpExch@CReaderWriterLock2@@AEAA_NJJ@Z equ <__imp_?_CmpExch@CReaderWriterLock2@@AEAA_NJJ@Z>

externdef __imp_?_CmpExch@CReaderWriterLock3@@AEAA_NJJ@Z:PPROC
?_CmpExch@CReaderWriterLock3@@AEAA_NJJ@Z equ <__imp_?_CmpExch@CReaderWriterLock3@@AEAA_NJJ@Z>

externdef __imp_?_CmpExch@CReaderWriterLock@@AEAA_NJJ@Z:PPROC
?_CmpExch@CReaderWriterLock@@AEAA_NJJ@Z equ <__imp_?_CmpExch@CReaderWriterLock@@AEAA_NJJ@Z>

externdef __imp_?_Contract@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ:PPROC
?_Contract@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ equ <__imp_?_Contract@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ>

externdef __imp_?_CurrentThreadId@CReaderWriterLock3@@CAJXZ:PPROC
?_CurrentThreadId@CReaderWriterLock3@@CAJXZ equ <__imp_?_CurrentThreadId@CReaderWriterLock3@@CAJXZ>

externdef __imp_?_CurrentThreadId@CSmallSpinLock@@CAJXZ:PPROC
?_CurrentThreadId@CSmallSpinLock@@CAJXZ equ <__imp_?_CurrentThreadId@CSmallSpinLock@@CAJXZ>

externdef __imp_?_CurrentThreadId@CSpinLock@@CAJXZ:PPROC
?_CurrentThreadId@CSpinLock@@CAJXZ equ <__imp_?_CurrentThreadId@CSpinLock@@CAJXZ>

externdef __imp_?_DeleteIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1AEAW42@@Z:PPROC
?_DeleteIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1AEAW42@@Z equ <__imp_?_DeleteIf@CLKRLinearHashTable@@AEAAKP6A?AW4LK_PREDICATE@@PEBXPEAX@Z1AEAW42@@Z>

externdef __imp_?_DeleteKey@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@_KK@Z:PPROC
?_DeleteKey@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@_KK@Z equ <__imp_?_DeleteKey@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@_KK@Z>

externdef __imp_?_DeleteNode@CLKRLinearHashTable@@AEAA_NPEAVCBucket@1@AEAPEAVCNodeClump@1@1AEAH@Z:PPROC
?_DeleteNode@CLKRLinearHashTable@@AEAA_NPEAVCBucket@1@AEAPEAVCNodeClump@1@1AEAH@Z equ <__imp_?_DeleteNode@CLKRLinearHashTable@@AEAA_NPEAVCBucket@1@AEAPEAVCNodeClump@1@1AEAH@Z>

externdef __imp_?_DeleteRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK@Z:PPROC
?_DeleteRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK@Z equ <__imp_?_DeleteRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK@Z>

externdef __imp_?_EqualKeys@CLKRLinearHashTable@@AEBA_N_K0@Z:PPROC
?_EqualKeys@CLKRLinearHashTable@@AEBA_N_K0@Z equ <__imp_?_EqualKeys@CLKRLinearHashTable@@AEBA_N_K0@Z>

externdef __imp_?_Expand@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ:PPROC
?_Expand@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ equ <__imp_?_Expand@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@XZ>

externdef __imp_?_ExtractKey@CLKRHashTable@@AEBA?B_KPEBX@Z:PPROC
?_ExtractKey@CLKRHashTable@@AEBA?B_KPEBX@Z equ <__imp_?_ExtractKey@CLKRHashTable@@AEBA?B_KPEBX@Z>

externdef __imp_?_ExtractKey@CLKRLinearHashTable@@AEBA?B_KPEBX@Z:PPROC
?_ExtractKey@CLKRLinearHashTable@@AEBA?B_KPEBX@Z equ <__imp_?_ExtractKey@CLKRLinearHashTable@@AEBA?B_KPEBX@Z>

externdef __imp_?_FindBucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K_N@Z:PPROC
?_FindBucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K_N@Z equ <__imp_?_FindBucket@CLKRLinearHashTable@@AEBAPEAVCBucket@1@K_N@Z>

externdef __imp_?_FindKey@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@_KKPEAPEBX@Z:PPROC
?_FindKey@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@_KKPEAPEBX@Z equ <__imp_?_FindKey@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@_KKPEAPEBX@Z>

externdef __imp_?_FindRecord@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@PEBXK@Z:PPROC
?_FindRecord@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@PEBXK@Z equ <__imp_?_FindRecord@CLKRLinearHashTable@@AEBA?AW4LK_RETCODE@@PEBXK@Z>

externdef __imp_?_FreeNodeClump@CLKRLinearHashTable@@CA_NPEAVCNodeClump@1@@Z:PPROC
?_FreeNodeClump@CLKRLinearHashTable@@CA_NPEAVCNodeClump@1@@Z equ <__imp_?_FreeNodeClump@CLKRLinearHashTable@@CA_NPEAVCNodeClump@1@@Z>

externdef __imp_?_FreeSegment@CLKRLinearHashTable@@AEBA_NPEAVCSegment@1@@Z:PPROC
?_FreeSegment@CLKRLinearHashTable@@AEBA_NPEAVCSegment@1@@Z equ <__imp_?_FreeSegment@CLKRLinearHashTable@@AEBA_NPEAVCSegment@1@@Z>

externdef __imp_?_FreeSegmentDirectory@CLKRLinearHashTable@@CA_NPEAVCDirEntry@1@@Z:PPROC
?_FreeSegmentDirectory@CLKRLinearHashTable@@CA_NPEAVCDirEntry@1@@Z equ <__imp_?_FreeSegmentDirectory@CLKRLinearHashTable@@CA_NPEAVCDirEntry@1@@Z>

externdef __imp_?_FreeSubTable@CLKRHashTable@@CA_NPEAVCLKRLinearHashTable@@@Z:PPROC
?_FreeSubTable@CLKRHashTable@@CA_NPEAVCLKRLinearHashTable@@@Z equ <__imp_?_FreeSubTable@CLKRHashTable@@CA_NPEAVCLKRLinearHashTable@@@Z>

externdef __imp_?_FreeSubTableArray@CLKRHashTable@@CA_NPEAPEAVCLKRLinearHashTable@@@Z:PPROC
?_FreeSubTableArray@CLKRHashTable@@CA_NPEAPEAVCLKRLinearHashTable@@@Z equ <__imp_?_FreeSubTableArray@CLKRHashTable@@CA_NPEAPEAVCLKRLinearHashTable@@@Z>

externdef __imp_?_H0@CLKRLinearHashTable@@AEBAKK@Z:PPROC
?_H0@CLKRLinearHashTable@@AEBAKK@Z equ <__imp_?_H0@CLKRLinearHashTable@@AEBAKK@Z>

externdef __imp_?_H0@CLKRLinearHashTable@@CAKKK@Z:PPROC
?_H0@CLKRLinearHashTable@@CAKKK@Z equ <__imp_?_H0@CLKRLinearHashTable@@CAKKK@Z>

externdef __imp_?_H1@CLKRLinearHashTable@@AEBAKK@Z:PPROC
?_H1@CLKRLinearHashTable@@AEBAKK@Z equ <__imp_?_H1@CLKRLinearHashTable@@AEBAKK@Z>

externdef __imp_?_H1@CLKRLinearHashTable@@CAKKK@Z:PPROC
?_H1@CLKRLinearHashTable@@CAKKK@Z equ <__imp_?_H1@CLKRLinearHashTable@@CAKKK@Z>

externdef __imp_?_Initialize@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@P6A?B_KPEBX@ZP6AK_K@ZP6A_N22@ZP6AX0H@ZPEBDNK@Z:PPROC
?_Initialize@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@P6A?B_KPEBX@ZP6AK_K@ZP6A_N22@ZP6AX0H@ZPEBDNK@Z equ <__imp_?_Initialize@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@P6A?B_KPEBX@ZP6AK_K@ZP6A_N22@ZP6AX0H@ZPEBDNK@Z>

externdef __imp_?_InitializeIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z:PPROC
?_InitializeIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z equ <__imp_?_InitializeIterator@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCIterator@1@@Z>

externdef __imp_?_InsertRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK_N@Z:PPROC
?_InsertRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK_N@Z equ <__imp_?_InsertRecord@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEBXK_N@Z>

externdef __imp_?_InsertThisIntoGlobalList@CLKRHashTable@@AEAAXXZ:PPROC
?_InsertThisIntoGlobalList@CLKRHashTable@@AEAAXXZ equ <__imp_?_InsertThisIntoGlobalList@CLKRHashTable@@AEAAXXZ>

externdef __imp_?_InsertThisIntoGlobalList@CLKRLinearHashTable@@AEAAXXZ:PPROC
?_InsertThisIntoGlobalList@CLKRLinearHashTable@@AEAAXXZ equ <__imp_?_InsertThisIntoGlobalList@CLKRLinearHashTable@@AEAAXXZ>

externdef __imp_?_IsLocked@CSpinLock@@AEBA_NXZ:PPROC
?_IsLocked@CSpinLock@@AEBA_NXZ equ <__imp_?_IsLocked@CSpinLock@@AEBA_NXZ>

externdef __imp_?_IsNodeCompact@CLKRLinearHashTable@@AEBAHQEAVCBucket@1@@Z:PPROC
?_IsNodeCompact@CLKRLinearHashTable@@AEBAHQEAVCBucket@1@@Z equ <__imp_?_IsNodeCompact@CLKRLinearHashTable@@AEBAHQEAVCBucket@1@@Z>

externdef __imp_?_Lock@CSpinLock@@AEAAXXZ:PPROC
?_Lock@CSpinLock@@AEAAXXZ equ <__imp_?_Lock@CSpinLock@@AEAAXXZ>

externdef __imp_?_LockSpin@CReaderWriterLock2@@AEAAX_N@Z:PPROC
?_LockSpin@CReaderWriterLock2@@AEAAX_N@Z equ <__imp_?_LockSpin@CReaderWriterLock2@@AEAAX_N@Z>

externdef __imp_?_LockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z:PPROC
?_LockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z equ <__imp_?_LockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z>

externdef __imp_?_LockSpin@CReaderWriterLock@@AEAAX_N@Z:PPROC
?_LockSpin@CReaderWriterLock@@AEAAX_N@Z equ <__imp_?_LockSpin@CReaderWriterLock@@AEAAX_N@Z>

externdef __imp_?_LockSpin@CSmallSpinLock@@AEAAXXZ:PPROC
?_LockSpin@CSmallSpinLock@@AEAAXXZ equ <__imp_?_LockSpin@CSmallSpinLock@@AEAAXXZ>

externdef __imp_?_LockSpin@CSpinLock@@AEAAXXZ:PPROC
?_LockSpin@CSpinLock@@AEAAXXZ equ <__imp_?_LockSpin@CSpinLock@@AEAAXXZ>

externdef __imp_?_MergeRecordSets@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCBucket@1@PEAVCNodeClump@1@1@Z:PPROC
?_MergeRecordSets@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCBucket@1@PEAVCNodeClump@1@1@Z equ <__imp_?_MergeRecordSets@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCBucket@1@PEAVCNodeClump@1@1@Z>

externdef __imp_?_PredTrue@CLKRLinearHashTable@@CA?AW4LK_PREDICATE@@PEBXPEAX@Z:PPROC
?_PredTrue@CLKRLinearHashTable@@CA?AW4LK_PREDICATE@@PEBXPEAX@Z equ <__imp_?_PredTrue@CLKRLinearHashTable@@CA?AW4LK_PREDICATE@@PEBXPEAX@Z>

externdef __imp_?_ReadLockSpin@CReaderWriterLock2@@AEAAXXZ:PPROC
?_ReadLockSpin@CReaderWriterLock2@@AEAAXXZ equ <__imp_?_ReadLockSpin@CReaderWriterLock2@@AEAAXXZ>

externdef __imp_?_ReadLockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z:PPROC
?_ReadLockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z equ <__imp_?_ReadLockSpin@CReaderWriterLock3@@AEAAXW4SPIN_TYPE@1@@Z>

externdef __imp_?_ReadLockSpin@CReaderWriterLock@@AEAAXXZ:PPROC
?_ReadLockSpin@CReaderWriterLock@@AEAAXXZ equ <__imp_?_ReadLockSpin@CReaderWriterLock@@AEAAXXZ>

externdef __imp_?_ReadOrWriteLock@CLKRLinearHashTable@@AEBA_NXZ:PPROC
?_ReadOrWriteLock@CLKRLinearHashTable@@AEBA_NXZ equ <__imp_?_ReadOrWriteLock@CLKRLinearHashTable@@AEBA_NXZ>

externdef __imp_?_ReadOrWriteUnlock@CLKRLinearHashTable@@AEBAX_N@Z:PPROC
?_ReadOrWriteUnlock@CLKRLinearHashTable@@AEBAX_N@Z equ <__imp_?_ReadOrWriteUnlock@CLKRLinearHashTable@@AEBAX_N@Z>

externdef __imp_?_RemoveThisFromGlobalList@CLKRHashTable@@AEAAXXZ:PPROC
?_RemoveThisFromGlobalList@CLKRHashTable@@AEAAXXZ equ <__imp_?_RemoveThisFromGlobalList@CLKRHashTable@@AEAAXXZ>

externdef __imp_?_RemoveThisFromGlobalList@CLKRLinearHashTable@@AEAAXXZ:PPROC
?_RemoveThisFromGlobalList@CLKRLinearHashTable@@AEAAXXZ equ <__imp_?_RemoveThisFromGlobalList@CLKRLinearHashTable@@AEAAXXZ>

externdef __imp_?_SegIndex@CLKRLinearHashTable@@AEBAKK@Z:PPROC
?_SegIndex@CLKRLinearHashTable@@AEBAKK@Z equ <__imp_?_SegIndex@CLKRLinearHashTable@@AEBAKK@Z>

externdef __imp_?_Segment@CLKRLinearHashTable@@AEBAAEAPEAVCSegment@1@K@Z:PPROC
?_Segment@CLKRLinearHashTable@@AEBAAEAPEAVCSegment@1@K@Z equ <__imp_?_Segment@CLKRLinearHashTable@@AEBAAEAPEAVCSegment@1@K@Z>

externdef __imp_?_SetSegVars@CLKRLinearHashTable@@AEAAXW4LK_TABLESIZE@@@Z:PPROC
?_SetSegVars@CLKRLinearHashTable@@AEAAXW4LK_TABLESIZE@@@Z equ <__imp_?_SetSegVars@CLKRLinearHashTable@@AEAAXW4LK_TABLESIZE@@@Z>

externdef __imp_?_SplitRecordSet@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCNodeClump@1@0KKK0@Z:PPROC
?_SplitRecordSet@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCNodeClump@1@0KKK0@Z equ <__imp_?_SplitRecordSet@CLKRLinearHashTable@@AEAA?AW4LK_RETCODE@@PEAVCNodeClump@1@0KKK0@Z>

externdef __imp_?_SubTable@CLKRHashTable@@AEBAPEAVCLKRLinearHashTable@@K@Z:PPROC
?_SubTable@CLKRHashTable@@AEBAPEAVCLKRLinearHashTable@@K@Z equ <__imp_?_SubTable@CLKRHashTable@@AEBAPEAVCLKRLinearHashTable@@K@Z>

externdef __imp_?_TryLock@CSmallSpinLock@@AEAA_NXZ:PPROC
?_TryLock@CSmallSpinLock@@AEAA_NXZ equ <__imp_?_TryLock@CSmallSpinLock@@AEAA_NXZ>

externdef __imp_?_TryLock@CSpinLock@@AEAA_NXZ:PPROC
?_TryLock@CSpinLock@@AEAA_NXZ equ <__imp_?_TryLock@CSpinLock@@AEAA_NXZ>

externdef __imp_?_TryReadLock@CReaderWriterLock2@@AEAA_NXZ:PPROC
?_TryReadLock@CReaderWriterLock2@@AEAA_NXZ equ <__imp_?_TryReadLock@CReaderWriterLock2@@AEAA_NXZ>

externdef __imp_?_TryReadLock@CReaderWriterLock3@@AEAA_NXZ:PPROC
?_TryReadLock@CReaderWriterLock3@@AEAA_NXZ equ <__imp_?_TryReadLock@CReaderWriterLock3@@AEAA_NXZ>

externdef __imp_?_TryReadLock@CReaderWriterLock@@AEAA_NXZ:PPROC
?_TryReadLock@CReaderWriterLock@@AEAA_NXZ equ <__imp_?_TryReadLock@CReaderWriterLock@@AEAA_NXZ>

externdef __imp_?_TryReadLockRecursive@CReaderWriterLock3@@AEAA_NXZ:PPROC
?_TryReadLockRecursive@CReaderWriterLock3@@AEAA_NXZ equ <__imp_?_TryReadLockRecursive@CReaderWriterLock3@@AEAA_NXZ>

externdef __imp_?_TryWriteLock2@CReaderWriterLock3@@AEAA_NXZ:PPROC
?_TryWriteLock2@CReaderWriterLock3@@AEAA_NXZ equ <__imp_?_TryWriteLock2@CReaderWriterLock3@@AEAA_NXZ>

externdef __imp_?_TryWriteLock@CReaderWriterLock2@@AEAA_NJ@Z:PPROC
?_TryWriteLock@CReaderWriterLock2@@AEAA_NJ@Z equ <__imp_?_TryWriteLock@CReaderWriterLock2@@AEAA_NJ@Z>

externdef __imp_?_TryWriteLock@CReaderWriterLock3@@AEAA_NJ@Z:PPROC
?_TryWriteLock@CReaderWriterLock3@@AEAA_NJ@Z equ <__imp_?_TryWriteLock@CReaderWriterLock3@@AEAA_NJ@Z>

externdef __imp_?_TryWriteLock@CReaderWriterLock@@AEAA_NXZ:PPROC
?_TryWriteLock@CReaderWriterLock@@AEAA_NXZ equ <__imp_?_TryWriteLock@CReaderWriterLock@@AEAA_NXZ>

externdef __imp_?_Unlock@CSpinLock@@AEAAXXZ:PPROC
?_Unlock@CSpinLock@@AEAAXXZ equ <__imp_?_Unlock@CSpinLock@@AEAAXXZ>

externdef __imp_?_WriteLockSpin@CReaderWriterLock2@@AEAAXXZ:PPROC
?_WriteLockSpin@CReaderWriterLock2@@AEAAXXZ equ <__imp_?_WriteLockSpin@CReaderWriterLock2@@AEAAXXZ>

externdef __imp_?_WriteLockSpin@CReaderWriterLock3@@AEAAXXZ:PPROC
?_WriteLockSpin@CReaderWriterLock3@@AEAAXXZ equ <__imp_?_WriteLockSpin@CReaderWriterLock3@@AEAAXXZ>

externdef __imp_?_WriteLockSpin@CReaderWriterLock@@AEAAXXZ:PPROC
?_WriteLockSpin@CReaderWriterLock@@AEAAXXZ equ <__imp_?_WriteLockSpin@CReaderWriterLock@@AEAAXXZ>

externdef __imp_?_getFileSecurity@CExFileOperation@@AEAAJPEBG@Z:PPROC
?_getFileSecurity@CExFileOperation@@AEAAJPEBG@Z equ <__imp_?_getFileSecurity@CExFileOperation@@AEAAJPEBG@Z>

externdef __imp_?_setFileSecurity@CExFileOperation@@AEAAJPEBG@Z:PPROC
?_setFileSecurity@CExFileOperation@@AEAAJPEBG@Z equ <__imp_?_setFileSecurity@CExFileOperation@@AEAAJPEBG@Z>

externdef __imp_?fHaveBackup@CEXAutoBackupFile@@QEAAHXZ:PPROC
?fHaveBackup@CEXAutoBackupFile@@QEAAHXZ equ <__imp_?fHaveBackup@CEXAutoBackupFile@@QEAAHXZ>

externdef __imp_?s_aBucketSizes@?1??BucketSizes@CLKRHashTableStats@@SAPEBJXZ@4QBJB:PPROC
?s_aBucketSizes@?1??BucketSizes@CLKRHashTableStats@@SAPEBJXZ@4QBJB equ <__imp_?s_aBucketSizes@?1??BucketSizes@CLKRHashTableStats@@SAPEBJXZ@4QBJB>

externdef __imp_?sm_dblDfltSpinAdjFctr@CCritSec@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CCritSec@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CCritSec@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CCritSec@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CCritSec@@1NA>
  ENDIF

externdef __imp_?sm_dblDfltSpinAdjFctr@CFakeLock@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CFakeLock@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CFakeLock@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CFakeLock@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CFakeLock@@1NA>
  ENDIF

externdef __imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock2@@1NA>
  ENDIF

externdef __imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock3@@1NA>
  ENDIF

externdef __imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CReaderWriterLock@@1NA>
  ENDIF

externdef __imp_?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CSmallSpinLock@@1NA>
  ENDIF

externdef __imp_?sm_dblDfltSpinAdjFctr@CSpinLock@@1NA:PPROC
?sm_dblDfltSpinAdjFctr@CSpinLock@@1NA equ <__imp_?sm_dblDfltSpinAdjFctr@CSpinLock@@1NA>
  IFNDEF __UNICODE__
    ?sm_dblDfltSpinAdjFctr@CSpinLock@@1N equ <__imp_?sm_dblDfltSpinAdjFctr@CSpinLock@@1NA>
  ENDIF

externdef __imp_?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@A:PPROC
?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@A equ <__imp_?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@A>
  IFNDEF __UNICODE__
    ?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@ equ <__imp_?sm_llGlobalList@CLKRHashTable@@0VCLockedDoubleList@@A>
  ENDIF

externdef __imp_?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@A:PPROC
?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@A equ <__imp_?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@A>
  IFNDEF __UNICODE__
    ?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@ equ <__imp_?sm_llGlobalList@CLKRLinearHashTable@@0VCLockedDoubleList@@A>
  ENDIF

externdef __imp_?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@EA:PPROC
?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@EA equ <__imp_?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@EA>
  IFNDEF __UNICODE__
    ?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@E equ <__imp_?sm_lpOSVERSIONINFO@CMdVersionInfo@@0PEAU_OSVERSIONINFOW@@EA>
  ENDIF

externdef __imp_?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZEA:PPROC
?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZEA equ <__imp_?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZEA>
  IFNDEF __UNICODE__
    ?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZE equ <__imp_?sm_pfnSetCriticalSectionSpinCount@CCriticalSection@@0P6AKPEAU_RTL_CRITICAL_SECTION@@K@ZEA>
  ENDIF

externdef __imp_?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZEA:PPROC
?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZEA equ <__imp_?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZEA>
  IFNDEF __UNICODE__
    ?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZE equ <__imp_?sm_pfnTryEnterCriticalSection@CCriticalSection@@0P6AHPEAU_RTL_CRITICAL_SECTION@@@ZEA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CCritSec@@1GA:PPROC
?sm_wDefaultSpinCount@CCritSec@@1GA equ <__imp_?sm_wDefaultSpinCount@CCritSec@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CCritSec@@1G equ <__imp_?sm_wDefaultSpinCount@CCritSec@@1GA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CFakeLock@@1GA:PPROC
?sm_wDefaultSpinCount@CFakeLock@@1GA equ <__imp_?sm_wDefaultSpinCount@CFakeLock@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CFakeLock@@1G equ <__imp_?sm_wDefaultSpinCount@CFakeLock@@1GA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CReaderWriterLock2@@1GA:PPROC
?sm_wDefaultSpinCount@CReaderWriterLock2@@1GA equ <__imp_?sm_wDefaultSpinCount@CReaderWriterLock2@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CReaderWriterLock2@@1G equ <__imp_?sm_wDefaultSpinCount@CReaderWriterLock2@@1GA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CReaderWriterLock3@@1GA:PPROC
?sm_wDefaultSpinCount@CReaderWriterLock3@@1GA equ <__imp_?sm_wDefaultSpinCount@CReaderWriterLock3@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CReaderWriterLock3@@1G equ <__imp_?sm_wDefaultSpinCount@CReaderWriterLock3@@1GA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CReaderWriterLock@@1GA:PPROC
?sm_wDefaultSpinCount@CReaderWriterLock@@1GA equ <__imp_?sm_wDefaultSpinCount@CReaderWriterLock@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CReaderWriterLock@@1G equ <__imp_?sm_wDefaultSpinCount@CReaderWriterLock@@1GA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CSmallSpinLock@@1GA:PPROC
?sm_wDefaultSpinCount@CSmallSpinLock@@1GA equ <__imp_?sm_wDefaultSpinCount@CSmallSpinLock@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CSmallSpinLock@@1G equ <__imp_?sm_wDefaultSpinCount@CSmallSpinLock@@1GA>
  ENDIF

externdef __imp_?sm_wDefaultSpinCount@CSpinLock@@1GA:PPROC
?sm_wDefaultSpinCount@CSpinLock@@1GA equ <__imp_?sm_wDefaultSpinCount@CSpinLock@@1GA>
  IFNDEF __UNICODE__
    ?sm_wDefaultSpinCount@CSpinLock@@1G equ <__imp_?sm_wDefaultSpinCount@CSpinLock@@1GA>
  ENDIF

externdef __imp_DllBidEntryPoint:PPROC
DllBidEntryPoint equ <__imp_DllBidEntryPoint>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_FXMemAttach:PPROC
FXMemAttach equ <__imp_FXMemAttach>

externdef __imp_FXMemDetach:PPROC
FXMemDetach equ <__imp_FXMemDetach>

externdef __imp_GetIUMS:PPROC
GetIUMS equ <__imp_GetIUMS>

externdef __imp_IrtlTrace:PPROC
IrtlTrace equ <__imp_IrtlTrace>

externdef __imp_IsValidAddress:PPROC
IsValidAddress equ <__imp_IsValidAddress>

externdef __imp_IsValidString:PPROC
IsValidString equ <__imp_IsValidString>

externdef __imp_LoadVersionedResourceEx:PPROC
LoadVersionedResourceEx equ <__imp_LoadVersionedResourceEx>

externdef __imp_MPCSInitialize:PPROC
MPCSInitialize equ <__imp_MPCSInitialize>

externdef __imp_MPCSUninitialize:PPROC
MPCSUninitialize equ <__imp_MPCSUninitialize>

externdef __imp_MPDeleteCriticalSection:PPROC
MPDeleteCriticalSection equ <__imp_MPDeleteCriticalSection>

externdef __imp_MPInitializeCriticalSection:PPROC
MPInitializeCriticalSection equ <__imp_MPInitializeCriticalSection>

externdef __imp_MPInitializeCriticalSectionAndSpinCount:PPROC
MPInitializeCriticalSectionAndSpinCount equ <__imp_MPInitializeCriticalSectionAndSpinCount>

externdef __imp_MpGetHeapHandle:PPROC
MpGetHeapHandle equ <__imp_MpGetHeapHandle>

externdef __imp_MpHeapAlloc:PPROC
MpHeapAlloc equ <__imp_MpHeapAlloc>

externdef __imp_MpHeapCreate:PPROC
MpHeapCreate equ <__imp_MpHeapCreate>

externdef __imp_MpHeapDestroy:PPROC
MpHeapDestroy equ <__imp_MpHeapDestroy>

externdef __imp_MpHeapFree:PPROC
MpHeapFree equ <__imp_MpHeapFree>

externdef __imp_MpHeapReAlloc:PPROC
MpHeapReAlloc equ <__imp_MpHeapReAlloc>

externdef __imp_MpHeapSize:PPROC
MpHeapSize equ <__imp_MpHeapSize>

externdef __imp_MpHeapValidate:PPROC
MpHeapValidate equ <__imp_MpHeapValidate>

externdef __imp_SetIUMS:PPROC
SetIUMS equ <__imp_SetIUMS>

externdef __imp_SetMemHook:PPROC
SetMemHook equ <__imp_SetMemHook>

externdef __imp_UMSEnterCSWraper:PPROC
UMSEnterCSWraper equ <__imp_UMSEnterCSWraper>

externdef __imp_mpCalloc:PPROC
mpCalloc equ <__imp_mpCalloc>

externdef __imp_mpFree:PPROC
mpFree equ <__imp_mpFree>

externdef __imp_mpMalloc:PPROC
mpMalloc equ <__imp_mpMalloc>

externdef __imp_mpRealloc:PPROC
mpRealloc equ <__imp_mpRealloc>
