externdef __imp_??0CDac@@QEAA@AEBV0@@Z:PPROC
??0CDac@@QEAA@AEBV0@@Z equ <__imp_??0CDac@@QEAA@AEBV0@@Z>

externdef __imp_??0CDac@@QEAA@K@Z:PPROC
??0CDac@@QEAA@K@Z equ <__imp_??0CDac@@QEAA@K@Z>

externdef __imp_??1CDac@@QEAA@XZ:PPROC
??1CDac@@QEAA@XZ equ <__imp_??1CDac@@QEAA@XZ>

externdef __imp_??4CDac@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CDac@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CDac@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_?Connect@CDac@@QEAAHPEAUHWND__@@PEAUINTServiceControl@@@Z:PPROC
?Connect@CDac@@QEAAHPEAUHWND__@@PEAUINTServiceControl@@@Z equ <__imp_?Connect@CDac@@QEAAHPEAUHWND__@@PEAUINTServiceControl@@@Z>

externdef __imp_?Create@CUicCore@@SAJPEAPEAV1@@Z:PPROC
?Create@CUicCore@@SAJPEAPEAV1@@Z equ <__imp_?Create@CUicCore@@SAJPEAPEAV1@@Z>

externdef __imp_?CreateAdvancedPropertySheet@CDac@@QEAAPEAVCDialog@@PEAVCWnd@@@Z:PPROC
?CreateAdvancedPropertySheet@CDac@@QEAAPEAVCDialog@@PEAVCWnd@@@Z equ <__imp_?CreateAdvancedPropertySheet@CDac@@QEAAPEAVCDialog@@PEAVCWnd@@@Z>

externdef __imp_?ErrorMessage@CDac@@QEAAHKI@Z:PPROC
?ErrorMessage@CDac@@QEAAHKI@Z equ <__imp_?ErrorMessage@CDac@@QEAAHKI@Z>

externdef __imp_?GetAdminAccess@CDac@@QEAAKXZ:PPROC
?GetAdminAccess@CDac@@QEAAKXZ equ <__imp_?GetAdminAccess@CDac@@QEAAKXZ>

externdef __imp_?GetHostNameA@CDac@@QEAAPEADXZ:PPROC
?GetHostNameA@CDac@@QEAAPEADXZ equ <__imp_?GetHostNameA@CDac@@QEAAPEADXZ>

externdef __imp_?GetHostNameW@CDac@@QEAAPEAGXZ:PPROC
?GetHostNameW@CDac@@QEAAPEAGXZ equ <__imp_?GetHostNameW@CDac@@QEAAPEAGXZ>

externdef __imp_?GetOwnerHwnd@CDac@@QEAAPEAUHWND__@@XZ:PPROC
?GetOwnerHwnd@CDac@@QEAAPEAUHWND__@@XZ equ <__imp_?GetOwnerHwnd@CDac@@QEAAPEAUHWND__@@XZ>

externdef __imp_?GetVirtualHostName@CDac@@QEAAPEAGXZ:PPROC
?GetVirtualHostName@CDac@@QEAAPEAGXZ equ <__imp_?GetVirtualHostName@CDac@@QEAAPEAGXZ>

externdef __imp_?Init@CDac@@QEAAJPEAG@Z:PPROC
?Init@CDac@@QEAAJPEAG@Z equ <__imp_?Init@CDac@@QEAAJPEAG@Z>

externdef __imp_?IsConnected@CDac@@QEAAHXZ:PPROC
?IsConnected@CDac@@QEAAHXZ equ <__imp_?IsConnected@CDac@@QEAAHXZ>

externdef __imp_?ProcessCommand@CDac@@QEAAH_K_J@Z:PPROC
?ProcessCommand@CDac@@QEAAH_K_J@Z equ <__imp_?ProcessCommand@CDac@@QEAAH_K_J@Z>

externdef __imp_?RegisterErrorSink@@YAXPEAUIDacErrorSink@@@Z:PPROC
?RegisterErrorSink@@YAXPEAUIDacErrorSink@@@Z equ <__imp_?RegisterErrorSink@@YAXPEAUIDacErrorSink@@@Z>

externdef __imp_?ServiceRequest@CDac@@QEAAJKPEAXK_N@Z:PPROC
?ServiceRequest@CDac@@QEAAJKPEAXK_N@Z equ <__imp_?ServiceRequest@CDac@@QEAAJKPEAXK_N@Z>

externdef __imp_?SetHostNameA@CDac@@QEAAXPEAD@Z:PPROC
?SetHostNameA@CDac@@QEAAXPEAD@Z equ <__imp_?SetHostNameA@CDac@@QEAAXPEAD@Z>

externdef __imp_?SetHostNameW@CDac@@QEAAXPEAG@Z:PPROC
?SetHostNameW@CDac@@QEAAXPEAG@Z equ <__imp_?SetHostNameW@CDac@@QEAAXPEAG@Z>

externdef __imp_?SetOwnerWnd@CDac@@QEAAXPEAVCWnd@@@Z:PPROC
?SetOwnerWnd@CDac@@QEAAXPEAVCWnd@@@Z equ <__imp_?SetOwnerWnd@CDac@@QEAAXPEAVCWnd@@@Z>

externdef __imp_?ValidateDACInstance@@YAPEAVCDac@@PEAPEAXPEAG@Z:PPROC
?ValidateDACInstance@@YAPEAVCDac@@PEAPEAXPEAG@Z equ <__imp_?ValidateDACInstance@@YAPEAVCDac@@PEAPEAXPEAG@Z>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllGetDTCUIC:PPROC
DllGetDTCUIC equ <__imp_DllGetDTCUIC>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DoDACAdvanced:PPROC
DoDACAdvanced equ <__imp_DoDACAdvanced>

externdef __imp_DoDACPropSheet:PPROC
DoDACPropSheet equ <__imp_DoDACPropSheet>

externdef __imp_DtcPerfClose:PPROC
DtcPerfClose equ <__imp_DtcPerfClose>

externdef __imp_DtcPerfCollect:PPROC
DtcPerfCollect equ <__imp_DtcPerfCollect>

externdef __imp_DtcPerfOpen:PPROC
DtcPerfOpen equ <__imp_DtcPerfOpen>

externdef __imp_GetDACStatsMinMaxInfo:PPROC
GetDACStatsMinMaxInfo equ <__imp_GetDACStatsMinMaxInfo>

externdef __imp_InitDACDLL:PPROC
InitDACDLL equ <__imp_InitDACDLL>

externdef __imp_PerfDllRegisterServer:PPROC
PerfDllRegisterServer equ <__imp_PerfDllRegisterServer>

externdef __imp_RunDACExe:PPROC
RunDACExe equ <__imp_RunDACExe>

externdef __imp_ShutDownUIC:PPROC
ShutDownUIC equ <__imp_ShutDownUIC>

externdef __imp_TermDACDLL:PPROC
TermDACDLL equ <__imp_TermDACDLL>

externdef __imp_TermDACInstance:PPROC
TermDACInstance equ <__imp_TermDACInstance>
