externdef __imp_?Create@CUISCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PPROC
?Create@CUISCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z equ <__imp_?Create@CUISCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z>

externdef __imp_?CreateInstance@CTm@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PPROC
?CreateInstance@CTm@@SAJPEAPEAV1@PEAUIUnknown@@@Z equ <__imp_?CreateInstance@CTm@@SAJPEAPEAV1@PEAUIUnknown@@@Z>

externdef __imp_?CreateInstance@CXaTmCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PPROC
?CreateInstance@CXaTmCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z equ <__imp_?CreateInstance@CXaTmCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z>

externdef __imp_?CreateThreadPool@@YAJXZ:PPROC
?CreateThreadPool@@YAJXZ equ <__imp_?CreateThreadPool@@YAJXZ>

externdef __imp_ASCDefer:PPROC
ASCDefer equ <__imp_ASCDefer>

externdef __imp_ASCDeliverDeferred:PPROC
ASCDeliverDeferred equ <__imp_ASCDeliverDeferred>

externdef __imp_ASCGetSafeReference:PPROC
ASCGetSafeReference equ <__imp_ASCGetSafeReference>

externdef __imp_ASCWrapClassFactory:PPROC
ASCWrapClassFactory equ <__imp_ASCWrapClassFactory>

externdef __imp_ASCWrapObject:PPROC
ASCWrapObject equ <__imp_ASCWrapObject>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DtcMainExt:PPROC
DtcMainExt equ <__imp_DtcMainExt>

externdef __imp_GetTipFunctionalityWorking:PPROC
GetTipFunctionalityWorking equ <__imp_GetTipFunctionalityWorking>

externdef __imp_SetTipFunctionalityWorking:PPROC
SetTipFunctionalityWorking equ <__imp_SetTipFunctionalityWorking>
