externdef __imp_??0CSecurityDescriptor@@QEAA@XZ:PPROC
??0CSecurityDescriptor@@QEAA@XZ equ <__imp_??0CSecurityDescriptor@@QEAA@XZ>

externdef __imp_??0CService@@IEAA@XZ:PPROC
??0CService@@IEAA@XZ equ <__imp_??0CService@@IEAA@XZ>

externdef __imp_??0CServiceControlManager@@IEAA@XZ:PPROC
??0CServiceControlManager@@IEAA@XZ equ <__imp_??0CServiceControlManager@@IEAA@XZ>

externdef __imp_??1CSecurityDescriptor@@QEAA@XZ:PPROC
??1CSecurityDescriptor@@QEAA@XZ equ <__imp_??1CSecurityDescriptor@@QEAA@XZ>

externdef __imp_??1CService@@IEAA@XZ:PPROC
??1CService@@IEAA@XZ equ <__imp_??1CService@@IEAA@XZ>

externdef __imp_??1CServiceControlManager@@IEAA@XZ:PPROC
??1CServiceControlManager@@IEAA@XZ equ <__imp_??1CServiceControlManager@@IEAA@XZ>

externdef __imp_??4CSecurityDescriptor@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CSecurityDescriptor@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CSecurityDescriptor@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CService@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CService@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CService@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CServiceControlManager@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CServiceControlManager@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CServiceControlManager@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_?AddRef@CService@@QEAAKXZ:PPROC
?AddRef@CService@@QEAAKXZ equ <__imp_?AddRef@CService@@QEAAKXZ>

externdef __imp_?AddRef@CServiceControlManager@@QEAAKXZ:PPROC
?AddRef@CServiceControlManager@@QEAAKXZ equ <__imp_?AddRef@CServiceControlManager@@QEAAKXZ>

externdef __imp_?AddSid@CSecurityDescriptor@@QEAAJPEAGKK@Z:PPROC
?AddSid@CSecurityDescriptor@@QEAAJPEAGKK@Z equ <__imp_?AddSid@CSecurityDescriptor@@QEAAJPEAGKK@Z>

externdef __imp_?AddSid@CSecurityDescriptor@@QEAAJPEAXKK@Z:PPROC
?AddSid@CSecurityDescriptor@@QEAAJPEAXKK@Z equ <__imp_?AddSid@CSecurityDescriptor@@QEAAJPEAXKK@Z>

externdef __imp_?Alloc@CSecurityDescriptor@@IEAAJK@Z:PPROC
?Alloc@CSecurityDescriptor@@IEAAJK@Z equ <__imp_?Alloc@CSecurityDescriptor@@IEAAJK@Z>

externdef __imp_?ApplyAccountSettings@@YAJHPEAGK000H@Z:PPROC
?ApplyAccountSettings@@YAJHPEAGK000H@Z equ <__imp_?ApplyAccountSettings@@YAJHPEAGK000H@Z>

externdef __imp_?ApplyNamedSecurityChange@@YAJPEAGW4_SE_OBJECT_TYPE@@PEAX2K@Z:PPROC
?ApplyNamedSecurityChange@@YAJPEAGW4_SE_OBJECT_TYPE@@PEAX2K@Z equ <__imp_?ApplyNamedSecurityChange@@YAJPEAGW4_SE_OBJECT_TYPE@@PEAX2K@Z>

externdef __imp_?CheckForDCPromotionDemotion@@YAJPEAG@Z:PPROC
?CheckForDCPromotionDemotion@@YAJPEAG@Z equ <__imp_?CheckForDCPromotionDemotion@@YAJPEAG@Z>

externdef __imp_?ClearAcl@CSecurityDescriptor@@QEAAJXZ:PPROC
?ClearAcl@CSecurityDescriptor@@QEAAJXZ equ <__imp_?ClearAcl@CSecurityDescriptor@@QEAAJXZ>

externdef __imp_?ClearInMemoryAcl@CSecurityDescriptor@@QEAAJXZ:PPROC
?ClearInMemoryAcl@CSecurityDescriptor@@QEAAJXZ equ <__imp_?ClearInMemoryAcl@CSecurityDescriptor@@QEAAJXZ>

externdef __imp_?CloseNetpEventLogHandle@@YAXXZ:PPROC
?CloseNetpEventLogHandle@@YAXXZ equ <__imp_?CloseNetpEventLogHandle@@YAXXZ>

externdef __imp_?Create@CConnectionManager@@SAJPEAPEAV1@@Z:PPROC
?Create@CConnectionManager@@SAJPEAPEAV1@@Z equ <__imp_?Create@CConnectionManager@@SAJPEAPEAV1@@Z>

externdef __imp_?Create@CNameService@@SAJPEAPEAV1@@Z:PPROC
?Create@CNameService@@SAJPEAPEAV1@@Z equ <__imp_?Create@CNameService@@SAJPEAPEAV1@@Z>

externdef __imp_?Create@CService@@SAJPEAPEAV1@PEAGPEAVCServiceControlManager@@K1@Z:PPROC
?Create@CService@@SAJPEAPEAV1@PEAGPEAVCServiceControlManager@@K1@Z equ <__imp_?Create@CService@@SAJPEAPEAV1@PEAGPEAVCServiceControlManager@@K1@Z>

externdef __imp_?Create@CServiceControlManager@@SAJPEAPEAV1@KPEAG1@Z:PPROC
?Create@CServiceControlManager@@SAJPEAPEAV1@KPEAG1@Z equ <__imp_?Create@CServiceControlManager@@SAJPEAPEAV1@KPEAG1@Z>

externdef __imp_?CreateASRKey@@YAXXZ:PPROC
?CreateASRKey@@YAXXZ equ <__imp_?CreateASRKey@@YAXXZ>

externdef __imp_?CreateInstance@CTmProxyCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z:PPROC
?CreateInstance@CTmProxyCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z equ <__imp_?CreateInstance@CTmProxyCore@@SAJPEAPEAV1@PEAUIUnknown@@@Z>

externdef __imp_?CreateNewContact@@YAJPEAPEAUIProperties@@@Z:PPROC
?CreateNewContact@@YAJPEAPEAUIProperties@@@Z equ <__imp_?CreateNewContact@@YAJPEAPEAUIProperties@@@Z>

externdef __imp_?CreateOrOpenMutexW@@YAJPEAPEAXPEBGH@Z:PPROC
?CreateOrOpenMutexW@@YAJPEAPEAXPEBGH@Z equ <__imp_?CreateOrOpenMutexW@@YAJPEAPEAXPEBGH@Z>

externdef __imp_?DeleteExistingContacts@@YAXPEAGPEAUIContactPool@@0@Z:PPROC
?DeleteExistingContacts@@YAXPEAGPEAUIContactPool@@0@Z equ <__imp_?DeleteExistingContacts@@YAXPEAGPEAUIContactPool@@0@Z>

externdef __imp_?DllGetDTCAdmin@@YAHAEBU_GUID@@0PEAPEAX@Z:PPROC
?DllGetDTCAdmin@@YAHAEBU_GUID@@0PEAPEAX@Z equ <__imp_?DllGetDTCAdmin@@YAHAEBU_GUID@@0PEAPEAX@Z>

externdef __imp_?DtcWriteToEventLogger@@YAJKKKKPEAXPEAD@Z:PPROC
?DtcWriteToEventLogger@@YAJKKKKPEAXPEAD@Z equ <__imp_?DtcWriteToEventLogger@@YAJKKKKPEAXPEAD@Z>

externdef __imp_?DtcWriteToEventLoggerEx@@YAJGGKPEAXGKPEAPEBD0@Z:PPROC
?DtcWriteToEventLoggerEx@@YAJGGKPEAXGKPEAPEBD0@Z equ <__imp_?DtcWriteToEventLoggerEx@@YAJGGKPEAXGKPEAPEBD0@Z>

externdef __imp_?DtcWriteToEventLoggerExUnFiltered@@YAJGGKPEAXGKPEAPEBD0@Z:PPROC
?DtcWriteToEventLoggerExUnFiltered@@YAJGGKPEAXGKPEAPEBD0@Z equ <__imp_?DtcWriteToEventLoggerExUnFiltered@@YAJGGKPEAXGKPEAPEBD0@Z>

externdef __imp_?DtcWriteToEventLoggerExUnFilteredA@@YAJGGKPEAXGKPEAPEBD0@Z:PPROC
?DtcWriteToEventLoggerExUnFilteredA@@YAJGGKPEAXGKPEAPEBD0@Z equ <__imp_?DtcWriteToEventLoggerExUnFilteredA@@YAJGGKPEAXGKPEAPEBD0@Z>

externdef __imp_?EraseDtcClient@@YAJPEAG@Z:PPROC
?EraseDtcClient@@YAJPEAG@Z equ <__imp_?EraseDtcClient@@YAJPEAG@Z>

externdef __imp_?GetAccount@CService@@QEAAJPEAGPEAK@Z:PPROC
?GetAccount@CService@@QEAAJPEAGPEAK@Z equ <__imp_?GetAccount@CService@@QEAAJPEAGPEAK@Z>

externdef __imp_?GetAccountSid@@YAJPEAG0PEAPEAX@Z:PPROC
?GetAccountSid@@YAJPEAG0PEAPEAX@Z equ <__imp_?GetAccountSid@@YAJPEAG0PEAPEAX@Z>

externdef __imp_?GetControl@CSecurityDescriptor@@QEAAJPEAG@Z:PPROC
?GetControl@CSecurityDescriptor@@QEAAJPEAG@Z equ <__imp_?GetControl@CSecurityDescriptor@@QEAAJPEAG@Z>

externdef __imp_?GetDefaultLogPath@@YAPEAGXZ:PPROC
?GetDefaultLogPath@@YAPEAGXZ equ <__imp_?GetDefaultLogPath@@YAPEAGXZ>

externdef __imp_?GetDefaultLogSize@@YAKXZ:PPROC
?GetDefaultLogSize@@YAKXZ equ <__imp_?GetDefaultLogSize@@YAKXZ>

externdef __imp_?GetDefaultSecurityConfigurationOptions@@YAJPEAGPEAK1@Z:PPROC
?GetDefaultSecurityConfigurationOptions@@YAJPEAGPEAK1@Z equ <__imp_?GetDefaultSecurityConfigurationOptions@@YAJPEAGPEAK1@Z>

externdef __imp_?GetDefaultServiceNameA@@YAPEADXZ:PPROC
?GetDefaultServiceNameA@@YAPEADXZ equ <__imp_?GetDefaultServiceNameA@@YAPEADXZ>

externdef __imp_?GetDefaultServiceNameW@@YAPEAGXZ:PPROC
?GetDefaultServiceNameW@@YAPEAGXZ equ <__imp_?GetDefaultServiceNameW@@YAPEAGXZ>

externdef __imp_?GetDefaultServicePath@@YAPEAGXZ:PPROC
?GetDefaultServicePath@@YAPEAGXZ equ <__imp_?GetDefaultServicePath@@YAPEAGXZ>

externdef __imp_?GetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z:PPROC
?GetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z equ <__imp_?GetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z>

externdef __imp_?GetDtcLogPath@@YAHKPEAG@Z:PPROC
?GetDtcLogPath@@YAHKPEAG@Z equ <__imp_?GetDtcLogPath@@YAHKPEAG@Z>

externdef __imp_?GetDtcPath@@YAHKPEAG@Z:PPROC
?GetDtcPath@@YAHKPEAG@Z equ <__imp_?GetDtcPath@@YAHKPEAG@Z>

externdef __imp_?GetDtcRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z:PPROC
?GetDtcRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z equ <__imp_?GetDtcRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z>

externdef __imp_?GetDtcRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z:PPROC
?GetDtcRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z equ <__imp_?GetDtcRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z>

externdef __imp_?GetDtcRpcSecurityLevel@@YAJPEAGPEAW4_DTC_SECURITY_LEVEL@@H@Z:PPROC
?GetDtcRpcSecurityLevel@@YAJPEAGPEAW4_DTC_SECURITY_LEVEL@@H@Z equ <__imp_?GetDtcRpcSecurityLevel@@YAJPEAGPEAW4_DTC_SECURITY_LEVEL@@H@Z>

externdef __imp_?GetEventLogSource@@YAPEAGXZ:PPROC
?GetEventLogSource@@YAPEAGXZ equ <__imp_?GetEventLogSource@@YAPEAGXZ>

externdef __imp_?GetHandle@CService@@QEAAJAEAPEAUSC_HANDLE__@@@Z:PPROC
?GetHandle@CService@@QEAAJAEAPEAUSC_HANDLE__@@@Z equ <__imp_?GetHandle@CService@@QEAAJAEAPEAUSC_HANDLE__@@@Z>

externdef __imp_?GetHandle@CServiceControlManager@@QEAAJAEAPEAUSC_HANDLE__@@@Z:PPROC
?GetHandle@CServiceControlManager@@QEAAJAEAPEAUSC_HANDLE__@@@Z equ <__imp_?GetHandle@CServiceControlManager@@QEAAJAEAPEAUSC_HANDLE__@@@Z>

externdef __imp_?GetLastKnownDomainControllerState@@YAJPEAGPEAK@Z:PPROC
?GetLastKnownDomainControllerState@@YAJPEAGPEAK@Z equ <__imp_?GetLastKnownDomainControllerState@@YAJPEAGPEAK@Z>

externdef __imp_?GetLocalDtcClusteringVersion@@YAJPEAK@Z:PPROC
?GetLocalDtcClusteringVersion@@YAJPEAK@Z equ <__imp_?GetLocalDtcClusteringVersion@@YAJPEAK@Z>

externdef __imp_?GetMsDtcSPN@@YAJPEAGPEAPEAG@Z:PPROC
?GetMsDtcSPN@@YAJPEAGPEAPEAG@Z equ <__imp_?GetMsDtcSPN@@YAJPEAGPEAPEAG@Z>

externdef __imp_?GetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@@Z:PPROC
?GetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@@Z equ <__imp_?GetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@@Z>

externdef __imp_?GetOldDefaultLogPath@@YAPEAGXZ:PPROC
?GetOldDefaultLogPath@@YAPEAGXZ equ <__imp_?GetOldDefaultLogPath@@YAPEAGXZ>

externdef __imp_?GetSecurityConfigurationOptions@@YAJPEAGPEAK1H@Z:PPROC
?GetSecurityConfigurationOptions@@YAJPEAGPEAK1H@Z equ <__imp_?GetSecurityConfigurationOptions@@YAJPEAGPEAK1H@Z>

externdef __imp_?GetSecurityDescriptor@CSecurityDescriptor@@QEAAJPEAPEAX@Z:PPROC
?GetSecurityDescriptor@CSecurityDescriptor@@QEAAJPEAPEAX@Z equ <__imp_?GetSecurityDescriptor@CSecurityDescriptor@@QEAAJPEAPEAX@Z>

externdef __imp_?GetSecurityRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z:PPROC
?GetSecurityRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z equ <__imp_?GetSecurityRegValueNonClusterW@@YAJPEAGPEBGPEAEPEAK@Z>

externdef __imp_?GetSecurityRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z:PPROC
?GetSecurityRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z equ <__imp_?GetSecurityRegValueW@@YAJPEAGPEBGPEAEPEAKH@Z>

externdef __imp_?GetSharedDtcClusteringVersion@@YAJPEAK@Z:PPROC
?GetSharedDtcClusteringVersion@@YAJPEAK@Z equ <__imp_?GetSharedDtcClusteringVersion@@YAJPEAK@Z>

externdef __imp_?GetTmContactA@@YAJPEAD0PEAPEAUIProperties@@@Z:PPROC
?GetTmContactA@@YAJPEAD0PEAPEAUIProperties@@@Z equ <__imp_?GetTmContactA@@YAJPEAD0PEAPEAUIProperties@@@Z>

externdef __imp_?GetTmContactW@@YAJPEAG0PEAPEAUIProperties@@@Z:PPROC
?GetTmContactW@@YAJPEAG0PEAPEAUIProperties@@@Z equ <__imp_?GetTmContactW@@YAJPEAG0PEAPEAUIProperties@@@Z>

externdef __imp_?GetTmUIContactA@@YAJPEAD0PEAPEAUIProperties@@@Z:PPROC
?GetTmUIContactA@@YAJPEAD0PEAPEAUIProperties@@@Z equ <__imp_?GetTmUIContactA@@YAJPEAD0PEAPEAUIProperties@@@Z>

externdef __imp_?GetTmUIContactW@@YAJPEAG0PEAPEAUIProperties@@@Z:PPROC
?GetTmUIContactW@@YAJPEAG0PEAPEAUIProperties@@@Z equ <__imp_?GetTmUIContactW@@YAJPEAG0PEAPEAUIProperties@@@Z>

externdef __imp_?GetXATmSecurityKey@@YAJPEAG0PEAK@Z:PPROC
?GetXATmSecurityKey@@YAJPEAG0PEAK@Z equ <__imp_?GetXATmSecurityKey@@YAJPEAG0PEAK@Z>

externdef __imp_?InstallDtc@@YAJPEAG0000K0H@Z:PPROC
?InstallDtc@@YAJPEAG0000K0H@Z equ <__imp_?InstallDtc@@YAJPEAG0000K0H@Z>

externdef __imp_?InstallDtcClient@@YAJPEAGKK@Z:PPROC
?InstallDtcClient@@YAJPEAGKK@Z equ <__imp_?InstallDtcClient@@YAJPEAGKK@Z>

externdef __imp_?InstallTipGw@@YAJPEAG@Z:PPROC
?InstallTipGw@@YAJPEAG@Z equ <__imp_?InstallTipGw@@YAJPEAG@Z>

externdef __imp_?InstallXaTm@@YAJPEAG@Z:PPROC
?InstallXaTm@@YAJPEAG@Z equ <__imp_?InstallXaTm@@YAJPEAG@Z>

externdef __imp_?InternalInit@CService@@IEAAJPEAGPEAVCServiceControlManager@@K0@Z:PPROC
?InternalInit@CService@@IEAAJPEAGPEAVCServiceControlManager@@K0@Z equ <__imp_?InternalInit@CService@@IEAAJPEAGPEAVCServiceControlManager@@K0@Z>

externdef __imp_?InternalInit@CServiceControlManager@@IEAAJKPEAG0@Z:PPROC
?InternalInit@CServiceControlManager@@IEAAJKPEAG0@Z equ <__imp_?InternalInit@CServiceControlManager@@IEAAJKPEAG0@Z>

externdef __imp_?IsNtVersion5OrMore@@YAHXZ:PPROC
?IsNtVersion5OrMore@@YAHXZ equ <__imp_?IsNtVersion5OrMore@@YAHXZ>

externdef __imp_?JoinDtc@@YAJXZ:PPROC
?JoinDtc@@YAJXZ equ <__imp_?JoinDtc@@YAJXZ>

externdef __imp_?JoinDtcEx@@YAJPEAG@Z:PPROC
?JoinDtcEx@@YAJPEAG@Z equ <__imp_?JoinDtcEx@@YAJPEAG@Z>

externdef __imp_?LookupSpecialAccount@@YAJPEAGPEAPEAU_SPECIAL_ACCOUNT_@@@Z:PPROC
?LookupSpecialAccount@@YAJPEAGPEAPEAU_SPECIAL_ACCOUNT_@@@Z equ <__imp_?LookupSpecialAccount@@YAJPEAGPEAPEAU_SPECIAL_ACCOUNT_@@@Z>

externdef __imp_?MakeAbsolute@CSecurityDescriptor@@IEAAJXZ:PPROC
?MakeAbsolute@CSecurityDescriptor@@IEAAJXZ equ <__imp_?MakeAbsolute@CSecurityDescriptor@@IEAAJXZ>

externdef __imp_?MirrorXaTmSecurityKey@@YAJPEAG@Z:PPROC
?MirrorXaTmSecurityKey@@YAJPEAG@Z equ <__imp_?MirrorXaTmSecurityKey@@YAJPEAG@Z>

externdef __imp_?MsDtcSPNFree@@YAJPEAPEAG@Z:PPROC
?MsDtcSPNFree@@YAJPEAPEAG@Z equ <__imp_?MsDtcSPNFree@@YAJPEAPEAG@Z>

externdef __imp_?OpenServiceA@CServiceControlManager@@QEAAJPEAPEAVCService@@PEAGK@Z:PPROC
?OpenServiceA@CServiceControlManager@@QEAAJPEAPEAVCService@@PEAGK@Z equ <__imp_?OpenServiceA@CServiceControlManager@@QEAAJPEAPEAVCService@@PEAGK@Z>

externdef __imp_?PopulateLocalRegistry@@YAJXZ:PPROC
?PopulateLocalRegistry@@YAJXZ equ <__imp_?PopulateLocalRegistry@@YAJXZ>

externdef __imp_?PopulateSharedClusterRegistryWithContacts@@YAJXZ:PPROC
?PopulateSharedClusterRegistryWithContacts@@YAJXZ equ <__imp_?PopulateSharedClusterRegistryWithContacts@@YAJXZ>

externdef __imp_?PopulateSharedClusterRegistryWithLogInfo@@YAJXZ:PPROC
?PopulateSharedClusterRegistryWithLogInfo@@YAJXZ equ <__imp_?PopulateSharedClusterRegistryWithLogInfo@@YAJXZ>

externdef __imp_?QueryServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z:PPROC
?QueryServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z equ <__imp_?QueryServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z>

externdef __imp_?Release@CService@@QEAAKXZ:PPROC
?Release@CService@@QEAAKXZ equ <__imp_?Release@CService@@QEAAKXZ>

externdef __imp_?Release@CServiceControlManager@@QEAAKXZ:PPROC
?Release@CServiceControlManager@@QEAAKXZ equ <__imp_?Release@CServiceControlManager@@QEAAKXZ>

externdef __imp_?RemoveDtc@@YAJPEAG00@Z:PPROC
?RemoveDtc@@YAJPEAG00@Z equ <__imp_?RemoveDtc@@YAJPEAG00@Z>

externdef __imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAG@Z:PPROC
?RemoveSid@CSecurityDescriptor@@QEAAJPEAG@Z equ <__imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAG@Z>

externdef __imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAX@Z:PPROC
?RemoveSid@CSecurityDescriptor@@QEAAJPEAX@Z equ <__imp_?RemoveSid@CSecurityDescriptor@@QEAAJPEAX@Z>

externdef __imp_?Reset@CSecurityDescriptor@@IEAAXXZ:PPROC
?Reset@CSecurityDescriptor@@IEAAXXZ equ <__imp_?Reset@CSecurityDescriptor@@IEAAXXZ>

externdef __imp_?RidToSid@@YAJKPEAPEAX@Z:PPROC
?RidToSid@@YAJKPEAPEAX@Z equ <__imp_?RidToSid@@YAJKPEAPEAX@Z>

externdef __imp_?SetAccount@CService@@QEAAJPEAG0@Z:PPROC
?SetAccount@CService@@QEAAJPEAG0@Z equ <__imp_?SetAccount@CService@@QEAAJPEAG0@Z>

externdef __imp_?SetAccountInfoInRegistryW@@YAJPEAG@Z:PPROC
?SetAccountInfoInRegistryW@@YAJPEAG@Z equ <__imp_?SetAccountInfoInRegistryW@@YAJPEAG@Z>

externdef __imp_?SetControl@CSecurityDescriptor@@QEAAJGG@Z:PPROC
?SetControl@CSecurityDescriptor@@QEAAJGG@Z equ <__imp_?SetControl@CSecurityDescriptor@@QEAAJGG@Z>

externdef __imp_?SetDomainControllerState@@YAJPEAG@Z:PPROC
?SetDomainControllerState@@YAJPEAG@Z equ <__imp_?SetDomainControllerState@@YAJPEAG@Z>

externdef __imp_?SetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z:PPROC
?SetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z equ <__imp_?SetDtcCIDProps@@YAHAEAU_LOG_PROPERTIES@@AEAU_DAC_PROPERTIES@@@Z>

externdef __imp_?SetDtcClient@@YAJPEAGPEAD0@Z:PPROC
?SetDtcClient@@YAJPEAGPEAD0@Z equ <__imp_?SetDtcClient@@YAJPEAGPEAD0@Z>

externdef __imp_?SetDtcRpcSecurityLevel@@YAJPEAGW4_DTC_SECURITY_LEVEL@@H@Z:PPROC
?SetDtcRpcSecurityLevel@@YAJPEAGW4_DTC_SECURITY_LEVEL@@H@Z equ <__imp_?SetDtcRpcSecurityLevel@@YAJPEAGW4_DTC_SECURITY_LEVEL@@H@Z>

externdef __imp_?SetDtcServerProtocol@@YAJPEAD0@Z:PPROC
?SetDtcServerProtocol@@YAJPEAD0@Z equ <__imp_?SetDtcServerProtocol@@YAJPEAD0@Z>

externdef __imp_?SetEventLogSourceToMsdtcCore@@YAXXZ:PPROC
?SetEventLogSourceToMsdtcCore@@YAXXZ equ <__imp_?SetEventLogSourceToMsdtcCore@@YAXXZ>

externdef __imp_?SetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@K@Z:PPROC
?SetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@K@Z equ <__imp_?SetNamedInfo@CSecurityDescriptor@@QEAAJPEAGW4_SE_OBJECT_TYPE@@K@Z>

externdef __imp_?SetNewAcl@CSecurityDescriptor@@IEAAJPEAU_ACL@@KHH@Z:PPROC
?SetNewAcl@CSecurityDescriptor@@IEAAJPEAU_ACL@@KHH@Z equ <__imp_?SetNewAcl@CSecurityDescriptor@@IEAAJPEAU_ACL@@KHH@Z>

externdef __imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAGH@Z:PPROC
?SetOwner@CSecurityDescriptor@@QEAAJPEAGH@Z equ <__imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAGH@Z>

externdef __imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAXH@Z:PPROC
?SetOwner@CSecurityDescriptor@@QEAAJPEAXH@Z equ <__imp_?SetOwner@CSecurityDescriptor@@QEAAJPEAXH@Z>

externdef __imp_?SetSecurityConfigurationOptions@@YAJPEAGKK@Z:PPROC
?SetSecurityConfigurationOptions@@YAJPEAGKK@Z equ <__imp_?SetSecurityConfigurationOptions@@YAJPEAGKK@Z>

externdef __imp_?SetSecurityRegValueNonClusterW@@YAJPEAGPEBGKPEAEK@Z:PPROC
?SetSecurityRegValueNonClusterW@@YAJPEAGPEBGKPEAEK@Z equ <__imp_?SetSecurityRegValueNonClusterW@@YAJPEAGPEBGKPEAEK@Z>

externdef __imp_?SetSecurityRegValueW@@YAJPEAGPEBGKPEAEK@Z:PPROC
?SetSecurityRegValueW@@YAJPEAGPEBGKPEAEK@Z equ <__imp_?SetSecurityRegValueW@@YAJPEAGPEBGKPEAEK@Z>

externdef __imp_?SetServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z:PPROC
?SetServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z equ <__imp_?SetServiceObjectSecurity@CSecurityDescriptor@@QEAAJPEAUSC_HANDLE__@@K@Z>

externdef __imp_?SetSpecialAccounts@CSecurityDescriptor@@QEAAJK@Z:PPROC
?SetSpecialAccounts@CSecurityDescriptor@@QEAAJK@Z equ <__imp_?SetSpecialAccounts@CSecurityDescriptor@@QEAAJK@Z>

externdef __imp_?StringToSid@@YAJPEAGPEAPEAX@Z:PPROC
?StringToSid@@YAJPEAGPEAPEAX@Z equ <__imp_?StringToSid@@YAJPEAGPEAPEAX@Z>

externdef __imp_?UpdateTmNameObject@@YAJPEAUINameObject@@PEAPEAU1@@Z:PPROC
?UpdateTmNameObject@@YAJPEAUINameObject@@PEAPEAU1@@Z equ <__imp_?UpdateTmNameObject@@YAJPEAUINameObject@@PEAPEAU1@@Z>

externdef __imp_?UpgradeDtc@@YAJH@Z:PPROC
?UpgradeDtc@@YAJH@Z equ <__imp_?UpgradeDtc@@YAJH@Z>

externdef __imp_?VerifyAccountInfo@@YAJXZ:PPROC
?VerifyAccountInfo@@YAJXZ equ <__imp_?VerifyAccountInfo@@YAJXZ>

externdef __imp_?Win95Present@@YAHXZ:PPROC
?Win95Present@@YAHXZ equ <__imp_?Win95Present@@YAHXZ>

externdef __imp_?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@A:PPROC
?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@A equ <__imp_?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@A>
  IFNDEF __UNICODE__
    ?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@ equ <__imp_?g_aSpecialAccounts@@3PAU_SPECIAL_ACCOUNT_@@A>
  ENDIF

externdef __imp_ClusterChangeDtcUserAccount:PPROC
ClusterChangeDtcUserAccount equ <__imp_ClusterChangeDtcUserAccount>

externdef __imp_ClusterCryptoContainerCreate:PPROC
ClusterCryptoContainerCreate equ <__imp_ClusterCryptoContainerCreate>

externdef __imp_ClusterCryptoContainerDelete:PPROC
ClusterCryptoContainerDelete equ <__imp_ClusterCryptoContainerDelete>

externdef __imp_ClusterDaclCryptoContainer:PPROC
ClusterDaclCryptoContainer equ <__imp_ClusterDaclCryptoContainer>

externdef __imp_ClusterUpdateAccountInformation:PPROC
ClusterUpdateAccountInformation equ <__imp_ClusterUpdateAccountInformation>

externdef __imp_ContactToNameObject:PPROC
ContactToNameObject equ <__imp_ContactToNameObject>

externdef __imp_DTC_AxReg:PPROC
DTC_AxReg equ <__imp_DTC_AxReg>

externdef __imp_DTC_AxUnReg:PPROC
DTC_AxUnReg equ <__imp_DTC_AxUnReg>

externdef __imp_DTC_XaClose:PPROC
DTC_XaClose equ <__imp_DTC_XaClose>

externdef __imp_DTC_XaCommit:PPROC
DTC_XaCommit equ <__imp_DTC_XaCommit>

externdef __imp_DTC_XaComplete:PPROC
DTC_XaComplete equ <__imp_DTC_XaComplete>

externdef __imp_DTC_XaEnd:PPROC
DTC_XaEnd equ <__imp_DTC_XaEnd>

externdef __imp_DTC_XaForget:PPROC
DTC_XaForget equ <__imp_DTC_XaForget>

externdef __imp_DTC_XaOpen:PPROC
DTC_XaOpen equ <__imp_DTC_XaOpen>

externdef __imp_DTC_XaPrepare:PPROC
DTC_XaPrepare equ <__imp_DTC_XaPrepare>

externdef __imp_DTC_XaRecover:PPROC
DTC_XaRecover equ <__imp_DTC_XaRecover>

externdef __imp_DTC_XaRollback:PPROC
DTC_XaRollback equ <__imp_DTC_XaRollback>

externdef __imp_DTC_XaStart:PPROC
DTC_XaStart equ <__imp_DTC_XaStart>

externdef __imp_DecryptAccountInformation:PPROC
DecryptAccountInformation equ <__imp_DecryptAccountInformation>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllGetDTCConnectionManager:PPROC
DllGetDTCConnectionManager equ <__imp_DllGetDTCConnectionManager>

externdef __imp_DllGetDTCProxy:PPROC
DllGetDTCProxy equ <__imp_DllGetDTCProxy>

externdef __imp_DllGetDTCUtilObject:PPROC
DllGetDTCUtilObject equ <__imp_DllGetDTCUtilObject>

externdef __imp_DllGetTransactionManagerCore:PPROC
DllGetTransactionManagerCore equ <__imp_DllGetTransactionManagerCore>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_EncryptAccountInformation:PPROC
EncryptAccountInformation equ <__imp_EncryptAccountInformation>

externdef __imp_ShutDownCM:PPROC
ShutDownCM equ <__imp_ShutDownCM>

externdef __imp_SysPrepDtcReinstall:PPROC
SysPrepDtcReinstall equ <__imp_SysPrepDtcReinstall>

externdef __imp_ax_reg:PPROC
ax_reg equ <__imp_ax_reg>

externdef __imp_ax_unreg:PPROC
ax_unreg equ <__imp_ax_unreg>
