externdef __imp_ShellShutdownDialog:PPROC
ShellShutdownDialog equ <__imp_ShellShutdownDialog>

externdef __imp_WlxActivateUserShell:PPROC
WlxActivateUserShell equ <__imp_WlxActivateUserShell>

externdef __imp_WlxDisconnectNotify:PPROC
WlxDisconnectNotify equ <__imp_WlxDisconnectNotify>

externdef __imp_WlxDisplayLockedNotice:PPROC
WlxDisplayLockedNotice equ <__imp_WlxDisplayLockedNotice>

externdef __imp_WlxDisplaySASNotice:PPROC
WlxDisplaySASNotice equ <__imp_WlxDisplaySASNotice>

externdef __imp_WlxDisplayStatusMessage:PPROC
WlxDisplayStatusMessage equ <__imp_WlxDisplayStatusMessage>

externdef __imp_WlxGetConsoleSwitchCredentials:PPROC
WlxGetConsoleSwitchCredentials equ <__imp_WlxGetConsoleSwitchCredentials>

externdef __imp_WlxGetStatusMessage:PPROC
WlxGetStatusMessage equ <__imp_WlxGetStatusMessage>

externdef __imp_WlxInitialize:PPROC
WlxInitialize equ <__imp_WlxInitialize>

externdef __imp_WlxIsLockOk:PPROC
WlxIsLockOk equ <__imp_WlxIsLockOk>

externdef __imp_WlxIsLogoffOk:PPROC
WlxIsLogoffOk equ <__imp_WlxIsLogoffOk>

externdef __imp_WlxLoggedOnSAS:PPROC
WlxLoggedOnSAS equ <__imp_WlxLoggedOnSAS>

externdef __imp_WlxLoggedOutSAS:PPROC
WlxLoggedOutSAS equ <__imp_WlxLoggedOutSAS>

externdef __imp_WlxLogoff:PPROC
WlxLogoff equ <__imp_WlxLogoff>

externdef __imp_WlxNegotiate:PPROC
WlxNegotiate equ <__imp_WlxNegotiate>

externdef __imp_WlxNetworkProviderLoad:PPROC
WlxNetworkProviderLoad equ <__imp_WlxNetworkProviderLoad>

externdef __imp_WlxReconnectNotify:PPROC
WlxReconnectNotify equ <__imp_WlxReconnectNotify>

externdef __imp_WlxRemoveStatusMessage:PPROC
WlxRemoveStatusMessage equ <__imp_WlxRemoveStatusMessage>

externdef __imp_WlxScreenSaverNotify:PPROC
WlxScreenSaverNotify equ <__imp_WlxScreenSaverNotify>

externdef __imp_WlxShutdown:PPROC
WlxShutdown equ <__imp_WlxShutdown>

externdef __imp_WlxStartApplication:PPROC
WlxStartApplication equ <__imp_WlxStartApplication>

externdef __imp_WlxWkstaLockedSAS:PPROC
WlxWkstaLockedSAS equ <__imp_WlxWkstaLockedSAS>

externdef __imp_msgina_ordinal10:PPROC
msgina_ordinal10 equ <__imp_msgina_ordinal10>

externdef __imp_msgina_ordinal11:PPROC
msgina_ordinal11 equ <__imp_msgina_ordinal11>

externdef __imp_msgina_ordinal12:PPROC
msgina_ordinal12 equ <__imp_msgina_ordinal12>

externdef __imp_msgina_ordinal13:PPROC
msgina_ordinal13 equ <__imp_msgina_ordinal13>

externdef __imp_msgina_ordinal14:PPROC
msgina_ordinal14 equ <__imp_msgina_ordinal14>

externdef __imp_msgina_ordinal15:PPROC
msgina_ordinal15 equ <__imp_msgina_ordinal15>

externdef __imp_msgina_ordinal16:PPROC
msgina_ordinal16 equ <__imp_msgina_ordinal16>

externdef __imp_msgina_ordinal17:PPROC
msgina_ordinal17 equ <__imp_msgina_ordinal17>

externdef __imp_msgina_ordinal18:PPROC
msgina_ordinal18 equ <__imp_msgina_ordinal18>

externdef __imp_msgina_ordinal19:PPROC
msgina_ordinal19 equ <__imp_msgina_ordinal19>

externdef __imp_msgina_ordinal1:PPROC
msgina_ordinal1 equ <__imp_msgina_ordinal1>

externdef __imp_msgina_ordinal20:PPROC
msgina_ordinal20 equ <__imp_msgina_ordinal20>

externdef __imp_msgina_ordinal21:PPROC
msgina_ordinal21 equ <__imp_msgina_ordinal21>

externdef __imp_msgina_ordinal22:PPROC
msgina_ordinal22 equ <__imp_msgina_ordinal22>

externdef __imp_msgina_ordinal23:PPROC
msgina_ordinal23 equ <__imp_msgina_ordinal23>

externdef __imp_msgina_ordinal24:PPROC
msgina_ordinal24 equ <__imp_msgina_ordinal24>

externdef __imp_msgina_ordinal25:PPROC
msgina_ordinal25 equ <__imp_msgina_ordinal25>

externdef __imp_msgina_ordinal26:PPROC
msgina_ordinal26 equ <__imp_msgina_ordinal26>

externdef __imp_msgina_ordinal27:PPROC
msgina_ordinal27 equ <__imp_msgina_ordinal27>

externdef __imp_msgina_ordinal28:PPROC
msgina_ordinal28 equ <__imp_msgina_ordinal28>

externdef __imp_msgina_ordinal2:PPROC
msgina_ordinal2 equ <__imp_msgina_ordinal2>

externdef __imp_msgina_ordinal3:PPROC
msgina_ordinal3 equ <__imp_msgina_ordinal3>

externdef __imp_msgina_ordinal4:PPROC
msgina_ordinal4 equ <__imp_msgina_ordinal4>

externdef __imp_msgina_ordinal5:PPROC
msgina_ordinal5 equ <__imp_msgina_ordinal5>

externdef __imp_msgina_ordinal6:PPROC
msgina_ordinal6 equ <__imp_msgina_ordinal6>

externdef __imp_msgina_ordinal7:PPROC
msgina_ordinal7 equ <__imp_msgina_ordinal7>

externdef __imp_msgina_ordinal8:PPROC
msgina_ordinal8 equ <__imp_msgina_ordinal8>

externdef __imp_msgina_ordinal9:PPROC
msgina_ordinal9 equ <__imp_msgina_ordinal9>
