externdef __imp_msidle_ordinal3:PPROC
msidle_ordinal3 equ <__imp_msidle_ordinal3>

externdef __imp_msidle_ordinal4:PPROC
msidle_ordinal4 equ <__imp_msidle_ordinal4>

externdef __imp_msidle_ordinal5:PPROC
msidle_ordinal5 equ <__imp_msidle_ordinal5>

externdef __imp_msidle_ordinal6:PPROC
msidle_ordinal6 equ <__imp_msidle_ordinal6>

externdef __imp_msidle_ordinal7:PPROC
msidle_ordinal7 equ <__imp_msidle_ordinal7>

externdef __imp_msidle_ordinal8:PPROC
msidle_ordinal8 equ <__imp_msidle_ordinal8>
