externdef __imp_msswch_ordinal10:PPROC
msswch_ordinal10 equ <__imp_msswch_ordinal10>

externdef __imp_msswch_ordinal11:PPROC
msswch_ordinal11 equ <__imp_msswch_ordinal11>

externdef __imp_msswch_ordinal12:PPROC
msswch_ordinal12 equ <__imp_msswch_ordinal12>

externdef __imp_msswch_ordinal13:PPROC
msswch_ordinal13 equ <__imp_msswch_ordinal13>

externdef __imp_msswch_ordinal14:PPROC
msswch_ordinal14 equ <__imp_msswch_ordinal14>

externdef __imp_msswch_ordinal1:PPROC
msswch_ordinal1 equ <__imp_msswch_ordinal1>

externdef __imp_msswch_ordinal2:PPROC
msswch_ordinal2 equ <__imp_msswch_ordinal2>

externdef __imp_msswch_ordinal3:PPROC
msswch_ordinal3 equ <__imp_msswch_ordinal3>

externdef __imp_msswch_ordinal4:PPROC
msswch_ordinal4 equ <__imp_msswch_ordinal4>

externdef __imp_msswch_ordinal5:PPROC
msswch_ordinal5 equ <__imp_msswch_ordinal5>

externdef __imp_msswch_ordinal6:PPROC
msswch_ordinal6 equ <__imp_msswch_ordinal6>

externdef __imp_msswch_ordinal7:PPROC
msswch_ordinal7 equ <__imp_msswch_ordinal7>

externdef __imp_msswch_ordinal8:PPROC
msswch_ordinal8 equ <__imp_msswch_ordinal8>

externdef __imp_msswch_ordinal9:PPROC
msswch_ordinal9 equ <__imp_msswch_ordinal9>
