externdef __imp_ClosePopupTipbar:PPROC
ClosePopupTipbar equ <__imp_ClosePopupTipbar>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_GetLibTls:PPROC
GetLibTls equ <__imp_GetLibTls>

externdef __imp_GetPopupTipbar:PPROC
GetPopupTipbar equ <__imp_GetPopupTipbar>

externdef __imp_SetRegisterLangBand:PPROC
SetRegisterLangBand equ <__imp_SetRegisterLangBand>
