externdef __imp_??0Iostream_init@@QEAA@AEAVios@@H@Z:PPROC
??0Iostream_init@@QEAA@AEAVios@@H@Z equ <__imp_??0Iostream_init@@QEAA@AEAVios@@H@Z>

externdef __imp_??0Iostream_init@@QEAA@XZ:PPROC
??0Iostream_init@@QEAA@XZ equ <__imp_??0Iostream_init@@QEAA@XZ>

externdef __imp_??0exception@@QEAA@AEBQEBD@Z:PPROC
??0exception@@QEAA@AEBQEBD@Z equ <__imp_??0exception@@QEAA@AEBQEBD@Z>

externdef __imp_??0exception@@QEAA@AEBV0@@Z:PPROC
??0exception@@QEAA@AEBV0@@Z equ <__imp_??0exception@@QEAA@AEBV0@@Z>

externdef __imp_??0exception@@QEAA@XZ:PPROC
??0exception@@QEAA@XZ equ <__imp_??0exception@@QEAA@XZ>

externdef __imp_??0filebuf@@QEAA@AEBV0@@Z:PPROC
??0filebuf@@QEAA@AEBV0@@Z equ <__imp_??0filebuf@@QEAA@AEBV0@@Z>

externdef __imp_??0filebuf@@QEAA@H@Z:PPROC
??0filebuf@@QEAA@H@Z equ <__imp_??0filebuf@@QEAA@H@Z>

externdef __imp_??0filebuf@@QEAA@HPEADH@Z:PPROC
??0filebuf@@QEAA@HPEADH@Z equ <__imp_??0filebuf@@QEAA@HPEADH@Z>

externdef __imp_??0filebuf@@QEAA@XZ:PPROC
??0filebuf@@QEAA@XZ equ <__imp_??0filebuf@@QEAA@XZ>

externdef __imp_??0fstream@@QEAA@AEBV0@@Z:PPROC
??0fstream@@QEAA@AEBV0@@Z equ <__imp_??0fstream@@QEAA@AEBV0@@Z>

externdef __imp_??0fstream@@QEAA@H@Z:PPROC
??0fstream@@QEAA@H@Z equ <__imp_??0fstream@@QEAA@H@Z>

externdef __imp_??0fstream@@QEAA@HPEADH@Z:PPROC
??0fstream@@QEAA@HPEADH@Z equ <__imp_??0fstream@@QEAA@HPEADH@Z>

externdef __imp_??0fstream@@QEAA@PEBDHH@Z:PPROC
??0fstream@@QEAA@PEBDHH@Z equ <__imp_??0fstream@@QEAA@PEBDHH@Z>

externdef __imp_??0fstream@@QEAA@XZ:PPROC
??0fstream@@QEAA@XZ equ <__imp_??0fstream@@QEAA@XZ>

externdef __imp_??0ifstream@@QEAA@AEBV0@@Z:PPROC
??0ifstream@@QEAA@AEBV0@@Z equ <__imp_??0ifstream@@QEAA@AEBV0@@Z>

externdef __imp_??0ifstream@@QEAA@H@Z:PPROC
??0ifstream@@QEAA@H@Z equ <__imp_??0ifstream@@QEAA@H@Z>

externdef __imp_??0ifstream@@QEAA@HPEADH@Z:PPROC
??0ifstream@@QEAA@HPEADH@Z equ <__imp_??0ifstream@@QEAA@HPEADH@Z>

externdef __imp_??0ifstream@@QEAA@PEBDHH@Z:PPROC
??0ifstream@@QEAA@PEBDHH@Z equ <__imp_??0ifstream@@QEAA@PEBDHH@Z>

externdef __imp_??0ifstream@@QEAA@XZ:PPROC
??0ifstream@@QEAA@XZ equ <__imp_??0ifstream@@QEAA@XZ>

externdef __imp_??0ios@@IEAA@AEBV0@@Z:PPROC
??0ios@@IEAA@AEBV0@@Z equ <__imp_??0ios@@IEAA@AEBV0@@Z>

externdef __imp_??0ios@@IEAA@XZ:PPROC
??0ios@@IEAA@XZ equ <__imp_??0ios@@IEAA@XZ>

externdef __imp_??0ios@@QEAA@PEAVstreambuf@@@Z:PPROC
??0ios@@QEAA@PEAVstreambuf@@@Z equ <__imp_??0ios@@QEAA@PEAVstreambuf@@@Z>

externdef __imp_??0iostream@@IEAA@AEBV0@@Z:PPROC
??0iostream@@IEAA@AEBV0@@Z equ <__imp_??0iostream@@IEAA@AEBV0@@Z>

externdef __imp_??0iostream@@IEAA@XZ:PPROC
??0iostream@@IEAA@XZ equ <__imp_??0iostream@@IEAA@XZ>

externdef __imp_??0iostream@@QEAA@PEAVstreambuf@@@Z:PPROC
??0iostream@@QEAA@PEAVstreambuf@@@Z equ <__imp_??0iostream@@QEAA@PEAVstreambuf@@@Z>

externdef __imp_??0istream@@IEAA@AEBV0@@Z:PPROC
??0istream@@IEAA@AEBV0@@Z equ <__imp_??0istream@@IEAA@AEBV0@@Z>

externdef __imp_??0istream@@IEAA@XZ:PPROC
??0istream@@IEAA@XZ equ <__imp_??0istream@@IEAA@XZ>

externdef __imp_??0istream@@QEAA@PEAVstreambuf@@@Z:PPROC
??0istream@@QEAA@PEAVstreambuf@@@Z equ <__imp_??0istream@@QEAA@PEAVstreambuf@@@Z>

externdef __imp_??0istream_withassign@@QEAA@AEBV0@@Z:PPROC
??0istream_withassign@@QEAA@AEBV0@@Z equ <__imp_??0istream_withassign@@QEAA@AEBV0@@Z>

externdef __imp_??0istream_withassign@@QEAA@PEAVstreambuf@@@Z:PPROC
??0istream_withassign@@QEAA@PEAVstreambuf@@@Z equ <__imp_??0istream_withassign@@QEAA@PEAVstreambuf@@@Z>

externdef __imp_??0istream_withassign@@QEAA@XZ:PPROC
??0istream_withassign@@QEAA@XZ equ <__imp_??0istream_withassign@@QEAA@XZ>

externdef __imp_??0istrstream@@QEAA@AEBV0@@Z:PPROC
??0istrstream@@QEAA@AEBV0@@Z equ <__imp_??0istrstream@@QEAA@AEBV0@@Z>

externdef __imp_??0istrstream@@QEAA@PEAD@Z:PPROC
??0istrstream@@QEAA@PEAD@Z equ <__imp_??0istrstream@@QEAA@PEAD@Z>

externdef __imp_??0istrstream@@QEAA@PEADH@Z:PPROC
??0istrstream@@QEAA@PEADH@Z equ <__imp_??0istrstream@@QEAA@PEADH@Z>

externdef __imp_??0logic_error@@QEAA@AEBQEBD@Z:PPROC
??0logic_error@@QEAA@AEBQEBD@Z equ <__imp_??0logic_error@@QEAA@AEBQEBD@Z>

externdef __imp_??0logic_error@@QEAA@AEBV0@@Z:PPROC
??0logic_error@@QEAA@AEBV0@@Z equ <__imp_??0logic_error@@QEAA@AEBV0@@Z>

externdef __imp_??0ofstream@@QEAA@AEBV0@@Z:PPROC
??0ofstream@@QEAA@AEBV0@@Z equ <__imp_??0ofstream@@QEAA@AEBV0@@Z>

externdef __imp_??0ofstream@@QEAA@H@Z:PPROC
??0ofstream@@QEAA@H@Z equ <__imp_??0ofstream@@QEAA@H@Z>

externdef __imp_??0ofstream@@QEAA@HPEADH@Z:PPROC
??0ofstream@@QEAA@HPEADH@Z equ <__imp_??0ofstream@@QEAA@HPEADH@Z>

externdef __imp_??0ofstream@@QEAA@PEBDHH@Z:PPROC
??0ofstream@@QEAA@PEBDHH@Z equ <__imp_??0ofstream@@QEAA@PEBDHH@Z>

externdef __imp_??0ofstream@@QEAA@XZ:PPROC
??0ofstream@@QEAA@XZ equ <__imp_??0ofstream@@QEAA@XZ>

externdef __imp_??0ostream@@IEAA@AEBV0@@Z:PPROC
??0ostream@@IEAA@AEBV0@@Z equ <__imp_??0ostream@@IEAA@AEBV0@@Z>

externdef __imp_??0ostream@@IEAA@XZ:PPROC
??0ostream@@IEAA@XZ equ <__imp_??0ostream@@IEAA@XZ>

externdef __imp_??0ostream@@QEAA@PEAVstreambuf@@@Z:PPROC
??0ostream@@QEAA@PEAVstreambuf@@@Z equ <__imp_??0ostream@@QEAA@PEAVstreambuf@@@Z>

externdef __imp_??0ostream_withassign@@QEAA@AEBV0@@Z:PPROC
??0ostream_withassign@@QEAA@AEBV0@@Z equ <__imp_??0ostream_withassign@@QEAA@AEBV0@@Z>

externdef __imp_??0ostream_withassign@@QEAA@PEAVstreambuf@@@Z:PPROC
??0ostream_withassign@@QEAA@PEAVstreambuf@@@Z equ <__imp_??0ostream_withassign@@QEAA@PEAVstreambuf@@@Z>

externdef __imp_??0ostream_withassign@@QEAA@XZ:PPROC
??0ostream_withassign@@QEAA@XZ equ <__imp_??0ostream_withassign@@QEAA@XZ>

externdef __imp_??0ostrstream@@QEAA@AEBV0@@Z:PPROC
??0ostrstream@@QEAA@AEBV0@@Z equ <__imp_??0ostrstream@@QEAA@AEBV0@@Z>

externdef __imp_??0ostrstream@@QEAA@PEADHH@Z:PPROC
??0ostrstream@@QEAA@PEADHH@Z equ <__imp_??0ostrstream@@QEAA@PEADHH@Z>

externdef __imp_??0ostrstream@@QEAA@XZ:PPROC
??0ostrstream@@QEAA@XZ equ <__imp_??0ostrstream@@QEAA@XZ>

externdef __imp_??0stdiobuf@@QEAA@AEBV0@@Z:PPROC
??0stdiobuf@@QEAA@AEBV0@@Z equ <__imp_??0stdiobuf@@QEAA@AEBV0@@Z>

externdef __imp_??0stdiobuf@@QEAA@PEAU_iobuf@@@Z:PPROC
??0stdiobuf@@QEAA@PEAU_iobuf@@@Z equ <__imp_??0stdiobuf@@QEAA@PEAU_iobuf@@@Z>

externdef __imp_??0stdiostream@@QEAA@AEBV0@@Z:PPROC
??0stdiostream@@QEAA@AEBV0@@Z equ <__imp_??0stdiostream@@QEAA@AEBV0@@Z>

externdef __imp_??0stdiostream@@QEAA@PEAU_iobuf@@@Z:PPROC
??0stdiostream@@QEAA@PEAU_iobuf@@@Z equ <__imp_??0stdiostream@@QEAA@PEAU_iobuf@@@Z>

externdef __imp_??0streambuf@@IEAA@PEADH@Z:PPROC
??0streambuf@@IEAA@PEADH@Z equ <__imp_??0streambuf@@IEAA@PEADH@Z>

externdef __imp_??0streambuf@@IEAA@XZ:PPROC
??0streambuf@@IEAA@XZ equ <__imp_??0streambuf@@IEAA@XZ>

externdef __imp_??0streambuf@@QEAA@AEBV0@@Z:PPROC
??0streambuf@@QEAA@AEBV0@@Z equ <__imp_??0streambuf@@QEAA@AEBV0@@Z>

externdef __imp_??0strstream@@QEAA@AEBV0@@Z:PPROC
??0strstream@@QEAA@AEBV0@@Z equ <__imp_??0strstream@@QEAA@AEBV0@@Z>

externdef __imp_??0strstream@@QEAA@PEADHH@Z:PPROC
??0strstream@@QEAA@PEADHH@Z equ <__imp_??0strstream@@QEAA@PEADHH@Z>

externdef __imp_??0strstream@@QEAA@XZ:PPROC
??0strstream@@QEAA@XZ equ <__imp_??0strstream@@QEAA@XZ>

externdef __imp_??0strstreambuf@@QEAA@AEBV0@@Z:PPROC
??0strstreambuf@@QEAA@AEBV0@@Z equ <__imp_??0strstreambuf@@QEAA@AEBV0@@Z>

externdef __imp_??0strstreambuf@@QEAA@H@Z:PPROC
??0strstreambuf@@QEAA@H@Z equ <__imp_??0strstreambuf@@QEAA@H@Z>

externdef __imp_??0strstreambuf@@QEAA@P6APEAXJ@ZP6AXPEAX@Z@Z:PPROC
??0strstreambuf@@QEAA@P6APEAXJ@ZP6AXPEAX@Z@Z equ <__imp_??0strstreambuf@@QEAA@P6APEAXJ@ZP6AXPEAX@Z@Z>

externdef __imp_??0strstreambuf@@QEAA@PEADH0@Z:PPROC
??0strstreambuf@@QEAA@PEADH0@Z equ <__imp_??0strstreambuf@@QEAA@PEADH0@Z>

externdef __imp_??0strstreambuf@@QEAA@PEAEH0@Z:PPROC
??0strstreambuf@@QEAA@PEAEH0@Z equ <__imp_??0strstreambuf@@QEAA@PEAEH0@Z>

externdef __imp_??0strstreambuf@@QEAA@XZ:PPROC
??0strstreambuf@@QEAA@XZ equ <__imp_??0strstreambuf@@QEAA@XZ>

externdef __imp_??1Iostream_init@@QEAA@XZ:PPROC
??1Iostream_init@@QEAA@XZ equ <__imp_??1Iostream_init@@QEAA@XZ>

externdef __imp_??1exception@@UEAA@XZ:PPROC
??1exception@@UEAA@XZ equ <__imp_??1exception@@UEAA@XZ>

externdef __imp_??1filebuf@@UEAA@XZ:PPROC
??1filebuf@@UEAA@XZ equ <__imp_??1filebuf@@UEAA@XZ>

externdef __imp_??1fstream@@UEAA@XZ:PPROC
??1fstream@@UEAA@XZ equ <__imp_??1fstream@@UEAA@XZ>

externdef __imp_??1ifstream@@UEAA@XZ:PPROC
??1ifstream@@UEAA@XZ equ <__imp_??1ifstream@@UEAA@XZ>

externdef __imp_??1ios@@UEAA@XZ:PPROC
??1ios@@UEAA@XZ equ <__imp_??1ios@@UEAA@XZ>

externdef __imp_??1iostream@@UEAA@XZ:PPROC
??1iostream@@UEAA@XZ equ <__imp_??1iostream@@UEAA@XZ>

externdef __imp_??1istream@@UEAA@XZ:PPROC
??1istream@@UEAA@XZ equ <__imp_??1istream@@UEAA@XZ>

externdef __imp_??1istream_withassign@@UEAA@XZ:PPROC
??1istream_withassign@@UEAA@XZ equ <__imp_??1istream_withassign@@UEAA@XZ>

externdef __imp_??1istrstream@@UEAA@XZ:PPROC
??1istrstream@@UEAA@XZ equ <__imp_??1istrstream@@UEAA@XZ>

externdef __imp_??1logic_error@@UEAA@XZ:PPROC
??1logic_error@@UEAA@XZ equ <__imp_??1logic_error@@UEAA@XZ>

externdef __imp_??1ofstream@@UEAA@XZ:PPROC
??1ofstream@@UEAA@XZ equ <__imp_??1ofstream@@UEAA@XZ>

externdef __imp_??1ostream@@UEAA@XZ:PPROC
??1ostream@@UEAA@XZ equ <__imp_??1ostream@@UEAA@XZ>

externdef __imp_??1ostream_withassign@@UEAA@XZ:PPROC
??1ostream_withassign@@UEAA@XZ equ <__imp_??1ostream_withassign@@UEAA@XZ>

externdef __imp_??1ostrstream@@UEAA@XZ:PPROC
??1ostrstream@@UEAA@XZ equ <__imp_??1ostrstream@@UEAA@XZ>

externdef __imp_??1stdiobuf@@UEAA@XZ:PPROC
??1stdiobuf@@UEAA@XZ equ <__imp_??1stdiobuf@@UEAA@XZ>

externdef __imp_??1stdiostream@@UEAA@XZ:PPROC
??1stdiostream@@UEAA@XZ equ <__imp_??1stdiostream@@UEAA@XZ>

externdef __imp_??1streambuf@@UEAA@XZ:PPROC
??1streambuf@@UEAA@XZ equ <__imp_??1streambuf@@UEAA@XZ>

externdef __imp_??1strstream@@UEAA@XZ:PPROC
??1strstream@@UEAA@XZ equ <__imp_??1strstream@@UEAA@XZ>

externdef __imp_??1strstreambuf@@UEAA@XZ:PPROC
??1strstreambuf@@UEAA@XZ equ <__imp_??1strstreambuf@@UEAA@XZ>

externdef __imp_??4Iostream_init@@QEAAAEAV0@AEBV0@@Z:PPROC
??4Iostream_init@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4Iostream_init@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4exception@@QEAAAEAV0@AEBV0@@Z:PPROC
??4exception@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4exception@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4filebuf@@QEAAAEAV0@AEBV0@@Z:PPROC
??4filebuf@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4filebuf@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4fstream@@QEAAAEAV0@AEAV0@@Z:PPROC
??4fstream@@QEAAAEAV0@AEAV0@@Z equ <__imp_??4fstream@@QEAAAEAV0@AEAV0@@Z>

externdef __imp_??4ifstream@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ifstream@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ifstream@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ios@@IEAAAEAV0@AEBV0@@Z:PPROC
??4ios@@IEAAAEAV0@AEBV0@@Z equ <__imp_??4ios@@IEAAAEAV0@AEBV0@@Z>

externdef __imp_??4iostream@@IEAAAEAV0@AEAV0@@Z:PPROC
??4iostream@@IEAAAEAV0@AEAV0@@Z equ <__imp_??4iostream@@IEAAAEAV0@AEAV0@@Z>

externdef __imp_??4iostream@@IEAAAEAV0@PEAVstreambuf@@@Z:PPROC
??4iostream@@IEAAAEAV0@PEAVstreambuf@@@Z equ <__imp_??4iostream@@IEAAAEAV0@PEAVstreambuf@@@Z>

externdef __imp_??4istream@@IEAAAEAV0@AEBV0@@Z:PPROC
??4istream@@IEAAAEAV0@AEBV0@@Z equ <__imp_??4istream@@IEAAAEAV0@AEBV0@@Z>

externdef __imp_??4istream@@IEAAAEAV0@PEAVstreambuf@@@Z:PPROC
??4istream@@IEAAAEAV0@PEAVstreambuf@@@Z equ <__imp_??4istream@@IEAAAEAV0@PEAVstreambuf@@@Z>

externdef __imp_??4istream_withassign@@QEAAAEAV0@AEBV0@@Z:PPROC
??4istream_withassign@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4istream_withassign@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4istream_withassign@@QEAAAEAVistream@@AEBV1@@Z:PPROC
??4istream_withassign@@QEAAAEAVistream@@AEBV1@@Z equ <__imp_??4istream_withassign@@QEAAAEAVistream@@AEBV1@@Z>

externdef __imp_??4istream_withassign@@QEAAAEAVistream@@PEAVstreambuf@@@Z:PPROC
??4istream_withassign@@QEAAAEAVistream@@PEAVstreambuf@@@Z equ <__imp_??4istream_withassign@@QEAAAEAVistream@@PEAVstreambuf@@@Z>

externdef __imp_??4istrstream@@QEAAAEAV0@AEBV0@@Z:PPROC
??4istrstream@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4istrstream@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4logic_error@@QEAAAEAV0@AEBV0@@Z:PPROC
??4logic_error@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4logic_error@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ofstream@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ofstream@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ofstream@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ostream@@IEAAAEAV0@AEBV0@@Z:PPROC
??4ostream@@IEAAAEAV0@AEBV0@@Z equ <__imp_??4ostream@@IEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ostream@@IEAAAEAV0@PEAVstreambuf@@@Z:PPROC
??4ostream@@IEAAAEAV0@PEAVstreambuf@@@Z equ <__imp_??4ostream@@IEAAAEAV0@PEAVstreambuf@@@Z>

externdef __imp_??4ostream_withassign@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ostream_withassign@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ostream_withassign@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4ostream_withassign@@QEAAAEAVostream@@AEBV1@@Z:PPROC
??4ostream_withassign@@QEAAAEAVostream@@AEBV1@@Z equ <__imp_??4ostream_withassign@@QEAAAEAVostream@@AEBV1@@Z>

externdef __imp_??4ostream_withassign@@QEAAAEAVostream@@PEAVstreambuf@@@Z:PPROC
??4ostream_withassign@@QEAAAEAVostream@@PEAVstreambuf@@@Z equ <__imp_??4ostream_withassign@@QEAAAEAVostream@@PEAVstreambuf@@@Z>

externdef __imp_??4ostrstream@@QEAAAEAV0@AEBV0@@Z:PPROC
??4ostrstream@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4ostrstream@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4stdiobuf@@QEAAAEAV0@AEBV0@@Z:PPROC
??4stdiobuf@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4stdiobuf@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4stdiostream@@QEAAAEAV0@AEAV0@@Z:PPROC
??4stdiostream@@QEAAAEAV0@AEAV0@@Z equ <__imp_??4stdiostream@@QEAAAEAV0@AEAV0@@Z>

externdef __imp_??4streambuf@@QEAAAEAV0@AEBV0@@Z:PPROC
??4streambuf@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4streambuf@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4strstream@@QEAAAEAV0@AEAV0@@Z:PPROC
??4strstream@@QEAAAEAV0@AEAV0@@Z equ <__imp_??4strstream@@QEAAAEAV0@AEAV0@@Z>

externdef __imp_??4strstreambuf@@QEAAAEAV0@AEBV0@@Z:PPROC
??4strstreambuf@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4strstreambuf@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAC@Z:PPROC
??5istream@@QEAAAEAV0@AEAC@Z equ <__imp_??5istream@@QEAAAEAV0@AEAC@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAD@Z:PPROC
??5istream@@QEAAAEAV0@AEAD@Z equ <__imp_??5istream@@QEAAAEAV0@AEAD@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAE@Z:PPROC
??5istream@@QEAAAEAV0@AEAE@Z equ <__imp_??5istream@@QEAAAEAV0@AEAE@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAF@Z:PPROC
??5istream@@QEAAAEAV0@AEAF@Z equ <__imp_??5istream@@QEAAAEAV0@AEAF@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAG@Z:PPROC
??5istream@@QEAAAEAV0@AEAG@Z equ <__imp_??5istream@@QEAAAEAV0@AEAG@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAH@Z:PPROC
??5istream@@QEAAAEAV0@AEAH@Z equ <__imp_??5istream@@QEAAAEAV0@AEAH@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAI@Z:PPROC
??5istream@@QEAAAEAV0@AEAI@Z equ <__imp_??5istream@@QEAAAEAV0@AEAI@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAJ@Z:PPROC
??5istream@@QEAAAEAV0@AEAJ@Z equ <__imp_??5istream@@QEAAAEAV0@AEAJ@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAK@Z:PPROC
??5istream@@QEAAAEAV0@AEAK@Z equ <__imp_??5istream@@QEAAAEAV0@AEAK@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAM@Z:PPROC
??5istream@@QEAAAEAV0@AEAM@Z equ <__imp_??5istream@@QEAAAEAV0@AEAM@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAN@Z:PPROC
??5istream@@QEAAAEAV0@AEAN@Z equ <__imp_??5istream@@QEAAAEAV0@AEAN@Z>

externdef __imp_??5istream@@QEAAAEAV0@AEAO@Z:PPROC
??5istream@@QEAAAEAV0@AEAO@Z equ <__imp_??5istream@@QEAAAEAV0@AEAO@Z>

externdef __imp_??5istream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z:PPROC
??5istream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z equ <__imp_??5istream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z>

externdef __imp_??5istream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z:PPROC
??5istream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z equ <__imp_??5istream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z>

externdef __imp_??5istream@@QEAAAEAV0@PEAC@Z:PPROC
??5istream@@QEAAAEAV0@PEAC@Z equ <__imp_??5istream@@QEAAAEAV0@PEAC@Z>

externdef __imp_??5istream@@QEAAAEAV0@PEAD@Z:PPROC
??5istream@@QEAAAEAV0@PEAD@Z equ <__imp_??5istream@@QEAAAEAV0@PEAD@Z>

externdef __imp_??5istream@@QEAAAEAV0@PEAE@Z:PPROC
??5istream@@QEAAAEAV0@PEAE@Z equ <__imp_??5istream@@QEAAAEAV0@PEAE@Z>

externdef __imp_??5istream@@QEAAAEAV0@PEAVstreambuf@@@Z:PPROC
??5istream@@QEAAAEAV0@PEAVstreambuf@@@Z equ <__imp_??5istream@@QEAAAEAV0@PEAVstreambuf@@@Z>

externdef __imp_??6ostream@@QEAAAEAV0@C@Z:PPROC
??6ostream@@QEAAAEAV0@C@Z equ <__imp_??6ostream@@QEAAAEAV0@C@Z>

externdef __imp_??6ostream@@QEAAAEAV0@D@Z:PPROC
??6ostream@@QEAAAEAV0@D@Z equ <__imp_??6ostream@@QEAAAEAV0@D@Z>

externdef __imp_??6ostream@@QEAAAEAV0@E@Z:PPROC
??6ostream@@QEAAAEAV0@E@Z equ <__imp_??6ostream@@QEAAAEAV0@E@Z>

externdef __imp_??6ostream@@QEAAAEAV0@F@Z:PPROC
??6ostream@@QEAAAEAV0@F@Z equ <__imp_??6ostream@@QEAAAEAV0@F@Z>

externdef __imp_??6ostream@@QEAAAEAV0@G@Z:PPROC
??6ostream@@QEAAAEAV0@G@Z equ <__imp_??6ostream@@QEAAAEAV0@G@Z>

externdef __imp_??6ostream@@QEAAAEAV0@H@Z:PPROC
??6ostream@@QEAAAEAV0@H@Z equ <__imp_??6ostream@@QEAAAEAV0@H@Z>

externdef __imp_??6ostream@@QEAAAEAV0@I@Z:PPROC
??6ostream@@QEAAAEAV0@I@Z equ <__imp_??6ostream@@QEAAAEAV0@I@Z>

externdef __imp_??6ostream@@QEAAAEAV0@J@Z:PPROC
??6ostream@@QEAAAEAV0@J@Z equ <__imp_??6ostream@@QEAAAEAV0@J@Z>

externdef __imp_??6ostream@@QEAAAEAV0@K@Z:PPROC
??6ostream@@QEAAAEAV0@K@Z equ <__imp_??6ostream@@QEAAAEAV0@K@Z>

externdef __imp_??6ostream@@QEAAAEAV0@M@Z:PPROC
??6ostream@@QEAAAEAV0@M@Z equ <__imp_??6ostream@@QEAAAEAV0@M@Z>

externdef __imp_??6ostream@@QEAAAEAV0@N@Z:PPROC
??6ostream@@QEAAAEAV0@N@Z equ <__imp_??6ostream@@QEAAAEAV0@N@Z>

externdef __imp_??6ostream@@QEAAAEAV0@O@Z:PPROC
??6ostream@@QEAAAEAV0@O@Z equ <__imp_??6ostream@@QEAAAEAV0@O@Z>

externdef __imp_??6ostream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z:PPROC
??6ostream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z equ <__imp_??6ostream@@QEAAAEAV0@P6AAEAV0@AEAV0@@Z@Z>

externdef __imp_??6ostream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z:PPROC
??6ostream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z equ <__imp_??6ostream@@QEAAAEAV0@P6AAEAVios@@AEAV1@@Z@Z>

externdef __imp_??6ostream@@QEAAAEAV0@PEAVstreambuf@@@Z:PPROC
??6ostream@@QEAAAEAV0@PEAVstreambuf@@@Z equ <__imp_??6ostream@@QEAAAEAV0@PEAVstreambuf@@@Z>

externdef __imp_??6ostream@@QEAAAEAV0@PEBC@Z:PPROC
??6ostream@@QEAAAEAV0@PEBC@Z equ <__imp_??6ostream@@QEAAAEAV0@PEBC@Z>

externdef __imp_??6ostream@@QEAAAEAV0@PEBD@Z:PPROC
??6ostream@@QEAAAEAV0@PEBD@Z equ <__imp_??6ostream@@QEAAAEAV0@PEBD@Z>

externdef __imp_??6ostream@@QEAAAEAV0@PEBE@Z:PPROC
??6ostream@@QEAAAEAV0@PEBE@Z equ <__imp_??6ostream@@QEAAAEAV0@PEBE@Z>

externdef __imp_??6ostream@@QEAAAEAV0@PEBX@Z:PPROC
??6ostream@@QEAAAEAV0@PEBX@Z equ <__imp_??6ostream@@QEAAAEAV0@PEBX@Z>

externdef __imp_??7ios@@QEBAHXZ:PPROC
??7ios@@QEBAHXZ equ <__imp_??7ios@@QEBAHXZ>

externdef __imp_??Bios@@QEBAPEAXXZ:PPROC
??Bios@@QEBAPEAXXZ equ <__imp_??Bios@@QEBAPEAXXZ>

externdef __imp_??_7exception@@6B@:PPROC
??_7exception@@6B@ equ <__imp_??_7exception@@6B@>

externdef __imp_??_7filebuf@@6B@:PPROC
??_7filebuf@@6B@ equ <__imp_??_7filebuf@@6B@>

externdef __imp_??_7fstream@@6B@:PPROC
??_7fstream@@6B@ equ <__imp_??_7fstream@@6B@>

externdef __imp_??_7ifstream@@6B@:PPROC
??_7ifstream@@6B@ equ <__imp_??_7ifstream@@6B@>

externdef __imp_??_7ios@@6B@:PPROC
??_7ios@@6B@ equ <__imp_??_7ios@@6B@>

externdef __imp_??_7iostream@@6B@:PPROC
??_7iostream@@6B@ equ <__imp_??_7iostream@@6B@>

externdef __imp_??_7istream@@6B@:PPROC
??_7istream@@6B@ equ <__imp_??_7istream@@6B@>

externdef __imp_??_7istream_withassign@@6B@:PPROC
??_7istream_withassign@@6B@ equ <__imp_??_7istream_withassign@@6B@>

externdef __imp_??_7istrstream@@6B@:PPROC
??_7istrstream@@6B@ equ <__imp_??_7istrstream@@6B@>

externdef __imp_??_7logic_error@@6B@:PPROC
??_7logic_error@@6B@ equ <__imp_??_7logic_error@@6B@>

externdef __imp_??_7ofstream@@6B@:PPROC
??_7ofstream@@6B@ equ <__imp_??_7ofstream@@6B@>

externdef __imp_??_7ostream@@6B@:PPROC
??_7ostream@@6B@ equ <__imp_??_7ostream@@6B@>

externdef __imp_??_7ostream_withassign@@6B@:PPROC
??_7ostream_withassign@@6B@ equ <__imp_??_7ostream_withassign@@6B@>

externdef __imp_??_7ostrstream@@6B@:PPROC
??_7ostrstream@@6B@ equ <__imp_??_7ostrstream@@6B@>

externdef __imp_??_7stdiobuf@@6B@:PPROC
??_7stdiobuf@@6B@ equ <__imp_??_7stdiobuf@@6B@>

externdef __imp_??_7stdiostream@@6B@:PPROC
??_7stdiostream@@6B@ equ <__imp_??_7stdiostream@@6B@>

externdef __imp_??_7streambuf@@6B@:PPROC
??_7streambuf@@6B@ equ <__imp_??_7streambuf@@6B@>

externdef __imp_??_7strstream@@6B@:PPROC
??_7strstream@@6B@ equ <__imp_??_7strstream@@6B@>

externdef __imp_??_7strstreambuf@@6B@:PPROC
??_7strstreambuf@@6B@ equ <__imp_??_7strstreambuf@@6B@>

externdef __imp_??_8fstream@@7Bistream@@@:PPROC
??_8fstream@@7Bistream@@@ equ <__imp_??_8fstream@@7Bistream@@@>

externdef __imp_??_8fstream@@7Bostream@@@:PPROC
??_8fstream@@7Bostream@@@ equ <__imp_??_8fstream@@7Bostream@@@>

externdef __imp_??_8ifstream@@7B@:PPROC
??_8ifstream@@7B@ equ <__imp_??_8ifstream@@7B@>

externdef __imp_??_8iostream@@7Bistream@@@:PPROC
??_8iostream@@7Bistream@@@ equ <__imp_??_8iostream@@7Bistream@@@>

externdef __imp_??_8iostream@@7Bostream@@@:PPROC
??_8iostream@@7Bostream@@@ equ <__imp_??_8iostream@@7Bostream@@@>

externdef __imp_??_8istream@@7B@:PPROC
??_8istream@@7B@ equ <__imp_??_8istream@@7B@>

externdef __imp_??_8istream_withassign@@7B@:PPROC
??_8istream_withassign@@7B@ equ <__imp_??_8istream_withassign@@7B@>

externdef __imp_??_8istrstream@@7B@:PPROC
??_8istrstream@@7B@ equ <__imp_??_8istrstream@@7B@>

externdef __imp_??_8ofstream@@7B@:PPROC
??_8ofstream@@7B@ equ <__imp_??_8ofstream@@7B@>

externdef __imp_??_8ostream@@7B@:PPROC
??_8ostream@@7B@ equ <__imp_??_8ostream@@7B@>

externdef __imp_??_8ostream_withassign@@7B@:PPROC
??_8ostream_withassign@@7B@ equ <__imp_??_8ostream_withassign@@7B@>

externdef __imp_??_8ostrstream@@7B@:PPROC
??_8ostrstream@@7B@ equ <__imp_??_8ostrstream@@7B@>

externdef __imp_??_8stdiostream@@7Bistream@@@:PPROC
??_8stdiostream@@7Bistream@@@ equ <__imp_??_8stdiostream@@7Bistream@@@>

externdef __imp_??_8stdiostream@@7Bostream@@@:PPROC
??_8stdiostream@@7Bostream@@@ equ <__imp_??_8stdiostream@@7Bostream@@@>

externdef __imp_??_8strstream@@7Bistream@@@:PPROC
??_8strstream@@7Bistream@@@ equ <__imp_??_8strstream@@7Bistream@@@>

externdef __imp_??_8strstream@@7Bostream@@@:PPROC
??_8strstream@@7Bostream@@@ equ <__imp_??_8strstream@@7Bostream@@@>

externdef __imp_??_Dfstream@@QEAAXXZ:PPROC
??_Dfstream@@QEAAXXZ equ <__imp_??_Dfstream@@QEAAXXZ>

externdef __imp_??_Difstream@@QEAAXXZ:PPROC
??_Difstream@@QEAAXXZ equ <__imp_??_Difstream@@QEAAXXZ>

externdef __imp_??_Diostream@@QEAAXXZ:PPROC
??_Diostream@@QEAAXXZ equ <__imp_??_Diostream@@QEAAXXZ>

externdef __imp_??_Distream@@QEAAXXZ:PPROC
??_Distream@@QEAAXXZ equ <__imp_??_Distream@@QEAAXXZ>

externdef __imp_??_Distream_withassign@@QEAAXXZ:PPROC
??_Distream_withassign@@QEAAXXZ equ <__imp_??_Distream_withassign@@QEAAXXZ>

externdef __imp_??_Distrstream@@QEAAXXZ:PPROC
??_Distrstream@@QEAAXXZ equ <__imp_??_Distrstream@@QEAAXXZ>

externdef __imp_??_Dofstream@@QEAAXXZ:PPROC
??_Dofstream@@QEAAXXZ equ <__imp_??_Dofstream@@QEAAXXZ>

externdef __imp_??_Dostream@@QEAAXXZ:PPROC
??_Dostream@@QEAAXXZ equ <__imp_??_Dostream@@QEAAXXZ>

externdef __imp_??_Dostream_withassign@@QEAAXXZ:PPROC
??_Dostream_withassign@@QEAAXXZ equ <__imp_??_Dostream_withassign@@QEAAXXZ>

externdef __imp_??_Dostrstream@@QEAAXXZ:PPROC
??_Dostrstream@@QEAAXXZ equ <__imp_??_Dostrstream@@QEAAXXZ>

externdef __imp_??_Dstdiostream@@QEAAXXZ:PPROC
??_Dstdiostream@@QEAAXXZ equ <__imp_??_Dstdiostream@@QEAAXXZ>

externdef __imp_??_Dstrstream@@QEAAXXZ:PPROC
??_Dstrstream@@QEAAXXZ equ <__imp_??_Dstrstream@@QEAAXXZ>

externdef __imp_?adjustfield@ios@@2JB:PPROC
?adjustfield@ios@@2JB equ <__imp_?adjustfield@ios@@2JB>

externdef __imp_?allocate@streambuf@@IEAAHXZ:PPROC
?allocate@streambuf@@IEAAHXZ equ <__imp_?allocate@streambuf@@IEAAHXZ>

externdef __imp_?attach@filebuf@@QEAAPEAV1@H@Z:PPROC
?attach@filebuf@@QEAAPEAV1@H@Z equ <__imp_?attach@filebuf@@QEAAPEAV1@H@Z>

externdef __imp_?attach@fstream@@QEAAXH@Z:PPROC
?attach@fstream@@QEAAXH@Z equ <__imp_?attach@fstream@@QEAAXH@Z>

externdef __imp_?attach@ifstream@@QEAAXH@Z:PPROC
?attach@ifstream@@QEAAXH@Z equ <__imp_?attach@ifstream@@QEAAXH@Z>

externdef __imp_?attach@ofstream@@QEAAXH@Z:PPROC
?attach@ofstream@@QEAAXH@Z equ <__imp_?attach@ofstream@@QEAAXH@Z>

externdef __imp_?bad@ios@@QEBAHXZ:PPROC
?bad@ios@@QEBAHXZ equ <__imp_?bad@ios@@QEBAHXZ>

externdef __imp_?base@streambuf@@IEBAPEADXZ:PPROC
?base@streambuf@@IEBAPEADXZ equ <__imp_?base@streambuf@@IEBAPEADXZ>

externdef __imp_?basefield@ios@@2JB:PPROC
?basefield@ios@@2JB equ <__imp_?basefield@ios@@2JB>

externdef __imp_?binary@filebuf@@2HB:PPROC
?binary@filebuf@@2HB equ <__imp_?binary@filebuf@@2HB>

externdef __imp_?bitalloc@ios@@SAJXZ:PPROC
?bitalloc@ios@@SAJXZ equ <__imp_?bitalloc@ios@@SAJXZ>

externdef __imp_?blen@streambuf@@IEBAHXZ:PPROC
?blen@streambuf@@IEBAHXZ equ <__imp_?blen@streambuf@@IEBAHXZ>

externdef __imp_?cerr@@3Vostream_withassign@@A:PPROC
?cerr@@3Vostream_withassign@@A equ <__imp_?cerr@@3Vostream_withassign@@A>
  IFNDEF __UNICODE__
    ?cerr@@3Vostream_withassign@@ equ <__imp_?cerr@@3Vostream_withassign@@A>
  ENDIF

externdef __imp_?cin@@3Vistream_withassign@@A:PPROC
?cin@@3Vistream_withassign@@A equ <__imp_?cin@@3Vistream_withassign@@A>
  IFNDEF __UNICODE__
    ?cin@@3Vistream_withassign@@ equ <__imp_?cin@@3Vistream_withassign@@A>
  ENDIF

externdef __imp_?clear@ios@@QEAAXH@Z:PPROC
?clear@ios@@QEAAXH@Z equ <__imp_?clear@ios@@QEAAXH@Z>

externdef __imp_?clog@@3Vostream_withassign@@A:PPROC
?clog@@3Vostream_withassign@@A equ <__imp_?clog@@3Vostream_withassign@@A>
  IFNDEF __UNICODE__
    ?clog@@3Vostream_withassign@@ equ <__imp_?clog@@3Vostream_withassign@@A>
  ENDIF

externdef __imp_?close@filebuf@@QEAAPEAV1@XZ:PPROC
?close@filebuf@@QEAAPEAV1@XZ equ <__imp_?close@filebuf@@QEAAPEAV1@XZ>

externdef __imp_?close@fstream@@QEAAXXZ:PPROC
?close@fstream@@QEAAXXZ equ <__imp_?close@fstream@@QEAAXXZ>

externdef __imp_?close@ifstream@@QEAAXXZ:PPROC
?close@ifstream@@QEAAXXZ equ <__imp_?close@ifstream@@QEAAXXZ>

externdef __imp_?close@ofstream@@QEAAXXZ:PPROC
?close@ofstream@@QEAAXXZ equ <__imp_?close@ofstream@@QEAAXXZ>

externdef __imp_?clrlock@ios@@QEAAXXZ:PPROC
?clrlock@ios@@QEAAXXZ equ <__imp_?clrlock@ios@@QEAAXXZ>

externdef __imp_?clrlock@streambuf@@QEAAXXZ:PPROC
?clrlock@streambuf@@QEAAXXZ equ <__imp_?clrlock@streambuf@@QEAAXXZ>

externdef __imp_?cout@@3Vostream_withassign@@A:PPROC
?cout@@3Vostream_withassign@@A equ <__imp_?cout@@3Vostream_withassign@@A>
  IFNDEF __UNICODE__
    ?cout@@3Vostream_withassign@@ equ <__imp_?cout@@3Vostream_withassign@@A>
  ENDIF

externdef __imp_?dbp@streambuf@@QEAAXXZ:PPROC
?dbp@streambuf@@QEAAXXZ equ <__imp_?dbp@streambuf@@QEAAXXZ>

externdef __imp_?dec@@YAAEAVios@@AEAV1@@Z:PPROC
?dec@@YAAEAVios@@AEAV1@@Z equ <__imp_?dec@@YAAEAVios@@AEAV1@@Z>

externdef __imp_?delbuf@ios@@QEAAXH@Z:PPROC
?delbuf@ios@@QEAAXH@Z equ <__imp_?delbuf@ios@@QEAAXH@Z>

externdef __imp_?delbuf@ios@@QEBAHXZ:PPROC
?delbuf@ios@@QEBAHXZ equ <__imp_?delbuf@ios@@QEBAHXZ>

externdef __imp_?doallocate@streambuf@@MEAAHXZ:PPROC
?doallocate@streambuf@@MEAAHXZ equ <__imp_?doallocate@streambuf@@MEAAHXZ>

externdef __imp_?doallocate@strstreambuf@@MEAAHXZ:PPROC
?doallocate@strstreambuf@@MEAAHXZ equ <__imp_?doallocate@strstreambuf@@MEAAHXZ>

externdef __imp_?eatwhite@istream@@QEAAXXZ:PPROC
?eatwhite@istream@@QEAAXXZ equ <__imp_?eatwhite@istream@@QEAAXXZ>

externdef __imp_?eback@streambuf@@IEBAPEADXZ:PPROC
?eback@streambuf@@IEBAPEADXZ equ <__imp_?eback@streambuf@@IEBAPEADXZ>

externdef __imp_?ebuf@streambuf@@IEBAPEADXZ:PPROC
?ebuf@streambuf@@IEBAPEADXZ equ <__imp_?ebuf@streambuf@@IEBAPEADXZ>

externdef __imp_?egptr@streambuf@@IEBAPEADXZ:PPROC
?egptr@streambuf@@IEBAPEADXZ equ <__imp_?egptr@streambuf@@IEBAPEADXZ>

externdef __imp_?endl@@YAAEAVostream@@AEAV1@@Z:PPROC
?endl@@YAAEAVostream@@AEAV1@@Z equ <__imp_?endl@@YAAEAVostream@@AEAV1@@Z>

externdef __imp_?ends@@YAAEAVostream@@AEAV1@@Z:PPROC
?ends@@YAAEAVostream@@AEAV1@@Z equ <__imp_?ends@@YAAEAVostream@@AEAV1@@Z>

externdef __imp_?eof@ios@@QEBAHXZ:PPROC
?eof@ios@@QEBAHXZ equ <__imp_?eof@ios@@QEBAHXZ>

externdef __imp_?epptr@streambuf@@IEBAPEADXZ:PPROC
?epptr@streambuf@@IEBAPEADXZ equ <__imp_?epptr@streambuf@@IEBAPEADXZ>

externdef __imp_?fLockcInit@ios@@0HA:PPROC
?fLockcInit@ios@@0HA equ <__imp_?fLockcInit@ios@@0HA>
  IFNDEF __UNICODE__
    ?fLockcInit@ios@@0H equ <__imp_?fLockcInit@ios@@0HA>
  ENDIF

externdef __imp_?fail@ios@@QEBAHXZ:PPROC
?fail@ios@@QEBAHXZ equ <__imp_?fail@ios@@QEBAHXZ>

externdef __imp_?fd@filebuf@@QEBAHXZ:PPROC
?fd@filebuf@@QEBAHXZ equ <__imp_?fd@filebuf@@QEBAHXZ>

externdef __imp_?fd@fstream@@QEBAHXZ:PPROC
?fd@fstream@@QEBAHXZ equ <__imp_?fd@fstream@@QEBAHXZ>

externdef __imp_?fd@ifstream@@QEBAHXZ:PPROC
?fd@ifstream@@QEBAHXZ equ <__imp_?fd@ifstream@@QEBAHXZ>

externdef __imp_?fd@ofstream@@QEBAHXZ:PPROC
?fd@ofstream@@QEBAHXZ equ <__imp_?fd@ofstream@@QEBAHXZ>

externdef __imp_?fill@ios@@QEAADD@Z:PPROC
?fill@ios@@QEAADD@Z equ <__imp_?fill@ios@@QEAADD@Z>

externdef __imp_?fill@ios@@QEBADXZ:PPROC
?fill@ios@@QEBADXZ equ <__imp_?fill@ios@@QEBADXZ>

externdef __imp_?flags@ios@@QEAAJJ@Z:PPROC
?flags@ios@@QEAAJJ@Z equ <__imp_?flags@ios@@QEAAJJ@Z>

externdef __imp_?flags@ios@@QEBAJXZ:PPROC
?flags@ios@@QEBAJXZ equ <__imp_?flags@ios@@QEBAJXZ>

externdef __imp_?floatfield@ios@@2JB:PPROC
?floatfield@ios@@2JB equ <__imp_?floatfield@ios@@2JB>

externdef __imp_?flush@@YAAEAVostream@@AEAV1@@Z:PPROC
?flush@@YAAEAVostream@@AEAV1@@Z equ <__imp_?flush@@YAAEAVostream@@AEAV1@@Z>

externdef __imp_?flush@ostream@@QEAAAEAV1@XZ:PPROC
?flush@ostream@@QEAAAEAV1@XZ equ <__imp_?flush@ostream@@QEAAAEAV1@XZ>

externdef __imp_?freeze@strstreambuf@@QEAAXH@Z:PPROC
?freeze@strstreambuf@@QEAAXH@Z equ <__imp_?freeze@strstreambuf@@QEAAXH@Z>

externdef __imp_?gbump@streambuf@@IEAAXH@Z:PPROC
?gbump@streambuf@@IEAAXH@Z equ <__imp_?gbump@streambuf@@IEAAXH@Z>

externdef __imp_?gcount@istream@@QEBAHXZ:PPROC
?gcount@istream@@QEBAHXZ equ <__imp_?gcount@istream@@QEBAHXZ>

externdef __imp_?get@istream@@IEAAAEAV1@PEADHH@Z:PPROC
?get@istream@@IEAAAEAV1@PEADHH@Z equ <__imp_?get@istream@@IEAAAEAV1@PEADHH@Z>

externdef __imp_?get@istream@@QEAAAEAV1@AEAC@Z:PPROC
?get@istream@@QEAAAEAV1@AEAC@Z equ <__imp_?get@istream@@QEAAAEAV1@AEAC@Z>

externdef __imp_?get@istream@@QEAAAEAV1@AEAD@Z:PPROC
?get@istream@@QEAAAEAV1@AEAD@Z equ <__imp_?get@istream@@QEAAAEAV1@AEAD@Z>

externdef __imp_?get@istream@@QEAAAEAV1@AEAE@Z:PPROC
?get@istream@@QEAAAEAV1@AEAE@Z equ <__imp_?get@istream@@QEAAAEAV1@AEAE@Z>

externdef __imp_?get@istream@@QEAAAEAV1@AEAVstreambuf@@D@Z:PPROC
?get@istream@@QEAAAEAV1@AEAVstreambuf@@D@Z equ <__imp_?get@istream@@QEAAAEAV1@AEAVstreambuf@@D@Z>

externdef __imp_?get@istream@@QEAAAEAV1@PEACHD@Z:PPROC
?get@istream@@QEAAAEAV1@PEACHD@Z equ <__imp_?get@istream@@QEAAAEAV1@PEACHD@Z>

externdef __imp_?get@istream@@QEAAAEAV1@PEADHD@Z:PPROC
?get@istream@@QEAAAEAV1@PEADHD@Z equ <__imp_?get@istream@@QEAAAEAV1@PEADHD@Z>

externdef __imp_?get@istream@@QEAAAEAV1@PEAEHD@Z:PPROC
?get@istream@@QEAAAEAV1@PEAEHD@Z equ <__imp_?get@istream@@QEAAAEAV1@PEAEHD@Z>

externdef __imp_?get@istream@@QEAAHXZ:PPROC
?get@istream@@QEAAHXZ equ <__imp_?get@istream@@QEAAHXZ>

externdef __imp_?getdouble@istream@@AEAAHPEADH@Z:PPROC
?getdouble@istream@@AEAAHPEADH@Z equ <__imp_?getdouble@istream@@AEAAHPEADH@Z>

externdef __imp_?getint@istream@@AEAAHPEAD@Z:PPROC
?getint@istream@@AEAAHPEAD@Z equ <__imp_?getint@istream@@AEAAHPEAD@Z>

externdef __imp_?getline@istream@@QEAAAEAV1@PEACHD@Z:PPROC
?getline@istream@@QEAAAEAV1@PEACHD@Z equ <__imp_?getline@istream@@QEAAAEAV1@PEACHD@Z>

externdef __imp_?getline@istream@@QEAAAEAV1@PEADHD@Z:PPROC
?getline@istream@@QEAAAEAV1@PEADHD@Z equ <__imp_?getline@istream@@QEAAAEAV1@PEADHD@Z>

externdef __imp_?getline@istream@@QEAAAEAV1@PEAEHD@Z:PPROC
?getline@istream@@QEAAAEAV1@PEAEHD@Z equ <__imp_?getline@istream@@QEAAAEAV1@PEAEHD@Z>

externdef __imp_?good@ios@@QEBAHXZ:PPROC
?good@ios@@QEBAHXZ equ <__imp_?good@ios@@QEBAHXZ>

externdef __imp_?gptr@streambuf@@IEBAPEADXZ:PPROC
?gptr@streambuf@@IEBAPEADXZ equ <__imp_?gptr@streambuf@@IEBAPEADXZ>

externdef __imp_?hex@@YAAEAVios@@AEAV1@@Z:PPROC
?hex@@YAAEAVios@@AEAV1@@Z equ <__imp_?hex@@YAAEAVios@@AEAV1@@Z>

externdef __imp_?ignore@istream@@QEAAAEAV1@HH@Z:PPROC
?ignore@istream@@QEAAAEAV1@HH@Z equ <__imp_?ignore@istream@@QEAAAEAV1@HH@Z>

externdef __imp_?in_avail@streambuf@@QEBAHXZ:PPROC
?in_avail@streambuf@@QEBAHXZ equ <__imp_?in_avail@streambuf@@QEBAHXZ>

externdef __imp_?init@ios@@IEAAXPEAVstreambuf@@@Z:PPROC
?init@ios@@IEAAXPEAVstreambuf@@@Z equ <__imp_?init@ios@@IEAAXPEAVstreambuf@@@Z>

externdef __imp_?ipfx@istream@@QEAAHH@Z:PPROC
?ipfx@istream@@QEAAHH@Z equ <__imp_?ipfx@istream@@QEAAHH@Z>

externdef __imp_?is_open@filebuf@@QEBAHXZ:PPROC
?is_open@filebuf@@QEBAHXZ equ <__imp_?is_open@filebuf@@QEBAHXZ>

externdef __imp_?is_open@fstream@@QEBAHXZ:PPROC
?is_open@fstream@@QEBAHXZ equ <__imp_?is_open@fstream@@QEBAHXZ>

externdef __imp_?is_open@ifstream@@QEBAHXZ:PPROC
?is_open@ifstream@@QEBAHXZ equ <__imp_?is_open@ifstream@@QEBAHXZ>

externdef __imp_?is_open@ofstream@@QEBAHXZ:PPROC
?is_open@ofstream@@QEBAHXZ equ <__imp_?is_open@ofstream@@QEBAHXZ>

externdef __imp_?isfx@istream@@QEAAXXZ:PPROC
?isfx@istream@@QEAAXXZ equ <__imp_?isfx@istream@@QEAAXXZ>

externdef __imp_?iword@ios@@QEBAAEAJH@Z:PPROC
?iword@ios@@QEBAAEAJH@Z equ <__imp_?iword@ios@@QEBAAEAJH@Z>

externdef __imp_?lock@ios@@QEAAXXZ:PPROC
?lock@ios@@QEAAXXZ equ <__imp_?lock@ios@@QEAAXXZ>

externdef __imp_?lock@streambuf@@QEAAXXZ:PPROC
?lock@streambuf@@QEAAXXZ equ <__imp_?lock@streambuf@@QEAAXXZ>

externdef __imp_?lockbuf@ios@@QEAAXXZ:PPROC
?lockbuf@ios@@QEAAXXZ equ <__imp_?lockbuf@ios@@QEAAXXZ>

externdef __imp_?lockc@ios@@KAXXZ:PPROC
?lockc@ios@@KAXXZ equ <__imp_?lockc@ios@@KAXXZ>

externdef __imp_?lockptr@ios@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ:PPROC
?lockptr@ios@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ equ <__imp_?lockptr@ios@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ>

externdef __imp_?lockptr@streambuf@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ:PPROC
?lockptr@streambuf@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ equ <__imp_?lockptr@streambuf@@IEAAPEAU_CRT_CRITICAL_SECTION@@XZ>

externdef __imp_?oct@@YAAEAVios@@AEAV1@@Z:PPROC
?oct@@YAAEAVios@@AEAV1@@Z equ <__imp_?oct@@YAAEAVios@@AEAV1@@Z>

externdef __imp_?open@filebuf@@QEAAPEAV1@PEBDHH@Z:PPROC
?open@filebuf@@QEAAPEAV1@PEBDHH@Z equ <__imp_?open@filebuf@@QEAAPEAV1@PEBDHH@Z>

externdef __imp_?open@fstream@@QEAAXPEBDHH@Z:PPROC
?open@fstream@@QEAAXPEBDHH@Z equ <__imp_?open@fstream@@QEAAXPEBDHH@Z>

externdef __imp_?open@ifstream@@QEAAXPEBDHH@Z:PPROC
?open@ifstream@@QEAAXPEBDHH@Z equ <__imp_?open@ifstream@@QEAAXPEBDHH@Z>

externdef __imp_?open@ofstream@@QEAAXPEBDHH@Z:PPROC
?open@ofstream@@QEAAXPEBDHH@Z equ <__imp_?open@ofstream@@QEAAXPEBDHH@Z>

externdef __imp_?openprot@filebuf@@2HB:PPROC
?openprot@filebuf@@2HB equ <__imp_?openprot@filebuf@@2HB>

externdef __imp_?opfx@ostream@@QEAAHXZ:PPROC
?opfx@ostream@@QEAAHXZ equ <__imp_?opfx@ostream@@QEAAHXZ>

externdef __imp_?osfx@ostream@@QEAAXXZ:PPROC
?osfx@ostream@@QEAAXXZ equ <__imp_?osfx@ostream@@QEAAXXZ>

externdef __imp_?out_waiting@streambuf@@QEBAHXZ:PPROC
?out_waiting@streambuf@@QEBAHXZ equ <__imp_?out_waiting@streambuf@@QEBAHXZ>

externdef __imp_?overflow@filebuf@@UEAAHH@Z:PPROC
?overflow@filebuf@@UEAAHH@Z equ <__imp_?overflow@filebuf@@UEAAHH@Z>

externdef __imp_?overflow@stdiobuf@@UEAAHH@Z:PPROC
?overflow@stdiobuf@@UEAAHH@Z equ <__imp_?overflow@stdiobuf@@UEAAHH@Z>

externdef __imp_?overflow@strstreambuf@@UEAAHH@Z:PPROC
?overflow@strstreambuf@@UEAAHH@Z equ <__imp_?overflow@strstreambuf@@UEAAHH@Z>

externdef __imp_?pbackfail@stdiobuf@@UEAAHH@Z:PPROC
?pbackfail@stdiobuf@@UEAAHH@Z equ <__imp_?pbackfail@stdiobuf@@UEAAHH@Z>

externdef __imp_?pbackfail@streambuf@@UEAAHH@Z:PPROC
?pbackfail@streambuf@@UEAAHH@Z equ <__imp_?pbackfail@streambuf@@UEAAHH@Z>

externdef __imp_?pbase@streambuf@@IEBAPEADXZ:PPROC
?pbase@streambuf@@IEBAPEADXZ equ <__imp_?pbase@streambuf@@IEBAPEADXZ>

externdef __imp_?pbump@streambuf@@IEAAXH@Z:PPROC
?pbump@streambuf@@IEAAXH@Z equ <__imp_?pbump@streambuf@@IEAAXH@Z>

externdef __imp_?pcount@ostrstream@@QEBAHXZ:PPROC
?pcount@ostrstream@@QEBAHXZ equ <__imp_?pcount@ostrstream@@QEBAHXZ>

externdef __imp_?pcount@strstream@@QEBAHXZ:PPROC
?pcount@strstream@@QEBAHXZ equ <__imp_?pcount@strstream@@QEBAHXZ>

externdef __imp_?peek@istream@@QEAAHXZ:PPROC
?peek@istream@@QEAAHXZ equ <__imp_?peek@istream@@QEAAHXZ>

externdef __imp_?pptr@streambuf@@IEBAPEADXZ:PPROC
?pptr@streambuf@@IEBAPEADXZ equ <__imp_?pptr@streambuf@@IEBAPEADXZ>

externdef __imp_?precision@ios@@QEAAHH@Z:PPROC
?precision@ios@@QEAAHH@Z equ <__imp_?precision@ios@@QEAAHH@Z>

externdef __imp_?precision@ios@@QEBAHXZ:PPROC
?precision@ios@@QEBAHXZ equ <__imp_?precision@ios@@QEBAHXZ>

externdef __imp_?put@ostream@@QEAAAEAV1@C@Z:PPROC
?put@ostream@@QEAAAEAV1@C@Z equ <__imp_?put@ostream@@QEAAAEAV1@C@Z>

externdef __imp_?put@ostream@@QEAAAEAV1@D@Z:PPROC
?put@ostream@@QEAAAEAV1@D@Z equ <__imp_?put@ostream@@QEAAAEAV1@D@Z>

externdef __imp_?put@ostream@@QEAAAEAV1@E@Z:PPROC
?put@ostream@@QEAAAEAV1@E@Z equ <__imp_?put@ostream@@QEAAAEAV1@E@Z>

externdef __imp_?putback@istream@@QEAAAEAV1@D@Z:PPROC
?putback@istream@@QEAAAEAV1@D@Z equ <__imp_?putback@istream@@QEAAAEAV1@D@Z>

externdef __imp_?pword@ios@@QEBAAEAPEAXH@Z:PPROC
?pword@ios@@QEBAAEAPEAXH@Z equ <__imp_?pword@ios@@QEBAAEAPEAXH@Z>

externdef __imp_?rdbuf@fstream@@QEBAPEAVfilebuf@@XZ:PPROC
?rdbuf@fstream@@QEBAPEAVfilebuf@@XZ equ <__imp_?rdbuf@fstream@@QEBAPEAVfilebuf@@XZ>

externdef __imp_?rdbuf@ifstream@@QEBAPEAVfilebuf@@XZ:PPROC
?rdbuf@ifstream@@QEBAPEAVfilebuf@@XZ equ <__imp_?rdbuf@ifstream@@QEBAPEAVfilebuf@@XZ>

externdef __imp_?rdbuf@ios@@QEBAPEAVstreambuf@@XZ:PPROC
?rdbuf@ios@@QEBAPEAVstreambuf@@XZ equ <__imp_?rdbuf@ios@@QEBAPEAVstreambuf@@XZ>

externdef __imp_?rdbuf@istrstream@@QEBAPEAVstrstreambuf@@XZ:PPROC
?rdbuf@istrstream@@QEBAPEAVstrstreambuf@@XZ equ <__imp_?rdbuf@istrstream@@QEBAPEAVstrstreambuf@@XZ>

externdef __imp_?rdbuf@ofstream@@QEBAPEAVfilebuf@@XZ:PPROC
?rdbuf@ofstream@@QEBAPEAVfilebuf@@XZ equ <__imp_?rdbuf@ofstream@@QEBAPEAVfilebuf@@XZ>

externdef __imp_?rdbuf@ostrstream@@QEBAPEAVstrstreambuf@@XZ:PPROC
?rdbuf@ostrstream@@QEBAPEAVstrstreambuf@@XZ equ <__imp_?rdbuf@ostrstream@@QEBAPEAVstrstreambuf@@XZ>

externdef __imp_?rdbuf@stdiostream@@QEBAPEAVstdiobuf@@XZ:PPROC
?rdbuf@stdiostream@@QEBAPEAVstdiobuf@@XZ equ <__imp_?rdbuf@stdiostream@@QEBAPEAVstdiobuf@@XZ>

externdef __imp_?rdbuf@strstream@@QEBAPEAVstrstreambuf@@XZ:PPROC
?rdbuf@strstream@@QEBAPEAVstrstreambuf@@XZ equ <__imp_?rdbuf@strstream@@QEBAPEAVstrstreambuf@@XZ>

externdef __imp_?rdstate@ios@@QEBAHXZ:PPROC
?rdstate@ios@@QEBAHXZ equ <__imp_?rdstate@ios@@QEBAHXZ>

externdef __imp_?read@istream@@QEAAAEAV1@PEACH@Z:PPROC
?read@istream@@QEAAAEAV1@PEACH@Z equ <__imp_?read@istream@@QEAAAEAV1@PEACH@Z>

externdef __imp_?read@istream@@QEAAAEAV1@PEADH@Z:PPROC
?read@istream@@QEAAAEAV1@PEADH@Z equ <__imp_?read@istream@@QEAAAEAV1@PEADH@Z>

externdef __imp_?read@istream@@QEAAAEAV1@PEAEH@Z:PPROC
?read@istream@@QEAAAEAV1@PEAEH@Z equ <__imp_?read@istream@@QEAAAEAV1@PEAEH@Z>

externdef __imp_?sbumpc@streambuf@@QEAAHXZ:PPROC
?sbumpc@streambuf@@QEAAHXZ equ <__imp_?sbumpc@streambuf@@QEAAHXZ>

externdef __imp_?seekg@istream@@QEAAAEAV1@J@Z:PPROC
?seekg@istream@@QEAAAEAV1@J@Z equ <__imp_?seekg@istream@@QEAAAEAV1@J@Z>

externdef __imp_?seekg@istream@@QEAAAEAV1@JW4seek_dir@ios@@@Z:PPROC
?seekg@istream@@QEAAAEAV1@JW4seek_dir@ios@@@Z equ <__imp_?seekg@istream@@QEAAAEAV1@JW4seek_dir@ios@@@Z>

externdef __imp_?seekoff@filebuf@@UEAAJJW4seek_dir@ios@@H@Z:PPROC
?seekoff@filebuf@@UEAAJJW4seek_dir@ios@@H@Z equ <__imp_?seekoff@filebuf@@UEAAJJW4seek_dir@ios@@H@Z>

externdef __imp_?seekoff@stdiobuf@@UEAAJJW4seek_dir@ios@@H@Z:PPROC
?seekoff@stdiobuf@@UEAAJJW4seek_dir@ios@@H@Z equ <__imp_?seekoff@stdiobuf@@UEAAJJW4seek_dir@ios@@H@Z>

externdef __imp_?seekoff@streambuf@@UEAAJJW4seek_dir@ios@@H@Z:PPROC
?seekoff@streambuf@@UEAAJJW4seek_dir@ios@@H@Z equ <__imp_?seekoff@streambuf@@UEAAJJW4seek_dir@ios@@H@Z>

externdef __imp_?seekoff@strstreambuf@@UEAAJJW4seek_dir@ios@@H@Z:PPROC
?seekoff@strstreambuf@@UEAAJJW4seek_dir@ios@@H@Z equ <__imp_?seekoff@strstreambuf@@UEAAJJW4seek_dir@ios@@H@Z>

externdef __imp_?seekp@ostream@@QEAAAEAV1@J@Z:PPROC
?seekp@ostream@@QEAAAEAV1@J@Z equ <__imp_?seekp@ostream@@QEAAAEAV1@J@Z>

externdef __imp_?seekp@ostream@@QEAAAEAV1@JW4seek_dir@ios@@@Z:PPROC
?seekp@ostream@@QEAAAEAV1@JW4seek_dir@ios@@@Z equ <__imp_?seekp@ostream@@QEAAAEAV1@JW4seek_dir@ios@@@Z>

externdef __imp_?seekpos@streambuf@@UEAAJJH@Z:PPROC
?seekpos@streambuf@@UEAAJJH@Z equ <__imp_?seekpos@streambuf@@UEAAJJH@Z>

externdef __imp_?setb@streambuf@@IEAAXPEAD0H@Z:PPROC
?setb@streambuf@@IEAAXPEAD0H@Z equ <__imp_?setb@streambuf@@IEAAXPEAD0H@Z>

externdef __imp_?setbuf@filebuf@@UEAAPEAVstreambuf@@PEADH@Z:PPROC
?setbuf@filebuf@@UEAAPEAVstreambuf@@PEADH@Z equ <__imp_?setbuf@filebuf@@UEAAPEAVstreambuf@@PEADH@Z>

externdef __imp_?setbuf@fstream@@QEAAPEAVstreambuf@@PEADH@Z:PPROC
?setbuf@fstream@@QEAAPEAVstreambuf@@PEADH@Z equ <__imp_?setbuf@fstream@@QEAAPEAVstreambuf@@PEADH@Z>

externdef __imp_?setbuf@ifstream@@QEAAPEAVstreambuf@@PEADH@Z:PPROC
?setbuf@ifstream@@QEAAPEAVstreambuf@@PEADH@Z equ <__imp_?setbuf@ifstream@@QEAAPEAVstreambuf@@PEADH@Z>

externdef __imp_?setbuf@ofstream@@QEAAPEAVstreambuf@@PEADH@Z:PPROC
?setbuf@ofstream@@QEAAPEAVstreambuf@@PEADH@Z equ <__imp_?setbuf@ofstream@@QEAAPEAVstreambuf@@PEADH@Z>

externdef __imp_?setbuf@streambuf@@UEAAPEAV1@PEADH@Z:PPROC
?setbuf@streambuf@@UEAAPEAV1@PEADH@Z equ <__imp_?setbuf@streambuf@@UEAAPEAV1@PEADH@Z>

externdef __imp_?setbuf@strstreambuf@@UEAAPEAVstreambuf@@PEADH@Z:PPROC
?setbuf@strstreambuf@@UEAAPEAVstreambuf@@PEADH@Z equ <__imp_?setbuf@strstreambuf@@UEAAPEAVstreambuf@@PEADH@Z>

externdef __imp_?setf@ios@@QEAAJJ@Z:PPROC
?setf@ios@@QEAAJJ@Z equ <__imp_?setf@ios@@QEAAJJ@Z>

externdef __imp_?setf@ios@@QEAAJJJ@Z:PPROC
?setf@ios@@QEAAJJJ@Z equ <__imp_?setf@ios@@QEAAJJJ@Z>

externdef __imp_?setg@streambuf@@IEAAXPEAD00@Z:PPROC
?setg@streambuf@@IEAAXPEAD00@Z equ <__imp_?setg@streambuf@@IEAAXPEAD00@Z>

externdef __imp_?setlock@ios@@QEAAXXZ:PPROC
?setlock@ios@@QEAAXXZ equ <__imp_?setlock@ios@@QEAAXXZ>

externdef __imp_?setlock@streambuf@@QEAAXXZ:PPROC
?setlock@streambuf@@QEAAXXZ equ <__imp_?setlock@streambuf@@QEAAXXZ>

externdef __imp_?setmode@filebuf@@QEAAHH@Z:PPROC
?setmode@filebuf@@QEAAHH@Z equ <__imp_?setmode@filebuf@@QEAAHH@Z>

externdef __imp_?setmode@fstream@@QEAAHH@Z:PPROC
?setmode@fstream@@QEAAHH@Z equ <__imp_?setmode@fstream@@QEAAHH@Z>

externdef __imp_?setmode@ifstream@@QEAAHH@Z:PPROC
?setmode@ifstream@@QEAAHH@Z equ <__imp_?setmode@ifstream@@QEAAHH@Z>

externdef __imp_?setmode@ofstream@@QEAAHH@Z:PPROC
?setmode@ofstream@@QEAAHH@Z equ <__imp_?setmode@ofstream@@QEAAHH@Z>

externdef __imp_?setp@streambuf@@IEAAXPEAD0@Z:PPROC
?setp@streambuf@@IEAAXPEAD0@Z equ <__imp_?setp@streambuf@@IEAAXPEAD0@Z>

externdef __imp_?setrwbuf@stdiobuf@@QEAAHHH@Z:PPROC
?setrwbuf@stdiobuf@@QEAAHHH@Z equ <__imp_?setrwbuf@stdiobuf@@QEAAHHH@Z>

externdef __imp_?sgetc@streambuf@@QEAAHXZ:PPROC
?sgetc@streambuf@@QEAAHXZ equ <__imp_?sgetc@streambuf@@QEAAHXZ>

externdef __imp_?sgetn@streambuf@@QEAAHPEADH@Z:PPROC
?sgetn@streambuf@@QEAAHPEADH@Z equ <__imp_?sgetn@streambuf@@QEAAHPEADH@Z>

externdef __imp_?sh_none@filebuf@@2HB:PPROC
?sh_none@filebuf@@2HB equ <__imp_?sh_none@filebuf@@2HB>

externdef __imp_?sh_read@filebuf@@2HB:PPROC
?sh_read@filebuf@@2HB equ <__imp_?sh_read@filebuf@@2HB>

externdef __imp_?sh_write@filebuf@@2HB:PPROC
?sh_write@filebuf@@2HB equ <__imp_?sh_write@filebuf@@2HB>

externdef __imp_?snextc@streambuf@@QEAAHXZ:PPROC
?snextc@streambuf@@QEAAHXZ equ <__imp_?snextc@streambuf@@QEAAHXZ>

externdef __imp_?sputbackc@streambuf@@QEAAHD@Z:PPROC
?sputbackc@streambuf@@QEAAHD@Z equ <__imp_?sputbackc@streambuf@@QEAAHD@Z>

externdef __imp_?sputc@streambuf@@QEAAHH@Z:PPROC
?sputc@streambuf@@QEAAHH@Z equ <__imp_?sputc@streambuf@@QEAAHH@Z>

externdef __imp_?sputn@streambuf@@QEAAHPEBDH@Z:PPROC
?sputn@streambuf@@QEAAHPEBDH@Z equ <__imp_?sputn@streambuf@@QEAAHPEBDH@Z>

externdef __imp_?stdiofile@stdiobuf@@QEAAPEAU_iobuf@@XZ:PPROC
?stdiofile@stdiobuf@@QEAAPEAU_iobuf@@XZ equ <__imp_?stdiofile@stdiobuf@@QEAAPEAU_iobuf@@XZ>

externdef __imp_?stossc@streambuf@@QEAAXXZ:PPROC
?stossc@streambuf@@QEAAXXZ equ <__imp_?stossc@streambuf@@QEAAXXZ>

externdef __imp_?str@istrstream@@QEAAPEADXZ:PPROC
?str@istrstream@@QEAAPEADXZ equ <__imp_?str@istrstream@@QEAAPEADXZ>

externdef __imp_?str@ostrstream@@QEAAPEADXZ:PPROC
?str@ostrstream@@QEAAPEADXZ equ <__imp_?str@ostrstream@@QEAAPEADXZ>

externdef __imp_?str@strstream@@QEAAPEADXZ:PPROC
?str@strstream@@QEAAPEADXZ equ <__imp_?str@strstream@@QEAAPEADXZ>

externdef __imp_?str@strstreambuf@@QEAAPEADXZ:PPROC
?str@strstreambuf@@QEAAPEADXZ equ <__imp_?str@strstreambuf@@QEAAPEADXZ>

externdef __imp_?sunk_with_stdio@ios@@0HA:PPROC
?sunk_with_stdio@ios@@0HA equ <__imp_?sunk_with_stdio@ios@@0HA>
  IFNDEF __UNICODE__
    ?sunk_with_stdio@ios@@0H equ <__imp_?sunk_with_stdio@ios@@0HA>
  ENDIF

externdef __imp_?sync@filebuf@@UEAAHXZ:PPROC
?sync@filebuf@@UEAAHXZ equ <__imp_?sync@filebuf@@UEAAHXZ>

externdef __imp_?sync@istream@@QEAAHXZ:PPROC
?sync@istream@@QEAAHXZ equ <__imp_?sync@istream@@QEAAHXZ>

externdef __imp_?sync@stdiobuf@@UEAAHXZ:PPROC
?sync@stdiobuf@@UEAAHXZ equ <__imp_?sync@stdiobuf@@UEAAHXZ>

externdef __imp_?sync@streambuf@@UEAAHXZ:PPROC
?sync@streambuf@@UEAAHXZ equ <__imp_?sync@streambuf@@UEAAHXZ>

externdef __imp_?sync@strstreambuf@@UEAAHXZ:PPROC
?sync@strstreambuf@@UEAAHXZ equ <__imp_?sync@strstreambuf@@UEAAHXZ>

externdef __imp_?sync_with_stdio@ios@@SAXXZ:PPROC
?sync_with_stdio@ios@@SAXXZ equ <__imp_?sync_with_stdio@ios@@SAXXZ>

externdef __imp_?tellg@istream@@QEAAJXZ:PPROC
?tellg@istream@@QEAAJXZ equ <__imp_?tellg@istream@@QEAAJXZ>

externdef __imp_?tellp@ostream@@QEAAJXZ:PPROC
?tellp@ostream@@QEAAJXZ equ <__imp_?tellp@ostream@@QEAAJXZ>

externdef __imp_?text@filebuf@@2HB:PPROC
?text@filebuf@@2HB equ <__imp_?text@filebuf@@2HB>

externdef __imp_?tie@ios@@QEAAPEAVostream@@PEAV2@@Z:PPROC
?tie@ios@@QEAAPEAVostream@@PEAV2@@Z equ <__imp_?tie@ios@@QEAAPEAVostream@@PEAV2@@Z>

externdef __imp_?tie@ios@@QEBAPEAVostream@@XZ:PPROC
?tie@ios@@QEBAPEAVostream@@XZ equ <__imp_?tie@ios@@QEBAPEAVostream@@XZ>

externdef __imp_?unbuffered@streambuf@@IEAAXH@Z:PPROC
?unbuffered@streambuf@@IEAAXH@Z equ <__imp_?unbuffered@streambuf@@IEAAXH@Z>

externdef __imp_?unbuffered@streambuf@@IEBAHXZ:PPROC
?unbuffered@streambuf@@IEBAHXZ equ <__imp_?unbuffered@streambuf@@IEBAHXZ>

externdef __imp_?underflow@filebuf@@UEAAHXZ:PPROC
?underflow@filebuf@@UEAAHXZ equ <__imp_?underflow@filebuf@@UEAAHXZ>

externdef __imp_?underflow@stdiobuf@@UEAAHXZ:PPROC
?underflow@stdiobuf@@UEAAHXZ equ <__imp_?underflow@stdiobuf@@UEAAHXZ>

externdef __imp_?underflow@strstreambuf@@UEAAHXZ:PPROC
?underflow@strstreambuf@@UEAAHXZ equ <__imp_?underflow@strstreambuf@@UEAAHXZ>

externdef __imp_?unlock@ios@@QEAAXXZ:PPROC
?unlock@ios@@QEAAXXZ equ <__imp_?unlock@ios@@QEAAXXZ>

externdef __imp_?unlock@streambuf@@QEAAXXZ:PPROC
?unlock@streambuf@@QEAAXXZ equ <__imp_?unlock@streambuf@@QEAAXXZ>

externdef __imp_?unlockbuf@ios@@QEAAXXZ:PPROC
?unlockbuf@ios@@QEAAXXZ equ <__imp_?unlockbuf@ios@@QEAAXXZ>

externdef __imp_?unlockc@ios@@KAXXZ:PPROC
?unlockc@ios@@KAXXZ equ <__imp_?unlockc@ios@@KAXXZ>

externdef __imp_?unsetf@ios@@QEAAJJ@Z:PPROC
?unsetf@ios@@QEAAJJ@Z equ <__imp_?unsetf@ios@@QEAAJJ@Z>

externdef __imp_?what@exception@@UEBAPEBDXZ:PPROC
?what@exception@@UEBAPEBDXZ equ <__imp_?what@exception@@UEBAPEBDXZ>

externdef __imp_?width@ios@@QEAAHH@Z:PPROC
?width@ios@@QEAAHH@Z equ <__imp_?width@ios@@QEAAHH@Z>

externdef __imp_?width@ios@@QEBAHXZ:PPROC
?width@ios@@QEBAHXZ equ <__imp_?width@ios@@QEBAHXZ>

externdef __imp_?write@ostream@@QEAAAEAV1@PEBCH@Z:PPROC
?write@ostream@@QEAAAEAV1@PEBCH@Z equ <__imp_?write@ostream@@QEAAAEAV1@PEBCH@Z>

externdef __imp_?write@ostream@@QEAAAEAV1@PEBDH@Z:PPROC
?write@ostream@@QEAAAEAV1@PEBDH@Z equ <__imp_?write@ostream@@QEAAAEAV1@PEBDH@Z>

externdef __imp_?write@ostream@@QEAAAEAV1@PEBEH@Z:PPROC
?write@ostream@@QEAAAEAV1@PEBEH@Z equ <__imp_?write@ostream@@QEAAAEAV1@PEBEH@Z>

externdef __imp_?writepad@ostream@@AEAAAEAV1@PEBD0@Z:PPROC
?writepad@ostream@@AEAAAEAV1@PEBD0@Z equ <__imp_?writepad@ostream@@AEAAAEAV1@PEBD0@Z>

externdef __imp_?ws@@YAAEAVistream@@AEAV1@@Z:PPROC
?ws@@YAAEAVistream@@AEAV1@@Z equ <__imp_?ws@@YAAEAVistream@@AEAV1@@Z>

externdef __imp_?x_curindex@ios@@0HA:PPROC
?x_curindex@ios@@0HA equ <__imp_?x_curindex@ios@@0HA>
  IFNDEF __UNICODE__
    ?x_curindex@ios@@0H equ <__imp_?x_curindex@ios@@0HA>
  ENDIF

externdef __imp_?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@A:PPROC
?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@A equ <__imp_?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@A>
  IFNDEF __UNICODE__
    ?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@ equ <__imp_?x_lockc@ios@@0U_CRT_CRITICAL_SECTION@@A>
  ENDIF

externdef __imp_?x_maxbit@ios@@0JA:PPROC
?x_maxbit@ios@@0JA equ <__imp_?x_maxbit@ios@@0JA>
  IFNDEF __UNICODE__
    ?x_maxbit@ios@@0J equ <__imp_?x_maxbit@ios@@0JA>
  ENDIF

externdef __imp_?x_statebuf@ios@@0PAJA:PPROC
?x_statebuf@ios@@0PAJA equ <__imp_?x_statebuf@ios@@0PAJA>
  IFNDEF __UNICODE__
    ?x_statebuf@ios@@0PAJ equ <__imp_?x_statebuf@ios@@0PAJA>
  ENDIF

externdef __imp_?xalloc@ios@@SAHXZ:PPROC
?xalloc@ios@@SAHXZ equ <__imp_?xalloc@ios@@SAHXZ>

externdef __imp_?xsgetn@streambuf@@UEAAHPEADH@Z:PPROC
?xsgetn@streambuf@@UEAAHPEADH@Z equ <__imp_?xsgetn@streambuf@@UEAAHPEADH@Z>

externdef __imp_?xsputn@streambuf@@UEAAHPEBDH@Z:PPROC
?xsputn@streambuf@@UEAAHPEBDH@Z equ <__imp_?xsputn@streambuf@@UEAAHPEBDH@Z>

externdef __imp___dummy_export:PPROC
__dummy_export equ <__imp___dummy_export>

externdef __imp__mtlock:PPROC
_mtlock equ <__imp__mtlock>

externdef __imp__mtunlock:PPROC
_mtunlock equ <__imp__mtunlock>
