externdef __imp_$I10_OUTPUT:PPROC
vc_$I10_OUTPUT equ <__imp_$I10_OUTPUT>

externdef __imp_??0__non_rtti_object@@QEAA@AEBV0@@Z:PPROC
vc_??0__non_rtti_object@@QEAA@AEBV0@@Z equ <__imp_??0__non_rtti_object@@QEAA@AEBV0@@Z>

externdef __imp_??0__non_rtti_object@@QEAA@PEBD@Z:PPROC
vc_??0__non_rtti_object@@QEAA@PEBD@Z equ <__imp_??0__non_rtti_object@@QEAA@PEBD@Z>

externdef __imp_??0bad_cast@@AEAA@PEBQEBD@Z:PPROC
vc_??0bad_cast@@AEAA@PEBQEBD@Z equ <__imp_??0bad_cast@@AEAA@PEBQEBD@Z>

externdef __imp_??0bad_cast@@QEAA@AEBQEBD@Z:PPROC
vc_??0bad_cast@@QEAA@AEBQEBD@Z equ <__imp_??0bad_cast@@QEAA@AEBQEBD@Z>

externdef __imp_??0bad_cast@@QEAA@AEBV0@@Z:PPROC
vc_??0bad_cast@@QEAA@AEBV0@@Z equ <__imp_??0bad_cast@@QEAA@AEBV0@@Z>

externdef __imp_??0bad_cast@@QEAA@PEBD@Z:PPROC
vc_??0bad_cast@@QEAA@PEBD@Z equ <__imp_??0bad_cast@@QEAA@PEBD@Z>

externdef __imp_??0bad_typeid@@QEAA@AEBV0@@Z:PPROC
vc_??0bad_typeid@@QEAA@AEBV0@@Z equ <__imp_??0bad_typeid@@QEAA@AEBV0@@Z>

externdef __imp_??0bad_typeid@@QEAA@PEBD@Z:PPROC
vc_??0bad_typeid@@QEAA@PEBD@Z equ <__imp_??0bad_typeid@@QEAA@PEBD@Z>

externdef __imp_??0exception@@QEAA@AEBQEBD@Z:PPROC
vc_??0exception@@QEAA@AEBQEBD@Z equ <__imp_??0exception@@QEAA@AEBQEBD@Z>

externdef __imp_??0exception@@QEAA@AEBQEBDH@Z:PPROC
vc_??0exception@@QEAA@AEBQEBDH@Z equ <__imp_??0exception@@QEAA@AEBQEBDH@Z>

externdef __imp_??0exception@@QEAA@AEBV0@@Z:PPROC
vc_??0exception@@QEAA@AEBV0@@Z equ <__imp_??0exception@@QEAA@AEBV0@@Z>

externdef __imp_??0exception@@QEAA@XZ:PPROC
vc_??0exception@@QEAA@XZ equ <__imp_??0exception@@QEAA@XZ>

externdef __imp_??1__non_rtti_object@@UEAA@XZ:PPROC
vc_??1__non_rtti_object@@UEAA@XZ equ <__imp_??1__non_rtti_object@@UEAA@XZ>

externdef __imp_??1bad_cast@@UEAA@XZ:PPROC
vc_??1bad_cast@@UEAA@XZ equ <__imp_??1bad_cast@@UEAA@XZ>

externdef __imp_??1bad_typeid@@UEAA@XZ:PPROC
vc_??1bad_typeid@@UEAA@XZ equ <__imp_??1bad_typeid@@UEAA@XZ>

externdef __imp_??1exception@@UEAA@XZ:PPROC
vc_??1exception@@UEAA@XZ equ <__imp_??1exception@@UEAA@XZ>

externdef __imp_??1type_info@@UEAA@XZ:PPROC
vc_??1type_info@@UEAA@XZ equ <__imp_??1type_info@@UEAA@XZ>

externdef __imp_??2@YAPEAX_K@Z:PPROC
vc_??2@YAPEAX_K@Z equ <__imp_??2@YAPEAX_K@Z>

externdef __imp_??3@YAXPEAX@Z:PPROC
vc_??3@YAXPEAX@Z equ <__imp_??3@YAXPEAX@Z>

externdef __imp_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z:PPROC
vc_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4__non_rtti_object@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4bad_cast@@QEAAAEAV0@AEBV0@@Z:PPROC
vc_??4bad_cast@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4bad_cast@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z:PPROC
vc_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4bad_typeid@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4exception@@QEAAAEAV0@AEBV0@@Z:PPROC
vc_??4exception@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4exception@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??8type_info@@QEBAHAEBV0@@Z:PPROC
vc_??8type_info@@QEBAHAEBV0@@Z equ <__imp_??8type_info@@QEBAHAEBV0@@Z>

externdef __imp_??9type_info@@QEBAHAEBV0@@Z:PPROC
vc_??9type_info@@QEBAHAEBV0@@Z equ <__imp_??9type_info@@QEBAHAEBV0@@Z>

externdef __imp_??_7__non_rtti_object@@6B@:PPROC
vc_??_7__non_rtti_object@@6B@ equ <__imp_??_7__non_rtti_object@@6B@>

externdef __imp_??_7bad_cast@@6B@:PPROC
vc_??_7bad_cast@@6B@ equ <__imp_??_7bad_cast@@6B@>

externdef __imp_??_7bad_typeid@@6B@:PPROC
vc_??_7bad_typeid@@6B@ equ <__imp_??_7bad_typeid@@6B@>

externdef __imp_??_7exception@@6B@:PPROC
vc_??_7exception@@6B@ equ <__imp_??_7exception@@6B@>

externdef __imp_??_Fbad_cast@@QEAAXXZ:PPROC
vc_??_Fbad_cast@@QEAAXXZ equ <__imp_??_Fbad_cast@@QEAAXXZ>

externdef __imp_??_Fbad_typeid@@QEAAXXZ:PPROC
vc_??_Fbad_typeid@@QEAAXXZ equ <__imp_??_Fbad_typeid@@QEAAXXZ>

externdef __imp_??_U@YAPEAX_K@Z:PPROC
vc_??_U@YAPEAX_K@Z equ <__imp_??_U@YAPEAX_K@Z>

externdef __imp_??_V@YAXPEAX@Z:PPROC
vc_??_V@YAXPEAX@Z equ <__imp_??_V@YAXPEAX@Z>

externdef __imp_?_query_new_handler@@YAP6AH_K@ZXZ:PPROC
vc_?_query_new_handler@@YAP6AH_K@ZXZ equ <__imp_?_query_new_handler@@YAP6AH_K@ZXZ>

externdef __imp_?_query_new_mode@@YAHXZ:PPROC
vc_?_query_new_mode@@YAHXZ equ <__imp_?_query_new_mode@@YAHXZ>

externdef __imp_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z:PPROC
vc_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z equ <__imp_?_set_new_handler@@YAP6AH_K@ZP6AH0@Z@Z>

externdef __imp_?_set_new_mode@@YAHH@Z:PPROC
vc_?_set_new_mode@@YAHH@Z equ <__imp_?_set_new_mode@@YAHH@Z>

externdef __imp_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z:PPROC
vc_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z equ <__imp_?_set_se_translator@@YAP6AXIPEAU_EXCEPTION_POINTERS@@@ZP6AXI0@Z@Z>

externdef __imp_?before@type_info@@QEBAHAEBV1@@Z:PPROC
vc_?before@type_info@@QEBAHAEBV1@@Z equ <__imp_?before@type_info@@QEBAHAEBV1@@Z>

externdef __imp_?name@type_info@@QEBAPEBDXZ:PPROC
vc_?name@type_info@@QEBAPEBDXZ equ <__imp_?name@type_info@@QEBAPEBDXZ>

externdef __imp_?raw_name@type_info@@QEBAPEBDXZ:PPROC
vc_?raw_name@type_info@@QEBAPEBDXZ equ <__imp_?raw_name@type_info@@QEBAPEBDXZ>

externdef __imp_?set_new_handler@@YAP6AXXZP6AXXZ@Z:PPROC
vc_?set_new_handler@@YAP6AXXZP6AXXZ@Z equ <__imp_?set_new_handler@@YAP6AXXZP6AXXZ@Z>

externdef __imp_?set_terminate@@YAP6AXXZP6AXXZ@Z:PPROC
vc_?set_terminate@@YAP6AXXZP6AXXZ@Z equ <__imp_?set_terminate@@YAP6AXXZP6AXXZ@Z>

externdef __imp_?set_unexpected@@YAP6AXXZP6AXXZ@Z:PPROC
vc_?set_unexpected@@YAP6AXXZP6AXXZ@Z equ <__imp_?set_unexpected@@YAP6AXXZP6AXXZ@Z>

externdef __imp_?terminate@@YAXXZ:PPROC
vc_?terminate@@YAXXZ equ <__imp_?terminate@@YAXXZ>

externdef __imp_?unexpected@@YAXXZ:PPROC
vc_?unexpected@@YAXXZ equ <__imp_?unexpected@@YAXXZ>

externdef __imp_?what@exception@@UEBAPEBDXZ:PPROC
vc_?what@exception@@UEBAPEBDXZ equ <__imp_?what@exception@@UEBAPEBDXZ>

externdef __imp__CxxThrowException:PPROC
vc__CxxThrowException equ <__imp__CxxThrowException>

externdef __imp__Getdays:PPROC
vc__Getdays equ <__imp__Getdays>

externdef __imp__Getmonths:PPROC
vc__Getmonths equ <__imp__Getmonths>

externdef __imp__Gettnames:PPROC
vc__Gettnames equ <__imp__Gettnames>

externdef __imp__HUGE:PPROC
vc__HUGE equ <__imp__HUGE>

externdef __imp__Strftime:PPROC
vc__Strftime equ <__imp__Strftime>

externdef __imp__XcptFilter:PPROC
vc__XcptFilter equ <__imp__XcptFilter>

externdef __imp___C_specific_handler:PPROC
vc___C_specific_handler equ <__imp___C_specific_handler>

externdef __imp___CppXcptFilter:PPROC
vc___CppXcptFilter equ <__imp___CppXcptFilter>

externdef __imp___CxxFrameHandler:PPROC
vc___CxxFrameHandler equ <__imp___CxxFrameHandler>

externdef __imp___DestructExceptionObject:PPROC
vc___DestructExceptionObject equ <__imp___DestructExceptionObject>

externdef __imp___RTCastToVoid:PPROC
vc___RTCastToVoid equ <__imp___RTCastToVoid>

externdef __imp___RTDynamicCast:PPROC
vc___RTDynamicCast equ <__imp___RTDynamicCast>

externdef __imp___RTtypeid:PPROC
vc___RTtypeid equ <__imp___RTtypeid>

externdef __imp___STRINGTOLD:PPROC
vc___STRINGTOLD equ <__imp___STRINGTOLD>

externdef __imp____lc_codepage_func:PPROC
vc____lc_codepage_func equ <__imp____lc_codepage_func>

externdef __imp____lc_collate_cp_func:PPROC
vc____lc_collate_cp_func equ <__imp____lc_collate_cp_func>

externdef __imp____lc_handle_func:PPROC
vc____lc_handle_func equ <__imp____lc_handle_func>

externdef __imp____mb_cur_max_func:PPROC
vc____mb_cur_max_func equ <__imp____mb_cur_max_func>

externdef __imp____setlc_active_func:PPROC
vc____setlc_active_func equ <__imp____setlc_active_func>

externdef __imp____unguarded_readlc_active_add_func:PPROC
vc____unguarded_readlc_active_add_func equ <__imp____unguarded_readlc_active_add_func>

externdef __imp___argc:PPROC
vc___argc equ <__imp___argc>

externdef __imp___argv:PPROC
vc___argv equ <__imp___argv>

externdef __imp___badioinfo:PPROC
vc___badioinfo equ <__imp___badioinfo>

externdef __imp___crtCompareStringA:PPROC
vc___crtCompareStringA equ <__imp___crtCompareStringA>
  IFNDEF __UNICODE__
    __crtCompareString equ <__imp___crtCompareStringA>
  ENDIF

externdef __imp___crtCompareStringW:PPROC
vc___crtCompareStringW equ <__imp___crtCompareStringW>
  IFDEF __UNICODE__
    __crtCompareString equ <__imp___crtCompareStringW>
  ENDIF

externdef __imp___crtGetLocaleInfoW:PPROC
vc___crtGetLocaleInfoW equ <__imp___crtGetLocaleInfoW>
  IFDEF __UNICODE__
    __crtGetLocaleInfo equ <__imp___crtGetLocaleInfoW>
  ENDIF

externdef __imp___crtGetStringTypeW:PPROC
vc___crtGetStringTypeW equ <__imp___crtGetStringTypeW>
  IFDEF __UNICODE__
    __crtGetStringType equ <__imp___crtGetStringTypeW>
  ENDIF

externdef __imp___crtLCMapStringA:PPROC
vc___crtLCMapStringA equ <__imp___crtLCMapStringA>
  IFNDEF __UNICODE__
    __crtLCMapString equ <__imp___crtLCMapStringA>
  ENDIF

externdef __imp___crtLCMapStringW:PPROC
vc___crtLCMapStringW equ <__imp___crtLCMapStringW>
  IFDEF __UNICODE__
    __crtLCMapString equ <__imp___crtLCMapStringW>
  ENDIF

externdef __imp___dllonexit:PPROC
vc___dllonexit equ <__imp___dllonexit>

externdef __imp___doserrno:PPROC
vc___doserrno equ <__imp___doserrno>

externdef __imp___fpecode:PPROC
vc___fpecode equ <__imp___fpecode>

externdef __imp___getmainargs:PPROC
vc___getmainargs equ <__imp___getmainargs>

externdef __imp___initenv:PPROC
vc___initenv equ <__imp___initenv>

externdef __imp___iob_func:PPROC
vc___iob_func equ <__imp___iob_func>

externdef __imp___isascii:PPROC
vc___isascii equ <__imp___isascii>

externdef __imp___iscsym:PPROC
vc___iscsym equ <__imp___iscsym>

externdef __imp___iscsymf:PPROC
vc___iscsymf equ <__imp___iscsymf>

externdef __imp___lc_codepage:PPROC
vc___lc_codepage equ <__imp___lc_codepage>

externdef __imp___lc_collate_cp:PPROC
vc___lc_collate_cp equ <__imp___lc_collate_cp>

externdef __imp___lc_handle:PPROC
vc___lc_handle equ <__imp___lc_handle>

externdef __imp___lconv_init:PPROC
vc___lconv_init equ <__imp___lconv_init>

externdef __imp___mb_cur_max:PPROC
vc___mb_cur_max equ <__imp___mb_cur_max>

externdef __imp___pctype_func:PPROC
vc___pctype_func equ <__imp___pctype_func>

externdef __imp___pioinfo:PPROC
vc___pioinfo equ <__imp___pioinfo>

externdef __imp___pwctype_func:PPROC
vc___pwctype_func equ <__imp___pwctype_func>

externdef __imp___pxcptinfoptrs:PPROC
vc___pxcptinfoptrs equ <__imp___pxcptinfoptrs>

externdef __imp___set_app_type:PPROC
vc___set_app_type equ <__imp___set_app_type>

externdef __imp___setlc_active:PPROC
vc___setlc_active equ <__imp___setlc_active>

externdef __imp___setusermatherr:PPROC
vc___setusermatherr equ <__imp___setusermatherr>

externdef __imp___threadhandle:PPROC
vc___threadhandle equ <__imp___threadhandle>

externdef __imp___threadid:PPROC
vc___threadid equ <__imp___threadid>

externdef __imp___toascii:PPROC
vc___toascii equ <__imp___toascii>

externdef __imp___unDName:PPROC
vc___unDName equ <__imp___unDName>

externdef __imp___unDNameEx:PPROC
vc___unDNameEx equ <__imp___unDNameEx>

externdef __imp___uncaught_exception:PPROC
vc___uncaught_exception equ <__imp___uncaught_exception>

externdef __imp___unguarded_readlc_active:PPROC
vc___unguarded_readlc_active equ <__imp___unguarded_readlc_active>

externdef __imp___wargv:PPROC
vc___wargv equ <__imp___wargv>

externdef __imp___wcserror:PPROC
vc___wcserror equ <__imp___wcserror>

externdef __imp___wgetmainargs:PPROC
vc___wgetmainargs equ <__imp___wgetmainargs>

externdef __imp___winitenv:PPROC
vc___winitenv equ <__imp___winitenv>

externdef __imp__abs64:PPROC
vc__abs64 equ <__imp__abs64>

externdef __imp__access:PPROC
vc__access equ <__imp__access>

externdef __imp__acmdln:PPROC
vc__acmdln equ <__imp__acmdln>

externdef __imp__aexit_rtn:PPROC
vc__aexit_rtn equ <__imp__aexit_rtn>

externdef __imp__aligned_free:PPROC
vc__aligned_free equ <__imp__aligned_free>

externdef __imp__aligned_malloc:PPROC
vc__aligned_malloc equ <__imp__aligned_malloc>

externdef __imp__aligned_offset_malloc:PPROC
vc__aligned_offset_malloc equ <__imp__aligned_offset_malloc>

externdef __imp__aligned_offset_realloc:PPROC
vc__aligned_offset_realloc equ <__imp__aligned_offset_realloc>

externdef __imp__aligned_realloc:PPROC
vc__aligned_realloc equ <__imp__aligned_realloc>

externdef __imp__amsg_exit:PPROC
vc__amsg_exit equ <__imp__amsg_exit>

externdef __imp__assert:PPROC
vc__assert equ <__imp__assert>

externdef __imp__atodbl:PPROC
vc__atodbl equ <__imp__atodbl>

externdef __imp__atoi64:PPROC
vc__atoi64 equ <__imp__atoi64>

externdef __imp__atoldbl:PPROC
vc__atoldbl equ <__imp__atoldbl>

externdef __imp__beep:PPROC
vc__beep equ <__imp__beep>

externdef __imp__beginthread:PPROC
vc__beginthread equ <__imp__beginthread>

externdef __imp__beginthreadex:PPROC
vc__beginthreadex equ <__imp__beginthreadex>

externdef __imp__c_exit:PPROC
vc__c_exit equ <__imp__c_exit>

externdef __imp__cabs:PPROC
vc__cabs equ <__imp__cabs>

externdef __imp__callnewh:PPROC
vc__callnewh equ <__imp__callnewh>

externdef __imp__cexit:PPROC
vc__cexit equ <__imp__cexit>

externdef __imp__cgets:PPROC
vc__cgets equ <__imp__cgets>

externdef __imp__cgetws:PPROC
vc__cgetws equ <__imp__cgetws>

externdef __imp__chdir:PPROC
vc__chdir equ <__imp__chdir>

externdef __imp__chdrive:PPROC
vc__chdrive equ <__imp__chdrive>

externdef __imp__chgsign:PPROC
vc__chgsign equ <__imp__chgsign>

externdef __imp__chgsignf:PPROC
vc__chgsignf equ <__imp__chgsignf>

externdef __imp__chmod:PPROC
vc__chmod equ <__imp__chmod>

externdef __imp__chsize:PPROC
vc__chsize equ <__imp__chsize>

externdef __imp__clearfp:PPROC
vc__clearfp equ <__imp__clearfp>

externdef __imp__close:PPROC
vc__close equ <__imp__close>

externdef __imp__commit:PPROC
vc__commit equ <__imp__commit>

externdef __imp__commode:PPROC
vc__commode equ <__imp__commode>

externdef __imp__control87:PPROC
vc__control87 equ <__imp__control87>

externdef __imp__controlfp:PPROC
vc__controlfp equ <__imp__controlfp>

externdef __imp__copysign:PPROC
vc__copysign equ <__imp__copysign>

externdef __imp__copysignf:PPROC
vc__copysignf equ <__imp__copysignf>

externdef __imp__cprintf:PPROC
vc__cprintf equ <__imp__cprintf>

externdef __imp__cputs:PPROC
vc__cputs equ <__imp__cputs>

externdef __imp__cputws:PPROC
vc__cputws equ <__imp__cputws>

externdef __imp__creat:PPROC
vc__creat equ <__imp__creat>

externdef __imp__cscanf:PPROC
vc__cscanf equ <__imp__cscanf>

externdef __imp__ctime64:PPROC
vc__ctime64 equ <__imp__ctime64>

externdef __imp__ctype:PPROC
vc__ctype equ <__imp__ctype>

externdef __imp__cwait:PPROC
vc__cwait equ <__imp__cwait>

externdef __imp__cwprintf:PPROC
vc__cwprintf equ <__imp__cwprintf>

externdef __imp__cwscanf:PPROC
vc__cwscanf equ <__imp__cwscanf>

externdef __imp__daylight:PPROC
vc__daylight equ <__imp__daylight>

externdef __imp__dstbias:PPROC
vc__dstbias equ <__imp__dstbias>

externdef __imp__dup2:PPROC
vc__dup2 equ <__imp__dup2>

externdef __imp__dup:PPROC
vc__dup equ <__imp__dup>

externdef __imp__ecvt:PPROC
vc__ecvt equ <__imp__ecvt>

externdef __imp__endthread:PPROC
vc__endthread equ <__imp__endthread>

externdef __imp__endthreadex:PPROC
vc__endthreadex equ <__imp__endthreadex>

externdef __imp__environ:PPROC
vc__environ equ <__imp__environ>

externdef __imp__eof:PPROC
vc__eof equ <__imp__eof>

externdef __imp__errno:PPROC
vc__errno equ <__imp__errno>

externdef __imp__execl:PPROC
vc__execl equ <__imp__execl>

externdef __imp__execle:PPROC
vc__execle equ <__imp__execle>

externdef __imp__execlp:PPROC
vc__execlp equ <__imp__execlp>

externdef __imp__execlpe:PPROC
vc__execlpe equ <__imp__execlpe>

externdef __imp__execv:PPROC
vc__execv equ <__imp__execv>

externdef __imp__execve:PPROC
vc__execve equ <__imp__execve>

externdef __imp__execvp:PPROC
vc__execvp equ <__imp__execvp>

externdef __imp__execvpe:PPROC
vc__execvpe equ <__imp__execvpe>

externdef __imp__exit:PPROC
vc__exit equ <__imp__exit>

externdef __imp__expand:PPROC
vc__expand equ <__imp__expand>

externdef __imp__fcloseall:PPROC
vc__fcloseall equ <__imp__fcloseall>

externdef __imp__fcvt:PPROC
vc__fcvt equ <__imp__fcvt>

externdef __imp__fdopen:PPROC
vc__fdopen equ <__imp__fdopen>

externdef __imp__fgetchar:PPROC
vc__fgetchar equ <__imp__fgetchar>

externdef __imp__fgetwchar:PPROC
vc__fgetwchar equ <__imp__fgetwchar>

externdef __imp__filbuf:PPROC
vc__filbuf equ <__imp__filbuf>

externdef __imp__fileinfo:PPROC
vc__fileinfo equ <__imp__fileinfo>

externdef __imp__filelength:PPROC
vc__filelength equ <__imp__filelength>

externdef __imp__filelengthi64:PPROC
vc__filelengthi64 equ <__imp__filelengthi64>

externdef __imp__fileno:PPROC
vc__fileno equ <__imp__fileno>

externdef __imp__findclose:PPROC
vc__findclose equ <__imp__findclose>

externdef __imp__findfirst64:PPROC
vc__findfirst64 equ <__imp__findfirst64>

externdef __imp__findfirst:PPROC
vc__findfirst equ <__imp__findfirst>

externdef __imp__findfirsti64:PPROC
vc__findfirsti64 equ <__imp__findfirsti64>

externdef __imp__findnext64:PPROC
vc__findnext64 equ <__imp__findnext64>

externdef __imp__findnext:PPROC
vc__findnext equ <__imp__findnext>

externdef __imp__findnexti64:PPROC
vc__findnexti64 equ <__imp__findnexti64>

externdef __imp__finite:PPROC
vc__finite equ <__imp__finite>

externdef __imp__finitef:PPROC
vc__finitef equ <__imp__finitef>

externdef __imp__flsbuf:PPROC
vc__flsbuf equ <__imp__flsbuf>

externdef __imp__flushall:PPROC
vc__flushall equ <__imp__flushall>

externdef __imp__fmode:PPROC
vc__fmode equ <__imp__fmode>

externdef __imp__fpclass:PPROC
vc__fpclass equ <__imp__fpclass>

externdef __imp__fpclassf:PPROC
vc__fpclassf equ <__imp__fpclassf>

externdef __imp__fpreset:PPROC
vc__fpreset equ <__imp__fpreset>

externdef __imp__fputchar:PPROC
vc__fputchar equ <__imp__fputchar>

externdef __imp__fputwchar:PPROC
vc__fputwchar equ <__imp__fputwchar>

externdef __imp__fsopen:PPROC
vc__fsopen equ <__imp__fsopen>

externdef __imp__fstat64:PPROC
vc__fstat64 equ <__imp__fstat64>

externdef __imp__fstat:PPROC
vc__fstat equ <__imp__fstat>

externdef __imp__fstati64:PPROC
vc__fstati64 equ <__imp__fstati64>

externdef __imp__ftime64:PPROC
vc__ftime64 equ <__imp__ftime64>

externdef __imp__ftime:PPROC
vc__ftime equ <__imp__ftime>

externdef __imp__fullpath:PPROC
vc__fullpath equ <__imp__fullpath>

externdef __imp__futime64:PPROC
vc__futime64 equ <__imp__futime64>

externdef __imp__futime:PPROC
vc__futime equ <__imp__futime>

externdef __imp__gcvt:PPROC
vc__gcvt equ <__imp__gcvt>

externdef __imp__get_heap_handle:PPROC
vc__get_heap_handle equ <__imp__get_heap_handle>

externdef __imp__get_osfhandle:PPROC
vc__get_osfhandle equ <__imp__get_osfhandle>

externdef __imp__get_sbh_threshold:PPROC
vc__get_sbh_threshold equ <__imp__get_sbh_threshold>

externdef __imp__getch:PPROC
vc__getch equ <__imp__getch>

externdef __imp__getche:PPROC
vc__getche equ <__imp__getche>

externdef __imp__getcwd:PPROC
vc__getcwd equ <__imp__getcwd>

externdef __imp__getdcwd:PPROC
vc__getdcwd equ <__imp__getdcwd>

externdef __imp__getdiskfree:PPROC
vc__getdiskfree equ <__imp__getdiskfree>

externdef __imp__getdllprocaddr:PPROC
vc__getdllprocaddr equ <__imp__getdllprocaddr>

externdef __imp__getdrive:PPROC
vc__getdrive equ <__imp__getdrive>

externdef __imp__getdrives:PPROC
vc__getdrives equ <__imp__getdrives>

externdef __imp__getmaxstdio:PPROC
vc__getmaxstdio equ <__imp__getmaxstdio>

externdef __imp__getmbcp:PPROC
vc__getmbcp equ <__imp__getmbcp>

externdef __imp__getpid:PPROC
vc__getpid equ <__imp__getpid>

externdef __imp__getsystime:PPROC
vc__getsystime equ <__imp__getsystime>

externdef __imp__getw:PPROC
vc__getw equ <__imp__getw>

externdef __imp__getwch:PPROC
vc__getwch equ <__imp__getwch>

externdef __imp__getwche:PPROC
vc__getwche equ <__imp__getwche>

externdef __imp__getws:PPROC
vc__getws equ <__imp__getws>

externdef __imp__gmtime64:PPROC
vc__gmtime64 equ <__imp__gmtime64>

externdef __imp__heapadd:PPROC
vc__heapadd equ <__imp__heapadd>

externdef __imp__heapchk:PPROC
vc__heapchk equ <__imp__heapchk>

externdef __imp__heapmin:PPROC
vc__heapmin equ <__imp__heapmin>

externdef __imp__heapset:PPROC
vc__heapset equ <__imp__heapset>

externdef __imp__heapused:PPROC
vc__heapused equ <__imp__heapused>

externdef __imp__heapwalk:PPROC
vc__heapwalk equ <__imp__heapwalk>

externdef __imp__hypot:PPROC
vc__hypot equ <__imp__hypot>

externdef __imp__hypotf:PPROC
vc__hypotf equ <__imp__hypotf>

externdef __imp__i64toa:PPROC
vc__i64toa equ <__imp__i64toa>

externdef __imp__i64tow:PPROC
vc__i64tow equ <__imp__i64tow>

externdef __imp__initterm:PPROC
vc__initterm equ <__imp__initterm>

externdef __imp__iob:PPROC
vc__iob equ <__imp__iob>

externdef __imp__isatty:PPROC
vc__isatty equ <__imp__isatty>

externdef __imp__isctype:PPROC
vc__isctype equ <__imp__isctype>

externdef __imp__ismbbalnum:PPROC
vc__ismbbalnum equ <__imp__ismbbalnum>

externdef __imp__ismbbalpha:PPROC
vc__ismbbalpha equ <__imp__ismbbalpha>

externdef __imp__ismbbgraph:PPROC
vc__ismbbgraph equ <__imp__ismbbgraph>

externdef __imp__ismbbkalnum:PPROC
vc__ismbbkalnum equ <__imp__ismbbkalnum>

externdef __imp__ismbbkana:PPROC
vc__ismbbkana equ <__imp__ismbbkana>

externdef __imp__ismbbkprint:PPROC
vc__ismbbkprint equ <__imp__ismbbkprint>

externdef __imp__ismbbkpunct:PPROC
vc__ismbbkpunct equ <__imp__ismbbkpunct>

externdef __imp__ismbblead:PPROC
vc__ismbblead equ <__imp__ismbblead>

externdef __imp__ismbbprint:PPROC
vc__ismbbprint equ <__imp__ismbbprint>

externdef __imp__ismbbpunct:PPROC
vc__ismbbpunct equ <__imp__ismbbpunct>

externdef __imp__ismbbtrail:PPROC
vc__ismbbtrail equ <__imp__ismbbtrail>

externdef __imp__ismbcalnum:PPROC
vc__ismbcalnum equ <__imp__ismbcalnum>

externdef __imp__ismbcalpha:PPROC
vc__ismbcalpha equ <__imp__ismbcalpha>

externdef __imp__ismbcdigit:PPROC
vc__ismbcdigit equ <__imp__ismbcdigit>

externdef __imp__ismbcgraph:PPROC
vc__ismbcgraph equ <__imp__ismbcgraph>

externdef __imp__ismbchira:PPROC
vc__ismbchira equ <__imp__ismbchira>

externdef __imp__ismbckata:PPROC
vc__ismbckata equ <__imp__ismbckata>

externdef __imp__ismbcl0:PPROC
vc__ismbcl0 equ <__imp__ismbcl0>

externdef __imp__ismbcl1:PPROC
vc__ismbcl1 equ <__imp__ismbcl1>

externdef __imp__ismbcl2:PPROC
vc__ismbcl2 equ <__imp__ismbcl2>

externdef __imp__ismbclegal:PPROC
vc__ismbclegal equ <__imp__ismbclegal>

externdef __imp__ismbclower:PPROC
vc__ismbclower equ <__imp__ismbclower>

externdef __imp__ismbcprint:PPROC
vc__ismbcprint equ <__imp__ismbcprint>

externdef __imp__ismbcpunct:PPROC
vc__ismbcpunct equ <__imp__ismbcpunct>

externdef __imp__ismbcspace:PPROC
vc__ismbcspace equ <__imp__ismbcspace>

externdef __imp__ismbcsymbol:PPROC
vc__ismbcsymbol equ <__imp__ismbcsymbol>

externdef __imp__ismbcupper:PPROC
vc__ismbcupper equ <__imp__ismbcupper>

externdef __imp__ismbslead:PPROC
vc__ismbslead equ <__imp__ismbslead>

externdef __imp__ismbstrail:PPROC
vc__ismbstrail equ <__imp__ismbstrail>

externdef __imp__isnan:PPROC
vc__isnan equ <__imp__isnan>

externdef __imp__isnanf:PPROC
vc__isnanf equ <__imp__isnanf>

externdef __imp__itoa:PPROC
vc__itoa equ <__imp__itoa>

externdef __imp__itow:PPROC
vc__itow equ <__imp__itow>

externdef __imp__j0:PPROC
vc__j0 equ <__imp__j0>

externdef __imp__j1:PPROC
vc__j1 equ <__imp__j1>

externdef __imp__jn:PPROC
vc__jn equ <__imp__jn>

externdef __imp__kbhit:PPROC
vc__kbhit equ <__imp__kbhit>

externdef __imp__lfind:PPROC
vc__lfind equ <__imp__lfind>

externdef __imp__loaddll:PPROC
vc__loaddll equ <__imp__loaddll>

externdef __imp__local_unwind:PPROC
vc__local_unwind equ <__imp__local_unwind>

externdef __imp__localtime64:PPROC
vc__localtime64 equ <__imp__localtime64>

externdef __imp__lock:PPROC
vc__lock equ <__imp__lock>

externdef __imp__locking:PPROC
vc__locking equ <__imp__locking>

externdef __imp__logb:PPROC
vc__logb equ <__imp__logb>

externdef __imp__logbf:PPROC
vc__logbf equ <__imp__logbf>

externdef __imp__lrotl:PPROC
vc__lrotl equ <__imp__lrotl>

externdef __imp__lrotr:PPROC
vc__lrotr equ <__imp__lrotr>

externdef __imp__lsearch:PPROC
vc__lsearch equ <__imp__lsearch>

externdef __imp__lseek:PPROC
vc__lseek equ <__imp__lseek>

externdef __imp__lseeki64:PPROC
vc__lseeki64 equ <__imp__lseeki64>

externdef __imp__ltoa:PPROC
vc__ltoa equ <__imp__ltoa>

externdef __imp__ltow:PPROC
vc__ltow equ <__imp__ltow>

externdef __imp__makepath:PPROC
vc__makepath equ <__imp__makepath>

externdef __imp__mbbtombc:PPROC
vc__mbbtombc equ <__imp__mbbtombc>

externdef __imp__mbbtype:PPROC
vc__mbbtype equ <__imp__mbbtype>

externdef __imp__mbcasemap:PPROC
vc__mbcasemap equ <__imp__mbcasemap>

externdef __imp__mbccpy:PPROC
vc__mbccpy equ <__imp__mbccpy>

externdef __imp__mbcjistojms:PPROC
vc__mbcjistojms equ <__imp__mbcjistojms>

externdef __imp__mbcjmstojis:PPROC
vc__mbcjmstojis equ <__imp__mbcjmstojis>

externdef __imp__mbclen:PPROC
vc__mbclen equ <__imp__mbclen>

externdef __imp__mbctohira:PPROC
vc__mbctohira equ <__imp__mbctohira>

externdef __imp__mbctokata:PPROC
vc__mbctokata equ <__imp__mbctokata>

externdef __imp__mbctolower:PPROC
vc__mbctolower equ <__imp__mbctolower>

externdef __imp__mbctombb:PPROC
vc__mbctombb equ <__imp__mbctombb>

externdef __imp__mbctoupper:PPROC
vc__mbctoupper equ <__imp__mbctoupper>

externdef __imp__mbctype:PPROC
vc__mbctype equ <__imp__mbctype>

externdef __imp__mbsbtype:PPROC
vc__mbsbtype equ <__imp__mbsbtype>

externdef __imp__mbscat:PPROC
vc__mbscat equ <__imp__mbscat>

externdef __imp__mbschr:PPROC
vc__mbschr equ <__imp__mbschr>

externdef __imp__mbscmp:PPROC
vc__mbscmp equ <__imp__mbscmp>

externdef __imp__mbscoll:PPROC
vc__mbscoll equ <__imp__mbscoll>

externdef __imp__mbscpy:PPROC
vc__mbscpy equ <__imp__mbscpy>

externdef __imp__mbscspn:PPROC
vc__mbscspn equ <__imp__mbscspn>

externdef __imp__mbsdec:PPROC
vc__mbsdec equ <__imp__mbsdec>

externdef __imp__mbsdup:PPROC
vc__mbsdup equ <__imp__mbsdup>

externdef __imp__mbsicmp:PPROC
vc__mbsicmp equ <__imp__mbsicmp>

externdef __imp__mbsicoll:PPROC
vc__mbsicoll equ <__imp__mbsicoll>

externdef __imp__mbsinc:PPROC
vc__mbsinc equ <__imp__mbsinc>

externdef __imp__mbslen:PPROC
vc__mbslen equ <__imp__mbslen>

externdef __imp__mbslwr:PPROC
vc__mbslwr equ <__imp__mbslwr>

externdef __imp__mbsnbcat:PPROC
vc__mbsnbcat equ <__imp__mbsnbcat>

externdef __imp__mbsnbcmp:PPROC
vc__mbsnbcmp equ <__imp__mbsnbcmp>

externdef __imp__mbsnbcnt:PPROC
vc__mbsnbcnt equ <__imp__mbsnbcnt>

externdef __imp__mbsnbcoll:PPROC
vc__mbsnbcoll equ <__imp__mbsnbcoll>

externdef __imp__mbsnbcpy:PPROC
vc__mbsnbcpy equ <__imp__mbsnbcpy>

externdef __imp__mbsnbicmp:PPROC
vc__mbsnbicmp equ <__imp__mbsnbicmp>

externdef __imp__mbsnbicoll:PPROC
vc__mbsnbicoll equ <__imp__mbsnbicoll>

externdef __imp__mbsnbset:PPROC
vc__mbsnbset equ <__imp__mbsnbset>

externdef __imp__mbsncat:PPROC
vc__mbsncat equ <__imp__mbsncat>

externdef __imp__mbsnccnt:PPROC
vc__mbsnccnt equ <__imp__mbsnccnt>

externdef __imp__mbsncmp:PPROC
vc__mbsncmp equ <__imp__mbsncmp>

externdef __imp__mbsncoll:PPROC
vc__mbsncoll equ <__imp__mbsncoll>

externdef __imp__mbsncpy:PPROC
vc__mbsncpy equ <__imp__mbsncpy>

externdef __imp__mbsnextc:PPROC
vc__mbsnextc equ <__imp__mbsnextc>

externdef __imp__mbsnicmp:PPROC
vc__mbsnicmp equ <__imp__mbsnicmp>

externdef __imp__mbsnicoll:PPROC
vc__mbsnicoll equ <__imp__mbsnicoll>

externdef __imp__mbsninc:PPROC
vc__mbsninc equ <__imp__mbsninc>

externdef __imp__mbsnset:PPROC
vc__mbsnset equ <__imp__mbsnset>

externdef __imp__mbspbrk:PPROC
vc__mbspbrk equ <__imp__mbspbrk>

externdef __imp__mbsrchr:PPROC
vc__mbsrchr equ <__imp__mbsrchr>

externdef __imp__mbsrev:PPROC
vc__mbsrev equ <__imp__mbsrev>

externdef __imp__mbsset:PPROC
vc__mbsset equ <__imp__mbsset>

externdef __imp__mbsspn:PPROC
vc__mbsspn equ <__imp__mbsspn>

externdef __imp__mbsspnp:PPROC
vc__mbsspnp equ <__imp__mbsspnp>

externdef __imp__mbsstr:PPROC
vc__mbsstr equ <__imp__mbsstr>

externdef __imp__mbstok:PPROC
vc__mbstok equ <__imp__mbstok>

externdef __imp__mbstrlen:PPROC
vc__mbstrlen equ <__imp__mbstrlen>

externdef __imp__mbsupr:PPROC
vc__mbsupr equ <__imp__mbsupr>

externdef __imp__memccpy:PPROC
vc__memccpy equ <__imp__memccpy>

externdef __imp__memicmp:PPROC
vc__memicmp equ <__imp__memicmp>

externdef __imp__mkdir:PPROC
vc__mkdir equ <__imp__mkdir>

externdef __imp__mkgmtime64:PPROC
vc__mkgmtime64 equ <__imp__mkgmtime64>

externdef __imp__mkgmtime:PPROC
vc__mkgmtime equ <__imp__mkgmtime>

externdef __imp__mktemp:PPROC
vc__mktemp equ <__imp__mktemp>

externdef __imp__mktime64:PPROC
vc__mktime64 equ <__imp__mktime64>

externdef __imp__msize:PPROC
vc__msize equ <__imp__msize>

externdef __imp__nextafter:PPROC
vc__nextafter equ <__imp__nextafter>

externdef __imp__nextafterf:PPROC
vc__nextafterf equ <__imp__nextafterf>

externdef __imp__onexit:PPROC
vc__onexit equ <__imp__onexit>

externdef __imp__open:PPROC
vc__open equ <__imp__open>

externdef __imp__open_osfhandle:PPROC
vc__open_osfhandle equ <__imp__open_osfhandle>

externdef __imp__osplatform:PPROC
vc__osplatform equ <__imp__osplatform>

externdef __imp__osver:PPROC
vc__osver equ <__imp__osver>

externdef __imp__pclose:PPROC
vc__pclose equ <__imp__pclose>

externdef __imp__pctype:PPROC
vc__pctype equ <__imp__pctype>

externdef __imp__pgmptr:PPROC
vc__pgmptr equ <__imp__pgmptr>

externdef __imp__pipe:PPROC
vc__pipe equ <__imp__pipe>

externdef __imp__popen:PPROC
vc__popen equ <__imp__popen>

externdef __imp__purecall:PPROC
vc__purecall equ <__imp__purecall>

externdef __imp__putch:PPROC
vc__putch equ <__imp__putch>

externdef __imp__putenv:PPROC
vc__putenv equ <__imp__putenv>

externdef __imp__putw:PPROC
vc__putw equ <__imp__putw>

externdef __imp__putwch:PPROC
vc__putwch equ <__imp__putwch>

externdef __imp__putws:PPROC
vc__putws equ <__imp__putws>

externdef __imp__pwctype:PPROC
vc__pwctype equ <__imp__pwctype>

externdef __imp__read:PPROC
vc__read equ <__imp__read>

externdef __imp__resetstkoflw:PPROC
vc__resetstkoflw equ <__imp__resetstkoflw>

externdef __imp__rmdir:PPROC
vc__rmdir equ <__imp__rmdir>

externdef __imp__rmtmp:PPROC
vc__rmtmp equ <__imp__rmtmp>

externdef __imp__rotl64:PPROC
vc__rotl64 equ <__imp__rotl64>

externdef __imp__rotl:PPROC
vc__rotl equ <__imp__rotl>

externdef __imp__rotr64:PPROC
vc__rotr64 equ <__imp__rotr64>

externdef __imp__rotr:PPROC
vc__rotr equ <__imp__rotr>

externdef __imp__scalb:PPROC
vc__scalb equ <__imp__scalb>

externdef __imp__scalbf:PPROC
vc__scalbf equ <__imp__scalbf>

externdef __imp__scprintf:PPROC
vc__scprintf equ <__imp__scprintf>

externdef __imp__scwprintf:PPROC
vc__scwprintf equ <__imp__scwprintf>

externdef __imp__searchenv:PPROC
vc__searchenv equ <__imp__searchenv>

externdef __imp__set_error_mode:PPROC
vc__set_error_mode equ <__imp__set_error_mode>

externdef __imp__set_sbh_threshold:PPROC
vc__set_sbh_threshold equ <__imp__set_sbh_threshold>

externdef __imp__seterrormode:PPROC
vc__seterrormode equ <__imp__seterrormode>

externdef __imp__setjmp:PPROC
vc__setjmp equ <__imp__setjmp>

externdef __imp__setjmpex:PPROC
vc__setjmpex equ <__imp__setjmpex>

externdef __imp__setmaxstdio:PPROC
vc__setmaxstdio equ <__imp__setmaxstdio>

externdef __imp__setmbcp:PPROC
vc__setmbcp equ <__imp__setmbcp>

externdef __imp__setmode:PPROC
vc__setmode equ <__imp__setmode>

externdef __imp__setsystime:PPROC
vc__setsystime equ <__imp__setsystime>

externdef __imp__sleep:PPROC
vc__sleep equ <__imp__sleep>

externdef __imp__snprintf:PPROC
vc__snprintf equ <__imp__snprintf>

externdef __imp__snscanf:PPROC
vc__snscanf equ <__imp__snscanf>

externdef __imp__snwprintf:PPROC
vc__snwprintf equ <__imp__snwprintf>

externdef __imp__snwscanf:PPROC
vc__snwscanf equ <__imp__snwscanf>

externdef __imp__sopen:PPROC
vc__sopen equ <__imp__sopen>

externdef __imp__spawnl:PPROC
vc__spawnl equ <__imp__spawnl>

externdef __imp__spawnle:PPROC
vc__spawnle equ <__imp__spawnle>

externdef __imp__spawnlp:PPROC
vc__spawnlp equ <__imp__spawnlp>

externdef __imp__spawnlpe:PPROC
vc__spawnlpe equ <__imp__spawnlpe>

externdef __imp__spawnv:PPROC
vc__spawnv equ <__imp__spawnv>

externdef __imp__spawnve:PPROC
vc__spawnve equ <__imp__spawnve>

externdef __imp__spawnvp:PPROC
vc__spawnvp equ <__imp__spawnvp>

externdef __imp__spawnvpe:PPROC
vc__spawnvpe equ <__imp__spawnvpe>

externdef __imp__splitpath:PPROC
vc__splitpath equ <__imp__splitpath>

externdef __imp__stat64:PPROC
vc__stat64 equ <__imp__stat64>

externdef __imp__stat:PPROC
vc__stat equ <__imp__stat>

externdef __imp__stati64:PPROC
vc__stati64 equ <__imp__stati64>

externdef __imp__statusfp:PPROC
vc__statusfp equ <__imp__statusfp>

externdef __imp__strcmpi:PPROC
vc__strcmpi equ <__imp__strcmpi>

externdef __imp__strdate:PPROC
vc__strdate equ <__imp__strdate>

externdef __imp__strdup:PPROC
vc__strdup equ <__imp__strdup>

externdef __imp__strerror:PPROC
vc__strerror equ <__imp__strerror>

externdef __imp__stricmp:PPROC
vc__stricmp equ <__imp__stricmp>

externdef __imp__stricoll:PPROC
vc__stricoll equ <__imp__stricoll>

externdef __imp__strlwr:PPROC
vc__strlwr equ <__imp__strlwr>

externdef __imp__strncoll:PPROC
vc__strncoll equ <__imp__strncoll>

externdef __imp__strnicmp:PPROC
vc__strnicmp equ <__imp__strnicmp>

externdef __imp__strnicoll:PPROC
vc__strnicoll equ <__imp__strnicoll>

externdef __imp__strnset:PPROC
vc__strnset equ <__imp__strnset>

externdef __imp__strrev:PPROC
vc__strrev equ <__imp__strrev>

externdef __imp__strset:PPROC
vc__strset equ <__imp__strset>

externdef __imp__strtime:PPROC
vc__strtime equ <__imp__strtime>

externdef __imp__strtoi64:PPROC
vc__strtoi64 equ <__imp__strtoi64>

externdef __imp__strtoui64:PPROC
vc__strtoui64 equ <__imp__strtoui64>

externdef __imp__strupr:PPROC
vc__strupr equ <__imp__strupr>

externdef __imp__swab:PPROC
vc__swab equ <__imp__swab>

externdef __imp__sys_errlist:PPROC
vc__sys_errlist equ <__imp__sys_errlist>

externdef __imp__sys_nerr:PPROC
vc__sys_nerr equ <__imp__sys_nerr>

externdef __imp__tell:PPROC
vc__tell equ <__imp__tell>

externdef __imp__telli64:PPROC
vc__telli64 equ <__imp__telli64>

externdef __imp__tempnam:PPROC
vc__tempnam equ <__imp__tempnam>

externdef __imp__time64:PPROC
vc__time64 equ <__imp__time64>

externdef __imp__timezone:PPROC
vc__timezone equ <__imp__timezone>

externdef __imp__tolower:PPROC
vc__tolower equ <__imp__tolower>

externdef __imp__toupper:PPROC
vc__toupper equ <__imp__toupper>

externdef __imp__tzname:PPROC
vc__tzname equ <__imp__tzname>

externdef __imp__tzset:PPROC
vc__tzset equ <__imp__tzset>

externdef __imp__ui64toa:PPROC
vc__ui64toa equ <__imp__ui64toa>

externdef __imp__ui64tow:PPROC
vc__ui64tow equ <__imp__ui64tow>

externdef __imp__ultoa:PPROC
vc__ultoa equ <__imp__ultoa>

externdef __imp__ultow:PPROC
vc__ultow equ <__imp__ultow>

externdef __imp__umask:PPROC
vc__umask equ <__imp__umask>

externdef __imp__ungetch:PPROC
vc__ungetch equ <__imp__ungetch>

externdef __imp__ungetwch:PPROC
vc__ungetwch equ <__imp__ungetwch>

externdef __imp__unlink:PPROC
vc__unlink equ <__imp__unlink>

externdef __imp__unloaddll:PPROC
vc__unloaddll equ <__imp__unloaddll>

externdef __imp__unlock:PPROC
vc__unlock equ <__imp__unlock>

externdef __imp__utime64:PPROC
vc__utime64 equ <__imp__utime64>

externdef __imp__utime:PPROC
vc__utime equ <__imp__utime>

externdef __imp__vscprintf:PPROC
vc__vscprintf equ <__imp__vscprintf>

externdef __imp__vscwprintf:PPROC
vc__vscwprintf equ <__imp__vscwprintf>

externdef __imp__vsnprintf:PPROC
vc__vsnprintf equ <__imp__vsnprintf>

externdef __imp__vsnwprintf:PPROC
vc__vsnwprintf equ <__imp__vsnwprintf>

externdef __imp__waccess:PPROC
vc__waccess equ <__imp__waccess>

externdef __imp__wasctime:PPROC
vc__wasctime equ <__imp__wasctime>

externdef __imp__wchdir:PPROC
vc__wchdir equ <__imp__wchdir>

externdef __imp__wchmod:PPROC
vc__wchmod equ <__imp__wchmod>

externdef __imp__wcmdln:PPROC
vc__wcmdln equ <__imp__wcmdln>

externdef __imp__wcreat:PPROC
vc__wcreat equ <__imp__wcreat>

externdef __imp__wcsdup:PPROC
vc__wcsdup equ <__imp__wcsdup>

externdef __imp__wcserror:PPROC
vc__wcserror equ <__imp__wcserror>

externdef __imp__wcsicmp:PPROC
vc__wcsicmp equ <__imp__wcsicmp>

externdef __imp__wcsicoll:PPROC
vc__wcsicoll equ <__imp__wcsicoll>

externdef __imp__wcslwr:PPROC
vc__wcslwr equ <__imp__wcslwr>

externdef __imp__wcsncoll:PPROC
vc__wcsncoll equ <__imp__wcsncoll>

externdef __imp__wcsnicmp:PPROC
vc__wcsnicmp equ <__imp__wcsnicmp>

externdef __imp__wcsnicoll:PPROC
vc__wcsnicoll equ <__imp__wcsnicoll>

externdef __imp__wcsnset:PPROC
vc__wcsnset equ <__imp__wcsnset>

externdef __imp__wcsrev:PPROC
vc__wcsrev equ <__imp__wcsrev>

externdef __imp__wcsset:PPROC
vc__wcsset equ <__imp__wcsset>

externdef __imp__wcstoi64:PPROC
vc__wcstoi64 equ <__imp__wcstoi64>

externdef __imp__wcstoui64:PPROC
vc__wcstoui64 equ <__imp__wcstoui64>

externdef __imp__wcsupr:PPROC
vc__wcsupr equ <__imp__wcsupr>

externdef __imp__wctime64:PPROC
vc__wctime64 equ <__imp__wctime64>

externdef __imp__wctime:PPROC
vc__wctime equ <__imp__wctime>

externdef __imp__wctype:PPROC
vc__wctype equ <__imp__wctype>

externdef __imp__wenviron:PPROC
vc__wenviron equ <__imp__wenviron>

externdef __imp__wexecl:PPROC
vc__wexecl equ <__imp__wexecl>

externdef __imp__wexecle:PPROC
vc__wexecle equ <__imp__wexecle>

externdef __imp__wexeclp:PPROC
vc__wexeclp equ <__imp__wexeclp>

externdef __imp__wexeclpe:PPROC
vc__wexeclpe equ <__imp__wexeclpe>

externdef __imp__wexecv:PPROC
vc__wexecv equ <__imp__wexecv>

externdef __imp__wexecve:PPROC
vc__wexecve equ <__imp__wexecve>

externdef __imp__wexecvp:PPROC
vc__wexecvp equ <__imp__wexecvp>

externdef __imp__wexecvpe:PPROC
vc__wexecvpe equ <__imp__wexecvpe>

externdef __imp__wfdopen:PPROC
vc__wfdopen equ <__imp__wfdopen>

externdef __imp__wfindfirst64:PPROC
vc__wfindfirst64 equ <__imp__wfindfirst64>

externdef __imp__wfindfirst:PPROC
vc__wfindfirst equ <__imp__wfindfirst>

externdef __imp__wfindfirsti64:PPROC
vc__wfindfirsti64 equ <__imp__wfindfirsti64>

externdef __imp__wfindnext64:PPROC
vc__wfindnext64 equ <__imp__wfindnext64>

externdef __imp__wfindnext:PPROC
vc__wfindnext equ <__imp__wfindnext>

externdef __imp__wfindnexti64:PPROC
vc__wfindnexti64 equ <__imp__wfindnexti64>

externdef __imp__wfopen:PPROC
vc__wfopen equ <__imp__wfopen>

externdef __imp__wfreopen:PPROC
vc__wfreopen equ <__imp__wfreopen>

externdef __imp__wfsopen:PPROC
vc__wfsopen equ <__imp__wfsopen>

externdef __imp__wfullpath:PPROC
vc__wfullpath equ <__imp__wfullpath>

externdef __imp__wgetcwd:PPROC
vc__wgetcwd equ <__imp__wgetcwd>

externdef __imp__wgetdcwd:PPROC
vc__wgetdcwd equ <__imp__wgetdcwd>

externdef __imp__wgetenv:PPROC
vc__wgetenv equ <__imp__wgetenv>

externdef __imp__winmajor:PPROC
vc__winmajor equ <__imp__winmajor>

externdef __imp__winminor:PPROC
vc__winminor equ <__imp__winminor>

externdef __imp__winver:PPROC
vc__winver equ <__imp__winver>

externdef __imp__wmakepath:PPROC
vc__wmakepath equ <__imp__wmakepath>

externdef __imp__wmkdir:PPROC
vc__wmkdir equ <__imp__wmkdir>

externdef __imp__wmktemp:PPROC
vc__wmktemp equ <__imp__wmktemp>

externdef __imp__wopen:PPROC
vc__wopen equ <__imp__wopen>

externdef __imp__wperror:PPROC
vc__wperror equ <__imp__wperror>

externdef __imp__wpgmptr:PPROC
vc__wpgmptr equ <__imp__wpgmptr>

externdef __imp__wpopen:PPROC
vc__wpopen equ <__imp__wpopen>

externdef __imp__wputenv:PPROC
vc__wputenv equ <__imp__wputenv>

externdef __imp__wremove:PPROC
vc__wremove equ <__imp__wremove>

externdef __imp__wrename:PPROC
vc__wrename equ <__imp__wrename>

externdef __imp__write:PPROC
vc__write equ <__imp__write>

externdef __imp__wrmdir:PPROC
vc__wrmdir equ <__imp__wrmdir>

externdef __imp__wsearchenv:PPROC
vc__wsearchenv equ <__imp__wsearchenv>

externdef __imp__wsetlocale:PPROC
vc__wsetlocale equ <__imp__wsetlocale>

externdef __imp__wsopen:PPROC
vc__wsopen equ <__imp__wsopen>

externdef __imp__wspawnl:PPROC
vc__wspawnl equ <__imp__wspawnl>

externdef __imp__wspawnle:PPROC
vc__wspawnle equ <__imp__wspawnle>

externdef __imp__wspawnlp:PPROC
vc__wspawnlp equ <__imp__wspawnlp>

externdef __imp__wspawnlpe:PPROC
vc__wspawnlpe equ <__imp__wspawnlpe>

externdef __imp__wspawnv:PPROC
vc__wspawnv equ <__imp__wspawnv>

externdef __imp__wspawnve:PPROC
vc__wspawnve equ <__imp__wspawnve>

externdef __imp__wspawnvp:PPROC
vc__wspawnvp equ <__imp__wspawnvp>

externdef __imp__wspawnvpe:PPROC
vc__wspawnvpe equ <__imp__wspawnvpe>

externdef __imp__wsplitpath:PPROC
vc__wsplitpath equ <__imp__wsplitpath>

externdef __imp__wstat64:PPROC
vc__wstat64 equ <__imp__wstat64>

externdef __imp__wstat:PPROC
vc__wstat equ <__imp__wstat>

externdef __imp__wstati64:PPROC
vc__wstati64 equ <__imp__wstati64>

externdef __imp__wstrdate:PPROC
vc__wstrdate equ <__imp__wstrdate>

externdef __imp__wstrtime:PPROC
vc__wstrtime equ <__imp__wstrtime>

externdef __imp__wsystem:PPROC
vc__wsystem equ <__imp__wsystem>

externdef __imp__wtempnam:PPROC
vc__wtempnam equ <__imp__wtempnam>

externdef __imp__wtmpnam:PPROC
vc__wtmpnam equ <__imp__wtmpnam>

externdef __imp__wtof:PPROC
vc__wtof equ <__imp__wtof>

externdef __imp__wtoi64:PPROC
vc__wtoi64 equ <__imp__wtoi64>

externdef __imp__wtoi:PPROC
vc__wtoi equ <__imp__wtoi>

externdef __imp__wtol:PPROC
vc__wtol equ <__imp__wtol>

externdef __imp__wunlink:PPROC
vc__wunlink equ <__imp__wunlink>

externdef __imp__wutime64:PPROC
vc__wutime64 equ <__imp__wutime64>

externdef __imp__wutime:PPROC
vc__wutime equ <__imp__wutime>

externdef __imp__y0:PPROC
vc__y0 equ <__imp__y0>

externdef __imp__y1:PPROC
vc__y1 equ <__imp__y1>

externdef __imp__yn:PPROC
vc__yn equ <__imp__yn>

externdef __imp_abort:PPROC
vc_abort equ <__imp_abort>

externdef __imp_abs:PPROC
vc_abs equ <__imp_abs>

externdef __imp_acos:PPROC
vc_acos equ <__imp_acos>

externdef __imp_acosf:PPROC
vc_acosf equ <__imp_acosf>

externdef __imp_asctime:PPROC
vc_asctime equ <__imp_asctime>

externdef __imp_asin:PPROC
vc_asin equ <__imp_asin>

externdef __imp_asinf:PPROC
vc_asinf equ <__imp_asinf>

externdef __imp_atan2:PPROC
vc_atan2 equ <__imp_atan2>

externdef __imp_atan2f:PPROC
vc_atan2f equ <__imp_atan2f>

externdef __imp_atan:PPROC
vc_atan equ <__imp_atan>

externdef __imp_atanf:PPROC
vc_atanf equ <__imp_atanf>

externdef __imp_atexit:PPROC
vc_atexit equ <__imp_atexit>

externdef __imp_atof:PPROC
vc_atof equ <__imp_atof>

externdef __imp_atoi:PPROC
vc_atoi equ <__imp_atoi>

externdef __imp_atol:PPROC
vc_atol equ <__imp_atol>

externdef __imp_bsearch:PPROC
vc_bsearch equ <__imp_bsearch>

externdef __imp_calloc:PPROC
vc_calloc equ <__imp_calloc>

externdef __imp_ceil:PPROC
vc_ceil equ <__imp_ceil>

externdef __imp_ceilf:PPROC
vc_ceilf equ <__imp_ceilf>

externdef __imp_clearerr:PPROC
vc_clearerr equ <__imp_clearerr>

externdef __imp_clock:PPROC
vc_clock equ <__imp_clock>

externdef __imp_cos:PPROC
vc_cos equ <__imp_cos>

externdef __imp_cosf:PPROC
vc_cosf equ <__imp_cosf>

externdef __imp_cosh:PPROC
vc_cosh equ <__imp_cosh>

externdef __imp_coshf:PPROC
vc_coshf equ <__imp_coshf>

externdef __imp_ctime:PPROC
vc_ctime equ <__imp_ctime>

externdef __imp_difftime:PPROC
vc_difftime equ <__imp_difftime>

externdef __imp_div:PPROC
vc_div equ <__imp_div>

externdef __imp_exit:PPROC
vc_exit equ <__imp_exit>

externdef __imp_exp:PPROC
vc_exp equ <__imp_exp>

externdef __imp_expf:PPROC
vc_expf equ <__imp_expf>

externdef __imp_fabs:PPROC
vc_fabs equ <__imp_fabs>

externdef __imp_fclose:PPROC
vc_fclose equ <__imp_fclose>

externdef __imp_feof:PPROC
vc_feof equ <__imp_feof>

externdef __imp_ferror:PPROC
vc_ferror equ <__imp_ferror>

externdef __imp_fflush:PPROC
vc_fflush equ <__imp_fflush>

externdef __imp_fgetc:PPROC
vc_fgetc equ <__imp_fgetc>

externdef __imp_fgetpos:PPROC
vc_fgetpos equ <__imp_fgetpos>

externdef __imp_fgets:PPROC
vc_fgets equ <__imp_fgets>

externdef __imp_fgetwc:PPROC
vc_fgetwc equ <__imp_fgetwc>

externdef __imp_fgetws:PPROC
vc_fgetws equ <__imp_fgetws>

externdef __imp_floor:PPROC
vc_floor equ <__imp_floor>

externdef __imp_floorf:PPROC
vc_floorf equ <__imp_floorf>

externdef __imp_fmod:PPROC
vc_fmod equ <__imp_fmod>

externdef __imp_fmodf:PPROC
vc_fmodf equ <__imp_fmodf>

externdef __imp_fopen:PPROC
vc_fopen equ <__imp_fopen>

externdef __imp_fprintf:PPROC
vc_fprintf equ <__imp_fprintf>

externdef __imp_fputc:PPROC
vc_fputc equ <__imp_fputc>

externdef __imp_fputs:PPROC
vc_fputs equ <__imp_fputs>

externdef __imp_fputwc:PPROC
vc_fputwc equ <__imp_fputwc>

externdef __imp_fputws:PPROC
vc_fputws equ <__imp_fputws>

externdef __imp_fread:PPROC
vc_fread equ <__imp_fread>

externdef __imp_free:PPROC
vc_free equ <__imp_free>

externdef __imp_freopen:PPROC
vc_freopen equ <__imp_freopen>

externdef __imp_frexp:PPROC
vc_frexp equ <__imp_frexp>

externdef __imp_fscanf:PPROC
vc_fscanf equ <__imp_fscanf>

externdef __imp_fseek:PPROC
vc_fseek equ <__imp_fseek>

externdef __imp_fsetpos:PPROC
vc_fsetpos equ <__imp_fsetpos>

externdef __imp_ftell:PPROC
vc_ftell equ <__imp_ftell>

externdef __imp_fwprintf:PPROC
vc_fwprintf equ <__imp_fwprintf>

externdef __imp_fwrite:PPROC
vc_fwrite equ <__imp_fwrite>

externdef __imp_fwscanf:PPROC
vc_fwscanf equ <__imp_fwscanf>

externdef __imp_getc:PPROC
vc_getc equ <__imp_getc>

externdef __imp_getchar:PPROC
vc_getchar equ <__imp_getchar>

externdef __imp_getenv:PPROC
vc_getenv equ <__imp_getenv>

externdef __imp_gets:PPROC
vc_gets equ <__imp_gets>

externdef __imp_getwc:PPROC
vc_getwc equ <__imp_getwc>

externdef __imp_getwchar:PPROC
vc_getwchar equ <__imp_getwchar>

externdef __imp_gmtime:PPROC
vc_gmtime equ <__imp_gmtime>

externdef __imp_is_wctype:PPROC
vc_is_wctype equ <__imp_is_wctype>

externdef __imp_isalnum:PPROC
vc_isalnum equ <__imp_isalnum>

externdef __imp_isalpha:PPROC
vc_isalpha equ <__imp_isalpha>

externdef __imp_iscntrl:PPROC
vc_iscntrl equ <__imp_iscntrl>

externdef __imp_isdigit:PPROC
vc_isdigit equ <__imp_isdigit>

externdef __imp_isgraph:PPROC
vc_isgraph equ <__imp_isgraph>

externdef __imp_isleadbyte:PPROC
vc_isleadbyte equ <__imp_isleadbyte>

externdef __imp_islower:PPROC
vc_islower equ <__imp_islower>

externdef __imp_isprint:PPROC
vc_isprint equ <__imp_isprint>

externdef __imp_ispunct:PPROC
vc_ispunct equ <__imp_ispunct>

externdef __imp_isspace:PPROC
vc_isspace equ <__imp_isspace>

externdef __imp_isupper:PPROC
vc_isupper equ <__imp_isupper>

externdef __imp_iswalnum:PPROC
vc_iswalnum equ <__imp_iswalnum>

externdef __imp_iswalpha:PPROC
vc_iswalpha equ <__imp_iswalpha>

externdef __imp_iswascii:PPROC
vc_iswascii equ <__imp_iswascii>

externdef __imp_iswcntrl:PPROC
vc_iswcntrl equ <__imp_iswcntrl>

externdef __imp_iswctype:PPROC
vc_iswctype equ <__imp_iswctype>

externdef __imp_iswdigit:PPROC
vc_iswdigit equ <__imp_iswdigit>

externdef __imp_iswgraph:PPROC
vc_iswgraph equ <__imp_iswgraph>

externdef __imp_iswlower:PPROC
vc_iswlower equ <__imp_iswlower>

externdef __imp_iswprint:PPROC
vc_iswprint equ <__imp_iswprint>

externdef __imp_iswpunct:PPROC
vc_iswpunct equ <__imp_iswpunct>

externdef __imp_iswspace:PPROC
vc_iswspace equ <__imp_iswspace>

externdef __imp_iswupper:PPROC
vc_iswupper equ <__imp_iswupper>

externdef __imp_iswxdigit:PPROC
vc_iswxdigit equ <__imp_iswxdigit>

externdef __imp_isxdigit:PPROC
vc_isxdigit equ <__imp_isxdigit>

externdef __imp_labs:PPROC
vc_labs equ <__imp_labs>

externdef __imp_ldexp:PPROC
vc_ldexp equ <__imp_ldexp>

externdef __imp_ldiv:PPROC
vc_ldiv equ <__imp_ldiv>

externdef __imp_localeconv:PPROC
vc_localeconv equ <__imp_localeconv>

externdef __imp_localtime:PPROC
vc_localtime equ <__imp_localtime>

externdef __imp_log10:PPROC
vc_log10 equ <__imp_log10>

externdef __imp_log10f:PPROC
vc_log10f equ <__imp_log10f>

externdef __imp_log:PPROC
vc_log equ <__imp_log>

externdef __imp_logf:PPROC
vc_logf equ <__imp_logf>

externdef __imp_longjmp:PPROC
vc_longjmp equ <__imp_longjmp>

externdef __imp_malloc:PPROC
vc_malloc equ <__imp_malloc>

externdef __imp_mblen:PPROC
vc_mblen equ <__imp_mblen>

externdef __imp_mbstowcs:PPROC
vc_mbstowcs equ <__imp_mbstowcs>

externdef __imp_mbtowc:PPROC
vc_mbtowc equ <__imp_mbtowc>

externdef __imp_memchr:PPROC
vc_memchr equ <__imp_memchr>

externdef __imp_memcmp:PPROC
vc_memcmp equ <__imp_memcmp>

externdef __imp_memcpy:PPROC
vc_memcpy equ <__imp_memcpy>

externdef __imp_memmove:PPROC
vc_memmove equ <__imp_memmove>

externdef __imp_memset:PPROC
vc_memset equ <__imp_memset>

externdef __imp_mktime:PPROC
vc_mktime equ <__imp_mktime>

externdef __imp_modf:PPROC
vc_modf equ <__imp_modf>

externdef __imp_modff:PPROC
vc_modff equ <__imp_modff>

externdef __imp_perror:PPROC
vc_perror equ <__imp_perror>

externdef __imp_pow:PPROC
vc_pow equ <__imp_pow>

externdef __imp_powf:PPROC
vc_powf equ <__imp_powf>

externdef __imp_printf:PPROC
vc_printf equ <__imp_printf>

externdef __imp_putc:PPROC
vc_putc equ <__imp_putc>

externdef __imp_putchar:PPROC
vc_putchar equ <__imp_putchar>

externdef __imp_puts:PPROC
vc_puts equ <__imp_puts>

externdef __imp_putwc:PPROC
vc_putwc equ <__imp_putwc>

externdef __imp_putwchar:PPROC
vc_putwchar equ <__imp_putwchar>

externdef __imp_qsort:PPROC
vc_qsort equ <__imp_qsort>

externdef __imp_raise:PPROC
vc_raise equ <__imp_raise>

externdef __imp_rand:PPROC
vc_rand equ <__imp_rand>

externdef __imp_realloc:PPROC
vc_realloc equ <__imp_realloc>

externdef __imp_remove:PPROC
vc_remove equ <__imp_remove>

externdef __imp_rename:PPROC
vc_rename equ <__imp_rename>

externdef __imp_rewind:PPROC
vc_rewind equ <__imp_rewind>

externdef __imp_scanf:PPROC
vc_scanf equ <__imp_scanf>

externdef __imp_setbuf:PPROC
vc_setbuf equ <__imp_setbuf>

externdef __imp_setjmp:PPROC
vc_setjmp equ <__imp_setjmp>

externdef __imp_setlocale:PPROC
vc_setlocale equ <__imp_setlocale>

externdef __imp_setvbuf:PPROC
vc_setvbuf equ <__imp_setvbuf>

externdef __imp_signal:PPROC
vc_signal equ <__imp_signal>

externdef __imp_sin:PPROC
vc_sin equ <__imp_sin>

externdef __imp_sinf:PPROC
vc_sinf equ <__imp_sinf>

externdef __imp_sinh:PPROC
vc_sinh equ <__imp_sinh>

externdef __imp_sinhf:PPROC
vc_sinhf equ <__imp_sinhf>

externdef __imp_sprintf:PPROC
vc_sprintf equ <__imp_sprintf>

externdef __imp_sqrt:PPROC
vc_sqrt equ <__imp_sqrt>

externdef __imp_sqrtf:PPROC
vc_sqrtf equ <__imp_sqrtf>

externdef __imp_srand:PPROC
vc_srand equ <__imp_srand>

externdef __imp_sscanf:PPROC
vc_sscanf equ <__imp_sscanf>

externdef __imp_strcat:PPROC
vc_strcat equ <__imp_strcat>

externdef __imp_strchr:PPROC
vc_strchr equ <__imp_strchr>

externdef __imp_strcmp:PPROC
vc_strcmp equ <__imp_strcmp>

externdef __imp_strcoll:PPROC
vc_strcoll equ <__imp_strcoll>

externdef __imp_strcpy:PPROC
vc_strcpy equ <__imp_strcpy>

externdef __imp_strcspn:PPROC
vc_strcspn equ <__imp_strcspn>

externdef __imp_strerror:PPROC
vc_strerror equ <__imp_strerror>

externdef __imp_strftime:PPROC
vc_strftime equ <__imp_strftime>

externdef __imp_strlen:PPROC
vc_strlen equ <__imp_strlen>

externdef __imp_strncat:PPROC
vc_strncat equ <__imp_strncat>

externdef __imp_strncmp:PPROC
vc_strncmp equ <__imp_strncmp>

externdef __imp_strncpy:PPROC
vc_strncpy equ <__imp_strncpy>

externdef __imp_strpbrk:PPROC
vc_strpbrk equ <__imp_strpbrk>

externdef __imp_strrchr:PPROC
vc_strrchr equ <__imp_strrchr>

externdef __imp_strspn:PPROC
vc_strspn equ <__imp_strspn>

externdef __imp_strstr:PPROC
vc_strstr equ <__imp_strstr>

externdef __imp_strtod:PPROC
vc_strtod equ <__imp_strtod>

externdef __imp_strtok:PPROC
vc_strtok equ <__imp_strtok>

externdef __imp_strtol:PPROC
vc_strtol equ <__imp_strtol>

externdef __imp_strtoul:PPROC
vc_strtoul equ <__imp_strtoul>

externdef __imp_strxfrm:PPROC
vc_strxfrm equ <__imp_strxfrm>

externdef __imp_swprintf:PPROC
vc_swprintf equ <__imp_swprintf>

externdef __imp_swscanf:PPROC
vc_swscanf equ <__imp_swscanf>

externdef __imp_system:PPROC
vc_system equ <__imp_system>

externdef __imp_tan:PPROC
vc_tan equ <__imp_tan>

externdef __imp_tanf:PPROC
vc_tanf equ <__imp_tanf>

externdef __imp_tanh:PPROC
vc_tanh equ <__imp_tanh>

externdef __imp_time:PPROC
vc_time equ <__imp_time>

externdef __imp_tmpfile:PPROC
vc_tmpfile equ <__imp_tmpfile>

externdef __imp_tmpnam:PPROC
vc_tmpnam equ <__imp_tmpnam>

externdef __imp_tolower:PPROC
vc_tolower equ <__imp_tolower>

externdef __imp_toupper:PPROC
vc_toupper equ <__imp_toupper>

externdef __imp_towlower:PPROC
vc_towlower equ <__imp_towlower>

externdef __imp_towupper:PPROC
vc_towupper equ <__imp_towupper>

externdef __imp_ungetc:PPROC
vc_ungetc equ <__imp_ungetc>

externdef __imp_ungetwc:PPROC
vc_ungetwc equ <__imp_ungetwc>

externdef __imp_vfprintf:PPROC
vc_vfprintf equ <__imp_vfprintf>

externdef __imp_vfwprintf:PPROC
vc_vfwprintf equ <__imp_vfwprintf>

externdef __imp_vprintf:PPROC
vc_vprintf equ <__imp_vprintf>

externdef __imp_vsprintf:PPROC
vc_vsprintf equ <__imp_vsprintf>

externdef __imp_vswprintf:PPROC
vc_vswprintf equ <__imp_vswprintf>

externdef __imp_vwprintf:PPROC
vc_vwprintf equ <__imp_vwprintf>

externdef __imp_wcscat:PPROC
vc_wcscat equ <__imp_wcscat>

externdef __imp_wcschr:PPROC
vc_wcschr equ <__imp_wcschr>

externdef __imp_wcscmp:PPROC
vc_wcscmp equ <__imp_wcscmp>

externdef __imp_wcscoll:PPROC
vc_wcscoll equ <__imp_wcscoll>

externdef __imp_wcscpy:PPROC
vc_wcscpy equ <__imp_wcscpy>

externdef __imp_wcscspn:PPROC
vc_wcscspn equ <__imp_wcscspn>

externdef __imp_wcsftime:PPROC
vc_wcsftime equ <__imp_wcsftime>

externdef __imp_wcslen:PPROC
vc_wcslen equ <__imp_wcslen>

externdef __imp_wcsncat:PPROC
vc_wcsncat equ <__imp_wcsncat>

externdef __imp_wcsncmp:PPROC
vc_wcsncmp equ <__imp_wcsncmp>

externdef __imp_wcsncpy:PPROC
vc_wcsncpy equ <__imp_wcsncpy>

externdef __imp_wcspbrk:PPROC
vc_wcspbrk equ <__imp_wcspbrk>

externdef __imp_wcsrchr:PPROC
vc_wcsrchr equ <__imp_wcsrchr>

externdef __imp_wcsspn:PPROC
vc_wcsspn equ <__imp_wcsspn>

externdef __imp_wcsstr:PPROC
vc_wcsstr equ <__imp_wcsstr>

externdef __imp_wcstod:PPROC
vc_wcstod equ <__imp_wcstod>

externdef __imp_wcstok:PPROC
vc_wcstok equ <__imp_wcstok>

externdef __imp_wcstol:PPROC
vc_wcstol equ <__imp_wcstol>

externdef __imp_wcstombs:PPROC
vc_wcstombs equ <__imp_wcstombs>

externdef __imp_wcstoul:PPROC
vc_wcstoul equ <__imp_wcstoul>

externdef __imp_wcsxfrm:PPROC
vc_wcsxfrm equ <__imp_wcsxfrm>

externdef __imp_wctomb:PPROC
vc_wctomb equ <__imp_wctomb>

externdef __imp_wprintf:PPROC
vc_wprintf equ <__imp_wprintf>

externdef __imp_wscanf:PPROC
vc_wscanf equ <__imp_wscanf>
