externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_MtxCluBringOnlineDTC2A:PPROC
MtxCluBringOnlineDTC2A equ <__imp_MtxCluBringOnlineDTC2A>
  IFNDEF __UNICODE__
    MtxCluBringOnlineDTC2 equ <__imp_MtxCluBringOnlineDTC2A>
  ENDIF

externdef __imp_MtxCluBringOnlineDTC2W:PPROC
MtxCluBringOnlineDTC2W equ <__imp_MtxCluBringOnlineDTC2W>
  IFDEF __UNICODE__
    MtxCluBringOnlineDTC2 equ <__imp_MtxCluBringOnlineDTC2W>
  ENDIF

externdef __imp_MtxCluBringOnlineDTCA:PPROC
MtxCluBringOnlineDTCA equ <__imp_MtxCluBringOnlineDTCA>
  IFNDEF __UNICODE__
    MtxCluBringOnlineDTC equ <__imp_MtxCluBringOnlineDTCA>
  ENDIF

externdef __imp_MtxCluBringOnlineDTCW:PPROC
MtxCluBringOnlineDTCW equ <__imp_MtxCluBringOnlineDTCW>
  IFDEF __UNICODE__
    MtxCluBringOnlineDTC equ <__imp_MtxCluBringOnlineDTCW>
  ENDIF

externdef __imp_MtxCluCheckIfOkToStartDtc:PPROC
MtxCluCheckIfOkToStartDtc equ <__imp_MtxCluCheckIfOkToStartDtc>

externdef __imp_MtxCluCheckPointCryptoW:PPROC
MtxCluCheckPointCryptoW equ <__imp_MtxCluCheckPointCryptoW>
  IFDEF __UNICODE__
    MtxCluCheckPointCrypto equ <__imp_MtxCluCheckPointCryptoW>
  ENDIF

externdef __imp_MtxCluCheckpointRegistryA:PPROC
MtxCluCheckpointRegistryA equ <__imp_MtxCluCheckpointRegistryA>
  IFNDEF __UNICODE__
    MtxCluCheckpointRegistry equ <__imp_MtxCluCheckpointRegistryA>
  ENDIF

externdef __imp_MtxCluCheckpointRegistryW:PPROC
MtxCluCheckpointRegistryW equ <__imp_MtxCluCheckpointRegistryW>
  IFDEF __UNICODE__
    MtxCluCheckpointRegistry equ <__imp_MtxCluCheckpointRegistryW>
  ENDIF

externdef __imp_MtxCluCloseNodeNotify:PPROC
MtxCluCloseNodeNotify equ <__imp_MtxCluCloseNodeNotify>

externdef __imp_MtxCluCreateDtcResourceKeyW:PPROC
MtxCluCreateDtcResourceKeyW equ <__imp_MtxCluCreateDtcResourceKeyW>
  IFDEF __UNICODE__
    MtxCluCreateDtcResourceKey equ <__imp_MtxCluCreateDtcResourceKeyW>
  ENDIF

externdef __imp_MtxCluCreateDtcResourceValueW:PPROC
MtxCluCreateDtcResourceValueW equ <__imp_MtxCluCreateDtcResourceValueW>
  IFDEF __UNICODE__
    MtxCluCreateDtcResourceValue equ <__imp_MtxCluCreateDtcResourceValueW>
  ENDIF

externdef __imp_MtxCluCreateDtcResourceW:PPROC
MtxCluCreateDtcResourceW equ <__imp_MtxCluCreateDtcResourceW>
  IFDEF __UNICODE__
    MtxCluCreateDtcResource equ <__imp_MtxCluCreateDtcResourceW>
  ENDIF

externdef __imp_MtxCluCreateRecommendedLogInfo:PPROC
MtxCluCreateRecommendedLogInfo equ <__imp_MtxCluCreateRecommendedLogInfo>

externdef __imp_MtxCluDeleteDtcResourceKeyW:PPROC
MtxCluDeleteDtcResourceKeyW equ <__imp_MtxCluDeleteDtcResourceKeyW>
  IFDEF __UNICODE__
    MtxCluDeleteDtcResourceKey equ <__imp_MtxCluDeleteDtcResourceKeyW>
  ENDIF

externdef __imp_MtxCluDeleteDtcResourceValueW:PPROC
MtxCluDeleteDtcResourceValueW equ <__imp_MtxCluDeleteDtcResourceValueW>
  IFDEF __UNICODE__
    MtxCluDeleteDtcResourceValue equ <__imp_MtxCluDeleteDtcResourceValueW>
  ENDIF

externdef __imp_MtxCluDoesDTCResourceExistA:PPROC
MtxCluDoesDTCResourceExistA equ <__imp_MtxCluDoesDTCResourceExistA>
  IFNDEF __UNICODE__
    MtxCluDoesDTCResourceExist equ <__imp_MtxCluDoesDTCResourceExistA>
  ENDIF

externdef __imp_MtxCluDoesDTCResourceExistW:PPROC
MtxCluDoesDTCResourceExistW equ <__imp_MtxCluDoesDTCResourceExistW>
  IFDEF __UNICODE__
    MtxCluDoesDTCResourceExist equ <__imp_MtxCluDoesDTCResourceExistW>
  ENDIF

externdef __imp_MtxCluGetComputerNameA:PPROC
MtxCluGetComputerNameA equ <__imp_MtxCluGetComputerNameA>
  IFNDEF __UNICODE__
    MtxCluGetComputerName equ <__imp_MtxCluGetComputerNameA>
  ENDIF

externdef __imp_MtxCluGetComputerNameW:PPROC
MtxCluGetComputerNameW equ <__imp_MtxCluGetComputerNameW>
  IFDEF __UNICODE__
    MtxCluGetComputerName equ <__imp_MtxCluGetComputerNameW>
  ENDIF

externdef __imp_MtxCluGetDTCInstallState:PPROC
MtxCluGetDTCInstallState equ <__imp_MtxCluGetDTCInstallState>

externdef __imp_MtxCluGetDTCInstallVersion:PPROC
MtxCluGetDTCInstallVersion equ <__imp_MtxCluGetDTCInstallVersion>

externdef __imp_MtxCluGetDTCIpAddressA:PPROC
MtxCluGetDTCIpAddressA equ <__imp_MtxCluGetDTCIpAddressA>
  IFNDEF __UNICODE__
    MtxCluGetDTCIpAddress equ <__imp_MtxCluGetDTCIpAddressA>
  ENDIF

externdef __imp_MtxCluGetDTCIpAddressW:PPROC
MtxCluGetDTCIpAddressW equ <__imp_MtxCluGetDTCIpAddressW>
  IFDEF __UNICODE__
    MtxCluGetDTCIpAddress equ <__imp_MtxCluGetDTCIpAddressW>
  ENDIF

externdef __imp_MtxCluGetDTCLogPathA:PPROC
MtxCluGetDTCLogPathA equ <__imp_MtxCluGetDTCLogPathA>
  IFNDEF __UNICODE__
    MtxCluGetDTCLogPath equ <__imp_MtxCluGetDTCLogPathA>
  ENDIF

externdef __imp_MtxCluGetDTCLogPathW:PPROC
MtxCluGetDTCLogPathW equ <__imp_MtxCluGetDTCLogPathW>
  IFDEF __UNICODE__
    MtxCluGetDTCLogPath equ <__imp_MtxCluGetDTCLogPathW>
  ENDIF

externdef __imp_MtxCluGetDTCLogSizeA:PPROC
MtxCluGetDTCLogSizeA equ <__imp_MtxCluGetDTCLogSizeA>
  IFNDEF __UNICODE__
    MtxCluGetDTCLogSize equ <__imp_MtxCluGetDTCLogSizeA>
  ENDIF

externdef __imp_MtxCluGetDTCLogSizeW:PPROC
MtxCluGetDTCLogSizeW equ <__imp_MtxCluGetDTCLogSizeW>
  IFDEF __UNICODE__
    MtxCluGetDTCLogSize equ <__imp_MtxCluGetDTCLogSizeW>
  ENDIF

externdef __imp_MtxCluGetDTCOwnerA:PPROC
MtxCluGetDTCOwnerA equ <__imp_MtxCluGetDTCOwnerA>
  IFNDEF __UNICODE__
    MtxCluGetDTCOwner equ <__imp_MtxCluGetDTCOwnerA>
  ENDIF

externdef __imp_MtxCluGetDTCOwnerW:PPROC
MtxCluGetDTCOwnerW equ <__imp_MtxCluGetDTCOwnerW>
  IFDEF __UNICODE__
    MtxCluGetDTCOwner equ <__imp_MtxCluGetDTCOwnerW>
  ENDIF

externdef __imp_MtxCluGetDTCStatusA:PPROC
MtxCluGetDTCStatusA equ <__imp_MtxCluGetDTCStatusA>
  IFNDEF __UNICODE__
    MtxCluGetDTCStatus equ <__imp_MtxCluGetDTCStatusA>
  ENDIF

externdef __imp_MtxCluGetDTCStatusW:PPROC
MtxCluGetDTCStatusW equ <__imp_MtxCluGetDTCStatusW>
  IFDEF __UNICODE__
    MtxCluGetDTCStatus equ <__imp_MtxCluGetDTCStatusW>
  ENDIF

externdef __imp_MtxCluGetDTCVirtualServerNameA:PPROC
MtxCluGetDTCVirtualServerNameA equ <__imp_MtxCluGetDTCVirtualServerNameA>
  IFNDEF __UNICODE__
    MtxCluGetDTCVirtualServerName equ <__imp_MtxCluGetDTCVirtualServerNameA>
  ENDIF

externdef __imp_MtxCluGetDTCVirtualServerNameW:PPROC
MtxCluGetDTCVirtualServerNameW equ <__imp_MtxCluGetDTCVirtualServerNameW>
  IFDEF __UNICODE__
    MtxCluGetDTCVirtualServerName equ <__imp_MtxCluGetDTCVirtualServerNameW>
  ENDIF

externdef __imp_MtxCluGetDtcRegValue:PPROC
MtxCluGetDtcRegValue equ <__imp_MtxCluGetDtcRegValue>

externdef __imp_MtxCluGetDtcUserInfo:PPROC
MtxCluGetDtcUserInfo equ <__imp_MtxCluGetDtcUserInfo>

externdef __imp_MtxCluGetJoinMasterA:PPROC
MtxCluGetJoinMasterA equ <__imp_MtxCluGetJoinMasterA>
  IFNDEF __UNICODE__
    MtxCluGetJoinMaster equ <__imp_MtxCluGetJoinMasterA>
  ENDIF

externdef __imp_MtxCluGetJoinMasterW:PPROC
MtxCluGetJoinMasterW equ <__imp_MtxCluGetJoinMasterW>
  IFDEF __UNICODE__
    MtxCluGetJoinMaster equ <__imp_MtxCluGetJoinMasterW>
  ENDIF

externdef __imp_MtxCluGetListOfSharedDisksA:PPROC
MtxCluGetListOfSharedDisksA equ <__imp_MtxCluGetListOfSharedDisksA>
  IFNDEF __UNICODE__
    MtxCluGetListOfSharedDisks equ <__imp_MtxCluGetListOfSharedDisksA>
  ENDIF

externdef __imp_MtxCluGetListOfSharedDisksOnVirtualServerA:PPROC
MtxCluGetListOfSharedDisksOnVirtualServerA equ <__imp_MtxCluGetListOfSharedDisksOnVirtualServerA>
  IFNDEF __UNICODE__
    MtxCluGetListOfSharedDisksOnVirtualServer equ <__imp_MtxCluGetListOfSharedDisksOnVirtualServerA>
  ENDIF

externdef __imp_MtxCluGetListOfSharedDisksOnVirtualServerW:PPROC
MtxCluGetListOfSharedDisksOnVirtualServerW equ <__imp_MtxCluGetListOfSharedDisksOnVirtualServerW>
  IFDEF __UNICODE__
    MtxCluGetListOfSharedDisksOnVirtualServer equ <__imp_MtxCluGetListOfSharedDisksOnVirtualServerW>
  ENDIF

externdef __imp_MtxCluGetListOfSharedDisksW:PPROC
MtxCluGetListOfSharedDisksW equ <__imp_MtxCluGetListOfSharedDisksW>
  IFDEF __UNICODE__
    MtxCluGetListOfSharedDisks equ <__imp_MtxCluGetListOfSharedDisksW>
  ENDIF

externdef __imp_MtxCluGetListOfVirtualServersA:PPROC
MtxCluGetListOfVirtualServersA equ <__imp_MtxCluGetListOfVirtualServersA>
  IFNDEF __UNICODE__
    MtxCluGetListOfVirtualServers equ <__imp_MtxCluGetListOfVirtualServersA>
  ENDIF

externdef __imp_MtxCluGetListOfVirtualServersW:PPROC
MtxCluGetListOfVirtualServersW equ <__imp_MtxCluGetListOfVirtualServersW>
  IFDEF __UNICODE__
    MtxCluGetListOfVirtualServers equ <__imp_MtxCluGetListOfVirtualServersW>
  ENDIF

externdef __imp_MtxCluGetNewCryptoKey:PPROC
MtxCluGetNewCryptoKey equ <__imp_MtxCluGetNewCryptoKey>

externdef __imp_MtxCluGetNodeClusterStateW:PPROC
MtxCluGetNodeClusterStateW equ <__imp_MtxCluGetNodeClusterStateW>
  IFDEF __UNICODE__
    MtxCluGetNodeClusterState equ <__imp_MtxCluGetNodeClusterStateW>
  ENDIF

externdef __imp_MtxCluGetSecurityRegValue:PPROC
MtxCluGetSecurityRegValue equ <__imp_MtxCluGetSecurityRegValue>

externdef __imp_MtxCluInitialize:PPROC
MtxCluInitialize equ <__imp_MtxCluInitialize>

externdef __imp_MtxCluIsClusterPresent:PPROC
MtxCluIsClusterPresent equ <__imp_MtxCluIsClusterPresent>

externdef __imp_MtxCluIsClusterPresentExA:PPROC
MtxCluIsClusterPresentExA equ <__imp_MtxCluIsClusterPresentExA>
  IFNDEF __UNICODE__
    MtxCluIsClusterPresentEx equ <__imp_MtxCluIsClusterPresentExA>
  ENDIF

externdef __imp_MtxCluIsClusterPresentExW:PPROC
MtxCluIsClusterPresentExW equ <__imp_MtxCluIsClusterPresentExW>
  IFDEF __UNICODE__
    MtxCluIsClusterPresentEx equ <__imp_MtxCluIsClusterPresentExW>
  ENDIF

externdef __imp_MtxCluIsNetworkNameInLocalClusterW:PPROC
MtxCluIsNetworkNameInLocalClusterW equ <__imp_MtxCluIsNetworkNameInLocalClusterW>
  IFDEF __UNICODE__
    MtxCluIsNetworkNameInLocalCluster equ <__imp_MtxCluIsNetworkNameInLocalClusterW>
  ENDIF

externdef __imp_MtxCluIsSameClusterW:PPROC
MtxCluIsSameClusterW equ <__imp_MtxCluIsSameClusterW>
  IFDEF __UNICODE__
    MtxCluIsSameCluster equ <__imp_MtxCluIsSameClusterW>
  ENDIF

externdef __imp_MtxCluIsSameNodeA:PPROC
MtxCluIsSameNodeA equ <__imp_MtxCluIsSameNodeA>
  IFNDEF __UNICODE__
    MtxCluIsSameNode equ <__imp_MtxCluIsSameNodeA>
  ENDIF

externdef __imp_MtxCluIsSameNodeW:PPROC
MtxCluIsSameNodeW equ <__imp_MtxCluIsSameNodeW>
  IFDEF __UNICODE__
    MtxCluIsSameNode equ <__imp_MtxCluIsSameNodeW>
  ENDIF

externdef __imp_MtxCluIsSharedDiskA:PPROC
MtxCluIsSharedDiskA equ <__imp_MtxCluIsSharedDiskA>
  IFNDEF __UNICODE__
    MtxCluIsSharedDisk equ <__imp_MtxCluIsSharedDiskA>
  ENDIF

externdef __imp_MtxCluIsSharedDiskW:PPROC
MtxCluIsSharedDiskW equ <__imp_MtxCluIsSharedDiskW>
  IFDEF __UNICODE__
    MtxCluIsSharedDisk equ <__imp_MtxCluIsSharedDiskW>
  ENDIF

externdef __imp_MtxCluIsVirtualServerInLocalClusterA:PPROC
MtxCluIsVirtualServerInLocalClusterA equ <__imp_MtxCluIsVirtualServerInLocalClusterA>
  IFNDEF __UNICODE__
    MtxCluIsVirtualServerInLocalCluster equ <__imp_MtxCluIsVirtualServerInLocalClusterA>
  ENDIF

externdef __imp_MtxCluIsVirtualServerInLocalClusterW:PPROC
MtxCluIsVirtualServerInLocalClusterW equ <__imp_MtxCluIsVirtualServerInLocalClusterW>
  IFDEF __UNICODE__
    MtxCluIsVirtualServerInLocalCluster equ <__imp_MtxCluIsVirtualServerInLocalClusterW>
  ENDIF

externdef __imp_MtxCluJoinDTCResource:PPROC
MtxCluJoinDTCResource equ <__imp_MtxCluJoinDTCResource>

externdef __imp_MtxCluListNodesA:PPROC
MtxCluListNodesA equ <__imp_MtxCluListNodesA>
  IFNDEF __UNICODE__
    MtxCluListNodes equ <__imp_MtxCluListNodesA>
  ENDIF

externdef __imp_MtxCluListNodesW:PPROC
MtxCluListNodesW equ <__imp_MtxCluListNodesW>
  IFDEF __UNICODE__
    MtxCluListNodes equ <__imp_MtxCluListNodesW>
  ENDIF

externdef __imp_MtxCluMoveDTCGroupA:PPROC
MtxCluMoveDTCGroupA equ <__imp_MtxCluMoveDTCGroupA>
  IFNDEF __UNICODE__
    MtxCluMoveDTCGroup equ <__imp_MtxCluMoveDTCGroupA>
  ENDIF

externdef __imp_MtxCluMoveDTCGroupW:PPROC
MtxCluMoveDTCGroupW equ <__imp_MtxCluMoveDTCGroupW>
  IFDEF __UNICODE__
    MtxCluMoveDTCGroup equ <__imp_MtxCluMoveDTCGroupW>
  ENDIF

externdef __imp_MtxCluNodeNotifyA:PPROC
MtxCluNodeNotifyA equ <__imp_MtxCluNodeNotifyA>
  IFNDEF __UNICODE__
    MtxCluNodeNotify equ <__imp_MtxCluNodeNotifyA>
  ENDIF

externdef __imp_MtxCluNodeNotifyW:PPROC
MtxCluNodeNotifyW equ <__imp_MtxCluNodeNotifyW>
  IFDEF __UNICODE__
    MtxCluNodeNotify equ <__imp_MtxCluNodeNotifyW>
  ENDIF

externdef __imp_MtxCluQueryDtcResourceValueW:PPROC
MtxCluQueryDtcResourceValueW equ <__imp_MtxCluQueryDtcResourceValueW>
  IFDEF __UNICODE__
    MtxCluQueryDtcResourceValue equ <__imp_MtxCluQueryDtcResourceValueW>
  ENDIF

externdef __imp_MtxCluRegisterDTCResourceA:PPROC
MtxCluRegisterDTCResourceA equ <__imp_MtxCluRegisterDTCResourceA>
  IFNDEF __UNICODE__
    MtxCluRegisterDTCResource equ <__imp_MtxCluRegisterDTCResourceA>
  ENDIF

externdef __imp_MtxCluRegisterDTCResourceW:PPROC
MtxCluRegisterDTCResourceW equ <__imp_MtxCluRegisterDTCResourceW>
  IFDEF __UNICODE__
    MtxCluRegisterDTCResource equ <__imp_MtxCluRegisterDTCResourceW>
  ENDIF

externdef __imp_MtxCluRemoveAllRegistryCheckpoints:PPROC
MtxCluRemoveAllRegistryCheckpoints equ <__imp_MtxCluRemoveAllRegistryCheckpoints>

externdef __imp_MtxCluRemoveCheckpointRegistryA:PPROC
MtxCluRemoveCheckpointRegistryA equ <__imp_MtxCluRemoveCheckpointRegistryA>
  IFNDEF __UNICODE__
    MtxCluRemoveCheckpointRegistry equ <__imp_MtxCluRemoveCheckpointRegistryA>
  ENDIF

externdef __imp_MtxCluRemoveCheckpointRegistryW:PPROC
MtxCluRemoveCheckpointRegistryW equ <__imp_MtxCluRemoveCheckpointRegistryW>
  IFDEF __UNICODE__
    MtxCluRemoveCheckpointRegistry equ <__imp_MtxCluRemoveCheckpointRegistryW>
  ENDIF

externdef __imp_MtxCluSetDTCLogPathA:PPROC
MtxCluSetDTCLogPathA equ <__imp_MtxCluSetDTCLogPathA>
  IFNDEF __UNICODE__
    MtxCluSetDTCLogPath equ <__imp_MtxCluSetDTCLogPathA>
  ENDIF

externdef __imp_MtxCluSetDTCLogPathW:PPROC
MtxCluSetDTCLogPathW equ <__imp_MtxCluSetDTCLogPathW>
  IFDEF __UNICODE__
    MtxCluSetDTCLogPath equ <__imp_MtxCluSetDTCLogPathW>
  ENDIF

externdef __imp_MtxCluSetDTCLogSizeA:PPROC
MtxCluSetDTCLogSizeA equ <__imp_MtxCluSetDTCLogSizeA>
  IFNDEF __UNICODE__
    MtxCluSetDTCLogSize equ <__imp_MtxCluSetDTCLogSizeA>
  ENDIF

externdef __imp_MtxCluSetDTCLogSizeW:PPROC
MtxCluSetDTCLogSizeW equ <__imp_MtxCluSetDTCLogSizeW>
  IFDEF __UNICODE__
    MtxCluSetDTCLogSize equ <__imp_MtxCluSetDTCLogSizeW>
  ENDIF

externdef __imp_MtxCluSetDtcUserInfo:PPROC
MtxCluSetDtcUserInfo equ <__imp_MtxCluSetDtcUserInfo>

externdef __imp_MtxCluSetNewCryptoKey:PPROC
MtxCluSetNewCryptoKey equ <__imp_MtxCluSetNewCryptoKey>

externdef __imp_MtxCluSetSecurityRegValue:PPROC
MtxCluSetSecurityRegValue equ <__imp_MtxCluSetSecurityRegValue>

externdef __imp_MtxCluTakeOfflineDTC2W:PPROC
MtxCluTakeOfflineDTC2W equ <__imp_MtxCluTakeOfflineDTC2W>
  IFDEF __UNICODE__
    MtxCluTakeOfflineDTC2 equ <__imp_MtxCluTakeOfflineDTC2W>
  ENDIF

externdef __imp_MtxCluTakeOfflineDTCA:PPROC
MtxCluTakeOfflineDTCA equ <__imp_MtxCluTakeOfflineDTCA>
  IFNDEF __UNICODE__
    MtxCluTakeOfflineDTC equ <__imp_MtxCluTakeOfflineDTCA>
  ENDIF

externdef __imp_MtxCluTakeOfflineDTCW:PPROC
MtxCluTakeOfflineDTCW equ <__imp_MtxCluTakeOfflineDTCW>
  IFDEF __UNICODE__
    MtxCluTakeOfflineDTC equ <__imp_MtxCluTakeOfflineDTCW>
  ENDIF

externdef __imp_MtxCluUninitialize:PPROC
MtxCluUninitialize equ <__imp_MtxCluUninitialize>

externdef __imp_MtxCluUpgradeDtcResourceW:PPROC
MtxCluUpgradeDtcResourceW equ <__imp_MtxCluUpgradeDtcResourceW>
  IFDEF __UNICODE__
    MtxCluUpgradeDtcResource equ <__imp_MtxCluUpgradeDtcResourceW>
  ENDIF

externdef __imp_Startup:PPROC
Startup equ <__imp_Startup>

externdef __imp_WasDTCInstalledBySQL:PPROC
WasDTCInstalledBySQL equ <__imp_WasDTCInstalledBySQL>
