externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_Enlist:PPROC
Enlist equ <__imp_Enlist>

externdef __imp_GetXaSwitch:PPROC
GetXaSwitch equ <__imp_GetXaSwitch>

externdef __imp_MTxOciGetVersion:PPROC
MTxOciGetVersion equ <__imp_MTxOciGetVersion>

externdef __imp_MTxOciInit:PPROC
MTxOciInit equ <__imp_MTxOciInit>

externdef __imp_MTxOciRegisterCursor:PPROC
MTxOciRegisterCursor equ <__imp_MTxOciRegisterCursor>

externdef __imp_MTxolog:PPROC
MTxolog equ <__imp_MTxolog>

externdef __imp_mtxoci_ordinal100:PPROC
mtxoci_ordinal100 equ <__imp_mtxoci_ordinal100>

externdef __imp_mtxoci_ordinal101:PPROC
mtxoci_ordinal101 equ <__imp_mtxoci_ordinal101>

externdef __imp_mtxoci_ordinal102:PPROC
mtxoci_ordinal102 equ <__imp_mtxoci_ordinal102>

externdef __imp_mtxoci_ordinal103:PPROC
mtxoci_ordinal103 equ <__imp_mtxoci_ordinal103>

externdef __imp_mtxoci_ordinal104:PPROC
mtxoci_ordinal104 equ <__imp_mtxoci_ordinal104>

externdef __imp_mtxoci_ordinal105:PPROC
mtxoci_ordinal105 equ <__imp_mtxoci_ordinal105>

externdef __imp_mtxoci_ordinal106:PPROC
mtxoci_ordinal106 equ <__imp_mtxoci_ordinal106>

externdef __imp_mtxoci_ordinal107:PPROC
mtxoci_ordinal107 equ <__imp_mtxoci_ordinal107>

externdef __imp_mtxoci_ordinal108:PPROC
mtxoci_ordinal108 equ <__imp_mtxoci_ordinal108>

externdef __imp_mtxoci_ordinal109:PPROC
mtxoci_ordinal109 equ <__imp_mtxoci_ordinal109>

externdef __imp_mtxoci_ordinal110:PPROC
mtxoci_ordinal110 equ <__imp_mtxoci_ordinal110>

externdef __imp_mtxoci_ordinal111:PPROC
mtxoci_ordinal111 equ <__imp_mtxoci_ordinal111>

externdef __imp_mtxoci_ordinal112:PPROC
mtxoci_ordinal112 equ <__imp_mtxoci_ordinal112>

externdef __imp_mtxoci_ordinal113:PPROC
mtxoci_ordinal113 equ <__imp_mtxoci_ordinal113>

externdef __imp_mtxoci_ordinal114:PPROC
mtxoci_ordinal114 equ <__imp_mtxoci_ordinal114>

externdef __imp_mtxoci_ordinal115:PPROC
mtxoci_ordinal115 equ <__imp_mtxoci_ordinal115>

externdef __imp_mtxoci_ordinal116:PPROC
mtxoci_ordinal116 equ <__imp_mtxoci_ordinal116>

externdef __imp_mtxoci_ordinal117:PPROC
mtxoci_ordinal117 equ <__imp_mtxoci_ordinal117>

externdef __imp_mtxoci_ordinal118:PPROC
mtxoci_ordinal118 equ <__imp_mtxoci_ordinal118>

externdef __imp_mtxoci_ordinal119:PPROC
mtxoci_ordinal119 equ <__imp_mtxoci_ordinal119>

externdef __imp_mtxoci_ordinal120:PPROC
mtxoci_ordinal120 equ <__imp_mtxoci_ordinal120>

externdef __imp_mtxoci_ordinal121:PPROC
mtxoci_ordinal121 equ <__imp_mtxoci_ordinal121>

externdef __imp_mtxoci_ordinal122:PPROC
mtxoci_ordinal122 equ <__imp_mtxoci_ordinal122>

externdef __imp_mtxoci_ordinal123:PPROC
mtxoci_ordinal123 equ <__imp_mtxoci_ordinal123>

externdef __imp_mtxoci_ordinal124:PPROC
mtxoci_ordinal124 equ <__imp_mtxoci_ordinal124>

externdef __imp_mtxoci_ordinal125:PPROC
mtxoci_ordinal125 equ <__imp_mtxoci_ordinal125>

externdef __imp_mtxoci_ordinal126:PPROC
mtxoci_ordinal126 equ <__imp_mtxoci_ordinal126>

externdef __imp_mtxoci_ordinal127:PPROC
mtxoci_ordinal127 equ <__imp_mtxoci_ordinal127>

externdef __imp_mtxoci_ordinal128:PPROC
mtxoci_ordinal128 equ <__imp_mtxoci_ordinal128>

externdef __imp_mtxoci_ordinal129:PPROC
mtxoci_ordinal129 equ <__imp_mtxoci_ordinal129>

externdef __imp_mtxoci_ordinal130:PPROC
mtxoci_ordinal130 equ <__imp_mtxoci_ordinal130>

externdef __imp_mtxoci_ordinal131:PPROC
mtxoci_ordinal131 equ <__imp_mtxoci_ordinal131>

externdef __imp_mtxoci_ordinal132:PPROC
mtxoci_ordinal132 equ <__imp_mtxoci_ordinal132>

externdef __imp_mtxoci_ordinal133:PPROC
mtxoci_ordinal133 equ <__imp_mtxoci_ordinal133>

externdef __imp_mtxoci_ordinal134:PPROC
mtxoci_ordinal134 equ <__imp_mtxoci_ordinal134>

externdef __imp_mtxoci_ordinal135:PPROC
mtxoci_ordinal135 equ <__imp_mtxoci_ordinal135>

externdef __imp_mtxoci_ordinal136:PPROC
mtxoci_ordinal136 equ <__imp_mtxoci_ordinal136>

externdef __imp_mtxoci_ordinal137:PPROC
mtxoci_ordinal137 equ <__imp_mtxoci_ordinal137>

externdef __imp_mtxoci_ordinal138:PPROC
mtxoci_ordinal138 equ <__imp_mtxoci_ordinal138>

externdef __imp_mtxoci_ordinal139:PPROC
mtxoci_ordinal139 equ <__imp_mtxoci_ordinal139>

externdef __imp_mtxoci_ordinal140:PPROC
mtxoci_ordinal140 equ <__imp_mtxoci_ordinal140>

externdef __imp_mtxoci_ordinal141:PPROC
mtxoci_ordinal141 equ <__imp_mtxoci_ordinal141>

externdef __imp_mtxoci_ordinal142:PPROC
mtxoci_ordinal142 equ <__imp_mtxoci_ordinal142>

externdef __imp_mtxoci_ordinal143:PPROC
mtxoci_ordinal143 equ <__imp_mtxoci_ordinal143>

externdef __imp_mtxoci_ordinal144:PPROC
mtxoci_ordinal144 equ <__imp_mtxoci_ordinal144>

externdef __imp_mtxoci_ordinal145:PPROC
mtxoci_ordinal145 equ <__imp_mtxoci_ordinal145>

externdef __imp_mtxoci_ordinal146:PPROC
mtxoci_ordinal146 equ <__imp_mtxoci_ordinal146>

externdef __imp_mtxoci_ordinal147:PPROC
mtxoci_ordinal147 equ <__imp_mtxoci_ordinal147>

externdef __imp_mtxoci_ordinal148:PPROC
mtxoci_ordinal148 equ <__imp_mtxoci_ordinal148>

externdef __imp_mtxoci_ordinal149:PPROC
mtxoci_ordinal149 equ <__imp_mtxoci_ordinal149>

externdef __imp_mtxoci_ordinal150:PPROC
mtxoci_ordinal150 equ <__imp_mtxoci_ordinal150>

externdef __imp_mtxoci_ordinal151:PPROC
mtxoci_ordinal151 equ <__imp_mtxoci_ordinal151>

externdef __imp_mtxoci_ordinal152:PPROC
mtxoci_ordinal152 equ <__imp_mtxoci_ordinal152>

externdef __imp_mtxoci_ordinal153:PPROC
mtxoci_ordinal153 equ <__imp_mtxoci_ordinal153>

externdef __imp_mtxoci_ordinal154:PPROC
mtxoci_ordinal154 equ <__imp_mtxoci_ordinal154>

externdef __imp_mtxoci_ordinal155:PPROC
mtxoci_ordinal155 equ <__imp_mtxoci_ordinal155>

externdef __imp_mtxoci_ordinal156:PPROC
mtxoci_ordinal156 equ <__imp_mtxoci_ordinal156>

externdef __imp_mtxoci_ordinal157:PPROC
mtxoci_ordinal157 equ <__imp_mtxoci_ordinal157>

externdef __imp_mtxoci_ordinal158:PPROC
mtxoci_ordinal158 equ <__imp_mtxoci_ordinal158>

externdef __imp_mtxoci_ordinal159:PPROC
mtxoci_ordinal159 equ <__imp_mtxoci_ordinal159>

externdef __imp_mtxoci_ordinal160:PPROC
mtxoci_ordinal160 equ <__imp_mtxoci_ordinal160>

externdef __imp_mtxoci_ordinal161:PPROC
mtxoci_ordinal161 equ <__imp_mtxoci_ordinal161>

externdef __imp_mtxoci_ordinal162:PPROC
mtxoci_ordinal162 equ <__imp_mtxoci_ordinal162>

externdef __imp_mtxoci_ordinal163:PPROC
mtxoci_ordinal163 equ <__imp_mtxoci_ordinal163>

externdef __imp_mtxoci_ordinal164:PPROC
mtxoci_ordinal164 equ <__imp_mtxoci_ordinal164>

externdef __imp_mtxoci_ordinal165:PPROC
mtxoci_ordinal165 equ <__imp_mtxoci_ordinal165>

externdef __imp_mtxoci_ordinal166:PPROC
mtxoci_ordinal166 equ <__imp_mtxoci_ordinal166>

externdef __imp_mtxoci_ordinal167:PPROC
mtxoci_ordinal167 equ <__imp_mtxoci_ordinal167>

externdef __imp_mtxoci_ordinal168:PPROC
mtxoci_ordinal168 equ <__imp_mtxoci_ordinal168>

externdef __imp_mtxoci_ordinal169:PPROC
mtxoci_ordinal169 equ <__imp_mtxoci_ordinal169>

externdef __imp_mtxoci_ordinal170:PPROC
mtxoci_ordinal170 equ <__imp_mtxoci_ordinal170>

externdef __imp_mtxoci_ordinal171:PPROC
mtxoci_ordinal171 equ <__imp_mtxoci_ordinal171>

externdef __imp_mtxoci_ordinal172:PPROC
mtxoci_ordinal172 equ <__imp_mtxoci_ordinal172>

externdef __imp_mtxoci_ordinal173:PPROC
mtxoci_ordinal173 equ <__imp_mtxoci_ordinal173>

externdef __imp_mtxoci_ordinal174:PPROC
mtxoci_ordinal174 equ <__imp_mtxoci_ordinal174>

externdef __imp_mtxoci_ordinal175:PPROC
mtxoci_ordinal175 equ <__imp_mtxoci_ordinal175>

externdef __imp_mtxoci_ordinal176:PPROC
mtxoci_ordinal176 equ <__imp_mtxoci_ordinal176>

externdef __imp_mtxoci_ordinal177:PPROC
mtxoci_ordinal177 equ <__imp_mtxoci_ordinal177>

externdef __imp_mtxoci_ordinal178:PPROC
mtxoci_ordinal178 equ <__imp_mtxoci_ordinal178>

externdef __imp_mtxoci_ordinal179:PPROC
mtxoci_ordinal179 equ <__imp_mtxoci_ordinal179>

externdef __imp_mtxoci_ordinal180:PPROC
mtxoci_ordinal180 equ <__imp_mtxoci_ordinal180>

externdef __imp_mtxoci_ordinal181:PPROC
mtxoci_ordinal181 equ <__imp_mtxoci_ordinal181>

externdef __imp_mtxoci_ordinal182:PPROC
mtxoci_ordinal182 equ <__imp_mtxoci_ordinal182>

externdef __imp_mtxoci_ordinal183:PPROC
mtxoci_ordinal183 equ <__imp_mtxoci_ordinal183>

externdef __imp_mtxoci_ordinal184:PPROC
mtxoci_ordinal184 equ <__imp_mtxoci_ordinal184>

externdef __imp_mtxoci_ordinal185:PPROC
mtxoci_ordinal185 equ <__imp_mtxoci_ordinal185>

externdef __imp_mtxoci_ordinal186:PPROC
mtxoci_ordinal186 equ <__imp_mtxoci_ordinal186>

externdef __imp_mtxoci_ordinal187:PPROC
mtxoci_ordinal187 equ <__imp_mtxoci_ordinal187>

externdef __imp_mtxoci_ordinal188:PPROC
mtxoci_ordinal188 equ <__imp_mtxoci_ordinal188>

externdef __imp_mtxoci_ordinal189:PPROC
mtxoci_ordinal189 equ <__imp_mtxoci_ordinal189>

externdef __imp_mtxoci_ordinal190:PPROC
mtxoci_ordinal190 equ <__imp_mtxoci_ordinal190>

externdef __imp_mtxoci_ordinal191:PPROC
mtxoci_ordinal191 equ <__imp_mtxoci_ordinal191>

externdef __imp_mtxoci_ordinal192:PPROC
mtxoci_ordinal192 equ <__imp_mtxoci_ordinal192>

externdef __imp_mtxoci_ordinal193:PPROC
mtxoci_ordinal193 equ <__imp_mtxoci_ordinal193>

externdef __imp_mtxoci_ordinal194:PPROC
mtxoci_ordinal194 equ <__imp_mtxoci_ordinal194>

externdef __imp_mtxoci_ordinal195:PPROC
mtxoci_ordinal195 equ <__imp_mtxoci_ordinal195>

externdef __imp_mtxoci_ordinal196:PPROC
mtxoci_ordinal196 equ <__imp_mtxoci_ordinal196>

externdef __imp_mtxoci_ordinal197:PPROC
mtxoci_ordinal197 equ <__imp_mtxoci_ordinal197>

externdef __imp_mtxoci_ordinal198:PPROC
mtxoci_ordinal198 equ <__imp_mtxoci_ordinal198>

externdef __imp_mtxoci_ordinal199:PPROC
mtxoci_ordinal199 equ <__imp_mtxoci_ordinal199>

externdef __imp_mtxoci_ordinal200:PPROC
mtxoci_ordinal200 equ <__imp_mtxoci_ordinal200>

externdef __imp_mtxoci_ordinal201:PPROC
mtxoci_ordinal201 equ <__imp_mtxoci_ordinal201>

externdef __imp_mtxoci_ordinal202:PPROC
mtxoci_ordinal202 equ <__imp_mtxoci_ordinal202>

externdef __imp_mtxoci_ordinal203:PPROC
mtxoci_ordinal203 equ <__imp_mtxoci_ordinal203>

externdef __imp_mtxoci_ordinal204:PPROC
mtxoci_ordinal204 equ <__imp_mtxoci_ordinal204>

externdef __imp_mtxoci_ordinal205:PPROC
mtxoci_ordinal205 equ <__imp_mtxoci_ordinal205>

externdef __imp_mtxoci_ordinal206:PPROC
mtxoci_ordinal206 equ <__imp_mtxoci_ordinal206>

externdef __imp_mtxoci_ordinal207:PPROC
mtxoci_ordinal207 equ <__imp_mtxoci_ordinal207>

externdef __imp_mtxoci_ordinal208:PPROC
mtxoci_ordinal208 equ <__imp_mtxoci_ordinal208>

externdef __imp_mtxoci_ordinal209:PPROC
mtxoci_ordinal209 equ <__imp_mtxoci_ordinal209>

externdef __imp_mtxoci_ordinal210:PPROC
mtxoci_ordinal210 equ <__imp_mtxoci_ordinal210>

externdef __imp_mtxoci_ordinal211:PPROC
mtxoci_ordinal211 equ <__imp_mtxoci_ordinal211>

externdef __imp_mtxoci_ordinal212:PPROC
mtxoci_ordinal212 equ <__imp_mtxoci_ordinal212>

externdef __imp_mtxoci_ordinal213:PPROC
mtxoci_ordinal213 equ <__imp_mtxoci_ordinal213>

externdef __imp_mtxoci_ordinal214:PPROC
mtxoci_ordinal214 equ <__imp_mtxoci_ordinal214>

externdef __imp_mtxoci_ordinal215:PPROC
mtxoci_ordinal215 equ <__imp_mtxoci_ordinal215>

externdef __imp_mtxoci_ordinal216:PPROC
mtxoci_ordinal216 equ <__imp_mtxoci_ordinal216>

externdef __imp_mtxoci_ordinal217:PPROC
mtxoci_ordinal217 equ <__imp_mtxoci_ordinal217>

externdef __imp_mtxoci_ordinal218:PPROC
mtxoci_ordinal218 equ <__imp_mtxoci_ordinal218>

externdef __imp_mtxoci_ordinal219:PPROC
mtxoci_ordinal219 equ <__imp_mtxoci_ordinal219>

externdef __imp_mtxoci_ordinal220:PPROC
mtxoci_ordinal220 equ <__imp_mtxoci_ordinal220>

externdef __imp_mtxoci_ordinal221:PPROC
mtxoci_ordinal221 equ <__imp_mtxoci_ordinal221>

externdef __imp_mtxoci_ordinal222:PPROC
mtxoci_ordinal222 equ <__imp_mtxoci_ordinal222>

externdef __imp_mtxoci_ordinal223:PPROC
mtxoci_ordinal223 equ <__imp_mtxoci_ordinal223>

externdef __imp_mtxoci_ordinal224:PPROC
mtxoci_ordinal224 equ <__imp_mtxoci_ordinal224>

externdef __imp_mtxoci_ordinal225:PPROC
mtxoci_ordinal225 equ <__imp_mtxoci_ordinal225>

externdef __imp_mtxoci_ordinal226:PPROC
mtxoci_ordinal226 equ <__imp_mtxoci_ordinal226>

externdef __imp_mtxoci_ordinal227:PPROC
mtxoci_ordinal227 equ <__imp_mtxoci_ordinal227>

externdef __imp_mtxoci_ordinal228:PPROC
mtxoci_ordinal228 equ <__imp_mtxoci_ordinal228>

externdef __imp_mtxoci_ordinal229:PPROC
mtxoci_ordinal229 equ <__imp_mtxoci_ordinal229>

externdef __imp_mtxoci_ordinal230:PPROC
mtxoci_ordinal230 equ <__imp_mtxoci_ordinal230>

externdef __imp_mtxoci_ordinal231:PPROC
mtxoci_ordinal231 equ <__imp_mtxoci_ordinal231>

externdef __imp_mtxoci_ordinal232:PPROC
mtxoci_ordinal232 equ <__imp_mtxoci_ordinal232>

externdef __imp_mtxoci_ordinal233:PPROC
mtxoci_ordinal233 equ <__imp_mtxoci_ordinal233>

externdef __imp_mtxoci_ordinal234:PPROC
mtxoci_ordinal234 equ <__imp_mtxoci_ordinal234>

externdef __imp_mtxoci_ordinal235:PPROC
mtxoci_ordinal235 equ <__imp_mtxoci_ordinal235>

externdef __imp_mtxoci_ordinal236:PPROC
mtxoci_ordinal236 equ <__imp_mtxoci_ordinal236>

externdef __imp_mtxoci_ordinal237:PPROC
mtxoci_ordinal237 equ <__imp_mtxoci_ordinal237>

externdef __imp_mtxoci_ordinal238:PPROC
mtxoci_ordinal238 equ <__imp_mtxoci_ordinal238>

externdef __imp_mtxoci_ordinal239:PPROC
mtxoci_ordinal239 equ <__imp_mtxoci_ordinal239>

externdef __imp_mtxoci_ordinal240:PPROC
mtxoci_ordinal240 equ <__imp_mtxoci_ordinal240>

externdef __imp_mtxoci_ordinal241:PPROC
mtxoci_ordinal241 equ <__imp_mtxoci_ordinal241>

externdef __imp_mtxoci_ordinal242:PPROC
mtxoci_ordinal242 equ <__imp_mtxoci_ordinal242>

externdef __imp_mtxoci_ordinal243:PPROC
mtxoci_ordinal243 equ <__imp_mtxoci_ordinal243>

externdef __imp_mtxoci_ordinal244:PPROC
mtxoci_ordinal244 equ <__imp_mtxoci_ordinal244>

externdef __imp_mtxoci_ordinal245:PPROC
mtxoci_ordinal245 equ <__imp_mtxoci_ordinal245>

externdef __imp_mtxoci_ordinal246:PPROC
mtxoci_ordinal246 equ <__imp_mtxoci_ordinal246>

externdef __imp_mtxoci_ordinal247:PPROC
mtxoci_ordinal247 equ <__imp_mtxoci_ordinal247>

externdef __imp_mtxoci_ordinal248:PPROC
mtxoci_ordinal248 equ <__imp_mtxoci_ordinal248>

externdef __imp_mtxoci_ordinal249:PPROC
mtxoci_ordinal249 equ <__imp_mtxoci_ordinal249>

externdef __imp_mtxoci_ordinal250:PPROC
mtxoci_ordinal250 equ <__imp_mtxoci_ordinal250>

externdef __imp_mtxoci_ordinal251:PPROC
mtxoci_ordinal251 equ <__imp_mtxoci_ordinal251>

externdef __imp_mtxoci_ordinal252:PPROC
mtxoci_ordinal252 equ <__imp_mtxoci_ordinal252>

externdef __imp_mtxoci_ordinal253:PPROC
mtxoci_ordinal253 equ <__imp_mtxoci_ordinal253>

externdef __imp_mtxoci_ordinal254:PPROC
mtxoci_ordinal254 equ <__imp_mtxoci_ordinal254>

externdef __imp_mtxoci_ordinal255:PPROC
mtxoci_ordinal255 equ <__imp_mtxoci_ordinal255>

externdef __imp_mtxoci_ordinal256:PPROC
mtxoci_ordinal256 equ <__imp_mtxoci_ordinal256>

externdef __imp_mtxoci_ordinal257:PPROC
mtxoci_ordinal257 equ <__imp_mtxoci_ordinal257>

externdef __imp_mtxoci_ordinal258:PPROC
mtxoci_ordinal258 equ <__imp_mtxoci_ordinal258>

externdef __imp_mtxoci_ordinal259:PPROC
mtxoci_ordinal259 equ <__imp_mtxoci_ordinal259>

externdef __imp_mtxoci_ordinal25:PPROC
mtxoci_ordinal25 equ <__imp_mtxoci_ordinal25>

externdef __imp_mtxoci_ordinal260:PPROC
mtxoci_ordinal260 equ <__imp_mtxoci_ordinal260>

externdef __imp_mtxoci_ordinal261:PPROC
mtxoci_ordinal261 equ <__imp_mtxoci_ordinal261>

externdef __imp_mtxoci_ordinal262:PPROC
mtxoci_ordinal262 equ <__imp_mtxoci_ordinal262>

externdef __imp_mtxoci_ordinal263:PPROC
mtxoci_ordinal263 equ <__imp_mtxoci_ordinal263>

externdef __imp_mtxoci_ordinal264:PPROC
mtxoci_ordinal264 equ <__imp_mtxoci_ordinal264>

externdef __imp_mtxoci_ordinal265:PPROC
mtxoci_ordinal265 equ <__imp_mtxoci_ordinal265>

externdef __imp_mtxoci_ordinal266:PPROC
mtxoci_ordinal266 equ <__imp_mtxoci_ordinal266>

externdef __imp_mtxoci_ordinal267:PPROC
mtxoci_ordinal267 equ <__imp_mtxoci_ordinal267>

externdef __imp_mtxoci_ordinal268:PPROC
mtxoci_ordinal268 equ <__imp_mtxoci_ordinal268>

externdef __imp_mtxoci_ordinal269:PPROC
mtxoci_ordinal269 equ <__imp_mtxoci_ordinal269>

externdef __imp_mtxoci_ordinal270:PPROC
mtxoci_ordinal270 equ <__imp_mtxoci_ordinal270>

externdef __imp_mtxoci_ordinal271:PPROC
mtxoci_ordinal271 equ <__imp_mtxoci_ordinal271>

externdef __imp_mtxoci_ordinal272:PPROC
mtxoci_ordinal272 equ <__imp_mtxoci_ordinal272>

externdef __imp_mtxoci_ordinal273:PPROC
mtxoci_ordinal273 equ <__imp_mtxoci_ordinal273>

externdef __imp_mtxoci_ordinal274:PPROC
mtxoci_ordinal274 equ <__imp_mtxoci_ordinal274>

externdef __imp_mtxoci_ordinal275:PPROC
mtxoci_ordinal275 equ <__imp_mtxoci_ordinal275>

externdef __imp_mtxoci_ordinal276:PPROC
mtxoci_ordinal276 equ <__imp_mtxoci_ordinal276>

externdef __imp_mtxoci_ordinal277:PPROC
mtxoci_ordinal277 equ <__imp_mtxoci_ordinal277>

externdef __imp_mtxoci_ordinal278:PPROC
mtxoci_ordinal278 equ <__imp_mtxoci_ordinal278>

externdef __imp_mtxoci_ordinal279:PPROC
mtxoci_ordinal279 equ <__imp_mtxoci_ordinal279>

externdef __imp_mtxoci_ordinal280:PPROC
mtxoci_ordinal280 equ <__imp_mtxoci_ordinal280>

externdef __imp_mtxoci_ordinal281:PPROC
mtxoci_ordinal281 equ <__imp_mtxoci_ordinal281>

externdef __imp_mtxoci_ordinal282:PPROC
mtxoci_ordinal282 equ <__imp_mtxoci_ordinal282>

externdef __imp_mtxoci_ordinal283:PPROC
mtxoci_ordinal283 equ <__imp_mtxoci_ordinal283>

externdef __imp_mtxoci_ordinal284:PPROC
mtxoci_ordinal284 equ <__imp_mtxoci_ordinal284>

externdef __imp_mtxoci_ordinal285:PPROC
mtxoci_ordinal285 equ <__imp_mtxoci_ordinal285>

externdef __imp_mtxoci_ordinal286:PPROC
mtxoci_ordinal286 equ <__imp_mtxoci_ordinal286>

externdef __imp_mtxoci_ordinal287:PPROC
mtxoci_ordinal287 equ <__imp_mtxoci_ordinal287>

externdef __imp_mtxoci_ordinal288:PPROC
mtxoci_ordinal288 equ <__imp_mtxoci_ordinal288>

externdef __imp_mtxoci_ordinal289:PPROC
mtxoci_ordinal289 equ <__imp_mtxoci_ordinal289>

externdef __imp_mtxoci_ordinal290:PPROC
mtxoci_ordinal290 equ <__imp_mtxoci_ordinal290>

externdef __imp_mtxoci_ordinal291:PPROC
mtxoci_ordinal291 equ <__imp_mtxoci_ordinal291>

externdef __imp_mtxoci_ordinal292:PPROC
mtxoci_ordinal292 equ <__imp_mtxoci_ordinal292>

externdef __imp_mtxoci_ordinal293:PPROC
mtxoci_ordinal293 equ <__imp_mtxoci_ordinal293>

externdef __imp_mtxoci_ordinal294:PPROC
mtxoci_ordinal294 equ <__imp_mtxoci_ordinal294>

externdef __imp_mtxoci_ordinal295:PPROC
mtxoci_ordinal295 equ <__imp_mtxoci_ordinal295>

externdef __imp_mtxoci_ordinal296:PPROC
mtxoci_ordinal296 equ <__imp_mtxoci_ordinal296>

externdef __imp_mtxoci_ordinal297:PPROC
mtxoci_ordinal297 equ <__imp_mtxoci_ordinal297>

externdef __imp_mtxoci_ordinal298:PPROC
mtxoci_ordinal298 equ <__imp_mtxoci_ordinal298>

externdef __imp_mtxoci_ordinal299:PPROC
mtxoci_ordinal299 equ <__imp_mtxoci_ordinal299>

externdef __imp_mtxoci_ordinal300:PPROC
mtxoci_ordinal300 equ <__imp_mtxoci_ordinal300>

externdef __imp_mtxoci_ordinal301:PPROC
mtxoci_ordinal301 equ <__imp_mtxoci_ordinal301>

externdef __imp_mtxoci_ordinal302:PPROC
mtxoci_ordinal302 equ <__imp_mtxoci_ordinal302>

externdef __imp_mtxoci_ordinal303:PPROC
mtxoci_ordinal303 equ <__imp_mtxoci_ordinal303>

externdef __imp_mtxoci_ordinal304:PPROC
mtxoci_ordinal304 equ <__imp_mtxoci_ordinal304>

externdef __imp_mtxoci_ordinal305:PPROC
mtxoci_ordinal305 equ <__imp_mtxoci_ordinal305>

externdef __imp_mtxoci_ordinal306:PPROC
mtxoci_ordinal306 equ <__imp_mtxoci_ordinal306>

externdef __imp_mtxoci_ordinal307:PPROC
mtxoci_ordinal307 equ <__imp_mtxoci_ordinal307>

externdef __imp_mtxoci_ordinal308:PPROC
mtxoci_ordinal308 equ <__imp_mtxoci_ordinal308>

externdef __imp_mtxoci_ordinal309:PPROC
mtxoci_ordinal309 equ <__imp_mtxoci_ordinal309>

externdef __imp_mtxoci_ordinal30:PPROC
mtxoci_ordinal30 equ <__imp_mtxoci_ordinal30>

externdef __imp_mtxoci_ordinal310:PPROC
mtxoci_ordinal310 equ <__imp_mtxoci_ordinal310>

externdef __imp_mtxoci_ordinal311:PPROC
mtxoci_ordinal311 equ <__imp_mtxoci_ordinal311>

externdef __imp_mtxoci_ordinal312:PPROC
mtxoci_ordinal312 equ <__imp_mtxoci_ordinal312>

externdef __imp_mtxoci_ordinal313:PPROC
mtxoci_ordinal313 equ <__imp_mtxoci_ordinal313>

externdef __imp_mtxoci_ordinal314:PPROC
mtxoci_ordinal314 equ <__imp_mtxoci_ordinal314>

externdef __imp_mtxoci_ordinal315:PPROC
mtxoci_ordinal315 equ <__imp_mtxoci_ordinal315>

externdef __imp_mtxoci_ordinal316:PPROC
mtxoci_ordinal316 equ <__imp_mtxoci_ordinal316>

externdef __imp_mtxoci_ordinal317:PPROC
mtxoci_ordinal317 equ <__imp_mtxoci_ordinal317>

externdef __imp_mtxoci_ordinal318:PPROC
mtxoci_ordinal318 equ <__imp_mtxoci_ordinal318>

externdef __imp_mtxoci_ordinal319:PPROC
mtxoci_ordinal319 equ <__imp_mtxoci_ordinal319>

externdef __imp_mtxoci_ordinal31:PPROC
mtxoci_ordinal31 equ <__imp_mtxoci_ordinal31>

externdef __imp_mtxoci_ordinal320:PPROC
mtxoci_ordinal320 equ <__imp_mtxoci_ordinal320>

externdef __imp_mtxoci_ordinal321:PPROC
mtxoci_ordinal321 equ <__imp_mtxoci_ordinal321>

externdef __imp_mtxoci_ordinal322:PPROC
mtxoci_ordinal322 equ <__imp_mtxoci_ordinal322>

externdef __imp_mtxoci_ordinal323:PPROC
mtxoci_ordinal323 equ <__imp_mtxoci_ordinal323>

externdef __imp_mtxoci_ordinal324:PPROC
mtxoci_ordinal324 equ <__imp_mtxoci_ordinal324>

externdef __imp_mtxoci_ordinal325:PPROC
mtxoci_ordinal325 equ <__imp_mtxoci_ordinal325>

externdef __imp_mtxoci_ordinal326:PPROC
mtxoci_ordinal326 equ <__imp_mtxoci_ordinal326>

externdef __imp_mtxoci_ordinal327:PPROC
mtxoci_ordinal327 equ <__imp_mtxoci_ordinal327>

externdef __imp_mtxoci_ordinal328:PPROC
mtxoci_ordinal328 equ <__imp_mtxoci_ordinal328>

externdef __imp_mtxoci_ordinal329:PPROC
mtxoci_ordinal329 equ <__imp_mtxoci_ordinal329>

externdef __imp_mtxoci_ordinal32:PPROC
mtxoci_ordinal32 equ <__imp_mtxoci_ordinal32>

externdef __imp_mtxoci_ordinal330:PPROC
mtxoci_ordinal330 equ <__imp_mtxoci_ordinal330>

externdef __imp_mtxoci_ordinal331:PPROC
mtxoci_ordinal331 equ <__imp_mtxoci_ordinal331>

externdef __imp_mtxoci_ordinal332:PPROC
mtxoci_ordinal332 equ <__imp_mtxoci_ordinal332>

externdef __imp_mtxoci_ordinal333:PPROC
mtxoci_ordinal333 equ <__imp_mtxoci_ordinal333>

externdef __imp_mtxoci_ordinal334:PPROC
mtxoci_ordinal334 equ <__imp_mtxoci_ordinal334>

externdef __imp_mtxoci_ordinal335:PPROC
mtxoci_ordinal335 equ <__imp_mtxoci_ordinal335>

externdef __imp_mtxoci_ordinal336:PPROC
mtxoci_ordinal336 equ <__imp_mtxoci_ordinal336>

externdef __imp_mtxoci_ordinal337:PPROC
mtxoci_ordinal337 equ <__imp_mtxoci_ordinal337>

externdef __imp_mtxoci_ordinal338:PPROC
mtxoci_ordinal338 equ <__imp_mtxoci_ordinal338>

externdef __imp_mtxoci_ordinal339:PPROC
mtxoci_ordinal339 equ <__imp_mtxoci_ordinal339>

externdef __imp_mtxoci_ordinal33:PPROC
mtxoci_ordinal33 equ <__imp_mtxoci_ordinal33>

externdef __imp_mtxoci_ordinal340:PPROC
mtxoci_ordinal340 equ <__imp_mtxoci_ordinal340>

externdef __imp_mtxoci_ordinal341:PPROC
mtxoci_ordinal341 equ <__imp_mtxoci_ordinal341>

externdef __imp_mtxoci_ordinal342:PPROC
mtxoci_ordinal342 equ <__imp_mtxoci_ordinal342>

externdef __imp_mtxoci_ordinal343:PPROC
mtxoci_ordinal343 equ <__imp_mtxoci_ordinal343>

externdef __imp_mtxoci_ordinal344:PPROC
mtxoci_ordinal344 equ <__imp_mtxoci_ordinal344>

externdef __imp_mtxoci_ordinal345:PPROC
mtxoci_ordinal345 equ <__imp_mtxoci_ordinal345>

externdef __imp_mtxoci_ordinal346:PPROC
mtxoci_ordinal346 equ <__imp_mtxoci_ordinal346>

externdef __imp_mtxoci_ordinal347:PPROC
mtxoci_ordinal347 equ <__imp_mtxoci_ordinal347>

externdef __imp_mtxoci_ordinal348:PPROC
mtxoci_ordinal348 equ <__imp_mtxoci_ordinal348>

externdef __imp_mtxoci_ordinal349:PPROC
mtxoci_ordinal349 equ <__imp_mtxoci_ordinal349>

externdef __imp_mtxoci_ordinal34:PPROC
mtxoci_ordinal34 equ <__imp_mtxoci_ordinal34>

externdef __imp_mtxoci_ordinal350:PPROC
mtxoci_ordinal350 equ <__imp_mtxoci_ordinal350>

externdef __imp_mtxoci_ordinal351:PPROC
mtxoci_ordinal351 equ <__imp_mtxoci_ordinal351>

externdef __imp_mtxoci_ordinal352:PPROC
mtxoci_ordinal352 equ <__imp_mtxoci_ordinal352>

externdef __imp_mtxoci_ordinal353:PPROC
mtxoci_ordinal353 equ <__imp_mtxoci_ordinal353>

externdef __imp_mtxoci_ordinal354:PPROC
mtxoci_ordinal354 equ <__imp_mtxoci_ordinal354>

externdef __imp_mtxoci_ordinal355:PPROC
mtxoci_ordinal355 equ <__imp_mtxoci_ordinal355>

externdef __imp_mtxoci_ordinal356:PPROC
mtxoci_ordinal356 equ <__imp_mtxoci_ordinal356>

externdef __imp_mtxoci_ordinal357:PPROC
mtxoci_ordinal357 equ <__imp_mtxoci_ordinal357>

externdef __imp_mtxoci_ordinal358:PPROC
mtxoci_ordinal358 equ <__imp_mtxoci_ordinal358>

externdef __imp_mtxoci_ordinal359:PPROC
mtxoci_ordinal359 equ <__imp_mtxoci_ordinal359>

externdef __imp_mtxoci_ordinal35:PPROC
mtxoci_ordinal35 equ <__imp_mtxoci_ordinal35>

externdef __imp_mtxoci_ordinal360:PPROC
mtxoci_ordinal360 equ <__imp_mtxoci_ordinal360>

externdef __imp_mtxoci_ordinal361:PPROC
mtxoci_ordinal361 equ <__imp_mtxoci_ordinal361>

externdef __imp_mtxoci_ordinal362:PPROC
mtxoci_ordinal362 equ <__imp_mtxoci_ordinal362>

externdef __imp_mtxoci_ordinal363:PPROC
mtxoci_ordinal363 equ <__imp_mtxoci_ordinal363>

externdef __imp_mtxoci_ordinal364:PPROC
mtxoci_ordinal364 equ <__imp_mtxoci_ordinal364>

externdef __imp_mtxoci_ordinal365:PPROC
mtxoci_ordinal365 equ <__imp_mtxoci_ordinal365>

externdef __imp_mtxoci_ordinal366:PPROC
mtxoci_ordinal366 equ <__imp_mtxoci_ordinal366>

externdef __imp_mtxoci_ordinal367:PPROC
mtxoci_ordinal367 equ <__imp_mtxoci_ordinal367>

externdef __imp_mtxoci_ordinal368:PPROC
mtxoci_ordinal368 equ <__imp_mtxoci_ordinal368>

externdef __imp_mtxoci_ordinal369:PPROC
mtxoci_ordinal369 equ <__imp_mtxoci_ordinal369>

externdef __imp_mtxoci_ordinal36:PPROC
mtxoci_ordinal36 equ <__imp_mtxoci_ordinal36>

externdef __imp_mtxoci_ordinal370:PPROC
mtxoci_ordinal370 equ <__imp_mtxoci_ordinal370>

externdef __imp_mtxoci_ordinal371:PPROC
mtxoci_ordinal371 equ <__imp_mtxoci_ordinal371>

externdef __imp_mtxoci_ordinal372:PPROC
mtxoci_ordinal372 equ <__imp_mtxoci_ordinal372>

externdef __imp_mtxoci_ordinal373:PPROC
mtxoci_ordinal373 equ <__imp_mtxoci_ordinal373>

externdef __imp_mtxoci_ordinal374:PPROC
mtxoci_ordinal374 equ <__imp_mtxoci_ordinal374>

externdef __imp_mtxoci_ordinal375:PPROC
mtxoci_ordinal375 equ <__imp_mtxoci_ordinal375>

externdef __imp_mtxoci_ordinal376:PPROC
mtxoci_ordinal376 equ <__imp_mtxoci_ordinal376>

externdef __imp_mtxoci_ordinal377:PPROC
mtxoci_ordinal377 equ <__imp_mtxoci_ordinal377>

externdef __imp_mtxoci_ordinal378:PPROC
mtxoci_ordinal378 equ <__imp_mtxoci_ordinal378>

externdef __imp_mtxoci_ordinal379:PPROC
mtxoci_ordinal379 equ <__imp_mtxoci_ordinal379>

externdef __imp_mtxoci_ordinal380:PPROC
mtxoci_ordinal380 equ <__imp_mtxoci_ordinal380>

externdef __imp_mtxoci_ordinal381:PPROC
mtxoci_ordinal381 equ <__imp_mtxoci_ordinal381>

externdef __imp_mtxoci_ordinal382:PPROC
mtxoci_ordinal382 equ <__imp_mtxoci_ordinal382>

externdef __imp_mtxoci_ordinal383:PPROC
mtxoci_ordinal383 equ <__imp_mtxoci_ordinal383>

externdef __imp_mtxoci_ordinal384:PPROC
mtxoci_ordinal384 equ <__imp_mtxoci_ordinal384>

externdef __imp_mtxoci_ordinal385:PPROC
mtxoci_ordinal385 equ <__imp_mtxoci_ordinal385>

externdef __imp_mtxoci_ordinal386:PPROC
mtxoci_ordinal386 equ <__imp_mtxoci_ordinal386>

externdef __imp_mtxoci_ordinal387:PPROC
mtxoci_ordinal387 equ <__imp_mtxoci_ordinal387>

externdef __imp_mtxoci_ordinal388:PPROC
mtxoci_ordinal388 equ <__imp_mtxoci_ordinal388>

externdef __imp_mtxoci_ordinal389:PPROC
mtxoci_ordinal389 equ <__imp_mtxoci_ordinal389>

externdef __imp_mtxoci_ordinal390:PPROC
mtxoci_ordinal390 equ <__imp_mtxoci_ordinal390>

externdef __imp_mtxoci_ordinal391:PPROC
mtxoci_ordinal391 equ <__imp_mtxoci_ordinal391>

externdef __imp_mtxoci_ordinal392:PPROC
mtxoci_ordinal392 equ <__imp_mtxoci_ordinal392>

externdef __imp_mtxoci_ordinal393:PPROC
mtxoci_ordinal393 equ <__imp_mtxoci_ordinal393>

externdef __imp_mtxoci_ordinal394:PPROC
mtxoci_ordinal394 equ <__imp_mtxoci_ordinal394>

externdef __imp_mtxoci_ordinal395:PPROC
mtxoci_ordinal395 equ <__imp_mtxoci_ordinal395>

externdef __imp_mtxoci_ordinal396:PPROC
mtxoci_ordinal396 equ <__imp_mtxoci_ordinal396>

externdef __imp_mtxoci_ordinal397:PPROC
mtxoci_ordinal397 equ <__imp_mtxoci_ordinal397>

externdef __imp_mtxoci_ordinal398:PPROC
mtxoci_ordinal398 equ <__imp_mtxoci_ordinal398>

externdef __imp_mtxoci_ordinal399:PPROC
mtxoci_ordinal399 equ <__imp_mtxoci_ordinal399>

externdef __imp_mtxoci_ordinal400:PPROC
mtxoci_ordinal400 equ <__imp_mtxoci_ordinal400>

externdef __imp_mtxoci_ordinal401:PPROC
mtxoci_ordinal401 equ <__imp_mtxoci_ordinal401>

externdef __imp_mtxoci_ordinal402:PPROC
mtxoci_ordinal402 equ <__imp_mtxoci_ordinal402>

externdef __imp_mtxoci_ordinal403:PPROC
mtxoci_ordinal403 equ <__imp_mtxoci_ordinal403>

externdef __imp_mtxoci_ordinal404:PPROC
mtxoci_ordinal404 equ <__imp_mtxoci_ordinal404>

externdef __imp_mtxoci_ordinal405:PPROC
mtxoci_ordinal405 equ <__imp_mtxoci_ordinal405>

externdef __imp_mtxoci_ordinal406:PPROC
mtxoci_ordinal406 equ <__imp_mtxoci_ordinal406>

externdef __imp_mtxoci_ordinal407:PPROC
mtxoci_ordinal407 equ <__imp_mtxoci_ordinal407>

externdef __imp_mtxoci_ordinal408:PPROC
mtxoci_ordinal408 equ <__imp_mtxoci_ordinal408>

externdef __imp_mtxoci_ordinal409:PPROC
mtxoci_ordinal409 equ <__imp_mtxoci_ordinal409>

externdef __imp_mtxoci_ordinal410:PPROC
mtxoci_ordinal410 equ <__imp_mtxoci_ordinal410>

externdef __imp_mtxoci_ordinal411:PPROC
mtxoci_ordinal411 equ <__imp_mtxoci_ordinal411>

externdef __imp_mtxoci_ordinal412:PPROC
mtxoci_ordinal412 equ <__imp_mtxoci_ordinal412>

externdef __imp_mtxoci_ordinal413:PPROC
mtxoci_ordinal413 equ <__imp_mtxoci_ordinal413>

externdef __imp_mtxoci_ordinal414:PPROC
mtxoci_ordinal414 equ <__imp_mtxoci_ordinal414>

externdef __imp_mtxoci_ordinal415:PPROC
mtxoci_ordinal415 equ <__imp_mtxoci_ordinal415>

externdef __imp_mtxoci_ordinal416:PPROC
mtxoci_ordinal416 equ <__imp_mtxoci_ordinal416>

externdef __imp_mtxoci_ordinal417:PPROC
mtxoci_ordinal417 equ <__imp_mtxoci_ordinal417>

externdef __imp_mtxoci_ordinal418:PPROC
mtxoci_ordinal418 equ <__imp_mtxoci_ordinal418>

externdef __imp_mtxoci_ordinal419:PPROC
mtxoci_ordinal419 equ <__imp_mtxoci_ordinal419>

externdef __imp_mtxoci_ordinal420:PPROC
mtxoci_ordinal420 equ <__imp_mtxoci_ordinal420>

externdef __imp_mtxoci_ordinal421:PPROC
mtxoci_ordinal421 equ <__imp_mtxoci_ordinal421>

externdef __imp_mtxoci_ordinal422:PPROC
mtxoci_ordinal422 equ <__imp_mtxoci_ordinal422>

externdef __imp_mtxoci_ordinal423:PPROC
mtxoci_ordinal423 equ <__imp_mtxoci_ordinal423>

externdef __imp_mtxoci_ordinal424:PPROC
mtxoci_ordinal424 equ <__imp_mtxoci_ordinal424>

externdef __imp_mtxoci_ordinal425:PPROC
mtxoci_ordinal425 equ <__imp_mtxoci_ordinal425>

externdef __imp_mtxoci_ordinal426:PPROC
mtxoci_ordinal426 equ <__imp_mtxoci_ordinal426>

externdef __imp_mtxoci_ordinal427:PPROC
mtxoci_ordinal427 equ <__imp_mtxoci_ordinal427>

externdef __imp_mtxoci_ordinal428:PPROC
mtxoci_ordinal428 equ <__imp_mtxoci_ordinal428>

externdef __imp_mtxoci_ordinal429:PPROC
mtxoci_ordinal429 equ <__imp_mtxoci_ordinal429>

externdef __imp_mtxoci_ordinal42:PPROC
mtxoci_ordinal42 equ <__imp_mtxoci_ordinal42>

externdef __imp_mtxoci_ordinal430:PPROC
mtxoci_ordinal430 equ <__imp_mtxoci_ordinal430>

externdef __imp_mtxoci_ordinal431:PPROC
mtxoci_ordinal431 equ <__imp_mtxoci_ordinal431>

externdef __imp_mtxoci_ordinal432:PPROC
mtxoci_ordinal432 equ <__imp_mtxoci_ordinal432>

externdef __imp_mtxoci_ordinal433:PPROC
mtxoci_ordinal433 equ <__imp_mtxoci_ordinal433>

externdef __imp_mtxoci_ordinal434:PPROC
mtxoci_ordinal434 equ <__imp_mtxoci_ordinal434>

externdef __imp_mtxoci_ordinal435:PPROC
mtxoci_ordinal435 equ <__imp_mtxoci_ordinal435>

externdef __imp_mtxoci_ordinal436:PPROC
mtxoci_ordinal436 equ <__imp_mtxoci_ordinal436>

externdef __imp_mtxoci_ordinal437:PPROC
mtxoci_ordinal437 equ <__imp_mtxoci_ordinal437>

externdef __imp_mtxoci_ordinal438:PPROC
mtxoci_ordinal438 equ <__imp_mtxoci_ordinal438>

externdef __imp_mtxoci_ordinal439:PPROC
mtxoci_ordinal439 equ <__imp_mtxoci_ordinal439>

externdef __imp_mtxoci_ordinal43:PPROC
mtxoci_ordinal43 equ <__imp_mtxoci_ordinal43>

externdef __imp_mtxoci_ordinal440:PPROC
mtxoci_ordinal440 equ <__imp_mtxoci_ordinal440>

externdef __imp_mtxoci_ordinal441:PPROC
mtxoci_ordinal441 equ <__imp_mtxoci_ordinal441>

externdef __imp_mtxoci_ordinal442:PPROC
mtxoci_ordinal442 equ <__imp_mtxoci_ordinal442>

externdef __imp_mtxoci_ordinal443:PPROC
mtxoci_ordinal443 equ <__imp_mtxoci_ordinal443>

externdef __imp_mtxoci_ordinal444:PPROC
mtxoci_ordinal444 equ <__imp_mtxoci_ordinal444>

externdef __imp_mtxoci_ordinal445:PPROC
mtxoci_ordinal445 equ <__imp_mtxoci_ordinal445>

externdef __imp_mtxoci_ordinal446:PPROC
mtxoci_ordinal446 equ <__imp_mtxoci_ordinal446>

externdef __imp_mtxoci_ordinal447:PPROC
mtxoci_ordinal447 equ <__imp_mtxoci_ordinal447>

externdef __imp_mtxoci_ordinal448:PPROC
mtxoci_ordinal448 equ <__imp_mtxoci_ordinal448>

externdef __imp_mtxoci_ordinal449:PPROC
mtxoci_ordinal449 equ <__imp_mtxoci_ordinal449>

externdef __imp_mtxoci_ordinal44:PPROC
mtxoci_ordinal44 equ <__imp_mtxoci_ordinal44>

externdef __imp_mtxoci_ordinal450:PPROC
mtxoci_ordinal450 equ <__imp_mtxoci_ordinal450>

externdef __imp_mtxoci_ordinal451:PPROC
mtxoci_ordinal451 equ <__imp_mtxoci_ordinal451>

externdef __imp_mtxoci_ordinal452:PPROC
mtxoci_ordinal452 equ <__imp_mtxoci_ordinal452>

externdef __imp_mtxoci_ordinal453:PPROC
mtxoci_ordinal453 equ <__imp_mtxoci_ordinal453>

externdef __imp_mtxoci_ordinal454:PPROC
mtxoci_ordinal454 equ <__imp_mtxoci_ordinal454>

externdef __imp_mtxoci_ordinal455:PPROC
mtxoci_ordinal455 equ <__imp_mtxoci_ordinal455>

externdef __imp_mtxoci_ordinal456:PPROC
mtxoci_ordinal456 equ <__imp_mtxoci_ordinal456>

externdef __imp_mtxoci_ordinal457:PPROC
mtxoci_ordinal457 equ <__imp_mtxoci_ordinal457>

externdef __imp_mtxoci_ordinal458:PPROC
mtxoci_ordinal458 equ <__imp_mtxoci_ordinal458>

externdef __imp_mtxoci_ordinal459:PPROC
mtxoci_ordinal459 equ <__imp_mtxoci_ordinal459>

externdef __imp_mtxoci_ordinal45:PPROC
mtxoci_ordinal45 equ <__imp_mtxoci_ordinal45>

externdef __imp_mtxoci_ordinal460:PPROC
mtxoci_ordinal460 equ <__imp_mtxoci_ordinal460>

externdef __imp_mtxoci_ordinal461:PPROC
mtxoci_ordinal461 equ <__imp_mtxoci_ordinal461>

externdef __imp_mtxoci_ordinal462:PPROC
mtxoci_ordinal462 equ <__imp_mtxoci_ordinal462>

externdef __imp_mtxoci_ordinal463:PPROC
mtxoci_ordinal463 equ <__imp_mtxoci_ordinal463>

externdef __imp_mtxoci_ordinal464:PPROC
mtxoci_ordinal464 equ <__imp_mtxoci_ordinal464>

externdef __imp_mtxoci_ordinal465:PPROC
mtxoci_ordinal465 equ <__imp_mtxoci_ordinal465>

externdef __imp_mtxoci_ordinal466:PPROC
mtxoci_ordinal466 equ <__imp_mtxoci_ordinal466>

externdef __imp_mtxoci_ordinal467:PPROC
mtxoci_ordinal467 equ <__imp_mtxoci_ordinal467>

externdef __imp_mtxoci_ordinal468:PPROC
mtxoci_ordinal468 equ <__imp_mtxoci_ordinal468>

externdef __imp_mtxoci_ordinal469:PPROC
mtxoci_ordinal469 equ <__imp_mtxoci_ordinal469>

externdef __imp_mtxoci_ordinal46:PPROC
mtxoci_ordinal46 equ <__imp_mtxoci_ordinal46>

externdef __imp_mtxoci_ordinal470:PPROC
mtxoci_ordinal470 equ <__imp_mtxoci_ordinal470>

externdef __imp_mtxoci_ordinal471:PPROC
mtxoci_ordinal471 equ <__imp_mtxoci_ordinal471>

externdef __imp_mtxoci_ordinal472:PPROC
mtxoci_ordinal472 equ <__imp_mtxoci_ordinal472>

externdef __imp_mtxoci_ordinal473:PPROC
mtxoci_ordinal473 equ <__imp_mtxoci_ordinal473>

externdef __imp_mtxoci_ordinal474:PPROC
mtxoci_ordinal474 equ <__imp_mtxoci_ordinal474>

externdef __imp_mtxoci_ordinal475:PPROC
mtxoci_ordinal475 equ <__imp_mtxoci_ordinal475>

externdef __imp_mtxoci_ordinal476:PPROC
mtxoci_ordinal476 equ <__imp_mtxoci_ordinal476>

externdef __imp_mtxoci_ordinal477:PPROC
mtxoci_ordinal477 equ <__imp_mtxoci_ordinal477>

externdef __imp_mtxoci_ordinal478:PPROC
mtxoci_ordinal478 equ <__imp_mtxoci_ordinal478>

externdef __imp_mtxoci_ordinal479:PPROC
mtxoci_ordinal479 equ <__imp_mtxoci_ordinal479>

externdef __imp_mtxoci_ordinal47:PPROC
mtxoci_ordinal47 equ <__imp_mtxoci_ordinal47>

externdef __imp_mtxoci_ordinal480:PPROC
mtxoci_ordinal480 equ <__imp_mtxoci_ordinal480>

externdef __imp_mtxoci_ordinal481:PPROC
mtxoci_ordinal481 equ <__imp_mtxoci_ordinal481>

externdef __imp_mtxoci_ordinal482:PPROC
mtxoci_ordinal482 equ <__imp_mtxoci_ordinal482>

externdef __imp_mtxoci_ordinal483:PPROC
mtxoci_ordinal483 equ <__imp_mtxoci_ordinal483>

externdef __imp_mtxoci_ordinal484:PPROC
mtxoci_ordinal484 equ <__imp_mtxoci_ordinal484>

externdef __imp_mtxoci_ordinal485:PPROC
mtxoci_ordinal485 equ <__imp_mtxoci_ordinal485>

externdef __imp_mtxoci_ordinal486:PPROC
mtxoci_ordinal486 equ <__imp_mtxoci_ordinal486>

externdef __imp_mtxoci_ordinal487:PPROC
mtxoci_ordinal487 equ <__imp_mtxoci_ordinal487>

externdef __imp_mtxoci_ordinal488:PPROC
mtxoci_ordinal488 equ <__imp_mtxoci_ordinal488>

externdef __imp_mtxoci_ordinal489:PPROC
mtxoci_ordinal489 equ <__imp_mtxoci_ordinal489>

externdef __imp_mtxoci_ordinal48:PPROC
mtxoci_ordinal48 equ <__imp_mtxoci_ordinal48>

externdef __imp_mtxoci_ordinal490:PPROC
mtxoci_ordinal490 equ <__imp_mtxoci_ordinal490>

externdef __imp_mtxoci_ordinal491:PPROC
mtxoci_ordinal491 equ <__imp_mtxoci_ordinal491>

externdef __imp_mtxoci_ordinal492:PPROC
mtxoci_ordinal492 equ <__imp_mtxoci_ordinal492>

externdef __imp_mtxoci_ordinal493:PPROC
mtxoci_ordinal493 equ <__imp_mtxoci_ordinal493>

externdef __imp_mtxoci_ordinal494:PPROC
mtxoci_ordinal494 equ <__imp_mtxoci_ordinal494>

externdef __imp_mtxoci_ordinal495:PPROC
mtxoci_ordinal495 equ <__imp_mtxoci_ordinal495>

externdef __imp_mtxoci_ordinal496:PPROC
mtxoci_ordinal496 equ <__imp_mtxoci_ordinal496>

externdef __imp_mtxoci_ordinal497:PPROC
mtxoci_ordinal497 equ <__imp_mtxoci_ordinal497>

externdef __imp_mtxoci_ordinal498:PPROC
mtxoci_ordinal498 equ <__imp_mtxoci_ordinal498>

externdef __imp_mtxoci_ordinal499:PPROC
mtxoci_ordinal499 equ <__imp_mtxoci_ordinal499>

externdef __imp_mtxoci_ordinal49:PPROC
mtxoci_ordinal49 equ <__imp_mtxoci_ordinal49>

externdef __imp_mtxoci_ordinal500:PPROC
mtxoci_ordinal500 equ <__imp_mtxoci_ordinal500>

externdef __imp_mtxoci_ordinal501:PPROC
mtxoci_ordinal501 equ <__imp_mtxoci_ordinal501>

externdef __imp_mtxoci_ordinal502:PPROC
mtxoci_ordinal502 equ <__imp_mtxoci_ordinal502>

externdef __imp_mtxoci_ordinal503:PPROC
mtxoci_ordinal503 equ <__imp_mtxoci_ordinal503>

externdef __imp_mtxoci_ordinal504:PPROC
mtxoci_ordinal504 equ <__imp_mtxoci_ordinal504>

externdef __imp_mtxoci_ordinal505:PPROC
mtxoci_ordinal505 equ <__imp_mtxoci_ordinal505>

externdef __imp_mtxoci_ordinal506:PPROC
mtxoci_ordinal506 equ <__imp_mtxoci_ordinal506>

externdef __imp_mtxoci_ordinal507:PPROC
mtxoci_ordinal507 equ <__imp_mtxoci_ordinal507>

externdef __imp_mtxoci_ordinal508:PPROC
mtxoci_ordinal508 equ <__imp_mtxoci_ordinal508>

externdef __imp_mtxoci_ordinal509:PPROC
mtxoci_ordinal509 equ <__imp_mtxoci_ordinal509>

externdef __imp_mtxoci_ordinal50:PPROC
mtxoci_ordinal50 equ <__imp_mtxoci_ordinal50>

externdef __imp_mtxoci_ordinal510:PPROC
mtxoci_ordinal510 equ <__imp_mtxoci_ordinal510>

externdef __imp_mtxoci_ordinal511:PPROC
mtxoci_ordinal511 equ <__imp_mtxoci_ordinal511>

externdef __imp_mtxoci_ordinal512:PPROC
mtxoci_ordinal512 equ <__imp_mtxoci_ordinal512>

externdef __imp_mtxoci_ordinal513:PPROC
mtxoci_ordinal513 equ <__imp_mtxoci_ordinal513>

externdef __imp_mtxoci_ordinal514:PPROC
mtxoci_ordinal514 equ <__imp_mtxoci_ordinal514>

externdef __imp_mtxoci_ordinal515:PPROC
mtxoci_ordinal515 equ <__imp_mtxoci_ordinal515>

externdef __imp_mtxoci_ordinal516:PPROC
mtxoci_ordinal516 equ <__imp_mtxoci_ordinal516>

externdef __imp_mtxoci_ordinal517:PPROC
mtxoci_ordinal517 equ <__imp_mtxoci_ordinal517>

externdef __imp_mtxoci_ordinal518:PPROC
mtxoci_ordinal518 equ <__imp_mtxoci_ordinal518>

externdef __imp_mtxoci_ordinal519:PPROC
mtxoci_ordinal519 equ <__imp_mtxoci_ordinal519>

externdef __imp_mtxoci_ordinal51:PPROC
mtxoci_ordinal51 equ <__imp_mtxoci_ordinal51>

externdef __imp_mtxoci_ordinal520:PPROC
mtxoci_ordinal520 equ <__imp_mtxoci_ordinal520>

externdef __imp_mtxoci_ordinal521:PPROC
mtxoci_ordinal521 equ <__imp_mtxoci_ordinal521>

externdef __imp_mtxoci_ordinal522:PPROC
mtxoci_ordinal522 equ <__imp_mtxoci_ordinal522>

externdef __imp_mtxoci_ordinal523:PPROC
mtxoci_ordinal523 equ <__imp_mtxoci_ordinal523>

externdef __imp_mtxoci_ordinal524:PPROC
mtxoci_ordinal524 equ <__imp_mtxoci_ordinal524>

externdef __imp_mtxoci_ordinal525:PPROC
mtxoci_ordinal525 equ <__imp_mtxoci_ordinal525>

externdef __imp_mtxoci_ordinal526:PPROC
mtxoci_ordinal526 equ <__imp_mtxoci_ordinal526>

externdef __imp_mtxoci_ordinal527:PPROC
mtxoci_ordinal527 equ <__imp_mtxoci_ordinal527>

externdef __imp_mtxoci_ordinal528:PPROC
mtxoci_ordinal528 equ <__imp_mtxoci_ordinal528>

externdef __imp_mtxoci_ordinal529:PPROC
mtxoci_ordinal529 equ <__imp_mtxoci_ordinal529>

externdef __imp_mtxoci_ordinal52:PPROC
mtxoci_ordinal52 equ <__imp_mtxoci_ordinal52>

externdef __imp_mtxoci_ordinal530:PPROC
mtxoci_ordinal530 equ <__imp_mtxoci_ordinal530>

externdef __imp_mtxoci_ordinal531:PPROC
mtxoci_ordinal531 equ <__imp_mtxoci_ordinal531>

externdef __imp_mtxoci_ordinal532:PPROC
mtxoci_ordinal532 equ <__imp_mtxoci_ordinal532>

externdef __imp_mtxoci_ordinal533:PPROC
mtxoci_ordinal533 equ <__imp_mtxoci_ordinal533>

externdef __imp_mtxoci_ordinal534:PPROC
mtxoci_ordinal534 equ <__imp_mtxoci_ordinal534>

externdef __imp_mtxoci_ordinal535:PPROC
mtxoci_ordinal535 equ <__imp_mtxoci_ordinal535>

externdef __imp_mtxoci_ordinal536:PPROC
mtxoci_ordinal536 equ <__imp_mtxoci_ordinal536>

externdef __imp_mtxoci_ordinal537:PPROC
mtxoci_ordinal537 equ <__imp_mtxoci_ordinal537>

externdef __imp_mtxoci_ordinal538:PPROC
mtxoci_ordinal538 equ <__imp_mtxoci_ordinal538>

externdef __imp_mtxoci_ordinal539:PPROC
mtxoci_ordinal539 equ <__imp_mtxoci_ordinal539>

externdef __imp_mtxoci_ordinal53:PPROC
mtxoci_ordinal53 equ <__imp_mtxoci_ordinal53>

externdef __imp_mtxoci_ordinal540:PPROC
mtxoci_ordinal540 equ <__imp_mtxoci_ordinal540>

externdef __imp_mtxoci_ordinal541:PPROC
mtxoci_ordinal541 equ <__imp_mtxoci_ordinal541>

externdef __imp_mtxoci_ordinal542:PPROC
mtxoci_ordinal542 equ <__imp_mtxoci_ordinal542>

externdef __imp_mtxoci_ordinal543:PPROC
mtxoci_ordinal543 equ <__imp_mtxoci_ordinal543>

externdef __imp_mtxoci_ordinal544:PPROC
mtxoci_ordinal544 equ <__imp_mtxoci_ordinal544>

externdef __imp_mtxoci_ordinal545:PPROC
mtxoci_ordinal545 equ <__imp_mtxoci_ordinal545>

externdef __imp_mtxoci_ordinal546:PPROC
mtxoci_ordinal546 equ <__imp_mtxoci_ordinal546>

externdef __imp_mtxoci_ordinal547:PPROC
mtxoci_ordinal547 equ <__imp_mtxoci_ordinal547>

externdef __imp_mtxoci_ordinal548:PPROC
mtxoci_ordinal548 equ <__imp_mtxoci_ordinal548>

externdef __imp_mtxoci_ordinal549:PPROC
mtxoci_ordinal549 equ <__imp_mtxoci_ordinal549>

externdef __imp_mtxoci_ordinal54:PPROC
mtxoci_ordinal54 equ <__imp_mtxoci_ordinal54>

externdef __imp_mtxoci_ordinal550:PPROC
mtxoci_ordinal550 equ <__imp_mtxoci_ordinal550>

externdef __imp_mtxoci_ordinal551:PPROC
mtxoci_ordinal551 equ <__imp_mtxoci_ordinal551>

externdef __imp_mtxoci_ordinal552:PPROC
mtxoci_ordinal552 equ <__imp_mtxoci_ordinal552>

externdef __imp_mtxoci_ordinal553:PPROC
mtxoci_ordinal553 equ <__imp_mtxoci_ordinal553>

externdef __imp_mtxoci_ordinal554:PPROC
mtxoci_ordinal554 equ <__imp_mtxoci_ordinal554>

externdef __imp_mtxoci_ordinal555:PPROC
mtxoci_ordinal555 equ <__imp_mtxoci_ordinal555>

externdef __imp_mtxoci_ordinal556:PPROC
mtxoci_ordinal556 equ <__imp_mtxoci_ordinal556>

externdef __imp_mtxoci_ordinal557:PPROC
mtxoci_ordinal557 equ <__imp_mtxoci_ordinal557>

externdef __imp_mtxoci_ordinal558:PPROC
mtxoci_ordinal558 equ <__imp_mtxoci_ordinal558>

externdef __imp_mtxoci_ordinal559:PPROC
mtxoci_ordinal559 equ <__imp_mtxoci_ordinal559>

externdef __imp_mtxoci_ordinal55:PPROC
mtxoci_ordinal55 equ <__imp_mtxoci_ordinal55>

externdef __imp_mtxoci_ordinal560:PPROC
mtxoci_ordinal560 equ <__imp_mtxoci_ordinal560>

externdef __imp_mtxoci_ordinal561:PPROC
mtxoci_ordinal561 equ <__imp_mtxoci_ordinal561>

externdef __imp_mtxoci_ordinal562:PPROC
mtxoci_ordinal562 equ <__imp_mtxoci_ordinal562>

externdef __imp_mtxoci_ordinal563:PPROC
mtxoci_ordinal563 equ <__imp_mtxoci_ordinal563>

externdef __imp_mtxoci_ordinal564:PPROC
mtxoci_ordinal564 equ <__imp_mtxoci_ordinal564>

externdef __imp_mtxoci_ordinal565:PPROC
mtxoci_ordinal565 equ <__imp_mtxoci_ordinal565>

externdef __imp_mtxoci_ordinal566:PPROC
mtxoci_ordinal566 equ <__imp_mtxoci_ordinal566>

externdef __imp_mtxoci_ordinal567:PPROC
mtxoci_ordinal567 equ <__imp_mtxoci_ordinal567>

externdef __imp_mtxoci_ordinal568:PPROC
mtxoci_ordinal568 equ <__imp_mtxoci_ordinal568>

externdef __imp_mtxoci_ordinal569:PPROC
mtxoci_ordinal569 equ <__imp_mtxoci_ordinal569>

externdef __imp_mtxoci_ordinal56:PPROC
mtxoci_ordinal56 equ <__imp_mtxoci_ordinal56>

externdef __imp_mtxoci_ordinal570:PPROC
mtxoci_ordinal570 equ <__imp_mtxoci_ordinal570>

externdef __imp_mtxoci_ordinal571:PPROC
mtxoci_ordinal571 equ <__imp_mtxoci_ordinal571>

externdef __imp_mtxoci_ordinal572:PPROC
mtxoci_ordinal572 equ <__imp_mtxoci_ordinal572>

externdef __imp_mtxoci_ordinal573:PPROC
mtxoci_ordinal573 equ <__imp_mtxoci_ordinal573>

externdef __imp_mtxoci_ordinal574:PPROC
mtxoci_ordinal574 equ <__imp_mtxoci_ordinal574>

externdef __imp_mtxoci_ordinal575:PPROC
mtxoci_ordinal575 equ <__imp_mtxoci_ordinal575>

externdef __imp_mtxoci_ordinal576:PPROC
mtxoci_ordinal576 equ <__imp_mtxoci_ordinal576>

externdef __imp_mtxoci_ordinal577:PPROC
mtxoci_ordinal577 equ <__imp_mtxoci_ordinal577>

externdef __imp_mtxoci_ordinal578:PPROC
mtxoci_ordinal578 equ <__imp_mtxoci_ordinal578>

externdef __imp_mtxoci_ordinal579:PPROC
mtxoci_ordinal579 equ <__imp_mtxoci_ordinal579>

externdef __imp_mtxoci_ordinal57:PPROC
mtxoci_ordinal57 equ <__imp_mtxoci_ordinal57>

externdef __imp_mtxoci_ordinal580:PPROC
mtxoci_ordinal580 equ <__imp_mtxoci_ordinal580>

externdef __imp_mtxoci_ordinal581:PPROC
mtxoci_ordinal581 equ <__imp_mtxoci_ordinal581>

externdef __imp_mtxoci_ordinal582:PPROC
mtxoci_ordinal582 equ <__imp_mtxoci_ordinal582>

externdef __imp_mtxoci_ordinal583:PPROC
mtxoci_ordinal583 equ <__imp_mtxoci_ordinal583>

externdef __imp_mtxoci_ordinal584:PPROC
mtxoci_ordinal584 equ <__imp_mtxoci_ordinal584>

externdef __imp_mtxoci_ordinal585:PPROC
mtxoci_ordinal585 equ <__imp_mtxoci_ordinal585>

externdef __imp_mtxoci_ordinal586:PPROC
mtxoci_ordinal586 equ <__imp_mtxoci_ordinal586>

externdef __imp_mtxoci_ordinal587:PPROC
mtxoci_ordinal587 equ <__imp_mtxoci_ordinal587>

externdef __imp_mtxoci_ordinal588:PPROC
mtxoci_ordinal588 equ <__imp_mtxoci_ordinal588>

externdef __imp_mtxoci_ordinal589:PPROC
mtxoci_ordinal589 equ <__imp_mtxoci_ordinal589>

externdef __imp_mtxoci_ordinal58:PPROC
mtxoci_ordinal58 equ <__imp_mtxoci_ordinal58>

externdef __imp_mtxoci_ordinal590:PPROC
mtxoci_ordinal590 equ <__imp_mtxoci_ordinal590>

externdef __imp_mtxoci_ordinal591:PPROC
mtxoci_ordinal591 equ <__imp_mtxoci_ordinal591>

externdef __imp_mtxoci_ordinal592:PPROC
mtxoci_ordinal592 equ <__imp_mtxoci_ordinal592>

externdef __imp_mtxoci_ordinal593:PPROC
mtxoci_ordinal593 equ <__imp_mtxoci_ordinal593>

externdef __imp_mtxoci_ordinal594:PPROC
mtxoci_ordinal594 equ <__imp_mtxoci_ordinal594>

externdef __imp_mtxoci_ordinal595:PPROC
mtxoci_ordinal595 equ <__imp_mtxoci_ordinal595>

externdef __imp_mtxoci_ordinal596:PPROC
mtxoci_ordinal596 equ <__imp_mtxoci_ordinal596>

externdef __imp_mtxoci_ordinal597:PPROC
mtxoci_ordinal597 equ <__imp_mtxoci_ordinal597>

externdef __imp_mtxoci_ordinal598:PPROC
mtxoci_ordinal598 equ <__imp_mtxoci_ordinal598>

externdef __imp_mtxoci_ordinal599:PPROC
mtxoci_ordinal599 equ <__imp_mtxoci_ordinal599>

externdef __imp_mtxoci_ordinal59:PPROC
mtxoci_ordinal59 equ <__imp_mtxoci_ordinal59>

externdef __imp_mtxoci_ordinal600:PPROC
mtxoci_ordinal600 equ <__imp_mtxoci_ordinal600>

externdef __imp_mtxoci_ordinal601:PPROC
mtxoci_ordinal601 equ <__imp_mtxoci_ordinal601>

externdef __imp_mtxoci_ordinal602:PPROC
mtxoci_ordinal602 equ <__imp_mtxoci_ordinal602>

externdef __imp_mtxoci_ordinal603:PPROC
mtxoci_ordinal603 equ <__imp_mtxoci_ordinal603>

externdef __imp_mtxoci_ordinal604:PPROC
mtxoci_ordinal604 equ <__imp_mtxoci_ordinal604>

externdef __imp_mtxoci_ordinal605:PPROC
mtxoci_ordinal605 equ <__imp_mtxoci_ordinal605>

externdef __imp_mtxoci_ordinal606:PPROC
mtxoci_ordinal606 equ <__imp_mtxoci_ordinal606>

externdef __imp_mtxoci_ordinal607:PPROC
mtxoci_ordinal607 equ <__imp_mtxoci_ordinal607>

externdef __imp_mtxoci_ordinal608:PPROC
mtxoci_ordinal608 equ <__imp_mtxoci_ordinal608>

externdef __imp_mtxoci_ordinal609:PPROC
mtxoci_ordinal609 equ <__imp_mtxoci_ordinal609>

externdef __imp_mtxoci_ordinal60:PPROC
mtxoci_ordinal60 equ <__imp_mtxoci_ordinal60>

externdef __imp_mtxoci_ordinal610:PPROC
mtxoci_ordinal610 equ <__imp_mtxoci_ordinal610>

externdef __imp_mtxoci_ordinal611:PPROC
mtxoci_ordinal611 equ <__imp_mtxoci_ordinal611>

externdef __imp_mtxoci_ordinal612:PPROC
mtxoci_ordinal612 equ <__imp_mtxoci_ordinal612>

externdef __imp_mtxoci_ordinal613:PPROC
mtxoci_ordinal613 equ <__imp_mtxoci_ordinal613>

externdef __imp_mtxoci_ordinal614:PPROC
mtxoci_ordinal614 equ <__imp_mtxoci_ordinal614>

externdef __imp_mtxoci_ordinal615:PPROC
mtxoci_ordinal615 equ <__imp_mtxoci_ordinal615>

externdef __imp_mtxoci_ordinal616:PPROC
mtxoci_ordinal616 equ <__imp_mtxoci_ordinal616>

externdef __imp_mtxoci_ordinal617:PPROC
mtxoci_ordinal617 equ <__imp_mtxoci_ordinal617>

externdef __imp_mtxoci_ordinal618:PPROC
mtxoci_ordinal618 equ <__imp_mtxoci_ordinal618>

externdef __imp_mtxoci_ordinal619:PPROC
mtxoci_ordinal619 equ <__imp_mtxoci_ordinal619>

externdef __imp_mtxoci_ordinal61:PPROC
mtxoci_ordinal61 equ <__imp_mtxoci_ordinal61>

externdef __imp_mtxoci_ordinal620:PPROC
mtxoci_ordinal620 equ <__imp_mtxoci_ordinal620>

externdef __imp_mtxoci_ordinal621:PPROC
mtxoci_ordinal621 equ <__imp_mtxoci_ordinal621>

externdef __imp_mtxoci_ordinal622:PPROC
mtxoci_ordinal622 equ <__imp_mtxoci_ordinal622>

externdef __imp_mtxoci_ordinal623:PPROC
mtxoci_ordinal623 equ <__imp_mtxoci_ordinal623>

externdef __imp_mtxoci_ordinal624:PPROC
mtxoci_ordinal624 equ <__imp_mtxoci_ordinal624>

externdef __imp_mtxoci_ordinal625:PPROC
mtxoci_ordinal625 equ <__imp_mtxoci_ordinal625>

externdef __imp_mtxoci_ordinal626:PPROC
mtxoci_ordinal626 equ <__imp_mtxoci_ordinal626>

externdef __imp_mtxoci_ordinal627:PPROC
mtxoci_ordinal627 equ <__imp_mtxoci_ordinal627>

externdef __imp_mtxoci_ordinal628:PPROC
mtxoci_ordinal628 equ <__imp_mtxoci_ordinal628>

externdef __imp_mtxoci_ordinal629:PPROC
mtxoci_ordinal629 equ <__imp_mtxoci_ordinal629>

externdef __imp_mtxoci_ordinal62:PPROC
mtxoci_ordinal62 equ <__imp_mtxoci_ordinal62>

externdef __imp_mtxoci_ordinal630:PPROC
mtxoci_ordinal630 equ <__imp_mtxoci_ordinal630>

externdef __imp_mtxoci_ordinal631:PPROC
mtxoci_ordinal631 equ <__imp_mtxoci_ordinal631>

externdef __imp_mtxoci_ordinal632:PPROC
mtxoci_ordinal632 equ <__imp_mtxoci_ordinal632>

externdef __imp_mtxoci_ordinal633:PPROC
mtxoci_ordinal633 equ <__imp_mtxoci_ordinal633>

externdef __imp_mtxoci_ordinal634:PPROC
mtxoci_ordinal634 equ <__imp_mtxoci_ordinal634>

externdef __imp_mtxoci_ordinal635:PPROC
mtxoci_ordinal635 equ <__imp_mtxoci_ordinal635>

externdef __imp_mtxoci_ordinal636:PPROC
mtxoci_ordinal636 equ <__imp_mtxoci_ordinal636>

externdef __imp_mtxoci_ordinal637:PPROC
mtxoci_ordinal637 equ <__imp_mtxoci_ordinal637>

externdef __imp_mtxoci_ordinal638:PPROC
mtxoci_ordinal638 equ <__imp_mtxoci_ordinal638>

externdef __imp_mtxoci_ordinal639:PPROC
mtxoci_ordinal639 equ <__imp_mtxoci_ordinal639>

externdef __imp_mtxoci_ordinal63:PPROC
mtxoci_ordinal63 equ <__imp_mtxoci_ordinal63>

externdef __imp_mtxoci_ordinal640:PPROC
mtxoci_ordinal640 equ <__imp_mtxoci_ordinal640>

externdef __imp_mtxoci_ordinal641:PPROC
mtxoci_ordinal641 equ <__imp_mtxoci_ordinal641>

externdef __imp_mtxoci_ordinal642:PPROC
mtxoci_ordinal642 equ <__imp_mtxoci_ordinal642>

externdef __imp_mtxoci_ordinal643:PPROC
mtxoci_ordinal643 equ <__imp_mtxoci_ordinal643>

externdef __imp_mtxoci_ordinal644:PPROC
mtxoci_ordinal644 equ <__imp_mtxoci_ordinal644>

externdef __imp_mtxoci_ordinal645:PPROC
mtxoci_ordinal645 equ <__imp_mtxoci_ordinal645>

externdef __imp_mtxoci_ordinal646:PPROC
mtxoci_ordinal646 equ <__imp_mtxoci_ordinal646>

externdef __imp_mtxoci_ordinal647:PPROC
mtxoci_ordinal647 equ <__imp_mtxoci_ordinal647>

externdef __imp_mtxoci_ordinal648:PPROC
mtxoci_ordinal648 equ <__imp_mtxoci_ordinal648>

externdef __imp_mtxoci_ordinal649:PPROC
mtxoci_ordinal649 equ <__imp_mtxoci_ordinal649>

externdef __imp_mtxoci_ordinal64:PPROC
mtxoci_ordinal64 equ <__imp_mtxoci_ordinal64>

externdef __imp_mtxoci_ordinal650:PPROC
mtxoci_ordinal650 equ <__imp_mtxoci_ordinal650>

externdef __imp_mtxoci_ordinal651:PPROC
mtxoci_ordinal651 equ <__imp_mtxoci_ordinal651>

externdef __imp_mtxoci_ordinal652:PPROC
mtxoci_ordinal652 equ <__imp_mtxoci_ordinal652>

externdef __imp_mtxoci_ordinal653:PPROC
mtxoci_ordinal653 equ <__imp_mtxoci_ordinal653>

externdef __imp_mtxoci_ordinal654:PPROC
mtxoci_ordinal654 equ <__imp_mtxoci_ordinal654>

externdef __imp_mtxoci_ordinal655:PPROC
mtxoci_ordinal655 equ <__imp_mtxoci_ordinal655>

externdef __imp_mtxoci_ordinal656:PPROC
mtxoci_ordinal656 equ <__imp_mtxoci_ordinal656>

externdef __imp_mtxoci_ordinal657:PPROC
mtxoci_ordinal657 equ <__imp_mtxoci_ordinal657>

externdef __imp_mtxoci_ordinal658:PPROC
mtxoci_ordinal658 equ <__imp_mtxoci_ordinal658>

externdef __imp_mtxoci_ordinal659:PPROC
mtxoci_ordinal659 equ <__imp_mtxoci_ordinal659>

externdef __imp_mtxoci_ordinal65:PPROC
mtxoci_ordinal65 equ <__imp_mtxoci_ordinal65>

externdef __imp_mtxoci_ordinal660:PPROC
mtxoci_ordinal660 equ <__imp_mtxoci_ordinal660>

externdef __imp_mtxoci_ordinal661:PPROC
mtxoci_ordinal661 equ <__imp_mtxoci_ordinal661>

externdef __imp_mtxoci_ordinal662:PPROC
mtxoci_ordinal662 equ <__imp_mtxoci_ordinal662>

externdef __imp_mtxoci_ordinal663:PPROC
mtxoci_ordinal663 equ <__imp_mtxoci_ordinal663>

externdef __imp_mtxoci_ordinal664:PPROC
mtxoci_ordinal664 equ <__imp_mtxoci_ordinal664>

externdef __imp_mtxoci_ordinal665:PPROC
mtxoci_ordinal665 equ <__imp_mtxoci_ordinal665>

externdef __imp_mtxoci_ordinal666:PPROC
mtxoci_ordinal666 equ <__imp_mtxoci_ordinal666>

externdef __imp_mtxoci_ordinal667:PPROC
mtxoci_ordinal667 equ <__imp_mtxoci_ordinal667>

externdef __imp_mtxoci_ordinal668:PPROC
mtxoci_ordinal668 equ <__imp_mtxoci_ordinal668>

externdef __imp_mtxoci_ordinal669:PPROC
mtxoci_ordinal669 equ <__imp_mtxoci_ordinal669>

externdef __imp_mtxoci_ordinal66:PPROC
mtxoci_ordinal66 equ <__imp_mtxoci_ordinal66>

externdef __imp_mtxoci_ordinal670:PPROC
mtxoci_ordinal670 equ <__imp_mtxoci_ordinal670>

externdef __imp_mtxoci_ordinal671:PPROC
mtxoci_ordinal671 equ <__imp_mtxoci_ordinal671>

externdef __imp_mtxoci_ordinal672:PPROC
mtxoci_ordinal672 equ <__imp_mtxoci_ordinal672>

externdef __imp_mtxoci_ordinal673:PPROC
mtxoci_ordinal673 equ <__imp_mtxoci_ordinal673>

externdef __imp_mtxoci_ordinal674:PPROC
mtxoci_ordinal674 equ <__imp_mtxoci_ordinal674>

externdef __imp_mtxoci_ordinal675:PPROC
mtxoci_ordinal675 equ <__imp_mtxoci_ordinal675>

externdef __imp_mtxoci_ordinal676:PPROC
mtxoci_ordinal676 equ <__imp_mtxoci_ordinal676>

externdef __imp_mtxoci_ordinal677:PPROC
mtxoci_ordinal677 equ <__imp_mtxoci_ordinal677>

externdef __imp_mtxoci_ordinal678:PPROC
mtxoci_ordinal678 equ <__imp_mtxoci_ordinal678>

externdef __imp_mtxoci_ordinal679:PPROC
mtxoci_ordinal679 equ <__imp_mtxoci_ordinal679>

externdef __imp_mtxoci_ordinal67:PPROC
mtxoci_ordinal67 equ <__imp_mtxoci_ordinal67>

externdef __imp_mtxoci_ordinal680:PPROC
mtxoci_ordinal680 equ <__imp_mtxoci_ordinal680>

externdef __imp_mtxoci_ordinal681:PPROC
mtxoci_ordinal681 equ <__imp_mtxoci_ordinal681>

externdef __imp_mtxoci_ordinal682:PPROC
mtxoci_ordinal682 equ <__imp_mtxoci_ordinal682>

externdef __imp_mtxoci_ordinal683:PPROC
mtxoci_ordinal683 equ <__imp_mtxoci_ordinal683>

externdef __imp_mtxoci_ordinal684:PPROC
mtxoci_ordinal684 equ <__imp_mtxoci_ordinal684>

externdef __imp_mtxoci_ordinal685:PPROC
mtxoci_ordinal685 equ <__imp_mtxoci_ordinal685>

externdef __imp_mtxoci_ordinal686:PPROC
mtxoci_ordinal686 equ <__imp_mtxoci_ordinal686>

externdef __imp_mtxoci_ordinal687:PPROC
mtxoci_ordinal687 equ <__imp_mtxoci_ordinal687>

externdef __imp_mtxoci_ordinal688:PPROC
mtxoci_ordinal688 equ <__imp_mtxoci_ordinal688>

externdef __imp_mtxoci_ordinal689:PPROC
mtxoci_ordinal689 equ <__imp_mtxoci_ordinal689>

externdef __imp_mtxoci_ordinal68:PPROC
mtxoci_ordinal68 equ <__imp_mtxoci_ordinal68>

externdef __imp_mtxoci_ordinal690:PPROC
mtxoci_ordinal690 equ <__imp_mtxoci_ordinal690>

externdef __imp_mtxoci_ordinal691:PPROC
mtxoci_ordinal691 equ <__imp_mtxoci_ordinal691>

externdef __imp_mtxoci_ordinal692:PPROC
mtxoci_ordinal692 equ <__imp_mtxoci_ordinal692>

externdef __imp_mtxoci_ordinal693:PPROC
mtxoci_ordinal693 equ <__imp_mtxoci_ordinal693>

externdef __imp_mtxoci_ordinal694:PPROC
mtxoci_ordinal694 equ <__imp_mtxoci_ordinal694>

externdef __imp_mtxoci_ordinal695:PPROC
mtxoci_ordinal695 equ <__imp_mtxoci_ordinal695>

externdef __imp_mtxoci_ordinal696:PPROC
mtxoci_ordinal696 equ <__imp_mtxoci_ordinal696>

externdef __imp_mtxoci_ordinal697:PPROC
mtxoci_ordinal697 equ <__imp_mtxoci_ordinal697>

externdef __imp_mtxoci_ordinal698:PPROC
mtxoci_ordinal698 equ <__imp_mtxoci_ordinal698>

externdef __imp_mtxoci_ordinal699:PPROC
mtxoci_ordinal699 equ <__imp_mtxoci_ordinal699>

externdef __imp_mtxoci_ordinal69:PPROC
mtxoci_ordinal69 equ <__imp_mtxoci_ordinal69>

externdef __imp_mtxoci_ordinal700:PPROC
mtxoci_ordinal700 equ <__imp_mtxoci_ordinal700>

externdef __imp_mtxoci_ordinal701:PPROC
mtxoci_ordinal701 equ <__imp_mtxoci_ordinal701>

externdef __imp_mtxoci_ordinal702:PPROC
mtxoci_ordinal702 equ <__imp_mtxoci_ordinal702>

externdef __imp_mtxoci_ordinal703:PPROC
mtxoci_ordinal703 equ <__imp_mtxoci_ordinal703>

externdef __imp_mtxoci_ordinal704:PPROC
mtxoci_ordinal704 equ <__imp_mtxoci_ordinal704>

externdef __imp_mtxoci_ordinal705:PPROC
mtxoci_ordinal705 equ <__imp_mtxoci_ordinal705>

externdef __imp_mtxoci_ordinal706:PPROC
mtxoci_ordinal706 equ <__imp_mtxoci_ordinal706>

externdef __imp_mtxoci_ordinal707:PPROC
mtxoci_ordinal707 equ <__imp_mtxoci_ordinal707>

externdef __imp_mtxoci_ordinal708:PPROC
mtxoci_ordinal708 equ <__imp_mtxoci_ordinal708>

externdef __imp_mtxoci_ordinal709:PPROC
mtxoci_ordinal709 equ <__imp_mtxoci_ordinal709>

externdef __imp_mtxoci_ordinal70:PPROC
mtxoci_ordinal70 equ <__imp_mtxoci_ordinal70>

externdef __imp_mtxoci_ordinal710:PPROC
mtxoci_ordinal710 equ <__imp_mtxoci_ordinal710>

externdef __imp_mtxoci_ordinal711:PPROC
mtxoci_ordinal711 equ <__imp_mtxoci_ordinal711>

externdef __imp_mtxoci_ordinal712:PPROC
mtxoci_ordinal712 equ <__imp_mtxoci_ordinal712>

externdef __imp_mtxoci_ordinal713:PPROC
mtxoci_ordinal713 equ <__imp_mtxoci_ordinal713>

externdef __imp_mtxoci_ordinal714:PPROC
mtxoci_ordinal714 equ <__imp_mtxoci_ordinal714>

externdef __imp_mtxoci_ordinal715:PPROC
mtxoci_ordinal715 equ <__imp_mtxoci_ordinal715>

externdef __imp_mtxoci_ordinal716:PPROC
mtxoci_ordinal716 equ <__imp_mtxoci_ordinal716>

externdef __imp_mtxoci_ordinal717:PPROC
mtxoci_ordinal717 equ <__imp_mtxoci_ordinal717>

externdef __imp_mtxoci_ordinal718:PPROC
mtxoci_ordinal718 equ <__imp_mtxoci_ordinal718>

externdef __imp_mtxoci_ordinal719:PPROC
mtxoci_ordinal719 equ <__imp_mtxoci_ordinal719>

externdef __imp_mtxoci_ordinal71:PPROC
mtxoci_ordinal71 equ <__imp_mtxoci_ordinal71>

externdef __imp_mtxoci_ordinal720:PPROC
mtxoci_ordinal720 equ <__imp_mtxoci_ordinal720>

externdef __imp_mtxoci_ordinal721:PPROC
mtxoci_ordinal721 equ <__imp_mtxoci_ordinal721>

externdef __imp_mtxoci_ordinal722:PPROC
mtxoci_ordinal722 equ <__imp_mtxoci_ordinal722>

externdef __imp_mtxoci_ordinal723:PPROC
mtxoci_ordinal723 equ <__imp_mtxoci_ordinal723>

externdef __imp_mtxoci_ordinal724:PPROC
mtxoci_ordinal724 equ <__imp_mtxoci_ordinal724>

externdef __imp_mtxoci_ordinal725:PPROC
mtxoci_ordinal725 equ <__imp_mtxoci_ordinal725>

externdef __imp_mtxoci_ordinal726:PPROC
mtxoci_ordinal726 equ <__imp_mtxoci_ordinal726>

externdef __imp_mtxoci_ordinal727:PPROC
mtxoci_ordinal727 equ <__imp_mtxoci_ordinal727>

externdef __imp_mtxoci_ordinal728:PPROC
mtxoci_ordinal728 equ <__imp_mtxoci_ordinal728>

externdef __imp_mtxoci_ordinal729:PPROC
mtxoci_ordinal729 equ <__imp_mtxoci_ordinal729>

externdef __imp_mtxoci_ordinal72:PPROC
mtxoci_ordinal72 equ <__imp_mtxoci_ordinal72>

externdef __imp_mtxoci_ordinal730:PPROC
mtxoci_ordinal730 equ <__imp_mtxoci_ordinal730>

externdef __imp_mtxoci_ordinal731:PPROC
mtxoci_ordinal731 equ <__imp_mtxoci_ordinal731>

externdef __imp_mtxoci_ordinal732:PPROC
mtxoci_ordinal732 equ <__imp_mtxoci_ordinal732>

externdef __imp_mtxoci_ordinal733:PPROC
mtxoci_ordinal733 equ <__imp_mtxoci_ordinal733>

externdef __imp_mtxoci_ordinal734:PPROC
mtxoci_ordinal734 equ <__imp_mtxoci_ordinal734>

externdef __imp_mtxoci_ordinal735:PPROC
mtxoci_ordinal735 equ <__imp_mtxoci_ordinal735>

externdef __imp_mtxoci_ordinal736:PPROC
mtxoci_ordinal736 equ <__imp_mtxoci_ordinal736>

externdef __imp_mtxoci_ordinal737:PPROC
mtxoci_ordinal737 equ <__imp_mtxoci_ordinal737>

externdef __imp_mtxoci_ordinal738:PPROC
mtxoci_ordinal738 equ <__imp_mtxoci_ordinal738>

externdef __imp_mtxoci_ordinal739:PPROC
mtxoci_ordinal739 equ <__imp_mtxoci_ordinal739>

externdef __imp_mtxoci_ordinal73:PPROC
mtxoci_ordinal73 equ <__imp_mtxoci_ordinal73>

externdef __imp_mtxoci_ordinal740:PPROC
mtxoci_ordinal740 equ <__imp_mtxoci_ordinal740>

externdef __imp_mtxoci_ordinal741:PPROC
mtxoci_ordinal741 equ <__imp_mtxoci_ordinal741>

externdef __imp_mtxoci_ordinal742:PPROC
mtxoci_ordinal742 equ <__imp_mtxoci_ordinal742>

externdef __imp_mtxoci_ordinal743:PPROC
mtxoci_ordinal743 equ <__imp_mtxoci_ordinal743>

externdef __imp_mtxoci_ordinal744:PPROC
mtxoci_ordinal744 equ <__imp_mtxoci_ordinal744>

externdef __imp_mtxoci_ordinal745:PPROC
mtxoci_ordinal745 equ <__imp_mtxoci_ordinal745>

externdef __imp_mtxoci_ordinal746:PPROC
mtxoci_ordinal746 equ <__imp_mtxoci_ordinal746>

externdef __imp_mtxoci_ordinal747:PPROC
mtxoci_ordinal747 equ <__imp_mtxoci_ordinal747>

externdef __imp_mtxoci_ordinal748:PPROC
mtxoci_ordinal748 equ <__imp_mtxoci_ordinal748>

externdef __imp_mtxoci_ordinal749:PPROC
mtxoci_ordinal749 equ <__imp_mtxoci_ordinal749>

externdef __imp_mtxoci_ordinal74:PPROC
mtxoci_ordinal74 equ <__imp_mtxoci_ordinal74>

externdef __imp_mtxoci_ordinal750:PPROC
mtxoci_ordinal750 equ <__imp_mtxoci_ordinal750>

externdef __imp_mtxoci_ordinal751:PPROC
mtxoci_ordinal751 equ <__imp_mtxoci_ordinal751>

externdef __imp_mtxoci_ordinal752:PPROC
mtxoci_ordinal752 equ <__imp_mtxoci_ordinal752>

externdef __imp_mtxoci_ordinal753:PPROC
mtxoci_ordinal753 equ <__imp_mtxoci_ordinal753>

externdef __imp_mtxoci_ordinal754:PPROC
mtxoci_ordinal754 equ <__imp_mtxoci_ordinal754>

externdef __imp_mtxoci_ordinal755:PPROC
mtxoci_ordinal755 equ <__imp_mtxoci_ordinal755>

externdef __imp_mtxoci_ordinal756:PPROC
mtxoci_ordinal756 equ <__imp_mtxoci_ordinal756>

externdef __imp_mtxoci_ordinal757:PPROC
mtxoci_ordinal757 equ <__imp_mtxoci_ordinal757>

externdef __imp_mtxoci_ordinal758:PPROC
mtxoci_ordinal758 equ <__imp_mtxoci_ordinal758>

externdef __imp_mtxoci_ordinal759:PPROC
mtxoci_ordinal759 equ <__imp_mtxoci_ordinal759>

externdef __imp_mtxoci_ordinal75:PPROC
mtxoci_ordinal75 equ <__imp_mtxoci_ordinal75>

externdef __imp_mtxoci_ordinal760:PPROC
mtxoci_ordinal760 equ <__imp_mtxoci_ordinal760>

externdef __imp_mtxoci_ordinal761:PPROC
mtxoci_ordinal761 equ <__imp_mtxoci_ordinal761>

externdef __imp_mtxoci_ordinal762:PPROC
mtxoci_ordinal762 equ <__imp_mtxoci_ordinal762>

externdef __imp_mtxoci_ordinal763:PPROC
mtxoci_ordinal763 equ <__imp_mtxoci_ordinal763>

externdef __imp_mtxoci_ordinal764:PPROC
mtxoci_ordinal764 equ <__imp_mtxoci_ordinal764>

externdef __imp_mtxoci_ordinal765:PPROC
mtxoci_ordinal765 equ <__imp_mtxoci_ordinal765>

externdef __imp_mtxoci_ordinal766:PPROC
mtxoci_ordinal766 equ <__imp_mtxoci_ordinal766>

externdef __imp_mtxoci_ordinal767:PPROC
mtxoci_ordinal767 equ <__imp_mtxoci_ordinal767>

externdef __imp_mtxoci_ordinal768:PPROC
mtxoci_ordinal768 equ <__imp_mtxoci_ordinal768>

externdef __imp_mtxoci_ordinal769:PPROC
mtxoci_ordinal769 equ <__imp_mtxoci_ordinal769>

externdef __imp_mtxoci_ordinal76:PPROC
mtxoci_ordinal76 equ <__imp_mtxoci_ordinal76>

externdef __imp_mtxoci_ordinal770:PPROC
mtxoci_ordinal770 equ <__imp_mtxoci_ordinal770>

externdef __imp_mtxoci_ordinal771:PPROC
mtxoci_ordinal771 equ <__imp_mtxoci_ordinal771>

externdef __imp_mtxoci_ordinal772:PPROC
mtxoci_ordinal772 equ <__imp_mtxoci_ordinal772>

externdef __imp_mtxoci_ordinal773:PPROC
mtxoci_ordinal773 equ <__imp_mtxoci_ordinal773>

externdef __imp_mtxoci_ordinal774:PPROC
mtxoci_ordinal774 equ <__imp_mtxoci_ordinal774>

externdef __imp_mtxoci_ordinal775:PPROC
mtxoci_ordinal775 equ <__imp_mtxoci_ordinal775>

externdef __imp_mtxoci_ordinal776:PPROC
mtxoci_ordinal776 equ <__imp_mtxoci_ordinal776>

externdef __imp_mtxoci_ordinal777:PPROC
mtxoci_ordinal777 equ <__imp_mtxoci_ordinal777>

externdef __imp_mtxoci_ordinal778:PPROC
mtxoci_ordinal778 equ <__imp_mtxoci_ordinal778>

externdef __imp_mtxoci_ordinal779:PPROC
mtxoci_ordinal779 equ <__imp_mtxoci_ordinal779>

externdef __imp_mtxoci_ordinal77:PPROC
mtxoci_ordinal77 equ <__imp_mtxoci_ordinal77>

externdef __imp_mtxoci_ordinal780:PPROC
mtxoci_ordinal780 equ <__imp_mtxoci_ordinal780>

externdef __imp_mtxoci_ordinal781:PPROC
mtxoci_ordinal781 equ <__imp_mtxoci_ordinal781>

externdef __imp_mtxoci_ordinal782:PPROC
mtxoci_ordinal782 equ <__imp_mtxoci_ordinal782>

externdef __imp_mtxoci_ordinal783:PPROC
mtxoci_ordinal783 equ <__imp_mtxoci_ordinal783>

externdef __imp_mtxoci_ordinal784:PPROC
mtxoci_ordinal784 equ <__imp_mtxoci_ordinal784>

externdef __imp_mtxoci_ordinal785:PPROC
mtxoci_ordinal785 equ <__imp_mtxoci_ordinal785>

externdef __imp_mtxoci_ordinal786:PPROC
mtxoci_ordinal786 equ <__imp_mtxoci_ordinal786>

externdef __imp_mtxoci_ordinal787:PPROC
mtxoci_ordinal787 equ <__imp_mtxoci_ordinal787>

externdef __imp_mtxoci_ordinal788:PPROC
mtxoci_ordinal788 equ <__imp_mtxoci_ordinal788>

externdef __imp_mtxoci_ordinal789:PPROC
mtxoci_ordinal789 equ <__imp_mtxoci_ordinal789>

externdef __imp_mtxoci_ordinal78:PPROC
mtxoci_ordinal78 equ <__imp_mtxoci_ordinal78>

externdef __imp_mtxoci_ordinal790:PPROC
mtxoci_ordinal790 equ <__imp_mtxoci_ordinal790>

externdef __imp_mtxoci_ordinal791:PPROC
mtxoci_ordinal791 equ <__imp_mtxoci_ordinal791>

externdef __imp_mtxoci_ordinal792:PPROC
mtxoci_ordinal792 equ <__imp_mtxoci_ordinal792>

externdef __imp_mtxoci_ordinal793:PPROC
mtxoci_ordinal793 equ <__imp_mtxoci_ordinal793>

externdef __imp_mtxoci_ordinal794:PPROC
mtxoci_ordinal794 equ <__imp_mtxoci_ordinal794>

externdef __imp_mtxoci_ordinal795:PPROC
mtxoci_ordinal795 equ <__imp_mtxoci_ordinal795>

externdef __imp_mtxoci_ordinal796:PPROC
mtxoci_ordinal796 equ <__imp_mtxoci_ordinal796>

externdef __imp_mtxoci_ordinal797:PPROC
mtxoci_ordinal797 equ <__imp_mtxoci_ordinal797>

externdef __imp_mtxoci_ordinal798:PPROC
mtxoci_ordinal798 equ <__imp_mtxoci_ordinal798>

externdef __imp_mtxoci_ordinal799:PPROC
mtxoci_ordinal799 equ <__imp_mtxoci_ordinal799>

externdef __imp_mtxoci_ordinal79:PPROC
mtxoci_ordinal79 equ <__imp_mtxoci_ordinal79>

externdef __imp_mtxoci_ordinal800:PPROC
mtxoci_ordinal800 equ <__imp_mtxoci_ordinal800>

externdef __imp_mtxoci_ordinal801:PPROC
mtxoci_ordinal801 equ <__imp_mtxoci_ordinal801>

externdef __imp_mtxoci_ordinal802:PPROC
mtxoci_ordinal802 equ <__imp_mtxoci_ordinal802>

externdef __imp_mtxoci_ordinal803:PPROC
mtxoci_ordinal803 equ <__imp_mtxoci_ordinal803>

externdef __imp_mtxoci_ordinal804:PPROC
mtxoci_ordinal804 equ <__imp_mtxoci_ordinal804>

externdef __imp_mtxoci_ordinal805:PPROC
mtxoci_ordinal805 equ <__imp_mtxoci_ordinal805>

externdef __imp_mtxoci_ordinal806:PPROC
mtxoci_ordinal806 equ <__imp_mtxoci_ordinal806>

externdef __imp_mtxoci_ordinal807:PPROC
mtxoci_ordinal807 equ <__imp_mtxoci_ordinal807>

externdef __imp_mtxoci_ordinal808:PPROC
mtxoci_ordinal808 equ <__imp_mtxoci_ordinal808>

externdef __imp_mtxoci_ordinal809:PPROC
mtxoci_ordinal809 equ <__imp_mtxoci_ordinal809>

externdef __imp_mtxoci_ordinal80:PPROC
mtxoci_ordinal80 equ <__imp_mtxoci_ordinal80>

externdef __imp_mtxoci_ordinal810:PPROC
mtxoci_ordinal810 equ <__imp_mtxoci_ordinal810>

externdef __imp_mtxoci_ordinal811:PPROC
mtxoci_ordinal811 equ <__imp_mtxoci_ordinal811>

externdef __imp_mtxoci_ordinal812:PPROC
mtxoci_ordinal812 equ <__imp_mtxoci_ordinal812>

externdef __imp_mtxoci_ordinal813:PPROC
mtxoci_ordinal813 equ <__imp_mtxoci_ordinal813>

externdef __imp_mtxoci_ordinal814:PPROC
mtxoci_ordinal814 equ <__imp_mtxoci_ordinal814>

externdef __imp_mtxoci_ordinal815:PPROC
mtxoci_ordinal815 equ <__imp_mtxoci_ordinal815>

externdef __imp_mtxoci_ordinal816:PPROC
mtxoci_ordinal816 equ <__imp_mtxoci_ordinal816>

externdef __imp_mtxoci_ordinal817:PPROC
mtxoci_ordinal817 equ <__imp_mtxoci_ordinal817>

externdef __imp_mtxoci_ordinal818:PPROC
mtxoci_ordinal818 equ <__imp_mtxoci_ordinal818>

externdef __imp_mtxoci_ordinal819:PPROC
mtxoci_ordinal819 equ <__imp_mtxoci_ordinal819>

externdef __imp_mtxoci_ordinal81:PPROC
mtxoci_ordinal81 equ <__imp_mtxoci_ordinal81>

externdef __imp_mtxoci_ordinal820:PPROC
mtxoci_ordinal820 equ <__imp_mtxoci_ordinal820>

externdef __imp_mtxoci_ordinal821:PPROC
mtxoci_ordinal821 equ <__imp_mtxoci_ordinal821>

externdef __imp_mtxoci_ordinal822:PPROC
mtxoci_ordinal822 equ <__imp_mtxoci_ordinal822>

externdef __imp_mtxoci_ordinal823:PPROC
mtxoci_ordinal823 equ <__imp_mtxoci_ordinal823>

externdef __imp_mtxoci_ordinal824:PPROC
mtxoci_ordinal824 equ <__imp_mtxoci_ordinal824>

externdef __imp_mtxoci_ordinal825:PPROC
mtxoci_ordinal825 equ <__imp_mtxoci_ordinal825>

externdef __imp_mtxoci_ordinal826:PPROC
mtxoci_ordinal826 equ <__imp_mtxoci_ordinal826>

externdef __imp_mtxoci_ordinal827:PPROC
mtxoci_ordinal827 equ <__imp_mtxoci_ordinal827>

externdef __imp_mtxoci_ordinal828:PPROC
mtxoci_ordinal828 equ <__imp_mtxoci_ordinal828>

externdef __imp_mtxoci_ordinal829:PPROC
mtxoci_ordinal829 equ <__imp_mtxoci_ordinal829>

externdef __imp_mtxoci_ordinal82:PPROC
mtxoci_ordinal82 equ <__imp_mtxoci_ordinal82>

externdef __imp_mtxoci_ordinal830:PPROC
mtxoci_ordinal830 equ <__imp_mtxoci_ordinal830>

externdef __imp_mtxoci_ordinal831:PPROC
mtxoci_ordinal831 equ <__imp_mtxoci_ordinal831>

externdef __imp_mtxoci_ordinal832:PPROC
mtxoci_ordinal832 equ <__imp_mtxoci_ordinal832>

externdef __imp_mtxoci_ordinal833:PPROC
mtxoci_ordinal833 equ <__imp_mtxoci_ordinal833>

externdef __imp_mtxoci_ordinal834:PPROC
mtxoci_ordinal834 equ <__imp_mtxoci_ordinal834>

externdef __imp_mtxoci_ordinal835:PPROC
mtxoci_ordinal835 equ <__imp_mtxoci_ordinal835>

externdef __imp_mtxoci_ordinal836:PPROC
mtxoci_ordinal836 equ <__imp_mtxoci_ordinal836>

externdef __imp_mtxoci_ordinal837:PPROC
mtxoci_ordinal837 equ <__imp_mtxoci_ordinal837>

externdef __imp_mtxoci_ordinal838:PPROC
mtxoci_ordinal838 equ <__imp_mtxoci_ordinal838>

externdef __imp_mtxoci_ordinal839:PPROC
mtxoci_ordinal839 equ <__imp_mtxoci_ordinal839>

externdef __imp_mtxoci_ordinal83:PPROC
mtxoci_ordinal83 equ <__imp_mtxoci_ordinal83>

externdef __imp_mtxoci_ordinal840:PPROC
mtxoci_ordinal840 equ <__imp_mtxoci_ordinal840>

externdef __imp_mtxoci_ordinal841:PPROC
mtxoci_ordinal841 equ <__imp_mtxoci_ordinal841>

externdef __imp_mtxoci_ordinal842:PPROC
mtxoci_ordinal842 equ <__imp_mtxoci_ordinal842>

externdef __imp_mtxoci_ordinal843:PPROC
mtxoci_ordinal843 equ <__imp_mtxoci_ordinal843>

externdef __imp_mtxoci_ordinal844:PPROC
mtxoci_ordinal844 equ <__imp_mtxoci_ordinal844>

externdef __imp_mtxoci_ordinal845:PPROC
mtxoci_ordinal845 equ <__imp_mtxoci_ordinal845>

externdef __imp_mtxoci_ordinal846:PPROC
mtxoci_ordinal846 equ <__imp_mtxoci_ordinal846>

externdef __imp_mtxoci_ordinal847:PPROC
mtxoci_ordinal847 equ <__imp_mtxoci_ordinal847>

externdef __imp_mtxoci_ordinal848:PPROC
mtxoci_ordinal848 equ <__imp_mtxoci_ordinal848>

externdef __imp_mtxoci_ordinal849:PPROC
mtxoci_ordinal849 equ <__imp_mtxoci_ordinal849>

externdef __imp_mtxoci_ordinal84:PPROC
mtxoci_ordinal84 equ <__imp_mtxoci_ordinal84>

externdef __imp_mtxoci_ordinal850:PPROC
mtxoci_ordinal850 equ <__imp_mtxoci_ordinal850>

externdef __imp_mtxoci_ordinal851:PPROC
mtxoci_ordinal851 equ <__imp_mtxoci_ordinal851>

externdef __imp_mtxoci_ordinal852:PPROC
mtxoci_ordinal852 equ <__imp_mtxoci_ordinal852>

externdef __imp_mtxoci_ordinal853:PPROC
mtxoci_ordinal853 equ <__imp_mtxoci_ordinal853>

externdef __imp_mtxoci_ordinal854:PPROC
mtxoci_ordinal854 equ <__imp_mtxoci_ordinal854>

externdef __imp_mtxoci_ordinal855:PPROC
mtxoci_ordinal855 equ <__imp_mtxoci_ordinal855>

externdef __imp_mtxoci_ordinal856:PPROC
mtxoci_ordinal856 equ <__imp_mtxoci_ordinal856>

externdef __imp_mtxoci_ordinal857:PPROC
mtxoci_ordinal857 equ <__imp_mtxoci_ordinal857>

externdef __imp_mtxoci_ordinal858:PPROC
mtxoci_ordinal858 equ <__imp_mtxoci_ordinal858>

externdef __imp_mtxoci_ordinal859:PPROC
mtxoci_ordinal859 equ <__imp_mtxoci_ordinal859>

externdef __imp_mtxoci_ordinal85:PPROC
mtxoci_ordinal85 equ <__imp_mtxoci_ordinal85>

externdef __imp_mtxoci_ordinal860:PPROC
mtxoci_ordinal860 equ <__imp_mtxoci_ordinal860>

externdef __imp_mtxoci_ordinal861:PPROC
mtxoci_ordinal861 equ <__imp_mtxoci_ordinal861>

externdef __imp_mtxoci_ordinal862:PPROC
mtxoci_ordinal862 equ <__imp_mtxoci_ordinal862>

externdef __imp_mtxoci_ordinal863:PPROC
mtxoci_ordinal863 equ <__imp_mtxoci_ordinal863>

externdef __imp_mtxoci_ordinal864:PPROC
mtxoci_ordinal864 equ <__imp_mtxoci_ordinal864>

externdef __imp_mtxoci_ordinal865:PPROC
mtxoci_ordinal865 equ <__imp_mtxoci_ordinal865>

externdef __imp_mtxoci_ordinal866:PPROC
mtxoci_ordinal866 equ <__imp_mtxoci_ordinal866>

externdef __imp_mtxoci_ordinal867:PPROC
mtxoci_ordinal867 equ <__imp_mtxoci_ordinal867>

externdef __imp_mtxoci_ordinal868:PPROC
mtxoci_ordinal868 equ <__imp_mtxoci_ordinal868>

externdef __imp_mtxoci_ordinal869:PPROC
mtxoci_ordinal869 equ <__imp_mtxoci_ordinal869>

externdef __imp_mtxoci_ordinal86:PPROC
mtxoci_ordinal86 equ <__imp_mtxoci_ordinal86>

externdef __imp_mtxoci_ordinal870:PPROC
mtxoci_ordinal870 equ <__imp_mtxoci_ordinal870>

externdef __imp_mtxoci_ordinal871:PPROC
mtxoci_ordinal871 equ <__imp_mtxoci_ordinal871>

externdef __imp_mtxoci_ordinal872:PPROC
mtxoci_ordinal872 equ <__imp_mtxoci_ordinal872>

externdef __imp_mtxoci_ordinal873:PPROC
mtxoci_ordinal873 equ <__imp_mtxoci_ordinal873>

externdef __imp_mtxoci_ordinal874:PPROC
mtxoci_ordinal874 equ <__imp_mtxoci_ordinal874>

externdef __imp_mtxoci_ordinal875:PPROC
mtxoci_ordinal875 equ <__imp_mtxoci_ordinal875>

externdef __imp_mtxoci_ordinal876:PPROC
mtxoci_ordinal876 equ <__imp_mtxoci_ordinal876>

externdef __imp_mtxoci_ordinal877:PPROC
mtxoci_ordinal877 equ <__imp_mtxoci_ordinal877>

externdef __imp_mtxoci_ordinal878:PPROC
mtxoci_ordinal878 equ <__imp_mtxoci_ordinal878>

externdef __imp_mtxoci_ordinal879:PPROC
mtxoci_ordinal879 equ <__imp_mtxoci_ordinal879>

externdef __imp_mtxoci_ordinal87:PPROC
mtxoci_ordinal87 equ <__imp_mtxoci_ordinal87>

externdef __imp_mtxoci_ordinal880:PPROC
mtxoci_ordinal880 equ <__imp_mtxoci_ordinal880>

externdef __imp_mtxoci_ordinal881:PPROC
mtxoci_ordinal881 equ <__imp_mtxoci_ordinal881>

externdef __imp_mtxoci_ordinal882:PPROC
mtxoci_ordinal882 equ <__imp_mtxoci_ordinal882>

externdef __imp_mtxoci_ordinal883:PPROC
mtxoci_ordinal883 equ <__imp_mtxoci_ordinal883>

externdef __imp_mtxoci_ordinal884:PPROC
mtxoci_ordinal884 equ <__imp_mtxoci_ordinal884>

externdef __imp_mtxoci_ordinal885:PPROC
mtxoci_ordinal885 equ <__imp_mtxoci_ordinal885>

externdef __imp_mtxoci_ordinal886:PPROC
mtxoci_ordinal886 equ <__imp_mtxoci_ordinal886>

externdef __imp_mtxoci_ordinal887:PPROC
mtxoci_ordinal887 equ <__imp_mtxoci_ordinal887>

externdef __imp_mtxoci_ordinal888:PPROC
mtxoci_ordinal888 equ <__imp_mtxoci_ordinal888>

externdef __imp_mtxoci_ordinal889:PPROC
mtxoci_ordinal889 equ <__imp_mtxoci_ordinal889>

externdef __imp_mtxoci_ordinal88:PPROC
mtxoci_ordinal88 equ <__imp_mtxoci_ordinal88>

externdef __imp_mtxoci_ordinal890:PPROC
mtxoci_ordinal890 equ <__imp_mtxoci_ordinal890>

externdef __imp_mtxoci_ordinal891:PPROC
mtxoci_ordinal891 equ <__imp_mtxoci_ordinal891>

externdef __imp_mtxoci_ordinal892:PPROC
mtxoci_ordinal892 equ <__imp_mtxoci_ordinal892>

externdef __imp_mtxoci_ordinal893:PPROC
mtxoci_ordinal893 equ <__imp_mtxoci_ordinal893>

externdef __imp_mtxoci_ordinal894:PPROC
mtxoci_ordinal894 equ <__imp_mtxoci_ordinal894>

externdef __imp_mtxoci_ordinal895:PPROC
mtxoci_ordinal895 equ <__imp_mtxoci_ordinal895>

externdef __imp_mtxoci_ordinal896:PPROC
mtxoci_ordinal896 equ <__imp_mtxoci_ordinal896>

externdef __imp_mtxoci_ordinal897:PPROC
mtxoci_ordinal897 equ <__imp_mtxoci_ordinal897>

externdef __imp_mtxoci_ordinal898:PPROC
mtxoci_ordinal898 equ <__imp_mtxoci_ordinal898>

externdef __imp_mtxoci_ordinal899:PPROC
mtxoci_ordinal899 equ <__imp_mtxoci_ordinal899>

externdef __imp_mtxoci_ordinal89:PPROC
mtxoci_ordinal89 equ <__imp_mtxoci_ordinal89>

externdef __imp_mtxoci_ordinal900:PPROC
mtxoci_ordinal900 equ <__imp_mtxoci_ordinal900>

externdef __imp_mtxoci_ordinal901:PPROC
mtxoci_ordinal901 equ <__imp_mtxoci_ordinal901>

externdef __imp_mtxoci_ordinal902:PPROC
mtxoci_ordinal902 equ <__imp_mtxoci_ordinal902>

externdef __imp_mtxoci_ordinal903:PPROC
mtxoci_ordinal903 equ <__imp_mtxoci_ordinal903>

externdef __imp_mtxoci_ordinal904:PPROC
mtxoci_ordinal904 equ <__imp_mtxoci_ordinal904>

externdef __imp_mtxoci_ordinal905:PPROC
mtxoci_ordinal905 equ <__imp_mtxoci_ordinal905>

externdef __imp_mtxoci_ordinal906:PPROC
mtxoci_ordinal906 equ <__imp_mtxoci_ordinal906>

externdef __imp_mtxoci_ordinal907:PPROC
mtxoci_ordinal907 equ <__imp_mtxoci_ordinal907>

externdef __imp_mtxoci_ordinal908:PPROC
mtxoci_ordinal908 equ <__imp_mtxoci_ordinal908>

externdef __imp_mtxoci_ordinal909:PPROC
mtxoci_ordinal909 equ <__imp_mtxoci_ordinal909>

externdef __imp_mtxoci_ordinal90:PPROC
mtxoci_ordinal90 equ <__imp_mtxoci_ordinal90>

externdef __imp_mtxoci_ordinal910:PPROC
mtxoci_ordinal910 equ <__imp_mtxoci_ordinal910>

externdef __imp_mtxoci_ordinal911:PPROC
mtxoci_ordinal911 equ <__imp_mtxoci_ordinal911>

externdef __imp_mtxoci_ordinal912:PPROC
mtxoci_ordinal912 equ <__imp_mtxoci_ordinal912>

externdef __imp_mtxoci_ordinal913:PPROC
mtxoci_ordinal913 equ <__imp_mtxoci_ordinal913>

externdef __imp_mtxoci_ordinal914:PPROC
mtxoci_ordinal914 equ <__imp_mtxoci_ordinal914>

externdef __imp_mtxoci_ordinal915:PPROC
mtxoci_ordinal915 equ <__imp_mtxoci_ordinal915>

externdef __imp_mtxoci_ordinal916:PPROC
mtxoci_ordinal916 equ <__imp_mtxoci_ordinal916>

externdef __imp_mtxoci_ordinal917:PPROC
mtxoci_ordinal917 equ <__imp_mtxoci_ordinal917>

externdef __imp_mtxoci_ordinal918:PPROC
mtxoci_ordinal918 equ <__imp_mtxoci_ordinal918>

externdef __imp_mtxoci_ordinal919:PPROC
mtxoci_ordinal919 equ <__imp_mtxoci_ordinal919>

externdef __imp_mtxoci_ordinal91:PPROC
mtxoci_ordinal91 equ <__imp_mtxoci_ordinal91>

externdef __imp_mtxoci_ordinal920:PPROC
mtxoci_ordinal920 equ <__imp_mtxoci_ordinal920>

externdef __imp_mtxoci_ordinal921:PPROC
mtxoci_ordinal921 equ <__imp_mtxoci_ordinal921>

externdef __imp_mtxoci_ordinal922:PPROC
mtxoci_ordinal922 equ <__imp_mtxoci_ordinal922>

externdef __imp_mtxoci_ordinal923:PPROC
mtxoci_ordinal923 equ <__imp_mtxoci_ordinal923>

externdef __imp_mtxoci_ordinal924:PPROC
mtxoci_ordinal924 equ <__imp_mtxoci_ordinal924>

externdef __imp_mtxoci_ordinal925:PPROC
mtxoci_ordinal925 equ <__imp_mtxoci_ordinal925>

externdef __imp_mtxoci_ordinal926:PPROC
mtxoci_ordinal926 equ <__imp_mtxoci_ordinal926>

externdef __imp_mtxoci_ordinal927:PPROC
mtxoci_ordinal927 equ <__imp_mtxoci_ordinal927>

externdef __imp_mtxoci_ordinal928:PPROC
mtxoci_ordinal928 equ <__imp_mtxoci_ordinal928>

externdef __imp_mtxoci_ordinal929:PPROC
mtxoci_ordinal929 equ <__imp_mtxoci_ordinal929>

externdef __imp_mtxoci_ordinal92:PPROC
mtxoci_ordinal92 equ <__imp_mtxoci_ordinal92>

externdef __imp_mtxoci_ordinal930:PPROC
mtxoci_ordinal930 equ <__imp_mtxoci_ordinal930>

externdef __imp_mtxoci_ordinal931:PPROC
mtxoci_ordinal931 equ <__imp_mtxoci_ordinal931>

externdef __imp_mtxoci_ordinal932:PPROC
mtxoci_ordinal932 equ <__imp_mtxoci_ordinal932>

externdef __imp_mtxoci_ordinal933:PPROC
mtxoci_ordinal933 equ <__imp_mtxoci_ordinal933>

externdef __imp_mtxoci_ordinal934:PPROC
mtxoci_ordinal934 equ <__imp_mtxoci_ordinal934>

externdef __imp_mtxoci_ordinal935:PPROC
mtxoci_ordinal935 equ <__imp_mtxoci_ordinal935>

externdef __imp_mtxoci_ordinal936:PPROC
mtxoci_ordinal936 equ <__imp_mtxoci_ordinal936>

externdef __imp_mtxoci_ordinal937:PPROC
mtxoci_ordinal937 equ <__imp_mtxoci_ordinal937>

externdef __imp_mtxoci_ordinal938:PPROC
mtxoci_ordinal938 equ <__imp_mtxoci_ordinal938>

externdef __imp_mtxoci_ordinal939:PPROC
mtxoci_ordinal939 equ <__imp_mtxoci_ordinal939>

externdef __imp_mtxoci_ordinal93:PPROC
mtxoci_ordinal93 equ <__imp_mtxoci_ordinal93>

externdef __imp_mtxoci_ordinal940:PPROC
mtxoci_ordinal940 equ <__imp_mtxoci_ordinal940>

externdef __imp_mtxoci_ordinal941:PPROC
mtxoci_ordinal941 equ <__imp_mtxoci_ordinal941>

externdef __imp_mtxoci_ordinal942:PPROC
mtxoci_ordinal942 equ <__imp_mtxoci_ordinal942>

externdef __imp_mtxoci_ordinal943:PPROC
mtxoci_ordinal943 equ <__imp_mtxoci_ordinal943>

externdef __imp_mtxoci_ordinal944:PPROC
mtxoci_ordinal944 equ <__imp_mtxoci_ordinal944>

externdef __imp_mtxoci_ordinal945:PPROC
mtxoci_ordinal945 equ <__imp_mtxoci_ordinal945>

externdef __imp_mtxoci_ordinal946:PPROC
mtxoci_ordinal946 equ <__imp_mtxoci_ordinal946>

externdef __imp_mtxoci_ordinal947:PPROC
mtxoci_ordinal947 equ <__imp_mtxoci_ordinal947>

externdef __imp_mtxoci_ordinal948:PPROC
mtxoci_ordinal948 equ <__imp_mtxoci_ordinal948>

externdef __imp_mtxoci_ordinal949:PPROC
mtxoci_ordinal949 equ <__imp_mtxoci_ordinal949>

externdef __imp_mtxoci_ordinal94:PPROC
mtxoci_ordinal94 equ <__imp_mtxoci_ordinal94>

externdef __imp_mtxoci_ordinal950:PPROC
mtxoci_ordinal950 equ <__imp_mtxoci_ordinal950>

externdef __imp_mtxoci_ordinal951:PPROC
mtxoci_ordinal951 equ <__imp_mtxoci_ordinal951>

externdef __imp_mtxoci_ordinal952:PPROC
mtxoci_ordinal952 equ <__imp_mtxoci_ordinal952>

externdef __imp_mtxoci_ordinal953:PPROC
mtxoci_ordinal953 equ <__imp_mtxoci_ordinal953>

externdef __imp_mtxoci_ordinal954:PPROC
mtxoci_ordinal954 equ <__imp_mtxoci_ordinal954>

externdef __imp_mtxoci_ordinal955:PPROC
mtxoci_ordinal955 equ <__imp_mtxoci_ordinal955>

externdef __imp_mtxoci_ordinal956:PPROC
mtxoci_ordinal956 equ <__imp_mtxoci_ordinal956>

externdef __imp_mtxoci_ordinal957:PPROC
mtxoci_ordinal957 equ <__imp_mtxoci_ordinal957>

externdef __imp_mtxoci_ordinal958:PPROC
mtxoci_ordinal958 equ <__imp_mtxoci_ordinal958>

externdef __imp_mtxoci_ordinal959:PPROC
mtxoci_ordinal959 equ <__imp_mtxoci_ordinal959>

externdef __imp_mtxoci_ordinal95:PPROC
mtxoci_ordinal95 equ <__imp_mtxoci_ordinal95>

externdef __imp_mtxoci_ordinal960:PPROC
mtxoci_ordinal960 equ <__imp_mtxoci_ordinal960>

externdef __imp_mtxoci_ordinal961:PPROC
mtxoci_ordinal961 equ <__imp_mtxoci_ordinal961>

externdef __imp_mtxoci_ordinal962:PPROC
mtxoci_ordinal962 equ <__imp_mtxoci_ordinal962>

externdef __imp_mtxoci_ordinal963:PPROC
mtxoci_ordinal963 equ <__imp_mtxoci_ordinal963>

externdef __imp_mtxoci_ordinal964:PPROC
mtxoci_ordinal964 equ <__imp_mtxoci_ordinal964>

externdef __imp_mtxoci_ordinal965:PPROC
mtxoci_ordinal965 equ <__imp_mtxoci_ordinal965>

externdef __imp_mtxoci_ordinal966:PPROC
mtxoci_ordinal966 equ <__imp_mtxoci_ordinal966>

externdef __imp_mtxoci_ordinal967:PPROC
mtxoci_ordinal967 equ <__imp_mtxoci_ordinal967>

externdef __imp_mtxoci_ordinal968:PPROC
mtxoci_ordinal968 equ <__imp_mtxoci_ordinal968>

externdef __imp_mtxoci_ordinal969:PPROC
mtxoci_ordinal969 equ <__imp_mtxoci_ordinal969>

externdef __imp_mtxoci_ordinal96:PPROC
mtxoci_ordinal96 equ <__imp_mtxoci_ordinal96>

externdef __imp_mtxoci_ordinal970:PPROC
mtxoci_ordinal970 equ <__imp_mtxoci_ordinal970>

externdef __imp_mtxoci_ordinal971:PPROC
mtxoci_ordinal971 equ <__imp_mtxoci_ordinal971>

externdef __imp_mtxoci_ordinal972:PPROC
mtxoci_ordinal972 equ <__imp_mtxoci_ordinal972>

externdef __imp_mtxoci_ordinal973:PPROC
mtxoci_ordinal973 equ <__imp_mtxoci_ordinal973>

externdef __imp_mtxoci_ordinal974:PPROC
mtxoci_ordinal974 equ <__imp_mtxoci_ordinal974>

externdef __imp_mtxoci_ordinal975:PPROC
mtxoci_ordinal975 equ <__imp_mtxoci_ordinal975>

externdef __imp_mtxoci_ordinal976:PPROC
mtxoci_ordinal976 equ <__imp_mtxoci_ordinal976>

externdef __imp_mtxoci_ordinal977:PPROC
mtxoci_ordinal977 equ <__imp_mtxoci_ordinal977>

externdef __imp_mtxoci_ordinal978:PPROC
mtxoci_ordinal978 equ <__imp_mtxoci_ordinal978>

externdef __imp_mtxoci_ordinal979:PPROC
mtxoci_ordinal979 equ <__imp_mtxoci_ordinal979>

externdef __imp_mtxoci_ordinal97:PPROC
mtxoci_ordinal97 equ <__imp_mtxoci_ordinal97>

externdef __imp_mtxoci_ordinal980:PPROC
mtxoci_ordinal980 equ <__imp_mtxoci_ordinal980>

externdef __imp_mtxoci_ordinal981:PPROC
mtxoci_ordinal981 equ <__imp_mtxoci_ordinal981>

externdef __imp_mtxoci_ordinal982:PPROC
mtxoci_ordinal982 equ <__imp_mtxoci_ordinal982>

externdef __imp_mtxoci_ordinal983:PPROC
mtxoci_ordinal983 equ <__imp_mtxoci_ordinal983>

externdef __imp_mtxoci_ordinal984:PPROC
mtxoci_ordinal984 equ <__imp_mtxoci_ordinal984>

externdef __imp_mtxoci_ordinal985:PPROC
mtxoci_ordinal985 equ <__imp_mtxoci_ordinal985>

externdef __imp_mtxoci_ordinal986:PPROC
mtxoci_ordinal986 equ <__imp_mtxoci_ordinal986>

externdef __imp_mtxoci_ordinal987:PPROC
mtxoci_ordinal987 equ <__imp_mtxoci_ordinal987>

externdef __imp_mtxoci_ordinal988:PPROC
mtxoci_ordinal988 equ <__imp_mtxoci_ordinal988>

externdef __imp_mtxoci_ordinal989:PPROC
mtxoci_ordinal989 equ <__imp_mtxoci_ordinal989>

externdef __imp_mtxoci_ordinal98:PPROC
mtxoci_ordinal98 equ <__imp_mtxoci_ordinal98>

externdef __imp_mtxoci_ordinal990:PPROC
mtxoci_ordinal990 equ <__imp_mtxoci_ordinal990>

externdef __imp_mtxoci_ordinal991:PPROC
mtxoci_ordinal991 equ <__imp_mtxoci_ordinal991>

externdef __imp_mtxoci_ordinal992:PPROC
mtxoci_ordinal992 equ <__imp_mtxoci_ordinal992>

externdef __imp_mtxoci_ordinal993:PPROC
mtxoci_ordinal993 equ <__imp_mtxoci_ordinal993>

externdef __imp_mtxoci_ordinal994:PPROC
mtxoci_ordinal994 equ <__imp_mtxoci_ordinal994>

externdef __imp_mtxoci_ordinal995:PPROC
mtxoci_ordinal995 equ <__imp_mtxoci_ordinal995>

externdef __imp_mtxoci_ordinal996:PPROC
mtxoci_ordinal996 equ <__imp_mtxoci_ordinal996>

externdef __imp_mtxoci_ordinal997:PPROC
mtxoci_ordinal997 equ <__imp_mtxoci_ordinal997>

externdef __imp_mtxoci_ordinal998:PPROC
mtxoci_ordinal998 equ <__imp_mtxoci_ordinal998>

externdef __imp_mtxoci_ordinal999:PPROC
mtxoci_ordinal999 equ <__imp_mtxoci_ordinal999>

externdef __imp_mtxoci_ordinal99:PPROC
mtxoci_ordinal99 equ <__imp_mtxoci_ordinal99>

externdef __imp_obindps:PPROC
obindps equ <__imp_obindps>

externdef __imp_obndra:PPROC
obndra equ <__imp_obndra>

externdef __imp_obndrn:PPROC
obndrn equ <__imp_obndrn>

externdef __imp_obndrv:PPROC
obndrv equ <__imp_obndrv>

externdef __imp_obreak:PPROC
obreak equ <__imp_obreak>

externdef __imp_ocan:PPROC
ocan equ <__imp_ocan>

externdef __imp_oclose:PPROC
oclose equ <__imp_oclose>

externdef __imp_ocof:PPROC
ocof equ <__imp_ocof>

externdef __imp_ocom:PPROC
ocom equ <__imp_ocom>

externdef __imp_ocon:PPROC
ocon equ <__imp_ocon>

externdef __imp_odefin:PPROC
odefin equ <__imp_odefin>

externdef __imp_odefinps:PPROC
odefinps equ <__imp_odefinps>

externdef __imp_odescr:PPROC
odescr equ <__imp_odescr>

externdef __imp_odessp:PPROC
odessp equ <__imp_odessp>

externdef __imp_oerhms:PPROC
oerhms equ <__imp_oerhms>

externdef __imp_oermsg:PPROC
oermsg equ <__imp_oermsg>

externdef __imp_oexec:PPROC
oexec equ <__imp_oexec>

externdef __imp_oexfet:PPROC
oexfet equ <__imp_oexfet>

externdef __imp_oexn:PPROC
oexn equ <__imp_oexn>

externdef __imp_ofen:PPROC
ofen equ <__imp_ofen>

externdef __imp_ofetch:PPROC
ofetch equ <__imp_ofetch>

externdef __imp_oflng:PPROC
oflng equ <__imp_oflng>

externdef __imp_ogetpi:PPROC
ogetpi equ <__imp_ogetpi>

externdef __imp_olog:PPROC
olog equ <__imp_olog>

externdef __imp_ologTransacted:PPROC
ologTransacted equ <__imp_ologTransacted>

externdef __imp_ologof:PPROC
ologof equ <__imp_ologof>

externdef __imp_oopen:PPROC
oopen equ <__imp_oopen>

externdef __imp_oopt:PPROC
oopt equ <__imp_oopt>

externdef __imp_oparse:PPROC
oparse equ <__imp_oparse>

externdef __imp_opinit:PPROC
opinit equ <__imp_opinit>

externdef __imp_orol:PPROC
orol equ <__imp_orol>

externdef __imp_osetpi:PPROC
osetpi equ <__imp_osetpi>
