externdef __imp_?BackToApplication@@YAXXZ:PPROC
?BackToApplication@@YAXXZ equ <__imp_?BackToApplication@@YAXXZ>

externdef __imp_?GetAnnounceMenu@@YAHXZ:PPROC
?GetAnnounceMenu@@YAHXZ equ <__imp_?GetAnnounceMenu@@YAHXZ>

externdef __imp_?GetAnnouncePopup@@YAHXZ:PPROC
?GetAnnouncePopup@@YAHXZ equ <__imp_?GetAnnouncePopup@@YAHXZ>

externdef __imp_?GetAnnounceToolTips@@YAHXZ:PPROC
?GetAnnounceToolTips@@YAHXZ equ <__imp_?GetAnnounceToolTips@@YAHXZ>

externdef __imp_?GetAnnounceWindow@@YAHXZ:PPROC
?GetAnnounceWindow@@YAHXZ equ <__imp_?GetAnnounceWindow@@YAHXZ>

externdef __imp_?GetCurrentText@@YAXPEAGH@Z:PPROC
?GetCurrentText@@YAXPEAGH@Z equ <__imp_?GetCurrentText@@YAXPEAGH@Z>

externdef __imp_?GetEchoChars@@YAHXZ:PPROC
?GetEchoChars@@YAHXZ equ <__imp_?GetEchoChars@@YAHXZ>

externdef __imp_?GetReviewLevel@@YAHXZ:PPROC
?GetReviewLevel@@YAHXZ equ <__imp_?GetReviewLevel@@YAHXZ>

externdef __imp_?GetReviewStyle@@YAHXZ:PPROC
?GetReviewStyle@@YAHXZ equ <__imp_?GetReviewStyle@@YAHXZ>

externdef __imp_?GetTrackCaret@@YAHXZ:PPROC
?GetTrackCaret@@YAHXZ equ <__imp_?GetTrackCaret@@YAHXZ>

externdef __imp_?GetTrackInputFocus@@YAHXZ:PPROC
?GetTrackInputFocus@@YAHXZ equ <__imp_?GetTrackInputFocus@@YAHXZ>

externdef __imp_?GetTrackSecondary@@YAHXZ:PPROC
?GetTrackSecondary@@YAHXZ equ <__imp_?GetTrackSecondary@@YAHXZ>

externdef __imp_?InitKeys@@YAHPEAUHWND__@@@Z:PPROC
?InitKeys@@YAHPEAUHWND__@@@Z equ <__imp_?InitKeys@@YAHPEAUHWND__@@@Z>

externdef __imp_?InitMSAA@@YAHXZ:PPROC
?InitMSAA@@YAHXZ equ <__imp_?InitMSAA@@YAHXZ>

externdef __imp_?SetAnnounceMenu@@YAXH@Z:PPROC
?SetAnnounceMenu@@YAXH@Z equ <__imp_?SetAnnounceMenu@@YAXH@Z>

externdef __imp_?SetAnnouncePopup@@YAXH@Z:PPROC
?SetAnnouncePopup@@YAXH@Z equ <__imp_?SetAnnouncePopup@@YAXH@Z>

externdef __imp_?SetAnnounceToolTips@@YAXH@Z:PPROC
?SetAnnounceToolTips@@YAXH@Z equ <__imp_?SetAnnounceToolTips@@YAXH@Z>

externdef __imp_?SetAnnounceWindow@@YAXH@Z:PPROC
?SetAnnounceWindow@@YAXH@Z equ <__imp_?SetAnnounceWindow@@YAXH@Z>

externdef __imp_?SetCurrentText@@YAXPEBG@Z:PPROC
?SetCurrentText@@YAXPEBG@Z equ <__imp_?SetCurrentText@@YAXPEBG@Z>

externdef __imp_?SetEchoChars@@YAXH@Z:PPROC
?SetEchoChars@@YAXH@Z equ <__imp_?SetEchoChars@@YAXH@Z>

externdef __imp_?SetReviewLevel@@YAXH@Z:PPROC
?SetReviewLevel@@YAXH@Z equ <__imp_?SetReviewLevel@@YAXH@Z>

externdef __imp_?SetReviewStyle@@YAXH@Z:PPROC
?SetReviewStyle@@YAXH@Z equ <__imp_?SetReviewStyle@@YAXH@Z>

externdef __imp_?SetTrackCaret@@YAXH@Z:PPROC
?SetTrackCaret@@YAXH@Z equ <__imp_?SetTrackCaret@@YAXH@Z>

externdef __imp_?SetTrackInputFocus@@YAXH@Z:PPROC
?SetTrackInputFocus@@YAXH@Z equ <__imp_?SetTrackInputFocus@@YAXH@Z>

externdef __imp_?SetTrackSecondary@@YAXH@Z:PPROC
?SetTrackSecondary@@YAXH@Z equ <__imp_?SetTrackSecondary@@YAXH@Z>

externdef __imp_?UnInitMSAA@@YAHXZ:PPROC
?UnInitMSAA@@YAHXZ equ <__imp_?UnInitMSAA@@YAHXZ>

externdef __imp_?UninitKeys@@YAHXZ:PPROC
?UninitKeys@@YAHXZ equ <__imp_?UninitKeys@@YAHXZ>

externdef __imp_?lstrcatn@@YAPEAGPEAG0H@Z:PPROC
?lstrcatn@@YAPEAGPEAG0H@Z equ <__imp_?lstrcatn@@YAPEAGPEAG0H@Z>
