externdef __imp_Configure:PPROC
Configure equ <__imp_Configure>

externdef __imp_ConfigureDlgProc:PPROC
ConfigureDlgProc equ <__imp_ConfigureDlgProc>

externdef __imp_LogDebugInfo:PPROC
LogDebugInfo equ <__imp_LogDebugInfo>

externdef __imp_NDDEAddConnection:PPROC
NDDEAddConnection equ <__imp_NDDEAddConnection>

externdef __imp_NDDEDeleteConnection:PPROC
NDDEDeleteConnection equ <__imp_NDDEDeleteConnection>

externdef __imp_NDDEGetCAPS:PPROC
NDDEGetCAPS equ <__imp_NDDEGetCAPS>

externdef __imp_NDDEGetConnectionConfig:PPROC
NDDEGetConnectionConfig equ <__imp_NDDEGetConnectionConfig>

externdef __imp_NDDEGetConnectionStatus:PPROC
NDDEGetConnectionStatus equ <__imp_NDDEGetConnectionStatus>

externdef __imp_NDDEGetNewConnection:PPROC
NDDEGetNewConnection equ <__imp_NDDEGetNewConnection>

externdef __imp_NDDEInit:PPROC
NDDEInit equ <__imp_NDDEInit>

externdef __imp_NDDERcvPacket:PPROC
NDDERcvPacket equ <__imp_NDDERcvPacket>

externdef __imp_NDDESetConnectionConfig:PPROC
NDDESetConnectionConfig equ <__imp_NDDESetConnectionConfig>

externdef __imp_NDDEShutdown:PPROC
NDDEShutdown equ <__imp_NDDEShutdown>

externdef __imp_NDDETimeSlice:PPROC
NDDETimeSlice equ <__imp_NDDETimeSlice>

externdef __imp_NDDEXmtPacket:PPROC
NDDEXmtPacket equ <__imp_NDDEXmtPacket>
