externdef __imp_AddNetPlaceRunDll:PPROC
AddNetPlaceRunDll equ <__imp_AddNetPlaceRunDll>

externdef __imp_ClearAutoLogon:PPROC
ClearAutoLogon equ <__imp_ClearAutoLogon>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_NetAccessWizard:PPROC
NetAccessWizard equ <__imp_NetAccessWizard>

externdef __imp_NetPlacesWizardDoModal:PPROC
NetPlacesWizardDoModal equ <__imp_NetPlacesWizardDoModal>

externdef __imp_PassportWizardRunDll:PPROC
PassportWizardRunDll equ <__imp_PassportWizardRunDll>

externdef __imp_PublishRunDll:PPROC
PublishRunDll equ <__imp_PublishRunDll>

externdef __imp_SHDisconnectNetDrives:PPROC
SHDisconnectNetDrives equ <__imp_SHDisconnectNetDrives>

externdef __imp_UsersRunDll:PPROC
UsersRunDll equ <__imp_UsersRunDll>
