externdef __imp_ConvertGuidToString:PPROC
ConvertGuidToString equ <__imp_ConvertGuidToString>

externdef __imp_ConvertStringToGuid:PPROC
ConvertStringToGuid equ <__imp_ConvertStringToGuid>

externdef __imp_DisplayMessageM:PPROC
DisplayMessageM equ <__imp_DisplayMessageM>

externdef __imp_DisplayMessageToConsole:PPROC
DisplayMessageToConsole equ <__imp_DisplayMessageToConsole>

externdef __imp_FreeQuotedString:PPROC
FreeQuotedString equ <__imp_FreeQuotedString>

externdef __imp_FreeString:PPROC
FreeString equ <__imp_FreeString>

externdef __imp_GenericMonitor:PPROC
GenericMonitor equ <__imp_GenericMonitor>

externdef __imp_GetEnumString:PPROC
GetEnumString equ <__imp_GetEnumString>

externdef __imp_GetHostMachineInfo:PPROC
GetHostMachineInfo equ <__imp_GetHostMachineInfo>

externdef __imp_InitializeConsole:PPROC
InitializeConsole equ <__imp_InitializeConsole>

externdef __imp_MakeQuotedString:PPROC
MakeQuotedString equ <__imp_MakeQuotedString>

externdef __imp_MakeString:PPROC
MakeString equ <__imp_MakeString>

externdef __imp_MatchCmdLine:PPROC
MatchCmdLine equ <__imp_MatchCmdLine>

externdef __imp_MatchEnumTag:PPROC
MatchEnumTag equ <__imp_MatchEnumTag>

externdef __imp_MatchTagsInCmdLine:PPROC
MatchTagsInCmdLine equ <__imp_MatchTagsInCmdLine>

externdef __imp_MatchToken:PPROC
MatchToken equ <__imp_MatchToken>

externdef __imp_NsGetFriendlyNameFromIfName:PPROC
NsGetFriendlyNameFromIfName equ <__imp_NsGetFriendlyNameFromIfName>

externdef __imp_NsGetIfNameFromFriendlyName:PPROC
NsGetIfNameFromFriendlyName equ <__imp_NsGetIfNameFromFriendlyName>

externdef __imp_PreprocessCommand:PPROC
PreprocessCommand equ <__imp_PreprocessCommand>

externdef __imp_PrintError:PPROC
PrintError equ <__imp_PrintError>

externdef __imp_PrintMessage:PPROC
PrintMessage equ <__imp_PrintMessage>

externdef __imp_PrintMessageFromModule:PPROC
PrintMessageFromModule equ <__imp_PrintMessageFromModule>

externdef __imp_ProcessCommand:PPROC
ProcessCommand equ <__imp_ProcessCommand>

externdef __imp_RefreshConsole:PPROC
RefreshConsole equ <__imp_RefreshConsole>

externdef __imp_RegisterContext:PPROC
RegisterContext equ <__imp_RegisterContext>

externdef __imp_RegisterHelper:PPROC
RegisterHelper equ <__imp_RegisterHelper>
