externdef __imp_ClearEventData:PPROC
ClearEventData equ <__imp_ClearEventData>

externdef __imp_ConvertHexStringToWString:PPROC
ConvertHexStringToWString equ <__imp_ConvertHexStringToWString>

externdef __imp_ConvertWStringToHexString:PPROC
ConvertWStringToHexString equ <__imp_ConvertWStringToHexString>

externdef __imp_CreateBlob:PPROC
CreateBlob equ <__imp_CreateBlob>

externdef __imp_CreateNPPInterface:PPROC
CreateNPPInterface equ <__imp_CreateNPPInterface>

externdef __imp_DestroyBlob:PPROC
DestroyBlob equ <__imp_DestroyBlob>

externdef __imp_DuplicateBlob:PPROC
DuplicateBlob equ <__imp_DuplicateBlob>

externdef __imp_FilterNPPBlob:PPROC
FilterNPPBlob equ <__imp_FilterNPPBlob>

externdef __imp_FindOneOf:PPROC
FindOneOf equ <__imp_FindOneOf>

externdef __imp_FindUnknownBlobCategories:PPROC
FindUnknownBlobCategories equ <__imp_FindUnknownBlobCategories>

externdef __imp_FindUnknownBlobTags:PPROC
FindUnknownBlobTags equ <__imp_FindUnknownBlobTags>

externdef __imp_GetBoolFromBlob:PPROC
GetBoolFromBlob equ <__imp_GetBoolFromBlob>

externdef __imp_GetClassIDFromBlob:PPROC
GetClassIDFromBlob equ <__imp_GetClassIDFromBlob>

externdef __imp_GetDwordFromBlob:PPROC
GetDwordFromBlob equ <__imp_GetDwordFromBlob>

externdef __imp_GetMacAddressFromBlob:PPROC
GetMacAddressFromBlob equ <__imp_GetMacAddressFromBlob>

externdef __imp_GetNPPAddress2FilterFromBlob:PPROC
GetNPPAddress2FilterFromBlob equ <__imp_GetNPPAddress2FilterFromBlob>

externdef __imp_GetNPPAddressFilterFromBlob:PPROC
GetNPPAddressFilterFromBlob equ <__imp_GetNPPAddressFilterFromBlob>

externdef __imp_GetNPPBlobFromUI:PPROC
GetNPPBlobFromUI equ <__imp_GetNPPBlobFromUI>

externdef __imp_GetNPPBlobTable:PPROC
GetNPPBlobTable equ <__imp_GetNPPBlobTable>

externdef __imp_GetNPPEtypeSapFilter:PPROC
GetNPPEtypeSapFilter equ <__imp_GetNPPEtypeSapFilter>

externdef __imp_GetNPPMacTypeAsNumber:PPROC
GetNPPMacTypeAsNumber equ <__imp_GetNPPMacTypeAsNumber>

externdef __imp_GetNPPPatternFilterFromBlob:PPROC
GetNPPPatternFilterFromBlob equ <__imp_GetNPPPatternFilterFromBlob>

externdef __imp_GetNPPTriggerFromBlob:PPROC
GetNPPTriggerFromBlob equ <__imp_GetNPPTriggerFromBlob>

externdef __imp_GetNetworkInfoFromBlob:PPROC
GetNetworkInfoFromBlob equ <__imp_GetNetworkInfoFromBlob>

externdef __imp_GetStringFromBlob:PPROC
GetStringFromBlob equ <__imp_GetStringFromBlob>

externdef __imp_GetStringsFromBlob:PPROC
GetStringsFromBlob equ <__imp_GetStringsFromBlob>

externdef __imp_GetWStringFromBlob:PPROC
GetWStringFromBlob equ <__imp_GetWStringFromBlob>

externdef __imp_IsRemoteNPP:PPROC
IsRemoteNPP equ <__imp_IsRemoteNPP>

externdef __imp_LockBlob:PPROC
LockBlob equ <__imp_LockBlob>

externdef __imp_MarshalBlob:PPROC
MarshalBlob equ <__imp_MarshalBlob>

externdef __imp_MergeBlob:PPROC
MergeBlob equ <__imp_MergeBlob>

externdef __imp_NmAddUsedEntry:PPROC
NmAddUsedEntry equ <__imp_NmAddUsedEntry>

externdef __imp_NmHeapAllocate:PPROC
NmHeapAllocate equ <__imp_NmHeapAllocate>

externdef __imp_NmHeapFree:PPROC
NmHeapFree equ <__imp_NmHeapFree>

externdef __imp_NmHeapReallocate:PPROC
NmHeapReallocate equ <__imp_NmHeapReallocate>

externdef __imp_NmHeapSetMaxSize:PPROC
NmHeapSetMaxSize equ <__imp_NmHeapSetMaxSize>

externdef __imp_NmHeapSize:PPROC
NmHeapSize equ <__imp_NmHeapSize>

externdef __imp_NmRemoveUsedEntry:PPROC
NmRemoveUsedEntry equ <__imp_NmRemoveUsedEntry>

externdef __imp_RaiseNMEvent:PPROC
RaiseNMEvent equ <__imp_RaiseNMEvent>

externdef __imp_ReadBlobFromFile:PPROC
ReadBlobFromFile equ <__imp_ReadBlobFromFile>

externdef __imp_RegCreateBlobKey:PPROC
RegCreateBlobKey equ <__imp_RegCreateBlobKey>

externdef __imp_RegOpenBlobKey:PPROC
RegOpenBlobKey equ <__imp_RegOpenBlobKey>

externdef __imp_ReleaseEventSystem:PPROC
ReleaseEventSystem equ <__imp_ReleaseEventSystem>

externdef __imp_RemoveFromBlob:PPROC
RemoveFromBlob equ <__imp_RemoveFromBlob>

externdef __imp_SelectNPPBlobFromTable:PPROC
SelectNPPBlobFromTable equ <__imp_SelectNPPBlobFromTable>

externdef __imp_SendEvent:PPROC
SendEvent equ <__imp_SendEvent>

externdef __imp_SetBoolInBlob:PPROC
SetBoolInBlob equ <__imp_SetBoolInBlob>

externdef __imp_SetClassIDInBlob:PPROC
SetClassIDInBlob equ <__imp_SetClassIDInBlob>

externdef __imp_SetDwordInBlob:PPROC
SetDwordInBlob equ <__imp_SetDwordInBlob>

externdef __imp_SetMacAddressInBlob:PPROC
SetMacAddressInBlob equ <__imp_SetMacAddressInBlob>

externdef __imp_SetNPPAddress2FilterInBlob:PPROC
SetNPPAddress2FilterInBlob equ <__imp_SetNPPAddress2FilterInBlob>

externdef __imp_SetNPPAddressFilterInBlob:PPROC
SetNPPAddressFilterInBlob equ <__imp_SetNPPAddressFilterInBlob>

externdef __imp_SetNPPEtypeSapFilter:PPROC
SetNPPEtypeSapFilter equ <__imp_SetNPPEtypeSapFilter>

externdef __imp_SetNPPPatternFilterInBlob:PPROC
SetNPPPatternFilterInBlob equ <__imp_SetNPPPatternFilterInBlob>

externdef __imp_SetNPPTriggerInBlob:PPROC
SetNPPTriggerInBlob equ <__imp_SetNPPTriggerInBlob>

externdef __imp_SetNetworkInfoInBlob:PPROC
SetNetworkInfoInBlob equ <__imp_SetNetworkInfoInBlob>

externdef __imp_SetStringInBlob:PPROC
SetStringInBlob equ <__imp_SetStringInBlob>

externdef __imp_SetWStringInBlob:PPROC
SetWStringInBlob equ <__imp_SetWStringInBlob>

externdef __imp_SubkeyExists:PPROC
SubkeyExists equ <__imp_SubkeyExists>

externdef __imp_UnMarshalBlob:PPROC
UnMarshalBlob equ <__imp_UnMarshalBlob>

externdef __imp_UnlockBlob:PPROC
UnlockBlob equ <__imp_UnlockBlob>

externdef __imp_WriteBlobToFile:PPROC
WriteBlobToFile equ <__imp_WriteBlobToFile>

externdef __imp_WriteCrackedBlobToFile:PPROC
WriteCrackedBlobToFile equ <__imp_WriteCrackedBlobToFile>

externdef __imp_recursiveDeleteKey:PPROC
recursiveDeleteKey equ <__imp_recursiveDeleteKey>

externdef __imp_setKeyAndValue:PPROC
setKeyAndValue equ <__imp_setKeyAndValue>
