externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_I_SystemFocusDialog:PPROC
I_SystemFocusDialog equ <__imp_I_SystemFocusDialog>

externdef __imp_IsDfsPathEx:PPROC
IsDfsPathEx equ <__imp_IsDfsPathEx>

externdef __imp_NPAddConnection3:PPROC
NPAddConnection3 equ <__imp_NPAddConnection3>

externdef __imp_NPAddConnection3ForCSCAgent:PPROC
NPAddConnection3ForCSCAgent equ <__imp_NPAddConnection3ForCSCAgent>

externdef __imp_NPAddConnection:PPROC
NPAddConnection equ <__imp_NPAddConnection>

externdef __imp_NPCancelConnection:PPROC
NPCancelConnection equ <__imp_NPCancelConnection>

externdef __imp_NPCancelConnectionForCSCAgent:PPROC
NPCancelConnectionForCSCAgent equ <__imp_NPCancelConnectionForCSCAgent>

externdef __imp_NPCloseEnum:PPROC
NPCloseEnum equ <__imp_NPCloseEnum>

externdef __imp_NPDirectoryNotify:PPROC
NPDirectoryNotify equ <__imp_NPDirectoryNotify>

externdef __imp_NPEnumResource:PPROC
NPEnumResource equ <__imp_NPEnumResource>

externdef __imp_NPFormatNetworkName:PPROC
NPFormatNetworkName equ <__imp_NPFormatNetworkName>

externdef __imp_NPGetCaps:PPROC
NPGetCaps equ <__imp_NPGetCaps>

externdef __imp_NPGetConnection3:PPROC
NPGetConnection3 equ <__imp_NPGetConnection3>

externdef __imp_NPGetConnection:PPROC
NPGetConnection equ <__imp_NPGetConnection>

externdef __imp_NPGetConnectionPerformance:PPROC
NPGetConnectionPerformance equ <__imp_NPGetConnectionPerformance>

externdef __imp_NPGetDirectoryType:PPROC
NPGetDirectoryType equ <__imp_NPGetDirectoryType>

externdef __imp_NPGetPropertyText:PPROC
NPGetPropertyText equ <__imp_NPGetPropertyText>

externdef __imp_NPGetReconnectFlags:PPROC
NPGetReconnectFlags equ <__imp_NPGetReconnectFlags>

externdef __imp_NPGetResourceInformation:PPROC
NPGetResourceInformation equ <__imp_NPGetResourceInformation>

externdef __imp_NPGetResourceParent:PPROC
NPGetResourceParent equ <__imp_NPGetResourceParent>

externdef __imp_NPGetUniversalName:PPROC
NPGetUniversalName equ <__imp_NPGetUniversalName>

externdef __imp_NPGetUser:PPROC
NPGetUser equ <__imp_NPGetUser>

externdef __imp_NPOpenEnum:PPROC
NPOpenEnum equ <__imp_NPOpenEnum>

externdef __imp_NPPropertyDialog:PPROC
NPPropertyDialog equ <__imp_NPPropertyDialog>

externdef __imp_ServerBrowseDialogA0:PPROC
ServerBrowseDialogA0 equ <__imp_ServerBrowseDialogA0>

externdef __imp_ShareAsDialogA0:PPROC
ShareAsDialogA0 equ <__imp_ShareAsDialogA0>

externdef __imp_ShareCreate:PPROC
ShareCreate equ <__imp_ShareCreate>

externdef __imp_ShareManage:PPROC
ShareManage equ <__imp_ShareManage>

externdef __imp_ShareStop:PPROC
ShareStop equ <__imp_ShareStop>

externdef __imp_StopShareDialogA0:PPROC
StopShareDialogA0 equ <__imp_StopShareDialogA0>

externdef __imp_ntlanman_ordinal28:PPROC
ntlanman_ordinal28 equ <__imp_ntlanman_ordinal28>

externdef __imp_ntlanman_ordinal37:PPROC
ntlanman_ordinal37 equ <__imp_ntlanman_ordinal37>

externdef __imp_ntlanman_ordinal39:PPROC
ntlanman_ordinal39 equ <__imp_ntlanman_ordinal39>

externdef __imp_ntlanman_ordinal42:PPROC
ntlanman_ordinal42 equ <__imp_ntlanman_ordinal42>

externdef __imp_ntlanman_ordinal43:PPROC
ntlanman_ordinal43 equ <__imp_ntlanman_ordinal43>

externdef __imp_ntlanman_ordinal44:PPROC
ntlanman_ordinal44 equ <__imp_ntlanman_ordinal44>

externdef __imp_ntlanman_ordinal45:PPROC
ntlanman_ordinal45 equ <__imp_ntlanman_ordinal45>

externdef __imp_ntlanman_ordinal46:PPROC
ntlanman_ordinal46 equ <__imp_ntlanman_ordinal46>

externdef __imp_ntlanman_ordinal47:PPROC
ntlanman_ordinal47 equ <__imp_ntlanman_ordinal47>

externdef __imp_ntlanman_ordinal48:PPROC
ntlanman_ordinal48 equ <__imp_ntlanman_ordinal48>

externdef __imp_ntlanman_ordinal50:PPROC
ntlanman_ordinal50 equ <__imp_ntlanman_ordinal50>

externdef __imp_ntlanman_ordinal51:PPROC
ntlanman_ordinal51 equ <__imp_ntlanman_ordinal51>
