externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_I_SystemFocusDialog:PPROC
I_SystemFocusDialog equ <__imp_I_SystemFocusDialog>

externdef __imp_NPGetPropertyText:PPROC
NPGetPropertyText equ <__imp_NPGetPropertyText>

externdef __imp_NPPropertyDialog:PPROC
NPPropertyDialog equ <__imp_NPPropertyDialog>

externdef __imp_ServerBrowseDialogA0:PPROC
ServerBrowseDialogA0 equ <__imp_ServerBrowseDialogA0>

externdef __imp_ShareAsDialogA0:PPROC
ShareAsDialogA0 equ <__imp_ShareAsDialogA0>

externdef __imp_ShareCreate:PPROC
ShareCreate equ <__imp_ShareCreate>

externdef __imp_ShareManage:PPROC
ShareManage equ <__imp_ShareManage>

externdef __imp_ShareStop:PPROC
ShareStop equ <__imp_ShareStop>

externdef __imp_StopShareDialogA0:PPROC
StopShareDialogA0 equ <__imp_StopShareDialogA0>
