externdef __imp_ReleaseCLStmtResources:PPROC
ReleaseCLStmtResources equ <__imp_ReleaseCLStmtResources>

externdef __imp_SQLBindCol:PPROC
SQLBindCol equ <__imp_SQLBindCol>

externdef __imp_SQLBindParameter:PPROC
SQLBindParameter equ <__imp_SQLBindParameter>

externdef __imp_SQLBulkOperations:PPROC
SQLBulkOperations equ <__imp_SQLBulkOperations>

externdef __imp_SQLCancel:PPROC
SQLCancel equ <__imp_SQLCancel>

externdef __imp_SQLCloseCursor:PPROC
SQLCloseCursor equ <__imp_SQLCloseCursor>

externdef __imp_SQLEndTran:PPROC
SQLEndTran equ <__imp_SQLEndTran>

externdef __imp_SQLExecDirect:PPROC
SQLExecDirect equ <__imp_SQLExecDirect>

externdef __imp_SQLExecute:PPROC
SQLExecute equ <__imp_SQLExecute>

externdef __imp_SQLExtendedFetch:PPROC
SQLExtendedFetch equ <__imp_SQLExtendedFetch>

externdef __imp_SQLFetch:PPROC
SQLFetch equ <__imp_SQLFetch>

externdef __imp_SQLFetchScroll:PPROC
SQLFetchScroll equ <__imp_SQLFetchScroll>

externdef __imp_SQLFreeHandle:PPROC
SQLFreeHandle equ <__imp_SQLFreeHandle>

externdef __imp_SQLFreeStmt:PPROC
SQLFreeStmt equ <__imp_SQLFreeStmt>

externdef __imp_SQLGetData:PPROC
SQLGetData equ <__imp_SQLGetData>

externdef __imp_SQLGetDescField:PPROC
SQLGetDescField equ <__imp_SQLGetDescField>

externdef __imp_SQLGetDescRec:PPROC
SQLGetDescRec equ <__imp_SQLGetDescRec>

externdef __imp_SQLGetInfo:PPROC
SQLGetInfo equ <__imp_SQLGetInfo>

externdef __imp_SQLGetStmtAttr:PPROC
SQLGetStmtAttr equ <__imp_SQLGetStmtAttr>

externdef __imp_SQLGetStmtOption:PPROC
SQLGetStmtOption equ <__imp_SQLGetStmtOption>

externdef __imp_SQLMoreResults:PPROC
SQLMoreResults equ <__imp_SQLMoreResults>

externdef __imp_SQLNativeSql:PPROC
SQLNativeSql equ <__imp_SQLNativeSql>

externdef __imp_SQLNumParams:PPROC
SQLNumParams equ <__imp_SQLNumParams>

externdef __imp_SQLParamData:PPROC
SQLParamData equ <__imp_SQLParamData>

externdef __imp_SQLParamOptions:PPROC
SQLParamOptions equ <__imp_SQLParamOptions>

externdef __imp_SQLPrepare:PPROC
SQLPrepare equ <__imp_SQLPrepare>

externdef __imp_SQLPutData:PPROC
SQLPutData equ <__imp_SQLPutData>

externdef __imp_SQLRowCount:PPROC
SQLRowCount equ <__imp_SQLRowCount>

externdef __imp_SQLSetConnectAttr:PPROC
SQLSetConnectAttr equ <__imp_SQLSetConnectAttr>

externdef __imp_SQLSetConnectOption:PPROC
SQLSetConnectOption equ <__imp_SQLSetConnectOption>

externdef __imp_SQLSetDescField:PPROC
SQLSetDescField equ <__imp_SQLSetDescField>

externdef __imp_SQLSetDescRec:PPROC
SQLSetDescRec equ <__imp_SQLSetDescRec>

externdef __imp_SQLSetPos:PPROC
SQLSetPos equ <__imp_SQLSetPos>

externdef __imp_SQLSetScrollOptions:PPROC
SQLSetScrollOptions equ <__imp_SQLSetScrollOptions>

externdef __imp_SQLSetStmtAttr:PPROC
SQLSetStmtAttr equ <__imp_SQLSetStmtAttr>

externdef __imp_SQLSetStmtOption:PPROC
SQLSetStmtOption equ <__imp_SQLSetStmtOption>

externdef __imp_SQLTransact:PPROC
SQLTransact equ <__imp_SQLTransact>

externdef __imp_odbccu32_ordinal10:PPROC
odbccu32_ordinal10 equ <__imp_odbccu32_ordinal10>

externdef __imp_odbccu32_ordinal14:PPROC
odbccu32_ordinal14 equ <__imp_odbccu32_ordinal14>

externdef __imp_odbccu32_ordinal15:PPROC
odbccu32_ordinal15 equ <__imp_odbccu32_ordinal15>

externdef __imp_odbccu32_ordinal17:PPROC
odbccu32_ordinal17 equ <__imp_odbccu32_ordinal17>

externdef __imp_odbccu32_ordinal18:PPROC
odbccu32_ordinal18 equ <__imp_odbccu32_ordinal18>

externdef __imp_odbccu32_ordinal21:PPROC
odbccu32_ordinal21 equ <__imp_odbccu32_ordinal21>

externdef __imp_odbccu32_ordinal22:PPROC
odbccu32_ordinal22 equ <__imp_odbccu32_ordinal22>

externdef __imp_odbccu32_ordinal24:PPROC
odbccu32_ordinal24 equ <__imp_odbccu32_ordinal24>

externdef __imp_odbccu32_ordinal25:PPROC
odbccu32_ordinal25 equ <__imp_odbccu32_ordinal25>

externdef __imp_odbccu32_ordinal27:PPROC
odbccu32_ordinal27 equ <__imp_odbccu32_ordinal27>

externdef __imp_odbccu32_ordinal28:PPROC
odbccu32_ordinal28 equ <__imp_odbccu32_ordinal28>

externdef __imp_odbccu32_ordinal32:PPROC
odbccu32_ordinal32 equ <__imp_odbccu32_ordinal32>

externdef __imp_odbccu32_ordinal35:PPROC
odbccu32_ordinal35 equ <__imp_odbccu32_ordinal35>

externdef __imp_odbccu32_ordinal36:PPROC
odbccu32_ordinal36 equ <__imp_odbccu32_ordinal36>

externdef __imp_odbccu32_ordinal37:PPROC
odbccu32_ordinal37 equ <__imp_odbccu32_ordinal37>

externdef __imp_odbccu32_ordinal40:PPROC
odbccu32_ordinal40 equ <__imp_odbccu32_ordinal40>

externdef __imp_odbccu32_ordinal41:PPROC
odbccu32_ordinal41 equ <__imp_odbccu32_ordinal41>

externdef __imp_odbccu32_ordinal42:PPROC
odbccu32_ordinal42 equ <__imp_odbccu32_ordinal42>

externdef __imp_odbccu32_ordinal44:PPROC
odbccu32_ordinal44 equ <__imp_odbccu32_ordinal44>

externdef __imp_odbccu32_ordinal47:PPROC
odbccu32_ordinal47 equ <__imp_odbccu32_ordinal47>

externdef __imp_odbccu32_ordinal52:PPROC
odbccu32_ordinal52 equ <__imp_odbccu32_ordinal52>

externdef __imp_odbccu32_ordinal53:PPROC
odbccu32_ordinal53 equ <__imp_odbccu32_ordinal53>

externdef __imp_odbccu32_ordinal54:PPROC
odbccu32_ordinal54 equ <__imp_odbccu32_ordinal54>

externdef __imp_odbccu32_ordinal55:PPROC
odbccu32_ordinal55 equ <__imp_odbccu32_ordinal55>

externdef __imp_odbccu32_ordinal56:PPROC
odbccu32_ordinal56 equ <__imp_odbccu32_ordinal56>

externdef __imp_odbccu32_ordinal57:PPROC
odbccu32_ordinal57 equ <__imp_odbccu32_ordinal57>

externdef __imp_odbccu32_ordinal58:PPROC
odbccu32_ordinal58 equ <__imp_odbccu32_ordinal58>

externdef __imp_odbccu32_ordinal60:PPROC
odbccu32_ordinal60 equ <__imp_odbccu32_ordinal60>

externdef __imp_odbccu32_ordinal65:PPROC
odbccu32_ordinal65 equ <__imp_odbccu32_ordinal65>

externdef __imp_odbccu32_ordinal66:PPROC
odbccu32_ordinal66 equ <__imp_odbccu32_ordinal66>

externdef __imp_odbccu32_ordinal67:PPROC
odbccu32_ordinal67 equ <__imp_odbccu32_ordinal67>

externdef __imp_odbccu32_ordinal70:PPROC
odbccu32_ordinal70 equ <__imp_odbccu32_ordinal70>

externdef __imp_odbccu32_ordinal71:PPROC
odbccu32_ordinal71 equ <__imp_odbccu32_ordinal71>

externdef __imp_odbccu32_ordinal75:PPROC
odbccu32_ordinal75 equ <__imp_odbccu32_ordinal75>

externdef __imp_odbccu32_ordinal77:PPROC
odbccu32_ordinal77 equ <__imp_odbccu32_ordinal77>

externdef __imp_odbccu32_ordinal7:PPROC
odbccu32_ordinal7 equ <__imp_odbccu32_ordinal7>

externdef __imp_odbccu32_ordinal8:PPROC
odbccu32_ordinal8 equ <__imp_odbccu32_ordinal8>

externdef __imp_odbccu32_ordinal9:PPROC
odbccu32_ordinal9 equ <__imp_odbccu32_ordinal9>
