externdef __imp_BSTR_UserFree64:PPROC
BSTR_UserFree64 equ <__imp_BSTR_UserFree64>

externdef __imp_BSTR_UserFree:PPROC
BSTR_UserFree equ <__imp_BSTR_UserFree>

externdef __imp_BSTR_UserMarshal64:PPROC
BSTR_UserMarshal64 equ <__imp_BSTR_UserMarshal64>

externdef __imp_BSTR_UserMarshal:PPROC
BSTR_UserMarshal equ <__imp_BSTR_UserMarshal>

externdef __imp_BSTR_UserSize64:PPROC
BSTR_UserSize64 equ <__imp_BSTR_UserSize64>

externdef __imp_BSTR_UserSize:PPROC
BSTR_UserSize equ <__imp_BSTR_UserSize>

externdef __imp_BSTR_UserUnmarshal64:PPROC
BSTR_UserUnmarshal64 equ <__imp_BSTR_UserUnmarshal64>

externdef __imp_BSTR_UserUnmarshal:PPROC
BSTR_UserUnmarshal equ <__imp_BSTR_UserUnmarshal>

externdef __imp_BstrFromVector:PPROC
BstrFromVector equ <__imp_BstrFromVector>

externdef __imp_ClearCustData:PPROC
ClearCustData equ <__imp_ClearCustData>

externdef __imp_CreateDispTypeInfo:PPROC
CreateDispTypeInfo equ <__imp_CreateDispTypeInfo>

externdef __imp_CreateErrorInfo:PPROC
CreateErrorInfo equ <__imp_CreateErrorInfo>

externdef __imp_CreateStdDispatch:PPROC
CreateStdDispatch equ <__imp_CreateStdDispatch>

externdef __imp_CreateTypeLib2:PPROC
CreateTypeLib2 equ <__imp_CreateTypeLib2>

externdef __imp_CreateTypeLib:PPROC
CreateTypeLib equ <__imp_CreateTypeLib>

externdef __imp_DispCallFunc:PPROC
DispCallFunc equ <__imp_DispCallFunc>

externdef __imp_DispGetIDsOfNames:PPROC
DispGetIDsOfNames equ <__imp_DispGetIDsOfNames>

externdef __imp_DispGetParam:PPROC
DispGetParam equ <__imp_DispGetParam>

externdef __imp_DispInvoke:PPROC
DispInvoke equ <__imp_DispInvoke>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DosDateTimeToVariantTime:PPROC
DosDateTimeToVariantTime equ <__imp_DosDateTimeToVariantTime>

externdef __imp_GetActiveObject:PPROC
GetActiveObject equ <__imp_GetActiveObject>

externdef __imp_GetAltMonthNames:PPROC
GetAltMonthNames equ <__imp_GetAltMonthNames>

externdef __imp_GetErrorInfo:PPROC
GetErrorInfo equ <__imp_GetErrorInfo>

externdef __imp_GetRecordInfoFromGuids:PPROC
GetRecordInfoFromGuids equ <__imp_GetRecordInfoFromGuids>

externdef __imp_GetRecordInfoFromTypeInfo:PPROC
GetRecordInfoFromTypeInfo equ <__imp_GetRecordInfoFromTypeInfo>

externdef __imp_GetVarConversionLocaleSetting:PPROC
GetVarConversionLocaleSetting equ <__imp_GetVarConversionLocaleSetting>

externdef __imp_LHashValOfNameSys:PPROC
LHashValOfNameSys equ <__imp_LHashValOfNameSys>

externdef __imp_LHashValOfNameSysA:PPROC
LHashValOfNameSysA equ <__imp_LHashValOfNameSysA>
  IFNDEF __UNICODE__
    LHashValOfNameSys equ <__imp_LHashValOfNameSysA>
  ENDIF

externdef __imp_LPSAFEARRAY_Marshal:PPROC
LPSAFEARRAY_Marshal equ <__imp_LPSAFEARRAY_Marshal>

externdef __imp_LPSAFEARRAY_Size:PPROC
LPSAFEARRAY_Size equ <__imp_LPSAFEARRAY_Size>

externdef __imp_LPSAFEARRAY_Unmarshal:PPROC
LPSAFEARRAY_Unmarshal equ <__imp_LPSAFEARRAY_Unmarshal>

externdef __imp_LPSAFEARRAY_UserFree64:PPROC
LPSAFEARRAY_UserFree64 equ <__imp_LPSAFEARRAY_UserFree64>

externdef __imp_LPSAFEARRAY_UserFree:PPROC
LPSAFEARRAY_UserFree equ <__imp_LPSAFEARRAY_UserFree>

externdef __imp_LPSAFEARRAY_UserMarshal64:PPROC
LPSAFEARRAY_UserMarshal64 equ <__imp_LPSAFEARRAY_UserMarshal64>

externdef __imp_LPSAFEARRAY_UserMarshal:PPROC
LPSAFEARRAY_UserMarshal equ <__imp_LPSAFEARRAY_UserMarshal>

externdef __imp_LPSAFEARRAY_UserSize64:PPROC
LPSAFEARRAY_UserSize64 equ <__imp_LPSAFEARRAY_UserSize64>

externdef __imp_LPSAFEARRAY_UserSize:PPROC
LPSAFEARRAY_UserSize equ <__imp_LPSAFEARRAY_UserSize>

externdef __imp_LPSAFEARRAY_UserUnmarshal64:PPROC
LPSAFEARRAY_UserUnmarshal64 equ <__imp_LPSAFEARRAY_UserUnmarshal64>

externdef __imp_LPSAFEARRAY_UserUnmarshal:PPROC
LPSAFEARRAY_UserUnmarshal equ <__imp_LPSAFEARRAY_UserUnmarshal>

externdef __imp_LoadRegTypeLib:PPROC
LoadRegTypeLib equ <__imp_LoadRegTypeLib>

externdef __imp_LoadTypeLib:PPROC
LoadTypeLib equ <__imp_LoadTypeLib>

externdef __imp_LoadTypeLibEx:PPROC
LoadTypeLibEx equ <__imp_LoadTypeLibEx>

externdef __imp_OACreateTypeLib2:PPROC
OACreateTypeLib2 equ <__imp_OACreateTypeLib2>

externdef __imp_OaBuildVersion:PPROC
OaBuildVersion equ <__imp_OaBuildVersion>

externdef __imp_OleCreateFontIndirect:PPROC
OleCreateFontIndirect equ <__imp_OleCreateFontIndirect>

externdef __imp_OleCreatePictureIndirect:PPROC
OleCreatePictureIndirect equ <__imp_OleCreatePictureIndirect>

externdef __imp_OleCreatePropertyFrame:PPROC
OleCreatePropertyFrame equ <__imp_OleCreatePropertyFrame>

externdef __imp_OleCreatePropertyFrameIndirect:PPROC
OleCreatePropertyFrameIndirect equ <__imp_OleCreatePropertyFrameIndirect>

externdef __imp_OleIconToCursor:PPROC
OleIconToCursor equ <__imp_OleIconToCursor>

externdef __imp_OleLoadPicture:PPROC
OleLoadPicture equ <__imp_OleLoadPicture>

externdef __imp_OleLoadPictureEx:PPROC
OleLoadPictureEx equ <__imp_OleLoadPictureEx>

externdef __imp_OleLoadPictureFile:PPROC
OleLoadPictureFile equ <__imp_OleLoadPictureFile>

externdef __imp_OleLoadPictureFileEx:PPROC
OleLoadPictureFileEx equ <__imp_OleLoadPictureFileEx>

externdef __imp_OleLoadPicturePath:PPROC
OleLoadPicturePath equ <__imp_OleLoadPicturePath>

externdef __imp_OleSavePictureFile:PPROC
OleSavePictureFile equ <__imp_OleSavePictureFile>

externdef __imp_OleTranslateColor:PPROC
OleTranslateColor equ <__imp_OleTranslateColor>

externdef __imp_QueryPathOfRegTypeLib:PPROC
QueryPathOfRegTypeLib equ <__imp_QueryPathOfRegTypeLib>

externdef __imp_RegisterActiveObject:PPROC
RegisterActiveObject equ <__imp_RegisterActiveObject>

externdef __imp_RegisterTypeLib:PPROC
RegisterTypeLib equ <__imp_RegisterTypeLib>

externdef __imp_RegisterTypeLibForUser:PPROC
RegisterTypeLibForUser equ <__imp_RegisterTypeLibForUser>

externdef __imp_RevokeActiveObject:PPROC
RevokeActiveObject equ <__imp_RevokeActiveObject>

externdef __imp_SafeArrayAccessData:PPROC
SafeArrayAccessData equ <__imp_SafeArrayAccessData>

externdef __imp_SafeArrayAllocData:PPROC
SafeArrayAllocData equ <__imp_SafeArrayAllocData>

externdef __imp_SafeArrayAllocDescriptor:PPROC
SafeArrayAllocDescriptor equ <__imp_SafeArrayAllocDescriptor>

externdef __imp_SafeArrayAllocDescriptorEx:PPROC
SafeArrayAllocDescriptorEx equ <__imp_SafeArrayAllocDescriptorEx>

externdef __imp_SafeArrayCopy:PPROC
SafeArrayCopy equ <__imp_SafeArrayCopy>

externdef __imp_SafeArrayCopyData:PPROC
SafeArrayCopyData equ <__imp_SafeArrayCopyData>

externdef __imp_SafeArrayCreate:PPROC
SafeArrayCreate equ <__imp_SafeArrayCreate>

externdef __imp_SafeArrayCreateEx:PPROC
SafeArrayCreateEx equ <__imp_SafeArrayCreateEx>

externdef __imp_SafeArrayCreateVector:PPROC
SafeArrayCreateVector equ <__imp_SafeArrayCreateVector>

externdef __imp_SafeArrayCreateVectorEx:PPROC
SafeArrayCreateVectorEx equ <__imp_SafeArrayCreateVectorEx>

externdef __imp_SafeArrayDestroy:PPROC
SafeArrayDestroy equ <__imp_SafeArrayDestroy>

externdef __imp_SafeArrayDestroyData:PPROC
SafeArrayDestroyData equ <__imp_SafeArrayDestroyData>

externdef __imp_SafeArrayDestroyDescriptor:PPROC
SafeArrayDestroyDescriptor equ <__imp_SafeArrayDestroyDescriptor>

externdef __imp_SafeArrayGetDim:PPROC
SafeArrayGetDim equ <__imp_SafeArrayGetDim>

externdef __imp_SafeArrayGetElement:PPROC
SafeArrayGetElement equ <__imp_SafeArrayGetElement>

externdef __imp_SafeArrayGetElemsize:PPROC
SafeArrayGetElemsize equ <__imp_SafeArrayGetElemsize>

externdef __imp_SafeArrayGetIID:PPROC
SafeArrayGetIID equ <__imp_SafeArrayGetIID>

externdef __imp_SafeArrayGetLBound:PPROC
SafeArrayGetLBound equ <__imp_SafeArrayGetLBound>

externdef __imp_SafeArrayGetRecordInfo:PPROC
SafeArrayGetRecordInfo equ <__imp_SafeArrayGetRecordInfo>

externdef __imp_SafeArrayGetUBound:PPROC
SafeArrayGetUBound equ <__imp_SafeArrayGetUBound>

externdef __imp_SafeArrayGetVartype:PPROC
SafeArrayGetVartype equ <__imp_SafeArrayGetVartype>

externdef __imp_SafeArrayLock:PPROC
SafeArrayLock equ <__imp_SafeArrayLock>

externdef __imp_SafeArrayPtrOfIndex:PPROC
SafeArrayPtrOfIndex equ <__imp_SafeArrayPtrOfIndex>

externdef __imp_SafeArrayPutElement:PPROC
SafeArrayPutElement equ <__imp_SafeArrayPutElement>

externdef __imp_SafeArrayRedim:PPROC
SafeArrayRedim equ <__imp_SafeArrayRedim>

externdef __imp_SafeArraySetIID:PPROC
SafeArraySetIID equ <__imp_SafeArraySetIID>

externdef __imp_SafeArraySetRecordInfo:PPROC
SafeArraySetRecordInfo equ <__imp_SafeArraySetRecordInfo>

externdef __imp_SafeArrayUnaccessData:PPROC
SafeArrayUnaccessData equ <__imp_SafeArrayUnaccessData>

externdef __imp_SafeArrayUnlock:PPROC
SafeArrayUnlock equ <__imp_SafeArrayUnlock>

externdef __imp_SetErrorInfo:PPROC
SetErrorInfo equ <__imp_SetErrorInfo>

externdef __imp_SetOaNoCache:PPROC
SetOaNoCache equ <__imp_SetOaNoCache>

externdef __imp_SetVarConversionLocaleSetting:PPROC
SetVarConversionLocaleSetting equ <__imp_SetVarConversionLocaleSetting>

externdef __imp_SysAllocString:PPROC
SysAllocString equ <__imp_SysAllocString>

externdef __imp_SysAllocStringByteLen:PPROC
SysAllocStringByteLen equ <__imp_SysAllocStringByteLen>

externdef __imp_SysAllocStringLen:PPROC
SysAllocStringLen equ <__imp_SysAllocStringLen>

externdef __imp_SysFreeString:PPROC
SysFreeString equ <__imp_SysFreeString>

externdef __imp_SysReAllocString:PPROC
SysReAllocString equ <__imp_SysReAllocString>

externdef __imp_SysReAllocStringLen:PPROC
SysReAllocStringLen equ <__imp_SysReAllocStringLen>

externdef __imp_SysStringByteLen:PPROC
SysStringByteLen equ <__imp_SysStringByteLen>

externdef __imp_SysStringLen:PPROC
SysStringLen equ <__imp_SysStringLen>

externdef __imp_SystemTimeToVariantTime:PPROC
SystemTimeToVariantTime equ <__imp_SystemTimeToVariantTime>

externdef __imp_UnRegisterTypeLib:PPROC
UnRegisterTypeLib equ <__imp_UnRegisterTypeLib>

externdef __imp_UnRegisterTypeLibForUser:PPROC
UnRegisterTypeLibForUser equ <__imp_UnRegisterTypeLibForUser>

externdef __imp_VARIANT_UserFree64:PPROC
VARIANT_UserFree64 equ <__imp_VARIANT_UserFree64>

externdef __imp_VARIANT_UserFree:PPROC
VARIANT_UserFree equ <__imp_VARIANT_UserFree>

externdef __imp_VARIANT_UserMarshal64:PPROC
VARIANT_UserMarshal64 equ <__imp_VARIANT_UserMarshal64>

externdef __imp_VARIANT_UserMarshal:PPROC
VARIANT_UserMarshal equ <__imp_VARIANT_UserMarshal>

externdef __imp_VARIANT_UserSize64:PPROC
VARIANT_UserSize64 equ <__imp_VARIANT_UserSize64>

externdef __imp_VARIANT_UserSize:PPROC
VARIANT_UserSize equ <__imp_VARIANT_UserSize>

externdef __imp_VARIANT_UserUnmarshal64:PPROC
VARIANT_UserUnmarshal64 equ <__imp_VARIANT_UserUnmarshal64>

externdef __imp_VARIANT_UserUnmarshal:PPROC
VARIANT_UserUnmarshal equ <__imp_VARIANT_UserUnmarshal>

externdef __imp_VarAbs:PPROC
VarAbs equ <__imp_VarAbs>

externdef __imp_VarAdd:PPROC
VarAdd equ <__imp_VarAdd>

externdef __imp_VarAnd:PPROC
VarAnd equ <__imp_VarAnd>

externdef __imp_VarBoolFromCy:PPROC
VarBoolFromCy equ <__imp_VarBoolFromCy>

externdef __imp_VarBoolFromDate:PPROC
VarBoolFromDate equ <__imp_VarBoolFromDate>

externdef __imp_VarBoolFromDec:PPROC
VarBoolFromDec equ <__imp_VarBoolFromDec>

externdef __imp_VarBoolFromDisp:PPROC
VarBoolFromDisp equ <__imp_VarBoolFromDisp>

externdef __imp_VarBoolFromI1:PPROC
VarBoolFromI1 equ <__imp_VarBoolFromI1>

externdef __imp_VarBoolFromI2:PPROC
VarBoolFromI2 equ <__imp_VarBoolFromI2>

externdef __imp_VarBoolFromI4:PPROC
VarBoolFromI4 equ <__imp_VarBoolFromI4>

externdef __imp_VarBoolFromI8:PPROC
VarBoolFromI8 equ <__imp_VarBoolFromI8>

externdef __imp_VarBoolFromR4:PPROC
VarBoolFromR4 equ <__imp_VarBoolFromR4>

externdef __imp_VarBoolFromR8:PPROC
VarBoolFromR8 equ <__imp_VarBoolFromR8>

externdef __imp_VarBoolFromStr:PPROC
VarBoolFromStr equ <__imp_VarBoolFromStr>

externdef __imp_VarBoolFromUI1:PPROC
VarBoolFromUI1 equ <__imp_VarBoolFromUI1>

externdef __imp_VarBoolFromUI2:PPROC
VarBoolFromUI2 equ <__imp_VarBoolFromUI2>

externdef __imp_VarBoolFromUI4:PPROC
VarBoolFromUI4 equ <__imp_VarBoolFromUI4>

externdef __imp_VarBoolFromUI8:PPROC
VarBoolFromUI8 equ <__imp_VarBoolFromUI8>

externdef __imp_VarBstrCat:PPROC
VarBstrCat equ <__imp_VarBstrCat>

externdef __imp_VarBstrCmp:PPROC
VarBstrCmp equ <__imp_VarBstrCmp>

externdef __imp_VarBstrFromBool:PPROC
VarBstrFromBool equ <__imp_VarBstrFromBool>

externdef __imp_VarBstrFromCy:PPROC
VarBstrFromCy equ <__imp_VarBstrFromCy>

externdef __imp_VarBstrFromDate:PPROC
VarBstrFromDate equ <__imp_VarBstrFromDate>

externdef __imp_VarBstrFromDec:PPROC
VarBstrFromDec equ <__imp_VarBstrFromDec>

externdef __imp_VarBstrFromDisp:PPROC
VarBstrFromDisp equ <__imp_VarBstrFromDisp>

externdef __imp_VarBstrFromI1:PPROC
VarBstrFromI1 equ <__imp_VarBstrFromI1>

externdef __imp_VarBstrFromI2:PPROC
VarBstrFromI2 equ <__imp_VarBstrFromI2>

externdef __imp_VarBstrFromI4:PPROC
VarBstrFromI4 equ <__imp_VarBstrFromI4>

externdef __imp_VarBstrFromI8:PPROC
VarBstrFromI8 equ <__imp_VarBstrFromI8>

externdef __imp_VarBstrFromR4:PPROC
VarBstrFromR4 equ <__imp_VarBstrFromR4>

externdef __imp_VarBstrFromR8:PPROC
VarBstrFromR8 equ <__imp_VarBstrFromR8>

externdef __imp_VarBstrFromUI1:PPROC
VarBstrFromUI1 equ <__imp_VarBstrFromUI1>

externdef __imp_VarBstrFromUI2:PPROC
VarBstrFromUI2 equ <__imp_VarBstrFromUI2>

externdef __imp_VarBstrFromUI4:PPROC
VarBstrFromUI4 equ <__imp_VarBstrFromUI4>

externdef __imp_VarBstrFromUI8:PPROC
VarBstrFromUI8 equ <__imp_VarBstrFromUI8>

externdef __imp_VarCat:PPROC
VarCat equ <__imp_VarCat>

externdef __imp_VarCmp:PPROC
VarCmp equ <__imp_VarCmp>

externdef __imp_VarCyAbs:PPROC
VarCyAbs equ <__imp_VarCyAbs>

externdef __imp_VarCyAdd:PPROC
VarCyAdd equ <__imp_VarCyAdd>

externdef __imp_VarCyCmp:PPROC
VarCyCmp equ <__imp_VarCyCmp>

externdef __imp_VarCyCmpR8:PPROC
VarCyCmpR8 equ <__imp_VarCyCmpR8>

externdef __imp_VarCyFix:PPROC
VarCyFix equ <__imp_VarCyFix>

externdef __imp_VarCyFromBool:PPROC
VarCyFromBool equ <__imp_VarCyFromBool>

externdef __imp_VarCyFromDate:PPROC
VarCyFromDate equ <__imp_VarCyFromDate>

externdef __imp_VarCyFromDec:PPROC
VarCyFromDec equ <__imp_VarCyFromDec>

externdef __imp_VarCyFromDisp:PPROC
VarCyFromDisp equ <__imp_VarCyFromDisp>

externdef __imp_VarCyFromI1:PPROC
VarCyFromI1 equ <__imp_VarCyFromI1>

externdef __imp_VarCyFromI2:PPROC
VarCyFromI2 equ <__imp_VarCyFromI2>

externdef __imp_VarCyFromI4:PPROC
VarCyFromI4 equ <__imp_VarCyFromI4>

externdef __imp_VarCyFromI8:PPROC
VarCyFromI8 equ <__imp_VarCyFromI8>

externdef __imp_VarCyFromR4:PPROC
VarCyFromR4 equ <__imp_VarCyFromR4>

externdef __imp_VarCyFromR8:PPROC
VarCyFromR8 equ <__imp_VarCyFromR8>

externdef __imp_VarCyFromStr:PPROC
VarCyFromStr equ <__imp_VarCyFromStr>

externdef __imp_VarCyFromUI1:PPROC
VarCyFromUI1 equ <__imp_VarCyFromUI1>

externdef __imp_VarCyFromUI2:PPROC
VarCyFromUI2 equ <__imp_VarCyFromUI2>

externdef __imp_VarCyFromUI4:PPROC
VarCyFromUI4 equ <__imp_VarCyFromUI4>

externdef __imp_VarCyFromUI8:PPROC
VarCyFromUI8 equ <__imp_VarCyFromUI8>

externdef __imp_VarCyInt:PPROC
VarCyInt equ <__imp_VarCyInt>

externdef __imp_VarCyMul:PPROC
VarCyMul equ <__imp_VarCyMul>

externdef __imp_VarCyMulI4:PPROC
VarCyMulI4 equ <__imp_VarCyMulI4>

externdef __imp_VarCyMulI8:PPROC
VarCyMulI8 equ <__imp_VarCyMulI8>

externdef __imp_VarCyNeg:PPROC
VarCyNeg equ <__imp_VarCyNeg>

externdef __imp_VarCyRound:PPROC
VarCyRound equ <__imp_VarCyRound>

externdef __imp_VarCySub:PPROC
VarCySub equ <__imp_VarCySub>

externdef __imp_VarDateFromBool:PPROC
VarDateFromBool equ <__imp_VarDateFromBool>

externdef __imp_VarDateFromCy:PPROC
VarDateFromCy equ <__imp_VarDateFromCy>

externdef __imp_VarDateFromDec:PPROC
VarDateFromDec equ <__imp_VarDateFromDec>

externdef __imp_VarDateFromDisp:PPROC
VarDateFromDisp equ <__imp_VarDateFromDisp>

externdef __imp_VarDateFromI1:PPROC
VarDateFromI1 equ <__imp_VarDateFromI1>

externdef __imp_VarDateFromI2:PPROC
VarDateFromI2 equ <__imp_VarDateFromI2>

externdef __imp_VarDateFromI4:PPROC
VarDateFromI4 equ <__imp_VarDateFromI4>

externdef __imp_VarDateFromI8:PPROC
VarDateFromI8 equ <__imp_VarDateFromI8>

externdef __imp_VarDateFromR4:PPROC
VarDateFromR4 equ <__imp_VarDateFromR4>

externdef __imp_VarDateFromR8:PPROC
VarDateFromR8 equ <__imp_VarDateFromR8>

externdef __imp_VarDateFromStr:PPROC
VarDateFromStr equ <__imp_VarDateFromStr>

externdef __imp_VarDateFromUI1:PPROC
VarDateFromUI1 equ <__imp_VarDateFromUI1>

externdef __imp_VarDateFromUI2:PPROC
VarDateFromUI2 equ <__imp_VarDateFromUI2>

externdef __imp_VarDateFromUI4:PPROC
VarDateFromUI4 equ <__imp_VarDateFromUI4>

externdef __imp_VarDateFromUI8:PPROC
VarDateFromUI8 equ <__imp_VarDateFromUI8>

externdef __imp_VarDateFromUdate:PPROC
VarDateFromUdate equ <__imp_VarDateFromUdate>

externdef __imp_VarDateFromUdateEx:PPROC
VarDateFromUdateEx equ <__imp_VarDateFromUdateEx>

externdef __imp_VarDecAbs:PPROC
VarDecAbs equ <__imp_VarDecAbs>

externdef __imp_VarDecAdd:PPROC
VarDecAdd equ <__imp_VarDecAdd>

externdef __imp_VarDecCmp:PPROC
VarDecCmp equ <__imp_VarDecCmp>

externdef __imp_VarDecCmpR8:PPROC
VarDecCmpR8 equ <__imp_VarDecCmpR8>

externdef __imp_VarDecDiv:PPROC
VarDecDiv equ <__imp_VarDecDiv>

externdef __imp_VarDecFix:PPROC
VarDecFix equ <__imp_VarDecFix>

externdef __imp_VarDecFromBool:PPROC
VarDecFromBool equ <__imp_VarDecFromBool>

externdef __imp_VarDecFromCy:PPROC
VarDecFromCy equ <__imp_VarDecFromCy>

externdef __imp_VarDecFromDate:PPROC
VarDecFromDate equ <__imp_VarDecFromDate>

externdef __imp_VarDecFromDisp:PPROC
VarDecFromDisp equ <__imp_VarDecFromDisp>

externdef __imp_VarDecFromI1:PPROC
VarDecFromI1 equ <__imp_VarDecFromI1>

externdef __imp_VarDecFromI2:PPROC
VarDecFromI2 equ <__imp_VarDecFromI2>

externdef __imp_VarDecFromI4:PPROC
VarDecFromI4 equ <__imp_VarDecFromI4>

externdef __imp_VarDecFromI8:PPROC
VarDecFromI8 equ <__imp_VarDecFromI8>

externdef __imp_VarDecFromR4:PPROC
VarDecFromR4 equ <__imp_VarDecFromR4>

externdef __imp_VarDecFromR8:PPROC
VarDecFromR8 equ <__imp_VarDecFromR8>

externdef __imp_VarDecFromStr:PPROC
VarDecFromStr equ <__imp_VarDecFromStr>

externdef __imp_VarDecFromUI1:PPROC
VarDecFromUI1 equ <__imp_VarDecFromUI1>

externdef __imp_VarDecFromUI2:PPROC
VarDecFromUI2 equ <__imp_VarDecFromUI2>

externdef __imp_VarDecFromUI4:PPROC
VarDecFromUI4 equ <__imp_VarDecFromUI4>

externdef __imp_VarDecFromUI8:PPROC
VarDecFromUI8 equ <__imp_VarDecFromUI8>

externdef __imp_VarDecInt:PPROC
VarDecInt equ <__imp_VarDecInt>

externdef __imp_VarDecMul:PPROC
VarDecMul equ <__imp_VarDecMul>

externdef __imp_VarDecNeg:PPROC
VarDecNeg equ <__imp_VarDecNeg>

externdef __imp_VarDecRound:PPROC
VarDecRound equ <__imp_VarDecRound>

externdef __imp_VarDecSub:PPROC
VarDecSub equ <__imp_VarDecSub>

externdef __imp_VarDiv:PPROC
VarDiv equ <__imp_VarDiv>

externdef __imp_VarEqv:PPROC
VarEqv equ <__imp_VarEqv>

externdef __imp_VarFix:PPROC
VarFix equ <__imp_VarFix>

externdef __imp_VarFormat:PPROC
VarFormat equ <__imp_VarFormat>

externdef __imp_VarFormatCurrency:PPROC
VarFormatCurrency equ <__imp_VarFormatCurrency>

externdef __imp_VarFormatDateTime:PPROC
VarFormatDateTime equ <__imp_VarFormatDateTime>

externdef __imp_VarFormatFromTokens:PPROC
VarFormatFromTokens equ <__imp_VarFormatFromTokens>

externdef __imp_VarFormatNumber:PPROC
VarFormatNumber equ <__imp_VarFormatNumber>

externdef __imp_VarFormatPercent:PPROC
VarFormatPercent equ <__imp_VarFormatPercent>

externdef __imp_VarI1FromBool:PPROC
VarI1FromBool equ <__imp_VarI1FromBool>

externdef __imp_VarI1FromCy:PPROC
VarI1FromCy equ <__imp_VarI1FromCy>

externdef __imp_VarI1FromDate:PPROC
VarI1FromDate equ <__imp_VarI1FromDate>

externdef __imp_VarI1FromDec:PPROC
VarI1FromDec equ <__imp_VarI1FromDec>

externdef __imp_VarI1FromDisp:PPROC
VarI1FromDisp equ <__imp_VarI1FromDisp>

externdef __imp_VarI1FromI2:PPROC
VarI1FromI2 equ <__imp_VarI1FromI2>

externdef __imp_VarI1FromI4:PPROC
VarI1FromI4 equ <__imp_VarI1FromI4>

externdef __imp_VarI1FromI8:PPROC
VarI1FromI8 equ <__imp_VarI1FromI8>

externdef __imp_VarI1FromR4:PPROC
VarI1FromR4 equ <__imp_VarI1FromR4>

externdef __imp_VarI1FromR8:PPROC
VarI1FromR8 equ <__imp_VarI1FromR8>

externdef __imp_VarI1FromStr:PPROC
VarI1FromStr equ <__imp_VarI1FromStr>

externdef __imp_VarI1FromUI1:PPROC
VarI1FromUI1 equ <__imp_VarI1FromUI1>

externdef __imp_VarI1FromUI2:PPROC
VarI1FromUI2 equ <__imp_VarI1FromUI2>

externdef __imp_VarI1FromUI4:PPROC
VarI1FromUI4 equ <__imp_VarI1FromUI4>

externdef __imp_VarI1FromUI8:PPROC
VarI1FromUI8 equ <__imp_VarI1FromUI8>

externdef __imp_VarI2FromBool:PPROC
VarI2FromBool equ <__imp_VarI2FromBool>

externdef __imp_VarI2FromCy:PPROC
VarI2FromCy equ <__imp_VarI2FromCy>

externdef __imp_VarI2FromDate:PPROC
VarI2FromDate equ <__imp_VarI2FromDate>

externdef __imp_VarI2FromDec:PPROC
VarI2FromDec equ <__imp_VarI2FromDec>

externdef __imp_VarI2FromDisp:PPROC
VarI2FromDisp equ <__imp_VarI2FromDisp>

externdef __imp_VarI2FromI1:PPROC
VarI2FromI1 equ <__imp_VarI2FromI1>

externdef __imp_VarI2FromI4:PPROC
VarI2FromI4 equ <__imp_VarI2FromI4>

externdef __imp_VarI2FromI8:PPROC
VarI2FromI8 equ <__imp_VarI2FromI8>

externdef __imp_VarI2FromR4:PPROC
VarI2FromR4 equ <__imp_VarI2FromR4>

externdef __imp_VarI2FromR8:PPROC
VarI2FromR8 equ <__imp_VarI2FromR8>

externdef __imp_VarI2FromStr:PPROC
VarI2FromStr equ <__imp_VarI2FromStr>

externdef __imp_VarI2FromUI1:PPROC
VarI2FromUI1 equ <__imp_VarI2FromUI1>

externdef __imp_VarI2FromUI2:PPROC
VarI2FromUI2 equ <__imp_VarI2FromUI2>

externdef __imp_VarI2FromUI4:PPROC
VarI2FromUI4 equ <__imp_VarI2FromUI4>

externdef __imp_VarI2FromUI8:PPROC
VarI2FromUI8 equ <__imp_VarI2FromUI8>

externdef __imp_VarI4FromBool:PPROC
VarI4FromBool equ <__imp_VarI4FromBool>

externdef __imp_VarI4FromCy:PPROC
VarI4FromCy equ <__imp_VarI4FromCy>

externdef __imp_VarI4FromDate:PPROC
VarI4FromDate equ <__imp_VarI4FromDate>

externdef __imp_VarI4FromDec:PPROC
VarI4FromDec equ <__imp_VarI4FromDec>

externdef __imp_VarI4FromDisp:PPROC
VarI4FromDisp equ <__imp_VarI4FromDisp>

externdef __imp_VarI4FromI1:PPROC
VarI4FromI1 equ <__imp_VarI4FromI1>

externdef __imp_VarI4FromI2:PPROC
VarI4FromI2 equ <__imp_VarI4FromI2>

externdef __imp_VarI4FromI8:PPROC
VarI4FromI8 equ <__imp_VarI4FromI8>

externdef __imp_VarI4FromR4:PPROC
VarI4FromR4 equ <__imp_VarI4FromR4>

externdef __imp_VarI4FromR8:PPROC
VarI4FromR8 equ <__imp_VarI4FromR8>

externdef __imp_VarI4FromStr:PPROC
VarI4FromStr equ <__imp_VarI4FromStr>

externdef __imp_VarI4FromUI1:PPROC
VarI4FromUI1 equ <__imp_VarI4FromUI1>

externdef __imp_VarI4FromUI2:PPROC
VarI4FromUI2 equ <__imp_VarI4FromUI2>

externdef __imp_VarI4FromUI4:PPROC
VarI4FromUI4 equ <__imp_VarI4FromUI4>

externdef __imp_VarI4FromUI8:PPROC
VarI4FromUI8 equ <__imp_VarI4FromUI8>

externdef __imp_VarI8FromBool:PPROC
VarI8FromBool equ <__imp_VarI8FromBool>

externdef __imp_VarI8FromCy:PPROC
VarI8FromCy equ <__imp_VarI8FromCy>

externdef __imp_VarI8FromDate:PPROC
VarI8FromDate equ <__imp_VarI8FromDate>

externdef __imp_VarI8FromDec:PPROC
VarI8FromDec equ <__imp_VarI8FromDec>

externdef __imp_VarI8FromDisp:PPROC
VarI8FromDisp equ <__imp_VarI8FromDisp>

externdef __imp_VarI8FromI1:PPROC
VarI8FromI1 equ <__imp_VarI8FromI1>

externdef __imp_VarI8FromI2:PPROC
VarI8FromI2 equ <__imp_VarI8FromI2>

externdef __imp_VarI8FromR4:PPROC
VarI8FromR4 equ <__imp_VarI8FromR4>

externdef __imp_VarI8FromR8:PPROC
VarI8FromR8 equ <__imp_VarI8FromR8>

externdef __imp_VarI8FromStr:PPROC
VarI8FromStr equ <__imp_VarI8FromStr>

externdef __imp_VarI8FromUI1:PPROC
VarI8FromUI1 equ <__imp_VarI8FromUI1>

externdef __imp_VarI8FromUI2:PPROC
VarI8FromUI2 equ <__imp_VarI8FromUI2>

externdef __imp_VarI8FromUI4:PPROC
VarI8FromUI4 equ <__imp_VarI8FromUI4>

externdef __imp_VarI8FromUI8:PPROC
VarI8FromUI8 equ <__imp_VarI8FromUI8>

externdef __imp_VarIdiv:PPROC
VarIdiv equ <__imp_VarIdiv>

externdef __imp_VarImp:PPROC
VarImp equ <__imp_VarImp>

externdef __imp_VarInt:PPROC
VarInt equ <__imp_VarInt>

externdef __imp_VarMod:PPROC
VarMod equ <__imp_VarMod>

externdef __imp_VarMonthName:PPROC
VarMonthName equ <__imp_VarMonthName>

externdef __imp_VarMul:PPROC
VarMul equ <__imp_VarMul>

externdef __imp_VarNeg:PPROC
VarNeg equ <__imp_VarNeg>

externdef __imp_VarNot:PPROC
VarNot equ <__imp_VarNot>

externdef __imp_VarNumFromParseNum:PPROC
VarNumFromParseNum equ <__imp_VarNumFromParseNum>

externdef __imp_VarOr:PPROC
VarOr equ <__imp_VarOr>

externdef __imp_VarParseNumFromStr:PPROC
VarParseNumFromStr equ <__imp_VarParseNumFromStr>

externdef __imp_VarPow:PPROC
VarPow equ <__imp_VarPow>

externdef __imp_VarR4CmpR8:PPROC
VarR4CmpR8 equ <__imp_VarR4CmpR8>

externdef __imp_VarR4FromBool:PPROC
VarR4FromBool equ <__imp_VarR4FromBool>

externdef __imp_VarR4FromCy:PPROC
VarR4FromCy equ <__imp_VarR4FromCy>

externdef __imp_VarR4FromDate:PPROC
VarR4FromDate equ <__imp_VarR4FromDate>

externdef __imp_VarR4FromDec:PPROC
VarR4FromDec equ <__imp_VarR4FromDec>

externdef __imp_VarR4FromDisp:PPROC
VarR4FromDisp equ <__imp_VarR4FromDisp>

externdef __imp_VarR4FromI1:PPROC
VarR4FromI1 equ <__imp_VarR4FromI1>

externdef __imp_VarR4FromI2:PPROC
VarR4FromI2 equ <__imp_VarR4FromI2>

externdef __imp_VarR4FromI4:PPROC
VarR4FromI4 equ <__imp_VarR4FromI4>

externdef __imp_VarR4FromI8:PPROC
VarR4FromI8 equ <__imp_VarR4FromI8>

externdef __imp_VarR4FromR8:PPROC
VarR4FromR8 equ <__imp_VarR4FromR8>

externdef __imp_VarR4FromStr:PPROC
VarR4FromStr equ <__imp_VarR4FromStr>

externdef __imp_VarR4FromUI1:PPROC
VarR4FromUI1 equ <__imp_VarR4FromUI1>

externdef __imp_VarR4FromUI2:PPROC
VarR4FromUI2 equ <__imp_VarR4FromUI2>

externdef __imp_VarR4FromUI4:PPROC
VarR4FromUI4 equ <__imp_VarR4FromUI4>

externdef __imp_VarR4FromUI8:PPROC
VarR4FromUI8 equ <__imp_VarR4FromUI8>

externdef __imp_VarR8FromBool:PPROC
VarR8FromBool equ <__imp_VarR8FromBool>

externdef __imp_VarR8FromCy:PPROC
VarR8FromCy equ <__imp_VarR8FromCy>

externdef __imp_VarR8FromDate:PPROC
VarR8FromDate equ <__imp_VarR8FromDate>

externdef __imp_VarR8FromDec:PPROC
VarR8FromDec equ <__imp_VarR8FromDec>

externdef __imp_VarR8FromDisp:PPROC
VarR8FromDisp equ <__imp_VarR8FromDisp>

externdef __imp_VarR8FromI1:PPROC
VarR8FromI1 equ <__imp_VarR8FromI1>

externdef __imp_VarR8FromI2:PPROC
VarR8FromI2 equ <__imp_VarR8FromI2>

externdef __imp_VarR8FromI4:PPROC
VarR8FromI4 equ <__imp_VarR8FromI4>

externdef __imp_VarR8FromI8:PPROC
VarR8FromI8 equ <__imp_VarR8FromI8>

externdef __imp_VarR8FromR4:PPROC
VarR8FromR4 equ <__imp_VarR8FromR4>

externdef __imp_VarR8FromStr:PPROC
VarR8FromStr equ <__imp_VarR8FromStr>

externdef __imp_VarR8FromUI1:PPROC
VarR8FromUI1 equ <__imp_VarR8FromUI1>

externdef __imp_VarR8FromUI2:PPROC
VarR8FromUI2 equ <__imp_VarR8FromUI2>

externdef __imp_VarR8FromUI4:PPROC
VarR8FromUI4 equ <__imp_VarR8FromUI4>

externdef __imp_VarR8FromUI8:PPROC
VarR8FromUI8 equ <__imp_VarR8FromUI8>

externdef __imp_VarR8Pow:PPROC
VarR8Pow equ <__imp_VarR8Pow>

externdef __imp_VarR8Round:PPROC
VarR8Round equ <__imp_VarR8Round>

externdef __imp_VarRound:PPROC
VarRound equ <__imp_VarRound>

externdef __imp_VarSub:PPROC
VarSub equ <__imp_VarSub>

externdef __imp_VarTokenizeFormatString:PPROC
VarTokenizeFormatString equ <__imp_VarTokenizeFormatString>

externdef __imp_VarUI1FromBool:PPROC
VarUI1FromBool equ <__imp_VarUI1FromBool>

externdef __imp_VarUI1FromCy:PPROC
VarUI1FromCy equ <__imp_VarUI1FromCy>

externdef __imp_VarUI1FromDate:PPROC
VarUI1FromDate equ <__imp_VarUI1FromDate>

externdef __imp_VarUI1FromDec:PPROC
VarUI1FromDec equ <__imp_VarUI1FromDec>

externdef __imp_VarUI1FromDisp:PPROC
VarUI1FromDisp equ <__imp_VarUI1FromDisp>

externdef __imp_VarUI1FromI1:PPROC
VarUI1FromI1 equ <__imp_VarUI1FromI1>

externdef __imp_VarUI1FromI2:PPROC
VarUI1FromI2 equ <__imp_VarUI1FromI2>

externdef __imp_VarUI1FromI4:PPROC
VarUI1FromI4 equ <__imp_VarUI1FromI4>

externdef __imp_VarUI1FromI8:PPROC
VarUI1FromI8 equ <__imp_VarUI1FromI8>

externdef __imp_VarUI1FromR4:PPROC
VarUI1FromR4 equ <__imp_VarUI1FromR4>

externdef __imp_VarUI1FromR8:PPROC
VarUI1FromR8 equ <__imp_VarUI1FromR8>

externdef __imp_VarUI1FromStr:PPROC
VarUI1FromStr equ <__imp_VarUI1FromStr>

externdef __imp_VarUI1FromUI2:PPROC
VarUI1FromUI2 equ <__imp_VarUI1FromUI2>

externdef __imp_VarUI1FromUI4:PPROC
VarUI1FromUI4 equ <__imp_VarUI1FromUI4>

externdef __imp_VarUI1FromUI8:PPROC
VarUI1FromUI8 equ <__imp_VarUI1FromUI8>

externdef __imp_VarUI2FromBool:PPROC
VarUI2FromBool equ <__imp_VarUI2FromBool>

externdef __imp_VarUI2FromCy:PPROC
VarUI2FromCy equ <__imp_VarUI2FromCy>

externdef __imp_VarUI2FromDate:PPROC
VarUI2FromDate equ <__imp_VarUI2FromDate>

externdef __imp_VarUI2FromDec:PPROC
VarUI2FromDec equ <__imp_VarUI2FromDec>

externdef __imp_VarUI2FromDisp:PPROC
VarUI2FromDisp equ <__imp_VarUI2FromDisp>

externdef __imp_VarUI2FromI1:PPROC
VarUI2FromI1 equ <__imp_VarUI2FromI1>

externdef __imp_VarUI2FromI2:PPROC
VarUI2FromI2 equ <__imp_VarUI2FromI2>

externdef __imp_VarUI2FromI4:PPROC
VarUI2FromI4 equ <__imp_VarUI2FromI4>

externdef __imp_VarUI2FromI8:PPROC
VarUI2FromI8 equ <__imp_VarUI2FromI8>

externdef __imp_VarUI2FromR4:PPROC
VarUI2FromR4 equ <__imp_VarUI2FromR4>

externdef __imp_VarUI2FromR8:PPROC
VarUI2FromR8 equ <__imp_VarUI2FromR8>

externdef __imp_VarUI2FromStr:PPROC
VarUI2FromStr equ <__imp_VarUI2FromStr>

externdef __imp_VarUI2FromUI1:PPROC
VarUI2FromUI1 equ <__imp_VarUI2FromUI1>

externdef __imp_VarUI2FromUI4:PPROC
VarUI2FromUI4 equ <__imp_VarUI2FromUI4>

externdef __imp_VarUI2FromUI8:PPROC
VarUI2FromUI8 equ <__imp_VarUI2FromUI8>

externdef __imp_VarUI4FromBool:PPROC
VarUI4FromBool equ <__imp_VarUI4FromBool>

externdef __imp_VarUI4FromCy:PPROC
VarUI4FromCy equ <__imp_VarUI4FromCy>

externdef __imp_VarUI4FromDate:PPROC
VarUI4FromDate equ <__imp_VarUI4FromDate>

externdef __imp_VarUI4FromDec:PPROC
VarUI4FromDec equ <__imp_VarUI4FromDec>

externdef __imp_VarUI4FromDisp:PPROC
VarUI4FromDisp equ <__imp_VarUI4FromDisp>

externdef __imp_VarUI4FromI1:PPROC
VarUI4FromI1 equ <__imp_VarUI4FromI1>

externdef __imp_VarUI4FromI2:PPROC
VarUI4FromI2 equ <__imp_VarUI4FromI2>

externdef __imp_VarUI4FromI4:PPROC
VarUI4FromI4 equ <__imp_VarUI4FromI4>

externdef __imp_VarUI4FromI8:PPROC
VarUI4FromI8 equ <__imp_VarUI4FromI8>

externdef __imp_VarUI4FromR4:PPROC
VarUI4FromR4 equ <__imp_VarUI4FromR4>

externdef __imp_VarUI4FromR8:PPROC
VarUI4FromR8 equ <__imp_VarUI4FromR8>

externdef __imp_VarUI4FromStr:PPROC
VarUI4FromStr equ <__imp_VarUI4FromStr>

externdef __imp_VarUI4FromUI1:PPROC
VarUI4FromUI1 equ <__imp_VarUI4FromUI1>

externdef __imp_VarUI4FromUI2:PPROC
VarUI4FromUI2 equ <__imp_VarUI4FromUI2>

externdef __imp_VarUI4FromUI8:PPROC
VarUI4FromUI8 equ <__imp_VarUI4FromUI8>

externdef __imp_VarUI8FromBool:PPROC
VarUI8FromBool equ <__imp_VarUI8FromBool>

externdef __imp_VarUI8FromCy:PPROC
VarUI8FromCy equ <__imp_VarUI8FromCy>

externdef __imp_VarUI8FromDate:PPROC
VarUI8FromDate equ <__imp_VarUI8FromDate>

externdef __imp_VarUI8FromDec:PPROC
VarUI8FromDec equ <__imp_VarUI8FromDec>

externdef __imp_VarUI8FromDisp:PPROC
VarUI8FromDisp equ <__imp_VarUI8FromDisp>

externdef __imp_VarUI8FromI1:PPROC
VarUI8FromI1 equ <__imp_VarUI8FromI1>

externdef __imp_VarUI8FromI2:PPROC
VarUI8FromI2 equ <__imp_VarUI8FromI2>

externdef __imp_VarUI8FromI8:PPROC
VarUI8FromI8 equ <__imp_VarUI8FromI8>

externdef __imp_VarUI8FromR4:PPROC
VarUI8FromR4 equ <__imp_VarUI8FromR4>

externdef __imp_VarUI8FromR8:PPROC
VarUI8FromR8 equ <__imp_VarUI8FromR8>

externdef __imp_VarUI8FromStr:PPROC
VarUI8FromStr equ <__imp_VarUI8FromStr>

externdef __imp_VarUI8FromUI1:PPROC
VarUI8FromUI1 equ <__imp_VarUI8FromUI1>

externdef __imp_VarUI8FromUI2:PPROC
VarUI8FromUI2 equ <__imp_VarUI8FromUI2>

externdef __imp_VarUI8FromUI4:PPROC
VarUI8FromUI4 equ <__imp_VarUI8FromUI4>

externdef __imp_VarUdateFromDate:PPROC
VarUdateFromDate equ <__imp_VarUdateFromDate>

externdef __imp_VarWeekdayName:PPROC
VarWeekdayName equ <__imp_VarWeekdayName>

externdef __imp_VarXor:PPROC
VarXor equ <__imp_VarXor>

externdef __imp_VariantChangeType:PPROC
VariantChangeType equ <__imp_VariantChangeType>

externdef __imp_VariantChangeTypeEx:PPROC
VariantChangeTypeEx equ <__imp_VariantChangeTypeEx>

externdef __imp_VariantClear:PPROC
VariantClear equ <__imp_VariantClear>

externdef __imp_VariantCopy:PPROC
VariantCopy equ <__imp_VariantCopy>

externdef __imp_VariantCopyInd:PPROC
VariantCopyInd equ <__imp_VariantCopyInd>

externdef __imp_VariantInit:PPROC
VariantInit equ <__imp_VariantInit>

externdef __imp_VariantTimeToDosDateTime:PPROC
VariantTimeToDosDateTime equ <__imp_VariantTimeToDosDateTime>

externdef __imp_VariantTimeToSystemTime:PPROC
VariantTimeToSystemTime equ <__imp_VariantTimeToSystemTime>

externdef __imp_VectorFromBstr:PPROC
VectorFromBstr equ <__imp_VectorFromBstr>

externdef __imp_oleaut32_ordinal357:PPROC
oleaut32_ordinal357 equ <__imp_oleaut32_ordinal357>

externdef __imp_oleaut32_ordinal358:PPROC
oleaut32_ordinal358 equ <__imp_oleaut32_ordinal358>

externdef __imp_oleaut32_ordinal359:PPROC
oleaut32_ordinal359 equ <__imp_oleaut32_ordinal359>

externdef __imp_oleaut32_ordinal380:PPROC
oleaut32_ordinal380 equ <__imp_oleaut32_ordinal380>

externdef __imp_oleaut32_ordinal381:PPROC
oleaut32_ordinal381 equ <__imp_oleaut32_ordinal381>

externdef __imp_oleaut32_ordinal382:PPROC
oleaut32_ordinal382 equ <__imp_oleaut32_ordinal382>

externdef __imp_oleaut32_ordinal383:PPROC
oleaut32_ordinal383 equ <__imp_oleaut32_ordinal383>

externdef __imp_oleaut32_ordinal384:PPROC
oleaut32_ordinal384 equ <__imp_oleaut32_ordinal384>

externdef __imp_oleaut32_ordinal385:PPROC
oleaut32_ordinal385 equ <__imp_oleaut32_ordinal385>

externdef __imp_oleaut32_ordinal386:PPROC
oleaut32_ordinal386 equ <__imp_oleaut32_ordinal386>

externdef __imp_oleaut32_ordinal387:PPROC
oleaut32_ordinal387 equ <__imp_oleaut32_ordinal387>

externdef __imp_oleaut32_ordinal388:PPROC
oleaut32_ordinal388 equ <__imp_oleaut32_ordinal388>

externdef __imp_oleaut32_ordinal389:PPROC
oleaut32_ordinal389 equ <__imp_oleaut32_ordinal389>

externdef __imp_oleaut32_ordinal390:PPROC
oleaut32_ordinal390 equ <__imp_oleaut32_ordinal390>

externdef __imp_oleaut32_ordinal391:PPROC
oleaut32_ordinal391 equ <__imp_oleaut32_ordinal391>

externdef __imp_oleaut32_ordinal392:PPROC
oleaut32_ordinal392 equ <__imp_oleaut32_ordinal392>

externdef __imp_oleaut32_ordinal393:PPROC
oleaut32_ordinal393 equ <__imp_oleaut32_ordinal393>

externdef __imp_oleaut32_ordinal394:PPROC
oleaut32_ordinal394 equ <__imp_oleaut32_ordinal394>

externdef __imp_oleaut32_ordinal395:PPROC
oleaut32_ordinal395 equ <__imp_oleaut32_ordinal395>

externdef __imp_oleaut32_ordinal396:PPROC
oleaut32_ordinal396 equ <__imp_oleaut32_ordinal396>

externdef __imp_oleaut32_ordinal397:PPROC
oleaut32_ordinal397 equ <__imp_oleaut32_ordinal397>

externdef __imp_oleaut32_ordinal398:PPROC
oleaut32_ordinal398 equ <__imp_oleaut32_ordinal398>

externdef __imp_oleaut32_ordinal399:PPROC
oleaut32_ordinal399 equ <__imp_oleaut32_ordinal399>

externdef __imp_oleaut32_ordinal400:PPROC
oleaut32_ordinal400 equ <__imp_oleaut32_ordinal400>

externdef __imp_oleaut32_ordinal403:PPROC
oleaut32_ordinal403 equ <__imp_oleaut32_ordinal403>

externdef __imp_oleaut32_ordinal404:PPROC
oleaut32_ordinal404 equ <__imp_oleaut32_ordinal404>

externdef __imp_oleaut32_ordinal405:PPROC
oleaut32_ordinal405 equ <__imp_oleaut32_ordinal405>

externdef __imp_oleaut32_ordinal406:PPROC
oleaut32_ordinal406 equ <__imp_oleaut32_ordinal406>

externdef __imp_oleaut32_ordinal407:PPROC
oleaut32_ordinal407 equ <__imp_oleaut32_ordinal407>

externdef __imp_oleaut32_ordinal408:PPROC
oleaut32_ordinal408 equ <__imp_oleaut32_ordinal408>

externdef __imp_oleaut32_ordinal409:PPROC
oleaut32_ordinal409 equ <__imp_oleaut32_ordinal409>

externdef __imp_oleaut32_ordinal410:PPROC
oleaut32_ordinal410 equ <__imp_oleaut32_ordinal410>
