externdef __imp_BmChangeData:PPROC
BmChangeData equ <__imp_BmChangeData>

externdef __imp_BmClone:PPROC
BmClone equ <__imp_BmClone>

externdef __imp_BmCopy:PPROC
BmCopy equ <__imp_BmCopy>

externdef __imp_BmDraw:PPROC
BmDraw equ <__imp_BmDraw>

externdef __imp_BmEnumFormat:PPROC
BmEnumFormat equ <__imp_BmEnumFormat>

externdef __imp_BmEqual:PPROC
BmEqual equ <__imp_BmEqual>

externdef __imp_BmGetData:PPROC
BmGetData equ <__imp_BmGetData>

externdef __imp_BmQueryBounds:PPROC
BmQueryBounds equ <__imp_BmQueryBounds>

externdef __imp_BmRelease:PPROC
BmRelease equ <__imp_BmRelease>

externdef __imp_BmSaveToStream:PPROC
BmSaveToStream equ <__imp_BmSaveToStream>

externdef __imp_CheckNetDrive:PPROC
CheckNetDrive equ <__imp_CheckNetDrive>

externdef __imp_ConnectDlgProc:PPROC
ConnectDlgProc equ <__imp_ConnectDlgProc>

externdef __imp_DefCreate:PPROC
DefCreate equ <__imp_DefCreate>

externdef __imp_DefCreateFromClip:PPROC
DefCreateFromClip equ <__imp_DefCreateFromClip>

externdef __imp_DefCreateFromFile:PPROC
DefCreateFromFile equ <__imp_DefCreateFromFile>

externdef __imp_DefCreateFromTemplate:PPROC
DefCreateFromTemplate equ <__imp_DefCreateFromTemplate>

externdef __imp_DefCreateInvisible:PPROC
DefCreateInvisible equ <__imp_DefCreateInvisible>

externdef __imp_DefCreateLinkFromClip:PPROC
DefCreateLinkFromClip equ <__imp_DefCreateLinkFromClip>

externdef __imp_DefCreateLinkFromFile:PPROC
DefCreateLinkFromFile equ <__imp_DefCreateLinkFromFile>

externdef __imp_DefLoadFromStream:PPROC
DefLoadFromStream equ <__imp_DefLoadFromStream>

externdef __imp_DibChangeData:PPROC
DibChangeData equ <__imp_DibChangeData>

externdef __imp_DibClone:PPROC
DibClone equ <__imp_DibClone>

externdef __imp_DibCopy:PPROC
DibCopy equ <__imp_DibCopy>

externdef __imp_DibDraw:PPROC
DibDraw equ <__imp_DibDraw>

externdef __imp_DibEnumFormat:PPROC
DibEnumFormat equ <__imp_DibEnumFormat>

externdef __imp_DibEqual:PPROC
DibEqual equ <__imp_DibEqual>

externdef __imp_DibGetData:PPROC
DibGetData equ <__imp_DibGetData>

externdef __imp_DibQueryBounds:PPROC
DibQueryBounds equ <__imp_DibQueryBounds>

externdef __imp_DibRelease:PPROC
DibRelease equ <__imp_DibRelease>

externdef __imp_DibSaveToStream:PPROC
DibSaveToStream equ <__imp_DibSaveToStream>

externdef __imp_DocWndProc:PPROC
DocWndProc equ <__imp_DocWndProc>

externdef __imp_ErrActivate:PPROC
ErrActivate equ <__imp_ErrActivate>

externdef __imp_ErrClose:PPROC
ErrClose equ <__imp_ErrClose>

externdef __imp_ErrCopyFromLink:PPROC
ErrCopyFromLink equ <__imp_ErrCopyFromLink>

externdef __imp_ErrExecute:PPROC
ErrExecute equ <__imp_ErrExecute>

externdef __imp_ErrGetUpdateOptions:PPROC
ErrGetUpdateOptions equ <__imp_ErrGetUpdateOptions>

externdef __imp_ErrObjectConvert:PPROC
ErrObjectConvert equ <__imp_ErrObjectConvert>

externdef __imp_ErrObjectLong:PPROC
ErrObjectLong equ <__imp_ErrObjectLong>

externdef __imp_ErrQueryOpen:PPROC
ErrQueryOpen equ <__imp_ErrQueryOpen>

externdef __imp_ErrQueryOutOfDate:PPROC
ErrQueryOutOfDate equ <__imp_ErrQueryOutOfDate>

externdef __imp_ErrQueryProtocol:PPROC
ErrQueryProtocol equ <__imp_ErrQueryProtocol>

externdef __imp_ErrReconnect:PPROC
ErrReconnect equ <__imp_ErrReconnect>

externdef __imp_ErrSetBounds:PPROC
ErrSetBounds equ <__imp_ErrSetBounds>

externdef __imp_ErrSetData:PPROC
ErrSetData equ <__imp_ErrSetData>

externdef __imp_ErrSetHostNames:PPROC
ErrSetHostNames equ <__imp_ErrSetHostNames>

externdef __imp_ErrSetTargetDevice:PPROC
ErrSetTargetDevice equ <__imp_ErrSetTargetDevice>

externdef __imp_ErrSetUpdateOptions:PPROC
ErrSetUpdateOptions equ <__imp_ErrSetUpdateOptions>

externdef __imp_ErrShow:PPROC
ErrShow equ <__imp_ErrShow>

externdef __imp_ErrUpdate:PPROC
ErrUpdate equ <__imp_ErrUpdate>

externdef __imp_GenChangeData:PPROC
GenChangeData equ <__imp_GenChangeData>

externdef __imp_GenClone:PPROC
GenClone equ <__imp_GenClone>

externdef __imp_GenCopy:PPROC
GenCopy equ <__imp_GenCopy>

externdef __imp_GenDraw:PPROC
GenDraw equ <__imp_GenDraw>

externdef __imp_GenEnumFormat:PPROC
GenEnumFormat equ <__imp_GenEnumFormat>

externdef __imp_GenEqual:PPROC
GenEqual equ <__imp_GenEqual>

externdef __imp_GenGetData:PPROC
GenGetData equ <__imp_GenGetData>

externdef __imp_GenQueryBounds:PPROC
GenQueryBounds equ <__imp_GenQueryBounds>

externdef __imp_GenRelease:PPROC
GenRelease equ <__imp_GenRelease>

externdef __imp_GenSaveToStream:PPROC
GenSaveToStream equ <__imp_GenSaveToStream>

externdef __imp_GenSetData:PPROC
GenSetData equ <__imp_GenSetData>

externdef __imp_GetTaskVisibleWindow:PPROC
GetTaskVisibleWindow equ <__imp_GetTaskVisibleWindow>

externdef __imp_LeActivate:PPROC
LeActivate equ <__imp_LeActivate>

externdef __imp_LeChangeData:PPROC
LeChangeData equ <__imp_LeChangeData>

externdef __imp_LeClone:PPROC
LeClone equ <__imp_LeClone>

externdef __imp_LeClose:PPROC
LeClose equ <__imp_LeClose>

externdef __imp_LeCopy:PPROC
LeCopy equ <__imp_LeCopy>

externdef __imp_LeCopyFromLink:PPROC
LeCopyFromLink equ <__imp_LeCopyFromLink>

externdef __imp_LeCreateInvisible:PPROC
LeCreateInvisible equ <__imp_LeCreateInvisible>

externdef __imp_LeDraw:PPROC
LeDraw equ <__imp_LeDraw>

externdef __imp_LeEnumFormat:PPROC
LeEnumFormat equ <__imp_LeEnumFormat>

externdef __imp_LeEqual:PPROC
LeEqual equ <__imp_LeEqual>

externdef __imp_LeExecute:PPROC
LeExecute equ <__imp_LeExecute>

externdef __imp_LeGetData:PPROC
LeGetData equ <__imp_LeGetData>

externdef __imp_LeGetUpdateOptions:PPROC
LeGetUpdateOptions equ <__imp_LeGetUpdateOptions>

externdef __imp_LeObjectConvert:PPROC
LeObjectConvert equ <__imp_LeObjectConvert>

externdef __imp_LeObjectLong:PPROC
LeObjectLong equ <__imp_LeObjectLong>

externdef __imp_LeQueryBounds:PPROC
LeQueryBounds equ <__imp_LeQueryBounds>

externdef __imp_LeQueryOpen:PPROC
LeQueryOpen equ <__imp_LeQueryOpen>

externdef __imp_LeQueryOutOfDate:PPROC
LeQueryOutOfDate equ <__imp_LeQueryOutOfDate>

externdef __imp_LeQueryProtocol:PPROC
LeQueryProtocol equ <__imp_LeQueryProtocol>

externdef __imp_LeQueryType:PPROC
LeQueryType equ <__imp_LeQueryType>

externdef __imp_LeReconnect:PPROC
LeReconnect equ <__imp_LeReconnect>

externdef __imp_LeRelease:PPROC
LeRelease equ <__imp_LeRelease>

externdef __imp_LeSaveToStream:PPROC
LeSaveToStream equ <__imp_LeSaveToStream>

externdef __imp_LeSetBounds:PPROC
LeSetBounds equ <__imp_LeSetBounds>

externdef __imp_LeSetData:PPROC
LeSetData equ <__imp_LeSetData>

externdef __imp_LeSetHostNames:PPROC
LeSetHostNames equ <__imp_LeSetHostNames>

externdef __imp_LeSetTargetDevice:PPROC
LeSetTargetDevice equ <__imp_LeSetTargetDevice>

externdef __imp_LeSetUpdateOptions:PPROC
LeSetUpdateOptions equ <__imp_LeSetUpdateOptions>

externdef __imp_LeShow:PPROC
LeShow equ <__imp_LeShow>

externdef __imp_LeUpdate:PPROC
LeUpdate equ <__imp_LeUpdate>

externdef __imp_MfCallbackFunc:PPROC
MfCallbackFunc equ <__imp_MfCallbackFunc>

externdef __imp_MfChangeData:PPROC
MfChangeData equ <__imp_MfChangeData>

externdef __imp_MfClone:PPROC
MfClone equ <__imp_MfClone>

externdef __imp_MfCopy:PPROC
MfCopy equ <__imp_MfCopy>

externdef __imp_MfDraw:PPROC
MfDraw equ <__imp_MfDraw>

externdef __imp_MfEnumFormat:PPROC
MfEnumFormat equ <__imp_MfEnumFormat>

externdef __imp_MfEqual:PPROC
MfEqual equ <__imp_MfEqual>

externdef __imp_MfGetData:PPROC
MfGetData equ <__imp_MfGetData>

externdef __imp_MfQueryBounds:PPROC
MfQueryBounds equ <__imp_MfQueryBounds>

externdef __imp_MfRelease:PPROC
MfRelease equ <__imp_MfRelease>

externdef __imp_MfSaveToStream:PPROC
MfSaveToStream equ <__imp_MfSaveToStream>

externdef __imp_ObjQueryName:PPROC
ObjQueryName equ <__imp_ObjQueryName>

externdef __imp_ObjQuerySize:PPROC
ObjQuerySize equ <__imp_ObjQuerySize>

externdef __imp_ObjQueryType:PPROC
ObjQueryType equ <__imp_ObjQueryType>

externdef __imp_ObjRename:PPROC
ObjRename equ <__imp_ObjRename>

externdef __imp_OleActivate:PPROC
OleActivate equ <__imp_OleActivate>

externdef __imp_OleClone:PPROC
OleClone equ <__imp_OleClone>

externdef __imp_OleClose:PPROC
OleClose equ <__imp_OleClose>

externdef __imp_OleCopyFromLink:PPROC
OleCopyFromLink equ <__imp_OleCopyFromLink>

externdef __imp_OleCopyToClipboard:PPROC
OleCopyToClipboard equ <__imp_OleCopyToClipboard>

externdef __imp_OleCreate:PPROC
OleCreate equ <__imp_OleCreate>

externdef __imp_OleCreateFromClip:PPROC
OleCreateFromClip equ <__imp_OleCreateFromClip>

externdef __imp_OleCreateFromFile:PPROC
OleCreateFromFile equ <__imp_OleCreateFromFile>

externdef __imp_OleCreateFromTemplate:PPROC
OleCreateFromTemplate equ <__imp_OleCreateFromTemplate>

externdef __imp_OleCreateInvisible:PPROC
OleCreateInvisible equ <__imp_OleCreateInvisible>

externdef __imp_OleCreateLinkFromClip:PPROC
OleCreateLinkFromClip equ <__imp_OleCreateLinkFromClip>

externdef __imp_OleCreateLinkFromFile:PPROC
OleCreateLinkFromFile equ <__imp_OleCreateLinkFromFile>

externdef __imp_OleDelete:PPROC
OleDelete equ <__imp_OleDelete>

externdef __imp_OleDraw:PPROC
OleDraw equ <__imp_OleDraw>

externdef __imp_OleEnumFormats:PPROC
OleEnumFormats equ <__imp_OleEnumFormats>

externdef __imp_OleEnumObjects:PPROC
OleEnumObjects equ <__imp_OleEnumObjects>

externdef __imp_OleEqual:PPROC
OleEqual equ <__imp_OleEqual>

externdef __imp_OleExecute:PPROC
OleExecute equ <__imp_OleExecute>

externdef __imp_OleGetData:PPROC
OleGetData equ <__imp_OleGetData>

externdef __imp_OleGetLinkUpdateOptions:PPROC
OleGetLinkUpdateOptions equ <__imp_OleGetLinkUpdateOptions>

externdef __imp_OleIsDcMeta:PPROC
OleIsDcMeta equ <__imp_OleIsDcMeta>

externdef __imp_OleLoadFromStream:PPROC
OleLoadFromStream equ <__imp_OleLoadFromStream>

externdef __imp_OleLockServer:PPROC
OleLockServer equ <__imp_OleLockServer>

externdef __imp_OleObjectConvert:PPROC
OleObjectConvert equ <__imp_OleObjectConvert>

externdef __imp_OleQueryBounds:PPROC
OleQueryBounds equ <__imp_OleQueryBounds>

externdef __imp_OleQueryClientVersion:PPROC
OleQueryClientVersion equ <__imp_OleQueryClientVersion>

externdef __imp_OleQueryCreateFromClip:PPROC
OleQueryCreateFromClip equ <__imp_OleQueryCreateFromClip>

externdef __imp_OleQueryLinkFromClip:PPROC
OleQueryLinkFromClip equ <__imp_OleQueryLinkFromClip>

externdef __imp_OleQueryName:PPROC
OleQueryName equ <__imp_OleQueryName>

externdef __imp_OleQueryOpen:PPROC
OleQueryOpen equ <__imp_OleQueryOpen>

externdef __imp_OleQueryOutOfDate:PPROC
OleQueryOutOfDate equ <__imp_OleQueryOutOfDate>

externdef __imp_OleQueryProtocol:PPROC
OleQueryProtocol equ <__imp_OleQueryProtocol>

externdef __imp_OleQueryReleaseError:PPROC
OleQueryReleaseError equ <__imp_OleQueryReleaseError>

externdef __imp_OleQueryReleaseMethod:PPROC
OleQueryReleaseMethod equ <__imp_OleQueryReleaseMethod>

externdef __imp_OleQueryReleaseStatus:PPROC
OleQueryReleaseStatus equ <__imp_OleQueryReleaseStatus>

externdef __imp_OleQuerySize:PPROC
OleQuerySize equ <__imp_OleQuerySize>

externdef __imp_OleQueryType:PPROC
OleQueryType equ <__imp_OleQueryType>

externdef __imp_OleReconnect:PPROC
OleReconnect equ <__imp_OleReconnect>

externdef __imp_OleRegisterClientDoc:PPROC
OleRegisterClientDoc equ <__imp_OleRegisterClientDoc>

externdef __imp_OleRelease:PPROC
OleRelease equ <__imp_OleRelease>

externdef __imp_OleRename:PPROC
OleRename equ <__imp_OleRename>

externdef __imp_OleRenameClientDoc:PPROC
OleRenameClientDoc equ <__imp_OleRenameClientDoc>

externdef __imp_OleRequestData:PPROC
OleRequestData equ <__imp_OleRequestData>

externdef __imp_OleRevertClientDoc:PPROC
OleRevertClientDoc equ <__imp_OleRevertClientDoc>

externdef __imp_OleRevokeClientDoc:PPROC
OleRevokeClientDoc equ <__imp_OleRevokeClientDoc>

externdef __imp_OleSaveToStream:PPROC
OleSaveToStream equ <__imp_OleSaveToStream>

externdef __imp_OleSavedClientDoc:PPROC
OleSavedClientDoc equ <__imp_OleSavedClientDoc>

externdef __imp_OleSetBounds:PPROC
OleSetBounds equ <__imp_OleSetBounds>

externdef __imp_OleSetColorScheme:PPROC
OleSetColorScheme equ <__imp_OleSetColorScheme>

externdef __imp_OleSetData:PPROC
OleSetData equ <__imp_OleSetData>

externdef __imp_OleSetHostNames:PPROC
OleSetHostNames equ <__imp_OleSetHostNames>

externdef __imp_OleSetLinkUpdateOptions:PPROC
OleSetLinkUpdateOptions equ <__imp_OleSetLinkUpdateOptions>

externdef __imp_OleSetTargetDevice:PPROC
OleSetTargetDevice equ <__imp_OleSetTargetDevice>

externdef __imp_OleUnlockServer:PPROC
OleUnlockServer equ <__imp_OleUnlockServer>

externdef __imp_OleUpdate:PPROC
OleUpdate equ <__imp_OleUpdate>

externdef __imp_PbCopyToClipboard:PPROC
PbCopyToClipboard equ <__imp_PbCopyToClipboard>

externdef __imp_PbCreate:PPROC
PbCreate equ <__imp_PbCreate>

externdef __imp_PbCreateFromClip:PPROC
PbCreateFromClip equ <__imp_PbCreateFromClip>

externdef __imp_PbCreateFromFile:PPROC
PbCreateFromFile equ <__imp_PbCreateFromFile>

externdef __imp_PbCreateFromTemplate:PPROC
PbCreateFromTemplate equ <__imp_PbCreateFromTemplate>

externdef __imp_PbCreateInvisible:PPROC
PbCreateInvisible equ <__imp_PbCreateInvisible>

externdef __imp_PbCreateLinkFromClip:PPROC
PbCreateLinkFromClip equ <__imp_PbCreateLinkFromClip>

externdef __imp_PbCreateLinkFromFile:PPROC
PbCreateLinkFromFile equ <__imp_PbCreateLinkFromFile>

externdef __imp_PbDraw:PPROC
PbDraw equ <__imp_PbDraw>

externdef __imp_PbEnumFormats:PPROC
PbEnumFormats equ <__imp_PbEnumFormats>

externdef __imp_PbGetData:PPROC
PbGetData equ <__imp_PbGetData>

externdef __imp_PbLoadFromStream:PPROC
PbLoadFromStream equ <__imp_PbLoadFromStream>

externdef __imp_PbQueryBounds:PPROC
PbQueryBounds equ <__imp_PbQueryBounds>

externdef __imp_SetNetName:PPROC
SetNetName equ <__imp_SetNetName>

externdef __imp_SetNextNetDrive:PPROC
SetNextNetDrive equ <__imp_SetNextNetDrive>

externdef __imp_SrvrWndProc:PPROC
SrvrWndProc equ <__imp_SrvrWndProc>

externdef __imp_WEP:PPROC
WEP equ <__imp_WEP>

externdef __imp_olecli32_ordinal103:PPROC
olecli32_ordinal103 equ <__imp_olecli32_ordinal103>

externdef __imp_olecli32_ordinal104:PPROC
olecli32_ordinal104 equ <__imp_olecli32_ordinal104>

externdef __imp_olecli32_ordinal105:PPROC
olecli32_ordinal105 equ <__imp_olecli32_ordinal105>

externdef __imp_olecli32_ordinal106:PPROC
olecli32_ordinal106 equ <__imp_olecli32_ordinal106>

externdef __imp_olecli32_ordinal107:PPROC
olecli32_ordinal107 equ <__imp_olecli32_ordinal107>

externdef __imp_olecli32_ordinal108:PPROC
olecli32_ordinal108 equ <__imp_olecli32_ordinal108>

externdef __imp_olecli32_ordinal109:PPROC
olecli32_ordinal109 equ <__imp_olecli32_ordinal109>

externdef __imp_olecli32_ordinal118:PPROC
olecli32_ordinal118 equ <__imp_olecli32_ordinal118>

externdef __imp_olecli32_ordinal119:PPROC
olecli32_ordinal119 equ <__imp_olecli32_ordinal119>

externdef __imp_olecli32_ordinal120:PPROC
olecli32_ordinal120 equ <__imp_olecli32_ordinal120>

externdef __imp_olecli32_ordinal121:PPROC
olecli32_ordinal121 equ <__imp_olecli32_ordinal121>

externdef __imp_olecli32_ordinal122:PPROC
olecli32_ordinal122 equ <__imp_olecli32_ordinal122>

externdef __imp_olecli32_ordinal123:PPROC
olecli32_ordinal123 equ <__imp_olecli32_ordinal123>

externdef __imp_olecli32_ordinal124:PPROC
olecli32_ordinal124 equ <__imp_olecli32_ordinal124>

externdef __imp_olecli32_ordinal125:PPROC
olecli32_ordinal125 equ <__imp_olecli32_ordinal125>

externdef __imp_olecli32_ordinal126:PPROC
olecli32_ordinal126 equ <__imp_olecli32_ordinal126>

externdef __imp_olecli32_ordinal127:PPROC
olecli32_ordinal127 equ <__imp_olecli32_ordinal127>

externdef __imp_olecli32_ordinal128:PPROC
olecli32_ordinal128 equ <__imp_olecli32_ordinal128>

externdef __imp_olecli32_ordinal129:PPROC
olecli32_ordinal129 equ <__imp_olecli32_ordinal129>

externdef __imp_olecli32_ordinal130:PPROC
olecli32_ordinal130 equ <__imp_olecli32_ordinal130>

externdef __imp_olecli32_ordinal131:PPROC
olecli32_ordinal131 equ <__imp_olecli32_ordinal131>

externdef __imp_olecli32_ordinal132:PPROC
olecli32_ordinal132 equ <__imp_olecli32_ordinal132>

externdef __imp_olecli32_ordinal133:PPROC
olecli32_ordinal133 equ <__imp_olecli32_ordinal133>

externdef __imp_olecli32_ordinal134:PPROC
olecli32_ordinal134 equ <__imp_olecli32_ordinal134>

externdef __imp_olecli32_ordinal135:PPROC
olecli32_ordinal135 equ <__imp_olecli32_ordinal135>

externdef __imp_olecli32_ordinal136:PPROC
olecli32_ordinal136 equ <__imp_olecli32_ordinal136>

externdef __imp_olecli32_ordinal137:PPROC
olecli32_ordinal137 equ <__imp_olecli32_ordinal137>

externdef __imp_olecli32_ordinal138:PPROC
olecli32_ordinal138 equ <__imp_olecli32_ordinal138>

externdef __imp_olecli32_ordinal139:PPROC
olecli32_ordinal139 equ <__imp_olecli32_ordinal139>

externdef __imp_olecli32_ordinal140:PPROC
olecli32_ordinal140 equ <__imp_olecli32_ordinal140>

externdef __imp_olecli32_ordinal141:PPROC
olecli32_ordinal141 equ <__imp_olecli32_ordinal141>

externdef __imp_olecli32_ordinal142:PPROC
olecli32_ordinal142 equ <__imp_olecli32_ordinal142>

externdef __imp_olecli32_ordinal143:PPROC
olecli32_ordinal143 equ <__imp_olecli32_ordinal143>

externdef __imp_olecli32_ordinal144:PPROC
olecli32_ordinal144 equ <__imp_olecli32_ordinal144>

externdef __imp_olecli32_ordinal145:PPROC
olecli32_ordinal145 equ <__imp_olecli32_ordinal145>

externdef __imp_olecli32_ordinal146:PPROC
olecli32_ordinal146 equ <__imp_olecli32_ordinal146>

externdef __imp_olecli32_ordinal147:PPROC
olecli32_ordinal147 equ <__imp_olecli32_ordinal147>

externdef __imp_olecli32_ordinal148:PPROC
olecli32_ordinal148 equ <__imp_olecli32_ordinal148>

externdef __imp_olecli32_ordinal149:PPROC
olecli32_ordinal149 equ <__imp_olecli32_ordinal149>

externdef __imp_olecli32_ordinal150:PPROC
olecli32_ordinal150 equ <__imp_olecli32_ordinal150>

externdef __imp_olecli32_ordinal151:PPROC
olecli32_ordinal151 equ <__imp_olecli32_ordinal151>

externdef __imp_olecli32_ordinal152:PPROC
olecli32_ordinal152 equ <__imp_olecli32_ordinal152>

externdef __imp_olecli32_ordinal153:PPROC
olecli32_ordinal153 equ <__imp_olecli32_ordinal153>

externdef __imp_olecli32_ordinal154:PPROC
olecli32_ordinal154 equ <__imp_olecli32_ordinal154>

externdef __imp_olecli32_ordinal155:PPROC
olecli32_ordinal155 equ <__imp_olecli32_ordinal155>

externdef __imp_olecli32_ordinal156:PPROC
olecli32_ordinal156 equ <__imp_olecli32_ordinal156>

externdef __imp_olecli32_ordinal157:PPROC
olecli32_ordinal157 equ <__imp_olecli32_ordinal157>

externdef __imp_olecli32_ordinal158:PPROC
olecli32_ordinal158 equ <__imp_olecli32_ordinal158>

externdef __imp_olecli32_ordinal159:PPROC
olecli32_ordinal159 equ <__imp_olecli32_ordinal159>

externdef __imp_olecli32_ordinal160:PPROC
olecli32_ordinal160 equ <__imp_olecli32_ordinal160>

externdef __imp_olecli32_ordinal161:PPROC
olecli32_ordinal161 equ <__imp_olecli32_ordinal161>

externdef __imp_olecli32_ordinal162:PPROC
olecli32_ordinal162 equ <__imp_olecli32_ordinal162>

externdef __imp_olecli32_ordinal163:PPROC
olecli32_ordinal163 equ <__imp_olecli32_ordinal163>

externdef __imp_olecli32_ordinal164:PPROC
olecli32_ordinal164 equ <__imp_olecli32_ordinal164>

externdef __imp_olecli32_ordinal165:PPROC
olecli32_ordinal165 equ <__imp_olecli32_ordinal165>

externdef __imp_olecli32_ordinal166:PPROC
olecli32_ordinal166 equ <__imp_olecli32_ordinal166>

externdef __imp_olecli32_ordinal167:PPROC
olecli32_ordinal167 equ <__imp_olecli32_ordinal167>

externdef __imp_olecli32_ordinal168:PPROC
olecli32_ordinal168 equ <__imp_olecli32_ordinal168>

externdef __imp_olecli32_ordinal169:PPROC
olecli32_ordinal169 equ <__imp_olecli32_ordinal169>

externdef __imp_olecli32_ordinal170:PPROC
olecli32_ordinal170 equ <__imp_olecli32_ordinal170>

externdef __imp_olecli32_ordinal171:PPROC
olecli32_ordinal171 equ <__imp_olecli32_ordinal171>

externdef __imp_olecli32_ordinal172:PPROC
olecli32_ordinal172 equ <__imp_olecli32_ordinal172>

externdef __imp_olecli32_ordinal173:PPROC
olecli32_ordinal173 equ <__imp_olecli32_ordinal173>

externdef __imp_olecli32_ordinal174:PPROC
olecli32_ordinal174 equ <__imp_olecli32_ordinal174>

externdef __imp_olecli32_ordinal175:PPROC
olecli32_ordinal175 equ <__imp_olecli32_ordinal175>

externdef __imp_olecli32_ordinal176:PPROC
olecli32_ordinal176 equ <__imp_olecli32_ordinal176>

externdef __imp_olecli32_ordinal177:PPROC
olecli32_ordinal177 equ <__imp_olecli32_ordinal177>

externdef __imp_olecli32_ordinal178:PPROC
olecli32_ordinal178 equ <__imp_olecli32_ordinal178>

externdef __imp_olecli32_ordinal179:PPROC
olecli32_ordinal179 equ <__imp_olecli32_ordinal179>

externdef __imp_olecli32_ordinal180:PPROC
olecli32_ordinal180 equ <__imp_olecli32_ordinal180>

externdef __imp_olecli32_ordinal181:PPROC
olecli32_ordinal181 equ <__imp_olecli32_ordinal181>

externdef __imp_olecli32_ordinal182:PPROC
olecli32_ordinal182 equ <__imp_olecli32_ordinal182>

externdef __imp_olecli32_ordinal183:PPROC
olecli32_ordinal183 equ <__imp_olecli32_ordinal183>

externdef __imp_olecli32_ordinal184:PPROC
olecli32_ordinal184 equ <__imp_olecli32_ordinal184>

externdef __imp_olecli32_ordinal185:PPROC
olecli32_ordinal185 equ <__imp_olecli32_ordinal185>

externdef __imp_olecli32_ordinal186:PPROC
olecli32_ordinal186 equ <__imp_olecli32_ordinal186>

externdef __imp_olecli32_ordinal187:PPROC
olecli32_ordinal187 equ <__imp_olecli32_ordinal187>

externdef __imp_olecli32_ordinal188:PPROC
olecli32_ordinal188 equ <__imp_olecli32_ordinal188>

externdef __imp_olecli32_ordinal189:PPROC
olecli32_ordinal189 equ <__imp_olecli32_ordinal189>

externdef __imp_olecli32_ordinal190:PPROC
olecli32_ordinal190 equ <__imp_olecli32_ordinal190>

externdef __imp_olecli32_ordinal191:PPROC
olecli32_ordinal191 equ <__imp_olecli32_ordinal191>

externdef __imp_olecli32_ordinal192:PPROC
olecli32_ordinal192 equ <__imp_olecli32_ordinal192>

externdef __imp_olecli32_ordinal193:PPROC
olecli32_ordinal193 equ <__imp_olecli32_ordinal193>

externdef __imp_olecli32_ordinal194:PPROC
olecli32_ordinal194 equ <__imp_olecli32_ordinal194>

externdef __imp_olecli32_ordinal195:PPROC
olecli32_ordinal195 equ <__imp_olecli32_ordinal195>

externdef __imp_olecli32_ordinal196:PPROC
olecli32_ordinal196 equ <__imp_olecli32_ordinal196>

externdef __imp_olecli32_ordinal197:PPROC
olecli32_ordinal197 equ <__imp_olecli32_ordinal197>

externdef __imp_olecli32_ordinal198:PPROC
olecli32_ordinal198 equ <__imp_olecli32_ordinal198>

externdef __imp_olecli32_ordinal199:PPROC
olecli32_ordinal199 equ <__imp_olecli32_ordinal199>

externdef __imp_olecli32_ordinal217:PPROC
olecli32_ordinal217 equ <__imp_olecli32_ordinal217>

externdef __imp_olecli32_ordinal231:PPROC
olecli32_ordinal231 equ <__imp_olecli32_ordinal231>

externdef __imp_olecli32_ordinal232:PPROC
olecli32_ordinal232 equ <__imp_olecli32_ordinal232>

externdef __imp_olecli32_ordinal233:PPROC
olecli32_ordinal233 equ <__imp_olecli32_ordinal233>

externdef __imp_olecli32_ordinal234:PPROC
olecli32_ordinal234 equ <__imp_olecli32_ordinal234>

externdef __imp_olecli32_ordinal235:PPROC
olecli32_ordinal235 equ <__imp_olecli32_ordinal235>

externdef __imp_olecli32_ordinal236:PPROC
olecli32_ordinal236 equ <__imp_olecli32_ordinal236>

externdef __imp_olecli32_ordinal237:PPROC
olecli32_ordinal237 equ <__imp_olecli32_ordinal237>

externdef __imp_olecli32_ordinal238:PPROC
olecli32_ordinal238 equ <__imp_olecli32_ordinal238>

externdef __imp_olecli32_ordinal239:PPROC
olecli32_ordinal239 equ <__imp_olecli32_ordinal239>

externdef __imp_olecli32_ordinal240:PPROC
olecli32_ordinal240 equ <__imp_olecli32_ordinal240>

externdef __imp_olecli32_ordinal241:PPROC
olecli32_ordinal241 equ <__imp_olecli32_ordinal241>

externdef __imp_olecli32_ordinal242:PPROC
olecli32_ordinal242 equ <__imp_olecli32_ordinal242>

externdef __imp_olecli32_ordinal243:PPROC
olecli32_ordinal243 equ <__imp_olecli32_ordinal243>

externdef __imp_olecli32_ordinal244:PPROC
olecli32_ordinal244 equ <__imp_olecli32_ordinal244>

externdef __imp_olecli32_ordinal245:PPROC
olecli32_ordinal245 equ <__imp_olecli32_ordinal245>

externdef __imp_olecli32_ordinal246:PPROC
olecli32_ordinal246 equ <__imp_olecli32_ordinal246>

externdef __imp_olecli32_ordinal247:PPROC
olecli32_ordinal247 equ <__imp_olecli32_ordinal247>

externdef __imp_olecli32_ordinal248:PPROC
olecli32_ordinal248 equ <__imp_olecli32_ordinal248>

externdef __imp_olecli32_ordinal249:PPROC
olecli32_ordinal249 equ <__imp_olecli32_ordinal249>

externdef __imp_olecli32_ordinal250:PPROC
olecli32_ordinal250 equ <__imp_olecli32_ordinal250>

externdef __imp_olecli32_ordinal251:PPROC
olecli32_ordinal251 equ <__imp_olecli32_ordinal251>

externdef __imp_olecli32_ordinal252:PPROC
olecli32_ordinal252 equ <__imp_olecli32_ordinal252>

externdef __imp_olecli32_ordinal253:PPROC
olecli32_ordinal253 equ <__imp_olecli32_ordinal253>

externdef __imp_olecli32_ordinal254:PPROC
olecli32_ordinal254 equ <__imp_olecli32_ordinal254>

externdef __imp_olecli32_ordinal255:PPROC
olecli32_ordinal255 equ <__imp_olecli32_ordinal255>

externdef __imp_olecli32_ordinal256:PPROC
olecli32_ordinal256 equ <__imp_olecli32_ordinal256>

externdef __imp_olecli32_ordinal257:PPROC
olecli32_ordinal257 equ <__imp_olecli32_ordinal257>

externdef __imp_olecli32_ordinal258:PPROC
olecli32_ordinal258 equ <__imp_olecli32_ordinal258>

externdef __imp_olecli32_ordinal259:PPROC
olecli32_ordinal259 equ <__imp_olecli32_ordinal259>

externdef __imp_olecli32_ordinal260:PPROC
olecli32_ordinal260 equ <__imp_olecli32_ordinal260>

externdef __imp_olecli32_ordinal261:PPROC
olecli32_ordinal261 equ <__imp_olecli32_ordinal261>

externdef __imp_olecli32_ordinal262:PPROC
olecli32_ordinal262 equ <__imp_olecli32_ordinal262>

externdef __imp_olecli32_ordinal263:PPROC
olecli32_ordinal263 equ <__imp_olecli32_ordinal263>

externdef __imp_olecli32_ordinal264:PPROC
olecli32_ordinal264 equ <__imp_olecli32_ordinal264>

externdef __imp_olecli32_ordinal265:PPROC
olecli32_ordinal265 equ <__imp_olecli32_ordinal265>

externdef __imp_olecli32_ordinal266:PPROC
olecli32_ordinal266 equ <__imp_olecli32_ordinal266>

externdef __imp_olecli32_ordinal267:PPROC
olecli32_ordinal267 equ <__imp_olecli32_ordinal267>

externdef __imp_olecli32_ordinal268:PPROC
olecli32_ordinal268 equ <__imp_olecli32_ordinal268>

externdef __imp_olecli32_ordinal269:PPROC
olecli32_ordinal269 equ <__imp_olecli32_ordinal269>

externdef __imp_olecli32_ordinal270:PPROC
olecli32_ordinal270 equ <__imp_olecli32_ordinal270>

externdef __imp_olecli32_ordinal271:PPROC
olecli32_ordinal271 equ <__imp_olecli32_ordinal271>

externdef __imp_olecli32_ordinal272:PPROC
olecli32_ordinal272 equ <__imp_olecli32_ordinal272>

externdef __imp_olecli32_ordinal273:PPROC
olecli32_ordinal273 equ <__imp_olecli32_ordinal273>

externdef __imp_olecli32_ordinal274:PPROC
olecli32_ordinal274 equ <__imp_olecli32_ordinal274>

externdef __imp_olecli32_ordinal275:PPROC
olecli32_ordinal275 equ <__imp_olecli32_ordinal275>

externdef __imp_olecli32_ordinal276:PPROC
olecli32_ordinal276 equ <__imp_olecli32_ordinal276>

externdef __imp_olecli32_ordinal277:PPROC
olecli32_ordinal277 equ <__imp_olecli32_ordinal277>

externdef __imp_olecli32_ordinal278:PPROC
olecli32_ordinal278 equ <__imp_olecli32_ordinal278>

externdef __imp_olecli32_ordinal279:PPROC
olecli32_ordinal279 equ <__imp_olecli32_ordinal279>

externdef __imp_olecli32_ordinal280:PPROC
olecli32_ordinal280 equ <__imp_olecli32_ordinal280>

externdef __imp_olecli32_ordinal281:PPROC
olecli32_ordinal281 equ <__imp_olecli32_ordinal281>

externdef __imp_olecli32_ordinal282:PPROC
olecli32_ordinal282 equ <__imp_olecli32_ordinal282>

externdef __imp_olecli32_ordinal283:PPROC
olecli32_ordinal283 equ <__imp_olecli32_ordinal283>

externdef __imp_olecli32_ordinal284:PPROC
olecli32_ordinal284 equ <__imp_olecli32_ordinal284>

externdef __imp_olecli32_ordinal285:PPROC
olecli32_ordinal285 equ <__imp_olecli32_ordinal285>

externdef __imp_olecli32_ordinal286:PPROC
olecli32_ordinal286 equ <__imp_olecli32_ordinal286>

externdef __imp_olecli32_ordinal287:PPROC
olecli32_ordinal287 equ <__imp_olecli32_ordinal287>

externdef __imp_olecli32_ordinal288:PPROC
olecli32_ordinal288 equ <__imp_olecli32_ordinal288>

externdef __imp_olecli32_ordinal289:PPROC
olecli32_ordinal289 equ <__imp_olecli32_ordinal289>

externdef __imp_olecli32_ordinal290:PPROC
olecli32_ordinal290 equ <__imp_olecli32_ordinal290>

externdef __imp_olecli32_ordinal291:PPROC
olecli32_ordinal291 equ <__imp_olecli32_ordinal291>

externdef __imp_olecli32_ordinal292:PPROC
olecli32_ordinal292 equ <__imp_olecli32_ordinal292>

externdef __imp_olecli32_ordinal293:PPROC
olecli32_ordinal293 equ <__imp_olecli32_ordinal293>

externdef __imp_olecli32_ordinal294:PPROC
olecli32_ordinal294 equ <__imp_olecli32_ordinal294>

externdef __imp_olecli32_ordinal295:PPROC
olecli32_ordinal295 equ <__imp_olecli32_ordinal295>

externdef __imp_olecli32_ordinal296:PPROC
olecli32_ordinal296 equ <__imp_olecli32_ordinal296>

externdef __imp_olecli32_ordinal297:PPROC
olecli32_ordinal297 equ <__imp_olecli32_ordinal297>

externdef __imp_olecli32_ordinal298:PPROC
olecli32_ordinal298 equ <__imp_olecli32_ordinal298>

externdef __imp_olecli32_ordinal299:PPROC
olecli32_ordinal299 equ <__imp_olecli32_ordinal299>

externdef __imp_olecli32_ordinal306:PPROC
olecli32_ordinal306 equ <__imp_olecli32_ordinal306>

externdef __imp_olecli32_ordinal311:PPROC
olecli32_ordinal311 equ <__imp_olecli32_ordinal311>

externdef __imp_olecli32_ordinal312:PPROC
olecli32_ordinal312 equ <__imp_olecli32_ordinal312>

externdef __imp_olecli32_ordinal313:PPROC
olecli32_ordinal313 equ <__imp_olecli32_ordinal313>

externdef __imp_olecli32_ordinal314:PPROC
olecli32_ordinal314 equ <__imp_olecli32_ordinal314>

externdef __imp_olecli32_ordinal315:PPROC
olecli32_ordinal315 equ <__imp_olecli32_ordinal315>

externdef __imp_olecli32_ordinal316:PPROC
olecli32_ordinal316 equ <__imp_olecli32_ordinal316>

externdef __imp_olecli32_ordinal317:PPROC
olecli32_ordinal317 equ <__imp_olecli32_ordinal317>

externdef __imp_olecli32_ordinal318:PPROC
olecli32_ordinal318 equ <__imp_olecli32_ordinal318>

externdef __imp_olecli32_ordinal319:PPROC
olecli32_ordinal319 equ <__imp_olecli32_ordinal319>

externdef __imp_olecli32_ordinal320:PPROC
olecli32_ordinal320 equ <__imp_olecli32_ordinal320>

externdef __imp_olecli32_ordinal321:PPROC
olecli32_ordinal321 equ <__imp_olecli32_ordinal321>

externdef __imp_olecli32_ordinal322:PPROC
olecli32_ordinal322 equ <__imp_olecli32_ordinal322>

externdef __imp_olecli32_ordinal323:PPROC
olecli32_ordinal323 equ <__imp_olecli32_ordinal323>

externdef __imp_olecli32_ordinal324:PPROC
olecli32_ordinal324 equ <__imp_olecli32_ordinal324>

externdef __imp_olecli32_ordinal325:PPROC
olecli32_ordinal325 equ <__imp_olecli32_ordinal325>

externdef __imp_olecli32_ordinal326:PPROC
olecli32_ordinal326 equ <__imp_olecli32_ordinal326>

externdef __imp_olecli32_ordinal327:PPROC
olecli32_ordinal327 equ <__imp_olecli32_ordinal327>

externdef __imp_olecli32_ordinal328:PPROC
olecli32_ordinal328 equ <__imp_olecli32_ordinal328>

externdef __imp_olecli32_ordinal329:PPROC
olecli32_ordinal329 equ <__imp_olecli32_ordinal329>

externdef __imp_olecli32_ordinal330:PPROC
olecli32_ordinal330 equ <__imp_olecli32_ordinal330>

externdef __imp_olecli32_ordinal331:PPROC
olecli32_ordinal331 equ <__imp_olecli32_ordinal331>

externdef __imp_olecli32_ordinal332:PPROC
olecli32_ordinal332 equ <__imp_olecli32_ordinal332>

externdef __imp_olecli32_ordinal333:PPROC
olecli32_ordinal333 equ <__imp_olecli32_ordinal333>

externdef __imp_olecli32_ordinal334:PPROC
olecli32_ordinal334 equ <__imp_olecli32_ordinal334>

externdef __imp_olecli32_ordinal335:PPROC
olecli32_ordinal335 equ <__imp_olecli32_ordinal335>

externdef __imp_olecli32_ordinal336:PPROC
olecli32_ordinal336 equ <__imp_olecli32_ordinal336>

externdef __imp_olecli32_ordinal337:PPROC
olecli32_ordinal337 equ <__imp_olecli32_ordinal337>

externdef __imp_olecli32_ordinal338:PPROC
olecli32_ordinal338 equ <__imp_olecli32_ordinal338>

externdef __imp_olecli32_ordinal339:PPROC
olecli32_ordinal339 equ <__imp_olecli32_ordinal339>

externdef __imp_olecli32_ordinal340:PPROC
olecli32_ordinal340 equ <__imp_olecli32_ordinal340>

externdef __imp_olecli32_ordinal341:PPROC
olecli32_ordinal341 equ <__imp_olecli32_ordinal341>

externdef __imp_olecli32_ordinal342:PPROC
olecli32_ordinal342 equ <__imp_olecli32_ordinal342>

externdef __imp_olecli32_ordinal343:PPROC
olecli32_ordinal343 equ <__imp_olecli32_ordinal343>

externdef __imp_olecli32_ordinal344:PPROC
olecli32_ordinal344 equ <__imp_olecli32_ordinal344>

externdef __imp_olecli32_ordinal345:PPROC
olecli32_ordinal345 equ <__imp_olecli32_ordinal345>

externdef __imp_olecli32_ordinal346:PPROC
olecli32_ordinal346 equ <__imp_olecli32_ordinal346>

externdef __imp_olecli32_ordinal347:PPROC
olecli32_ordinal347 equ <__imp_olecli32_ordinal347>

externdef __imp_olecli32_ordinal348:PPROC
olecli32_ordinal348 equ <__imp_olecli32_ordinal348>

externdef __imp_olecli32_ordinal349:PPROC
olecli32_ordinal349 equ <__imp_olecli32_ordinal349>

externdef __imp_olecli32_ordinal350:PPROC
olecli32_ordinal350 equ <__imp_olecli32_ordinal350>

externdef __imp_olecli32_ordinal351:PPROC
olecli32_ordinal351 equ <__imp_olecli32_ordinal351>

externdef __imp_olecli32_ordinal352:PPROC
olecli32_ordinal352 equ <__imp_olecli32_ordinal352>

externdef __imp_olecli32_ordinal353:PPROC
olecli32_ordinal353 equ <__imp_olecli32_ordinal353>

externdef __imp_olecli32_ordinal354:PPROC
olecli32_ordinal354 equ <__imp_olecli32_ordinal354>

externdef __imp_olecli32_ordinal355:PPROC
olecli32_ordinal355 equ <__imp_olecli32_ordinal355>

externdef __imp_olecli32_ordinal356:PPROC
olecli32_ordinal356 equ <__imp_olecli32_ordinal356>

externdef __imp_olecli32_ordinal357:PPROC
olecli32_ordinal357 equ <__imp_olecli32_ordinal357>

externdef __imp_olecli32_ordinal358:PPROC
olecli32_ordinal358 equ <__imp_olecli32_ordinal358>

externdef __imp_olecli32_ordinal359:PPROC
olecli32_ordinal359 equ <__imp_olecli32_ordinal359>

externdef __imp_olecli32_ordinal360:PPROC
olecli32_ordinal360 equ <__imp_olecli32_ordinal360>

externdef __imp_olecli32_ordinal361:PPROC
olecli32_ordinal361 equ <__imp_olecli32_ordinal361>

externdef __imp_olecli32_ordinal362:PPROC
olecli32_ordinal362 equ <__imp_olecli32_ordinal362>

externdef __imp_olecli32_ordinal363:PPROC
olecli32_ordinal363 equ <__imp_olecli32_ordinal363>

externdef __imp_olecli32_ordinal364:PPROC
olecli32_ordinal364 equ <__imp_olecli32_ordinal364>

externdef __imp_olecli32_ordinal365:PPROC
olecli32_ordinal365 equ <__imp_olecli32_ordinal365>

externdef __imp_olecli32_ordinal366:PPROC
olecli32_ordinal366 equ <__imp_olecli32_ordinal366>

externdef __imp_olecli32_ordinal367:PPROC
olecli32_ordinal367 equ <__imp_olecli32_ordinal367>

externdef __imp_olecli32_ordinal368:PPROC
olecli32_ordinal368 equ <__imp_olecli32_ordinal368>

externdef __imp_olecli32_ordinal369:PPROC
olecli32_ordinal369 equ <__imp_olecli32_ordinal369>

externdef __imp_olecli32_ordinal370:PPROC
olecli32_ordinal370 equ <__imp_olecli32_ordinal370>

externdef __imp_olecli32_ordinal371:PPROC
olecli32_ordinal371 equ <__imp_olecli32_ordinal371>

externdef __imp_olecli32_ordinal372:PPROC
olecli32_ordinal372 equ <__imp_olecli32_ordinal372>

externdef __imp_olecli32_ordinal373:PPROC
olecli32_ordinal373 equ <__imp_olecli32_ordinal373>

externdef __imp_olecli32_ordinal374:PPROC
olecli32_ordinal374 equ <__imp_olecli32_ordinal374>

externdef __imp_olecli32_ordinal375:PPROC
olecli32_ordinal375 equ <__imp_olecli32_ordinal375>

externdef __imp_olecli32_ordinal376:PPROC
olecli32_ordinal376 equ <__imp_olecli32_ordinal376>

externdef __imp_olecli32_ordinal377:PPROC
olecli32_ordinal377 equ <__imp_olecli32_ordinal377>

externdef __imp_olecli32_ordinal378:PPROC
olecli32_ordinal378 equ <__imp_olecli32_ordinal378>

externdef __imp_olecli32_ordinal379:PPROC
olecli32_ordinal379 equ <__imp_olecli32_ordinal379>

externdef __imp_olecli32_ordinal380:PPROC
olecli32_ordinal380 equ <__imp_olecli32_ordinal380>

externdef __imp_olecli32_ordinal381:PPROC
olecli32_ordinal381 equ <__imp_olecli32_ordinal381>

externdef __imp_olecli32_ordinal382:PPROC
olecli32_ordinal382 equ <__imp_olecli32_ordinal382>

externdef __imp_olecli32_ordinal383:PPROC
olecli32_ordinal383 equ <__imp_olecli32_ordinal383>

externdef __imp_olecli32_ordinal384:PPROC
olecli32_ordinal384 equ <__imp_olecli32_ordinal384>

externdef __imp_olecli32_ordinal385:PPROC
olecli32_ordinal385 equ <__imp_olecli32_ordinal385>

externdef __imp_olecli32_ordinal386:PPROC
olecli32_ordinal386 equ <__imp_olecli32_ordinal386>

externdef __imp_olecli32_ordinal387:PPROC
olecli32_ordinal387 equ <__imp_olecli32_ordinal387>

externdef __imp_olecli32_ordinal388:PPROC
olecli32_ordinal388 equ <__imp_olecli32_ordinal388>

externdef __imp_olecli32_ordinal389:PPROC
olecli32_ordinal389 equ <__imp_olecli32_ordinal389>

externdef __imp_olecli32_ordinal390:PPROC
olecli32_ordinal390 equ <__imp_olecli32_ordinal390>

externdef __imp_olecli32_ordinal391:PPROC
olecli32_ordinal391 equ <__imp_olecli32_ordinal391>

externdef __imp_olecli32_ordinal392:PPROC
olecli32_ordinal392 equ <__imp_olecli32_ordinal392>

externdef __imp_olecli32_ordinal393:PPROC
olecli32_ordinal393 equ <__imp_olecli32_ordinal393>

externdef __imp_olecli32_ordinal394:PPROC
olecli32_ordinal394 equ <__imp_olecli32_ordinal394>

externdef __imp_olecli32_ordinal395:PPROC
olecli32_ordinal395 equ <__imp_olecli32_ordinal395>

externdef __imp_olecli32_ordinal396:PPROC
olecli32_ordinal396 equ <__imp_olecli32_ordinal396>

externdef __imp_olecli32_ordinal397:PPROC
olecli32_ordinal397 equ <__imp_olecli32_ordinal397>

externdef __imp_olecli32_ordinal398:PPROC
olecli32_ordinal398 equ <__imp_olecli32_ordinal398>

externdef __imp_olecli32_ordinal399:PPROC
olecli32_ordinal399 equ <__imp_olecli32_ordinal399>

externdef __imp_olecli32_ordinal406:PPROC
olecli32_ordinal406 equ <__imp_olecli32_ordinal406>

externdef __imp_olecli32_ordinal411:PPROC
olecli32_ordinal411 equ <__imp_olecli32_ordinal411>

externdef __imp_olecli32_ordinal412:PPROC
olecli32_ordinal412 equ <__imp_olecli32_ordinal412>

externdef __imp_olecli32_ordinal413:PPROC
olecli32_ordinal413 equ <__imp_olecli32_ordinal413>

externdef __imp_olecli32_ordinal414:PPROC
olecli32_ordinal414 equ <__imp_olecli32_ordinal414>

externdef __imp_olecli32_ordinal415:PPROC
olecli32_ordinal415 equ <__imp_olecli32_ordinal415>

externdef __imp_olecli32_ordinal416:PPROC
olecli32_ordinal416 equ <__imp_olecli32_ordinal416>

externdef __imp_olecli32_ordinal417:PPROC
olecli32_ordinal417 equ <__imp_olecli32_ordinal417>

externdef __imp_olecli32_ordinal418:PPROC
olecli32_ordinal418 equ <__imp_olecli32_ordinal418>

externdef __imp_olecli32_ordinal419:PPROC
olecli32_ordinal419 equ <__imp_olecli32_ordinal419>

externdef __imp_olecli32_ordinal420:PPROC
olecli32_ordinal420 equ <__imp_olecli32_ordinal420>

externdef __imp_olecli32_ordinal421:PPROC
olecli32_ordinal421 equ <__imp_olecli32_ordinal421>

externdef __imp_olecli32_ordinal422:PPROC
olecli32_ordinal422 equ <__imp_olecli32_ordinal422>

externdef __imp_olecli32_ordinal423:PPROC
olecli32_ordinal423 equ <__imp_olecli32_ordinal423>

externdef __imp_olecli32_ordinal424:PPROC
olecli32_ordinal424 equ <__imp_olecli32_ordinal424>

externdef __imp_olecli32_ordinal425:PPROC
olecli32_ordinal425 equ <__imp_olecli32_ordinal425>

externdef __imp_olecli32_ordinal426:PPROC
olecli32_ordinal426 equ <__imp_olecli32_ordinal426>

externdef __imp_olecli32_ordinal427:PPROC
olecli32_ordinal427 equ <__imp_olecli32_ordinal427>

externdef __imp_olecli32_ordinal428:PPROC
olecli32_ordinal428 equ <__imp_olecli32_ordinal428>

externdef __imp_olecli32_ordinal429:PPROC
olecli32_ordinal429 equ <__imp_olecli32_ordinal429>

externdef __imp_olecli32_ordinal430:PPROC
olecli32_ordinal430 equ <__imp_olecli32_ordinal430>

externdef __imp_olecli32_ordinal431:PPROC
olecli32_ordinal431 equ <__imp_olecli32_ordinal431>

externdef __imp_olecli32_ordinal432:PPROC
olecli32_ordinal432 equ <__imp_olecli32_ordinal432>

externdef __imp_olecli32_ordinal433:PPROC
olecli32_ordinal433 equ <__imp_olecli32_ordinal433>

externdef __imp_olecli32_ordinal434:PPROC
olecli32_ordinal434 equ <__imp_olecli32_ordinal434>

externdef __imp_olecli32_ordinal435:PPROC
olecli32_ordinal435 equ <__imp_olecli32_ordinal435>

externdef __imp_olecli32_ordinal436:PPROC
olecli32_ordinal436 equ <__imp_olecli32_ordinal436>

externdef __imp_olecli32_ordinal437:PPROC
olecli32_ordinal437 equ <__imp_olecli32_ordinal437>

externdef __imp_olecli32_ordinal438:PPROC
olecli32_ordinal438 equ <__imp_olecli32_ordinal438>

externdef __imp_olecli32_ordinal439:PPROC
olecli32_ordinal439 equ <__imp_olecli32_ordinal439>

externdef __imp_olecli32_ordinal440:PPROC
olecli32_ordinal440 equ <__imp_olecli32_ordinal440>

externdef __imp_olecli32_ordinal441:PPROC
olecli32_ordinal441 equ <__imp_olecli32_ordinal441>

externdef __imp_olecli32_ordinal442:PPROC
olecli32_ordinal442 equ <__imp_olecli32_ordinal442>

externdef __imp_olecli32_ordinal443:PPROC
olecli32_ordinal443 equ <__imp_olecli32_ordinal443>

externdef __imp_olecli32_ordinal444:PPROC
olecli32_ordinal444 equ <__imp_olecli32_ordinal444>

externdef __imp_olecli32_ordinal445:PPROC
olecli32_ordinal445 equ <__imp_olecli32_ordinal445>

externdef __imp_olecli32_ordinal446:PPROC
olecli32_ordinal446 equ <__imp_olecli32_ordinal446>

externdef __imp_olecli32_ordinal447:PPROC
olecli32_ordinal447 equ <__imp_olecli32_ordinal447>

externdef __imp_olecli32_ordinal448:PPROC
olecli32_ordinal448 equ <__imp_olecli32_ordinal448>

externdef __imp_olecli32_ordinal449:PPROC
olecli32_ordinal449 equ <__imp_olecli32_ordinal449>

externdef __imp_olecli32_ordinal450:PPROC
olecli32_ordinal450 equ <__imp_olecli32_ordinal450>

externdef __imp_olecli32_ordinal451:PPROC
olecli32_ordinal451 equ <__imp_olecli32_ordinal451>

externdef __imp_olecli32_ordinal452:PPROC
olecli32_ordinal452 equ <__imp_olecli32_ordinal452>

externdef __imp_olecli32_ordinal453:PPROC
olecli32_ordinal453 equ <__imp_olecli32_ordinal453>

externdef __imp_olecli32_ordinal454:PPROC
olecli32_ordinal454 equ <__imp_olecli32_ordinal454>

externdef __imp_olecli32_ordinal455:PPROC
olecli32_ordinal455 equ <__imp_olecli32_ordinal455>

externdef __imp_olecli32_ordinal456:PPROC
olecli32_ordinal456 equ <__imp_olecli32_ordinal456>

externdef __imp_olecli32_ordinal457:PPROC
olecli32_ordinal457 equ <__imp_olecli32_ordinal457>

externdef __imp_olecli32_ordinal458:PPROC
olecli32_ordinal458 equ <__imp_olecli32_ordinal458>

externdef __imp_olecli32_ordinal459:PPROC
olecli32_ordinal459 equ <__imp_olecli32_ordinal459>

externdef __imp_olecli32_ordinal460:PPROC
olecli32_ordinal460 equ <__imp_olecli32_ordinal460>

externdef __imp_olecli32_ordinal461:PPROC
olecli32_ordinal461 equ <__imp_olecli32_ordinal461>

externdef __imp_olecli32_ordinal462:PPROC
olecli32_ordinal462 equ <__imp_olecli32_ordinal462>

externdef __imp_olecli32_ordinal463:PPROC
olecli32_ordinal463 equ <__imp_olecli32_ordinal463>

externdef __imp_olecli32_ordinal464:PPROC
olecli32_ordinal464 equ <__imp_olecli32_ordinal464>

externdef __imp_olecli32_ordinal465:PPROC
olecli32_ordinal465 equ <__imp_olecli32_ordinal465>

externdef __imp_olecli32_ordinal466:PPROC
olecli32_ordinal466 equ <__imp_olecli32_ordinal466>

externdef __imp_olecli32_ordinal467:PPROC
olecli32_ordinal467 equ <__imp_olecli32_ordinal467>

externdef __imp_olecli32_ordinal468:PPROC
olecli32_ordinal468 equ <__imp_olecli32_ordinal468>

externdef __imp_olecli32_ordinal469:PPROC
olecli32_ordinal469 equ <__imp_olecli32_ordinal469>

externdef __imp_olecli32_ordinal470:PPROC
olecli32_ordinal470 equ <__imp_olecli32_ordinal470>

externdef __imp_olecli32_ordinal471:PPROC
olecli32_ordinal471 equ <__imp_olecli32_ordinal471>

externdef __imp_olecli32_ordinal472:PPROC
olecli32_ordinal472 equ <__imp_olecli32_ordinal472>

externdef __imp_olecli32_ordinal473:PPROC
olecli32_ordinal473 equ <__imp_olecli32_ordinal473>

externdef __imp_olecli32_ordinal474:PPROC
olecli32_ordinal474 equ <__imp_olecli32_ordinal474>

externdef __imp_olecli32_ordinal475:PPROC
olecli32_ordinal475 equ <__imp_olecli32_ordinal475>

externdef __imp_olecli32_ordinal476:PPROC
olecli32_ordinal476 equ <__imp_olecli32_ordinal476>

externdef __imp_olecli32_ordinal477:PPROC
olecli32_ordinal477 equ <__imp_olecli32_ordinal477>

externdef __imp_olecli32_ordinal478:PPROC
olecli32_ordinal478 equ <__imp_olecli32_ordinal478>

externdef __imp_olecli32_ordinal479:PPROC
olecli32_ordinal479 equ <__imp_olecli32_ordinal479>

externdef __imp_olecli32_ordinal480:PPROC
olecli32_ordinal480 equ <__imp_olecli32_ordinal480>

externdef __imp_olecli32_ordinal481:PPROC
olecli32_ordinal481 equ <__imp_olecli32_ordinal481>

externdef __imp_olecli32_ordinal482:PPROC
olecli32_ordinal482 equ <__imp_olecli32_ordinal482>

externdef __imp_olecli32_ordinal483:PPROC
olecli32_ordinal483 equ <__imp_olecli32_ordinal483>

externdef __imp_olecli32_ordinal484:PPROC
olecli32_ordinal484 equ <__imp_olecli32_ordinal484>

externdef __imp_olecli32_ordinal485:PPROC
olecli32_ordinal485 equ <__imp_olecli32_ordinal485>

externdef __imp_olecli32_ordinal486:PPROC
olecli32_ordinal486 equ <__imp_olecli32_ordinal486>

externdef __imp_olecli32_ordinal487:PPROC
olecli32_ordinal487 equ <__imp_olecli32_ordinal487>

externdef __imp_olecli32_ordinal488:PPROC
olecli32_ordinal488 equ <__imp_olecli32_ordinal488>

externdef __imp_olecli32_ordinal489:PPROC
olecli32_ordinal489 equ <__imp_olecli32_ordinal489>

externdef __imp_olecli32_ordinal490:PPROC
olecli32_ordinal490 equ <__imp_olecli32_ordinal490>

externdef __imp_olecli32_ordinal491:PPROC
olecli32_ordinal491 equ <__imp_olecli32_ordinal491>

externdef __imp_olecli32_ordinal492:PPROC
olecli32_ordinal492 equ <__imp_olecli32_ordinal492>

externdef __imp_olecli32_ordinal493:PPROC
olecli32_ordinal493 equ <__imp_olecli32_ordinal493>

externdef __imp_olecli32_ordinal494:PPROC
olecli32_ordinal494 equ <__imp_olecli32_ordinal494>

externdef __imp_olecli32_ordinal495:PPROC
olecli32_ordinal495 equ <__imp_olecli32_ordinal495>

externdef __imp_olecli32_ordinal496:PPROC
olecli32_ordinal496 equ <__imp_olecli32_ordinal496>

externdef __imp_olecli32_ordinal497:PPROC
olecli32_ordinal497 equ <__imp_olecli32_ordinal497>

externdef __imp_olecli32_ordinal498:PPROC
olecli32_ordinal498 equ <__imp_olecli32_ordinal498>

externdef __imp_olecli32_ordinal499:PPROC
olecli32_ordinal499 equ <__imp_olecli32_ordinal499>

externdef __imp_olecli32_ordinal506:PPROC
olecli32_ordinal506 equ <__imp_olecli32_ordinal506>

externdef __imp_olecli32_ordinal511:PPROC
olecli32_ordinal511 equ <__imp_olecli32_ordinal511>

externdef __imp_olecli32_ordinal512:PPROC
olecli32_ordinal512 equ <__imp_olecli32_ordinal512>

externdef __imp_olecli32_ordinal513:PPROC
olecli32_ordinal513 equ <__imp_olecli32_ordinal513>

externdef __imp_olecli32_ordinal514:PPROC
olecli32_ordinal514 equ <__imp_olecli32_ordinal514>

externdef __imp_olecli32_ordinal515:PPROC
olecli32_ordinal515 equ <__imp_olecli32_ordinal515>

externdef __imp_olecli32_ordinal516:PPROC
olecli32_ordinal516 equ <__imp_olecli32_ordinal516>

externdef __imp_olecli32_ordinal517:PPROC
olecli32_ordinal517 equ <__imp_olecli32_ordinal517>

externdef __imp_olecli32_ordinal518:PPROC
olecli32_ordinal518 equ <__imp_olecli32_ordinal518>

externdef __imp_olecli32_ordinal519:PPROC
olecli32_ordinal519 equ <__imp_olecli32_ordinal519>

externdef __imp_olecli32_ordinal51:PPROC
olecli32_ordinal51 equ <__imp_olecli32_ordinal51>

externdef __imp_olecli32_ordinal520:PPROC
olecli32_ordinal520 equ <__imp_olecli32_ordinal520>

externdef __imp_olecli32_ordinal521:PPROC
olecli32_ordinal521 equ <__imp_olecli32_ordinal521>

externdef __imp_olecli32_ordinal522:PPROC
olecli32_ordinal522 equ <__imp_olecli32_ordinal522>

externdef __imp_olecli32_ordinal523:PPROC
olecli32_ordinal523 equ <__imp_olecli32_ordinal523>

externdef __imp_olecli32_ordinal524:PPROC
olecli32_ordinal524 equ <__imp_olecli32_ordinal524>

externdef __imp_olecli32_ordinal525:PPROC
olecli32_ordinal525 equ <__imp_olecli32_ordinal525>

externdef __imp_olecli32_ordinal526:PPROC
olecli32_ordinal526 equ <__imp_olecli32_ordinal526>

externdef __imp_olecli32_ordinal527:PPROC
olecli32_ordinal527 equ <__imp_olecli32_ordinal527>

externdef __imp_olecli32_ordinal528:PPROC
olecli32_ordinal528 equ <__imp_olecli32_ordinal528>

externdef __imp_olecli32_ordinal529:PPROC
olecli32_ordinal529 equ <__imp_olecli32_ordinal529>

externdef __imp_olecli32_ordinal52:PPROC
olecli32_ordinal52 equ <__imp_olecli32_ordinal52>

externdef __imp_olecli32_ordinal530:PPROC
olecli32_ordinal530 equ <__imp_olecli32_ordinal530>

externdef __imp_olecli32_ordinal531:PPROC
olecli32_ordinal531 equ <__imp_olecli32_ordinal531>

externdef __imp_olecli32_ordinal532:PPROC
olecli32_ordinal532 equ <__imp_olecli32_ordinal532>

externdef __imp_olecli32_ordinal533:PPROC
olecli32_ordinal533 equ <__imp_olecli32_ordinal533>

externdef __imp_olecli32_ordinal534:PPROC
olecli32_ordinal534 equ <__imp_olecli32_ordinal534>

externdef __imp_olecli32_ordinal535:PPROC
olecli32_ordinal535 equ <__imp_olecli32_ordinal535>

externdef __imp_olecli32_ordinal536:PPROC
olecli32_ordinal536 equ <__imp_olecli32_ordinal536>

externdef __imp_olecli32_ordinal537:PPROC
olecli32_ordinal537 equ <__imp_olecli32_ordinal537>

externdef __imp_olecli32_ordinal538:PPROC
olecli32_ordinal538 equ <__imp_olecli32_ordinal538>

externdef __imp_olecli32_ordinal539:PPROC
olecli32_ordinal539 equ <__imp_olecli32_ordinal539>

externdef __imp_olecli32_ordinal53:PPROC
olecli32_ordinal53 equ <__imp_olecli32_ordinal53>

externdef __imp_olecli32_ordinal540:PPROC
olecli32_ordinal540 equ <__imp_olecli32_ordinal540>

externdef __imp_olecli32_ordinal541:PPROC
olecli32_ordinal541 equ <__imp_olecli32_ordinal541>

externdef __imp_olecli32_ordinal542:PPROC
olecli32_ordinal542 equ <__imp_olecli32_ordinal542>

externdef __imp_olecli32_ordinal543:PPROC
olecli32_ordinal543 equ <__imp_olecli32_ordinal543>

externdef __imp_olecli32_ordinal544:PPROC
olecli32_ordinal544 equ <__imp_olecli32_ordinal544>

externdef __imp_olecli32_ordinal545:PPROC
olecli32_ordinal545 equ <__imp_olecli32_ordinal545>

externdef __imp_olecli32_ordinal546:PPROC
olecli32_ordinal546 equ <__imp_olecli32_ordinal546>

externdef __imp_olecli32_ordinal547:PPROC
olecli32_ordinal547 equ <__imp_olecli32_ordinal547>

externdef __imp_olecli32_ordinal548:PPROC
olecli32_ordinal548 equ <__imp_olecli32_ordinal548>

externdef __imp_olecli32_ordinal549:PPROC
olecli32_ordinal549 equ <__imp_olecli32_ordinal549>

externdef __imp_olecli32_ordinal550:PPROC
olecli32_ordinal550 equ <__imp_olecli32_ordinal550>

externdef __imp_olecli32_ordinal551:PPROC
olecli32_ordinal551 equ <__imp_olecli32_ordinal551>

externdef __imp_olecli32_ordinal552:PPROC
olecli32_ordinal552 equ <__imp_olecli32_ordinal552>

externdef __imp_olecli32_ordinal553:PPROC
olecli32_ordinal553 equ <__imp_olecli32_ordinal553>

externdef __imp_olecli32_ordinal554:PPROC
olecli32_ordinal554 equ <__imp_olecli32_ordinal554>

externdef __imp_olecli32_ordinal555:PPROC
olecli32_ordinal555 equ <__imp_olecli32_ordinal555>

externdef __imp_olecli32_ordinal556:PPROC
olecli32_ordinal556 equ <__imp_olecli32_ordinal556>

externdef __imp_olecli32_ordinal557:PPROC
olecli32_ordinal557 equ <__imp_olecli32_ordinal557>

externdef __imp_olecli32_ordinal558:PPROC
olecli32_ordinal558 equ <__imp_olecli32_ordinal558>

externdef __imp_olecli32_ordinal559:PPROC
olecli32_ordinal559 equ <__imp_olecli32_ordinal559>

externdef __imp_olecli32_ordinal560:PPROC
olecli32_ordinal560 equ <__imp_olecli32_ordinal560>

externdef __imp_olecli32_ordinal561:PPROC
olecli32_ordinal561 equ <__imp_olecli32_ordinal561>

externdef __imp_olecli32_ordinal562:PPROC
olecli32_ordinal562 equ <__imp_olecli32_ordinal562>

externdef __imp_olecli32_ordinal563:PPROC
olecli32_ordinal563 equ <__imp_olecli32_ordinal563>

externdef __imp_olecli32_ordinal564:PPROC
olecli32_ordinal564 equ <__imp_olecli32_ordinal564>

externdef __imp_olecli32_ordinal565:PPROC
olecli32_ordinal565 equ <__imp_olecli32_ordinal565>

externdef __imp_olecli32_ordinal566:PPROC
olecli32_ordinal566 equ <__imp_olecli32_ordinal566>

externdef __imp_olecli32_ordinal567:PPROC
olecli32_ordinal567 equ <__imp_olecli32_ordinal567>

externdef __imp_olecli32_ordinal568:PPROC
olecli32_ordinal568 equ <__imp_olecli32_ordinal568>

externdef __imp_olecli32_ordinal569:PPROC
olecli32_ordinal569 equ <__imp_olecli32_ordinal569>

externdef __imp_olecli32_ordinal570:PPROC
olecli32_ordinal570 equ <__imp_olecli32_ordinal570>

externdef __imp_olecli32_ordinal571:PPROC
olecli32_ordinal571 equ <__imp_olecli32_ordinal571>

externdef __imp_olecli32_ordinal572:PPROC
olecli32_ordinal572 equ <__imp_olecli32_ordinal572>

externdef __imp_olecli32_ordinal573:PPROC
olecli32_ordinal573 equ <__imp_olecli32_ordinal573>

externdef __imp_olecli32_ordinal574:PPROC
olecli32_ordinal574 equ <__imp_olecli32_ordinal574>

externdef __imp_olecli32_ordinal575:PPROC
olecli32_ordinal575 equ <__imp_olecli32_ordinal575>

externdef __imp_olecli32_ordinal576:PPROC
olecli32_ordinal576 equ <__imp_olecli32_ordinal576>

externdef __imp_olecli32_ordinal577:PPROC
olecli32_ordinal577 equ <__imp_olecli32_ordinal577>

externdef __imp_olecli32_ordinal578:PPROC
olecli32_ordinal578 equ <__imp_olecli32_ordinal578>

externdef __imp_olecli32_ordinal579:PPROC
olecli32_ordinal579 equ <__imp_olecli32_ordinal579>

externdef __imp_olecli32_ordinal580:PPROC
olecli32_ordinal580 equ <__imp_olecli32_ordinal580>

externdef __imp_olecli32_ordinal581:PPROC
olecli32_ordinal581 equ <__imp_olecli32_ordinal581>

externdef __imp_olecli32_ordinal582:PPROC
olecli32_ordinal582 equ <__imp_olecli32_ordinal582>

externdef __imp_olecli32_ordinal583:PPROC
olecli32_ordinal583 equ <__imp_olecli32_ordinal583>

externdef __imp_olecli32_ordinal584:PPROC
olecli32_ordinal584 equ <__imp_olecli32_ordinal584>

externdef __imp_olecli32_ordinal585:PPROC
olecli32_ordinal585 equ <__imp_olecli32_ordinal585>

externdef __imp_olecli32_ordinal586:PPROC
olecli32_ordinal586 equ <__imp_olecli32_ordinal586>

externdef __imp_olecli32_ordinal587:PPROC
olecli32_ordinal587 equ <__imp_olecli32_ordinal587>

externdef __imp_olecli32_ordinal588:PPROC
olecli32_ordinal588 equ <__imp_olecli32_ordinal588>

externdef __imp_olecli32_ordinal589:PPROC
olecli32_ordinal589 equ <__imp_olecli32_ordinal589>

externdef __imp_olecli32_ordinal590:PPROC
olecli32_ordinal590 equ <__imp_olecli32_ordinal590>

externdef __imp_olecli32_ordinal591:PPROC
olecli32_ordinal591 equ <__imp_olecli32_ordinal591>

externdef __imp_olecli32_ordinal592:PPROC
olecli32_ordinal592 equ <__imp_olecli32_ordinal592>

externdef __imp_olecli32_ordinal593:PPROC
olecli32_ordinal593 equ <__imp_olecli32_ordinal593>

externdef __imp_olecli32_ordinal594:PPROC
olecli32_ordinal594 equ <__imp_olecli32_ordinal594>

externdef __imp_olecli32_ordinal595:PPROC
olecli32_ordinal595 equ <__imp_olecli32_ordinal595>

externdef __imp_olecli32_ordinal596:PPROC
olecli32_ordinal596 equ <__imp_olecli32_ordinal596>

externdef __imp_olecli32_ordinal597:PPROC
olecli32_ordinal597 equ <__imp_olecli32_ordinal597>

externdef __imp_olecli32_ordinal598:PPROC
olecli32_ordinal598 equ <__imp_olecli32_ordinal598>

externdef __imp_olecli32_ordinal599:PPROC
olecli32_ordinal599 equ <__imp_olecli32_ordinal599>

externdef __imp_olecli32_ordinal5:PPROC
olecli32_ordinal5 equ <__imp_olecli32_ordinal5>

externdef __imp_olecli32_ordinal607:PPROC
olecli32_ordinal607 equ <__imp_olecli32_ordinal607>

externdef __imp_olecli32_ordinal612:PPROC
olecli32_ordinal612 equ <__imp_olecli32_ordinal612>

externdef __imp_olecli32_ordinal613:PPROC
olecli32_ordinal613 equ <__imp_olecli32_ordinal613>

externdef __imp_olecli32_ordinal614:PPROC
olecli32_ordinal614 equ <__imp_olecli32_ordinal614>

externdef __imp_olecli32_ordinal615:PPROC
olecli32_ordinal615 equ <__imp_olecli32_ordinal615>

externdef __imp_olecli32_ordinal616:PPROC
olecli32_ordinal616 equ <__imp_olecli32_ordinal616>

externdef __imp_olecli32_ordinal617:PPROC
olecli32_ordinal617 equ <__imp_olecli32_ordinal617>

externdef __imp_olecli32_ordinal618:PPROC
olecli32_ordinal618 equ <__imp_olecli32_ordinal618>

externdef __imp_olecli32_ordinal619:PPROC
olecli32_ordinal619 equ <__imp_olecli32_ordinal619>

externdef __imp_olecli32_ordinal61:PPROC
olecli32_ordinal61 equ <__imp_olecli32_ordinal61>

externdef __imp_olecli32_ordinal620:PPROC
olecli32_ordinal620 equ <__imp_olecli32_ordinal620>

externdef __imp_olecli32_ordinal621:PPROC
olecli32_ordinal621 equ <__imp_olecli32_ordinal621>

externdef __imp_olecli32_ordinal622:PPROC
olecli32_ordinal622 equ <__imp_olecli32_ordinal622>

externdef __imp_olecli32_ordinal623:PPROC
olecli32_ordinal623 equ <__imp_olecli32_ordinal623>

externdef __imp_olecli32_ordinal624:PPROC
olecli32_ordinal624 equ <__imp_olecli32_ordinal624>

externdef __imp_olecli32_ordinal625:PPROC
olecli32_ordinal625 equ <__imp_olecli32_ordinal625>

externdef __imp_olecli32_ordinal626:PPROC
olecli32_ordinal626 equ <__imp_olecli32_ordinal626>

externdef __imp_olecli32_ordinal627:PPROC
olecli32_ordinal627 equ <__imp_olecli32_ordinal627>

externdef __imp_olecli32_ordinal628:PPROC
olecli32_ordinal628 equ <__imp_olecli32_ordinal628>

externdef __imp_olecli32_ordinal629:PPROC
olecli32_ordinal629 equ <__imp_olecli32_ordinal629>

externdef __imp_olecli32_ordinal62:PPROC
olecli32_ordinal62 equ <__imp_olecli32_ordinal62>

externdef __imp_olecli32_ordinal630:PPROC
olecli32_ordinal630 equ <__imp_olecli32_ordinal630>

externdef __imp_olecli32_ordinal631:PPROC
olecli32_ordinal631 equ <__imp_olecli32_ordinal631>

externdef __imp_olecli32_ordinal632:PPROC
olecli32_ordinal632 equ <__imp_olecli32_ordinal632>

externdef __imp_olecli32_ordinal633:PPROC
olecli32_ordinal633 equ <__imp_olecli32_ordinal633>

externdef __imp_olecli32_ordinal634:PPROC
olecli32_ordinal634 equ <__imp_olecli32_ordinal634>

externdef __imp_olecli32_ordinal635:PPROC
olecli32_ordinal635 equ <__imp_olecli32_ordinal635>

externdef __imp_olecli32_ordinal636:PPROC
olecli32_ordinal636 equ <__imp_olecli32_ordinal636>

externdef __imp_olecli32_ordinal637:PPROC
olecli32_ordinal637 equ <__imp_olecli32_ordinal637>

externdef __imp_olecli32_ordinal638:PPROC
olecli32_ordinal638 equ <__imp_olecli32_ordinal638>

externdef __imp_olecli32_ordinal639:PPROC
olecli32_ordinal639 equ <__imp_olecli32_ordinal639>

externdef __imp_olecli32_ordinal63:PPROC
olecli32_ordinal63 equ <__imp_olecli32_ordinal63>

externdef __imp_olecli32_ordinal640:PPROC
olecli32_ordinal640 equ <__imp_olecli32_ordinal640>

externdef __imp_olecli32_ordinal641:PPROC
olecli32_ordinal641 equ <__imp_olecli32_ordinal641>

externdef __imp_olecli32_ordinal642:PPROC
olecli32_ordinal642 equ <__imp_olecli32_ordinal642>

externdef __imp_olecli32_ordinal643:PPROC
olecli32_ordinal643 equ <__imp_olecli32_ordinal643>

externdef __imp_olecli32_ordinal644:PPROC
olecli32_ordinal644 equ <__imp_olecli32_ordinal644>

externdef __imp_olecli32_ordinal645:PPROC
olecli32_ordinal645 equ <__imp_olecli32_ordinal645>

externdef __imp_olecli32_ordinal646:PPROC
olecli32_ordinal646 equ <__imp_olecli32_ordinal646>

externdef __imp_olecli32_ordinal647:PPROC
olecli32_ordinal647 equ <__imp_olecli32_ordinal647>

externdef __imp_olecli32_ordinal648:PPROC
olecli32_ordinal648 equ <__imp_olecli32_ordinal648>

externdef __imp_olecli32_ordinal649:PPROC
olecli32_ordinal649 equ <__imp_olecli32_ordinal649>

externdef __imp_olecli32_ordinal64:PPROC
olecli32_ordinal64 equ <__imp_olecli32_ordinal64>

externdef __imp_olecli32_ordinal650:PPROC
olecli32_ordinal650 equ <__imp_olecli32_ordinal650>

externdef __imp_olecli32_ordinal651:PPROC
olecli32_ordinal651 equ <__imp_olecli32_ordinal651>

externdef __imp_olecli32_ordinal652:PPROC
olecli32_ordinal652 equ <__imp_olecli32_ordinal652>

externdef __imp_olecli32_ordinal653:PPROC
olecli32_ordinal653 equ <__imp_olecli32_ordinal653>

externdef __imp_olecli32_ordinal654:PPROC
olecli32_ordinal654 equ <__imp_olecli32_ordinal654>

externdef __imp_olecli32_ordinal655:PPROC
olecli32_ordinal655 equ <__imp_olecli32_ordinal655>

externdef __imp_olecli32_ordinal656:PPROC
olecli32_ordinal656 equ <__imp_olecli32_ordinal656>

externdef __imp_olecli32_ordinal657:PPROC
olecli32_ordinal657 equ <__imp_olecli32_ordinal657>

externdef __imp_olecli32_ordinal658:PPROC
olecli32_ordinal658 equ <__imp_olecli32_ordinal658>

externdef __imp_olecli32_ordinal659:PPROC
olecli32_ordinal659 equ <__imp_olecli32_ordinal659>

externdef __imp_olecli32_ordinal65:PPROC
olecli32_ordinal65 equ <__imp_olecli32_ordinal65>

externdef __imp_olecli32_ordinal660:PPROC
olecli32_ordinal660 equ <__imp_olecli32_ordinal660>

externdef __imp_olecli32_ordinal661:PPROC
olecli32_ordinal661 equ <__imp_olecli32_ordinal661>

externdef __imp_olecli32_ordinal662:PPROC
olecli32_ordinal662 equ <__imp_olecli32_ordinal662>

externdef __imp_olecli32_ordinal663:PPROC
olecli32_ordinal663 equ <__imp_olecli32_ordinal663>

externdef __imp_olecli32_ordinal664:PPROC
olecli32_ordinal664 equ <__imp_olecli32_ordinal664>

externdef __imp_olecli32_ordinal665:PPROC
olecli32_ordinal665 equ <__imp_olecli32_ordinal665>

externdef __imp_olecli32_ordinal666:PPROC
olecli32_ordinal666 equ <__imp_olecli32_ordinal666>

externdef __imp_olecli32_ordinal667:PPROC
olecli32_ordinal667 equ <__imp_olecli32_ordinal667>

externdef __imp_olecli32_ordinal668:PPROC
olecli32_ordinal668 equ <__imp_olecli32_ordinal668>

externdef __imp_olecli32_ordinal669:PPROC
olecli32_ordinal669 equ <__imp_olecli32_ordinal669>

externdef __imp_olecli32_ordinal66:PPROC
olecli32_ordinal66 equ <__imp_olecli32_ordinal66>

externdef __imp_olecli32_ordinal670:PPROC
olecli32_ordinal670 equ <__imp_olecli32_ordinal670>

externdef __imp_olecli32_ordinal671:PPROC
olecli32_ordinal671 equ <__imp_olecli32_ordinal671>

externdef __imp_olecli32_ordinal672:PPROC
olecli32_ordinal672 equ <__imp_olecli32_ordinal672>

externdef __imp_olecli32_ordinal673:PPROC
olecli32_ordinal673 equ <__imp_olecli32_ordinal673>

externdef __imp_olecli32_ordinal674:PPROC
olecli32_ordinal674 equ <__imp_olecli32_ordinal674>

externdef __imp_olecli32_ordinal675:PPROC
olecli32_ordinal675 equ <__imp_olecli32_ordinal675>

externdef __imp_olecli32_ordinal676:PPROC
olecli32_ordinal676 equ <__imp_olecli32_ordinal676>

externdef __imp_olecli32_ordinal677:PPROC
olecli32_ordinal677 equ <__imp_olecli32_ordinal677>

externdef __imp_olecli32_ordinal678:PPROC
olecli32_ordinal678 equ <__imp_olecli32_ordinal678>

externdef __imp_olecli32_ordinal679:PPROC
olecli32_ordinal679 equ <__imp_olecli32_ordinal679>

externdef __imp_olecli32_ordinal67:PPROC
olecli32_ordinal67 equ <__imp_olecli32_ordinal67>

externdef __imp_olecli32_ordinal680:PPROC
olecli32_ordinal680 equ <__imp_olecli32_ordinal680>

externdef __imp_olecli32_ordinal681:PPROC
olecli32_ordinal681 equ <__imp_olecli32_ordinal681>

externdef __imp_olecli32_ordinal682:PPROC
olecli32_ordinal682 equ <__imp_olecli32_ordinal682>

externdef __imp_olecli32_ordinal683:PPROC
olecli32_ordinal683 equ <__imp_olecli32_ordinal683>

externdef __imp_olecli32_ordinal684:PPROC
olecli32_ordinal684 equ <__imp_olecli32_ordinal684>

externdef __imp_olecli32_ordinal685:PPROC
olecli32_ordinal685 equ <__imp_olecli32_ordinal685>

externdef __imp_olecli32_ordinal686:PPROC
olecli32_ordinal686 equ <__imp_olecli32_ordinal686>

externdef __imp_olecli32_ordinal687:PPROC
olecli32_ordinal687 equ <__imp_olecli32_ordinal687>

externdef __imp_olecli32_ordinal688:PPROC
olecli32_ordinal688 equ <__imp_olecli32_ordinal688>

externdef __imp_olecli32_ordinal689:PPROC
olecli32_ordinal689 equ <__imp_olecli32_ordinal689>

externdef __imp_olecli32_ordinal68:PPROC
olecli32_ordinal68 equ <__imp_olecli32_ordinal68>

externdef __imp_olecli32_ordinal690:PPROC
olecli32_ordinal690 equ <__imp_olecli32_ordinal690>

externdef __imp_olecli32_ordinal691:PPROC
olecli32_ordinal691 equ <__imp_olecli32_ordinal691>

externdef __imp_olecli32_ordinal692:PPROC
olecli32_ordinal692 equ <__imp_olecli32_ordinal692>

externdef __imp_olecli32_ordinal693:PPROC
olecli32_ordinal693 equ <__imp_olecli32_ordinal693>

externdef __imp_olecli32_ordinal694:PPROC
olecli32_ordinal694 equ <__imp_olecli32_ordinal694>

externdef __imp_olecli32_ordinal695:PPROC
olecli32_ordinal695 equ <__imp_olecli32_ordinal695>

externdef __imp_olecli32_ordinal696:PPROC
olecli32_ordinal696 equ <__imp_olecli32_ordinal696>

externdef __imp_olecli32_ordinal697:PPROC
olecli32_ordinal697 equ <__imp_olecli32_ordinal697>

externdef __imp_olecli32_ordinal698:PPROC
olecli32_ordinal698 equ <__imp_olecli32_ordinal698>

externdef __imp_olecli32_ordinal699:PPROC
olecli32_ordinal699 equ <__imp_olecli32_ordinal699>

externdef __imp_olecli32_ordinal69:PPROC
olecli32_ordinal69 equ <__imp_olecli32_ordinal69>

externdef __imp_olecli32_ordinal700:PPROC
olecli32_ordinal700 equ <__imp_olecli32_ordinal700>

externdef __imp_olecli32_ordinal70:PPROC
olecli32_ordinal70 equ <__imp_olecli32_ordinal70>

externdef __imp_olecli32_ordinal719:PPROC
olecli32_ordinal719 equ <__imp_olecli32_ordinal719>

externdef __imp_olecli32_ordinal71:PPROC
olecli32_ordinal71 equ <__imp_olecli32_ordinal71>

externdef __imp_olecli32_ordinal720:PPROC
olecli32_ordinal720 equ <__imp_olecli32_ordinal720>

externdef __imp_olecli32_ordinal721:PPROC
olecli32_ordinal721 equ <__imp_olecli32_ordinal721>

externdef __imp_olecli32_ordinal722:PPROC
olecli32_ordinal722 equ <__imp_olecli32_ordinal722>

externdef __imp_olecli32_ordinal723:PPROC
olecli32_ordinal723 equ <__imp_olecli32_ordinal723>

externdef __imp_olecli32_ordinal724:PPROC
olecli32_ordinal724 equ <__imp_olecli32_ordinal724>

externdef __imp_olecli32_ordinal725:PPROC
olecli32_ordinal725 equ <__imp_olecli32_ordinal725>

externdef __imp_olecli32_ordinal726:PPROC
olecli32_ordinal726 equ <__imp_olecli32_ordinal726>

externdef __imp_olecli32_ordinal727:PPROC
olecli32_ordinal727 equ <__imp_olecli32_ordinal727>

externdef __imp_olecli32_ordinal728:PPROC
olecli32_ordinal728 equ <__imp_olecli32_ordinal728>

externdef __imp_olecli32_ordinal729:PPROC
olecli32_ordinal729 equ <__imp_olecli32_ordinal729>

externdef __imp_olecli32_ordinal72:PPROC
olecli32_ordinal72 equ <__imp_olecli32_ordinal72>

externdef __imp_olecli32_ordinal730:PPROC
olecli32_ordinal730 equ <__imp_olecli32_ordinal730>

externdef __imp_olecli32_ordinal731:PPROC
olecli32_ordinal731 equ <__imp_olecli32_ordinal731>

externdef __imp_olecli32_ordinal732:PPROC
olecli32_ordinal732 equ <__imp_olecli32_ordinal732>

externdef __imp_olecli32_ordinal733:PPROC
olecli32_ordinal733 equ <__imp_olecli32_ordinal733>

externdef __imp_olecli32_ordinal734:PPROC
olecli32_ordinal734 equ <__imp_olecli32_ordinal734>

externdef __imp_olecli32_ordinal735:PPROC
olecli32_ordinal735 equ <__imp_olecli32_ordinal735>

externdef __imp_olecli32_ordinal736:PPROC
olecli32_ordinal736 equ <__imp_olecli32_ordinal736>

externdef __imp_olecli32_ordinal737:PPROC
olecli32_ordinal737 equ <__imp_olecli32_ordinal737>

externdef __imp_olecli32_ordinal738:PPROC
olecli32_ordinal738 equ <__imp_olecli32_ordinal738>

externdef __imp_olecli32_ordinal739:PPROC
olecli32_ordinal739 equ <__imp_olecli32_ordinal739>

externdef __imp_olecli32_ordinal73:PPROC
olecli32_ordinal73 equ <__imp_olecli32_ordinal73>

externdef __imp_olecli32_ordinal740:PPROC
olecli32_ordinal740 equ <__imp_olecli32_ordinal740>

externdef __imp_olecli32_ordinal741:PPROC
olecli32_ordinal741 equ <__imp_olecli32_ordinal741>

externdef __imp_olecli32_ordinal742:PPROC
olecli32_ordinal742 equ <__imp_olecli32_ordinal742>

externdef __imp_olecli32_ordinal743:PPROC
olecli32_ordinal743 equ <__imp_olecli32_ordinal743>

externdef __imp_olecli32_ordinal744:PPROC
olecli32_ordinal744 equ <__imp_olecli32_ordinal744>

externdef __imp_olecli32_ordinal745:PPROC
olecli32_ordinal745 equ <__imp_olecli32_ordinal745>

externdef __imp_olecli32_ordinal746:PPROC
olecli32_ordinal746 equ <__imp_olecli32_ordinal746>

externdef __imp_olecli32_ordinal747:PPROC
olecli32_ordinal747 equ <__imp_olecli32_ordinal747>

externdef __imp_olecli32_ordinal748:PPROC
olecli32_ordinal748 equ <__imp_olecli32_ordinal748>

externdef __imp_olecli32_ordinal749:PPROC
olecli32_ordinal749 equ <__imp_olecli32_ordinal749>

externdef __imp_olecli32_ordinal74:PPROC
olecli32_ordinal74 equ <__imp_olecli32_ordinal74>

externdef __imp_olecli32_ordinal750:PPROC
olecli32_ordinal750 equ <__imp_olecli32_ordinal750>

externdef __imp_olecli32_ordinal751:PPROC
olecli32_ordinal751 equ <__imp_olecli32_ordinal751>

externdef __imp_olecli32_ordinal752:PPROC
olecli32_ordinal752 equ <__imp_olecli32_ordinal752>

externdef __imp_olecli32_ordinal753:PPROC
olecli32_ordinal753 equ <__imp_olecli32_ordinal753>

externdef __imp_olecli32_ordinal754:PPROC
olecli32_ordinal754 equ <__imp_olecli32_ordinal754>

externdef __imp_olecli32_ordinal755:PPROC
olecli32_ordinal755 equ <__imp_olecli32_ordinal755>

externdef __imp_olecli32_ordinal756:PPROC
olecli32_ordinal756 equ <__imp_olecli32_ordinal756>

externdef __imp_olecli32_ordinal757:PPROC
olecli32_ordinal757 equ <__imp_olecli32_ordinal757>

externdef __imp_olecli32_ordinal758:PPROC
olecli32_ordinal758 equ <__imp_olecli32_ordinal758>

externdef __imp_olecli32_ordinal759:PPROC
olecli32_ordinal759 equ <__imp_olecli32_ordinal759>

externdef __imp_olecli32_ordinal75:PPROC
olecli32_ordinal75 equ <__imp_olecli32_ordinal75>

externdef __imp_olecli32_ordinal760:PPROC
olecli32_ordinal760 equ <__imp_olecli32_ordinal760>

externdef __imp_olecli32_ordinal761:PPROC
olecli32_ordinal761 equ <__imp_olecli32_ordinal761>

externdef __imp_olecli32_ordinal762:PPROC
olecli32_ordinal762 equ <__imp_olecli32_ordinal762>

externdef __imp_olecli32_ordinal763:PPROC
olecli32_ordinal763 equ <__imp_olecli32_ordinal763>

externdef __imp_olecli32_ordinal764:PPROC
olecli32_ordinal764 equ <__imp_olecli32_ordinal764>

externdef __imp_olecli32_ordinal765:PPROC
olecli32_ordinal765 equ <__imp_olecli32_ordinal765>

externdef __imp_olecli32_ordinal766:PPROC
olecli32_ordinal766 equ <__imp_olecli32_ordinal766>

externdef __imp_olecli32_ordinal767:PPROC
olecli32_ordinal767 equ <__imp_olecli32_ordinal767>

externdef __imp_olecli32_ordinal768:PPROC
olecli32_ordinal768 equ <__imp_olecli32_ordinal768>

externdef __imp_olecli32_ordinal769:PPROC
olecli32_ordinal769 equ <__imp_olecli32_ordinal769>

externdef __imp_olecli32_ordinal76:PPROC
olecli32_ordinal76 equ <__imp_olecli32_ordinal76>

externdef __imp_olecli32_ordinal770:PPROC
olecli32_ordinal770 equ <__imp_olecli32_ordinal770>

externdef __imp_olecli32_ordinal771:PPROC
olecli32_ordinal771 equ <__imp_olecli32_ordinal771>

externdef __imp_olecli32_ordinal772:PPROC
olecli32_ordinal772 equ <__imp_olecli32_ordinal772>

externdef __imp_olecli32_ordinal773:PPROC
olecli32_ordinal773 equ <__imp_olecli32_ordinal773>

externdef __imp_olecli32_ordinal774:PPROC
olecli32_ordinal774 equ <__imp_olecli32_ordinal774>

externdef __imp_olecli32_ordinal775:PPROC
olecli32_ordinal775 equ <__imp_olecli32_ordinal775>

externdef __imp_olecli32_ordinal776:PPROC
olecli32_ordinal776 equ <__imp_olecli32_ordinal776>

externdef __imp_olecli32_ordinal777:PPROC
olecli32_ordinal777 equ <__imp_olecli32_ordinal777>

externdef __imp_olecli32_ordinal778:PPROC
olecli32_ordinal778 equ <__imp_olecli32_ordinal778>

externdef __imp_olecli32_ordinal779:PPROC
olecli32_ordinal779 equ <__imp_olecli32_ordinal779>

externdef __imp_olecli32_ordinal77:PPROC
olecli32_ordinal77 equ <__imp_olecli32_ordinal77>

externdef __imp_olecli32_ordinal780:PPROC
olecli32_ordinal780 equ <__imp_olecli32_ordinal780>

externdef __imp_olecli32_ordinal781:PPROC
olecli32_ordinal781 equ <__imp_olecli32_ordinal781>

externdef __imp_olecli32_ordinal782:PPROC
olecli32_ordinal782 equ <__imp_olecli32_ordinal782>

externdef __imp_olecli32_ordinal783:PPROC
olecli32_ordinal783 equ <__imp_olecli32_ordinal783>

externdef __imp_olecli32_ordinal784:PPROC
olecli32_ordinal784 equ <__imp_olecli32_ordinal784>

externdef __imp_olecli32_ordinal785:PPROC
olecli32_ordinal785 equ <__imp_olecli32_ordinal785>

externdef __imp_olecli32_ordinal786:PPROC
olecli32_ordinal786 equ <__imp_olecli32_ordinal786>

externdef __imp_olecli32_ordinal787:PPROC
olecli32_ordinal787 equ <__imp_olecli32_ordinal787>

externdef __imp_olecli32_ordinal788:PPROC
olecli32_ordinal788 equ <__imp_olecli32_ordinal788>

externdef __imp_olecli32_ordinal789:PPROC
olecli32_ordinal789 equ <__imp_olecli32_ordinal789>

externdef __imp_olecli32_ordinal78:PPROC
olecli32_ordinal78 equ <__imp_olecli32_ordinal78>

externdef __imp_olecli32_ordinal790:PPROC
olecli32_ordinal790 equ <__imp_olecli32_ordinal790>

externdef __imp_olecli32_ordinal791:PPROC
olecli32_ordinal791 equ <__imp_olecli32_ordinal791>

externdef __imp_olecli32_ordinal792:PPROC
olecli32_ordinal792 equ <__imp_olecli32_ordinal792>

externdef __imp_olecli32_ordinal793:PPROC
olecli32_ordinal793 equ <__imp_olecli32_ordinal793>

externdef __imp_olecli32_ordinal794:PPROC
olecli32_ordinal794 equ <__imp_olecli32_ordinal794>

externdef __imp_olecli32_ordinal795:PPROC
olecli32_ordinal795 equ <__imp_olecli32_ordinal795>

externdef __imp_olecli32_ordinal796:PPROC
olecli32_ordinal796 equ <__imp_olecli32_ordinal796>

externdef __imp_olecli32_ordinal797:PPROC
olecli32_ordinal797 equ <__imp_olecli32_ordinal797>

externdef __imp_olecli32_ordinal798:PPROC
olecli32_ordinal798 equ <__imp_olecli32_ordinal798>

externdef __imp_olecli32_ordinal799:PPROC
olecli32_ordinal799 equ <__imp_olecli32_ordinal799>

externdef __imp_olecli32_ordinal79:PPROC
olecli32_ordinal79 equ <__imp_olecli32_ordinal79>

externdef __imp_olecli32_ordinal80:PPROC
olecli32_ordinal80 equ <__imp_olecli32_ordinal80>

externdef __imp_olecli32_ordinal813:PPROC
olecli32_ordinal813 equ <__imp_olecli32_ordinal813>

externdef __imp_olecli32_ordinal814:PPROC
olecli32_ordinal814 equ <__imp_olecli32_ordinal814>

externdef __imp_olecli32_ordinal815:PPROC
olecli32_ordinal815 equ <__imp_olecli32_ordinal815>

externdef __imp_olecli32_ordinal816:PPROC
olecli32_ordinal816 equ <__imp_olecli32_ordinal816>

externdef __imp_olecli32_ordinal817:PPROC
olecli32_ordinal817 equ <__imp_olecli32_ordinal817>

externdef __imp_olecli32_ordinal818:PPROC
olecli32_ordinal818 equ <__imp_olecli32_ordinal818>

externdef __imp_olecli32_ordinal819:PPROC
olecli32_ordinal819 equ <__imp_olecli32_ordinal819>

externdef __imp_olecli32_ordinal81:PPROC
olecli32_ordinal81 equ <__imp_olecli32_ordinal81>

externdef __imp_olecli32_ordinal820:PPROC
olecli32_ordinal820 equ <__imp_olecli32_ordinal820>

externdef __imp_olecli32_ordinal821:PPROC
olecli32_ordinal821 equ <__imp_olecli32_ordinal821>

externdef __imp_olecli32_ordinal822:PPROC
olecli32_ordinal822 equ <__imp_olecli32_ordinal822>

externdef __imp_olecli32_ordinal823:PPROC
olecli32_ordinal823 equ <__imp_olecli32_ordinal823>

externdef __imp_olecli32_ordinal824:PPROC
olecli32_ordinal824 equ <__imp_olecli32_ordinal824>

externdef __imp_olecli32_ordinal825:PPROC
olecli32_ordinal825 equ <__imp_olecli32_ordinal825>

externdef __imp_olecli32_ordinal826:PPROC
olecli32_ordinal826 equ <__imp_olecli32_ordinal826>

externdef __imp_olecli32_ordinal827:PPROC
olecli32_ordinal827 equ <__imp_olecli32_ordinal827>

externdef __imp_olecli32_ordinal828:PPROC
olecli32_ordinal828 equ <__imp_olecli32_ordinal828>

externdef __imp_olecli32_ordinal829:PPROC
olecli32_ordinal829 equ <__imp_olecli32_ordinal829>

externdef __imp_olecli32_ordinal82:PPROC
olecli32_ordinal82 equ <__imp_olecli32_ordinal82>

externdef __imp_olecli32_ordinal830:PPROC
olecli32_ordinal830 equ <__imp_olecli32_ordinal830>

externdef __imp_olecli32_ordinal831:PPROC
olecli32_ordinal831 equ <__imp_olecli32_ordinal831>

externdef __imp_olecli32_ordinal832:PPROC
olecli32_ordinal832 equ <__imp_olecli32_ordinal832>

externdef __imp_olecli32_ordinal833:PPROC
olecli32_ordinal833 equ <__imp_olecli32_ordinal833>

externdef __imp_olecli32_ordinal834:PPROC
olecli32_ordinal834 equ <__imp_olecli32_ordinal834>

externdef __imp_olecli32_ordinal835:PPROC
olecli32_ordinal835 equ <__imp_olecli32_ordinal835>

externdef __imp_olecli32_ordinal836:PPROC
olecli32_ordinal836 equ <__imp_olecli32_ordinal836>

externdef __imp_olecli32_ordinal837:PPROC
olecli32_ordinal837 equ <__imp_olecli32_ordinal837>

externdef __imp_olecli32_ordinal838:PPROC
olecli32_ordinal838 equ <__imp_olecli32_ordinal838>

externdef __imp_olecli32_ordinal839:PPROC
olecli32_ordinal839 equ <__imp_olecli32_ordinal839>

externdef __imp_olecli32_ordinal83:PPROC
olecli32_ordinal83 equ <__imp_olecli32_ordinal83>

externdef __imp_olecli32_ordinal840:PPROC
olecli32_ordinal840 equ <__imp_olecli32_ordinal840>

externdef __imp_olecli32_ordinal841:PPROC
olecli32_ordinal841 equ <__imp_olecli32_ordinal841>

externdef __imp_olecli32_ordinal842:PPROC
olecli32_ordinal842 equ <__imp_olecli32_ordinal842>

externdef __imp_olecli32_ordinal843:PPROC
olecli32_ordinal843 equ <__imp_olecli32_ordinal843>

externdef __imp_olecli32_ordinal844:PPROC
olecli32_ordinal844 equ <__imp_olecli32_ordinal844>

externdef __imp_olecli32_ordinal845:PPROC
olecli32_ordinal845 equ <__imp_olecli32_ordinal845>

externdef __imp_olecli32_ordinal846:PPROC
olecli32_ordinal846 equ <__imp_olecli32_ordinal846>

externdef __imp_olecli32_ordinal847:PPROC
olecli32_ordinal847 equ <__imp_olecli32_ordinal847>

externdef __imp_olecli32_ordinal848:PPROC
olecli32_ordinal848 equ <__imp_olecli32_ordinal848>

externdef __imp_olecli32_ordinal849:PPROC
olecli32_ordinal849 equ <__imp_olecli32_ordinal849>

externdef __imp_olecli32_ordinal84:PPROC
olecli32_ordinal84 equ <__imp_olecli32_ordinal84>

externdef __imp_olecli32_ordinal850:PPROC
olecli32_ordinal850 equ <__imp_olecli32_ordinal850>

externdef __imp_olecli32_ordinal851:PPROC
olecli32_ordinal851 equ <__imp_olecli32_ordinal851>

externdef __imp_olecli32_ordinal852:PPROC
olecli32_ordinal852 equ <__imp_olecli32_ordinal852>

externdef __imp_olecli32_ordinal853:PPROC
olecli32_ordinal853 equ <__imp_olecli32_ordinal853>

externdef __imp_olecli32_ordinal854:PPROC
olecli32_ordinal854 equ <__imp_olecli32_ordinal854>

externdef __imp_olecli32_ordinal855:PPROC
olecli32_ordinal855 equ <__imp_olecli32_ordinal855>

externdef __imp_olecli32_ordinal856:PPROC
olecli32_ordinal856 equ <__imp_olecli32_ordinal856>

externdef __imp_olecli32_ordinal857:PPROC
olecli32_ordinal857 equ <__imp_olecli32_ordinal857>

externdef __imp_olecli32_ordinal858:PPROC
olecli32_ordinal858 equ <__imp_olecli32_ordinal858>

externdef __imp_olecli32_ordinal859:PPROC
olecli32_ordinal859 equ <__imp_olecli32_ordinal859>

externdef __imp_olecli32_ordinal85:PPROC
olecli32_ordinal85 equ <__imp_olecli32_ordinal85>

externdef __imp_olecli32_ordinal860:PPROC
olecli32_ordinal860 equ <__imp_olecli32_ordinal860>

externdef __imp_olecli32_ordinal861:PPROC
olecli32_ordinal861 equ <__imp_olecli32_ordinal861>

externdef __imp_olecli32_ordinal862:PPROC
olecli32_ordinal862 equ <__imp_olecli32_ordinal862>

externdef __imp_olecli32_ordinal863:PPROC
olecli32_ordinal863 equ <__imp_olecli32_ordinal863>

externdef __imp_olecli32_ordinal864:PPROC
olecli32_ordinal864 equ <__imp_olecli32_ordinal864>

externdef __imp_olecli32_ordinal865:PPROC
olecli32_ordinal865 equ <__imp_olecli32_ordinal865>

externdef __imp_olecli32_ordinal866:PPROC
olecli32_ordinal866 equ <__imp_olecli32_ordinal866>

externdef __imp_olecli32_ordinal867:PPROC
olecli32_ordinal867 equ <__imp_olecli32_ordinal867>

externdef __imp_olecli32_ordinal868:PPROC
olecli32_ordinal868 equ <__imp_olecli32_ordinal868>

externdef __imp_olecli32_ordinal869:PPROC
olecli32_ordinal869 equ <__imp_olecli32_ordinal869>

externdef __imp_olecli32_ordinal86:PPROC
olecli32_ordinal86 equ <__imp_olecli32_ordinal86>

externdef __imp_olecli32_ordinal870:PPROC
olecli32_ordinal870 equ <__imp_olecli32_ordinal870>

externdef __imp_olecli32_ordinal871:PPROC
olecli32_ordinal871 equ <__imp_olecli32_ordinal871>

externdef __imp_olecli32_ordinal872:PPROC
olecli32_ordinal872 equ <__imp_olecli32_ordinal872>

externdef __imp_olecli32_ordinal873:PPROC
olecli32_ordinal873 equ <__imp_olecli32_ordinal873>

externdef __imp_olecli32_ordinal874:PPROC
olecli32_ordinal874 equ <__imp_olecli32_ordinal874>

externdef __imp_olecli32_ordinal875:PPROC
olecli32_ordinal875 equ <__imp_olecli32_ordinal875>

externdef __imp_olecli32_ordinal876:PPROC
olecli32_ordinal876 equ <__imp_olecli32_ordinal876>

externdef __imp_olecli32_ordinal877:PPROC
olecli32_ordinal877 equ <__imp_olecli32_ordinal877>

externdef __imp_olecli32_ordinal878:PPROC
olecli32_ordinal878 equ <__imp_olecli32_ordinal878>

externdef __imp_olecli32_ordinal879:PPROC
olecli32_ordinal879 equ <__imp_olecli32_ordinal879>

externdef __imp_olecli32_ordinal87:PPROC
olecli32_ordinal87 equ <__imp_olecli32_ordinal87>

externdef __imp_olecli32_ordinal880:PPROC
olecli32_ordinal880 equ <__imp_olecli32_ordinal880>

externdef __imp_olecli32_ordinal881:PPROC
olecli32_ordinal881 equ <__imp_olecli32_ordinal881>

externdef __imp_olecli32_ordinal882:PPROC
olecli32_ordinal882 equ <__imp_olecli32_ordinal882>

externdef __imp_olecli32_ordinal883:PPROC
olecli32_ordinal883 equ <__imp_olecli32_ordinal883>

externdef __imp_olecli32_ordinal884:PPROC
olecli32_ordinal884 equ <__imp_olecli32_ordinal884>

externdef __imp_olecli32_ordinal885:PPROC
olecli32_ordinal885 equ <__imp_olecli32_ordinal885>

externdef __imp_olecli32_ordinal886:PPROC
olecli32_ordinal886 equ <__imp_olecli32_ordinal886>

externdef __imp_olecli32_ordinal887:PPROC
olecli32_ordinal887 equ <__imp_olecli32_ordinal887>

externdef __imp_olecli32_ordinal888:PPROC
olecli32_ordinal888 equ <__imp_olecli32_ordinal888>

externdef __imp_olecli32_ordinal889:PPROC
olecli32_ordinal889 equ <__imp_olecli32_ordinal889>

externdef __imp_olecli32_ordinal88:PPROC
olecli32_ordinal88 equ <__imp_olecli32_ordinal88>

externdef __imp_olecli32_ordinal890:PPROC
olecli32_ordinal890 equ <__imp_olecli32_ordinal890>

externdef __imp_olecli32_ordinal891:PPROC
olecli32_ordinal891 equ <__imp_olecli32_ordinal891>

externdef __imp_olecli32_ordinal892:PPROC
olecli32_ordinal892 equ <__imp_olecli32_ordinal892>

externdef __imp_olecli32_ordinal893:PPROC
olecli32_ordinal893 equ <__imp_olecli32_ordinal893>

externdef __imp_olecli32_ordinal894:PPROC
olecli32_ordinal894 equ <__imp_olecli32_ordinal894>

externdef __imp_olecli32_ordinal895:PPROC
olecli32_ordinal895 equ <__imp_olecli32_ordinal895>

externdef __imp_olecli32_ordinal896:PPROC
olecli32_ordinal896 equ <__imp_olecli32_ordinal896>

externdef __imp_olecli32_ordinal897:PPROC
olecli32_ordinal897 equ <__imp_olecli32_ordinal897>

externdef __imp_olecli32_ordinal898:PPROC
olecli32_ordinal898 equ <__imp_olecli32_ordinal898>

externdef __imp_olecli32_ordinal899:PPROC
olecli32_ordinal899 equ <__imp_olecli32_ordinal899>

externdef __imp_olecli32_ordinal89:PPROC
olecli32_ordinal89 equ <__imp_olecli32_ordinal89>

externdef __imp_olecli32_ordinal900:PPROC
olecli32_ordinal900 equ <__imp_olecli32_ordinal900>

externdef __imp_olecli32_ordinal901:PPROC
olecli32_ordinal901 equ <__imp_olecli32_ordinal901>

externdef __imp_olecli32_ordinal902:PPROC
olecli32_ordinal902 equ <__imp_olecli32_ordinal902>

externdef __imp_olecli32_ordinal903:PPROC
olecli32_ordinal903 equ <__imp_olecli32_ordinal903>

externdef __imp_olecli32_ordinal904:PPROC
olecli32_ordinal904 equ <__imp_olecli32_ordinal904>

externdef __imp_olecli32_ordinal905:PPROC
olecli32_ordinal905 equ <__imp_olecli32_ordinal905>

externdef __imp_olecli32_ordinal906:PPROC
olecli32_ordinal906 equ <__imp_olecli32_ordinal906>

externdef __imp_olecli32_ordinal907:PPROC
olecli32_ordinal907 equ <__imp_olecli32_ordinal907>

externdef __imp_olecli32_ordinal908:PPROC
olecli32_ordinal908 equ <__imp_olecli32_ordinal908>

externdef __imp_olecli32_ordinal909:PPROC
olecli32_ordinal909 equ <__imp_olecli32_ordinal909>

externdef __imp_olecli32_ordinal90:PPROC
olecli32_ordinal90 equ <__imp_olecli32_ordinal90>

externdef __imp_olecli32_ordinal914:PPROC
olecli32_ordinal914 equ <__imp_olecli32_ordinal914>

externdef __imp_olecli32_ordinal915:PPROC
olecli32_ordinal915 equ <__imp_olecli32_ordinal915>

externdef __imp_olecli32_ordinal916:PPROC
olecli32_ordinal916 equ <__imp_olecli32_ordinal916>

externdef __imp_olecli32_ordinal917:PPROC
olecli32_ordinal917 equ <__imp_olecli32_ordinal917>

externdef __imp_olecli32_ordinal918:PPROC
olecli32_ordinal918 equ <__imp_olecli32_ordinal918>

externdef __imp_olecli32_ordinal919:PPROC
olecli32_ordinal919 equ <__imp_olecli32_ordinal919>

externdef __imp_olecli32_ordinal91:PPROC
olecli32_ordinal91 equ <__imp_olecli32_ordinal91>

externdef __imp_olecli32_ordinal920:PPROC
olecli32_ordinal920 equ <__imp_olecli32_ordinal920>

externdef __imp_olecli32_ordinal921:PPROC
olecli32_ordinal921 equ <__imp_olecli32_ordinal921>

externdef __imp_olecli32_ordinal922:PPROC
olecli32_ordinal922 equ <__imp_olecli32_ordinal922>

externdef __imp_olecli32_ordinal923:PPROC
olecli32_ordinal923 equ <__imp_olecli32_ordinal923>

externdef __imp_olecli32_ordinal924:PPROC
olecli32_ordinal924 equ <__imp_olecli32_ordinal924>

externdef __imp_olecli32_ordinal925:PPROC
olecli32_ordinal925 equ <__imp_olecli32_ordinal925>

externdef __imp_olecli32_ordinal926:PPROC
olecli32_ordinal926 equ <__imp_olecli32_ordinal926>

externdef __imp_olecli32_ordinal927:PPROC
olecli32_ordinal927 equ <__imp_olecli32_ordinal927>

externdef __imp_olecli32_ordinal928:PPROC
olecli32_ordinal928 equ <__imp_olecli32_ordinal928>

externdef __imp_olecli32_ordinal929:PPROC
olecli32_ordinal929 equ <__imp_olecli32_ordinal929>

externdef __imp_olecli32_ordinal92:PPROC
olecli32_ordinal92 equ <__imp_olecli32_ordinal92>

externdef __imp_olecli32_ordinal930:PPROC
olecli32_ordinal930 equ <__imp_olecli32_ordinal930>

externdef __imp_olecli32_ordinal931:PPROC
olecli32_ordinal931 equ <__imp_olecli32_ordinal931>

externdef __imp_olecli32_ordinal932:PPROC
olecli32_ordinal932 equ <__imp_olecli32_ordinal932>

externdef __imp_olecli32_ordinal933:PPROC
olecli32_ordinal933 equ <__imp_olecli32_ordinal933>

externdef __imp_olecli32_ordinal934:PPROC
olecli32_ordinal934 equ <__imp_olecli32_ordinal934>

externdef __imp_olecli32_ordinal935:PPROC
olecli32_ordinal935 equ <__imp_olecli32_ordinal935>

externdef __imp_olecli32_ordinal936:PPROC
olecli32_ordinal936 equ <__imp_olecli32_ordinal936>

externdef __imp_olecli32_ordinal937:PPROC
olecli32_ordinal937 equ <__imp_olecli32_ordinal937>

externdef __imp_olecli32_ordinal938:PPROC
olecli32_ordinal938 equ <__imp_olecli32_ordinal938>

externdef __imp_olecli32_ordinal939:PPROC
olecli32_ordinal939 equ <__imp_olecli32_ordinal939>

externdef __imp_olecli32_ordinal93:PPROC
olecli32_ordinal93 equ <__imp_olecli32_ordinal93>

externdef __imp_olecli32_ordinal940:PPROC
olecli32_ordinal940 equ <__imp_olecli32_ordinal940>

externdef __imp_olecli32_ordinal941:PPROC
olecli32_ordinal941 equ <__imp_olecli32_ordinal941>

externdef __imp_olecli32_ordinal942:PPROC
olecli32_ordinal942 equ <__imp_olecli32_ordinal942>

externdef __imp_olecli32_ordinal943:PPROC
olecli32_ordinal943 equ <__imp_olecli32_ordinal943>

externdef __imp_olecli32_ordinal944:PPROC
olecli32_ordinal944 equ <__imp_olecli32_ordinal944>

externdef __imp_olecli32_ordinal945:PPROC
olecli32_ordinal945 equ <__imp_olecli32_ordinal945>

externdef __imp_olecli32_ordinal946:PPROC
olecli32_ordinal946 equ <__imp_olecli32_ordinal946>

externdef __imp_olecli32_ordinal947:PPROC
olecli32_ordinal947 equ <__imp_olecli32_ordinal947>

externdef __imp_olecli32_ordinal948:PPROC
olecli32_ordinal948 equ <__imp_olecli32_ordinal948>

externdef __imp_olecli32_ordinal949:PPROC
olecli32_ordinal949 equ <__imp_olecli32_ordinal949>

externdef __imp_olecli32_ordinal94:PPROC
olecli32_ordinal94 equ <__imp_olecli32_ordinal94>

externdef __imp_olecli32_ordinal95:PPROC
olecli32_ordinal95 equ <__imp_olecli32_ordinal95>

externdef __imp_olecli32_ordinal96:PPROC
olecli32_ordinal96 equ <__imp_olecli32_ordinal96>

externdef __imp_olecli32_ordinal97:PPROC
olecli32_ordinal97 equ <__imp_olecli32_ordinal97>

externdef __imp_olecli32_ordinal98:PPROC
olecli32_ordinal98 equ <__imp_olecli32_ordinal98>

externdef __imp_olecli32_ordinal99:PPROC
olecli32_ordinal99 equ <__imp_olecli32_ordinal99>
