externdef __imp_OleUIAddVerbMenuA:PPROC
OleUIAddVerbMenuA equ <__imp_OleUIAddVerbMenuA>
  IFNDEF __UNICODE__
    OleUIAddVerbMenu equ <__imp_OleUIAddVerbMenuA>
  ENDIF

externdef __imp_OleUIAddVerbMenuW:PPROC
OleUIAddVerbMenuW equ <__imp_OleUIAddVerbMenuW>
  IFDEF __UNICODE__
    OleUIAddVerbMenu equ <__imp_OleUIAddVerbMenuW>
  ENDIF

externdef __imp_OleUIBusyA:PPROC
OleUIBusyA equ <__imp_OleUIBusyA>
  IFNDEF __UNICODE__
    OleUIBusy equ <__imp_OleUIBusyA>
  ENDIF

externdef __imp_OleUIBusyW:PPROC
OleUIBusyW equ <__imp_OleUIBusyW>
  IFDEF __UNICODE__
    OleUIBusy equ <__imp_OleUIBusyW>
  ENDIF

externdef __imp_OleUICanConvertOrActivateAs:PPROC
OleUICanConvertOrActivateAs equ <__imp_OleUICanConvertOrActivateAs>

externdef __imp_OleUIChangeIconA:PPROC
OleUIChangeIconA equ <__imp_OleUIChangeIconA>
  IFNDEF __UNICODE__
    OleUIChangeIcon equ <__imp_OleUIChangeIconA>
  ENDIF

externdef __imp_OleUIChangeIconW:PPROC
OleUIChangeIconW equ <__imp_OleUIChangeIconW>
  IFDEF __UNICODE__
    OleUIChangeIcon equ <__imp_OleUIChangeIconW>
  ENDIF

externdef __imp_OleUIChangeSourceA:PPROC
OleUIChangeSourceA equ <__imp_OleUIChangeSourceA>
  IFNDEF __UNICODE__
    OleUIChangeSource equ <__imp_OleUIChangeSourceA>
  ENDIF

externdef __imp_OleUIChangeSourceW:PPROC
OleUIChangeSourceW equ <__imp_OleUIChangeSourceW>
  IFDEF __UNICODE__
    OleUIChangeSource equ <__imp_OleUIChangeSourceW>
  ENDIF

externdef __imp_OleUIConvertA:PPROC
OleUIConvertA equ <__imp_OleUIConvertA>
  IFNDEF __UNICODE__
    OleUIConvert equ <__imp_OleUIConvertA>
  ENDIF

externdef __imp_OleUIConvertW:PPROC
OleUIConvertW equ <__imp_OleUIConvertW>
  IFDEF __UNICODE__
    OleUIConvert equ <__imp_OleUIConvertW>
  ENDIF

externdef __imp_OleUIEditLinksA:PPROC
OleUIEditLinksA equ <__imp_OleUIEditLinksA>
  IFNDEF __UNICODE__
    OleUIEditLinks equ <__imp_OleUIEditLinksA>
  ENDIF

externdef __imp_OleUIEditLinksW:PPROC
OleUIEditLinksW equ <__imp_OleUIEditLinksW>
  IFDEF __UNICODE__
    OleUIEditLinks equ <__imp_OleUIEditLinksW>
  ENDIF

externdef __imp_OleUIInsertObjectA:PPROC
OleUIInsertObjectA equ <__imp_OleUIInsertObjectA>
  IFNDEF __UNICODE__
    OleUIInsertObject equ <__imp_OleUIInsertObjectA>
  ENDIF

externdef __imp_OleUIInsertObjectW:PPROC
OleUIInsertObjectW equ <__imp_OleUIInsertObjectW>
  IFDEF __UNICODE__
    OleUIInsertObject equ <__imp_OleUIInsertObjectW>
  ENDIF

externdef __imp_OleUIObjectPropertiesA:PPROC
OleUIObjectPropertiesA equ <__imp_OleUIObjectPropertiesA>
  IFNDEF __UNICODE__
    OleUIObjectProperties equ <__imp_OleUIObjectPropertiesA>
  ENDIF

externdef __imp_OleUIObjectPropertiesW:PPROC
OleUIObjectPropertiesW equ <__imp_OleUIObjectPropertiesW>
  IFDEF __UNICODE__
    OleUIObjectProperties equ <__imp_OleUIObjectPropertiesW>
  ENDIF

externdef __imp_OleUIPasteSpecialA:PPROC
OleUIPasteSpecialA equ <__imp_OleUIPasteSpecialA>
  IFNDEF __UNICODE__
    OleUIPasteSpecial equ <__imp_OleUIPasteSpecialA>
  ENDIF

externdef __imp_OleUIPasteSpecialW:PPROC
OleUIPasteSpecialW equ <__imp_OleUIPasteSpecialW>
  IFDEF __UNICODE__
    OleUIPasteSpecial equ <__imp_OleUIPasteSpecialW>
  ENDIF

externdef __imp_OleUIPromptUserA:PPROC
OleUIPromptUserA equ <__imp_OleUIPromptUserA>
  IFNDEF __UNICODE__
    OleUIPromptUser equ <__imp_OleUIPromptUserA>
  ENDIF

externdef __imp_OleUIPromptUserW:PPROC
OleUIPromptUserW equ <__imp_OleUIPromptUserW>
  IFDEF __UNICODE__
    OleUIPromptUser equ <__imp_OleUIPromptUserW>
  ENDIF

externdef __imp_OleUIUpdateLinksA:PPROC
OleUIUpdateLinksA equ <__imp_OleUIUpdateLinksA>
  IFNDEF __UNICODE__
    OleUIUpdateLinks equ <__imp_OleUIUpdateLinksA>
  ENDIF

externdef __imp_OleUIUpdateLinksW:PPROC
OleUIUpdateLinksW equ <__imp_OleUIUpdateLinksW>
  IFDEF __UNICODE__
    OleUIUpdateLinks equ <__imp_OleUIUpdateLinksW>
  ENDIF
