externdef __imp_DeleteClientInfo:PPROC
DeleteClientInfo equ <__imp_DeleteClientInfo>

externdef __imp_DocWndProc:PPROC
DocWndProc equ <__imp_DocWndProc>

externdef __imp_EnumForTerminate:PPROC
EnumForTerminate equ <__imp_EnumForTerminate>

externdef __imp_FindItemWnd:PPROC
FindItemWnd equ <__imp_FindItemWnd>

externdef __imp_ItemCallBack:PPROC
ItemCallBack equ <__imp_ItemCallBack>

externdef __imp_ItemWndProc:PPROC
ItemWndProc equ <__imp_ItemWndProc>

externdef __imp_OleBlockServer:PPROC
OleBlockServer equ <__imp_OleBlockServer>

externdef __imp_OleQueryServerVersion:PPROC
OleQueryServerVersion equ <__imp_OleQueryServerVersion>

externdef __imp_OleRegisterServer:PPROC
OleRegisterServer equ <__imp_OleRegisterServer>

externdef __imp_OleRegisterServerDoc:PPROC
OleRegisterServerDoc equ <__imp_OleRegisterServerDoc>

externdef __imp_OleRenameServerDoc:PPROC
OleRenameServerDoc equ <__imp_OleRenameServerDoc>

externdef __imp_OleRevertServerDoc:PPROC
OleRevertServerDoc equ <__imp_OleRevertServerDoc>

externdef __imp_OleRevokeObject:PPROC
OleRevokeObject equ <__imp_OleRevokeObject>

externdef __imp_OleRevokeServer:PPROC
OleRevokeServer equ <__imp_OleRevokeServer>

externdef __imp_OleRevokeServerDoc:PPROC
OleRevokeServerDoc equ <__imp_OleRevokeServerDoc>

externdef __imp_OleSavedServerDoc:PPROC
OleSavedServerDoc equ <__imp_OleSavedServerDoc>

externdef __imp_OleUnblockServer:PPROC
OleUnblockServer equ <__imp_OleUnblockServer>

externdef __imp_SendDataMsg:PPROC
SendDataMsg equ <__imp_SendDataMsg>

externdef __imp_SendRenameMsg:PPROC
SendRenameMsg equ <__imp_SendRenameMsg>

externdef __imp_SrvrWndProc:PPROC
SrvrWndProc equ <__imp_SrvrWndProc>

externdef __imp_TerminateClients:PPROC
TerminateClients equ <__imp_TerminateClients>

externdef __imp_TerminateDocClients:PPROC
TerminateDocClients equ <__imp_TerminateDocClients>

externdef __imp_WEP:PPROC
WEP equ <__imp_WEP>

externdef __imp_olesvr32_ordinal13:PPROC
olesvr32_ordinal13 equ <__imp_olesvr32_ordinal13>

externdef __imp_olesvr32_ordinal14:PPROC
olesvr32_ordinal14 equ <__imp_olesvr32_ordinal14>

externdef __imp_olesvr32_ordinal15:PPROC
olesvr32_ordinal15 equ <__imp_olesvr32_ordinal15>

externdef __imp_olesvr32_ordinal16:PPROC
olesvr32_ordinal16 equ <__imp_olesvr32_ordinal16>

externdef __imp_olesvr32_ordinal17:PPROC
olesvr32_ordinal17 equ <__imp_olesvr32_ordinal17>

externdef __imp_olesvr32_ordinal18:PPROC
olesvr32_ordinal18 equ <__imp_olesvr32_ordinal18>

externdef __imp_olesvr32_ordinal19:PPROC
olesvr32_ordinal19 equ <__imp_olesvr32_ordinal19>

externdef __imp_olesvr32_ordinal20:PPROC
olesvr32_ordinal20 equ <__imp_olesvr32_ordinal20>
