externdef __imp_GlmfBeginGlsBlock:PPROC
GlmfBeginGlsBlock equ <__imp_GlmfBeginGlsBlock>

externdef __imp_GlmfCloseMetaFile:PPROC
GlmfCloseMetaFile equ <__imp_GlmfCloseMetaFile>

externdef __imp_GlmfEndGlsBlock:PPROC
GlmfEndGlsBlock equ <__imp_GlmfEndGlsBlock>

externdef __imp_GlmfEndPlayback:PPROC
GlmfEndPlayback equ <__imp_GlmfEndPlayback>

externdef __imp_GlmfInitPlayback:PPROC
GlmfInitPlayback equ <__imp_GlmfInitPlayback>

externdef __imp_GlmfPlayGlsRecord:PPROC
GlmfPlayGlsRecord equ <__imp_GlmfPlayGlsRecord>

externdef __imp_glAccum:PPROC
glAccum equ <__imp_glAccum>

externdef __imp_glAlphaFunc:PPROC
glAlphaFunc equ <__imp_glAlphaFunc>

externdef __imp_glAreTexturesResident:PPROC
glAreTexturesResident equ <__imp_glAreTexturesResident>

externdef __imp_glArrayElement:PPROC
glArrayElement equ <__imp_glArrayElement>

externdef __imp_glBegin:PPROC
glBegin equ <__imp_glBegin>

externdef __imp_glBindTexture:PPROC
glBindTexture equ <__imp_glBindTexture>

externdef __imp_glBitmap:PPROC
glBitmap equ <__imp_glBitmap>

externdef __imp_glBlendFunc:PPROC
glBlendFunc equ <__imp_glBlendFunc>

externdef __imp_glCallList:PPROC
glCallList equ <__imp_glCallList>

externdef __imp_glCallLists:PPROC
glCallLists equ <__imp_glCallLists>

externdef __imp_glClear:PPROC
glClear equ <__imp_glClear>

externdef __imp_glClearAccum:PPROC
glClearAccum equ <__imp_glClearAccum>

externdef __imp_glClearColor:PPROC
glClearColor equ <__imp_glClearColor>

externdef __imp_glClearDepth:PPROC
glClearDepth equ <__imp_glClearDepth>

externdef __imp_glClearIndex:PPROC
glClearIndex equ <__imp_glClearIndex>

externdef __imp_glClearStencil:PPROC
glClearStencil equ <__imp_glClearStencil>

externdef __imp_glClipPlane:PPROC
glClipPlane equ <__imp_glClipPlane>

externdef __imp_glColor3b:PPROC
glColor3b equ <__imp_glColor3b>

externdef __imp_glColor3bv:PPROC
glColor3bv equ <__imp_glColor3bv>

externdef __imp_glColor3d:PPROC
glColor3d equ <__imp_glColor3d>

externdef __imp_glColor3dv:PPROC
glColor3dv equ <__imp_glColor3dv>

externdef __imp_glColor3f:PPROC
glColor3f equ <__imp_glColor3f>

externdef __imp_glColor3fv:PPROC
glColor3fv equ <__imp_glColor3fv>

externdef __imp_glColor3i:PPROC
glColor3i equ <__imp_glColor3i>

externdef __imp_glColor3iv:PPROC
glColor3iv equ <__imp_glColor3iv>

externdef __imp_glColor3s:PPROC
glColor3s equ <__imp_glColor3s>

externdef __imp_glColor3sv:PPROC
glColor3sv equ <__imp_glColor3sv>

externdef __imp_glColor3ub:PPROC
glColor3ub equ <__imp_glColor3ub>

externdef __imp_glColor3ubv:PPROC
glColor3ubv equ <__imp_glColor3ubv>

externdef __imp_glColor3ui:PPROC
glColor3ui equ <__imp_glColor3ui>

externdef __imp_glColor3uiv:PPROC
glColor3uiv equ <__imp_glColor3uiv>

externdef __imp_glColor3us:PPROC
glColor3us equ <__imp_glColor3us>

externdef __imp_glColor3usv:PPROC
glColor3usv equ <__imp_glColor3usv>

externdef __imp_glColor4b:PPROC
glColor4b equ <__imp_glColor4b>

externdef __imp_glColor4bv:PPROC
glColor4bv equ <__imp_glColor4bv>

externdef __imp_glColor4d:PPROC
glColor4d equ <__imp_glColor4d>

externdef __imp_glColor4dv:PPROC
glColor4dv equ <__imp_glColor4dv>

externdef __imp_glColor4f:PPROC
glColor4f equ <__imp_glColor4f>

externdef __imp_glColor4fv:PPROC
glColor4fv equ <__imp_glColor4fv>

externdef __imp_glColor4i:PPROC
glColor4i equ <__imp_glColor4i>

externdef __imp_glColor4iv:PPROC
glColor4iv equ <__imp_glColor4iv>

externdef __imp_glColor4s:PPROC
glColor4s equ <__imp_glColor4s>

externdef __imp_glColor4sv:PPROC
glColor4sv equ <__imp_glColor4sv>

externdef __imp_glColor4ub:PPROC
glColor4ub equ <__imp_glColor4ub>

externdef __imp_glColor4ubv:PPROC
glColor4ubv equ <__imp_glColor4ubv>

externdef __imp_glColor4ui:PPROC
glColor4ui equ <__imp_glColor4ui>

externdef __imp_glColor4uiv:PPROC
glColor4uiv equ <__imp_glColor4uiv>

externdef __imp_glColor4us:PPROC
glColor4us equ <__imp_glColor4us>

externdef __imp_glColor4usv:PPROC
glColor4usv equ <__imp_glColor4usv>

externdef __imp_glColorMask:PPROC
glColorMask equ <__imp_glColorMask>

externdef __imp_glColorMaterial:PPROC
glColorMaterial equ <__imp_glColorMaterial>

externdef __imp_glColorPointer:PPROC
glColorPointer equ <__imp_glColorPointer>

externdef __imp_glCopyPixels:PPROC
glCopyPixels equ <__imp_glCopyPixels>

externdef __imp_glCopyTexImage1D:PPROC
glCopyTexImage1D equ <__imp_glCopyTexImage1D>

externdef __imp_glCopyTexImage2D:PPROC
glCopyTexImage2D equ <__imp_glCopyTexImage2D>

externdef __imp_glCopyTexSubImage1D:PPROC
glCopyTexSubImage1D equ <__imp_glCopyTexSubImage1D>

externdef __imp_glCopyTexSubImage2D:PPROC
glCopyTexSubImage2D equ <__imp_glCopyTexSubImage2D>

externdef __imp_glCullFace:PPROC
glCullFace equ <__imp_glCullFace>

externdef __imp_glDebugEntry:PPROC
glDebugEntry equ <__imp_glDebugEntry>

externdef __imp_glDeleteLists:PPROC
glDeleteLists equ <__imp_glDeleteLists>

externdef __imp_glDeleteTextures:PPROC
glDeleteTextures equ <__imp_glDeleteTextures>

externdef __imp_glDepthFunc:PPROC
glDepthFunc equ <__imp_glDepthFunc>

externdef __imp_glDepthMask:PPROC
glDepthMask equ <__imp_glDepthMask>

externdef __imp_glDepthRange:PPROC
glDepthRange equ <__imp_glDepthRange>

externdef __imp_glDisable:PPROC
glDisable equ <__imp_glDisable>

externdef __imp_glDisableClientState:PPROC
glDisableClientState equ <__imp_glDisableClientState>

externdef __imp_glDrawArrays:PPROC
glDrawArrays equ <__imp_glDrawArrays>

externdef __imp_glDrawBuffer:PPROC
glDrawBuffer equ <__imp_glDrawBuffer>

externdef __imp_glDrawElements:PPROC
glDrawElements equ <__imp_glDrawElements>

externdef __imp_glDrawPixels:PPROC
glDrawPixels equ <__imp_glDrawPixels>

externdef __imp_glEdgeFlag:PPROC
glEdgeFlag equ <__imp_glEdgeFlag>

externdef __imp_glEdgeFlagPointer:PPROC
glEdgeFlagPointer equ <__imp_glEdgeFlagPointer>

externdef __imp_glEdgeFlagv:PPROC
glEdgeFlagv equ <__imp_glEdgeFlagv>

externdef __imp_glEnable:PPROC
glEnable equ <__imp_glEnable>

externdef __imp_glEnableClientState:PPROC
glEnableClientState equ <__imp_glEnableClientState>

externdef __imp_glEnd:PPROC
glEnd equ <__imp_glEnd>

externdef __imp_glEndList:PPROC
glEndList equ <__imp_glEndList>

externdef __imp_glEvalCoord1d:PPROC
glEvalCoord1d equ <__imp_glEvalCoord1d>

externdef __imp_glEvalCoord1dv:PPROC
glEvalCoord1dv equ <__imp_glEvalCoord1dv>

externdef __imp_glEvalCoord1f:PPROC
glEvalCoord1f equ <__imp_glEvalCoord1f>

externdef __imp_glEvalCoord1fv:PPROC
glEvalCoord1fv equ <__imp_glEvalCoord1fv>

externdef __imp_glEvalCoord2d:PPROC
glEvalCoord2d equ <__imp_glEvalCoord2d>

externdef __imp_glEvalCoord2dv:PPROC
glEvalCoord2dv equ <__imp_glEvalCoord2dv>

externdef __imp_glEvalCoord2f:PPROC
glEvalCoord2f equ <__imp_glEvalCoord2f>

externdef __imp_glEvalCoord2fv:PPROC
glEvalCoord2fv equ <__imp_glEvalCoord2fv>

externdef __imp_glEvalMesh1:PPROC
glEvalMesh1 equ <__imp_glEvalMesh1>

externdef __imp_glEvalMesh2:PPROC
glEvalMesh2 equ <__imp_glEvalMesh2>

externdef __imp_glEvalPoint1:PPROC
glEvalPoint1 equ <__imp_glEvalPoint1>

externdef __imp_glEvalPoint2:PPROC
glEvalPoint2 equ <__imp_glEvalPoint2>

externdef __imp_glFeedbackBuffer:PPROC
glFeedbackBuffer equ <__imp_glFeedbackBuffer>

externdef __imp_glFinish:PPROC
glFinish equ <__imp_glFinish>

externdef __imp_glFlush:PPROC
glFlush equ <__imp_glFlush>

externdef __imp_glFogf:PPROC
glFogf equ <__imp_glFogf>

externdef __imp_glFogfv:PPROC
glFogfv equ <__imp_glFogfv>

externdef __imp_glFogi:PPROC
glFogi equ <__imp_glFogi>

externdef __imp_glFogiv:PPROC
glFogiv equ <__imp_glFogiv>

externdef __imp_glFrontFace:PPROC
glFrontFace equ <__imp_glFrontFace>

externdef __imp_glFrustum:PPROC
glFrustum equ <__imp_glFrustum>

externdef __imp_glGenLists:PPROC
glGenLists equ <__imp_glGenLists>

externdef __imp_glGenTextures:PPROC
glGenTextures equ <__imp_glGenTextures>

externdef __imp_glGetBooleanv:PPROC
glGetBooleanv equ <__imp_glGetBooleanv>

externdef __imp_glGetClipPlane:PPROC
glGetClipPlane equ <__imp_glGetClipPlane>

externdef __imp_glGetDoublev:PPROC
glGetDoublev equ <__imp_glGetDoublev>

externdef __imp_glGetError:PPROC
glGetError equ <__imp_glGetError>

externdef __imp_glGetFloatv:PPROC
glGetFloatv equ <__imp_glGetFloatv>

externdef __imp_glGetIntegerv:PPROC
glGetIntegerv equ <__imp_glGetIntegerv>

externdef __imp_glGetLightfv:PPROC
glGetLightfv equ <__imp_glGetLightfv>

externdef __imp_glGetLightiv:PPROC
glGetLightiv equ <__imp_glGetLightiv>

externdef __imp_glGetMapdv:PPROC
glGetMapdv equ <__imp_glGetMapdv>

externdef __imp_glGetMapfv:PPROC
glGetMapfv equ <__imp_glGetMapfv>

externdef __imp_glGetMapiv:PPROC
glGetMapiv equ <__imp_glGetMapiv>

externdef __imp_glGetMaterialfv:PPROC
glGetMaterialfv equ <__imp_glGetMaterialfv>

externdef __imp_glGetMaterialiv:PPROC
glGetMaterialiv equ <__imp_glGetMaterialiv>

externdef __imp_glGetPixelMapfv:PPROC
glGetPixelMapfv equ <__imp_glGetPixelMapfv>

externdef __imp_glGetPixelMapuiv:PPROC
glGetPixelMapuiv equ <__imp_glGetPixelMapuiv>

externdef __imp_glGetPixelMapusv:PPROC
glGetPixelMapusv equ <__imp_glGetPixelMapusv>

externdef __imp_glGetPointerv:PPROC
glGetPointerv equ <__imp_glGetPointerv>

externdef __imp_glGetPolygonStipple:PPROC
glGetPolygonStipple equ <__imp_glGetPolygonStipple>

externdef __imp_glGetString:PPROC
glGetString equ <__imp_glGetString>

externdef __imp_glGetTexEnvfv:PPROC
glGetTexEnvfv equ <__imp_glGetTexEnvfv>

externdef __imp_glGetTexEnviv:PPROC
glGetTexEnviv equ <__imp_glGetTexEnviv>

externdef __imp_glGetTexGendv:PPROC
glGetTexGendv equ <__imp_glGetTexGendv>

externdef __imp_glGetTexGenfv:PPROC
glGetTexGenfv equ <__imp_glGetTexGenfv>

externdef __imp_glGetTexGeniv:PPROC
glGetTexGeniv equ <__imp_glGetTexGeniv>

externdef __imp_glGetTexImage:PPROC
glGetTexImage equ <__imp_glGetTexImage>

externdef __imp_glGetTexLevelParameterfv:PPROC
glGetTexLevelParameterfv equ <__imp_glGetTexLevelParameterfv>

externdef __imp_glGetTexLevelParameteriv:PPROC
glGetTexLevelParameteriv equ <__imp_glGetTexLevelParameteriv>

externdef __imp_glGetTexParameterfv:PPROC
glGetTexParameterfv equ <__imp_glGetTexParameterfv>

externdef __imp_glGetTexParameteriv:PPROC
glGetTexParameteriv equ <__imp_glGetTexParameteriv>

externdef __imp_glHint:PPROC
glHint equ <__imp_glHint>

externdef __imp_glIndexMask:PPROC
glIndexMask equ <__imp_glIndexMask>

externdef __imp_glIndexPointer:PPROC
glIndexPointer equ <__imp_glIndexPointer>

externdef __imp_glIndexd:PPROC
glIndexd equ <__imp_glIndexd>

externdef __imp_glIndexdv:PPROC
glIndexdv equ <__imp_glIndexdv>

externdef __imp_glIndexf:PPROC
glIndexf equ <__imp_glIndexf>

externdef __imp_glIndexfv:PPROC
glIndexfv equ <__imp_glIndexfv>

externdef __imp_glIndexi:PPROC
glIndexi equ <__imp_glIndexi>

externdef __imp_glIndexiv:PPROC
glIndexiv equ <__imp_glIndexiv>

externdef __imp_glIndexs:PPROC
glIndexs equ <__imp_glIndexs>

externdef __imp_glIndexsv:PPROC
glIndexsv equ <__imp_glIndexsv>

externdef __imp_glIndexub:PPROC
glIndexub equ <__imp_glIndexub>

externdef __imp_glIndexubv:PPROC
glIndexubv equ <__imp_glIndexubv>

externdef __imp_glInitNames:PPROC
glInitNames equ <__imp_glInitNames>

externdef __imp_glInterleavedArrays:PPROC
glInterleavedArrays equ <__imp_glInterleavedArrays>

externdef __imp_glIsEnabled:PPROC
glIsEnabled equ <__imp_glIsEnabled>

externdef __imp_glIsList:PPROC
glIsList equ <__imp_glIsList>

externdef __imp_glIsTexture:PPROC
glIsTexture equ <__imp_glIsTexture>

externdef __imp_glLightModelf:PPROC
glLightModelf equ <__imp_glLightModelf>

externdef __imp_glLightModelfv:PPROC
glLightModelfv equ <__imp_glLightModelfv>

externdef __imp_glLightModeli:PPROC
glLightModeli equ <__imp_glLightModeli>

externdef __imp_glLightModeliv:PPROC
glLightModeliv equ <__imp_glLightModeliv>

externdef __imp_glLightf:PPROC
glLightf equ <__imp_glLightf>

externdef __imp_glLightfv:PPROC
glLightfv equ <__imp_glLightfv>

externdef __imp_glLighti:PPROC
glLighti equ <__imp_glLighti>

externdef __imp_glLightiv:PPROC
glLightiv equ <__imp_glLightiv>

externdef __imp_glLineStipple:PPROC
glLineStipple equ <__imp_glLineStipple>

externdef __imp_glLineWidth:PPROC
glLineWidth equ <__imp_glLineWidth>

externdef __imp_glListBase:PPROC
glListBase equ <__imp_glListBase>

externdef __imp_glLoadIdentity:PPROC
glLoadIdentity equ <__imp_glLoadIdentity>

externdef __imp_glLoadMatrixd:PPROC
glLoadMatrixd equ <__imp_glLoadMatrixd>

externdef __imp_glLoadMatrixf:PPROC
glLoadMatrixf equ <__imp_glLoadMatrixf>

externdef __imp_glLoadName:PPROC
glLoadName equ <__imp_glLoadName>

externdef __imp_glLogicOp:PPROC
glLogicOp equ <__imp_glLogicOp>

externdef __imp_glMap1d:PPROC
glMap1d equ <__imp_glMap1d>

externdef __imp_glMap1f:PPROC
glMap1f equ <__imp_glMap1f>

externdef __imp_glMap2d:PPROC
glMap2d equ <__imp_glMap2d>

externdef __imp_glMap2f:PPROC
glMap2f equ <__imp_glMap2f>

externdef __imp_glMapGrid1d:PPROC
glMapGrid1d equ <__imp_glMapGrid1d>

externdef __imp_glMapGrid1f:PPROC
glMapGrid1f equ <__imp_glMapGrid1f>

externdef __imp_glMapGrid2d:PPROC
glMapGrid2d equ <__imp_glMapGrid2d>

externdef __imp_glMapGrid2f:PPROC
glMapGrid2f equ <__imp_glMapGrid2f>

externdef __imp_glMaterialf:PPROC
glMaterialf equ <__imp_glMaterialf>

externdef __imp_glMaterialfv:PPROC
glMaterialfv equ <__imp_glMaterialfv>

externdef __imp_glMateriali:PPROC
glMateriali equ <__imp_glMateriali>

externdef __imp_glMaterialiv:PPROC
glMaterialiv equ <__imp_glMaterialiv>

externdef __imp_glMatrixMode:PPROC
glMatrixMode equ <__imp_glMatrixMode>

externdef __imp_glMultMatrixd:PPROC
glMultMatrixd equ <__imp_glMultMatrixd>

externdef __imp_glMultMatrixf:PPROC
glMultMatrixf equ <__imp_glMultMatrixf>

externdef __imp_glNewList:PPROC
glNewList equ <__imp_glNewList>

externdef __imp_glNormal3b:PPROC
glNormal3b equ <__imp_glNormal3b>

externdef __imp_glNormal3bv:PPROC
glNormal3bv equ <__imp_glNormal3bv>

externdef __imp_glNormal3d:PPROC
glNormal3d equ <__imp_glNormal3d>

externdef __imp_glNormal3dv:PPROC
glNormal3dv equ <__imp_glNormal3dv>

externdef __imp_glNormal3f:PPROC
glNormal3f equ <__imp_glNormal3f>

externdef __imp_glNormal3fv:PPROC
glNormal3fv equ <__imp_glNormal3fv>

externdef __imp_glNormal3i:PPROC
glNormal3i equ <__imp_glNormal3i>

externdef __imp_glNormal3iv:PPROC
glNormal3iv equ <__imp_glNormal3iv>

externdef __imp_glNormal3s:PPROC
glNormal3s equ <__imp_glNormal3s>

externdef __imp_glNormal3sv:PPROC
glNormal3sv equ <__imp_glNormal3sv>

externdef __imp_glNormalPointer:PPROC
glNormalPointer equ <__imp_glNormalPointer>

externdef __imp_glOrtho:PPROC
glOrtho equ <__imp_glOrtho>

externdef __imp_glPassThrough:PPROC
glPassThrough equ <__imp_glPassThrough>

externdef __imp_glPixelMapfv:PPROC
glPixelMapfv equ <__imp_glPixelMapfv>

externdef __imp_glPixelMapuiv:PPROC
glPixelMapuiv equ <__imp_glPixelMapuiv>

externdef __imp_glPixelMapusv:PPROC
glPixelMapusv equ <__imp_glPixelMapusv>

externdef __imp_glPixelStoref:PPROC
glPixelStoref equ <__imp_glPixelStoref>

externdef __imp_glPixelStorei:PPROC
glPixelStorei equ <__imp_glPixelStorei>

externdef __imp_glPixelTransferf:PPROC
glPixelTransferf equ <__imp_glPixelTransferf>

externdef __imp_glPixelTransferi:PPROC
glPixelTransferi equ <__imp_glPixelTransferi>

externdef __imp_glPixelZoom:PPROC
glPixelZoom equ <__imp_glPixelZoom>

externdef __imp_glPointSize:PPROC
glPointSize equ <__imp_glPointSize>

externdef __imp_glPolygonMode:PPROC
glPolygonMode equ <__imp_glPolygonMode>

externdef __imp_glPolygonOffset:PPROC
glPolygonOffset equ <__imp_glPolygonOffset>

externdef __imp_glPolygonStipple:PPROC
glPolygonStipple equ <__imp_glPolygonStipple>

externdef __imp_glPopAttrib:PPROC
glPopAttrib equ <__imp_glPopAttrib>

externdef __imp_glPopClientAttrib:PPROC
glPopClientAttrib equ <__imp_glPopClientAttrib>

externdef __imp_glPopMatrix:PPROC
glPopMatrix equ <__imp_glPopMatrix>

externdef __imp_glPopName:PPROC
glPopName equ <__imp_glPopName>

externdef __imp_glPrioritizeTextures:PPROC
glPrioritizeTextures equ <__imp_glPrioritizeTextures>

externdef __imp_glPushAttrib:PPROC
glPushAttrib equ <__imp_glPushAttrib>

externdef __imp_glPushClientAttrib:PPROC
glPushClientAttrib equ <__imp_glPushClientAttrib>

externdef __imp_glPushMatrix:PPROC
glPushMatrix equ <__imp_glPushMatrix>

externdef __imp_glPushName:PPROC
glPushName equ <__imp_glPushName>

externdef __imp_glRasterPos2d:PPROC
glRasterPos2d equ <__imp_glRasterPos2d>

externdef __imp_glRasterPos2dv:PPROC
glRasterPos2dv equ <__imp_glRasterPos2dv>

externdef __imp_glRasterPos2f:PPROC
glRasterPos2f equ <__imp_glRasterPos2f>

externdef __imp_glRasterPos2fv:PPROC
glRasterPos2fv equ <__imp_glRasterPos2fv>

externdef __imp_glRasterPos2i:PPROC
glRasterPos2i equ <__imp_glRasterPos2i>

externdef __imp_glRasterPos2iv:PPROC
glRasterPos2iv equ <__imp_glRasterPos2iv>

externdef __imp_glRasterPos2s:PPROC
glRasterPos2s equ <__imp_glRasterPos2s>

externdef __imp_glRasterPos2sv:PPROC
glRasterPos2sv equ <__imp_glRasterPos2sv>

externdef __imp_glRasterPos3d:PPROC
glRasterPos3d equ <__imp_glRasterPos3d>

externdef __imp_glRasterPos3dv:PPROC
glRasterPos3dv equ <__imp_glRasterPos3dv>

externdef __imp_glRasterPos3f:PPROC
glRasterPos3f equ <__imp_glRasterPos3f>

externdef __imp_glRasterPos3fv:PPROC
glRasterPos3fv equ <__imp_glRasterPos3fv>

externdef __imp_glRasterPos3i:PPROC
glRasterPos3i equ <__imp_glRasterPos3i>

externdef __imp_glRasterPos3iv:PPROC
glRasterPos3iv equ <__imp_glRasterPos3iv>

externdef __imp_glRasterPos3s:PPROC
glRasterPos3s equ <__imp_glRasterPos3s>

externdef __imp_glRasterPos3sv:PPROC
glRasterPos3sv equ <__imp_glRasterPos3sv>

externdef __imp_glRasterPos4d:PPROC
glRasterPos4d equ <__imp_glRasterPos4d>

externdef __imp_glRasterPos4dv:PPROC
glRasterPos4dv equ <__imp_glRasterPos4dv>

externdef __imp_glRasterPos4f:PPROC
glRasterPos4f equ <__imp_glRasterPos4f>

externdef __imp_glRasterPos4fv:PPROC
glRasterPos4fv equ <__imp_glRasterPos4fv>

externdef __imp_glRasterPos4i:PPROC
glRasterPos4i equ <__imp_glRasterPos4i>

externdef __imp_glRasterPos4iv:PPROC
glRasterPos4iv equ <__imp_glRasterPos4iv>

externdef __imp_glRasterPos4s:PPROC
glRasterPos4s equ <__imp_glRasterPos4s>

externdef __imp_glRasterPos4sv:PPROC
glRasterPos4sv equ <__imp_glRasterPos4sv>

externdef __imp_glReadBuffer:PPROC
glReadBuffer equ <__imp_glReadBuffer>

externdef __imp_glReadPixels:PPROC
glReadPixels equ <__imp_glReadPixels>

externdef __imp_glRectd:PPROC
glRectd equ <__imp_glRectd>

externdef __imp_glRectdv:PPROC
glRectdv equ <__imp_glRectdv>

externdef __imp_glRectf:PPROC
glRectf equ <__imp_glRectf>

externdef __imp_glRectfv:PPROC
glRectfv equ <__imp_glRectfv>

externdef __imp_glRecti:PPROC
glRecti equ <__imp_glRecti>

externdef __imp_glRectiv:PPROC
glRectiv equ <__imp_glRectiv>

externdef __imp_glRects:PPROC
glRects equ <__imp_glRects>

externdef __imp_glRectsv:PPROC
glRectsv equ <__imp_glRectsv>

externdef __imp_glRenderMode:PPROC
glRenderMode equ <__imp_glRenderMode>

externdef __imp_glRotated:PPROC
glRotated equ <__imp_glRotated>

externdef __imp_glRotatef:PPROC
glRotatef equ <__imp_glRotatef>

externdef __imp_glScaled:PPROC
glScaled equ <__imp_glScaled>

externdef __imp_glScalef:PPROC
glScalef equ <__imp_glScalef>

externdef __imp_glScissor:PPROC
glScissor equ <__imp_glScissor>

externdef __imp_glSelectBuffer:PPROC
glSelectBuffer equ <__imp_glSelectBuffer>

externdef __imp_glShadeModel:PPROC
glShadeModel equ <__imp_glShadeModel>

externdef __imp_glStencilFunc:PPROC
glStencilFunc equ <__imp_glStencilFunc>

externdef __imp_glStencilMask:PPROC
glStencilMask equ <__imp_glStencilMask>

externdef __imp_glStencilOp:PPROC
glStencilOp equ <__imp_glStencilOp>

externdef __imp_glTexCoord1d:PPROC
glTexCoord1d equ <__imp_glTexCoord1d>

externdef __imp_glTexCoord1dv:PPROC
glTexCoord1dv equ <__imp_glTexCoord1dv>

externdef __imp_glTexCoord1f:PPROC
glTexCoord1f equ <__imp_glTexCoord1f>

externdef __imp_glTexCoord1fv:PPROC
glTexCoord1fv equ <__imp_glTexCoord1fv>

externdef __imp_glTexCoord1i:PPROC
glTexCoord1i equ <__imp_glTexCoord1i>

externdef __imp_glTexCoord1iv:PPROC
glTexCoord1iv equ <__imp_glTexCoord1iv>

externdef __imp_glTexCoord1s:PPROC
glTexCoord1s equ <__imp_glTexCoord1s>

externdef __imp_glTexCoord1sv:PPROC
glTexCoord1sv equ <__imp_glTexCoord1sv>

externdef __imp_glTexCoord2d:PPROC
glTexCoord2d equ <__imp_glTexCoord2d>

externdef __imp_glTexCoord2dv:PPROC
glTexCoord2dv equ <__imp_glTexCoord2dv>

externdef __imp_glTexCoord2f:PPROC
glTexCoord2f equ <__imp_glTexCoord2f>

externdef __imp_glTexCoord2fv:PPROC
glTexCoord2fv equ <__imp_glTexCoord2fv>

externdef __imp_glTexCoord2i:PPROC
glTexCoord2i equ <__imp_glTexCoord2i>

externdef __imp_glTexCoord2iv:PPROC
glTexCoord2iv equ <__imp_glTexCoord2iv>

externdef __imp_glTexCoord2s:PPROC
glTexCoord2s equ <__imp_glTexCoord2s>

externdef __imp_glTexCoord2sv:PPROC
glTexCoord2sv equ <__imp_glTexCoord2sv>

externdef __imp_glTexCoord3d:PPROC
glTexCoord3d equ <__imp_glTexCoord3d>

externdef __imp_glTexCoord3dv:PPROC
glTexCoord3dv equ <__imp_glTexCoord3dv>

externdef __imp_glTexCoord3f:PPROC
glTexCoord3f equ <__imp_glTexCoord3f>

externdef __imp_glTexCoord3fv:PPROC
glTexCoord3fv equ <__imp_glTexCoord3fv>

externdef __imp_glTexCoord3i:PPROC
glTexCoord3i equ <__imp_glTexCoord3i>

externdef __imp_glTexCoord3iv:PPROC
glTexCoord3iv equ <__imp_glTexCoord3iv>

externdef __imp_glTexCoord3s:PPROC
glTexCoord3s equ <__imp_glTexCoord3s>

externdef __imp_glTexCoord3sv:PPROC
glTexCoord3sv equ <__imp_glTexCoord3sv>

externdef __imp_glTexCoord4d:PPROC
glTexCoord4d equ <__imp_glTexCoord4d>

externdef __imp_glTexCoord4dv:PPROC
glTexCoord4dv equ <__imp_glTexCoord4dv>

externdef __imp_glTexCoord4f:PPROC
glTexCoord4f equ <__imp_glTexCoord4f>

externdef __imp_glTexCoord4fv:PPROC
glTexCoord4fv equ <__imp_glTexCoord4fv>

externdef __imp_glTexCoord4i:PPROC
glTexCoord4i equ <__imp_glTexCoord4i>

externdef __imp_glTexCoord4iv:PPROC
glTexCoord4iv equ <__imp_glTexCoord4iv>

externdef __imp_glTexCoord4s:PPROC
glTexCoord4s equ <__imp_glTexCoord4s>

externdef __imp_glTexCoord4sv:PPROC
glTexCoord4sv equ <__imp_glTexCoord4sv>

externdef __imp_glTexCoordPointer:PPROC
glTexCoordPointer equ <__imp_glTexCoordPointer>

externdef __imp_glTexEnvf:PPROC
glTexEnvf equ <__imp_glTexEnvf>

externdef __imp_glTexEnvfv:PPROC
glTexEnvfv equ <__imp_glTexEnvfv>

externdef __imp_glTexEnvi:PPROC
glTexEnvi equ <__imp_glTexEnvi>

externdef __imp_glTexEnviv:PPROC
glTexEnviv equ <__imp_glTexEnviv>

externdef __imp_glTexGend:PPROC
glTexGend equ <__imp_glTexGend>

externdef __imp_glTexGendv:PPROC
glTexGendv equ <__imp_glTexGendv>

externdef __imp_glTexGenf:PPROC
glTexGenf equ <__imp_glTexGenf>

externdef __imp_glTexGenfv:PPROC
glTexGenfv equ <__imp_glTexGenfv>

externdef __imp_glTexGeni:PPROC
glTexGeni equ <__imp_glTexGeni>

externdef __imp_glTexGeniv:PPROC
glTexGeniv equ <__imp_glTexGeniv>

externdef __imp_glTexImage1D:PPROC
glTexImage1D equ <__imp_glTexImage1D>

externdef __imp_glTexImage2D:PPROC
glTexImage2D equ <__imp_glTexImage2D>

externdef __imp_glTexParameterf:PPROC
glTexParameterf equ <__imp_glTexParameterf>

externdef __imp_glTexParameterfv:PPROC
glTexParameterfv equ <__imp_glTexParameterfv>

externdef __imp_glTexParameteri:PPROC
glTexParameteri equ <__imp_glTexParameteri>

externdef __imp_glTexParameteriv:PPROC
glTexParameteriv equ <__imp_glTexParameteriv>

externdef __imp_glTexSubImage1D:PPROC
glTexSubImage1D equ <__imp_glTexSubImage1D>

externdef __imp_glTexSubImage2D:PPROC
glTexSubImage2D equ <__imp_glTexSubImage2D>

externdef __imp_glTranslated:PPROC
glTranslated equ <__imp_glTranslated>

externdef __imp_glTranslatef:PPROC
glTranslatef equ <__imp_glTranslatef>

externdef __imp_glVertex2d:PPROC
glVertex2d equ <__imp_glVertex2d>

externdef __imp_glVertex2dv:PPROC
glVertex2dv equ <__imp_glVertex2dv>

externdef __imp_glVertex2f:PPROC
glVertex2f equ <__imp_glVertex2f>

externdef __imp_glVertex2fv:PPROC
glVertex2fv equ <__imp_glVertex2fv>

externdef __imp_glVertex2i:PPROC
glVertex2i equ <__imp_glVertex2i>

externdef __imp_glVertex2iv:PPROC
glVertex2iv equ <__imp_glVertex2iv>

externdef __imp_glVertex2s:PPROC
glVertex2s equ <__imp_glVertex2s>

externdef __imp_glVertex2sv:PPROC
glVertex2sv equ <__imp_glVertex2sv>

externdef __imp_glVertex3d:PPROC
glVertex3d equ <__imp_glVertex3d>

externdef __imp_glVertex3dv:PPROC
glVertex3dv equ <__imp_glVertex3dv>

externdef __imp_glVertex3f:PPROC
glVertex3f equ <__imp_glVertex3f>

externdef __imp_glVertex3fv:PPROC
glVertex3fv equ <__imp_glVertex3fv>

externdef __imp_glVertex3i:PPROC
glVertex3i equ <__imp_glVertex3i>

externdef __imp_glVertex3iv:PPROC
glVertex3iv equ <__imp_glVertex3iv>

externdef __imp_glVertex3s:PPROC
glVertex3s equ <__imp_glVertex3s>

externdef __imp_glVertex3sv:PPROC
glVertex3sv equ <__imp_glVertex3sv>

externdef __imp_glVertex4d:PPROC
glVertex4d equ <__imp_glVertex4d>

externdef __imp_glVertex4dv:PPROC
glVertex4dv equ <__imp_glVertex4dv>

externdef __imp_glVertex4f:PPROC
glVertex4f equ <__imp_glVertex4f>

externdef __imp_glVertex4fv:PPROC
glVertex4fv equ <__imp_glVertex4fv>

externdef __imp_glVertex4i:PPROC
glVertex4i equ <__imp_glVertex4i>

externdef __imp_glVertex4iv:PPROC
glVertex4iv equ <__imp_glVertex4iv>

externdef __imp_glVertex4s:PPROC
glVertex4s equ <__imp_glVertex4s>

externdef __imp_glVertex4sv:PPROC
glVertex4sv equ <__imp_glVertex4sv>

externdef __imp_glVertexPointer:PPROC
glVertexPointer equ <__imp_glVertexPointer>

externdef __imp_glViewport:PPROC
glViewport equ <__imp_glViewport>

externdef __imp_wglChoosePixelFormat:PPROC
wglChoosePixelFormat equ <__imp_wglChoosePixelFormat>

externdef __imp_wglCopyContext:PPROC
wglCopyContext equ <__imp_wglCopyContext>

externdef __imp_wglCreateContext:PPROC
wglCreateContext equ <__imp_wglCreateContext>

externdef __imp_wglCreateLayerContext:PPROC
wglCreateLayerContext equ <__imp_wglCreateLayerContext>

externdef __imp_wglDeleteContext:PPROC
wglDeleteContext equ <__imp_wglDeleteContext>

externdef __imp_wglDescribeLayerPlane:PPROC
wglDescribeLayerPlane equ <__imp_wglDescribeLayerPlane>

externdef __imp_wglDescribePixelFormat:PPROC
wglDescribePixelFormat equ <__imp_wglDescribePixelFormat>

externdef __imp_wglGetCurrentContext:PPROC
wglGetCurrentContext equ <__imp_wglGetCurrentContext>

externdef __imp_wglGetCurrentDC:PPROC
wglGetCurrentDC equ <__imp_wglGetCurrentDC>

externdef __imp_wglGetDefaultProcAddress:PPROC
wglGetDefaultProcAddress equ <__imp_wglGetDefaultProcAddress>

externdef __imp_wglGetLayerPaletteEntries:PPROC
wglGetLayerPaletteEntries equ <__imp_wglGetLayerPaletteEntries>

externdef __imp_wglGetPixelFormat:PPROC
wglGetPixelFormat equ <__imp_wglGetPixelFormat>

externdef __imp_wglGetProcAddress:PPROC
wglGetProcAddress equ <__imp_wglGetProcAddress>

externdef __imp_wglMakeCurrent:PPROC
wglMakeCurrent equ <__imp_wglMakeCurrent>

externdef __imp_wglRealizeLayerPalette:PPROC
wglRealizeLayerPalette equ <__imp_wglRealizeLayerPalette>

externdef __imp_wglSetLayerPaletteEntries:PPROC
wglSetLayerPaletteEntries equ <__imp_wglSetLayerPaletteEntries>

externdef __imp_wglSetPixelFormat:PPROC
wglSetPixelFormat equ <__imp_wglSetPixelFormat>

externdef __imp_wglShareLists:PPROC
wglShareLists equ <__imp_wglShareLists>

externdef __imp_wglSwapBuffers:PPROC
wglSwapBuffers equ <__imp_wglSwapBuffers>

externdef __imp_wglSwapLayerBuffers:PPROC
wglSwapLayerBuffers equ <__imp_wglSwapLayerBuffers>

externdef __imp_wglSwapMultipleBuffers:PPROC
wglSwapMultipleBuffers equ <__imp_wglSwapMultipleBuffers>

externdef __imp_wglUseFontBitmapsA:PPROC
wglUseFontBitmapsA equ <__imp_wglUseFontBitmapsA>
  IFNDEF __UNICODE__
    wglUseFontBitmaps equ <__imp_wglUseFontBitmapsA>
  ENDIF

externdef __imp_wglUseFontBitmapsW:PPROC
wglUseFontBitmapsW equ <__imp_wglUseFontBitmapsW>
  IFDEF __UNICODE__
    wglUseFontBitmaps equ <__imp_wglUseFontBitmapsW>
  ENDIF

externdef __imp_wglUseFontOutlinesA:PPROC
wglUseFontOutlinesA equ <__imp_wglUseFontOutlinesA>
  IFNDEF __UNICODE__
    wglUseFontOutlines equ <__imp_wglUseFontOutlinesA>
  ENDIF

externdef __imp_wglUseFontOutlinesW:PPROC
wglUseFontOutlinesW equ <__imp_wglUseFontOutlinesW>
  IFDEF __UNICODE__
    wglUseFontOutlines equ <__imp_wglUseFontOutlinesW>
  ENDIF
