externdef __imp_FPasswordChangeNotify:PPROC
FPasswordChangeNotify equ <__imp_FPasswordChangeNotify>

externdef __imp_SPAcquireContext:PPROC
SPAcquireContext equ <__imp_SPAcquireContext>

externdef __imp_SPCloseItem:PPROC
SPCloseItem equ <__imp_SPCloseItem>

externdef __imp_SPCreateSubtype:PPROC
SPCreateSubtype equ <__imp_SPCreateSubtype>

externdef __imp_SPCreateType:PPROC
SPCreateType equ <__imp_SPCreateType>

externdef __imp_SPDeleteItem:PPROC
SPDeleteItem equ <__imp_SPDeleteItem>

externdef __imp_SPDeleteSubtype:PPROC
SPDeleteSubtype equ <__imp_SPDeleteSubtype>

externdef __imp_SPDeleteType:PPROC
SPDeleteType equ <__imp_SPDeleteType>

externdef __imp_SPEnumItems:PPROC
SPEnumItems equ <__imp_SPEnumItems>

externdef __imp_SPEnumSubtypes:PPROC
SPEnumSubtypes equ <__imp_SPEnumSubtypes>

externdef __imp_SPEnumTypes:PPROC
SPEnumTypes equ <__imp_SPEnumTypes>

externdef __imp_SPGetProvInfo:PPROC
SPGetProvInfo equ <__imp_SPGetProvInfo>

externdef __imp_SPGetProvParam:PPROC
SPGetProvParam equ <__imp_SPGetProvParam>

externdef __imp_SPGetSubtypeInfo:PPROC
SPGetSubtypeInfo equ <__imp_SPGetSubtypeInfo>

externdef __imp_SPGetTypeInfo:PPROC
SPGetTypeInfo equ <__imp_SPGetTypeInfo>

externdef __imp_SPOpenItem:PPROC
SPOpenItem equ <__imp_SPOpenItem>

externdef __imp_SPProviderInitialize:PPROC
SPProviderInitialize equ <__imp_SPProviderInitialize>

externdef __imp_SPReadItem:PPROC
SPReadItem equ <__imp_SPReadItem>

externdef __imp_SPReleaseContext:PPROC
SPReleaseContext equ <__imp_SPReleaseContext>

externdef __imp_SPSetProvParam:PPROC
SPSetProvParam equ <__imp_SPSetProvParam>

externdef __imp_SPWriteItem:PPROC
SPWriteItem equ <__imp_SPWriteItem>
