externdef __imp_??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z:PPROC
??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z equ <__imp_??0CNestedImpersonation@@QEAA@AEAVTokenHandle@@@Z>

externdef __imp_??0CNestedImpersonation@@QEAA@PEAX@Z:PPROC
??0CNestedImpersonation@@QEAA@PEAX@Z equ <__imp_??0CNestedImpersonation@@QEAA@PEAX@Z>

externdef __imp_??0CNestedImpersonation@@QEAA@XZ:PPROC
??0CNestedImpersonation@@QEAA@XZ equ <__imp_??0CNestedImpersonation@@QEAA@XZ>

externdef __imp_??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z:PPROC
??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z equ <__imp_??0PROXY_SETTINGS_CONTAINER@@QEAA@PEBGPEBUPROXY_SETTINGS@@@Z>

externdef __imp_?BITSAlloc@@YAPEAX_K@Z:PPROC
?BITSAlloc@@YAPEAX_K@Z equ <__imp_?BITSAlloc@@YAPEAX_K@Z>

externdef __imp_?BITSFree@@YAXPEAX@Z:PPROC
?BITSFree@@YAXPEAX@Z equ <__imp_?BITSFree@@YAXPEAX@Z>

externdef __imp_?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ:PPROC
?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ equ <__imp_?BytesRemainingInCurrentRange@CRangeCollection@@QEAA_KXZ>

externdef __imp_?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ:PPROC
?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ equ <__imp_?CalculateBytesTotal@CRangeCollection@@IEAA_NXZ>

externdef __imp_?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z:PPROC
?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z equ <__imp_?Find@CCredentialsContainer@@QEBAJW4__MIDL_IBackgroundCopyJob2_0001@@W4__MIDL_IBackgroundCopyJob2_0002@@PEAPEAU__MIDL_IBackgroundCopyJob2_0005@@@Z>

externdef __imp_?FindInterfaceIndex@@YAKPEBG@Z:PPROC
?FindInterfaceIndex@@YAKPEBG@Z equ <__imp_?FindInterfaceIndex@@YAKPEBG@Z>

externdef __imp_?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z:PPROC
?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z equ <__imp_?GetSubRanges@CRangeCollection@@QEAAJ_K00IPEAPEAV1@@Z>

externdef __imp_?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z:PPROC
?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z equ <__imp_?HostFromProxyDescription@@YA?AV?$auto_ptr@G@std@@PEAG@Z>

externdef __imp_?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A:PPROC
?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A equ <__imp_?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A>
  IFNDEF __UNICODE__
    ?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@ equ <__imp_?s_EmptyString@?$GenericStringHandle@G@@0UStringData@1@A>
  ENDIF

externdef __imp_BITSServiceMain:PPROC
BITSServiceMain equ <__imp_BITSServiceMain>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_ServiceMain:PPROC
ServiceMain equ <__imp_ServiceMain>
