externdef __imp_??0CAllocStorageVariant@@QEAA@AEAUtagPROPVARIANT@@AEAVPMemoryAllocator@@@Z:PPROC
??0CAllocStorageVariant@@QEAA@AEAUtagPROPVARIANT@@AEAVPMemoryAllocator@@@Z equ <__imp_??0CAllocStorageVariant@@QEAA@AEAUtagPROPVARIANT@@AEAVPMemoryAllocator@@@Z>

externdef __imp_??0CAllocStorageVariant@@QEAA@AEAVPDeSerStream@@AEAVPMemoryAllocator@@@Z:PPROC
??0CAllocStorageVariant@@QEAA@AEAVPDeSerStream@@AEAVPMemoryAllocator@@@Z equ <__imp_??0CAllocStorageVariant@@QEAA@AEAVPDeSerStream@@AEAVPMemoryAllocator@@@Z>

externdef __imp_??0CAllocStorageVariant@@QEAA@PEBDAEAVPMemoryAllocator@@@Z:PPROC
??0CAllocStorageVariant@@QEAA@PEBDAEAVPMemoryAllocator@@@Z equ <__imp_??0CAllocStorageVariant@@QEAA@PEBDAEAVPMemoryAllocator@@@Z>

externdef __imp_??0CAllocStorageVariant@@QEAA@PEBGAEAVPMemoryAllocator@@@Z:PPROC
??0CAllocStorageVariant@@QEAA@PEBGAEAVPMemoryAllocator@@@Z equ <__imp_??0CAllocStorageVariant@@QEAA@PEBGAEAVPMemoryAllocator@@@Z>

externdef __imp_??0CAllocStorageVariant@@QEAA@PEBU_GUID@@AEAVPMemoryAllocator@@@Z:PPROC
??0CAllocStorageVariant@@QEAA@PEBU_GUID@@AEAVPMemoryAllocator@@@Z equ <__imp_??0CAllocStorageVariant@@QEAA@PEBU_GUID@@AEAVPMemoryAllocator@@@Z>

externdef __imp_??0CAllocStorageVariant@@QEAA@W4VARENUM@@KAEAVPMemoryAllocator@@@Z:PPROC
??0CAllocStorageVariant@@QEAA@W4VARENUM@@KAEAVPMemoryAllocator@@@Z equ <__imp_??0CAllocStorageVariant@@QEAA@W4VARENUM@@KAEAVPMemoryAllocator@@@Z>

externdef __imp_??0CCatState@@QEAA@XZ:PPROC
??0CCatState@@QEAA@XZ equ <__imp_??0CCatState@@QEAA@XZ>

externdef __imp_??0CCategorizationSet@@QEAA@AEBV0@@Z:PPROC
??0CCategorizationSet@@QEAA@AEBV0@@Z equ <__imp_??0CCategorizationSet@@QEAA@AEBV0@@Z>

externdef __imp_??0CCategorizationSet@@QEAA@I@Z:PPROC
??0CCategorizationSet@@QEAA@I@Z equ <__imp_??0CCategorizationSet@@QEAA@I@Z>

externdef __imp_??0CCiAdminParams@@QEAA@PEAVCLangList@@@Z:PPROC
??0CCiAdminParams@@QEAA@PEAVCLangList@@@Z equ <__imp_??0CCiAdminParams@@QEAA@PEAVCLangList@@@Z>

externdef __imp_??0CCiRegParams@@QEAA@PEBG@Z:PPROC
??0CCiRegParams@@QEAA@PEBG@Z equ <__imp_??0CCiRegParams@@QEAA@PEBG@Z>

externdef __imp_??0CColumnSet@@QEAA@I@Z:PPROC
??0CColumnSet@@QEAA@I@Z equ <__imp_??0CColumnSet@@QEAA@I@Z>

externdef __imp_??0CColumns@@QEAA@AEBV0@@Z:PPROC
??0CColumns@@QEAA@AEBV0@@Z equ <__imp_??0CColumns@@QEAA@AEBV0@@Z>

externdef __imp_??0CColumns@@QEAA@I@Z:PPROC
??0CColumns@@QEAA@I@Z equ <__imp_??0CColumns@@QEAA@I@Z>

externdef __imp_??0CContentRestriction@@QEAA@PEBGAEBVCFullPropSpec@@KK@Z:PPROC
??0CContentRestriction@@QEAA@PEBGAEBVCFullPropSpec@@KK@Z equ <__imp_??0CContentRestriction@@QEAA@PEBGAEBVCFullPropSpec@@KK@Z>

externdef __imp_??0CDFA@@QEAA@PEBGAEAVCTimeLimit@@E@Z:PPROC
??0CDFA@@QEAA@PEBGAEAVCTimeLimit@@E@Z equ <__imp_??0CDFA@@QEAA@PEBGAEAVCTimeLimit@@E@Z>

externdef __imp_??0CDbColId@@QEAA@AEBU_GUID@@PEBG@Z:PPROC
??0CDbColId@@QEAA@AEBU_GUID@@PEBG@Z equ <__imp_??0CDbColId@@QEAA@AEBU_GUID@@PEBG@Z>

externdef __imp_??0CDbColId@@QEAA@AEBUtagDBID@@@Z:PPROC
??0CDbColId@@QEAA@AEBUtagDBID@@@Z equ <__imp_??0CDbColId@@QEAA@AEBUtagDBID@@@Z>

externdef __imp_??0CDbColId@@QEAA@AEBV0@@Z:PPROC
??0CDbColId@@QEAA@AEBV0@@Z equ <__imp_??0CDbColId@@QEAA@AEBV0@@Z>

externdef __imp_??0CDbColId@@QEAA@XZ:PPROC
??0CDbColId@@QEAA@XZ equ <__imp_??0CDbColId@@QEAA@XZ>

externdef __imp_??0CDbColumns@@QEAA@I@Z:PPROC
??0CDbColumns@@QEAA@I@Z equ <__imp_??0CDbColumns@@QEAA@I@Z>

externdef __imp_??0CDbContentRestriction@@QEAA@PEBGAEBUtagDBID@@KK@Z:PPROC
??0CDbContentRestriction@@QEAA@PEBGAEBUtagDBID@@KK@Z equ <__imp_??0CDbContentRestriction@@QEAA@PEBGAEBUtagDBID@@KK@Z>

externdef __imp_??0CDbContentRestriction@@QEAA@PEBGAEBVCDbColumnNode@@KK@Z:PPROC
??0CDbContentRestriction@@QEAA@PEBGAEBVCDbColumnNode@@KK@Z equ <__imp_??0CDbContentRestriction@@QEAA@PEBGAEBVCDbColumnNode@@KK@Z>

externdef __imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBUtagDBID@@K@Z:PPROC
??0CDbNatLangRestriction@@QEAA@PEBGAEBUtagDBID@@K@Z equ <__imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBUtagDBID@@K@Z>

externdef __imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBVCDbColumnNode@@K@Z:PPROC
??0CDbNatLangRestriction@@QEAA@PEBGAEBVCDbColumnNode@@K@Z equ <__imp_??0CDbNatLangRestriction@@QEAA@PEBGAEBVCDbColumnNode@@K@Z>

externdef __imp_??0CDbQueryResults@@QEAA@XZ:PPROC
??0CDbQueryResults@@QEAA@XZ equ <__imp_??0CDbQueryResults@@QEAA@XZ>

externdef __imp_??0CDbSelectNode@@QEAA@XZ:PPROC
??0CDbSelectNode@@QEAA@XZ equ <__imp_??0CDbSelectNode@@QEAA@XZ>

externdef __imp_??0CDbSortSet@@QEAA@I@Z:PPROC
??0CDbSortSet@@QEAA@I@Z equ <__imp_??0CDbSortSet@@QEAA@I@Z>

externdef __imp_??0CDefColumnRegEntry@@QEAA@XZ:PPROC
??0CDefColumnRegEntry@@QEAA@XZ equ <__imp_??0CDefColumnRegEntry@@QEAA@XZ>

externdef __imp_??0CDriveInfo@@QEAA@PEBGK@Z:PPROC
??0CDriveInfo@@QEAA@PEBGK@Z equ <__imp_??0CDriveInfo@@QEAA@PEBGK@Z>

externdef __imp_??0CDynStream@@QEAA@PEAVPMmStream@@@Z:PPROC
??0CDynStream@@QEAA@PEAVPMmStream@@@Z equ <__imp_??0CDynStream@@QEAA@PEAVPMmStream@@@Z>

externdef __imp_??0CEventItem@@QEAA@GGKGKPEBX@Z:PPROC
??0CEventItem@@QEAA@GGKGKPEBX@Z equ <__imp_??0CEventItem@@QEAA@GGKGKPEBX@Z>

externdef __imp_??0CEventLog@@QEAA@PEBG0@Z:PPROC
??0CEventLog@@QEAA@PEBG0@Z equ <__imp_??0CEventLog@@QEAA@PEBG0@Z>

externdef __imp_??0CException@@QEAA@J@Z:PPROC
??0CException@@QEAA@J@Z equ <__imp_??0CException@@QEAA@J@Z>

externdef __imp_??0CException@@QEAA@XZ:PPROC
??0CException@@QEAA@XZ equ <__imp_??0CException@@QEAA@XZ>

externdef __imp_??0CFileBuffer@@QEAA@AEAVCFileMapView@@I@Z:PPROC
??0CFileBuffer@@QEAA@AEAVCFileMapView@@I@Z equ <__imp_??0CFileBuffer@@QEAA@AEAVCFileMapView@@I@Z>

externdef __imp_??0CFileMapView@@QEAA@PEBG@Z:PPROC
??0CFileMapView@@QEAA@PEBG@Z equ <__imp_??0CFileMapView@@QEAA@PEBG@Z>

externdef __imp_??0CFilterDaemon@@QEAA@AEAVCiProxy@@AEAVCCiFrameworkParams@@AEAVCLangList@@PEAEKPEAUICiCFilterClient@@@Z:PPROC
??0CFilterDaemon@@QEAA@AEAVCiProxy@@AEAVCCiFrameworkParams@@AEAVCLangList@@PEAEKPEAUICiCFilterClient@@@Z equ <__imp_??0CFilterDaemon@@QEAA@AEAVCiProxy@@AEAVCCiFrameworkParams@@AEAVCLangList@@PEAEKPEAUICiCFilterClient@@@Z>

externdef __imp_??0CFullPath@@QEAA@PEBG@Z:PPROC
??0CFullPath@@QEAA@PEBG@Z equ <__imp_??0CFullPath@@QEAA@PEBG@Z>

externdef __imp_??0CFullPath@@QEAA@PEBGI@Z:PPROC
??0CFullPath@@QEAA@PEBGI@Z equ <__imp_??0CFullPath@@QEAA@PEBGI@Z>

externdef __imp_??0CFullPropSpec@@QEAA@AEAVPDeSerStream@@@Z:PPROC
??0CFullPropSpec@@QEAA@AEAVPDeSerStream@@@Z equ <__imp_??0CFullPropSpec@@QEAA@AEAVPDeSerStream@@@Z>

externdef __imp_??0CFullPropSpec@@QEAA@AEBV0@@Z:PPROC
??0CFullPropSpec@@QEAA@AEBV0@@Z equ <__imp_??0CFullPropSpec@@QEAA@AEBV0@@Z>

externdef __imp_??0CFullPropSpec@@QEAA@XZ:PPROC
??0CFullPropSpec@@QEAA@XZ equ <__imp_??0CFullPropSpec@@QEAA@XZ>

externdef __imp_??0CFwAsyncWorkItem@@QEAA@AEAVCWorkManager@@AEAVCWorkQueue@@@Z:PPROC
??0CFwAsyncWorkItem@@QEAA@AEAVCWorkManager@@AEAVCWorkQueue@@@Z equ <__imp_??0CFwAsyncWorkItem@@QEAA@AEAVCWorkManager@@AEAVCWorkQueue@@@Z>

externdef __imp_??0CFwEventItem@@QEAA@GKGKPEAX@Z:PPROC
??0CFwEventItem@@QEAA@GKGKPEAX@Z equ <__imp_??0CFwEventItem@@QEAA@GKGKPEAX@Z>

externdef __imp_??0CGenericCiProxy@@QEAA@AEAVCSharedNameGen@@KK@Z:PPROC
??0CGenericCiProxy@@QEAA@AEAVCSharedNameGen@@KK@Z equ <__imp_??0CGenericCiProxy@@QEAA@AEAVCSharedNameGen@@KK@Z>

externdef __imp_??0CGetDbProps@@QEAA@XZ:PPROC
??0CGetDbProps@@QEAA@XZ equ <__imp_??0CGetDbProps@@QEAA@XZ>

externdef __imp_??0CImpersonateRemoteAccess@@QEAA@PEAVCImpersonationTokenCache@@@Z:PPROC
??0CImpersonateRemoteAccess@@QEAA@PEAVCImpersonationTokenCache@@@Z equ <__imp_??0CImpersonateRemoteAccess@@QEAA@PEAVCImpersonationTokenCache@@@Z>

externdef __imp_??0CImpersonationTokenCache@@QEAA@PEBG@Z:PPROC
??0CImpersonationTokenCache@@QEAA@PEBG@Z equ <__imp_??0CImpersonationTokenCache@@QEAA@PEBG@Z>

externdef __imp_??0CIndexTable@@QEAA@AEAVCiStorage@@AEAVCTransaction@@@Z:PPROC
??0CIndexTable@@QEAA@AEAVCiStorage@@AEAVCTransaction@@@Z equ <__imp_??0CIndexTable@@QEAA@AEAVCiStorage@@AEAVCTransaction@@@Z>

externdef __imp_??0CInternalPropertyRestriction@@QEAA@KKAEBVCStorageVariant@@PEAVCRestriction@@@Z:PPROC
??0CInternalPropertyRestriction@@QEAA@KKAEBVCStorageVariant@@PEAVCRestriction@@@Z equ <__imp_??0CInternalPropertyRestriction@@QEAA@KKAEBVCStorageVariant@@PEAVCRestriction@@@Z>

externdef __imp_??0CKeyArray@@QEAA@HH@Z:PPROC
??0CKeyArray@@QEAA@HH@Z equ <__imp_??0CKeyArray@@QEAA@HH@Z>

externdef __imp_??0CLangList@@QEAA@PEAUICiCLangRes@@K@Z:PPROC
??0CLangList@@QEAA@PEAUICiCLangRes@@K@Z equ <__imp_??0CLangList@@QEAA@PEAUICiCLangRes@@K@Z>

externdef __imp_??0CLocalGlobalPropertyList@@QEAA@K@Z:PPROC
??0CLocalGlobalPropertyList@@QEAA@K@Z equ <__imp_??0CLocalGlobalPropertyList@@QEAA@K@Z>

externdef __imp_??0CLocalGlobalPropertyList@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z:PPROC
??0CLocalGlobalPropertyList@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z equ <__imp_??0CLocalGlobalPropertyList@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z>

externdef __imp_??0CMachineAdmin@@QEAA@PEBGH@Z:PPROC
??0CMachineAdmin@@QEAA@PEBGH@Z equ <__imp_??0CMachineAdmin@@QEAA@PEBGH@Z>

externdef __imp_??0CMemSerStream@@QEAA@I@Z:PPROC
??0CMemSerStream@@QEAA@I@Z equ <__imp_??0CMemSerStream@@QEAA@I@Z>

externdef __imp_??0CMemSerStream@@QEAA@PEAEK@Z:PPROC
??0CMemSerStream@@QEAA@PEAEK@Z equ <__imp_??0CMemSerStream@@QEAA@PEAEK@Z>

externdef __imp_??0CMetaDataMgr@@QEAA@HW4CiVRootTypeEnum@@KPEBG@Z:PPROC
??0CMetaDataMgr@@QEAA@HW4CiVRootTypeEnum@@KPEBG@Z equ <__imp_??0CMetaDataMgr@@QEAA@HW4CiVRootTypeEnum@@KPEBG@Z>

externdef __imp_??0CMmStream@@QEAA@KH@Z:PPROC
??0CMmStream@@QEAA@KH@Z equ <__imp_??0CMmStream@@QEAA@KH@Z>

externdef __imp_??0CMmStreamConsecBuf@@QEAA@XZ:PPROC
??0CMmStreamConsecBuf@@QEAA@XZ equ <__imp_??0CMmStreamConsecBuf@@QEAA@XZ>

externdef __imp_??0CNatLanguageRestriction@@QEAA@PEBGAEBVCFullPropSpec@@K@Z:PPROC
??0CNatLanguageRestriction@@QEAA@PEBGAEBVCFullPropSpec@@K@Z equ <__imp_??0CNatLanguageRestriction@@QEAA@PEBGAEBVCFullPropSpec@@K@Z>

externdef __imp_??0CNodeRestriction@@QEAA@KI@Z:PPROC
??0CNodeRestriction@@QEAA@KI@Z equ <__imp_??0CNodeRestriction@@QEAA@KI@Z>

externdef __imp_??0CNormalizer@@QEAA@AEAVPNoiseList@@@Z:PPROC
??0CNormalizer@@QEAA@AEAVPNoiseList@@@Z equ <__imp_??0CNormalizer@@QEAA@AEAVPNoiseList@@@Z>

externdef __imp_??0CPathParser@@QEAA@PEBGK@Z:PPROC
??0CPathParser@@QEAA@PEBGK@Z equ <__imp_??0CPathParser@@QEAA@PEBGK@Z>

externdef __imp_??0CPerfMon@@QEAA@PEBG@Z:PPROC
??0CPerfMon@@QEAA@PEBG@Z equ <__imp_??0CPerfMon@@QEAA@PEBG@Z>

externdef __imp_??0CPersDeComp@@QEAA@AEAVPDirectory@@KAEAVCPhysIndex@@KHH@Z:PPROC
??0CPersDeComp@@QEAA@AEAVPDirectory@@KAEAVCPhysIndex@@KHH@Z equ <__imp_??0CPersDeComp@@QEAA@AEAVPDirectory@@KAEAVCPhysIndex@@KHH@Z>

externdef __imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KIPEAVPMmStream@@HIH@Z:PPROC
??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KIPEAVPMmStream@@HIH@Z equ <__imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KIPEAVPMmStream@@HIH@Z>

externdef __imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KPEAVPMmStream@@W4EOpenMode@1@HIH@Z:PPROC
??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KPEAVPMmStream@@W4EOpenMode@1@HIH@Z equ <__imp_??0CPhysStorage@@IEAA@AEAVPStorage@@AEAVPStorageObject@@KPEAVPMmStream@@W4EOpenMode@1@HIH@Z>

externdef __imp_??0CPidLookupTable@@QEAA@XZ:PPROC
??0CPidLookupTable@@QEAA@XZ equ <__imp_??0CPidLookupTable@@QEAA@XZ>

externdef __imp_??0CPidRemapper@@QEAA@AEAV?$XInterface@UIPropertyMapper@@@@@Z:PPROC
??0CPidRemapper@@QEAA@AEAV?$XInterface@UIPropertyMapper@@@@@Z equ <__imp_??0CPidRemapper@@QEAA@AEAV?$XInterface@UIPropertyMapper@@@@@Z>

externdef __imp_??0CPidRemapper@@QEAA@AEBVCPidMapper@@AEAV?$XInterface@UIPropertyMapper@@@@PEAVCRestriction@@PEAVCColumnSet@@PEAVCSortSet@@@Z:PPROC
??0CPidRemapper@@QEAA@AEBVCPidMapper@@AEAV?$XInterface@UIPropertyMapper@@@@PEAVCRestriction@@PEAVCColumnSet@@PEAVCSortSet@@@Z equ <__imp_??0CPidRemapper@@QEAA@AEBVCPidMapper@@AEAV?$XInterface@UIPropertyMapper@@@@PEAVCRestriction@@PEAVCColumnSet@@PEAVCSortSet@@@Z>

externdef __imp_??0CPropListFile@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z:PPROC
??0CPropListFile@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z equ <__imp_??0CPropListFile@@QEAA@PEAVCEmptyPropertyList@@HPEBGK@Z>

externdef __imp_??0CPropNameArray@@QEAA@AEAVPDeSerStream@@@Z:PPROC
??0CPropNameArray@@QEAA@AEAVPDeSerStream@@@Z equ <__imp_??0CPropNameArray@@QEAA@AEAVPDeSerStream@@@Z>

externdef __imp_??0CPropNameArray@@QEAA@I@Z:PPROC
??0CPropNameArray@@QEAA@I@Z equ <__imp_??0CPropNameArray@@QEAA@I@Z>

externdef __imp_??0CPropStoreManager@@QEAA@K@Z:PPROC
??0CPropStoreManager@@QEAA@K@Z equ <__imp_??0CPropStoreManager@@QEAA@K@Z>

externdef __imp_??0CPropertyRestriction@@QEAA@KAEBVCFullPropSpec@@AEBVCStorageVariant@@@Z:PPROC
??0CPropertyRestriction@@QEAA@KAEBVCFullPropSpec@@AEBVCStorageVariant@@@Z equ <__imp_??0CPropertyRestriction@@QEAA@KAEBVCFullPropSpec@@AEBVCStorageVariant@@@Z>

externdef __imp_??0CPropertyRestriction@@QEAA@XZ:PPROC
??0CPropertyRestriction@@QEAA@XZ equ <__imp_??0CPropertyRestriction@@QEAA@XZ>

externdef __imp_??0CPropertyStoreWids@@QEAA@AEAVCPropStoreManager@@@Z:PPROC
??0CPropertyStoreWids@@QEAA@AEAVCPropStoreManager@@@Z equ <__imp_??0CPropertyStoreWids@@QEAA@AEAVCPropStoreManager@@@Z>

externdef __imp_??0CPropertyValueParser@@QEAA@AEAVCQueryScanner@@GK@Z:PPROC
??0CPropertyValueParser@@QEAA@AEAVCQueryScanner@@GK@Z equ <__imp_??0CPropertyValueParser@@QEAA@AEAVCQueryScanner@@GK@Z>

externdef __imp_??0CQueryScanner@@QEAA@PEBGHKH@Z:PPROC
??0CQueryScanner@@QEAA@PEBGHKH@Z equ <__imp_??0CQueryScanner@@QEAA@PEBGHKH@Z>

externdef __imp_??0CRangeKeyRepository@@QEAA@XZ:PPROC
??0CRangeKeyRepository@@QEAA@XZ equ <__imp_??0CRangeKeyRepository@@QEAA@XZ>

externdef __imp_??0CRcovStrmAppendTrans@@QEAA@AEAVPRcovStorageObj@@@Z:PPROC
??0CRcovStrmAppendTrans@@QEAA@AEAVPRcovStorageObj@@@Z equ <__imp_??0CRcovStrmAppendTrans@@QEAA@AEAVPRcovStorageObj@@@Z>

externdef __imp_??0CRcovStrmMDTrans@@QEAA@AEAVPRcovStorageObj@@W4MDOp@0@K@Z:PPROC
??0CRcovStrmMDTrans@@QEAA@AEAVPRcovStorageObj@@W4MDOp@0@K@Z equ <__imp_??0CRcovStrmMDTrans@@QEAA@AEAVPRcovStorageObj@@W4MDOp@0@K@Z>

externdef __imp_??0CRcovStrmTrans@@IEAA@AEAVPRcovStorageObj@@W4RcovOpType@@@Z:PPROC
??0CRcovStrmTrans@@IEAA@AEAVPRcovStorageObj@@W4RcovOpType@@@Z equ <__imp_??0CRcovStrmTrans@@IEAA@AEAVPRcovStorageObj@@W4RcovOpType@@@Z>

externdef __imp_??0CRegAccess@@QEAA@KPEBG@Z:PPROC
??0CRegAccess@@QEAA@KPEBG@Z equ <__imp_??0CRegAccess@@QEAA@KPEBG@Z>

externdef __imp_??0CRegChangeEvent@@QEAA@PEBGH@Z:PPROC
??0CRegChangeEvent@@QEAA@PEBGH@Z equ <__imp_??0CRegChangeEvent@@QEAA@PEBGH@Z>

externdef __imp_??0CRegNotify@@QEAA@PEBG@Z:PPROC
??0CRegNotify@@QEAA@PEBG@Z equ <__imp_??0CRegNotify@@QEAA@PEBG@Z>

externdef __imp_??0CRequestClient@@QEAA@PEBGPEAUIDBProperties@@@Z:PPROC
??0CRequestClient@@QEAA@PEBGPEAUIDBProperties@@@Z equ <__imp_??0CRequestClient@@QEAA@PEBGPEAUIDBProperties@@@Z>

externdef __imp_??0CRequestQueue@@QEAA@IIIHIIAEBU_GUID@@@Z:PPROC
??0CRequestQueue@@QEAA@IIIHIIAEBU_GUID@@@Z equ <__imp_??0CRequestQueue@@QEAA@IIIHIIAEBU_GUID@@@Z>

externdef __imp_??0CScopeRestriction@@QEAA@PEBGHH@Z:PPROC
??0CScopeRestriction@@QEAA@PEBGHH@Z equ <__imp_??0CScopeRestriction@@QEAA@PEBGHH@Z>

externdef __imp_??0CSdidLookupTable@@QEAA@XZ:PPROC
??0CSdidLookupTable@@QEAA@XZ equ <__imp_??0CSdidLookupTable@@QEAA@XZ>

externdef __imp_??0CSizeSerStream@@QEAA@XZ:PPROC
??0CSizeSerStream@@QEAA@XZ equ <__imp_??0CSizeSerStream@@QEAA@XZ>

externdef __imp_??0CSort@@QEAA@I@Z:PPROC
??0CSort@@QEAA@I@Z equ <__imp_??0CSort@@QEAA@I@Z>

externdef __imp_??0CSortSet@@QEAA@I@Z:PPROC
??0CSortSet@@QEAA@I@Z equ <__imp_??0CSortSet@@QEAA@I@Z>

externdef __imp_??0CStandardPropMapper@@QEAA@XZ:PPROC
??0CStandardPropMapper@@QEAA@XZ equ <__imp_??0CStandardPropMapper@@QEAA@XZ>

externdef __imp_??0CSvcQuery@@QEAA@PEBGPEAUIDBProperties@@@Z:PPROC
??0CSvcQuery@@QEAA@PEBGPEAUIDBProperties@@@Z equ <__imp_??0CSvcQuery@@QEAA@PEBGPEAUIDBProperties@@@Z>

externdef __imp_??0CSynRestriction@@QEAA@AEBVCKey@@KKKH@Z:PPROC
??0CSynRestriction@@QEAA@AEBVCKey@@KKKH@Z equ <__imp_??0CSynRestriction@@QEAA@AEBVCKey@@KKKH@Z>

externdef __imp_??0CTimeLimit@@QEAA@KK@Z:PPROC
??0CTimeLimit@@QEAA@KK@Z equ <__imp_??0CTimeLimit@@QEAA@KK@Z>

externdef __imp_??0CTransaction@@QEAA@XZ:PPROC
??0CTransaction@@QEAA@XZ equ <__imp_??0CTransaction@@QEAA@XZ>

externdef __imp_??0CUnfilteredRestriction@@QEAA@XZ:PPROC
??0CUnfilteredRestriction@@QEAA@XZ equ <__imp_??0CUnfilteredRestriction@@QEAA@XZ>

externdef __imp_??0CValueNormalizer@@QEAA@AEAVPKeyRepository@@@Z:PPROC
??0CValueNormalizer@@QEAA@AEAVPKeyRepository@@@Z equ <__imp_??0CValueNormalizer@@QEAA@AEAVPKeyRepository@@@Z>

externdef __imp_??0CVirtualString@@QEAA@I@Z:PPROC
??0CVirtualString@@QEAA@I@Z equ <__imp_??0CVirtualString@@QEAA@I@Z>

externdef __imp_??0CWin32RegAccess@@QEAA@PEAUHKEY__@@PEBG@Z:PPROC
??0CWin32RegAccess@@QEAA@PEAUHKEY__@@PEBG@Z equ <__imp_??0CWin32RegAccess@@QEAA@PEAUHKEY__@@PEBG@Z>

externdef __imp_??0CWordRestriction@@QEAA@AEBVCKeyBuf@@KKKH@Z:PPROC
??0CWordRestriction@@QEAA@AEBVCKeyBuf@@KKKH@Z equ <__imp_??0CWordRestriction@@QEAA@AEBVCKeyBuf@@KKKH@Z>

externdef __imp_??0CWorkQueue@@QEAA@IW4WorkQueueType@0@@Z:PPROC
??0CWorkQueue@@QEAA@IW4WorkQueueType@0@@Z equ <__imp_??0CWorkQueue@@QEAA@IW4WorkQueueType@0@@Z>

externdef __imp_??0CiStorage@@QEAA@PEBGAEAUICiCAdviseStatus@@KKH@Z:PPROC
??0CiStorage@@QEAA@PEBGAEAUICiCAdviseStatus@@KKH@Z equ <__imp_??0CiStorage@@QEAA@PEBGAEAUICiCAdviseStatus@@KKH@Z>

externdef __imp_??0SStorageObject@@QEAA@PEAVPStorageObject@@@Z:PPROC
??0SStorageObject@@QEAA@PEAVPStorageObject@@@Z equ <__imp_??0SStorageObject@@QEAA@PEAVPStorageObject@@@Z>

externdef __imp_??1CAllocStorageVariant@@IEAA@XZ:PPROC
??1CAllocStorageVariant@@IEAA@XZ equ <__imp_??1CAllocStorageVariant@@IEAA@XZ>

externdef __imp_??1CCatState@@QEAA@XZ:PPROC
??1CCatState@@QEAA@XZ equ <__imp_??1CCatState@@QEAA@XZ>

externdef __imp_??1CCatalogAdmin@@QEAA@XZ:PPROC
??1CCatalogAdmin@@QEAA@XZ equ <__imp_??1CCatalogAdmin@@QEAA@XZ>

externdef __imp_??1CCatalogEnum@@QEAA@XZ:PPROC
??1CCatalogEnum@@QEAA@XZ equ <__imp_??1CCatalogEnum@@QEAA@XZ>

externdef __imp_??1CColumns@@QEAA@XZ:PPROC
??1CColumns@@QEAA@XZ equ <__imp_??1CColumns@@QEAA@XZ>

externdef __imp_??1CContentRestriction@@QEAA@XZ:PPROC
??1CContentRestriction@@QEAA@XZ equ <__imp_??1CContentRestriction@@QEAA@XZ>

externdef __imp_??1CDFA@@QEAA@XZ:PPROC
??1CDFA@@QEAA@XZ equ <__imp_??1CDFA@@QEAA@XZ>

externdef __imp_??1CDbCmdTreeNode@@QEAA@XZ:PPROC
??1CDbCmdTreeNode@@QEAA@XZ equ <__imp_??1CDbCmdTreeNode@@QEAA@XZ>

externdef __imp_??1CDbColumns@@QEAA@XZ:PPROC
??1CDbColumns@@QEAA@XZ equ <__imp_??1CDbColumns@@QEAA@XZ>

externdef __imp_??1CDbPropSet@@QEAA@XZ:PPROC
??1CDbPropSet@@QEAA@XZ equ <__imp_??1CDbPropSet@@QEAA@XZ>

externdef __imp_??1CDbQueryResults@@QEAA@XZ:PPROC
??1CDbQueryResults@@QEAA@XZ equ <__imp_??1CDbQueryResults@@QEAA@XZ>

externdef __imp_??1CDbSortSet@@QEAA@XZ:PPROC
??1CDbSortSet@@QEAA@XZ equ <__imp_??1CDbSortSet@@QEAA@XZ>

externdef __imp_??1CDynStream@@QEAA@XZ:PPROC
??1CDynStream@@QEAA@XZ equ <__imp_??1CDynStream@@QEAA@XZ>

externdef __imp_??1CEventItem@@QEAA@XZ:PPROC
??1CEventItem@@QEAA@XZ equ <__imp_??1CEventItem@@QEAA@XZ>

externdef __imp_??1CEventLog@@QEAA@XZ:PPROC
??1CEventLog@@QEAA@XZ equ <__imp_??1CEventLog@@QEAA@XZ>

externdef __imp_??1CFileMapView@@QEAA@XZ:PPROC
??1CFileMapView@@QEAA@XZ equ <__imp_??1CFileMapView@@QEAA@XZ>

externdef __imp_??1CFilterDaemon@@QEAA@XZ:PPROC
??1CFilterDaemon@@QEAA@XZ equ <__imp_??1CFilterDaemon@@QEAA@XZ>

externdef __imp_??1CFwAsyncWorkItem@@UEAA@XZ:PPROC
??1CFwAsyncWorkItem@@UEAA@XZ equ <__imp_??1CFwAsyncWorkItem@@UEAA@XZ>

externdef __imp_??1CFwEventItem@@QEAA@XZ:PPROC
??1CFwEventItem@@QEAA@XZ equ <__imp_??1CFwEventItem@@QEAA@XZ>

externdef __imp_??1CGenericCiProxy@@UEAA@XZ:PPROC
??1CGenericCiProxy@@UEAA@XZ equ <__imp_??1CGenericCiProxy@@UEAA@XZ>

externdef __imp_??1CImpersonateClient@@QEAA@XZ:PPROC
??1CImpersonateClient@@QEAA@XZ equ <__imp_??1CImpersonateClient@@QEAA@XZ>

externdef __imp_??1CImpersonateSystem@@QEAA@XZ:PPROC
??1CImpersonateSystem@@QEAA@XZ equ <__imp_??1CImpersonateSystem@@QEAA@XZ>

externdef __imp_??1CImpersonationTokenCache@@QEAA@XZ:PPROC
??1CImpersonationTokenCache@@QEAA@XZ equ <__imp_??1CImpersonationTokenCache@@QEAA@XZ>

externdef __imp_??1CInternalPropertyRestriction@@QEAA@XZ:PPROC
??1CInternalPropertyRestriction@@QEAA@XZ equ <__imp_??1CInternalPropertyRestriction@@QEAA@XZ>

externdef __imp_??1CKeyArray@@QEAA@XZ:PPROC
??1CKeyArray@@QEAA@XZ equ <__imp_??1CKeyArray@@QEAA@XZ>

externdef __imp_??1CLangList@@QEAA@XZ:PPROC
??1CLangList@@QEAA@XZ equ <__imp_??1CLangList@@QEAA@XZ>

externdef __imp_??1CMachineAdmin@@QEAA@XZ:PPROC
??1CMachineAdmin@@QEAA@XZ equ <__imp_??1CMachineAdmin@@QEAA@XZ>

externdef __imp_??1CMemSerStream@@UEAA@XZ:PPROC
??1CMemSerStream@@UEAA@XZ equ <__imp_??1CMemSerStream@@UEAA@XZ>

externdef __imp_??1CMetaDataMgr@@QEAA@XZ:PPROC
??1CMetaDataMgr@@QEAA@XZ equ <__imp_??1CMetaDataMgr@@QEAA@XZ>

externdef __imp_??1CMmStream@@UEAA@XZ:PPROC
??1CMmStream@@UEAA@XZ equ <__imp_??1CMmStream@@UEAA@XZ>

externdef __imp_??1CMmStreamConsecBuf@@QEAA@XZ:PPROC
??1CMmStreamConsecBuf@@QEAA@XZ equ <__imp_??1CMmStreamConsecBuf@@QEAA@XZ>

externdef __imp_??1CNatLanguageRestriction@@QEAA@XZ:PPROC
??1CNatLanguageRestriction@@QEAA@XZ equ <__imp_??1CNatLanguageRestriction@@QEAA@XZ>

externdef __imp_??1CNodeRestriction@@QEAA@XZ:PPROC
??1CNodeRestriction@@QEAA@XZ equ <__imp_??1CNodeRestriction@@QEAA@XZ>

externdef __imp_??1CNotRestriction@@QEAA@XZ:PPROC
??1CNotRestriction@@QEAA@XZ equ <__imp_??1CNotRestriction@@QEAA@XZ>

externdef __imp_??1COccRestriction@@QEAA@XZ:PPROC
??1COccRestriction@@QEAA@XZ equ <__imp_??1COccRestriction@@QEAA@XZ>

externdef __imp_??1CParseCommandTree@@QEAA@XZ:PPROC
??1CParseCommandTree@@QEAA@XZ equ <__imp_??1CParseCommandTree@@QEAA@XZ>

externdef __imp_??1CPerfMon@@QEAA@XZ:PPROC
??1CPerfMon@@QEAA@XZ equ <__imp_??1CPerfMon@@QEAA@XZ>

externdef __imp_??1CPhraseRestriction@@QEAA@XZ:PPROC
??1CPhraseRestriction@@QEAA@XZ equ <__imp_??1CPhraseRestriction@@QEAA@XZ>

externdef __imp_??1CPhysStorage@@UEAA@XZ:PPROC
??1CPhysStorage@@UEAA@XZ equ <__imp_??1CPhysStorage@@UEAA@XZ>

externdef __imp_??1CPidLookupTable@@QEAA@XZ:PPROC
??1CPidLookupTable@@QEAA@XZ equ <__imp_??1CPidLookupTable@@QEAA@XZ>

externdef __imp_??1CPidRemapper@@QEAA@XZ:PPROC
??1CPidRemapper@@QEAA@XZ equ <__imp_??1CPidRemapper@@QEAA@XZ>

externdef __imp_??1CProcess@@QEAA@XZ:PPROC
??1CProcess@@QEAA@XZ equ <__imp_??1CProcess@@QEAA@XZ>

externdef __imp_??1CPropStoreManager@@QEAA@XZ:PPROC
??1CPropStoreManager@@QEAA@XZ equ <__imp_??1CPropStoreManager@@QEAA@XZ>

externdef __imp_??1CPropertyList@@UEAA@XZ:PPROC
??1CPropertyList@@UEAA@XZ equ <__imp_??1CPropertyList@@UEAA@XZ>

externdef __imp_??1CPropertyRestriction@@QEAA@XZ:PPROC
??1CPropertyRestriction@@QEAA@XZ equ <__imp_??1CPropertyRestriction@@QEAA@XZ>

externdef __imp_??1CPropertyStore@@QEAA@XZ:PPROC
??1CPropertyStore@@QEAA@XZ equ <__imp_??1CPropertyStore@@QEAA@XZ>

externdef __imp_??1CPropertyStoreWids@@QEAA@XZ:PPROC
??1CPropertyStoreWids@@QEAA@XZ equ <__imp_??1CPropertyStoreWids@@QEAA@XZ>

externdef __imp_??1CQueryUnknown@@QEAA@XZ:PPROC
??1CQueryUnknown@@QEAA@XZ equ <__imp_??1CQueryUnknown@@QEAA@XZ>

externdef __imp_??1CRangeKeyRepository@@UEAA@XZ:PPROC
??1CRangeKeyRepository@@UEAA@XZ equ <__imp_??1CRangeKeyRepository@@UEAA@XZ>

externdef __imp_??1CRegChangeEvent@@QEAA@XZ:PPROC
??1CRegChangeEvent@@QEAA@XZ equ <__imp_??1CRegChangeEvent@@QEAA@XZ>

externdef __imp_??1CRegNotify@@MEAA@XZ:PPROC
??1CRegNotify@@MEAA@XZ equ <__imp_??1CRegNotify@@MEAA@XZ>

externdef __imp_??1CRestriction@@QEAA@XZ:PPROC
??1CRestriction@@QEAA@XZ equ <__imp_??1CRestriction@@QEAA@XZ>

externdef __imp_??1CScopeAdmin@@QEAA@XZ:PPROC
??1CScopeAdmin@@QEAA@XZ equ <__imp_??1CScopeAdmin@@QEAA@XZ>

externdef __imp_??1CScopeEnum@@QEAA@XZ:PPROC
??1CScopeEnum@@QEAA@XZ equ <__imp_??1CScopeEnum@@QEAA@XZ>

externdef __imp_??1CScopeRestriction@@QEAA@XZ:PPROC
??1CScopeRestriction@@QEAA@XZ equ <__imp_??1CScopeRestriction@@QEAA@XZ>

externdef __imp_??1CSdidLookupTable@@QEAA@XZ:PPROC
??1CSdidLookupTable@@QEAA@XZ equ <__imp_??1CSdidLookupTable@@QEAA@XZ>

externdef __imp_??1CSizeSerStream@@UEAA@XZ:PPROC
??1CSizeSerStream@@UEAA@XZ equ <__imp_??1CSizeSerStream@@UEAA@XZ>

externdef __imp_??1CSort@@QEAA@XZ:PPROC
??1CSort@@QEAA@XZ equ <__imp_??1CSort@@QEAA@XZ>

externdef __imp_??1CSynRestriction@@QEAA@XZ:PPROC
??1CSynRestriction@@QEAA@XZ equ <__imp_??1CSynRestriction@@QEAA@XZ>

externdef __imp_??1CVirtualString@@QEAA@XZ:PPROC
??1CVirtualString@@QEAA@XZ equ <__imp_??1CVirtualString@@QEAA@XZ>

externdef __imp_??1CWin32RegAccess@@QEAA@XZ:PPROC
??1CWin32RegAccess@@QEAA@XZ equ <__imp_??1CWin32RegAccess@@QEAA@XZ>

externdef __imp_??1CWordRestriction@@QEAA@XZ:PPROC
??1CWordRestriction@@QEAA@XZ equ <__imp_??1CWordRestriction@@QEAA@XZ>

externdef __imp_??1CWorkManager@@QEAA@XZ:PPROC
??1CWorkManager@@QEAA@XZ equ <__imp_??1CWorkManager@@QEAA@XZ>

externdef __imp_??1CWorkQueue@@QEAA@XZ:PPROC
??1CWorkQueue@@QEAA@XZ equ <__imp_??1CWorkQueue@@QEAA@XZ>

externdef __imp_??1SStorageObject@@QEAA@XZ:PPROC
??1SStorageObject@@QEAA@XZ equ <__imp_??1SStorageObject@@QEAA@XZ>

externdef __imp_??4CDbColId@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CDbColId@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CDbColId@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??8CDbColId@@QEBAHAEBV0@@Z:PPROC
??8CDbColId@@QEBAHAEBV0@@Z equ <__imp_??8CDbColId@@QEBAHAEBV0@@Z>

externdef __imp_?AbortWorkItems@CWorkManager@@QEAAXXZ:PPROC
?AbortWorkItems@CWorkManager@@QEAAXXZ equ <__imp_?AbortWorkItems@CWorkManager@@QEAAXXZ>

externdef __imp_?Accept@CQueryScanner@@QEAAXXZ:PPROC
?Accept@CQueryScanner@@QEAAXXZ equ <__imp_?Accept@CQueryScanner@@QEAAXXZ>

externdef __imp_?AcceptCommand@CQueryScanner@@QEAAXXZ:PPROC
?AcceptCommand@CQueryScanner@@QEAAXXZ equ <__imp_?AcceptCommand@CQueryScanner@@QEAAXXZ>

externdef __imp_?AcceptWord@CQueryScanner@@QEAAXXZ:PPROC
?AcceptWord@CQueryScanner@@QEAAXXZ equ <__imp_?AcceptWord@CQueryScanner@@QEAAXXZ>

externdef __imp_?AccessCheck@CSdidLookupTable@@QEAAHKPEAXKAEAH@Z:PPROC
?AccessCheck@CSdidLookupTable@@QEAAHKPEAXKAEAH@Z equ <__imp_?AccessCheck@CSdidLookupTable@@QEAAHKPEAXKAEAH@Z>

externdef __imp_?AcqLine@CQueryScanner@@QEAAPEAGH@Z:PPROC
?AcqLine@CQueryScanner@@QEAAPEAGH@Z equ <__imp_?AcqLine@CQueryScanner@@QEAAPEAGH@Z>

externdef __imp_?AcqPath@CQueryScanner@@QEAAPEAGXZ:PPROC
?AcqPath@CQueryScanner@@QEAAPEAGXZ equ <__imp_?AcqPath@CQueryScanner@@QEAAPEAGXZ>

externdef __imp_?AcqPhrase@CQueryScanner@@QEAAPEAGXZ:PPROC
?AcqPhrase@CQueryScanner@@QEAAPEAGXZ equ <__imp_?AcqPhrase@CQueryScanner@@QEAAPEAGXZ>

externdef __imp_?AcqRst@CRangeKeyRepository@@QEAAPEAVCRangeRestriction@@XZ:PPROC
?AcqRst@CRangeKeyRepository@@QEAAPEAVCRangeRestriction@@XZ equ <__imp_?AcqRst@CRangeKeyRepository@@QEAAPEAVCRangeRestriction@@XZ>

externdef __imp_?AcqWord@CQueryScanner@@QEAAPEAGXZ:PPROC
?AcqWord@CQueryScanner@@QEAAPEAGXZ equ <__imp_?AcqWord@CQueryScanner@@QEAAPEAGXZ>

externdef __imp_?AcquireRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z:PPROC
?AcquireRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z equ <__imp_?AcquireRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z>

externdef __imp_?Add@CDbColumns@@QEAAHAEBVCDbColId@@I@Z:PPROC
?Add@CDbColumns@@QEAAHAEBVCDbColId@@I@Z equ <__imp_?Add@CDbColumns@@QEAAHAEBVCDbColId@@I@Z>

externdef __imp_?Add@CDbQueryResults@@QEAAXPEAGK@Z:PPROC
?Add@CDbQueryResults@@QEAAXPEAGK@Z equ <__imp_?Add@CDbQueryResults@@QEAAXPEAGK@Z>

externdef __imp_?Add@CDbSortSet@@QEAAHAEBVCDbColId@@KI@Z:PPROC
?Add@CDbSortSet@@QEAAHAEBVCDbColId@@KI@Z equ <__imp_?Add@CDbSortSet@@QEAAHAEBVCDbColId@@KI@Z>

externdef __imp_?Add@CDbSortSet@@QEAAHAEBVCDbSortKey@@I@Z:PPROC
?Add@CDbSortSet@@QEAAHAEBVCDbSortKey@@I@Z equ <__imp_?Add@CDbSortSet@@QEAAHAEBVCDbSortKey@@I@Z>

externdef __imp_?Add@CKeyArray@@QEAAHHAEBVCKey@@@Z:PPROC
?Add@CKeyArray@@QEAAHHAEBVCKey@@@Z equ <__imp_?Add@CKeyArray@@QEAAHHAEBVCKey@@@Z>

externdef __imp_?Add@CKeyArray@@QEAAHHAEBVCKeyBuf@@@Z:PPROC
?Add@CKeyArray@@QEAAHHAEBVCKeyBuf@@@Z equ <__imp_?Add@CKeyArray@@QEAAHHAEBVCKeyBuf@@@Z>

externdef __imp_?Add@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z:PPROC
?Add@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z equ <__imp_?Add@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z>

externdef __imp_?AddArg@CEventItem@@QEAAXK@Z:PPROC
?AddArg@CEventItem@@QEAAXK@Z equ <__imp_?AddArg@CEventItem@@QEAAXK@Z>

externdef __imp_?AddArg@CEventItem@@QEAAXPEBG@Z:PPROC
?AddArg@CEventItem@@QEAAXPEBG@Z equ <__imp_?AddArg@CEventItem@@QEAAXPEBG@Z>

externdef __imp_?AddArg@CFwEventItem@@QEAAXK@Z:PPROC
?AddArg@CFwEventItem@@QEAAXK@Z equ <__imp_?AddArg@CFwEventItem@@QEAAXK@Z>

externdef __imp_?AddArg@CFwEventItem@@QEAAXPEBG@Z:PPROC
?AddArg@CFwEventItem@@QEAAXPEBG@Z equ <__imp_?AddArg@CFwEventItem@@QEAAXPEBG@Z>

externdef __imp_?AddCachedProperty@CCatalogAdmin@@QEAAXAEBVCFullPropSpec@@KKKH@Z:PPROC
?AddCachedProperty@CCatalogAdmin@@QEAAXAEBVCFullPropSpec@@KKKH@Z equ <__imp_?AddCachedProperty@CCatalogAdmin@@QEAAXAEBVCFullPropSpec@@KKKH@Z>

externdef __imp_?AddCatalog@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z:PPROC
?AddCatalog@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z equ <__imp_?AddCatalog@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z>

externdef __imp_?AddCatalog@CMachineAdmin@@QEAAXPEBG0@Z:PPROC
?AddCatalog@CMachineAdmin@@QEAAXPEBG0@Z equ <__imp_?AddCatalog@CMachineAdmin@@QEAAXPEBG0@Z>

externdef __imp_?AddChild@CNodeRestriction@@QEAAXPEAVCRestriction@@AEAI@Z:PPROC
?AddChild@CNodeRestriction@@QEAAXPEAVCRestriction@@AEAI@Z equ <__imp_?AddChild@CNodeRestriction@@QEAAXPEAVCRestriction@@AEAI@Z>

externdef __imp_?AddDir@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z:PPROC
?AddDir@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z equ <__imp_?AddDir@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z>

externdef __imp_?AddEntry@CPropertyList@@UEAAXPEAVCPropEntry@@H@Z:PPROC
?AddEntry@CPropertyList@@UEAAXPEAVCPropEntry@@H@Z equ <__imp_?AddEntry@CPropertyList@@UEAAXPEAVCPropEntry@@H@Z>

externdef __imp_?AddError@CEventItem@@QEAAXK@Z:PPROC
?AddError@CEventItem@@QEAAXK@Z equ <__imp_?AddError@CEventItem@@QEAAXK@Z>

externdef __imp_?AddKey@CSynRestriction@@QEAAXAEBVCKeyBuf@@@Z:PPROC
?AddKey@CSynRestriction@@QEAAXAEBVCKeyBuf@@@Z equ <__imp_?AddKey@CSynRestriction@@QEAAXAEBVCKeyBuf@@@Z>

externdef __imp_?AddMachine@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z:PPROC
?AddMachine@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z equ <__imp_?AddMachine@CCatState@@QEAAXAEAV?$XPtrST@G@@@Z>

externdef __imp_?AddRef@CDbProperties@@UEAAKXZ:PPROC
?AddRef@CDbProperties@@UEAAKXZ equ <__imp_?AddRef@CDbProperties@@UEAAKXZ>

externdef __imp_?AddRef@CEmptyPropertyList@@UEAAKXZ:PPROC
?AddRef@CEmptyPropertyList@@UEAAKXZ equ <__imp_?AddRef@CEmptyPropertyList@@UEAAKXZ>

externdef __imp_?AddRef@CEnumString@@UEAAKXZ:PPROC
?AddRef@CEnumString@@UEAAKXZ equ <__imp_?AddRef@CEnumString@@UEAAKXZ>

externdef __imp_?AddRef@CEnumWorkid@@UEAAKXZ:PPROC
?AddRef@CEnumWorkid@@UEAAKXZ equ <__imp_?AddRef@CEnumWorkid@@UEAAKXZ>

externdef __imp_?AddRef@CFwPropertyMapper@@UEAAKXZ:PPROC
?AddRef@CFwPropertyMapper@@UEAAKXZ equ <__imp_?AddRef@CFwPropertyMapper@@UEAAKXZ>

externdef __imp_?AddRef@CQueryUnknown@@UEAAKXZ:PPROC
?AddRef@CQueryUnknown@@UEAAKXZ equ <__imp_?AddRef@CQueryUnknown@@UEAAKXZ>

externdef __imp_?AddRefWorkThreads@CWorkQueue@@QEAAXXZ:PPROC
?AddRefWorkThreads@CWorkQueue@@QEAAXXZ equ <__imp_?AddRefWorkThreads@CWorkQueue@@QEAAXXZ>

externdef __imp_?AddScope@CCatalogAdmin@@QEAAXPEBG0H00@Z:PPROC
?AddScope@CCatalogAdmin@@QEAAXPEBG0H00@Z equ <__imp_?AddScope@CCatalogAdmin@@QEAAXPEBG0H00@Z>

externdef __imp_?AddSortColumn@CDbSortNode@@QEAAHAEBUtagDBID@@HK@Z:PPROC
?AddSortColumn@CDbSortNode@@QEAAHAEBUtagDBID@@HK@Z equ <__imp_?AddSortColumn@CDbSortNode@@QEAAHAEBUtagDBID@@HK@Z>

externdef __imp_?AddTable@CDbNestingNode@@QEAAHPEAVCDbCmdTreeNode@@@Z:PPROC
?AddTable@CDbNestingNode@@QEAAHPEAVCDbCmdTreeNode@@@Z equ <__imp_?AddTable@CDbNestingNode@@QEAAHPEAVCDbCmdTreeNode@@@Z>

externdef __imp_?AddToWorkList@CWorkManager@@QEAAXPEAVCFwAsyncWorkItem@@@Z:PPROC
?AddToWorkList@CWorkManager@@QEAAXPEAVCFwAsyncWorkItem@@@Z equ <__imp_?AddToWorkList@CWorkManager@@QEAAXPEAVCFwAsyncWorkItem@@@Z>

externdef __imp_?AddToWorkQueue@CFwAsyncWorkItem@@QEAAXXZ:PPROC
?AddToWorkQueue@CFwAsyncWorkItem@@QEAAXXZ equ <__imp_?AddToWorkQueue@CFwAsyncWorkItem@@QEAAXXZ>

externdef __imp_?AllocAndCopyWString@CDbCmdTreeNode@@SAPEAGPEBG@Z:PPROC
?AllocAndCopyWString@CDbCmdTreeNode@@SAPEAGPEBG@Z equ <__imp_?AllocAndCopyWString@CDbCmdTreeNode@@SAPEAGPEBG@Z>

externdef __imp_?AllocHeapAndCopy@@YAPEAGPEBGAEAK@Z:PPROC
?AllocHeapAndCopy@@YAPEAGPEBGAEAK@Z equ <__imp_?AllocHeapAndCopy@@YAPEAGPEBGAEAK@Z>

externdef __imp_?AllocHeapAndGetWString@@YAPEAGAEAVPDeSerStream@@@Z:PPROC
?AllocHeapAndGetWString@@YAPEAGAEAVPDeSerStream@@@Z equ <__imp_?AllocHeapAndGetWString@@YAPEAGAEAVPDeSerStream@@@Z>

externdef __imp_?Append@CEnumString@@QEAAXPEBG@Z:PPROC
?Append@CEnumString@@QEAAXPEBG@Z equ <__imp_?Append@CEnumString@@QEAAXPEBG@Z>

externdef __imp_?Append@CEnumWorkid@@QEAAXK@Z:PPROC
?Append@CEnumWorkid@@QEAAXK@Z equ <__imp_?Append@CEnumWorkid@@QEAAXK@Z>

externdef __imp_?AppendChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z:PPROC
?AppendChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z equ <__imp_?AppendChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z>

externdef __imp_?AppendListElement@CDbListAnchor@@IEAAHGAEBUtagDBID@@@Z:PPROC
?AppendListElement@CDbListAnchor@@IEAAHGAEBUtagDBID@@@Z equ <__imp_?AppendListElement@CDbListAnchor@@IEAAHGAEBUtagDBID@@@Z>

externdef __imp_?AppendListElement@CDbListAnchor@@IEAAHPEAVCDbCmdTreeNode@@@Z:PPROC
?AppendListElement@CDbListAnchor@@IEAAHPEAVCDbCmdTreeNode@@@Z equ <__imp_?AppendListElement@CDbListAnchor@@IEAAHPEAVCDbCmdTreeNode@@@Z>

externdef __imp_?AppendListElement@CDbProjectListAnchor@@QEAAHAEBUtagDBID@@PEAG@Z:PPROC
?AppendListElement@CDbProjectListAnchor@@QEAAHAEBUtagDBID@@PEAG@Z equ <__imp_?AppendListElement@CDbProjectListAnchor@@QEAAHAEBUtagDBID@@PEAG@Z>

externdef __imp_?BeginTransaction@CPropStoreManager@@QEAA_KXZ:PPROC
?BeginTransaction@CPropStoreManager@@QEAA_KXZ equ <__imp_?BeginTransaction@CPropStoreManager@@QEAA_KXZ>

externdef __imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@AEBU_GUID@@PEAPEAUIFilter@@H@Z:PPROC
?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@AEBU_GUID@@PEAPEAUIFilter@@H@Z equ <__imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@AEBU_GUID@@PEAPEAUIFilter@@H@Z>

externdef __imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@PEAPEAUIFilter@@H@Z:PPROC
?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@PEAPEAUIFilter@@H@Z equ <__imp_?BindIFilter@CCiOle@@SAJPEBGPEAUIUnknown@@PEAPEAUIFilter@@H@Z>

externdef __imp_?BorrowBuffer@CPhysStorage@@QEAAPEAKKHH@Z:PPROC
?BorrowBuffer@CPhysStorage@@QEAAPEAKKHH@Z equ <__imp_?BorrowBuffer@CPhysStorage@@QEAAPEAKKHH@Z>

externdef __imp_?BorrowNewBuffer@CPhysStorage@@QEAAPEAKK@Z:PPROC
?BorrowNewBuffer@CPhysStorage@@QEAAPEAKK@Z equ <__imp_?BorrowNewBuffer@CPhysStorage@@QEAAPEAKK@Z>

externdef __imp_?BuildRegistryPropertiesKey@@YAXAEAV?$XArray@G@@PEBG@Z:PPROC
?BuildRegistryPropertiesKey@@YAXAEAV?$XArray@G@@PEBG@Z equ <__imp_?BuildRegistryPropertiesKey@@YAXAEAV?$XArray@G@@PEBG@Z>

externdef __imp_?BuildRegistryScopesKey@@YAXAEAV?$XArray@G@@PEBG@Z:PPROC
?BuildRegistryScopesKey@@YAXAEAV?$XArray@G@@PEBG@Z equ <__imp_?BuildRegistryScopesKey@@YAXAEAV?$XArray@G@@PEBG@Z>

externdef __imp_?CIShutdown@@YAXXZ:PPROC
?CIShutdown@@YAXXZ equ <__imp_?CIShutdown@@YAXXZ>

externdef __imp_?ChangeCurrentCatalog@CCatState@@QEAAXPEBG@Z:PPROC
?ChangeCurrentCatalog@CCatState@@QEAAXPEBG@Z equ <__imp_?ChangeCurrentCatalog@CCatState@@QEAAXPEBG@Z>

externdef __imp_?ChangeCurrentDepth@CCatState@@QEAAXH@Z:PPROC
?ChangeCurrentDepth@CCatState@@QEAAXH@Z equ <__imp_?ChangeCurrentDepth@CCatState@@QEAAXH@Z>

externdef __imp_?ChangeCurrentMachine@CCatState@@QEAAXPEBG@Z:PPROC
?ChangeCurrentMachine@CCatState@@QEAAXPEBG@Z equ <__imp_?ChangeCurrentMachine@CCatState@@QEAAXPEBG@Z>

externdef __imp_?ChangeCurrentScope@CCatState@@QEAAXPEBG@Z:PPROC
?ChangeCurrentScope@CCatState@@QEAAXPEBG@Z equ <__imp_?ChangeCurrentScope@CCatState@@QEAAXPEBG@Z>

externdef __imp_?ChangeDirty@CPropStoreInfo@@AEAAXH@Z:PPROC
?ChangeDirty@CPropStoreInfo@@AEAAXH@Z equ <__imp_?ChangeDirty@CPropStoreInfo@@AEAAXH@Z>

externdef __imp_?CheckError@CLocalGlobalPropertyList@@QEAAJAEAKPEAPEAG@Z:PPROC
?CheckError@CLocalGlobalPropertyList@@QEAAJAEAKPEAPEAG@Z equ <__imp_?CheckError@CLocalGlobalPropertyList@@QEAAJAEAKPEAPEAG@Z>

externdef __imp_?CheckError@CPropListFile@@QEAAJAEAKPEAPEAG@Z:PPROC
?CheckError@CPropListFile@@QEAAJAEAKPEAPEAG@Z equ <__imp_?CheckError@CPropListFile@@QEAAJAEAKPEAPEAG@Z>

externdef __imp_?CheckHasIndexTable@CiStorage@@SAHPEBG@Z:PPROC
?CheckHasIndexTable@CiStorage@@SAHPEBG@Z equ <__imp_?CheckHasIndexTable@CiStorage@@SAHPEBG@Z>

externdef __imp_?CiGetPassword@@YAHPEBG0PEAG@Z:PPROC
?CiGetPassword@@YAHPEBG0PEAG@Z equ <__imp_?CiGetPassword@@YAHPEBG0PEAG@Z>

externdef __imp_?CiNtOpen@@YAPEAXPEBGKKK@Z:PPROC
?CiNtOpen@@YAPEAXPEBGKKK@Z equ <__imp_?CiNtOpen@@YAPEAXPEBGKKK@Z>

externdef __imp_?CiNtOpenNoThrow@@YAJAEAPEAXPEBGKKK@Z:PPROC
?CiNtOpenNoThrow@@YAJAEAPEAXPEBGKKK@Z equ <__imp_?CiNtOpenNoThrow@@YAJAEAPEAXPEBGKKK@Z>

externdef __imp_?Cleanup@CDbColId@@QEAAXXZ:PPROC
?Cleanup@CDbColId@@QEAAXXZ equ <__imp_?Cleanup@CDbColId@@QEAAXXZ>

externdef __imp_?CleanupDataValue@CDbCmdTreeNode@@IEAAXXZ:PPROC
?CleanupDataValue@CDbCmdTreeNode@@IEAAXXZ equ <__imp_?CleanupDataValue@CDbCmdTreeNode@@IEAAXXZ>

externdef __imp_?ClearList@CCombinedPropertyList@@QEAAXXZ:PPROC
?ClearList@CCombinedPropertyList@@QEAAXXZ equ <__imp_?ClearList@CCombinedPropertyList@@QEAAXXZ>

externdef __imp_?ClearList@CPropertyList@@QEAAXXZ:PPROC
?ClearList@CPropertyList@@QEAAXXZ equ <__imp_?ClearList@CPropertyList@@QEAAXXZ>

externdef __imp_?Clone@CDbCmdTreeNode@@QEBAPEAV1@H@Z:PPROC
?Clone@CDbCmdTreeNode@@QEBAPEAV1@H@Z equ <__imp_?Clone@CDbCmdTreeNode@@QEBAPEAV1@H@Z>

externdef __imp_?Clone@CEnumString@@UEAAJPEAPEAUIEnumString@@@Z:PPROC
?Clone@CEnumString@@UEAAJPEAPEAUIEnumString@@@Z equ <__imp_?Clone@CEnumString@@UEAAJPEAPEAUIEnumString@@@Z>

externdef __imp_?Clone@CNodeRestriction@@QEBAPEAV1@XZ:PPROC
?Clone@CNodeRestriction@@QEBAPEAV1@XZ equ <__imp_?Clone@CNodeRestriction@@QEBAPEAV1@XZ>

externdef __imp_?Clone@COccRestriction@@QEBAPEAV1@XZ:PPROC
?Clone@COccRestriction@@QEBAPEAV1@XZ equ <__imp_?Clone@COccRestriction@@QEBAPEAV1@XZ>

externdef __imp_?Clone@CRestriction@@QEBAPEAV1@XZ:PPROC
?Clone@CRestriction@@QEBAPEAV1@XZ equ <__imp_?Clone@CRestriction@@QEBAPEAV1@XZ>

externdef __imp_?Close@CPhysStorage@@QEAAXXZ:PPROC
?Close@CPhysStorage@@QEAAXXZ equ <__imp_?Close@CPhysStorage@@QEAAXXZ>

externdef __imp_?Close@CPipeClient@@IEAAXXZ:PPROC
?Close@CPipeClient@@IEAAXXZ equ <__imp_?Close@CPipeClient@@IEAAXXZ>

externdef __imp_?Close@CPropSetMap@COLEPropManager@@QEAAXXZ:PPROC
?Close@CPropSetMap@COLEPropManager@@QEAAXXZ equ <__imp_?Close@CPropSetMap@COLEPropManager@@QEAAXXZ>

externdef __imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecord@@@Z:PPROC
?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecord@@@Z equ <__imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecord@@@Z>

externdef __imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecordForWrites@@@Z:PPROC
?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecordForWrites@@@Z equ <__imp_?CloseRecord@CPropStoreManager@@QEAAXPEAVCCompositePropRecordForWrites@@@Z>

externdef __imp_?CoTaskAllocator@@3VCCoTaskAllocator@@A:PPROC
?CoTaskAllocator@@3VCCoTaskAllocator@@A equ <__imp_?CoTaskAllocator@@3VCCoTaskAllocator@@A>
  IFNDEF __UNICODE__
    ?CoTaskAllocator@@3VCCoTaskAllocator@@ equ <__imp_?CoTaskAllocator@@3VCCoTaskAllocator@@A>
  ENDIF

externdef __imp_?Commit@CRcovStrmAppendTrans@@QEAAXXZ:PPROC
?Commit@CRcovStrmAppendTrans@@QEAAXXZ equ <__imp_?Commit@CRcovStrmAppendTrans@@QEAAXXZ>

externdef __imp_?Commit@CRcovStrmMDTrans@@QEAAXXZ:PPROC
?Commit@CRcovStrmMDTrans@@QEAAXXZ equ <__imp_?Commit@CRcovStrmMDTrans@@QEAAXXZ>

externdef __imp_?Commit@CRcovStrmWriteTrans@@QEAAXXZ:PPROC
?Commit@CRcovStrmWriteTrans@@QEAAXXZ equ <__imp_?Commit@CRcovStrmWriteTrans@@QEAAXXZ>

externdef __imp_?ContainsDrive@CDriveInfo@@SAHPEBG@Z:PPROC
?ContainsDrive@CDriveInfo@@SAHPEBG@Z equ <__imp_?ContainsDrive@CDriveInfo@@SAHPEBG@Z>

externdef __imp_?CreateSubdirs@CMachineAdmin@@QEAAXPEBG@Z:PPROC
?CreateSubdirs@CMachineAdmin@@QEAAXPEBG@Z equ <__imp_?CreateSubdirs@CMachineAdmin@@QEAAXPEBG@Z>

externdef __imp_?DataWriteRead@CRequestClient@@QEAAXPEAXK0KAEAK@Z:PPROC
?DataWriteRead@CRequestClient@@QEAAXPEAXK0KAEAK@Z equ <__imp_?DataWriteRead@CRequestClient@@QEAAXPEAXK0KAEAK@Z>

externdef __imp_?DecodeEscapes@@YAXPEAGAEAK0@Z:PPROC
?DecodeEscapes@@YAXPEAGAEAK0@Z equ <__imp_?DecodeEscapes@@YAXPEAGAEAK0@Z>

externdef __imp_?DecodeHtmlNumeric@@YAXPEAG@Z:PPROC
?DecodeHtmlNumeric@@YAXPEAG@Z equ <__imp_?DecodeHtmlNumeric@@YAXPEAG@Z>

externdef __imp_?DecodeURLEscapes@@YAXPEAEAEAKPEAGK@Z:PPROC
?DecodeURLEscapes@@YAXPEAEAEAKPEAGK@Z equ <__imp_?DecodeURLEscapes@@YAXPEAEAEAKPEAGK@Z>

externdef __imp_?DeleteRecord@CPropStoreManager@@QEAAXK@Z:PPROC
?DeleteRecord@CPropStoreManager@@QEAAXK@Z equ <__imp_?DeleteRecord@CPropStoreManager@@QEAAXK@Z>

externdef __imp_?DeleteRegistryParamNoThrow@CCatalogAdmin@@QEAAXPEBG@Z:PPROC
?DeleteRegistryParamNoThrow@CCatalogAdmin@@QEAAXPEBG@Z equ <__imp_?DeleteRegistryParamNoThrow@CCatalogAdmin@@QEAAXPEBG@Z>

externdef __imp_?DetermineDriveType@CiStorage@@SAIPEBG@Z:PPROC
?DetermineDriveType@CiStorage@@SAIPEBG@Z equ <__imp_?DetermineDriveType@CiStorage@@SAIPEBG@Z>

externdef __imp_?DisableCI@CMachineAdmin@@QEAAHXZ:PPROC
?DisableCI@CMachineAdmin@@QEAAHXZ equ <__imp_?DisableCI@CMachineAdmin@@QEAAHXZ>

externdef __imp_?DisableNotification@CRegNotify@@QEAAXXZ:PPROC
?DisableNotification@CRegNotify@@QEAAXXZ equ <__imp_?DisableNotification@CRegNotify@@QEAAXXZ>

externdef __imp_?DisableVPathNotify@CMetaDataMgr@@QEAAXXZ:PPROC
?DisableVPathNotify@CMetaDataMgr@@QEAAXXZ equ <__imp_?DisableVPathNotify@CMetaDataMgr@@QEAAXXZ>

externdef __imp_?Disconnect@CRequestClient@@QEAAXXZ:PPROC
?Disconnect@CRequestClient@@QEAAXXZ equ <__imp_?Disconnect@CRequestClient@@QEAAXXZ>

externdef __imp_?DoIt@CCopyRcovObject@@QEAAJXZ:PPROC
?DoIt@CCopyRcovObject@@QEAAJXZ equ <__imp_?DoIt@CCopyRcovObject@@QEAAJXZ>

externdef __imp_?DoUpdates@CFilterDaemon@@QEAAJXZ:PPROC
?DoUpdates@CFilterDaemon@@QEAAJXZ equ <__imp_?DoUpdates@CFilterDaemon@@QEAAJXZ>

externdef __imp_?Done@CFwAsyncWorkItem@@QEAAXXZ:PPROC
?Done@CFwAsyncWorkItem@@QEAAXXZ equ <__imp_?Done@CFwAsyncWorkItem@@QEAAXXZ>

externdef __imp_?DumpWorkId@@YAJPEBGKPEAEAEAK00K@Z:PPROC
?DumpWorkId@@YAJPEBGKPEAEAEAK00K@Z equ <__imp_?DumpWorkId@@YAJPEBGKPEAEAEAK00K@Z>

externdef __imp_?Empty@CPidLookupTable@@QEAAXXZ:PPROC
?Empty@CPidLookupTable@@QEAAXXZ equ <__imp_?Empty@CPidLookupTable@@QEAAXXZ>

externdef __imp_?Empty@CPropStoreManager@@QEAAXXZ:PPROC
?Empty@CPropStoreManager@@QEAAXXZ equ <__imp_?Empty@CPropStoreManager@@QEAAXXZ>

externdef __imp_?Empty@CRcovStrmWriteTrans@@QEAAXXZ:PPROC
?Empty@CRcovStrmWriteTrans@@QEAAXXZ equ <__imp_?Empty@CRcovStrmWriteTrans@@QEAAXXZ>

externdef __imp_?Empty@CSdidLookupTable@@QEAAXXZ:PPROC
?Empty@CSdidLookupTable@@QEAAXXZ equ <__imp_?Empty@CSdidLookupTable@@QEAAXXZ>

externdef __imp_?EnableCI@CMachineAdmin@@QEAAHXZ:PPROC
?EnableCI@CMachineAdmin@@QEAAHXZ equ <__imp_?EnableCI@CMachineAdmin@@QEAAHXZ>

externdef __imp_?EnableVPathNotify@CMetaDataMgr@@QEAAXPEAVCMetaDataVPathChangeCallBack@@@Z:PPROC
?EnableVPathNotify@CMetaDataMgr@@QEAAXPEAVCMetaDataVPathChangeCallBack@@@Z equ <__imp_?EnableVPathNotify@CMetaDataMgr@@QEAAXPEAVCMetaDataVPathChangeCallBack@@@Z>

externdef __imp_?EndTransaction@CPropStoreManager@@QEAAX_KHKK@Z:PPROC
?EndTransaction@CPropStoreManager@@QEAAX_KHKK@Z equ <__imp_?EndTransaction@CPropStoreManager@@QEAAX_KHKK@Z>

externdef __imp_?Enum@CWin32RegAccess@@QEAAHPEAGK@Z:PPROC
?Enum@CWin32RegAccess@@QEAAHPEAGK@Z equ <__imp_?Enum@CWin32RegAccess@@QEAAHPEAGK@Z>

externdef __imp_?EnumPropInfo@CEmptyPropertyList@@UEAAJKPEAPEBGPEAPEAUtagDBID@@PEAGPEAI@Z:PPROC
?EnumPropInfo@CEmptyPropertyList@@UEAAJKPEAPEBGPEAPEAUtagDBID@@PEAGPEAI@Z equ <__imp_?EnumPropInfo@CEmptyPropertyList@@UEAAJKPEAPEBGPEAPEAUtagDBID@@PEAGPEAI@Z>

externdef __imp_?EnumVPaths@CMetaDataMgr@@QEAAXAEAVCMetaDataCallBack@@@Z:PPROC
?EnumVPaths@CMetaDataMgr@@QEAAXAEAVCMetaDataCallBack@@@Z equ <__imp_?EnumVPaths@CMetaDataMgr@@QEAAXAEAVCMetaDataCallBack@@@Z>

externdef __imp_?EnumVServers@CMetaDataMgr@@QEAAXAEAVCMetaDataVirtualServerCallBack@@@Z:PPROC
?EnumVServers@CMetaDataMgr@@QEAAXAEAVCMetaDataVirtualServerCallBack@@@Z equ <__imp_?EnumVServers@CMetaDataMgr@@QEAAXAEAVCMetaDataVirtualServerCallBack@@@Z>

externdef __imp_?EnumerateFilesInDir@CiStorage@@SAXPEBGAEAVCEnumString@@@Z:PPROC
?EnumerateFilesInDir@CiStorage@@SAXPEBGAEAVCEnumString@@@Z equ <__imp_?EnumerateFilesInDir@CiStorage@@SAXPEBGAEAVCEnumString@@@Z>

externdef __imp_?EnumerateProperty@CPidLookupTable@@QEAAHAEAVCFullPropSpec@@AEAI@Z:PPROC
?EnumerateProperty@CPidLookupTable@@QEAAHAEAVCFullPropSpec@@AEAI@Z equ <__imp_?EnumerateProperty@CPidLookupTable@@QEAAHAEAVCFullPropSpec@@AEAI@Z>

externdef __imp_?EnumerateValues@CRegAccess@@QEAAXPEAGAEAVCRegCallBack@@@Z:PPROC
?EnumerateValues@CRegAccess@@QEAAXPEAGAEAVCRegCallBack@@@Z equ <__imp_?EnumerateValues@CRegAccess@@QEAAXPEAGAEAVCRegCallBack@@@Z>

externdef __imp_?Eof@CMmStreamConsecBuf@@QEAAHXZ:PPROC
?Eof@CMmStreamConsecBuf@@QEAAHXZ equ <__imp_?Eof@CMmStreamConsecBuf@@QEAAHXZ>

externdef __imp_?ExtensionHasScriptMap@CMetaDataMgr@@QEAAHPEBG@Z:PPROC
?ExtensionHasScriptMap@CMetaDataMgr@@QEAAHPEBG@Z equ <__imp_?ExtensionHasScriptMap@CMetaDataMgr@@QEAAHPEBG@Z>

externdef __imp_?FPSToPROPID@CPidConverter@@UEAAJAEBVCFullPropSpec@@AEAK@Z:PPROC
?FPSToPROPID@CPidConverter@@UEAAJAEBVCFullPropSpec@@AEAK@Z equ <__imp_?FPSToPROPID@CPidConverter@@UEAAJAEBVCFullPropSpec@@AEAK@Z>

externdef __imp_?FastInit@CPropStoreManager@@QEAAXPEAVCiStorage@@@Z:PPROC
?FastInit@CPropStoreManager@@QEAAXPEAVCiStorage@@@Z equ <__imp_?FastInit@CPropStoreManager@@QEAAXPEAVCiStorage@@@Z>

externdef __imp_?FetchProperty@COLEPropManager@@QEAAXAEBU_GUID@@AEBUtagPROPSPEC@@PEAUtagPROPVARIANT@@PEAI@Z:PPROC
?FetchProperty@COLEPropManager@@QEAAXAEBU_GUID@@AEBUtagPROPSPEC@@PEAUtagPROPVARIANT@@PEAI@Z equ <__imp_?FetchProperty@COLEPropManager@@QEAAXAEBU_GUID@@AEBUtagPROPSPEC@@PEAUtagPROPVARIANT@@PEAI@Z>

externdef __imp_?FillMax@CKeyArray@@QEAAHH@Z:PPROC
?FillMax@CKeyArray@@QEAAHH@Z equ <__imp_?FillMax@CKeyArray@@QEAAHH@Z>

externdef __imp_?Find@CEmptyPropertyList@@QEAAPEBVCPropEntry@@AEBVCDbColId@@@Z:PPROC
?Find@CEmptyPropertyList@@QEAAPEBVCPropEntry@@AEBVCDbColId@@@Z equ <__imp_?Find@CEmptyPropertyList@@QEAAPEBVCPropEntry@@AEBVCDbColId@@@Z>

externdef __imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@AEBVCDbColId@@@Z:PPROC
?Find@CPropertyList@@UEAAPEBVCPropEntry@@AEBVCDbColId@@@Z equ <__imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@AEBVCDbColId@@@Z>

externdef __imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@PEBG@Z:PPROC
?Find@CPropertyList@@UEAAPEBVCPropEntry@@PEBG@Z equ <__imp_?Find@CPropertyList@@UEAAPEBVCPropEntry@@PEBG@Z>

externdef __imp_?FindPropid@CPidLookupTable@@QEAAHAEBVCFullPropSpec@@AEAKH@Z:PPROC
?FindPropid@CPidLookupTable@@QEAAHAEBVCFullPropSpec@@AEAKH@Z equ <__imp_?FindPropid@CPidLookupTable@@QEAAHAEBVCFullPropSpec@@AEAKH@Z>

externdef __imp_?Flush@CDynStream@@QEAAXXZ:PPROC
?Flush@CDynStream@@QEAAXXZ equ <__imp_?Flush@CDynStream@@QEAAXXZ>

externdef __imp_?Flush@CPhysStorage@@QEAAXH@Z:PPROC
?Flush@CPhysStorage@@QEAAXH@Z equ <__imp_?Flush@CPhysStorage@@QEAAXH@Z>

externdef __imp_?Flush@CPropStoreManager@@QEAAXXZ:PPROC
?Flush@CPropStoreManager@@QEAAXXZ equ <__imp_?Flush@CPropStoreManager@@QEAAXXZ>

externdef __imp_?FlushIdle@CCiOle@@SAXXZ:PPROC
?FlushIdle@CCiOle@@SAXXZ equ <__imp_?FlushIdle@CCiOle@@SAXXZ>

externdef __imp_?FormFullTree@CTextToTree@@QEAAPEAUtagDBCOMMANDTREE@@XZ:PPROC
?FormFullTree@CTextToTree@@QEAAPEAUtagDBCOMMANDTREE@@XZ equ <__imp_?FormFullTree@CTextToTree@@QEAAPEAUtagDBCOMMANDTREE@@XZ>

externdef __imp_?FormQueryTree@@YAPEAVCDbCmdTreeNode@@AEAV1@AEAVCCatState@@PEAUIColumnMapper@@HH@Z:PPROC
?FormQueryTree@@YAPEAVCDbCmdTreeNode@@AEAV1@AEAVCCatState@@PEAUIColumnMapper@@HH@Z equ <__imp_?FormQueryTree@@YAPEAVCDbCmdTreeNode@@AEAV1@AEAVCCatState@@PEAUIColumnMapper@@HH@Z>

externdef __imp_?Get@CRegAccess@@QEAAKPEBG@Z:PPROC
?Get@CRegAccess@@QEAAKPEBG@Z equ <__imp_?Get@CRegAccess@@QEAAKPEBG@Z>

externdef __imp_?Get@CRegAccess@@QEAAXPEBGPEAGI@Z:PPROC
?Get@CRegAccess@@QEAAXPEBGPEAGI@Z equ <__imp_?Get@CRegAccess@@QEAAXPEBGPEAGI@Z>

externdef __imp_?Get@CWin32RegAccess@@QEAAHPEBGAEAK@Z:PPROC
?Get@CWin32RegAccess@@QEAAHPEBGAEAK@Z equ <__imp_?Get@CWin32RegAccess@@QEAAHPEBGAEAK@Z>

externdef __imp_?Get@CWin32RegAccess@@QEAAHPEBGPEAGIH@Z:PPROC
?Get@CWin32RegAccess@@QEAAHPEBGPEAGIH@Z equ <__imp_?Get@CWin32RegAccess@@QEAAHPEBGPEAGIH@Z>

externdef __imp_?GetAllEntries@CPropertyList@@UEAAJPEAPEAVCPropEntry@@K@Z:PPROC
?GetAllEntries@CPropertyList@@UEAAJPEAPEAVCPropEntry@@K@Z equ <__imp_?GetAllEntries@CPropertyList@@UEAAJPEAPEAVCPropEntry@@K@Z>

externdef __imp_?GetBOOL@CAllocStorageVariant@@QEBAFI@Z:PPROC
?GetBOOL@CAllocStorageVariant@@QEBAFI@Z equ <__imp_?GetBOOL@CAllocStorageVariant@@QEBAFI@Z>

externdef __imp_?GetBackupSize@CPropStoreManager@@QEAAKK@Z:PPROC
?GetBackupSize@CPropStoreManager@@QEAAKK@Z equ <__imp_?GetBackupSize@CPropStoreManager@@QEAAKK@Z>

externdef __imp_?GetBlob@CMemDeSerStream@@UEAAXPEAEK@Z:PPROC
?GetBlob@CMemDeSerStream@@UEAAXPEAEK@Z equ <__imp_?GetBlob@CMemDeSerStream@@UEAAXPEAEK@Z>

externdef __imp_?GetBrowserCodepage@@YAKAEAVCWebServer@@K@Z:PPROC
?GetBrowserCodepage@@YAKAEAVCWebServer@@K@Z equ <__imp_?GetBrowserCodepage@@YAKAEAVCWebServer@@K@Z>

externdef __imp_?GetByte@CMemDeSerStream@@UEAAEXZ:PPROC
?GetByte@CMemDeSerStream@@UEAAEXZ equ <__imp_?GetByte@CMemDeSerStream@@UEAAEXZ>

externdef __imp_?GetCD@CCatState@@QEAAPEBGXZ:PPROC
?GetCD@CCatState@@QEAAPEBGXZ equ <__imp_?GetCD@CCatState@@QEAAPEBGXZ>

externdef __imp_?GetCGIVariable@CWebServer@@QEAAHPEBDAEAV?$XArray@G@@AEAK@Z:PPROC
?GetCGIVariable@CWebServer@@QEAAHPEBDAEAV?$XArray@G@@AEAK@Z equ <__imp_?GetCGIVariable@CWebServer@@QEAAHPEBDAEAV?$XArray@G@@AEAK@Z>

externdef __imp_?GetCGIVariableW@CWebServer@@QEAAHPEBGAEAV?$XArray@G@@AEAK@Z:PPROC
?GetCGIVariableW@CWebServer@@QEAAHPEBGAEAV?$XArray@G@@AEAK@Z equ <__imp_?GetCGIVariableW@CWebServer@@QEAAHPEBGAEAV?$XArray@G@@AEAK@Z>

externdef __imp_?GetCLSID@CAllocStorageVariant@@QEBA?AU_GUID@@I@Z:PPROC
?GetCLSID@CAllocStorageVariant@@QEBA?AU_GUID@@I@Z equ <__imp_?GetCLSID@CAllocStorageVariant@@QEBA?AU_GUID@@I@Z>

externdef __imp_?GetCY@CAllocStorageVariant@@QEBA?ATtagCY@@I@Z:PPROC
?GetCY@CAllocStorageVariant@@QEBA?ATtagCY@@I@Z equ <__imp_?GetCY@CAllocStorageVariant@@QEBA?ATtagCY@@I@Z>

externdef __imp_?GetCategory@CCatState@@QEBAPEBGI@Z:PPROC
?GetCategory@CCatState@@QEBAPEBGI@Z equ <__imp_?GetCategory@CCatState@@QEBAPEBGI@Z>

externdef __imp_?GetChar@CMemDeSerStream@@UEAAXPEADK@Z:PPROC
?GetChar@CMemDeSerStream@@UEAAXPEADK@Z equ <__imp_?GetChar@CMemDeSerStream@@UEAAXPEADK@Z>

externdef __imp_?GetColumn@CCatState@@QEBAPEBGI@Z:PPROC
?GetColumn@CCatState@@QEBAPEBGI@Z equ <__imp_?GetColumn@CCatState@@QEBAPEBGI@Z>

externdef __imp_?GetCommandChar@CQueryScanner@@QEAAGXZ:PPROC
?GetCommandChar@CQueryScanner@@QEAAGXZ equ <__imp_?GetCommandChar@CQueryScanner@@QEAAGXZ>

externdef __imp_?GetDATE@CAllocStorageVariant@@QEBANI@Z:PPROC
?GetDATE@CAllocStorageVariant@@QEBANI@Z equ <__imp_?GetDATE@CAllocStorageVariant@@QEBANI@Z>

externdef __imp_?GetDWORDParam@CCatalogAdmin@@QEAAHPEBGAEAK@Z:PPROC
?GetDWORDParam@CCatalogAdmin@@QEAAHPEBGAEAK@Z equ <__imp_?GetDWORDParam@CCatalogAdmin@@QEAAHPEBGAEAK@Z>

externdef __imp_?GetDWORDParam@CMachineAdmin@@QEAAHPEBGAEAK@Z:PPROC
?GetDWORDParam@CMachineAdmin@@QEAAHPEBGAEAK@Z equ <__imp_?GetDWORDParam@CMachineAdmin@@QEAAHPEBGAEAK@Z>

externdef __imp_?GetDiskSpace@CDriveInfo@@QEAAXAEA_J0@Z:PPROC
?GetDiskSpace@CDriveInfo@@QEAAXAEA_J0@Z equ <__imp_?GetDiskSpace@CDriveInfo@@QEAAXAEA_J0@Z>

externdef __imp_?GetDouble@CMemDeSerStream@@UEAANXZ:PPROC
?GetDouble@CMemDeSerStream@@UEAANXZ equ <__imp_?GetDouble@CMemDeSerStream@@UEAANXZ>

externdef __imp_?GetDrive@CDriveInfo@@SAXPEBGPEAG@Z:PPROC
?GetDrive@CDriveInfo@@SAXPEBGPEAG@Z equ <__imp_?GetDrive@CDriveInfo@@SAXPEBGPEAG@Z>

externdef __imp_?GetEntryBuffer@CGenericCiProxy@@QEAAPEAEAEAK@Z:PPROC
?GetEntryBuffer@CGenericCiProxy@@QEAAPEAEAEAK@Z equ <__imp_?GetEntryBuffer@CGenericCiProxy@@QEAAPEAEAEAK@Z>

externdef __imp_?GetFILETIME@CAllocStorageVariant@@QEBA?AU_FILETIME@@I@Z:PPROC
?GetFILETIME@CAllocStorageVariant@@QEBA?AU_FILETIME@@I@Z equ <__imp_?GetFILETIME@CAllocStorageVariant@@QEBA?AU_FILETIME@@I@Z>

externdef __imp_?GetFileName@CPathParser@@QEBAHPEAGAEAK@Z:PPROC
?GetFileName@CPathParser@@QEBAHPEAGAEAK@Z equ <__imp_?GetFileName@CPathParser@@QEBAHPEAGAEAK@Z>

externdef __imp_?GetFileSystem@CDriveInfo@@QEAA?AW4eFileSystem@1@H@Z:PPROC
?GetFileSystem@CDriveInfo@@QEAA?AW4eFileSystem@1@H@Z equ <__imp_?GetFileSystem@CDriveInfo@@QEAA?AW4eFileSystem@1@H@Z>

externdef __imp_?GetFloat@CMemDeSerStream@@UEAAMXZ:PPROC
?GetFloat@CMemDeSerStream@@UEAAMXZ equ <__imp_?GetFloat@CMemDeSerStream@@UEAAMXZ>

externdef __imp_?GetGUID@CMemDeSerStream@@UEAAXAEAU_GUID@@@Z:PPROC
?GetGUID@CMemDeSerStream@@UEAAXAEAU_GUID@@@Z equ <__imp_?GetGUID@CMemDeSerStream@@UEAAXAEAU_GUID@@@Z>

externdef __imp_?GetGlobalPropListFile@@YAPEAVCPropListFile@@XZ:PPROC
?GetGlobalPropListFile@@YAPEAVCPropListFile@@XZ equ <__imp_?GetGlobalPropListFile@@YAPEAVCPropListFile@@XZ>

externdef __imp_?GetGlobalStaticPropertyList@@YAPEAVCStaticPropertyList@@XZ:PPROC
?GetGlobalStaticPropertyList@@YAPEAVCStaticPropertyList@@XZ equ <__imp_?GetGlobalStaticPropertyList@@YAPEAVCStaticPropertyList@@XZ>

externdef __imp_?GetI2@CAllocStorageVariant@@QEBAFI@Z:PPROC
?GetI2@CAllocStorageVariant@@QEBAFI@Z equ <__imp_?GetI2@CAllocStorageVariant@@QEBAFI@Z>

externdef __imp_?GetI4@CAllocStorageVariant@@QEBAJI@Z:PPROC
?GetI4@CAllocStorageVariant@@QEBAJI@Z equ <__imp_?GetI4@CAllocStorageVariant@@QEBAJI@Z>

externdef __imp_?GetI8@CAllocStorageVariant@@QEBA?AT_LARGE_INTEGER@@I@Z:PPROC
?GetI8@CAllocStorageVariant@@QEBA?AT_LARGE_INTEGER@@I@Z equ <__imp_?GetI8@CAllocStorageVariant@@QEBA?AT_LARGE_INTEGER@@I@Z>

externdef __imp_?GetLCIDFromString@@YAKPEAG@Z:PPROC
?GetLCIDFromString@@YAKPEAG@Z equ <__imp_?GetLCIDFromString@@YAKPEAG@Z>

externdef __imp_?GetLPSTR@CAllocStorageVariant@@QEBAPEADI@Z:PPROC
?GetLPSTR@CAllocStorageVariant@@QEBAPEADI@Z equ <__imp_?GetLPSTR@CAllocStorageVariant@@QEBAPEADI@Z>

externdef __imp_?GetLPWSTR@CAllocStorageVariant@@QEBAPEAGI@Z:PPROC
?GetLPWSTR@CAllocStorageVariant@@QEBAPEAGI@Z equ <__imp_?GetLPWSTR@CAllocStorageVariant@@QEBAPEAGI@Z>

externdef __imp_?GetLocation@CCatalogAdmin@@QEAAPEBGXZ:PPROC
?GetLocation@CCatalogAdmin@@QEAAPEBGXZ equ <__imp_?GetLocation@CCatalogAdmin@@QEAAPEBGXZ>

externdef __imp_?GetLong@CMemDeSerStream@@UEAAJXZ:PPROC
?GetLong@CMemDeSerStream@@UEAAJXZ equ <__imp_?GetLong@CMemDeSerStream@@UEAAJXZ>

externdef __imp_?GetNumber@CQueryScanner@@QEAAHAEAKAEAH@Z:PPROC
?GetNumber@CQueryScanner@@QEAAHAEAKAEAH@Z equ <__imp_?GetNumber@CQueryScanner@@QEAAHAEAKAEAH@Z>

externdef __imp_?GetNumber@CQueryScanner@@QEAAHAEAN@Z:PPROC
?GetNumber@CQueryScanner@@QEAAHAEAN@Z equ <__imp_?GetNumber@CQueryScanner@@QEAAHAEAN@Z>

externdef __imp_?GetNumber@CQueryScanner@@QEAAHAEA_JAEAH@Z:PPROC
?GetNumber@CQueryScanner@@QEAAHAEA_JAEAH@Z equ <__imp_?GetNumber@CQueryScanner@@QEAAHAEA_JAEAH@Z>

externdef __imp_?GetNumber@CQueryScanner@@QEAAHAEA_KAEAH@Z:PPROC
?GetNumber@CQueryScanner@@QEAAHAEA_KAEAH@Z equ <__imp_?GetNumber@CQueryScanner@@QEAAHAEA_KAEAH@Z>

externdef __imp_?GetOffset@CKeyDeComp@@QEAAXAEAUBitOffset@@@Z:PPROC
?GetOffset@CKeyDeComp@@QEAAXAEAUBitOffset@@@Z equ <__imp_?GetOffset@CKeyDeComp@@QEAAXAEAUBitOffset@@@Z>

externdef __imp_?GetOleDBErrorInfo@@YAJPEAUIUnknown@@AEBU_GUID@@KIPEAUtagERRORINFO@@PEAPEAUIErrorInfo@@@Z:PPROC
?GetOleDBErrorInfo@@YAJPEAUIUnknown@@AEBU_GUID@@KIPEAUtagERRORINFO@@PEAPEAUIErrorInfo@@@Z equ <__imp_?GetOleDBErrorInfo@@YAJPEAUIUnknown@@AEBU_GUID@@KIPEAUtagERRORINFO@@PEAPEAUIErrorInfo@@@Z>

externdef __imp_?GetOleError@@YAJAEAVCException@@@Z:PPROC
?GetOleError@@YAJAEAVCException@@@Z equ <__imp_?GetOleError@@YAJAEAVCException@@@Z>

externdef __imp_?GetPhysicalPath@CWebServer@@QEAAKPEBGPEAGKK@Z:PPROC
?GetPhysicalPath@CWebServer@@QEAAKPEBGPEAGKK@Z equ <__imp_?GetPhysicalPath@CWebServer@@QEAAKPEBGPEAGKK@Z>

externdef __imp_?GetPropInfo@CEmptyPropertyList@@QEAAHAEBVCDbColId@@PEAPEBGPEAGPEAI@Z:PPROC
?GetPropInfo@CEmptyPropertyList@@QEAAHAEBVCDbColId@@PEAPEBGPEAGPEAI@Z equ <__imp_?GetPropInfo@CEmptyPropertyList@@QEAAHAEBVCDbColId@@PEAPEBGPEAGPEAI@Z>

externdef __imp_?GetPropInfo@CEmptyPropertyList@@QEAAHPEBGPEAPEAVCDbColId@@PEAGPEAI@Z:PPROC
?GetPropInfo@CEmptyPropertyList@@QEAAHPEBGPEAPEAVCDbColId@@PEAGPEAI@Z equ <__imp_?GetPropInfo@CEmptyPropertyList@@QEAAHPEBGPEAPEAVCDbColId@@PEAGPEAI@Z>

externdef __imp_?GetPropInfoFromId@CEmptyPropertyList@@UEAAJPEBUtagDBID@@PEAPEAGPEAGPEAI@Z:PPROC
?GetPropInfoFromId@CEmptyPropertyList@@UEAAJPEBUtagDBID@@PEAPEAGPEAGPEAI@Z equ <__imp_?GetPropInfoFromId@CEmptyPropertyList@@UEAAJPEBUtagDBID@@PEAPEAGPEAGPEAI@Z>

externdef __imp_?GetPropInfoFromName@CEmptyPropertyList@@UEAAJPEBGPEAPEAUtagDBID@@PEAGPEAI@Z:PPROC
?GetPropInfoFromName@CEmptyPropertyList@@UEAAJPEBGPEAPEAUtagDBID@@PEAGPEAI@Z equ <__imp_?GetPropInfoFromName@CEmptyPropertyList@@UEAAJPEBGPEAPEAUtagDBID@@PEAGPEAI@Z>

externdef __imp_?GetPropType@CEmptyPropertyList@@SAGI@Z:PPROC
?GetPropType@CEmptyPropertyList@@SAGI@Z equ <__imp_?GetPropType@CEmptyPropertyList@@SAGI@Z>

externdef __imp_?GetPropTypeCount@CEmptyPropertyList@@SAIXZ:PPROC
?GetPropTypeCount@CEmptyPropertyList@@SAIXZ equ <__imp_?GetPropTypeCount@CEmptyPropertyList@@SAIXZ>

externdef __imp_?GetPropTypeName@CEmptyPropertyList@@SAPEBGI@Z:PPROC
?GetPropTypeName@CEmptyPropertyList@@SAPEBGI@Z equ <__imp_?GetPropTypeName@CEmptyPropertyList@@SAPEBGI@Z>

externdef __imp_?GetProperties@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPSET@@@Z:PPROC
?GetProperties@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPSET@@@Z equ <__imp_?GetProperties@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPSET@@@Z>

externdef __imp_?GetProperties@CGetDbProps@@QEAAXPEAUIDBProperties@@K@Z:PPROC
?GetProperties@CGetDbProps@@QEAAXPEAUIDBProperties@@K@Z equ <__imp_?GetProperties@CGetDbProps@@QEAAXPEAUIDBProperties@@K@Z>

externdef __imp_?GetPropertyInfo@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPINFOSET@@PEAPEAG@Z:PPROC
?GetPropertyInfo@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPINFOSET@@PEAPEAG@Z equ <__imp_?GetPropertyInfo@CDbProperties@@UEAAJKQEBUtagDBPROPIDSET@@PEAKPEAPEAUtagDBPROPINFOSET@@PEAPEAG@Z>

externdef __imp_?GetR4@CAllocStorageVariant@@QEBAMI@Z:PPROC
?GetR4@CAllocStorageVariant@@QEBAMI@Z equ <__imp_?GetR4@CAllocStorageVariant@@QEBAMI@Z>

externdef __imp_?GetR8@CAllocStorageVariant@@QEBANI@Z:PPROC
?GetR8@CAllocStorageVariant@@QEBANI@Z equ <__imp_?GetR8@CAllocStorageVariant@@QEBANI@Z>

externdef __imp_?GetSZParam@CMachineAdmin@@QEAAHPEBGPEAGK@Z:PPROC
?GetSZParam@CMachineAdmin@@QEAAHPEBGPEAGK@Z equ <__imp_?GetSZParam@CMachineAdmin@@QEAAHPEBGPEAGK@Z>

externdef __imp_?GetScodeError@@YAJAEAVCException@@@Z:PPROC
?GetScodeError@@YAJAEAVCException@@@Z equ <__imp_?GetScodeError@@YAJAEAVCException@@@Z>

externdef __imp_?GetSecret@@YAHPEBG0PEAPEAGPEAK@Z:PPROC
?GetSecret@@YAHPEBG0PEAPEAGPEAK@Z equ <__imp_?GetSecret@@YAHPEBG0PEAPEAGPEAK@Z>

externdef __imp_?GetSectorSize@CDriveInfo@@QEAAKXZ:PPROC
?GetSectorSize@CDriveInfo@@QEAAKXZ equ <__imp_?GetSectorSize@CDriveInfo@@QEAAKXZ>

externdef __imp_?GetSortProp@CCatState@@QEBAXIPEAPEBGPEAW4SORTDIR@@@Z:PPROC
?GetSortProp@CCatState@@QEBAXIPEAPEBGPEAW4SORTDIR@@@Z equ <__imp_?GetSortProp@CCatState@@QEBAXIPEAPEBGPEAW4SORTDIR@@@Z>

externdef __imp_?GetStackTrace@@YAXPEADK@Z:PPROC
?GetStackTrace@@YAXPEADK@Z equ <__imp_?GetStackTrace@@YAXPEADK@Z>

externdef __imp_?GetStartupData@CGenericCiProxy@@QEAAPEBEAEAU_GUID@@AEAK@Z:PPROC
?GetStartupData@CGenericCiProxy@@QEAAPEBEAEAU_GUID@@AEAK@Z equ <__imp_?GetStartupData@CGenericCiProxy@@QEAAPEBEAEAU_GUID@@AEAK@Z>

externdef __imp_?GetStorage@CPropStoreManager@@QEAAAEAVPStorage@@K@Z:PPROC
?GetStorage@CPropStoreManager@@QEAAAEAVPStorage@@K@Z equ <__imp_?GetStorage@CPropStoreManager@@QEAAAEAVPStorage@@K@Z>

externdef __imp_?GetStr@CKey@@QEBAPEAGXZ:PPROC
?GetStr@CKey@@QEBAPEAGXZ equ <__imp_?GetStr@CKey@@QEBAPEAGXZ>

externdef __imp_?GetStr@CKeyBuf@@QEBAPEAGXZ:PPROC
?GetStr@CKeyBuf@@QEBAPEAGXZ equ <__imp_?GetStr@CKeyBuf@@QEBAPEAGXZ>

externdef __imp_?GetString@CMemDeSerStream@@UEAAPEADXZ:PPROC
?GetString@CMemDeSerStream@@UEAAPEADXZ equ <__imp_?GetString@CMemDeSerStream@@UEAAPEADXZ>

externdef __imp_?GetStringDbRestriction@@YAPEAVCDbRestriction@@PEBGKPEAUIColumnMapper@@K@Z:PPROC
?GetStringDbRestriction@@YAPEAVCDbRestriction@@PEBGKPEAUIColumnMapper@@K@Z equ <__imp_?GetStringDbRestriction@@YAPEAVCDbRestriction@@PEBGKPEAUIColumnMapper@@K@Z>

externdef __imp_?GetStringFromLCID@@YAXKPEAG@Z:PPROC
?GetStringFromLCID@@YAXKPEAG@Z equ <__imp_?GetStringFromLCID@@YAXKPEAG@Z>

externdef __imp_?GetTotalSizeInKB@CPropStoreManager@@QEAAKXZ:PPROC
?GetTotalSizeInKB@CPropStoreManager@@QEAAKXZ equ <__imp_?GetTotalSizeInKB@CPropStoreManager@@QEAAKXZ>

externdef __imp_?GetTotalSizeInKB@CPropertyStore@@QEAAKXZ:PPROC
?GetTotalSizeInKB@CPropertyStore@@QEAAKXZ equ <__imp_?GetTotalSizeInKB@CPropertyStore@@QEAAKXZ>

externdef __imp_?GetULong@CMemDeSerStream@@UEAAKXZ:PPROC
?GetULong@CMemDeSerStream@@UEAAKXZ equ <__imp_?GetULong@CMemDeSerStream@@UEAAKXZ>

externdef __imp_?GetUShort@CMemDeSerStream@@UEAAGXZ:PPROC
?GetUShort@CMemDeSerStream@@UEAAGXZ equ <__imp_?GetUShort@CMemDeSerStream@@UEAAGXZ>

externdef __imp_?GetUserHdrInfo@CIndexTable@@QEAAXAEAIAEAH@Z:PPROC
?GetUserHdrInfo@CIndexTable@@QEAAXAEAIAEAH@Z equ <__imp_?GetUserHdrInfo@CIndexTable@@QEAAXAEAIAEAH@Z>

externdef __imp_?GetVPathAccess@CMetaDataMgr@@QEAAKPEBG@Z:PPROC
?GetVPathAccess@CMetaDataMgr@@QEAAKPEBG@Z equ <__imp_?GetVPathAccess@CMetaDataMgr@@QEAAKPEBG@Z>

externdef __imp_?GetVPathAuthorization@CMetaDataMgr@@QEAAKPEBG@Z:PPROC
?GetVPathAuthorization@CMetaDataMgr@@QEAAKPEBG@Z equ <__imp_?GetVPathAuthorization@CMetaDataMgr@@QEAAKPEBG@Z>

externdef __imp_?GetVPathSSLAccess@CMetaDataMgr@@QEAAKPEBG@Z:PPROC
?GetVPathSSLAccess@CMetaDataMgr@@QEAAKPEBG@Z equ <__imp_?GetVPathSSLAccess@CMetaDataMgr@@QEAAKPEBG@Z>

externdef __imp_?GetVolumeName@CDriveInfo@@QEAAPEBGH@Z:PPROC
?GetVolumeName@CDriveInfo@@QEAAPEBGH@Z equ <__imp_?GetVolumeName@CDriveInfo@@QEAAPEBGH@Z>

externdef __imp_?GetWChar@CMemDeSerStream@@UEAAXPEAGK@Z:PPROC
?GetWChar@CMemDeSerStream@@UEAAXPEAGK@Z equ <__imp_?GetWChar@CMemDeSerStream@@UEAAXPEAGK@Z>

externdef __imp_?GetWString@CMemDeSerStream@@UEAAPEAGXZ:PPROC
?GetWString@CMemDeSerStream@@UEAAPEAGXZ equ <__imp_?GetWString@CMemDeSerStream@@UEAAPEAGXZ>

externdef __imp_?GetWeight@CDbCmdTreeNode@@QEBAJXZ:PPROC
?GetWeight@CDbCmdTreeNode@@QEBAJXZ equ <__imp_?GetWeight@CDbCmdTreeNode@@QEBAJXZ>

externdef __imp_?Grow@CDynStream@@QEAAXAEAVPStorage@@K@Z:PPROC
?Grow@CDynStream@@QEAAXAEAVPStorage@@K@Z equ <__imp_?Grow@CDynStream@@QEAAXAEAVPStorage@@K@Z>

externdef __imp_?GrowBuffer@CVirtualString@@AEAAXK@Z:PPROC
?GrowBuffer@CVirtualString@@AEAAXK@Z equ <__imp_?GrowBuffer@CVirtualString@@AEAAXK@Z>

externdef __imp_?HTMLEscapeW@@YAXPEBGAEAVCVirtualString@@K@Z:PPROC
?HTMLEscapeW@@YAXPEBGAEAVCVirtualString@@K@Z equ <__imp_?HTMLEscapeW@@YAXPEBGAEAVCVirtualString@@K@Z>

externdef __imp_?Impersonate@CImpersonateClient@@AEAAXXZ:PPROC
?Impersonate@CImpersonateClient@@AEAAXXZ equ <__imp_?Impersonate@CImpersonateClient@@AEAAXXZ>

externdef __imp_?Init@CFileMapView@@QEAAXXZ:PPROC
?Init@CFileMapView@@QEAAXXZ equ <__imp_?Init@CFileMapView@@QEAAXXZ>

externdef __imp_?Init@CMmStreamConsecBuf@@QEAAXPEAVPMmStream@@@Z:PPROC
?Init@CMmStreamConsecBuf@@QEAAXPEAVPMmStream@@@Z equ <__imp_?Init@CMmStreamConsecBuf@@QEAAXPEAVPMmStream@@@Z>

externdef __imp_?Init@CPidLookupTable@@QEAAHPEAVPRcovStorageObj@@@Z:PPROC
?Init@CPidLookupTable@@QEAAHPEAVPRcovStorageObj@@@Z equ <__imp_?Init@CPidLookupTable@@QEAAHPEAVPRcovStorageObj@@@Z>

externdef __imp_?Init@CRcovStorageHdr@@QEAAXK@Z:PPROC
?Init@CRcovStorageHdr@@QEAAXK@Z equ <__imp_?Init@CRcovStorageHdr@@QEAAXK@Z>

externdef __imp_?Init@CRegChangeEvent@@QEAAXXZ:PPROC
?Init@CRegChangeEvent@@QEAAXXZ equ <__imp_?Init@CRegChangeEvent@@QEAAXXZ>

externdef __imp_?Init@CSdidLookupTable@@QEAAHPEAVCiStorage@@@Z:PPROC
?Init@CSdidLookupTable@@QEAAHPEAVCiStorage@@@Z equ <__imp_?Init@CSdidLookupTable@@QEAAHPEAVCiStorage@@@Z>

externdef __imp_?InitIterator@CPropertyList@@UEAAXXZ:PPROC
?InitIterator@CPropertyList@@UEAAXXZ equ <__imp_?InitIterator@CPropertyList@@UEAAXXZ>

externdef __imp_?Initialize@CImpersonationTokenCache@@QEAAXPEBGHHHKKK@Z:PPROC
?Initialize@CImpersonationTokenCache@@QEAAXPEBGHHHKKK@Z equ <__imp_?Initialize@CImpersonationTokenCache@@QEAAXPEBGHHHKKK@Z>

externdef __imp_?InitializeForRead@CDynStream@@QEAAXXZ:PPROC
?InitializeForRead@CDynStream@@QEAAXXZ equ <__imp_?InitializeForRead@CDynStream@@QEAAXXZ>

externdef __imp_?InitializeForWrite@CDynStream@@QEAAXK@Z:PPROC
?InitializeForWrite@CDynStream@@QEAAXK@Z equ <__imp_?InitializeForWrite@CDynStream@@QEAAXK@Z>

externdef __imp_?InsertChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z:PPROC
?InsertChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z equ <__imp_?InsertChild@CDbCmdTreeNode@@IEAAXPEAV1@@Z>

externdef __imp_?IsCIEnabled@CMachineAdmin@@QEAAHXZ:PPROC
?IsCIEnabled@CMachineAdmin@@QEAAHXZ equ <__imp_?IsCIEnabled@CMachineAdmin@@QEAAHXZ>

externdef __imp_?IsCIPaused@CMachineAdmin@@QEAAHXZ:PPROC
?IsCIPaused@CMachineAdmin@@QEAAHXZ equ <__imp_?IsCIPaused@CMachineAdmin@@QEAAHXZ>

externdef __imp_?IsCIStarted@CMachineAdmin@@QEAAHXZ:PPROC
?IsCIStarted@CMachineAdmin@@QEAAHXZ equ <__imp_?IsCIStarted@CMachineAdmin@@QEAAHXZ>

externdef __imp_?IsCIStopped@CMachineAdmin@@QEAAHXZ:PPROC
?IsCIStopped@CMachineAdmin@@QEAAHXZ equ <__imp_?IsCIStopped@CMachineAdmin@@QEAAHXZ>

externdef __imp_?IsCatalogInactive@CCatalogAdmin@@QEAAHXZ:PPROC
?IsCatalogInactive@CCatalogAdmin@@QEAAHXZ equ <__imp_?IsCatalogInactive@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?IsDirectoryWritable@@YAHPEBG@Z:PPROC
?IsDirectoryWritable@@YAHPEBG@Z equ <__imp_?IsDirectoryWritable@@YAHPEBG@Z>

externdef __imp_?IsIISAdminUp@CMetaDataMgr@@SAHAEAH@Z:PPROC
?IsIISAdminUp@CMetaDataMgr@@SAHAEAH@Z equ <__imp_?IsIISAdminUp@CMetaDataMgr@@SAHAEAH@Z>

externdef __imp_?IsImpersonated@CImpersonateSystem@@SAHXZ:PPROC
?IsImpersonated@CImpersonateSystem@@SAHXZ equ <__imp_?IsImpersonated@CImpersonateSystem@@SAHXZ>

externdef __imp_?IsLeaf@CRestriction@@QEBAHXZ:PPROC
?IsLeaf@CRestriction@@QEBAHXZ equ <__imp_?IsLeaf@CRestriction@@QEBAHXZ>

externdef __imp_?IsNullPointerVariant@@YAHPEAUtagPROPVARIANT@@@Z:PPROC
?IsNullPointerVariant@@YAHPEAUtagPROPVARIANT@@@Z equ <__imp_?IsNullPointerVariant@@YAHPEAUtagPROPVARIANT@@@Z>

externdef __imp_?IsPaused@CCatalogAdmin@@QEAAHXZ:PPROC
?IsPaused@CCatalogAdmin@@QEAAHXZ equ <__imp_?IsPaused@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?IsRunningAsSystem@CImpersonateSystem@@SAHXZ:PPROC
?IsRunningAsSystem@CImpersonateSystem@@SAHXZ equ <__imp_?IsRunningAsSystem@CImpersonateSystem@@SAHXZ>

externdef __imp_?IsSameDrive@CDriveInfo@@QEAAHPEBG@Z:PPROC
?IsSameDrive@CDriveInfo@@QEAAHPEBG@Z equ <__imp_?IsSameDrive@CDriveInfo@@QEAAHPEBG@Z>

externdef __imp_?IsScopeValid@@YAJPEBGIH@Z:PPROC
?IsScopeValid@@YAJPEBGIH@Z equ <__imp_?IsScopeValid@@YAJPEBGIH@Z>

externdef __imp_?IsStarted@CCatalogAdmin@@QEAAHXZ:PPROC
?IsStarted@CCatalogAdmin@@QEAAHXZ equ <__imp_?IsStarted@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?IsStopped@CCatalogAdmin@@QEAAHXZ:PPROC
?IsStopped@CCatalogAdmin@@QEAAHXZ equ <__imp_?IsStopped@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?IsValid@CAllocStorageVariant@@QEBAHXZ:PPROC
?IsValid@CAllocStorageVariant@@QEBAHXZ equ <__imp_?IsValid@CAllocStorageVariant@@QEBAHXZ>

externdef __imp_?IsValid@CNodeRestriction@@QEBAHXZ:PPROC
?IsValid@CNodeRestriction@@QEBAHXZ equ <__imp_?IsValid@CNodeRestriction@@QEBAHXZ>

externdef __imp_?IsValid@COccRestriction@@QEBAHXZ:PPROC
?IsValid@COccRestriction@@QEBAHXZ equ <__imp_?IsValid@COccRestriction@@QEBAHXZ>

externdef __imp_?IsValid@CRestriction@@QEBAHXZ:PPROC
?IsValid@CRestriction@@QEBAHXZ equ <__imp_?IsValid@CRestriction@@QEBAHXZ>

externdef __imp_?IsWaitingForDocument@CFilterDaemon@@QEAAHXZ:PPROC
?IsWaitingForDocument@CFilterDaemon@@QEAAHXZ equ <__imp_?IsWaitingForDocument@CFilterDaemon@@QEAAHXZ>

externdef __imp_?IsWriteProtected@CDriveInfo@@QEAAHXZ:PPROC
?IsWriteProtected@CDriveInfo@@QEAAHXZ equ <__imp_?IsWriteProtected@CDriveInfo@@QEAAHXZ>

externdef __imp_?Load@CLocalGlobalPropertyList@@QEAAXQEBG@Z:PPROC
?Load@CLocalGlobalPropertyList@@QEAAXQEBG@Z equ <__imp_?Load@CLocalGlobalPropertyList@@QEAAXQEBG@Z>

externdef __imp_?LocaleToCodepage@@YAKK@Z:PPROC
?LocaleToCodepage@@YAKK@Z equ <__imp_?LocaleToCodepage@@YAKK@Z>

externdef __imp_?LokNewWorkId@CPropertyStore@@AEAAKKHH@Z:PPROC
?LokNewWorkId@CPropertyStore@@AEAAKKHH@Z equ <__imp_?LokNewWorkId@CPropertyStore@@AEAAKKHH@Z>

externdef __imp_?LokUpdate@CCatStateInfo@@QEAAHXZ:PPROC
?LokUpdate@CCatStateInfo@@QEAAHXZ equ <__imp_?LokUpdate@CCatStateInfo@@QEAAHXZ>

externdef __imp_?LongInit@CPropStoreManager@@QEAAXAEAHAEAKP6AXKHPEBX@Z2@Z:PPROC
?LongInit@CPropStoreManager@@QEAAXAEAHAEAKP6AXKHPEBX@Z2@Z equ <__imp_?LongInit@CPropStoreManager@@QEAAXAEAHAEAKP6AXKHPEBX@Z2@Z>

externdef __imp_?Lookup@CPropStoreInfo@@AEAAIK@Z:PPROC
?Lookup@CPropStoreInfo@@AEAAIK@Z equ <__imp_?Lookup@CPropStoreInfo@@AEAAIK@Z>

externdef __imp_?LookupSDID@CSdidLookupTable@@QEAAKPEAXK@Z:PPROC
?LookupSDID@CSdidLookupTable@@QEAAKPEAXK@Z equ <__imp_?LookupSDID@CSdidLookupTable@@QEAAKPEAXK@Z>

externdef __imp_?MakeBackupCopy@CPhysStorage@@QEAAXAEAV1@AEAVPSaveProgressTracker@@@Z:PPROC
?MakeBackupCopy@CPhysStorage@@QEAAXAEAV1@AEAVPSaveProgressTracker@@@Z equ <__imp_?MakeBackupCopy@CPhysStorage@@QEAAXAEAV1@AEAVPSaveProgressTracker@@@Z>

externdef __imp_?MakeBackupCopy@CPidLookupTable@@QEAAXAEAVPRcovStorageObj@@AEAVPSaveProgressTracker@@@Z:PPROC
?MakeBackupCopy@CPidLookupTable@@QEAAXAEAVPRcovStorageObj@@AEAVPSaveProgressTracker@@@Z equ <__imp_?MakeBackupCopy@CPidLookupTable@@QEAAXAEAVPRcovStorageObj@@AEAVPSaveProgressTracker@@@Z>

externdef __imp_?MakeBackupCopy@CPropStoreManager@@QEAAXPEAUIProgressNotify@@AEAHAEAVCiStorage@@PEAUICiEnumWorkids@@PEAPEAUIEnumString@@@Z:PPROC
?MakeBackupCopy@CPropStoreManager@@QEAAXPEAUIProgressNotify@@AEAHAEAVCiStorage@@PEAUICiEnumWorkids@@PEAPEAUIEnumString@@@Z equ <__imp_?MakeBackupCopy@CPropStoreManager@@QEAAXPEAUIProgressNotify@@AEAHAEAVCiStorage@@PEAUICiEnumWorkids@@PEAPEAUIEnumString@@@Z>

externdef __imp_?MakeICommand@@YAJPEAPEAUIUnknown@@PEBG1PEAU1@@Z:PPROC
?MakeICommand@@YAJPEAPEAUIUnknown@@PEBG1PEAU1@@Z equ <__imp_?MakeICommand@@YAJPEAPEAUIUnknown@@PEBG1PEAU1@@Z>

externdef __imp_?MakeISearch@@YAJPEAPEAUISearchQueryHits@@PEAVCDbRestriction@@PEBG@Z:PPROC
?MakeISearch@@YAJPEAPEAUISearchQueryHits@@PEAVCDbRestriction@@PEBG@Z equ <__imp_?MakeISearch@@YAJPEAPEAUISearchQueryHits@@PEAVCDbRestriction@@PEBG@Z>

externdef __imp_?MakeLocalICommand@@YAJPEAPEAUIUnknown@@PEAUICiCDocStore@@PEAU1@@Z:PPROC
?MakeLocalICommand@@YAJPEAPEAUIUnknown@@PEAUICiCDocStore@@PEAU1@@Z equ <__imp_?MakeLocalICommand@@YAJPEAPEAUIUnknown@@PEAUICiCDocStore@@PEAU1@@Z>

externdef __imp_?MakeMetadataICommand@@YAJPEAPEAUIUnknown@@W4CiMetaData@@PEBG2PEAU1@@Z:PPROC
?MakeMetadataICommand@@YAJPEAPEAUIUnknown@@W4CiMetaData@@PEBG2PEAU1@@Z equ <__imp_?MakeMetadataICommand@@YAJPEAPEAUIUnknown@@W4CiMetaData@@PEBG2PEAU1@@Z>

externdef __imp_?MakePath@CFullPath@@QEAAXPEBG@Z:PPROC
?MakePath@CFullPath@@QEAAXPEBG@Z equ <__imp_?MakePath@CFullPath@@QEAAXPEBG@Z>

externdef __imp_?MakePath@CFullPath@@QEAAXPEBGI@Z:PPROC
?MakePath@CFullPath@@QEAAXPEBGI@Z equ <__imp_?MakePath@CFullPath@@QEAAXPEBGI@Z>

externdef __imp_?MakePrivileged@CImpersonateSystem@@AEAAXXZ:PPROC
?MakePrivileged@CImpersonateSystem@@AEAAXXZ equ <__imp_?MakePrivileged@CImpersonateSystem@@AEAAXXZ>

externdef __imp_?Map@CMmStreamConsecBuf@@QEAAXK@Z:PPROC
?Map@CMmStreamConsecBuf@@QEAAXK@Z equ <__imp_?Map@CMmStreamConsecBuf@@QEAAXK@Z>

externdef __imp_?MarkDirty@CDynStream@@QEAAHXZ:PPROC
?MarkDirty@CDynStream@@QEAAHXZ equ <__imp_?MarkDirty@CDynStream@@QEAAHXZ>

externdef __imp_?Marshall@CBaseStorageVariant@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CBaseStorageVariant@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CBaseStorageVariant@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CContentRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CContentRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CContentRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CDbCmdTreeNode@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CDbCmdTreeNode@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CDbCmdTreeNode@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CFullPropSpec@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CFullPropSpec@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CFullPropSpec@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CNatLanguageRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CNatLanguageRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CNatLanguageRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CNodeRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CNodeRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CNodeRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CNotRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CNotRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CNotRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CPropNameArray@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CPropNameArray@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CPropNameArray@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CPropertyRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CPropertyRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CPropertyRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Marshall@CVectorRestriction@@QEBAXAEAVPSerStream@@@Z:PPROC
?Marshall@CVectorRestriction@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Marshall@CVectorRestriction@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?MinPageInUse@CBufferCache@@QEAAHAEAK@Z:PPROC
?MinPageInUse@CBufferCache@@QEAAHAEAK@Z equ <__imp_?MinPageInUse@CBufferCache@@QEAAHAEAK@Z>

externdef __imp_?MinPageInUse@CPhysStorage@@QEAAHAEAK@Z:PPROC
?MinPageInUse@CPhysStorage@@QEAAHAEAK@Z equ <__imp_?MinPageInUse@CPhysStorage@@QEAAHAEAK@Z>

externdef __imp_?MultiByteToXArrayWideChar@@YAKPEBEKIAEAV?$XArray@G@@@Z:PPROC
?MultiByteToXArrayWideChar@@YAKPEBEKIAEAV?$XArray@G@@@Z equ <__imp_?MultiByteToXArrayWideChar@@YAKPEBEKIAEAV?$XArray@G@@@Z>

externdef __imp_?My_wcstoui64@@YA_KPEBGPEAPEAGH@Z:PPROC
?My_wcstoui64@@YA_KPEBGPEAPEAGH@Z equ <__imp_?My_wcstoui64@@YA_KPEBGPEAPEAGH@Z>

externdef __imp_?NameToReal@CPidRemapper@@QEAAKPEBVCFullPropSpec@@@Z:PPROC
?NameToReal@CPidRemapper@@QEAAKPEBVCFullPropSpec@@@Z equ <__imp_?NameToReal@CPidRemapper@@QEAAKPEBVCFullPropSpec@@@Z>

externdef __imp_?NewStemmer@CCiOle@@SAPEAUIStemmer@@AEBU_GUID@@@Z:PPROC
?NewStemmer@CCiOle@@SAPEAUIStemmer@@AEBU_GUID@@@Z equ <__imp_?NewStemmer@CCiOle@@SAPEAUIStemmer@@AEBU_GUID@@@Z>

externdef __imp_?NewWordBreaker@CCiOle@@SAPEAUIWordBreaker@@AEBU_GUID@@@Z:PPROC
?NewWordBreaker@CCiOle@@SAPEAUIWordBreaker@@AEBU_GUID@@@Z equ <__imp_?NewWordBreaker@CCiOle@@SAPEAUIWordBreaker@@AEBU_GUID@@@Z>

externdef __imp_?Next@CCatalogEnum@@QEAAHXZ:PPROC
?Next@CCatalogEnum@@QEAAHXZ equ <__imp_?Next@CCatalogEnum@@QEAAHXZ>

externdef __imp_?Next@CEnumString@@UEAAJKPEAPEAGPEAK@Z:PPROC
?Next@CEnumString@@UEAAJKPEAPEAGPEAK@Z equ <__imp_?Next@CEnumString@@UEAAJKPEAPEAGPEAK@Z>

externdef __imp_?Next@CEnumWorkid@@UEAAJKPEAK0@Z:PPROC
?Next@CEnumWorkid@@UEAAJKPEAK0@Z equ <__imp_?Next@CEnumWorkid@@UEAAJKPEAK0@Z>

externdef __imp_?Next@CPropertyList@@UEAAPEBVCPropEntry@@XZ:PPROC
?Next@CPropertyList@@UEAAPEBVCPropEntry@@XZ equ <__imp_?Next@CPropertyList@@UEAAPEBVCPropEntry@@XZ>

externdef __imp_?Next@CScopeEnum@@QEAAHXZ:PPROC
?Next@CScopeEnum@@QEAAHXZ equ <__imp_?Next@CScopeEnum@@QEAAHXZ>

externdef __imp_?NextWorkId@CPropertyStoreWids@@QEAAKXZ:PPROC
?NextWorkId@CPropertyStoreWids@@QEAAKXZ equ <__imp_?NextWorkId@CPropertyStoreWids@@QEAAKXZ>

externdef __imp_?NumberOfColumns@CCatState@@QEBAIXZ:PPROC
?NumberOfColumns@CCatState@@QEBAIXZ equ <__imp_?NumberOfColumns@CCatState@@QEBAIXZ>

externdef __imp_?NumberOfSortProps@CCatState@@QEBAIXZ:PPROC
?NumberOfSortProps@CCatState@@QEBAIXZ equ <__imp_?NumberOfSortProps@CCatState@@QEBAIXZ>

externdef __imp_?Open@CMmStream@@QEAAXPEBGKKKKH@Z:PPROC
?Open@CMmStream@@QEAAXPEBGKKKKH@Z equ <__imp_?Open@CMmStream@@QEAAXPEBGKKKKH@Z>

externdef __imp_?Open@COLEPropManager@@QEAAHAEBVCFunnyPath@@@Z:PPROC
?Open@COLEPropManager@@QEAAHAEBVCFunnyPath@@@Z equ <__imp_?Open@COLEPropManager@@QEAAHAEBVCFunnyPath@@@Z>

externdef __imp_?OpenExclusive@CMmStream@@QEAAXPEAGH@Z:PPROC
?OpenExclusive@CMmStream@@QEAAXPEAGH@Z equ <__imp_?OpenExclusive@CMmStream@@QEAAXPEAGH@Z>

externdef __imp_?OpenFileFromPath@@YAPEAU_iobuf@@PEBG@Z:PPROC
?OpenFileFromPath@@YAPEAU_iobuf@@PEBG@Z equ <__imp_?OpenFileFromPath@@YAPEAU_iobuf@@PEBG@Z>

externdef __imp_?OpenRecord@CPropStoreManager@@QEAAPEAVCCompositePropRecord@@KPEAE@Z:PPROC
?OpenRecord@CPropStoreManager@@QEAAPEAVCCompositePropRecord@@KPEAE@Z equ <__imp_?OpenRecord@CPropStoreManager@@QEAAPEAVCCompositePropRecord@@KPEAE@Z>

externdef __imp_?OpenRecordForWrites@CPropStoreManager@@QEAAPEAVCCompositePropRecordForWrites@@KPEAE@Z:PPROC
?OpenRecordForWrites@CPropStoreManager@@QEAAPEAVCCompositePropRecordForWrites@@KPEAE@Z equ <__imp_?OpenRecordForWrites@CPropStoreManager@@QEAAPEAVCCompositePropRecordForWrites@@KPEAE@Z>

externdef __imp_?ParseCatalogURL@@YAJPEBGAEAV?$XPtrST@G@@1@Z:PPROC
?ParseCatalogURL@@YAJPEBGAEAV?$XPtrST@G@@1@Z equ <__imp_?ParseCatalogURL@@YAJPEBGAEAV?$XPtrST@G@@1@Z>

externdef __imp_?ParseExpression@CParseCommandTree@@QEAAPEAVCRestriction@@PEAVCDbCmdTreeNode@@@Z:PPROC
?ParseExpression@CParseCommandTree@@QEAAPEAVCRestriction@@PEAVCDbCmdTreeNode@@@Z equ <__imp_?ParseExpression@CParseCommandTree@@QEAAPEAVCRestriction@@PEAVCDbCmdTreeNode@@@Z>

externdef __imp_?ParseOneLine@CPropertyList@@SAXAEAVCQueryScanner@@HAEAV?$XPtr@VCPropEntry@@@@@Z:PPROC
?ParseOneLine@CPropertyList@@SAXAEAVCQueryScanner@@HAEAV?$XPtr@VCPropEntry@@@@@Z equ <__imp_?ParseOneLine@CPropertyList@@SAXAEAVCQueryScanner@@HAEAV?$XPtr@VCPropEntry@@@@@Z>

externdef __imp_?ParseQueryPhrase@CQueryParser@@QEAAPEAVCDbRestriction@@XZ:PPROC
?ParseQueryPhrase@CQueryParser@@QEAAPEAVCDbRestriction@@XZ equ <__imp_?ParseQueryPhrase@CQueryParser@@QEAAPEAVCDbRestriction@@XZ>

externdef __imp_?ParseStringColumns@@YAPEAVCDbColumns@@PEBGPEAUIColumnMapper@@KPEAVPVariableSet@@PEAV?$CDynArray@G@@@Z:PPROC
?ParseStringColumns@@YAPEAVCDbColumns@@PEBGPEAUIColumnMapper@@KPEAVPVariableSet@@PEAV?$CDynArray@G@@@Z equ <__imp_?ParseStringColumns@@YAPEAVCDbColumns@@PEBGPEAUIColumnMapper@@KPEAVPVariableSet@@PEAV?$CDynArray@G@@@Z>

externdef __imp_?Pause@CCatalogAdmin@@QEAAHXZ:PPROC
?Pause@CCatalogAdmin@@QEAAHXZ equ <__imp_?Pause@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?PauseCI@CMachineAdmin@@QEAAHXZ:PPROC
?PauseCI@CMachineAdmin@@QEAAHXZ equ <__imp_?PauseCI@CMachineAdmin@@QEAAHXZ>

externdef __imp_?PeekULong@CMemDeSerStream@@UEAAKXZ:PPROC
?PeekULong@CMemDeSerStream@@UEAAKXZ equ <__imp_?PeekULong@CMemDeSerStream@@UEAAKXZ>

externdef __imp_?PidToRealPid@CPidMapper@@QEAAKK@Z:PPROC
?PidToRealPid@CPidMapper@@QEAAKK@Z equ <__imp_?PidToRealPid@CPidMapper@@QEAAKK@Z>

externdef __imp_?PropertyToPropId@CStandardPropMapper@@QEAAKAEBVCFullPropSpec@@H@Z:PPROC
?PropertyToPropId@CStandardPropMapper@@QEAAKAEBVCFullPropSpec@@H@Z equ <__imp_?PropertyToPropId@CStandardPropMapper@@QEAAKAEBVCFullPropSpec@@H@Z>

externdef __imp_?PropertyToPropid@CFwPropertyMapper@@UEAAJPEBUtagFULLPROPSPEC@@HPEAK@Z:PPROC
?PropertyToPropid@CFwPropertyMapper@@UEAAJPEBUtagFULLPROPSPEC@@HPEAK@Z equ <__imp_?PropertyToPropid@CFwPropertyMapper@@UEAAJPEBUtagFULLPROPSPEC@@HPEAK@Z>

externdef __imp_?PutMaxValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z:PPROC
?PutMaxValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z equ <__imp_?PutMaxValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z>

externdef __imp_?PutMinValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z:PPROC
?PutMinValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z equ <__imp_?PutMinValue@CValueNormalizer@@QEAAXKAEAKW4VARENUM@@@Z>

externdef __imp_?PutValue@CValueNormalizer@@QEAAXKAEAKAEBVCStorageVariant@@@Z:PPROC
?PutValue@CValueNormalizer@@QEAAXKAEAKAEBVCStorageVariant@@@Z equ <__imp_?PutValue@CValueNormalizer@@QEAAXKAEAKAEBVCStorageVariant@@@Z>

externdef __imp_?PutWString@@YAXAEAVPSerStream@@PEBG@Z:PPROC
?PutWString@@YAXAEAVPSerStream@@PEBG@Z equ <__imp_?PutWString@@YAXAEAVPSerStream@@PEBG@Z>

externdef __imp_?Query@CQueryParser@@AEAAPEAVCDbRestriction@@PEAVCDbNodeRestriction@@@Z:PPROC
?Query@CQueryParser@@AEAAPEAVCDbRestriction@@PEAVCDbNodeRestriction@@@Z equ <__imp_?Query@CQueryParser@@AEAAPEAVCDbRestriction@@PEAVCDbNodeRestriction@@@Z>

externdef __imp_?QueryCatalogAdmin@CCatalogEnum@@QEAAPEAVCCatalogAdmin@@XZ:PPROC
?QueryCatalogAdmin@CCatalogEnum@@QEAAPEAVCCatalogAdmin@@XZ equ <__imp_?QueryCatalogAdmin@CCatalogEnum@@QEAAPEAVCCatalogAdmin@@XZ>

externdef __imp_?QueryCatalogAdmin@CMachineAdmin@@QEAAPEAVCCatalogAdmin@@PEBG@Z:PPROC
?QueryCatalogAdmin@CMachineAdmin@@QEAAPEAVCCatalogAdmin@@PEBG@Z equ <__imp_?QueryCatalogAdmin@CMachineAdmin@@QEAAPEAVCCatalogAdmin@@PEBG@Z>

externdef __imp_?QueryCatalogEnum@CMachineAdmin@@QEAAPEAVCCatalogEnum@@XZ:PPROC
?QueryCatalogEnum@CMachineAdmin@@QEAAPEAVCCatalogEnum@@XZ equ <__imp_?QueryCatalogEnum@CMachineAdmin@@QEAAPEAVCCatalogEnum@@XZ>

externdef __imp_?QueryInterface@CDbProperties@@UEAAJAEBU_GUID@@PEAPEAX@Z:PPROC
?QueryInterface@CDbProperties@@UEAAJAEBU_GUID@@PEAPEAX@Z equ <__imp_?QueryInterface@CDbProperties@@UEAAJAEBU_GUID@@PEAPEAX@Z>

externdef __imp_?QueryInterface@CEmptyPropertyList@@UEAAJAEBU_GUID@@PEAPEAX@Z:PPROC
?QueryInterface@CEmptyPropertyList@@UEAAJAEBU_GUID@@PEAPEAX@Z equ <__imp_?QueryInterface@CEmptyPropertyList@@UEAAJAEBU_GUID@@PEAPEAX@Z>

externdef __imp_?QueryInterface@CEnumString@@UEAAJAEBU_GUID@@PEAPEAX@Z:PPROC
?QueryInterface@CEnumString@@UEAAJAEBU_GUID@@PEAPEAX@Z equ <__imp_?QueryInterface@CEnumString@@UEAAJAEBU_GUID@@PEAPEAX@Z>

externdef __imp_?QueryInterface@CEnumWorkid@@UEAAJAEBU_GUID@@PEAPEAX@Z:PPROC
?QueryInterface@CEnumWorkid@@UEAAJAEBU_GUID@@PEAPEAX@Z equ <__imp_?QueryInterface@CEnumWorkid@@UEAAJAEBU_GUID@@PEAPEAX@Z>

externdef __imp_?QueryInterface@CFwPropertyMapper@@UEAAJAEBU_GUID@@PEAPEAX@Z:PPROC
?QueryInterface@CFwPropertyMapper@@UEAAJAEBU_GUID@@PEAPEAX@Z equ <__imp_?QueryInterface@CFwPropertyMapper@@UEAAJAEBU_GUID@@PEAPEAX@Z>

externdef __imp_?QueryInterface@CQueryUnknown@@UEAAJAEBU_GUID@@PEAPEAX@Z:PPROC
?QueryInterface@CQueryUnknown@@UEAAJAEBU_GUID@@PEAPEAX@Z equ <__imp_?QueryInterface@CQueryUnknown@@UEAAJAEBU_GUID@@PEAPEAX@Z>

externdef __imp_?QueryPidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PPROC
?QueryPidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z equ <__imp_?QueryPidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>

externdef __imp_?QueryScopeAdmin@CCatalogAdmin@@QEAAPEAVCScopeAdmin@@PEBG@Z:PPROC
?QueryScopeAdmin@CCatalogAdmin@@QEAAPEAVCScopeAdmin@@PEBG@Z equ <__imp_?QueryScopeAdmin@CCatalogAdmin@@QEAAPEAVCScopeAdmin@@PEBG@Z>

externdef __imp_?QueryScopeAdmin@CScopeEnum@@QEAAPEAVCScopeAdmin@@XZ:PPROC
?QueryScopeAdmin@CScopeEnum@@QEAAPEAVCScopeAdmin@@XZ equ <__imp_?QueryScopeAdmin@CScopeEnum@@QEAAPEAVCScopeAdmin@@XZ>

externdef __imp_?QueryScopeEnum@CCatalogAdmin@@QEAAPEAVCScopeEnum@@XZ:PPROC
?QueryScopeEnum@CCatalogAdmin@@QEAAPEAVCScopeEnum@@XZ equ <__imp_?QueryScopeEnum@CCatalogAdmin@@QEAAPEAVCScopeEnum@@XZ>

externdef __imp_?QueryScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PPROC
?QueryScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z equ <__imp_?QueryScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>

externdef __imp_?QuerySdidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PPROC
?QuerySdidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z equ <__imp_?QuerySdidLookupTable@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>

externdef __imp_?QueryVirtualScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z:PPROC
?QueryVirtualScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z equ <__imp_?QueryVirtualScopeList@CiStorage@@QEAAPEAVPRcovStorageObj@@K@Z>

externdef __imp_?ReBuild@CPidRemapper@@QEAAXAEBVCPidMapper@@@Z:PPROC
?ReBuild@CPidRemapper@@QEAAXAEBVCPidMapper@@@Z equ <__imp_?ReBuild@CPidRemapper@@QEAAXAEBVCPidMapper@@@Z>

externdef __imp_?ReInit@CQueryUnknown@@QEAAXKPEAPEAVCRowset@@@Z:PPROC
?ReInit@CQueryUnknown@@QEAAXKPEAPEAVCRowset@@@Z equ <__imp_?ReInit@CQueryUnknown@@QEAAXKPEAPEAVCRowset@@@Z>

externdef __imp_?ReInitializeIISScopes@CImpersonationTokenCache@@QEAAXXZ:PPROC
?ReInitializeIISScopes@CImpersonationTokenCache@@QEAAXXZ equ <__imp_?ReInitializeIISScopes@CImpersonationTokenCache@@QEAAXXZ>

externdef __imp_?ReOpenStream@CPhysIndex@@EEAAXXZ:PPROC
?ReOpenStream@CPhysIndex@@EEAAXXZ equ <__imp_?ReOpenStream@CPhysIndex@@EEAAXXZ>

externdef __imp_?Read@CDynStream@@QEAAKPEAXK@Z:PPROC
?Read@CDynStream@@QEAAKPEAXK@Z equ <__imp_?Read@CDynStream@@QEAAKPEAXK@Z>

externdef __imp_?Read@CRcovStrmTrans@@QEAAKPEAXK@Z:PPROC
?Read@CRcovStrmTrans@@QEAAKPEAXK@Z equ <__imp_?Read@CRcovStrmTrans@@QEAAKPEAXK@Z>

externdef __imp_?Read@CRegAccess@@QEAAKPEBGK@Z:PPROC
?Read@CRegAccess@@QEAAKPEBGK@Z equ <__imp_?Read@CRegAccess@@QEAAKPEBGK@Z>

externdef __imp_?Read@CRegAccess@@QEAAPEAGPEBG0@Z:PPROC
?Read@CRegAccess@@QEAAPEAGPEBG0@Z equ <__imp_?Read@CRegAccess@@QEAAPEAGPEBG0@Z>

externdef __imp_?ReadPrimaryProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z:PPROC
?ReadPrimaryProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z equ <__imp_?ReadPrimaryProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z>

externdef __imp_?ReadProperty@COLEPropManager@@QEAAHAEBVCFullPropSpec@@AEAUtagPROPVARIANT@@@Z:PPROC
?ReadProperty@COLEPropManager@@QEAAHAEBVCFullPropSpec@@AEAUtagPROPVARIANT@@@Z equ <__imp_?ReadProperty@COLEPropManager@@QEAAHAEBVCFullPropSpec@@AEAUtagPROPVARIANT@@@Z>

externdef __imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@@Z:PPROC
?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@@Z equ <__imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@@Z>

externdef __imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@PEAEPEAI@Z:PPROC
?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@PEAEPEAI@Z equ <__imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KAEAUtagPROPVARIANT@@PEAEPEAI@Z>

externdef __imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KPEAUtagPROPVARIANT@@PEAI@Z:PPROC
?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KPEAUtagPROPVARIANT@@PEAI@Z equ <__imp_?ReadProperty@CPropStoreManager@@QEAAHAEAVCCompositePropRecord@@KPEAUtagPROPVARIANT@@PEAI@Z>

externdef __imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z:PPROC
?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z equ <__imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@@Z>

externdef __imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@PEAEPEAI@Z:PPROC
?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@PEAEPEAI@Z equ <__imp_?ReadProperty@CPropStoreManager@@QEAAHKKAEAUtagPROPVARIANT@@PEAEPEAI@Z>

externdef __imp_?ReadProperty@CPropStoreManager@@QEAAHKKPEAUtagPROPVARIANT@@PEAI@Z:PPROC
?ReadProperty@CPropStoreManager@@QEAAHKKPEAUtagPROPVARIANT@@PEAI@Z equ <__imp_?ReadProperty@CPropStoreManager@@QEAAHKKPEAUtagPROPVARIANT@@PEAI@Z>

externdef __imp_?ReadProperty@CPropertyStore@@QEAAHAEAVCPropRecordNoLock@@KPEAUtagPROPVARIANT@@PEAI@Z:PPROC
?ReadProperty@CPropertyStore@@QEAAHAEAVCPropRecordNoLock@@KPEAUtagPROPVARIANT@@PEAI@Z equ <__imp_?ReadProperty@CPropertyStore@@QEAAHAEAVCPropRecordNoLock@@KPEAUtagPROPVARIANT@@PEAI@Z>

externdef __imp_?ReadProperty@CPropertyStore@@QEAAHKKAEAUtagPROPVARIANT@@@Z:PPROC
?ReadProperty@CPropertyStore@@QEAAHKKAEAUtagPROPVARIANT@@@Z equ <__imp_?ReadProperty@CPropertyStore@@QEAAHKKAEAUtagPROPVARIANT@@@Z>

externdef __imp_?Recognize@CDFA@@QEAAEPEBG@Z:PPROC
?Recognize@CDFA@@QEAAEPEBG@Z equ <__imp_?Recognize@CDFA@@QEAAEPEBG@Z>

externdef __imp_?Refresh@CCiRegParams@@QEAAXPEAUICiAdminParams@@H@Z:PPROC
?Refresh@CCiRegParams@@QEAAXPEAUICiAdminParams@@H@Z equ <__imp_?Refresh@CCiRegParams@@QEAAXPEAUICiAdminParams@@H@Z>

externdef __imp_?Refresh@CDefColumnRegEntry@@QEAAXH@Z:PPROC
?Refresh@CDefColumnRegEntry@@QEAAXH@Z equ <__imp_?Refresh@CDefColumnRegEntry@@QEAAXH@Z>

externdef __imp_?RefreshParams@CWorkQueue@@QEAAXKK@Z:PPROC
?RefreshParams@CWorkQueue@@QEAAXKK@Z equ <__imp_?RefreshParams@CWorkQueue@@QEAAXKK@Z>

externdef __imp_?Release@CDbProperties@@UEAAKXZ:PPROC
?Release@CDbProperties@@UEAAKXZ equ <__imp_?Release@CDbProperties@@UEAAKXZ>

externdef __imp_?Release@CEmptyPropertyList@@UEAAKXZ:PPROC
?Release@CEmptyPropertyList@@UEAAKXZ equ <__imp_?Release@CEmptyPropertyList@@UEAAKXZ>

externdef __imp_?Release@CEnumString@@UEAAKXZ:PPROC
?Release@CEnumString@@UEAAKXZ equ <__imp_?Release@CEnumString@@UEAAKXZ>

externdef __imp_?Release@CEnumWorkid@@UEAAKXZ:PPROC
?Release@CEnumWorkid@@UEAAKXZ equ <__imp_?Release@CEnumWorkid@@UEAAKXZ>

externdef __imp_?Release@CFwPropertyMapper@@UEAAKXZ:PPROC
?Release@CFwPropertyMapper@@UEAAKXZ equ <__imp_?Release@CFwPropertyMapper@@UEAAKXZ>

externdef __imp_?Release@CImpersonateRemoteAccess@@QEAAXXZ:PPROC
?Release@CImpersonateRemoteAccess@@QEAAXXZ equ <__imp_?Release@CImpersonateRemoteAccess@@QEAAXXZ>

externdef __imp_?Release@CQueryUnknown@@UEAAKXZ:PPROC
?Release@CQueryUnknown@@UEAAKXZ equ <__imp_?Release@CQueryUnknown@@UEAAKXZ>

externdef __imp_?Release@CWorkQueue@@QEAAXPEAVCWorkThread@@@Z:PPROC
?Release@CWorkQueue@@QEAAXPEAVCWorkThread@@@Z equ <__imp_?Release@CWorkQueue@@QEAAXPEAVCWorkThread@@@Z>

externdef __imp_?ReleaseRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z:PPROC
?ReleaseRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z equ <__imp_?ReleaseRead@CPropertyStore@@AEAAXAEAVCReadWriteLockRecord@@@Z>

externdef __imp_?ReleaseWorkThreads@CWorkQueue@@QEAAXXZ:PPROC
?ReleaseWorkThreads@CWorkQueue@@QEAAXXZ equ <__imp_?ReleaseWorkThreads@CWorkQueue@@QEAAXXZ>

externdef __imp_?Remove@CColumns@@QEAAXI@Z:PPROC
?Remove@CColumns@@QEAAXI@Z equ <__imp_?Remove@CColumns@@QEAAXI@Z>

externdef __imp_?Remove@CDbSortSet@@QEAAXI@Z:PPROC
?Remove@CDbSortSet@@QEAAXI@Z equ <__imp_?Remove@CDbSortSet@@QEAAXI@Z>

externdef __imp_?Remove@CSort@@QEAAXI@Z:PPROC
?Remove@CSort@@QEAAXI@Z equ <__imp_?Remove@CSort@@QEAAXI@Z>

externdef __imp_?Remove@CWorkQueue@@AEAAXAEAVCWorkThread@@@Z:PPROC
?Remove@CWorkQueue@@AEAAXAEAVCWorkThread@@@Z equ <__imp_?Remove@CWorkQueue@@AEAAXAEAVCWorkThread@@@Z>

externdef __imp_?Remove@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z:PPROC
?Remove@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z equ <__imp_?Remove@CWorkQueue@@QEAAXPEAVPWorkItem@@@Z>

externdef __imp_?RemoveCatalog@CMachineAdmin@@QEAAXPEBGH@Z:PPROC
?RemoveCatalog@CMachineAdmin@@QEAAXPEBGH@Z equ <__imp_?RemoveCatalog@CMachineAdmin@@QEAAXPEBGH@Z>

externdef __imp_?RemoveCatalogFiles@CMachineAdmin@@QEAAXPEBG@Z:PPROC
?RemoveCatalogFiles@CMachineAdmin@@QEAAXPEBG@Z equ <__imp_?RemoveCatalogFiles@CMachineAdmin@@QEAAXPEBG@Z>

externdef __imp_?RemoveChild@CNodeRestriction@@QEAAPEAVCRestriction@@I@Z:PPROC
?RemoveChild@CNodeRestriction@@QEAAPEAVCRestriction@@I@Z equ <__imp_?RemoveChild@CNodeRestriction@@QEAAPEAVCRestriction@@I@Z>

externdef __imp_?RemoveFirstChild@CDbCmdTreeNode@@IEAAPEAV1@XZ:PPROC
?RemoveFirstChild@CDbCmdTreeNode@@IEAAPEAV1@XZ equ <__imp_?RemoveFirstChild@CDbCmdTreeNode@@IEAAPEAV1@XZ>

externdef __imp_?RemoveScope@CCatalogAdmin@@QEAAXPEBG@Z:PPROC
?RemoveScope@CCatalogAdmin@@QEAAXPEBG@Z equ <__imp_?RemoveScope@CCatalogAdmin@@QEAAXPEBG@Z>

externdef __imp_?Reopen@CPhysStorage@@QEAAXH@Z:PPROC
?Reopen@CPhysStorage@@QEAAXH@Z equ <__imp_?Reopen@CPhysStorage@@QEAAXH@Z>

externdef __imp_?ReportEventW@CEventLog@@QEAAXAEAVCEventItem@@@Z:PPROC
?ReportEventW@CEventLog@@QEAAXAEAVCEventItem@@@Z equ <__imp_?ReportEventW@CEventLog@@QEAAXAEAVCEventItem@@@Z>

externdef __imp_?ReportEventW@CFwEventItem@@QEAAXAEAUICiCAdviseStatus@@@Z:PPROC
?ReportEventW@CFwEventItem@@QEAAXAEAUICiCAdviseStatus@@@Z equ <__imp_?ReportEventW@CFwEventItem@@QEAAXAEAUICiCAdviseStatus@@@Z>

externdef __imp_?RequiresFlush@CPhysStorage@@QEAAHK@Z:PPROC
?RequiresFlush@CPhysStorage@@QEAAHK@Z equ <__imp_?RequiresFlush@CPhysStorage@@QEAAHK@Z>

externdef __imp_?Reset@CRegChangeEvent@@QEAAXXZ:PPROC
?Reset@CRegChangeEvent@@QEAAXXZ equ <__imp_?Reset@CRegChangeEvent@@QEAAXXZ>

externdef __imp_?ResetBuffer@CQueryScanner@@QEAAXPEBG@Z:PPROC
?ResetBuffer@CQueryScanner@@QEAAXPEBG@Z equ <__imp_?ResetBuffer@CQueryScanner@@QEAAXPEBG@Z>

externdef __imp_?ResetType@CAllocStorageVariant@@IEAAXAEAVPMemoryAllocator@@@Z:PPROC
?ResetType@CAllocStorageVariant@@IEAAXAEAVPMemoryAllocator@@@Z equ <__imp_?ResetType@CAllocStorageVariant@@IEAAXAEAVPMemoryAllocator@@@Z>

externdef __imp_?Resume@CProcess@@QEAAXXZ:PPROC
?Resume@CProcess@@QEAAXXZ equ <__imp_?Resume@CProcess@@QEAAXXZ>

externdef __imp_?ReturnBuffer@CPhysStorage@@QEAAXKHH@Z:PPROC
?ReturnBuffer@CPhysStorage@@QEAAXKHH@Z equ <__imp_?ReturnBuffer@CPhysStorage@@QEAAXKHH@Z>

externdef __imp_?Rewind@CMmStreamConsecBuf@@QEAAXXZ:PPROC
?Rewind@CMmStreamConsecBuf@@QEAAXXZ equ <__imp_?Rewind@CMmStreamConsecBuf@@QEAAXXZ>

externdef __imp_?SaComputeSize@@YAKGAEAUtagSAFEARRAY@@@Z:PPROC
?SaComputeSize@@YAKGAEAUtagSAFEARRAY@@@Z equ <__imp_?SaComputeSize@@YAKGAEAUtagSAFEARRAY@@@Z>

externdef __imp_?SaCreateAndCopy@@YAHAEAVPMemoryAllocator@@PEAUtagSAFEARRAY@@PEAPEAU2@@Z:PPROC
?SaCreateAndCopy@@YAHAEAVPMemoryAllocator@@PEAUtagSAFEARRAY@@PEAPEAU2@@Z equ <__imp_?SaCreateAndCopy@@YAHAEAVPMemoryAllocator@@PEAUtagSAFEARRAY@@PEAPEAU2@@Z>

externdef __imp_?SaCreateData@@YAHAEAVPVarAllocator@@GAEAUtagSAFEARRAY@@1H@Z:PPROC
?SaCreateData@@YAHAEAVPVarAllocator@@GAEAUtagSAFEARRAY@@1H@Z equ <__imp_?SaCreateData@@YAHAEAVPVarAllocator@@GAEAUtagSAFEARRAY@@1H@Z>

externdef __imp_?Seek@CRcovStrmTrans@@QEAAHK@Z:PPROC
?Seek@CRcovStrmTrans@@QEAAHK@Z equ <__imp_?Seek@CRcovStrmTrans@@QEAAHK@Z>

externdef __imp_?Serialize@CDbQueryResults@@QEBAXAEAVPSerStream@@@Z:PPROC
?Serialize@CDbQueryResults@@QEBAXAEAVPSerStream@@@Z equ <__imp_?Serialize@CDbQueryResults@@QEBAXAEAVPSerStream@@@Z>

externdef __imp_?Set@CPidRemapper@@QEAAXAEAV?$XArray@K@@@Z:PPROC
?Set@CPidRemapper@@QEAAXAEAV?$XArray@K@@@Z equ <__imp_?Set@CPidRemapper@@QEAAXAEAV?$XArray@K@@@Z>

externdef __imp_?SetAlias@CScopeAdmin@@QEAAXPEBG@Z:PPROC
?SetAlias@CScopeAdmin@@QEAAXPEBG@Z equ <__imp_?SetAlias@CScopeAdmin@@QEAAXPEBG@Z>

externdef __imp_?SetBOOL@CStorageVariant@@QEAAXFI@Z:PPROC
?SetBOOL@CStorageVariant@@QEAAXFI@Z equ <__imp_?SetBOOL@CStorageVariant@@QEAAXFI@Z>

externdef __imp_?SetBSTR@CAllocStorageVariant@@QEAAXPEAGAEAVPMemoryAllocator@@@Z:PPROC
?SetBSTR@CAllocStorageVariant@@QEAAXPEAGAEAVPMemoryAllocator@@@Z equ <__imp_?SetBSTR@CAllocStorageVariant@@QEAAXPEAGAEAVPMemoryAllocator@@@Z>

externdef __imp_?SetBSTR@CStorageVariant@@QEAAXPEAGI@Z:PPROC
?SetBSTR@CStorageVariant@@QEAAXPEAGI@Z equ <__imp_?SetBSTR@CStorageVariant@@QEAAXPEAGI@Z>

externdef __imp_?SetBackupSize@CPropStoreManager@@QEAAXKK@Z:PPROC
?SetBackupSize@CPropStoreManager@@QEAAXKK@Z equ <__imp_?SetBackupSize@CPropStoreManager@@QEAAXKK@Z>

externdef __imp_?SetCD@CCatState@@QEAAXPEBG@Z:PPROC
?SetCD@CCatState@@QEAAXPEBG@Z equ <__imp_?SetCD@CCatState@@QEAAXPEBG@Z>

externdef __imp_?SetCLSID@CStorageVariant@@QEAAXPEBU_GUID@@@Z:PPROC
?SetCLSID@CStorageVariant@@QEAAXPEBU_GUID@@@Z equ <__imp_?SetCLSID@CStorageVariant@@QEAAXPEBU_GUID@@@Z>

externdef __imp_?SetCLSID@CStorageVariant@@QEAAXU_GUID@@I@Z:PPROC
?SetCLSID@CStorageVariant@@QEAAXU_GUID@@I@Z equ <__imp_?SetCLSID@CStorageVariant@@QEAAXU_GUID@@I@Z>

externdef __imp_?SetCY@CStorageVariant@@QEAAXTtagCY@@I@Z:PPROC
?SetCY@CStorageVariant@@QEAAXTtagCY@@I@Z equ <__imp_?SetCY@CStorageVariant@@QEAAXTtagCY@@I@Z>

externdef __imp_?SetCatalog@CCatState@@QEAAXPEBG@Z:PPROC
?SetCatalog@CCatState@@QEAAXPEBG@Z equ <__imp_?SetCatalog@CCatState@@QEAAXPEBG@Z>

externdef __imp_?SetColumn@CCatState@@QEAAXPEBGI@Z:PPROC
?SetColumn@CCatState@@QEAAXPEBGI@Z equ <__imp_?SetColumn@CCatState@@QEAAXPEBGI@Z>

externdef __imp_?SetCurrentProperty@CQueryParser@@AEAAXPEBGW4PropertyType@@@Z:PPROC
?SetCurrentProperty@CQueryParser@@AEAAXPEBGW4PropertyType@@@Z equ <__imp_?SetCurrentProperty@CQueryParser@@AEAAXPEBGW4PropertyType@@@Z>

externdef __imp_?SetDATE@CStorageVariant@@QEAAXNI@Z:PPROC
?SetDATE@CStorageVariant@@QEAAXNI@Z equ <__imp_?SetDATE@CStorageVariant@@QEAAXNI@Z>

externdef __imp_?SetDWORDParam@CCatalogAdmin@@QEAAXPEBGK@Z:PPROC
?SetDWORDParam@CCatalogAdmin@@QEAAXPEBGK@Z equ <__imp_?SetDWORDParam@CCatalogAdmin@@QEAAXPEBGK@Z>

externdef __imp_?SetDWORDParam@CMachineAdmin@@QEAAXPEBGK@Z:PPROC
?SetDWORDParam@CMachineAdmin@@QEAAXPEBGK@Z equ <__imp_?SetDWORDParam@CMachineAdmin@@QEAAXPEBGK@Z>

externdef __imp_?SetDefaultProperty@CCatState@@QEAAXPEBG@Z:PPROC
?SetDefaultProperty@CCatState@@QEAAXPEBG@Z equ <__imp_?SetDefaultProperty@CCatState@@QEAAXPEBG@Z>

externdef __imp_?SetExclude@CScopeAdmin@@QEAAXH@Z:PPROC
?SetExclude@CScopeAdmin@@QEAAXH@Z equ <__imp_?SetExclude@CScopeAdmin@@QEAAXH@Z>

externdef __imp_?SetFILETIME@CStorageVariant@@QEAAXU_FILETIME@@I@Z:PPROC
?SetFILETIME@CStorageVariant@@QEAAXU_FILETIME@@I@Z equ <__imp_?SetFILETIME@CStorageVariant@@QEAAXU_FILETIME@@I@Z>

externdef __imp_?SetI2@CStorageVariant@@QEAAXFI@Z:PPROC
?SetI2@CStorageVariant@@QEAAXFI@Z equ <__imp_?SetI2@CStorageVariant@@QEAAXFI@Z>

externdef __imp_?SetI4@CStorageVariant@@QEAAXJI@Z:PPROC
?SetI4@CStorageVariant@@QEAAXJI@Z equ <__imp_?SetI4@CStorageVariant@@QEAAXJI@Z>

externdef __imp_?SetI8@CStorageVariant@@QEAAXT_LARGE_INTEGER@@I@Z:PPROC
?SetI8@CStorageVariant@@QEAAXT_LARGE_INTEGER@@I@Z equ <__imp_?SetI8@CStorageVariant@@QEAAXT_LARGE_INTEGER@@I@Z>

externdef __imp_?SetLPSTR@CStorageVariant@@QEAAXPEBDI@Z:PPROC
?SetLPSTR@CStorageVariant@@QEAAXPEBDI@Z equ <__imp_?SetLPSTR@CStorageVariant@@QEAAXPEBDI@Z>

externdef __imp_?SetLPWSTR@CStorageVariant@@QEAAXPEBGI@Z:PPROC
?SetLPWSTR@CStorageVariant@@QEAAXPEBGI@Z equ <__imp_?SetLPWSTR@CStorageVariant@@QEAAXPEBGI@Z>

externdef __imp_?SetLocale@CCatState@@QEAAXPEBG@Z:PPROC
?SetLocale@CCatState@@QEAAXPEBG@Z equ <__imp_?SetLocale@CCatState@@QEAAXPEBG@Z>

externdef __imp_?SetLogonInfo@CScopeAdmin@@QEAAXPEBG0AEAVCCatalogAdmin@@@Z:PPROC
?SetLogonInfo@CScopeAdmin@@QEAAXPEBG0AEAVCCatalogAdmin@@@Z equ <__imp_?SetLogonInfo@CScopeAdmin@@QEAAXPEBG0AEAVCCatalogAdmin@@@Z>

externdef __imp_?SetMappedCacheSize@CPropStoreManager@@QEAAXKK@Z:PPROC
?SetMappedCacheSize@CPropStoreManager@@QEAAXKK@Z equ <__imp_?SetMappedCacheSize@CPropStoreManager@@QEAAXKK@Z>

externdef __imp_?SetNumberOfColumns@CCatState@@QEAAXI@Z:PPROC
?SetNumberOfColumns@CCatState@@QEAAXI@Z equ <__imp_?SetNumberOfColumns@CCatState@@QEAAXI@Z>

externdef __imp_?SetNumberOfSortProps@CCatState@@QEAAXI@Z:PPROC
?SetNumberOfSortProps@CCatState@@QEAAXI@Z equ <__imp_?SetNumberOfSortProps@CCatState@@QEAAXI@Z>

externdef __imp_?SetPath@CScopeAdmin@@QEAAXPEBG@Z:PPROC
?SetPath@CScopeAdmin@@QEAAXPEBG@Z equ <__imp_?SetPath@CScopeAdmin@@QEAAXPEBG@Z>

externdef __imp_?SetPhrase@CContentRestriction@@QEAAXPEBG@Z:PPROC
?SetPhrase@CContentRestriction@@QEAAXPEBG@Z equ <__imp_?SetPhrase@CContentRestriction@@QEAAXPEBG@Z>

externdef __imp_?SetPhrase@CNatLanguageRestriction@@QEAAXPEBG@Z:PPROC
?SetPhrase@CNatLanguageRestriction@@QEAAXPEBG@Z equ <__imp_?SetPhrase@CNatLanguageRestriction@@QEAAXPEBG@Z>

externdef __imp_?SetPriority@CGenericCiProxy@@QEAAXKK@Z:PPROC
?SetPriority@CGenericCiProxy@@QEAAXKK@Z equ <__imp_?SetPriority@CGenericCiProxy@@QEAAXKK@Z>

externdef __imp_?SetProperties@CDbProperties@@UEAAJKQEAUtagDBPROPSET@@@Z:PPROC
?SetProperties@CDbProperties@@UEAAJKQEAUtagDBPROPSET@@@Z equ <__imp_?SetProperties@CDbProperties@@UEAAJKQEAUtagDBPROPSET@@@Z>

externdef __imp_?SetProperty@CDbColId@@QEAAHPEBG@Z:PPROC
?SetProperty@CDbColId@@QEAAHPEBG@Z equ <__imp_?SetProperty@CDbColId@@QEAAHPEBG@Z>

externdef __imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBUtagDBID@@@Z:PPROC
?SetProperty@CDbPropBaseRestriction@@QEAAHAEBUtagDBID@@@Z equ <__imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBUtagDBID@@@Z>

externdef __imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBVCDbColumnNode@@@Z:PPROC
?SetProperty@CDbPropBaseRestriction@@QEAAHAEBVCDbColumnNode@@@Z equ <__imp_?SetProperty@CDbPropBaseRestriction@@QEAAHAEBVCDbColumnNode@@@Z>

externdef __imp_?SetProperty@CFullPropSpec@@QEAAHPEBG@Z:PPROC
?SetProperty@CFullPropSpec@@QEAAHPEBG@Z equ <__imp_?SetProperty@CFullPropSpec@@QEAAHPEBG@Z>

externdef __imp_?SetProperty@CFullPropSpec@@QEAAXK@Z:PPROC
?SetProperty@CFullPropSpec@@QEAAXK@Z equ <__imp_?SetProperty@CFullPropSpec@@QEAAXK@Z>

externdef __imp_?SetR4@CStorageVariant@@QEAAXMI@Z:PPROC
?SetR4@CStorageVariant@@QEAAXMI@Z equ <__imp_?SetR4@CStorageVariant@@QEAAXMI@Z>

externdef __imp_?SetR8@CStorageVariant@@QEAAXNI@Z:PPROC
?SetR8@CStorageVariant@@QEAAXNI@Z equ <__imp_?SetR8@CStorageVariant@@QEAAXNI@Z>

externdef __imp_?SetRestriction@CDbSelectNode@@QEAAHPEAVCDbCmdTreeNode@@@Z:PPROC
?SetRestriction@CDbSelectNode@@QEAAHPEAVCDbCmdTreeNode@@@Z equ <__imp_?SetRestriction@CDbSelectNode@@QEAAHPEAVCDbCmdTreeNode@@@Z>

externdef __imp_?SetRunningAsSystem@CImpersonateSystem@@SAXXZ:PPROC
?SetRunningAsSystem@CImpersonateSystem@@SAXXZ equ <__imp_?SetRunningAsSystem@CImpersonateSystem@@SAXXZ>

externdef __imp_?SetSZParam@CMachineAdmin@@QEAAXPEBG0K@Z:PPROC
?SetSZParam@CMachineAdmin@@QEAAXPEBG0K@Z equ <__imp_?SetSZParam@CMachineAdmin@@QEAAXPEBG0K@Z>

externdef __imp_?SetScopeProperties@@YAXPEAUICommand@@IPEBQEBGPEBK11@Z:PPROC
?SetScopeProperties@@YAXPEAUICommand@@IPEBQEBGPEBK11@Z equ <__imp_?SetScopeProperties@@YAXPEAUICommand@@IPEBQEBGPEBK11@Z>

externdef __imp_?SetScopePropertiesNoThrow@@YAJPEAUICommand@@IPEBQEBGPEBK11@Z:PPROC
?SetScopePropertiesNoThrow@@YAJPEAUICommand@@IPEBQEBGPEBK11@Z equ <__imp_?SetScopePropertiesNoThrow@@YAJPEAUICommand@@IPEBQEBGPEBK11@Z>

externdef __imp_?SetSecret@@YAXPEBG00K@Z:PPROC
?SetSecret@@YAXPEBG00K@Z equ <__imp_?SetSecret@@YAXPEBG00K@Z>

externdef __imp_?SetSortProp@CCatState@@QEAAXPEBGW4SORTDIR@@I@Z:PPROC
?SetSortProp@CCatState@@QEAAXPEBGW4SORTDIR@@I@Z equ <__imp_?SetSortProp@CCatState@@QEAAXPEBGW4SORTDIR@@I@Z>

externdef __imp_?SetUI1@CStorageVariant@@QEAAXEI@Z:PPROC
?SetUI1@CStorageVariant@@QEAAXEI@Z equ <__imp_?SetUI1@CStorageVariant@@QEAAXEI@Z>

externdef __imp_?SetUI2@CStorageVariant@@QEAAXGI@Z:PPROC
?SetUI2@CStorageVariant@@QEAAXGI@Z equ <__imp_?SetUI2@CStorageVariant@@QEAAXGI@Z>

externdef __imp_?SetUI4@CStorageVariant@@QEAAXKI@Z:PPROC
?SetUI4@CStorageVariant@@QEAAXKI@Z equ <__imp_?SetUI4@CStorageVariant@@QEAAXKI@Z>

externdef __imp_?SetUI8@CStorageVariant@@QEAAXT_ULARGE_INTEGER@@I@Z:PPROC
?SetUI8@CStorageVariant@@QEAAXT_ULARGE_INTEGER@@I@Z equ <__imp_?SetUI8@CStorageVariant@@QEAAXT_ULARGE_INTEGER@@I@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXAEAUtagBLOB@@@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXPEAG@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAG@Z>

externdef __imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z:PPROC
?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z equ <__imp_?SetValue@CPropertyRestriction@@QEAAXPEAU_GUID@@@Z>

externdef __imp_?SetWeight@CDbCmdTreeNode@@QEAAXJ@Z:PPROC
?SetWeight@CDbCmdTreeNode@@QEAAXJ@Z equ <__imp_?SetWeight@CDbCmdTreeNode@@QEAAXJ@Z>

externdef __imp_?Setup@CPropStoreManager@@QEAAXKKK_KHK@Z:PPROC
?Setup@CPropStoreManager@@QEAAXKKK_KHK@Z equ <__imp_?Setup@CPropStoreManager@@QEAAXKKK_KHK@Z>

externdef __imp_?Shrink@CDynStream@@QEAAXAEAVPStorage@@K@Z:PPROC
?Shrink@CDynStream@@QEAAXAEAVPStorage@@K@Z equ <__imp_?Shrink@CDynStream@@QEAAXAEAVPStorage@@K@Z>

externdef __imp_?ShrinkFromFront@CPhysStorage@@QEAAKKK@Z:PPROC
?ShrinkFromFront@CPhysStorage@@QEAAKKK@Z equ <__imp_?ShrinkFromFront@CPhysStorage@@QEAAKKK@Z>

externdef __imp_?ShrinkToFit@CPhysStorage@@QEAAXXZ:PPROC
?ShrinkToFit@CPhysStorage@@QEAAXXZ equ <__imp_?ShrinkToFit@CPhysStorage@@QEAAXXZ>

externdef __imp_?Shutdown@CCiOle@@SAXXZ:PPROC
?Shutdown@CCiOle@@SAXXZ equ <__imp_?Shutdown@CCiOle@@SAXXZ>

externdef __imp_?Shutdown@CPropStoreManager@@QEAAXXZ:PPROC
?Shutdown@CPropStoreManager@@QEAAXXZ equ <__imp_?Shutdown@CPropStoreManager@@QEAAXXZ>

externdef __imp_?Shutdown@CWorkQueue@@QEAAXXZ:PPROC
?Shutdown@CWorkQueue@@QEAAXXZ equ <__imp_?Shutdown@CWorkQueue@@QEAAXXZ>

externdef __imp_?Size@CDbQueryResults@@QEAAKXZ:PPROC
?Size@CDbQueryResults@@QEAAKXZ equ <__imp_?Size@CDbQueryResults@@QEAAKXZ>

externdef __imp_?Skip@CEnumString@@UEAAJK@Z:PPROC
?Skip@CEnumString@@UEAAJK@Z equ <__imp_?Skip@CEnumString@@UEAAJK@Z>

externdef __imp_?Skip@CEnumWorkid@@UEAAJK@Z:PPROC
?Skip@CEnumWorkid@@UEAAJK@Z equ <__imp_?Skip@CEnumWorkid@@UEAAJK@Z>

externdef __imp_?SkipBlob@CMemDeSerStream@@UEAAXK@Z:PPROC
?SkipBlob@CMemDeSerStream@@UEAAXK@Z equ <__imp_?SkipBlob@CMemDeSerStream@@UEAAXK@Z>

externdef __imp_?SkipByte@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipByte@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipByte@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipChar@CMemDeSerStream@@UEAAXK@Z:PPROC
?SkipChar@CMemDeSerStream@@UEAAXK@Z equ <__imp_?SkipChar@CMemDeSerStream@@UEAAXK@Z>

externdef __imp_?SkipDouble@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipDouble@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipDouble@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipFloat@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipFloat@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipFloat@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipGUID@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipGUID@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipGUID@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipLong@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipLong@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipLong@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipULong@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipULong@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipULong@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipUShort@CMemDeSerStream@@UEAAXXZ:PPROC
?SkipUShort@CMemDeSerStream@@UEAAXXZ equ <__imp_?SkipUShort@CMemDeSerStream@@UEAAXXZ>

externdef __imp_?SkipWChar@CMemDeSerStream@@UEAAXK@Z:PPROC
?SkipWChar@CMemDeSerStream@@UEAAXK@Z equ <__imp_?SkipWChar@CMemDeSerStream@@UEAAXK@Z>

externdef __imp_?Start@CCatalogAdmin@@QEAAHXZ:PPROC
?Start@CCatalogAdmin@@QEAAHXZ equ <__imp_?Start@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?StartCI@CMachineAdmin@@QEAAHXZ:PPROC
?StartCI@CMachineAdmin@@QEAAHXZ equ <__imp_?StartCI@CMachineAdmin@@QEAAHXZ>

externdef __imp_?Stop@CCatalogAdmin@@QEAAHXZ:PPROC
?Stop@CCatalogAdmin@@QEAAHXZ equ <__imp_?Stop@CCatalogAdmin@@QEAAHXZ>

externdef __imp_?StopCI@CMachineAdmin@@QEAAHXZ:PPROC
?StopCI@CMachineAdmin@@QEAAHXZ equ <__imp_?StopCI@CMachineAdmin@@QEAAHXZ>

externdef __imp_?StopFiltering@CFilterDaemon@@QEAAXXZ:PPROC
?StopFiltering@CFilterDaemon@@QEAAXXZ equ <__imp_?StopFiltering@CFilterDaemon@@QEAAXXZ>

externdef __imp_?StrLen@CKey@@QEBAIXZ:PPROC
?StrLen@CKey@@QEBAIXZ equ <__imp_?StrLen@CKey@@QEBAIXZ>

externdef __imp_?StrLen@CKeyBuf@@QEBAIXZ:PPROC
?StrLen@CKeyBuf@@QEBAIXZ equ <__imp_?StrLen@CKeyBuf@@QEBAIXZ>

externdef __imp_?SystemExceptionTranslator@@YAXIPEAU_EXCEPTION_POINTERS@@@Z:PPROC
?SystemExceptionTranslator@@YAXIPEAU_EXCEPTION_POINTERS@@@Z equ <__imp_?SystemExceptionTranslator@@YAXIPEAU_EXCEPTION_POINTERS@@@Z>

externdef __imp_?TreeCount@CRestriction@@QEBAKXZ:PPROC
?TreeCount@CRestriction@@QEBAKXZ equ <__imp_?TreeCount@CRestriction@@QEBAKXZ>

externdef __imp_?TunePerformance@CMachineAdmin@@QEAAXHGG@Z:PPROC
?TunePerformance@CMachineAdmin@@QEAAXHGG@Z equ <__imp_?TunePerformance@CMachineAdmin@@QEAAXHGG@Z>

externdef __imp_?URLEscapeW@@YAXPEBGAEAVCVirtualString@@KH@Z:PPROC
?URLEscapeW@@YAXPEBGAEAVCVirtualString@@KH@Z equ <__imp_?URLEscapeW@@YAXPEBGAEAVCVirtualString@@KH@Z>

externdef __imp_?UnMarshall@CDbProperties@@QEAAHAEAVPDeSerStream@@@Z:PPROC
?UnMarshall@CDbProperties@@QEAAHAEAVPDeSerStream@@@Z equ <__imp_?UnMarshall@CDbProperties@@QEAAHAEAVPDeSerStream@@@Z>

externdef __imp_?UnMarshall@CRestriction@@SAPEAV1@AEAVPDeSerStream@@@Z:PPROC
?UnMarshall@CRestriction@@SAPEAV1@AEAVPDeSerStream@@@Z equ <__imp_?UnMarshall@CRestriction@@SAPEAV1@AEAVPDeSerStream@@@Z>

externdef __imp_?UnMarshallTree@CDbCmdTreeNode@@SAPEAV1@AEAVPDeSerStream@@@Z:PPROC
?UnMarshallTree@CDbCmdTreeNode@@SAPEAV1@AEAVPDeSerStream@@@Z equ <__imp_?UnMarshallTree@CDbCmdTreeNode@@SAPEAV1@AEAVPDeSerStream@@@Z>

externdef __imp_?UnPickle@@YAXHAEAV?$XPtr@VCColumnSet@@@@AEAV?$XPtr@VCRestriction@@@@AEAV?$XPtr@VCSortSet@@@@AEAV?$XPtr@VCCategorizationSet@@@@AEAVCRowsetProperties@@AEAV?$XPtr@VCPidMapper@@@@PEAEK@Z:PPROC
?UnPickle@@YAXHAEAV?$XPtr@VCColumnSet@@@@AEAV?$XPtr@VCRestriction@@@@AEAV?$XPtr@VCSortSet@@@@AEAV?$XPtr@VCCategorizationSet@@@@AEAVCRowsetProperties@@AEAV?$XPtr@VCPidMapper@@@@PEAEK@Z equ <__imp_?UnPickle@@YAXHAEAV?$XPtr@VCColumnSet@@@@AEAV?$XPtr@VCRestriction@@@@AEAV?$XPtr@VCSortSet@@@@AEAV?$XPtr@VCCategorizationSet@@@@AEAVCRowsetProperties@@AEAV?$XPtr@VCPidMapper@@@@PEAEK@Z>

externdef __imp_?Unmap@CRcovStrmTrans@@IEAAXW4DataCopyNum@CRcovStorageHdr@@@Z:PPROC
?Unmap@CRcovStrmTrans@@IEAAXW4DataCopyNum@CRcovStorageHdr@@@Z equ <__imp_?Unmap@CRcovStrmTrans@@IEAAXW4DataCopyNum@CRcovStorageHdr@@@Z>

externdef __imp_?UpdateContentIndex@@YAKPEBG00H@Z:PPROC
?UpdateContentIndex@@YAKPEBG00H@Z equ <__imp_?UpdateContentIndex@@YAKPEBG00H@Z>

externdef __imp_?UpdateDiskLowInfo@CDiskFreeStatus@@QEAAXXZ:PPROC
?UpdateDiskLowInfo@CDiskFreeStatus@@QEAAXXZ equ <__imp_?UpdateDiskLowInfo@CDiskFreeStatus@@QEAAXXZ>

externdef __imp_?VT_VARIANT_EQ@@YAHAEBUtagPROPVARIANT@@0@Z:PPROC
?VT_VARIANT_EQ@@YAHAEBUtagPROPVARIANT@@0@Z equ <__imp_?VT_VARIANT_EQ@@YAHAEBUtagPROPVARIANT@@0@Z>

externdef __imp_?VT_VARIANT_GE@@YAHAEBUtagPROPVARIANT@@0@Z:PPROC
?VT_VARIANT_GE@@YAHAEBUtagPROPVARIANT@@0@Z equ <__imp_?VT_VARIANT_GE@@YAHAEBUtagPROPVARIANT@@0@Z>

externdef __imp_?VT_VARIANT_GT@@YAHAEBUtagPROPVARIANT@@0@Z:PPROC
?VT_VARIANT_GT@@YAHAEBUtagPROPVARIANT@@0@Z equ <__imp_?VT_VARIANT_GT@@YAHAEBUtagPROPVARIANT@@0@Z>

externdef __imp_?VT_VARIANT_LE@@YAHAEBUtagPROPVARIANT@@0@Z:PPROC
?VT_VARIANT_LE@@YAHAEBUtagPROPVARIANT@@0@Z equ <__imp_?VT_VARIANT_LE@@YAHAEBUtagPROPVARIANT@@0@Z>

externdef __imp_?VT_VARIANT_LT@@YAHAEBUtagPROPVARIANT@@0@Z:PPROC
?VT_VARIANT_LT@@YAHAEBUtagPROPVARIANT@@0@Z equ <__imp_?VT_VARIANT_LT@@YAHAEBUtagPROPVARIANT@@0@Z>

externdef __imp_?VT_VARIANT_NE@@YAHAEBUtagPROPVARIANT@@0@Z:PPROC
?VT_VARIANT_NE@@YAHAEBUtagPROPVARIANT@@0@Z equ <__imp_?VT_VARIANT_NE@@YAHAEBUtagPROPVARIANT@@0@Z>

externdef __imp_?ValidateScopeRestriction@@YAHPEAVCRestriction@@@Z:PPROC
?ValidateScopeRestriction@@YAHPEAVCRestriction@@@Z equ <__imp_?ValidateScopeRestriction@@YAHPEAVCRestriction@@@Z>

externdef __imp_?VerifyConsistency@PRcovStorageObj@@QEAAXXZ:PPROC
?VerifyConsistency@PRcovStorageObj@@QEAAXXZ equ <__imp_?VerifyConsistency@PRcovStorageObj@@QEAAXXZ>

externdef __imp_?VerifyThreadHasAdminPrivilege@@YAXXZ:PPROC
?VerifyThreadHasAdminPrivilege@@YAXXZ equ <__imp_?VerifyThreadHasAdminPrivilege@@YAXXZ>

externdef __imp_?WideCharToXArrayMultiByte@@YAKPEBGKIAEAV?$XArray@E@@@Z:PPROC
?WideCharToXArrayMultiByte@@YAKPEBGKIAEAV?$XArray@E@@@Z equ <__imp_?WideCharToXArrayMultiByte@@YAKPEBGKIAEAV?$XArray@E@@@Z>

externdef __imp_?Write@CDynStream@@QEAAXPEAXK@Z:PPROC
?Write@CDynStream@@QEAAXPEAXK@Z equ <__imp_?Write@CDynStream@@QEAAXPEAXK@Z>

externdef __imp_?Write@CRcovStrmTrans@@IEAAXPEBXK@Z:PPROC
?Write@CRcovStrmTrans@@IEAAXPEBXK@Z equ <__imp_?Write@CRcovStrmTrans@@IEAAXPEBXK@Z>

externdef __imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z:PPROC
?WritePrimaryProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z equ <__imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z>

externdef __imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z:PPROC
?WritePrimaryProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z equ <__imp_?WritePrimaryProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z>

externdef __imp_?WriteProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z:PPROC
?WriteProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z equ <__imp_?WriteProperty@CPropStoreManager@@QEAAJAEAVCCompositePropRecordForWrites@@KAEBVCStorageVariant@@@Z>

externdef __imp_?WriteProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z:PPROC
?WriteProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z equ <__imp_?WriteProperty@CPropStoreManager@@QEAAJKKAEBVCStorageVariant@@@Z>

externdef __imp_?WritePropertyInNewRecord@CPropStoreManager@@QEAAKKAEBVCStorageVariant@@@Z:PPROC
?WritePropertyInNewRecord@CPropStoreManager@@QEAAKKAEBVCStorageVariant@@@Z equ <__imp_?WritePropertyInNewRecord@CPropStoreManager@@QEAAKKAEBVCStorageVariant@@@Z>

externdef __imp_?_FindGroupListAnchor@CDbNestingNode@@AEAAPEAVCDbProjectListAnchor@@XZ:PPROC
?_FindGroupListAnchor@CDbNestingNode@@AEAAPEAVCDbProjectListAnchor@@XZ equ <__imp_?_FindGroupListAnchor@CDbNestingNode@@AEAAPEAVCDbProjectListAnchor@@XZ>

externdef __imp_?_FindOrAddAnchor@CDbProjectNode@@AEAAPEAVCDbProjectListAnchor@@XZ:PPROC
?_FindOrAddAnchor@CDbProjectNode@@AEAAPEAVCDbProjectListAnchor@@XZ equ <__imp_?_FindOrAddAnchor@CDbProjectNode@@AEAAPEAVCDbProjectListAnchor@@XZ>

externdef __imp_?_FindOrAddAnchor@CDbSortNode@@AEAAPEAVCDbSortListAnchor@@XZ:PPROC
?_FindOrAddAnchor@CDbSortNode@@AEAAPEAVCDbSortListAnchor@@XZ equ <__imp_?_FindOrAddAnchor@CDbSortNode@@AEAAPEAVCDbSortListAnchor@@XZ>

externdef __imp_?_FindOrAddValueNode@CDbPropertyRestriction@@AEAAPEAVCDbScalarValue@@XZ:PPROC
?_FindOrAddValueNode@CDbPropertyRestriction@@AEAAPEAVCDbScalarValue@@XZ equ <__imp_?_FindOrAddValueNode@CDbPropertyRestriction@@AEAAPEAVCDbScalarValue@@XZ>

externdef __imp_?_ImpersonateIf@CImpersonateRemoteAccess@@AEAAHPEBG0K@Z:PPROC
?_ImpersonateIf@CImpersonateRemoteAccess@@AEAAHPEBG0K@Z equ <__imp_?_ImpersonateIf@CImpersonateRemoteAccess@@AEAAHPEBG0K@Z>

externdef __imp_?_wcstoui64@@YA_KPEBGPEAPEAGH@Z:PPROC
?_wcstoui64@@YA_KPEBGPEAPEAGH@Z equ <__imp_?_wcstoui64@@YA_KPEBGPEAPEAGH@Z>

externdef __imp_?ciDelete@@YAXPEAX@Z:PPROC
?ciDelete@@YAXPEAX@Z equ <__imp_?ciDelete@@YAXPEAX@Z>

externdef __imp_?ciIsValidPointer@@YAHPEBX@Z:PPROC
?ciIsValidPointer@@YAHPEBX@Z equ <__imp_?ciIsValidPointer@@YAHPEBX@Z>

externdef __imp_?ciNew@@YAPEAX_K@Z:PPROC
?ciNew@@YAPEAX_K@Z equ <__imp_?ciNew@@YAPEAX_K@Z>

externdef __imp_?fgetsw@CFileBuffer@@QEAAKAEAV?$XGrowable@G$0BAE@@@@Z:PPROC
?fgetsw@CFileBuffer@@QEAAKAEAV?$XGrowable@G$0BAE@@@@Z equ <__imp_?fgetsw@CFileBuffer@@QEAAKAEAV?$XGrowable@G$0BAE@@@@Z>

externdef __imp_?wcsipattern@@YAPEAGPEAGPEBG@Z:PPROC
?wcsipattern@@YAPEAGPEAGPEBG@Z equ <__imp_?wcsipattern@@YAPEAGPEAGPEBG@Z>

externdef __imp_AbortMerges:PPROC
AbortMerges equ <__imp_AbortMerges>

externdef __imp_BeginCacheTransaction:PPROC
BeginCacheTransaction equ <__imp_BeginCacheTransaction>

externdef __imp_BindIFilterFromStorage:PPROC
BindIFilterFromStorage equ <__imp_BindIFilterFromStorage>

externdef __imp_BindIFilterFromStream:PPROC
BindIFilterFromStream equ <__imp_BindIFilterFromStream>

externdef __imp_CIBuildQueryNode:PPROC
CIBuildQueryNode equ <__imp_CIBuildQueryNode>

externdef __imp_CIBuildQueryTree:PPROC
CIBuildQueryTree equ <__imp_CIBuildQueryTree>

externdef __imp_CICreateCommand:PPROC
CICreateCommand equ <__imp_CICreateCommand>

externdef __imp_CIGetGlobalPropertyList:PPROC
CIGetGlobalPropertyList equ <__imp_CIGetGlobalPropertyList>

externdef __imp_CIMakeICommand:PPROC
CIMakeICommand equ <__imp_CIMakeICommand>

externdef __imp_CIRestrictionToFullTree:PPROC
CIRestrictionToFullTree equ <__imp_CIRestrictionToFullTree>

externdef __imp_CIState:PPROC
CIState equ <__imp_CIState>

externdef __imp_CITextToFullTree:PPROC
CITextToFullTree equ <__imp_CITextToFullTree>

externdef __imp_CITextToFullTreeEx:PPROC
CITextToFullTreeEx equ <__imp_CITextToFullTreeEx>

externdef __imp_CITextToSelectTree:PPROC
CITextToSelectTree equ <__imp_CITextToSelectTree>

externdef __imp_CITextToSelectTreeEx:PPROC
CITextToSelectTreeEx equ <__imp_CITextToSelectTreeEx>

externdef __imp_CiCreateSecurityDescriptor:PPROC
CiCreateSecurityDescriptor equ <__imp_CiCreateSecurityDescriptor>

externdef __imp_CiSvcMain:PPROC
CiSvcMain equ <__imp_CiSvcMain>

externdef __imp_CollectCIISAPIPerformanceData:PPROC
CollectCIISAPIPerformanceData equ <__imp_CollectCIISAPIPerformanceData>

externdef __imp_CollectCIPerformanceData:PPROC
CollectCIPerformanceData equ <__imp_CollectCIPerformanceData>

externdef __imp_CollectFILTERPerformanceData:PPROC
CollectFILTERPerformanceData equ <__imp_CollectFILTERPerformanceData>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DoneCIISAPIPerformanceData:PPROC
DoneCIISAPIPerformanceData equ <__imp_DoneCIISAPIPerformanceData>

externdef __imp_DoneCIPerformanceData:PPROC
DoneCIPerformanceData equ <__imp_DoneCIPerformanceData>

externdef __imp_DoneFILTERPerformanceData:PPROC
DoneFILTERPerformanceData equ <__imp_DoneFILTERPerformanceData>

externdef __imp_EndCacheTransaction:PPROC
EndCacheTransaction equ <__imp_EndCacheTransaction>

externdef __imp_ForceMasterMerge:PPROC
ForceMasterMerge equ <__imp_ForceMasterMerge>

externdef __imp_FsCiShutdown:PPROC
FsCiShutdown equ <__imp_FsCiShutdown>

externdef __imp_InitializeCIISAPIPerformanceData:PPROC
InitializeCIISAPIPerformanceData equ <__imp_InitializeCIISAPIPerformanceData>

externdef __imp_InitializeCIPerformanceData:PPROC
InitializeCIPerformanceData equ <__imp_InitializeCIPerformanceData>

externdef __imp_InitializeFILTERPerformanceData:PPROC
InitializeFILTERPerformanceData equ <__imp_InitializeFILTERPerformanceData>

externdef __imp_LoadBHIFilter:PPROC
LoadBHIFilter equ <__imp_LoadBHIFilter>

externdef __imp_LoadBinaryFilter:PPROC
LoadBinaryFilter equ <__imp_LoadBinaryFilter>

externdef __imp_LoadIFilter:PPROC
LoadIFilter equ <__imp_LoadIFilter>

externdef __imp_LoadIFilterEx:PPROC
LoadIFilterEx equ <__imp_LoadIFilterEx>

externdef __imp_LoadTextFilter:PPROC
LoadTextFilter equ <__imp_LoadTextFilter>

externdef __imp_LocateCatalogs:PPROC
LocateCatalogs equ <__imp_LocateCatalogs>

externdef __imp_LocateCatalogsA:PPROC
LocateCatalogsA equ <__imp_LocateCatalogsA>
  IFNDEF __UNICODE__
    LocateCatalogs equ <__imp_LocateCatalogsA>
  ENDIF

externdef __imp_LocateCatalogsW:PPROC
LocateCatalogsW equ <__imp_LocateCatalogsW>
  IFDEF __UNICODE__
    LocateCatalogs equ <__imp_LocateCatalogsW>
  ENDIF

externdef __imp_SetCatalogState:PPROC
SetCatalogState equ <__imp_SetCatalogState>

externdef __imp_SetupCache:PPROC
SetupCache equ <__imp_SetupCache>

externdef __imp_SetupCacheEx:PPROC
SetupCacheEx equ <__imp_SetupCacheEx>

externdef __imp_StartFWCiSvcWork:PPROC
StartFWCiSvcWork equ <__imp_StartFWCiSvcWork>

externdef __imp_StopFWCiSvcWork:PPROC
StopFWCiSvcWork equ <__imp_StopFWCiSvcWork>

externdef __imp_SvcEntry_CiSvc:PPROC
SvcEntry_CiSvc equ <__imp_SvcEntry_CiSvc>
