externdef __imp_DeviceConnect:PPROC
DeviceConnect equ <__imp_DeviceConnect>

externdef __imp_DeviceDone:PPROC
DeviceDone equ <__imp_DeviceDone>

externdef __imp_DeviceEnum:PPROC
DeviceEnum equ <__imp_DeviceEnum>

externdef __imp_DeviceGetInfo:PPROC
DeviceGetInfo equ <__imp_DeviceGetInfo>

externdef __imp_DeviceListen:PPROC
DeviceListen equ <__imp_DeviceListen>

externdef __imp_DeviceSetInfo:PPROC
DeviceSetInfo equ <__imp_DeviceSetInfo>

externdef __imp_DeviceWork:PPROC
DeviceWork equ <__imp_DeviceWork>
