externdef __imp_ServiceMain:PPROC
ServiceMain equ <__imp_ServiceMain>

externdef __imp_ServiceRequestInProcess:PPROC
ServiceRequestInProcess equ <__imp_ServiceRequestInProcess>

externdef __imp_SetEntryDialParams:PPROC
SetEntryDialParams equ <__imp_SetEntryDialParams>

externdef __imp__RasmanEngine:PPROC
_RasmanEngine equ <__imp__RasmanEngine>

externdef __imp__RasmanInit:PPROC
_RasmanInit equ <__imp__RasmanInit>
