externdef __imp_GetDiagnosticFunctions:PPROC
GetDiagnosticFunctions equ <__imp_GetDiagnosticFunctions>

externdef __imp_InitHelperDll:PPROC
InitHelperDll equ <__imp_InitHelperDll>

externdef __imp_RutlAlloc:PPROC
RutlAlloc equ <__imp_RutlAlloc>

externdef __imp_RutlAssignmentFromTokenAndDword:PPROC
RutlAssignmentFromTokenAndDword equ <__imp_RutlAssignmentFromTokenAndDword>

externdef __imp_RutlAssignmentFromTokens:PPROC
RutlAssignmentFromTokens equ <__imp_RutlAssignmentFromTokens>

externdef __imp_RutlCloseDumpFile:PPROC
RutlCloseDumpFile equ <__imp_RutlCloseDumpFile>

externdef __imp_RutlCreateDumpFile:PPROC
RutlCreateDumpFile equ <__imp_RutlCreateDumpFile>

externdef __imp_RutlDwordDup:PPROC
RutlDwordDup equ <__imp_RutlDwordDup>

externdef __imp_RutlFree:PPROC
RutlFree equ <__imp_RutlFree>

externdef __imp_RutlGetOsVersion:PPROC
RutlGetOsVersion equ <__imp_RutlGetOsVersion>

externdef __imp_RutlGetTagToken:PPROC
RutlGetTagToken equ <__imp_RutlGetTagToken>

externdef __imp_RutlIsHelpToken:PPROC
RutlIsHelpToken equ <__imp_RutlIsHelpToken>

externdef __imp_RutlParse:PPROC
RutlParse equ <__imp_RutlParse>

externdef __imp_RutlStrDup:PPROC
RutlStrDup equ <__imp_RutlStrDup>
