externdef __imp_PortChangeCallback:PPROC
PortChangeCallback equ <__imp_PortChangeCallback>

externdef __imp_PortClearStatistics:PPROC
PortClearStatistics equ <__imp_PortClearStatistics>

externdef __imp_PortClose:PPROC
PortClose equ <__imp_PortClose>

externdef __imp_PortCompressionSetInfo:PPROC
PortCompressionSetInfo equ <__imp_PortCompressionSetInfo>

externdef __imp_PortConnect:PPROC
PortConnect equ <__imp_PortConnect>

externdef __imp_PortDisconnect:PPROC
PortDisconnect equ <__imp_PortDisconnect>

externdef __imp_PortEnum:PPROC
PortEnum equ <__imp_PortEnum>

externdef __imp_PortGetInfo:PPROC
PortGetInfo equ <__imp_PortGetInfo>

externdef __imp_PortGetPortState:PPROC
PortGetPortState equ <__imp_PortGetPortState>

externdef __imp_PortGetStatistics:PPROC
PortGetStatistics equ <__imp_PortGetStatistics>

externdef __imp_PortInit:PPROC
PortInit equ <__imp_PortInit>

externdef __imp_PortOpen:PPROC
PortOpen equ <__imp_PortOpen>

externdef __imp_PortReceive:PPROC
PortReceive equ <__imp_PortReceive>

externdef __imp_PortReceiveComplete:PPROC
PortReceiveComplete equ <__imp_PortReceiveComplete>

externdef __imp_PortSend:PPROC
PortSend equ <__imp_PortSend>

externdef __imp_PortSetFraming:PPROC
PortSetFraming equ <__imp_PortSetFraming>

externdef __imp_PortSetINetCfg:PPROC
PortSetINetCfg equ <__imp_PortSetINetCfg>

externdef __imp_PortSetInfo:PPROC
PortSetInfo equ <__imp_PortSetInfo>

externdef __imp_PortTestSignalState:PPROC
PortTestSignalState equ <__imp_PortTestSignalState>
