externdef __imp_AddPorts:PPROC
AddPorts equ <__imp_AddPorts>

externdef __imp_DeviceConnect:PPROC
DeviceConnect equ <__imp_DeviceConnect>

externdef __imp_DeviceDone:PPROC
DeviceDone equ <__imp_DeviceDone>

externdef __imp_DeviceEnum:PPROC
DeviceEnum equ <__imp_DeviceEnum>

externdef __imp_DeviceGetDevConfig:PPROC
DeviceGetDevConfig equ <__imp_DeviceGetDevConfig>

externdef __imp_DeviceGetDevConfigEx:PPROC
DeviceGetDevConfigEx equ <__imp_DeviceGetDevConfigEx>

externdef __imp_DeviceGetInfo:PPROC
DeviceGetInfo equ <__imp_DeviceGetInfo>

externdef __imp_DeviceListen:PPROC
DeviceListen equ <__imp_DeviceListen>

externdef __imp_DeviceSetDevConfig:PPROC
DeviceSetDevConfig equ <__imp_DeviceSetDevConfig>

externdef __imp_DeviceSetInfo:PPROC
DeviceSetInfo equ <__imp_DeviceSetInfo>

externdef __imp_DeviceWork:PPROC
DeviceWork equ <__imp_DeviceWork>

externdef __imp_EnableDeviceForDialIn:PPROC
EnableDeviceForDialIn equ <__imp_EnableDeviceForDialIn>

externdef __imp_GetConnectInfo:PPROC
GetConnectInfo equ <__imp_GetConnectInfo>

externdef __imp_GetZeroDeviceInfo:PPROC
GetZeroDeviceInfo equ <__imp_GetZeroDeviceInfo>

externdef __imp_PortChangeCallback:PPROC
PortChangeCallback equ <__imp_PortChangeCallback>

externdef __imp_PortClearStatistics:PPROC
PortClearStatistics equ <__imp_PortClearStatistics>

externdef __imp_PortClose:PPROC
PortClose equ <__imp_PortClose>

externdef __imp_PortCompressionSetInfo:PPROC
PortCompressionSetInfo equ <__imp_PortCompressionSetInfo>

externdef __imp_PortConnect:PPROC
PortConnect equ <__imp_PortConnect>

externdef __imp_PortDisconnect:PPROC
PortDisconnect equ <__imp_PortDisconnect>

externdef __imp_PortEnum:PPROC
PortEnum equ <__imp_PortEnum>

externdef __imp_PortGetIOHandle:PPROC
PortGetIOHandle equ <__imp_PortGetIOHandle>

externdef __imp_PortGetInfo:PPROC
PortGetInfo equ <__imp_PortGetInfo>

externdef __imp_PortGetPortState:PPROC
PortGetPortState equ <__imp_PortGetPortState>

externdef __imp_PortGetStatistics:PPROC
PortGetStatistics equ <__imp_PortGetStatistics>

externdef __imp_PortInit:PPROC
PortInit equ <__imp_PortInit>

externdef __imp_PortOpen:PPROC
PortOpen equ <__imp_PortOpen>

externdef __imp_PortOpenExternal:PPROC
PortOpenExternal equ <__imp_PortOpenExternal>

externdef __imp_PortReceive:PPROC
PortReceive equ <__imp_PortReceive>

externdef __imp_PortReceiveComplete:PPROC
PortReceiveComplete equ <__imp_PortReceiveComplete>

externdef __imp_PortSend:PPROC
PortSend equ <__imp_PortSend>

externdef __imp_PortSetFraming:PPROC
PortSetFraming equ <__imp_PortSetFraming>

externdef __imp_PortSetInfo:PPROC
PortSetInfo equ <__imp_PortSetInfo>

externdef __imp_PortSetIoCompletionPort:PPROC
PortSetIoCompletionPort equ <__imp_PortSetIoCompletionPort>

externdef __imp_PortTestSignalState:PPROC
PortTestSignalState equ <__imp_PortTestSignalState>

externdef __imp_RasTapiIsPulseDial:PPROC
RasTapiIsPulseDial equ <__imp_RasTapiIsPulseDial>

externdef __imp_RastapiGetCalledID:PPROC
RastapiGetCalledID equ <__imp_RastapiGetCalledID>

externdef __imp_RastapiSetCalledID:PPROC
RastapiSetCalledID equ <__imp_RastapiSetCalledID>

externdef __imp_RemovePort:PPROC
RemovePort equ <__imp_RemovePort>

externdef __imp_SetCommSettings:PPROC
SetCommSettings equ <__imp_SetCommSettings>

externdef __imp_UnloadRastapiDll:PPROC
UnloadRastapiDll equ <__imp_UnloadRastapiDll>
