externdef __imp_DriverProc:PPROC
DriverProc equ <__imp_DriverProc>

externdef __imp_auxMessage:PPROC
auxMessage equ <__imp_auxMessage>

externdef __imp_midMessage:PPROC
midMessage equ <__imp_midMessage>

externdef __imp_modMessage:PPROC
modMessage equ <__imp_modMessage>

externdef __imp_mxdMessage:PPROC
mxdMessage equ <__imp_mxdMessage>

externdef __imp_widMessage:PPROC
widMessage equ <__imp_widMessage>

externdef __imp_wodMessage:PPROC
wodMessage equ <__imp_wodMessage>
