externdef __imp_AddRoute:PPROC
AddRoute equ <__imp_AddRoute>

externdef __imp_DeleteRoute:PPROC
DeleteRoute equ <__imp_DeleteRoute>

externdef __imp_FreeIPAddressTable:PPROC
FreeIPAddressTable equ <__imp_FreeIPAddressTable>

externdef __imp_FreeRouteTable:PPROC
FreeRouteTable equ <__imp_FreeRouteTable>

externdef __imp_GetIPAddressTable:PPROC
GetIPAddressTable equ <__imp_GetIPAddressTable>

externdef __imp_GetIfEntry:PPROC
GetIfEntry equ <__imp_GetIfEntry>

externdef __imp_GetRouteTable:PPROC
GetRouteTable equ <__imp_GetRouteTable>

externdef __imp_RefreshAddresses:PPROC
RefreshAddresses equ <__imp_RefreshAddresses>

externdef __imp_ReloadIPAddressTable:PPROC
ReloadIPAddressTable equ <__imp_ReloadIPAddressTable>

externdef __imp_SetAddrChangeNotifyEvent:PPROC
SetAddrChangeNotifyEvent equ <__imp_SetAddrChangeNotifyEvent>
