externdef __imp_CloseProc:PPROC
CloseProc equ <__imp_CloseProc>

externdef __imp_SPUninstall:PPROC
SPUninstall equ <__imp_SPUninstall>

externdef __imp_SPUninstallCallback:PPROC
SPUninstallCallback equ <__imp_SPUninstallCallback>

externdef __imp_SchedServiceMain:PPROC
SchedServiceMain equ <__imp_SchedServiceMain>

externdef __imp_SysPrepBackup:PPROC
SysPrepBackup equ <__imp_SysPrepBackup>

externdef __imp_SysPrepCallback:PPROC
SysPrepCallback equ <__imp_SysPrepCallback>

externdef __imp_SysPrepRestore:PPROC
SysPrepRestore equ <__imp_SysPrepRestore>
