externdef __imp_SfcGetNextProtectedFile:PPROC
SfcGetNextProtectedFile equ <__imp_SfcGetNextProtectedFile>

externdef __imp_SfcIsFileProtected:PPROC
SfcIsFileProtected equ <__imp_SfcIsFileProtected>

externdef __imp_SfcWLEventLogoff:PPROC
SfcWLEventLogoff equ <__imp_SfcWLEventLogoff>

externdef __imp_SfcWLEventLogon:PPROC
SfcWLEventLogon equ <__imp_SfcWLEventLogon>

externdef __imp_sfc_os_ordinal1:PPROC
sfc_os_ordinal1 equ <__imp_sfc_os_ordinal1>

externdef __imp_sfc_os_ordinal2:PPROC
sfc_os_ordinal2 equ <__imp_sfc_os_ordinal2>

externdef __imp_sfc_os_ordinal3:PPROC
sfc_os_ordinal3 equ <__imp_sfc_os_ordinal3>

externdef __imp_sfc_os_ordinal4:PPROC
sfc_os_ordinal4 equ <__imp_sfc_os_ordinal4>

externdef __imp_sfc_os_ordinal5:PPROC
sfc_os_ordinal5 equ <__imp_sfc_os_ordinal5>

externdef __imp_sfc_os_ordinal6:PPROC
sfc_os_ordinal6 equ <__imp_sfc_os_ordinal6>

externdef __imp_sfc_os_ordinal7:PPROC
sfc_os_ordinal7 equ <__imp_sfc_os_ordinal7>
