externdef __imp_AddUrlToFavorites:PPROC
AddUrlToFavorites equ <__imp_AddUrlToFavorites>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllGetVersion:PPROC
DllGetVersion equ <__imp_DllGetVersion>

externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllRegisterWindowClasses:PPROC
DllRegisterWindowClasses equ <__imp_DllRegisterWindowClasses>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_DoAddToFavDlg:PPROC
DoAddToFavDlg equ <__imp_DoAddToFavDlg>

externdef __imp_DoAddToFavDlgW:PPROC
DoAddToFavDlgW equ <__imp_DoAddToFavDlgW>
  IFDEF __UNICODE__
    DoAddToFavDlg equ <__imp_DoAddToFavDlgW>
  ENDIF

externdef __imp_DoFileDownload:PPROC
DoFileDownload equ <__imp_DoFileDownload>

externdef __imp_DoFileDownloadEx:PPROC
DoFileDownloadEx equ <__imp_DoFileDownloadEx>

externdef __imp_DoOrganizeFavDlg:PPROC
DoOrganizeFavDlg equ <__imp_DoOrganizeFavDlg>

externdef __imp_DoOrganizeFavDlgW:PPROC
DoOrganizeFavDlgW equ <__imp_DoOrganizeFavDlgW>
  IFDEF __UNICODE__
    DoOrganizeFavDlg equ <__imp_DoOrganizeFavDlgW>
  ENDIF

externdef __imp_DoPrivacyDlg:PPROC
DoPrivacyDlg equ <__imp_DoPrivacyDlg>

externdef __imp_HlinkFindFrame:PPROC
HlinkFindFrame equ <__imp_HlinkFindFrame>

externdef __imp_HlinkFrameNavigate:PPROC
HlinkFrameNavigate equ <__imp_HlinkFrameNavigate>

externdef __imp_HlinkFrameNavigateNHL:PPROC
HlinkFrameNavigateNHL equ <__imp_HlinkFrameNavigateNHL>

externdef __imp_IEWriteErrorLog:PPROC
IEWriteErrorLog equ <__imp_IEWriteErrorLog>

externdef __imp_ImportPrivacySettings:PPROC
ImportPrivacySettings equ <__imp_ImportPrivacySettings>

externdef __imp_OpenURL:PPROC
OpenURL equ <__imp_OpenURL>

externdef __imp_SHAddSubscribeFavorite:PPROC
SHAddSubscribeFavorite equ <__imp_SHAddSubscribeFavorite>

externdef __imp_SHGetIDispatchForFolder:PPROC
SHGetIDispatchForFolder equ <__imp_SHGetIDispatchForFolder>

externdef __imp_SetQueryNetSessionCount:PPROC
SetQueryNetSessionCount equ <__imp_SetQueryNetSessionCount>

externdef __imp_SetShellOfflineState:PPROC
SetShellOfflineState equ <__imp_SetShellOfflineState>

externdef __imp_SoftwareUpdateMessageBox:PPROC
SoftwareUpdateMessageBox equ <__imp_SoftwareUpdateMessageBox>

externdef __imp_URLQualifyA:PPROC
URLQualifyA equ <__imp_URLQualifyA>
  IFNDEF __UNICODE__
    URLQualify equ <__imp_URLQualifyA>
  ENDIF

externdef __imp_URLQualifyW:PPROC
URLQualifyW equ <__imp_URLQualifyW>
  IFDEF __UNICODE__
    URLQualify equ <__imp_URLQualifyW>
  ENDIF

externdef __imp_shdocvw_ordinal101:PPROC
shdocvw_ordinal101 equ <__imp_shdocvw_ordinal101>

externdef __imp_shdocvw_ordinal102:PPROC
shdocvw_ordinal102 equ <__imp_shdocvw_ordinal102>

externdef __imp_shdocvw_ordinal103:PPROC
shdocvw_ordinal103 equ <__imp_shdocvw_ordinal103>

externdef __imp_shdocvw_ordinal104:PPROC
shdocvw_ordinal104 equ <__imp_shdocvw_ordinal104>

externdef __imp_shdocvw_ordinal105:PPROC
shdocvw_ordinal105 equ <__imp_shdocvw_ordinal105>

externdef __imp_shdocvw_ordinal110:PPROC
shdocvw_ordinal110 equ <__imp_shdocvw_ordinal110>

externdef __imp_shdocvw_ordinal111:PPROC
shdocvw_ordinal111 equ <__imp_shdocvw_ordinal111>

externdef __imp_shdocvw_ordinal115:PPROC
shdocvw_ordinal115 equ <__imp_shdocvw_ordinal115>

externdef __imp_shdocvw_ordinal116:PPROC
shdocvw_ordinal116 equ <__imp_shdocvw_ordinal116>

externdef __imp_shdocvw_ordinal117:PPROC
shdocvw_ordinal117 equ <__imp_shdocvw_ordinal117>

externdef __imp_shdocvw_ordinal118:PPROC
shdocvw_ordinal118 equ <__imp_shdocvw_ordinal118>

externdef __imp_shdocvw_ordinal119:PPROC
shdocvw_ordinal119 equ <__imp_shdocvw_ordinal119>

externdef __imp_shdocvw_ordinal120:PPROC
shdocvw_ordinal120 equ <__imp_shdocvw_ordinal120>

externdef __imp_shdocvw_ordinal121:PPROC
shdocvw_ordinal121 equ <__imp_shdocvw_ordinal121>

externdef __imp_shdocvw_ordinal122:PPROC
shdocvw_ordinal122 equ <__imp_shdocvw_ordinal122>

externdef __imp_shdocvw_ordinal123:PPROC
shdocvw_ordinal123 equ <__imp_shdocvw_ordinal123>

externdef __imp_shdocvw_ordinal125:PPROC
shdocvw_ordinal125 equ <__imp_shdocvw_ordinal125>

externdef __imp_shdocvw_ordinal130:PPROC
shdocvw_ordinal130 equ <__imp_shdocvw_ordinal130>

externdef __imp_shdocvw_ordinal131:PPROC
shdocvw_ordinal131 equ <__imp_shdocvw_ordinal131>

externdef __imp_shdocvw_ordinal135:PPROC
shdocvw_ordinal135 equ <__imp_shdocvw_ordinal135>

externdef __imp_shdocvw_ordinal136:PPROC
shdocvw_ordinal136 equ <__imp_shdocvw_ordinal136>

externdef __imp_shdocvw_ordinal137:PPROC
shdocvw_ordinal137 equ <__imp_shdocvw_ordinal137>

externdef __imp_shdocvw_ordinal138:PPROC
shdocvw_ordinal138 equ <__imp_shdocvw_ordinal138>

externdef __imp_shdocvw_ordinal139:PPROC
shdocvw_ordinal139 equ <__imp_shdocvw_ordinal139>

externdef __imp_shdocvw_ordinal140:PPROC
shdocvw_ordinal140 equ <__imp_shdocvw_ordinal140>

externdef __imp_shdocvw_ordinal141:PPROC
shdocvw_ordinal141 equ <__imp_shdocvw_ordinal141>

externdef __imp_shdocvw_ordinal142:PPROC
shdocvw_ordinal142 equ <__imp_shdocvw_ordinal142>

externdef __imp_shdocvw_ordinal143:PPROC
shdocvw_ordinal143 equ <__imp_shdocvw_ordinal143>

externdef __imp_shdocvw_ordinal145:PPROC
shdocvw_ordinal145 equ <__imp_shdocvw_ordinal145>

externdef __imp_shdocvw_ordinal146:PPROC
shdocvw_ordinal146 equ <__imp_shdocvw_ordinal146>

externdef __imp_shdocvw_ordinal147:PPROC
shdocvw_ordinal147 equ <__imp_shdocvw_ordinal147>

externdef __imp_shdocvw_ordinal148:PPROC
shdocvw_ordinal148 equ <__imp_shdocvw_ordinal148>

externdef __imp_shdocvw_ordinal149:PPROC
shdocvw_ordinal149 equ <__imp_shdocvw_ordinal149>

externdef __imp_shdocvw_ordinal150:PPROC
shdocvw_ordinal150 equ <__imp_shdocvw_ordinal150>

externdef __imp_shdocvw_ordinal151:PPROC
shdocvw_ordinal151 equ <__imp_shdocvw_ordinal151>

externdef __imp_shdocvw_ordinal152:PPROC
shdocvw_ordinal152 equ <__imp_shdocvw_ordinal152>

externdef __imp_shdocvw_ordinal153:PPROC
shdocvw_ordinal153 equ <__imp_shdocvw_ordinal153>

externdef __imp_shdocvw_ordinal158:PPROC
shdocvw_ordinal158 equ <__imp_shdocvw_ordinal158>

externdef __imp_shdocvw_ordinal159:PPROC
shdocvw_ordinal159 equ <__imp_shdocvw_ordinal159>

externdef __imp_shdocvw_ordinal160:PPROC
shdocvw_ordinal160 equ <__imp_shdocvw_ordinal160>

externdef __imp_shdocvw_ordinal161:PPROC
shdocvw_ordinal161 equ <__imp_shdocvw_ordinal161>

externdef __imp_shdocvw_ordinal162:PPROC
shdocvw_ordinal162 equ <__imp_shdocvw_ordinal162>

externdef __imp_shdocvw_ordinal164:PPROC
shdocvw_ordinal164 equ <__imp_shdocvw_ordinal164>

externdef __imp_shdocvw_ordinal165:PPROC
shdocvw_ordinal165 equ <__imp_shdocvw_ordinal165>

externdef __imp_shdocvw_ordinal167:PPROC
shdocvw_ordinal167 equ <__imp_shdocvw_ordinal167>

externdef __imp_shdocvw_ordinal169:PPROC
shdocvw_ordinal169 equ <__imp_shdocvw_ordinal169>

externdef __imp_shdocvw_ordinal170:PPROC
shdocvw_ordinal170 equ <__imp_shdocvw_ordinal170>

externdef __imp_shdocvw_ordinal171:PPROC
shdocvw_ordinal171 equ <__imp_shdocvw_ordinal171>

externdef __imp_shdocvw_ordinal172:PPROC
shdocvw_ordinal172 equ <__imp_shdocvw_ordinal172>

externdef __imp_shdocvw_ordinal173:PPROC
shdocvw_ordinal173 equ <__imp_shdocvw_ordinal173>

externdef __imp_shdocvw_ordinal174:PPROC
shdocvw_ordinal174 equ <__imp_shdocvw_ordinal174>

externdef __imp_shdocvw_ordinal175:PPROC
shdocvw_ordinal175 equ <__imp_shdocvw_ordinal175>

externdef __imp_shdocvw_ordinal176:PPROC
shdocvw_ordinal176 equ <__imp_shdocvw_ordinal176>

externdef __imp_shdocvw_ordinal177:PPROC
shdocvw_ordinal177 equ <__imp_shdocvw_ordinal177>

externdef __imp_shdocvw_ordinal178:PPROC
shdocvw_ordinal178 equ <__imp_shdocvw_ordinal178>

externdef __imp_shdocvw_ordinal179:PPROC
shdocvw_ordinal179 equ <__imp_shdocvw_ordinal179>

externdef __imp_shdocvw_ordinal180:PPROC
shdocvw_ordinal180 equ <__imp_shdocvw_ordinal180>

externdef __imp_shdocvw_ordinal181:PPROC
shdocvw_ordinal181 equ <__imp_shdocvw_ordinal181>

externdef __imp_shdocvw_ordinal183:PPROC
shdocvw_ordinal183 equ <__imp_shdocvw_ordinal183>

externdef __imp_shdocvw_ordinal185:PPROC
shdocvw_ordinal185 equ <__imp_shdocvw_ordinal185>

externdef __imp_shdocvw_ordinal187:PPROC
shdocvw_ordinal187 equ <__imp_shdocvw_ordinal187>

externdef __imp_shdocvw_ordinal188:PPROC
shdocvw_ordinal188 equ <__imp_shdocvw_ordinal188>

externdef __imp_shdocvw_ordinal189:PPROC
shdocvw_ordinal189 equ <__imp_shdocvw_ordinal189>

externdef __imp_shdocvw_ordinal190:PPROC
shdocvw_ordinal190 equ <__imp_shdocvw_ordinal190>

externdef __imp_shdocvw_ordinal191:PPROC
shdocvw_ordinal191 equ <__imp_shdocvw_ordinal191>

externdef __imp_shdocvw_ordinal192:PPROC
shdocvw_ordinal192 equ <__imp_shdocvw_ordinal192>

externdef __imp_shdocvw_ordinal194:PPROC
shdocvw_ordinal194 equ <__imp_shdocvw_ordinal194>

externdef __imp_shdocvw_ordinal195:PPROC
shdocvw_ordinal195 equ <__imp_shdocvw_ordinal195>

externdef __imp_shdocvw_ordinal196:PPROC
shdocvw_ordinal196 equ <__imp_shdocvw_ordinal196>

externdef __imp_shdocvw_ordinal197:PPROC
shdocvw_ordinal197 equ <__imp_shdocvw_ordinal197>

externdef __imp_shdocvw_ordinal198:PPROC
shdocvw_ordinal198 equ <__imp_shdocvw_ordinal198>

externdef __imp_shdocvw_ordinal200:PPROC
shdocvw_ordinal200 equ <__imp_shdocvw_ordinal200>

externdef __imp_shdocvw_ordinal201:PPROC
shdocvw_ordinal201 equ <__imp_shdocvw_ordinal201>

externdef __imp_shdocvw_ordinal202:PPROC
shdocvw_ordinal202 equ <__imp_shdocvw_ordinal202>

externdef __imp_shdocvw_ordinal203:PPROC
shdocvw_ordinal203 equ <__imp_shdocvw_ordinal203>

externdef __imp_shdocvw_ordinal204:PPROC
shdocvw_ordinal204 equ <__imp_shdocvw_ordinal204>

externdef __imp_shdocvw_ordinal205:PPROC
shdocvw_ordinal205 equ <__imp_shdocvw_ordinal205>

externdef __imp_shdocvw_ordinal206:PPROC
shdocvw_ordinal206 equ <__imp_shdocvw_ordinal206>

externdef __imp_shdocvw_ordinal207:PPROC
shdocvw_ordinal207 equ <__imp_shdocvw_ordinal207>

externdef __imp_shdocvw_ordinal208:PPROC
shdocvw_ordinal208 equ <__imp_shdocvw_ordinal208>

externdef __imp_shdocvw_ordinal209:PPROC
shdocvw_ordinal209 equ <__imp_shdocvw_ordinal209>

externdef __imp_shdocvw_ordinal210:PPROC
shdocvw_ordinal210 equ <__imp_shdocvw_ordinal210>

externdef __imp_shdocvw_ordinal211:PPROC
shdocvw_ordinal211 equ <__imp_shdocvw_ordinal211>

externdef __imp_shdocvw_ordinal212:PPROC
shdocvw_ordinal212 equ <__imp_shdocvw_ordinal212>

externdef __imp_shdocvw_ordinal213:PPROC
shdocvw_ordinal213 equ <__imp_shdocvw_ordinal213>

externdef __imp_shdocvw_ordinal214:PPROC
shdocvw_ordinal214 equ <__imp_shdocvw_ordinal214>

externdef __imp_shdocvw_ordinal215:PPROC
shdocvw_ordinal215 equ <__imp_shdocvw_ordinal215>

externdef __imp_shdocvw_ordinal216:PPROC
shdocvw_ordinal216 equ <__imp_shdocvw_ordinal216>

externdef __imp_shdocvw_ordinal217:PPROC
shdocvw_ordinal217 equ <__imp_shdocvw_ordinal217>

externdef __imp_shdocvw_ordinal218:PPROC
shdocvw_ordinal218 equ <__imp_shdocvw_ordinal218>

externdef __imp_shdocvw_ordinal219:PPROC
shdocvw_ordinal219 equ <__imp_shdocvw_ordinal219>

externdef __imp_shdocvw_ordinal220:PPROC
shdocvw_ordinal220 equ <__imp_shdocvw_ordinal220>

externdef __imp_shdocvw_ordinal221:PPROC
shdocvw_ordinal221 equ <__imp_shdocvw_ordinal221>

externdef __imp_shdocvw_ordinal222:PPROC
shdocvw_ordinal222 equ <__imp_shdocvw_ordinal222>

externdef __imp_shdocvw_ordinal223:PPROC
shdocvw_ordinal223 equ <__imp_shdocvw_ordinal223>

externdef __imp_shdocvw_ordinal224:PPROC
shdocvw_ordinal224 equ <__imp_shdocvw_ordinal224>

externdef __imp_shdocvw_ordinal225:PPROC
shdocvw_ordinal225 equ <__imp_shdocvw_ordinal225>

externdef __imp_shdocvw_ordinal226:PPROC
shdocvw_ordinal226 equ <__imp_shdocvw_ordinal226>

externdef __imp_shdocvw_ordinal227:PPROC
shdocvw_ordinal227 equ <__imp_shdocvw_ordinal227>

externdef __imp_shdocvw_ordinal228:PPROC
shdocvw_ordinal228 equ <__imp_shdocvw_ordinal228>

externdef __imp_shdocvw_ordinal229:PPROC
shdocvw_ordinal229 equ <__imp_shdocvw_ordinal229>

externdef __imp_shdocvw_ordinal230:PPROC
shdocvw_ordinal230 equ <__imp_shdocvw_ordinal230>

externdef __imp_shdocvw_ordinal231:PPROC
shdocvw_ordinal231 equ <__imp_shdocvw_ordinal231>

externdef __imp_shdocvw_ordinal232:PPROC
shdocvw_ordinal232 equ <__imp_shdocvw_ordinal232>

externdef __imp_shdocvw_ordinal233:PPROC
shdocvw_ordinal233 equ <__imp_shdocvw_ordinal233>

externdef __imp_shdocvw_ordinal234:PPROC
shdocvw_ordinal234 equ <__imp_shdocvw_ordinal234>
