externdef __imp_SE_DllLoaded:PPROC
SE_DllLoaded equ <__imp_SE_DllLoaded>

externdef __imp_SE_DllUnloaded:PPROC
SE_DllUnloaded equ <__imp_SE_DllUnloaded>

externdef __imp_SE_DynamicShim:PPROC
SE_DynamicShim equ <__imp_SE_DynamicShim>

externdef __imp_SE_DynamicUnshim:PPROC
SE_DynamicUnshim equ <__imp_SE_DynamicUnshim>

externdef __imp_SE_InstallAfterInit:PPROC
SE_InstallAfterInit equ <__imp_SE_InstallAfterInit>

externdef __imp_SE_InstallBeforeInit:PPROC
SE_InstallBeforeInit equ <__imp_SE_InstallBeforeInit>

externdef __imp_SE_IsShimDll:PPROC
SE_IsShimDll equ <__imp_SE_IsShimDll>

externdef __imp_SE_ProcessDying:PPROC
SE_ProcessDying equ <__imp_SE_ProcessDying>

externdef __imp_SE_RemoveNTVDMTask:PPROC
SE_RemoveNTVDMTask equ <__imp_SE_RemoveNTVDMTask>

externdef __imp_SE_ShimNTVDM:PPROC
SE_ShimNTVDM equ <__imp_SE_ShimNTVDM>
