externdef __imp_CreateHardwareEventMoniker:PPROC
CreateHardwareEventMoniker equ <__imp_CreateHardwareEventMoniker>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_HardwareDetectionServiceMain:PPROC
HardwareDetectionServiceMain equ <__imp_HardwareDetectionServiceMain>

externdef __imp_ThemeServiceMain:PPROC
ThemeServiceMain equ <__imp_ThemeServiceMain>

externdef __imp_shsvcs_ordinal1:PPROC
shsvcs_ordinal1 equ <__imp_shsvcs_ordinal1>

externdef __imp_shsvcs_ordinal2:PPROC
shsvcs_ordinal2 equ <__imp_shsvcs_ordinal2>

externdef __imp_shsvcs_ordinal3:PPROC
shsvcs_ordinal3 equ <__imp_shsvcs_ordinal3>

externdef __imp_shsvcs_ordinal4:PPROC
shsvcs_ordinal4 equ <__imp_shsvcs_ordinal4>

externdef __imp_shsvcs_ordinal5:PPROC
shsvcs_ordinal5 equ <__imp_shsvcs_ordinal5>

externdef __imp_shsvcs_ordinal6:PPROC
shsvcs_ordinal6 equ <__imp_shsvcs_ordinal6>
