externdef __imp_SnmpSvcAddrIsIpx:PPROC
SnmpSvcAddrIsIpx equ <__imp_SnmpSvcAddrIsIpx>

externdef __imp_SnmpSvcAddrToSocket:PPROC
SnmpSvcAddrToSocket equ <__imp_SnmpSvcAddrToSocket>

externdef __imp_SnmpSvcGetEnterpriseOID:PPROC
SnmpSvcGetEnterpriseOID equ <__imp_SnmpSvcGetEnterpriseOID>

externdef __imp_SnmpSvcGetUptime:PPROC
SnmpSvcGetUptime equ <__imp_SnmpSvcGetUptime>

externdef __imp_SnmpSvcGetUptimeFromTime:PPROC
SnmpSvcGetUptimeFromTime equ <__imp_SnmpSvcGetUptimeFromTime>

externdef __imp_SnmpSvcInitUptime:PPROC
SnmpSvcInitUptime equ <__imp_SnmpSvcInitUptime>

externdef __imp_SnmpSvcSetLogLevel:PPROC
SnmpSvcSetLogLevel equ <__imp_SnmpSvcSetLogLevel>

externdef __imp_SnmpSvcSetLogType:PPROC
SnmpSvcSetLogType equ <__imp_SnmpSvcSetLogType>

externdef __imp_SnmpTfxClose:PPROC
SnmpTfxClose equ <__imp_SnmpTfxClose>

externdef __imp_SnmpTfxOpen:PPROC
SnmpTfxOpen equ <__imp_SnmpTfxOpen>

externdef __imp_SnmpTfxQuery:PPROC
SnmpTfxQuery equ <__imp_SnmpTfxQuery>

externdef __imp_SnmpUtilAnsiToUnicode:PPROC
SnmpUtilAnsiToUnicode equ <__imp_SnmpUtilAnsiToUnicode>

externdef __imp_SnmpUtilAsnAnyCpy:PPROC
SnmpUtilAsnAnyCpy equ <__imp_SnmpUtilAsnAnyCpy>

externdef __imp_SnmpUtilAsnAnyFree:PPROC
SnmpUtilAsnAnyFree equ <__imp_SnmpUtilAsnAnyFree>

externdef __imp_SnmpUtilDbgPrint:PPROC
SnmpUtilDbgPrint equ <__imp_SnmpUtilDbgPrint>

externdef __imp_SnmpUtilIdsToA:PPROC
SnmpUtilIdsToA equ <__imp_SnmpUtilIdsToA>
  IFNDEF __UNICODE__
    SnmpUtilIdsTo equ <__imp_SnmpUtilIdsToA>
  ENDIF

externdef __imp_SnmpUtilMemAlloc:PPROC
SnmpUtilMemAlloc equ <__imp_SnmpUtilMemAlloc>

externdef __imp_SnmpUtilMemFree:PPROC
SnmpUtilMemFree equ <__imp_SnmpUtilMemFree>

externdef __imp_SnmpUtilMemReAlloc:PPROC
SnmpUtilMemReAlloc equ <__imp_SnmpUtilMemReAlloc>

externdef __imp_SnmpUtilOctetsCmp:PPROC
SnmpUtilOctetsCmp equ <__imp_SnmpUtilOctetsCmp>

externdef __imp_SnmpUtilOctetsCpy:PPROC
SnmpUtilOctetsCpy equ <__imp_SnmpUtilOctetsCpy>

externdef __imp_SnmpUtilOctetsFree:PPROC
SnmpUtilOctetsFree equ <__imp_SnmpUtilOctetsFree>

externdef __imp_SnmpUtilOctetsNCmp:PPROC
SnmpUtilOctetsNCmp equ <__imp_SnmpUtilOctetsNCmp>

externdef __imp_SnmpUtilOidAppend:PPROC
SnmpUtilOidAppend equ <__imp_SnmpUtilOidAppend>

externdef __imp_SnmpUtilOidCmp:PPROC
SnmpUtilOidCmp equ <__imp_SnmpUtilOidCmp>

externdef __imp_SnmpUtilOidCpy:PPROC
SnmpUtilOidCpy equ <__imp_SnmpUtilOidCpy>

externdef __imp_SnmpUtilOidFree:PPROC
SnmpUtilOidFree equ <__imp_SnmpUtilOidFree>

externdef __imp_SnmpUtilOidNCmp:PPROC
SnmpUtilOidNCmp equ <__imp_SnmpUtilOidNCmp>

externdef __imp_SnmpUtilOidToA:PPROC
SnmpUtilOidToA equ <__imp_SnmpUtilOidToA>
  IFNDEF __UNICODE__
    SnmpUtilOidTo equ <__imp_SnmpUtilOidToA>
  ENDIF

externdef __imp_SnmpUtilPrintAsnAny:PPROC
SnmpUtilPrintAsnAny equ <__imp_SnmpUtilPrintAsnAny>

externdef __imp_SnmpUtilPrintOid:PPROC
SnmpUtilPrintOid equ <__imp_SnmpUtilPrintOid>

externdef __imp_SnmpUtilUTF8ToUnicode:PPROC
SnmpUtilUTF8ToUnicode equ <__imp_SnmpUtilUTF8ToUnicode>

externdef __imp_SnmpUtilUnicodeToAnsi:PPROC
SnmpUtilUnicodeToAnsi equ <__imp_SnmpUtilUnicodeToAnsi>

externdef __imp_SnmpUtilUnicodeToUTF8:PPROC
SnmpUtilUnicodeToUTF8 equ <__imp_SnmpUtilUnicodeToUTF8>

externdef __imp_SnmpUtilVarBindCpy:PPROC
SnmpUtilVarBindCpy equ <__imp_SnmpUtilVarBindCpy>

externdef __imp_SnmpUtilVarBindFree:PPROC
SnmpUtilVarBindFree equ <__imp_SnmpUtilVarBindFree>

externdef __imp_SnmpUtilVarBindListCpy:PPROC
SnmpUtilVarBindListCpy equ <__imp_SnmpUtilVarBindListCpy>

externdef __imp_SnmpUtilVarBindListFree:PPROC
SnmpUtilVarBindListFree equ <__imp_SnmpUtilVarBindListFree>
