externdef __imp_YDriverUnloadComplete:PPROC
YDriverUnloadComplete equ <__imp_YDriverUnloadComplete>

externdef __imp_YEndDocPrinter:PPROC
YEndDocPrinter equ <__imp_YEndDocPrinter>

externdef __imp_YFlushPrinter:PPROC
YFlushPrinter equ <__imp_YFlushPrinter>

externdef __imp_YGetPrinter:PPROC
YGetPrinter equ <__imp_YGetPrinter>

externdef __imp_YGetPrinterDriver2:PPROC
YGetPrinterDriver2 equ <__imp_YGetPrinterDriver2>

externdef __imp_YGetPrinterDriverDirectory:PPROC
YGetPrinterDriverDirectory equ <__imp_YGetPrinterDriverDirectory>

externdef __imp_YReadPrinter:PPROC
YReadPrinter equ <__imp_YReadPrinter>

externdef __imp_YSeekPrinter:PPROC
YSeekPrinter equ <__imp_YSeekPrinter>

externdef __imp_YSetJob:PPROC
YSetJob equ <__imp_YSetJob>

externdef __imp_YSetPort:PPROC
YSetPort equ <__imp_YSetPort>

externdef __imp_YSplReadPrinter:PPROC
YSplReadPrinter equ <__imp_YSplReadPrinter>

externdef __imp_YWritePrinter:PPROC
YWritePrinter equ <__imp_YWritePrinter>
