externdef __imp_AbortPrinter:PPROC
AbortPrinter equ <__imp_AbortPrinter>

externdef __imp_AddDriverCatalog:PPROC
AddDriverCatalog equ <__imp_AddDriverCatalog>

externdef __imp_AddFormW:PPROC
AddFormW equ <__imp_AddFormW>
  IFDEF __UNICODE__
    AddForm equ <__imp_AddFormW>
  ENDIF

externdef __imp_AddJobW:PPROC
AddJobW equ <__imp_AddJobW>
  IFDEF __UNICODE__
    AddJob equ <__imp_AddJobW>
  ENDIF

externdef __imp_AddMonitorW:PPROC
AddMonitorW equ <__imp_AddMonitorW>
  IFDEF __UNICODE__
    AddMonitor equ <__imp_AddMonitorW>
  ENDIF

externdef __imp_AddPerMachineConnectionW:PPROC
AddPerMachineConnectionW equ <__imp_AddPerMachineConnectionW>
  IFDEF __UNICODE__
    AddPerMachineConnection equ <__imp_AddPerMachineConnectionW>
  ENDIF

externdef __imp_AddPortExW:PPROC
AddPortExW equ <__imp_AddPortExW>
  IFDEF __UNICODE__
    AddPortEx equ <__imp_AddPortExW>
  ENDIF

externdef __imp_AddPortW:PPROC
AddPortW equ <__imp_AddPortW>
  IFDEF __UNICODE__
    AddPort equ <__imp_AddPortW>
  ENDIF

externdef __imp_AddPrintProcessorW:PPROC
AddPrintProcessorW equ <__imp_AddPrintProcessorW>
  IFDEF __UNICODE__
    AddPrintProcessor equ <__imp_AddPrintProcessorW>
  ENDIF

externdef __imp_AddPrintProvidorW:PPROC
AddPrintProvidorW equ <__imp_AddPrintProvidorW>
  IFDEF __UNICODE__
    AddPrintProvidor equ <__imp_AddPrintProvidorW>
  ENDIF

externdef __imp_AddPrinterConnectionW:PPROC
AddPrinterConnectionW equ <__imp_AddPrinterConnectionW>
  IFDEF __UNICODE__
    AddPrinterConnection equ <__imp_AddPrinterConnectionW>
  ENDIF

externdef __imp_AddPrinterDriverExW:PPROC
AddPrinterDriverExW equ <__imp_AddPrinterDriverExW>
  IFDEF __UNICODE__
    AddPrinterDriverEx equ <__imp_AddPrinterDriverExW>
  ENDIF

externdef __imp_AddPrinterDriverW:PPROC
AddPrinterDriverW equ <__imp_AddPrinterDriverW>
  IFDEF __UNICODE__
    AddPrinterDriver equ <__imp_AddPrinterDriverW>
  ENDIF

externdef __imp_AddPrinterExW:PPROC
AddPrinterExW equ <__imp_AddPrinterExW>
  IFDEF __UNICODE__
    AddPrinterEx equ <__imp_AddPrinterExW>
  ENDIF

externdef __imp_AddPrinterW:PPROC
AddPrinterW equ <__imp_AddPrinterW>
  IFDEF __UNICODE__
    AddPrinter equ <__imp_AddPrinterW>
  ENDIF

externdef __imp_AdjustPointers:PPROC
AdjustPointers equ <__imp_AdjustPointers>

externdef __imp_AdjustPointersInStructuresArray:PPROC
AdjustPointersInStructuresArray equ <__imp_AdjustPointersInStructuresArray>

externdef __imp_AlignKMPtr:PPROC
AlignKMPtr equ <__imp_AlignKMPtr>

externdef __imp_AlignRpcPtr:PPROC
AlignRpcPtr equ <__imp_AlignRpcPtr>

externdef __imp_AllocSplStr:PPROC
AllocSplStr equ <__imp_AllocSplStr>

externdef __imp_AllowRemoteCalls:PPROC
AllowRemoteCalls equ <__imp_AllowRemoteCalls>

externdef __imp_AppendPrinterNotifyInfoData:PPROC
AppendPrinterNotifyInfoData equ <__imp_AppendPrinterNotifyInfoData>

externdef __imp_BuildOtherNamesFromMachineName:PPROC
BuildOtherNamesFromMachineName equ <__imp_BuildOtherNamesFromMachineName>

externdef __imp_CacheAddName:PPROC
CacheAddName equ <__imp_CacheAddName>

externdef __imp_CacheCreateAndAddNode:PPROC
CacheCreateAndAddNode equ <__imp_CacheCreateAndAddNode>

externdef __imp_CacheCreateAndAddNodeWithIPAddresses:PPROC
CacheCreateAndAddNodeWithIPAddresses equ <__imp_CacheCreateAndAddNodeWithIPAddresses>

externdef __imp_CacheDeleteNode:PPROC
CacheDeleteNode equ <__imp_CacheDeleteNode>

externdef __imp_CacheIsNameCluster:PPROC
CacheIsNameCluster equ <__imp_CacheIsNameCluster>

externdef __imp_CacheIsNameInNodeList:PPROC
CacheIsNameInNodeList equ <__imp_CacheIsNameInNodeList>

externdef __imp_CallDrvDevModeConversion:PPROC
CallDrvDevModeConversion equ <__imp_CallDrvDevModeConversion>

externdef __imp_CallRouterFindFirstPrinterChangeNotification:PPROC
CallRouterFindFirstPrinterChangeNotification equ <__imp_CallRouterFindFirstPrinterChangeNotification>

externdef __imp_CheckLocalCall:PPROC
CheckLocalCall equ <__imp_CheckLocalCall>

externdef __imp_ClosePrinter:PPROC
ClosePrinter equ <__imp_ClosePrinter>

externdef __imp_ClusterSplClose:PPROC
ClusterSplClose equ <__imp_ClusterSplClose>

externdef __imp_ClusterSplIsAlive:PPROC
ClusterSplIsAlive equ <__imp_ClusterSplIsAlive>

externdef __imp_ClusterSplOpen:PPROC
ClusterSplOpen equ <__imp_ClusterSplOpen>

externdef __imp_ConfigurePortW:PPROC
ConfigurePortW equ <__imp_ConfigurePortW>
  IFDEF __UNICODE__
    ConfigurePort equ <__imp_ConfigurePortW>
  ENDIF

externdef __imp_CreatePrinterIC:PPROC
CreatePrinterIC equ <__imp_CreatePrinterIC>

externdef __imp_DbgGetPointers:PPROC
DbgGetPointers equ <__imp_DbgGetPointers>

externdef __imp_DeleteFormW:PPROC
DeleteFormW equ <__imp_DeleteFormW>
  IFDEF __UNICODE__
    DeleteForm equ <__imp_DeleteFormW>
  ENDIF

externdef __imp_DeleteMonitorW:PPROC
DeleteMonitorW equ <__imp_DeleteMonitorW>
  IFDEF __UNICODE__
    DeleteMonitor equ <__imp_DeleteMonitorW>
  ENDIF

externdef __imp_DeletePerMachineConnectionW:PPROC
DeletePerMachineConnectionW equ <__imp_DeletePerMachineConnectionW>
  IFDEF __UNICODE__
    DeletePerMachineConnection equ <__imp_DeletePerMachineConnectionW>
  ENDIF

externdef __imp_DeletePortW:PPROC
DeletePortW equ <__imp_DeletePortW>
  IFDEF __UNICODE__
    DeletePort equ <__imp_DeletePortW>
  ENDIF

externdef __imp_DeletePrintProcessorW:PPROC
DeletePrintProcessorW equ <__imp_DeletePrintProcessorW>
  IFDEF __UNICODE__
    DeletePrintProcessor equ <__imp_DeletePrintProcessorW>
  ENDIF

externdef __imp_DeletePrintProvidorW:PPROC
DeletePrintProvidorW equ <__imp_DeletePrintProvidorW>
  IFDEF __UNICODE__
    DeletePrintProvidor equ <__imp_DeletePrintProvidorW>
  ENDIF

externdef __imp_DeletePrinter:PPROC
DeletePrinter equ <__imp_DeletePrinter>

externdef __imp_DeletePrinterConnectionW:PPROC
DeletePrinterConnectionW equ <__imp_DeletePrinterConnectionW>
  IFDEF __UNICODE__
    DeletePrinterConnection equ <__imp_DeletePrinterConnectionW>
  ENDIF

externdef __imp_DeletePrinterDataExW:PPROC
DeletePrinterDataExW equ <__imp_DeletePrinterDataExW>
  IFDEF __UNICODE__
    DeletePrinterDataEx equ <__imp_DeletePrinterDataExW>
  ENDIF

externdef __imp_DeletePrinterDataW:PPROC
DeletePrinterDataW equ <__imp_DeletePrinterDataW>
  IFDEF __UNICODE__
    DeletePrinterData equ <__imp_DeletePrinterDataW>
  ENDIF

externdef __imp_DeletePrinterDriverExW:PPROC
DeletePrinterDriverExW equ <__imp_DeletePrinterDriverExW>
  IFDEF __UNICODE__
    DeletePrinterDriverEx equ <__imp_DeletePrinterDriverExW>
  ENDIF

externdef __imp_DeletePrinterDriverW:PPROC
DeletePrinterDriverW equ <__imp_DeletePrinterDriverW>
  IFDEF __UNICODE__
    DeletePrinterDriver equ <__imp_DeletePrinterDriverW>
  ENDIF

externdef __imp_DeletePrinterIC:PPROC
DeletePrinterIC equ <__imp_DeletePrinterIC>

externdef __imp_DeletePrinterKeyW:PPROC
DeletePrinterKeyW equ <__imp_DeletePrinterKeyW>
  IFDEF __UNICODE__
    DeletePrinterKey equ <__imp_DeletePrinterKeyW>
  ENDIF

externdef __imp_DllAllocSplMem:PPROC
DllAllocSplMem equ <__imp_DllAllocSplMem>

externdef __imp_DllFreeSplMem:PPROC
DllFreeSplMem equ <__imp_DllFreeSplMem>

externdef __imp_DllFreeSplStr:PPROC
DllFreeSplStr equ <__imp_DllFreeSplStr>

externdef __imp_EndDocPrinter:PPROC
EndDocPrinter equ <__imp_EndDocPrinter>

externdef __imp_EndPagePrinter:PPROC
EndPagePrinter equ <__imp_EndPagePrinter>

externdef __imp_EnumFormsW:PPROC
EnumFormsW equ <__imp_EnumFormsW>
  IFDEF __UNICODE__
    EnumForms equ <__imp_EnumFormsW>
  ENDIF

externdef __imp_EnumJobsW:PPROC
EnumJobsW equ <__imp_EnumJobsW>
  IFDEF __UNICODE__
    EnumJobs equ <__imp_EnumJobsW>
  ENDIF

externdef __imp_EnumMonitorsW:PPROC
EnumMonitorsW equ <__imp_EnumMonitorsW>
  IFDEF __UNICODE__
    EnumMonitors equ <__imp_EnumMonitorsW>
  ENDIF

externdef __imp_EnumPerMachineConnectionsW:PPROC
EnumPerMachineConnectionsW equ <__imp_EnumPerMachineConnectionsW>
  IFDEF __UNICODE__
    EnumPerMachineConnections equ <__imp_EnumPerMachineConnectionsW>
  ENDIF

externdef __imp_EnumPortsW:PPROC
EnumPortsW equ <__imp_EnumPortsW>
  IFDEF __UNICODE__
    EnumPorts equ <__imp_EnumPortsW>
  ENDIF

externdef __imp_EnumPrintProcessorDatatypesW:PPROC
EnumPrintProcessorDatatypesW equ <__imp_EnumPrintProcessorDatatypesW>
  IFDEF __UNICODE__
    EnumPrintProcessorDatatypes equ <__imp_EnumPrintProcessorDatatypesW>
  ENDIF

externdef __imp_EnumPrintProcessorsW:PPROC
EnumPrintProcessorsW equ <__imp_EnumPrintProcessorsW>
  IFDEF __UNICODE__
    EnumPrintProcessors equ <__imp_EnumPrintProcessorsW>
  ENDIF

externdef __imp_EnumPrinterDataExW:PPROC
EnumPrinterDataExW equ <__imp_EnumPrinterDataExW>
  IFDEF __UNICODE__
    EnumPrinterDataEx equ <__imp_EnumPrinterDataExW>
  ENDIF

externdef __imp_EnumPrinterDataW:PPROC
EnumPrinterDataW equ <__imp_EnumPrinterDataW>
  IFDEF __UNICODE__
    EnumPrinterData equ <__imp_EnumPrinterDataW>
  ENDIF

externdef __imp_EnumPrinterDriversW:PPROC
EnumPrinterDriversW equ <__imp_EnumPrinterDriversW>
  IFDEF __UNICODE__
    EnumPrinterDrivers equ <__imp_EnumPrinterDriversW>
  ENDIF

externdef __imp_EnumPrinterKeyW:PPROC
EnumPrinterKeyW equ <__imp_EnumPrinterKeyW>
  IFDEF __UNICODE__
    EnumPrinterKey equ <__imp_EnumPrinterKeyW>
  ENDIF

externdef __imp_EnumPrintersW:PPROC
EnumPrintersW equ <__imp_EnumPrintersW>
  IFDEF __UNICODE__
    EnumPrinters equ <__imp_EnumPrintersW>
  ENDIF

externdef __imp_FindClosePrinterChangeNotification:PPROC
FindClosePrinterChangeNotification equ <__imp_FindClosePrinterChangeNotification>

externdef __imp_FlushPrinter:PPROC
FlushPrinter equ <__imp_FlushPrinter>

externdef __imp_FormatPrinterForRegistryKey:PPROC
FormatPrinterForRegistryKey equ <__imp_FormatPrinterForRegistryKey>

externdef __imp_FormatRegistryKeyForPrinter:PPROC
FormatRegistryKeyForPrinter equ <__imp_FormatRegistryKeyForPrinter>

externdef __imp_FreeOtherNames:PPROC
FreeOtherNames equ <__imp_FreeOtherNames>

externdef __imp_GetClientUserHandle:PPROC
GetClientUserHandle equ <__imp_GetClientUserHandle>

externdef __imp_GetFormW:PPROC
GetFormW equ <__imp_GetFormW>
  IFDEF __UNICODE__
    GetForm equ <__imp_GetFormW>
  ENDIF

externdef __imp_GetJobAttributes:PPROC
GetJobAttributes equ <__imp_GetJobAttributes>

externdef __imp_GetJobW:PPROC
GetJobW equ <__imp_GetJobW>
  IFDEF __UNICODE__
    GetJob equ <__imp_GetJobW>
  ENDIF

externdef __imp_GetNetworkId:PPROC
GetNetworkId equ <__imp_GetNetworkId>

externdef __imp_GetPrintProcessorDirectoryW:PPROC
GetPrintProcessorDirectoryW equ <__imp_GetPrintProcessorDirectoryW>
  IFDEF __UNICODE__
    GetPrintProcessorDirectory equ <__imp_GetPrintProcessorDirectoryW>
  ENDIF

externdef __imp_GetPrinterDataExW:PPROC
GetPrinterDataExW equ <__imp_GetPrinterDataExW>
  IFDEF __UNICODE__
    GetPrinterDataEx equ <__imp_GetPrinterDataExW>
  ENDIF

externdef __imp_GetPrinterDataW:PPROC
GetPrinterDataW equ <__imp_GetPrinterDataW>
  IFDEF __UNICODE__
    GetPrinterData equ <__imp_GetPrinterDataW>
  ENDIF

externdef __imp_GetPrinterDriverDirectoryW:PPROC
GetPrinterDriverDirectoryW equ <__imp_GetPrinterDriverDirectoryW>
  IFDEF __UNICODE__
    GetPrinterDriverDirectory equ <__imp_GetPrinterDriverDirectoryW>
  ENDIF

externdef __imp_GetPrinterDriverExW:PPROC
GetPrinterDriverExW equ <__imp_GetPrinterDriverExW>
  IFDEF __UNICODE__
    GetPrinterDriverEx equ <__imp_GetPrinterDriverExW>
  ENDIF

externdef __imp_GetPrinterDriverW:PPROC
GetPrinterDriverW equ <__imp_GetPrinterDriverW>
  IFDEF __UNICODE__
    GetPrinterDriver equ <__imp_GetPrinterDriverW>
  ENDIF

externdef __imp_GetPrinterW:PPROC
GetPrinterW equ <__imp_GetPrinterW>
  IFDEF __UNICODE__
    GetPrinter equ <__imp_GetPrinterW>
  ENDIF

externdef __imp_GetServerPolicy:PPROC
GetServerPolicy equ <__imp_GetServerPolicy>

externdef __imp_GetShrinkedSize:PPROC
GetShrinkedSize equ <__imp_GetShrinkedSize>

externdef __imp_ImpersonatePrinterClient:PPROC
ImpersonatePrinterClient equ <__imp_ImpersonatePrinterClient>

externdef __imp_InitializeRouter:PPROC
InitializeRouter equ <__imp_InitializeRouter>

externdef __imp_IsNamedPipeRpcCall:PPROC
IsNamedPipeRpcCall equ <__imp_IsNamedPipeRpcCall>

externdef __imp_LoadDriver:PPROC
LoadDriver equ <__imp_LoadDriver>

externdef __imp_LoadDriverFiletoConvertDevmode:PPROC
LoadDriverFiletoConvertDevmode equ <__imp_LoadDriverFiletoConvertDevmode>

externdef __imp_LoadDriverWithVersion:PPROC
LoadDriverWithVersion equ <__imp_LoadDriverWithVersion>

externdef __imp_LogWmiTraceEvent:PPROC
LogWmiTraceEvent equ <__imp_LogWmiTraceEvent>

externdef __imp_MIDL_user_allocate1:PPROC
MIDL_user_allocate1 equ <__imp_MIDL_user_allocate1>

externdef __imp_MIDL_user_free1:PPROC
MIDL_user_free1 equ <__imp_MIDL_user_free1>

externdef __imp_MarshallDownStructure:PPROC
MarshallDownStructure equ <__imp_MarshallDownStructure>

externdef __imp_MarshallDownStructuresArray:PPROC
MarshallDownStructuresArray equ <__imp_MarshallDownStructuresArray>

externdef __imp_MarshallUpStructure:PPROC
MarshallUpStructure equ <__imp_MarshallUpStructure>

externdef __imp_MarshallUpStructuresArray:PPROC
MarshallUpStructuresArray equ <__imp_MarshallUpStructuresArray>

externdef __imp_OldGetPrinterDriverW:PPROC
OldGetPrinterDriverW equ <__imp_OldGetPrinterDriverW>
  IFDEF __UNICODE__
    OldGetPrinterDriver equ <__imp_OldGetPrinterDriverW>
  ENDIF

externdef __imp_OpenPrinterExW:PPROC
OpenPrinterExW equ <__imp_OpenPrinterExW>
  IFDEF __UNICODE__
    OpenPrinterEx equ <__imp_OpenPrinterExW>
  ENDIF

externdef __imp_OpenPrinterPortW:PPROC
OpenPrinterPortW equ <__imp_OpenPrinterPortW>
  IFDEF __UNICODE__
    OpenPrinterPort equ <__imp_OpenPrinterPortW>
  ENDIF

externdef __imp_OpenPrinterW:PPROC
OpenPrinterW equ <__imp_OpenPrinterW>
  IFDEF __UNICODE__
    OpenPrinter equ <__imp_OpenPrinterW>
  ENDIF

externdef __imp_PackStrings:PPROC
PackStrings equ <__imp_PackStrings>

externdef __imp_PartialReplyPrinterChangeNotification:PPROC
PartialReplyPrinterChangeNotification equ <__imp_PartialReplyPrinterChangeNotification>

externdef __imp_PlayGdiScriptOnPrinterIC:PPROC
PlayGdiScriptOnPrinterIC equ <__imp_PlayGdiScriptOnPrinterIC>

externdef __imp_PrinterHandleRundown:PPROC
PrinterHandleRundown equ <__imp_PrinterHandleRundown>

externdef __imp_PrinterMessageBoxW:PPROC
PrinterMessageBoxW equ <__imp_PrinterMessageBoxW>
  IFDEF __UNICODE__
    PrinterMessageBox equ <__imp_PrinterMessageBoxW>
  ENDIF

externdef __imp_ProvidorFindClosePrinterChangeNotification:PPROC
ProvidorFindClosePrinterChangeNotification equ <__imp_ProvidorFindClosePrinterChangeNotification>

externdef __imp_ProvidorFindFirstPrinterChangeNotification:PPROC
ProvidorFindFirstPrinterChangeNotification equ <__imp_ProvidorFindFirstPrinterChangeNotification>

externdef __imp_ReadPrinter:PPROC
ReadPrinter equ <__imp_ReadPrinter>

externdef __imp_ReallocSplMem:PPROC
ReallocSplMem equ <__imp_ReallocSplMem>

externdef __imp_ReallocSplStr:PPROC
ReallocSplStr equ <__imp_ReallocSplStr>

externdef __imp_RemoteFindFirstPrinterChangeNotification:PPROC
RemoteFindFirstPrinterChangeNotification equ <__imp_RemoteFindFirstPrinterChangeNotification>

externdef __imp_ReplyClosePrinter:PPROC
ReplyClosePrinter equ <__imp_ReplyClosePrinter>

externdef __imp_ReplyOpenPrinter:PPROC
ReplyOpenPrinter equ <__imp_ReplyOpenPrinter>

externdef __imp_ReplyPrinterChangeNotification:PPROC
ReplyPrinterChangeNotification equ <__imp_ReplyPrinterChangeNotification>

externdef __imp_ResetPrinterW:PPROC
ResetPrinterW equ <__imp_ResetPrinterW>
  IFDEF __UNICODE__
    ResetPrinter equ <__imp_ResetPrinterW>
  ENDIF

externdef __imp_RevertToPrinterSelf:PPROC
RevertToPrinterSelf equ <__imp_RevertToPrinterSelf>

externdef __imp_RouterAllocBidiMem:PPROC
RouterAllocBidiMem equ <__imp_RouterAllocBidiMem>

externdef __imp_RouterAllocBidiResponseContainer:PPROC
RouterAllocBidiResponseContainer equ <__imp_RouterAllocBidiResponseContainer>

externdef __imp_RouterAllocPrinterNotifyInfo:PPROC
RouterAllocPrinterNotifyInfo equ <__imp_RouterAllocPrinterNotifyInfo>

externdef __imp_RouterFindFirstPrinterChangeNotification:PPROC
RouterFindFirstPrinterChangeNotification equ <__imp_RouterFindFirstPrinterChangeNotification>

externdef __imp_RouterFindNextPrinterChangeNotification:PPROC
RouterFindNextPrinterChangeNotification equ <__imp_RouterFindNextPrinterChangeNotification>

externdef __imp_RouterFreeBidiMem:PPROC
RouterFreeBidiMem equ <__imp_RouterFreeBidiMem>

externdef __imp_RouterFreePrinterNotifyInfo:PPROC
RouterFreePrinterNotifyInfo equ <__imp_RouterFreePrinterNotifyInfo>

externdef __imp_RouterRefreshPrinterChangeNotification:PPROC
RouterRefreshPrinterChangeNotification equ <__imp_RouterRefreshPrinterChangeNotification>

externdef __imp_RouterReplyPrinter:PPROC
RouterReplyPrinter equ <__imp_RouterReplyPrinter>

externdef __imp_ScheduleJob:PPROC
ScheduleJob equ <__imp_ScheduleJob>

externdef __imp_SeekPrinter:PPROC
SeekPrinter equ <__imp_SeekPrinter>

externdef __imp_SendRecvBidiData:PPROC
SendRecvBidiData equ <__imp_SendRecvBidiData>

externdef __imp_SetAllocFailCount:PPROC
SetAllocFailCount equ <__imp_SetAllocFailCount>

externdef __imp_SetFormW:PPROC
SetFormW equ <__imp_SetFormW>
  IFDEF __UNICODE__
    SetForm equ <__imp_SetFormW>
  ENDIF

externdef __imp_SetJobW:PPROC
SetJobW equ <__imp_SetJobW>
  IFDEF __UNICODE__
    SetJob equ <__imp_SetJobW>
  ENDIF

externdef __imp_SetPortW:PPROC
SetPortW equ <__imp_SetPortW>
  IFDEF __UNICODE__
    SetPort equ <__imp_SetPortW>
  ENDIF

externdef __imp_SetPrinterDataExW:PPROC
SetPrinterDataExW equ <__imp_SetPrinterDataExW>
  IFDEF __UNICODE__
    SetPrinterDataEx equ <__imp_SetPrinterDataExW>
  ENDIF

externdef __imp_SetPrinterDataW:PPROC
SetPrinterDataW equ <__imp_SetPrinterDataW>
  IFDEF __UNICODE__
    SetPrinterData equ <__imp_SetPrinterDataW>
  ENDIF

externdef __imp_SetPrinterW:PPROC
SetPrinterW equ <__imp_SetPrinterW>
  IFDEF __UNICODE__
    SetPrinter equ <__imp_SetPrinterW>
  ENDIF

externdef __imp_SplCloseSpoolFileHandle:PPROC
SplCloseSpoolFileHandle equ <__imp_SplCloseSpoolFileHandle>

externdef __imp_SplCommitSpoolData:PPROC
SplCommitSpoolData equ <__imp_SplCommitSpoolData>

externdef __imp_SplDriverUnloadComplete:PPROC
SplDriverUnloadComplete equ <__imp_SplDriverUnloadComplete>

externdef __imp_SplGetSpoolFileInfo:PPROC
SplGetSpoolFileInfo equ <__imp_SplGetSpoolFileInfo>

externdef __imp_SplInitializeWinSpoolDrv:PPROC
SplInitializeWinSpoolDrv equ <__imp_SplInitializeWinSpoolDrv>

externdef __imp_SplIsSessionZero:PPROC
SplIsSessionZero equ <__imp_SplIsSessionZero>

externdef __imp_SplIsUpgrade:PPROC
SplIsUpgrade equ <__imp_SplIsUpgrade>

externdef __imp_SplPowerEvent:PPROC
SplPowerEvent equ <__imp_SplPowerEvent>

externdef __imp_SplProcessPnPEvent:PPROC
SplProcessPnPEvent equ <__imp_SplProcessPnPEvent>

externdef __imp_SplPromptUIInUsersSession:PPROC
SplPromptUIInUsersSession equ <__imp_SplPromptUIInUsersSession>

externdef __imp_SplReadPrinter:PPROC
SplReadPrinter equ <__imp_SplReadPrinter>

externdef __imp_SplRegisterForDeviceEvents:PPROC
SplRegisterForDeviceEvents equ <__imp_SplRegisterForDeviceEvents>

externdef __imp_SplShutDownRouter:PPROC
SplShutDownRouter equ <__imp_SplShutDownRouter>

externdef __imp_SplUnregisterForDeviceEvents:PPROC
SplUnregisterForDeviceEvents equ <__imp_SplUnregisterForDeviceEvents>

externdef __imp_SpoolerFindClosePrinterChangeNotification:PPROC
SpoolerFindClosePrinterChangeNotification equ <__imp_SpoolerFindClosePrinterChangeNotification>

externdef __imp_SpoolerFindFirstPrinterChangeNotification:PPROC
SpoolerFindFirstPrinterChangeNotification equ <__imp_SpoolerFindFirstPrinterChangeNotification>

externdef __imp_SpoolerFindNextPrinterChangeNotification:PPROC
SpoolerFindNextPrinterChangeNotification equ <__imp_SpoolerFindNextPrinterChangeNotification>

externdef __imp_SpoolerFreePrinterNotifyInfo:PPROC
SpoolerFreePrinterNotifyInfo equ <__imp_SpoolerFreePrinterNotifyInfo>

externdef __imp_SpoolerHasInitialized:PPROC
SpoolerHasInitialized equ <__imp_SpoolerHasInitialized>

externdef __imp_SpoolerInit:PPROC
SpoolerInit equ <__imp_SpoolerInit>

externdef __imp_StartDocPrinterW:PPROC
StartDocPrinterW equ <__imp_StartDocPrinterW>
  IFDEF __UNICODE__
    StartDocPrinter equ <__imp_StartDocPrinterW>
  ENDIF

externdef __imp_StartPagePrinter:PPROC
StartPagePrinter equ <__imp_StartPagePrinter>

externdef __imp_UndoAlignKMPtr:PPROC
UndoAlignKMPtr equ <__imp_UndoAlignKMPtr>

externdef __imp_UndoAlignRpcPtr:PPROC
UndoAlignRpcPtr equ <__imp_UndoAlignRpcPtr>

externdef __imp_UnloadDriver:PPROC
UnloadDriver equ <__imp_UnloadDriver>

externdef __imp_UnloadDriverFile:PPROC
UnloadDriverFile equ <__imp_UnloadDriverFile>

externdef __imp_UpdateBufferSize:PPROC
UpdateBufferSize equ <__imp_UpdateBufferSize>

externdef __imp_UpdatePrinterRegAll:PPROC
UpdatePrinterRegAll equ <__imp_UpdatePrinterRegAll>

externdef __imp_UpdatePrinterRegUser:PPROC
UpdatePrinterRegUser equ <__imp_UpdatePrinterRegUser>

externdef __imp_WaitForPrinterChange:PPROC
WaitForPrinterChange equ <__imp_WaitForPrinterChange>

externdef __imp_WaitForSpoolerInitialization:PPROC
WaitForSpoolerInitialization equ <__imp_WaitForSpoolerInitialization>

externdef __imp_WritePrinter:PPROC
WritePrinter equ <__imp_WritePrinter>

externdef __imp_XcvDataW:PPROC
XcvDataW equ <__imp_XcvDataW>
  IFDEF __UNICODE__
    XcvData equ <__imp_XcvDataW>
  ENDIF

externdef __imp_bGetDevModePerUser:PPROC
bGetDevModePerUser equ <__imp_bGetDevModePerUser>

externdef __imp_bSetDevModePerUser:PPROC
bSetDevModePerUser equ <__imp_bSetDevModePerUser>

externdef __imp_pszDbgAllocMsgA:PPROC
pszDbgAllocMsgA equ <__imp_pszDbgAllocMsgA>
  IFNDEF __UNICODE__
    pszDbgAllocMsg equ <__imp_pszDbgAllocMsgA>
  ENDIF

externdef __imp_vDbgLogError:PPROC
vDbgLogError equ <__imp_vDbgLogError>
