externdef __imp_CheckPrivilegesForRestore:PPROC
CheckPrivilegesForRestore equ <__imp_CheckPrivilegesForRestore>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_InitializeChangeNotify:PPROC
InitializeChangeNotify equ <__imp_InitializeChangeNotify>

externdef __imp_InitiateRestore:PPROC
InitiateRestore equ <__imp_InitiateRestore>

externdef __imp_InvokeDiskCleanup:PPROC
InvokeDiskCleanup equ <__imp_InvokeDiskCleanup>

externdef __imp_IsSRFrozen:PPROC
IsSRFrozen equ <__imp_IsSRFrozen>

externdef __imp_PasswordChangeNotify:PPROC
PasswordChangeNotify equ <__imp_PasswordChangeNotify>

externdef __imp_PrepareRestore:PPROC
PrepareRestore equ <__imp_PrepareRestore>

externdef __imp_ResumeRestore:PPROC
ResumeRestore equ <__imp_ResumeRestore>

externdef __imp_SRGetCplPropPage:PPROC
SRGetCplPropPage equ <__imp_SRGetCplPropPage>
