externdef __imp_CleanupCache:PPROC
CleanupCache equ <__imp_CleanupCache>

externdef __imp_DHDisableDeviceHost:PPROC
DHDisableDeviceHost equ <__imp_DHDisableDeviceHost>

externdef __imp_DHEnableDeviceHost:PPROC
DHEnableDeviceHost equ <__imp_DHEnableDeviceHost>

externdef __imp_DHSetICSInterfaces:PPROC
DHSetICSInterfaces equ <__imp_DHSetICSInterfaces>

externdef __imp_DHSetICSOff:PPROC
DHSetICSOff equ <__imp_DHSetICSOff>

externdef __imp_DeregisterNotification:PPROC
DeregisterNotification equ <__imp_DeregisterNotification>

externdef __imp_DeregisterService:PPROC
DeregisterService equ <__imp_DeregisterService>

externdef __imp_DeregisterServiceByUSN:PPROC
DeregisterServiceByUSN equ <__imp_DeregisterServiceByUSN>

externdef __imp_FindServices:PPROC
FindServices equ <__imp_FindServices>

externdef __imp_FindServicesCallback:PPROC
FindServicesCallback equ <__imp_FindServicesCallback>

externdef __imp_FindServicesCancel:PPROC
FindServicesCancel equ <__imp_FindServicesCancel>

externdef __imp_FindServicesClose:PPROC
FindServicesClose equ <__imp_FindServicesClose>

externdef __imp_FreeSsdpMessage:PPROC
FreeSsdpMessage equ <__imp_FreeSsdpMessage>

externdef __imp_GetFirstService:PPROC
GetFirstService equ <__imp_GetFirstService>

externdef __imp_GetNextService:PPROC
GetNextService equ <__imp_GetNextService>

externdef __imp_RegisterNotification:PPROC
RegisterNotification equ <__imp_RegisterNotification>

externdef __imp_RegisterService:PPROC
RegisterService equ <__imp_RegisterService>

externdef __imp_SsdpCleanup:PPROC
SsdpCleanup equ <__imp_SsdpCleanup>

externdef __imp_SsdpStartup:PPROC
SsdpStartup equ <__imp_SsdpStartup>
