externdef __imp_??0BUFFER@@QEAA@I@Z:PPROC
??0BUFFER@@QEAA@I@Z equ <__imp_??0BUFFER@@QEAA@I@Z>

externdef __imp_??0BUFFER_CHAIN@@QEAA@XZ:PPROC
??0BUFFER_CHAIN@@QEAA@XZ equ <__imp_??0BUFFER_CHAIN@@QEAA@XZ>

externdef __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PPROC
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z equ <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>

externdef __imp_??1BUFFER@@QEAA@XZ:PPROC
??1BUFFER@@QEAA@XZ equ <__imp_??1BUFFER@@QEAA@XZ>

externdef __imp_??1BUFFER_CHAIN@@QEAA@XZ:PPROC
??1BUFFER_CHAIN@@QEAA@XZ equ <__imp_??1BUFFER_CHAIN@@QEAA@XZ>

externdef __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PPROC
??1BUFFER_CHAIN_ITEM@@QEAA@XZ equ <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>

externdef __imp_??_FBUFFER@@QEAAXXZ:PPROC
??_FBUFFER@@QEAAXXZ equ <__imp_??_FBUFFER@@QEAAXXZ>

externdef __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PPROC
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ equ <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>

externdef __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PPROC
?QueryPtr@BUFFER@@QEBAPEAXXZ equ <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>

externdef __imp_?QuerySize@BUFFER@@QEBAIXZ:PPROC
?QuerySize@BUFFER@@QEBAIXZ equ <__imp_?QuerySize@BUFFER@@QEBAIXZ>

externdef __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PPROC
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ equ <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>

externdef __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PPROC
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z equ <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>

externdef __imp_AddDevice:PPROC
AddDevice equ <__imp_AddDevice>

externdef __imp_ClassInstall:PPROC
ClassInstall equ <__imp_ClassInstall>

externdef __imp_CoinstallerEntry:PPROC
CoinstallerEntry equ <__imp_CoinstallerEntry>

externdef __imp_InstallWiaService:PPROC
InstallWiaService equ <__imp_InstallWiaService>

externdef __imp_MigrateDevice:PPROC
MigrateDevice equ <__imp_MigrateDevice>

externdef __imp_PTPCoinstallerEntry:PPROC
PTPCoinstallerEntry equ <__imp_PTPCoinstallerEntry>

externdef __imp_WiaAddDevice:PPROC
WiaAddDevice equ <__imp_WiaAddDevice>

externdef __imp_WiaCreatePortList:PPROC
WiaCreatePortList equ <__imp_WiaCreatePortList>

externdef __imp_WiaCreateWizardMenu:PPROC
WiaCreateWizardMenu equ <__imp_WiaCreateWizardMenu>

externdef __imp_WiaDestroyPortList:PPROC
WiaDestroyPortList equ <__imp_WiaDestroyPortList>

externdef __imp_WiaRemoveDevice:PPROC
WiaRemoveDevice equ <__imp_WiaRemoveDevice>
