externdef __imp_?VssFreeSnapshotProperties@@YAXPEAU_VSS_SNAPSHOT_PROP@@@Z:PPROC
?VssFreeSnapshotProperties@@YAXPEAU_VSS_SNAPSHOT_PROP@@@Z equ <__imp_?VssFreeSnapshotProperties@@YAXPEAU_VSS_SNAPSHOT_PROP@@@Z>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_ServiceMain:PPROC
ServiceMain equ <__imp_ServiceMain>
