externdef __imp_AddAllTwinsToTwinList:PPROC
AddAllTwinsToTwinList equ <__imp_AddAllTwinsToTwinList>

externdef __imp_AddFolderTwin:PPROC
AddFolderTwin equ <__imp_AddFolderTwin>

externdef __imp_AddObjectTwin:PPROC
AddObjectTwin equ <__imp_AddObjectTwin>

externdef __imp_AddTwinToTwinList:PPROC
AddTwinToTwinList equ <__imp_AddTwinToTwinList>

externdef __imp_AnyTwins:PPROC
AnyTwins equ <__imp_AnyTwins>

externdef __imp_BeginReconciliation:PPROC
BeginReconciliation equ <__imp_BeginReconciliation>

externdef __imp_ClearBriefcaseCache:PPROC
ClearBriefcaseCache equ <__imp_ClearBriefcaseCache>

externdef __imp_CloseBriefcase:PPROC
CloseBriefcase equ <__imp_CloseBriefcase>

externdef __imp_CompareFileStamps:PPROC
CompareFileStamps equ <__imp_CompareFileStamps>

externdef __imp_CountSourceFolderTwins:PPROC
CountSourceFolderTwins equ <__imp_CountSourceFolderTwins>

externdef __imp_CreateFolderTwinList:PPROC
CreateFolderTwinList equ <__imp_CreateFolderTwinList>

externdef __imp_CreateRecList:PPROC
CreateRecList equ <__imp_CreateRecList>

externdef __imp_CreateTwinList:PPROC
CreateTwinList equ <__imp_CreateTwinList>

externdef __imp_DeleteBriefcase:PPROC
DeleteBriefcase equ <__imp_DeleteBriefcase>

externdef __imp_DeleteTwin:PPROC
DeleteTwin equ <__imp_DeleteTwin>

externdef __imp_DestroyFolderTwinList:PPROC
DestroyFolderTwinList equ <__imp_DestroyFolderTwinList>

externdef __imp_DestroyRecList:PPROC
DestroyRecList equ <__imp_DestroyRecList>

externdef __imp_DestroyTwinList:PPROC
DestroyTwinList equ <__imp_DestroyTwinList>

externdef __imp_EndReconciliation:PPROC
EndReconciliation equ <__imp_EndReconciliation>

externdef __imp_FindBriefcaseClose:PPROC
FindBriefcaseClose equ <__imp_FindBriefcaseClose>

externdef __imp_FindFirstBriefcase:PPROC
FindFirstBriefcase equ <__imp_FindFirstBriefcase>

externdef __imp_FindNextBriefcase:PPROC
FindNextBriefcase equ <__imp_FindNextBriefcase>

externdef __imp_GetFileStamp:PPROC
GetFileStamp equ <__imp_GetFileStamp>

externdef __imp_GetFolderTwinStatus:PPROC
GetFolderTwinStatus equ <__imp_GetFolderTwinStatus>

externdef __imp_GetObjectTwinHandle:PPROC
GetObjectTwinHandle equ <__imp_GetObjectTwinHandle>

externdef __imp_GetOpenBriefcaseInfo:PPROC
GetOpenBriefcaseInfo equ <__imp_GetOpenBriefcaseInfo>

externdef __imp_GetVolumeDescription:PPROC
GetVolumeDescription equ <__imp_GetVolumeDescription>

externdef __imp_IsFolderTwin:PPROC
IsFolderTwin equ <__imp_IsFolderTwin>

externdef __imp_IsOrphanObjectTwin:PPROC
IsOrphanObjectTwin equ <__imp_IsOrphanObjectTwin>

externdef __imp_IsPathOnVolume:PPROC
IsPathOnVolume equ <__imp_IsPathOnVolume>

externdef __imp_OpenBriefcase:PPROC
OpenBriefcase equ <__imp_OpenBriefcase>

externdef __imp_ReconcileItem:PPROC
ReconcileItem equ <__imp_ReconcileItem>

externdef __imp_ReleaseTwinHandle:PPROC
ReleaseTwinHandle equ <__imp_ReleaseTwinHandle>

externdef __imp_RemoveAllTwinsFromTwinList:PPROC
RemoveAllTwinsFromTwinList equ <__imp_RemoveAllTwinsFromTwinList>

externdef __imp_RemoveTwinFromTwinList:PPROC
RemoveTwinFromTwinList equ <__imp_RemoveTwinFromTwinList>

externdef __imp_SaveBriefcase:PPROC
SaveBriefcase equ <__imp_SaveBriefcase>
