externdef __imp_??0CTcpMib@@QEAA@AEBV0@@Z:PPROC
??0CTcpMib@@QEAA@AEBV0@@Z equ <__imp_??0CTcpMib@@QEAA@AEBV0@@Z>

externdef __imp_??0CTcpMib@@QEAA@XZ:PPROC
??0CTcpMib@@QEAA@XZ equ <__imp_??0CTcpMib@@QEAA@XZ>

externdef __imp_??0CTcpMibABC@@QEAA@AEBV0@@Z:PPROC
??0CTcpMibABC@@QEAA@AEBV0@@Z equ <__imp_??0CTcpMibABC@@QEAA@AEBV0@@Z>

externdef __imp_??0CTcpMibABC@@QEAA@XZ:PPROC
??0CTcpMibABC@@QEAA@XZ equ <__imp_??0CTcpMibABC@@QEAA@XZ>

externdef __imp_??1CTcpMib@@UEAA@XZ:PPROC
??1CTcpMib@@UEAA@XZ equ <__imp_??1CTcpMib@@UEAA@XZ>

externdef __imp_??1CTcpMibABC@@UEAA@XZ:PPROC
??1CTcpMibABC@@UEAA@XZ equ <__imp_??1CTcpMibABC@@UEAA@XZ>

externdef __imp_??4CTcpMib@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CTcpMib@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CTcpMib@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_7CTcpMib@@6B@:PPROC
??_7CTcpMib@@6B@ equ <__imp_??_7CTcpMib@@6B@>

externdef __imp_??_7CTcpMibABC@@6B@:PPROC
??_7CTcpMibABC@@6B@ equ <__imp_??_7CTcpMibABC@@6B@>

externdef __imp_?EnterCSection@CTcpMib@@AEAAXXZ:PPROC
?EnterCSection@CTcpMib@@AEAAXXZ equ <__imp_?EnterCSection@CTcpMib@@AEAAXXZ>

externdef __imp_?ExitCSection@CTcpMib@@AEAAXXZ:PPROC
?ExitCSection@CTcpMib@@AEAAXXZ equ <__imp_?ExitCSection@CTcpMib@@AEAAXXZ>

externdef __imp_?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z:PPROC
?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z equ <__imp_?GetDeviceDescription@CTcpMib@@UEAAKPEBD0KPEAGK@Z>

externdef __imp_?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z:PPROC
?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z equ <__imp_?GetDeviceHWAddress@CTcpMib@@UEAAKPEBD0KKPEAG@Z>

externdef __imp_?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z:PPROC
?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z equ <__imp_?GetDeviceName@CTcpMib@@UEAAKPEBD0KKPEAG@Z>

externdef __imp_?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z:PPROC
?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z equ <__imp_?GetNextRequestId@CTcpMib@@UEAAKPEAK@Z>

externdef __imp_?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z:PPROC
?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z equ <__imp_?GetStatusFromVBL@CTcpMib@@CAKPEAXPEAUsmiVALUE@@11@Z>

externdef __imp_?InitSnmp@CTcpMib@@UEAAKXZ:PPROC
?InitSnmp@CTcpMib@@UEAAKXZ equ <__imp_?InitSnmp@CTcpMib@@UEAAKXZ>

externdef __imp_?IsValid@CTcpMib@@QEBAHXZ:PPROC
?IsValid@CTcpMib@@QEBAHXZ equ <__imp_?IsValid@CTcpMib@@QEBAHXZ>

externdef __imp_?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z:PPROC
?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z equ <__imp_?MapAsynchToPortStatus@CTcpMib@@CAHKPEAU_PORT_INFO_3W@@@Z>

externdef __imp_?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z:PPROC
?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z equ <__imp_?RegisterDeviceStatusCallback@CTcpMib@@UEAAKP6AKHPEBD0KKK@ZPEAPEAX@Z>

externdef __imp_?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z:PPROC
?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z equ <__imp_?RequestDeviceStatus@CTcpMib@@UEAAKPEAXKPEBG1K@Z>

externdef __imp_?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z:PPROC
?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z equ <__imp_?SnmpCallback@CTcpMib@@CAKPEAX0I_K_J0@Z>

externdef __imp_?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z:PPROC
?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z equ <__imp_?SnmpGet@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z>

externdef __imp_?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z:PPROC
?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z equ <__imp_?SnmpGet@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z>

externdef __imp_?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z:PPROC
?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z equ <__imp_?SnmpGetNext@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z>

externdef __imp_?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z:PPROC
?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z equ <__imp_?SnmpGetNext@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z>

externdef __imp_?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z:PPROC
?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z equ <__imp_?SnmpWalk@CTcpMib@@QEAAKPEBD0KPEAUSnmpVarBindList@@@Z>

externdef __imp_?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z:PPROC
?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z equ <__imp_?SnmpWalk@CTcpMib@@UEAAKPEBD0KPEAUAsnObjectIdentifier@@PEAUSnmpVarBindList@@@Z>

externdef __imp_?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z:PPROC
?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z equ <__imp_?SupportsPrinterMib@CTcpMib@@UEAAHPEBD0KPEAH@Z>

externdef __imp_?UnInitSnmp@CTcpMib@@UEAAXXZ:PPROC
?UnInitSnmp@CTcpMib@@UEAAXXZ equ <__imp_?UnInitSnmp@CTcpMib@@UEAAXXZ>

externdef __imp_GetTcpMibPtr:PPROC
GetTcpMibPtr equ <__imp_GetTcpMibPtr>

externdef __imp_Ping:PPROC
Ping equ <__imp_Ping>
