externdef __imp_??0CPortABC@@QEAA@AEBV0@@Z:PPROC
??0CPortABC@@QEAA@AEBV0@@Z equ <__imp_??0CPortABC@@QEAA@AEBV0@@Z>

externdef __imp_??0CPortABC@@QEAA@XZ:PPROC
??0CPortABC@@QEAA@XZ equ <__imp_??0CPortABC@@QEAA@XZ>

externdef __imp_??0CTcpMibABC@@QEAA@AEBV0@@Z:PPROC
??0CTcpMibABC@@QEAA@AEBV0@@Z equ <__imp_??0CTcpMibABC@@QEAA@AEBV0@@Z>

externdef __imp_??0CTcpMibABC@@QEAA@XZ:PPROC
??0CTcpMibABC@@QEAA@XZ equ <__imp_??0CTcpMibABC@@QEAA@XZ>

externdef __imp_??1CPortABC@@UEAA@XZ:PPROC
??1CPortABC@@UEAA@XZ equ <__imp_??1CPortABC@@UEAA@XZ>

externdef __imp_??1CTcpMibABC@@UEAA@XZ:PPROC
??1CTcpMibABC@@UEAA@XZ equ <__imp_??1CTcpMibABC@@UEAA@XZ>

externdef __imp_??4CPortABC@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CPortABC@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CPortABC@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z:PPROC
??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4CTcpMibABC@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??_7CPortABC@@6B@:PPROC
??_7CPortABC@@6B@ equ <__imp_??_7CPortABC@@6B@>

externdef __imp_??_7CTcpMibABC@@6B@:PPROC
??_7CTcpMibABC@@6B@ equ <__imp_??_7CTcpMibABC@@6B@>

externdef __imp_?Read@CPortABC@@UEAAKQEAXPEAEKPEAK@Z:PPROC
?Read@CPortABC@@UEAAKQEAXPEAEKPEAK@Z equ <__imp_?Read@CPortABC@@UEAAKQEAXPEAEKPEAK@Z>

externdef __imp_InitializePrintMonitorUI:PPROC
InitializePrintMonitorUI equ <__imp_InitializePrintMonitorUI>

externdef __imp_LocalAddPortUI:PPROC
LocalAddPortUI equ <__imp_LocalAddPortUI>

externdef __imp_LocalConfigurePortUI:PPROC
LocalConfigurePortUI equ <__imp_LocalConfigurePortUI>
