externdef __imp_TrueSpeech_Decod:PPROC
TrueSpeech_Decod equ <__imp_TrueSpeech_Decod>

externdef __imp_TrueSpeech_Encod:PPROC
TrueSpeech_Encod equ <__imp_TrueSpeech_Encod>

externdef __imp_TrueSpeech_Init:PPROC
TrueSpeech_Init equ <__imp_TrueSpeech_Init>

externdef __imp_TrueSpeech_Reset:PPROC
TrueSpeech_Reset equ <__imp_TrueSpeech_Reset>

externdef __imp_TrueSpeech_Term:PPROC
TrueSpeech_Term equ <__imp_TrueSpeech_Term>

externdef __imp_TrueSpeech_Version:PPROC
TrueSpeech_Version equ <__imp_TrueSpeech_Version>
