externdef __imp_??0CLUSTER_CHAIN@@QEAA@XZ:PPROC
??0CLUSTER_CHAIN@@QEAA@XZ equ <__imp_??0CLUSTER_CHAIN@@QEAA@XZ>

externdef __imp_??0EA_HEADER@@QEAA@XZ:PPROC
??0EA_HEADER@@QEAA@XZ equ <__imp_??0EA_HEADER@@QEAA@XZ>

externdef __imp_??0EA_SET@@QEAA@XZ:PPROC
??0EA_SET@@QEAA@XZ equ <__imp_??0EA_SET@@QEAA@XZ>

externdef __imp_??0FAT_DIRENT@@QEAA@XZ:PPROC
??0FAT_DIRENT@@QEAA@XZ equ <__imp_??0FAT_DIRENT@@QEAA@XZ>

externdef __imp_??0FAT_SA@@QEAA@XZ:PPROC
??0FAT_SA@@QEAA@XZ equ <__imp_??0FAT_SA@@QEAA@XZ>

externdef __imp_??0FILEDIR@@QEAA@XZ:PPROC
??0FILEDIR@@QEAA@XZ equ <__imp_??0FILEDIR@@QEAA@XZ>

externdef __imp_??0REAL_FAT_SA@@QEAA@XZ:PPROC
??0REAL_FAT_SA@@QEAA@XZ equ <__imp_??0REAL_FAT_SA@@QEAA@XZ>

externdef __imp_??0ROOTDIR@@QEAA@XZ:PPROC
??0ROOTDIR@@QEAA@XZ equ <__imp_??0ROOTDIR@@QEAA@XZ>

externdef __imp_??1CLUSTER_CHAIN@@UEAA@XZ:PPROC
??1CLUSTER_CHAIN@@UEAA@XZ equ <__imp_??1CLUSTER_CHAIN@@UEAA@XZ>

externdef __imp_??1EA_HEADER@@UEAA@XZ:PPROC
??1EA_HEADER@@UEAA@XZ equ <__imp_??1EA_HEADER@@UEAA@XZ>

externdef __imp_??1EA_SET@@UEAA@XZ:PPROC
??1EA_SET@@UEAA@XZ equ <__imp_??1EA_SET@@UEAA@XZ>

externdef __imp_??1FAT_DIRENT@@UEAA@XZ:PPROC
??1FAT_DIRENT@@UEAA@XZ equ <__imp_??1FAT_DIRENT@@UEAA@XZ>

externdef __imp_??1FAT_SA@@UEAA@XZ:PPROC
??1FAT_SA@@UEAA@XZ equ <__imp_??1FAT_SA@@UEAA@XZ>

externdef __imp_??1FILEDIR@@UEAA@XZ:PPROC
??1FILEDIR@@UEAA@XZ equ <__imp_??1FILEDIR@@UEAA@XZ>

externdef __imp_??1REAL_FAT_SA@@UEAA@XZ:PPROC
??1REAL_FAT_SA@@UEAA@XZ equ <__imp_??1REAL_FAT_SA@@UEAA@XZ>

externdef __imp_??1ROOTDIR@@UEAA@XZ:PPROC
??1ROOTDIR@@UEAA@XZ equ <__imp_??1ROOTDIR@@UEAA@XZ>

externdef __imp_?AllocChain@FAT@@QEAAKKPEAK@Z:PPROC
?AllocChain@FAT@@QEAAKKPEAK@Z equ <__imp_?AllocChain@FAT@@QEAAKKPEAK@Z>

externdef __imp_?FreeChain@FAT@@QEAAXK@Z:PPROC
?FreeChain@FAT@@QEAAXK@Z equ <__imp_?FreeChain@FAT@@QEAAXK@Z>

externdef __imp_?GetEa@EA_SET@@QEAAPEAU_EA@@KPEAJPEAE@Z:PPROC
?GetEa@EA_SET@@QEAAPEAU_EA@@KPEAJPEAE@Z equ <__imp_?GetEa@EA_SET@@QEAAPEAU_EA@@KPEAJPEAE@Z>

externdef __imp_?Index12@FAT@@AEBAKK@Z:PPROC
?Index12@FAT@@AEBAKK@Z equ <__imp_?Index12@FAT@@AEBAKK@Z>

externdef __imp_?InitFATChkDirty@REAL_FAT_SA@@QEAAEPEAVLOG_IO_DP_DRIVE@@PEAVMESSAGE@@@Z:PPROC
?InitFATChkDirty@REAL_FAT_SA@@QEAAEPEAVLOG_IO_DP_DRIVE@@PEAVMESSAGE@@@Z equ <__imp_?InitFATChkDirty@REAL_FAT_SA@@QEAAEPEAVLOG_IO_DP_DRIVE@@PEAVMESSAGE@@@Z>

externdef __imp_?Initialize@CLUSTER_CHAIN@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z:PPROC
?Initialize@CLUSTER_CHAIN@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z equ <__imp_?Initialize@CLUSTER_CHAIN@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z>

externdef __imp_?Initialize@EA_HEADER@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z:PPROC
?Initialize@EA_HEADER@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z equ <__imp_?Initialize@EA_HEADER@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z>

externdef __imp_?Initialize@EA_SET@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z:PPROC
?Initialize@EA_SET@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z equ <__imp_?Initialize@EA_SET@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@KK@Z>

externdef __imp_?Initialize@FAT_DIRENT@@QEAAEPEAX@Z:PPROC
?Initialize@FAT_DIRENT@@QEAAEPEAX@Z equ <__imp_?Initialize@FAT_DIRENT@@QEAAEPEAX@Z>

externdef __imp_?Initialize@FAT_DIRENT@@QEAAEPEAXE@Z:PPROC
?Initialize@FAT_DIRENT@@QEAAEPEAXE@Z equ <__imp_?Initialize@FAT_DIRENT@@QEAAEPEAXE@Z>

externdef __imp_?Initialize@FILEDIR@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@K@Z:PPROC
?Initialize@FILEDIR@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@K@Z equ <__imp_?Initialize@FILEDIR@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@PEAVFAT_SA@@PEBVFAT@@K@Z>

externdef __imp_?Initialize@REAL_FAT_SA@@UEAAEPEAVLOG_IO_DP_DRIVE@@PEAVMESSAGE@@E@Z:PPROC
?Initialize@REAL_FAT_SA@@UEAAEPEAVLOG_IO_DP_DRIVE@@PEAVMESSAGE@@E@Z equ <__imp_?Initialize@REAL_FAT_SA@@UEAAEPEAVLOG_IO_DP_DRIVE@@PEAVMESSAGE@@E@Z>

externdef __imp_?Initialize@ROOTDIR@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@KJ@Z:PPROC
?Initialize@ROOTDIR@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@KJ@Z equ <__imp_?Initialize@ROOTDIR@@QEAAEPEAVMEM@@PEAVLOG_IO_DP_DRIVE@@KJ@Z>

externdef __imp_?IsValidCreationTime@FAT_DIRENT@@QEBAEXZ:PPROC
?IsValidCreationTime@FAT_DIRENT@@QEBAEXZ equ <__imp_?IsValidCreationTime@FAT_DIRENT@@QEBAEXZ>

externdef __imp_?IsValidLastAccessTime@FAT_DIRENT@@QEBAEXZ:PPROC
?IsValidLastAccessTime@FAT_DIRENT@@QEBAEXZ equ <__imp_?IsValidLastAccessTime@FAT_DIRENT@@QEBAEXZ>

externdef __imp_?IsValidLastWriteTime@FAT_DIRENT@@QEBAEXZ:PPROC
?IsValidLastWriteTime@FAT_DIRENT@@QEBAEXZ equ <__imp_?IsValidLastWriteTime@FAT_DIRENT@@QEBAEXZ>

externdef __imp_?QueryAllocatedClusters@FAT@@QEBAKXZ:PPROC
?QueryAllocatedClusters@FAT@@QEBAKXZ equ <__imp_?QueryAllocatedClusters@FAT@@QEBAKXZ>

externdef __imp_?QueryCensusAndRelocate@FAT_SA@@QEAAEPEAU_CENSUS_REPORT@@PEAVINTSTACK@@PEAE@Z:PPROC
?QueryCensusAndRelocate@FAT_SA@@QEAAEPEAU_CENSUS_REPORT@@PEAVINTSTACK@@PEAE@Z equ <__imp_?QueryCensusAndRelocate@FAT_SA@@QEAAEPEAU_CENSUS_REPORT@@PEAVINTSTACK@@PEAE@Z>

externdef __imp_?QueryCreationTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z:PPROC
?QueryCreationTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z equ <__imp_?QueryCreationTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z>

externdef __imp_?QueryEaSetClusterNumber@EA_HEADER@@QEBAGG@Z:PPROC
?QueryEaSetClusterNumber@EA_HEADER@@QEBAGG@Z equ <__imp_?QueryEaSetClusterNumber@EA_HEADER@@QEBAGG@Z>

externdef __imp_?QueryFileStartingCluster@FAT_SA@@QEAAKPEBVWSTRING@@PEAVHMEM@@PEAPEAVFATDIR@@PEAEPEAVFAT_DIRENT@@@Z:PPROC
?QueryFileStartingCluster@FAT_SA@@QEAAKPEBVWSTRING@@PEAVHMEM@@PEAPEAVFATDIR@@PEAEPEAVFAT_DIRENT@@@Z equ <__imp_?QueryFileStartingCluster@FAT_SA@@QEAAKPEBVWSTRING@@PEAVHMEM@@PEAPEAVFATDIR@@PEAEPEAVFAT_DIRENT@@@Z>

externdef __imp_?QueryFreeSectors@REAL_FAT_SA@@QEBAKXZ:PPROC
?QueryFreeSectors@REAL_FAT_SA@@QEBAKXZ equ <__imp_?QueryFreeSectors@REAL_FAT_SA@@QEBAKXZ>

externdef __imp_?QueryLastAccessTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z:PPROC
?QueryLastAccessTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z equ <__imp_?QueryLastAccessTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z>

externdef __imp_?QueryLastWriteTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z:PPROC
?QueryLastWriteTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z equ <__imp_?QueryLastWriteTime@FAT_DIRENT@@QEBAEPEAT_LARGE_INTEGER@@@Z>

externdef __imp_?QueryLengthOfChain@FAT@@QEBAKKPEAK@Z:PPROC
?QueryLengthOfChain@FAT@@QEBAKKPEAK@Z equ <__imp_?QueryLengthOfChain@FAT@@QEBAKKPEAK@Z>

externdef __imp_?QueryLongName@FATDIR@@QEAAEJPEAVWSTRING@@@Z:PPROC
?QueryLongName@FATDIR@@QEAAEJPEAVWSTRING@@@Z equ <__imp_?QueryLongName@FATDIR@@QEAAEJPEAVWSTRING@@@Z>

externdef __imp_?QueryName@FAT_DIRENT@@QEBAEPEAVWSTRING@@@Z:PPROC
?QueryName@FAT_DIRENT@@QEBAEPEAVWSTRING@@@Z equ <__imp_?QueryName@FAT_DIRENT@@QEBAEPEAVWSTRING@@@Z>

externdef __imp_?QueryNthCluster@FAT@@QEBAKKK@Z:PPROC
?QueryNthCluster@FAT@@QEBAKKK@Z equ <__imp_?QueryNthCluster@FAT@@QEBAKKK@Z>

externdef __imp_?Read@CLUSTER_CHAIN@@UEAAEXZ:PPROC
?Read@CLUSTER_CHAIN@@UEAAEXZ equ <__imp_?Read@CLUSTER_CHAIN@@UEAAEXZ>

externdef __imp_?Read@EA_SET@@UEAAEXZ:PPROC
?Read@EA_SET@@UEAAEXZ equ <__imp_?Read@EA_SET@@UEAAEXZ>

externdef __imp_?Read@REAL_FAT_SA@@UEAAEPEAVMESSAGE@@@Z:PPROC
?Read@REAL_FAT_SA@@UEAAEPEAVMESSAGE@@@Z equ <__imp_?Read@REAL_FAT_SA@@UEAAEPEAVMESSAGE@@@Z>

externdef __imp_?SearchForDirEntry@FATDIR@@QEAAPEAXPEBVWSTRING@@@Z:PPROC
?SearchForDirEntry@FATDIR@@QEAAPEAXPEBVWSTRING@@@Z equ <__imp_?SearchForDirEntry@FATDIR@@QEAAPEAXPEBVWSTRING@@@Z>

externdef __imp_?Set12@FAT@@AEAAXKK@Z:PPROC
?Set12@FAT@@AEAAXKK@Z equ <__imp_?Set12@FAT@@AEAAXKK@Z>

externdef __imp_?Write@CLUSTER_CHAIN@@UEAAEXZ:PPROC
?Write@CLUSTER_CHAIN@@UEAAEXZ equ <__imp_?Write@CLUSTER_CHAIN@@UEAAEXZ>

externdef __imp_Chkdsk:PPROC
Chkdsk equ <__imp_Chkdsk>

externdef __imp_ChkdskEx:PPROC
ChkdskEx equ <__imp_ChkdskEx>

externdef __imp_Format:PPROC
Format equ <__imp_Format>

externdef __imp_FormatEx:PPROC
FormatEx equ <__imp_FormatEx>

externdef __imp_Recover:PPROC
Recover equ <__imp_Recover>
