externdef __imp_??0ARGUMENT_LEXEMIZER@@QEAA@XZ:PPROC
??0ARGUMENT_LEXEMIZER@@QEAA@XZ equ <__imp_??0ARGUMENT_LEXEMIZER@@QEAA@XZ>

externdef __imp_??0ARRAY@@QEAA@XZ:PPROC
??0ARRAY@@QEAA@XZ equ <__imp_??0ARRAY@@QEAA@XZ>

externdef __imp_??0BDSTRING@@QEAA@AEBV0@@Z:PPROC
??0BDSTRING@@QEAA@AEBV0@@Z equ <__imp_??0BDSTRING@@QEAA@AEBV0@@Z>

externdef __imp_??0BDSTRING@@QEAA@XZ:PPROC
??0BDSTRING@@QEAA@XZ equ <__imp_??0BDSTRING@@QEAA@XZ>

externdef __imp_??0BITVECTOR@@QEAA@XZ:PPROC
??0BITVECTOR@@QEAA@XZ equ <__imp_??0BITVECTOR@@QEAA@XZ>

externdef __imp_??0BSTRING@@IEAA@XZ:PPROC
??0BSTRING@@IEAA@XZ equ <__imp_??0BSTRING@@IEAA@XZ>

externdef __imp_??0BSTRING@@QEAA@AEBV0@@Z:PPROC
??0BSTRING@@QEAA@AEBV0@@Z equ <__imp_??0BSTRING@@QEAA@AEBV0@@Z>

externdef __imp_??0BYTE_STREAM@@QEAA@XZ:PPROC
??0BYTE_STREAM@@QEAA@XZ equ <__imp_??0BYTE_STREAM@@QEAA@XZ>

externdef __imp_??0CHKDSK_MESSAGE@@QEAA@XZ:PPROC
??0CHKDSK_MESSAGE@@QEAA@XZ equ <__imp_??0CHKDSK_MESSAGE@@QEAA@XZ>

externdef __imp_??0CLASS_DESCRIPTOR@@QEAA@XZ:PPROC
??0CLASS_DESCRIPTOR@@QEAA@XZ equ <__imp_??0CLASS_DESCRIPTOR@@QEAA@XZ>

externdef __imp_??0COMM_DEVICE@@QEAA@XZ:PPROC
??0COMM_DEVICE@@QEAA@XZ equ <__imp_??0COMM_DEVICE@@QEAA@XZ>

externdef __imp_??0CONT_MEM@@QEAA@XZ:PPROC
??0CONT_MEM@@QEAA@XZ equ <__imp_??0CONT_MEM@@QEAA@XZ>

externdef __imp_??0DSTRING@@QEAA@AEBV0@@Z:PPROC
??0DSTRING@@QEAA@AEBV0@@Z equ <__imp_??0DSTRING@@QEAA@AEBV0@@Z>

externdef __imp_??0DSTRING@@QEAA@XZ:PPROC
??0DSTRING@@QEAA@XZ equ <__imp_??0DSTRING@@QEAA@XZ>

externdef __imp_??0FLAG_ARGUMENT@@QEAA@XZ:PPROC
??0FLAG_ARGUMENT@@QEAA@XZ equ <__imp_??0FLAG_ARGUMENT@@QEAA@XZ>

externdef __imp_??0FSN_FILTER@@QEAA@XZ:PPROC
??0FSN_FILTER@@QEAA@XZ equ <__imp_??0FSN_FILTER@@QEAA@XZ>

externdef __imp_??0FSTRING@@QEAA@AEBV0@@Z:PPROC
??0FSTRING@@QEAA@AEBV0@@Z equ <__imp_??0FSTRING@@QEAA@AEBV0@@Z>

externdef __imp_??0FSTRING@@QEAA@XZ:PPROC
??0FSTRING@@QEAA@XZ equ <__imp_??0FSTRING@@QEAA@XZ>

externdef __imp_??0HMEM@@QEAA@XZ:PPROC
??0HMEM@@QEAA@XZ equ <__imp_??0HMEM@@QEAA@XZ>

externdef __imp_??0KEYBOARD@@QEAA@XZ:PPROC
??0KEYBOARD@@QEAA@XZ equ <__imp_??0KEYBOARD@@QEAA@XZ>

externdef __imp_??0LIST@@QEAA@XZ:PPROC
??0LIST@@QEAA@XZ equ <__imp_??0LIST@@QEAA@XZ>

externdef __imp_??0LONG_ARGUMENT@@QEAA@XZ:PPROC
??0LONG_ARGUMENT@@QEAA@XZ equ <__imp_??0LONG_ARGUMENT@@QEAA@XZ>

externdef __imp_??0MEM_ALLOCATOR@@QEAA@XZ:PPROC
??0MEM_ALLOCATOR@@QEAA@XZ equ <__imp_??0MEM_ALLOCATOR@@QEAA@XZ>

externdef __imp_??0MEM_BLOCK_MGR@@QEAA@XZ:PPROC
??0MEM_BLOCK_MGR@@QEAA@XZ equ <__imp_??0MEM_BLOCK_MGR@@QEAA@XZ>

externdef __imp_??0MESSAGE@@QEAA@XZ:PPROC
??0MESSAGE@@QEAA@XZ equ <__imp_??0MESSAGE@@QEAA@XZ>

externdef __imp_??0MULTIPLE_PATH_ARGUMENT@@QEAA@XZ:PPROC
??0MULTIPLE_PATH_ARGUMENT@@QEAA@XZ equ <__imp_??0MULTIPLE_PATH_ARGUMENT@@QEAA@XZ>

externdef __imp_??0OBJECT@@IEAA@XZ:PPROC
??0OBJECT@@IEAA@XZ equ <__imp_??0OBJECT@@IEAA@XZ>

externdef __imp_??0OBJECT@@QEAA@AEBV0@@Z:PPROC
??0OBJECT@@QEAA@AEBV0@@Z equ <__imp_??0OBJECT@@QEAA@AEBV0@@Z>

externdef __imp_??0PATH@@QEAA@XZ:PPROC
??0PATH@@QEAA@XZ equ <__imp_??0PATH@@QEAA@XZ>

externdef __imp_??0PATH_ARGUMENT@@QEAA@XZ:PPROC
??0PATH_ARGUMENT@@QEAA@XZ equ <__imp_??0PATH_ARGUMENT@@QEAA@XZ>

externdef __imp_??0PRINT_STREAM@@QEAA@XZ:PPROC
??0PRINT_STREAM@@QEAA@XZ equ <__imp_??0PRINT_STREAM@@QEAA@XZ>

externdef __imp_??0PROGRAM@@IEAA@XZ:PPROC
??0PROGRAM@@IEAA@XZ equ <__imp_??0PROGRAM@@IEAA@XZ>

externdef __imp_??0REST_OF_LINE_ARGUMENT@@QEAA@XZ:PPROC
??0REST_OF_LINE_ARGUMENT@@QEAA@XZ equ <__imp_??0REST_OF_LINE_ARGUMENT@@QEAA@XZ>

externdef __imp_??0SCREEN@@QEAA@XZ:PPROC
??0SCREEN@@QEAA@XZ equ <__imp_??0SCREEN@@QEAA@XZ>

externdef __imp_??0SORTED_LIST@@QEAA@XZ:PPROC
??0SORTED_LIST@@QEAA@XZ equ <__imp_??0SORTED_LIST@@QEAA@XZ>

externdef __imp_??0STREAM_MESSAGE@@QEAA@XZ:PPROC
??0STREAM_MESSAGE@@QEAA@XZ equ <__imp_??0STREAM_MESSAGE@@QEAA@XZ>

externdef __imp_??0STRING_ARGUMENT@@QEAA@XZ:PPROC
??0STRING_ARGUMENT@@QEAA@XZ equ <__imp_??0STRING_ARGUMENT@@QEAA@XZ>

externdef __imp_??0STRING_ARRAY@@QEAA@XZ:PPROC
??0STRING_ARRAY@@QEAA@XZ equ <__imp_??0STRING_ARRAY@@QEAA@XZ>

externdef __imp_??0TIMEINFO@@QEAA@XZ:PPROC
??0TIMEINFO@@QEAA@XZ equ <__imp_??0TIMEINFO@@QEAA@XZ>

externdef __imp_??0TIMEINFO_ARGUMENT@@QEAA@XZ:PPROC
??0TIMEINFO_ARGUMENT@@QEAA@XZ equ <__imp_??0TIMEINFO_ARGUMENT@@QEAA@XZ>

externdef __imp_??0WSTRING@@IEAA@XZ:PPROC
??0WSTRING@@IEAA@XZ equ <__imp_??0WSTRING@@IEAA@XZ>

externdef __imp_??0WSTRING@@QEAA@AEBV0@@Z:PPROC
??0WSTRING@@QEAA@AEBV0@@Z equ <__imp_??0WSTRING@@QEAA@AEBV0@@Z>

externdef __imp_??1ARGUMENT_LEXEMIZER@@UEAA@XZ:PPROC
??1ARGUMENT_LEXEMIZER@@UEAA@XZ equ <__imp_??1ARGUMENT_LEXEMIZER@@UEAA@XZ>

externdef __imp_??1ARRAY@@UEAA@XZ:PPROC
??1ARRAY@@UEAA@XZ equ <__imp_??1ARRAY@@UEAA@XZ>

externdef __imp_??1BDSTRING@@UEAA@XZ:PPROC
??1BDSTRING@@UEAA@XZ equ <__imp_??1BDSTRING@@UEAA@XZ>

externdef __imp_??1BITVECTOR@@UEAA@XZ:PPROC
??1BITVECTOR@@UEAA@XZ equ <__imp_??1BITVECTOR@@UEAA@XZ>

externdef __imp_??1BSTRING@@UEAA@XZ:PPROC
??1BSTRING@@UEAA@XZ equ <__imp_??1BSTRING@@UEAA@XZ>

externdef __imp_??1BYTE_STREAM@@UEAA@XZ:PPROC
??1BYTE_STREAM@@UEAA@XZ equ <__imp_??1BYTE_STREAM@@UEAA@XZ>

externdef __imp_??1CHKDSK_MESSAGE@@UEAA@XZ:PPROC
??1CHKDSK_MESSAGE@@UEAA@XZ equ <__imp_??1CHKDSK_MESSAGE@@UEAA@XZ>

externdef __imp_??1COMM_DEVICE@@UEAA@XZ:PPROC
??1COMM_DEVICE@@UEAA@XZ equ <__imp_??1COMM_DEVICE@@UEAA@XZ>

externdef __imp_??1DSTRING@@UEAA@XZ:PPROC
??1DSTRING@@UEAA@XZ equ <__imp_??1DSTRING@@UEAA@XZ>

externdef __imp_??1FSN_FILTER@@UEAA@XZ:PPROC
??1FSN_FILTER@@UEAA@XZ equ <__imp_??1FSN_FILTER@@UEAA@XZ>

externdef __imp_??1FSTRING@@UEAA@XZ:PPROC
??1FSTRING@@UEAA@XZ equ <__imp_??1FSTRING@@UEAA@XZ>

externdef __imp_??1HMEM@@UEAA@XZ:PPROC
??1HMEM@@UEAA@XZ equ <__imp_??1HMEM@@UEAA@XZ>

externdef __imp_??1LIST@@UEAA@XZ:PPROC
??1LIST@@UEAA@XZ equ <__imp_??1LIST@@UEAA@XZ>

externdef __imp_??1MEM_ALLOCATOR@@UEAA@XZ:PPROC
??1MEM_ALLOCATOR@@UEAA@XZ equ <__imp_??1MEM_ALLOCATOR@@UEAA@XZ>

externdef __imp_??1MEM_BLOCK_MGR@@UEAA@XZ:PPROC
??1MEM_BLOCK_MGR@@UEAA@XZ equ <__imp_??1MEM_BLOCK_MGR@@UEAA@XZ>

externdef __imp_??1MESSAGE@@UEAA@XZ:PPROC
??1MESSAGE@@UEAA@XZ equ <__imp_??1MESSAGE@@UEAA@XZ>

externdef __imp_??1MULTIPLE_PATH_ARGUMENT@@UEAA@XZ:PPROC
??1MULTIPLE_PATH_ARGUMENT@@UEAA@XZ equ <__imp_??1MULTIPLE_PATH_ARGUMENT@@UEAA@XZ>

externdef __imp_??1OBJECT@@UEAA@XZ:PPROC
??1OBJECT@@UEAA@XZ equ <__imp_??1OBJECT@@UEAA@XZ>

externdef __imp_??1PATH@@UEAA@XZ:PPROC
??1PATH@@UEAA@XZ equ <__imp_??1PATH@@UEAA@XZ>

externdef __imp_??1PATH_ARGUMENT@@UEAA@XZ:PPROC
??1PATH_ARGUMENT@@UEAA@XZ equ <__imp_??1PATH_ARGUMENT@@UEAA@XZ>

externdef __imp_??1PRINT_STREAM@@UEAA@XZ:PPROC
??1PRINT_STREAM@@UEAA@XZ equ <__imp_??1PRINT_STREAM@@UEAA@XZ>

externdef __imp_??1PROGRAM@@UEAA@XZ:PPROC
??1PROGRAM@@UEAA@XZ equ <__imp_??1PROGRAM@@UEAA@XZ>

externdef __imp_??1SCREEN@@UEAA@XZ:PPROC
??1SCREEN@@UEAA@XZ equ <__imp_??1SCREEN@@UEAA@XZ>

externdef __imp_??1SORTED_LIST@@UEAA@XZ:PPROC
??1SORTED_LIST@@UEAA@XZ equ <__imp_??1SORTED_LIST@@UEAA@XZ>

externdef __imp_??1STREAM_MESSAGE@@UEAA@XZ:PPROC
??1STREAM_MESSAGE@@UEAA@XZ equ <__imp_??1STREAM_MESSAGE@@UEAA@XZ>

externdef __imp_??1STRING_ARGUMENT@@UEAA@XZ:PPROC
??1STRING_ARGUMENT@@UEAA@XZ equ <__imp_??1STRING_ARGUMENT@@UEAA@XZ>

externdef __imp_??1TIMEINFO_ARGUMENT@@UEAA@XZ:PPROC
??1TIMEINFO_ARGUMENT@@UEAA@XZ equ <__imp_??1TIMEINFO_ARGUMENT@@UEAA@XZ>

externdef __imp_??1WSTRING@@UEAA@XZ:PPROC
??1WSTRING@@UEAA@XZ equ <__imp_??1WSTRING@@UEAA@XZ>

externdef __imp_??4BDSTRING@@QEAAAEAV0@AEBV0@@Z:PPROC
??4BDSTRING@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4BDSTRING@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4BSTRING@@QEAAAEAV0@AEBV0@@Z:PPROC
??4BSTRING@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4BSTRING@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4DSTRING@@QEAAAEAV0@AEBV0@@Z:PPROC
??4DSTRING@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4DSTRING@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4FSTRING@@QEAAAEAV0@AEBV0@@Z:PPROC
??4FSTRING@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4FSTRING@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4OBJECT@@QEAAAEAV0@AEBV0@@Z:PPROC
??4OBJECT@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4OBJECT@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??4WSTRING@@QEAAAEAV0@AEBV0@@Z:PPROC
??4WSTRING@@QEAAAEAV0@AEBV0@@Z equ <__imp_??4WSTRING@@QEAAAEAV0@AEBV0@@Z>

externdef __imp_??8WSTRING@@QEBAEAEBV0@@Z:PPROC
??8WSTRING@@QEBAEAEBV0@@Z equ <__imp_??8WSTRING@@QEBAEAEBV0@@Z>

externdef __imp_??9WSTRING@@QEBAEAEBV0@@Z:PPROC
??9WSTRING@@QEBAEAEBV0@@Z equ <__imp_??9WSTRING@@QEBAEAEBV0@@Z>

externdef __imp_??MTIMEINFO@@QEBAEV0@@Z:PPROC
??MTIMEINFO@@QEBAEV0@@Z equ <__imp_??MTIMEINFO@@QEBAEV0@@Z>

externdef __imp_??MWSTRING@@QEBAEAEBV0@@Z:PPROC
??MWSTRING@@QEBAEAEBV0@@Z equ <__imp_??MWSTRING@@QEBAEAEBV0@@Z>

externdef __imp_??NWSTRING@@QEBAEAEBV0@@Z:PPROC
??NWSTRING@@QEBAEAEBV0@@Z equ <__imp_??NWSTRING@@QEBAEAEBV0@@Z>

externdef __imp_??OTIMEINFO@@QEBAEV0@@Z:PPROC
??OTIMEINFO@@QEBAEV0@@Z equ <__imp_??OTIMEINFO@@QEBAEV0@@Z>

externdef __imp_??OWSTRING@@QEBAEAEBV0@@Z:PPROC
??OWSTRING@@QEBAEAEBV0@@Z equ <__imp_??OWSTRING@@QEBAEAEBV0@@Z>

externdef __imp_??PWSTRING@@QEBAEAEBV0@@Z:PPROC
??PWSTRING@@QEBAEAEBV0@@Z equ <__imp_??PWSTRING@@QEBAEAEBV0@@Z>

externdef __imp_??_7BDSTRING@@6B@:PPROC
??_7BDSTRING@@6B@ equ <__imp_??_7BDSTRING@@6B@>

externdef __imp_??_7BSTRING@@6B@:PPROC
??_7BSTRING@@6B@ equ <__imp_??_7BSTRING@@6B@>

externdef __imp_??_7DSTRING@@6B@:PPROC
??_7DSTRING@@6B@ equ <__imp_??_7DSTRING@@6B@>

externdef __imp_??_7FSTRING@@6B@:PPROC
??_7FSTRING@@6B@ equ <__imp_??_7FSTRING@@6B@>

externdef __imp_??_7OBJECT@@6B@:PPROC
??_7OBJECT@@6B@ equ <__imp_??_7OBJECT@@6B@>

externdef __imp_??_7WSTRING@@6B@:PPROC
??_7WSTRING@@6B@ equ <__imp_??_7WSTRING@@6B@>

externdef __imp_?Acquire@CONT_MEM@@UEAAPEAXKK@Z:PPROC
?Acquire@CONT_MEM@@UEAAPEAXKK@Z equ <__imp_?Acquire@CONT_MEM@@UEAAPEAXKK@Z>

externdef __imp_?Acquire@HMEM@@UEAAPEAXKK@Z:PPROC
?Acquire@HMEM@@UEAAPEAXKK@Z equ <__imp_?Acquire@HMEM@@UEAAPEAXKK@Z>

externdef __imp_?Alloc@MEM_BLOCK_MGR@@QEAAPEAXXZ:PPROC
?Alloc@MEM_BLOCK_MGR@@QEAAPEAXXZ equ <__imp_?Alloc@MEM_BLOCK_MGR@@QEAAPEAXXZ>

externdef __imp_?Allocate@MEM_ALLOCATOR@@QEAAPEAXK@Z:PPROC
?Allocate@MEM_ALLOCATOR@@QEAAPEAXK@Z equ <__imp_?Allocate@MEM_ALLOCATOR@@QEAAPEAXK@Z>

externdef __imp_?AnalyzePath@PATH@@QEAA?AW4PATH_ANALYZE_CODE@@PEAVWSTRING@@PEAV1@0@Z:PPROC
?AnalyzePath@PATH@@QEAA?AW4PATH_ANALYZE_CODE@@PEAVWSTRING@@PEAV1@0@Z equ <__imp_?AnalyzePath@PATH@@QEAA?AW4PATH_ANALYZE_CODE@@PEAVWSTRING@@PEAV1@0@Z>

externdef __imp_?AppendBase@PATH@@QEAAEPEBVWSTRING@@E@Z:PPROC
?AppendBase@PATH@@QEAAEPEBVWSTRING@@E@Z equ <__imp_?AppendBase@PATH@@QEAAEPEBVWSTRING@@E@Z>

externdef __imp_?AppendDelimiter@PATH@@QEAAEXZ:PPROC
?AppendDelimiter@PATH@@QEAAEXZ equ <__imp_?AppendDelimiter@PATH@@QEAAEXZ>

externdef __imp_?AppendString@PATH@@QEAAEPEBVWSTRING@@@Z:PPROC
?AppendString@PATH@@QEAAEPEBVWSTRING@@@Z equ <__imp_?AppendString@PATH@@QEAAEPEBVWSTRING@@@Z>

externdef __imp_?Cast@FILE_STREAM@@SAPEAV1@PEBVOBJECT@@@Z:PPROC
?Cast@FILE_STREAM@@SAPEAV1@PEBVOBJECT@@@Z equ <__imp_?Cast@FILE_STREAM@@SAPEAV1@PEBVOBJECT@@@Z>

externdef __imp_?Cast@KEYBOARD@@SAPEAV1@PEBVOBJECT@@@Z:PPROC
?Cast@KEYBOARD@@SAPEAV1@PEBVOBJECT@@@Z equ <__imp_?Cast@KEYBOARD@@SAPEAV1@PEBVOBJECT@@@Z>

externdef __imp_?Cast@SCREEN@@SAPEAV1@PEBVOBJECT@@@Z:PPROC
?Cast@SCREEN@@SAPEAV1@PEBVOBJECT@@@Z equ <__imp_?Cast@SCREEN@@SAPEAV1@PEBVOBJECT@@@Z>

externdef __imp_?ChangeScreenSize@SCREEN@@QEAAEGGPEAE@Z:PPROC
?ChangeScreenSize@SCREEN@@QEAAEGGPEAE@Z equ <__imp_?ChangeScreenSize@SCREEN@@QEAAEGGPEAE@Z>

externdef __imp_?CharNextW@MBSTR@@SAPEADPEAD@Z:PPROC
?CharNextW@MBSTR@@SAPEADPEAD@Z equ <__imp_?CharNextW@MBSTR@@SAPEADPEAD@Z>

externdef __imp_?CheckSpace@WSTRING@@CAHPEAG@Z:PPROC
?CheckSpace@WSTRING@@CAHPEAG@Z equ <__imp_?CheckSpace@WSTRING@@CAHPEAG@Z>

externdef __imp_?CommitState@COMM_DEVICE@@QEAAEXZ:PPROC
?CommitState@COMM_DEVICE@@QEAAEXZ equ <__imp_?CommitState@COMM_DEVICE@@QEAAEXZ>

externdef __imp_?Compare@OBJECT@@UEBAJPEBV1@@Z:PPROC
?Compare@OBJECT@@UEBAJPEBV1@@Z equ <__imp_?Compare@OBJECT@@UEBAJPEBV1@@Z>

externdef __imp_?ComputeCountSet@BITVECTOR@@AEBAKXZ:PPROC
?ComputeCountSet@BITVECTOR@@AEBAKXZ equ <__imp_?ComputeCountSet@BITVECTOR@@AEBAKXZ>

externdef __imp_?Construct@BDSTRING@@AEAAXXZ:PPROC
?Construct@BDSTRING@@AEAAXXZ equ <__imp_?Construct@BDSTRING@@AEAAXXZ>

externdef __imp_?Construct@BSTRING@@IEAAXXZ:PPROC
?Construct@BSTRING@@IEAAXXZ equ <__imp_?Construct@BSTRING@@IEAAXXZ>

externdef __imp_?Construct@DSTRING@@AEAAXXZ:PPROC
?Construct@DSTRING@@AEAAXXZ equ <__imp_?Construct@DSTRING@@AEAAXXZ>

externdef __imp_?Construct@OBJECT@@IEAAXXZ:PPROC
?Construct@OBJECT@@IEAAXXZ equ <__imp_?Construct@OBJECT@@IEAAXXZ>

externdef __imp_?Construct@WSTRING@@IEAAXXZ:PPROC
?Construct@WSTRING@@IEAAXXZ equ <__imp_?Construct@WSTRING@@IEAAXXZ>

externdef __imp_?ConvertOemToUnicodeN@WSTRING@@CAEPEAGKPEAKPEADK@Z:PPROC
?ConvertOemToUnicodeN@WSTRING@@CAEPEAGKPEAKPEADK@Z equ <__imp_?ConvertOemToUnicodeN@WSTRING@@CAEPEAGKPEAKPEADK@Z>

externdef __imp_?ConvertToLocal@TIMEINFO@@QEAAEXZ:PPROC
?ConvertToLocal@TIMEINFO@@QEAAEXZ equ <__imp_?ConvertToLocal@TIMEINFO@@QEAAEXZ>

externdef __imp_?ConvertToUTC@TIMEINFO@@QEAAEXZ:PPROC
?ConvertToUTC@TIMEINFO@@QEAAEXZ equ <__imp_?ConvertToUTC@TIMEINFO@@QEAAEXZ>

externdef __imp_?ConvertUnicodeToOemN@WSTRING@@CAEPEADKPEAKPEAGK@Z:PPROC
?ConvertUnicodeToOemN@WSTRING@@CAEPEADKPEAKPEAGK@Z equ <__imp_?ConvertUnicodeToOemN@WSTRING@@CAEPEADKPEAKPEAGK@Z>

externdef __imp_?Copy@FSN_FILE@@QEBAEPEAVPATH@@PEAW4_COPY_ERROR@@KP6AKT_LARGE_INTEGER@@222KKPEAX33@Z3PEAH@Z:PPROC
?Copy@FSN_FILE@@QEBAEPEAVPATH@@PEAW4_COPY_ERROR@@KP6AKT_LARGE_INTEGER@@222KKPEAX33@Z3PEAH@Z equ <__imp_?Copy@FSN_FILE@@QEBAEPEAVPATH@@PEAW4_COPY_ERROR@@KP6AKT_LARGE_INTEGER@@222KKPEAX33@Z3PEAH@Z>

externdef __imp_?CreateDirectoryPath@FSN_DIRECTORY@@QEBAPEAV1@PEBVPATH@@@Z:PPROC
?CreateDirectoryPath@FSN_DIRECTORY@@QEBAPEAV1@PEBVPATH@@@Z equ <__imp_?CreateDirectoryPath@FSN_DIRECTORY@@QEBAPEAV1@PEBVPATH@@@Z>

externdef __imp_?DeleteAllMembers@ARRAY@@UEAAEXZ:PPROC
?DeleteAllMembers@ARRAY@@UEAAEXZ equ <__imp_?DeleteAllMembers@ARRAY@@UEAAEXZ>

externdef __imp_?DeleteAllMembers@SEQUENTIAL_CONTAINER@@UEAAEXZ:PPROC
?DeleteAllMembers@SEQUENTIAL_CONTAINER@@UEAAEXZ equ <__imp_?DeleteAllMembers@SEQUENTIAL_CONTAINER@@UEAAEXZ>

externdef __imp_?DeleteAllMembers@SORTED_LIST@@UEAAEXZ:PPROC
?DeleteAllMembers@SORTED_LIST@@UEAAEXZ equ <__imp_?DeleteAllMembers@SORTED_LIST@@UEAAEXZ>

externdef __imp_?DeleteChAt@BSTRING@@QEAAXKK@Z:PPROC
?DeleteChAt@BSTRING@@QEAAXKK@Z equ <__imp_?DeleteChAt@BSTRING@@QEAAXKK@Z>

externdef __imp_?DeleteChAt@WSTRING@@QEAAXKK@Z:PPROC
?DeleteChAt@WSTRING@@QEAAXKK@Z equ <__imp_?DeleteChAt@WSTRING@@QEAAXKK@Z>

externdef __imp_?DeleteDirectory@FSN_DIRECTORY@@QEAAEXZ:PPROC
?DeleteDirectory@FSN_DIRECTORY@@QEAAEXZ equ <__imp_?DeleteDirectory@FSN_DIRECTORY@@QEAAEXZ>

externdef __imp_?DisableBreakHandling@KEYBOARD@@SAEXZ:PPROC
?DisableBreakHandling@KEYBOARD@@SAEXZ equ <__imp_?DisableBreakHandling@KEYBOARD@@SAEXZ>

externdef __imp_?DisableLineMode@KEYBOARD@@QEAAEXZ:PPROC
?DisableLineMode@KEYBOARD@@QEAAEXZ equ <__imp_?DisableLineMode@KEYBOARD@@QEAAEXZ>

externdef __imp_?Display@MESSAGE@@QEAAEPEBDZZ:PPROC
?Display@MESSAGE@@QEAAEPEBDZZ equ <__imp_?Display@MESSAGE@@QEAAEPEBDZZ>

externdef __imp_?DisplayMessage@PROGRAM@@UEBAEKW4MESSAGE_TYPE@@@Z:PPROC
?DisplayMessage@PROGRAM@@UEBAEKW4MESSAGE_TYPE@@@Z equ <__imp_?DisplayMessage@PROGRAM@@UEBAEKW4MESSAGE_TYPE@@@Z>

externdef __imp_?DisplayMessage@PROGRAM@@UEBAEKW4MESSAGE_TYPE@@PEADZZ:PPROC
?DisplayMessage@PROGRAM@@UEBAEKW4MESSAGE_TYPE@@PEADZZ equ <__imp_?DisplayMessage@PROGRAM@@UEBAEKW4MESSAGE_TYPE@@PEADZZ>

externdef __imp_?DisplayMsg@MESSAGE@@QEAAEK@Z:PPROC
?DisplayMsg@MESSAGE@@QEAAEK@Z equ <__imp_?DisplayMsg@MESSAGE@@QEAAEK@Z>

externdef __imp_?DisplayMsg@MESSAGE@@QEAAEKPEBDZZ:PPROC
?DisplayMsg@MESSAGE@@QEAAEKPEBDZZ equ <__imp_?DisplayMsg@MESSAGE@@QEAAEKPEBDZZ>

externdef __imp_?DisplayMsg@MESSAGE@@QEAAEKW4MESSAGE_TYPE@@K@Z:PPROC
?DisplayMsg@MESSAGE@@QEAAEKW4MESSAGE_TYPE@@K@Z equ <__imp_?DisplayMsg@MESSAGE@@QEAAEKW4MESSAGE_TYPE@@K@Z>

externdef __imp_?DisplayMsg@MESSAGE@@QEAAEKW4MESSAGE_TYPE@@KPEBDZZ:PPROC
?DisplayMsg@MESSAGE@@QEAAEKW4MESSAGE_TYPE@@KPEBDZZ equ <__imp_?DisplayMsg@MESSAGE@@QEAAEKW4MESSAGE_TYPE@@KPEBDZZ>

externdef __imp_?DisplaySystemError@SYSTEM@@SAXKH@Z:PPROC
?DisplaySystemError@SYSTEM@@SAXKH@Z equ <__imp_?DisplaySystemError@SYSTEM@@SAXKH@Z>

externdef __imp_?DoNotRestoreConsoleMode@KEYBOARD@@UEAAXXZ:PPROC
?DoNotRestoreConsoleMode@KEYBOARD@@UEAAXXZ equ <__imp_?DoNotRestoreConsoleMode@KEYBOARD@@UEAAXXZ>

externdef __imp_?DoParsing@ARGUMENT_LEXEMIZER@@QEAAEPEAVARRAY@@@Z:PPROC
?DoParsing@ARGUMENT_LEXEMIZER@@QEAAEPEAVARRAY@@@Z equ <__imp_?DoParsing@ARGUMENT_LEXEMIZER@@QEAAEPEAVARRAY@@@Z>

externdef __imp_?DoesNodeMatch@FSN_FILTER@@QEAAEPEAVFSNODE@@@Z:PPROC
?DoesNodeMatch@FSN_FILTER@@QEAAEPEAVFSNODE@@@Z equ <__imp_?DoesNodeMatch@FSN_FILTER@@QEAAEPEAVFSNODE@@@Z>

externdef __imp_?DumpDataToLog@MESSAGE@@QEAAEPEAXK@Z:PPROC
?DumpDataToLog@MESSAGE@@QEAAEPEAXK@Z equ <__imp_?DumpDataToLog@MESSAGE@@QEAAEPEAXK@Z>

externdef __imp_?EnableBreakHandling@KEYBOARD@@SAEXZ:PPROC
?EnableBreakHandling@KEYBOARD@@SAEXZ equ <__imp_?EnableBreakHandling@KEYBOARD@@SAEXZ>

externdef __imp_?EnableLineMode@KEYBOARD@@QEAAEXZ:PPROC
?EnableLineMode@KEYBOARD@@QEAAEXZ equ <__imp_?EnableLineMode@KEYBOARD@@QEAAEXZ>

externdef __imp_?EndsWithDelimiter@PATH@@QEBAEXZ:PPROC
?EndsWithDelimiter@PATH@@QEBAEXZ equ <__imp_?EndsWithDelimiter@PATH@@QEBAEXZ>

externdef __imp_?EraseScreen@SCREEN@@QEAAEXZ:PPROC
?EraseScreen@SCREEN@@QEAAEXZ equ <__imp_?EraseScreen@SCREEN@@QEAAEXZ>

externdef __imp_?EraseScreenAndResetAttribute@SCREEN@@QEAAEXZ:PPROC
?EraseScreenAndResetAttribute@SCREEN@@QEAAEXZ equ <__imp_?EraseScreenAndResetAttribute@SCREEN@@QEAAEXZ>

externdef __imp_?ExitProgram@PROGRAM@@SAXK@Z:PPROC
?ExitProgram@PROGRAM@@SAXK@Z equ <__imp_?ExitProgram@PROGRAM@@SAXK@Z>

externdef __imp_?Fatal@PROGRAM@@UEBAXKKPEADZZ:PPROC
?Fatal@PROGRAM@@UEBAXKKPEADZZ equ <__imp_?Fatal@PROGRAM@@UEBAXKKPEADZZ>

externdef __imp_?Fatal@PROGRAM@@UEBAXXZ:PPROC
?Fatal@PROGRAM@@UEBAXXZ equ <__imp_?Fatal@PROGRAM@@UEBAXXZ>

externdef __imp_?FillAndReadByte@BYTE_STREAM@@AEAAEPEAE@Z:PPROC
?FillAndReadByte@BYTE_STREAM@@AEAAEPEAE@Z equ <__imp_?FillAndReadByte@BYTE_STREAM@@AEAAEPEAE@Z>

externdef __imp_?FindFirstFileW@@YAPEAXPEBVPATH@@PEAU_WIN32_FIND_DATAW@@@Z:PPROC
?FindFirstFileW@@YAPEAXPEBVPATH@@PEAU_WIN32_FIND_DATAW@@@Z equ <__imp_?FindFirstFileW@@YAPEAXPEBVPATH@@PEAU_WIN32_FIND_DATAW@@@Z>

externdef __imp_?Flush@KEYBOARD@@QEAAEXZ:PPROC
?Flush@KEYBOARD@@QEAAEXZ equ <__imp_?Flush@KEYBOARD@@QEAAEXZ>

externdef __imp_?Free@MEM_BLOCK_MGR@@QEAAEPEAX@Z:PPROC
?Free@MEM_BLOCK_MGR@@QEAAEPEAX@Z equ <__imp_?Free@MEM_BLOCK_MGR@@QEAAEPEAX@Z>

externdef __imp_?FreeLibraryHandle@SYSTEM@@SAXPEAX@Z:PPROC
?FreeLibraryHandle@SYSTEM@@SAXPEAX@Z equ <__imp_?FreeLibraryHandle@SYSTEM@@SAXPEAX@Z>

externdef __imp_?GetClassDescriptor@OBJECT@@QEBAPEBVCLASS_DESCRIPTOR@@XZ:PPROC
?GetClassDescriptor@OBJECT@@QEBAPEBVCLASS_DESCRIPTOR@@XZ equ <__imp_?GetClassDescriptor@OBJECT@@QEBAPEBVCLASS_DESCRIPTOR@@XZ>

externdef __imp_?GetFileSecurityBackup@SYSTEM@@SAEPEBVPATH@@KPEAU_SECURITY_ATTRIBUTES@@PEAK@Z:PPROC
?GetFileSecurityBackup@SYSTEM@@SAEPEBVPATH@@KPEAU_SECURITY_ATTRIBUTES@@PEAK@Z equ <__imp_?GetFileSecurityBackup@SYSTEM@@SAEPEBVPATH@@KPEAU_SECURITY_ATTRIBUTES@@PEAK@Z>

externdef __imp_?GetLexeme@ARGUMENT@@QEAAPEAVWSTRING@@XZ:PPROC
?GetLexeme@ARGUMENT@@QEAAPEAVWSTRING@@XZ equ <__imp_?GetLexeme@ARGUMENT@@QEAAPEAVWSTRING@@XZ>

externdef __imp_?GetLexemeAt@ARGUMENT_LEXEMIZER@@QEAAPEAVWSTRING@@K@Z:PPROC
?GetLexemeAt@ARGUMENT_LEXEMIZER@@QEAAPEAVWSTRING@@K@Z equ <__imp_?GetLexemeAt@ARGUMENT_LEXEMIZER@@QEAAPEAVWSTRING@@K@Z>

externdef __imp_?GetNext@FSN_DIRECTORY@@QEAAPEAVFSNODE@@PEAPEAXPEAK@Z:PPROC
?GetNext@FSN_DIRECTORY@@QEAAPEAVFSNODE@@PEAPEAXPEAK@Z equ <__imp_?GetNext@FSN_DIRECTORY@@QEAAPEAVFSNODE@@PEAPEAXPEAK@Z>

externdef __imp_?GetPFlagBreak@KEYBOARD@@QEBAQEAHXZ:PPROC
?GetPFlagBreak@KEYBOARD@@QEBAQEAHXZ equ <__imp_?GetPFlagBreak@KEYBOARD@@QEBAQEAHXZ>

externdef __imp_?GetPattern@ARGUMENT@@QEAAPEAVWSTRING@@XZ:PPROC
?GetPattern@ARGUMENT@@QEAAPEAVWSTRING@@XZ equ <__imp_?GetPattern@ARGUMENT@@QEAAPEAVWSTRING@@XZ>

externdef __imp_?GetStandardError@PROGRAM@@UEAAPEAVSTREAM@@XZ:PPROC
?GetStandardError@PROGRAM@@UEAAPEAVSTREAM@@XZ equ <__imp_?GetStandardError@PROGRAM@@UEAAPEAVSTREAM@@XZ>

externdef __imp_?GetStandardInput@PROGRAM@@UEAAPEAVSTREAM@@XZ:PPROC
?GetStandardInput@PROGRAM@@UEAAPEAVSTREAM@@XZ equ <__imp_?GetStandardInput@PROGRAM@@UEAAPEAVSTREAM@@XZ>

externdef __imp_?GetStandardOutput@PROGRAM@@UEAAPEAVSTREAM@@XZ:PPROC
?GetStandardOutput@PROGRAM@@UEAAPEAVSTREAM@@XZ equ <__imp_?GetStandardOutput@PROGRAM@@UEAAPEAVSTREAM@@XZ>

externdef __imp_?GetWSTR@WSTRING@@QEBAPEBGXZ:PPROC
?GetWSTR@WSTRING@@QEBAPEBGXZ equ <__imp_?GetWSTR@WSTRING@@QEBAPEBGXZ>

externdef __imp_?Get_Standard_Error_Stream@@YAPEAVSTREAM@@XZ:PPROC
?Get_Standard_Error_Stream@@YAPEAVSTREAM@@XZ equ <__imp_?Get_Standard_Error_Stream@@YAPEAVSTREAM@@XZ>

externdef __imp_?Get_Standard_Input_Stream@@YAPEAVSTREAM@@XZ:PPROC
?Get_Standard_Input_Stream@@YAPEAVSTREAM@@XZ equ <__imp_?Get_Standard_Input_Stream@@YAPEAVSTREAM@@XZ>

externdef __imp_?Get_Standard_Output_Stream@@YAPEAVSTREAM@@XZ:PPROC
?Get_Standard_Output_Stream@@YAPEAVSTREAM@@XZ equ <__imp_?Get_Standard_Output_Stream@@YAPEAVSTREAM@@XZ>

externdef __imp_?GotABreak@KEYBOARD@@SAEXZ:PPROC
?GotABreak@KEYBOARD@@SAEXZ equ <__imp_?GotABreak@KEYBOARD@@SAEXZ>

externdef __imp_?HasWildCard@PATH@@QEBAEXZ:PPROC
?HasWildCard@PATH@@QEBAEXZ equ <__imp_?HasWildCard@PATH@@QEBAEXZ>

externdef __imp_?Initialize@ARGUMENT_LEXEMIZER@@QEAAEPEAVARRAY@@@Z:PPROC
?Initialize@ARGUMENT_LEXEMIZER@@QEAAEPEAVARRAY@@@Z equ <__imp_?Initialize@ARGUMENT_LEXEMIZER@@QEAAEPEAVARRAY@@@Z>

externdef __imp_?Initialize@ARRAY@@QEAAEKK@Z:PPROC
?Initialize@ARRAY@@QEAAEKK@Z equ <__imp_?Initialize@ARRAY@@QEAAEKK@Z>

externdef __imp_?Initialize@BITVECTOR@@QEAAEKW4BIT@@PEAK@Z:PPROC
?Initialize@BITVECTOR@@QEAAEKW4BIT@@PEAK@Z equ <__imp_?Initialize@BITVECTOR@@QEAAEKW4BIT@@PEAK@Z>

externdef __imp_?Initialize@BSTRING@@QEAAEPEBDK@Z:PPROC
?Initialize@BSTRING@@QEAAEPEBDK@Z equ <__imp_?Initialize@BSTRING@@QEAAEPEBDK@Z>

externdef __imp_?Initialize@BSTRING@@QEAAEXZ:PPROC
?Initialize@BSTRING@@QEAAEXZ equ <__imp_?Initialize@BSTRING@@QEAAEXZ>

externdef __imp_?Initialize@BYTE_STREAM@@QEAAEPEAVSTREAM@@K@Z:PPROC
?Initialize@BYTE_STREAM@@QEAAEPEAVSTREAM@@K@Z equ <__imp_?Initialize@BYTE_STREAM@@QEAAEPEAVSTREAM@@K@Z>

externdef __imp_?Initialize@CHKDSK_MESSAGE@@QEAAEPEAVSTREAM@@00@Z:PPROC
?Initialize@CHKDSK_MESSAGE@@QEAAEPEAVSTREAM@@00@Z equ <__imp_?Initialize@CHKDSK_MESSAGE@@QEAAEPEAVSTREAM@@00@Z>

externdef __imp_?Initialize@CLASS_DESCRIPTOR@@QEAAEXZ:PPROC
?Initialize@CLASS_DESCRIPTOR@@QEAAEXZ equ <__imp_?Initialize@CLASS_DESCRIPTOR@@QEAAEXZ>

externdef __imp_?Initialize@COMM_DEVICE@@QEAAEPEBVPATH@@PEAE@Z:PPROC
?Initialize@COMM_DEVICE@@QEAAEPEBVPATH@@PEAE@Z equ <__imp_?Initialize@COMM_DEVICE@@QEAAEPEBVPATH@@PEAE@Z>

externdef __imp_?Initialize@CONT_MEM@@QEAAEPEAXK@Z:PPROC
?Initialize@CONT_MEM@@QEAAEPEAXK@Z equ <__imp_?Initialize@CONT_MEM@@QEAAEPEAXK@Z>

externdef __imp_?Initialize@FLAG_ARGUMENT@@QEAAEPEAD@Z:PPROC
?Initialize@FLAG_ARGUMENT@@QEAAEPEAD@Z equ <__imp_?Initialize@FLAG_ARGUMENT@@QEAAEPEAD@Z>

externdef __imp_?Initialize@FLAG_ARGUMENT@@QEAAEPEAVWSTRING@@@Z:PPROC
?Initialize@FLAG_ARGUMENT@@QEAAEPEAVWSTRING@@@Z equ <__imp_?Initialize@FLAG_ARGUMENT@@QEAAEPEAVWSTRING@@@Z>

externdef __imp_?Initialize@FSN_FILTER@@QEAAEXZ:PPROC
?Initialize@FSN_FILTER@@QEAAEXZ equ <__imp_?Initialize@FSN_FILTER@@QEAAEXZ>

externdef __imp_?Initialize@FSTRING@@QEAAPEAVWSTRING@@PEAGK@Z:PPROC
?Initialize@FSTRING@@QEAAPEAVWSTRING@@PEAGK@Z equ <__imp_?Initialize@FSTRING@@QEAAPEAVWSTRING@@PEAGK@Z>

externdef __imp_?Initialize@HMEM@@QEAAEXZ:PPROC
?Initialize@HMEM@@QEAAEXZ equ <__imp_?Initialize@HMEM@@QEAAEXZ>

externdef __imp_?Initialize@KEYBOARD@@QEAAEEE@Z:PPROC
?Initialize@KEYBOARD@@QEAAEEE@Z equ <__imp_?Initialize@KEYBOARD@@QEAAEEE@Z>

externdef __imp_?Initialize@LIST@@QEAAEXZ:PPROC
?Initialize@LIST@@QEAAEXZ equ <__imp_?Initialize@LIST@@QEAAEXZ>

externdef __imp_?Initialize@LONG_ARGUMENT@@QEAAEPEAD@Z:PPROC
?Initialize@LONG_ARGUMENT@@QEAAEPEAD@Z equ <__imp_?Initialize@LONG_ARGUMENT@@QEAAEPEAD@Z>

externdef __imp_?Initialize@MEM_ALLOCATOR@@QEAAE_KK@Z:PPROC
?Initialize@MEM_ALLOCATOR@@QEAAE_KK@Z equ <__imp_?Initialize@MEM_ALLOCATOR@@QEAAE_KK@Z>

externdef __imp_?Initialize@MEM_BLOCK_MGR@@QEAAEKK@Z:PPROC
?Initialize@MEM_BLOCK_MGR@@QEAAEKK@Z equ <__imp_?Initialize@MEM_BLOCK_MGR@@QEAAEKK@Z>

externdef __imp_?Initialize@MESSAGE@@QEAAEXZ:PPROC
?Initialize@MESSAGE@@QEAAEXZ equ <__imp_?Initialize@MESSAGE@@QEAAEXZ>

externdef __imp_?Initialize@MULTIPLE_PATH_ARGUMENT@@QEAAEPEADEE@Z:PPROC
?Initialize@MULTIPLE_PATH_ARGUMENT@@QEAAEPEADEE@Z equ <__imp_?Initialize@MULTIPLE_PATH_ARGUMENT@@QEAAEPEADEE@Z>

externdef __imp_?Initialize@PATH@@QEAAEPEBGE@Z:PPROC
?Initialize@PATH@@QEAAEPEBGE@Z equ <__imp_?Initialize@PATH@@QEAAEPEBGE@Z>

externdef __imp_?Initialize@PATH@@QEAAEPEBV1@E@Z:PPROC
?Initialize@PATH@@QEAAEPEBV1@E@Z equ <__imp_?Initialize@PATH@@QEAAEPEBV1@E@Z>

externdef __imp_?Initialize@PATH@@QEAAEPEBVWSTRING@@E@Z:PPROC
?Initialize@PATH@@QEAAEPEBVWSTRING@@E@Z equ <__imp_?Initialize@PATH@@QEAAEPEBVWSTRING@@E@Z>

externdef __imp_?Initialize@PATH_ARGUMENT@@QEAAEPEADE@Z:PPROC
?Initialize@PATH_ARGUMENT@@QEAAEPEADE@Z equ <__imp_?Initialize@PATH_ARGUMENT@@QEAAEPEADE@Z>

externdef __imp_?Initialize@PRINT_STREAM@@QEAAEPEBVPATH@@@Z:PPROC
?Initialize@PRINT_STREAM@@QEAAEPEBVPATH@@@Z equ <__imp_?Initialize@PRINT_STREAM@@QEAAEPEBVPATH@@@Z>

externdef __imp_?Initialize@PROGRAM@@QEAAEKKK@Z:PPROC
?Initialize@PROGRAM@@QEAAEKKK@Z equ <__imp_?Initialize@PROGRAM@@QEAAEKKK@Z>

externdef __imp_?Initialize@REST_OF_LINE_ARGUMENT@@QEAAEXZ:PPROC
?Initialize@REST_OF_LINE_ARGUMENT@@QEAAEXZ equ <__imp_?Initialize@REST_OF_LINE_ARGUMENT@@QEAAEXZ>

externdef __imp_?Initialize@SCREEN@@QEAAEXZ:PPROC
?Initialize@SCREEN@@QEAAEXZ equ <__imp_?Initialize@SCREEN@@QEAAEXZ>

externdef __imp_?Initialize@SORTED_LIST@@QEAAEE@Z:PPROC
?Initialize@SORTED_LIST@@QEAAEE@Z equ <__imp_?Initialize@SORTED_LIST@@QEAAEE@Z>

externdef __imp_?Initialize@STREAM_MESSAGE@@QEAAEPEAVSTREAM@@00@Z:PPROC
?Initialize@STREAM_MESSAGE@@QEAAEPEAVSTREAM@@00@Z equ <__imp_?Initialize@STREAM_MESSAGE@@QEAAEPEAVSTREAM@@00@Z>

externdef __imp_?Initialize@STRING_ARGUMENT@@QEAAEPEAD@Z:PPROC
?Initialize@STRING_ARGUMENT@@QEAAEPEAD@Z equ <__imp_?Initialize@STRING_ARGUMENT@@QEAAEPEAD@Z>

externdef __imp_?Initialize@STRING_ARRAY@@QEAAEKKK@Z:PPROC
?Initialize@STRING_ARRAY@@QEAAEKKK@Z equ <__imp_?Initialize@STRING_ARRAY@@QEAAEKKK@Z>

externdef __imp_?Initialize@TIMEINFO@@QEAAEPEAU_FILETIME@@@Z:PPROC
?Initialize@TIMEINFO@@QEAAEPEAU_FILETIME@@@Z equ <__imp_?Initialize@TIMEINFO@@QEAAEPEAU_FILETIME@@@Z>

externdef __imp_?Initialize@TIMEINFO@@QEAAXPEBV1@@Z:PPROC
?Initialize@TIMEINFO@@QEAAXPEBV1@@Z equ <__imp_?Initialize@TIMEINFO@@QEAAXPEBV1@@Z>

externdef __imp_?Initialize@TIMEINFO_ARGUMENT@@QEAAEPEAD@Z:PPROC
?Initialize@TIMEINFO_ARGUMENT@@QEAAEPEAD@Z equ <__imp_?Initialize@TIMEINFO_ARGUMENT@@QEAAEPEAD@Z>

externdef __imp_?Initialize@WSTRING@@QEAAEJ@Z:PPROC
?Initialize@WSTRING@@QEAAEJ@Z equ <__imp_?Initialize@WSTRING@@QEAAEJ@Z>

externdef __imp_?Initialize@WSTRING@@QEAAEPEBDK@Z:PPROC
?Initialize@WSTRING@@QEAAEPEBDK@Z equ <__imp_?Initialize@WSTRING@@QEAAEPEBDK@Z>

externdef __imp_?Initialize@WSTRING@@QEAAEPEBGK@Z:PPROC
?Initialize@WSTRING@@QEAAEPEBGK@Z equ <__imp_?Initialize@WSTRING@@QEAAEPEBGK@Z>

externdef __imp_?Initialize@WSTRING@@QEAAEPEBV1@KK@Z:PPROC
?Initialize@WSTRING@@QEAAEPEBV1@KK@Z equ <__imp_?Initialize@WSTRING@@QEAAEPEBV1@KK@Z>

externdef __imp_?Initialize@WSTRING@@QEAAEXZ:PPROC
?Initialize@WSTRING@@QEAAEXZ equ <__imp_?Initialize@WSTRING@@QEAAEXZ>

externdef __imp_?Insert@LIST@@QEAAEPEAVOBJECT@@PEAVITERATOR@@@Z:PPROC
?Insert@LIST@@QEAAEPEAVOBJECT@@PEAVITERATOR@@@Z equ <__imp_?Insert@LIST@@QEAAEPEAVOBJECT@@PEAVITERATOR@@@Z>

externdef __imp_?InsertString@WSTRING@@QEAAEKPEBV1@KK@Z:PPROC
?InsertString@WSTRING@@QEAAEKPEBV1@KK@Z equ <__imp_?InsertString@WSTRING@@QEAAEKPEBV1@KK@Z>

externdef __imp_?IsCorrectVersion@SYSTEM@@SAEXZ:PPROC
?IsCorrectVersion@SYSTEM@@SAEXZ equ <__imp_?IsCorrectVersion@SYSTEM@@SAEXZ>

externdef __imp_?IsDrive@PATH@@QEBAEXZ:PPROC
?IsDrive@PATH@@QEBAEXZ equ <__imp_?IsDrive@PATH@@QEBAEXZ>

externdef __imp_?IsEmpty@FSN_DIRECTORY@@QEBAEXZ:PPROC
?IsEmpty@FSN_DIRECTORY@@QEBAEXZ equ <__imp_?IsEmpty@FSN_DIRECTORY@@QEBAEXZ>

externdef __imp_?IsGuidVolName@PATH@@QEAAEXZ:PPROC
?IsGuidVolName@PATH@@QEAAEXZ equ <__imp_?IsGuidVolName@PATH@@QEAAEXZ>

externdef __imp_?IsInAutoChk@MESSAGE@@UEAAEXZ:PPROC
?IsInAutoChk@MESSAGE@@UEAAEXZ equ <__imp_?IsInAutoChk@MESSAGE@@UEAAEXZ>

externdef __imp_?IsInSetup@MESSAGE@@UEAAEXZ:PPROC
?IsInSetup@MESSAGE@@UEAAEXZ equ <__imp_?IsInSetup@MESSAGE@@UEAAEXZ>

externdef __imp_?IsKeyAvailable@KEYBOARD@@QEBAEPEAE@Z:PPROC
?IsKeyAvailable@KEYBOARD@@QEBAEPEAE@Z equ <__imp_?IsKeyAvailable@KEYBOARD@@QEBAEPEAE@Z>

externdef __imp_?IsKeyPressed@MESSAGE@@UEAAEKK@Z:PPROC
?IsKeyPressed@MESSAGE@@UEAAEKK@Z equ <__imp_?IsKeyPressed@MESSAGE@@UEAAEKK@Z>

externdef __imp_?IsLoggingEnabled@MESSAGE@@QEAAEXZ:PPROC
?IsLoggingEnabled@MESSAGE@@QEAAEXZ equ <__imp_?IsLoggingEnabled@MESSAGE@@QEAAEXZ>

externdef __imp_?IsSameClass@OBJECT@@QEBAEPEBV1@@Z:PPROC
?IsSameClass@OBJECT@@QEBAEPEBV1@@Z equ <__imp_?IsSameClass@OBJECT@@QEBAEPEBV1@@Z>

externdef __imp_?IsSameObject@OBJECT@@QEBAEPEBV1@@Z:PPROC
?IsSameObject@OBJECT@@QEBAEPEBV1@@Z equ <__imp_?IsSameObject@OBJECT@@QEBAEPEBV1@@Z>

externdef __imp_?IsSuppressedMessage@MESSAGE@@UEAAEXZ:PPROC
?IsSuppressedMessage@MESSAGE@@UEAAEXZ equ <__imp_?IsSuppressedMessage@MESSAGE@@UEAAEXZ>

externdef __imp_?IsValueSet@ARGUMENT@@QEAAEXZ:PPROC
?IsValueSet@ARGUMENT@@QEAAEXZ equ <__imp_?IsValueSet@ARGUMENT@@QEAAEXZ>

externdef __imp_?IsYesResponse@CHKDSK_MESSAGE@@UEAAEE@Z:PPROC
?IsYesResponse@CHKDSK_MESSAGE@@UEAAEE@Z equ <__imp_?IsYesResponse@CHKDSK_MESSAGE@@UEAAEE@Z>

externdef __imp_?IsYesResponse@MESSAGE@@UEAAEE@Z:PPROC
?IsYesResponse@MESSAGE@@UEAAEE@Z equ <__imp_?IsYesResponse@MESSAGE@@UEAAEE@Z>

externdef __imp_?IsYesResponse@STREAM_MESSAGE@@UEAAEE@Z:PPROC
?IsYesResponse@STREAM_MESSAGE@@UEAAEE@Z equ <__imp_?IsYesResponse@STREAM_MESSAGE@@UEAAEE@Z>

externdef __imp_?Lock@MESSAGE@@QEAAXXZ:PPROC
?Lock@MESSAGE@@QEAAXXZ equ <__imp_?Lock@MESSAGE@@QEAAXXZ>

externdef __imp_?Log@MESSAGE@@QEAAEPEBDZZ:PPROC
?Log@MESSAGE@@QEAAEPEBDZZ equ <__imp_?Log@MESSAGE@@QEAAEPEBDZZ>

externdef __imp_?LogMessage@MESSAGE@@QEAAEPEBVWSTRING@@@Z:PPROC
?LogMessage@MESSAGE@@QEAAEPEBVWSTRING@@@Z equ <__imp_?LogMessage@MESSAGE@@QEAAEPEBVWSTRING@@@Z>

externdef __imp_?LogMsg@MESSAGE@@QEAAEK@Z:PPROC
?LogMsg@MESSAGE@@QEAAEK@Z equ <__imp_?LogMsg@MESSAGE@@QEAAEK@Z>

externdef __imp_?LogMsg@MESSAGE@@QEAAEKPEBDZZ:PPROC
?LogMsg@MESSAGE@@QEAAEKPEBDZZ equ <__imp_?LogMsg@MESSAGE@@QEAAEKPEBDZZ>

externdef __imp_?MakeDirectory@SYSTEM@@SAPEAVFSN_DIRECTORY@@PEBVPATH@@0PEAW4_COPY_ERROR@@P6AKT_LARGE_INTEGER@@222KKPEAX33@Z3PEAHK@Z:PPROC
?MakeDirectory@SYSTEM@@SAPEAVFSN_DIRECTORY@@PEBVPATH@@0PEAW4_COPY_ERROR@@P6AKT_LARGE_INTEGER@@222KKPEAX33@Z3PEAHK@Z equ <__imp_?MakeDirectory@SYSTEM@@SAPEAVFSN_DIRECTORY@@PEBVPATH@@0PEAW4_COPY_ERROR@@P6AKT_LARGE_INTEGER@@222KKPEAX33@Z3PEAHK@Z>

externdef __imp_?MakeFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVPATH@@@Z:PPROC
?MakeFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVPATH@@@Z equ <__imp_?MakeFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVPATH@@@Z>

externdef __imp_?MakeTemporaryFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVWSTRING@@PEBVPATH@@@Z:PPROC
?MakeTemporaryFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVWSTRING@@PEBVPATH@@@Z equ <__imp_?MakeTemporaryFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVWSTRING@@PEBVPATH@@@Z>

externdef __imp_?ModifyName@PATH@@QEAAEPEBVWSTRING@@@Z:PPROC
?ModifyName@PATH@@QEAAEPEBVWSTRING@@@Z equ <__imp_?ModifyName@PATH@@QEAAEPEBVWSTRING@@@Z>

externdef __imp_?MoveCursorTo@SCREEN@@QEAAEGG@Z:PPROC
?MoveCursorTo@SCREEN@@QEAAEGG@Z equ <__imp_?MoveCursorTo@SCREEN@@QEAAEGG@Z>

externdef __imp_?NewBuf@BDSTRING@@UEAAEK@Z:PPROC
?NewBuf@BDSTRING@@UEAAEK@Z equ <__imp_?NewBuf@BDSTRING@@UEAAEK@Z>

externdef __imp_?NewBuf@DSTRING@@UEAAEK@Z:PPROC
?NewBuf@DSTRING@@UEAAEK@Z equ <__imp_?NewBuf@DSTRING@@UEAAEK@Z>

externdef __imp_?NewBuf@FSTRING@@UEAAEK@Z:PPROC
?NewBuf@FSTRING@@UEAAEK@Z equ <__imp_?NewBuf@FSTRING@@UEAAEK@Z>

externdef __imp_?NextChar@BSTRING@@QEAAKK@Z:PPROC
?NextChar@BSTRING@@QEAAKK@Z equ <__imp_?NextChar@BSTRING@@QEAAKK@Z>

externdef __imp_?PrepareToParse@ARGUMENT_LEXEMIZER@@QEAAEPEAVWSTRING@@@Z:PPROC
?PrepareToParse@ARGUMENT_LEXEMIZER@@QEAAEPEAVWSTRING@@@Z equ <__imp_?PrepareToParse@ARGUMENT_LEXEMIZER@@QEAAEPEAVWSTRING@@@Z>

externdef __imp_?Put@ARRAY@@UEAAEPEAVOBJECT@@@Z:PPROC
?Put@ARRAY@@UEAAEPEAVOBJECT@@@Z equ <__imp_?Put@ARRAY@@UEAAEPEAVOBJECT@@@Z>

externdef __imp_?Put@LIST@@UEAAEPEAVOBJECT@@@Z:PPROC
?Put@LIST@@UEAAEPEAVOBJECT@@@Z equ <__imp_?Put@LIST@@UEAAEPEAVOBJECT@@@Z>

externdef __imp_?Put@SORTED_LIST@@UEAAEPEAVOBJECT@@@Z:PPROC
?Put@SORTED_LIST@@UEAAEPEAVOBJECT@@@Z equ <__imp_?Put@SORTED_LIST@@UEAAEPEAVOBJECT@@@Z>

externdef __imp_?PutMultipleSwitch@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z:PPROC
?PutMultipleSwitch@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z equ <__imp_?PutMultipleSwitch@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z>

externdef __imp_?PutMultipleSwitch@ARGUMENT_LEXEMIZER@@QEAAXPEBVWSTRING@@@Z:PPROC
?PutMultipleSwitch@ARGUMENT_LEXEMIZER@@QEAAXPEBVWSTRING@@@Z equ <__imp_?PutMultipleSwitch@ARGUMENT_LEXEMIZER@@QEAAXPEBVWSTRING@@@Z>

externdef __imp_?PutSeparators@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z:PPROC
?PutSeparators@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z equ <__imp_?PutSeparators@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z>

externdef __imp_?PutString@BSTRING@@IEAAXPEADK@Z:PPROC
?PutString@BSTRING@@IEAAXPEADK@Z equ <__imp_?PutString@BSTRING@@IEAAXPEADK@Z>

externdef __imp_?PutString@WSTRING@@IEAAXPEAG@Z:PPROC
?PutString@WSTRING@@IEAAXPEAG@Z equ <__imp_?PutString@WSTRING@@IEAAXPEAG@Z>

externdef __imp_?PutString@WSTRING@@IEAAXPEAGK@Z:PPROC
?PutString@WSTRING@@IEAAXPEAGK@Z equ <__imp_?PutString@WSTRING@@IEAAXPEAGK@Z>

externdef __imp_?PutSwitches@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z:PPROC
?PutSwitches@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z equ <__imp_?PutSwitches@ARGUMENT_LEXEMIZER@@QEAAXPEBD@Z>

externdef __imp_?PutSwitches@ARGUMENT_LEXEMIZER@@QEAAXPEBVWSTRING@@@Z:PPROC
?PutSwitches@ARGUMENT_LEXEMIZER@@QEAAXPEBVWSTRING@@@Z equ <__imp_?PutSwitches@ARGUMENT_LEXEMIZER@@QEAAXPEBVWSTRING@@@Z>

externdef __imp_?QueryByteCount@WSTRING@@QEBAKXZ:PPROC
?QueryByteCount@WSTRING@@QEBAKXZ equ <__imp_?QueryByteCount@WSTRING@@QEBAKXZ>

externdef __imp_?QueryChAt@WSTRING@@QEBAGK@Z:PPROC
?QueryChAt@WSTRING@@QEBAGK@Z equ <__imp_?QueryChAt@WSTRING@@QEBAGK@Z>

externdef __imp_?QueryChCount@BSTRING@@QEBAKXZ:PPROC
?QueryChCount@BSTRING@@QEBAKXZ equ <__imp_?QueryChCount@BSTRING@@QEBAKXZ>

externdef __imp_?QueryChCount@WSTRING@@QEBAKXZ:PPROC
?QueryChCount@WSTRING@@QEBAKXZ equ <__imp_?QueryChCount@WSTRING@@QEBAKXZ>

externdef __imp_?QueryClassId@OBJECT@@QEBA_KXZ:PPROC
?QueryClassId@OBJECT@@QEBA_KXZ equ <__imp_?QueryClassId@OBJECT@@QEBA_KXZ>

externdef __imp_?QueryCodePage@SCREEN@@QEAAKXZ:PPROC
?QueryCodePage@SCREEN@@QEAAKXZ equ <__imp_?QueryCodePage@SCREEN@@QEAAKXZ>

externdef __imp_?QueryComponentArray@PATH@@QEBAPEAVARRAY@@PEAV2@@Z:PPROC
?QueryComponentArray@PATH@@QEBAPEAVARRAY@@PEAV2@@Z equ <__imp_?QueryComponentArray@PATH@@QEBAPEAVARRAY@@PEAV2@@Z>

externdef __imp_?QueryCurrentDosDriveName@SYSTEM@@SAEPEAVWSTRING@@@Z:PPROC
?QueryCurrentDosDriveName@SYSTEM@@SAEPEAVWSTRING@@@Z equ <__imp_?QueryCurrentDosDriveName@SYSTEM@@SAEPEAVWSTRING@@@Z>

externdef __imp_?QueryDate@TIMEINFO@@QEBAEPEAVWSTRING@@@Z:PPROC
?QueryDate@TIMEINFO@@QEBAEPEAVWSTRING@@@Z equ <__imp_?QueryDate@TIMEINFO@@QEBAEPEAVWSTRING@@@Z>

externdef __imp_?QueryDirectory@SYSTEM@@SAPEAVFSN_DIRECTORY@@PEBVPATH@@E@Z:PPROC
?QueryDirectory@SYSTEM@@SAPEAVFSN_DIRECTORY@@PEBVPATH@@E@Z equ <__imp_?QueryDirectory@SYSTEM@@SAPEAVFSN_DIRECTORY@@PEBVPATH@@E@Z>

externdef __imp_?QueryDriveType@SYSTEM@@SA?AW4DRIVE_TYPE@@PEBVWSTRING@@@Z:PPROC
?QueryDriveType@SYSTEM@@SA?AW4DRIVE_TYPE@@PEBVWSTRING@@@Z equ <__imp_?QueryDriveType@SYSTEM@@SA?AW4DRIVE_TYPE@@PEBVWSTRING@@@Z>

externdef __imp_?QueryEnvironmentVariable@SYSTEM@@SAPEAVWSTRING@@PEBV2@@Z:PPROC
?QueryEnvironmentVariable@SYSTEM@@SAPEAVWSTRING@@PEBV2@@Z equ <__imp_?QueryEnvironmentVariable@SYSTEM@@SAPEAVWSTRING@@PEBV2@@Z>

externdef __imp_?QueryFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVPATH@@EPEAE@Z:PPROC
?QueryFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVPATH@@EPEAE@Z equ <__imp_?QueryFile@SYSTEM@@SAPEAVFSN_FILE@@PEBVPATH@@EPEAE@Z>

externdef __imp_?QueryFileType@SYSTEM@@SA?AW4FILE_TYPE@@PEBVWSTRING@@@Z:PPROC
?QueryFileType@SYSTEM@@SA?AW4FILE_TYPE@@PEBVWSTRING@@@Z equ <__imp_?QueryFileType@SYSTEM@@SA?AW4FILE_TYPE@@PEBVWSTRING@@@Z>

externdef __imp_?QueryFsnodeArray@FSN_DIRECTORY@@QEBAPEAVARRAY@@PEAVFSN_FILTER@@@Z:PPROC
?QueryFsnodeArray@FSN_DIRECTORY@@QEBAPEAVARRAY@@PEAVFSN_FILTER@@@Z equ <__imp_?QueryFsnodeArray@FSN_DIRECTORY@@QEBAPEAVARRAY@@PEAVFSN_FILTER@@@Z>

externdef __imp_?QueryFullPath@PATH@@QEBAPEAV1@XZ:PPROC
?QueryFullPath@PATH@@QEBAPEAV1@XZ equ <__imp_?QueryFullPath@PATH@@QEBAPEAV1@XZ>

externdef __imp_?QueryFullPathString@PATH@@QEBAPEAVWSTRING@@XZ:PPROC
?QueryFullPathString@PATH@@QEBAPEAVWSTRING@@XZ equ <__imp_?QueryFullPathString@PATH@@QEBAPEAVWSTRING@@XZ>

externdef __imp_?QueryGuidString@PATH@@QEAAPEAVWSTRING@@PEAV2@PEAE0@Z:PPROC
?QueryGuidString@PATH@@QEAAPEAVWSTRING@@PEAV2@PEAE0@Z equ <__imp_?QueryGuidString@PATH@@QEAAPEAVWSTRING@@PEAV2@PEAE0@Z>

externdef __imp_?QueryInvalidArgument@ARGUMENT_LEXEMIZER@@QEAAPEAVWSTRING@@XZ:PPROC
?QueryInvalidArgument@ARGUMENT_LEXEMIZER@@QEAAPEAVWSTRING@@XZ equ <__imp_?QueryInvalidArgument@ARGUMENT_LEXEMIZER@@QEAAPEAVWSTRING@@XZ>

externdef __imp_?QueryIterator@ARRAY@@UEBAPEAVITERATOR@@XZ:PPROC
?QueryIterator@ARRAY@@UEBAPEAVITERATOR@@XZ equ <__imp_?QueryIterator@ARRAY@@UEBAPEAVITERATOR@@XZ>

externdef __imp_?QueryIterator@LIST@@UEBAPEAVITERATOR@@XZ:PPROC
?QueryIterator@LIST@@UEBAPEAVITERATOR@@XZ equ <__imp_?QueryIterator@LIST@@UEBAPEAVITERATOR@@XZ>

externdef __imp_?QueryIterator@SORTED_LIST@@UEBAPEAVITERATOR@@XZ:PPROC
?QueryIterator@SORTED_LIST@@UEBAPEAVITERATOR@@XZ equ <__imp_?QueryIterator@SORTED_LIST@@UEBAPEAVITERATOR@@XZ>

externdef __imp_?QueryLibraryEntryPoint@SYSTEM@@SAP6A_JXZPEBVWSTRING@@0PEAPEAX@Z:PPROC
?QueryLibraryEntryPoint@SYSTEM@@SAP6A_JXZPEBVWSTRING@@0PEAPEAX@Z equ <__imp_?QueryLibraryEntryPoint@SYSTEM@@SAP6A_JXZPEBVWSTRING@@0PEAPEAX@Z>

externdef __imp_?QueryLocalTimeFromUTime@SYSTEM@@SAEPEBVTIMEINFO@@PEAV2@@Z:PPROC
?QueryLocalTimeFromUTime@SYSTEM@@SAEPEBVTIMEINFO@@PEAV2@@Z equ <__imp_?QueryLocalTimeFromUTime@SYSTEM@@SAEPEBVTIMEINFO@@PEAV2@@Z>

externdef __imp_?QueryMemberCount@LIST@@UEBAKXZ:PPROC
?QueryMemberCount@LIST@@UEBAKXZ equ <__imp_?QueryMemberCount@LIST@@UEBAKXZ>

externdef __imp_?QueryMemberCount@SORTED_LIST@@UEBAKXZ:PPROC
?QueryMemberCount@SORTED_LIST@@UEBAKXZ equ <__imp_?QueryMemberCount@SORTED_LIST@@UEBAKXZ>

externdef __imp_?QueryMountPointPath@PATH@@QEAAPEAV1@XZ:PPROC
?QueryMountPointPath@PATH@@QEAAPEAV1@XZ equ <__imp_?QueryMountPointPath@PATH@@QEAAPEAV1@XZ>

externdef __imp_?QueryNextLoggedMessage@MESSAGE@@QEAAEPEAVFSTRING@@@Z:PPROC
?QueryNextLoggedMessage@MESSAGE@@QEAAEPEAVFSTRING@@@Z equ <__imp_?QueryNextLoggedMessage@MESSAGE@@QEAAEPEAVFSTRING@@@Z>

externdef __imp_?QueryNumber@WSTRING@@QEBAEPEAJKK@Z:PPROC
?QueryNumber@WSTRING@@QEBAEPEAJKK@Z equ <__imp_?QueryNumber@WSTRING@@QEBAEPEAJKK@Z>

externdef __imp_?QueryPackedLog@MESSAGE@@QEAAEPEAVHMEM@@PEAK@Z:PPROC
?QueryPackedLog@MESSAGE@@QEAAEPEAVHMEM@@PEAK@Z equ <__imp_?QueryPackedLog@MESSAGE@@QEAAEPEAVHMEM@@PEAK@Z>

externdef __imp_?QueryPath@PATH@@QEBAPEAV1@XZ:PPROC
?QueryPath@PATH@@QEBAPEAV1@XZ equ <__imp_?QueryPath@PATH@@QEBAPEAV1@XZ>

externdef __imp_?QueryResourceString@BASE_SYSTEM@@SAEPEAVWSTRING@@KPEBDZZ:PPROC
?QueryResourceString@BASE_SYSTEM@@SAEPEAVWSTRING@@KPEBDZZ equ <__imp_?QueryResourceString@BASE_SYSTEM@@SAEPEAVWSTRING@@KPEBDZZ>

externdef __imp_?QueryResourceStringV@BASE_SYSTEM@@SAEPEAVWSTRING@@KPEBDPEAD@Z:PPROC
?QueryResourceStringV@BASE_SYSTEM@@SAEPEAVWSTRING@@KPEBDPEAD@Z equ <__imp_?QueryResourceStringV@BASE_SYSTEM@@SAEPEAVWSTRING@@KPEBDPEAD@Z>

externdef __imp_?QueryRoot@PATH@@QEAAPEAVWSTRING@@XZ:PPROC
?QueryRoot@PATH@@QEAAPEAVWSTRING@@XZ equ <__imp_?QueryRoot@PATH@@QEAAPEAVWSTRING@@XZ>

externdef __imp_?QuerySTR@BSTRING@@QEBAPEADKKPEADKE@Z:PPROC
?QuerySTR@BSTRING@@QEBAPEADKKPEADKE@Z equ <__imp_?QuerySTR@BSTRING@@QEBAPEADKKPEADKE@Z>

externdef __imp_?QuerySTR@WSTRING@@QEBAPEADKKPEADKE@Z:PPROC
?QuerySTR@WSTRING@@QEBAPEADKKPEADKE@Z equ <__imp_?QuerySTR@WSTRING@@QEBAPEADKKPEADKE@Z>

externdef __imp_?QueryScreenSize@SCREEN@@QEBAXPEAG000@Z:PPROC
?QueryScreenSize@SCREEN@@QEBAXPEAG000@Z equ <__imp_?QueryScreenSize@SCREEN@@QEBAXPEAG000@Z>

externdef __imp_?QueryStream@FSN_FILE@@QEAAPEAVFILE_STREAM@@W4STREAMACCESS@@K@Z:PPROC
?QueryStream@FSN_FILE@@QEAAPEAVFILE_STREAM@@W4STREAMACCESS@@K@Z equ <__imp_?QueryStream@FSN_FILE@@QEAAPEAVFILE_STREAM@@W4STREAMACCESS@@K@Z>

externdef __imp_?QueryString@WSTRING@@QEBAPEAV1@KK@Z:PPROC
?QueryString@WSTRING@@QEBAPEAV1@KK@Z equ <__imp_?QueryString@WSTRING@@QEBAPEAV1@KK@Z>

externdef __imp_?QueryStringInput@MESSAGE@@UEAAEPEAVWSTRING@@@Z:PPROC
?QueryStringInput@MESSAGE@@UEAAEPEAVWSTRING@@@Z equ <__imp_?QueryStringInput@MESSAGE@@UEAAEPEAVWSTRING@@@Z>

externdef __imp_?QuerySystemDirectory@SYSTEM@@SAPEAVPATH@@XZ:PPROC
?QuerySystemDirectory@SYSTEM@@SAPEAVPATH@@XZ equ <__imp_?QuerySystemDirectory@SYSTEM@@SAPEAVPATH@@XZ>

externdef __imp_?QueryTime@TIMEINFO@@QEBAEPEAVWSTRING@@@Z:PPROC
?QueryTime@TIMEINFO@@QEBAEPEAVWSTRING@@@Z equ <__imp_?QueryTime@TIMEINFO@@QEBAEPEAVWSTRING@@@Z>

externdef __imp_?QueryTimeOut@COMM_DEVICE@@QEBAEXZ:PPROC
?QueryTimeOut@COMM_DEVICE@@QEBAEXZ equ <__imp_?QueryTimeOut@COMM_DEVICE@@QEBAEXZ>

externdef __imp_?QueryVolumeLabel@SYSTEM@@SAPEAVWSTRING@@PEAVPATH@@PEAU_VOL_SERIAL_NUMBER@@@Z:PPROC
?QueryVolumeLabel@SYSTEM@@SAPEAVWSTRING@@PEAVPATH@@PEAU_VOL_SERIAL_NUMBER@@@Z equ <__imp_?QueryVolumeLabel@SYSTEM@@SAPEAVWSTRING@@PEAVPATH@@PEAU_VOL_SERIAL_NUMBER@@@Z>

externdef __imp_?QueryWCExpansion@PATH@@QEAAPEAV1@PEAV1@@Z:PPROC
?QueryWCExpansion@PATH@@QEAAPEAV1@PEAV1@@Z equ <__imp_?QueryWCExpansion@PATH@@QEAAPEAV1@PEAV1@@Z>

externdef __imp_?QueryWSTR@WSTRING@@QEBAPEAGKKPEAGKE@Z:PPROC
?QueryWSTR@WSTRING@@QEBAPEAGKKPEAGKE@Z equ <__imp_?QueryWSTR@WSTRING@@QEBAPEAGKKPEAGKE@Z>

externdef __imp_?QueryWindowsErrorMessage@SYSTEM@@SAEKPEAVWSTRING@@@Z:PPROC
?QueryWindowsErrorMessage@SYSTEM@@SAEKPEAVWSTRING@@@Z equ <__imp_?QueryWindowsErrorMessage@SYSTEM@@SAEKPEAVWSTRING@@@Z>

externdef __imp_?ReadAt@FILE_STREAM@@QEAAEPEAEK_JW4SEEKORIGIN@@PEAK@Z:PPROC
?ReadAt@FILE_STREAM@@QEAAEPEAEK_JW4SEEKORIGIN@@PEAK@Z equ <__imp_?ReadAt@FILE_STREAM@@QEAAEPEAEK_JW4SEEKORIGIN@@PEAK@Z>

externdef __imp_?ReadLine@STREAM@@QEAAEPEAVWSTRING@@E@Z:PPROC
?ReadLine@STREAM@@QEAAEPEAVWSTRING@@E@Z equ <__imp_?ReadLine@STREAM@@QEAAEPEAVWSTRING@@E@Z>

externdef __imp_?ReadMbLine@STREAM@@QEAAEPEADKPEAKEK@Z:PPROC
?ReadMbLine@STREAM@@QEAAEPEADKPEAKEK@Z equ <__imp_?ReadMbLine@STREAM@@QEAAEPEADKPEAKEK@Z>

externdef __imp_?ReadWLine@STREAM@@QEAAEPEAGKPEAKEK@Z:PPROC
?ReadWLine@STREAM@@QEAAEPEAGKPEAKEK@Z equ <__imp_?ReadWLine@STREAM@@QEAAEPEAGKPEAKEK@Z>

externdef __imp_?Remove@ARRAY@@UEAAPEAVOBJECT@@PEAVITERATOR@@@Z:PPROC
?Remove@ARRAY@@UEAAPEAVOBJECT@@PEAVITERATOR@@@Z equ <__imp_?Remove@ARRAY@@UEAAPEAVOBJECT@@PEAVITERATOR@@@Z>

externdef __imp_?RemoveNode@SYSTEM@@SAEPEAPEAVFSNODE@@E@Z:PPROC
?RemoveNode@SYSTEM@@SAEPEAPEAVFSNODE@@E@Z equ <__imp_?RemoveNode@SYSTEM@@SAEPEAPEAVFSNODE@@E@Z>

externdef __imp_?Replace@WSTRING@@QEAAEKKPEBV1@KK@Z:PPROC
?Replace@WSTRING@@QEAAEKKPEBV1@KK@Z equ <__imp_?Replace@WSTRING@@QEAAEKKPEBV1@KK@Z>

externdef __imp_?ReplaceWithChars@BSTRING@@QEAAEKKDK@Z:PPROC
?ReplaceWithChars@BSTRING@@QEAAEKKDK@Z equ <__imp_?ReplaceWithChars@BSTRING@@QEAAEKKDK@Z>

externdef __imp_?ReplaceWithChars@WSTRING@@QEAAEKKGK@Z:PPROC
?ReplaceWithChars@WSTRING@@QEAAEKKGK@Z equ <__imp_?ReplaceWithChars@WSTRING@@QEAAEKKGK@Z>

externdef __imp_?ResetBit@BITVECTOR@@QEAAXKK@Z:PPROC
?ResetBit@BITVECTOR@@QEAAXKK@Z equ <__imp_?ResetBit@BITVECTOR@@QEAAXKK@Z>

externdef __imp_?ResetConversions@WSTRING@@SAXXZ:PPROC
?ResetConversions@WSTRING@@SAXXZ equ <__imp_?ResetConversions@WSTRING@@SAXXZ>

externdef __imp_?ResetLoggingIterator@MESSAGE@@QEAAXXZ:PPROC
?ResetLoggingIterator@MESSAGE@@QEAAXXZ equ <__imp_?ResetLoggingIterator@MESSAGE@@QEAAXXZ>

externdef __imp_?Resize@BDSTRING@@UEAAEK@Z:PPROC
?Resize@BDSTRING@@UEAAEK@Z equ <__imp_?Resize@BDSTRING@@UEAAEK@Z>

externdef __imp_?Resize@DSTRING@@UEAAEK@Z:PPROC
?Resize@DSTRING@@UEAAEK@Z equ <__imp_?Resize@DSTRING@@UEAAEK@Z>

externdef __imp_?Resize@FSTRING@@UEAAEK@Z:PPROC
?Resize@FSTRING@@UEAAEK@Z equ <__imp_?Resize@FSTRING@@UEAAEK@Z>

externdef __imp_?Resize@HMEM@@QEAAEKK@Z:PPROC
?Resize@HMEM@@QEAAEKK@Z equ <__imp_?Resize@HMEM@@QEAAEKK@Z>

externdef __imp_?SearchPathW@SYSTEM@@SAPEAVPATH@@PEAVWSTRING@@0@Z:PPROC
?SearchPathW@SYSTEM@@SAPEAVPATH@@PEAVWSTRING@@0@Z equ <__imp_?SearchPathW@SYSTEM@@SAPEAVPATH@@PEAVWSTRING@@0@Z>

externdef __imp_?SelectResponse@MESSAGE@@UEAAKKZZ:PPROC
?SelectResponse@MESSAGE@@UEAAKKZZ equ <__imp_?SelectResponse@MESSAGE@@UEAAKKZZ>

externdef __imp_?Set@CHKDSK_MESSAGE@@UEAAEKW4MESSAGE_TYPE@@K@Z:PPROC
?Set@CHKDSK_MESSAGE@@UEAAEKW4MESSAGE_TYPE@@K@Z equ <__imp_?Set@CHKDSK_MESSAGE@@UEAAEKW4MESSAGE_TYPE@@K@Z>

externdef __imp_?Set@STREAM_MESSAGE@@UEAAEKW4MESSAGE_TYPE@@K@Z:PPROC
?Set@STREAM_MESSAGE@@UEAAEKW4MESSAGE_TYPE@@K@Z equ <__imp_?Set@STREAM_MESSAGE@@UEAAEKW4MESSAGE_TYPE@@K@Z>

externdef __imp_?SetAllowSwitchGlomming@ARGUMENT_LEXEMIZER@@QEAAXE@Z:PPROC
?SetAllowSwitchGlomming@ARGUMENT_LEXEMIZER@@QEAAXE@Z equ <__imp_?SetAllowSwitchGlomming@ARGUMENT_LEXEMIZER@@QEAAXE@Z>

externdef __imp_?SetAnsiConversions@WSTRING@@SAXXZ:PPROC
?SetAnsiConversions@WSTRING@@SAXXZ equ <__imp_?SetAnsiConversions@WSTRING@@SAXXZ>

externdef __imp_?SetAttributes@FSN_FILTER@@QEAAEKKK@Z:PPROC
?SetAttributes@FSN_FILTER@@QEAAEKKK@Z equ <__imp_?SetAttributes@FSN_FILTER@@QEAAEKKK@Z>

externdef __imp_?SetBaudRate@COMM_DEVICE@@QEAAEK@Z:PPROC
?SetBaudRate@COMM_DEVICE@@QEAAEK@Z equ <__imp_?SetBaudRate@COMM_DEVICE@@QEAAEK@Z>

externdef __imp_?SetBit@BITVECTOR@@QEAAXKK@Z:PPROC
?SetBit@BITVECTOR@@QEAAXKK@Z equ <__imp_?SetBit@BITVECTOR@@QEAAXKK@Z>

externdef __imp_?SetCaseSensitive@ARGUMENT_LEXEMIZER@@QEAAXE@Z:PPROC
?SetCaseSensitive@ARGUMENT_LEXEMIZER@@QEAAXE@Z equ <__imp_?SetCaseSensitive@ARGUMENT_LEXEMIZER@@QEAAXE@Z>

externdef __imp_?SetChAt@WSTRING@@QEAAGGK@Z:PPROC
?SetChAt@WSTRING@@QEAAGGK@Z equ <__imp_?SetChAt@WSTRING@@QEAAGGK@Z>

externdef __imp_?SetClassDescriptor@OBJECT@@IEAAXPEBVCLASS_DESCRIPTOR@@@Z:PPROC
?SetClassDescriptor@OBJECT@@IEAAXPEBVCLASS_DESCRIPTOR@@@Z equ <__imp_?SetClassDescriptor@OBJECT@@IEAAXPEBVCLASS_DESCRIPTOR@@@Z>

externdef __imp_?SetCodePage@SCREEN@@QEAAEK@Z:PPROC
?SetCodePage@SCREEN@@QEAAEK@Z equ <__imp_?SetCodePage@SCREEN@@QEAAEK@Z>

externdef __imp_?SetConsoleConversions@WSTRING@@SAXXZ:PPROC
?SetConsoleConversions@WSTRING@@SAXXZ equ <__imp_?SetConsoleConversions@WSTRING@@SAXXZ>

externdef __imp_?SetDataBits@COMM_DEVICE@@QEAAEK@Z:PPROC
?SetDataBits@COMM_DEVICE@@QEAAEK@Z equ <__imp_?SetDataBits@COMM_DEVICE@@QEAAEK@Z>

externdef __imp_?SetDevice@PATH@@QEAAEPEBVWSTRING@@@Z:PPROC
?SetDevice@PATH@@QEAAEPEBVWSTRING@@@Z equ <__imp_?SetDevice@PATH@@QEAAEPEBVWSTRING@@@Z>

externdef __imp_?SetDotsOnly@MESSAGE@@UEAAEE@Z:PPROC
?SetDotsOnly@MESSAGE@@UEAAEE@Z equ <__imp_?SetDotsOnly@MESSAGE@@UEAAEE@Z>

externdef __imp_?SetDtrControl@COMM_DEVICE@@QEAAEW4DTR_CONTROL@@@Z:PPROC
?SetDtrControl@COMM_DEVICE@@QEAAEW4DTR_CONTROL@@@Z equ <__imp_?SetDtrControl@COMM_DEVICE@@QEAAEW4DTR_CONTROL@@@Z>

externdef __imp_?SetFileName@FSN_FILTER@@QEAAEPEBD@Z:PPROC
?SetFileName@FSN_FILTER@@QEAAEPEBD@Z equ <__imp_?SetFileName@FSN_FILTER@@QEAAEPEBD@Z>

externdef __imp_?SetFileName@FSN_FILTER@@QEAAEPEBVWSTRING@@@Z:PPROC
?SetFileName@FSN_FILTER@@QEAAEPEBVWSTRING@@@Z equ <__imp_?SetFileName@FSN_FILTER@@QEAAEPEBVWSTRING@@@Z>

externdef __imp_?SetIdsr@COMM_DEVICE@@QEAAEE@Z:PPROC
?SetIdsr@COMM_DEVICE@@QEAAEE@Z equ <__imp_?SetIdsr@COMM_DEVICE@@QEAAEE@Z>

externdef __imp_?SetLoggingEnabled@MESSAGE@@QEAAXE@Z:PPROC
?SetLoggingEnabled@MESSAGE@@QEAAXE@Z equ <__imp_?SetLoggingEnabled@MESSAGE@@QEAAXE@Z>

externdef __imp_?SetName@PATH@@QEAAEPEBVWSTRING@@@Z:PPROC
?SetName@PATH@@QEAAEPEBVWSTRING@@@Z equ <__imp_?SetName@PATH@@QEAAEPEBVWSTRING@@@Z>

externdef __imp_?SetNoSpcBetweenDstAndSwitch@ARGUMENT_LEXEMIZER@@QEAAXE@Z:PPROC
?SetNoSpcBetweenDstAndSwitch@ARGUMENT_LEXEMIZER@@QEAAXE@Z equ <__imp_?SetNoSpcBetweenDstAndSwitch@ARGUMENT_LEXEMIZER@@QEAAXE@Z>

externdef __imp_?SetOcts@COMM_DEVICE@@QEAAEE@Z:PPROC
?SetOcts@COMM_DEVICE@@QEAAEE@Z equ <__imp_?SetOcts@COMM_DEVICE@@QEAAEE@Z>

externdef __imp_?SetOdsr@COMM_DEVICE@@QEAAEE@Z:PPROC
?SetOdsr@COMM_DEVICE@@QEAAEE@Z equ <__imp_?SetOdsr@COMM_DEVICE@@QEAAEE@Z>

externdef __imp_?SetOemConversions@WSTRING@@SAXXZ:PPROC
?SetOemConversions@WSTRING@@SAXXZ equ <__imp_?SetOemConversions@WSTRING@@SAXXZ>

externdef __imp_?SetOutputCodePage@SCREEN@@QEAAEK@Z:PPROC
?SetOutputCodePage@SCREEN@@QEAAEK@Z equ <__imp_?SetOutputCodePage@SCREEN@@QEAAEK@Z>

externdef __imp_?SetParity@COMM_DEVICE@@QEAAEW4PARITY@@@Z:PPROC
?SetParity@COMM_DEVICE@@QEAAEW4PARITY@@@Z equ <__imp_?SetParity@COMM_DEVICE@@QEAAEW4PARITY@@@Z>

externdef __imp_?SetRtsControl@COMM_DEVICE@@QEAAEW4RTS_CONTROL@@@Z:PPROC
?SetRtsControl@COMM_DEVICE@@QEAAEW4RTS_CONTROL@@@Z equ <__imp_?SetRtsControl@COMM_DEVICE@@QEAAEW4RTS_CONTROL@@@Z>

externdef __imp_?SetSize@BITVECTOR@@QEAAKKW4BIT@@@Z:PPROC
?SetSize@BITVECTOR@@QEAAKKW4BIT@@@Z equ <__imp_?SetSize@BITVECTOR@@QEAAKKW4BIT@@@Z>

externdef __imp_?SetStopBits@COMM_DEVICE@@QEAAEW4STOPBITS@@@Z:PPROC
?SetStopBits@COMM_DEVICE@@QEAAEW4STOPBITS@@@Z equ <__imp_?SetStopBits@COMM_DEVICE@@QEAAEW4STOPBITS@@@Z>

externdef __imp_?SetTimeInfo@FSN_FILTER@@QEAAEPEBVTIMEINFO@@W4FSN_TIME@@G@Z:PPROC
?SetTimeInfo@FSN_FILTER@@QEAAEPEBVTIMEINFO@@W4FSN_TIME@@G@Z equ <__imp_?SetTimeInfo@FSN_FILTER@@QEAAEPEBVTIMEINFO@@W4FSN_TIME@@G@Z>

externdef __imp_?SetTimeOut@COMM_DEVICE@@QEAAEE@Z:PPROC
?SetTimeOut@COMM_DEVICE@@QEAAEE@Z equ <__imp_?SetTimeOut@COMM_DEVICE@@QEAAEE@Z>

externdef __imp_?SetXon@COMM_DEVICE@@QEAAEE@Z:PPROC
?SetXon@COMM_DEVICE@@QEAAEE@Z equ <__imp_?SetXon@COMM_DEVICE@@QEAAEE@Z>

externdef __imp_?SkipWhite@WSTRING@@SAPEAGPEAG@Z:PPROC
?SkipWhite@WSTRING@@SAPEAGPEAG@Z equ <__imp_?SkipWhite@WSTRING@@SAPEAGPEAG@Z>

externdef __imp_?Sort@STRING_ARRAY@@UEAAEE@Z:PPROC
?Sort@STRING_ARRAY@@UEAAEE@Z equ <__imp_?Sort@STRING_ARRAY@@UEAAEE@Z>

externdef __imp_?Strcat@WSTRING@@QEAAEPEBV1@@Z:PPROC
?Strcat@WSTRING@@QEAAEPEBV1@@Z equ <__imp_?Strcat@WSTRING@@QEAAEPEBV1@@Z>

externdef __imp_?Strchr@BSTRING@@QEBAKDK@Z:PPROC
?Strchr@BSTRING@@QEBAKDK@Z equ <__imp_?Strchr@BSTRING@@QEBAKDK@Z>

externdef __imp_?Strchr@WSTRING@@QEBAKGK@Z:PPROC
?Strchr@WSTRING@@QEBAKGK@Z equ <__imp_?Strchr@WSTRING@@QEBAKGK@Z>

externdef __imp_?Strcmp@WSTRING@@QEBAJPEBV1@@Z:PPROC
?Strcmp@WSTRING@@QEBAJPEBV1@@Z equ <__imp_?Strcmp@WSTRING@@QEBAJPEBV1@@Z>

externdef __imp_?Strcmp@WSTRING@@QEBAJPEBV1@K@Z:PPROC
?Strcmp@WSTRING@@QEBAJPEBV1@K@Z equ <__imp_?Strcmp@WSTRING@@QEBAJPEBV1@K@Z>

externdef __imp_?Strcmp@WSTRING@@QEBAJPEBV1@KKKK@Z:PPROC
?Strcmp@WSTRING@@QEBAJPEBV1@KKKK@Z equ <__imp_?Strcmp@WSTRING@@QEBAJPEBV1@KKKK@Z>

externdef __imp_?Strcmp@WSTRING@@SAHPEAG0@Z:PPROC
?Strcmp@WSTRING@@SAHPEAG0@Z equ <__imp_?Strcmp@WSTRING@@SAHPEAG0@Z>

externdef __imp_?Strcmpis@MBSTR@@SAHPEAD0@Z:PPROC
?Strcmpis@MBSTR@@SAHPEAD0@Z equ <__imp_?Strcmpis@MBSTR@@SAHPEAD0@Z>

externdef __imp_?Strcmpis@WSTRING@@SAHPEAG0@Z:PPROC
?Strcmpis@WSTRING@@SAHPEAG0@Z equ <__imp_?Strcmpis@WSTRING@@SAHPEAG0@Z>

externdef __imp_?Strcmps@MBSTR@@SAHPEAD0@Z:PPROC
?Strcmps@MBSTR@@SAHPEAD0@Z equ <__imp_?Strcmps@MBSTR@@SAHPEAD0@Z>

externdef __imp_?Strcmps@WSTRING@@SAHPEAG0@Z:PPROC
?Strcmps@WSTRING@@SAHPEAG0@Z equ <__imp_?Strcmps@WSTRING@@SAHPEAG0@Z>

externdef __imp_?Strcspn@WSTRING@@QEBAKPEBV1@K@Z:PPROC
?Strcspn@WSTRING@@QEBAKPEBV1@K@Z equ <__imp_?Strcspn@WSTRING@@QEBAKPEBV1@K@Z>

externdef __imp_?Stricmp@MBSTR@@SAHPEAD0@Z:PPROC
?Stricmp@MBSTR@@SAHPEAD0@Z equ <__imp_?Stricmp@MBSTR@@SAHPEAD0@Z>

externdef __imp_?Stricmp@WSTRING@@QEBAJPEBV1@@Z:PPROC
?Stricmp@WSTRING@@QEBAJPEBV1@@Z equ <__imp_?Stricmp@WSTRING@@QEBAJPEBV1@@Z>

externdef __imp_?Stricmp@WSTRING@@QEBAJPEBV1@K@Z:PPROC
?Stricmp@WSTRING@@QEBAJPEBV1@K@Z equ <__imp_?Stricmp@WSTRING@@QEBAJPEBV1@K@Z>

externdef __imp_?Stricmp@WSTRING@@QEBAJPEBV1@KKKK@Z:PPROC
?Stricmp@WSTRING@@QEBAJPEBV1@KKKK@Z equ <__imp_?Stricmp@WSTRING@@QEBAJPEBV1@KKKK@Z>

externdef __imp_?Stricmp@WSTRING@@SAHPEAG0@Z:PPROC
?Stricmp@WSTRING@@SAHPEAG0@Z equ <__imp_?Stricmp@WSTRING@@SAHPEAG0@Z>

externdef __imp_?Strlwr@WSTRING@@QEAAPEAV1@KK@Z:PPROC
?Strlwr@WSTRING@@QEAAPEAV1@KK@Z equ <__imp_?Strlwr@WSTRING@@QEAAPEAV1@KK@Z>

externdef __imp_?Strlwr@WSTRING@@QEAAPEAV1@XZ:PPROC
?Strlwr@WSTRING@@QEAAPEAV1@XZ equ <__imp_?Strlwr@WSTRING@@QEAAPEAV1@XZ>

externdef __imp_?Strrchr@WSTRING@@QEBAKGK@Z:PPROC
?Strrchr@WSTRING@@QEBAKGK@Z equ <__imp_?Strrchr@WSTRING@@QEBAKGK@Z>

externdef __imp_?Strspn@WSTRING@@QEBAKPEBV1@K@Z:PPROC
?Strspn@WSTRING@@QEBAKPEBV1@K@Z equ <__imp_?Strspn@WSTRING@@QEBAKPEBV1@K@Z>

externdef __imp_?Strstr@MBSTR@@SAPEADPEAD0@Z:PPROC
?Strstr@MBSTR@@SAPEADPEAD0@Z equ <__imp_?Strstr@MBSTR@@SAPEADPEAD0@Z>

externdef __imp_?Strstr@WSTRING@@QEBAKPEBV1@@Z:PPROC
?Strstr@WSTRING@@QEBAKPEBV1@@Z equ <__imp_?Strstr@WSTRING@@QEBAKPEBV1@@Z>

externdef __imp_?Strupr@WSTRING@@QEAAPEAV1@KK@Z:PPROC
?Strupr@WSTRING@@QEAAPEAV1@KK@Z equ <__imp_?Strupr@WSTRING@@QEAAPEAV1@KK@Z>

externdef __imp_?Strupr@WSTRING@@QEAAPEAV1@XZ:PPROC
?Strupr@WSTRING@@QEAAPEAV1@XZ equ <__imp_?Strupr@WSTRING@@QEAAPEAV1@XZ>

externdef __imp_?SyncLength@WSTRING@@QEAAKXZ:PPROC
?SyncLength@WSTRING@@QEAAKXZ equ <__imp_?SyncLength@WSTRING@@QEAAKXZ>

externdef __imp_?Traverse@FSN_DIRECTORY@@QEBAEPEAXPEAVFSN_FILTER@@PEAVPATH@@P6AE0PEAVFSNODE@@2@Z@Z:PPROC
?Traverse@FSN_DIRECTORY@@QEBAEPEAXPEAVFSN_FILTER@@PEAVPATH@@P6AE0PEAVFSNODE@@2@Z@Z equ <__imp_?Traverse@FSN_DIRECTORY@@QEBAEPEAXPEAVFSN_FILTER@@PEAVPATH@@P6AE0PEAVFSNODE@@2@Z@Z>

externdef __imp_?Truncate@WSTRING@@QEAAKK@Z:PPROC
?Truncate@WSTRING@@QEAAKK@Z equ <__imp_?Truncate@WSTRING@@QEAAKK@Z>

externdef __imp_?TruncateBase@PATH@@QEAAEXZ:PPROC
?TruncateBase@PATH@@QEAAEXZ equ <__imp_?TruncateBase@PATH@@QEAAEXZ>

externdef __imp_?TruncateDelimiter@PATH@@QEAAXXZ:PPROC
?TruncateDelimiter@PATH@@QEAAXXZ equ <__imp_?TruncateDelimiter@PATH@@QEAAXXZ>

externdef __imp_?TruncateNameAtColon@PATH@@QEAAXXZ:PPROC
?TruncateNameAtColon@PATH@@QEAAXXZ equ <__imp_?TruncateNameAtColon@PATH@@QEAAXXZ>

externdef __imp_?UlibRealloc@@YAPEAXPEAXK@Z:PPROC
?UlibRealloc@@YAPEAXPEAXK@Z equ <__imp_?UlibRealloc@@YAPEAXPEAXK@Z>

externdef __imp_?Unlock@MESSAGE@@QEAAXXZ:PPROC
?Unlock@MESSAGE@@QEAAXXZ equ <__imp_?Unlock@MESSAGE@@QEAAXXZ>

externdef __imp_?Usage@PROGRAM@@UEBAXXZ:PPROC
?Usage@PROGRAM@@UEBAXXZ equ <__imp_?Usage@PROGRAM@@UEBAXXZ>

externdef __imp_?UseAlternateName@FSNODE@@QEAAEXZ:PPROC
?UseAlternateName@FSNODE@@QEAAEXZ equ <__imp_?UseAlternateName@FSNODE@@QEAAEXZ>

externdef __imp_?ValidateVersion@PROGRAM@@UEBAXKK@Z:PPROC
?ValidateVersion@PROGRAM@@UEBAXKK@Z equ <__imp_?ValidateVersion@PROGRAM@@UEBAXKK@Z>

externdef __imp_?WaitForUserSignal@MESSAGE@@UEAAEXZ:PPROC
?WaitForUserSignal@MESSAGE@@UEAAEXZ equ <__imp_?WaitForUserSignal@MESSAGE@@UEAAEXZ>

externdef __imp_?WriteByte@STREAM@@QEAAEE@Z:PPROC
?WriteByte@STREAM@@QEAAEE@Z equ <__imp_?WriteByte@STREAM@@QEAAEE@Z>

externdef __imp_?_UseAnsiConversions@WSTRING@@0EA:PPROC
?_UseAnsiConversions@WSTRING@@0EA equ <__imp_?_UseAnsiConversions@WSTRING@@0EA>
  IFNDEF __UNICODE__
    ?_UseAnsiConversions@WSTRING@@0E equ <__imp_?_UseAnsiConversions@WSTRING@@0EA>
  ENDIF

externdef __imp_?_UseAnsiConversionsPrev@WSTRING@@0EA:PPROC
?_UseAnsiConversionsPrev@WSTRING@@0EA equ <__imp_?_UseAnsiConversionsPrev@WSTRING@@0EA>
  IFNDEF __UNICODE__
    ?_UseAnsiConversionsPrev@WSTRING@@0E equ <__imp_?_UseAnsiConversionsPrev@WSTRING@@0EA>
  ENDIF

externdef __imp_?_UseConsoleConversions@WSTRING@@0EA:PPROC
?_UseConsoleConversions@WSTRING@@0EA equ <__imp_?_UseConsoleConversions@WSTRING@@0EA>
  IFNDEF __UNICODE__
    ?_UseConsoleConversions@WSTRING@@0E equ <__imp_?_UseConsoleConversions@WSTRING@@0EA>
  ENDIF

externdef __imp_?_UseConsoleConversionsPrev@WSTRING@@0EA:PPROC
?_UseConsoleConversionsPrev@WSTRING@@0EA equ <__imp_?_UseConsoleConversionsPrev@WSTRING@@0EA>
  IFNDEF __UNICODE__
    ?_UseConsoleConversionsPrev@WSTRING@@0E equ <__imp_?_UseConsoleConversionsPrev@WSTRING@@0EA>
  ENDIF
