externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_InstallUPnPUI:PPROC
InstallUPnPUI equ <__imp_InstallUPnPUI>

externdef __imp_IsUPnPUIInstalled:PPROC
IsUPnPUIInstalled equ <__imp_IsUPnPUIInstalled>

externdef __imp_UnInstallUPnPUI:PPROC
UnInstallUPnPUI equ <__imp_UnInstallUPnPUI>
