externdef __imp_LpkPresent:PPROC
LpkPresent equ <__imp_LpkPresent>

externdef __imp_ScriptApplyDigitSubstitution:PPROC
ScriptApplyDigitSubstitution equ <__imp_ScriptApplyDigitSubstitution>

externdef __imp_ScriptApplyLogicalWidth:PPROC
ScriptApplyLogicalWidth equ <__imp_ScriptApplyLogicalWidth>

externdef __imp_ScriptBreak:PPROC
ScriptBreak equ <__imp_ScriptBreak>

externdef __imp_ScriptCPtoX:PPROC
ScriptCPtoX equ <__imp_ScriptCPtoX>

externdef __imp_ScriptCacheGetHeight:PPROC
ScriptCacheGetHeight equ <__imp_ScriptCacheGetHeight>

externdef __imp_ScriptFreeCache:PPROC
ScriptFreeCache equ <__imp_ScriptFreeCache>

externdef __imp_ScriptGetCMap:PPROC
ScriptGetCMap equ <__imp_ScriptGetCMap>

externdef __imp_ScriptGetFontProperties:PPROC
ScriptGetFontProperties equ <__imp_ScriptGetFontProperties>

externdef __imp_ScriptGetGlyphABCWidth:PPROC
ScriptGetGlyphABCWidth equ <__imp_ScriptGetGlyphABCWidth>

externdef __imp_ScriptGetLogicalWidths:PPROC
ScriptGetLogicalWidths equ <__imp_ScriptGetLogicalWidths>

externdef __imp_ScriptGetProperties:PPROC
ScriptGetProperties equ <__imp_ScriptGetProperties>

externdef __imp_ScriptIsComplex:PPROC
ScriptIsComplex equ <__imp_ScriptIsComplex>

externdef __imp_ScriptItemize:PPROC
ScriptItemize equ <__imp_ScriptItemize>

externdef __imp_ScriptJustify:PPROC
ScriptJustify equ <__imp_ScriptJustify>

externdef __imp_ScriptLayout:PPROC
ScriptLayout equ <__imp_ScriptLayout>

externdef __imp_ScriptPlace:PPROC
ScriptPlace equ <__imp_ScriptPlace>

externdef __imp_ScriptRecordDigitSubstitution:PPROC
ScriptRecordDigitSubstitution equ <__imp_ScriptRecordDigitSubstitution>

externdef __imp_ScriptShape:PPROC
ScriptShape equ <__imp_ScriptShape>

externdef __imp_ScriptStringAnalyse:PPROC
ScriptStringAnalyse equ <__imp_ScriptStringAnalyse>

externdef __imp_ScriptStringCPtoX:PPROC
ScriptStringCPtoX equ <__imp_ScriptStringCPtoX>

externdef __imp_ScriptStringFree:PPROC
ScriptStringFree equ <__imp_ScriptStringFree>

externdef __imp_ScriptStringGetLogicalWidths:PPROC
ScriptStringGetLogicalWidths equ <__imp_ScriptStringGetLogicalWidths>

externdef __imp_ScriptStringGetOrder:PPROC
ScriptStringGetOrder equ <__imp_ScriptStringGetOrder>

externdef __imp_ScriptStringOut:PPROC
ScriptStringOut equ <__imp_ScriptStringOut>

externdef __imp_ScriptStringValidate:PPROC
ScriptStringValidate equ <__imp_ScriptStringValidate>

externdef __imp_ScriptStringXtoCP:PPROC
ScriptStringXtoCP equ <__imp_ScriptStringXtoCP>

externdef __imp_ScriptString_pLogAttr:PPROC
ScriptString_pLogAttr equ <__imp_ScriptString_pLogAttr>

externdef __imp_ScriptString_pSize:PPROC
ScriptString_pSize equ <__imp_ScriptString_pSize>

externdef __imp_ScriptString_pcOutChars:PPROC
ScriptString_pcOutChars equ <__imp_ScriptString_pcOutChars>

externdef __imp_ScriptTextOut:PPROC
ScriptTextOut equ <__imp_ScriptTextOut>

externdef __imp_ScriptXtoCP:PPROC
ScriptXtoCP equ <__imp_ScriptXtoCP>

externdef __imp_UspAllocCache:PPROC
UspAllocCache equ <__imp_UspAllocCache>

externdef __imp_UspAllocTemp:PPROC
UspAllocTemp equ <__imp_UspAllocTemp>

externdef __imp_UspFreeMem:PPROC
UspFreeMem equ <__imp_UspFreeMem>
