externdef __imp_CloseThemeData:PPROC
CloseThemeData equ <__imp_CloseThemeData>

externdef __imp_DrawThemeBackground:PPROC
DrawThemeBackground equ <__imp_DrawThemeBackground>

externdef __imp_DrawThemeBackgroundEx:PPROC
DrawThemeBackgroundEx equ <__imp_DrawThemeBackgroundEx>

externdef __imp_DrawThemeEdge:PPROC
DrawThemeEdge equ <__imp_DrawThemeEdge>

externdef __imp_DrawThemeIcon:PPROC
DrawThemeIcon equ <__imp_DrawThemeIcon>

externdef __imp_DrawThemeParentBackground:PPROC
DrawThemeParentBackground equ <__imp_DrawThemeParentBackground>

externdef __imp_DrawThemeText:PPROC
DrawThemeText equ <__imp_DrawThemeText>

externdef __imp_EnableThemeDialogTexture:PPROC
EnableThemeDialogTexture equ <__imp_EnableThemeDialogTexture>

externdef __imp_EnableTheming:PPROC
EnableTheming equ <__imp_EnableTheming>

externdef __imp_GetCurrentThemeName:PPROC
GetCurrentThemeName equ <__imp_GetCurrentThemeName>

externdef __imp_GetThemeAppProperties:PPROC
GetThemeAppProperties equ <__imp_GetThemeAppProperties>

externdef __imp_GetThemeBackgroundContentRect:PPROC
GetThemeBackgroundContentRect equ <__imp_GetThemeBackgroundContentRect>

externdef __imp_GetThemeBackgroundExtent:PPROC
GetThemeBackgroundExtent equ <__imp_GetThemeBackgroundExtent>

externdef __imp_GetThemeBackgroundRegion:PPROC
GetThemeBackgroundRegion equ <__imp_GetThemeBackgroundRegion>

externdef __imp_GetThemeBool:PPROC
GetThemeBool equ <__imp_GetThemeBool>

externdef __imp_GetThemeColor:PPROC
GetThemeColor equ <__imp_GetThemeColor>

externdef __imp_GetThemeDocumentationProperty:PPROC
GetThemeDocumentationProperty equ <__imp_GetThemeDocumentationProperty>

externdef __imp_GetThemeEnumValue:PPROC
GetThemeEnumValue equ <__imp_GetThemeEnumValue>

externdef __imp_GetThemeFilename:PPROC
GetThemeFilename equ <__imp_GetThemeFilename>

externdef __imp_GetThemeFont:PPROC
GetThemeFont equ <__imp_GetThemeFont>

externdef __imp_GetThemeInt:PPROC
GetThemeInt equ <__imp_GetThemeInt>

externdef __imp_GetThemeIntList:PPROC
GetThemeIntList equ <__imp_GetThemeIntList>

externdef __imp_GetThemeMargins:PPROC
GetThemeMargins equ <__imp_GetThemeMargins>

externdef __imp_GetThemeMetric:PPROC
GetThemeMetric equ <__imp_GetThemeMetric>

externdef __imp_GetThemePartSize:PPROC
GetThemePartSize equ <__imp_GetThemePartSize>

externdef __imp_GetThemePosition:PPROC
GetThemePosition equ <__imp_GetThemePosition>

externdef __imp_GetThemePropertyOrigin:PPROC
GetThemePropertyOrigin equ <__imp_GetThemePropertyOrigin>

externdef __imp_GetThemeRect:PPROC
GetThemeRect equ <__imp_GetThemeRect>

externdef __imp_GetThemeString:PPROC
GetThemeString equ <__imp_GetThemeString>

externdef __imp_GetThemeSysBool:PPROC
GetThemeSysBool equ <__imp_GetThemeSysBool>

externdef __imp_GetThemeSysColor:PPROC
GetThemeSysColor equ <__imp_GetThemeSysColor>

externdef __imp_GetThemeSysColorBrush:PPROC
GetThemeSysColorBrush equ <__imp_GetThemeSysColorBrush>

externdef __imp_GetThemeSysFont:PPROC
GetThemeSysFont equ <__imp_GetThemeSysFont>

externdef __imp_GetThemeSysInt:PPROC
GetThemeSysInt equ <__imp_GetThemeSysInt>

externdef __imp_GetThemeSysSize:PPROC
GetThemeSysSize equ <__imp_GetThemeSysSize>

externdef __imp_GetThemeSysString:PPROC
GetThemeSysString equ <__imp_GetThemeSysString>

externdef __imp_GetThemeTextExtent:PPROC
GetThemeTextExtent equ <__imp_GetThemeTextExtent>

externdef __imp_GetThemeTextMetrics:PPROC
GetThemeTextMetrics equ <__imp_GetThemeTextMetrics>

externdef __imp_GetWindowTheme:PPROC
GetWindowTheme equ <__imp_GetWindowTheme>

externdef __imp_HitTestThemeBackground:PPROC
HitTestThemeBackground equ <__imp_HitTestThemeBackground>

externdef __imp_IsAppThemed:PPROC
IsAppThemed equ <__imp_IsAppThemed>

externdef __imp_IsThemeActive:PPROC
IsThemeActive equ <__imp_IsThemeActive>

externdef __imp_IsThemeBackgroundPartiallyTransparent:PPROC
IsThemeBackgroundPartiallyTransparent equ <__imp_IsThemeBackgroundPartiallyTransparent>

externdef __imp_IsThemeDialogTextureEnabled:PPROC
IsThemeDialogTextureEnabled equ <__imp_IsThemeDialogTextureEnabled>

externdef __imp_IsThemePartDefined:PPROC
IsThemePartDefined equ <__imp_IsThemePartDefined>

externdef __imp_OpenThemeData:PPROC
OpenThemeData equ <__imp_OpenThemeData>

externdef __imp_SetThemeAppProperties:PPROC
SetThemeAppProperties equ <__imp_SetThemeAppProperties>

externdef __imp_SetWindowTheme:PPROC
SetWindowTheme equ <__imp_SetWindowTheme>

externdef __imp_ThemeInitApiHook:PPROC
ThemeInitApiHook equ <__imp_ThemeInitApiHook>

externdef __imp_uxtheme_ordinal10:PPROC
uxtheme_ordinal10 equ <__imp_uxtheme_ordinal10>

externdef __imp_uxtheme_ordinal11:PPROC
uxtheme_ordinal11 equ <__imp_uxtheme_ordinal11>

externdef __imp_uxtheme_ordinal13:PPROC
uxtheme_ordinal13 equ <__imp_uxtheme_ordinal13>

externdef __imp_uxtheme_ordinal14:PPROC
uxtheme_ordinal14 equ <__imp_uxtheme_ordinal14>

externdef __imp_uxtheme_ordinal15:PPROC
uxtheme_ordinal15 equ <__imp_uxtheme_ordinal15>

externdef __imp_uxtheme_ordinal16:PPROC
uxtheme_ordinal16 equ <__imp_uxtheme_ordinal16>

externdef __imp_uxtheme_ordinal17:PPROC
uxtheme_ordinal17 equ <__imp_uxtheme_ordinal17>

externdef __imp_uxtheme_ordinal18:PPROC
uxtheme_ordinal18 equ <__imp_uxtheme_ordinal18>

externdef __imp_uxtheme_ordinal19:PPROC
uxtheme_ordinal19 equ <__imp_uxtheme_ordinal19>

externdef __imp_uxtheme_ordinal1:PPROC
uxtheme_ordinal1 equ <__imp_uxtheme_ordinal1>

externdef __imp_uxtheme_ordinal20:PPROC
uxtheme_ordinal20 equ <__imp_uxtheme_ordinal20>

externdef __imp_uxtheme_ordinal21:PPROC
uxtheme_ordinal21 equ <__imp_uxtheme_ordinal21>

externdef __imp_uxtheme_ordinal22:PPROC
uxtheme_ordinal22 equ <__imp_uxtheme_ordinal22>

externdef __imp_uxtheme_ordinal23:PPROC
uxtheme_ordinal23 equ <__imp_uxtheme_ordinal23>

externdef __imp_uxtheme_ordinal24:PPROC
uxtheme_ordinal24 equ <__imp_uxtheme_ordinal24>

externdef __imp_uxtheme_ordinal25:PPROC
uxtheme_ordinal25 equ <__imp_uxtheme_ordinal25>

externdef __imp_uxtheme_ordinal26:PPROC
uxtheme_ordinal26 equ <__imp_uxtheme_ordinal26>

externdef __imp_uxtheme_ordinal27:PPROC
uxtheme_ordinal27 equ <__imp_uxtheme_ordinal27>

externdef __imp_uxtheme_ordinal28:PPROC
uxtheme_ordinal28 equ <__imp_uxtheme_ordinal28>

externdef __imp_uxtheme_ordinal29:PPROC
uxtheme_ordinal29 equ <__imp_uxtheme_ordinal29>

externdef __imp_uxtheme_ordinal2:PPROC
uxtheme_ordinal2 equ <__imp_uxtheme_ordinal2>

externdef __imp_uxtheme_ordinal30:PPROC
uxtheme_ordinal30 equ <__imp_uxtheme_ordinal30>

externdef __imp_uxtheme_ordinal31:PPROC
uxtheme_ordinal31 equ <__imp_uxtheme_ordinal31>

externdef __imp_uxtheme_ordinal32:PPROC
uxtheme_ordinal32 equ <__imp_uxtheme_ordinal32>

externdef __imp_uxtheme_ordinal33:PPROC
uxtheme_ordinal33 equ <__imp_uxtheme_ordinal33>

externdef __imp_uxtheme_ordinal34:PPROC
uxtheme_ordinal34 equ <__imp_uxtheme_ordinal34>

externdef __imp_uxtheme_ordinal35:PPROC
uxtheme_ordinal35 equ <__imp_uxtheme_ordinal35>

externdef __imp_uxtheme_ordinal36:PPROC
uxtheme_ordinal36 equ <__imp_uxtheme_ordinal36>

externdef __imp_uxtheme_ordinal3:PPROC
uxtheme_ordinal3 equ <__imp_uxtheme_ordinal3>

externdef __imp_uxtheme_ordinal43:PPROC
uxtheme_ordinal43 equ <__imp_uxtheme_ordinal43>

externdef __imp_uxtheme_ordinal44:PPROC
uxtheme_ordinal44 equ <__imp_uxtheme_ordinal44>

externdef __imp_uxtheme_ordinal45:PPROC
uxtheme_ordinal45 equ <__imp_uxtheme_ordinal45>

externdef __imp_uxtheme_ordinal46:PPROC
uxtheme_ordinal46 equ <__imp_uxtheme_ordinal46>

externdef __imp_uxtheme_ordinal48:PPROC
uxtheme_ordinal48 equ <__imp_uxtheme_ordinal48>

externdef __imp_uxtheme_ordinal4:PPROC
uxtheme_ordinal4 equ <__imp_uxtheme_ordinal4>

externdef __imp_uxtheme_ordinal60:PPROC
uxtheme_ordinal60 equ <__imp_uxtheme_ordinal60>

externdef __imp_uxtheme_ordinal61:PPROC
uxtheme_ordinal61 equ <__imp_uxtheme_ordinal61>

externdef __imp_uxtheme_ordinal62:PPROC
uxtheme_ordinal62 equ <__imp_uxtheme_ordinal62>

externdef __imp_uxtheme_ordinal63:PPROC
uxtheme_ordinal63 equ <__imp_uxtheme_ordinal63>

externdef __imp_uxtheme_ordinal64:PPROC
uxtheme_ordinal64 equ <__imp_uxtheme_ordinal64>

externdef __imp_uxtheme_ordinal65:PPROC
uxtheme_ordinal65 equ <__imp_uxtheme_ordinal65>

externdef __imp_uxtheme_ordinal66:PPROC
uxtheme_ordinal66 equ <__imp_uxtheme_ordinal66>

externdef __imp_uxtheme_ordinal73:PPROC
uxtheme_ordinal73 equ <__imp_uxtheme_ordinal73>

externdef __imp_uxtheme_ordinal7:PPROC
uxtheme_ordinal7 equ <__imp_uxtheme_ordinal7>

externdef __imp_uxtheme_ordinal8:PPROC
uxtheme_ordinal8 equ <__imp_uxtheme_ordinal8>

externdef __imp_uxtheme_ordinal9:PPROC
uxtheme_ordinal9 equ <__imp_uxtheme_ordinal9>
