externdef __imp_??0?$CVdsHandleImpl@$0?0@@QEAA@XZ:PPROC
??0?$CVdsHandleImpl@$0?0@@QEAA@XZ equ <__imp_??0?$CVdsHandleImpl@$0?0@@QEAA@XZ>

externdef __imp_??0?$CVdsHandleImpl@$0A@@@QEAA@XZ:PPROC
??0?$CVdsHandleImpl@$0A@@@QEAA@XZ equ <__imp_??0?$CVdsHandleImpl@$0A@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@D@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@D@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@D@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@E@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@E@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@E@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@G@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@G@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@G@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_FILE_PATH@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_FILE_PATH@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_FILE_PATH@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@D@@QEAA@XZ:PPROC
??0?$CVdsPtr@D@@QEAA@XZ equ <__imp_??0?$CVdsPtr@D@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@E@@QEAA@XZ:PPROC
??0?$CVdsPtr@E@@QEAA@XZ equ <__imp_??0?$CVdsPtr@E@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@G@@QEAA@XZ:PPROC
??0?$CVdsPtr@G@@QEAA@XZ equ <__imp_??0?$CVdsPtr@G@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_BOOT_ENTRY@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_BOOT_ENTRY@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_BOOT_ENTRY@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_FILE_PATH@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_FILE_PATH@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_FILE_PATH@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ>

externdef __imp_??0CPrvEnumObject@@QEAA@XZ:PPROC
??0CPrvEnumObject@@QEAA@XZ equ <__imp_??0CPrvEnumObject@@QEAA@XZ>

externdef __imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z:PPROC
??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z equ <__imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z>

externdef __imp_??0CVdsPnPNotificationBase@@QEAA@XZ:PPROC
??0CVdsPnPNotificationBase@@QEAA@XZ equ <__imp_??0CVdsPnPNotificationBase@@QEAA@XZ>

externdef __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??0CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z:PPROC
??0CVdsUnlockIt@@QEAA@AEAJ@Z equ <__imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z>

externdef __imp_??1?$CVdsHandleImpl@$0?0@@QEAA@XZ:PPROC
??1?$CVdsHandleImpl@$0?0@@QEAA@XZ equ <__imp_??1?$CVdsHandleImpl@$0?0@@QEAA@XZ>

externdef __imp_??1?$CVdsHandleImpl@$0A@@@QEAA@XZ:PPROC
??1?$CVdsHandleImpl@$0A@@@QEAA@XZ equ <__imp_??1?$CVdsHandleImpl@$0A@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@D@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@D@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@D@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@E@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@E@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@E@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@G@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@G@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@G@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_FILE_PATH@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_FILE_PATH@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_FILE_PATH@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@D@@QEAA@XZ:PPROC
??1?$CVdsPtr@D@@QEAA@XZ equ <__imp_??1?$CVdsPtr@D@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@E@@QEAA@XZ:PPROC
??1?$CVdsPtr@E@@QEAA@XZ equ <__imp_??1?$CVdsPtr@E@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@G@@QEAA@XZ:PPROC
??1?$CVdsPtr@G@@QEAA@XZ equ <__imp_??1?$CVdsPtr@G@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_BOOT_ENTRY@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_BOOT_ENTRY@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_BOOT_ENTRY@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_FILE_PATH@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_FILE_PATH@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_FILE_PATH@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAA@XZ>

externdef __imp_??1CPrvEnumObject@@QEAA@XZ:PPROC
??1CPrvEnumObject@@QEAA@XZ equ <__imp_??1CPrvEnumObject@@QEAA@XZ>

externdef __imp_??1CVdsCriticalSection@@QEAA@XZ:PPROC
??1CVdsCriticalSection@@QEAA@XZ equ <__imp_??1CVdsCriticalSection@@QEAA@XZ>

externdef __imp_??1CVdsDebugLog@@QEAA@XZ:PPROC
??1CVdsDebugLog@@QEAA@XZ equ <__imp_??1CVdsDebugLog@@QEAA@XZ>

externdef __imp_??1CVdsPnPNotificationBase@@QEAA@XZ:PPROC
??1CVdsPnPNotificationBase@@QEAA@XZ equ <__imp_??1CVdsPnPNotificationBase@@QEAA@XZ>

externdef __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??1CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??1CVdsUnlockIt@@QEAA@XZ:PPROC
??1CVdsUnlockIt@@QEAA@XZ equ <__imp_??1CVdsUnlockIt@@QEAA@XZ>

externdef __imp_??4?$CVdsHandleImpl@$0A@@@QEAAPEAXPEAX@Z:PPROC
??4?$CVdsHandleImpl@$0A@@@QEAAPEAXPEAX@Z equ <__imp_??4?$CVdsHandleImpl@$0A@@@QEAAPEAXPEAX@Z>

externdef __imp_??4?$CVdsHeapPtr@D@@QEAAPEADPEAD@Z:PPROC
??4?$CVdsHeapPtr@D@@QEAAPEADPEAD@Z equ <__imp_??4?$CVdsHeapPtr@D@@QEAAPEADPEAD@Z>

externdef __imp_??4?$CVdsHeapPtr@E@@QEAAPEAEPEAE@Z:PPROC
??4?$CVdsHeapPtr@E@@QEAAPEAEPEAE@Z equ <__imp_??4?$CVdsHeapPtr@E@@QEAAPEAEPEAE@Z>

externdef __imp_??4?$CVdsHeapPtr@G@@QEAAPEAGPEAG@Z:PPROC
??4?$CVdsHeapPtr@G@@QEAAPEAGPEAG@Z equ <__imp_??4?$CVdsHeapPtr@G@@QEAAPEAGPEAG@Z>

externdef __imp_??4?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAAPEAU_AUCTION_THREAD_PARAMETER@@PEAU1@@Z:PPROC
??4?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAAPEAU_AUCTION_THREAD_PARAMETER@@PEAU1@@Z equ <__imp_??4?$CVdsHeapPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAAPEAU_AUCTION_THREAD_PARAMETER@@PEAU1@@Z>

externdef __imp_??4?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAAPEAU_BOOT_ENTRY@@PEAU1@@Z:PPROC
??4?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAAPEAU_BOOT_ENTRY@@PEAU1@@Z equ <__imp_??4?$CVdsHeapPtr@U_BOOT_ENTRY@@@@QEAAPEAU_BOOT_ENTRY@@PEAU1@@Z>

externdef __imp_??4?$CVdsHeapPtr@U_FILE_PATH@@@@QEAAPEAU_FILE_PATH@@PEAU1@@Z:PPROC
??4?$CVdsHeapPtr@U_FILE_PATH@@@@QEAAPEAU_FILE_PATH@@PEAU1@@Z equ <__imp_??4?$CVdsHeapPtr@U_FILE_PATH@@@@QEAAPEAU_FILE_PATH@@PEAU1@@Z>

externdef __imp_??4?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@PEAU1@@Z:PPROC
??4?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@PEAU1@@Z equ <__imp_??4?$CVdsHeapPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@PEAU1@@Z>

externdef __imp_??8?$CVdsHandleImpl@$0A@@@QEBA_NPEAX@Z:PPROC
??8?$CVdsHandleImpl@$0A@@@QEBA_NPEAX@Z equ <__imp_??8?$CVdsHandleImpl@$0A@@@QEBA_NPEAX@Z>

externdef __imp_??8?$CVdsPtr@D@@QEBA_NPEAD@Z:PPROC
??8?$CVdsPtr@D@@QEBA_NPEAD@Z equ <__imp_??8?$CVdsPtr@D@@QEBA_NPEAD@Z>

externdef __imp_??8?$CVdsPtr@E@@QEBA_NPEAE@Z:PPROC
??8?$CVdsPtr@E@@QEBA_NPEAE@Z equ <__imp_??8?$CVdsPtr@E@@QEBA_NPEAE@Z>

externdef __imp_??8?$CVdsPtr@G@@QEBA_NPEAG@Z:PPROC
??8?$CVdsPtr@G@@QEBA_NPEAG@Z equ <__imp_??8?$CVdsPtr@G@@QEBA_NPEAG@Z>

externdef __imp_??8?$CVdsPtr@U_BOOT_ENTRY@@@@QEBA_NPEAU_BOOT_ENTRY@@@Z:PPROC
??8?$CVdsPtr@U_BOOT_ENTRY@@@@QEBA_NPEAU_BOOT_ENTRY@@@Z equ <__imp_??8?$CVdsPtr@U_BOOT_ENTRY@@@@QEBA_NPEAU_BOOT_ENTRY@@@Z>

externdef __imp_??8?$CVdsPtr@U_FILE_PATH@@@@QEBA_NPEAU_FILE_PATH@@@Z:PPROC
??8?$CVdsPtr@U_FILE_PATH@@@@QEBA_NPEAU_FILE_PATH@@@Z equ <__imp_??8?$CVdsPtr@U_FILE_PATH@@@@QEBA_NPEAU_FILE_PATH@@@Z>

externdef __imp_??9?$CVdsHandleImpl@$0A@@@QEBA_NPEAX@Z:PPROC
??9?$CVdsHandleImpl@$0A@@@QEBA_NPEAX@Z equ <__imp_??9?$CVdsHandleImpl@$0A@@@QEBA_NPEAX@Z>

externdef __imp_??9?$CVdsPtr@E@@QEBA_NPEAE@Z:PPROC
??9?$CVdsPtr@E@@QEBA_NPEAE@Z equ <__imp_??9?$CVdsPtr@E@@QEBA_NPEAE@Z>

externdef __imp_??9?$CVdsPtr@G@@QEBA_NPEAG@Z:PPROC
??9?$CVdsPtr@G@@QEBA_NPEAG@Z equ <__imp_??9?$CVdsPtr@G@@QEBA_NPEAG@Z>

externdef __imp_??9?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBA_NPEAU_AUCTION_THREAD_PARAMETER@@@Z:PPROC
??9?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBA_NPEAU_AUCTION_THREAD_PARAMETER@@@Z equ <__imp_??9?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBA_NPEAU_AUCTION_THREAD_PARAMETER@@@Z>

externdef __imp_??A?$CVdsPtr@D@@QEAAAEADK@Z:PPROC
??A?$CVdsPtr@D@@QEAAAEADK@Z equ <__imp_??A?$CVdsPtr@D@@QEAAAEADK@Z>

externdef __imp_??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ:PPROC
??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ equ <__imp_??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ>

externdef __imp_??B?$CVdsHandleImpl@$0A@@@QEAAPEAXXZ:PPROC
??B?$CVdsHandleImpl@$0A@@@QEAAPEAXXZ equ <__imp_??B?$CVdsHandleImpl@$0A@@@QEAAPEAXXZ>

externdef __imp_??B?$CVdsPtr@D@@QEBAPEADXZ:PPROC
??B?$CVdsPtr@D@@QEBAPEADXZ equ <__imp_??B?$CVdsPtr@D@@QEBAPEADXZ>

externdef __imp_??B?$CVdsPtr@E@@QEBAPEAEXZ:PPROC
??B?$CVdsPtr@E@@QEBAPEAEXZ equ <__imp_??B?$CVdsPtr@E@@QEBAPEAEXZ>

externdef __imp_??B?$CVdsPtr@G@@QEBAPEAGXZ:PPROC
??B?$CVdsPtr@G@@QEBAPEAGXZ equ <__imp_??B?$CVdsPtr@G@@QEBAPEAGXZ>

externdef __imp_??B?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBAPEAU_AUCTION_THREAD_PARAMETER@@XZ:PPROC
??B?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBAPEAU_AUCTION_THREAD_PARAMETER@@XZ equ <__imp_??B?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBAPEAU_AUCTION_THREAD_PARAMETER@@XZ>

externdef __imp_??B?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
??B?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_??B?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_??B?$CVdsPtr@U_FILE_PATH@@@@QEBAPEAU_FILE_PATH@@XZ:PPROC
??B?$CVdsPtr@U_FILE_PATH@@@@QEBAPEAU_FILE_PATH@@XZ equ <__imp_??B?$CVdsPtr@U_FILE_PATH@@@@QEBAPEAU_FILE_PATH@@XZ>

externdef __imp_??B?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
??B?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_??B?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_??C?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBAPEAU_AUCTION_THREAD_PARAMETER@@XZ:PPROC
??C?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBAPEAU_AUCTION_THREAD_PARAMETER@@XZ equ <__imp_??C?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEBAPEAU_AUCTION_THREAD_PARAMETER@@XZ>

externdef __imp_??C?$CVdsPtr@U_BOOT_ENTRY@@@@QEBAPEAU_BOOT_ENTRY@@XZ:PPROC
??C?$CVdsPtr@U_BOOT_ENTRY@@@@QEBAPEAU_BOOT_ENTRY@@XZ equ <__imp_??C?$CVdsPtr@U_BOOT_ENTRY@@@@QEBAPEAU_BOOT_ENTRY@@XZ>

externdef __imp_??C?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
??C?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_??C?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_??C?$CVdsPtr@U_FILE_PATH@@@@QEBAPEAU_FILE_PATH@@XZ:PPROC
??C?$CVdsPtr@U_FILE_PATH@@@@QEBAPEAU_FILE_PATH@@XZ equ <__imp_??C?$CVdsPtr@U_FILE_PATH@@@@QEBAPEAU_FILE_PATH@@XZ>

externdef __imp_??C?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
??C?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_??C?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEBAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ:PPROC
??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ equ <__imp_??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ>

externdef __imp_??I?$CVdsPtr@G@@QEAAPEAPEAGXZ:PPROC
??I?$CVdsPtr@G@@QEAAPEAPEAGXZ equ <__imp_??I?$CVdsPtr@G@@QEAAPEAPEAGXZ>

externdef __imp_??I?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
??I?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_??I?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_??I?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
??I?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_??I?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?Attach@?$CVdsPtr@G@@QEAAXPEAG@Z:PPROC
?Attach@?$CVdsPtr@G@@QEAAXPEAG@Z equ <__imp_?Attach@?$CVdsPtr@G@@QEAAXPEAG@Z>

externdef __imp_?Attach@?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z:PPROC
?Attach@?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z equ <__imp_?Attach@?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z>

externdef __imp_?Attach@?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAAXPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z:PPROC
?Attach@?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAAXPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z equ <__imp_?Attach@?$CVdsPtr@U_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@@QEAAXPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z>

externdef __imp_?Attach@?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAXPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@Z:PPROC
?Attach@?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAXPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@Z equ <__imp_?Attach@?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAXPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@Z>

externdef __imp_?Attach@?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAAXPEAU_VOLMGR_HIDDEN_VOLUMES@@@Z:PPROC
?Attach@?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAAXPEAU_VOLMGR_HIDDEN_VOLUMES@@@Z equ <__imp_?Attach@?$CVdsPtr@U_VOLMGR_HIDDEN_VOLUMES@@@@QEAAXPEAU_VOLMGR_HIDDEN_VOLUMES@@@Z>

externdef __imp_?Close@?$CVdsHandleImpl@$0?0@@QEAAXXZ:PPROC
?Close@?$CVdsHandleImpl@$0?0@@QEAAXXZ equ <__imp_?Close@?$CVdsHandleImpl@$0?0@@QEAAXXZ>

externdef __imp_?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ:PPROC
?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ equ <__imp_?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ>

externdef __imp_?Detach@?$CVdsPtr@G@@QEAAPEAGXZ:PPROC
?Detach@?$CVdsPtr@G@@QEAAPEAGXZ equ <__imp_?Detach@?$CVdsPtr@G@@QEAAPEAGXZ>

externdef __imp_?Detach@?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAAPEAU_AUCTION_THREAD_PARAMETER@@XZ:PPROC
?Detach@?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAAPEAU_AUCTION_THREAD_PARAMETER@@XZ equ <__imp_?Detach@?$CVdsPtr@U_AUCTION_THREAD_PARAMETER@@@@QEAAPEAU_AUCTION_THREAD_PARAMETER@@XZ>

externdef __imp_?Detach@?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
?Detach@?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_?Detach@?$CVdsPtr@U_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_?Detach@?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ:PPROC
?Detach@?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ equ <__imp_?Detach@?$CVdsPtr@U_VDS_DRIVE_LAYOUT_INFORMATION_EX@@@@QEAAPEAU_VDS_DRIVE_LAYOUT_INFORMATION_EX@@XZ>

externdef __imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ:PPROC
?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ equ <__imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ>

externdef __imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ:PPROC
?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ equ <__imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ>

externdef __imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z:PPROC
?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z equ <__imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z>

externdef __imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ:PPROC
?SetPositionToLast@CPrvEnumObject@@QEAAXXZ equ <__imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ>

externdef __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PPROC
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ equ <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>

externdef __imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
