externdef __imp_??0CPrvEnumObject@@QEAA@XZ:PPROC
??0CPrvEnumObject@@QEAA@XZ equ <__imp_??0CPrvEnumObject@@QEAA@XZ>

externdef __imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z:PPROC
??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z equ <__imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z>

externdef __imp_??0CVdsPnPNotificationBase@@QEAA@XZ:PPROC
??0CVdsPnPNotificationBase@@QEAA@XZ equ <__imp_??0CVdsPnPNotificationBase@@QEAA@XZ>

externdef __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??0CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z:PPROC
??0CVdsUnlockIt@@QEAA@AEAJ@Z equ <__imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z>

externdef __imp_??1CPrvEnumObject@@QEAA@XZ:PPROC
??1CPrvEnumObject@@QEAA@XZ equ <__imp_??1CPrvEnumObject@@QEAA@XZ>

externdef __imp_??1CVdsCriticalSection@@QEAA@XZ:PPROC
??1CVdsCriticalSection@@QEAA@XZ equ <__imp_??1CVdsCriticalSection@@QEAA@XZ>

externdef __imp_??1CVdsDebugLog@@QEAA@XZ:PPROC
??1CVdsDebugLog@@QEAA@XZ equ <__imp_??1CVdsDebugLog@@QEAA@XZ>

externdef __imp_??1CVdsPnPNotificationBase@@QEAA@XZ:PPROC
??1CVdsPnPNotificationBase@@QEAA@XZ equ <__imp_??1CVdsPnPNotificationBase@@QEAA@XZ>

externdef __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??1CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??1CVdsUnlockIt@@QEAA@XZ:PPROC
??1CVdsUnlockIt@@QEAA@XZ equ <__imp_??1CVdsUnlockIt@@QEAA@XZ>

externdef __imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ:PPROC
?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ equ <__imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@XZ>

externdef __imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ:PPROC
?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ equ <__imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ>

externdef __imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z:PPROC
?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z equ <__imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdsswprv_0000_0002@@@Z>

externdef __imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ:PPROC
?SetPositionToLast@CPrvEnumObject@@QEAAXXZ equ <__imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ>

externdef __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PPROC
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ equ <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>

externdef __imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_DllCanUnloadNow:PPROC
DllCanUnloadNow equ <__imp_DllCanUnloadNow>

externdef __imp_DllGetClassObject:PPROC
DllGetClassObject equ <__imp_DllGetClassObject>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>
