externdef __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??0CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??1CVdsDebugLog@@QEAA@XZ:PPROC
??1CVdsDebugLog@@QEAA@XZ equ <__imp_??1CVdsDebugLog@@QEAA@XZ>

externdef __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??1CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PPROC
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ equ <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>
