externdef __imp_??0?$CVdsHandleImpl@$0?0@@QEAA@XZ:PPROC
??0?$CVdsHandleImpl@$0?0@@QEAA@XZ equ <__imp_??0?$CVdsHandleImpl@$0?0@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>

externdef __imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PPROC
??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ equ <__imp_??0?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>

externdef __imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PPROC
??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ equ <__imp_??0?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>

externdef __imp_??0CPrvEnumObject@@QEAA@XZ:PPROC
??0CPrvEnumObject@@QEAA@XZ equ <__imp_??0CPrvEnumObject@@QEAA@XZ>

externdef __imp_??0CVdsAsyncObjectBase@@QEAA@XZ:PPROC
??0CVdsAsyncObjectBase@@QEAA@XZ equ <__imp_??0CVdsAsyncObjectBase@@QEAA@XZ>

externdef __imp_??0CVdsCallTracer@@QEAA@KPEBD@Z:PPROC
??0CVdsCallTracer@@QEAA@KPEBD@Z equ <__imp_??0CVdsCallTracer@@QEAA@KPEBD@Z>

externdef __imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z:PPROC
??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z equ <__imp_??0CVdsCriticalSection@@QEAA@PEAU_RTL_CRITICAL_SECTION@@@Z>

externdef __imp_??0CVdsDebugLog@@QEAA@H@Z:PPROC
??0CVdsDebugLog@@QEAA@H@Z equ <__imp_??0CVdsDebugLog@@QEAA@H@Z>

externdef __imp_??0CVdsPnPNotificationBase@@QEAA@XZ:PPROC
??0CVdsPnPNotificationBase@@QEAA@XZ equ <__imp_??0CVdsPnPNotificationBase@@QEAA@XZ>

externdef __imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??0CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??0CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z:PPROC
??0CVdsUnlockIt@@QEAA@AEAJ@Z equ <__imp_??0CVdsUnlockIt@@QEAA@AEAJ@Z>

externdef __imp_??0CVdsWmiVariantObjectArrayEnum@@QEAA@XZ:PPROC
??0CVdsWmiVariantObjectArrayEnum@@QEAA@XZ equ <__imp_??0CVdsWmiVariantObjectArrayEnum@@QEAA@XZ>

externdef __imp_??1?$CVdsHandleImpl@$0?0@@QEAA@XZ:PPROC
??1?$CVdsHandleImpl@$0?0@@QEAA@XZ equ <__imp_??1?$CVdsHandleImpl@$0?0@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>

externdef __imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PPROC
??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ equ <__imp_??1?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAA@XZ>

externdef __imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ:PPROC
??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ equ <__imp_??1?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAA@XZ>

externdef __imp_??1CPrvEnumObject@@QEAA@XZ:PPROC
??1CPrvEnumObject@@QEAA@XZ equ <__imp_??1CPrvEnumObject@@QEAA@XZ>

externdef __imp_??1CVdsAsyncObjectBase@@QEAA@XZ:PPROC
??1CVdsAsyncObjectBase@@QEAA@XZ equ <__imp_??1CVdsAsyncObjectBase@@QEAA@XZ>

externdef __imp_??1CVdsCallTracer@@QEAA@XZ:PPROC
??1CVdsCallTracer@@QEAA@XZ equ <__imp_??1CVdsCallTracer@@QEAA@XZ>

externdef __imp_??1CVdsCriticalSection@@QEAA@XZ:PPROC
??1CVdsCriticalSection@@QEAA@XZ equ <__imp_??1CVdsCriticalSection@@QEAA@XZ>

externdef __imp_??1CVdsDebugLog@@QEAA@XZ:PPROC
??1CVdsDebugLog@@QEAA@XZ equ <__imp_??1CVdsDebugLog@@QEAA@XZ>

externdef __imp_??1CVdsPnPNotificationBase@@QEAA@XZ:PPROC
??1CVdsPnPNotificationBase@@QEAA@XZ equ <__imp_??1CVdsPnPNotificationBase@@QEAA@XZ>

externdef __imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ:PPROC
??1CVdsStructuredExceptionTranslator@@QEAA@XZ equ <__imp_??1CVdsStructuredExceptionTranslator@@QEAA@XZ>

externdef __imp_??1CVdsUnlockIt@@QEAA@XZ:PPROC
??1CVdsUnlockIt@@QEAA@XZ equ <__imp_??1CVdsUnlockIt@@QEAA@XZ>

externdef __imp_??1CVdsWmiVariantObjectArrayEnum@@QEAA@XZ:PPROC
??1CVdsWmiVariantObjectArrayEnum@@QEAA@XZ equ <__imp_??1CVdsWmiVariantObjectArrayEnum@@QEAA@XZ>

externdef __imp_??4?$CVdsHandleImpl@$0?0@@QEAAPEAXPEAX@Z:PPROC
??4?$CVdsHandleImpl@$0?0@@QEAAPEAXPEAX@Z equ <__imp_??4?$CVdsHandleImpl@$0?0@@QEAAPEAXPEAX@Z>

externdef __imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINT@@PEAU1@@Z:PPROC
??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINT@@PEAU1@@Z equ <__imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINT@@PEAU1@@Z>

externdef __imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINTS@@PEAU1@@Z:PPROC
??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINTS@@PEAU1@@Z equ <__imp_??4?$CVdsHeapPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEAAPEAU_MOUNTMGR_MOUNT_POINTS@@PEAU1@@Z>

externdef __imp_??8?$CVdsHandleImpl@$0?0@@QEBA_NPEAX@Z:PPROC
??8?$CVdsHandleImpl@$0?0@@QEBA_NPEAX@Z equ <__imp_??8?$CVdsHandleImpl@$0?0@@QEBA_NPEAX@Z>

externdef __imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINT@@@Z:PPROC
??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINT@@@Z equ <__imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINT@@@Z>

externdef __imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINTS@@@Z:PPROC
??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINTS@@@Z equ <__imp_??8?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBA_NPEAU_MOUNTMGR_MOUNT_POINTS@@@Z>

externdef __imp_??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ:PPROC
??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ equ <__imp_??B?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ>

externdef __imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ:PPROC
??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ equ <__imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ>

externdef __imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ:PPROC
??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ equ <__imp_??B?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ>

externdef __imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ:PPROC
??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ equ <__imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINT@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINT@@XZ>

externdef __imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ:PPROC
??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ equ <__imp_??C?$CVdsPtr@U_MOUNTMGR_MOUNT_POINTS@@@@QEBAPEAU_MOUNTMGR_MOUNT_POINTS@@XZ>

externdef __imp_??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ:PPROC
??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ equ <__imp_??I?$CVdsHandleImpl@$0?0@@QEAAPEAPEAXXZ>

externdef __imp_??M@YA_NAEBU_GUID@@0@Z:PPROC
??M@YA_NAEBU_GUID@@0@Z equ <__imp_??M@YA_NAEBU_GUID@@0@Z>

externdef __imp_?AddEventSource@@YAKPEAGPEAUHINSTANCE__@@@Z:PPROC
?AddEventSource@@YAKPEAGPEAUHINSTANCE__@@@Z equ <__imp_?AddEventSource@@YAKPEAGPEAUHINSTANCE__@@@Z>

externdef __imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?AllowCancel@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?Append@CPrvEnumObject@@QEAAJPEAUIUnknown@@@Z:PPROC
?Append@CPrvEnumObject@@QEAAJPEAUIUnknown@@@Z equ <__imp_?Append@CPrvEnumObject@@QEAAJPEAUIUnknown@@@Z>

externdef __imp_?AssignTempVolumeName@@YAJPEAGQEAG@Z:PPROC
?AssignTempVolumeName@@YAJPEAGQEAG@Z equ <__imp_?AssignTempVolumeName@@YAJPEAGQEAG@Z>

externdef __imp_?Attach@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAUtagVARIANT@@@Z:PPROC
?Attach@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAUtagVARIANT@@@Z equ <__imp_?Attach@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAUtagVARIANT@@@Z>

externdef __imp_?Cancel@CVdsAsyncObjectBase@@UEAAJXZ:PPROC
?Cancel@CVdsAsyncObjectBase@@UEAAJXZ equ <__imp_?Cancel@CVdsAsyncObjectBase@@UEAAJXZ>

externdef __imp_?Clear@CPrvEnumObject@@QEAAXXZ:PPROC
?Clear@CPrvEnumObject@@QEAAXXZ equ <__imp_?Clear@CPrvEnumObject@@QEAAXXZ>

externdef __imp_?Clone@CPrvEnumObject@@UEAAJPEAPEAUIEnumVdsObject@@@Z:PPROC
?Clone@CPrvEnumObject@@UEAAJPEAPEAUIEnumVdsObject@@@Z equ <__imp_?Clone@CPrvEnumObject@@UEAAJPEAPEAUIEnumVdsObject@@@Z>

externdef __imp_?CoFreeStringArray@@YAXPEAPEAGJ@Z:PPROC
?CoFreeStringArray@@YAXPEAPEAGJ@Z equ <__imp_?CoFreeStringArray@@YAXPEAPEAGJ@Z>

externdef __imp_?CreateDeviceInfoSet@@YAKPEAGPEAPEAXPEAU_SP_DEVINFO_DATA@@@Z:PPROC
?CreateDeviceInfoSet@@YAKPEAGPEAPEAXPEAU_SP_DEVINFO_DATA@@@Z equ <__imp_?CreateDeviceInfoSet@@YAKPEAGPEAPEAXPEAU_SP_DEVINFO_DATA@@@Z>

externdef __imp_?CreateListenThread@CVdsPnPNotificationBase@@AEAAKXZ:PPROC
?CreateListenThread@CVdsPnPNotificationBase@@AEAAKXZ equ <__imp_?CreateListenThread@CVdsPnPNotificationBase@@AEAAKXZ>

externdef __imp_?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ:PPROC
?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ equ <__imp_?Detach@?$CVdsHandleImpl@$0?0@@QEAAPEAXXZ>

externdef __imp_?Detach@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ:PPROC
?Detach@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ equ <__imp_?Detach@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ>

externdef __imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?DisallowCancel@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?GarbageCollectDriveLetters@@YAXXZ:PPROC
?GarbageCollectDriveLetters@@YAXXZ equ <__imp_?GarbageCollectDriveLetters@@YAXXZ>

externdef __imp_?GetDeviceAndMediaType@@YAKPEAXPEAK1@Z:PPROC
?GetDeviceAndMediaType@@YAKPEAXPEAK1@Z equ <__imp_?GetDeviceAndMediaType@@YAKPEAXPEAK1@Z>

externdef __imp_?GetDeviceLocation@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z:PPROC
?GetDeviceLocation@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z equ <__imp_?GetDeviceLocation@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z>

externdef __imp_?GetDeviceName@@YAKPEAXHQEAG@Z:PPROC
?GetDeviceName@@YAKPEAXHQEAG@Z equ <__imp_?GetDeviceName@@YAKPEAXHQEAG@Z>

externdef __imp_?GetDeviceNumber@@YAKPEAXPEAU_STORAGE_DEVICE_NUMBER@@@Z:PPROC
?GetDeviceNumber@@YAKPEAXPEAU_STORAGE_DEVICE_NUMBER@@@Z equ <__imp_?GetDeviceNumber@@YAKPEAXPEAU_STORAGE_DEVICE_NUMBER@@@Z>

externdef __imp_?GetDeviceRegistryProperty@@YAKKKPEAPEAEK@Z:PPROC
?GetDeviceRegistryProperty@@YAKKKPEAPEAEK@Z equ <__imp_?GetDeviceRegistryProperty@@YAKKKPEAPEAEK@Z>

externdef __imp_?GetDeviceRegistryProperty@@YAKPEAXPEAU_SP_DEVINFO_DATA@@KPEAPEAEK@Z:PPROC
?GetDeviceRegistryProperty@@YAKPEAXPEAU_SP_DEVINFO_DATA@@KPEAPEAEK@Z equ <__imp_?GetDeviceRegistryProperty@@YAKPEAXPEAU_SP_DEVINFO_DATA@@KPEAPEAEK@Z>

externdef __imp_?GetDiskLayout@@YAKPEAXPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z:PPROC
?GetDiskLayout@@YAKPEAXPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z equ <__imp_?GetDiskLayout@@YAKPEAXPEAPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z>

externdef __imp_?GetInterfaceDetailData@@YAKPEAXPEAU_SP_DEVICE_INTERFACE_DATA@@PEAPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z:PPROC
?GetInterfaceDetailData@@YAKPEAXPEAU_SP_DEVICE_INTERFACE_DATA@@PEAPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z equ <__imp_?GetInterfaceDetailData@@YAKPEAXPEAU_SP_DEVICE_INTERFACE_DATA@@PEAPEAU_SP_DEVICE_INTERFACE_DETAIL_DATA_W@@@Z>

externdef __imp_?GetIsRemovable@@YAKPEAXPEAH@Z:PPROC
?GetIsRemovable@@YAKPEAXPEAH@Z equ <__imp_?GetIsRemovable@@YAKPEAXPEAH@Z>

externdef __imp_?GetMediaGeometry@@YAKPEAXKPEAU_DISK_GEOMETRY@@@Z:PPROC
?GetMediaGeometry@@YAKPEAXKPEAU_DISK_GEOMETRY@@@Z equ <__imp_?GetMediaGeometry@@YAKPEAXKPEAU_DISK_GEOMETRY@@@Z>

externdef __imp_?GetMediaGeometry@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z:PPROC
?GetMediaGeometry@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z equ <__imp_?GetMediaGeometry@@YAKPEAXPEAU_VDS_DISK_PROP@@@Z>

externdef __imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@XZ:PPROC
?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@XZ equ <__imp_?GetOutputType@CVdsAsyncObjectBase@@QEAA?AW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@XZ>

externdef __imp_?GetPartitionInformation@@YAKPEAXPEAU_PARTITION_INFORMATION_EX@@@Z:PPROC
?GetPartitionInformation@@YAKPEAXPEAU_PARTITION_INFORMATION_EX@@@Z equ <__imp_?GetPartitionInformation@@YAKPEAXPEAU_PARTITION_INFORMATION_EX@@@Z>

externdef __imp_?GetVolumeDiskExtentInfo@@YAKPEAXPEAPEAU_VOLUME_DISK_EXTENTS@@@Z:PPROC
?GetVolumeDiskExtentInfo@@YAKPEAXPEAPEAU_VOLUME_DISK_EXTENTS@@@Z equ <__imp_?GetVolumeDiskExtentInfo@@YAKPEAXPEAPEAU_VOLUME_DISK_EXTENTS@@@Z>

externdef __imp_?GetVolumeName@@YAJPEAG0@Z:PPROC
?GetVolumeName@@YAJPEAG0@Z equ <__imp_?GetVolumeName@@YAJPEAG0@Z>

externdef __imp_?GetVolumeSize@@YAKPEAGPEA_K@Z:PPROC
?GetVolumeSize@@YAKPEAGPEA_K@Z equ <__imp_?GetVolumeSize@@YAKPEAGPEA_K@Z>

externdef __imp_?GetWindowHandle@CVdsPnPNotificationBase@@QEAAPEAUHWND__@@XZ:PPROC
?GetWindowHandle@CVdsPnPNotificationBase@@QEAAPEAUHWND__@@XZ equ <__imp_?GetWindowHandle@CVdsPnPNotificationBase@@QEAAPEAUHWND__@@XZ>

externdef __imp_?HasMatchingNotification@CVdsPnPNotificationBase@@IEAAH_KK@Z:PPROC
?HasMatchingNotification@CVdsPnPNotificationBase@@IEAAH_KK@Z equ <__imp_?HasMatchingNotification@CVdsPnPNotificationBase@@IEAAH_KK@Z>

externdef __imp_?Initialize@CVdsAsyncObjectBase@@SAKXZ:PPROC
?Initialize@CVdsAsyncObjectBase@@SAKXZ equ <__imp_?Initialize@CVdsAsyncObjectBase@@SAKXZ>

externdef __imp_?Initialize@CVdsPnPNotificationBase@@QEAAKXZ:PPROC
?Initialize@CVdsPnPNotificationBase@@QEAAKXZ equ <__imp_?Initialize@CVdsPnPNotificationBase@@QEAAKXZ>

externdef __imp_?InitializeSecurityDescriptor@@YAKKPEAXPEAPEAU_ACL@@PEAPEAX22@Z:PPROC
?InitializeSecurityDescriptor@@YAKKPEAXPEAPEAU_ACL@@PEAPEAX22@Z equ <__imp_?InitializeSecurityDescriptor@@YAKKPEAXPEAPEAU_ACL@@PEAPEAX22@Z>

externdef __imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ:PPROC
?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ equ <__imp_?IsCancelRequested@CVdsAsyncObjectBase@@QEAAHXZ>

externdef __imp_?IsDeviceFullyInstalled@@YAHPEAG@Z:PPROC
?IsDeviceFullyInstalled@@YAHPEAG@Z equ <__imp_?IsDeviceFullyInstalled@@YAHPEAG@Z>

externdef __imp_?IsDiskClustered@@YAHPEAX@Z:PPROC
?IsDiskClustered@@YAHPEAX@Z equ <__imp_?IsDiskClustered@@YAHPEAX@Z>

externdef __imp_?IsFinished@CVdsAsyncObjectBase@@QEAAHXZ:PPROC
?IsFinished@CVdsAsyncObjectBase@@QEAAHXZ equ <__imp_?IsFinished@CVdsAsyncObjectBase@@QEAAHXZ>

externdef __imp_?IsLocalComputer@@YAJPEAG@Z:PPROC
?IsLocalComputer@@YAJPEAG@Z equ <__imp_?IsLocalComputer@@YAJPEAG@Z>

externdef __imp_?IsMediaPresent@@YAHPEAX@Z:PPROC
?IsMediaPresent@@YAHPEAX@Z equ <__imp_?IsMediaPresent@@YAHPEAX@Z>

externdef __imp_?IsNoAutoMount@@YAHXZ:PPROC
?IsNoAutoMount@@YAHXZ equ <__imp_?IsNoAutoMount@@YAHXZ>

externdef __imp_?IsWinPE@@YAHXZ:PPROC
?IsWinPE@@YAHXZ equ <__imp_?IsWinPE@@YAHXZ>

externdef __imp_?LockDismountVolume@@YAKPEAXH@Z:PPROC
?LockDismountVolume@@YAKPEAXH@Z equ <__imp_?LockDismountVolume@@YAKPEAXH@Z>

externdef __imp_?LockVolume@@YAKPEAX@Z:PPROC
?LockVolume@@YAKPEAX@Z equ <__imp_?LockVolume@@YAKPEAX@Z>

externdef __imp_?Log@CVdsDebugLog@@QEAAXKKHPEAD0@Z:PPROC
?Log@CVdsDebugLog@@QEAAXKKHPEAD0@Z equ <__imp_?Log@CVdsDebugLog@@QEAAXKKHPEAD0@Z>

externdef __imp_?Log@CVdsDebugLog@@QEAAXKKHPEADZZ:PPROC
?Log@CVdsDebugLog@@QEAAXKKHPEADZZ equ <__imp_?Log@CVdsDebugLog@@QEAAXKKHPEADZZ>

externdef __imp_?LogError@@YAXPEAGKKPEAXKK0PEAD@Z:PPROC
?LogError@@YAXPEAGKKPEAXKK0PEAD@Z equ <__imp_?LogError@@YAXPEAGKKPEAXKK0PEAD@Z>

externdef __imp_?LogEvent@@YAXPEAGKGKPEAXKQEAPEAG@Z:PPROC
?LogEvent@@YAXPEAGKGKPEAXKQEAPEAG@Z equ <__imp_?LogEvent@@YAXPEAGKGKPEAXKQEAPEAG@Z>

externdef __imp_?LogInfo@@YAXPEAGKKPEAXK0PEAD@Z:PPROC
?LogInfo@@YAXPEAGKKPEAXK0PEAD@Z equ <__imp_?LogInfo@@YAXPEAGKKPEAXK0PEAD@Z>

externdef __imp_?LogWarning@@YAXPEAGKKPEAXKK0PEAD@Z:PPROC
?LogWarning@@YAXPEAGKKPEAXKK0PEAD@Z equ <__imp_?LogWarning@@YAXPEAGKKPEAXKK0PEAD@Z>

externdef __imp_?MountVolume@@YAKPEAG@Z:PPROC
?MountVolume@@YAKPEAG@Z equ <__imp_?MountVolume@@YAKPEAG@Z>

externdef __imp_?Next@CPrvEnumObject@@UEAAJKPEAPEAUIUnknown@@PEAK@Z:PPROC
?Next@CPrvEnumObject@@UEAAJKPEAPEAUIUnknown@@PEAK@Z equ <__imp_?Next@CPrvEnumObject@@UEAAJKPEAPEAUIUnknown@@PEAK@Z>

externdef __imp_?Next@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAPEAUIWbemClassObject@@@Z:PPROC
?Next@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAPEAUIWbemClassObject@@@Z equ <__imp_?Next@CVdsWmiVariantObjectArrayEnum@@QEAAJPEAPEAUIWbemClassObject@@@Z>

externdef __imp_?NotificationThread@CVdsPnPNotificationBase@@AEAAKPEAX@Z:PPROC
?NotificationThread@CVdsPnPNotificationBase@@AEAAKPEAX@Z equ <__imp_?NotificationThread@CVdsPnPNotificationBase@@AEAAKPEAX@Z>

externdef __imp_?NotificationThreadEntry@CVdsPnPNotificationBase@@CAKPEAX@Z:PPROC
?NotificationThreadEntry@CVdsPnPNotificationBase@@CAKPEAX@Z equ <__imp_?NotificationThreadEntry@CVdsPnPNotificationBase@@CAKPEAX@Z>

externdef __imp_?OpenDevice@@YAKPEAGKPEAPEAX@Z:PPROC
?OpenDevice@@YAKPEAGKPEAPEAX@Z equ <__imp_?OpenDevice@@YAKPEAGKPEAPEAX@Z>

externdef __imp_?QueryObjects@@YAJPEAUIUnknown@@PEAPEAUIEnumVdsObject@@AEAU_RTL_CRITICAL_SECTION@@@Z:PPROC
?QueryObjects@@YAJPEAUIUnknown@@PEAPEAUIEnumVdsObject@@AEAU_RTL_CRITICAL_SECTION@@@Z equ <__imp_?QueryObjects@@YAJPEAUIUnknown@@PEAPEAUIEnumVdsObject@@AEAU_RTL_CRITICAL_SECTION@@@Z>

externdef __imp_?QueryStatus@CVdsAsyncObjectBase@@UEAAJPEAJPEAK@Z:PPROC
?QueryStatus@CVdsAsyncObjectBase@@UEAAJPEAJPEAK@Z equ <__imp_?QueryStatus@CVdsAsyncObjectBase@@UEAAJPEAJPEAK@Z>

externdef __imp_?Register@CVdsPnPNotificationBase@@QEAAKPEAU_NotificationListeningRequest@@K@Z:PPROC
?Register@CVdsPnPNotificationBase@@QEAAKPEAU_NotificationListeningRequest@@K@Z equ <__imp_?Register@CVdsPnPNotificationBase@@QEAAKPEAU_NotificationListeningRequest@@K@Z>

externdef __imp_?RegisterHandle@CVdsPnPNotificationBase@@QEAAKPEAXPEAPEAX@Z:PPROC
?RegisterHandle@CVdsPnPNotificationBase@@QEAAKPEAXPEAPEAX@Z equ <__imp_?RegisterHandle@CVdsPnPNotificationBase@@QEAAKPEAXPEAPEAX@Z>

externdef __imp_?RegisterProvider@@YAJU_GUID@@0PEAGW4_VDS_PROVIDER_TYPE@@110@Z:PPROC
?RegisterProvider@@YAJU_GUID@@0PEAGW4_VDS_PROVIDER_TYPE@@110@Z equ <__imp_?RegisterProvider@@YAJU_GUID@@0PEAGW4_VDS_PROVIDER_TYPE@@110@Z>

externdef __imp_?RemoveEventSource@@YAKPEAG@Z:PPROC
?RemoveEventSource@@YAKPEAG@Z equ <__imp_?RemoveEventSource@@YAKPEAG@Z>

externdef __imp_?RemoveTempVolumeName@@YAXPEAG0@Z:PPROC
?RemoveTempVolumeName@@YAXPEAG0@Z equ <__imp_?RemoveTempVolumeName@@YAXPEAG0@Z>

externdef __imp_?Reset@CPrvEnumObject@@UEAAJXZ:PPROC
?Reset@CPrvEnumObject@@UEAAJXZ equ <__imp_?Reset@CPrvEnumObject@@UEAAJXZ>

externdef __imp_?Reset@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ:PPROC
?Reset@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ equ <__imp_?Reset@CVdsWmiVariantObjectArrayEnum@@QEAAJXZ>

externdef __imp_?SetCompletionStatus@CVdsAsyncObjectBase@@QEAAXJK@Z:PPROC
?SetCompletionStatus@CVdsAsyncObjectBase@@QEAAXJK@Z equ <__imp_?SetCompletionStatus@CVdsAsyncObjectBase@@QEAAXJK@Z>

externdef __imp_?SetDiskLayout@@YAKPEAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z:PPROC
?SetDiskLayout@@YAKPEAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z equ <__imp_?SetDiskLayout@@YAKPEAXPEAU_DRIVE_LAYOUT_INFORMATION_EX@@@Z>

externdef __imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@@Z:PPROC
?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@@Z equ <__imp_?SetOutputType@CVdsAsyncObjectBase@@QEAAXW4__MIDL___MIDL_itf_vdscmlyr_0000_0002@@@Z>

externdef __imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ:PPROC
?SetPositionToLast@CPrvEnumObject@@QEAAXXZ equ <__imp_?SetPositionToLast@CPrvEnumObject@@QEAAXXZ>

externdef __imp_?Signal@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?Signal@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?Signal@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_?Skip@CPrvEnumObject@@UEAAJK@Z:PPROC
?Skip@CPrvEnumObject@@UEAAJK@Z equ <__imp_?Skip@CPrvEnumObject@@UEAAJK@Z>

externdef __imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ:PPROC
?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ equ <__imp_?TracingLogEnabled@CVdsDebugLog@@QEAAHXZ>

externdef __imp_?Uninitialize@CVdsAsyncObjectBase@@SAXXZ:PPROC
?Uninitialize@CVdsAsyncObjectBase@@SAXXZ equ <__imp_?Uninitialize@CVdsAsyncObjectBase@@SAXXZ>

externdef __imp_?Uninitialize@CVdsPnPNotificationBase@@QEAAXXZ:PPROC
?Uninitialize@CVdsPnPNotificationBase@@QEAAXXZ equ <__imp_?Uninitialize@CVdsPnPNotificationBase@@QEAAXXZ>

externdef __imp_?Unregister@CVdsPnPNotificationBase@@QEAAXPEAU_NotificationListeningRequest@@@Z:PPROC
?Unregister@CVdsPnPNotificationBase@@QEAAXPEAU_NotificationListeningRequest@@@Z equ <__imp_?Unregister@CVdsPnPNotificationBase@@QEAAXPEAU_NotificationListeningRequest@@@Z>

externdef __imp_?UnregisterHandle@CVdsPnPNotificationBase@@QEAAXPEAX@Z:PPROC
?UnregisterHandle@CVdsPnPNotificationBase@@QEAAXPEAX@Z equ <__imp_?UnregisterHandle@CVdsPnPNotificationBase@@QEAAXPEAX@Z>

externdef __imp_?UnregisterProvider@@YAJU_GUID@@@Z:PPROC
?UnregisterProvider@@YAJU_GUID@@@Z equ <__imp_?UnregisterProvider@@YAJU_GUID@@@Z>

externdef __imp_?VdsAllocateEmptyString@@YAPEAGXZ:PPROC
?VdsAllocateEmptyString@@YAPEAGXZ equ <__imp_?VdsAllocateEmptyString@@YAPEAGXZ>

externdef __imp_?VdsHeapAlloc@@YAPEAXPEAXK_K@Z:PPROC
?VdsHeapAlloc@@YAPEAXPEAXK_K@Z equ <__imp_?VdsHeapAlloc@@YAPEAXPEAXK_K@Z>

externdef __imp_?VdsHeapFree@@YAHPEAXK0@Z:PPROC
?VdsHeapFree@@YAHPEAXK0@Z equ <__imp_?VdsHeapFree@@YAHPEAXK0@Z>

externdef __imp_?VdsInitializeCriticalSection@@YAKPEAU_RTL_CRITICAL_SECTION@@@Z:PPROC
?VdsInitializeCriticalSection@@YAKPEAU_RTL_CRITICAL_SECTION@@@Z equ <__imp_?VdsInitializeCriticalSection@@YAKPEAU_RTL_CRITICAL_SECTION@@@Z>

externdef __imp_?VdsIscsiCacheSessionDevices@@YAJPEAUIEnumWbemClassObject@@PEAPEAU_VDSISCSI_SESSION_DEVICES_CACHE@@@Z:PPROC
?VdsIscsiCacheSessionDevices@@YAJPEAUIEnumWbemClassObject@@PEAPEAU_VDSISCSI_SESSION_DEVICES_CACHE@@@Z equ <__imp_?VdsIscsiCacheSessionDevices@@YAJPEAUIEnumWbemClassObject@@PEAPEAU_VDSISCSI_SESSION_DEVICES_CACHE@@@Z>

externdef __imp_?VdsIscsiCheckEqualIpAddress@@YAHU_VDS_IPADDRESS@@0@Z:PPROC
?VdsIscsiCheckEqualIpAddress@@YAHU_VDS_IPADDRESS@@0@Z equ <__imp_?VdsIscsiCheckEqualIpAddress@@YAHU_VDS_IPADDRESS@@0@Z>

externdef __imp_?VdsIscsiGetIpAddressFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z:PPROC
?VdsIscsiGetIpAddressFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z equ <__imp_?VdsIscsiGetIpAddressFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z>

externdef __imp_?VdsIscsiIpAddressToIpsecId@@YAJPEAU_VDS_IPADDRESS@@PEAEPEAKPEAPEAE@Z:PPROC
?VdsIscsiIpAddressToIpsecId@@YAJPEAU_VDS_IPADDRESS@@PEAEPEAKPEAPEAE@Z equ <__imp_?VdsIscsiIpAddressToIpsecId@@YAJPEAU_VDS_IPADDRESS@@PEAEPEAKPEAPEAE@Z>

externdef __imp_?VdsIscsiIpAddressToString@@YAJPEAU_VDS_IPADDRESS@@KPEAG@Z:PPROC
?VdsIscsiIpAddressToString@@YAJPEAU_VDS_IPADDRESS@@KPEAG@Z equ <__imp_?VdsIscsiIpAddressToString@@YAJPEAU_VDS_IPADDRESS@@KPEAG@Z>

externdef __imp_?VdsIscsiIpsecIdToIpAddress@@YAJEKPEAEPEAU_VDS_IPADDRESS@@@Z:PPROC
?VdsIscsiIpsecIdToIpAddress@@YAJEKPEAEPEAU_VDS_IPADDRESS@@@Z equ <__imp_?VdsIscsiIpsecIdToIpAddress@@YAJEKPEAEPEAU_VDS_IPADDRESS@@@Z>

externdef __imp_?VdsIscsiIsIscsiLun@@YAJPEAUIWbemClassObject@@PEAU_VDSISCSI_SESSION_DEVICES_CACHE@@PEAH@Z:PPROC
?VdsIscsiIsIscsiLun@@YAJPEAUIWbemClassObject@@PEAU_VDSISCSI_SESSION_DEVICES_CACHE@@PEAH@Z equ <__imp_?VdsIscsiIsIscsiLun@@YAJPEAUIWbemClassObject@@PEAU_VDSISCSI_SESSION_DEVICES_CACHE@@PEAH@Z>

externdef __imp_?VdsIscsiSetIpAddressInInstance@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z:PPROC
?VdsIscsiSetIpAddressInInstance@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z equ <__imp_?VdsIscsiSetIpAddressInInstance@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAGPEAU_VDS_IPADDRESS@@@Z>

externdef __imp_?VdsSeTranslator@CVdsStructuredExceptionTranslator@@SAXIPEAU_EXCEPTION_POINTERS@@@Z:PPROC
?VdsSeTranslator@CVdsStructuredExceptionTranslator@@SAXIPEAU_EXCEPTION_POINTERS@@@Z equ <__imp_?VdsSeTranslator@CVdsStructuredExceptionTranslator@@SAXIPEAU_EXCEPTION_POINTERS@@@Z>

externdef __imp_?VdsTrace@@YAXKPEADZZ:PPROC
?VdsTrace@@YAXKPEADZZ equ <__imp_?VdsTrace@@YAXKPEADZZ>

externdef __imp_?VdsTraceEx@@YAXKKPEADZZ:PPROC
?VdsTraceEx@@YAXKKPEADZZ equ <__imp_?VdsTraceEx@@YAXKKPEADZZ>

externdef __imp_?VdsTraceExHelper@@YAXKKPEAD0@Z:PPROC
?VdsTraceExHelper@@YAXKKPEAD0@Z equ <__imp_?VdsTraceExHelper@@YAXKKPEAD0@Z>

externdef __imp_?VdsTraceExW@@YAXKKPEAGZZ:PPROC
?VdsTraceExW@@YAXKKPEAGZZ equ <__imp_?VdsTraceExW@@YAXKKPEAGZZ>

externdef __imp_?VdsTraceExWHelper@@YAXKKPEAGPEAD@Z:PPROC
?VdsTraceExWHelper@@YAXKKPEAGPEAD@Z equ <__imp_?VdsTraceExWHelper@@YAXKKPEAGPEAD@Z>

externdef __imp_?VdsTraceW@@YAXKPEAGZZ:PPROC
?VdsTraceW@@YAXKPEAGZZ equ <__imp_?VdsTraceW@@YAXKPEAGZZ>

externdef __imp_?VdsWmiCallMethod@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAG1PEAPEAU2@@Z:PPROC
?VdsWmiCallMethod@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAG1PEAPEAU2@@Z equ <__imp_?VdsWmiCallMethod@@YAJPEAUIWbemServices@@PEAUIWbemClassObject@@PEAG1PEAPEAU2@@Z>

externdef __imp_?VdsWmiConnectToNamespace@@YAJPEAGPEAPEAUIWbemLocator@@PEAPEAUIWbemServices@@@Z:PPROC
?VdsWmiConnectToNamespace@@YAJPEAGPEAPEAUIWbemLocator@@PEAPEAUIWbemServices@@@Z equ <__imp_?VdsWmiConnectToNamespace@@YAJPEAGPEAPEAUIWbemLocator@@PEAPEAUIWbemServices@@@Z>

externdef __imp_?VdsWmiCopyFromVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z:PPROC
?VdsWmiCopyFromVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z equ <__imp_?VdsWmiCopyFromVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z>

externdef __imp_?VdsWmiCopyToVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z:PPROC
?VdsWmiCopyToVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z equ <__imp_?VdsWmiCopyToVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z>

externdef __imp_?VdsWmiCreateClassInstance@@YAJPEAUIWbemServices@@PEAGPEAPEAUIWbemClassObject@@@Z:PPROC
?VdsWmiCreateClassInstance@@YAJPEAUIWbemServices@@PEAGPEAPEAUIWbemClassObject@@@Z equ <__imp_?VdsWmiCreateClassInstance@@YAJPEAUIWbemServices@@PEAGPEAPEAUIWbemClassObject@@@Z>

externdef __imp_?VdsWmiCreateVariantArray@@YAJGJPEAUtagVARIANT@@@Z:PPROC
?VdsWmiCreateVariantArray@@YAJGJPEAUtagVARIANT@@@Z equ <__imp_?VdsWmiCreateVariantArray@@YAJGJPEAUtagVARIANT@@@Z>

externdef __imp_?VdsWmiFindInstanceOfClass@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z:PPROC
?VdsWmiFindInstanceOfClass@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z equ <__imp_?VdsWmiFindInstanceOfClass@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z>

externdef __imp_?VdsWmiGetBoolFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAH@Z:PPROC
?VdsWmiGetBoolFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAH@Z equ <__imp_?VdsWmiGetBoolFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAH@Z>

externdef __imp_?VdsWmiGetByteFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAE@Z:PPROC
?VdsWmiGetByteFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAE@Z equ <__imp_?VdsWmiGetByteFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAE@Z>

externdef __imp_?VdsWmiGetByteInVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z:PPROC
?VdsWmiGetByteInVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z equ <__imp_?VdsWmiGetByteInVariantByteArray@@YAJPEAUIWbemClassObject@@PEAGJPEAE@Z>

externdef __imp_?VdsWmiGetMethodArgumentObject@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z:PPROC
?VdsWmiGetMethodArgumentObject@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z equ <__imp_?VdsWmiGetMethodArgumentObject@@YAJPEAUIWbemServices@@PEAG1PEAPEAUIWbemClassObject@@@Z>

externdef __imp_?VdsWmiGetObjectFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAPEAU1@@Z:PPROC
?VdsWmiGetObjectFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAPEAU1@@Z equ <__imp_?VdsWmiGetObjectFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAPEAU1@@Z>

externdef __imp_?VdsWmiGetObjectInVariantObjectArray@@YAJPEAUIWbemClassObject@@PEAGJPEAPEAU1@@Z:PPROC
?VdsWmiGetObjectInVariantObjectArray@@YAJPEAUIWbemClassObject@@PEAGJPEAPEAU1@@Z equ <__imp_?VdsWmiGetObjectInVariantObjectArray@@YAJPEAUIWbemClassObject@@PEAGJPEAPEAU1@@Z>

externdef __imp_?VdsWmiGetUlongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAK@Z:PPROC
?VdsWmiGetUlongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAK@Z equ <__imp_?VdsWmiGetUlongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEAK@Z>

externdef __imp_?VdsWmiGetUlonglongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEA_K@Z:PPROC
?VdsWmiGetUlonglongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEA_K@Z equ <__imp_?VdsWmiGetUlonglongFromInstance@@YAJPEAUIWbemClassObject@@PEAGPEA_K@Z>

externdef __imp_?VdsWmiSetBoolInInstance@@YAJPEAUIWbemClassObject@@PEAGH@Z:PPROC
?VdsWmiSetBoolInInstance@@YAJPEAUIWbemClassObject@@PEAGH@Z equ <__imp_?VdsWmiSetBoolInInstance@@YAJPEAUIWbemClassObject@@PEAGH@Z>

externdef __imp_?VdsWmiSetByteInInstance@@YAJPEAUIWbemClassObject@@PEAGE@Z:PPROC
?VdsWmiSetByteInInstance@@YAJPEAUIWbemClassObject@@PEAGE@Z equ <__imp_?VdsWmiSetByteInInstance@@YAJPEAUIWbemClassObject@@PEAGE@Z>

externdef __imp_?VdsWmiSetObjectInInstance@@YAJPEAUIWbemClassObject@@PEAG0@Z:PPROC
?VdsWmiSetObjectInInstance@@YAJPEAUIWbemClassObject@@PEAG0@Z equ <__imp_?VdsWmiSetObjectInInstance@@YAJPEAUIWbemClassObject@@PEAG0@Z>

externdef __imp_?VdsWmiSetStringInInstance@@YAJPEAUIWbemClassObject@@PEAG1@Z:PPROC
?VdsWmiSetStringInInstance@@YAJPEAUIWbemClassObject@@PEAG1@Z equ <__imp_?VdsWmiSetStringInInstance@@YAJPEAUIWbemClassObject@@PEAG1@Z>

externdef __imp_?VdsWmiSetUlongInInstance@@YAJPEAUIWbemClassObject@@PEAGK@Z:PPROC
?VdsWmiSetUlongInInstance@@YAJPEAUIWbemClassObject@@PEAGK@Z equ <__imp_?VdsWmiSetUlongInInstance@@YAJPEAUIWbemClassObject@@PEAGK@Z>

externdef __imp_?VdsWmiSetUlonglongInInstance@@YAJPEAUIWbemClassObject@@PEAG_K@Z:PPROC
?VdsWmiSetUlonglongInInstance@@YAJPEAUIWbemClassObject@@PEAG_K@Z equ <__imp_?VdsWmiSetUlonglongInInstance@@YAJPEAUIWbemClassObject@@PEAG_K@Z>

externdef __imp_?WaitImpl@CVdsAsyncObjectBase@@QEAAJPEAJ@Z:PPROC
?WaitImpl@CVdsAsyncObjectBase@@QEAAJPEAJ@Z equ <__imp_?WaitImpl@CVdsAsyncObjectBase@@QEAAJPEAJ@Z>

externdef __imp_?WindowProcEntry@CVdsPnPNotificationBase@@CA_JPEAUHWND__@@I_K_J@Z:PPROC
?WindowProcEntry@CVdsPnPNotificationBase@@CA_JPEAUHWND__@@I_K_J@Z equ <__imp_?WindowProcEntry@CVdsPnPNotificationBase@@CA_JPEAUHWND__@@I_K_J@Z>

externdef __imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ:PPROC
?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ equ <__imp_?ZeroAsyncOut@CVdsAsyncObjectBase@@QEAAXXZ>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_RegisterVdsFabric:PPROC
RegisterVdsFabric equ <__imp_RegisterVdsFabric>

externdef __imp_UnregisterVdsFabric:PPROC
UnregisterVdsFabric equ <__imp_UnregisterVdsFabric>
