externdef __imp_??0CVssJetWriter@@QEAA@XZ:PPROC
??0CVssJetWriter@@QEAA@XZ equ <__imp_??0CVssJetWriter@@QEAA@XZ>

externdef __imp_??0CVssWriter@@QEAA@XZ:PPROC
??0CVssWriter@@QEAA@XZ equ <__imp_??0CVssWriter@@QEAA@XZ>

externdef __imp_??1CVssJetWriter@@UEAA@XZ:PPROC
??1CVssJetWriter@@UEAA@XZ equ <__imp_??1CVssJetWriter@@UEAA@XZ>

externdef __imp_??1CVssWriter@@UEAA@XZ:PPROC
??1CVssWriter@@UEAA@XZ equ <__imp_??1CVssWriter@@UEAA@XZ>

externdef __imp_?AreComponentsSelected@CVssWriter@@IEBA_NXZ:PPROC
?AreComponentsSelected@CVssWriter@@IEBA_NXZ equ <__imp_?AreComponentsSelected@CVssWriter@@IEBA_NXZ>

externdef __imp_?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z:PPROC
?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z equ <__imp_?CreateVssBackupComponents@@YAJPEAPEAVIVssBackupComponents@@@Z>

externdef __imp_?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z:PPROC
?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z equ <__imp_?CreateVssExamineWriterMetadata@@YAJPEAGPEAPEAVIVssExamineWriterMetadata@@@Z>

externdef __imp_?CreateVssSnapshotSetDescription@@YAJU_GUID@@JPEAPEAVIVssSnapshotSetDescription@@@Z:PPROC
?CreateVssSnapshotSetDescription@@YAJU_GUID@@JPEAPEAVIVssSnapshotSetDescription@@@Z equ <__imp_?CreateVssSnapshotSetDescription@@YAJU_GUID@@JPEAPEAVIVssSnapshotSetDescription@@@Z>

externdef __imp_?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ:PPROC
?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ equ <__imp_?GetBackupType@CVssWriter@@IEBA?AW4_VSS_BACKUP_TYPE@@XZ>

externdef __imp_?GetContext@CVssWriter@@IEBAJXZ:PPROC
?GetContext@CVssWriter@@IEBAJXZ equ <__imp_?GetContext@CVssWriter@@IEBAJXZ>

externdef __imp_?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ:PPROC
?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ equ <__imp_?GetCurrentLevel@CVssWriter@@IEBA?AW4_VSS_APPLICATION_LEVEL@@XZ>

externdef __imp_?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ:PPROC
?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ equ <__imp_?GetCurrentSnapshotSetId@CVssWriter@@IEBA?AU_GUID@@XZ>

externdef __imp_?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ:PPROC
?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ equ <__imp_?GetCurrentVolumeArray@CVssWriter@@IEBAPEAPEBGXZ>

externdef __imp_?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ:PPROC
?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ equ <__imp_?GetCurrentVolumeCount@CVssWriter@@IEBAIXZ>

externdef __imp_?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ:PPROC
?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ equ <__imp_?GetRestoreType@CVssWriter@@IEBA?AW4_VSS_RESTORE_TYPE@@XZ>

externdef __imp_?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z:PPROC
?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z equ <__imp_?GetSnapshotDeviceName@CVssWriter@@IEBAJPEBGPEAPEBG@Z>

externdef __imp_?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211@Z:PPROC
?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211@Z equ <__imp_?Initialize@CVssJetWriter@@QEAAJU_GUID@@PEBG_N211@Z>

externdef __imp_?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z:PPROC
?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z equ <__imp_?Initialize@CVssWriter@@QEAAJU_GUID@@PEBGW4VSS_USAGE_TYPE@@W4VSS_SOURCE_TYPE@@W4_VSS_APPLICATION_LEVEL@@KW4VSS_ALTERNATE_WRITER_STATE@@_N1@Z>

externdef __imp_?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z:PPROC
?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z equ <__imp_?InstallAlternateWriter@CVssWriter@@QEAAJU_GUID@@0@Z>

externdef __imp_?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ:PPROC
?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ equ <__imp_?IsBootableSystemStateBackedUp@CVssWriter@@IEBA_NXZ>

externdef __imp_?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ:PPROC
?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ equ <__imp_?IsPartialFileSupportEnabled@CVssWriter@@IEBA_NXZ>

externdef __imp_?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z:PPROC
?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z equ <__imp_?IsPathAffected@CVssWriter@@IEBA_NPEBG@Z>

externdef __imp_?LoadVssSnapshotSetDescription@@YAJPEBGPEAPEAVIVssSnapshotSetDescription@@U_GUID@@@Z:PPROC
?LoadVssSnapshotSetDescription@@YAJPEBGPEAPEAVIVssSnapshotSetDescription@@U_GUID@@@Z equ <__imp_?LoadVssSnapshotSetDescription@@YAJPEBGPEAPEAVIVssSnapshotSetDescription@@U_GUID@@@Z>

externdef __imp_?OnAbortBegin@CVssJetWriter@@UEAAXXZ:PPROC
?OnAbortBegin@CVssJetWriter@@UEAAXXZ equ <__imp_?OnAbortBegin@CVssJetWriter@@UEAAXXZ>

externdef __imp_?OnAbortEnd@CVssJetWriter@@UEAAXXZ:PPROC
?OnAbortEnd@CVssJetWriter@@UEAAXXZ equ <__imp_?OnAbortEnd@CVssJetWriter@@UEAAXXZ>

externdef __imp_?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z:PPROC
?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z equ <__imp_?OnBackOffIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z>

externdef __imp_?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnBackupComplete@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnBackupCompleteBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PPROC
?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z equ <__imp_?OnBackupCompleteEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>

externdef __imp_?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z:PPROC
?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z equ <__imp_?OnBackupShutdown@CVssWriter@@UEAA_NU_GUID@@@Z>

externdef __imp_?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z:PPROC
?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z equ <__imp_?OnContinueIOOnVolume@CVssWriter@@UEAA_NPEAGU_GUID@@1@Z>

externdef __imp_?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ:PPROC
?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ equ <__imp_?OnFreezeBegin@CVssJetWriter@@UEAA_NXZ>

externdef __imp_?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z:PPROC
?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z equ <__imp_?OnFreezeEnd@CVssJetWriter@@UEAA_N_N@Z>

externdef __imp_?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z:PPROC
?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z equ <__imp_?OnIdentify@CVssJetWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z>

externdef __imp_?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z:PPROC
?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z equ <__imp_?OnIdentify@CVssWriter@@UEAA_NPEAVIVssCreateWriterMetadata@@@Z>

externdef __imp_?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPostRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPostRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PPROC
?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z equ <__imp_?OnPostRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>

externdef __imp_?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPostSnapshot@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPostSnapshot@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPreRestore@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPreRestoreBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PPROC
?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z equ <__imp_?OnPreRestoreEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>

externdef __imp_?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPrepareBackup@CVssWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z:PPROC
?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z equ <__imp_?OnPrepareBackupBegin@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@@Z>

externdef __imp_?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z:PPROC
?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z equ <__imp_?OnPrepareBackupEnd@CVssJetWriter@@UEAA_NPEAVIVssWriterComponents@@_N@Z>

externdef __imp_?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ:PPROC
?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ equ <__imp_?OnPrepareSnapshotBegin@CVssJetWriter@@UEAA_NXZ>

externdef __imp_?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z:PPROC
?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z equ <__imp_?OnPrepareSnapshotEnd@CVssJetWriter@@UEAA_N_N@Z>

externdef __imp_?OnThawBegin@CVssJetWriter@@UEAA_NXZ:PPROC
?OnThawBegin@CVssJetWriter@@UEAA_NXZ equ <__imp_?OnThawBegin@CVssJetWriter@@UEAA_NXZ>

externdef __imp_?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z:PPROC
?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z equ <__imp_?OnThawEnd@CVssJetWriter@@UEAA_N_N@Z>

externdef __imp_?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ:PPROC
?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ equ <__imp_?OnVSSApplicationStartup@CVssWriter@@UEAA_NXZ>

externdef __imp_?OnVSSShutdown@CVssWriter@@UEAA_NXZ:PPROC
?OnVSSShutdown@CVssWriter@@UEAA_NXZ equ <__imp_?OnVSSShutdown@CVssWriter@@UEAA_NXZ>

externdef __imp_?SetWriterFailure@CVssWriter@@IEAAJJ@Z:PPROC
?SetWriterFailure@CVssWriter@@IEAAJJ@Z equ <__imp_?SetWriterFailure@CVssWriter@@IEAAJJ@Z>

externdef __imp_?Subscribe@CVssWriter@@QEAAJK@Z:PPROC
?Subscribe@CVssWriter@@QEAAJK@Z equ <__imp_?Subscribe@CVssWriter@@QEAAJK@Z>

externdef __imp_?Uninitialize@CVssJetWriter@@QEAAXXZ:PPROC
?Uninitialize@CVssJetWriter@@QEAAXXZ equ <__imp_?Uninitialize@CVssJetWriter@@QEAAXXZ>

externdef __imp_?Unsubscribe@CVssWriter@@QEAAJXZ:PPROC
?Unsubscribe@CVssWriter@@QEAAJXZ equ <__imp_?Unsubscribe@CVssWriter@@QEAAJXZ>

externdef __imp_IsVolumeSnapshotted:PPROC
IsVolumeSnapshotted equ <__imp_IsVolumeSnapshotted>

externdef __imp_ShouldBlockRevert:PPROC
ShouldBlockRevert equ <__imp_ShouldBlockRevert>

externdef __imp_SimulateSnapshotFreeze:PPROC
SimulateSnapshotFreeze equ <__imp_SimulateSnapshotFreeze>

externdef __imp_SimulateSnapshotThaw:PPROC
SimulateSnapshotThaw equ <__imp_SimulateSnapshotThaw>

externdef __imp_VssFreeSnapshotProperties:PPROC
VssFreeSnapshotProperties equ <__imp_VssFreeSnapshotProperties>
