externdef __imp_??0BUFFER@@QEAA@I@Z:PPROC
??0BUFFER@@QEAA@I@Z equ <__imp_??0BUFFER@@QEAA@I@Z>

externdef __imp_??0BUFFER_CHAIN@@QEAA@XZ:PPROC
??0BUFFER_CHAIN@@QEAA@XZ equ <__imp_??0BUFFER_CHAIN@@QEAA@XZ>

externdef __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PPROC
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z equ <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>

externdef __imp_??1BUFFER@@QEAA@XZ:PPROC
??1BUFFER@@QEAA@XZ equ <__imp_??1BUFFER@@QEAA@XZ>

externdef __imp_??1BUFFER_CHAIN@@QEAA@XZ:PPROC
??1BUFFER_CHAIN@@QEAA@XZ equ <__imp_??1BUFFER_CHAIN@@QEAA@XZ>

externdef __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PPROC
??1BUFFER_CHAIN_ITEM@@QEAA@XZ equ <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>

externdef __imp_??_FBUFFER@@QEAAXXZ:PPROC
??_FBUFFER@@QEAAXXZ equ <__imp_??_FBUFFER@@QEAAXXZ>

externdef __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PPROC
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ equ <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>

externdef __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PPROC
?QueryPtr@BUFFER@@QEBAPEAXXZ equ <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>

externdef __imp_?QuerySize@BUFFER@@QEBAIXZ:PPROC
?QuerySize@BUFFER@@QEBAIXZ equ <__imp_?QuerySize@BUFFER@@QEBAIXZ>

externdef __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PPROC
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ equ <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>

externdef __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PPROC
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z equ <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>

externdef __imp_CloseFindContext:PPROC
CloseFindContext equ <__imp_CloseFindContext>

externdef __imp_FindFirstImportDS:PPROC
FindFirstImportDS equ <__imp_FindFirstImportDS>

externdef __imp_FindImportDSByDeviceName:PPROC
FindImportDSByDeviceName equ <__imp_FindImportDSByDeviceName>

externdef __imp_FindNextImportDS:PPROC
FindNextImportDS equ <__imp_FindNextImportDS>

externdef __imp_GetLoaderStatus:PPROC
GetLoaderStatus equ <__imp_GetLoaderStatus>

externdef __imp_LoadImportDS:PPROC
LoadImportDS equ <__imp_LoadImportDS>

externdef __imp_UnloadImportDS:PPROC
UnloadImportDS equ <__imp_UnloadImportDS>
