externdef __imp_??0BUFFER@@QEAA@I@Z:PPROC
??0BUFFER@@QEAA@I@Z equ <__imp_??0BUFFER@@QEAA@I@Z>

externdef __imp_??0BUFFER_CHAIN@@QEAA@XZ:PPROC
??0BUFFER_CHAIN@@QEAA@XZ equ <__imp_??0BUFFER_CHAIN@@QEAA@XZ>

externdef __imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z:PPROC
??0BUFFER_CHAIN_ITEM@@QEAA@I@Z equ <__imp_??0BUFFER_CHAIN_ITEM@@QEAA@I@Z>

externdef __imp_??1BUFFER@@QEAA@XZ:PPROC
??1BUFFER@@QEAA@XZ equ <__imp_??1BUFFER@@QEAA@XZ>

externdef __imp_??1BUFFER_CHAIN@@QEAA@XZ:PPROC
??1BUFFER_CHAIN@@QEAA@XZ equ <__imp_??1BUFFER_CHAIN@@QEAA@XZ>

externdef __imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ:PPROC
??1BUFFER_CHAIN_ITEM@@QEAA@XZ equ <__imp_??1BUFFER_CHAIN_ITEM@@QEAA@XZ>

externdef __imp_??_FBUFFER@@QEAAXXZ:PPROC
??_FBUFFER@@QEAAXXZ equ <__imp_??_FBUFFER@@QEAAXXZ>

externdef __imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ:PPROC
??_FBUFFER_CHAIN_ITEM@@QEAAXXZ equ <__imp_??_FBUFFER_CHAIN_ITEM@@QEAAXXZ>

externdef __imp_?QueryPtr@BUFFER@@QEBAPEAXXZ:PPROC
?QueryPtr@BUFFER@@QEBAPEAXXZ equ <__imp_?QueryPtr@BUFFER@@QEBAPEAXXZ>

externdef __imp_?QuerySize@BUFFER@@QEBAIXZ:PPROC
?QuerySize@BUFFER@@QEBAIXZ equ <__imp_?QuerySize@BUFFER@@QEBAIXZ>

externdef __imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ:PPROC
?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ equ <__imp_?QueryUsed@BUFFER_CHAIN_ITEM@@QEBAKXZ>

externdef __imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z:PPROC
?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z equ <__imp_?SetUsed@BUFFER_CHAIN_ITEM@@QEAAXK@Z>

externdef __imp_DllEntryPoint:PPROC
DllEntryPoint equ <__imp_DllEntryPoint>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_ServiceMain:PPROC
ServiceMain equ <__imp_ServiceMain>

externdef __imp_SvchostPushServiceGlobals:PPROC
SvchostPushServiceGlobals equ <__imp_SvchostPushServiceGlobals>

externdef __imp_wiasCreateChildAppItem:PPROC
wiasCreateChildAppItem equ <__imp_wiasCreateChildAppItem>

externdef __imp_wiasCreateDrvItem:PPROC
wiasCreateDrvItem equ <__imp_wiasCreateDrvItem>

externdef __imp_wiasCreateLogInstance:PPROC
wiasCreateLogInstance equ <__imp_wiasCreateLogInstance>

externdef __imp_wiasCreatePropContext:PPROC
wiasCreatePropContext equ <__imp_wiasCreatePropContext>

externdef __imp_wiasDebugError:PPROC
wiasDebugError equ <__imp_wiasDebugError>

externdef __imp_wiasDebugTrace:PPROC
wiasDebugTrace equ <__imp_wiasDebugTrace>

externdef __imp_wiasDownSampleBuffer:PPROC
wiasDownSampleBuffer equ <__imp_wiasDownSampleBuffer>

externdef __imp_wiasFormatArgs:PPROC
wiasFormatArgs equ <__imp_wiasFormatArgs>

externdef __imp_wiasFreePropContext:PPROC
wiasFreePropContext equ <__imp_wiasFreePropContext>

externdef __imp_wiasGetChangedValueFloat:PPROC
wiasGetChangedValueFloat equ <__imp_wiasGetChangedValueFloat>

externdef __imp_wiasGetChangedValueGuid:PPROC
wiasGetChangedValueGuid equ <__imp_wiasGetChangedValueGuid>

externdef __imp_wiasGetChangedValueLong:PPROC
wiasGetChangedValueLong equ <__imp_wiasGetChangedValueLong>

externdef __imp_wiasGetChangedValueStr:PPROC
wiasGetChangedValueStr equ <__imp_wiasGetChangedValueStr>

externdef __imp_wiasGetChildrenContexts:PPROC
wiasGetChildrenContexts equ <__imp_wiasGetChildrenContexts>

externdef __imp_wiasGetContextFromName:PPROC
wiasGetContextFromName equ <__imp_wiasGetContextFromName>

externdef __imp_wiasGetDrvItem:PPROC
wiasGetDrvItem equ <__imp_wiasGetDrvItem>

externdef __imp_wiasGetImageInformation:PPROC
wiasGetImageInformation equ <__imp_wiasGetImageInformation>

externdef __imp_wiasGetItemType:PPROC
wiasGetItemType equ <__imp_wiasGetItemType>

externdef __imp_wiasGetPropertyAttributes:PPROC
wiasGetPropertyAttributes equ <__imp_wiasGetPropertyAttributes>

externdef __imp_wiasGetRootItem:PPROC
wiasGetRootItem equ <__imp_wiasGetRootItem>

externdef __imp_wiasIsPropChanged:PPROC
wiasIsPropChanged equ <__imp_wiasIsPropChanged>

externdef __imp_wiasParseEndorserString:PPROC
wiasParseEndorserString equ <__imp_wiasParseEndorserString>

externdef __imp_wiasPrintDebugHResult:PPROC
wiasPrintDebugHResult equ <__imp_wiasPrintDebugHResult>

externdef __imp_wiasQueueEvent:PPROC
wiasQueueEvent equ <__imp_wiasQueueEvent>

externdef __imp_wiasReadMultiple:PPROC
wiasReadMultiple equ <__imp_wiasReadMultiple>

externdef __imp_wiasReadPropBin:PPROC
wiasReadPropBin equ <__imp_wiasReadPropBin>

externdef __imp_wiasReadPropFloat:PPROC
wiasReadPropFloat equ <__imp_wiasReadPropFloat>

externdef __imp_wiasReadPropGuid:PPROC
wiasReadPropGuid equ <__imp_wiasReadPropGuid>

externdef __imp_wiasReadPropLong:PPROC
wiasReadPropLong equ <__imp_wiasReadPropLong>

externdef __imp_wiasReadPropStr:PPROC
wiasReadPropStr equ <__imp_wiasReadPropStr>

externdef __imp_wiasSendEndOfPage:PPROC
wiasSendEndOfPage equ <__imp_wiasSendEndOfPage>

externdef __imp_wiasSetItemPropAttribs:PPROC
wiasSetItemPropAttribs equ <__imp_wiasSetItemPropAttribs>

externdef __imp_wiasSetItemPropNames:PPROC
wiasSetItemPropNames equ <__imp_wiasSetItemPropNames>

externdef __imp_wiasSetPropChanged:PPROC
wiasSetPropChanged equ <__imp_wiasSetPropChanged>

externdef __imp_wiasSetPropertyAttributes:PPROC
wiasSetPropertyAttributes equ <__imp_wiasSetPropertyAttributes>

externdef __imp_wiasSetValidFlag:PPROC
wiasSetValidFlag equ <__imp_wiasSetValidFlag>

externdef __imp_wiasSetValidListFloat:PPROC
wiasSetValidListFloat equ <__imp_wiasSetValidListFloat>

externdef __imp_wiasSetValidListGuid:PPROC
wiasSetValidListGuid equ <__imp_wiasSetValidListGuid>

externdef __imp_wiasSetValidListLong:PPROC
wiasSetValidListLong equ <__imp_wiasSetValidListLong>

externdef __imp_wiasSetValidListStr:PPROC
wiasSetValidListStr equ <__imp_wiasSetValidListStr>

externdef __imp_wiasSetValidRangeFloat:PPROC
wiasSetValidRangeFloat equ <__imp_wiasSetValidRangeFloat>

externdef __imp_wiasSetValidRangeLong:PPROC
wiasSetValidRangeLong equ <__imp_wiasSetValidRangeLong>

externdef __imp_wiasUpdateScanRect:PPROC
wiasUpdateScanRect equ <__imp_wiasUpdateScanRect>

externdef __imp_wiasUpdateValidFormat:PPROC
wiasUpdateValidFormat equ <__imp_wiasUpdateValidFormat>

externdef __imp_wiasValidateItemProperties:PPROC
wiasValidateItemProperties equ <__imp_wiasValidateItemProperties>

externdef __imp_wiasWriteBufToFile:PPROC
wiasWriteBufToFile equ <__imp_wiasWriteBufToFile>

externdef __imp_wiasWriteMultiple:PPROC
wiasWriteMultiple equ <__imp_wiasWriteMultiple>

externdef __imp_wiasWritePageBufToFile:PPROC
wiasWritePageBufToFile equ <__imp_wiasWritePageBufToFile>

externdef __imp_wiasWritePropBin:PPROC
wiasWritePropBin equ <__imp_wiasWritePropBin>

externdef __imp_wiasWritePropFloat:PPROC
wiasWritePropFloat equ <__imp_wiasWritePropFloat>

externdef __imp_wiasWritePropGuid:PPROC
wiasWritePropGuid equ <__imp_wiasWritePropGuid>

externdef __imp_wiasWritePropLong:PPROC
wiasWritePropLong equ <__imp_wiasWritePropLong>

externdef __imp_wiasWritePropStr:PPROC
wiasWritePropStr equ <__imp_wiasWritePropStr>
