externdef __imp_CommitUrlCacheEntryA:PPROC
CommitUrlCacheEntryA equ <__imp_CommitUrlCacheEntryA>
  IFNDEF __UNICODE__
    CommitUrlCacheEntry equ <__imp_CommitUrlCacheEntryA>
  ENDIF

externdef __imp_CommitUrlCacheEntryW:PPROC
CommitUrlCacheEntryW equ <__imp_CommitUrlCacheEntryW>
  IFDEF __UNICODE__
    CommitUrlCacheEntry equ <__imp_CommitUrlCacheEntryW>
  ENDIF

externdef __imp_CreateMD5SSOHash:PPROC
CreateMD5SSOHash equ <__imp_CreateMD5SSOHash>

externdef __imp_CreateUrlCacheContainerA:PPROC
CreateUrlCacheContainerA equ <__imp_CreateUrlCacheContainerA>
  IFNDEF __UNICODE__
    CreateUrlCacheContainer equ <__imp_CreateUrlCacheContainerA>
  ENDIF

externdef __imp_CreateUrlCacheContainerW:PPROC
CreateUrlCacheContainerW equ <__imp_CreateUrlCacheContainerW>
  IFDEF __UNICODE__
    CreateUrlCacheContainer equ <__imp_CreateUrlCacheContainerW>
  ENDIF

externdef __imp_CreateUrlCacheEntryA:PPROC
CreateUrlCacheEntryA equ <__imp_CreateUrlCacheEntryA>
  IFNDEF __UNICODE__
    CreateUrlCacheEntry equ <__imp_CreateUrlCacheEntryA>
  ENDIF

externdef __imp_CreateUrlCacheEntryW:PPROC
CreateUrlCacheEntryW equ <__imp_CreateUrlCacheEntryW>
  IFDEF __UNICODE__
    CreateUrlCacheEntry equ <__imp_CreateUrlCacheEntryW>
  ENDIF

externdef __imp_CreateUrlCacheGroup:PPROC
CreateUrlCacheGroup equ <__imp_CreateUrlCacheGroup>

externdef __imp_DeleteIE3Cache:PPROC
DeleteIE3Cache equ <__imp_DeleteIE3Cache>

externdef __imp_DeleteUrlCacheContainerA:PPROC
DeleteUrlCacheContainerA equ <__imp_DeleteUrlCacheContainerA>
  IFNDEF __UNICODE__
    DeleteUrlCacheContainer equ <__imp_DeleteUrlCacheContainerA>
  ENDIF

externdef __imp_DeleteUrlCacheContainerW:PPROC
DeleteUrlCacheContainerW equ <__imp_DeleteUrlCacheContainerW>
  IFDEF __UNICODE__
    DeleteUrlCacheContainer equ <__imp_DeleteUrlCacheContainerW>
  ENDIF

externdef __imp_DeleteUrlCacheEntry:PPROC
DeleteUrlCacheEntry equ <__imp_DeleteUrlCacheEntry>

externdef __imp_DeleteUrlCacheEntryA:PPROC
DeleteUrlCacheEntryA equ <__imp_DeleteUrlCacheEntryA>
  IFNDEF __UNICODE__
    DeleteUrlCacheEntry equ <__imp_DeleteUrlCacheEntryA>
  ENDIF

externdef __imp_DeleteUrlCacheEntryW:PPROC
DeleteUrlCacheEntryW equ <__imp_DeleteUrlCacheEntryW>
  IFDEF __UNICODE__
    DeleteUrlCacheEntry equ <__imp_DeleteUrlCacheEntryW>
  ENDIF

externdef __imp_DeleteUrlCacheGroup:PPROC
DeleteUrlCacheGroup equ <__imp_DeleteUrlCacheGroup>

externdef __imp_DetectAutoProxyUrl:PPROC
DetectAutoProxyUrl equ <__imp_DetectAutoProxyUrl>

externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_FindCloseUrlCache:PPROC
FindCloseUrlCache equ <__imp_FindCloseUrlCache>

externdef __imp_FindFirstUrlCacheContainerA:PPROC
FindFirstUrlCacheContainerA equ <__imp_FindFirstUrlCacheContainerA>
  IFNDEF __UNICODE__
    FindFirstUrlCacheContainer equ <__imp_FindFirstUrlCacheContainerA>
  ENDIF

externdef __imp_FindFirstUrlCacheContainerW:PPROC
FindFirstUrlCacheContainerW equ <__imp_FindFirstUrlCacheContainerW>
  IFDEF __UNICODE__
    FindFirstUrlCacheContainer equ <__imp_FindFirstUrlCacheContainerW>
  ENDIF

externdef __imp_FindFirstUrlCacheEntryA:PPROC
FindFirstUrlCacheEntryA equ <__imp_FindFirstUrlCacheEntryA>
  IFNDEF __UNICODE__
    FindFirstUrlCacheEntry equ <__imp_FindFirstUrlCacheEntryA>
  ENDIF

externdef __imp_FindFirstUrlCacheEntryExA:PPROC
FindFirstUrlCacheEntryExA equ <__imp_FindFirstUrlCacheEntryExA>
  IFNDEF __UNICODE__
    FindFirstUrlCacheEntryEx equ <__imp_FindFirstUrlCacheEntryExA>
  ENDIF

externdef __imp_FindFirstUrlCacheEntryExW:PPROC
FindFirstUrlCacheEntryExW equ <__imp_FindFirstUrlCacheEntryExW>
  IFDEF __UNICODE__
    FindFirstUrlCacheEntryEx equ <__imp_FindFirstUrlCacheEntryExW>
  ENDIF

externdef __imp_FindFirstUrlCacheEntryW:PPROC
FindFirstUrlCacheEntryW equ <__imp_FindFirstUrlCacheEntryW>
  IFDEF __UNICODE__
    FindFirstUrlCacheEntry equ <__imp_FindFirstUrlCacheEntryW>
  ENDIF

externdef __imp_FindFirstUrlCacheGroup:PPROC
FindFirstUrlCacheGroup equ <__imp_FindFirstUrlCacheGroup>

externdef __imp_FindNextUrlCacheContainerA:PPROC
FindNextUrlCacheContainerA equ <__imp_FindNextUrlCacheContainerA>
  IFNDEF __UNICODE__
    FindNextUrlCacheContainer equ <__imp_FindNextUrlCacheContainerA>
  ENDIF

externdef __imp_FindNextUrlCacheContainerW:PPROC
FindNextUrlCacheContainerW equ <__imp_FindNextUrlCacheContainerW>
  IFDEF __UNICODE__
    FindNextUrlCacheContainer equ <__imp_FindNextUrlCacheContainerW>
  ENDIF

externdef __imp_FindNextUrlCacheEntryA:PPROC
FindNextUrlCacheEntryA equ <__imp_FindNextUrlCacheEntryA>
  IFNDEF __UNICODE__
    FindNextUrlCacheEntry equ <__imp_FindNextUrlCacheEntryA>
  ENDIF

externdef __imp_FindNextUrlCacheEntryExA:PPROC
FindNextUrlCacheEntryExA equ <__imp_FindNextUrlCacheEntryExA>
  IFNDEF __UNICODE__
    FindNextUrlCacheEntryEx equ <__imp_FindNextUrlCacheEntryExA>
  ENDIF

externdef __imp_FindNextUrlCacheEntryExW:PPROC
FindNextUrlCacheEntryExW equ <__imp_FindNextUrlCacheEntryExW>
  IFDEF __UNICODE__
    FindNextUrlCacheEntryEx equ <__imp_FindNextUrlCacheEntryExW>
  ENDIF

externdef __imp_FindNextUrlCacheEntryW:PPROC
FindNextUrlCacheEntryW equ <__imp_FindNextUrlCacheEntryW>
  IFDEF __UNICODE__
    FindNextUrlCacheEntry equ <__imp_FindNextUrlCacheEntryW>
  ENDIF

externdef __imp_FindNextUrlCacheGroup:PPROC
FindNextUrlCacheGroup equ <__imp_FindNextUrlCacheGroup>

externdef __imp_ForceNexusLookup:PPROC
ForceNexusLookup equ <__imp_ForceNexusLookup>

externdef __imp_ForceNexusLookupExW:PPROC
ForceNexusLookupExW equ <__imp_ForceNexusLookupExW>
  IFDEF __UNICODE__
    ForceNexusLookupEx equ <__imp_ForceNexusLookupExW>
  ENDIF

externdef __imp_FreeUrlCacheSpaceA:PPROC
FreeUrlCacheSpaceA equ <__imp_FreeUrlCacheSpaceA>
  IFNDEF __UNICODE__
    FreeUrlCacheSpace equ <__imp_FreeUrlCacheSpaceA>
  ENDIF

externdef __imp_FreeUrlCacheSpaceW:PPROC
FreeUrlCacheSpaceW equ <__imp_FreeUrlCacheSpaceW>
  IFDEF __UNICODE__
    FreeUrlCacheSpace equ <__imp_FreeUrlCacheSpaceW>
  ENDIF

externdef __imp_FtpCommandA:PPROC
FtpCommandA equ <__imp_FtpCommandA>
  IFNDEF __UNICODE__
    FtpCommand equ <__imp_FtpCommandA>
  ENDIF

externdef __imp_FtpCommandW:PPROC
FtpCommandW equ <__imp_FtpCommandW>
  IFDEF __UNICODE__
    FtpCommand equ <__imp_FtpCommandW>
  ENDIF

externdef __imp_FtpCreateDirectoryA:PPROC
FtpCreateDirectoryA equ <__imp_FtpCreateDirectoryA>
  IFNDEF __UNICODE__
    FtpCreateDirectory equ <__imp_FtpCreateDirectoryA>
  ENDIF

externdef __imp_FtpCreateDirectoryW:PPROC
FtpCreateDirectoryW equ <__imp_FtpCreateDirectoryW>
  IFDEF __UNICODE__
    FtpCreateDirectory equ <__imp_FtpCreateDirectoryW>
  ENDIF

externdef __imp_FtpDeleteFileA:PPROC
FtpDeleteFileA equ <__imp_FtpDeleteFileA>
  IFNDEF __UNICODE__
    FtpDeleteFile equ <__imp_FtpDeleteFileA>
  ENDIF

externdef __imp_FtpDeleteFileW:PPROC
FtpDeleteFileW equ <__imp_FtpDeleteFileW>
  IFDEF __UNICODE__
    FtpDeleteFile equ <__imp_FtpDeleteFileW>
  ENDIF

externdef __imp_FtpFindFirstFileA:PPROC
FtpFindFirstFileA equ <__imp_FtpFindFirstFileA>
  IFNDEF __UNICODE__
    FtpFindFirstFile equ <__imp_FtpFindFirstFileA>
  ENDIF

externdef __imp_FtpFindFirstFileW:PPROC
FtpFindFirstFileW equ <__imp_FtpFindFirstFileW>
  IFDEF __UNICODE__
    FtpFindFirstFile equ <__imp_FtpFindFirstFileW>
  ENDIF

externdef __imp_FtpGetCurrentDirectoryA:PPROC
FtpGetCurrentDirectoryA equ <__imp_FtpGetCurrentDirectoryA>
  IFNDEF __UNICODE__
    FtpGetCurrentDirectory equ <__imp_FtpGetCurrentDirectoryA>
  ENDIF

externdef __imp_FtpGetCurrentDirectoryW:PPROC
FtpGetCurrentDirectoryW equ <__imp_FtpGetCurrentDirectoryW>
  IFDEF __UNICODE__
    FtpGetCurrentDirectory equ <__imp_FtpGetCurrentDirectoryW>
  ENDIF

externdef __imp_FtpGetFileA:PPROC
FtpGetFileA equ <__imp_FtpGetFileA>
  IFNDEF __UNICODE__
    FtpGetFile equ <__imp_FtpGetFileA>
  ENDIF

externdef __imp_FtpGetFileEx:PPROC
FtpGetFileEx equ <__imp_FtpGetFileEx>

externdef __imp_FtpGetFileSize:PPROC
FtpGetFileSize equ <__imp_FtpGetFileSize>

externdef __imp_FtpGetFileW:PPROC
FtpGetFileW equ <__imp_FtpGetFileW>
  IFDEF __UNICODE__
    FtpGetFile equ <__imp_FtpGetFileW>
  ENDIF

externdef __imp_FtpOpenFileA:PPROC
FtpOpenFileA equ <__imp_FtpOpenFileA>
  IFNDEF __UNICODE__
    FtpOpenFile equ <__imp_FtpOpenFileA>
  ENDIF

externdef __imp_FtpOpenFileW:PPROC
FtpOpenFileW equ <__imp_FtpOpenFileW>
  IFDEF __UNICODE__
    FtpOpenFile equ <__imp_FtpOpenFileW>
  ENDIF

externdef __imp_FtpPutFileA:PPROC
FtpPutFileA equ <__imp_FtpPutFileA>
  IFNDEF __UNICODE__
    FtpPutFile equ <__imp_FtpPutFileA>
  ENDIF

externdef __imp_FtpPutFileEx:PPROC
FtpPutFileEx equ <__imp_FtpPutFileEx>

externdef __imp_FtpPutFileW:PPROC
FtpPutFileW equ <__imp_FtpPutFileW>
  IFDEF __UNICODE__
    FtpPutFile equ <__imp_FtpPutFileW>
  ENDIF

externdef __imp_FtpRemoveDirectoryA:PPROC
FtpRemoveDirectoryA equ <__imp_FtpRemoveDirectoryA>
  IFNDEF __UNICODE__
    FtpRemoveDirectory equ <__imp_FtpRemoveDirectoryA>
  ENDIF

externdef __imp_FtpRemoveDirectoryW:PPROC
FtpRemoveDirectoryW equ <__imp_FtpRemoveDirectoryW>
  IFDEF __UNICODE__
    FtpRemoveDirectory equ <__imp_FtpRemoveDirectoryW>
  ENDIF

externdef __imp_FtpRenameFileA:PPROC
FtpRenameFileA equ <__imp_FtpRenameFileA>
  IFNDEF __UNICODE__
    FtpRenameFile equ <__imp_FtpRenameFileA>
  ENDIF

externdef __imp_FtpRenameFileW:PPROC
FtpRenameFileW equ <__imp_FtpRenameFileW>
  IFDEF __UNICODE__
    FtpRenameFile equ <__imp_FtpRenameFileW>
  ENDIF

externdef __imp_FtpSetCurrentDirectoryA:PPROC
FtpSetCurrentDirectoryA equ <__imp_FtpSetCurrentDirectoryA>
  IFNDEF __UNICODE__
    FtpSetCurrentDirectory equ <__imp_FtpSetCurrentDirectoryA>
  ENDIF

externdef __imp_FtpSetCurrentDirectoryW:PPROC
FtpSetCurrentDirectoryW equ <__imp_FtpSetCurrentDirectoryW>
  IFDEF __UNICODE__
    FtpSetCurrentDirectory equ <__imp_FtpSetCurrentDirectoryW>
  ENDIF

externdef __imp_GetUrlCacheConfigInfoA:PPROC
GetUrlCacheConfigInfoA equ <__imp_GetUrlCacheConfigInfoA>
  IFNDEF __UNICODE__
    GetUrlCacheConfigInfo equ <__imp_GetUrlCacheConfigInfoA>
  ENDIF

externdef __imp_GetUrlCacheConfigInfoW:PPROC
GetUrlCacheConfigInfoW equ <__imp_GetUrlCacheConfigInfoW>
  IFDEF __UNICODE__
    GetUrlCacheConfigInfo equ <__imp_GetUrlCacheConfigInfoW>
  ENDIF

externdef __imp_GetUrlCacheEntryInfoA:PPROC
GetUrlCacheEntryInfoA equ <__imp_GetUrlCacheEntryInfoA>
  IFNDEF __UNICODE__
    GetUrlCacheEntryInfo equ <__imp_GetUrlCacheEntryInfoA>
  ENDIF

externdef __imp_GetUrlCacheEntryInfoExA:PPROC
GetUrlCacheEntryInfoExA equ <__imp_GetUrlCacheEntryInfoExA>
  IFNDEF __UNICODE__
    GetUrlCacheEntryInfoEx equ <__imp_GetUrlCacheEntryInfoExA>
  ENDIF

externdef __imp_GetUrlCacheEntryInfoExW:PPROC
GetUrlCacheEntryInfoExW equ <__imp_GetUrlCacheEntryInfoExW>
  IFDEF __UNICODE__
    GetUrlCacheEntryInfoEx equ <__imp_GetUrlCacheEntryInfoExW>
  ENDIF

externdef __imp_GetUrlCacheEntryInfoW:PPROC
GetUrlCacheEntryInfoW equ <__imp_GetUrlCacheEntryInfoW>
  IFDEF __UNICODE__
    GetUrlCacheEntryInfo equ <__imp_GetUrlCacheEntryInfoW>
  ENDIF

externdef __imp_GetUrlCacheGroupAttributeA:PPROC
GetUrlCacheGroupAttributeA equ <__imp_GetUrlCacheGroupAttributeA>
  IFNDEF __UNICODE__
    GetUrlCacheGroupAttribute equ <__imp_GetUrlCacheGroupAttributeA>
  ENDIF

externdef __imp_GetUrlCacheGroupAttributeW:PPROC
GetUrlCacheGroupAttributeW equ <__imp_GetUrlCacheGroupAttributeW>
  IFDEF __UNICODE__
    GetUrlCacheGroupAttribute equ <__imp_GetUrlCacheGroupAttributeW>
  ENDIF

externdef __imp_GetUrlCacheHeaderData:PPROC
GetUrlCacheHeaderData equ <__imp_GetUrlCacheHeaderData>

externdef __imp_GopherCreateLocatorA:PPROC
GopherCreateLocatorA equ <__imp_GopherCreateLocatorA>
  IFNDEF __UNICODE__
    GopherCreateLocator equ <__imp_GopherCreateLocatorA>
  ENDIF

externdef __imp_GopherCreateLocatorW:PPROC
GopherCreateLocatorW equ <__imp_GopherCreateLocatorW>
  IFDEF __UNICODE__
    GopherCreateLocator equ <__imp_GopherCreateLocatorW>
  ENDIF

externdef __imp_GopherFindFirstFileA:PPROC
GopherFindFirstFileA equ <__imp_GopherFindFirstFileA>
  IFNDEF __UNICODE__
    GopherFindFirstFile equ <__imp_GopherFindFirstFileA>
  ENDIF

externdef __imp_GopherFindFirstFileW:PPROC
GopherFindFirstFileW equ <__imp_GopherFindFirstFileW>
  IFDEF __UNICODE__
    GopherFindFirstFile equ <__imp_GopherFindFirstFileW>
  ENDIF

externdef __imp_GopherGetAttributeA:PPROC
GopherGetAttributeA equ <__imp_GopherGetAttributeA>
  IFNDEF __UNICODE__
    GopherGetAttribute equ <__imp_GopherGetAttributeA>
  ENDIF

externdef __imp_GopherGetAttributeW:PPROC
GopherGetAttributeW equ <__imp_GopherGetAttributeW>
  IFDEF __UNICODE__
    GopherGetAttribute equ <__imp_GopherGetAttributeW>
  ENDIF

externdef __imp_GopherGetLocatorTypeA:PPROC
GopherGetLocatorTypeA equ <__imp_GopherGetLocatorTypeA>
  IFNDEF __UNICODE__
    GopherGetLocatorType equ <__imp_GopherGetLocatorTypeA>
  ENDIF

externdef __imp_GopherGetLocatorTypeW:PPROC
GopherGetLocatorTypeW equ <__imp_GopherGetLocatorTypeW>
  IFDEF __UNICODE__
    GopherGetLocatorType equ <__imp_GopherGetLocatorTypeW>
  ENDIF

externdef __imp_GopherOpenFileA:PPROC
GopherOpenFileA equ <__imp_GopherOpenFileA>
  IFNDEF __UNICODE__
    GopherOpenFile equ <__imp_GopherOpenFileA>
  ENDIF

externdef __imp_GopherOpenFileW:PPROC
GopherOpenFileW equ <__imp_GopherOpenFileW>
  IFDEF __UNICODE__
    GopherOpenFile equ <__imp_GopherOpenFileW>
  ENDIF

externdef __imp_HttpAddRequestHeadersA:PPROC
HttpAddRequestHeadersA equ <__imp_HttpAddRequestHeadersA>
  IFNDEF __UNICODE__
    HttpAddRequestHeaders equ <__imp_HttpAddRequestHeadersA>
  ENDIF

externdef __imp_HttpAddRequestHeadersW:PPROC
HttpAddRequestHeadersW equ <__imp_HttpAddRequestHeadersW>
  IFDEF __UNICODE__
    HttpAddRequestHeaders equ <__imp_HttpAddRequestHeadersW>
  ENDIF

externdef __imp_HttpCheckDavCompliance:PPROC
HttpCheckDavCompliance equ <__imp_HttpCheckDavCompliance>

externdef __imp_HttpEndRequestA:PPROC
HttpEndRequestA equ <__imp_HttpEndRequestA>
  IFNDEF __UNICODE__
    HttpEndRequest equ <__imp_HttpEndRequestA>
  ENDIF

externdef __imp_HttpEndRequestW:PPROC
HttpEndRequestW equ <__imp_HttpEndRequestW>
  IFDEF __UNICODE__
    HttpEndRequest equ <__imp_HttpEndRequestW>
  ENDIF

externdef __imp_HttpOpenRequestA:PPROC
HttpOpenRequestA equ <__imp_HttpOpenRequestA>
  IFNDEF __UNICODE__
    HttpOpenRequest equ <__imp_HttpOpenRequestA>
  ENDIF

externdef __imp_HttpOpenRequestW:PPROC
HttpOpenRequestW equ <__imp_HttpOpenRequestW>
  IFDEF __UNICODE__
    HttpOpenRequest equ <__imp_HttpOpenRequestW>
  ENDIF

externdef __imp_HttpQueryInfoA:PPROC
HttpQueryInfoA equ <__imp_HttpQueryInfoA>
  IFNDEF __UNICODE__
    HttpQueryInfo equ <__imp_HttpQueryInfoA>
  ENDIF

externdef __imp_HttpQueryInfoW:PPROC
HttpQueryInfoW equ <__imp_HttpQueryInfoW>
  IFDEF __UNICODE__
    HttpQueryInfo equ <__imp_HttpQueryInfoW>
  ENDIF

externdef __imp_HttpSendRequestA:PPROC
HttpSendRequestA equ <__imp_HttpSendRequestA>
  IFNDEF __UNICODE__
    HttpSendRequest equ <__imp_HttpSendRequestA>
  ENDIF

externdef __imp_HttpSendRequestExA:PPROC
HttpSendRequestExA equ <__imp_HttpSendRequestExA>
  IFNDEF __UNICODE__
    HttpSendRequestEx equ <__imp_HttpSendRequestExA>
  ENDIF

externdef __imp_HttpSendRequestExW:PPROC
HttpSendRequestExW equ <__imp_HttpSendRequestExW>
  IFDEF __UNICODE__
    HttpSendRequestEx equ <__imp_HttpSendRequestExW>
  ENDIF

externdef __imp_HttpSendRequestW:PPROC
HttpSendRequestW equ <__imp_HttpSendRequestW>
  IFDEF __UNICODE__
    HttpSendRequest equ <__imp_HttpSendRequestW>
  ENDIF

externdef __imp_IncrementUrlCacheHeaderData:PPROC
IncrementUrlCacheHeaderData equ <__imp_IncrementUrlCacheHeaderData>

externdef __imp_InternetAlgIdToStringA:PPROC
InternetAlgIdToStringA equ <__imp_InternetAlgIdToStringA>
  IFNDEF __UNICODE__
    InternetAlgIdToString equ <__imp_InternetAlgIdToStringA>
  ENDIF

externdef __imp_InternetAlgIdToStringW:PPROC
InternetAlgIdToStringW equ <__imp_InternetAlgIdToStringW>
  IFDEF __UNICODE__
    InternetAlgIdToString equ <__imp_InternetAlgIdToStringW>
  ENDIF

externdef __imp_InternetAttemptConnect:PPROC
InternetAttemptConnect equ <__imp_InternetAttemptConnect>

externdef __imp_InternetAutodial:PPROC
InternetAutodial equ <__imp_InternetAutodial>

externdef __imp_InternetAutodialCallback:PPROC
InternetAutodialCallback equ <__imp_InternetAutodialCallback>

externdef __imp_InternetAutodialHangup:PPROC
InternetAutodialHangup equ <__imp_InternetAutodialHangup>

externdef __imp_InternetCanonicalizeUrlA:PPROC
InternetCanonicalizeUrlA equ <__imp_InternetCanonicalizeUrlA>
  IFNDEF __UNICODE__
    InternetCanonicalizeUrl equ <__imp_InternetCanonicalizeUrlA>
  ENDIF

externdef __imp_InternetCanonicalizeUrlW:PPROC
InternetCanonicalizeUrlW equ <__imp_InternetCanonicalizeUrlW>
  IFDEF __UNICODE__
    InternetCanonicalizeUrl equ <__imp_InternetCanonicalizeUrlW>
  ENDIF

externdef __imp_InternetCheckConnectionA:PPROC
InternetCheckConnectionA equ <__imp_InternetCheckConnectionA>
  IFNDEF __UNICODE__
    InternetCheckConnection equ <__imp_InternetCheckConnectionA>
  ENDIF

externdef __imp_InternetCheckConnectionW:PPROC
InternetCheckConnectionW equ <__imp_InternetCheckConnectionW>
  IFDEF __UNICODE__
    InternetCheckConnection equ <__imp_InternetCheckConnectionW>
  ENDIF

externdef __imp_InternetClearAllPerSiteCookieDecisions:PPROC
InternetClearAllPerSiteCookieDecisions equ <__imp_InternetClearAllPerSiteCookieDecisions>

externdef __imp_InternetCloseHandle:PPROC
InternetCloseHandle equ <__imp_InternetCloseHandle>

externdef __imp_InternetCombineUrlA:PPROC
InternetCombineUrlA equ <__imp_InternetCombineUrlA>
  IFNDEF __UNICODE__
    InternetCombineUrl equ <__imp_InternetCombineUrlA>
  ENDIF

externdef __imp_InternetCombineUrlW:PPROC
InternetCombineUrlW equ <__imp_InternetCombineUrlW>
  IFDEF __UNICODE__
    InternetCombineUrl equ <__imp_InternetCombineUrlW>
  ENDIF

externdef __imp_InternetConfirmZoneCrossing:PPROC
InternetConfirmZoneCrossing equ <__imp_InternetConfirmZoneCrossing>

externdef __imp_InternetConfirmZoneCrossingA:PPROC
InternetConfirmZoneCrossingA equ <__imp_InternetConfirmZoneCrossingA>
  IFNDEF __UNICODE__
    InternetConfirmZoneCrossing equ <__imp_InternetConfirmZoneCrossingA>
  ENDIF

externdef __imp_InternetConfirmZoneCrossingW:PPROC
InternetConfirmZoneCrossingW equ <__imp_InternetConfirmZoneCrossingW>
  IFDEF __UNICODE__
    InternetConfirmZoneCrossing equ <__imp_InternetConfirmZoneCrossingW>
  ENDIF

externdef __imp_InternetConnectA:PPROC
InternetConnectA equ <__imp_InternetConnectA>
  IFNDEF __UNICODE__
    InternetConnect equ <__imp_InternetConnectA>
  ENDIF

externdef __imp_InternetConnectW:PPROC
InternetConnectW equ <__imp_InternetConnectW>
  IFDEF __UNICODE__
    InternetConnect equ <__imp_InternetConnectW>
  ENDIF

externdef __imp_InternetCrackUrlA:PPROC
InternetCrackUrlA equ <__imp_InternetCrackUrlA>
  IFNDEF __UNICODE__
    InternetCrackUrl equ <__imp_InternetCrackUrlA>
  ENDIF

externdef __imp_InternetCrackUrlW:PPROC
InternetCrackUrlW equ <__imp_InternetCrackUrlW>
  IFDEF __UNICODE__
    InternetCrackUrl equ <__imp_InternetCrackUrlW>
  ENDIF

externdef __imp_InternetCreateUrlA:PPROC
InternetCreateUrlA equ <__imp_InternetCreateUrlA>
  IFNDEF __UNICODE__
    InternetCreateUrl equ <__imp_InternetCreateUrlA>
  ENDIF

externdef __imp_InternetCreateUrlW:PPROC
InternetCreateUrlW equ <__imp_InternetCreateUrlW>
  IFDEF __UNICODE__
    InternetCreateUrl equ <__imp_InternetCreateUrlW>
  ENDIF

externdef __imp_InternetDial:PPROC
InternetDial equ <__imp_InternetDial>

externdef __imp_InternetDialA:PPROC
InternetDialA equ <__imp_InternetDialA>
  IFNDEF __UNICODE__
    InternetDial equ <__imp_InternetDialA>
  ENDIF

externdef __imp_InternetDialW:PPROC
InternetDialW equ <__imp_InternetDialW>
  IFDEF __UNICODE__
    InternetDial equ <__imp_InternetDialW>
  ENDIF

externdef __imp_InternetEnumPerSiteCookieDecisionA:PPROC
InternetEnumPerSiteCookieDecisionA equ <__imp_InternetEnumPerSiteCookieDecisionA>
  IFNDEF __UNICODE__
    InternetEnumPerSiteCookieDecision equ <__imp_InternetEnumPerSiteCookieDecisionA>
  ENDIF

externdef __imp_InternetEnumPerSiteCookieDecisionW:PPROC
InternetEnumPerSiteCookieDecisionW equ <__imp_InternetEnumPerSiteCookieDecisionW>
  IFDEF __UNICODE__
    InternetEnumPerSiteCookieDecision equ <__imp_InternetEnumPerSiteCookieDecisionW>
  ENDIF

externdef __imp_InternetErrorDlg:PPROC
InternetErrorDlg equ <__imp_InternetErrorDlg>

externdef __imp_InternetFindNextFileA:PPROC
InternetFindNextFileA equ <__imp_InternetFindNextFileA>
  IFNDEF __UNICODE__
    InternetFindNextFile equ <__imp_InternetFindNextFileA>
  ENDIF

externdef __imp_InternetFindNextFileW:PPROC
InternetFindNextFileW equ <__imp_InternetFindNextFileW>
  IFDEF __UNICODE__
    InternetFindNextFile equ <__imp_InternetFindNextFileW>
  ENDIF

externdef __imp_InternetFortezzaCommand:PPROC
InternetFortezzaCommand equ <__imp_InternetFortezzaCommand>

externdef __imp_InternetGetCertByURL:PPROC
InternetGetCertByURL equ <__imp_InternetGetCertByURL>

externdef __imp_InternetGetCertByURLA:PPROC
InternetGetCertByURLA equ <__imp_InternetGetCertByURLA>
  IFNDEF __UNICODE__
    InternetGetCertByURL equ <__imp_InternetGetCertByURLA>
  ENDIF

externdef __imp_InternetGetConnectedState:PPROC
InternetGetConnectedState equ <__imp_InternetGetConnectedState>

externdef __imp_InternetGetConnectedStateEx:PPROC
InternetGetConnectedStateEx equ <__imp_InternetGetConnectedStateEx>

externdef __imp_InternetGetConnectedStateExA:PPROC
InternetGetConnectedStateExA equ <__imp_InternetGetConnectedStateExA>
  IFNDEF __UNICODE__
    InternetGetConnectedStateEx equ <__imp_InternetGetConnectedStateExA>
  ENDIF

externdef __imp_InternetGetConnectedStateExW:PPROC
InternetGetConnectedStateExW equ <__imp_InternetGetConnectedStateExW>
  IFDEF __UNICODE__
    InternetGetConnectedStateEx equ <__imp_InternetGetConnectedStateExW>
  ENDIF

externdef __imp_InternetGetCookieA:PPROC
InternetGetCookieA equ <__imp_InternetGetCookieA>
  IFNDEF __UNICODE__
    InternetGetCookie equ <__imp_InternetGetCookieA>
  ENDIF

externdef __imp_InternetGetCookieExA:PPROC
InternetGetCookieExA equ <__imp_InternetGetCookieExA>
  IFNDEF __UNICODE__
    InternetGetCookieEx equ <__imp_InternetGetCookieExA>
  ENDIF

externdef __imp_InternetGetCookieExW:PPROC
InternetGetCookieExW equ <__imp_InternetGetCookieExW>
  IFDEF __UNICODE__
    InternetGetCookieEx equ <__imp_InternetGetCookieExW>
  ENDIF

externdef __imp_InternetGetCookieW:PPROC
InternetGetCookieW equ <__imp_InternetGetCookieW>
  IFDEF __UNICODE__
    InternetGetCookie equ <__imp_InternetGetCookieW>
  ENDIF

externdef __imp_InternetGetLastResponseInfoA:PPROC
InternetGetLastResponseInfoA equ <__imp_InternetGetLastResponseInfoA>
  IFNDEF __UNICODE__
    InternetGetLastResponseInfo equ <__imp_InternetGetLastResponseInfoA>
  ENDIF

externdef __imp_InternetGetLastResponseInfoW:PPROC
InternetGetLastResponseInfoW equ <__imp_InternetGetLastResponseInfoW>
  IFDEF __UNICODE__
    InternetGetLastResponseInfo equ <__imp_InternetGetLastResponseInfoW>
  ENDIF

externdef __imp_InternetGetPerSiteCookieDecisionA:PPROC
InternetGetPerSiteCookieDecisionA equ <__imp_InternetGetPerSiteCookieDecisionA>
  IFNDEF __UNICODE__
    InternetGetPerSiteCookieDecision equ <__imp_InternetGetPerSiteCookieDecisionA>
  ENDIF

externdef __imp_InternetGetPerSiteCookieDecisionW:PPROC
InternetGetPerSiteCookieDecisionW equ <__imp_InternetGetPerSiteCookieDecisionW>
  IFDEF __UNICODE__
    InternetGetPerSiteCookieDecision equ <__imp_InternetGetPerSiteCookieDecisionW>
  ENDIF

externdef __imp_InternetGoOnline:PPROC
InternetGoOnline equ <__imp_InternetGoOnline>

externdef __imp_InternetGoOnlineA:PPROC
InternetGoOnlineA equ <__imp_InternetGoOnlineA>
  IFNDEF __UNICODE__
    InternetGoOnline equ <__imp_InternetGoOnlineA>
  ENDIF

externdef __imp_InternetGoOnlineW:PPROC
InternetGoOnlineW equ <__imp_InternetGoOnlineW>
  IFDEF __UNICODE__
    InternetGoOnline equ <__imp_InternetGoOnlineW>
  ENDIF

externdef __imp_InternetHangUp:PPROC
InternetHangUp equ <__imp_InternetHangUp>

externdef __imp_InternetInitializeAutoProxyDll:PPROC
InternetInitializeAutoProxyDll equ <__imp_InternetInitializeAutoProxyDll>

externdef __imp_InternetLockRequestFile:PPROC
InternetLockRequestFile equ <__imp_InternetLockRequestFile>

externdef __imp_InternetOpenA:PPROC
InternetOpenA equ <__imp_InternetOpenA>
  IFNDEF __UNICODE__
    InternetOpen equ <__imp_InternetOpenA>
  ENDIF

externdef __imp_InternetOpenUrlA:PPROC
InternetOpenUrlA equ <__imp_InternetOpenUrlA>
  IFNDEF __UNICODE__
    InternetOpenUrl equ <__imp_InternetOpenUrlA>
  ENDIF

externdef __imp_InternetOpenUrlW:PPROC
InternetOpenUrlW equ <__imp_InternetOpenUrlW>
  IFDEF __UNICODE__
    InternetOpenUrl equ <__imp_InternetOpenUrlW>
  ENDIF

externdef __imp_InternetOpenW:PPROC
InternetOpenW equ <__imp_InternetOpenW>
  IFDEF __UNICODE__
    InternetOpen equ <__imp_InternetOpenW>
  ENDIF

externdef __imp_InternetQueryDataAvailable:PPROC
InternetQueryDataAvailable equ <__imp_InternetQueryDataAvailable>

externdef __imp_InternetQueryFortezzaStatus:PPROC
InternetQueryFortezzaStatus equ <__imp_InternetQueryFortezzaStatus>

externdef __imp_InternetQueryOptionA:PPROC
InternetQueryOptionA equ <__imp_InternetQueryOptionA>
  IFNDEF __UNICODE__
    InternetQueryOption equ <__imp_InternetQueryOptionA>
  ENDIF

externdef __imp_InternetQueryOptionW:PPROC
InternetQueryOptionW equ <__imp_InternetQueryOptionW>
  IFDEF __UNICODE__
    InternetQueryOption equ <__imp_InternetQueryOptionW>
  ENDIF

externdef __imp_InternetReadFile:PPROC
InternetReadFile equ <__imp_InternetReadFile>

externdef __imp_InternetReadFileExA:PPROC
InternetReadFileExA equ <__imp_InternetReadFileExA>
  IFNDEF __UNICODE__
    InternetReadFileEx equ <__imp_InternetReadFileExA>
  ENDIF

externdef __imp_InternetReadFileExW:PPROC
InternetReadFileExW equ <__imp_InternetReadFileExW>
  IFDEF __UNICODE__
    InternetReadFileEx equ <__imp_InternetReadFileExW>
  ENDIF

externdef __imp_InternetSecurityProtocolToStringA:PPROC
InternetSecurityProtocolToStringA equ <__imp_InternetSecurityProtocolToStringA>
  IFNDEF __UNICODE__
    InternetSecurityProtocolToString equ <__imp_InternetSecurityProtocolToStringA>
  ENDIF

externdef __imp_InternetSecurityProtocolToStringW:PPROC
InternetSecurityProtocolToStringW equ <__imp_InternetSecurityProtocolToStringW>
  IFDEF __UNICODE__
    InternetSecurityProtocolToString equ <__imp_InternetSecurityProtocolToStringW>
  ENDIF

externdef __imp_InternetSetCookieA:PPROC
InternetSetCookieA equ <__imp_InternetSetCookieA>
  IFNDEF __UNICODE__
    InternetSetCookie equ <__imp_InternetSetCookieA>
  ENDIF

externdef __imp_InternetSetCookieExA:PPROC
InternetSetCookieExA equ <__imp_InternetSetCookieExA>
  IFNDEF __UNICODE__
    InternetSetCookieEx equ <__imp_InternetSetCookieExA>
  ENDIF

externdef __imp_InternetSetCookieExW:PPROC
InternetSetCookieExW equ <__imp_InternetSetCookieExW>
  IFDEF __UNICODE__
    InternetSetCookieEx equ <__imp_InternetSetCookieExW>
  ENDIF

externdef __imp_InternetSetCookieW:PPROC
InternetSetCookieW equ <__imp_InternetSetCookieW>
  IFDEF __UNICODE__
    InternetSetCookie equ <__imp_InternetSetCookieW>
  ENDIF

externdef __imp_InternetSetDialState:PPROC
InternetSetDialState equ <__imp_InternetSetDialState>

externdef __imp_InternetSetDialStateA:PPROC
InternetSetDialStateA equ <__imp_InternetSetDialStateA>
  IFNDEF __UNICODE__
    InternetSetDialState equ <__imp_InternetSetDialStateA>
  ENDIF

externdef __imp_InternetSetDialStateW:PPROC
InternetSetDialStateW equ <__imp_InternetSetDialStateW>
  IFDEF __UNICODE__
    InternetSetDialState equ <__imp_InternetSetDialStateW>
  ENDIF

externdef __imp_InternetSetFilePointer:PPROC
InternetSetFilePointer equ <__imp_InternetSetFilePointer>

externdef __imp_InternetSetOptionA:PPROC
InternetSetOptionA equ <__imp_InternetSetOptionA>
  IFNDEF __UNICODE__
    InternetSetOption equ <__imp_InternetSetOptionA>
  ENDIF

externdef __imp_InternetSetOptionExA:PPROC
InternetSetOptionExA equ <__imp_InternetSetOptionExA>
  IFNDEF __UNICODE__
    InternetSetOptionEx equ <__imp_InternetSetOptionExA>
  ENDIF

externdef __imp_InternetSetOptionExW:PPROC
InternetSetOptionExW equ <__imp_InternetSetOptionExW>
  IFDEF __UNICODE__
    InternetSetOptionEx equ <__imp_InternetSetOptionExW>
  ENDIF

externdef __imp_InternetSetOptionW:PPROC
InternetSetOptionW equ <__imp_InternetSetOptionW>
  IFDEF __UNICODE__
    InternetSetOption equ <__imp_InternetSetOptionW>
  ENDIF

externdef __imp_InternetSetPerSiteCookieDecisionA:PPROC
InternetSetPerSiteCookieDecisionA equ <__imp_InternetSetPerSiteCookieDecisionA>
  IFNDEF __UNICODE__
    InternetSetPerSiteCookieDecision equ <__imp_InternetSetPerSiteCookieDecisionA>
  ENDIF

externdef __imp_InternetSetPerSiteCookieDecisionW:PPROC
InternetSetPerSiteCookieDecisionW equ <__imp_InternetSetPerSiteCookieDecisionW>
  IFDEF __UNICODE__
    InternetSetPerSiteCookieDecision equ <__imp_InternetSetPerSiteCookieDecisionW>
  ENDIF

externdef __imp_InternetSetStatusCallback:PPROC
InternetSetStatusCallback equ <__imp_InternetSetStatusCallback>

externdef __imp_InternetSetStatusCallbackA:PPROC
InternetSetStatusCallbackA equ <__imp_InternetSetStatusCallbackA>
  IFNDEF __UNICODE__
    InternetSetStatusCallback equ <__imp_InternetSetStatusCallbackA>
  ENDIF

externdef __imp_InternetSetStatusCallbackW:PPROC
InternetSetStatusCallbackW equ <__imp_InternetSetStatusCallbackW>
  IFDEF __UNICODE__
    InternetSetStatusCallback equ <__imp_InternetSetStatusCallbackW>
  ENDIF

externdef __imp_InternetShowSecurityInfoByURL:PPROC
InternetShowSecurityInfoByURL equ <__imp_InternetShowSecurityInfoByURL>

externdef __imp_InternetShowSecurityInfoByURLA:PPROC
InternetShowSecurityInfoByURLA equ <__imp_InternetShowSecurityInfoByURLA>
  IFNDEF __UNICODE__
    InternetShowSecurityInfoByURL equ <__imp_InternetShowSecurityInfoByURLA>
  ENDIF

externdef __imp_InternetShowSecurityInfoByURLW:PPROC
InternetShowSecurityInfoByURLW equ <__imp_InternetShowSecurityInfoByURLW>
  IFDEF __UNICODE__
    InternetShowSecurityInfoByURL equ <__imp_InternetShowSecurityInfoByURLW>
  ENDIF

externdef __imp_InternetTimeFromSystemTime:PPROC
InternetTimeFromSystemTime equ <__imp_InternetTimeFromSystemTime>

externdef __imp_InternetTimeFromSystemTimeA:PPROC
InternetTimeFromSystemTimeA equ <__imp_InternetTimeFromSystemTimeA>
  IFNDEF __UNICODE__
    InternetTimeFromSystemTime equ <__imp_InternetTimeFromSystemTimeA>
  ENDIF

externdef __imp_InternetTimeFromSystemTimeW:PPROC
InternetTimeFromSystemTimeW equ <__imp_InternetTimeFromSystemTimeW>
  IFDEF __UNICODE__
    InternetTimeFromSystemTime equ <__imp_InternetTimeFromSystemTimeW>
  ENDIF

externdef __imp_InternetTimeToSystemTime:PPROC
InternetTimeToSystemTime equ <__imp_InternetTimeToSystemTime>

externdef __imp_InternetTimeToSystemTimeA:PPROC
InternetTimeToSystemTimeA equ <__imp_InternetTimeToSystemTimeA>
  IFNDEF __UNICODE__
    InternetTimeToSystemTime equ <__imp_InternetTimeToSystemTimeA>
  ENDIF

externdef __imp_InternetTimeToSystemTimeW:PPROC
InternetTimeToSystemTimeW equ <__imp_InternetTimeToSystemTimeW>
  IFDEF __UNICODE__
    InternetTimeToSystemTime equ <__imp_InternetTimeToSystemTimeW>
  ENDIF

externdef __imp_InternetUnlockRequestFile:PPROC
InternetUnlockRequestFile equ <__imp_InternetUnlockRequestFile>

externdef __imp_InternetWriteFile:PPROC
InternetWriteFile equ <__imp_InternetWriteFile>

externdef __imp_InternetWriteFileExA:PPROC
InternetWriteFileExA equ <__imp_InternetWriteFileExA>
  IFNDEF __UNICODE__
    InternetWriteFileEx equ <__imp_InternetWriteFileExA>
  ENDIF

externdef __imp_InternetWriteFileExW:PPROC
InternetWriteFileExW equ <__imp_InternetWriteFileExW>
  IFDEF __UNICODE__
    InternetWriteFileEx equ <__imp_InternetWriteFileExW>
  ENDIF

externdef __imp_IsHostInProxyBypassList:PPROC
IsHostInProxyBypassList equ <__imp_IsHostInProxyBypassList>

externdef __imp_IsUrlCacheEntryExpiredA:PPROC
IsUrlCacheEntryExpiredA equ <__imp_IsUrlCacheEntryExpiredA>
  IFNDEF __UNICODE__
    IsUrlCacheEntryExpired equ <__imp_IsUrlCacheEntryExpiredA>
  ENDIF

externdef __imp_IsUrlCacheEntryExpiredW:PPROC
IsUrlCacheEntryExpiredW equ <__imp_IsUrlCacheEntryExpiredW>
  IFDEF __UNICODE__
    IsUrlCacheEntryExpired equ <__imp_IsUrlCacheEntryExpiredW>
  ENDIF

externdef __imp_LoadUrlCacheContent:PPROC
LoadUrlCacheContent equ <__imp_LoadUrlCacheContent>

externdef __imp_ParseX509EncodedCertificateForListBoxEntry:PPROC
ParseX509EncodedCertificateForListBoxEntry equ <__imp_ParseX509EncodedCertificateForListBoxEntry>

externdef __imp_PrivacyGetZonePreferenceW:PPROC
PrivacyGetZonePreferenceW equ <__imp_PrivacyGetZonePreferenceW>
  IFDEF __UNICODE__
    PrivacyGetZonePreference equ <__imp_PrivacyGetZonePreferenceW>
  ENDIF

externdef __imp_PrivacySetZonePreferenceW:PPROC
PrivacySetZonePreferenceW equ <__imp_PrivacySetZonePreferenceW>
  IFDEF __UNICODE__
    PrivacySetZonePreference equ <__imp_PrivacySetZonePreferenceW>
  ENDIF

externdef __imp_ReadUrlCacheEntryStream:PPROC
ReadUrlCacheEntryStream equ <__imp_ReadUrlCacheEntryStream>

externdef __imp_RegisterUrlCacheNotification:PPROC
RegisterUrlCacheNotification equ <__imp_RegisterUrlCacheNotification>

externdef __imp_ResumeSuspendedDownload:PPROC
ResumeSuspendedDownload equ <__imp_ResumeSuspendedDownload>

externdef __imp_RetrieveUrlCacheEntryFileA:PPROC
RetrieveUrlCacheEntryFileA equ <__imp_RetrieveUrlCacheEntryFileA>
  IFNDEF __UNICODE__
    RetrieveUrlCacheEntryFile equ <__imp_RetrieveUrlCacheEntryFileA>
  ENDIF

externdef __imp_RetrieveUrlCacheEntryFileW:PPROC
RetrieveUrlCacheEntryFileW equ <__imp_RetrieveUrlCacheEntryFileW>
  IFDEF __UNICODE__
    RetrieveUrlCacheEntryFile equ <__imp_RetrieveUrlCacheEntryFileW>
  ENDIF

externdef __imp_RetrieveUrlCacheEntryStreamA:PPROC
RetrieveUrlCacheEntryStreamA equ <__imp_RetrieveUrlCacheEntryStreamA>
  IFNDEF __UNICODE__
    RetrieveUrlCacheEntryStream equ <__imp_RetrieveUrlCacheEntryStreamA>
  ENDIF

externdef __imp_RetrieveUrlCacheEntryStreamW:PPROC
RetrieveUrlCacheEntryStreamW equ <__imp_RetrieveUrlCacheEntryStreamW>
  IFDEF __UNICODE__
    RetrieveUrlCacheEntryStream equ <__imp_RetrieveUrlCacheEntryStreamW>
  ENDIF

externdef __imp_RunOnceUrlCache:PPROC
RunOnceUrlCache equ <__imp_RunOnceUrlCache>

externdef __imp_SetUrlCacheConfigInfoA:PPROC
SetUrlCacheConfigInfoA equ <__imp_SetUrlCacheConfigInfoA>
  IFNDEF __UNICODE__
    SetUrlCacheConfigInfo equ <__imp_SetUrlCacheConfigInfoA>
  ENDIF

externdef __imp_SetUrlCacheConfigInfoW:PPROC
SetUrlCacheConfigInfoW equ <__imp_SetUrlCacheConfigInfoW>
  IFDEF __UNICODE__
    SetUrlCacheConfigInfo equ <__imp_SetUrlCacheConfigInfoW>
  ENDIF

externdef __imp_SetUrlCacheEntryGroup:PPROC
SetUrlCacheEntryGroup equ <__imp_SetUrlCacheEntryGroup>

externdef __imp_SetUrlCacheEntryGroupA:PPROC
SetUrlCacheEntryGroupA equ <__imp_SetUrlCacheEntryGroupA>
  IFNDEF __UNICODE__
    SetUrlCacheEntryGroup equ <__imp_SetUrlCacheEntryGroupA>
  ENDIF

externdef __imp_SetUrlCacheEntryGroupW:PPROC
SetUrlCacheEntryGroupW equ <__imp_SetUrlCacheEntryGroupW>
  IFDEF __UNICODE__
    SetUrlCacheEntryGroup equ <__imp_SetUrlCacheEntryGroupW>
  ENDIF

externdef __imp_SetUrlCacheEntryInfoA:PPROC
SetUrlCacheEntryInfoA equ <__imp_SetUrlCacheEntryInfoA>
  IFNDEF __UNICODE__
    SetUrlCacheEntryInfo equ <__imp_SetUrlCacheEntryInfoA>
  ENDIF

externdef __imp_SetUrlCacheEntryInfoW:PPROC
SetUrlCacheEntryInfoW equ <__imp_SetUrlCacheEntryInfoW>
  IFDEF __UNICODE__
    SetUrlCacheEntryInfo equ <__imp_SetUrlCacheEntryInfoW>
  ENDIF

externdef __imp_SetUrlCacheGroupAttributeA:PPROC
SetUrlCacheGroupAttributeA equ <__imp_SetUrlCacheGroupAttributeA>
  IFNDEF __UNICODE__
    SetUrlCacheGroupAttribute equ <__imp_SetUrlCacheGroupAttributeA>
  ENDIF

externdef __imp_SetUrlCacheGroupAttributeW:PPROC
SetUrlCacheGroupAttributeW equ <__imp_SetUrlCacheGroupAttributeW>
  IFDEF __UNICODE__
    SetUrlCacheGroupAttribute equ <__imp_SetUrlCacheGroupAttributeW>
  ENDIF

externdef __imp_SetUrlCacheHeaderData:PPROC
SetUrlCacheHeaderData equ <__imp_SetUrlCacheHeaderData>

externdef __imp_ShowCertificate:PPROC
ShowCertificate equ <__imp_ShowCertificate>

externdef __imp_ShowClientAuthCerts:PPROC
ShowClientAuthCerts equ <__imp_ShowClientAuthCerts>

externdef __imp_ShowSecurityInfo:PPROC
ShowSecurityInfo equ <__imp_ShowSecurityInfo>

externdef __imp_ShowX509EncodedCertificate:PPROC
ShowX509EncodedCertificate equ <__imp_ShowX509EncodedCertificate>

externdef __imp_UnlockUrlCacheEntryFile:PPROC
UnlockUrlCacheEntryFile equ <__imp_UnlockUrlCacheEntryFile>

externdef __imp_UnlockUrlCacheEntryFileA:PPROC
UnlockUrlCacheEntryFileA equ <__imp_UnlockUrlCacheEntryFileA>
  IFNDEF __UNICODE__
    UnlockUrlCacheEntryFile equ <__imp_UnlockUrlCacheEntryFileA>
  ENDIF

externdef __imp_UnlockUrlCacheEntryFileW:PPROC
UnlockUrlCacheEntryFileW equ <__imp_UnlockUrlCacheEntryFileW>
  IFDEF __UNICODE__
    UnlockUrlCacheEntryFile equ <__imp_UnlockUrlCacheEntryFileW>
  ENDIF

externdef __imp_UnlockUrlCacheEntryStream:PPROC
UnlockUrlCacheEntryStream equ <__imp_UnlockUrlCacheEntryStream>

externdef __imp_UpdateUrlCacheContentPath:PPROC
UpdateUrlCacheContentPath equ <__imp_UpdateUrlCacheContentPath>

externdef __imp_UrlZonesDetach:PPROC
UrlZonesDetach equ <__imp_UrlZonesDetach>

externdef __imp__GetFileExtensionFromUrl:PPROC
_GetFileExtensionFromUrl equ <__imp__GetFileExtensionFromUrl>

externdef __imp_wininet_ordinal101:PPROC
wininet_ordinal101 equ <__imp_wininet_ordinal101>

externdef __imp_wininet_ordinal102:PPROC
wininet_ordinal102 equ <__imp_wininet_ordinal102>

externdef __imp_wininet_ordinal103:PPROC
wininet_ordinal103 equ <__imp_wininet_ordinal103>

externdef __imp_wininet_ordinal104:PPROC
wininet_ordinal104 equ <__imp_wininet_ordinal104>

externdef __imp_wininet_ordinal105:PPROC
wininet_ordinal105 equ <__imp_wininet_ordinal105>

externdef __imp_wininet_ordinal108:PPROC
wininet_ordinal108 equ <__imp_wininet_ordinal108>

externdef __imp_wininet_ordinal109:PPROC
wininet_ordinal109 equ <__imp_wininet_ordinal109>

externdef __imp_wininet_ordinal110:PPROC
wininet_ordinal110 equ <__imp_wininet_ordinal110>

externdef __imp_wininet_ordinal111:PPROC
wininet_ordinal111 equ <__imp_wininet_ordinal111>

externdef __imp_wininet_ordinal112:PPROC
wininet_ordinal112 equ <__imp_wininet_ordinal112>

externdef __imp_wininet_ordinal116:PPROC
wininet_ordinal116 equ <__imp_wininet_ordinal116>

externdef __imp_wininet_ordinal117:PPROC
wininet_ordinal117 equ <__imp_wininet_ordinal117>

externdef __imp_wininet_ordinal118:PPROC
wininet_ordinal118 equ <__imp_wininet_ordinal118>

externdef __imp_wininet_ordinal120:PPROC
wininet_ordinal120 equ <__imp_wininet_ordinal120>

externdef __imp_wininet_ordinal121:PPROC
wininet_ordinal121 equ <__imp_wininet_ordinal121>

externdef __imp_wininet_ordinal122:PPROC
wininet_ordinal122 equ <__imp_wininet_ordinal122>

externdef __imp_wininet_ordinal123:PPROC
wininet_ordinal123 equ <__imp_wininet_ordinal123>
