externdef __imp_AddMMAuthMethods:PPROC
AddMMAuthMethods equ <__imp_AddMMAuthMethods>

externdef __imp_AddMMFilter:PPROC
AddMMFilter equ <__imp_AddMMFilter>

externdef __imp_AddMMPolicy:PPROC
AddMMPolicy equ <__imp_AddMMPolicy>

externdef __imp_AddQMPolicy:PPROC
AddQMPolicy equ <__imp_AddQMPolicy>

externdef __imp_AddSAs:PPROC
AddSAs equ <__imp_AddSAs>

externdef __imp_AddTransportFilter:PPROC
AddTransportFilter equ <__imp_AddTransportFilter>

externdef __imp_AddTunnelFilter:PPROC
AddTunnelFilter equ <__imp_AddTunnelFilter>

externdef __imp_CloseIKENegotiationHandle:PPROC
CloseIKENegotiationHandle equ <__imp_CloseIKENegotiationHandle>

externdef __imp_CloseIKENotifyHandle:PPROC
CloseIKENotifyHandle equ <__imp_CloseIKENotifyHandle>

externdef __imp_CloseIPSecPerformanceData:PPROC
CloseIPSecPerformanceData equ <__imp_CloseIPSecPerformanceData>

externdef __imp_CloseMMFilterHandle:PPROC
CloseMMFilterHandle equ <__imp_CloseMMFilterHandle>

externdef __imp_CloseTransportFilterHandle:PPROC
CloseTransportFilterHandle equ <__imp_CloseTransportFilterHandle>

externdef __imp_CloseTunnelFilterHandle:PPROC
CloseTunnelFilterHandle equ <__imp_CloseTunnelFilterHandle>

externdef __imp_CollectIPSecPerformanceData:PPROC
CollectIPSecPerformanceData equ <__imp_CollectIPSecPerformanceData>

externdef __imp_DeleteMMAuthMethods:PPROC
DeleteMMAuthMethods equ <__imp_DeleteMMAuthMethods>

externdef __imp_DeleteMMFilter:PPROC
DeleteMMFilter equ <__imp_DeleteMMFilter>

externdef __imp_DeleteMMPolicy:PPROC
DeleteMMPolicy equ <__imp_DeleteMMPolicy>

externdef __imp_DeleteMMSAs:PPROC
DeleteMMSAs equ <__imp_DeleteMMSAs>

externdef __imp_DeleteQMPolicy:PPROC
DeleteQMPolicy equ <__imp_DeleteQMPolicy>

externdef __imp_DeleteQMSAs:PPROC
DeleteQMSAs equ <__imp_DeleteQMSAs>

externdef __imp_DeleteTransportFilter:PPROC
DeleteTransportFilter equ <__imp_DeleteTransportFilter>

externdef __imp_DeleteTunnelFilter:PPROC
DeleteTunnelFilter equ <__imp_DeleteTunnelFilter>

externdef __imp_EnumIPSecInterfaces:PPROC
EnumIPSecInterfaces equ <__imp_EnumIPSecInterfaces>

externdef __imp_EnumMMAuthMethods:PPROC
EnumMMAuthMethods equ <__imp_EnumMMAuthMethods>

externdef __imp_EnumMMFilters:PPROC
EnumMMFilters equ <__imp_EnumMMFilters>

externdef __imp_EnumMMPolicies:PPROC
EnumMMPolicies equ <__imp_EnumMMPolicies>

externdef __imp_EnumMMSAs:PPROC
EnumMMSAs equ <__imp_EnumMMSAs>

externdef __imp_EnumQMPolicies:PPROC
EnumQMPolicies equ <__imp_EnumQMPolicies>

externdef __imp_EnumQMSAs:PPROC
EnumQMSAs equ <__imp_EnumQMSAs>

externdef __imp_EnumTransportFilters:PPROC
EnumTransportFilters equ <__imp_EnumTransportFilters>

externdef __imp_EnumTunnelFilters:PPROC
EnumTunnelFilters equ <__imp_EnumTunnelFilters>

externdef __imp_GetConfigurationVariables:PPROC
GetConfigurationVariables equ <__imp_GetConfigurationVariables>

externdef __imp_GetMMAuthMethods:PPROC
GetMMAuthMethods equ <__imp_GetMMAuthMethods>

externdef __imp_GetMMFilter:PPROC
GetMMFilter equ <__imp_GetMMFilter>

externdef __imp_GetMMPolicy:PPROC
GetMMPolicy equ <__imp_GetMMPolicy>

externdef __imp_GetMMPolicyByID:PPROC
GetMMPolicyByID equ <__imp_GetMMPolicyByID>

externdef __imp_GetQMPolicy:PPROC
GetQMPolicy equ <__imp_GetQMPolicy>

externdef __imp_GetQMPolicyByID:PPROC
GetQMPolicyByID equ <__imp_GetQMPolicyByID>

externdef __imp_GetTransportFilter:PPROC
GetTransportFilter equ <__imp_GetTransportFilter>

externdef __imp_GetTunnelFilter:PPROC
GetTunnelFilter equ <__imp_GetTunnelFilter>

externdef __imp_InitiateIKENegotiation:PPROC
InitiateIKENegotiation equ <__imp_InitiateIKENegotiation>

externdef __imp_MatchMMFilter:PPROC
MatchMMFilter equ <__imp_MatchMMFilter>

externdef __imp_MatchTransportFilter:PPROC
MatchTransportFilter equ <__imp_MatchTransportFilter>

externdef __imp_MatchTunnelFilter:PPROC
MatchTunnelFilter equ <__imp_MatchTunnelFilter>

externdef __imp_OpenIPSecPerformanceData:PPROC
OpenIPSecPerformanceData equ <__imp_OpenIPSecPerformanceData>

externdef __imp_OpenMMFilterHandle:PPROC
OpenMMFilterHandle equ <__imp_OpenMMFilterHandle>

externdef __imp_OpenTransportFilterHandle:PPROC
OpenTransportFilterHandle equ <__imp_OpenTransportFilterHandle>

externdef __imp_OpenTunnelFilterHandle:PPROC
OpenTunnelFilterHandle equ <__imp_OpenTunnelFilterHandle>

externdef __imp_QueryIKENegotiationStatus:PPROC
QueryIKENegotiationStatus equ <__imp_QueryIKENegotiationStatus>

externdef __imp_QueryIKENotifyData:PPROC
QueryIKENotifyData equ <__imp_QueryIKENotifyData>

externdef __imp_QueryIKEStatistics:PPROC
QueryIKEStatistics equ <__imp_QueryIKEStatistics>

externdef __imp_QueryIPSecStatistics:PPROC
QueryIPSecStatistics equ <__imp_QueryIPSecStatistics>

externdef __imp_QuerySpdPolicyState:PPROC
QuerySpdPolicyState equ <__imp_QuerySpdPolicyState>

externdef __imp_RegisterIKENotifyClient:PPROC
RegisterIKENotifyClient equ <__imp_RegisterIKENotifyClient>

externdef __imp_SPDApiBufferAllocate:PPROC
SPDApiBufferAllocate equ <__imp_SPDApiBufferAllocate>

externdef __imp_SPDApiBufferFree:PPROC
SPDApiBufferFree equ <__imp_SPDApiBufferFree>

externdef __imp_SetConfigurationVariables:PPROC
SetConfigurationVariables equ <__imp_SetConfigurationVariables>

externdef __imp_SetMMAuthMethods:PPROC
SetMMAuthMethods equ <__imp_SetMMAuthMethods>

externdef __imp_SetMMFilter:PPROC
SetMMFilter equ <__imp_SetMMFilter>

externdef __imp_SetMMPolicy:PPROC
SetMMPolicy equ <__imp_SetMMPolicy>

externdef __imp_SetQMPolicy:PPROC
SetQMPolicy equ <__imp_SetQMPolicy>

externdef __imp_SetSddlConfig:PPROC
SetSddlConfig equ <__imp_SetSddlConfig>

externdef __imp_SetTransportFilter:PPROC
SetTransportFilter equ <__imp_SetTransportFilter>

externdef __imp_SetTunnelFilter:PPROC
SetTunnelFilter equ <__imp_SetTunnelFilter>
