externdef __imp_BB_Refresh:PPROC
BB_Refresh equ <__imp_BB_Refresh>

externdef __imp_GetBBHwnd:PPROC
GetBBHwnd equ <__imp_GetBBHwnd>

externdef __imp_GetBBMainHwnd:PPROC
GetBBMainHwnd equ <__imp_GetBBMainHwnd>

externdef __imp_GetPanelCount:PPROC
GetPanelCount equ <__imp_GetPanelCount>

externdef __imp_InitBillBoard:PPROC
InitBillBoard equ <__imp_InitBillBoard>

externdef __imp_ProgressGaugeMsg:PPROC
ProgressGaugeMsg equ <__imp_ProgressGaugeMsg>

externdef __imp_SetInfoText:PPROC
SetInfoText equ <__imp_SetInfoText>

externdef __imp_SetProgress:PPROC
SetProgress equ <__imp_SetProgress>

externdef __imp_SetProgressText:PPROC
SetProgressText equ <__imp_SetProgressText>

externdef __imp_SetStep:PPROC
SetStep equ <__imp_SetStep>

externdef __imp_SetTimeEstimate:PPROC
SetTimeEstimate equ <__imp_SetTimeEstimate>

externdef __imp_ShowProgressGaugeWindow:PPROC
ShowProgressGaugeWindow equ <__imp_ShowProgressGaugeWindow>

externdef __imp_StartBillBoard:PPROC
StartBillBoard equ <__imp_StartBillBoard>

externdef __imp_StopBillBoard:PPROC
StopBillBoard equ <__imp_StopBillBoard>

externdef __imp_TermBillBoard:PPROC
TermBillBoard equ <__imp_TermBillBoard>
