externdef __imp_NSPStartup:PPROC
NSPStartup equ <__imp_NSPStartup>

externdef __imp_WSHAddressToString:PPROC
WSHAddressToString equ <__imp_WSHAddressToString>

externdef __imp_WSHEnumProtocols:PPROC
WSHEnumProtocols equ <__imp_WSHEnumProtocols>

externdef __imp_WSHGetBroadcastSockaddr:PPROC
WSHGetBroadcastSockaddr equ <__imp_WSHGetBroadcastSockaddr>

externdef __imp_WSHGetProviderGuid:PPROC
WSHGetProviderGuid equ <__imp_WSHGetProviderGuid>

externdef __imp_WSHGetSockaddrType:PPROC
WSHGetSockaddrType equ <__imp_WSHGetSockaddrType>

externdef __imp_WSHGetSocketInformation:PPROC
WSHGetSocketInformation equ <__imp_WSHGetSocketInformation>

externdef __imp_WSHGetWSAProtocolInfo:PPROC
WSHGetWSAProtocolInfo equ <__imp_WSHGetWSAProtocolInfo>

externdef __imp_WSHGetWildcardSockaddr:PPROC
WSHGetWildcardSockaddr equ <__imp_WSHGetWildcardSockaddr>

externdef __imp_WSHGetWinsockMapping:PPROC
WSHGetWinsockMapping equ <__imp_WSHGetWinsockMapping>

externdef __imp_WSHIoctl:PPROC
WSHIoctl equ <__imp_WSHIoctl>

externdef __imp_WSHJoinLeaf:PPROC
WSHJoinLeaf equ <__imp_WSHJoinLeaf>

externdef __imp_WSHNotify:PPROC
WSHNotify equ <__imp_WSHNotify>

externdef __imp_WSHOpenSocket2:PPROC
WSHOpenSocket2 equ <__imp_WSHOpenSocket2>

externdef __imp_WSHOpenSocket:PPROC
WSHOpenSocket equ <__imp_WSHOpenSocket>

externdef __imp_WSHSetSocketInformation:PPROC
WSHSetSocketInformation equ <__imp_WSHSetSocketInformation>

externdef __imp_WSHStringToAddress:PPROC
WSHStringToAddress equ <__imp_WSHStringToAddress>
