externdef __imp_DllInstall:PPROC
DllInstall equ <__imp_DllInstall>

externdef __imp_DllMain:PPROC
DllMain equ <__imp_DllMain>

externdef __imp_DllRegisterServer:PPROC
DllRegisterServer equ <__imp_DllRegisterServer>

externdef __imp_DllUnregisterServer:PPROC
DllUnregisterServer equ <__imp_DllUnregisterServer>

externdef __imp_GeneralizeForImaging:PPROC
GeneralizeForImaging equ <__imp_GeneralizeForImaging>

externdef __imp_GetAUOptionsEx:PPROC
GetAUOptionsEx equ <__imp_GetAUOptionsEx>

externdef __imp_GetEngineStatusInfo:PPROC
GetEngineStatusInfo equ <__imp_GetEngineStatusInfo>

externdef __imp_RegisterServiceVersion:PPROC
RegisterServiceVersion equ <__imp_RegisterServiceVersion>

externdef __imp_ServiceHandler:PPROC
ServiceHandler equ <__imp_ServiceHandler>

externdef __imp_ServiceMain:PPROC
ServiceMain equ <__imp_ServiceMain>

externdef __imp_WUAutoUpdateAtShutdown:PPROC
WUAutoUpdateAtShutdown equ <__imp_WUAutoUpdateAtShutdown>

externdef __imp_WUCheckForUpdatesAtShutdown:PPROC
WUCheckForUpdatesAtShutdown equ <__imp_WUCheckForUpdatesAtShutdown>

externdef __imp_WUServiceMain:PPROC
WUServiceMain equ <__imp_WUServiceMain>

externdef __imp_wuaueng_ordinal2:PPROC
wuaueng_ordinal2 equ <__imp_wuaueng_ordinal2>

externdef __imp_wuaueng_ordinal3:PPROC
wuaueng_ordinal3 equ <__imp_wuaueng_ordinal3>
