externdef __imp_adler32:PPROC
adler32 equ <__imp_adler32>

externdef __imp_adler32_combine64:PPROC
adler32_combine64 equ <__imp_adler32_combine64>

externdef __imp_adler32_combine:PPROC
adler32_combine equ <__imp_adler32_combine>

externdef __imp_compress2:PPROC
compress2 equ <__imp_compress2>

externdef __imp_compress:PPROC
compress equ <__imp_compress>

externdef __imp_compressBound:PPROC
compressBound equ <__imp_compressBound>

externdef __imp_crc32:PPROC
crc32 equ <__imp_crc32>

externdef __imp_crc32_combine64:PPROC
crc32_combine64 equ <__imp_crc32_combine64>

externdef __imp_crc32_combine:PPROC
crc32_combine equ <__imp_crc32_combine>

externdef __imp_deflate:PPROC
deflate equ <__imp_deflate>

externdef __imp_deflateBound:PPROC
deflateBound equ <__imp_deflateBound>

externdef __imp_deflateCopy:PPROC
deflateCopy equ <__imp_deflateCopy>

externdef __imp_deflateEnd:PPROC
deflateEnd equ <__imp_deflateEnd>

externdef __imp_deflateInit2_:PPROC
deflateInit2_ equ <__imp_deflateInit2_>

externdef __imp_deflateInit_:PPROC
deflateInit_ equ <__imp_deflateInit_>

externdef __imp_deflateParams:PPROC
deflateParams equ <__imp_deflateParams>

externdef __imp_deflatePending:PPROC
deflatePending equ <__imp_deflatePending>

externdef __imp_deflatePrime:PPROC
deflatePrime equ <__imp_deflatePrime>

externdef __imp_deflateReset:PPROC
deflateReset equ <__imp_deflateReset>

externdef __imp_deflateResetKeep:PPROC
deflateResetKeep equ <__imp_deflateResetKeep>

externdef __imp_deflateSetDictionary:PPROC
deflateSetDictionary equ <__imp_deflateSetDictionary>

externdef __imp_deflateSetHeader:PPROC
deflateSetHeader equ <__imp_deflateSetHeader>

externdef __imp_deflateTune:PPROC
deflateTune equ <__imp_deflateTune>

externdef __imp_get_crc_table:PPROC
get_crc_table equ <__imp_get_crc_table>

externdef __imp_gzbuffer:PPROC
gzbuffer equ <__imp_gzbuffer>

externdef __imp_gzclearerr:PPROC
gzclearerr equ <__imp_gzclearerr>

externdef __imp_gzclose:PPROC
gzclose equ <__imp_gzclose>

externdef __imp_gzclose_r:PPROC
gzclose_r equ <__imp_gzclose_r>

externdef __imp_gzclose_w:PPROC
gzclose_w equ <__imp_gzclose_w>

externdef __imp_gzdirect:PPROC
gzdirect equ <__imp_gzdirect>

externdef __imp_gzdopen:PPROC
gzdopen equ <__imp_gzdopen>

externdef __imp_gzeof:PPROC
gzeof equ <__imp_gzeof>

externdef __imp_gzerror:PPROC
gzerror equ <__imp_gzerror>

externdef __imp_gzflush:PPROC
gzflush equ <__imp_gzflush>

externdef __imp_gzgetc:PPROC
gzgetc equ <__imp_gzgetc>

externdef __imp_gzgetc_:PPROC
gzgetc_ equ <__imp_gzgetc_>

externdef __imp_gzgets:PPROC
gzgets equ <__imp_gzgets>

externdef __imp_gzoffset64:PPROC
gzoffset64 equ <__imp_gzoffset64>

externdef __imp_gzoffset:PPROC
gzoffset equ <__imp_gzoffset>

externdef __imp_gzopen64:PPROC
gzopen64 equ <__imp_gzopen64>

externdef __imp_gzopen:PPROC
gzopen equ <__imp_gzopen>

externdef __imp_gzopen_w:PPROC
gzopen_w equ <__imp_gzopen_w>

externdef __imp_gzprintf:PPROC
gzprintf equ <__imp_gzprintf>

externdef __imp_gzputc:PPROC
gzputc equ <__imp_gzputc>

externdef __imp_gzputs:PPROC
gzputs equ <__imp_gzputs>

externdef __imp_gzread:PPROC
gzread equ <__imp_gzread>

externdef __imp_gzrewind:PPROC
gzrewind equ <__imp_gzrewind>

externdef __imp_gzseek64:PPROC
gzseek64 equ <__imp_gzseek64>

externdef __imp_gzseek:PPROC
gzseek equ <__imp_gzseek>

externdef __imp_gzsetparams:PPROC
gzsetparams equ <__imp_gzsetparams>

externdef __imp_gztell64:PPROC
gztell64 equ <__imp_gztell64>

externdef __imp_gztell:PPROC
gztell equ <__imp_gztell>

externdef __imp_gzungetc:PPROC
gzungetc equ <__imp_gzungetc>

externdef __imp_gzwrite:PPROC
gzwrite equ <__imp_gzwrite>

externdef __imp_inflate:PPROC
inflate equ <__imp_inflate>

externdef __imp_inflateBack:PPROC
inflateBack equ <__imp_inflateBack>

externdef __imp_inflateBackEnd:PPROC
inflateBackEnd equ <__imp_inflateBackEnd>

externdef __imp_inflateBackInit_:PPROC
inflateBackInit_ equ <__imp_inflateBackInit_>

externdef __imp_inflateCopy:PPROC
inflateCopy equ <__imp_inflateCopy>

externdef __imp_inflateEnd:PPROC
inflateEnd equ <__imp_inflateEnd>

externdef __imp_inflateGetHeader:PPROC
inflateGetHeader equ <__imp_inflateGetHeader>

externdef __imp_inflateInit2_:PPROC
inflateInit2_ equ <__imp_inflateInit2_>

externdef __imp_inflateInit_:PPROC
inflateInit_ equ <__imp_inflateInit_>

externdef __imp_inflateMark:PPROC
inflateMark equ <__imp_inflateMark>

externdef __imp_inflatePrime:PPROC
inflatePrime equ <__imp_inflatePrime>

externdef __imp_inflateReset2:PPROC
inflateReset2 equ <__imp_inflateReset2>

externdef __imp_inflateReset:PPROC
inflateReset equ <__imp_inflateReset>

externdef __imp_inflateResetKeep:PPROC
inflateResetKeep equ <__imp_inflateResetKeep>

externdef __imp_inflateSetDictionary:PPROC
inflateSetDictionary equ <__imp_inflateSetDictionary>

externdef __imp_inflateSync:PPROC
inflateSync equ <__imp_inflateSync>

externdef __imp_inflateSyncPoint:PPROC
inflateSyncPoint equ <__imp_inflateSyncPoint>

externdef __imp_inflateUndermine:PPROC
inflateUndermine equ <__imp_inflateUndermine>

externdef __imp_uncompress:PPROC
uncompress equ <__imp_uncompress>

externdef __imp_zError:PPROC
zError equ <__imp_zError>

externdef __imp_zlibCompileFlags:PPROC
zlibCompileFlags equ <__imp_zlibCompileFlags>

externdef __imp_zlibVersion:PPROC
zlibVersion equ <__imp_zlibVersion>
